### ISSUE TITLE
rename could not use path-based uri

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#10]
when rename an item, I got error when use the path-base URI.

Now I use item_id instead, is this a bug ?

Thanks!

**Comment by jscaria** [comment]
@mikechiu1012 - can you describe the error further?   Can you send me your request & the response the service gave you?

**Comment by mikechiu1012** [comment]
here is the test information:
I'll rename file 5M to 5M.rename under root dir.
url: https://api.onedrive.com/v1.0/drive/root: 
headers: {'Content-Type': 'application/json'}, 
data: {
  "name": "5M.rename"
}

The response is:
<Response [400]> {u'error': {u'innererror': {u'code': u'badArgument'}, u'message': u'Bad Argument', u'code': u'invalidArgument'}}
{u'error': {u'innererror': {u'code': u'badArgument'}, u'message': u'Bad Argument', u'code': u'invalidArgument'}}

the result is the same even if I change the uri from url: https://api.onedrive.com/v1.0/drive/root:  to url: https://api.onedrive.com/v1.0/drive/root:/ 
but if I use item-id, the command is worked.
the response information is I test just now
I hope this information is useful, thanks!

**Comment by peternied** [comment]
@mikechiu1012 Looks like when are building up the path based syntax you are missing the item location, I would expect your URL to look like http://api.onedrive.com/v1.0/drive/root:/path/to/5M: If you make this change does the scenario work?

**Comment by mikechiu1012** [comment]
Use the item path could solve this problem, thanks.

by the way, the description listed on http://onedrive.github.io/items/update.htm is 

PATCH /drive/items/{item-id}
PATCH /drive/root:/{folder-path}

I suggest this description had better changed to {item-path} like other page to make fewer confusion.

Thanks!

**Comment by peternied** [comment]
Good catch, I'll fix that up.  Thanks!
