### ISSUE TITLE
some clarification over view.changes

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#100]
some clarification over use of view.changes

according to documentation whenever the first request will be for root folder without the @changes.token, all the tree hierarchy i.e children of children will be responded back. 

what if some folders say has many children, and the user has never used that folders, but in the first call everything will be available at the app (no use full)

can have more clarity how to work with view.changes really interested to use this

thank u

**Comment by The-Lion** [comment]
I don't want to hijack this thread, but is it indeed possible to get the latest change token for a folder without needing to walk through the current state of the hierarchy. For example, for the first [view.changes](https://dev.onedrive.com/items/view_changes.htm) call I do, I don't have a token yet. So I need almost 20 follow-up calls to finally receive the latest token, while the data received is simply not used. I limit the response size by selecting only the ID field, but I still need to do 20 additional calls.

So, is there a way to receive the latest change token just with one API call (as is possible with other cloud API's: https://api.dropbox.com/1/delta/latest_cursor, https://www.googleapis.com/drive/v2/changes?maxResults=1)?

**Comment by The-Lion** [comment]
Any updates on this? I just want to receive the latest change token for a OneDrive folder without walking through the whole hierarchy of >100GB of files if I don't have a token for the first call.

Google Drive for example just provides a 'largestChangeId'  (similar to the latest token) for each change call. Dropbox has a specific end point to obtain the latest token.

**Comment by rgregg** [comment]
We don't have a way to do that today. I've added it to our backlog though so we'll track the request. Right now the only option you have is paging through 1000 items at a time with a small set of properties (ID only). I know that's very inefficient and so we'll look at getting this added.

**Comment by daspek** [comment]
@The-Lion check out the new [view.delta](https://dev.onedrive.com/items/view_delta.htm) api, which replaces view.changes. you can now get the latest delta token by calling view.delta?token=latest.
