### ISSUE TITLE
Remoteitem is null on DriveItem when querying for children in sharedWithMe

### ISSUE THREAD

**Issue by Terkildsen** [OneDrive/onedrive-api-docs#1000]
#### Category
- [X ] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

The RemoteItem-facet should be present when querying for children DriveItems in a SharedWithMe-request.

#### Observed Behavior

I'm getting a list of DriveItems that are shared with me. I use the method /SharedWithMe to get these DriveItems. These DriveItems include folders. I would like the user to be able to view the files in these folders. In order to do that I use the remote drive id and the remote item id as keys in a new list. Here I use the following query in order to get these files and folders:
https://graph.microsoft.com/v1.0/me/drive/" + remoteItemDriveId + "/items/" + remoteItemId + "/children"

This query provides me the expected list of folders and files. However, the RemoteItem-facet is null meaning that I'm not able to get the subfolders.

I'm probably reading the documentation wrong, so please forgive me. I hope that you can point me in the right direction. Thanks in advance.

**Comment by chackman** [comment]
Thanks for your feedback.

Could you please clarify which API call where you were expecting to get a RemoteItem facet?

If it is this one
  https://graph.microsoft.com/v1.0/me/drive/" + remoteItemDriveId + "/items/" + remoteItemId + "/children"

You should instead use the /drives/ endpoint [as follows](https://docs.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0)
  https://graph.microsoft.com/v1.0/drives/" + remoteItemDriveId + "/items/" + remoteItemId + "/children"

And then to get the children of a folder returned by that call, use the ID of the folder:
  https://graph.microsoft.com/v1.0/drives/" + remoteItemDriveId + "/items/" + folderItemId + "/children"

Example (with parts truncated for brevity):

GET https://graph.microsoft.com/v1.0/me/drive/sharedWithMe

    "value": [
        {
            "name": "SharedFolder",
            "remoteItem": {
                "id": "**987def!123**",
                "parentReference": {
                    "driveId": "**987def**",
                }
            }
        }
    ]

GET https://graph.microsoft.com/v1.0/drives/**987def**/items/**987def!123**/children

    "value": [
        {
            "id": "**987def!456**",
            "name": "Subfolder",
            "parentReference": {
                "driveId": "**987def**",
                "id": "**987def!123**"
                "name": "SharedFolder"
            }
        }
    ]

GET https://graph.microsoft.com/v1.0/drives/**987def**/items/**987def!456**/children
will return metadata of the items in the "Subfolder" folder.

Let us know if that helps.

**Comment by Terkildsen** [comment]
aaahhh!!! Now I get it! :-) 

I was expecting that I should use the remoteItem-facet everytime in order to get files shared with me. This is also true for the parent-folder. But not when I want to request subfolders. Instead, I should use the folder-id and the parentReference.

Thank you so much for clearing this out for me. You have helped me pass a great obstacle.
