### ISSUE TITLE
Failed to validate redirect uri during authentication

### ISSUE THREAD

**Issue by vslsquared** [OneDrive/onedrive-api-docs#1002]
I am trying to authenticate user with redirect uri on non standard port, using following URl

https://my.domain.com:1150/api/onedrive/auth

and i am getting response like redirect_uri is not valid

but on other side when i try to authenticate user without the port "1150", it gets create successfully.

Please help!

**Comment by chackman** [comment]
Thanks for your feedback.  What feature are you using the authenticate the user?  For example, ADAL, file picker, etc.

**Comment by vslsquared** [comment]
We are following these [steps ](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth?view=odsp-graph-online#step-1-log-in-and-get-an-authorization-code) to authenticate user.

**Comment by chackman** [comment]
Thanks for your feedback.  Since this question is about Azure Active Directory, please ask it here: https://stackoverflow.com/questions/tagged/azure-active-directory
