### ISSUE TITLE
SharePoint Online doesn't support filtering on 'url' and 'name' fields.

### ISSUE THREAD

**Issue by Kerfier** [OneDrive/onedrive-api-docs#1004]
Hi, I faced the inconsistency in the SharePoint Online filtering documentation.
In documentation mentioned that in OneDrive for Business, SharePoint Online and SharePoint Server 2016, filtering support only name and url properties.

API responds on the "https://graph.microsoft.com/v1.0/sites/{siteId}/drive/root/search(q='')?filter=name%20eq%20'some_name'" request  with the message: "Only createdDateTime is supported for filtering".

The request like this "https://graph.microsoft.com/v1.0/sites/{siteId}/drive/root/search(q='')?filter=createdDateTime%20gt%20'2019-02-10T09:07:57'" works well.
But request with the 'and' operator ("https://graph.microsoft.com/v1.0/sites/{siteId}/drive/root/search(q='')?filter=createdDateTime%20gt%20'2019-02-10T09:07:57'%20and%20createdDateTime%20lt%20'2019-02-14T09:07:57") fails with the message: "Only createdDateTime is supported for filtering".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b69523-6e05-fc2e-57c9-4ee861c8e0b2
* Version Independent ID: 05845d47-c93a-7b9b-cb65-e18826cc5116
* Content: [How to filter items - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/filtering-results.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/filtering-results.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback; please provide the following response headers:
> * Date (in UTC, please)
> * request-id
> * SPRequestGuid (for requests made to OneDrive for Business)
