### ISSUE TITLE
MSOneDrive : Unable to retrieve all files of a specific folder

### ISSUE THREAD

**Issue by crk2904** [OneDrive/onedrive-api-docs#1005]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
According to [documentation ](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online) the user should be able to retrieve only files of the specific parent folder.

#### Observed Behavior
When we are using a filter as file ne null or folder eq null, we are getting the following error:
Error Code: 501
{
    "error": {
        "code": "notSupported",
        "message": "The request is not supported by the system.",
        "innerError": {
            "request-id": "f28365f7-2721-482e-8c52-7e4bc87469a8",
            "date": "2019-02-19T13:03:11"
        }
    }
}
#### Steps to Reproduce
We are hitting url in the following format : /{ParentFolderPath}/children?$filter= folder eq null or
/{ParentFolderPath}/children?$filter= file ne null 

Kindly help to achieve 'retrieve' only files.
Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.

Unfortunately, in OneDrive for Business / SharePoint Online, [filtering does not currently support the file or folder properties](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online#filterable-properties).
