### ISSUE TITLE
Upload sessions don't support zero length file (reopening issue 53)

### ISSUE THREAD

**Issue by coderazzi** [OneDrive/onedrive-api-docs#1006]
Debugging an error : "JSONValue is not an object"
I found that it related to a file with size 0. Your code is treating it specially, as mentioned in issue #53 .
My guess is that OneDrive is now strictly enforcing its rule: "Files that are 0 bytes in size can't be uploaded from the OneDrive website."
The HTTP response (removing client-request-id) is:

> < HTTP/1.1 400 Bad Request
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json
< request-id: 9c95a521-7c7c-4222-9c4c-97fcd6f1cf5b
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"2","ScaleUnit":"000","RoleInstance":"AGSFE_IN_29","ADSiteName":"NEU"}}
< Duration: 127.0394
< Strict-Transport-Security: max-age=31536000
< Date: Thu, 21 Feb 2019 14:13:58 GMT
< 
OneDrive HTTP Server Response: 400
* Connection #1 to host graph.microsoft.com left intact
Giving up on sync after three attempts: JSONValue is not an object

**Comment by chackman** [comment]
Thanks for your feedback.  However, the request-id given corresponds to a GET operation.  Could you please confirm whether this request was for the drive that you are having issues with?

**Comment by coderazzi** [comment]
Hi, the log I sent was indeed for the drive / file I have issues with. I
was using onedrive --monitor --verbose and that was the failing request,
corresponding, indeed, to a zero-size file.

**Comment by abraunegg** [comment]
@coderazzi 
FYI you are also using the outdated 'skilion' client, and not the correct Linux client for OneDrive, which can be found here - https://github.com/abraunegg

The handling of zero size files is correctly managed in my fork.

**Comment by coderazzi** [comment]
Sorry, I am using indeed your fork:

onedrive$ git remote show origin
* remote origin
  Fetch URL: https://github.com/abraunegg/onedrive.git
  Push  URL: https://github.com/abraunegg/onedrive.git
  HEAD branch: master

The handling of zero size files is managed in your fork, but it seems that
the Onedrive behaviour has changed, as your code is not correct anymore.

**Comment by abraunegg** [comment]
@coderazzi 
Can you please validate that this is actually correct on your system:
```
[alex@centos7full OneDrivePersonal]$ touch zero-file-size
[alex@centos7full OneDrivePersonal]$ ls -la
total 4
drwxrwxr-x.  2 alex alex   28 Mar 30 06:04 .
drwx------. 29 alex alex 4096 Mar 29 11:45 ..
-rw-rw-r--.  1 alex alex    0 Mar 30 06:04 zero-file-size
[alex@centos7full OneDrivePersonal]$ 
```
upload file:
```
./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 4498492245
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Uploading new file ./zero-file-size ... done.
Remaining free space: 4498492245
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

zero size files are handled correctly and this is one of the checks performed each and every build

**Comment by abraunegg** [comment]
@coderazzi 
even in `--monitor` there is no issue:
```
 ./onedrive --confdir '~/.config/onedrive-personal' --monitor --verbose    
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 4498492245
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
[M] File changed: ./2nd-zero-file-size
Uploading differences of ./2nd-zero-file-size
Uploading new items of ./2nd-zero-file-size
Uploading new file ./2nd-zero-file-size ... done.
Remaining free space: 4498492245
```

**Comment by coderazzi** [comment]
Hi, confirmed your answer - I updated the repository, recompiled, and
checked the behavior with the zero size file, and it uploaded it without
problems - and the file is present indeed in OneDrive.

My apologies for wasting your time, I really don't know where is my error,
as I had already updated my git sources and recompiled, and the error was
still happening. My bad.

**Comment by abraunegg** [comment]
@coderazzi
Most likely you were still running the 'skilion' code somehow - which has significant defects like the one you raised - the only plausible answer as zero file size upload has been fixed for well over ~12 months

**Comment by coderazzi** [comment]
Right... But I had to modify your code. src/sync.d, method private
void uploadNewFile(string path)

And the comment was clear:
                    // Can we read the file - as a permissions issue
or file corruption will cause a failure
                        // https://github.com/abraunegg/onedrive/issues/113
                        if (readLocalFile(path)){
 ....

So no, I was using your fork. But it beats me why it would fail last
time and not now. My zero file size was on a linked folder, but I have
tried that now and it works still fine.

In any case, the error is obviously on my side, I will try to find the
reason, just for the sake of it...

**Comment by abraunegg** [comment]
@coderazzi
Unclear as to why you would be modifying the code. If you have an issue / problem - please open an issue ticket

**Comment by chackman** [comment]
This issue appears to be with a client application and is not part of the OneDrive API docs area.
