### ISSUE TITLE
File count not correct in the GET /drive api

### ISSUE THREAD

**Issue by asivanadi** [OneDrive/onedrive-api-docs#1007]
We are using "GET /drive"  api specified in this document.
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_get?view=odsp-graph-online
 
From the documentation we see that the drive resource details are returned as specified by
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/drive?view=odsp-graph-online
 
We see the quota block returned as a response.
 
"quota": {
                "deleted": 187917,
                "fileCount": 192,
                "remaining": 1099509515764,
                "state": "normal",
                "total": 1099511627776,
                "used": 82688
            }
 
The fileCount is not specified in this document 
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/drive?view=odsp-graph-online.
 
The file count that we see in this response does not match with that of the total number of files in onedrive.
In case if this is not the total file count, what is this file count number representing.

**Comment by asivanadi** [comment]
<img width="1235" alt="screen shot 2019-02-22 at 11 35 34 am" src="https://user-images.githubusercontent.com/6239301/53275562-5fbee200-36b0-11e9-8509-a20adcc3efac.png">

**Comment by apertureqa** [comment]
Same case with "reportRoot: getOneDriveUsageAccountDetail" endpoint.

As per this document the response has 

The CSV file has the following headers for columns.

Report Refresh Date
Site URL
Owner Display Name
Is Deleted
Last Activity Date
File Count
Active File Count
Storage Used (Byte)
Storage Allocated (Byte)
Report Period


Here the file count gives us the total file count for the user as per this document

https://docs.microsoft.com/en-us/office365/admin/activity-reports/onedrive-for-business-usage?redirectSourcePath=%252fclient%252fOneDrive-for-Business-usage-0de3b312-c4e8-4e4b-a02d-32b2f726a680&view=o365-worldwide

But the total file count is not matching the actual file count of the user.

https://docs.microsoft.com/en-us/office365/admin/activity-reports/onedrive-for-business-usage?redirectSourcePath=%252fclient%252fOneDrive-for-Business-usage-0de3b312-c4e8-4e4b-a02d-32b2f726a680&view=o365-worldwide

This document says the data reflects the 24-48 hours snapshot.But even after 48 hours we see the same data returned.

**Comment by chackman** [comment]
thanks for your feedback; please provide the following response headers
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by asivanadi** [comment]
Date Fri, 26 Feb 2019 21:43:21 GMT
request-id f816c79e-c0dd-0000-271b-647373b23a1b
SPRequestGuid f816c79e-c0dd-0000-271b-647373b23a1b

**Comment by asivanadi** [comment]
> thanks for your feedback; please provide the following response headers
> 
> > * Date (in UTC, please)
> > * request-id
> > * SPRequestGuid (for requests made to OneDrive for Business)

**Comment by msft-support** [comment]
Reference:
https://docs.microsoft.com/en-us/office365/admin/activity-reports/onedrive-for-business-usage?redirectSourcePath=%252fclient%252fOneDrive-for-Business-usage-0de3b312-c4e8-4e4b-a02d-32b2f726a680&view=o365-worldwide
Similar to
NOTE: At times there may be unpredictable delays in data collection and processing which may delay report generation. The displayed report date is always reflective of the current date for which the system has processed report data. We strive to keep these within 24-48 hours from the time of activity.

The count usually reflect a 24 to 48 hour latency from time of activity.
Sometime this count is subject to unpredictable delays
