### ISSUE TITLE
Error: The folders couldn't be shared. Please try again later.

### ISSUE THREAD

**Issue by adimkovikj** [OneDrive/onedrive-api-docs#1009]
I am using a private One Drive account to test the picker, but I get the error as per the title. I assume the problem lies in the permissions of the app, so I tried granting following:
Application Permissions: Files.ReadWrite.all and Sites.ReadWrite.all
Delegated Permissions: Files.ReadWrite.all, Sites.ReadWrite.all and Users.Read

I also created a shared folder, but no success. I am able to create a new folder, but not to upload a file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c613df58-666d-a413-70cf-f29d0ffb27d2
* Version Independent ID: 2521214c-fd2e-27e0-03f9-e24ca0871f97
* Content: [Save to OneDrive from JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/save-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/save-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/save-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by KevinTCoughlin** [comment]
@adimkovikj is the "private OneDrive account" you are using for OneDrive for Business or OneDrive consumer?

Can you provide the File Picker configuration with the clientId and any other sensitive information omitted so that I can try to repro?

I'm also a bit unclear on what the following means:

>I also created a shared folder, but no success. I am able to create a new folder, but not to upload a file.

Are you trying to share a folder/file or upload a file? Or both?

**Comment by adimkovikj** [comment]
Hi Kevin,
I am actually following this example:
https://stackoverflow.com/questions/50610418/saving-pdf-to-onedrive-using-jquery/54887896?noredirect=1#comment96545902_54887896
I use my OneDrive personal account (not business) and try to upload a file. 
Here you can see the error: https://paste.pics/c074540d49520123483f3769601f9467
I was able to create folders, those two you can see on the screenshot but I can't upload a file. 
Here is the code:
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<form id="uploadfile">
  <input type="file" id="pdfFile" name="pdfFile" class="form-control" />
  <button type="button" class="btn btn-primary" id="uploadBtn">Upload File</button>
</form>
<script type="text/javascript">
$('#uploadBtn').on('click', function(e)
{
  e.preventDefault();
  var formData = new FormData($('#uploadfile')[0]);  // <-- not currently using this variable, but I know I will need it
  var filename = $('#pdfFile').val().replace(/.*(\/|\\)/, '');

  var odOptions = 
  {
    clientId: "APP ID",
    action: "upload",  // <-- was originally set to save
    sourceInputElementId: "pdfFile",
    sourceUri: "",
    fileName: filename,
    openInNewWindow: false,
    advanced: {endpointHint: "api.onedrive.com"},
    success: function(files) { /* success handler */ },
    progress: function(p) { /* progress handler */ },
    cancel: function() { /* cancel handler */ },
    error: function(e) { /* error handler */ }
  }
  OneDrive.save(odOptions);
});
</script>

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
