### ISSUE TITLE
Search requires caller to have access to "context site"

### ISSUE THREAD

**Issue by ificator** [OneDrive/onedrive-api-docs#1010]
An issue was discovered with the search API requiring the caller to have access to the "context site". This generally means the "root site" since most calls are made like:

https://graph.microsoft.com/v1.0/sites/mydomaine.sharepoint.com,uuid1,uuid2

**_Original Report_**
@ificator hi Brad, I'm using the `Delegated Permissions` and search does not work anymore for me. 2 weeks ago it worked properly (but I used at that time `App Permissions`). As we want to scope our rights to specific user we changed to Delegated. 

We requested these permissions `offline_access Sites.ReadWrite.All`  and so far all other API calls work properly (list files in the site, upload file, change meta data, ...) but search does not.

I also tried with https://developer.microsoft.com/graph/graph-explorer/ directly but no luck. 

Works : https://graph.microsoft.com/v1.0/me/drive/root/search(q='a')
Does not : https://graph.microsoft.com/v1.0/sites/mydomaine.sharepoint.com,uuid1,uuid2/lists/uuid3/drive/root/microsoft.graph.search(q='Document')

Regarding uuids I'm pretty sure they are correct because I can do other things with the path (like browse items).

Is there a chance something is broken regarding search functionality (eg. https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0) ?

If not any hint?

Keep good work on Graph API.

_I searched on stackoverflow too : https://stackoverflow.com/questions/52446307/does-microsoft-graph-api-search-work-when-using-app-only-token
https://stackoverflow.com/questions/52446307/does-microsoft-graph-api-search-work-when-using-app-only-token_

_Originally posted by @laguiz in https://github.com/OneDrive/onedrive-api-docs/issues/893#issuecomment-463709544_

**Comment by ificator** [comment]
See https://github.com/OneDrive/onedrive-api-docs/issues/893#issuecomment-463709544 and later comments for more context on this issue.

**Comment by laguiz** [comment]
We are available if you need us to perform new tests.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
