### ISSUE TITLE
MS Graph - Get a DriveItem resource - /users/{userId}/drive/items/{itemId} - returning wrong updated at date

### ISSUE THREAD

**Issue by asivanadi** [OneDrive/onedrive-api-docs#1011]
Get a DriveItem resource - /users/{userId}/drive/items/{itemId} - returning wrong updated at date

<img width="1101" alt="screen shot 2019-02-27 at 8 31 01 pm" src="https://user-images.githubusercontent.com/6239301/53541703-eff59080-3acf-11e9-82cc-ee7be216e5b2.png">

**Comment by chackman** [comment]
Thanks for your feedback, could you please provide the following information:

> If you are reporting a bug, please describe the expected behavior.

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action.
>
> The following response headers would also be helpful if they are available: 
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by asivanadi** [comment]
date →Fri, 08 Mar 2019 21:56:43 GMT
duration →729.5451
odata-version →4.0
request-id →b59297dd-dd89-47a6-b9ec-e6084883c7d4

**Comment by chackman** [comment]
Thanks for your feedback.  Unfortunately I have tried a few times and have been unable to find that request.  Could you please provide a new date/request-id combination?  Thanks!
