### ISSUE TITLE
redirect uri is not in the same domain as picker sdk

### ISSUE THREAD

**Issue by nickeidler** [OneDrive/onedrive-api-docs#1012]
Is there any way I can bypass this client-side check? My app has some use cases in development/staging environments where the redirect domain is on a different domain from the onedrive sdk. Without some way to override this check (short of modifying the SDK code manually) it is difficult to test functionality locally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by KevinTCoughlin** [comment]
@nickeidler, looking at the code.. not currently unfortunately, but I believe we'll be in a position to support such a change this month. Tagging this as a feature ask for when we can make the update in a new release.

**Comment by arsnyder16** [comment]
@KevinTCoughlin Any update here, there hasn't been a release for a while.

**Comment by nlfurniss** [comment]
@KevinTCoughlin can this be added to a backlog?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
