### ISSUE TITLE
Get Embed Links for OneDrive for Business

### ISSUE THREAD

**Issue by DonkeyKongJr** [OneDrive/onedrive-api-docs#1013]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

When calling the createLink endpoint I would expect to retrieve the embed link on both OneDrive Versions (Personal and Business), but when using the Business version an error is returned.

`POST: https://graph.microsoft.com/v1.0/me/drive/items/{id}/createLink`
```
{
  "type": "embed"
}
```

Expected Result:
```
HTTP/1.1 201 Created
Content-Type: application/json

{
  "id": "123ABC",
  "roles": ["read"],
  "link": {
    "type": "embed",
    "webHtml": "<IFRAME src=\"https://onedrive.live.com/...\"></IFRAME>",
    "webUrl": "https://onedrive.live.com/...",
    "application": {
      "id": "1234",
      "displayName": "Sample Application"
    },
  }
}
```

#### Observed Behavior

Actual Result:
```
400 - Bad Request

{
    "error": {
        "code": "invalidRequest",
        "message": "Link type must be either 'edit' or 'view'.",
        "innerError": {
            "request-id": "99f6c0b2-dae0-4958-bfa6-51100f96ff16",
            "date": "2019-03-01T08:58:42"
        }
    }
}
```

I know that the documentation lays out that this feature isn't available for the Business version, but will this be added anytime in the future or not?

[Note: Embed links are only supported for OneDrive personal.](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0)

**Comment by lalitpanda7** [comment]
Is there a workaround for this yet?

**Comment by gsubiran** [comment]
Any progress on this?

**Comment by DonkeyKongJr** [comment]
We somehow managed to build the URL on our own, but keep in mind this is a very fragile workaround. Any change from Microsoft will break our current URL building system.

Basically, we took existing OneDrive Business URLs and reverse engineered them for the file types we support. We faced the isse that for every file type the URL is ever so slightly different.

**Comment by istvanrenyo** [comment]
Still no support, im using the short lived file preview url in a iframe for file previews.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online

**Comment by PRUTHIRAJ97** [comment]
how can I find ondrive embed link from one drive shared link

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
