### ISSUE TITLE
Preview params doesn't work for Excel files

### ISSUE THREAD

**Issue by becker86** [OneDrive/onedrive-api-docs#1014]
Is it already a part of stable public API? Preview params (viewer, chromeless, allowEdit, page, zoom) doesn't work for Excel files.

The same method supports these params in Beta API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abaca550-f44d-455b-ef18-a284dd222dbc
* Version Independent ID: de0dfe46-b10b-5b53-59a1-37967fe2b1ab
* Content: [Get short-lived embeddable link for preview purposes - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_preview.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_preview.md)
* Product: **onedrive**
* GitHub Login: @kevinlam
* Microsoft Alias: **kevinlam**

**Comment by sven5** [comment]
Any update on this question?

**Comment by UmairZahid1** [comment]
Same problem as mentioned above.

**Comment by MoSalib1** [comment]
@JeremyKelley Sir, I have same issue. Can you provide us its solution so we can preview our files in office. No params of preview working.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
