### ISSUE TITLE
The SP site selection is missing from file picker

### ISSUE THREAD

**Issue by tvanh** [OneDrive/onedrive-api-docs#1015]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

The SP site selection is missing from file picker
![image](https://user-images.githubusercontent.com/15227407/53859892-8ff87000-4022-11e9-886c-b3361f2804bc.png)

#### Observed Behavior

File picker with site selection (from sharepoint)

#### Steps to Reproduce

Got following errors

odbonedrive-mini-cfc25a4d.js:1 Refused to get unsafe header "SPClientServiceRequestDuration"
h._onReadyStateChange @ odbonedrive-mini-cfc25a4d.js:1
14:18:40.090 odbonedrive-mini-cfc25a4d.js:1 Refused to get unsafe header "SPRequestGuid"
h._onReadyStateChange @ odbonedrive-mini-cfc25a4d.js:1
14:18:40.090 odbonedrive-mini-cfc25a4d.js:1 Refused to get unsafe header "SPRequestGuid"
r.getCorrelationId @ odbonedrive-mini-cfc25a4d.js:1
Thank you.

**Comment by KevinTCoughlin** [comment]
@tvanh are you still using the following Picker configuration options:

```html
<script type="text/javascript">
function launchOneDrivePicker() {
var odOptions = {
  clientId : "xxxxxxxx",
  action : "share",
  multiSelect : true,
  advanced : {
  },
  success : function(files) {
    fncAddRelationUrlFromO365Onedrive('frmInput:i_urlReference', null, files);
  },
  cancel : function() {
  },
  error : function(e) {
    alert(e);
  }
}

OneDrive.open(odOptions);
}
</script>
```

**Comment by tvanh** [comment]
Yes

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
