### ISSUE TITLE
Checkin/checkout faulty response code

### ISSUE THREAD

**Issue by blackmamba7** [OneDrive/onedrive-api-docs#1016]
Upon calling checkout(graph api beta) on a file to which somebody already has called checkout through the API, the error response status code comes as 500 ("code": "-1, Microsoft.SharePoint.Client.UnknownError",
"message": "Unknown Error",)
instead of 409 or 423. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1671461-eb7b-3519-f62a-2a918b4d7c30
* Version Independent ID: 8e077425-83d0-0faa-607f-b62142244110
* Content: [Check In Files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_checkin?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_checkin.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_checkin.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback; please provide the following response headers:
- Date (in UTC, please)
- request-id

**Comment by blackmamba7** [comment]
I was able to reproduce the same response, here's the date and request-id for the same-
Date: 2019-03-13T13:08:41
Request-id: 03fc7e62-a8e8-4ce1-9463-2409f09a29af

**Comment by dgsqrs** [comment]
same problem here, but mine starts from December 2019
{ "request-id": "040f518d-56c9-49b4-9b3e-81cc2e21aa06", "date": "2020-03-02T08:45:40" }

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
