### ISSUE TITLE
File count not correct in the GET /drive api

### ISSUE THREAD

**Issue by asivanadi** [OneDrive/onedrive-api-docs#1017]
We are using "GET /drive" api specified in this document.
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_get?view=odsp-graph-online

From the documentation we see that the drive resource details are returned as specified by
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/drive?view=odsp-graph-online

We see the quota block returned as a response.

"quota": {
"deleted": 187917,
"fileCount": 192,
"remaining": 1099509515764,
"state": "normal",
"total": 1099511627776,
"used": 82688
}

The fileCount is not specified in this document
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/drive?view=odsp-graph-online.

The file count that we see in this response does not match with that of the total number of files in onedrive.
In case if this is not the total file count, what is this file count number representing.

Date Fri, 26 Feb 2019 21:43:21 GMT
request-id f816c79e-c0dd-0000-271b-647373b23a1b
SPRequestGuid f816c79e-c0dd-0000-271b-647373b23a1b

**Comment by msft-support** [comment]
Reference:
https://docs.microsoft.com/en-us/office365/admin/activity-reports/onedrive-for-business-usage?redirectSourcePath=%252fclient%252fOneDrive-for-Business-usage-0de3b312-c4e8-4e4b-a02d-32b2f726a680&view=o365-worldwide
Similar to 
NOTE: At times there may be unpredictable delays in data collection and processing which may delay report generation. The displayed report date is always reflective of the current date for which the system has processed report data. We strive to keep these within 24-48 hours from the time of activity.

The count usually reflect a 24 to 48 hour latency from time of activity. 
Sometime this count is subject to unpredictable delays

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
