### ISSUE TITLE
Login screen not working properly in inappbrowser.

### ISSUE THREAD

**Issue by kishanbharda** [OneDrive/onedrive-api-docs#1018]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
Login screen should work proper with sort loading time. Input box should focus properly.

#### Observed Behavior
When login screen appear, there are one spinner which loading continuously it not stopping. There are also one input box for email, when i click on it, it is not getting focus so i am not able to enter email. After trying many time if i get input focus, then after email and submitting form, i am again redirect to that enter email id form instead of enter password. 

#### What I have done in my code 
Currently I am using Onedrive Rest API in my ionic app. So first I am calling Onedrive authentication login screen using [Ionic InAppBrowser](https://ionicframework.com/docs/v3/native/in-app-browser/) to login user.
Here is the code that i have used : 

```
  doLogIn():Promise<any>{
    return new Promise((resolve,reject)=>{
      let closeFlag:boolean=false;
      let browser=this.iab.create("https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=my_client_id&scope=Files.ReadWrite.All offline_access Sites.ReadWrite.All&response_type=token&redirect_uri=http://localhost","_blank");
  
      let listener=browser.on("loadstart").subscribe((event: any) => {   
        //Ignore the dropbox authorize screen
        if(event.url.indexOf('oauth2/authorize') > -1){
          return;
        }   
        // Check the redirect uri
        if(event.url.indexOf("access_token") > -1 ){
          closeFlag=true;
          listener.unsubscribe();
          browser.close();
          let token = event.url.split('=')[1].split('&')[0];
          this.accessToken=token;
          this.storage.set("OneDriveAccessToken",token).then(()=>{
            resolve(token);
          }).catch((error)=>{
            reject(error);
          });
        }   
      });
      
      browser.on('exit').subscribe(event => {
        if(!closeFlag){
          reject();
        }        
      });
    });     
  }

  ```

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback. Since this question is about Azure Active Directory, please ask it here: https://stackoverflow.com/questions/tagged/azure-active-directory

**Comment by kishanbharda** [comment]
Actually this issue was inAppBrowser not onedrive api.
