### ISSUE TITLE
OAuth2 authorization process forces download of a file called "nativeclient" when using Chrome

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#1019]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior
Correct URL response as per IE / Edge / Firefox

#### Observed Behavior
Prior to ~ 20th February 2019, any authentication request to the following URL would work without issue:
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
```

After ~20th February, when using Chrome web browser, Chrome downloads an empty file called 'nativeclient'

When performing the EXACT same process under Edge, IE, Firefox - there is no issue.

#### Steps to Reproduce

1. Open in Chrome the above URL & authenticate using any OneDrive Account
2. Chrome will download an empty file
3. Open in Firefox the above URL & authenticate using any OneDrive Account
4. URL will be returned correctly in browser

#### References:
1. https://github.com/skilion/onedrive/issues/455
2. https://github.com/abraunegg/onedrive/issues/405

**Comment by chackman** [comment]
Thanks for your feedback. Since this question is about Azure Active Directory, please ask it here: https://stackoverflow.com/questions/tagged/azure-active-directory

**Comment by abraunegg** [comment]
@chackman 
Why is this problem with Azure Active Directory?

**Comment by chackman** [comment]
The URL is one of the Azure Active Directory endpoints.  AAD StackOverflow is a better place to discuss authentication issues with your application.
