### ISSUE TITLE
Creating and receiving item (embedded) links?

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#102]
Two questions about the OneDrive API regarding SharingLinks.

1. Is it possible to receive already existing links via the OneDrive API in another way than by doing a separate {file-ID}/action.createLink call? For example by expanding the metadata of an item?

    `https://api.onedrive.com/v1.0/drive/items/{item-id}?expand=***links/permissions***`

2. How do I create an embedded link via the OneDrive API? I know that it is possible to create a view or edit link via the following POST call via: 

    ```POST https://api.onedrive.com/v1.0/drive/items/{item-id}/action.createLink
Body: {  "type": "view|edit" }```

    However, requesting an 'embed' link isn't possible although the [documentation](https://github.com/OneDrive/onedrive-api-docs/blob/master/facets/sharinglink_facet.md) shows that it is one of the valid types. I know that it is possible to obtain a embedded link via the [Live SDK](https://msdn.microsoft.com/en-us/library/office/dn659731.aspx#get_links_to_files_and_folders):

    `https://apis.live.net/v5.0/{file-ID}/embed?access_token=ACCESS_TOKEN`

    But how do I do this for the OneDrive API?

**Comment by ginach** [comment]
Currently the OneDrive API only supports view and read links. This looks like a documentation bug in the JSON representation. The type enumeration table on the bottom of the page has the correct information.

As for adding embed support, could you make sure to go add this request to our [User Voice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) page so the community can help prioritize which requests we should focus on fixing?

**Comment by The-Lion** [comment]
I am glad to hear that you are actively working on this API. I created a new suggestion on [User Voice](http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7845657-improve-api-by-extending-the-createlink-method-to) regarding the embedded links: 

http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7845657-improve-api-by-extending-the-createlink-method-to

**Comment by rgregg** [comment]
Closing out old issues. Embed is still not supported, but is on our radar. The documentation has been updated to remove this mention.
