### ISSUE TITLE
400 error with The Path property ... of ODataMessageWriterSetting.ODataUri must end with the navigation property which the contained elements being written belong to

### ISSUE THREAD

**Issue by qx-juilliard** [OneDrive/onedrive-api-docs#1020]
See also: https://github.com/ncw/rclone/issues/3039

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

`https://graph.microsoft.com/v1.0/drives/{drive_id}/items/{item_id}:/photo` should produce correct response

#### Observed Behavior

400 error with message

>  "message": "The Path property ... of ODataMessageWriterSetting.ODataUri must end with the navigation property which the contained elements being written belong to.",

#### Steps to Reproduce

1. Create folder named "photo" within a parent folder
1. Call api `https://graph.microsoft.com/v1.0/drives/{drive_id}/items/{item_id}:/photo` where {item_id} is the id of the parent folder.

This error is caused by having "photo" as directory name.

Thank you.

**Comment by qx-juilliard** [comment]
thanks bot!

**Comment by Cnly** [comment]
I'd like to add some related things: If there is a trailing colon in the path (E.g., `/drives/{drive_id}/items/{item_id}:/photo:`), there seems to be no problem. And, there is actually an issue similar to this: #941. And, this seems to affect both OneDrive for Business and OneDrive Personal.

**Comment by ificator** [comment]
Thanks @qx-juilliard - this is definitely a weird one.

**Comment by qx-juilliard** [comment]
> Thanks @qx-juilliard - this is definitely a weird one.
> 
> Do you by any chance have the `request-id` and `date` values that would have also been returned in the response along with that error message?

```json

  "error": {
    "code": "BadRequest",
    "message": "The Path property 'drives('b%my_drive_id')/items('my_path_id%3A')/photo' of ODataMessageWriterSetting.ODataUri must end with the navigation property which the contained elements being written belong to.",
    "innerError": {
      "request-id": "3f4dee5b-dee4-48ab-804d-2797e609c1f5",
      "date": "2019-03-10T04:52:16"
    }
  }

```

**Comment by ificator** [comment]
Thanks for the details - that's exactly what we needed!

**Comment by ificator** [comment]
We're drilling in to what's going on now, but at least the work around suggested by @Cnly appears to work. I'd definitely recommend using that while we work on fixing the underlying issue.

**Comment by ificator** [comment]
Hey all, I tried reproing this again and it seems like it was fixed by Graph. Do you all concur? If so, I'll mark this issue as resolved.
