### ISSUE TITLE
File Picker: Add configuration option to disable "Switch account" UI

### ISSUE THREAD

**Issue by KevinTCoughlin** [OneDrive/onedrive-api-docs#1022]
## Description

I'm opening this issue to track the release of a configuration option, `accountSwitchEnabled?: boolean`, for the File Picker that hides the "Switch account" UI on the hosted page.

By default, the value is `true` unless in certain first-party scenarios which already exist as to not regress those customers.

## Example Usage

Here is an example usage once the change rolls-out:

```js
var options = {
    clientId: '00000000-0000-0000-0000-000000000000',
    accountSwitchEnabled: false,
    success: (files) => console.log('success', files),
    cancel: () => console.log('cancel'),
    error: (err) => console.log('error', err)
};

OneDrive.open(options);
```

### Enabled (true | Default)

![image](https://user-images.githubusercontent.com/706967/54319772-e8da8200-45a7-11e9-8a8f-65374b790b78.png)

### Disabled (false)

![image](https://user-images.githubusercontent.com/706967/54319782-f09a2680-45a7-11e9-9929-87cd826a1028.png)

## Release

This is scheduled to begin rolling out for `v7.2` of the File Picker tomorrow AM PST, note that CDN caching is involved for ~24hrs. I will close this issue once confirmed deployed to production.

Tagging folks interested in tracking this: @aditima @ldcm3 @jokr

**Comment by KevinTCoughlin** [comment]
I just verified that this change is now live in `v7.2` using the config mentioned above. I will keep this issue open until documentation is updated in the AM.

Scripts to verify:

- js.live.net/v7.2/OneDrive.debug.js
js.live.net/v7.2/OneDrive.js

**Comment by ldcm3** [comment]
Thanks @KevinTCoughlin! Just tested it =)

**Comment by KevinTCoughlin** [comment]
Cool! Closing now that we have verification and documentation has been updated to reflect the new param.
