### ISSUE TITLE
Questions about hashes while and after online redacting of Microsoft Office documents

### ISSUE THREAD

**Issue by sploid** [OneDrive/onedrive-api-docs#1023]
Hello.

#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
We are expecting that all files have hashes (at least one type of hashes).
But while redacting of Microsoft Office documents in the online editor files lost hashes.
After finishing of redacting a document the hash does not appear.

#### Observed Behavior
We need a hash of the file in any state of a file.

#### Steps to Reproduce
Create an "xlsx" file.
Begin editing it in the online editor.
Get a DriveItem resource for this file.

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.  Does this issue affect OneDrive for Business, OneDrive Personal, or both services?

**Comment by AnnaDubrovina** [comment]
Hello!

Let me answer instead of sploid (we are colleagues). We have only personal accounts, so couldn't test OneDrive for Business.

Thanks in advance.

**Comment by chackman** [comment]
Which [hashes in](https://docs.microsoft.com/en-us/graph/api/resources/hashes?view=graph-rest-1.0) particular are lost after redacting the content?

**Comment by AnnaDubrovina** [comment]
For OneDrive Personal sha1Hash and crc32Hash are used, and they both are lost.

**Comment by chackman** [comment]
Unfortunately in some cases hash values may not be available. If this is the case, the hash values on an item will be updated after the item is downloaded.
