### ISSUE TITLE
Non-functional link

### ISSUE THREAD

**Issue by felixaMSFT** [OneDrive/onedrive-api-docs#1026]
This link: (https://dev.onedrive.com/odx) in the text "You can try the OneDrive explorer sample app" does not take the user to a sample app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 956919d9-c495-4a37-03e7-645e75c65484
* Version Independent ID: 2b7ebb7d-e501-53ae-c5a1-7a2cbced45bc
* Content: [CORS support - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/working-with-cors?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/concepts/working-with-cors.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/working-with-cors.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
