### ISSUE TITLE
`OneDrive.open()` opens a new chrome-less window with my own app

### ISSUE THREAD

**Issue by localjo** [OneDrive/onedrive-api-docs#1027]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

`OneDrive.open()` should open the OneDrive file picker.

#### Observed Behavior

`OneDrive.open()` opens a new chrome-less window with my own app

#### Steps to Reproduce

```
const options = {
      clientId: ONEDRIVE_APP_ID,
      action: 'query',
      multiSelect: true,
      advanced: { navigation: { disable: false } },
      success: files => {
        console.log(files);
      },
      error: e => {
        console.log(e);
      },
      cancel: () => {
        console.log('cancelled');
      }
    };
window.OneDrive.open(options);
```

I followed [the steps described here](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online) and I would expect that to open OneDrive so that I can authenticate and/or pick files. But instead, a window opens with my app's domain and an encoded query string. Did I miss a setup step? Am I supposed to somehow handle the query string that's passed back before I can actually open the OneDrive window? Is something wrong with my configuration?

**Comment by localjo** [comment]
It seems that the thing I missed was at the bottom of the [Using alternative API endpoints](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#using-alternative-api-endpoints) section:

> The page you redirect to needs only to load the OneDrive SDK script

I had to create a page in my app that loads the OneDrive SDK script without any user interaction. I think this should be mentioned after step 2 in the docs, instead of way down underneath advanced and alternative options.

**Comment by KevinTCoughlin** [comment]
@localjo glad you found resolution. The documentation is open source and welcomes contributions. That page specifically can be found at: https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md

I'm unsure where to hoist that documentation since it does fall under the "Advanced" scenarios where a user has configured their application to redirect to a different page.

By default, the SDK will redirect to your host page which already has the script loaded.

Open to suggestions!

**Comment by localjo** [comment]
In my situation, I was loading the OneDrive SDK after a user opened a modal and clicked on the OneDrive icon, which was one of many options. I didn't want the page to load the SDK automatically. I think this is a pretty common situation, so I opened a PR the explain how this works.

**Comment by localjo** [comment]
@KevinTCoughlin Quick question about this. I'm triggering the popup from `myapp/library` which loads the OneDrive SDK when a user clicks a button. I have a redirect URI of `myapp/onedrive` which loads the OneDrive SDK immediately. This successfully gets me to the page where I can authenticate with a OneDrive account, but after granting access, I'm redirected to `myapp/onedrive`, skipping the file picker entirely and with no indication that any data has been passed back to my app. Am I missing another step here?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin Quick question about this. I'm triggering the popup from `myapp/library` which loads the OneDrive SDK when a user clicks a button. I have a redirect URI of `myapp/onedrive` which loads the OneDrive SDK immediately. This successfully gets me to the page where I can authenticate with a OneDrive account, but after granting access, I'm redirected to `myapp/onedrive`, skipping the file picker entirely and with no indication that any data has been passed back to my app. Am I missing another step here?

@localjo, what you've described above seems like a misconfiguration of the redirect URL at some level. Is your SDK configuration the same as originally posted above?

If you could share as much of your SDK config and relevant application pages, that would really help me debug. A sample app that repros would be even better.

**Comment by localjo** [comment]
I've essentially got a component that looks like this. First, the component loads in a modal window on my app's gallery page with an icon as a child. Then, on the redirect URL (`/OneDrive`) it loads with no children.

```
import React from "react";
import PropTypes from "prop-types";
import loadScript from "load-script";
import { ONEDRIVE_APP_ID } from "../keys";
const ONEDRIVE_SDK_URL = "https://js.live.net/v7.2/OneDrive.js";

export default class OneDrivePicker extends React.Component {
  constructor(props) {
    super(props);
    this.state = { scriptLoaded: false };
  }

  componentDidMount() {
    if (!this.state.scriptLoaded) {
      loadScript(ONEDRIVE_SDK_URL, () => this.setState({ scriptLoaded: true }));
    }
  }

  launchOneDrivePicker() {
    const { multiSelect, success } = this.props;
    const options = {
      clientId: ONEDRIVE_APP_ID,
      action: "query",
      multiSelect,
      success,
      advanced: {
        redirectUri: "https://localhost:3000/OneDrive"
      }
    };
    window.OneDrive.open(options);
  }

  render() {
    const { scriptLoaded } = this.state;
    const { children } = this.props;
    if (children) {
      return (
        <a onClick={() => this.launchOneDrivePicker()}>
          {scriptLoaded ? this.props.children : "Loading..."}
        </a>
      );
    } else {
      return <span>{scriptLoaded ? "Loaded" : "Loading..."}</span>;
    }
  }
}

OneDrivePicker.propTypes = {
  children: PropTypes.node,
  success: PropTypes.func,
  multiSelect: PropTypes.bool
};
```

**Comment by localjo** [comment]
When I get to the redirect URL, I am still in the popup window, and there is a hash on the URL that looks something like this;

```
"#access_token=<access_token>&token_type=bearer&expires_in=3600&scope=profile%20openid%20https://graph.microsoft.com/User.Read%20https://graph.microsoft.com/Files.Read.All&id_token=<id_token>&state=https://localhost:3000_xx000"
```

**Comment by localjo** [comment]
I'm not completely sure what the issue was. It seems that something in the way my app has routing configured was causing the hash to be lost before the OneDrive SDK was loaded. I opted to create a plain HTML page outside of React instead, and now things are working as expected.
