### ISSUE TITLE
PDF files corrupted on upload

### ISSUE THREAD

**Issue by williamdlupo** [OneDrive/onedrive-api-docs#1029]
When uploading a new or exisiting file as a byte array with "application/pdf" as a header content-type, the file is corrupted and unable to be read. Any advice would be greatly appreciated!

C# Code snippet:
var fileByteArray = ReportFileStream.ToArray();
var fileByteContent = new ByteArrayContent(fileByteArray);
            fileByteContent.Headers.ContentType = new MediaTypeHeaderValue("application/pdf");

var client = _clientFactory.CreateClient("graphApi");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

HttpResponseMessage response = await client.PutAsync($"drives/{driveId}/items/{updatedOneDriveFile.ParentFolderId}:/Report.pdf:/content", fileByteContent);
            

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350cd850-d19a-ef5c-2761-e342fc3c506c
* Version Independent ID: 5bf3ef39-f20a-6c7f-77f6-3bc7e9d246f4
* Content: [Upload small files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online#http-request-to-upload-a-new-file)
* Content Source: [docs/rest-api/api/driveitem_put_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_put_content.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback; could you please provide the following response headers:
- Date (in UTC, please)
- request-id
- SPRequestGuid (for requests made to OneDrive for Business)
