### ISSUE TITLE
What about the wl.imap scope

### ISSUE THREAD

**Issue by mmoya** [OneDrive/onedrive-api-docs#1031]
What about the _wl.imap_ scope? Will an equivalent be eventually added to Microsoft Graph?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8535c93-aaae-ebfe-cfcb-5ebd37dd7d00
* Version Independent ID: 33863b36-3494-d437-b1fc-3e1bff634e74
* Content: [Migrating from Live SDK to Microsoft Graph - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/concepts/migrating-from-live-sdk.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/migrating-from-live-sdk.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
If your target scenario in Graph is [reading email](https://docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0), have you tried the `Mail.Read` scope (or one of the scopes defined in the [Mail permissions section](https://docs.microsoft.com/en-us/graph/permissions-reference#mail-permissions)) of the Graph documentation)?

**Comment by adrinavarro** [comment]
Is it possible to access Office365 email using the IMAP standard and with passwordless auth i.e. OAuth access? (for example XOAuth, as supported by other providers, incl. Outlook/Hotmail)

**Comment by chackman** [comment]
Regarding the specific IMAP question, could you please ask that question on the Microsoft Exchange Server forums?

**Comment by mmoya** [comment]
@chackman Can you share a link for such forum? It's not evident for me which result is the correct one by asking $SEARCHENGINE for 'microsoft exchange server forum'. Thanks.

**Comment by chackman** [comment]
Unfortunately I don't know the best place to look for support with Microsoft Exchange.  If I were to guess, try StackOverflow - https://stackoverflow.com/questions/tagged/exchange-server

**Comment by mmoya** [comment]
As of 2020-04-30 there is support for scope [`IMAP.AccessAsUser.All`][1] but [only for interactive applications][2] (ie: you can't ask it besides `offline_access` scope).


[1]: https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#configure-your-application
[2]: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-oauth-2-0-support-for-imap-and-smtp-auth-protocols-in/ba-p/1330432
