### ISSUE TITLE
GET /drive api returns 404 for existing users

### ISSUE THREAD

**Issue by apertureqa** [OneDrive/onedrive-api-docs#1037]
I’m using "GET /drive" api specified at 
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_get?view=odsp-graph-online

This endpoint returns 404 for some of the existing users but returns the successful response for other users. I’m able to login in the UI and verify the account and the files for the user.

Date: 2019-04-02 18:34:17 UTC
request-id: 1718cf9e-8010-0000-3801-b2294b4a078b
SPRequestGuid: 1718cf9e-8010-0000-3801-b2294b4a078b

**Comment by chackman** [comment]
Thanks for your feedback.  Unfortunately I have tried a few times and have been unable to find that request.  Could you please provide a new date/request-id combination?  Thanks!
