### ISSUE TITLE
🐞 Bug with Graph API uploading file to Modern SharePoint library with Date column containing a default value 

### ISSUE THREAD

**Issue by CameronDwyer** [OneDrive/onedrive-api-docs#1038]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I expect to be able to upload a file to SharePoint via the Graph API (using createUploadSession) irrespective of the SharePoint column configuration. This call fails when the SharePoint document library is a modern document library and contains a Date column with the default value specified as a specific date.

#### Observed Behavior

Call to createUploadSession fails with status code 400 and message “One of the provided arguments is not acceptable”

#### Steps to Reproduce

1. Create modern document library
2. Add Date column (with no default value specified)
3. Use Graph Explorer to create an upload session
    - Sign-in to Graph Explorer to access the tenant with the SharePoint library you just created
    - Find the drive Id for your SharePoint library and substitute it into this URL to use in Graph Explorer
    - POST https://graph.microsoft.com/v1.0/drives/{driveId}/root://test.docx:/createUploadSession
    - You should get a Status Code 200 (OK) 
4. Go back to SharePoint and edit the Date column to specify a default value
5. Execute exactly the same request in Graph Explorer again now the default value has been specified for the date column
   - You should now get a Status Code 400 (Failure) returned
   - The error message is “One of the provided arguments is not acceptable”

I've attached a file with the steps to reproduce including screenshots so it's nice and clear :-)
[GraphAPI-CreateUploadSession-Issue-Date-Column-Default.docx](https://github.com/OneDrive/onedrive-api-docs/files/3036110/GraphAPI-CreateUploadSession-Issue-Date-Column-Default.docx)

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please clarify what you mean by "modern document library" and "classic document library"?  Do you mean which UI experience was used to create and configure the document library?

**Comment by CameronDwyer** [comment]
Yes, that’s exactly what I mean. One of my colleagues was looking into this further and appears the format of the default date differs if set in a  document library with modern UI vs Classic. I suspect the knock on affect of this is the upload failure.

**Comment by chackman** [comment]
OK, thanks for your feedback; we'll need to investigate this further.

**Comment by CameronDwyer** [comment]
Any update on this one? We have several customers of our software striking this issue in the last few days. As it causes a complete failure to create an upload session and we have no control over how customer configure SharePoint libraries our only option is this isn't fixed is to rollback the code and not use the Graph for uploading files to SharePoint.

**Comment by chackman** [comment]
Hi @CameronDwyer, thanks for your patience. I'll contact the team that I have assigned this issue to.

**Comment by CameronDwyer** [comment]
Hi @chackman what's the update from the team? This is still causing us failures in production that we can't work around other than moving away from the Graph API. cc: @JeremyKelley

**Comment by chackman** [comment]
I've asked the team again for an update; thanks for your patience.

**Comment by chackman** [comment]
Thanks @CameronDwyer for your patience; according to the team, the ETA for a fix to the underlying issue is mid-to-late July.

**Comment by CameronDwyer** [comment]
Thanks for the update @chackman.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
