### ISSUE TITLE
hope for the limit explaination

### ISSUE THREAD

**Issue by Zxilly** [OneDrive/onedrive-api-docs#1040]
i got a
  "status": 413,
  "message": "文件包含 810.245 兆字节的信息，超过 52428800 兆字节的上限。",
  "source": "api.connectorp.svc.ms"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 42443681-dd86-ce0c-587f-2336f965ebaf
* Version Independent ID: abcbaeba-560b-661d-0127-5c44d9089915
* Content: [Upload from a URL - OneDrive API - OneDrive dev center](https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_upload_url?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_upload_url.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_upload_url.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  We'll double-check the limit and update the docs.
