### ISSUE TITLE
Example of (OneDrive authentication and sign-in ) In VBA 

### ISSUE THREAD

**Issue by modernsystemit** [OneDrive/onedrive-api-docs#1042]
Please I need an example of the following (OneDrive authentication and sign-in)
which is DESCRIBE in the this page , using  VBA languge will used in Microsoft Access2013 File -or Microsoft access 2016 file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945d553b-251f-6ffa-f040-a3146e04139e
* Version Independent ID: ce3ca8c1-ed4b-0015-3d46-fdedb649ff2d
* Content: [Authorization for OneDrive API for Microsoft Accounts - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/getting-started/msa-oauth.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/msa-oauth.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
