### ISSUE TITLE
OneDrive File Picker JavaScript SDK v7.2: Unable to specify target library or root folder when opening onedrive file picker

### ISSUE THREAD

**Issue by lpoublan** [OneDrive/onedrive-api-docs#1045]
I use OneDrive File Picker JavaScript SDK v7.2.
The user is already authenticated and has a token (auth end point: https://login.microsoftonline.com/common/oauth2/v2.0/authorize).
I want to open the file picker for a given team/group drive (and a specific folder in that drive).
Documentation says it is possible with the following parameters:
(https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
entryLocation: {
        sharePoint: {
          sitePath: "THE-SITE-PATH",
          listPath: "THE-LIST-PATH",
          itemPath: "THE-ITEM-PATH"
        }
However, those parameters are not explained and there is no example.
I searched for examples but did not find. I only found unanswered questions.
See also unanswered question here:
https://github.com/OneDrive/onedrive-api-docs/issues/862

With Graph API, I can get Sharepoint Ids, with requests like:
/groups/1c68e6bb-20bf-4b94-9d13-14379993801e/drive/root?select=sharepointIds
The result is:
listId: "8943d039-cbea-4873-8c7b-e92f34487386"
listItemUniqueId: "cc7b91b3-b9f1-4c00-86e2-1b5128362b63"
siteId: "1732760a-ac4a-40a0-b1cc-d3777acbb659"
siteUrl: "https://msdarwino.sharepoint.com/sites/team0"
webId: "da3ef5ea-1699-450e-9e5d-59beaa12acac"

How can I use this result to fill sitePath, listPah and itemPath?
I just want to open the picker for this team/group, which seems something very basic.

Regards,
Laurent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#feedback)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by lauraemilyjacobsen** [comment]
I am having the same problem. My requirement is to open the picker to a specified SharePoint site's root drive. Is this possible?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
