### ISSUE TITLE
Localization support for File Handlers

### ISSUE THREAD

**Issue by maurocchi** [OneDrive/onedrive-api-docs#1047]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
Can a custom action of a file handler have a localized [displayName](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/define-actions?view=odsp-graph-online#properties)?

Example:
```
{
    "type": "custom",
    "displayName": {
      "en": "Add signature",
      "it": "Aggiungi firma"
    },
    ...
}
```

Thank you.

**Comment by ificator** [comment]
Does [this documentation](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/localization?view=odsp-graph-online) help?

You'd essentially generate a manifest that looks something like:
```
{
    "id": "guid",
    "type": "FileHandler",
    "properties": [
        { "key": "version", "value": "2" },
        { "key": "actions", "value": "[{\"type\": \"custom\", \"displayName\": \"Contoso Document\", ... }]" },
        { "key": "strings en-us", "value": "{\"Contoso Document\": \"Contoso Document in en-us\"}" },
        { "key": "strings fr-fr", "value": "{\"Contoso Document\": \"Contoso Document in fr-fr\"}" },
        { "key": "strings de-de", "value": "{\"Contoso Document\": \"Contoso Document in de-de\"}" }
    ]
}
```

**Comment by maurocchi** [comment]
Thanks @ificator, I didn't notice such page.
