### ISSUE TITLE
How to properly set endpointHint with queryParameters

### ISSUE THREAD

**Issue by godwin2423** [OneDrive/onedrive-api-docs#1048]
There’s an issue using the combination of queryParameters, apiEndpoint and endpointHint. Without any of these we don’t get the full required functionality.

advanced: {
                                                queryParameters: "select=name,webUrl",
                                                apiEndpoint: "https://alamy.sharepoint.com/sites/Salesforce-CRM-group/Shared%20Documents/Price%20Agreements/",
                                                endpointHint: "https://alamy.sharepoint.com/sites/Salesforce-CRM-group/Shared%20Documents/Price%20Agreements/"
                                    },

The error thrown with this code snippet is as follows.

![11](https://user-images.githubusercontent.com/5090445/56191744-91b64a00-604a-11e9-8d50-fcb6304cfd4e.png)

Full function code:
                        function launchOneDrivePicker() {
                            var odOptions = {
                                clientId: "529cb33b-ec76-40f8-94e0-e78c90d27eaf",
                                action: "query",
                                multiSelect: false,
                                advanced: {
                                                queryParameters: "select=name,webUrl",
                                                apiEndpoint: "https://alamy.sharepoint.com/sites/Salesforce-CRM-group/Shared%20Documents/Price%20Agreements/",
                                                endpointHint: "https://alamy.sharepoint.com/sites/Salesforce-CRM-group/Shared%20Documents/Price%20Agreements/",
                                    
                                                navigation: {
                                                            disable: true
                                                }
                                    },

                                success: function (files) {
                                                var files_array = files.value;
                                                for(var i in files_array) {
                                                            alert("name = " + files_array[i].name);           // without queryParameters, this returns undefined.
                                            }
                                },
                                cancel: function () { /* cancel handler */ },
                                error: function (e) { /* error handler */ }
                            }

                            OneDrive.open(odOptions);
                        }

**Comment by KevinTCoughlin** [comment]
@godwin2423, I don't believe you need to specify `apiEndpoint` in this case, only `endpointHint` if at all. Can you try modifying your configuration?

The calls are failing because the requests being constructed by the SDK with those configs are hitting the wrong URL.

cc: @margoflynn

**Comment by godwin2423** [comment]
I have removed apiEndpoint and used only endpointHint option but now getting some console error and the file picker is not working.


![code](https://user-images.githubusercontent.com/5090445/57914953-58713400-78ad-11e9-8010-83744ba286ee.JPG)

Please see the error

![error](https://user-images.githubusercontent.com/5090445/57915021-85bde200-78ad-11e9-9e4f-7919d4e67e98.JPG)
