### ISSUE TITLE
[ODB] 503 serviceNotAvailable when get siteUrl

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1050]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hi all,

I change my OAuth flow to request GRAPH DRIVE API in order to get the onedrive endpoint.

`https://graph.microsoft.com/v1.0/me/drive/sharepointIds/siteUrl`

However, this API failed with following error:
```
http code 503
{
  "error": {
     "code": "serviceNotAvailable",
     "message": "Service unavailable",
     "innerError": {
     "request-id": "b3d019b0-f262-44f1-929f-2843e2bc57f9",
     "date": "2019-04-16T11:48:44"
    }
  }
}
```

But this API works fine with user info part.

`https://graph.microsoft.com/v1.0/me`

Clue 1: This API have little chance to be successful, most time is broken.
Clue 2: Some of my client feedback they enabled the MFA (Multi-Factor Authentication), it might be related.

Is possible that we can fix in client part of it would be a server-side problem?

Thank you.

**Comment by ificator** [comment]
The 503 response suggests that the request is being throttled. Are you seeing any other requests to the tenant in question getting 503s as well, or just this `siteUrl` request through Graph?

**Comment by joewutaiwan** [comment]
Hi @ificator ,

thank you for reply,

In my testing, only drive related API received this response, the rest API work fine(User or mail)

And it is not the only case in this tenant, we encountered this with many accounts.

In my experience, the kind of error would recovered maybe after weeks later.

**Comment by JeremyKelley** [comment]
Investigation indicates that the 503 is returned as expected for the state of the service.  If the 503 is persisting, please open a support ticket with https://www.office.com.

In general you may want to take a look at https://aka.ms/scanguidance and ensure that your app is following our best practices for working with high volume apps.

**Comment by joewutaiwan** [comment]
Hi @JeremyKelley ,

Thanks for reply,
But the support on https://www.office.com. do not accept API things about graph,
I have ask for help and then rejected.

That why I am here.

Do you have any other channel to report API things in specific account?

thanks.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
