### ISSUE TITLE
How do I upload a file located on my hard disk?

### ISSUE THREAD

**Issue by marcelogrsp** [OneDrive/onedrive-api-docs#1051]
Hi, How is the request to upload this file for example?
"C:\Users\Marcelo\Pictures\dashboard.png"

**Comment by chackman** [comment]
As part of "[30 Days of Microsoft Graph](https://aka.ms/30DaysMSGraph)" effort we have a thorough example here - https://developer.microsoft.com/en-us/graph/blogs/30daysmsgraph-day-29-use-case-upload-files-to-onedrive/

Also we have individual API's documented here 
https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0
https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
