### ISSUE TITLE
Search on group not working without Sites.Read.All permission

### ISSUE THREAD

**Issue by dennisameling** [OneDrive/onedrive-api-docs#1052]
Searching in a Group Drive with a **Client Credentials** (Application permission) token doesn't work with the `Files.ReadWrite.All` permission. For example:

`https://graph.microsoft.com/v1.0/groups/{GROUP_ID}/drive/root/search(q='newFileTest.docx')`

... results in a 403 Forbidden error:

```json
{
    "error": {
        "code": "accessDenied",
        "message": "The caller does not have permission to perform the action.",
        "innerError": {
            "request-id": "**redacted**",
            "date": "2019-04-17T12:47:10"
        }
    }
}
```

Only when the **Client Credentials** (Application permission) token has the `Sites.ReadWrite.All` permission (probably `Sites.Read.All` is enough already), search works. Please update the docs to clarify this behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a094aa0-adc5-9f08-d75e-bff6c5c42b4b
* Version Independent ID: c674446f-0d55-5c4b-0d0a-bbddf184dd1b
* Content: [Search for files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_search?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_search.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_search.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback, we'll update the docs.

**Comment by CasperWSchmidt** [comment]
I can confirm this issue. Took me quite some time to figure out :/ Sites.Read.All IS enough though 👍

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
