### ISSUE TITLE
[ODB] get negative size value from a aspx file

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1053]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

Hi all,

Symptom:

1. Get file information encounter size is negative
`GET https://<user_domain>/_api/v2.0/drives/<drive_id>/items/<item_id>`

2. This drive is Wikipage library which is one of the document library in Share Point Online

3. Download is fine for this file.

Response:
```
"name": "Home.aspx",
"file": {
        "hashes": {
            "quickXorHash": "YrWKTN7tmyGNyRicTMvDQltNmk0="
        },
        "irmEnabled": false,
        "mimeType": "application/xml"
    },
    ....
   "size": -425661
```
Header:
```
request-id →da46d69e-00c6-8000-12b2-435e588b9d2a
date →Thu, 25 Apr 2019 02:09:01 GMT
```

Thank you for further help.

**Comment by JeremyKelley** [comment]
Hi, thanks for reporting this issue.  We'll need to investigate further.

Do you observe this with any other ASPX pages or other files or just this particular one?

**Comment by joewutaiwan** [comment]
Hi @JeremyKelley ,

I encountered this issue before.
https://github.com/OneDrive/onedrive-api-docs/issues/926

and the previous one is about onenote files
```
"name" : "Open Notebook.onetoc2",
"size" : -4783,
```

I do not observe any ASPX file with the issue, it is the first.
In other document library this ASPX file could be downloaded properly.

Thanks

**Comment by chackman** [comment]
Thanks for your feedback; we're following up internally about this issue.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
