### ISSUE TITLE
Invalid syntax error when clicking "Return to the application without granting consent"

### ISSUE THREAD

**Issue by nickeidler** [OneDrive/onedrive-api-docs#1054]
When a user tries to authenticate via the File Chooser to their business account, they may be prompted with the "Need admin approval" screen. This is fine. However, if they click the "Return to the application without granting consent" link it redirects to the SDK and hits the following syntax error:

`Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'https%3a%2f%2fwww.REDACTED.com' in a call to 'postMessage'.`

It seems that it is redirecting using the encoded URL, when it really needs to be unencoded prior to use with the `postMessage` API. This error prevents the page from successfully posting the message back to the opening window and results in the window being stuck in a loading screen forever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by KevinTCoughlin** [comment]
Thanks for the report and debug information @nickeidler, we'll take a look at this and get back to you.

cc: @margoflynn

**Comment by nickeidler** [comment]
@KevinTCoughlin any update?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
