### ISSUE TITLE
How to upload files to OneDrive using MS graph sdk?

### ISSUE THREAD

**Issue by ohs0612** [OneDrive/onedrive-api-docs#1056]
Hi all,

Now I have a java.io.File object and trying to implement the "upload" function to OneDrive by using MS Graph SDK.
And now I find out that there are might be two ways to doing this:
1. createUploadSession:
IGraphServiceClient mClient = GraphServiceClient.builder().authenticationProvider(mAuthenticationProvider).buildClient();
mClient
    .me()
    .drive()
    .items(parentID)
    .createUploadSession()
    .buildRequest()
    .post(ICallback<UploadSession>)

2.  Using post(like creating a folder here: https://github.com/microsoftgraph/msgraph-sdk-java/wiki/Working-with-Collections)
try {
	  final DriveItem fileToCreate = new DriveItem();
	  fileToCreate.name = file.getName();
	  fileToCreate.description = "Folder uploaded by MyAPP";
	  fileToCreate.parentReference.id = parentID;
	  fileToCreate.file = new com.microsoft.graph.models.extensions.File();
	  final ICallback<DriveItem> createCallback = new ICallback<DriveItem>() {

		@Override
		public void success(final DriveItem result) {
			Log.d(TAG, "Success");
		}

		@Override
		public void failure(ClientException ex) {
                    Log.d(TAG, "Failure");
		}
	};

	getDriveService()
	.me()
	.drive()
	.items(parentID)
	.children()
	.buildRequest()
	.post(fileToCreate, createCallback);
} catch (Exception e) {
	e.printStackTrace();
	return null;
}

I have tried the second way to do this, and I got the error:

com.microsoft.graph.http.GraphServiceException: Error code: invalidRequest
    Error message: Cannot create a file without content
    
    POST https://graph.microsoft.com/v1.0/me/drive/items/307D4F6201D062EE!101/children
    SdkVersion : graph-java-v1.2.0
    SdkVersion : graph-java-v1.2.0
    Authorization : bearer EwBQA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAAcz1K/2mwAZv5a+T4LEOctJN4Xd1/aePndynE3xVRuakjoKklI8jMRnASJe/hFOOw7jMuLRHSYvP0xstTdlGTKV2kZxjUt/Gu9+AZjPvQe6FNBLJ3e2hWHhhNIfOBgw0GoRPh+hLO9nG7HibzcMusxvMdY+UD0z2rvENX2JkxiEjNDwEiwc3eJzW07apKxFhX1/OtyPkkUf/b4DNz7cBOpzSWH63XjfMbBPT1TIJTmYbTrhaocknP4Be6B+GxLtYskhNDlj5X8wKNs4hpFVIuDvPEvZC12YyjeO9x3fcbuNl9tKtLm4cEEVToiSKIM6hOfDqPwVc981wtfYHzkl0RXIDZgAACLX7XlRz/Z+uIAIyyLhyoSTZZ6jQz8n1C7+gngbSQ/BXaqmnUAnydhy0/jmIH2rU1S0FH7pVtz7zuDFnTo+6tSf6/FQqcGfIgH/jKAawqcCy7t0AscJS8buit9yCXj8dDE8T3qlsDIlayIZfrEAOWjQefgihuzNubkC4a1+KF/hEEPG0ME+LxcqcqXUyNtHB/lYFVqVBcnGggNEBG0LC99oEmX2ngVVkzMc7hG5xdwszawYsCu2dMrXRrFDTtBJeksBJ92w1jpKHm6JTsy5lKL90R5Utyq1NCwf7OVNJukFnMFzhUrSeD5L/SbT+GALKRfgGqO+xW8Y4WHIEuDXkA8A3+lvUPAKYcTl3pYtPcMzlSFCF9uP7/Hlvji4QKI0riaRRptOuy8ym/fNeFtuYC1iVxMoA1FECzwcfVT62sdo2xXvfDE0g2NFlfqNna1X7jJZVHBbOmMxkrY1ZiBPl3t6k7U33BQIJwlIj2Bsmq6RX6+AD8pIQ4mZAWB0VnBhtv/8ShjJn/mokWWOmIT2icx38j9+0OVstvLHr+WGo2dSkjaYIAObPukUYp8r381ktDqP+wUCKGRPMUfP3yrFDAvbozUpEfcUylfe9V41LYGHC6s05S++WqGzOxI4SUijIC1ZGq58NvWwVqHC1Y+vZSamSKBBT//L/OwZ99KeYoJvtfFGvw0XtAao0AZyubb0K1ymOSsGz92x3Yt9x1w1EKprq+LkvrG5xpEXeZQI=
    {"file":{},"description":"Folder uploaded by MVBA.","name":"qqq.iwb"}
    
    400 : Bad Request
    Transfer-Encoding : chunked
    Duration : 537.3145
    request-id : 4cec0e80-dd6d-4fcc-9f1b-e742c76988f3
    X-Android-Received-Millis : 1556268175999
    Date : Fri, 26 Apr 2019 08:42:55 GMT
    X-Android-Selected-Protocol : http/1.1
    Strict-Transport-Security : max-age=31536000
    Cache-Control : private
    x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"East Asia","Slice":"SliceC","Ring":"4","ScaleUnit":"000","RoleInstance":"AGSFE_IN_5","ADSiteName":"EAS"}}
    client-request-id : 4cec0e80-dd6d-4fcc-9f1b-e742c76988f3
    X-Android-Response-Source : NETWORK 400
    X-Android-Sent-Millis : 1556268175387
    Content-Type : application/json
    {
      "error": {
        "code": "invalidRequest",
        "message": "Cannot create a file without content",
        "innerError": {
          "request-id": "4cec0e80-dd6d-4fcc-9f1b-e742c76988f3",
          "date": "2019-04-26T08:42:55"
        }
      }
    }

I know there is no contents inside "fileToCreate.file", but, how do I correctly put my data into this file from my file resource which is a java.io.File type? Or, the correct way to do uploading files to OneDrive is using the first way, createUploadSession? If so, does anyone have any sample or just clue to light me a direction? 

Thank you in advance!

Odee

#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

**Comment by ificator** [comment]
`createUploadSession` is required for files that are greater than 4MiB in size, however if your files are smaller than that you can use put-to-content. In the Java SDK I believe it'll look something like this:

```
getDriveService()
.me()
.drive()
.items(parentID)
.children("childname")
.content()
.buildRequest()
.put(fileContentsInBytes, createCallback);
```

**Comment by ohs0612** [comment]
Hello ificator,

Thank you for your answer!
I think I need to use the createUploadSession as I have to upload file over 4MiB size.

So, I keep digging into how to use that and find out maybe we need another key word, which is "ChunkedUploadProvider", based on many reference pages, for instance:
1. https://github.com/microsoftgraph/msgraph-sdk-android/issues/70
2. https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/7c037cf15413b73d1ad7b52ee027a703f4b63be1#diff-374daffefc443a2b383da1d332b730c6

however, now I find out it seems like there are some differences when using ChunkedUploadProvider, in C# code, there are only four parameters passed when we need are going to get an instance of ChunkedUploadProvider while in java we need "five" parameters to achieve that. Below is my code snippet:
DriveItemUploadableProperties driveItemUploadableProperties = new DriveItemUploadableProperties();
driveItemUploadableProperties.description = "File uploaded by Test.";
driveItemUploadableProperties.name = file.getName();
driveItemUploadableProperties.oDataType = "microsoft.graph.driveItemUploadableProperties";

IGraphServiceClient iGraphServiceClient = getDriveService();
iGraphServiceClient
	.getMe()
	.getDrive()
	.getItems(parentID)
	.getItemWithPath(file.getPath())
	.getCreateUploadSession(driveItemUploadableProperties)
	.buildRequest()
	.post(new ICallback<UploadSession>() {
		@Override
		public void success(UploadSession uploadSession) {
			UtilityHelper.myLogDebug(TAG, "success: " + uploadSession.toString());
			int maxChunkSize = 320 * 1024; // 320 KB
			InputStream inputStream;
			try{
				inputStream = new FileInputStream(file);
				ChunkedUploadProvider provider = new ChunkedUploadProvider(uploadSession, iGraphServiceClient, inputStream, maxChunkSize, null);// what should I pass for the last parameter?
				//TODO find out how to use chunk...
				
			} catch(FileNotFoundException ex){
				ex.printStackTrace();
			}
		}

		@Override
		public void failure(ClientException ex) {
			UtilityHelper.myLogDebug(TAG, "Upload FAIL \n" + ex);
		}
	});

And I can successfully get the upload session with log like:
success: com.microsoft.graph.extensions.UploadSession@e7149a4

So, do you know how to use "ChunkedUploadProvider" in java sdk? And, is that possible to have a code sample if ChunkedUploadProvider is the correct way to upload 4MiB size more file?

By the way, in my gradle file, now I am using:
implementation 'com.microsoft.graph:msgraph-sdk-android:1.7.0' 
instead of:
implementation('com.microsoft.graph:microsoft-graph:1.2.0')
as there are some proguard problems when I am about to build up release version; and it seems like it is similar to this:
https://github.com/microsoftgraph/msgraph-sdk-java/issues/213

Thank you again for replying me above.

**Comment by ificator** [comment]
I'm not all that familiar with the Java SDK, but a quick glance at the code suggests you'll want to provide class as `DriveItem.class`. To actually trigger the upload you'll want to call the `upload` method on the `ChunkedUploadProvider` instance, and you can probably just leave default values for parameters (apart from the callback). Hopefully that helps in some way.

**Comment by ohs0612** [comment]
Hello ificator,

Thank you for your response.
Actually, I knew that I should use upload, and after 1 to 2 days try and error on how to correctly using "upload", I finally found out the right way as below:

		InputStream inputStream = null;
		int fileSize = 0;
		try{
			inputStream = new FileInputStream(file);
			fileSize = inputStream.available();
		} catch(IOException ex){
			ex.printStackTrace();
		}

		IProgressCallback<DriveItem> callback = new IProgressCallback<DriveItem> () {
			@Override
			public void progress(final long current, final long max) {
				//Check progress
				UtilityHelper.myLogDebug(TAG, "The driveItem(" + file.getName() +") with size is:" + max + ", and the current progress: " + current);
			}
			@Override
			public void success(final DriveItem result) {
				//Handle the successful response
				String finishedItemId = result.id;
				UtilityHelper.myLogDebug(TAG, "Successfully uploaded item ID:" + finishedItemId);
			}

			@Override
			public void failure(final ClientException ex) {
				//Handle the failed upload
				UtilityHelper.myLogDebug(TAG, "ClientException happens at IProgressCallback " + ex);
			}
		};

		IGraphServiceClient iGraphServiceClient = getDriveService();
		UploadSession uploadSession = iGraphServiceClient
				.getMe()
				.getDrive()
				.getItems(parentID)
				.getItemWithPath(file.getName())
				.getCreateUploadSession(driveItemUploadableProperties)
				.buildRequest()
				.post();

		if(null != inputStream) {
			ChunkedUploadProvider<DriveItem> chunkedUploadProvider = new ChunkedUploadProvider<DriveItem>(
					uploadSession, iGraphServiceClient, inputStream, fileSize, DriveItem.class);
			try{
				chunkedUploadProvider.upload(null, callback, new int[] { 10 * 320 * 1024 });
			} catch(IOException ex){
				ex.printStackTrace();
			}
		}

and the log would be like:

The driveItem(scallop.iwb) with size is:15253564, and the current progress: 0
The driveItem(scallop.iwb) with size is:15253564, and the current progress: 3276800
The driveItem(scallop.iwb) with size is:15253564, and the current progress: 6553600
The driveItem(scallop.iwb) with size is:15253564, and the current progress: 9830400
The driveItem(scallop.iwb) with size is:15253564, and the current progress: 15253564
Successfully uploaded item ID:307D4F6201D062EE!245

And I am now referencing from here:
https://github.com/microsoftgraph/msgraph-sdk-java/blob/master/src/test/java/com/microsoft/graph/functional/OneDriveTests.java

I was struggling from put initializing the ChunkedUploadProvider inside the callback from uploadSession.post, and that kept failing down unfortunately until I found the link above.
That definitely saves me!

Hope this article helps others as well!

Appreciate your reply again, ificator! :)
