### ISSUE TITLE
Received Url to custom Thumbnail is invalid?

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#106]
Hi,

We are using OneDrive API to create custom thumbnail sizes. After testing I have found out that the custom thumbnail url that is returned to my App always links to a page with the following error:

>Bad Request - Invalid URL
HTTP Error 400. The request URL is invalid.

However, if I do the same request via the OneDrive apigee console, the url is valid.

<h4>Here is request via the apigee console:</h4>
*Request*
<pre>GET /v1.0/drive/items/{item-id}?expand=thumbnails(select%3Dmedium,large,mediumSquare,c1500x1500) HTTP/1.1
Authorization: Bearer EW…..
Host:api.onedrive.com
X-Target-URI:https://api.onedrive.com
Connection:Keep-Alive
</pre>
*Response*
<pre>HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000; includeSubDomains
Strict-Transport-Security:max-age=31536000; includeSubDomains
Date: Wed, 06 May 2015 09:59:22 GMT
X-MSNSERVER:BN1304____PAP075
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Content-Length:2616
OData-Version:4.0
Via:1.1 DM2304____PAP310 (wls-colorado)
Connection:keep-alive
X-AsmVersion:UNKNOWN; 19.18.0.0
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
Server:Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
X-WLSPROXY: DM2304____PAP310

---First part of body is removed---
"thumbnails@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives('me')/items({item-id})/thumbnails",
  "thumbnails":  [
     {
      "id": "0",
      "large":  {…},
      "medium":  {…},
      "mediumSquare":  {…},
      "c1500x1500":  {
        "@odata.type": "#oneDrive.thumbnail",
        "height": 1500,
        "url": "https://public.bn1304.livefilestore.com/y2mBrJyp_Ei5zqFWpQ-uF_jYgIyFEiunH7EtMfjXvt8duKn0ZiPWnj2p9MUb5Xmjpzy6ROaqgbNQkbXRXq-8FNAJKizR2KBLshYTGHyXWpxmA29HI6mAQTC9ZdbRZQNm5HLYToNOmYevOHm1huJSGYeZ-IokLoCkblXOFpA-yQrz1FkVtyK2SVJwWuTmqd_u9dN?width=1500&height=1500&cropmode=none",
        "width": 1500
      }
    }
  ]
</pre>
<h4>Response for the same request received by my App:</h4>
<pre>HTTP/1.1 200 OK
Date: Wed, 06 May 2015 10:04:03 GMT
X-MSNSERVER:BN1304____PAP104
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Content-Length:1864
OData-Version:4.0
Via:1.1 DM2306____PAP280 (wls-colorado)
Connection:keep-alive
X-AsmVersion:UNKNOWN; 19.18.0.0
Content-Type: application/json; odata.metadata=minimal;
Content-Encoding: gzip
Server:Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
X-WLSPROXY: DDM2306____PAP280

---First part of body is removed---
"thumbnails@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives('me')/items({item-id})/thumbnails",
  "thumbnails":  [
     {
      "id": "0",
      "large":  {…},
      "medium":  {…},
      "mediumSquare":  {…},
      "c1500x1500":  {
        "@odata.type": "#oneDrive.thumbnail",
        "height": 1500,
        "url": "https://public.bn1304.livefilestore.com/y2m3UabicOMZedsKjA00pBDJ0WfWSa25RopQFQETdgnsVyDAg1jCmMhAiJsZTlIXMV3VhkolTp6mA2kgZwVVfJiU3lViOkbPmCqXYu43MOV3Pqx9B6cwRM-Xcpkx2RPgplmHhllPmJWtn8HG0FJUc-W7l49FonPVsQFlag2xLue9X2EyOoyb1VmkDUs7lkZZox7EY7pueIQSGXsPB3Ywl7DVhqAVprT66ey_TQoHlV73mxQJRzdOQATtdI_isjeHBjoXCvgMxkmK8ygYJMMXe2yAw?width=1500&height=1500&cropmode=none",
        "width": 1500
      }
    }
  ]
</pre>

Am I missing something here, or do you have any ideas why the generated url via the apigee console is valid, where as the url that is received by my App isn't?

**Comment by ificator** [comment]
Hi @The-Lion, when you get a 400 using the returned thumbnail URL could you capture the response headers and provide them here?

**Comment by The-Lion** [comment]
There are almost no headers available:

<pre>
GET /y2mRxNEEfhWmINxyls7GIn2sCy6bNm9VbICU52R7NN2hWIfrs5l__KIin0ewSDIgBvqvJra3kW8oP3EJXZgBzxjGFbB-ZENRVATRevWngHd7m9Scjx8DHu64O9QD8dpkjNeYYhv-UfG7kVYSNCHb2PCOZgsQFSBjDTuoix6rn7V5dpv4f5PxwLtiNW-Q5gAbeLdBsXlC2BL0R0qgwBAFtTtPrnIQNpzk5-68rPQCTNJAHwARowGF14uDoPDPnLKFxPkyGS3l-TNRPCpd2GfgG2RYw?width=1500&height=1500&cropmode=none HTTP/1.1
Host: public.bn1304.livefilestore.com:443

HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 324
Content-Type: text/html; charset=us-ascii
Date: Wed, 06 May 2015 17:13:46 GMT
</pre>

**Comment by ificator** [comment]
Strange, that either means it's an error really (really) low level in our stack, or it's not an error that came from us. From the request you provided I reconstructed the request and it seemed to work ok:

    GET https://public.bn1304.livefilestore.com/y2mRxNEEfhWmINxyls7GIn2sCy6bNm9VbICU52R7NN2hWIfrs5l__KIin0ewSDIgBvqvJra3kW8oP3EJXZgBzxjGFbB-ZENRVATRevWngHd7m9Scjx8DHu64O9QD8dpkjNeYYhv-UfG7kVYSNCHb2PCOZgsQFSBjDTuoix6rn7V5dpv4f5PxwLtiNW-Q5gAbeLdBsXlC2BL0R0qgwBAFtTtPrnIQNpzk5-68rPQCTNJAHwARowGF14uDoPDPnLKFxPkyGS3l-TNRPCpd2GfgG2RYw?width=1500&height=1500&cropmode=none HTTP/1.1
    Host: public.bn1304.livefilestore.com

    HTTP/1.1 200 OK
    Cache-Control: public
    Content-Length: 158991
    Content-Type: image/jpeg
    ... snip ...

Is it possible there's some kind of proxy in the way that's doing something unexpected?

**Comment by The-Lion** [comment]
Hmm, that's strange. I just tested it in different browsers, on my iPad (wifi) and 2 mobiles connected via 4G, and all give the same 400 error. So I don't think that something local is causing the trouble. Besides that, in that case I would expect the same 400 issue for the URL generated by apigee...

**Comment by The-Lion** [comment]
It seems that it has to do with the geolocation. If I use an USA proxy, the link is working fine. If I use a proxy from Germany or The Netherlands I get the 400.

**Comment by ificator** [comment]
I talked this over with some other people on the team and given the lack of headers it doesn't appear to be coming from us and we therefore don't really have much to go on. I managed to repro with hide.me but there's not much to go on. As much as I hate to say it, at this point it looks like this issue is external to our api/service.

**Comment by The-Lion** [comment]
I did some extra research as just couldn't see the difference between the standard thumbnails links, the custom thumbnail link generated by apigee and the link generated for my app. The only difference I can see is the length of the path (livefilestore.com/{path}?query) in the link. So I just started removing characters from the path in the link that throws the error, and surprisingly, if the path is truncated to less than 260 characters, the error is gone...

All the thumbnail links that are generated by default are shorter than 260 characters (including the apigee call), but via my app they are always longer. If you start searching on that issue, a lot of results will pop up ([ref1](http://forums.iis.net/t/1105360.aspx), [ref2](http://forums.iis.net/t/1190185.aspx), [ref3](https://msdn.microsoft.com/en-us/library/system.web.configuration.httpruntimesection.maxurllength(v=vs.100).aspx)). Apparently it is a well know issue with windows servers. And it explains why no headers are returned as the request is not even being processed by IIS.

This still doesn't explain why I have this issue here in Europe where as you can't reproduce it in the US. I tried to do some tracing on the different urls, but the valid and the non-valid link seems to end just in the same server (a-0011.a-msedge.net), suggesting that it is still caused by some servers on your side...

So, perhaps this information can help us solve the problem? Is it possible to reduce the size of the path to less than 260 characters? Or perhaps you can add the path to the query as that doesn't have the limit?

**Comment by ificator** [comment]
Our maximum path segment length is well above 260 characters, so it would have to be something in the middle that's not handling it correctly. Having said that, we're looking in to some changes with the urls we generate so this is great information to factor in to that discussion. Thanks for keeping us up to date on your investigation!

**Comment by ificator** [comment]
We've captured the segment limit requirement and will consider it when we drill deeper in how we want our URLs to work long term.
