### ISSUE TITLE
[ODB] Unable to return view.delta information for folders shared with me

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#1060]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

Able to query view.delta or delta for a specific object which has been shared with me

#### Observed Behavior

As per https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online#remarks, this states the following:

For shared folders added to a drive, delta will not return any information about changes within the shared folder. Instead, another delta call should be made that targets the shared folder itself.

However, creating the applicable URL to target the delta for the folder:

url = https://graph.microsoft.com/v1.0/drives/ ~ driveId ~ "/items/" ~ id ~ "/delta";

generates the following error:
```
{
    "error": {
        "code": "notSupported",
        "message": "view.delta can only be called on the root.",
        "innerError": {
            "request-id": "63850350-8e61-4df0-9383-6495fda61bb4",
            "date": "2019-05-06T16:31:03"
        }
    }
}
```
How to query a 'shared folder' that is not in the drive root?

If the folder structure is:
```
root:/Level1/
```

Then view.delta works when querying Level1 - if Level1 is shared with me

however if the folder structure is:
```
root:/Level1/Level2
```

AND Level2 is what is shared with me:

* view.delta on root for any changes returns nothing for any changes in Level2
* unable to query Level2 via item id as query is not implemented

How to query view.delta in this scenario?

#### Steps to Reproduce

1. Create a multi level folder structure as user a
2. Pick the last folder and share that folder with user b
3. As user B, upload data via web interface to shared folder
4. As user B, use MS Graph API to view the changes (view.delta) of that shared folder ... you cant even though it is shared with you.

**Comment by chackman** [comment]
Currently, Delta has additional restrictions in OneDrive for Business; specifically the [delta action is only available on the root item of a drive](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/release-notes?view=odsp-graph-online#view-deltas) (and also the delta API call would be made against the owner's OneDrive).  For feature requests please log an item in our User Voice.
