### ISSUE TITLE
AADSTS900144: The request body must contain the following parameter: 'scope'.

### ISSUE THREAD

**Issue by jnbarlow** [OneDrive/onedrive-api-docs#1063]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
Following the example  here: https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online

I'm expecting to get a file picker, but instead am getting a bizarre auth error.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/1322371/57554193-cca45880-733e-11e9-9f0d-6e0c78f4c72f.png)

The error is `AADSTS900144: The request body must contain the following parameter: 'scope'.` 
This might have to do with the graph api expects scope, but the params for the file picker uses scopes.

#### Steps to Reproduce

- Follow the example at: https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online 
- attempt to auth
- observe

**Comment by KevinTCoughlin** [comment]
Hey @jnbarlow thanks for the report. I'll need additional information to debug.

Can you provide your configuration with client key / proprietary information omitted?

Is it exactly as the example has it?

```js
var odOptions = {
  clientId: "INSERT-APP-ID-HERE",
  action: "query",
  multiSelect: true,
  advanced: {},
  success: function(files) { /* success handler */ },
  cancel: function() { /* cancel handler */ },
  error: function(error) { /* error handler */ }
}
```

**Comment by jnbarlow** [comment]
@KevinTCoughlin yeah, it's basically the exact same as the config (with console logs in the callbacks.  The only thing I changed was removing the multi-select line, but everything else is pretty much just like the example.

There's a chance something is wonky with our account, but the error makes it seem like the SDK didn't send the graph something it wanted.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
