### ISSUE TITLE
Cannot refresh the file handler in a short time

### ISSUE THREAD

**Issue by maurocchi** [OneDrive/onedrive-api-docs#1065]
After the registration of a new set of manifests, in base of my experience, when I invoke the reset endpoint, each request concludes successfully but the result is always the previous set of manifests. The new manifests are refreshed only a lot of hours after.

Is this your expected behaviour when you say "the cache may take several seconds to repopulate"?

---
#### Document Details

* ID: b18ba6d3-b187-12d6-2e08-418b0746ac5b
* Version Independent ID: dd01f1c1-7e26-39e2-9e06-afd3305c65e7
* Content: [Reload OneDrive File Handlers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/reset-cache?view=odsp-graph-online#feedback)
* Content Source: [docs/file-handlers/reset-cache.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/reset-cache.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment]
Hello,

After you upload the new manifests do you see them reflected in the Manifest Editor in Microsoft Azure?  If you log in to https://portal.azure.com you should see the AddIns property populated with the manifest in the manifest for your app.

-Jeremy

**Comment by maurocchi** [comment]
@JeremyKelley yes, the changes are reflected in the Manifest Editor, the problem concerns only the "reset" endpoint.

A sample flow is the following:
* update the manifest (M1)
* do reset --> ok, it returns the prevous manifest
* do reset again --> ok, it returns the new manifest
* update the manifest again due to a fix (M2)
* do reset n times --> fail, it always returns the first updated manifest (M1) and the file handler is not refreshed.

So it seems like you can do a single reset a day (very annoying if you are a developer).

**Comment by MalikDrako** [comment]
Was any progress ever made on this issue? I'm running in to it now
