### ISSUE TITLE
[ODB] GET item report wrong information sometimes

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1066]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

Hello,

I use this request would return wrong information sometimes

`GET items/<item_id>`

Now I have two cases about this issue with headers
1. hash response is wrong
```
"quickXorHash": "EOEIyiQUFXTmlRKTQY6JLZ6ufHQ="
real hash is 'pNiPYTLbq89nUCcISn3+HanoumY='

date →Thu, 16 May 2019 10:39:05 GMT
request-id →6326dd9e-2017-0000-9a0e-dca6f3b2986d
```

2.size response is wrong
```
"size": 23907174
real size is 22101889

request-id →eb25dd9e-c0dd-0000-9a0e-d1e1278d1f92
date →Thu, 16 May 2019 10:30:56 GMT
```

How can I determine this?
Because I can not reproduce this on different O365 account with files I downloaded from the issued O365 account

All information is correct after I uploaded to another O365 account

Thank you.

**Comment by ificator** [comment]
We're following up to see if there's an explanation to what you're seeing. Is there any particular pattern for files that seem to have either of these issues? All of one type? All in on drive? etc

**Comment by joewutaiwan** [comment]
Hi @ificator,

Really appreciated to hear about that!
Thank you for contributions.

**Comment by joewutaiwan** [comment]
Hi @ificator ,

In my observation of this issue:
1. For now, all cases are online document like docx, pptx etc.
2. The issue happened on many drives among users, for now at least 4-5 user cases
3. Not sure how long will this persists.
4. Only saw this on One Drive service

thanks!

**Comment by ificator** [comment]
Thanks @joewutaiwan.

I'd like to quickly confirm a scenario that may give us a lead on what's going on:
1. Call the service and get the hash (I'll call it Hash1)
2. Download the file
3. Compute the hash for the local file (I'll call it Hash2)
4. Confirm Hash1 != Hash2
5. Call the service and get the hash (I'll call it Hash3)

Which of Hash1 and Hash2 matches Hash3?

**Comment by joewutaiwan** [comment]
hi @ificator 

Hash1 equals to Hash3

but Hash2 is the real value of this file.

I have tested and confirm this by re-uploading to another account and then get the info again.


thanks!

**Comment by joewutaiwan** [comment]
hi @ificator ,

Sorry for bothering, do you have any update?

Thanks.

**Comment by ificator** [comment]
Nothing to share at the moment unfortunately.

**Comment by ificator** [comment]
Hi @joewutaiwan - do you know if IRM is enabled on the document library for which you're seeing this behavior?

**Comment by ificator** [comment]
Good news! We understand what's happening with the file size issue and are investigating how we can fix it.

We still aren't sure what's going on with the hash mismatch.

**Comment by joewutaiwan** [comment]
Hi @ificator ,

Thank you for investigation,

Now we encountered many cases with this issue, like with .pdf files

So it might happen in any kind of files.

Hoping you have fix soon

Appreciated!

**Comment by joewutaiwan** [comment]
Hi @ificator ,

Sorry for bothering,

Two more things need to be checked:

1.What kinds of extensions would be affected? maybe we could add a filter to skip this.

2.Will the fix apply to all files? or only apply to the new-added file? but the old files is still broken?

Thanks!

**Comment by ificator** [comment]
Theoretically any file type can be affected by the issue, but thankfully the fix would apply instantaneously - you won't need to worry about uploading the files again.

It may take some time for us to get it fixed though as there are a few edge cases that will require some thought.

**Comment by joewutaiwan** [comment]
Hi @ificator ,

Is possible to know the progress of this issue? If the schedule is far away maybe I should do some workaround in my app.

Thank you for help.

**Comment by onedrive-dev** [comment]
Is any update on this issue?

I occasionally encounter the same problem with a file's metadata from the Document Library.

The server gives me the right file size but incorrect file hash.
It seems to happen to  Microsoft files. (e.g., .docx, .pub and .mmp)

Many thanks.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
