### ISSUE TITLE
Keep getting generalException (500 error from server) on get delta changes request

### ISSUE THREAD

**Issue by AnnaDubrovina** [OneDrive/onedrive-api-docs#1067]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

Hello!

We get 500 error after get delta changes request:
"error": {
        "code": "generalException",
        "message": "General Exception While Processing",
        "innerError": {
            "request-id": "eb7172a2-cba0-4b05-9f08-26dcc8fb9815",
            "date": "2019-05-17T07:42:09"
        }
    } 
and we keep getting it until some data is not removed from account.
I can reproduce it by loading or restoring from recycle byn some directory with many files. Also this behaviour can be seen in another account with absolutely different files, and in Microsoft Graph Explorer, too.
![Testing request in graph explorer](https://user-images.githubusercontent.com/42321724/57915473-8ba9c800-7899-11e9-890f-d5797aaf0d8d.png)
I can provide you with data for test if needed. 

We have tested only personal accounts on Windows.

Thanks in advance.

**Comment by ificator** [comment]
I had a quick look at the request at it seems like the value being provided for `token` is incorrect. It appears as though the correct token is being provided twice, separated by a comma:

```
https://graph.microsoft.com/v1.0/me/drive/root/delta?token=abc123,abc123
```

This fails is, rightly, being treated as an invalid token. How was the token obtained? Is it possible there was some process on the client side that transformed the token?

**Comment by AnnaDubrovina** [comment]
Thank you very much for your reply, it helped me to find error in my code.
