### ISSUE TITLE
Sharepoint: Replacing Files of Specific Types Return 404

### ISSUE THREAD

**Issue by Cnly** [OneDrive/onedrive-api-docs#1068]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

After uploading a file with the API to Sharepoint, re-uploading a modified version of the file should work and should replace the previously uploaded version.

#### Observed Behavior

For files of some types (currently there have been reports for .docx and .xlsx), attempts to replace the uploaded versions get 404 instead: `{"error":{"code":"itemNotFound","message":"The resource could not be found."}}`

Response headers required:
```
Date: Tue, 21 May 2019 18:34:35 GMT
Request-Id: 95ddde9e-2046-0000-348a-810bf34ec6af
Sprequestguid: 95ddde9e-2046-0000-348a-810bf34ec6af
```

#### Steps to Reproduce

1. Create an Office document file (`.docx`) locally. This file should not exist on remote at this time.
1. Upload it to a Sharepoint site with requests `POST /v1.0/drives/b!{driveID}/items/{itemID}:/{filename}.docx:/createUploadSession` and `PUT {path in uploadUrl}`. The upload should succeed normally.
1. Make any changes to the local document file.
1. Re-upload the modified file using the same types of requests in step 2.
1. The server returns `200` for `createUploadSession`, but then `404` for `PUT`, with the body `{"error":{"code":"itemNotFound","message":"The resource could not be found."}}`.

Thank you.

**Comment by abraunegg** [comment]
@Cnly 
Most likely - as you are uploading to Sharepoint - are being hit by this bug - https://github.com/OneDrive/onedrive-api-docs/issues/935

Microsoft modifies your files when uploading to Sharepoint by 'enriching' them, thus the file you 'think' your trying to replace actually now does not exist - the MS version does, with it's metadata / content.

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please clarify when the application uploaded the original version of the document?  And whether there were other upload sessions that had recently been created on this file, such as to replace the content?

**Comment by Cnly** [comment]
@chackman Thanks for replying. The application uploaded the first version of the document no more than 3 minutes before uploading the modified version. (If you need a timestamp I can re-run the steps to reproduce.) There shouldn't be other upload sessions as the document is a newly created one. And I'm not using other clients such as the official OneDrive client.

**Comment by chackman** [comment]
Thanks @Cnly, we have sent the request/response information along to another team for them to investigate further.

**Comment by kotsak** [comment]
Not sure how related could be to an issue I had raised almost 2 years ago and it still bugs some of our users from time to time. In our case the only solution is to manually deleted the existing files before re-uploading.
#689

**Comment by chackman** [comment]
I have requested an update from the team looking in to this issue.

**Comment by alexgran** [comment]
Hey,  @chackman any news one the issue? We are seeing this also while trying to sync a few TB into onedrive/sharepoint. Together with the known defect of sharepoint modifying uploaded files, finding out if an upload was successful is not straight forward...

**Comment by chackman** [comment]
I have requested an update from the team looking in to this issue.

**Comment by ItherNiT** [comment]
Hey, @chackman any update from the team yet?

**Comment by chackman** [comment]
Sorry, nothing to report from that team.

**Comment by akdor1154** [comment]
2.5 years later.. any movement? :)

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
