### ISSUE TITLE
MediaServiceAutoTags and MediaServiceOCR Fields

### ISSUE THREAD

**Issue by AJIXuMuK** [OneDrive/onedrive-api-docs#1069]
**Please, do not delete. @JeremyKelley asked to add this question here :)**

#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hi all! I saw new fields MediaServiceAutoTags and MediaServiceOCR in Documents returned by SharePoint and OneDrive APIs. What are the story and plans around these props? Another thing is that these props don't exist on "old" sites, created few months ago...

Thanks!

**Comment by chackman** [comment]
Thanks, we'll follow up with another team to get more information about your request.

**Comment by chackman** [comment]
Could you also please clarify a little more about your scenario?  For example are you interested in particular properties that the API should make available via the [`[DriveItem]` resource type](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0), its properties/facets, or something else?

**Comment by AJIXuMuK** [comment]
@chackman - the properties I pointed above are interesting for me as they are populated from document content. And could be used for auto tagging, grouping and relative search. Especially with combination of taxonomy.
So, I'm interested in these particular properties and the story around them:
1. How are they used my Microsoft?
2. Will they be propagated for "old" documents? (these fields appeared maybe 6 months ago and populated only for docs that are created afterwards)
3. Will these properties be included in "documented" API so we could use it?
...

Thanks!

**Comment by chackman** [comment]
Thanks, those specific list fields should be treated as internal.

If there are specific properties that would be useful, we could consider requests to officially support by adding to the relevant API's (such as `driveItem` or some of its facets like `image` and `photo`).  This is something that we would have to consider like we do via UserVoice.  More information about your specific needs would help.

**Comment by chackman** [comment]
Could you please provide more information about your specific needs regarding these fields - which properties that you would like to have as part of the API?  Also please ask via our UserVoice as feature enhancement suggestions go there.

> Please use the OneDrive Developer Platform UserVoice at https://onedrive.uservoice.com/, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.
