### ISSUE TITLE
Wrong Format in the part of error response

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1071]
format is incorrect.
What I see is:
Read the [Error Responses][error-response] topic for more info about how errors are returned. [error-response]: ../concepts/errors.md [item-resource]: ../resources/driveitem.md [folder-facet]: ../resources/folder.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8e0c33b-73b9-4086-4fa3-c54b701d9695
* Version Independent ID: 869bb2ba-3e32-36c9-7b4f-3875b6c5c277
* Content: [Create a new folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_post_children?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_post_children.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_post_children.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
