### ISSUE TITLE
[ODB] How to explain the expirationDateTime in resume upload?

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1073]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hello folks,

According to this document:
https://docs.microsoft.com/zh-tw/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#upload-bytes-to-the-upload-session

We will get a uploadUrl after we request a upload session

And then we can use following request to get the status and resume our upload:
`GET uploadUrl`

My question is when I request above, it will give me a **expirationDateTime**, but I dont know how to explain the time.

For example:
1. I created a session at 2019-05-31T07:30:00.000Z
2. get the response from above request :  "expirationDateTime": "2019-05-31T07:48:28.928Z",
3. There are only 15 minutes between the expirationDateTime
4. the uploadUrl is still work after the expirationDateTime

1.How can I explain the expirationDateTime?
2.How long will the uploadUrl get expired?
3.Will request GET uploadUrl response 401 error? (In my case, it happened)

Thank you.

**Comment by joewutaiwan** [comment]
Hi, 

I request this again today: `GET uploadUrl
`

response:
```
401
{"error":
{"innerError":{"code":"expiredToken"},
"code":"unauthenticated",
"message":"The access token has expired.
 It's valid from '5/31/2019 7:33:29 AM' and to '6/1/2019 7:33:29 AM'."}}
```

In my understanding,  the lifetime of a upload url seems to be 24 hours?

Thank you

**Comment by chackman** [comment]
Thanks for your feedback.  The `expirationDateTime` is only guaranteed to be valid for the specified length of time returned in the `createUploadSession` API response.
