### ISSUE TITLE
Want to subscribe (Web Hook) to a specific folder within Drive

### ISSUE THREAD

**Issue by BaileyMillerSSI** [OneDrive/onedrive-api-docs#1074]
I am working on a project that I want to watch my Videos/Xbox Game DVR folder for changes but every way that I try and set my resource to that I get errors like, 
```
"error": 
{
        "code": "InvalidRequest",
        "message": "resource '/drive/root:/Videos/Xbox Game DVR' is not supported.",
        "innerError": {
            "request-id": "50e1eba1-660a-443b-a692-bcd0109c60f3",
            "date": "2019-06-03T15:32:54"
        }
}
```

Is it not possible to subscribe to a specific folder because watching my entire OneDrive directory for changes seems like a lot of waste when I only really want my specific videos folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4523605a-9b7a-86bd-ce4e-66f7413b551f
* Version Independent ID: 60c0eb4b-7da3-5ade-322b-a028325c5bd8
* Content: [Webhook Notification - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/webhooknotification?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/resources/webhooknotification.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/webhooknotification.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please clarify whether this request is for OneDrive Consumer or for OneDrive for Business?
Also if this is for OneDrive Consumer, have you tried ending your resource path with a colon?  i.e. /drive/root:/Videos/Xbox Game DVR:

**Comment by JeremyKelley** [comment]
Also in case it helps, here's the WebHooks doc page:  https://docs.microsoft.com/en-us/graph/webhooks?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0

You may want to try removing the : entirely from the path as it looks like that's not in the path example on the docs.

**Comment by BaileyMillerSSI** [comment]
@chackman This code was run against OneDrive consumer.  I am using my personal OneDrive account to do all this stuff. 
@JeremyKelley  I will try the new code without using the colon. 

Sadly this code is insanely hard to debug because it's running inside an Azure Function for the Auth hook and the OneDrive hook. So I have to watch the Azure Portal for logs from my functions to get the tokens to then input into Postman to make API calls.

**Comment by BaileyMillerSSI** [comment]
@JeremyKelley I ran the code again and I still get the same error with or without the colon. Depending on how I format it I either get these errors:
Also I tried removing the inner folder Game Dvr and went to just Videos and it's the same problem.
```
"error": {
        "code": "BadRequest",
        "message": "Unsupported segment type. ODataQuery: /users/baileymiller@live.com/drive/root/Videos",
        "innerError": {
            "request-id": "3a29d758-29cf-4c4e-8430-3fcc0c3212aa",
            "date": "2019-06-10T20:12:21"
        }
    }
```
or 
```
"error": {
        "code": "InvalidRequest",
        "message": "resource 'me/drive/root:/Videos' is not supported.",
        "innerError": {
            "request-id": "9965c39c-1aaa-4324-a64d-6ab258bbd041",
            "date": "2019-06-10T20:13:08"
        }
    }
```

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
