### ISSUE TITLE
OneDrive file picker - "More libraries" button not working

### ISSUE THREAD

**Issue by vikdet** [OneDrive/onedrive-api-docs#1076]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
I am using OneDrive file picker for JavaScript v7.2. 
1) Open picker with the following parameters:
```javascript 
{
      clientId: '***'
      action: 'share',
      multiSelect: 'true',
      openInNewWindow: true,
      advanced: {redirectUri: '***'},
      success: ***


    }
```
2) login..
3) click on "More libraries" button at Shared Libraries section
4) All libraries page should be shown (works in web version of picker [https://dogbob-my.sharepoint.com/personal/msteams_eu_dogbob_onmicrosoft_com/_layouts/15/onedrive.aspx?view=15](https://dogbob-my.sharepoint.com/personal/msteams_eu_dogbob_onmicrosoft_com/_layouts/15/onedrive.aspx?view=15)]

#### Observed Behavior
Nothing happens in picker opened from JavaScript.

Thank you.

**Comment by KevinTCoughlin** [comment]
I can confirm this regression, thanks for the report @vikdet. We'll get this fixed and communicate back.

cc: @ThomasMichon @margoflynn

**Comment by KevinTCoughlin** [comment]
@vikdet, @ThomasMichon is working on a fix, will update when merged with roll-out ETA.

**Comment by KevinTCoughlin** [comment]
@vikdet are you still impacted by this issue? We've begun rolling out a fix.

**Comment by abdulkareemnalband** [comment]
We are also facing this issue, our options are
```js
{
  clientId:'****',
  advanced:{
    accessToken:'****',
    endpointHint:'<users personal sharepoint url >', // `webUrl` from  `https://graph.microsoft.com/v1.0/me/drive`
    navigation:{
      sourceTypes: ['OneDrive', 'Sites']
    },
    success:succesCalback,
    error:errorCallback,
    cancel:cancelCallback,
    action: 'query'
  }
}
```

**Comment by KevinTCoughlin** [comment]
Hey @abdulkareemnalband, the Picker options shouldn't matter in this case. The regression occurred on the hosted page within the Picker frame and is currently rolling out worldwide. ETA for a fix is early next week.

**Comment by vikdet** [comment]
@KevinTCoughlin Thanks for updates! We are waiting for fix.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin Thanks for updates! We are waiting for fix.

@vikdet, to my knowledge this fix is now deployed. I confirmed with both my primary and test accounts.

Please open a new issue and tag me if you do not see the fix. Thanks for your patience and the report.

**Comment by moos** [comment]
We're still not seeing this fix -- nothing happens when clicking on "more libraries" -- no JS errors either.

**Comment by KevinTCoughlin** [comment]
> We're still not seeing this fix -- nothing happens when clicking on "more libraries" -- no JS errors either.

I'll follow-up with the team. Are you seeing this when the Picker is being used for a SharePoint tenant?

**Comment by moos** [comment]
Not sure what a "sharepoint tenant" is -- here's a screenshot if it helps.

![Screen Shot 2019-07-16 at 5 42 50 PM](https://user-images.githubusercontent.com/233047/61490276-6bfa5300-a961-11e9-9aef-8eca2ade539c.png)

**Comment by KevinTCoughlin** [comment]
@moos, I received confirmation from the team that this change is deployed world wide. Have you confirmed that the JavaScript cache is disabled or at least refreshed?

I'll continue to try to repro with test accounts.

**Comment by moos** [comment]
We self-host the file OneDrive.js.  Even though ours says `e.SDK_VERSION_NUMBER = "7.2";` doing a diff against https://js.live.net/v7.2/OneDrive.js shows they are different!  😖 I tried this version as well and still not working.  Is it possible to open a service ticket so I can provide more info that might help in debugging this issue?

**Comment by KevinTCoughlin** [comment]
We have a support ticket open and are investigating.

**Comment by moos** [comment]
Hi -- any update on this?

**Comment by moos** [comment]
Be great to get an update on this issue and/or an ETA.  Is this even being looked at?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
