### ISSUE TITLE
Picker stuck in loading state 

### ISSUE THREAD

**Issue by splinter** [OneDrive/onedrive-api-docs#1077]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
The OneDriver Picker should load the user's OneDrive view.

#### Observed Behavior
The OneDriver Picker does not load after the authentication process but instead shows a spinner.

#### Steps to Reproduce

OneDrive Scripts Tested: 
- https://js.live.net/v7.2/OneDrive.debug.js
- https://js.live.net/v7.2/OneDrive.js

Code used to Initiate the OneDriver Picker:

```
function launchOneDriverPicker() {
      debugger;
      var odOptions = {
        clientId: "${clientId}",
        action: "share",
        multiSelect: true,
        openInNewWindow: true,
        advanced: {
          redirectUri: "${redirectUri}"
        },
        success: function(r) {
        },
        cancel: function() {
        },
        error: function(error) {
        }
      };
      OneDrive.open(odOptions);
    }
```

Environments Tested:
- Chrome (Normal/Incognito)
- Firefox (Normal/Incognito)

*Steps*
- The page hosting the OneDrive Picker and redirect URLs are served from the same domain 
- The redirect occurs to a redirect page with the following content hosted under the same domain (domain/redirect):

```html
<html>
<head>
<link rel="icon" href="data:;base64,iVBORw0KGgo=">
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.debug.js"></script>
</head>
</html>
```

**Additional Notes**
- The above setup  works correctly with the OneDriver Picker 7.0 as noted in an earlier issue:
https://github.com/OneDrive/onedrive-api-docs/issues/824
- While debugging the issue I noticed that the OneDriver Picker makes a cross document call to the parent window which opened the Picker. There are no errors up to this point but the parent page does not receive this message.
- The domain specified in the cross document call is correct

**Reference**
[1] https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#using-a-custom-redirect-uri

Thank you.

**Comment by splinter** [comment]
I have created a sample here: https://1drv.ms/u/s!AqFHpzX4iwNucp-2zcXQaSyyH3Y?e=nkfQXQ

**Comment by splinter** [comment]
App permissions: 
https://1drv.ms/u/s!AqFHpzX4iwNudFf8OxLDEyOw2k4?e=0UmZO1

**Comment by splinter** [comment]
Any update?

**Comment by KevinTCoughlin** [comment]
> Any update?

I'm working to setup a repro. To my knowledge, nothing changes that would have regressed this functionality. We'll see shortly.

**Comment by KevinTCoughlin** [comment]
@splinter I'm unable to repro this issue using File Picker `7.2`. Please see my sample repository at https://github.com/KevinTCoughlin/onedrive-file-picker-redirect-uri-debug.

Have you confirmed that the browser is not stopped on the `debugger;` in your configuration block?

That is the only difference I notice compared to https://github.com/KevinTCoughlin/onedrive-file-picker-redirect-uri-debug/blob/14b0bc9a6dd744a3ea6372dc6bb8ce2d362406fe/index.html#L8.

cc: @margoflynn

**Comment by splinter** [comment]
@KevinTCoughlin Thank You for the sample. I was successfully able to load the picker using the sample.

After comparing your sample with my own one I noticed that the only difference was that we were launching the picker with an anchor tag with an empty href.

**Comment by KevinTCoughlin** [comment]
@splinter glad you're unblocked. We'll add this to the backlog to investigate why that would cause issues and if we can guard against it. It might be the case that the URL is modified and does not match the redirect URI causing problems redirect problems. But I'm not sure until we test.

**Comment by KevinTCoughlin** [comment]
I modified our test page to launch the Picker with an empty anchor tag i.e. `<a id="openPicker">Open</a>` and was able to complete the Picker flow end-to-end. I'm going to close this as I cannot repro and the user is unblocked.

**Comment by splinter** [comment]
@KevinTCoughlin 

Can you please try with the following:

```html
<a href="">Open</a>
```
