### ISSUE TITLE
API copies files to LiveFolders instead of root folder

### ISSUE THREAD

**Issue by bloha** [OneDrive/onedrive-api-docs#1079]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected and Observed Behavior
Path "/drive/root:/:" should refer to "/drive/root::".
But API thinks that "/drive/root:/:" is equal to "/drive/root:/LiveFolders:".
So if I perform copy to "/drive/root:/:", it copies files to "/drive/root:/LiveFolders:".

#### Steps to Reproduce
<code>
POST https://api.onedrive.com/v1.0/drive/root:/Tora:/oneDrive.copy

{
  "name":"Tora2",
  "parentReference": {
    "path":"/drive/root:/:"
  }
}
</code>

**Comment by chackman** [comment]
Thanks for your feedback.  Are you observing that /drive/root/ (no colons or sub-paths) is working as expected?  We would like to clarify whether the behavior that you describe is only observed when addressing via "/drive/root:/:"

**Comment by bloha** [comment]
Yes, '/drive/root/' is working as expected. '/drive/root:' and '/drive/root::' works too.
Referring to root folders (like '/drive/root:/Documents:') is working as expected.
The problem exists only with '/drive/root:/:'

**Comment by chackman** [comment]
Thanks for the clarification; we'll need to investigate further but this looks like a bug.
