### ISSUE TITLE
Documentation Missing for Existing File Upload Conflict Resolution Option

### ISSUE THREAD

**Issue by alexwaibelmsft** [OneDrive/onedrive-api-docs#1080]
#### Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

#### Background

[Here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online) is the relevant endpoint. Currently, if you upload a file with the same filename as an existing file, the existing file is overwritten. To change this behavior so that filename conflicts are handled by renaming the new file, you can append the following query parameter: `@name.conflictBehavior=rename`. This is currently not documented anywhere

#### Expected or Desired Behavior

The optional request parameter for handling filename conflicts for file uploads should be recorded in the documentation for the endpoint.

#### Observed Behavior

Files uploaded with the same name as that of an existing file overwrite the existing file.

#### Steps to Reproduce

1. Upload any file using the endpoint linked above.
2. Upload a different file with the same name as that of the file in part 1.
3. Observe that the file from part 1 was overwritten with the file from part 2.
4. Upload the file from part 1 again, this time adding the query parameter `@name.conflictBehavior=rename`.
5. Observe that both files exist in the drive with the last one to be uploaded having been renamed.

**Comment by alexwaibelmsft** [comment]
#1072 should be enough to resolve this issue.

**Comment by chackman** [comment]
@alexwaibelmsft I committed the merge, let me know if it all looks good.

**Comment by alexwaibelmsft** [comment]
@chackman Looks perfect, I can see it on docs.microsoft.com. Thank you!
