### ISSUE TITLE
How do I upload a large video to my Shared Documents folder?

### ISSUE THREAD

**Issue by jwilhelm48** [OneDrive/onedrive-api-docs#1081]
Looking for to use the API to upload large files to a folder created in a Shared Documents drive. 

Right now "createUploadSession" creates and entirely new folder/drive within the Shared Documents rather than putting the file in the folder itself.

**Comment by chackman** [comment]
Here is an example
https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#request
