### ISSUE TITLE
authentication_token in code flow?

### ISSUE THREAD

**Issue by ljw1004** [OneDrive/onedrive-api-docs#1082]
#### Category
- [ ] Question
- [X] Documentation issue
- [ ] Bug

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#response-2

The documentation for code-flow says: "If the call is successful, the response for the POST request contains a JSON string that includes several properties including access_token, authentication_token and refresh_token if you requested the wl.offline_access scope."

However, (1) the example of a response doesn't include authentication_token, (2) the onedrive oauth API doesn't even return authentication_token in practice for code flow.

**Comment by chackman** [comment]
Thanks for your feedback. Which document are you referencing?

**Comment by ljw1004** [comment]
@chackman The document is https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#response-2

(Sorry I didn't include that. The old MSDN "document feedback" always knew which document it was feedbacking about. I didn't realize that the move to github had lost that feature).

**Comment by seanix99** [comment]
just to add to my question. Here the result returned when you point directly to a sharePoint site:

Object:
value: Array(1)
0: {id: "01KFYDXCCSPIM52FIDDVHKD477Y6VSID5M", parentReference: {…}, sharePoint: {…}, endpoint: "https://idscollabdev.sharepoint.com/_api/v2.0"}
length: 1
__proto__: Array(0)
webUrl: null

**Comment by chackman** [comment]
@ljw1004 are you also using the picker to get an auth token?  This will help with categorizing the issue.

**Comment by ljw1004** [comment]
@chackman I'm not sure what "picker" means in this context. What I'm doing is the code flow described at https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#code-flow --

Step 1. https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#step-1-get-an-authorization-code
My app sends
```
GET https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id={client_id}&scope={scope}
  &response_type=code&redirect_uri={redirect_uri}
```
and onedrive redirects to `{redirect_uri}`

Step 2. https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#step-2-redeem-the-code-for-access-tokens
My server's handler for `{redirect_uri}` makes a request to
```
POST https://login.microsoftonline.com/common/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}
&code={code}&grant_type=authorization_code
```
and in response gets a refresh_token.

Step 3. https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#step-3-get-a-new-access-token-or-refresh-token
My app makes a further request
```
POST https://login.microsoftonline.com/common/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}
&refresh_token={refresh_token}&grant_type=refresh_token
```

The docs for this step 3 claim that the server will send back "several properties including access_token, authentication_token and refresh_token if you requested the offline_access scope"

However, my experimentation shows that even if when I request the offline_access scope, onedrive nevertheless fails to return `authentication_token`.

That's why I filed a doc bug, because I believe the docs are wrong to claim that I'll get one back in this step.

(Onedrive used to be sending back an authentication_token in step 3 when I last checked 2 years ago,. But apparently it no longer does. Maybe the docs are old and date from that time?)

**Comment by chackman** [comment]
@ljw1004, thanks for clarifying.  As you suggest, this could be a documentation issue, rather than something else.
The `authentication_token` property looks like a typo and instead should be removed.  You should use the `access_token` property instead, per the AAD docs here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#refresh-the-access-token

Does that token work for your scenario?  If so, then a quick fix to the OneDrive docs would be to remove `authentication_token` from that part of the doc to avoid confusion.  Furthermore, we can backlog a task to go through the auth section of the OneDrive API docs and clear up any discrepancies with the AAD and Graph docs, and also add some references where appropriate.

--

@seanix99, the issue that you are reporting is a separate issue.  Please create a separate issue in GitHub for tracking your request.

**Comment by ljw1004** [comment]
@chackman Yes I'm sure this is solely a documentation issue.

(I can't use `access_token`. It serves a very different purpose. The job of `authentication_token` is to provide to the app's server an indefinite cryptographic guarantee of the UUID of the logged-in user, assuming the app's server knows the app's crypotgraphic secret that was registered on the Live developer portal. The job of `access_token` is to provide to Onedrive temporary authentication.)

Anyway, it doesn't matter. I can roll my own authentication token in a similar way to how OneDrive used to do it. I just wanted the docs fixed up!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
