### ISSUE TITLE
accessToken is missing in the json response

### ISSUE THREAD

**Issue by seanix99** [OneDrive/onedrive-api-docs#1087]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior
When using the parameter "endpointHint" to specify a full path to a Sharepoint library, it is expected to retreive in the json response the accessToken and the apiEndpoint. You can read the info in the section 4 of the documentation [here](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online).

#### Observed Behavior

When populating the parameter "endpointHint" with a full URL to a SharePoint document library, the returned json response is missing accessToken and apiEndpoint.

#### Steps to Reproduce

**Here an example of code to use to reproduce the bug.**

var odOptions = {
clientId: oneDriveApplicationId,
action: "query",
multiSelect: false,
openInNewWindow: false,
advanced: {
endpointHint: "https://xxxxxxx.sharepoint.com/sites/TestServicesRequests1/TestServicesRequests/",
redirectUri: "http://127.0.0.1:5500/DoSomething.html"
},
success: function (files) {
resolve(files);
},
cancel: function () { resolve(null); },
error: function (e) { reject(e); }
};
OneDrive.open(odOptions);

**Here the result returned when you point directly to a sharePoint site:**

Object:
value: Array(1)
0: {id: "01KFYDXCCSPIM52FIDDVHKD477Y6VSID5M", parentReference: {…}, sharePoint: {…}, endpoint: "https://idscollabdev.sharepoint.com/_api/v2.0"}
length: 1
proto: Array(0)
webUrl: null

**Comment by KevinTCoughlin** [comment]
Thanks for your report @seanix99. We will look into this and get back to you. cc: @margoflynn

**Comment by seanix99** [comment]
@KevinTCoughlin Any news about this issue ?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin Any news about this issue ?

The team is currently addressing a few Picker regressions including #1076. We will investigate this soonest. cc: @aditima @margoflynn 

The Picker response should include `accessToken` to issue subsequent API requests. I'm not yet sure why it isn't in the above case.

**Comment by seanix99** [comment]
@KevinTCoughlin @JeremyKelley Any news if its have been adressed by the teams ?

**Comment by westleyMS** [comment]
one thing I did find is that the token while I believe it used to be populated in more cases, is only documented to give one back for Graph endpoints -
_"The access token received by the file picker for your application. This can be used to make additional requests to Microsoft Graph without requiring another authentication flow."_
([https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#response-properties](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#response-properties))

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
