### ISSUE TITLE
Inaccurate search results

### ISSUE THREAD

**Issue by jdew73** [OneDrive/onedrive-api-docs#1088]
####Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Using vb.net Graph API, do a driveitem search like this: client.Sites.Item(_siteID).Drive.Search(_queryText).Request().

Where _queryText equals "human resources", using the encapsulating quotes.  I would expect it to return only those documents with the phrase "human resources".

#### Observed Behavior

The search returns results with "human" only and "resources" only.  It is not limited to the exact phrase.

Please advise.  Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
