### ISSUE TITLE
@microsoft/file-browser: preview release status?

### ISSUE THREAD

**Issue by arsnyder16** [OneDrive/onedrive-api-docs#1089]
What is the status of the file-browser react component? It seems to be stale for the last 9 months. Is there a road map for officially supporting this component? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd8a4b3-eb11-087a-2406-5979bd3931b3
* Version Independent ID: 39e9d7ef-e826-0096-2758-f6259741cd91
* Content: [Microsoft File Browser SDK (Preview) - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/react/?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/react/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/react/index.md)
* Product: **onedrive**
* GitHub Login: @KevinTCoughlin
* Microsoft Alias: **keco**

**Comment by KevinTCoughlin** [comment]
I'm working with the team to surface our roadmap for `@microsoft/file-browser` publicly. I will update this issue and relevant documentation soonest. cc: @aditima

**Comment by aditima** [comment]
We certainly plan to support @microsoft/file-browser officially, and the team is currently working hard on getting it to a polished state for public consumption. Please stay tuned for updated documentation and announcements in this space in the next few months.

**Comment by bryankai** [comment]
Do you have any code samples available using this package?

**Comment by KevinTCoughlin** [comment]
> Do you have any code samples available using this package?

@bryankai, here are a few from the initial release:

- https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/react/select-files?view=odsp-graph-online#1-attach-an-onsuccess-callback
- https://www.npmjs.com/package/@microsoft/file-browser#usage
- https://github.com/KevinTCoughlin/file-browser-example

**Comment by DonKoko** [comment]
We are testing this and we are facing some issues with the code samples provided. The view renders but then we get an error "GraphError: Unable to retrieve user's mysite URL.". The token we are using is a token we generated using the Microsoft Graph endpoint using Postman. Any ideas/directions on what could be the issue? Have been stuck for too long here. Thanks in advance.

**Comment by arsnyder16** [comment]
It's almost been 9 months with no updates.

* Any update on a road map surfacing?  @KevinTCoughlin
* What about the progress of the team polishing this off?   @aditima 
* How does this relate to the [microsoft-graph-toolkit]( https://github.com/microsoftgraph/microsoft-graph-toolkit)?
  * Are these independent efforts by Microsoft? 

9 months we should be ready to deliver :)

**Comment by sagar-ranglani** [comment]
1. We want an option to show this in Read-only mode. That means, no Update/delete button.
2. `selectionMode="single"` is not working

Everything, as far as I saw, is working great! :-)

Awaiting your updates on this! :-)

**Comment by sagar-ranglani** [comment]
@KevinTCoughlin, @aditima Please let us know if you have any news about this package. Or else, we'll have no choice but find something else, and somehow patch that in.

I really hope that the work on this continues. Looks promising package for future Onedrive development.

Any news update would be highly appreciated. Thanks! :-)

**Comment by anilabsinc-harpreet** [comment]
@KevinTCoughlin, @aditima  @microsoft/file-browser not providing us share/move/search feature. Can you help me on this to introduce these feature into my app?

**Comment by braydonburn** [comment]
> 1. We want an option to show this in Read-only mode. That means, no Update/delete button.
> 2. `selectionMode="single"` is not working
> 
> Everything, as far as I saw, is working great! :-)
> 
> Awaiting your updates on this! :-)

Along with what @sagar-ranglani has commented:
-  `itemMode='folders'` is not working

Can we please have an update?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
