### ISSUE TITLE
dataLocationCode field is not available in graph API for multi geo.

### ISSUE THREAD

**Issue by yuvarajp1515** [OneDrive/onedrive-api-docs#1091]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
With reference to https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery
![Screenshot from 2019-06-27 22-08-09](https://user-images.githubusercontent.com/37432927/60569534-3feda800-9d8d-11e9-8c99-a6d9adf9550e.png)

#### Observed Behavior
Missing of dataLocationCode in getting all geolocation API
URL: https://graph.microsoft.com/v1.0/sites?filter=siteCollection/root%20ne%20null&select=webUrl,siteCollection
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites",
    "value": [
        {
            "webUrl": "https://netskopepmskopejpn.sharepoint.com/",
            "siteCollection": {
                "hostname": "netskopepmskopejpn.sharepoint.com",
                "root": {}
            }
        },
        {
            "webUrl": "https://netskopepmskopegbr.sharepoint.com/",
            "siteCollection": {
                "hostname": "netskopepmskopegbr.sharepoint.com",
                "root": {}
            }
        },
        {
            "webUrl": "https://netskopepmskope.sharepoint.com/",
            "siteCollection": {
                "hostname": "netskopepmskope.sharepoint.com",
                "root": {}
            }
        },
        {
            "webUrl": "https://netskopepmskopeind.sharepoint.com/",
            "siteCollection": {
                "hostname": "netskopepmskopeind.sharepoint.com",
                "root": {}
            }
        }
    ]
}
```

![Screenshot from 2019-06-27 11-59-37](https://user-images.githubusercontent.com/37432927/60569577-509e1e00-9d8d-11e9-9f06-f9940fb2a769.png)

 Please also provide the following response headers corresponding to your request(s):
 - Date - Wed, 03 Jul 2019 06:38:47
 - request-id - 566ae7b6-4852-40e3-8485-7daf9c010472
 - SPRequestGuid - 1d8dec9e-c071-0000-3f4a-597faa9ba2ef

#### Steps to Reproduce
Make graph api call with graph token
url : URL: https://graph.microsoft.com/v1.0/sites?filter=siteCollection/root%20ne%20null&select=webUrl,siteCollection

Thank you.

**Comment by manojdes** [comment]
@chackman can you please take a look at this issue, this is a key scenario for us to be able multi geo. if you can pls share some timelines of a fix (if you are planning one) that would be good to know. Thanks again for your response and fast turn around. Really appreciate . Have a good day.

**Comment by chackman** [comment]
I have assigned to another engineer to investigate this issue further, I can update next week if we have anything to report.

**Comment by manojdes** [comment]
@chackman thank you so much , appreciate your response, since this affects multiple production customers. Looking forward to an update if you have any this week.

**Comment by chackman** [comment]
We’re working on getting the `dataLocationCode` property of the `SiteCollection` resource type reviewed and published to Graph v1.0 in the upcoming month.  It is currently available in [Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/sitecollection?view=graph-rest-beta#properties).

We don’t expect there to be any changes between beta and v1.0 (particularly since we have sample code that references Graph v1.0 where this property is missing).  If there are any changes, we will reply on this issue.

**Comment by chackman** [comment]
We've been encountering issues with the publishing process, so the work is currently delayed while we sort that out.  Apologies on this unexpected delay.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
