### ISSUE TITLE
Unable/Error while getting preferredDataLocation in users/delta API

### ISSUE THREAD

**Issue by yuvarajp1515** [OneDrive/onedrive-api-docs#1092]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
With reference to https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0. while making user/delta API call we should get preferredDataLocation for multi geo

#### Observed Behavior
Unable to get preferredDataLocation in users/delta API
URL used : https://graph.microsoft.com/v1.0/users/delta?$select=id,mail,userType,userPrincipalName,accountEnabled,displayName,assignedPlans,preferredDataLocation

![Screenshot from 2019-06-27 11-28-10](https://user-images.githubusercontent.com/37432927/60571612-9957d600-9d91-11e9-9d46-931f047adbef.png)

 Response headers corresponding to your request(s):
 - Date - Wed, 03 Jul 2019 07:25:2
 - request-id - 1d42128-c88b-4e1c-9fd8-c6e0f7519a37
 - SPRequestGuid - 1d8dec9e-c071-0000-3f4a-597faa9ba2ef

#### Steps to Reproduce

Make graph API call with graph token
URL used : https://graph.microsoft.com/v1.0/users/delta?$select=id,mail,userType,userPrincipalName,accountEnabled,displayName,assignedPlans,preferredDataLocation

Thank you.

**Comment by manojdes** [comment]
@chackman , am not sure how this relates to AAD, but @yuvarajp1515  will create a ticket. These are specific to multi geo, do you kindly mind taking another pass at this question, just to be sure . thank you very much in advance.

**Comment by chackman** [comment]
Like with #1093 the `user` resource is defined in AAD, so it would be best to start with the AAD team.
