### ISSUE TITLE
Missing preferredDataLocation field in users graph API

### ISSUE THREAD

**Issue by yuvarajp1515** [OneDrive/onedrive-api-docs#1093]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
With reference to https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0. while making user/delta API call we should get preferredDataLocation for multi geo

#### Observed Behavior
Missing preferredDataLocation field in users graph API 
URL: https://graph.microsoft.com/v1.0/users/indiauser1@netskopepmskope.onmicrosoft.com?%24select=displayName%2CpreferredDataLocation

![Screenshot from 2019-07-03 14-30-34](https://user-images.githubusercontent.com/37432927/60578696-4ab13880-9d9f-11e9-9a50-d415649d6231.png)

response headers corresponding to your request(s):
 - Date - Wed, 03 Jul 2019 08:57:05
 - request-id - f8119dbe-6027-4682-bfa4-6821b4e1d9f3
 - SPRequestGuid - 1d8dec9e-c071-0000-3f4a-597faa9ba2ef

#### Steps to Reproduce

Make graph API call with graph token
URL used : https://graph.microsoft.com/v1.0/users/indiauser1@netskopepmskope.onmicrosoft.com?$select=displayName,preferredDataLocation

Thank you.

**Comment by manojdes** [comment]
@chackman , am not sure how this relates to AAD, but @yuvarajp1515 will create a ticket. These are specific to multi geo, do you kindly mind taking another pass at this question, just to be sure . thank you very much in advance.

**Comment by chackman** [comment]
The `user` resource is defined in Azure Active Directory, so please start with the AAD team.  I tested with a similar API call and that API call was answered by AAD.

However I wasn't able to find the logs to confirm for your case; I assumed the time was in UTC, please correct if the time is wrong.

**Comment by manojdes** [comment]
@yuvarajp1515  can you confirm , this has been answered ?  I am guessing this is the where Microsoft has recommended usage of beta. If thats the case, lets close this one.
