### ISSUE TITLE
"Query" typo, spelt as puery

### ISSUE THREAD

**Issue by zakisaad** [OneDrive/onedrive-api-docs#1095]
"This method supports the $select OData puery parameter to customize the response."

Should be:

"This method supports the $select OData *query* parameter to customize the response."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 860b00a0-e2f0-0ac9-5feb-4e488d99098f
* Version Independent ID: 4000c65d-ef19-4c94-0d89-2e6e7a21401b
* Content: [Retrieve thumbnails for a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_thumbnails?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_list_thumbnails.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_list_thumbnails.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback, I'll create a pull request to fix the typo.

**Comment by chackman** [comment]
commit 942d5e6
