### ISSUE TITLE
Service returns 403 Forbidden when creating upload session to appfolder

### ISSUE THREAD

**Issue by tipa** [OneDrive/onedrive-api-docs#1097]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
creating an upload session works without 403

#### Observed Behavior
Creating an upload session in order to upload a file to the app folder returns 403 Forbidden when the app folder does not exist yet.

"Simple item upload" via PUT works without problems.
Also, if the app folder already exists (e.g. because it was created previously with a "Simple item upload") creating an upload session also works as expected

#### Steps to Reproduce
I am hitting OneDrive Personal (beta endpoint).
Requested Scopes are `Files.ReadWrite.AppFolder`

```
client-request-id: 53a479a5-1e7e-4c28-884e-d3fea39c86ff
Strict-Transport-Security: max-age=31536000
request-id: 53a479a5-1e7e-4c28-884e-d3fea39c86ff
Transfer-Encoding: chunked
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_30","ADSiteName":"WEU"}}
Duration: 583.478
Cache-Control: private
Date: Tue, 09 Jul 2019 07:59:51 GMT
```

```
client-request-id: 3664db26-148f-49e6-b452-bc1a6f4950b5
Strict-Transport-Security: max-age=31536000
request-id: 3664db26-148f-49e6-b452-bc1a6f4950b5
Transfer-Encoding: chunked
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_36","ADSiteName":"WEU"}}
Duration: 617.6514
Cache-Control: private
Date: Tue, 09 Jul 2019 08:01:51 GMT
```

**Comment by tipa** [comment]
Any updates on this? Any additional details needed?

**Comment by tipa** [comment]
Any updates on this? This bug still exists

**Comment by tipa** [comment]
Will this ever be fixed? I would love to assist any way I can

**Comment by tipa** [comment]
Over a year since creation of this issue and still no comment...
@ificator @zachzi

**Comment by tipa** [comment]
@ificator @zachzi @darrelmiller This bug is still preset and can be very easily reproduced. Did I post this into the wrong issue tracker? I would really appreciate some short feedback

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
