### ISSUE TITLE
onedrive api in localhost

### ISSUE THREAD

**Issue by svnindia** [OneDrive/onedrive-api-docs#11]
Hi,

How to test the onedrive api in localhost ?

Thanks,
SVNindia

**Comment by jsinh** [comment]
"Testing OneDrive API in localhost" - what I understand is implementing and testing Authentication / Authorization process (OAuth 2.0) offered by OneDrive API.

Here is how you can accomplish that:
In the application you created at "Microsoft Account Developer Center", go to > Edit Settings > API Settings

Any URL like `localhost` or `localhost:34342` is not allowed and gives an error on save like:
> `You must enter a valid domain that begins with http:// or https:// – query strings are not allowed. Length is limited to 248 characters.`

To overcome this issue you can add a test domain entry in your development machine's host file (Path: `C:\Windows\System32\drivers\etc\hosts`).

Example:
`127.0.0.1               localhost34342.com`
`127.0.0.1               www.localhost34342.com`

Use following URL as **Redirect URLs** : `http://localhost34342.com/redirectendpoint/` in Edit Settings > API Settings and save settings.

This will enable you to test the OneDrive API now on local host / development environment.

Hope it helps,
Jaspal

**Comment by peternied** [comment]
@svnindia Did you manage to get it working?  The OneDrive team has often used https://pages.github.com/ for quickly setting up a domain to auth against

**Comment by svnindia** [comment]
Thanks @jsinh @peternied 

Yes its working now for me. Implemented the [Single Sign On](http://svn17d33njsmmg.devcloud.acquia-sites.com/) with [Drupal](https://www.drupal.org/sandbox/svnindia/2447123) . To [Simply Test](http://simplytest.me/project/2447123)

Since I am on linux I used below steps
    `vi /etc/hosts`
added the below line
    `127.0.1.1	localhost.dev`
