### ISSUE TITLE
URL 2048 character limit is being exceeded.

### ISSUE THREAD

**Issue by BenWhite27** [OneDrive/onedrive-api-docs#1100]
"The URLs returned in the items collection may be very long (but less than the maximum URL length of 2048 characters)."  This doesn't appear to be the case, my in-production app is occasionally getting URLs that are in excess of this (2105 characters long in one instance) and is failing to call the MS Graph API with a HTTP 400 response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54125c13-f269-89ae-ca8f-b37f2b049c00
* Version Independent ID: 71319f9d-c785-ee02-de6e-718b81bea58c
* Content: [Integrate with OneDrive file handlers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online#feedback)
* Content Source: [docs/file-handlers/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by BenWhite27** [comment]
For more information I've base64 decoded the sharing token part of the items link.  I can see it's comprised of the full URL to the SharePoint item and a query string of ?tempauth=[jwt]

I'm not sure how any guarantees can be made here regarding the URL length?

I understand this repo is for the documentation only so the info below is really for any devs that might find it useful, if there's somewhere better to post it let me know.

The sharing URL I received was 2105 chacters long, the SharePoint component of the URL is 275 characters and the query string + temp auth token are 1266 characters .  I don't actually need the JWT in the URL as my app already has an auth token for the Graph API so I'm going to try stripping that out and see if that works.

**Comment by chackman** [comment]
Thanks @BenWhite27 for your feedback.  Could you help clarify what the other characters, other than "the SharePoint component of the URL is 275 characters and the query string + temp auth token are 1266 characters", were?

**Comment by BenWhite27** [comment]
Sorry @chackman I could have been clearer there.

Taking the same example I used above, The URL I get from the File Handler activation parameters is 2105 characters long and looks like this.
```
https://graph.microsoft.com/v1.0/shares/u![--long base64 encoded string--]/driveItem
```
So the technical issue with the API itself is that it can return invalid URLs, when trying to use them I get a HTTP 401 response saying the URL is invalid.

When I decided to dive into that base64 encoded string it decoded as a full SharePoint URL and a JWT payload in the following format.
```
https://[--tennant--].sharepoint.com/sites/[--site url--]/Library/Long/Path/To/File.pdf?tempauth=[--jwt payload--]
```
In my case everything up to the ? was 275 characters, and everything else was 1266 characters.

So given that there must be (I assume) a length relationship between the URL and it's base64 encoded equivalent it's not correct to say in the documentation that it will be less than 2048 characters in length.

Hope that's clearer.
Ben

**Comment by BenWhite27** [comment]
We're still running into this issue in our app, I understand this repo is for documentation so the technical issue isn't really welcome here but is there somewhere else I can post this in hopes of a fix?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
