### ISSUE TITLE
Shared key missing in the Delta API response

### ISSUE THREAD

**Issue by ashwani-1310** [OneDrive/onedrive-api-docs#1101]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

We have recently encountered this issue where in we stopped receiving this particular key called "shared" within the Delta API response.
Earlier we used to get this key "shared" in the response schema indicating that a file is shared, this key is no longer returned by the Delta API response for a shared file.

This is only happening for SharePoint's Delta endpoint. This is working fine in case of Delta endpoint for OneDrive.

Method: GET
API:  https://graph.microsoft.com/v1.0/sites/{site-id}/drive/root/delta

Earlier Response: 

{
            "@odata.type": "#microsoft.graph.driveItem",
            "createdDateTime": "2018-09-03T17:28:30Z",
            "eTag": "\"{B6733094-1855-4FE9-8EBE-EA990D12A1E3},5\"",
            "id": "01TZ6SPX4UGBZ3MVIY5FHY5PXKTEGRFIPD",
            "lastModifiedDateTime": "2018-09-03T17:28:42Z",
            "name": "105.txt",
            "webUrl": "https://sumoskope.sharepoint.com/Shared%20Documents/Folder2/F2Child1/105.txt",
            "cTag": "\"c:{B6733094-1855-4FE9-8EBE-EA990D12A1E3},2\"",
            "size": 52,
            "createdBy": {
                "user": {
                    "email": "admin@sumoskope.onmicrosoft.com",
                    "displayName": "Ravi Balupari Sumoskope"
                }
            },
            "parentReference": {
                "driveId": "b!ytJMNBfX8UiShN9HvOhi7zkgjKsxirFHirJUsCobcdjIA8J-uHpGRbBiP-fibzDF",
                "driveType": "documentLibrary",
                "id": "01TZ6SPXYOARDFDDCTBRDKHXOAJYCZKSXF",
                "path": "/drive/root:/Folder2/F2Child1"
            },
            "file": {
                "mimeType": "text/plain",
                "hashes": {
                    "quickXorHash": "vvYXpAy6eBKFCwzBnGeWgzFK4So="
                }
            },
            "fileSystemInfo": {
                "createdDateTime": "2018-09-03T17:28:30Z",
                "lastModifiedDateTime": "2018-09-03T17:28:42Z"
            },
            "shared": {
                "scope": "users"
            }
        }

#### Observed Behavior

Current Response:
{
            "@odata.type": "#microsoft.graph.driveItem",
            "createdDateTime": "2019-07-12T08:07:06Z",
            "eTag": "\"{4643FFC5-D6BD-4C8C-8FBD-EF746A19CD3D},5\"",
            "id": "01XJZVJZ6F75BUNPOWRRGI7PPPORVBTTJ5",
            "lastModifiedDateTime": "2019-07-12T08:07:35Z",
            "name": "test_file.docx",
            "webUrl": "https://apiqaskope.sharepoint.com/sites/apic_automation/_layouts/15/Doc.aspx?sourcedoc=%7B4643FFC5-D6BD-4C8C-8FBD-EF746A19CD3D%7D&file=test_file.docx&action=default&mobileredirect=true",
            "cTag": "\"c:{4643FFC5-D6BD-4C8C-8FBD-EF746A19CD3D},6\"",
            "size": 17333,
            "createdBy": {
                "user": {
                    "email": "admin@apiqaskope.onmicrosoft.com",
                    "displayName": "Nagesh Shenoy"
                }
            },
            "parentReference": {
                "driveId": "b!TVyD1-q-fEmIRVQHnV9j59BDqUSxSvlBo-8pDqUCCxVC5JvgKe6HSrhm5MpWTnT8",
                "driveType": "documentLibrary",
                "id": "01XJZVJZ56Y2GOVW7725BZO354PWSELRRZ",
                "path": "/drives/b!TVyD1-q-fEmIRVQHnV9j59BDqUSxSvlBo-8pDqUCCxVC5JvgKe6HSrhm5MpWTnT8/root:"
            },
            "file": {
                "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "hashes": {
                    "quickXorHash": "NgZmNi3gBvdYD1hkVMIjK+MeejM="
                }
            },
            "fileSystemInfo": {
                "createdDateTime": "2019-07-12T08:07:06Z",
                "lastModifiedDateTime": "2019-07-12T08:07:35Z"
            }
        }
   
As it can be seen the highlighted shared key in the earlier response is missing from the current response in case of a shared file.

Please also provide the following response headers corresponding to your request(s):
 - Date - Wed, 12 Jul 2019 09:10:00
 - request-id - db5205ea-45f1-40e6-8189-93287119f411

#### Steps to Reproduce

Make graph api call with graph token
URL: https://graph.microsoft.com/v1.0/sites/{site-id}/drive/root/delta

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.  We're looking into this issue and evaluating potential fixes.

**Comment by manojdes** [comment]
@chackman  thank you so much. This is affecting all production customers. Thank you for considering the fixes, this will help us greatly if you fixed this.

**Comment by chackman** [comment]
We have a few updates improving accuracy of the `shared` facet that we will be testing in our validation rings.  We can update on progress middle of next week (first couple of days in August).

**Comment by JeremyKelley** [comment]
A wave of improvements have gone out around this feature, please let us know if you're continuing to see issues or if things are resolved.  Thank you!

**Comment by manojdes** [comment]
@JeremyKelley @chackman We are still issues as per @ashwani-1310 . Please let us know if the fix has gone live.

**Comment by chackman** [comment]
Could you please provide more information about the issue that you are currently seeing?  (Please open a new issue if it's still reproducing.)
