### ISSUE TITLE
FileHandler not working in case of sharing links internally or externally

### ISSUE THREAD

**Issue by sumitmodi84** [OneDrive/onedrive-api-docs#1103]
FileHandler does not launch nor visible whenever a file is shared via Link. Rather default preview is launched immaterial of whether preview or open url is registered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54125c13-f269-89ae-ca8f-b37f2b049c00
* Version Independent ID: 71319f9d-c785-ee02-de6e-718b81bea58c
* Content: [Integrate with OneDrive file handlers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online#feedback)
* Content Source: [docs/file-handlers/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment]
Are you seeing this behavior in both OneDrive for Business and SharePoint document libraries?

**Comment by JeremyKelley** [comment]
Also, quick clarification, you're seeing a behavior that when a user clicks the shared link the default previewer is where the user is directed rather than opening the action associated with preview in the file handler?

**Comment by sumitmodi84** [comment]
Yes. It is visible in both one drive and SharePoint.

**Comment by sumitmodi84** [comment]
Yes. This behavior is observed when the user clicks on the shared link
immaterial of member or guest user. Also, the registered handler option is
not visible in open with....
I tried with registering open handler only as well as open and preview
handler both.
The result is same that the default preview handler window is launched. I
tired for HTML as well as abc file extension.

**Comment by arsnyder16** [comment]
@JeremyKelley @chackman 

Any update on this? This is not a very good experience when sharing files, that have custom file handlers

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
