### ISSUE TITLE
"selectionMode" and "itemMode" descriptions are swapped

### ISSUE THREAD

**Issue by bryankai** [OneDrive/onedrive-api-docs#1104]
In the documentation for the React file picker (preview) on the "Select Files" page, in the  "Advanced Configuration" table, the descriptions for the "selectionMode" and "itemMode" component props are swapped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c1cf57-06ef-8d4a-0171-9371d2d18e0e
* Version Independent ID: 034c0e36-9028-16b4-985b-6c17f3718bae
* Content: [Selecting Files with the Microsoft File Browser SDK - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/react/select-files?view=odsp-graph-online#feedback)
* Content Source: [docs/controls/file-pickers/react/select-files.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/react/select-files.md)
* Product: **onedrive**
* GitHub Login: @KevinTCoughlin
* Microsoft Alias: **keco**

**Comment by KevinTCoughlin** [comment]
Thanks for catching this @bryankai. I've raised a PR to address the above issue.
