### ISSUE TITLE
Saving Files with the OneDrive File Picker JavaScript SDK using sourceUri property

### ISSUE THREAD

**Issue by dnagasuresh** [OneDrive/onedrive-api-docs#1106]
As per the below OneDrive File Picker JavaScript SDK Saving Files document, we should send the sourceInputElementId to the request to upload the files into OneDrive. But in our scenario, the user will not select the files explicitly. The program itself will create few files and need to export them into OneDrive. In this case, we don't require File input control in the UI. What option will work for us to export the program generated files into OneDrive by using JavaScript SDK?

https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/save-file?view=odsp-graph-online

Other question is, what is the use of sourceUri property?

Please help us to fix the file upload issue asap. Thanks in advance.

We look forward to your reply.

Regards,
Naga Suresh D

**Comment by KevinTCoughlin** [comment]
> But in our scenario, the user will not select the files explicitly. The program itself will create few files and need to export them into OneDrive. In this case, we don't require File input control in the UI. What option will work for us to export the program generated files into OneDrive by using JavaScript SDK?

@dnagasuresh, have you considered using the OneDrive & SharePoint REST API?

The File Picker is primarily used in UI driven scenarios. If you are creating data programmatically to be uploaded, then it seems like an API might be better suited for that scenario.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/upload?view=odsp-graph-online

cc: @margoflynn @aditima
