### ISSUE TITLE
[ODB] how to better understand about Proxy_InternalServerError error

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1107]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hi all,

When I use this request to get the OneDrive end point from graph:
`GET graph.microsoft.com/v1.0/users/<user_id>?$select=id,mysite`

it returns this response:
```
http code : 503
err_code:(Proxy_InternalServerError), 
err_message(Failure in forwarding request.), 
err_request_id(ce1d1721-3d2a-4581-ba1d-825799641ede), 
err_date(2019-06-11T03:36:17)
```

1. It is kind of plan which do not support OneDrive service (exchange online only).
2. In other tenant case, it would return 404 instead of this message.
3. What is the proper way to handle this? (Retry will not work)

Thank you.

**Comment by chackman** [comment]
When asking Graph, it would be helpful to explain the scenario; for example, whether the user has a particular license or capability.

**Comment by joewutaiwan** [comment]
Hi @chackman ,

This plan only DO NOT have capability to access SPO and OneDrive service, it only supports Exchange Online services.

thanks!
