### ISSUE TITLE
parentReference missing in response search call

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#111]
If I search items via https://api.onedrive.com/v1.0/drive/items/{item-id}/view.search?q={query}, the items that are returned are missing the parentReference property. Is this a bug or expected behavior? I would like to know in which subfolders the items are located without getting the metadata for each file separately.

**Comment by daspek** [comment]
Thanks for the report. This looks like a bug. We're investigating.

**Comment by ificator** [comment]
Hi @The-Lion, we believe we've fixed the issue now. Can you confirm?

**Comment by The-Lion** [comment]
Perfect, works like a charm!

One other question related to the search call, is it possible to search only for filenames and not for content. If it isn't possible yet, do you have plans to add this in the future?

**Comment by rgregg** [comment]
Right now we're just passing the query along and it is matches again anything in the index. We'll look at potentially enabling filtering or another way to search just for filename only. Can you elaborate on the scenario where you'd like to search for just filenames?

**Comment by The-Lion** [comment]
Well, the real question is actually a little bit broader than I mentioned. Some clients want to search for specific attributes that are also possible with in the windows file search like: 'datemodified:', 'size:' and 'filename:'. If they want to search for a specific filename for example, they are looking for Document Project Z, but don't want to find all the documents that are referring to this project. Or they want to find all the documents that are modified last week.

I can of course just handle this within my App, but I was just wondering if such filtering is already possible via the API or if it will be added in the future.

**Comment by ificator** [comment]
To avoid morphing this issue into a new one I'm going to close it now. If you feel strongly about areas that we could improve our search API please head on over to our [user voice](https://onedrive.uservoice.com/) page and make sure your idea is covered!

**Comment by imkk** [comment]
Hello @ificator , is it normal that the returned search results miss the property "_path_" contained in property "_parentReference_"? I want to use this to present  the path of searched items.
