### ISSUE TITLE
URL upload not supported for OneDrive business

### ISSUE THREAD

**Issue by ClaroJack** [OneDrive/onedrive-api-docs#1110]
I keep receiving the 'URL upload not supported for OneDrive business' error when passing a dataUri option to OneDrive.save().

The documentation says data URI works for OneDrive business, so this error seems to counter that.

For context, I am wanting to save a .txt/.rtf file created from an online text editor to OneDrive, so I don't have access to using input type=file, I can only upload either as a URL to the .txt/.rtf file or a data URI.

**Comment by ificator** [comment]
OneDrive Business does not support the service that OneDrive Personal provides whereby you can give it an arbitrary, internet accessible, URL and it'll be downloaded to your drive. It *should*, however, support being provided with a data URI.

It may be that the picker is applying the restriction for the former on the latter.

**Comment by KevinTCoughlin** [comment]
@ClaroJack, can you provide your Picker configuration options used or better yet a repro branch for us to debug?

cc: @aditima @margoflynn

**Comment by ClaroJack** [comment]
Here is the function I am executing,

```
            OneDrive.save({
                clientId: 'MY_CLIENT_ID',
                action: 'save',
                sourceUri: 'data:' + mimeType + ';charset=utf-8;base64,' + btoa(content),
            })
```

**Comment by ClaroJack** [comment]
Has there been an update on this? I still get this error when passing a data URI in sourceUri.

**Comment by Brad-Stevens** [comment]
Clarojack - any resolution?  Seeing the same thing here...

**Comment by DPD-30** [comment]
Bump I am getting the same thing.  Data uri not web url.

**Comment by ankur99** [comment]
Even I me I m getting the same issue....found no solution anywhere

**Comment by sweetgiorni** [comment]
I was able to get around this by removing the offending API check. See my commit [here](https://github.com/sweetgiorni/onedrive-file-picker/commit/26b28bab7f9330ec9b1466658e88c7809a46e133).

This seems to work okay for me, but there's no guarantee it doesn't break other things. Obviously an official fix would be preferred here. Until then, here's the CDN URL if you want to use my fork:
`<script src="https://cdn.jsdelivr.net/gh/sweetgiorni/onedrive-file-picker@26b28ba/OneDrive.js"></script>`

**Comment by vaas-montenegro** [comment]
Any update on this? facing the same issue @msft-github-bot

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
