### ISSUE TITLE
How to get refresh token using the GraphServiceClient uaing code flow

### ISSUE THREAD

**Issue by yChakradhar** [OneDrive/onedrive-api-docs#1111]
We have a WPF application in production and want to consume the onedrive API from the application. Now we are using the C# graph SDK tp connect with onedrive and we are able to upload and download files with token-based authentication which is expiring in one hour. But we want to implement code-based authentication to get a refresh token so that when the access token expires we will get the token again using a refresh token. Please provide a way to do that so that we can proceed with other functionality. I would be very thankful if you provide a sample application 

Thanks,
Chakradhar

**Comment by ificator** [comment]
This sounds like a question better suited for the [C# Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues) GitHub page.
