### ISSUE TITLE
File Handler action to support Teams integration

### ISSUE THREAD

**Issue by arsnyder16** [OneDrive/onedrive-api-docs#1116]
Currently you can create the predefined newfile/open/preview file handlers or a custom handler. I currently  have open and preview implemented.  When i click on my custom file type in Microsoft Teams. I get the following error:
`Hmm… looks like this file doesn't have a preview we can show you.`

Is it possible to create a file handler that gives preview functionality inside Teams similar to the office products?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815ef941-29d7-1864-6be3-f533dd62da00
* Version Independent ID: 1d566c70-e679-caf2-312a-27aa5e2cc62e
* Content: [Add custom actions to files - OneDrive - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/define-actions?view=odsp-graph-online)
* Content Source: [docs/file-handlers/define-actions.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/define-actions.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment]
File Handlers on the shared control in Teams is a feature that we're looking at.  I don't have an exact date to share but it's something being worked on.

**Comment by jviney** [comment]
Any update?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
