### ISSUE TITLE
Enumerate subsites of the root site returns accessDenied

### ISSUE THREAD

**Issue by gmarland** [OneDrive/onedrive-api-docs#1117]
Using the Microsoft Graph Explorer, when I attempt to enumerate the subsites using

> https://graph.microsoft.com/v1.0/sites/root/sites

it returns

`{
    "error": {
        "code": "accessDenied",
        "message": "The caller does not have permission to perform the action.",
        "innerError": {
            "request-id": "44e8cca0-ce71-4353-a165-0daefed7aad0",
            "date": "2019-08-06T17:45:27"
        }
    }
}`

Even though I am assigned the permissions Sites.Manage.All, Sites.Read.All  and Sites.ReadWrite.All

Calling 

> https://graph.microsoft.com/v1.0/sites/root

correctly return the details of my root site.

I'm not sure why the subsites are not being returned.

**Comment by chackman** [comment]
Thanks for your feedback.  Your OAuth token is a Delegated token, which means that the application _and_ user must have permission to enumerate subsites.  While the application has permission to enumerate subsites of the root site, the user does not have permission to enumerate subsites of teh root site  Therefore, the `accessDenied` failure is expected.
