### ISSUE TITLE
ODB: API Regression for /v1.0/sites?search={query} as it now returns HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#1119]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Able to query `/v1.0/sites?search={query}` as per API spec:

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_search?view=odsp-graph-online

#### Observed Behavior

Call to API now returns HTTP/1.1 403 Forbidden

#### Steps to Reproduce

Query via MS Graph any Sharepoint Site name that you know is valid

**Example:**

```
> GET /v1.0/sites?search=od-test HTTP/1.1
User-Agent: Phobos-std.net.curl/2.085 (libcurl/7.29.0)
Host: graph.microsoft.com
Accept: */*
Authorization: bearer <redacted>

< HTTP/1.1 403 Forbidden
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json
< request-id: 400ab892-3b10-429a-ba7b-22eaa1951bb1
< client-request-id: 400ab892-3b10-429a-ba7b-22eaa1951bb1
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Australia Southeast","Slice":"SliceC","Ring":"2","ScaleUnit":"000","RoleInstance":"AGSFE_IN_3","ADSiteName":"ASE"}}
< Duration: 160.0182
< Strict-Transport-Security: max-age=31536000
< Date: Thu, 08 Aug 2019 19:55:59 GMT
< 
OneDrive HTTP Server Response: 403
* Connection #2 to host graph.microsoft.com left intact
OneDrive returned a 'HTTP 403 - Forbidden' - gracefully handling error
ERROR: Query of OneDrive for Office 365 Library Name failed
Error Message: HTTP request returned status code 403 (Forbidden)
Error Reason:  The caller does not have permission to perform the action.
```

**Comment by ificator** [comment]
The provided token only has `Files.ReadWrite` and `Files.ReadWrite.All`. Site scenarios require `Sites.ReadWrite.All` in order to function.

**Comment by abraunegg** [comment]
@ificator
Thanks - however when did this change occur as this used to work without issue?

**Comment by abraunegg** [comment]
@ificator 
Closing issue as resolved with updating scopes. It would be good to know however when this change occurred.
