### ISSUE TITLE
[Question] How to download a file with correct file name and extension?

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#112]
If I download a file via the API I do a call to `/drive/items/{item-id}/content` according to the [docs](https://github.com/OneDrive/onedrive-api-docs/blob/master/items/download.md). As I just want the user to download the file, I send the user to the `Location` header that is available in the response. However, the file that is download doesn't have the file name (+extension) of the file, but it has the name of the path that is used in the location header and no extension at all.

So I am wondering:

1. Is it possible to download a file with the correct file name and extension?
2. Is it possible to force a 'Save as' dialog (this is possible with the Live SDK by adding `?download=true` to the query)?

**Comment by ificator** [comment]
For #1 you can get the @content.downloadUrl yourself, and attach the filename to the end. E.g.
    string urlToUse = item.DownloadUrl + "/" + item.Name

I'll look at making /content redirect to a URL that has the name already appended.

For #2 I don't believe there is a way currently, but we'll look in to that as well.

**Comment by The-Lion** [comment]
Great! That works perfectly. I hope #2 will be added in the future.

**Comment by ificator** [comment]
FYI we've made a couple of changes here:
1. The URL that we return should now have the filename appended
2. We should be returning a Content-Disposition header when the download URLs are used to trigger the "save as" dialog

**Comment by The-Lion** [comment]
I am sorry for re-opening this old issue, but I am curious how #2 works as adding '?download=true' doesn't do the job and I can't find any information about it in the documentation.

**Comment by ificator** [comment]
It should now be returning the Content-Disposition header on all responses and so there shouldn't be a need to a switch like the ?download=true one that was present on Live SDK. Are you not seeing the "Save As" dialog being forced?

**Comment by The-Lion** [comment]
Hmm, I only tested it in Chrome (my mistake :) ), and apparently Chrome has a (setting)[http://stackoverflow.com/questions/8863940/how-to-force-chrome-display-a-save-as-dialog-when-i-click-a-download-link] that overrules this... I didn't know that.
