### ISSUE TITLE
/apps?forceRefresh=1 always return 500 Internal Server Error

### ISSUE THREAD

**Issue by ikrauchunas** [OneDrive/onedrive-api-docs#1120]
This query 'GET https://{tenant}-my.sharepoint.com/_api/v2.0/drive/apps?forceRefresh=1' with access token requested with appropriate permissions and 'resource=https://{tenant}-my.sharepoint.com' always return 500 Internal Server Error.

But at the same time i can get drive info with this token by calling 'GET https://{tenantName}-my.sharepoint.com/_api/v2.0/drive'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18ba6d3-b187-12d6-2e08-418b0746ac5b
* Version Independent ID: dd01f1c1-7e26-39e2-9e06-afd3305c65e7
* Content: [Reload OneDrive File Handlers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/reset-cache?view=odsp-graph-online)
* Content Source: [docs/file-handlers/reset-cache.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/reset-cache.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ikrauchunas** [comment]
Date: '08/12/2019 6:21 PM' (UTC)
request-id: 'd993f99e-d09a-0000-49aa-7193fa8aea56'
SPRequestGuid: 'd993f99e-d09a-0000-49aa-7193fa8aea56'

1. Get access token to your one drive resource (resource=https://{tenant}-my.sharepoint.com)
2. Call 'GET https://{tenant}-my.sharepoint.com/_api/v2.0/drive/apps?forceRefresh=1' with header 'Authorization: Bearer {access-token}' as described in documentation.
3. Expected result: 'This request will tell OneDrive to refresh the cache, but will return the current values from the cache' according to documentation.
4. Actual result: {"error":{"code":"generalException","message":"An unspecified error has occurred."}} with headers i provided in start of the message.

**Comment by ificator** [comment]
Looks like we already have an issue tracking this weird behavior. I'll close out this and we should use https://github.com/OneDrive/onedrive-api-docs/issues/1109 instead.
