### ISSUE TITLE
FilePicker in IOS 9.3.5 does not work.

### ISSUE THREAD

**Issue by gomartmsft** [OneDrive/onedrive-api-docs#1121]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug? Possible?

#### Expected or Desired Behavior

File Picker SDK for JavaScript - OneDrive - OneDrive dev center | Microsoft Docs
https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online
 
I have a customer that is using the OneDrive File Picker for JS.
Customer said that this does not work on IOS 9.3.5 with the latest Safari browser, or Chrome.
This works just fine on 12.4.

Question: Do you know if there is any limitation around the IOS version? Do you believe we can do something here? Maybe an ICM for a specific team or something?

#### Observed Behavior
![IMG_0089](https://user-images.githubusercontent.com/53855321/62867054-3ea78780-bd0a-11e9-9827-dfbb9c55857b.PNG)

In IOS 9.3.5 customer will get the message attached.
Customer said this worked fine up until April 2019.

#### Steps to Reproduce
Cannot reproduce as I don't have access to an IOS 9.3.5

I'll attach the Fiddler traces later.

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
