### ISSUE TITLE
downloadUrl not available when searching

### ISSUE THREAD

**Issue by filipbech** [OneDrive/onedrive-api-docs#1123]
## Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

It seems that @microsoft.graph.downloadUrl is not available from the graph **when searching**... 

Something like this only gives the name:
`https://graph.microsoft.com/v1.0/drive/root/search(q='mp4')?select=name,@microsoft.graph.downloadUrl`

whereas the desired property is available on a specific file. e.g `https://graph.microsoft.com/v1.0/drive/items/{itemID}?select=name,@microsoft.graph.downloadUrl`

**Comment by chackman** [comment]
Thanks for your feedback, the docs should be updated to make that clearer.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
