### ISSUE TITLE
How to figure out resource path?

### ISSUE THREAD

**Issue by sshresthareach** [OneDrive/onedrive-api-docs#1125]
Hi, I can't seem to figure out the resource path. I want to subscribe to a file in a subfolder and I tried several variations as follows:
1. /me/drive/root/{subfolder}/{file}
2. /drives/{drive-id}/root/{subfolder}/{file}
etc.

I either get "resource --- not supported" or bad request errors. I could not subscribe to just the subfolders either. If I use the path only till root, it seems to work. 
Is subfolder and file subscription not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0409421-4fe0-6f2b-1a68-e7bb707cb51e
* Version Independent ID: 5c43e484-ba8e-48d1-0501-c75a6d35e38c
* Content: [Create a webhook subscription - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_post_subscriptions?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/subscription_post_subscriptions.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/subscription_post_subscriptions.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by sshresthareach** [comment]
Hi,
I went back and tested different types of resources with a personal account and nothing seems to work. Below is the list of resource path format I tried. I found these paths scattered around in graph docs.

```
/drives/{drive-id}/root/{path-to-file}
/drives/{drive-id}/root/{path-to-folder}
/drives/{drive-id}/items/{item-id}
drive/items/{item-id}
me/drive/root/{path-to-file/path-to-folder}
/drive/root/{path-to-file/path-to-folder}
```

None of them work. They all return the error below:
`resource '*' is not supported.
`
The only resource route that worked is me/drive/root.

Could you please provide me with a link that shows how to give path to a resource that is not root folder?

**Comment by sshresthareach** [comment]
Hi, is this not possible at all?

**Comment by Nogginboink** [comment]
I second this. After much frustration, it appears that I can get a webhook on the root of my personal OneDrive, but not on any subfolders. This seems... less than optimal. I don't need my webhook to be called every time any item in my OneDrive changes. My webhook is hosted on Azure and that costs me money. I only want my webhook to be called when files in root/Apps/MyApp change. Is this not possible? And if it's not, is it documented?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
