### ISSUE TITLE
validationtoken should be in camelcase

### ISSUE THREAD

**Issue by sshresthareach** [OneDrive/onedrive-api-docs#1126]
validationtoken does not work but validationToken works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf7e0127-2978-8f38-8c14-1fc2057ef486
* Version Independent ID: a2a95bdb-b166-afb9-6fa3-5c9b0416c05c
* Content: [Validating webhook subscriptions - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/webhook-receiver-validation-request?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/webhook-receiver-validation-request.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/webhook-receiver-validation-request.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by jeffwidman** [comment]
See also https://github.com/OneDrive/onedrive-api-docs/issues/381

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
