### ISSUE TITLE
Search results have been changed?

### ISSUE THREAD

**Issue by DetlefJaeger** [OneDrive/onedrive-api-docs#1127]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

We have a folder structure with a reference number in brackets like [10000], [10001] , [10002], etc.

So far, the search function with my keyword [123456] found exactly the one, desired folder:
https://graph.microsoft.com/v1.0/me/drive/root/search(q='[123456]')?select=name,id,webUrl,folder

Currently the brackets are ignored and the search result also contain all files, that contains in the file name 123456.

**Comment by DetlefJaeger** [comment]
Hello,

thank you for the feedback.

Unfortunately I can't say with certainty whether previously the brackets were ignored in the search and therefore always the files were included in the search result.
In this case the folder in the search result was always included in the first child.

So far, we have always found the folder after the search with:
var children = data.children || data.value;
var folder = children [0] .name;

Maybe the order of the search result was temporarily changed?
Currently we find in the first child again the searched folder.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
