### ISSUE TITLE
Reporting several bugs in the GraphFileBrowser react component

### ISSUE THREAD

**Issue by Namhto** [OneDrive/onedrive-api-docs#1129]
Hello,

When using the GraphFileBrowser react component I noticed the following bugs:

- The `selectionMode` is always set to `multiple` even when passing a props set to `single` or `pick`

- The `itemMode` is always set to `files` even when passing a props set to `folders`

- When trying to customize the primary button, the following error occurs inside the component code: `r is not a function`

These are the props I am passing to the GrahFileBrowser component:
[Top level props](https://i.ibb.co/2sgr552/Capture-d-e-cran-2019-09-02-a-11-34-17.png)

And this is the state of the nested component I identified with the react dev tools:
[Actual state](https://i.ibb.co/bgNscXp/Capture-d-e-cran-2019-09-02-a-11-35-57.png)

It seems like the state is hardcoded and these props are doing nothing right now.

Best regards

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 89c1cf57-06ef-8d4a-0171-9371d2d18e0e
* Version Independent ID: 034c0e36-9028-16b4-985b-6c17f3718bae
* Content: [Selecting Files with the Microsoft File Browser SDK - OneDrive dev center](https://docs.microsoft.com/fr-fr/onedrive/developer/controls/file-pickers/react/select-files?view=odsp-graph-online#feedback)
* Content Source: [docs/controls/file-pickers/react/select-files.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/react/select-files.md)
* Product: **onedrive**
* GitHub Login: @KevinTCoughlin
* Microsoft Alias: **keco**

**Comment by jackow98** [comment]
Did this ever get fixed? Trying to use File Picker in-app and it is proving difficult. If not, is there an alternative to the file picker that works better?

**Comment by nousada-chetu** [comment]
any update on this or any alternative of this???

**Comment by sagar-ranglani** [comment]
Any updates?

**Comment by chandangowda** [comment]
Is this issue fixed, still I am facing the same issue

**Comment by braydonburn** [comment]
+1 currently have this problem

**Comment by michwii** [comment]
Having the same issue. Could you please solve it ?

**Comment by michwii** [comment]
Also have the same problem. Please fix it !
The ticket has been open almost 3 years ago...

**Comment by Namhto** [comment]
Guys I think this componentnis not maintained anymore. There is no point of asking again and again. What I would advice you is to write your proper component or at least reuse a file explorer react component and "populate" is with the one drive api. Good luck to everyone

**Comment by Moriquendi** [comment]
Gosh....Still not fixed ;v

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
