### ISSUE TITLE
Why the logout callback function delay 30000 ms

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#113]
I have checked the logout function, the callback function will executed after 30000 ms. I just want to make sure why we set it so long.

**Comment by rgregg** [comment]
Hi Ben, can you provide more details / information about what calls you're making?

**Comment by rgregg** [comment]
Closing due to lack of a response. Please feel free to reopen with more details.

**Comment by benjaminliugang** [comment]
Sorry, it seems I missed the comment.
I mean when I use WL.logout().then( callback ), every times the callback function will execute after 30 seconds. It's not reasonable.
