### ISSUE TITLE
Inconsistent response when using GET /drives/{drive-id}/items/{item-id}/delta of a Shared Folder

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#1131]
It appears that depending on the 'age' of a folder / shared folder, this will depend on what information is returned when using the /delta API call.

**Example 1:**
```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives('bc7d88ec1f539dcf')/items/$entity",
	"cTag": "adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMwNDkxNzUwMDAwMDAw",
	"eTag": "aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI",
	"fileSystemInfo": {
		"createdDateTime": "2019-01-14T18:54:43.266Z",
		"lastModifiedDateTime": "2019-04-24T03:47:22.53Z"
	},
	"folder": {
		"childCount": 5,
		"view": {
			"sortBy": "takenOrCreatedDateTime",
			"sortOrder": "ascending",
			"viewType": "thumbnails"
		}
	},
	"id": "BC7D88EC1F539DCF!1288",
	"name": "shared",
	"parentReference": {
		"driveId": "bc7d88ec1f539dcf",
		"driveType": "personal"
	},
	"size": 30422431
}
```

**Example 2:**
```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives('d8c0cbad315ff555')/items/$entity",
	"cTag": "adDpEOEMwQ0JBRDMxNUZGNTU1ITk0MDUuNjM3MDI4NDQ2MTg4NzcwMDAw",
	"eTag": "aRDhDMENCQUQzMTVGRjU1NSE5NDA1LjE",
	"fileSystemInfo": {
		"createdDateTime": "2017-12-11T06:31:24.02Z",
		"lastModifiedDateTime": "2018-12-30T10:14:29.566Z"
	},
	"folder": {
		"childCount": 25,
		"view": {
			"sortBy": "takenOrCreatedDateTime",
			"sortOrder": "ascending",
			"viewType": "thumbnails"
		}
	},
	"id": "D8C0CBAD315FF555!9405",
	"name": "Aquaculture",
	"parentReference": {
		"driveId": "d8c0cbad315ff555",
		"driveType": "personal",
		"id": "D8C0CBAD315FF555!9441",
		"name": "Gardening",
		"path": "/drives/d8c0cbad315ff555/items/D8C0CBAD315FF555!8769:/Gardening"
	},
	"size": 532686383
}
```

Note the difference - in the `parentReference` object, there is the follow as additional:
```
                "id": "D8C0CBAD315FF555!9441",
		"name": "Gardening",
		"path": "/drives/d8c0cbad315ff555/items/D8C0CBAD315FF555!8769:/Gardening"
```

What API response is correct - Example 1 or Example 2?

#### Category
- [X] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

The API response to be the same each and every time

#### Observed Behavior

See above - extra (or missing) data depending on what should actually be returned

#### Steps to Reproduce

Make a call similar to the following:

```
https://graph.microsoft.com/v1.0/drives/bc7d88ec1f539dcf/items/BC7D88EC1F539DCF!1288/delta?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
```

This is the call that returned example 1 above

**Comment by JeremyKelley** [comment]
A shared folder will return less information about the parent reference than an item directly in the target user's drive.  This is expected behavior for how we resolve shared items.

This is calling delta on the same user's drive in two different contexts correct?

**Comment by abraunegg** [comment]
@JeremyKelley 
> This is calling delta on the same user's drive in two different contexts correct?

No - in correct.

Same delta API call / construct, but 2 different users calling 2 totally different shared folders.

Example 1:
* User A is using shared folder from User Z
* User A = 66D53BE8A5056ECA
* User Z = BC7D88EC1F539DCF
User A is making this call for the User Z shared folder:
```  
getPathDetailsById: https://graph.microsoft.com/v1.0/drives/bc7d88ec1f539dcf/items/BC7D88EC1F539DCF!1288?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size,shared
```


Example 2: 
* User B is using shared folder from User X
* User A = B1D4FA35EF5F1F0F
* User X = D8C0CBAD315FF555
User B is making this call for the User X shared folder:
```
https://graph.microsoft.com/v1.0/drives/d8c0cbad315ff555/items/D8C0CBAD315FF555!9405?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size,shared
```

In the API response, Example 1 (based on your response) should be deemed correct, however Example 2, shows that 'additional' information is being returned - ergo - for the same API call the responses are inconsistent

**Comment by JeremyKelley** [comment]
I see, in this case it's still dependent on what actual access the user making the delta call has to the original drive.  So it really comes down to what kind of "sharing" is being done to give the remote users access to the two folders.  At the surface it sounds like they're being done differently.  If you can verify that the sharing and access for both remote users is the same for the specific drive they're accessing and it returns different results then we might have something to look into.

**Comment by abraunegg** [comment]
The sharing is being done the exact same way - all personal accounts, giving access to user using the webui then adding to onedrive account using webui

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
