### ISSUE TITLE
Upload URL  return monitor status notStarted

### ISSUE THREAD

**Issue by felipe-negri** [OneDrive/onedrive-api-docs#1133]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
I tried to test the file upload limits via URL, but now no new request returns status completed just notStarted, can I see the file list being uploaded or cancel all current uploads?

link of the monitor
https://api.onedrive.com/v1.0/monitor/4sQ7bxynoif2_FOxjzrtGWK6M6Kpieo7-2LLL8ZHw1SEcJuxa9r1LywEo17LtjTJjWPfzWSjUkxDahD6IpDHoDksvJo7FfsM8oS2LfrqsOpGR2Ez3A54JwBQiAQmXfeF6KREh-FknGieMgUzY2sqq1D8iYLlRIPM5a6ghGsviBRiN20L3oVrjHB5UzO6IsoQta

**Comment by ificator** [comment]
It looks like it did end up completing - do you have any idea how long it took to start? Does this kind of delay occur frequently for you?

**Comment by felipe-negri** [comment]
it took about two days for this request to be completed, I believe this was because the queue I just generated was 1000 requests each with a 7.7 MB image and the queue just crashed, now it is back to normal and is working normally

**Comment by ificator** [comment]
There's definitely some serialization of requests to make limit cross-app impacts, but even if each of your 1000 requests were executed sequentially I wouldn't expect a 2 day turn around time.. that's something like an overall download speed of 92KiB/s. Have you seen this kind of behavior frequently, or do you normally not generate so many download requests at any one time?

**Comment by felipe-negri** [comment]
its just for check the rate limits of the api.

**Comment by akash0905** [comment]
I am also getting same response from  (Speaker Recognition - Get Operation Status) "status": "not started"
i am not enrolling the profile I am checking the operation status, i am following this tutorial westus.dev.cognitive.microsoft.com/docs/services/… while running the code 50% of time i am getting Case 1 - not started and rest 50% of time i am getting Case 5.2.1: Identification Result. i always want Case 5.2.1 but i am not getting it. (I am using Microsoft Free Speaker API) and doing 1 API call / minute.

How to get rid of this issue

https://stackoverflow.com/questions/62521544/how-to-fix-not-started-response-in-microsoft-speaker-recognization-api
