### ISSUE TITLE
One Drive Android app Api

### ISSUE THREAD

**Issue by AlexTrotsenko** [OneDrive/onedrive-api-docs#1134]
I am not sure if it's the best place to ask for such kind of issues, but since all _...-android_ repos are _dead_ for some years already on GitHub - I don't see any better place either.

Briefly: when OneDrive app is installed it support  [ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT)  Intent ([Android Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider#flow)), but unfortunately it does **not** support [ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent.html#ACTION_CREATE_DOCUMENT) intent from the same [SAF](https://developer.android.com/guide/topics/providers/document-provider). The same time document creation is supported by old [ACTION_SEND](https://developer.android.com/reference/android/content/Intent.html#ACTION_SEND) Intent. 

Thus we can implement work-around:  1st invoke `ACTION_SEND` and latter `ACTION_OPEN_DOCUMENT`.
**But** this means _bad user experience_ for end user when interacting with _OneDrive_ comparing to doing same action with _Google Drive_ (which support both open and create intents.) As result user would need to select file twice using _OneDrive_ and only once if he use _GDrive_.

I am wondered if there is any particular reason **why** [ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent.html#ACTION_CREATE_DOCUMENT) Intent is not supported ? If it was simply **not** implemented **yet** - is there _any chance_ that it will be implemented relatively soon?

Just in case: these two "new" intents belongs to [Storage Access Framework ](https://developer.android.com/guide/topics/providers/document-provider) and it was added in Android *4.4* several years ago. Nowadays these means, that almost all devices do support these API.

Additionally now Google make using SAF API mandatory starting from [Android 10](https://developer.android.com/about/versions/10/privacy/?hl=ru). You may expect much more apps to implement interaction using these API starting from now. As result when these API will be fully supported you may expect growing number of users, which is also beneficial for OneDrive. 

Lastly, in order to emphasize how standard these Storage Access Framework API are, I will link documentation from Microsoft Office for Android: 
> **Implement a document provider**
> If you're developing an app that provides storage services for documents, you can make your files available through the SAF by writing a custom document provider. Office apps can then invoke the ACTION_OPEN_DOCUMENT and/or ACTION_CREATE_DOCUMENT intent to receive the files returned by your document provider. Note that the intent might include filters to further refine the criteria.
https://docs.microsoft.com/en-us/office/client-developer/integration/office-for-android-support-for-the-android-storage-access-framework

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please clarify whether your question which application or SDK you are talking about - the OneDrive app on Android, a particular SDK, or something else?

**Comment by AlexTrotsenko** [comment]
Hello @chackman thanks for your prompt reply. I am referring to [Microsoft OneDrive](https://play.google.com/store/apps/details?id=com.microsoft.skydrive&hl=en) Android app, which is publicly available via store.

**Comment by AlexTrotsenko** [comment]
@chackman  may I possibly ask you if you received all the required information? 
If it's the case - could you please advice when I should expect to receive feedback on this issue?

**Comment by chackman** [comment]
I'm following up with a partner team to see what the appropriate channel would be for this request.

**Comment by AlexTrotsenko** [comment]
@chackman  thanks for your help and feedback, please keep me posted.

**Comment by chackman** [comment]
This would be a feature request for the OneDrive app on Android.  The appropriate channel to make this feature request is UserVoice.

Here is a link to the "OneDrive on Android" UserVoice forum to suggest this feature: https://onedrive.uservoice.com/forums/913516

**Comment by AlexTrotsenko** [comment]
@chackman  thank you for investigation. I will report this feature request via UserVoice.

**Comment by pekspro** [comment]
I didn’t find anything about this on UserVoice, so I created this:

https://onedrive.uservoice.com/forums/913516-onedrive-on-android/suggestions/44130834-add-support-for-creating-files-via-storage-access

**Comment by bhm** [comment]
Is there any update on this.
No support for `Intent.ACTION_CREATE_DOCUMENT` is a bit perplexing.

**Comment by dkijkuit** [comment]
Four years have passed, still not implemented and Android is forcing developers to SAF now. Is this coming anytime soon? If not, I will have to recommend my users to migrate to Dropbox since they did their homework.

**Comment by dzucchetti** [comment]
I understand that this issue is closed, but I am posting about this topic because I believe many people searching for information on the internet end up on this page. 
I truly cannot comprehend why OneDrive does not fully support the Storage Access Framework (SAF).  
I assume the issue does not surface because regular Android users are not aware that apps utilize the SAF API. So, when they encounter a problem, they mistakenly assume that the app is at fault, not OneDrive.  
In fact, we continuously receive support requests from users who are experiencing issues with our app, even though the problem lies with OneDrive. 
Therefore, I have created a feature request on the support page of the Microsoft portal. 
Kindly vote for the issue.
https://feedbackportal.microsoft.com/feedback/idea/4d345f68-c5cf-ee11-92be-000d3a0e6cad

**Comment by dzucchetti** [comment]
I imagine that the decision to not fully support SAF relate to political reasons, to prevent programs from competing with Excel, Word or others. 
From a technical point of view, it is completely incomprehensible that Microsoft does not complete the Storage Access Framework (SAF) driver for Onedrive so that files can be saved and created.
