### ISSUE TITLE
List Permissions endpoint returns 400 Bad Request in some tenants

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#1135]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I expect the [list permissions](https://docs.microsoft.com/en-ca/onedrive/developer/rest-api/api/driveitem_list_permissions?view=odsp-graph-online) API endpoint to work consistently for all tenants.

#### Observed Behavior

For some tenants that we work with, the `list permissions` endpoint is returning `400 Bad Request` error for any drive items.

Request/Response:
```json
{
  "status": "fail",
  "method": "GET",
  "uri": "https://{tenant}.sharepoint.com/_api/v2.0/sites/{site}/drives/{drive}/items/01UEIXTED2RCCI3IONSRD2OGKY35W47PD2/permissions",
  "request": {
    "headers": {
      "Host": "{tenant}.sharepoint.com",
      "User-Agent": "ISV|{isv}|{app}/1.0",
      "Accept": "application/json"
    },
    "body": "",
    "body_length": 0
  },
  "response": {
    "headers": {
      "Content-Length": "63",
      "Content-Type": "application/json",
      "X-SharePointHealthScore": "3",
      "X-VroomVersion": "2.0",
      "SPRequestGuid": "88de039f-e042-9000-513e-84ec289c8818",
      "request-id": "88de039f-e042-9000-513e-84ec289c8818",
      "MS-CV": "nwPeiELgAJBRPoTsKJyIGA.0",
      "SPRequestDuration": "304",
      "SPIisLatency": "8",
      "MicrosoftSharePointTeamServices": "16.0.0.19228",
      "X-MS-InvokeApp": "1; RequireReadOnly",
      "X-MSEdge-Ref": "Ref A: FB0B262898664BB69E5C8E5F5B12897E Ref B: CH1EDGE1205 Ref C: 2019-09-13T17:46:22Z",
      "Date": "Fri, 13 Sep 2019 17:46:22 GMT"
    },
    "body": "{\"error\":{\"code\":\"invalidRequest\",\"message\":\"Invalid request\"}}",
    "body_length": "63"
  },
  "code": 400,
  "reason": "Bad Request",
  "duration": 0.4474668502807617
}
```

#### Steps to Reproduce

We have seen this behaviour on some tenants while on other tenants the endpoint still work as expected. Not sure if this is something introduced recently and is just being distributed to all farms. However, reproducing that API call (on that tenant, site, drive and item) will always result on a `400 Bad Request` error.

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.  Is this issue still reproducing?

**Comment by chackman** [comment]
We also detected an issue with a rollout that we addressed.

**Comment by dluces** [comment]
@chackman thanks for the response. I can confirm we're not seeing this behaviour on our test tenants. I'm just waiting for confirmation on our customers' tenants.

**Comment by chackman** [comment]
Thanks, please let us know if this issue was not resolved.

**Comment by dluces** [comment]
@chackman seems like this has been resolved for all our current clients as well. Closing, will re-open if I see new failures. Thanks!
