### ISSUE TITLE
File Handler icon and option not showing in Open menu or contextual menu in OneDrive or SharePoint

### ISSUE THREAD

**Issue by iamrati** [OneDrive/onedrive-api-docs#1136]
![image](https://user-images.githubusercontent.com/33255833/64907095-dd5d4480-d70b-11e9-9a85-6a101d497a68.png)
![image](https://user-images.githubusercontent.com/33255833/64907107-0087f400-d70c-11e9-890d-4b6f03b5e6e5.png)
![image](https://user-images.githubusercontent.com/33255833/64907116-201f1c80-d70c-11e9-8ce0-8a7fa38b9902.png)
![image](https://user-images.githubusercontent.com/33255833/64907124-3a58fa80-d70c-11e9-87be-0b78edc65269.png)

It does not show the file type icon or the app icon in default view, however details pane and preview pane do show the handler.
Here is my apps JSON from /_api/v2.0/drive/apps

`{"@odata.context":"https://secloresi-my.sharepoint.com/_api/v2.0/$metadata#driveApps","value":[{"@odata.type":"#oneDrive.driveApp","@odata.id":"https://secloresi-my.sharepoint.com/_api/v2.0/oneDrive.driveAppee360a15-2a7b-41b5-90a9-309a899eb36b","@odata.editLink":"oneDrive.driveAppee360a15-2a7b-41b5-90a9-309a899eb36b","application":{"id":"d1a56703-db22-4104-a26d-53fb7e5a0025","displayName":"Adobe Document Cloud"},"fileHandler":{"fileTypeDisplayName":"Adobe PDF for Office 365","fileTypeIcon":{"png1x":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/file-handler-icon.svg"},"fileTypeIconUrl":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/file-handler-icon.svg","version":2},"id":"a0345218-04d9-4e3e-8c2c-de3117f260a7"},{"@odata.type":"#oneDrive.driveApp","@odata.id":"https://secloresi-my.sharepoint.com/_api/v2.0/oneDrive.driveAppf1510c0b-682b-4af0-b397-bf48422c2198","@odata.editLink":"oneDrive.driveAppf1510c0b-682b-4af0-b397-bf48422c2198","application":{"id":"dfc90964-c451-4866-b2bf-c340ef034164","displayName":"Seclore"},"fileHandler":{"actionMenuDisplayName":"Seclore","appIcon":{"png1_5x":"https://localhost:44362/images/ic_openwith_24px.png","png1x":"https://localhost:44362/images/ic_openwith_16px.png","png2x":"https://localhost:44362/images/ic_openwith_32px.png","svg":"https://localhost:44362/images/ic_openwith_24px.svg"},"fileTypeDisplayName":"Seclore Protected File","fileTypeIcon":{"png1_5x":"https://localhost:44362/images/ic_protected_24px.png","png1x":"https://localhost:44362/images/ic_protected_16px.png","png2x":"https://localhost:44362/images/ic_protected_32px.png","svg":"https://localhost:44362/images/ic_protected_24px.svg"},"fileTypeIconUrl":"https://localhost:44362/images/ic_protected_16px.png","version":2},"id":"56d2ac82-27e0-426f-8ba3-d44fd1d59389"}]}`

@ificator

**Comment by chackman** [comment]
Thanks for your feedback.  We're taking a look.

**Comment by iamrati** [comment]
@chackman - I checked the same today and the issue seems to be fixed. However I have provided different icons for File Handler command and file type. However at both places the File Handler command icon is getting rendered.

{"actionMenuDisplayName":"Seclore","appIcon":{"png1_5x":"https://localhost:44362/images/ic_openwith_24px.png","png1x":"https://localhost:44362/images/ic_openwith_16px.png","png2x":"https://localhost:44362/images/ic_openwith_32px.png","svg":"https://localhost:44362/images/ic_openwith_24px.svg"},"fileTypeDisplayName":"Seclore Protected File","fileTypeIcon":{"png1_5x":"https://localhost:44362/images/ic_protected_24px.png","png1x":"https://localhost:44362/images/ic_protected_16px.png","png2x":"https://localhost:44362/images/ic_protected_32px.png","svg":"https://localhost:44362/images/ic_protected_24px.svg"},"fileTypeIconUrl":"https://localhost:44362/images/ic_protected_16px.png","version":2},"id":"56d2ac82-27e0-426f-8ba3-d44fd1d59389"}]}

![image](https://user-images.githubusercontent.com/33255833/65426662-4b9db780-de2e-11e9-84a3-4f1497c468fb.png)

![image](https://user-images.githubusercontent.com/33255833/65426373-c0bcbd00-de2d-11e9-8ebb-bb74143f6095.png)
![image](https://user-images.githubusercontent.com/33255833/65426424-daf69b00-de2d-11e9-9648-b780becece83.png)

Also the app name being displayed in command bar open menu and preview pane open menu is different. In command bar open menu its taking the app name from Azure AD registration.
![image](https://user-images.githubusercontent.com/33255833/65426564-11ccb100-de2e-11e9-9569-023f4c41918c.png)

![image](https://user-images.githubusercontent.com/33255833/65426606-2610ae00-de2e-11e9-8ff7-c8ecfc7a7124.png)

@chackman - Can you please let me know the complete addIns manifest schema that can be used with File Handlers?

**Comment by chackman** [comment]
[Take a look here](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/index?view=odsp-graph-online) in regards to file handler documentation; there is a link to the Graph registration process.

Apologies about the issues, I have reached out again to a partner team in regards to investigating the issue.

**Comment by iamrati** [comment]
> [Take a look here](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/index?view=odsp-graph-online) in regards to file handler documentation; there is a link to the Graph registration process.
> 
> Apologies about the issues, I have reached out again to a partner team in regards to investigating the issue.

**Comment by iamrati** [comment]
@chackman - Any updates on this issue? Its still not working as expected.

**Comment by iamrati** [comment]
@chackman Any updates on this issue? Its still not working as expected.

**Comment by chackman** [comment]
Sorry, I don't have an update to share from that partner team.

**Comment by chackman** [comment]
@iamrati  could you please let us know whether this issue is still reproducing?

If so, could you please provide us with: 
The output of this query (`{tenant}` is your ODB tenant name):
`https://{tenant}-my.sharepoint.com/_api/v2.0/drive/apps?select=*,promoted&expand=actions`

The following response headers corresponding to your request:
 - Date (in UTC, please)
 - request-id
 - SPRequestGuid (for requests made to OneDrive for Business)

Thank you.

**Comment by iamrati** [comment]
@chackman result of query https://secloredev-my.sharepoint.com/_api/v2.0/drive/apps?select=*,promoted&expand=actions

`{"@odata.context":"https://secloredev-my.sharepoint.com/_api/v2.0/$metadata#driveApps","value":[{"@odata.type":"#oneDrive.driveApp","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppecf2c33f-1a7d-433c-ba5a-68849b18e6ca","@odata.editLink":"oneDrive.driveAppecf2c33f-1a7d-433c-ba5a-68849b18e6ca","application":{"id":"5630ad59-b026-4427-b5d1-ebda1dafedba","displayName":"Seclore"},"fileHandler":{"version":2},"id":"1057e305-633e-4e18-8130-5dd6fa3bfe57","actions@odata.navigationLink":"oneDrive.driveAppecf2c33f-1a7d-433c-ba5a-68849b18e6ca/actions","actions":[{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppActionfa06e583-0c51-4734-a6dc-a9997f8ab8b6","@odata.editLink":"oneDrive.driveAppActionfa06e583-0c51-4734-a6dc-a9997f8ab8b6","availableOn":{"file":{"extensions":[".bmp",".csv",".doc",".docx",".gif",".jpeg",".jpg",".odp",".ods",".odt",".pdf",".png",".ppt",".pptx",".rtf",".tif",".tiff",".txt",".xls",".xlsx"]},"allowMultiSelect":false},"displayName":"Seclore4","type":"open","url":"https://devjava1.stringsend.com/SecloreO365Service/openfile"}]},{"@odata.type":"#oneDrive.driveApp","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveApp2f142cea-2a6a-463e-b94b-0b60b2455111","@odata.editLink":"oneDrive.driveApp2f142cea-2a6a-463e-b94b-0b60b2455111","application":{"id":"5630ad59-b026-4427-b5d1-ebda1dafedba","displayName":"Seclore"},"fileHandler":{"version":2},"id":"eb39d967-2d38-4a0b-811d-25e17c538f9b","actions@odata.navigationLink":"oneDrive.driveApp2f142cea-2a6a-463e-b94b-0b60b2455111/actions","actions":[{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppAction84ee9049-8208-4d2f-a145-1c846b926af4","@odata.editLink":"oneDrive.driveAppAction84ee9049-8208-4d2f-a145-1c846b926af4","availableOn":{"file":{"extensions":[".html"]},"allowMultiSelect":false},"displayName":"Seclore4","icon":{"png1x":"https://dzlue6m1oppe1.cloudfront.net/file-handler-icons/ic_seclore_16px.png"},"type":"open","url":"https://devjava1.stringsend.com/SecloreO365Service/openfile"}]},{"@odata.type":"#oneDrive.driveApp","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveApp2a09dd7d-1983-4f55-9708-bdc2704900b7","@odata.editLink":"oneDrive.driveApp2a09dd7d-1983-4f55-9708-bdc2704900b7","application":{"id":"d1a56703-db22-4104-a26d-53fb7e5a0025","displayName":"Adobe Document Cloud"},"fileHandler":{"fileTypeDisplayName":"Adobe PDF for Office 365","fileTypeIcon":{"png1x":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/file-handler-icon.svg"},"fileTypeIconUrl":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/file-handler-icon.svg","version":2},"id":"a0345218-04d9-4e3e-8c2c-de3117f260a7","actions@odata.navigationLink":"oneDrive.driveApp2a09dd7d-1983-4f55-9708-bdc2704900b7/actions","actions":[{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppAction438415c5-0fae-46ad-91b7-c15da8171275","@odata.editLink":"oneDrive.driveAppAction438415c5-0fae-46ad-91b7-c15da8171275","availableOn":{"file":{"extensions":[".pdf"]},"web":{},"allowMultiSelect":false},"displayName":"Open in Adobe Document Cloud","icon":{"svg":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/file-handler-icon.svg"},"type":"open","url":"https://dcsi.adobe.io/ms/filehandler/preview?stream=production&api_key=dc-prod-dcsi"},{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppAction05362d09-3817-4c1d-8efc-6c9d53fabd69","@odata.editLink":"oneDrive.driveAppAction05362d09-3817-4c1d-8efc-6c9d53fabd69","availableOn":{"file":{"extensions":[".pdf"]},"web":{},"allowMultiSelect":false},"displayName":"Organize Pages by Adobe","icon":{"png1x":"https://main.iam.ad.ext.azure.com/api/Images/Applications/RNZTGx2vC5572ojyvafnUL6JuoITftJzABJ5Tdjh9vg=.jpg?t=636452206561972792","svg":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/A12_Organize.svg"},"shortDisplayName":"Organize Pages","type":"custom","url":"https://dcsi.adobe.io/ms/filehandler/organize?stream=production&api_key=dc-prod-dcsi"},{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppActionfd3255a8-e1f8-4006-bdf8-fae43ff0c4c6","@odata.editLink":"oneDrive.driveAppActionfd3255a8-e1f8-4006-bdf8-fae43ff0c4c6","availableOn":{"file":{"extensions":[".pdf"]},"web":{},"allowMultiSelect":false},"displayName":"Export PDF by Adobe","icon":{"png1x":"https://main.iam.ad.ext.azure.com/api/Images/Applications/RNZTGx2vC5572ojyvafnUL6JuoITftJzABJ5Tdjh9vg=.jpg?t=636452206561972792","svg":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/A12_Export.svg"},"shortDisplayName":"Export PDF","type":"custom","url":"https://dcsi.adobe.io/ms/filehandler/export?stream=production&api_key=dc-prod-dcsi"},{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppActionf0fdfe50-dd3d-4449-8cfe-4741a9816e02","@odata.editLink":"oneDrive.driveAppActionf0fdfe50-dd3d-4449-8cfe-4741a9816e02","availableOn":{"file":{"extensions":[".ai",".bmp",".doc",".docx",".form",".gif",".indd",".jpeg",".jpg",".png",".ppt",".pptx",".psd",".rtf",".text",".tif",".tiff",".txt",".xls",".xlsx"]},"web":{},"allowMultiSelect":false},"displayName":"Create PDF by Adobe","icon":{"png1x":"https://main.iam.ad.ext.azure.com/api/Images/Applications/RNZTGx2vC5572ojyvafnUL6JuoITftJzABJ5Tdjh9vg=.jpg?t=636452206561972792","svg":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/A12_Create.svg"},"shortDisplayName":"Create PDF","type":"custom","url":"https://dcsi.adobe.io/ms/filehandler/create?stream=production&api_key=dc-prod-dcsi"},{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppActioncc1a466e-752b-4967-a59b-098e78252a67","@odata.editLink":"oneDrive.driveAppActioncc1a466e-752b-4967-a59b-098e78252a67","availableOn":{"file":{"extensions":[".ai",".bmp",".doc",".docx",".form",".gif",".indd",".jpeg",".jpg",".png",".ppt",".pptx",".psd",".rtf",".text",".tif",".tiff",".txt",".xls",".xlsx",".pdf"]},"web":{},"allowMultiSelect":true},"displayName":"Combine Files by Adobe","icon":{"png1x":"https://main.iam.ad.ext.azure.com/api/Images/Applications/RNZTGx2vC5572ojyvafnUL6JuoITftJzABJ5Tdjh9vg=.jpg?t=636452206561972792","svg":"https://dc.acrobat.com/spodpdfservices/filehandler-resources/A12_Combine.svg"},"shortDisplayName":"Combine Files","type":"custom","url":"https://dcsi.adobe.io/ms/filehandler/combine?stream=production&api_key=dc-prod-dcsi"}]},{"@odata.type":"#oneDrive.driveApp","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppa997f18e-2c1a-480a-8381-d90b3c5e21b8","@odata.editLink":"oneDrive.driveAppa997f18e-2c1a-480a-8381-d90b3c5e21b8","application":{},"fileHandler":{"actionMenuDisplayName":"Open in AutoCAD (web app)","appIcon":{"png1_5x":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/png/autodesk_16x1_5.png","png1x":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/png/autodesk_16x1.png","png2x":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/png/autodesk_16x2.png","svg":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/svg/autodesk_16x1.svg"},"fileTypeDisplayName":"AutoCAD (web app)","version":2},"promoted":{},"actions@odata.navigationLink":"oneDrive.driveAppa997f18e-2c1a-480a-8381-d90b3c5e21b8/actions","actions":[{"@odata.type":"#oneDrive.driveAppAction","@odata.id":"https://secloredev-my.sharepoint.com/_api/v2.0/oneDrive.driveAppAction3da115bf-44e1-4859-8e09-e786499472e2","@odata.editLink":"oneDrive.driveAppAction3da115bf-44e1-4859-8e09-e786499472e2","availableOn":{"file":{"extensions":[".dwg"]},"allowMultiSelect":false},"displayName":"AutoCAD (web app)","icon":{"png1_5x":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/png/autodesk_16x1_5.png","png1x":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/png/autodesk_16x1.png","png2x":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/png/autodesk_16x2.png","svg":"https://static2.sharepointonline.com/files/fabric/partner-assets/brand-icons/product/svg/autodesk_16x1.svg"},"shortDisplayName":"AutoCAD (web app)","type":"open","url":"https://app.autocad.com/post-forward-one-drive?stage=prod"}]}]}`

It shows the same icon in Open Menu as well as for file type even though i have supplied both which are different. It shows the appIcon everywhere.
Also the issue of preceding 'Open with' with the display name of app in SharePoint and OD Preview Pane toolbar still persists.

Let me know if you need more info.

**Comment by iamrati** [comment]
@chackman Do you have any updates regarding when it will be fixed?

**Comment by chackman** [comment]
I've asked the team working on this issue to provide an update.

**Comment by iamrati** [comment]
Hey @chackman We are experiencing the same issue again "File Handler icon and option not showing in Open menu or contextual menu in OneDrive or SharePoint".
Can you provide an update?

**Comment by iamrati** [comment]
@JeremyKelley can you help me with this.
@OneDriveAutomation

**Comment by laurensmartz** [comment]
I have the same problem, I want to know how to reslove this problem

**Comment by westleyMS** [comment]
I am seeing the same issue, the icon I use is not shown, but I get a default option instead.
I can get the file menu icons to show, just not the actual file icon picture.

**Comment by k-tsoi** [comment]
@chackman could you take a look at this

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
