### ISSUE TITLE
It seems too easy to delete a folder, by mistake

### ISSUE THREAD

**Issue by crspybits** [OneDrive/onedrive-api-docs#1137]
It seems a folder can be deleted:
a) without giving the id for that folder specifically,
b) when the folder is not empty. 
When I was developing my usage of this endpoint, I mistakenly gave the endpoint path:
"/me/drive/special/approot/items/\(itemId)"
with a DELETE REST request and that deleted my entire app folder. The itemId referred to an item in the folder, and the folder was not empty.
Thanks for your consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1972b81a-297f-08b6-274a-60ecda82a218
* Version Independent ID: f0da765f-de5f-e6a1-a17c-c02dcfabd3ae
* Content: [Delete a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delete?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_delete.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delete.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for you feedback.  This looks like an issue that we'll need to investigate.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
