### ISSUE TITLE
GET /me/drive/sharedWithMe does not return the newest result

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1138]
Reproduce:
1. account A shared a folder to account B, with POST /me/drive/items/{item-id}/invite
2. GET /me/drive/sharedWithMe
3. account A delete the shared permission.
4. GET /me/drive/sharedWithMe

I get the newest result of step 4 until about 10 minutes after step 3.
What is wrong with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1345b3aa-4bfb-8fb7-9bde-13889851819a
* Version Independent ID: 46495ed9-3ec8-8e52-4b0a-518a4918c969
* Content: [List Files Shared With Me - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_sharedwithme?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/drive_sharedwithme.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/drive_sharedwithme.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  A delay, such as 10 minutes, in the shared with me response is to be expected.  We have a backlogged item to clarify in docs.

**Comment by landall** [comment]
OK,thank you. 
Onedrive.com is blocked in China so I can only use /sharedWithMe API to confirm if my invitation makes effect or not.
