### ISSUE TITLE
EntryLocation not working or documentation incomplete

### ISSUE THREAD

**Issue by mder** [OneDrive/onedrive-api-docs#1139]
#### Category
- [ ] Question
- [x] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
The OneDrive picker should redirect users to the location specified in the sitePath/listPath/itemPath params OR it should report a meaningful error when these are being used incorrectly.

#### Observed Behavior
The OneDrive picker loads to the user's personal OneDrive rather than the specified path. No error is reported when this occurs. However, an error is reported if the specified path doesn't pass validation.

#### Steps to Reproduce

1. Create a html file with the following code:
```<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
<script type="text/javascript">
	function launchOneDrivePicker(){
		var odOptions = { 
			clientId: "<id_here>",
			openInNewWindow: true,
			action: "share",
			multiSelect: false,
			advanced: {
                navigation: {
                    entryLocation: {
                        disable: false,
                        sharePoint: {
                            sitePath: "https://<site>.sharepoint.com/teams/<site>/Shared%20Documents/",
                            listPath: "https://<site>.sharepoint.com/teams/<site>/Shared%20Documents/",
                            itemPath: "https://<site>.sharepoint.com/teams/<site>/Shared%20Documents/",
                        },
                        sourceTypes: "Sites" //or "OneDrive"
                    }
                }
			},
			success: function(files) { console.log("Success"); },
			cancel: function() { console.log("Cancel") },
			error: function(error) { console.log("Error"); }
		};
		OneDrive.open(odOptions);
	}
</script>
<button onClick="launchOneDrivePicker()">Open from OneDrive</button>
```
2. Open the web page and click the button
3. Observe that opens (after sign in) to the user's Files and not the given paths
4. Modify the code above so the paths are e.g. `listPath: "/teams/<site>/Shared%20Documents/"`
5. Reload the page and click the button
6. Observe that it reports an error: `Uncaught Error: uri /teams/<site>/Shared%20Documents/Forms/ does not match protocol(s): HTTPS`

This issue has already been reported in #862 and #1045. The modification to the paths to remove the https://<site>sharepoint.com was an attempt to follow the advice given here: https://github.com/OneDrive/onedrive-api-docs/issues/862#issuecomment-466609340

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
