### ISSUE TITLE
file without extension upload getting fail 

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#114]
trying to upload the file without extension, firstly it is getting upload but finally failing with following error

"json reply: code: pathContainsInvalidCharacters | message: Path is Invalid | innerError:    code: badArgument |  | innerError:    code: invalidPath | "

**Comment by ificator** [comment]
I don't repro this

    PUT https://api.onedrive.com/v1.0/drive/root:/foo2:/content HTTP/1.1
    Content-Type: image/jpeg
    Content-Length: 33178

    HTTP/1.1 201 Created
    Content-Length: 1295
    Content-Type: application/json; odata.metadata=minimal; odata.streaming=true

    {
      ...
      "name":"foo2",
      ...
      "file":{
        "hashes":{
          "sha1Hash":"5A4DDA15D03496240C47FEE1BA949FEADF1CFF2C"
        },"mimeType":"image/jpeg"
      },
      ...
    }

Can you show us how you're trying to upload the file? Is it possible that there's an invalid character in it's name?

**Comment by ankit-ankuagrawal** [comment]
there is no special character in the file name...
1) "hello"
2) "Getting_Things_Done_-_The_Art_Of_Stress-Free_Productivity"

**Comment by ificator** [comment]
Can you show us how you're trying to upload the files?

**Comment by ankit-ankuagrawal** [comment]
PUT /drive/items/{parent-id}/children/{filename}/content
Content-Type: text/plain

**Comment by ankit-ankuagrawal** [comment]
the uri contains "."

https://api.onedrive.com/v1.0/drive/items/root/children/Hello./content?%40name.conflictBehavior=rename
Content-Type: text/plain

**Comment by ificator** [comment]
Ah, that makes sense, thanks!

We currently do not allow file names to end with a trailing "." (nor at the beginning). I've heard people request this before, but I couldn't find anything on [uservoice](http://onedrive.uservoice.com/forums/262982-onedrive). If you feel strongly about us supporting files like that please create a new idea (or vote up an existing one if you search skills are better than mine) and we'll look into it further.

**Comment by ankit-ankuagrawal** [comment]
@ificator documentation for one drive only mention abt folder "Note: Additionally, folder names can't end with a period (.)"

can u update for files also...

can u pls elaborate wht is the use of "." at the end of the file name without extension, because it doesnt have any meaning

**Comment by ificator** [comment]
Agreed that we should be more clear about the various restrictions that exists on names and paths - I'll see what we can do on that front.

As for scenarios for ending in "." I'm not sure. Windows itself allows you to specify it but ends up removing it, and so at least from a purely Windows perspective files with a trailing . are not treated any differently to those without.
