### ISSUE TITLE
What will be returned if I add many files and delete all of it?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1140]
After I add many many(for example, 1,000,000) files to OneDrive and then delete all of it, What will be returned if I call the delta api? An emtpy set or a large set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f139d8af-bd5e-3289-daec-a101e7071fbf
* Version Independent ID: 69ddaa8b-120b-14e7-643e-dfa921d196fb
* Content: [Sync the contents of a drive - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_delta.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delta.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Delta will contain records for the deleted items.

**Comment by chackman** [comment]
Note that the standard behavior of the `delta` API would apply - delta shows the latest state of the item compared to the state of that item at the time of your token, and not a list of changes; there's a possibility of a resync error; etc.
