### ISSUE TITLE
When will the checkout lock be timeout?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1141]
If I checkout a file and forget it, what will happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e96e772-005a-c84c-41c0-3bd20f629b34
* Version Independent ID: 6b1ac10f-2d0f-0471-68c8-5f241b70592f
* Content: [Check Out Files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_checkout?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_checkout.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_checkout.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
The file will stay checked out until it is checked in.

**Comment by landall** [comment]
> The file will stay checked out until it is checked in.

if i forget to check in, then how can i find this thing? in the next checkout?

**Comment by chackman** [comment]
Are you looking for an API to find the list of checked-out files?
Explaining your scenario would help.

**Comment by landall** [comment]
Yes, I am looking for an API to find the list of checked-out files

**Comment by chackman** [comment]
Thanks.  We recommend suggesting this feature enhancement via UserVoice.  UserVoice helps us track and prioritize feedback about our features.

Here are a couple of links to the relevant UserVoice forums for OneDrive and SharePoint Development Platforms:
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.

**Comment by landall** [comment]
I have submitted it to uservoice, thank you. should i close this issue?

**Comment by chackman** [comment]
Yes, please close the issue.  Thanks!

Also here's the link to the UserVoice request for those interested: https://onedrive.uservoice.com/forums/913708-onedrive-developer-platform/suggestions/38810857-graph-api-to-list-all-checked-out-files
