### ISSUE TITLE
Should I handle Paging when I use this API?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1142]
As the title mentioned, should I handle paging in my code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7c4436-e84b-c5d0-d6c0-f89fa4087b29
* Version Independent ID: 8cc996e9-bc65-2e6a-cb2b-a74490572aad
* Content: [List versions of a file - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_versions?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_list_versions.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_list_versions.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ificator** [comment]
Any request that returns a collection of objects could potentially require paging if the data being returned becomes too large. So as a general rule I would say "yes, you application should be written to handle paging on this api".

In the case of versions that's probably a likely scenario on a heavily modified file.

**Comment by landall** [comment]
ok. thank you.
