### ISSUE TITLE
409 ETag does not match current item's value

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1143]
I upload and replace a file for 400 times but get this error during the process.
What does this mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350cd850-d19a-ef5c-2761-e342fc3c506c
* Version Independent ID: 5bf3ef39-f20a-6c7f-77f6-3bc7e9d246f4
* Content: [Upload small files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_put_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_put_content.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ificator** [comment]
Are you providing an `If-Match` header in your request?

**Comment by ificator** [comment]
Are you making the update calls in parallel, or sequentially?

**Comment by landall** [comment]
> Are you making the update calls in parallel, or sequentially?
sequentially.

for($i=0;$i<400;$i++)
	print_r($od->saveContent(new Uri('path','','abc/hi.txt'), 'hello world!!!'.date('Y-m-d H:i:s')));

just like this. and the saveContent function call POST /xxx/xx/content.

**Comment by landall** [comment]
Just run a test round. failed at the 20th loop.

{
  "error": {
    "code": "resourceModified",
    "message": "ETag does not match current item's value",
    "innerError": {
      "request-id": "0566a99e-d2a1-4e41-b030-7358250a5d7d",
      "date": "2019-09-20T09:57:26"
    }
  }
}

**Comment by ificator** [comment]
It looks like even though you're making the calls one at a time, one of the updates is racing with another change and that's causing the system to detect a conflict and fail the request. It's hard to say what is causing the other change though, but ideally your code should be resilient to conflict responses and execute appropriate resolution logic.

Such logic could look like:
1. Fetch the current state of the object
2. Merge it with the state that you want to apply
3. Write it back again

**Comment by landall** [comment]
> It looks like even though you're making the calls one at a time, one of the updates is racing with another change and that's causing the system to detect a conflict and fail the request. It's hard to say what is causing the other change though, but ideally your code should be resilient to conflict responses and execute appropriate resolution logic.
> 
> Such logic could look like:
> 
> 1. Fetch the current state of the object
> 2. Merge it with the state that you want to apply
> 3. Write it back again

I think I can treat the upload action as an asynchronous action with a little delay after the api call.
I am writing a php framework to handle ms-graph call so I want it can handle every unexpected reply.
