### ISSUE TITLE
behavior when @microsoft.graph.conflictBehavior=replace

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1144]
It is not mentioned in this document. According to my test, the api call will refresh the folder's fileSystemInfo,  not modify the id of the new folder. All files under the new folder are safe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8e0c33b-73b9-4086-4fa3-c54b701d9695
* Version Independent ID: 869bb2ba-3e32-36c9-7b4f-3875b6c5c277
* Content: [Create a new folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_post_children?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_post_children.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_post_children.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment]
Hi @landall can you give us a little more info about what call you're making with the conflict behavior specified?  It's not entirely clear from you initial question.  Thank You!

**Comment by landall** [comment]
I just suggest that it should be mentioned in the doc what will happen when the folder  already exists and even has some children.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
