### ISSUE TITLE
Get 400 Bad Request when call this api

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1146]
I get 400 Bad request nomatter I call /drive/shared or /me/drive/shared
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f46139d9-79ca-b2b6-101a-c4d9b9bc2afb
* Version Independent ID: 22a63aa2-d507-71ae-1890-b13c9fbd79d8
* Content: [List Shared Items - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_sharedbyme?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/drive_sharedbyme.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/drive_sharedbyme.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by landall** [comment]
{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'shared'.",
    "innerError": {
      "request-id": "7d349f4f-b148-47a1-9ab5-21c839e7ccd3",
      "date": "2019-09-20T11:08:34"
    }
  }
}

**Comment by ificator** [comment]
I don't believe `shared` is currently exposed via Graph. It's only present if you call the direct endpoint for OneDrive Consumer. I'm not sure if that's by-design though so I'll follow up.

**Comment by landall** [comment]
I got to this page from https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/upload?view=odsp-graph-online
I do not know what preview means in the title.

**Comment by landall** [comment]
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/release-notes?view=odsp-graph-online#shared-by-me
It is exposed by this page.

> OneDrive for Business and SharePoint
> Shared by Me is not available.

click the link, you can go to this document. but can not call it successfully.

**Comment by ificator** [comment]
Those docs used to be specific to the direct endpoint, but were converted to primarily reference Graph. It looks like that process resulted in an ambiguity. The current state of the world is:

1. `shared` works on the direct endpoint for OneDrive Consumer
2. `shared` does NOT work on either Graph or the direct endpoint for OneDrive Business

I'm going to mark this as a documentation bug.

**Comment by landall** [comment]
> Those docs used to be specific to the direct endpoint, but were converted to primarily reference Graph. It looks like that process resulted in an ambiguity. The current state of the world is:
> 
> 1. `shared` works on the direct endpoint for OneDrive Consumer
> 2. `shared` does NOT work on either Graph or the direct endpoint for OneDrive Business
> 
> I'm going to mark this as a documentation bug.

Is the endpoint of OneDrive Consumer in a format of https://api.onedrive.com/... ?

**Comment by ificator** [comment]
Correct, that's the direct endpoint for the service.

**Comment by ificator** [comment]
Closing stale issues.
