### ISSUE TITLE
Does Onedrive for Business support Add a shared folder to the user's drive?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1147]
I tried but got this response:

{
  "error": {
    "code": "invalidRequest",
    "message": "Either 'folder' or 'file' must be provided, but not both.",
    "innerError": {
      "request-id": "249b5674-8058-4865-a366-325d55aa9410",
      "date": "2019-09-20T11:14:28"
    }
  }
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18c4933a-ac05-cde1-69dc-89fa97449cb1
* Version Independent ID: a2bac76b-9541-6dfa-aea9-b76e7c7bbae2
* Content: [Accessing shared files and folders - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-sharing-links?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/using-sharing-links.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/using-sharing-links.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ificator** [comment]
We won't comment on future plans except to say that we've heard this request. I suggest you look at our [UserVoice page](https://onedrive.uservoice.com/forums/913708/) and upvote whatever ideas you find along these lines.

**Comment by landall** [comment]
I found I ask a wrong question for a syntax error.
I want to know if this feature is supported by OD4B now. I can not find any document mentions this thing.

**Comment by ificator** [comment]
You're right, there doesn't appear to be anything that clarifies this in the documentation. Current OD4B does NOT support adding shared items into a user's drive.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
