### ISSUE TITLE
How to set @microsoft.graph.conflictBehavior in this api?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1148]
I found it always replaces the exist file nomatter I add @microsoft.graph.conflictBehavior to the request body or the query string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42443681-dd86-ce0c-587f-2336f965ebaf
* Version Independent ID: abcbaeba-560b-661d-0127-5c44d9089915
* Content: [Upload from a URL - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_upload_url?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_upload_url.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_upload_url.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ificator** [comment]
You should be able to provide the annotation in the request body like you do for a session based upload

```
{
  ...
  "@microsoft.graph.conflictBehavior": "fail",
  ...
}
```

**Comment by landall** [comment]
> You should be able to provide the annotation in the request body like you do for a session based upload
> 
> ```
> {
>   ...
>   "@microsoft.graph.conflictBehavior": "fail",
>   ...
> }
> ```

that means upload from url do not support this feature?

**Comment by ificator** [comment]
It should support the feature.

All I said was the mechanism to do so was the same as what you use when you call `createUploadSession`.

**Comment by landall** [comment]
> It should support the feature.
> 
> All I said was the mechanism to do so was the same as what you use when you call `createUploadSession`.

I ran a test a minute ago but it just replaced my file, not renamed the download file.

[OneDriveBase::run]retry:0 method:POST /me/drive/root:/abc:/children
{
    "name": "hi.txt",
    "file": {},
    "@microsoft.graph.sourceUrl": "https:\/\/raw.githubusercontent.com\/landall\/pup\/master\/README.md",
    "@microsoft.graph.conflictBehavior": "rename"
}

The monitor url:
https://api.onedrive.com/v1.0/monitor/4sN76QDWXFLYK79j9FEPZ-gT_keVL4ron3Ht-baAWQDTE7UfUi0r2zZHwJTj0fsz8MeojoQ_joC1kCjERmnXkA_k_XlxYmNj12tka2_RMFsNygedFpc0m7MXVcDzCSJXs4bH6LtPEPemMH7Xwr3qJQuER8s3HdPA_JAEUv7g6_pi5McNhWXVdxqW5HqzDKYWn_

Array
(
    [operation] => downloadUrl
    [percentageComplete] => 100
    [resourceId] => 980C6E7F4AC1CD92!39449
    [status] => completed
    [statusDescription] => URL was successfully downloaded to target
)

**Comment by ificator** [comment]
It looks like we have a bug where it's not accepting the Graph instance annotation. Does it work if you provide `"@name.conflictBehavior": "rename"`?

**Comment by landall** [comment]
> @name.conflictBehavior

it do not work, also replace the old version.

I try a further test. The result is that:

- @microsoft.graph.conflictBehavior=fail,  it will return a monitor url. The url is accessible when its status is [notStarted]. then it suddenly become 404 Not Found.

- @microsoft.graph.conflictBehavior=rename, it will replace the target.

**Comment by ificator** [comment]
I had a closer look at the code and it seems like it should be doing the right thing after all. We'll need to debug further to see what's going on.

**Comment by landall** [comment]
> I had a closer look at the code and it seems like it should be doing the right thing after all. We'll need to debug further to see what's going on.

This api do not return the request id so I can commit it to you to review the log.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
