### ISSUE TITLE
Web URL is null

### ISSUE THREAD

**Issue by namiqi** [OneDrive/onedrive-api-docs#1149]
Hi,

I am using file picker to get the folder destination:

      
        
        var odOptions = {
        clientId: "My-ID",
        action: "query",
        multiSelect: true,success: function (files) { console.debug(files); },
        cancel: function () { /* cancel handler */ },
        error: function (error) { /* error handler */ }
        
    };
    OneDrive.open(odOptions);

On success, response object does not have a valid WebURL.

here is my response object:

`{webUrl: null, value: Array(1), accessToken: "eyJ0eXAiOiJKV1Q..."
apiEndpoint: "https://graph.microsoft.com/v1.0/"
value: Array(1)
0:
endpoint: "https://messageware-my.sharepoint.com/_api/v2.0"
id: "01ZRARHNIWEUQDARCYGJHLXDLQTS2J7WasQE"
parentReference: {driveId: "b!k2-bw-uKOUqrdasr_5De2ZN2LBz7xVLLFNntYe-yMgeRPxmyS3bhxVQImtrt2qET_O"}
sharePoint: {uniqueId: "30202516-5844-4e32-bb8d-709cb49fda04", listId: "{B7249BF1-1C6E-4055-89AD-AEDDAA113FCE}"}
__proto__: Object
length: 1
__proto__: Array(0)
webUrl: null
__proto__: Object`

And here is the response object from [docs](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#4-handling-the-picker-response-object).  

Let me also mention that it behaves the same for file&folder picking.

So my question is what are the potential reasons that can cause webURL to be null?

**Comment by pablolimainfo** [comment]
hello, any update?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
