### ISSUE TITLE
HTTP Status code forbidden for createUploadSession

### ISSUE THREAD

**Issue by crspybits** [OneDrive/onedrive-api-docs#1150]
If I use POST /drive/special/approot:/{filename}:/createUploadSession
without the app folder being present, I get HTTP Status code forbidden. In my case this was a new account and even the more general "Apps" folder itself was absent. 
Thanks for looking into this.
Chris.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd45832d-84c9-36e7-5c06-77eb70e1b55a
* Version Independent ID: 0ca96ced-7304-2ea0-08fa-b2a3f22afa1a
* Content: [What is an App Folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/special-folders-appfolder.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/special-folders-appfolder.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please provide the following response headers for that request:
- Date (in UTC, please)
- request-id
- SPRequestGuid (for requests made to OneDrive for Business)

**Comment by crspybits** [comment]
Well, I can't reproduce the issue now. So, I guess this ought to be closed. Thanks.
