### ISSUE TITLE
FilePicker JS opens OneDrive app

### ISSUE THREAD

**Issue by knmr** [OneDrive/onedrive-api-docs#1151]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

After calling `OneDrive.open(odOptions);` I expect to see the OneDrive Web UI. Allowing me to pick a folder.

#### Observed Behavior

The OneDrive web UI is opened and instantly the OneDrive app is opened as well. There seems to be no connection/callback between FilePicker.js and the OneDrive app. The OneDrive app doesn't show any options to picker a folder.

#### Steps to Reproduce

1. Install OneDrive app on the mobile device (Android in our case)
2. Open browser page in the phone browser. On this page the user should be able to trigger `OneDrive.open(odOptions);`
3. After `OneDrive.open(odOptions);` opens the webpage, the user is instantly redirected to the OneDrive app.

**Comment by nc-csl** [comment]
I can confirm that I experience the same issue. OneDrive.open redirects to OneDrive app (if installed), making it impossible to select a file for the webpage that was redirected from.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
