### ISSUE TITLE
What is the best way to specify fileSystemInfo.createdDateTime on Linux?

### ISSUE THREAD

**Issue by miwarin** [OneDrive/onedrive-api-docs#1152]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

[GNU stat](https://www.gnu.org/software/coreutils/manual/html_node/stat-invocation.html) has 'birth time'. but it's not standard (https://unix.stackexchange.com/a/67895)

What should I set for fileSystemInfo.createdDateTime?

**Comment by chackman** [comment]
Thanks for your feedback. Is your question in reference to this document?
  https://docs.microsoft.com/en-us/graph/api/resources/filesysteminfo?view=graph-rest-1.0

If so, the property's type is `DateTimeOffset`, so the value should satisfy that type.

**Comment by miwarin** [comment]
Hi.

Yes. I asked about the document.

It depends on the Linux design(This is also true for other UNIX operating systems):

* Linux has 'ctime'. but ctime means the date and time of the change metadata(file permission, file owner, etc...)
* Linux does not have a way to get the file creation date and time.

How do people using Linux set the createdDateTime?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
