### ISSUE TITLE
How to browse to sites in a different tenancy?

### ISSUE THREAD

**Issue by LL-chill** [OneDrive/onedrive-api-docs#1153]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behaviour

Our company (A) has a SharePoint site which has external members from another company (B). They are able to interact with our SharePoint as if they are internal members using their company (B) credentials.

Our app requires these users to use the picker to select files from our SharePoint (A), not their SharePoint (B).

#### Observed Behaviour

The OneDrive picker loads and authenticates correctly with the users' company (B) credentials. There is no way for the users to browse to our SharePoint site. The "Shared libraries" list only shows sites/libraries within the company (B) tenancy.

Workarounds such as setting the default library for the picker do not work because of bugs such as #1139  #1045  #862 

Advice on how to proceed would be greatly appreciated!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-au/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#feedback)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
