### ISSUE TITLE
sharepoint permissions not showing up in onedrive query

### ISSUE THREAD

**Issue by ryazonjr** [OneDrive/onedrive-api-docs#1156]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Sharepoint permissions not enumerated in onedrive permissions query, roles is an empty array.

#### Observed Behavior

roles for "Team Site Visitors" should have "SP.Restricted View"
https://developer.microsoft.com/en-us/graph/graph-explorer?request=drives/b!W1bOyuFaoEmGFks9GquXprP3lMF-CuhEmGjXwHY-eNIv4Wg9FavCTb7rLHLC2q0w/items/01SE2NEZLTBESGWWFITRCJ73TFV3LFQ4ML/permissions&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

![image](https://user-images.githubusercontent.com/6005611/65915436-75f8f300-e3a1-11e9-98a6-4bc69a5c1be0.png)

Here's the corresponding sharepoint permissions page:
![image](https://user-images.githubusercontent.com/6005611/65915394-6083c900-e3a1-11e9-808a-4356577d87b0.png)

Related issue #1154.
Thank you.

**Comment by JeremyKelley** [comment]
SharePoint permissions only express a limited set of roles in Microsoft Graph today, we consider this an enhancement request (a very good one).  If you could log this in [UserVoice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform) that would help us get a sense for the broad support for adding this.

Thanks for the suggestion!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
