### ISSUE TITLE
The personal onedrive 'Hashes facet' includes quickXorHash and sha1Hash.

### ISSUE THREAD

**Issue by miwarin** [OneDrive/onedrive-api-docs#1157]
#### Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

The personal onedrive 'Hashes facet' includes quickXorHash and sha1Hash.

[Remarks](https://github.com/OneDrive/onedrive-api-docs/blob/master/facets/hashes_facet.md#remarks)

> In OneDrive for Business, sha1Hash and crc32Hash are not available. In OneDrive Personal, quickXorHash is not available.

I upload file to OneDrive. The hashes included in response:

In Personal.

```
u'hashes': 
{
  u'quickXorHash': u'AAAAAAAAAAAAAAAAAAAAQAAAAAA=',
  u'sha1Hash': u'2A492F15396A6768BCBCA016993F4B4C8B0B5307'
}
```

In Business.

```
u'hashes': 
{
  u'quickXorHash': u'AAAAAAAAAAAAAAAAAC0xAQAAAAA='
}
```

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
