### ISSUE TITLE
sha256Hash is new hashes?

### ISSUE THREAD

**Issue by miwarin** [OneDrive/onedrive-api-docs#1159]
## Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

I upload file today (2019-10-07 (JST)).
`sha256Hash` is included in the upload response.
[hashes.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/hashes.md) doesn't include `sha256Hash`.

```
  "file":
  {
    "hashes":
    {
      "quickXorHash":"MbCBDmJQAwUAAAAABgAAAAAAAAA=",
      "sha1Hash":"8151459B3A925AEB86C04FDA42481042C89F4179",
      "sha256Hash":"F27D68A65BC70B066EF0569954CF2FA3ED6C18AA7F4408C3AC834A203311DFBF"
    },
    "mimeType":"application/octet-stream"
  },
```

**Comment by miwarin** [comment]
This seems to be a beta version(I found japanese page only.)

https://docs.microsoft.com/ja-jp/graph/changelog#files-onedrive-for-business-and-onedrive-personal

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
