### ISSUE TITLE
can't get nameAlreadyExists

### ISSUE THREAD

**Issue by miwarin** [OneDrive/onedrive-api-docs#1162]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I want to get `nameAlreadyExists` (error response). If file/directory already exists in onedrive.

I create new folder 'zzz' ('zzz' folder is already exists in onedrive). 
but I can't get error response.
I think that error, status-code is not 201.

How do I get back nameAlreadyExists?

## case: microsoft.graph.conflictBehavior = replace

```
code:200 
res:
{
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives('9c7f1f894e31f659')/items('9C7F1F894E31F659%21103664')/children/$entity",
  "createdDateTime":"2019-09-30T04:56:51.377Z",
  
  snip

}
```

## case: microsoft.graph.conflictBehavior = rename

```
code:200 
res:
{
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives('9c7f1f894e31f659')/items('9C7F1F894E31F659%21103664')/children/$entity",
  "createdDateTime":"2019-09-30T05:05:25.803Z",
  
  snip
  
}
```

## case: microsoft.graph.conflictBehavior = fail

```
code:200 
res:
{
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives('9c7f1f894e31f659')/items('9C7F1F894E31F659%21103664')/children/$entity",
  "createdDateTime":"2019-09-30T05:26:10.71Z",
  
  snip

}
```

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please clarify whether you are seeing this behavior _only_ when creating a folder?

**Comment by miwarin** [comment]
Hi.

> only when creating a folder?

Yes. Occurs when creating a folder.

When file upload, I use [Upload large files with an upload session](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createuploadsession.md).

An error occurred(I want this!) when `microsoft.graph.conflictBehavior = fail` was specified, Create an upload session. Otherwise(conflictBehavior=replace, rename) these were success.

microsoft.graph.conflictBehavior = fail

```python
code:409
text:{
  "error": {
    "code": "nameAlreadyExists",
    "message": "An item with the same name already exists under the parent",
    "innerError": {
      "request-id": "7b72aba1-1fcd-482b-8b2b-3a3633ec34c4",
      "date": "2019-10-09T00:24:28"
    }
  }
}
```

**Comment by chackman** [comment]
Thanks.  This would be a feature request for our backlog.

**Comment by chackman** [comment]
Linking to #1144

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
