### ISSUE TITLE
SharePoint drive delta query returns 500 - General exception while processing

### ISSUE THREAD

**Issue by nunespascal** [OneDrive/onedrive-api-docs#1163]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

Calls to drive delta-query are failing with 500 - General exception while processing.

Here is my call

```
curl -X GET \
  'https://graph.microsoft.com/v1.0/sites/{{Site-Id}}/drive/root/delta' \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer {{TOKEN}}' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: graph.microsoft.com' \
  -H 'Prefer: apiversion=2.1' \
  -H 'cache-control: no-cache'
```

I have also tried the same using the drive api. Only change there is the url

`https://graph.microsoft.com/v1.0/drives/{{drive-id}}/root/delta`

#### Expected or Desired Behavior

On the first call to delta, I should get the list of drive items.

#### Observed Behavior
I get a 500 - Internal server error
```
{
  "error": {
    "code": "generalException",
    "message": "General exception while processing",
    "innerError": {
      "request-id": "37f2d492-2952-49bf-beda-2abcd595d91d",
      "date": "2019-10-07T09:48:26"
    }
  }
}
```

#### Steps to Reproduce

Visit a drive connected to a sharepoint site and make the first call to delta on the drive root.

#### Additional information
Sending token = "latest" works and returns a valid token to get back.

When changes are made to the drive and you request for the delta by providing a valid token, again one gets the same General exception while processing, instead of drive items that have changed.

If there are no changes in the drive, you get a response with an updated token that can be used for subsequent calls.

I have tried this across two different tenants and multiple drives.

I could share the drive id, site-id and tenant id if required. But I hope those are not needed.

I can also share the request ids of subsequent calls if required. I am able to consistently reproduce this issue.

Thank you.

**Comment by nunespascal** [comment]
This seems to be the wrong place to raise this issue.

**Comment by ificator** [comment]
Remove the `Prefer: apiversion=2.1` header - it's not supported and is causing issues with your request.

**Comment by nunespascal** [comment]
@ificator Thanks! Appreciate the help.
