### ISSUE TITLE
nameConflictBehavior does not work when using sourceUri

### ISSUE THREAD

**Issue by malinkody** [OneDrive/onedrive-api-docs#1164]
The nameConflictBehavior option is ignored when using OneDrive.save({...}) with sourceUri instead of the sourceInputElementId option. A similar issue was mentioned on the thread of issue #460. 

- What can I do to handle nameConflictBehavior when using sourceUri?
- Is there a newer release than v7.2?
- Is there a source repository for the OneDrive.js?
- What other options are available to integrate OneDrive into a web application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c613df58-666d-a413-70cf-f29d0ffb27d2
* Version Independent ID: 2521214c-fd2e-27e0-03f9-e24ca0871f97
* Content: [Save to OneDrive from JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/save-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/save-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/save-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
