### ISSUE TITLE
503 error while creating upload session and uploading bytes

### ISSUE THREAD

**Issue by hustler79** [OneDrive/onedrive-api-docs#1165]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hi there,

While I am trying create upload session or uploading bytes I get 503 error. Not always but quite often.
Below response headers:

```json 
'Content-Length': '95', 
'Content-Type': 'application/json; charset=utf-8', 
'Retry-After': '30', 
'SPRequestGuid': '5c7c0c9f-208a-1000-1e8a-b526fa691616', 
'request-id': '5c7c0c9f-208a-1000-1e8a-b526fa691616', 
'Date': 'Thu, 10 Oct 2019 12:16:05 GMT'
```

Request URL:
```
https://graph.microsoft.com/v1.0/groups/GROUP_ID/drive/root:/FILE_NAME:/createUploadSession
```

What am I doing wrong? :)
Thanks

**Comment by hustler79** [comment]
Response JSON (other request):

```javascipt
{'error': 
{'code': 'serviceNotAvailable', 'message': 'Service unavailable', 
'innerError': 
{'request-id': '3fddc9bf-6c4b-4962-b1d9-723ea2b56bfa', 'date': '2019-10-10T12:47:05'}}}
```

**Comment by chackman** [comment]
There are cases in which the API can return a 503 or a 429, indicating that the API calls are being throttled by the service.  For more information about handling these responses, we recommend looking at https://aka.ms/spo429.

As there have been many issues open about throttling and guidelines, we're tracking feedback with a single issue - #853 - which links to further guidance for applications, primarily those that scan content (https://aka.ms/scanguidance), and a corresponding UserVoice request about throttling feedback.  These links and content talk primarily about SharePoint/OneDrive for Business.
