### ISSUE TITLE
Expiring check out

### ISSUE THREAD

**Issue by arsnyder16** [OneDrive/onedrive-api-docs#1168]
Is it possible to have the check out expire? For example, if i implement a file handler for a file that cannot merge concurrent changes, i will need to implicitly check out the file to avoid merge conflicts.

What happens if the session is lost before we can check the file back in? Does it stay checked out indefinitely? Is there a different strategy that should be made for file types that cannot be merged.

It would be nice if checkout allowed a duration for example `/checkout?duration=30s`  then my application can pulse the checkout endpoint every 15s

**Comment by chackman** [comment]
We recommend suggesting this feature enhancement via UserVoice.  UserVoice helps us track and prioritize feedback about our features.

Here are a couple of links to the relevant UserVoice forums for OneDrive and SharePoint Development Platforms:
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.

Also please provide a link to the UserVoice entry for anyone interested, and close this issue.  Thanks!
