### ISSUE TITLE
This doc points to deprecated portal for app registrations - apps.dev.microsoft.com

### ISSUE THREAD

**Issue by archieag** [OneDrive/onedrive-api-docs#1169]
#### Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior.
> This doc points to a deprecated portal for app registrations - apps.dev.microsoft.com. This portal is no longer available to register or manage apps for personal Microsoft accounts and will soon be sunset for all users. Please update it to point to the new experience for App registrations in the Azure portal. Refer to this doc for detailed steps: https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app

Thank you.

**Comment by chackman** [comment]
See #1158
