### ISSUE TITLE
[Question] Accessing an Item's comments

### ISSUE THREAD

**Issue by aheinrich** [OneDrive/onedrive-api-docs#117]
I was reading through the documentation for both Item and Drive resource models, but I haven't been able to find any references to accessing an individual item's "Comments"...?

It looks like that functionality is available through Live SDK API: https://msdn.microsoft.com/en-us/library/hh826524.aspx

Is this an extended attribute that I'm not seeing? Have I missed something obvious, or is this attribute not yet available?

**Comment by rgregg** [comment]
This isn't supported right now, but is coming soon (very soon).

**Comment by rgregg** [comment]
This isn't supported right now. We're adding support for "description" very soon, but it looks like you're looking for a different feature (comments), which isn't coming soon. Please add this to the [User Voice page](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) and include the scenario for how you want to use it please.

**Comment by aheinrich** [comment]
Will do, thanks
