### ISSUE TITLE
When onedrive refresh token expire? (Code flow)

### ISSUE THREAD

**Issue by TruongDuyIT** [OneDrive/onedrive-api-docs#1170]
Hi there,  
I am reading documentation about authentication for the OneDrive API using code flow.
In step 2: redeeming the access token, I sent a POST request and received a response with `refresh_token` unlike the JWT format.

My request:
`https://login.microsoftonline.com/common/oauth2/v2.0/token client_id={my-app_client_id}&grant_type=authorization_code&code={auth-code)&client_secret={my-app_secrect_id}&redirect_uri=https://my.app`

Response:
```
{
  "token_type":"bearer",
  "expires_in": 3600,
  "scope":"wl.basic onedrive.readwrite",
  "access_token":"EwCo...AA==",
  "refresh_token":"MCX9...Ug$$"
}

```
"refresh_token":"MCX9...Ug$$" <- This format is difference with document ("refresh_token":"eyJh...9323")

So i can not decode `refresh_token` to get expired time.
Please explain to me how to get expired time of `refresh_token`. Thank you!

References: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#code-flow.

**Comment by chackman** [comment]
The AAD team would have a more authoritative answer as the token is returned by AAD.
