### ISSUE TITLE
Automatic logout by calling the logout endpoint

### ISSUE THREAD

**Issue by laventy** [OneDrive/onedrive-api-docs#1171]
Hi there,

In terms of OneDrive logout documentation below:

![image](https://user-images.githubusercontent.com/18434619/67088365-b5706d80-f1f0-11e9-95ca-2cb5e7973632.png)

Now it works for me by making the browser load this URL. Basically it will show the Microsoft Logout Page and then the user needs to select the logged-in account and logout. like below

![image](https://user-images.githubusercontent.com/18434619/67089270-f49fbe00-f1f2-11e9-871d-0813410c00c4.png)

However, for logout, **is it possible to let backend or frontend call some endpoint instead of using the browser to load some URL, so that I can make the whole log-out process automated.**

I tried to send a GET request in the frontend by using the endpoint in the doc. However, after that, when redirecting the browser to the login URL again, it still used the previous account and skipped the login step.

I used the Code Flow.

Thanks so much.

**Comment by chackman** [comment]
The AAD team would be the best team to answer this question about the AAD login/logout experience.
