### ISSUE TITLE
Cannot get the DriveItem when I renamed file (PATCH)

### ISSUE THREAD

**Issue by miwarin** [OneDrive/onedrive-api-docs#1173]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hi.
I cannot get the DriveItem when I renamed file (use `PATCH`).
However, `DriveItem` can be obtained by executing `delta` after executing `PATCH`.
Is this behavior correct?

It's NG

1. PATCH
1. GET DriveItem -> NG. response is empty.

It's OK

1. PATCH
1. delta
1. GET DriveItem -> OK

# PATCH -> GET DriveItem

PATCH (`xxxxxx` is comment out)

```
response: 200: 
{
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives('xxxxxx')/items/$entity",
  "@microsoft.graph.downloadUrl":"https://2vau8w.dm.files.1drv.com/xxxxxxxx",
  "createdDateTime":"2019-10-23T01:22:10.347Z",
  "cTag":"aYzo5QzdGMUY4OTRFMzFGNjU5ITE0MjIwMy4yNTc",
  "eTag":"aOUM3RjFGODk0RTMxRjY1OSExNDIyMDMuMg",
  "id":"xxxxxx",
  "name":"bbb",    <- renamed name

  snip

}
```

I can't get DriveItem. response is empty.

```
item: {}
```

# PATCH -> delta -> GET DriveItem

PATCH

```
response: 200: 
{
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives('xxxxxx')/items/$entity",
  "@microsoft.graph.downloadUrl":"https://2vau8w.dm.files.1drv.com/xxxxxxxxxxx",
  "createdDateTime":"2019-10-23T01:27:08.787Z",
  "cTag":"aYzo5QzdGMUY4OTRFMzFGNjU5ITE0MjIwNy4yNTc",
  "eTag":"aOUM3RjFGODk0RTMxRjY1OSExNDIyMDcuMg",
  "id":"xxxxxx",
  "name":"bbb",    <- renamed name
  
  snip

}
```

delta

```
{
  "xxxxxxxx": 
  {
    "value": 
    [
      {
        "@odata.type": "#microsoft.graph.driveItem", 
        "id": "xxxxxxxxxx", 
        "name": "bbb",     <- renamed name
        "cTag": "aYzo5QzdGMUY4OTRFMzFGNjU5ITE0MzE1Ny4yNTc", 
        "eTag": "aOUM3RjFGODk0RTMxRjY1OSExNDMxNTcuMg", 
        "lastModifiedDateTime": "2019-10-23T06:43:37.19Z", 

    
    snip

}
```

DriveItem

```
item: 
{
  '@odata.type': '#microsoft.graph.driveItem', 
  'id': 'xxxxxxxxxx', 
  'name': 'bbb',    <- renamed name
  'cTag': 'aYzo5QzdGMUY4OTRFMzFGNjU5ITE0MjIwNy4yNTc', 
  'eTag': 'aOUM3RjFGODk0RTMxRjY1OSExNDIyMDcuMg', 
  'lastModifiedDateTime': '2019-10-23T01:28:09.34Z', 

  snip

}
```

**Comment by chackman** [comment]
Which API did you call to make this request?
> GET DriveItem -> NG. response is empty.
And which arguments did you provide?  ID or path?

**Comment by miwarin** [comment]
sorry. reply later.

> Which API did you call to make this request?
> 
> > GET DriveItem -> NG. response is empty.
> > And which arguments did you provide?  ID or path?

I use `GET /drives/{drive-id}/root/delta` .

(ref.  [Sync the contents of a drive - Microsoft Graph v1.0 | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http) )

**Comment by chackman** [comment]
Might be confused, but for the case that we wanted to know more about, delta isn't being called - is it?

Could you please provide more information about the driveItem call that is returning an empty result?
https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http#http-request
Did you use itemId, item-path, or something else to get the renamed driveItem's metadata?
