### ISSUE TITLE
Onedrive personal Hash changed?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1174]
I find the hashes in File facet changed recently.
Now, OneDrive Personal start to provide SHA1 and QuickXorHash without CRC32.
OneDrive for Business is still SHA1 only.
Is it true?
Will I have to change my code for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40c044a7-71d2-b1b1-d2b3-9d014888a09e
* Version Independent ID: 08abe874-0f62-dfc9-303d-8048d5fc9b65
* Content: [OneDrive API release notes - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/release-notes?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/release-notes.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/release-notes.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
ODB should have `quickXorHash`, not the other two, per that document

Could you please clarify for OneDrive Personal whether the CRC32 hash was previously always returned? Note that per the documentation here
    https://docs.microsoft.com/en-us/graph/api/resources/hashes?view=graph-rest-1.0
hashes may not always be immediately available.

**Comment by landall** [comment]
i have always seen crc32 before. but never seen quickxorhash for personal account.
is it a new feature for personal account?

**Comment by chackman** [comment]
Thanks, we'll follow up with a partner team about this issue.

**Comment by landall** [comment]
Further Hint:
Most of files in my onedrive personal contains QuickXorHash, but a small part of them not contain QuickXorHash.

**Comment by chackman** [comment]
We'll re-ping the partner team about this.  Are the files without QuickXorHash files that have not changed recently?

**Comment by landall** [comment]
> We'll re-ping the partner team about this. Are the files without QuickXorHash files that have not changed recently?

yes but I have not checked all the files because it is too slow to list the whole file tree.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
