### ISSUE TITLE
Graph /beta/sites?filter=siteCollection/root%20ne%20null&select=webUrl,siteCollection responding with 400

### ISSUE THREAD

**Issue by yuvarajp1515** [OneDrive/onedrive-api-docs#1175]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Used API:
With reference to https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery

https://graph.microsoft.com/beta/sites?filter=siteCollection/root%20ne%20null&select=webUrl,siteCollection

#### Expected or Desired Behavior
With response code 200 (for valid account) and the response of geo-location information

#### Observed Behavior
Returning 400 bad request.
![Screenshot from 2019-10-24 16-07-50](https://user-images.githubusercontent.com/37432927/67478436-b2a2cc00-f679-11e9-98cf-ed182642ebdf.png)

With headers:
Authorization:Bearer <token>

client-request-id →320a5a33-6ebf-466e-8501-1102446dd2c0
content-length →222
content-type →application/json
date →Thu, 24 Oct 2019 10:26:41 GMT
request-id →320a5a33-6ebf-466e-8501-1102446dd2c0

#### Steps to Reproduce
Executed `https://graph.microsoft.com/beta/sites?filter=siteCollection/root%20ne%20null&select=webUrl,siteCollection` with headers

**Comment by manojdes** [comment]
@chackman  can u please take a look , as this is urgent and needs attention and affects critical customers.

**Comment by chackman** [comment]
This was a regression, we reverted the change and the API should be restored.
