### ISSUE TITLE
Please add this API to Microsoft Graph API documentation.

### ISSUE THREAD

**Issue by aaronmi** [OneDrive/onedrive-api-docs#1176]
This API is actually part of Microsoft Graph API as well. Please add this API to Microsoft Graph API documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d2ed0c6-4c40-5d52-51b9-679aed8df5d8
* Version Independent ID: 3b0f9af8-8de0-b7e7-89d6-cc150665ede4
* Content: [Enumerate sites - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_list?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/site_list.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/site_list.md)
* Product: **onedrive**
* GitHub Login: @daspek

**Comment by chackman** [comment]
This is on our backlog.

**Comment by chackman** [comment]
Documentation for Graph is in beta: https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http

**Comment by jenniferlwilson** [comment]
> This API is actually part of Microsoft Graph API as well. Please add this API to Microsoft Graph API documentation.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 5d2ed0c6-4c40-5d52-51b9-679aed8df5d8
> * Version Independent ID: 3b0f9af8-8de0-b7e7-89d6-cc150665ede4
> * Content: [Enumerate sites - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_list?view=odsp-graph-online#feedback)
> * Content Source: [docs/rest-api/api/site_list.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/site_list.md)
> * Product: **onedrive**
> * GitHub Login: @daspek

none

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
