### ISSUE TITLE
OneDrive.open action "download" fails, "query" works until I request file information

### ISSUE THREAD

**Issue by ghedwards** [OneDrive/onedrive-api-docs#1179]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug
![image](https://user-images.githubusercontent.com/125586/67909573-67357400-fbcb-11e9-9b4b-e045d04ce9fd.png)

OneDrive.open action "download" is failing with the error attached, "query" works until I request file information.

**Comment by chackman** [comment]
It would also be helpful to know whether there even is a request made to the service.
Also when you say "query" works until I request file information - is "query" broken afterwards?  And does "download" work after requesting file information?

**Comment by ghedwards** [comment]
This wasn't working on my local configuration but is working on our test server, so we've closed our ticket, I don't really have time to find out why my local instance wasn't working. Noted: errorCode: "badResponse" wasn't listed in the possible error responses in your documentation.
