### ISSUE TITLE
folder creation getting failed if drive has already same file name with out extension 

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#118]
If drive contain the file without extension lets say "Hello", and when creating the folder with the same name "Hello" it is getting failed. Can anyone comment on this behaviour

**Comment by daspek** [comment]
Hi Ankit,
OneDrive respects file system semantics, where no two children under a single folder can have the same name. A path /foo/bar/baz must point to exactly one item. If it were possible have both a 'baz' folder and a 'baz' file under 'bar' then we wouldn't know which one you were trying to access.
