### ISSUE TITLE
How to show more navigation locations

### ISSUE THREAD

**Issue by arsnyder16** [OneDrive/onedrive-api-docs#1180]
When using the regular one drive UI I can see the following navigation folder on the left pane:
![image](https://user-images.githubusercontent.com/6554919/68303061-1c0add80-0071-11ea-8a7c-1f6718819e2c.png)

How do i get these same locations to show up in the file pickers? All i am able to get is the "Files" navigation.

Is these even available? Based on the documentation there seems to be settings for this under "advanced/navigation", but there are no concrete examples that i can find. I tried some of the items mentioned in the docs but to no avail. 
```JSON
advanced: {
    navigation: {
       sourceTypes: [`OneDrive`, `Recent`, `Shared`, `Sites`]
    }
}
```
The critical one for our users is the `Shared` item. Without this navigation the picker is not nearly as useful 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by paella55** [comment]
I am using OneDrive for business and `sourceTypes` seem to change absolutely nothing. I still see the same things.

Using:

```JavaScript
navigation: {
      sourceTypes: ["OneDrive", "Recent", "Sites", "Shared"],
}
```
Does not change the default view:

![image](https://user-images.githubusercontent.com/28304354/115385643-a77e1d00-a1d8-11eb-9d29-1dafea63e10d.png)

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
