### ISSUE TITLE
Use of $expand appears to not be supported

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-api-docs#1181]
This page suggests that $expand can be used, but when doing a simple expand (e.g. below), the request returns a 400 with the error "One of the provided arguments is not acceptable."

https://graph.microsoft.com/v1.0/me/drive/root/delta?$select=id,name,listItem&$expand=listItem

A similar API call on children works fine, but we require the listItem metadata on deltas. Is this possible?

https://graph.microsoft.com/v1.0/me/drive/root/children?$select=id,name,listItem&$expand=listItem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f139d8af-bd5e-3289-daec-a101e7071fbf
* Version Independent ID: 69ddaa8b-120b-14e7-643e-dfa921d196fb
* Content: [Sync the contents of a drive - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_delta.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delta.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.
Unfortunately the delta API does not support expanding the `listItem` relationship.  I'll tag this for us to clarify in our docs.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
