### ISSUE TITLE
ETag does not match current item's value

### ISSUE THREAD

**Issue by apogoreliy** [OneDrive/onedrive-api-docs#1182]
I try to upload a large file. But i get an error - 412 after uploading. 
Error message is "ETag does not match current item's value"

Could please someone help me with this issue?!

First, i create an upload session using - /me/drive/items/{path}:/{to}:/createUploadSession
And post it to https://graph.microsoft.com/v1.0.
After a success request i receive an upload url as a response. 

Second, using an upload url i try to put a file to a OneDrive storage.
Place "Content-Length", "Content-Range" with values to a request's header and send it with a file data to upload url. After a success request i receive an drive item info with details.

Problem begins here. 
First of all i can not get files from a storage.
Second, i saw in an original documentation that i need to commit an upload session. So i tried to do this. I took a received eTag an put it in "If-Match" field in headers. Also i use upload url to send it in "@microsoft.graph.sourceUrl" param. And when i put it to OneDrive server i receive an error 412 with a message "ETag does not match current item's value". I can't understand what is wrong.

When i look into OneDrive storage, file is present and it seems everything is correct.

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please clarify a few things?

- Which doc page you were using to help guide you through the scenario?
For example, was it this one - "Resumable file upload"
   https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
or another document, blog post, or something else?
- On which request(s) did you provide the `If-Match` header?
- For the requests that failed could you please provide more information about the requests, including headers, sample URL's, etc.:
> If you have not provided the following information, could you please provide the following?
>
>Could you please provide the following response headers:
>- Date (in UTC, please)
>- request-id
>- SPRequestGuid (for requests made to OneDrive for Business)
>
> Please provide as recent values as possible.
>
>Could you please provide sample requests and responses that illustrate the issue that you are encountering?

**Comment by apogoreliy** [comment]
Thank you for a response, Chris!

1. Yes, it was ["Resumable file upload"](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online) page.

2. A request - "https://graph.microsoft.com/v1.0/me/drive/root:/test/test_file.zip"

But actually it seems i was not clear regarding committing an upload session. Probably i should not make this kind of request because my previous request was success.

My real problem is that i can not get a list of files after uploading.

**Comment by chackman** [comment]
Correct, if the entire content of the file has been uploaded, the [commit is implicit](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#completing-a-file).

Also, the `driveItem` for the newly-completed file should be returned by the API.
Would that meet the needs of your scenario?

**Comment by apogoreliy** [comment]
Sorry for a delay, but my problem is still not fixed. That is true, after an uploading of the last portion of a file i receive `driveItem`.

But after that i can not make any request to a OneDrive storage, a request is stuck.

In another part of my code i need to verify if a file was uploaded to a storage. I use this kind of a request - GET /me/drive/root:/{file_name} . And nothing happens.  Would you please explain me what happens after an uploading of the last portion of a file?

**Comment by chackman** [comment]
Could you please explain what requests do not work?
> But after that i can not make any request to a OneDrive storage, a request is stuck.

When the last byte range of a file is received, assuming no conflicts such as a file name conflict, the server should respond with the `driveItem` object corresponding to the file that has completed uploading.

**Comment by apogoreliy** [comment]
It seems, the issue fixed
