### ISSUE TITLE
Embedding of Word and Excel Previews fails.

### ISSUE THREAD

**Issue by patrickheinzelmann** [OneDrive/onedrive-api-docs#1183]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I can embed the preview of a files stored in Onedrive into an external website.

#### Observed Behavior

The preview doesn't work for Word and Excel, while Powerpoint, PDF and images work fine!

**Word:**

The browser calls multiple times following url:
https://euc-word-view.officeapps.live.com/wv/ResReader.ashx?...

And service is always throwing a 404 exception:

`<h2>404 - File or directory not found.</h2>
<h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>`

After a view minutes the iFrame shows following error message.

![onedrive-preview-error-word](https://user-images.githubusercontent.com/578630/68536377-320aed80-0352-11ea-9162-59e0fe2400bd.png)

**Excel:**

I can see some timeouts during the loading thrown in the javascript file embed-mini-c903f097.js

Console output:
embed-mini-c903f097.js:1 Promise with no error callback:5

The loading stuck in the view with the Excel logo.

![onedrive-preview-error-excel](https://user-images.githubusercontent.com/578630/68536380-3fc07300-0352-11ea-9886-ef6782edd4c6.png)

#### Steps to Reproduce

Load the preview information via REST API.

Extract the value of the parameter "getUrl" of the response and use the value to load the preview via iFrame .

<iframe width="100%" height="600" src="{getUrl}" frameborder="0" allowfullscreen=""></iframe>

Thank you.

**Comment by JeremyKelley** [comment]
Hi @patrickheinzelmann what API are you using to get the embeddable preview?

Additionally when you say you're embedding in an external site can you explain further what you're attempting to do?  Is this a OneDrive for Business scenario or OneDrive consumer?

**Comment by patrickheinzelmann** [comment]
We've build an integration of SharePoint for Content Management System.

You can see the integration and preview here in action:
https://youtu.be/ovrEEobxLsE?t=25

We're using the Graph API with the OneDrive for Business / SharePoint Online.

https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0

**Comment by JeremyKelley** [comment]
Hi Patrick, we're still looking at this issue. I don't have an update at the moment but I didn't want you to think we forgot about it.

**Comment by marisa-barradas** [comment]
Hi, any news about this issue? I'm having the exact same problem, trying to preview a document using the link provided by Microsoft Graph API: https://graph.microsoft.com/v1.0/drives/{drive-id}/items/{driveItem-id}/microsoft.graph.preview

After using the result URL, I'm getting the error "Can't contact server" even though the document preview appears for a minute, and then presents a error message like the one above suggesting edition on desktop app.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
