### ISSUE TITLE
Types not representing LastModifiedBy correctly

### ISSUE THREAD

**Issue by weshackett** [OneDrive/onedrive-api-docs#1184]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X ] Bug

#### Expected or Desired Behavior

calling:
 
https://graph.microsoft.com/v1.0/me/drive/recent?select=weburl,name,lastModifiedDateTime,lastModifiedBy,remoteItem
 
Within the object returned:
 
 "lastModifiedBy": {
                    "user": {
                        "email": "wes@dev111.addin365.com",
                        "displayName": "Wes Hackett"
                    }
                },
 
In the SPFx solution
 

"devDependencies": {
    "@microsoft/microsoft-graph-types": "1.12.0",
 
But then the Typescript is failing as the Identity interface doesn't match the returned outputs
 
The type is:
 

export interface Identity {
    /**
     * The identity's display name. Note that this may not always be available or up to date. For example, if a user changes
     * their display name, the API may show the new value in a future response, but the items associated with the user won't
     * show up as having changed when using delta.
     */
    displayName?: string;
    // Unique identifier for the identity.
    id?: string;
}
// tslint:disable-next-line: interface-name
export interface IdentitySet {
    // Optional. The application associated with this action.
    application?: Identity;
    // Optional. The device associated with this action.
    device?: Identity;
    // Optional. The user associated with this action.
    user?: Identity;
}

 
So it lacks the email which is returned.

**Comment by JeremyKelley** [comment]
It looks like the issue is that the Identity type is an Open Complex type, the question is how this should be treated by the type generator, since it seems to be valid that we return additional information.  We will talk to the Microsoft Graph team about this to see what the proper resolution is.

**Comment by weshackett** [comment]
@JeremyKelley is this closed and resolved? or did the bot just get a bit keen.....?
