### ISSUE TITLE
More sites link does not work in v7.2

### ISSUE THREAD

**Issue by pallavs** [OneDrive/onedrive-api-docs#1185]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug 

#### Expected or Desired Behavior
"more sites" link should work and allow us to browse through SharePoint sites across tenancy. There should be option to search sites too.

#### Observed Behavior

I have implemented File picker V.2 in our application. I have setup the root SharePoint site and opens well. It shows the list of sites on the left navigation pane and has small text link at the bottom which says "more sites". "more sites " ink does not work at all. We can not really see all the list of sites or browse through other than the 8 sites which are listed.

#### Steps to Reproduce
Try loading i chrome with the below options:
function launchOneDrivePicker(txtTemplateUrl, isDestination) {
        loader.show();
        var spURl = "";/*Sharepoint url*/        
        var spToken = "";/*access token*/
        var odOptions = {
            clientId: "APP CLIENT ID",
         viewType: 'all',
            action: "query",
            multiSelect: false,
            accountSwitchEnabled: false,
            advanced: {                
                endpointHint: spURl,
                accessToken: spToken,
                navigation: {
                    sourceTypes: ["onedrive", "sites","recent","shared"], 
                }
            },
            success: function (files) {               
              /*success handle*/
            },
            cancel: function () { /* cancel handler */ },
            error: function (error) { /* error handler */ }
        }
        
        OneDrive.open(odOptions);
        
    }

![onedrive](https://user-images.githubusercontent.com/20644215/68902484-72a5a500-075e-11ea-938c-055f77ca5f0b.png)

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
