### ISSUE TITLE
Create upload session error

### ISSUE THREAD

**Issue by pahmtrugno** [OneDrive/onedrive-api-docs#1187]
** Below is my code and result i received
![image](https://user-images.githubusercontent.com/57932903/69122292-0960c180-0ad1-11ea-90d5-4b3a6cd1d416.png)

![image](https://user-images.githubusercontent.com/57932903/69122506-9c99f700-0ad1-11ea-8b8a-a207604198fd.png)

Please help me handle this error

**Comment by chackman** [comment]
Given the error message, the content-type on the request appears to be wrong.  What content-type is provided in the request?
Could you also provide more information about the client libraries that you are using to access Microsoft Graph?  For example if you are using the Microsoft Graph SDK, what version are you using?
