### ISSUE TITLE
Graph API responding with incorrect lastModifiedDateTime

### ISSUE THREAD

**Issue by yuvarajp1515** [OneDrive/onedrive-api-docs#1188]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

API used: `https://graph.microsoft.com/v1.0/drives/b&#33;ksqe_3QdF0CrNAygN7ANHSf6wBGhtH9BhKAL-PVxPM_oe1gchO5JQrONW6uZPkrU/root/search(q='{Horses Group Gallop 01.wav}')
`

Response:
`{ "_id" : "9e9caf15-c3f5-495e-b272-f881fac87cc8", "access_method" : [ "API Connector" ], "app" : "Microsoft Office 365 OneDrive for Business", "appname" : "onedrive", "createdDate" : 1227222019, "domain_shared_with" : [ ], "driveId" : "b!ksqe_3QdF0CrNAygN7ANHSf6wBGhtH9BhKAL-PVxPM_oe1gchO5JQrONW6uZPkrU", "filePath" : [ "/drive/root:/desktop_hasado/sound_efx/Sony loops/Animals/Horses Group Gallop 01.wav" ], "fileSize" : 1240492, "fileType" : "Other", "graphId" : "014GTNG4QVV6OJ55ODLZE3E4XYQH5MQ7GI", "instance" : "ifsalpha", "introspection_saas_id" : "9e9caf15-c3f5-495e-b272-f881fac87cc8", "itemId" : "5628", "links" : 0, "listId" : "1c587be8-ee84-4249-b38d-5bab993e4ad4", "lut" : 1573737283, "method" : "hoard", "mimeType" : "audio/wav", "modifiedDate" : 2147483647, "obj_status" : "active", "parentId" : "014GTNG4RNTFKIVTTVKRFLTXVB4P4RRCLT", "pathId" : "9e9caf15-c3f5-495e-b272-f881fac87cc8", "public" : [ ], "shared" : [ ], "sharedType" : "private", "tenantid" : "8054", "title" : "Horses Group Gallop 01.wav", "uid" : "hasado.barkhou@ifsalpha.com", "user" : "hasado.barkhou@ifsalpha.com", "web_url" : "https://ifsalpha-my.sharepoint.com/personal/hasado_barkhou_ifsalpha_com/Documents/desktop_hasado/sound_efx/Sony%20loops/Animals/Horses%20Group%20Gallop%2001.wav" }`

#### Expected or Desired Behavior
The API Should respond with valid lastModifiedDateTime

#### Observed Behavior
The API is responding with invalid lastModifiedDateTime, which is pointing to 2038

*date →*Thu, 14 Nov 2019 14:47:35 GMT

*request-id →*427af182-cade-4501-88d3-2c9c82f3fd9b

*client-request-id →*427af182-cade-4501-88d3-2c9c82f3fd9b

#### Steps to Reproduce
Use the above API to get a response.

Thank you.

**Comment by chackman** [comment]
Could you please provide the raw response from the API to make sure there isn't a serialization/deserialization issue?

**Comment by yuvarajp1515** [comment]
> Could you please provide the raw response from the API to make sure there isn't a serialization/deserialization issue?

@chackman  Following the json response from the API ( Added in the description)
`{ "_id" : "9e9caf15-c3f5-495e-b272-f881fac87cc8", "access_method" : [ "API Connector" ], "app" : "Microsoft Office 365 OneDrive for Business", "appname" : "onedrive", "createdDate" : 1227222019, "domain_shared_with" : [ ], "driveId" : "b!ksqe_3QdF0CrNAygN7ANHSf6wBGhtH9BhKAL-PVxPM_oe1gchO5JQrONW6uZPkrU", "filePath" : [ "/drive/root:/desktop_hasado/sound_efx/Sony loops/Animals/Horses Group Gallop 01.wav" ], "fileSize" : 1240492, "fileType" : "Other", "graphId" : "014GTNG4QVV6OJ55ODLZE3E4XYQH5MQ7GI", "instance" : "ifsalpha", "introspection_saas_id" : "9e9caf15-c3f5-495e-b272-f881fac87cc8", "itemId" : "5628", "links" : 0, "listId" : "1c587be8-ee84-4249-b38d-5bab993e4ad4", "lut" : 1573737283, "method" : "hoard", "mimeType" : "audio/wav", "modifiedDate" : 2147483647, "obj_status" : "active", "parentId" : "014GTNG4RNTFKIVTTVKRFLTXVB4P4RRCLT", "pathId" : "9e9caf15-c3f5-495e-b272-f881fac87cc8", "public" : [ ], "shared" : [ ], "sharedType" : "private", "tenantid" : "8054", "title" : "Horses Group Gallop 01.wav", "uid" : "hasado.barkhou@ifsalpha.com", "user" : "hasado.barkhou@ifsalpha.com", "web_url" : "https://ifsalpha-my.sharepoint.com/personal/hasado_barkhou_ifsalpha_com/Documents/desktop_hasado/sound_efx/Sony%20loops/Animals/Horses%20Group%20Gallop%2001.wav" }`

**Comment by yuvarajp1515** [comment]
@chackman Any update on this ticket?

**Comment by chackman** [comment]
The JSON does not look like an API response from Microsoft Graph; could you please provide more information about the Microsoft Graph response that has an incorrect date/time value?
