### ISSUE TITLE
Custom file type icon is not correctly resized in "Tiles" view option

### ISSUE THREAD

**Issue by nikitamovs** [OneDrive/onedrive-api-docs#1189]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I have registered the following file handler:
```
{
  "version": "2",
  "fileTypeIcon": {
    "png1x": "https://localhost:3000/ball.png"
  },
  "actions": [
    {
      "type": "open",
      "url": "https://localhost:3000/open",
      "availableOn": {
        "file": { "extensions":  ["*.ball"] },
        "web": {}
      }
    }
  ]
}
```
When I list the files with the `.ball` extension in OneDrive folder using the `Tiles` view option I am expecting that the icon image is correctly resized in order to fill completely the region of the tile.

#### Observed Behavior

The custom icon is not resized as expected:
![ball](https://user-images.githubusercontent.com/12925985/69245757-b86fcc80-0ba7-11ea-9586-fed51fb5944e.png)
I've also tried adding the `png1.5x` and `png2x` keys to the `fileTypeIcon` configuration but the behavior didn't changed.

#### Steps to Reproduce

1. Register the above file handler to a specific app registration.
2. Enable the app on a OneDrive for Business account.
3. Go to OneDrive on cloud and open a folder containing the files with the `.ball` extension.
4. Switch the view option to `Tiles`.

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
