### ISSUE TITLE
[ODB] resume upload fail to upload exist onenote files

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1191]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

When I use create session to upload onenote file like:

- Open Notebook.onetoc2
- s2.one

it responded:
```
Cache-Control: no-cache
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Date: Thu, 21 Nov 2019 02:52:14 GMT
Expires: -1
HTTP/1.1 500 Internal Server Error
MS-CV: nxngy2DgAKDID78/l11NhA.0
MicrosoftSharePointTeamServices: 16.0.0.19506
ODATA-VERSION: 4.0
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Pragma: no-cache
SPClientServiceRequestDuration: 406
SPRequestGuid: cbe0199f-e060-a000-c80f-bf3f975d4d84
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
X-AspNet-Version: 4.0.30319
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: 5C305FFB91A54ADB95A0C5BCE6BCEB64 Ref B: HK2EDGE1122 Ref C: 2019-11-21T02:52:14Z
X-Powered-By: ASP.NET
X-SP-SERVERSTATE: ReadOnly=0
X-SharePointHealthScore: 6
request-id: cbe0199f-e060-a000-c80f-bf3f975d4d84

  body :{"error":{"code":"generalException","message":"An unspecified error has occurred."}}
  http_code :500

```

But these files work fine with simple upload API, and both resume upload and simple upload APIs work properly in ODP.

Thank you.

**Comment by ificator** [comment]
It sounds like a fix for this is already working its way through the deployment pipeline. I'll update this issue once it's completed.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
