### ISSUE TITLE
[ODP] fail to download onenote file temporarily - http code 503

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1192]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

1. Open a onenote file on OneDrive for Personal
2. Update its section name to "new section rename"
3. Download this *.one file
4. it keeps returning http code 503 and fail to download
5. After at least 30 mins, this *.one file could be downloaded properly.

Is it a problem on server side? or it is by design?

Thank you.

**Comment by JeremyKelley** [comment]
A 503 response indicates that the server was under load and is a valid throttle response that your app should be prepared to handle.  For more information about throttling please see [https://aka.ms/spo429](https://aka.ms/spo429).
