### ISSUE TITLE
The upload file size is 0

### ISSUE THREAD

**Issue by langzicx** [OneDrive/onedrive-api-docs#1193]
data = {
        "@content.sourceUrl": "http://wscont2.apps.microsoft.com/winstore/1x/e33e38d9-d138-42a1-b252-27da1924ca87/Screenshot.225037.100000.jpg",
        "name": "2-screensho2t.jpg",
        "file": {}
    }
    res = requests.post(
        discovery_uri + '/me/drive/items/root/children',
        headers=headers, json=data).json()
    print(res)

cTag': '"c:{8B3420CE-9536-42AD-96E9-8623D40ED367},1"', 'size': 0,
Byte is empty

---
#### 文件的詳細資料

⚠ *請勿編輯此部分。 docs.microsoft.com 必要 ➟ 連結 GitHub 問題。*

* ID: 42443681-dd86-ce0c-587f-2336f965ebaf
* Version Independent ID: abcbaeba-560b-661d-0127-5c44d9089915
* Content: [Upload from a URL - OneDrive API - OneDrive dev center](https://docs.microsoft.com/zh-hk/onedrive/developer/rest-api/api/driveitem_upload_url?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_upload_url.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_upload_url.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by langzicx** [comment]
res = {'@odata.context': "https://graph.microsoft.com/v1.0/$metadata#users('de6d64dd-3d81-4e63-9e75-6271e859de6d')/drive/items('root')/children/$entity", '@microsoft.graph.downloadUrl': 'https://ubest-my.sharepoint.com/personal/r1d4jrb3r_onedrive_readmail_net/_layouts/15/download.aspx?UniqueId=8b3420ce-9536-42ad-96e9-8623d40ed367&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdWJlc3QtbXkuc2hhcmVwb2ludC5jb21AMDdhNjE5NDItZmQyYi00OGIzLTlkZTMtZTc4NDQxZTRkNmVlIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU3NDY2NTQ2MCIsImV4cCI6IjE1NzQ2NjkwNjAiLCJlbmRwb2ludHVybCI6IkRjZUtCYzIzZ3JYT1RlMFNjTnRVUVJUd3A2UkRlblJWNmVZdXBnYmJPbXM9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNjAiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik0yWXdNemRtTkRndFl6WTRNQzAwWm1KbUxUZzNObUV0WXpoa1l6VmhOalEyWm1RdyIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJOelZqTW1GaE1UWXRNV0ZoTlMwME1UaGtMVGd4TnpZdE0yWTVNVFpsWXpBMk1XWmkiLCJhcHBfZGlzcGxheW5hbWUiOiJjaHV4aWFkYWRhIiwiZ2l2ZW5fbmFtZSI6IuWmguW4uCIsImZhbWlseV9uYW1lIjoi5p2OIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiOWMxZDM3ZTYtMTA1MC00NDUzLWJmZWUtNGNiMzNlNzhiOGEwIiwidGlkIjoiMDdhNjE5NDItZmQyYi00OGIzLTlkZTMtZTc4NDQxZTRkNmVlIiwidXBuIjoicjFkNGpyYjNyQG9uZWRyaXZlLnJlYWRtYWlsLm5ldCIsInB1aWQiOiIxMDAzMjAwMDg5MkM3M0EzIiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzIwMDA4OTJjNzNhM0BsaXZlLmNvbSIsInNjcCI6ImFsbGZpbGVzLndyaXRlIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.Z2hqenJ1M0JDT3F4R0lVMkdBNnA5N0FnYm1zamFaZU90azB1dDBNV3BQbz0&ApiVersion=2.0', 'createdDateTime': '2019-11-25T07:04:20Z', 'eTag': '"{8B3420CE-9536-42AD-96E9-8623D40ED367},1"', 'id': '01QKNVWHWOEA2IWNUVVVBJN2MGEPKA5U3H', 'lastModifiedDateTime': '2019-11-25T07:04:20Z', 'name': '2-screensho2t 1.jpg', 'webUrl': 'https://ubest-my.sharepoint.com/personal/r1d4jrb3r_onedrive_readmail_net/Documents/2-screensho2t%201.jpg', 'cTag': '"c:{8B3420CE-9536-42AD-96E9-8623D40ED367},1"', 'size': 0,

**Comment by langzicx** [comment]
I tried. There is a problem. I recorded a video. May I refer you to `@microsoft.graph.sourceUrl`

`{'error': {'code': 'invalidRequest', 'message': '@content.sourceUrl can only contain a data uri.', 'innerError': {'request-id': '7ced2d77-07f2-45c2-b0b7-eb7c832d0f1d', 'date': '2019-11-26T02:23:58'}}}
`
[https://ubest-my.sharepoint.com/:v:/g/personal/r1d4jrb3r_onedrive_readmail_net/EQSpYEL5n8ZOt0gsjNFDZuMBkilyBUODAvPCqweDmmOpDQ?e=PIyhtp](https://ubest-my.sharepoint.com/:v:/g/personal/r1d4jrb3r_onedrive_readmail_net/EQSpYEL5n8ZOt0gsjNFDZuMBkilyBUODAvPCqweDmmOpDQ?e=PIyhtp)

**Comment by ificator** [comment]
Yeah, that's because your request is hitting SharePoint / OneDrive for Business, and using `sourceUrl` to download a file into a drive is not supported. It only works for personal accounts (i.e. OneDrive Personal / OneDrive Consumer).

**Comment by langzicx** [comment]
thank you I have been using the student account, registered a personal can.
