### ISSUE TITLE
Beta pages API doesn't work if you have pages with custom content types

### ISSUE THREAD

**Issue by baywet** [OneDrive/onedrive-api-docs#1194]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
The API call to succeed and return pages.

#### Observed Behavior
You get the following error.
```JSON
{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "request-id": "6041c48f-732f-4a0b-9849-0294bd9e637b",
            "date": "2019-11-25T17:00:43"
        }
    }
}
```

Tenant mag013qa2tolead
RID's
6041c48f-732f-4a0b-9849-0294bd9e637b (graph explorer)
3df05a8d-84e5-49f8-8809-1feff5127225 (dotnet sdk)

#### Steps to Reproduce
1. create a team or communication site
1. add custom content types to the site pages library
1. add pages using that new content type
1. GET `https://graph.microsoft.com/beta/<siteid>/pages`

Thanks for your help!

**Comment by chackman** [comment]
Thanks for the feedback.  We'll follow up with this feedback internally to our partner team working on this API.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
