### ISSUE TITLE
GET /me/drive/root:/{item-path}:/content returns HTML "Error" instead of 404.

### ISSUE THREAD

**Issue by arqbackup** [OneDrive/onedrive-api-docs#1195]
GET /me/drive/root:/{item-path}:/content for a file that doesn't exist resulted in a 200 response with the HTML below, instead of a 404 response.
Our app stored the response as if it were actual file contents.
The API should return a 500 error.
I can't think of any way to mitigate against this bug.

Is this a known issue?

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns:o="urn:schemas-microsoft-com:office:office" lang="en-us" dir="ltr">
<head><meta name="GENERATOR" content="Microsoft SharePoint" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="Expires" content="0" /><meta http-equiv="X-UA-Compatible" content="IE=8"/><meta name="ROBOTS" content="NOHTMLINDEX" /><title>

Error

</title><link id="CssLink-1d14d71424624c8e8d51acecdeb7dfba" rel="stylesheet" type="text/css" href="/_layouts/15/1033/styles/corev15.css?rev=x1CgmQ4tDkmtLHp8dxPL6g%3D%3DTAG592"/>
<link id="CssLink-66518b0ddef34f548e557d419c3a41a9" rel="stylesheet" type="text/css" href="/_layouts/15/1033/styles/error.css?rev=%2F3%2F1Ql%2FSCnyuBJ%2B%2FM9tFhg%3D%3DTAG592"/>
<style id="SPThemeHideForms" type="text/css">body {opacity:0 !important}</style><script type="text/javascript">// <![CDATA[ 

var _initGlobalSnapShot = {};try { if (Object.keys(_initGlobalSnapShot).length == 0) { for (var memberIndex in window) { if (Boolean(memberIndex)) { _initGlobalSnapShot[memberIndex] = 1; } } }} catch (ex) {};
// ]]>
</script>

**Comment by ificator** [comment]
Hi @arqbackup, do you have an `SPRequestGuid` value from the response headers for a request that returns this? You should not see HTML come back, but there are edge cases during failure scenarios that can result in responses that are not to spec. If we can track down the cause we'll definitely fix it.

**Comment by arqbackup** [comment]
Unfortunately I don't have the GUID because we only noticed this at a much later date when we went to read the file we had downloaded previously.
