### ISSUE TITLE
Encoding method doesn't work with 1drv.ms links

### ISSUE THREAD

**Issue by thonkdifferent** [OneDrive/onedrive-api-docs#1197]
The encoding method doesn't work with those types of links.
I managed to get it working by triming everything before the s! part of the link. For examle if you have https://1drv.ms/f/s!characters, the id is s!characters;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292c23a1-9aab-8349-11b2-dc6f28d54e6e
* Version Independent ID: 083a591a-6425-3408-aa2f-ace9db3c43c8
* Content: [Access shared items - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/shares_get.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/shares_get.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Could you please clarify exactly how you encoded the URL?  Did you encode the whole URL (including https://1drv...) or just a part?

**Comment by bpetru05** [comment]
I tried to encode the whole URL( including the https://1drv... part)

**Comment by JeremyKelley** [comment]
Thanks for your feedback, we'll look at how to improve the documentation for this particular case and evaluate whether it's correct for us to accept the full encoded URL.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
