### ISSUE TITLE
Folder Name Collision

### ISSUE THREAD

**Issue by Max-Sum** [OneDrive/onedrive-api-docs#1198]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Folders with different name should be allowed to coexist.

#### Observed Behavior

Using Graph API or Web to operate Onedrive for Business, Creating two folder named "㴈㴈" and "㴈㴈㴈" would result in conflict.

#### Steps to Reproduce

Create folder named "㴈㴈" and create another called "㴈㴈㴈“.
Error message pops up claiming the folder named "㴈㴈㴈" is exist.

Thank you.

**Comment by JeremyKelley** [comment]
Hello, in order for us to investigate please provide the request ID from the response headers on the failing request and the timestamp associated with the request.

Thank you!
