### ISSUE TITLE
Logged-in user profile

### ISSUE THREAD

**Issue by shierabisdak** [OneDrive/onedrive-api-docs#12]
I want to get the logged-in user's email address and other information.

In the old API, I got it through this URL:  https://apis.live.net/v5.0/me
and by specifying the wl.emails scope.

In the new OneDrive API, I tried this URL:  https://api.onedrive.com/v1.0/drives/me
and specified the wl.emails scope but only got the following information:

{
  "quota": {
    "total": 32212254720,
    "remaining": 1562125249,
    "used": 30650129471,
    "deleted": 57979,
    "state": "nearing"
  },
  "id": "<xxxxxxxxxxxx>",
  "driveType": "personal",
  "@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives/$entity",
  "owner": {
    "user": {
      "displayName": "My Name",
      "id": "<xxxxxxxxxxxx>"
    }
  }
}

Does someone know how to get more user information through the new API?
Thank you !

**Comment by peternied** [comment]
The OneDrive APIs have a specific purpose, providing access to all of your content on OneDrive.  The user profile/relationships story isn't something that we have exposed at this time, we are still working on making it great.  You can keep using the LiveConnect APIs to get this information until we come up with a better solution through this service or the proper authoritative service to use.
