### ISSUE TITLE
Byte Range must be multiple of 320 KiB, but the example shows uploading of 26 bytes

### ISSUE THREAD

**Issue by AJIXuMuK** [OneDrive/onedrive-api-docs#1200]
In the documentation:

> **Note**: If your app splits a file into multiple byte ranges, the size of each byte range MUST be a multiple of 320 KiB (327,680 bytes). Using a fragment size that does not divide evenly by 320 KiB will result in errors committing some files.

But later:
> In this example, the app is uploading the first 26 bytes of a 128 byte file.

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d409f771-fd62-e549-d581-aac009e79e8c
* Version Independent ID: fe646b3a-06f5-a269-47e6-b4ee693e5410
* Content: [Resumable file upload - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_createuploadsession.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createuploadsession.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment]
Thanks for the feedback, the example is just an illustration but your point is well taken.  We'll add a doc bug to our backlog, alternatively if you would like to suggest a change to the docs yourself, feel free to submit a pull request and we'll take a look.

**Comment by agat366** [comment]
Actually the docs are quite misleading in that part indeed. It states "will result in errors committing some files". But that's kind of not reliable in programming world. What does that mean? "I can go with that, but not sure if that works"? Or "It will work for particular file types, but images (jpgs) are ok (for instance)"? Why is it mentioned "sometimes" if you just should follow that rule to have your code working in 100% cases?

**Comment by ificator** [comment]
It used to be the case that such failures could occur on files with a large number of chunks, but that hasn't been an issue for quite some time. The docs are out of date and need to be fixed.

**Comment by sravanpalakala** [comment]
can your team provide example with larger file, by using multiple of 320 KiB under Content-Range

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
