### ISSUE TITLE
Permanently delete a file in App Folder

### ISSUE THREAD

**Issue by byteamaze** [OneDrive/onedrive-api-docs#1201]
Is there any way to permanently delete a file in my App Folder?

DELETE /me/drive/items/item-id

This method move the items to the recycle bin, but the storage usage isn't decrease.
Why the App Data can not be deleted permanently? This is unexpected for users.

Thank you.

**Comment by JeremyKelley** [comment]
At the moment we do not provide an API endpoint for working with the recycle bin through Microsoft Graph, this is an item in our roadmap but does not have an ETA right now.
