### ISSUE TITLE
invitation facet not returned and grantedTo returned empty on Graph permissions APIs 

### ISSUE THREAD

**Issue by braimondo** [OneDrive/onedrive-api-docs#1202]
#### Category
- [x ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
From https://docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0 we would expect to see a list of email addresses with whom a file is shared (for external sharing) in either the grantedTo facet or in the invitation facet (if the invitation was not redeemed). 

#### Observed Behavior
We are not seeing the grantedTo populated (regardless of whether the invitation was redeemed or not), and the invitation facet is not returned at all. 

We are seeing the grantedto correctly populated in the beta version of the APIs. 

#### Steps to Reproduce

This happens all the times with the Graph Permissions APIs.

**Comment by chackman** [comment]
Thanks for your feedback.  Publishing the beta API's to v1.0 is on our plans for early next quarter (i.e. Q1 of calendar year 2020).

**Comment by braimondo** [comment]
Thank you Chris. The question is not about the beta API, but about the current version of the API, as the behavior does not reflect the docs. Thus the question.

**Comment by JeremyKelley** [comment]
Hi Bruno, what Chris is implying (and you should be able to verify) is that the Beta endpoint returns the data as expected while 1.0 doesn't.  Pushing the updates to 1.0 is a priority for us after the new year.
