### ISSUE TITLE
Embeddable URLs from the "driveItem: preview" endpoint fail to load ~20% of the time.

### ISSUE THREAD

**Issue by hassanacto** [OneDrive/onedrive-api-docs#1203]
#### Category
- [ ] Question
- [ ] Documentation issue
- [ x] Bug

#### Expected or Desired Behavior

Embeddable URL that should display the contents of the sharepoint office file in the web browser (as ready only). 

#### Observed Behavior

Fails about 20% of the time with JS errors on the viewer (through the link returned). When this occurs, the viewer does not load, and the page needs to be refreshed.

#### Steps to Reproduce

Call the "driveItem: preview" endpoint, receive an embeddable link to display within an iframe. Fails to load ~20% of the time.

Thank you.

**Comment by chackman** [comment]
Does this issue affect OneDrive for Business, OneDrive Personal, or both services?  Also do you know which viewer(s) or file type(s) are affected by this issue?

**Comment by hassanacto** [comment]
I'm using it Microsoft Graph 1.0 which is using SharePoint, but I'm assuming it's the same and uses One Drive for business. It's affecting all Document, Excel, and PowerPoint viewers. This is the endpoint I'm using: https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0

The same link works if refreshed. There are some request issues for cross domain requests. I think it could be due to the way the older anonymous web viewer was set up. It could be a combination of these JavaScript errors that stop it from loading.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
