### ISSUE TITLE
office 365 account got error: InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by Simon4638** [OneDrive/onedrive-api-docs#1205]
Hi Engineer,

I got an error when I upload file to OneDrive with office365 business account. 

The Error is ‘InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217‘

I tried person account which work fine without problem. 

I also checked the following link but with no luck.
https://github.com/OfficeDev/outlook-dev-docs/issues/508
https://github.com/OneDrive/onedrive-api-docs/issues/785

I got the authorize code from here:
https://login.microsoftonline.com/common/oauth2/v2.0/
exchanged the token from here:
https://login.microsoftonline.com/common/oauth2/v2.0/token

Scope is: "offline_access+files.readwrite"

After I got the token, I can browse the onedrive folder list success, but cannot upload file. (error code: 80049217)

The code that I am using work fine around one year ago. So I am not sure if there is any change on server side recently. 

Thanks in advance.

**Comment by chackman** [comment]
Could you please provide the following response headers corresponding to your request(s):
 - Date (in UTC, please)
 - request-id
 - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by Simon4638** [comment]
Hi chackman:

Thank you very much first.

The Date is : 2019-12-18T01:18:20
The Request-id is: 6e25e46f-6ace-4cb5-ac79-db141454f528

I am sorry that I didn't find the SPRequestGuid. Could you please let me know where to get SPRequestGuid. The following are the code that I made this request:

`strUploadSession = "me/drive/root:/"
                    + strOneDrivePath
                    + strFileName + ":/"
                    + "createUploadSession";


                RestClient restClient = new RestClient("https://graph.microsoft.com/v1.0");
                RestRequest restRequest = new RestRequest(strUploadSession);
                restRequest.RequestFormat = RestSharp.DataFormat.Json;
                restRequest.Method = Method.POST;
                restRequest.AddParameter("Authorization", string.Format("Bearer " + strToken), ParameterType.HttpHeader);

                restRequest.AddHeader("Authorization", "Authorization");
                restRequest.AddHeader("Content-Type", "application/json");

                restRequest.AddParameter("application/json", "{}", ParameterType.RequestBody);

                var response = restClient.Execute(restRequest);
                var myResult = response.StatusCode;
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {`

**Comment by chackman** [comment]
Thanks... unfortunately we could not find logs for this particular request.
To be clear was this a request ID returned by graph.microsoft.com?  If so that request ID (and time) should be good enough.
Could you please provide another request ID + time (in UTC)?  Thanks!

**Comment by Simon4638** [comment]
Hi Chackman. 
Thanks for your quick reply. I just made another request. 
This time the request ID is : b0a13a9b-0489-4af4-87c4-c556d48629a4
Time is: 2019-12-23T09:09:37

The text below is the content which return value from restClient.Execute method:

"{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"CompactToken parsing failed with error code: 80049217\",\r\n    \"innerError\": {\r\n      \"request-id\": \"b0a13a9b-0489-4af4-87c4-c556d48629a4\",\r\n      \"date\": \"2019-12-23T09:09:37\"\r\n    }\r\n  }\r\n}"

Please take a look if I did anything wrong.

**Comment by Simon4638** [comment]
Hi Chackman,

Please take a look at this above when you have time.

Thanks a lot.

**Comment by chackman** [comment]
Sorry, I cannot find the logs.  I would suggest reaching out to the Microsoft Graph team since I cannot find anything indicating an issue on OneDrive or SharePoint.

**Comment by asith-w** [comment]
@chackman 
i also using "https://login.microsoftonline.com/common/oauth2/v2.0/authorize" ,"https://login.microsoftonline.com/common/oauth2/v2.0/token" for oauth process, 
what can be the reason for  this error
**InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217**

**Comment by Nikunjksanghavi** [comment]
I am also using similar URL but still I am facing the issue.

**Comment by Nikunjksanghavi** [comment]
@asith-w have you found solution? or any workaround?
