### ISSUE TITLE
Missing icons and menu items in custom file handler

### ISSUE THREAD

**Issue by enerdgumen** [OneDrive/onedrive-api-docs#1206]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

My company is using a custom file handler registered with the [file handler integration api](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online).

Recently the custom menu items are not shown anymore in the contextual menu of OneDrive/SharePoint web interfaces, and the custom icons are not applied.

#### Observed Behavior

I see the handler properly registered on Azure:
```
GET /_api/v2.0/drive/apps?select=*,promoted&expand=actions
{
  "@odata.context": "https://<omitted>-my.sharepoint.com/_api/v2.0/$metadata#driveApps",
  "value": [
    {
      "@odata.type": "#oneDrive.driveApp",
      "@odata.id": "https://<omitted>-my.sharepoint.com/_api/v2.0/oneDrive.driveApp314eedad-aeb3-445f-bd4f-f1dd84f39035",
      "@odata.editLink": "oneDrive.driveApp314eedad-aeb3-445f-bd4f-f1dd84f39035",
      "application": {
        "id": "94097542-d2db-4568-a7b9-ac7f4fab4f1b",
        "displayName": "<omitted>"
      },
      "fileHandler": {
        "fileTypeDisplayName": "<omitted>",
        "fileTypeIcon": {
          "png1x": "https://localhost:3000/images/itemtypes/96/default.png",
          "png2x": "https://localhost:3000/images/itemtypes/96/default.png"
        },
        "fileTypeIconUrl": "https://localhost:3000/images/itemtypes/96/default.png",
        "version": 2
      },
      "id": "42aecef6-775f-54a7-b3b9-a3a07644fc1b",
      "actions@odata.navigationLink": "oneDrive.driveApp314eedad-aeb3-445f-bd4f-f1dd84f39035/actions",
      "actions": [
        {
          "@odata.type": "#oneDrive.driveAppAction",
          "@odata.id": "https://<omitted>-my.sharepoint.com/_api/v2.0/oneDrive.driveAppAction1033e7d9-99e9-4b6f-af35-0c28a59290ee",
          "@odata.editLink": "oneDrive.driveAppAction1033e7d9-99e9-4b6f-af35-0c28a59290ee",
          "availableOn": {
            "file": {
              "extensions": [
                ".ab1",
                ".ab2"
              ]
            },
            "web": {},
            "allowMultiSelect": false
          },
          "type": "open",
          "url": "https://localhost:3000/api/open"
        }
      ]
    },
    ...
```

We haven't updated these manifests recently, it seems the OneDrive web interface now is broken for some reason.

However the actions are loaded because they are shown in the file preview:
![image](https://user-images.githubusercontent.com/240925/70923675-888dda80-2028-11ea-9db1-a09c59fb54e2.png)

But the contextual menu does not contain them, moreover the custom icons are not applied:
![image](https://user-images.githubusercontent.com/240925/70925165-0f43b700-202b-11ea-94e3-7309c12fb77a.png)

Please give us some feedback,
Thanks.

**Comment by JeremyKelley** [comment]
We're investigating issues with the File Handlers currently and will let you know when we have a resolution that you should verify.

**Comment by dleone-boole** [comment]
I have the same issue. It resolved some time ago, but now the problem has reoccurred

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
