### ISSUE TITLE
Can not create OneNote notebook item.

### ISSUE THREAD

**Issue by lockelost** [OneDrive/onedrive-api-docs#1207]
In the case of the OneDrive business, it synchs the OneNote contents under 'Notebooks' folder on OneDrive storage.

With the RET API we can get all the information about this special type of item which works like a folder. And we can download all the files (*.one, *.toc) inside.

But if we want to 'restore' the contents we just downloaded, we can not create this kind of OneNote sync item.

If we create the normal folder under the 'Notebooks' folder and upload the files under the folder we just created, it will mess up the OneNote API to return an Error.

We can call OneNote API to create this kind of special folder, which is Notebook in OneNote API's view, and if we upload the files inside, it works all right.

But the problem with that approach is that the OneDrive webpage provides the 'Copy To' button for OneNote item there, and if you click on it, it will generate a new OneNote notebook also on the OneNote website. The problem is that you can specify other Folders on OneDrive storage, no matter how many depths it is.

Because OneDrive does not provide an API option to create this kind of 'OneNote synch' item, In case if you want to restore the OneNote notebook item you have to call this API to create a new Notebook.

But because you can not specify the 'path' to where in the OneDrive's storage, it will always create one inside the OneDrive's 'Notebooks' folder. So you can not restore properly the Notebook files that were in some other folder location on OneDrive storage.

Maybe you guys can simply make this API to have the additional option what type of the Folder we want to create? just a normal folder or OneNote sync item.

Basically, you guys enabled the Synch between OneNote and OneDrive and provided the OneDrive API to get all the information of them, but did not provide the API to create that only one specific type. So asking the API consumers to call different API does not make sense. If it takes time, please revise OneNote API to work properly, or disable the synch & copy-to features till your APIs get ready.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8e0c33b-73b9-4086-4fa3-c54b701d9695
* Version Independent ID: 869bb2ba-3e32-36c9-7b4f-3875b6c5c277
* Content: [Create a new folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_post_children?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_post_children.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_post_children.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  The OneDrive API currently does not support working with OneNote content in the way that you describe.
Could you please propose an enhancement via the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice?  Thanks!

**Comment by lockelost** [comment]
Thanks @chackman but I don't think this is 'enhancement' but rather it's 'bug fix'.
Sovereign networks like China cloud doesn't even support OneNote API.
Yet you can create OneNote contents and manipulate them on OneDrive web site,
you can not do the same with OneDrive API.

Anyway, I posted a suggestion there, but I don't think anybody will look at it.
