### ISSUE TITLE
OneDrive filepicker unauthorized_client error in localhost

### ISSUE THREAD

**Issue by shyamal890** [OneDrive/onedrive-api-docs#1208]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

It should allow authentication

#### Observed Behavior

- I created App in Azure Active Directory as suggested [here](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/index?view=odsp-graph-online#setting-up). 
- Entered 2 RedirectUris in the Azure Active Directory App - `https://localhost:4200` (for local testing) and `https://something.com` for live application.

- After which when I execute the following code in localhost:
```
pick = (): Promise<any> => {
        var deffered = new Deferred<any>();
        var odOptions = {
            clientId: this.appId,
            action: "query",
            multiSelect: true,
            advanced: {
                redirectUri: "https://localhost:4200"
            },
            success: (files) => {
                deffered.resolve(files);
            },
            cancel: () => { 
                deffered.reject("cancel");
            },
            error: (error) => {
                deffered.reject(error);
            }
        }
        OneDrive.open(odOptions);
        return deffered.promise;
    };
```
I get an error saying `unauthorized_client`. How do I resolve this?

**Comment by KevinTCoughlin** [comment]
@shyamal890, you should not need to specify `redirectUri` in this case. Regardless, the error `unauthorized_client` seems like a misconfiguration of the AAD application for the provided client ID.

Are you serving the local test page over `https`? There is a mismatch between the reply urls you've specified in Azure Portal and what you are testing locally.

https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis#add-redirect-uris-to-your-application

**Comment by shyamal890** [comment]
Hi @KevinTCoughlin Here's the screenshot of the AAD app configuration.
![image](https://user-images.githubusercontent.com/6606965/73744490-e613ed00-4776-11ea-8c20-27b83798448d.png)

And I tried both with and without `redirectUri` it still is giving me the same error.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
