### ISSUE TITLE
Does OneDrive personal accounts still need to use https://api.onedrive.com/v1.0 endpoint for all requests?

### ISSUE THREAD

**Issue by TrentXu** [OneDrive/onedrive-api-docs#1209]
If not, please update the information.
Because I found in the graph-explorer(https://developer.microsoft.com/en-us/graph/graph-explorer), it can use https://graph.microsoft.com/v1.0/ endpoint for OneDrive personal accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea09cc9-7668-ae89-2fee-cee17c0b34de
* Version Independent ID: 4a851b01-ed02-9cef-8c23-4408d148991c
* Content: [Understand differences between OneDrive API and Microsoft Graph - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences?view=odsp-graph-online#onedrive-personal-accounts)
* Content Source: [docs/rest-api/concepts/direct-endpoint-differences.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/direct-endpoint-differences.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Personal accounts may use the graph.microsoft.com endpoint - it is the preferred endpoint for accessing OneDrive personal, OneDrive for Business, and SharePoint online files.

The section referenced in this issue applies to when an application is using the OneDrive API directly, and therefore must discover the appropriate OneDrive API endpoint.
