### ISSUE TITLE
content format convertion failing

### ISSUE THREAD

**Issue by facditul** [OneDrive/onedrive-api-docs#1211]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

When you call Download a file in [another format endpoint](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get_content_format.md) to convert a image with mime type _image/heic_ to jpg you should receive the converted file.

#### Observed Behavior

When you call the endpoint the return is a _400 Bad Request_ error:
```json
{
  "error": {
    "code": "invalidRequest",
    "message": "Bad Argument",
    "innerError": {
      "request-id": "4c17c7aa-9d77-4325-9d35-30498526e456",
      "date": "2020-01-12T12:15:46"
    }
  }
}
```

#### Steps to Reproduce

Call Download a file in another format enpoint:

- https://graph.microsoft.com/v1.0/me/drive/items/{id}/content?format=jpg
- https://graph.microsoft.com/beta/me/drive/items/{beta}/content?format=jpg

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback. Does this only affect heic format?

**Comment by jonasgaiswinkler** [comment]
Are there any updates on this issue? I am also getting the same error when trying to convert an image with mime type _image/heic_ to jpg.
