### ISSUE TITLE
Recycle Bin API documentation is missing

### ISSUE THREAD

**Issue by jstaf** [OneDrive/onedrive-api-docs#1212]
The documentation on how to delete a DriveItem mentions the following:

> Note that deleting items using this method will move the items to the recycle bin instead of permanently deleting the item.

Despite [searching for awhile](https://github.com/OneDrive/onedrive-api-docs/search?q=recycle+bin&unscoped_q=recycle+bin), there is no documentation on the Recycle Bin anywhere. How do I access and manipulate a user's recycle bin via the OneDrive API? I'm specifically interested in the following:

* How do I get a list of DriveItems currently in the Recycle Bin via the API?
* How do I restore an item (and its children, if the deleted item was a folder) via the API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1972b81a-297f-08b6-274a-60ecda82a218
* Version Independent ID: f0da765f-de5f-e6a1-a17c-c02dcfabd3ae
* Content: [Delete a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delete?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_delete.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delete.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  There is currently no Recycle Bin API available.  While we are considering a Recycle Bin API, we would also recommend that you vote for it on the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice.  Community feedback feeds into the review and planning process.  Thanks!

**Comment by jstaf** [comment]
Thanks for the heads-up, that's what I suspected after digging through things. It's not a huge deal in my case (I have another way to trash/restore files), but would be useful to have in the future.

I'm leaning towards leaving this issue open just as a heads up to others reading the "Delete a DriveItem" article that the API isn't there yet.
