### ISSUE TITLE
Zoom levels

### ISSUE THREAD

**Issue by LarryWMSN** [OneDrive/onedrive-api-docs#1213]
When we are able set the zoom level, are there any values that can be used for Fit or Page Width? This should be documented a bit clearer if it's not available or what the values are if it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abaca550-f44d-455b-ef18-a284dd222dbc
* Version Independent ID: de0dfe46-b10b-5b53-59a1-37967fe2b1ab
* Content: [Get short-lived embeddable link for preview purposes - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online&source=docs#feedback)
* Content Source: [docs/rest-api/api/driveitem_preview.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_preview.md)
* Product: **onedrive**
* GitHub Login: @kevinlam
* Microsoft Alias: **kevinlam**

**Comment by chackman** [comment]
Thanks for your feedback.  The `zoom` property is a number, and there are currently no ways to specify values that correspond to "Fit" or "Page Width"

Could you please propose an enhancement via the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice?  Thanks!

**Comment by LarryWMSN** [comment]
This information should be noted in the Page/Zoom paragraph: 

> This is a number (int/double?) between x and y. The 'page' and 'zoom' options may not be available for all preview apps, but will be applied if the preview app supports it.  There are no values to represent Fit or Page Width. Click here to find out which preview apps support Page/Zoom.
