### ISSUE TITLE
Business Onedrive - Notification Doesn't return actual resource path

### ISSUE THREAD

**Issue by ghodasarakartik** [OneDrive/onedrive-api-docs#1214]
#### Category
- [ ] Question

#### Observed Behavior

I am able to create a subscription to "drives/driveid/root" but the notification doesn't contain the actual resource path rather it already returns "drives/driveid/root".

How can I get which exact resource is changed under root?
is there any way?

Thank you.

**Comment by ghodasarakartik** [comment]
How much time it usually takes to get the response? I am on the clock here and I am not able to find relevant answers anywhere

**Comment by ificator** [comment]
Subscriptions are intended to be used in conjunction with the `delta` endpoint - the notification you receives is essentially just a "shoulder tap", and a follow up call to find the changes is required.

**Comment by ghodasarakartik** [comment]
Hi @ificator 
Thanks for the reply.

So currently there is no way I can get which exact resource is changed,  like resourceData in response.

I tried to create subscription with "includeResourceData": true property but getting error response 
"File Services workload is not enabled for rich notifications."

**Comment by ghodasarakartik** [comment]
Also, please note that I am using Admin Consent and created the subscription without login.

**Comment by ificator** [comment]
Unfortunately not at this time - I'd suggest making sure there's an idea over on our [UserVoice page](https://onedrive.uservoice.com/forums/913708) if this is something you'd like to see.

**Comment by ghodasarakartik** [comment]
Sure, thanks

Looking at this post, it seems you guys are already on it 👍 

https://stackoverflow.com/questions/54221923/unable-to-subscribe-to-rich-notifications-in-ms-graph

**Comment by ghodasarakartik** [comment]
I think we can close this now. will eagerly wait for this enhancement though.
