### ISSUE TITLE
Onedrive picker is not listing group sharepoints in sidebar

### ISSUE THREAD

**Issue by abdulkareemnalband** [OneDrive/onedrive-api-docs#1215]
We are opening **open file picker** using following configuration
```js
{
  clientId:'****',
  advanced:{
    accessToken:'****',
    endpointHint:'<users personal sharepoint url >', // `webUrl` from  `https://graph.microsoft.com/v1.0/me/drive`
    navigation:{
      sourceTypes: ['OneDrive', 'Sites']
    },
    success:succesCalback,
    error:errorCallback,
    cancel:cancelCallback,
    action: 'query'
  }
}
```
But group sharepoints are not listed in sidebar, It used to work before two days

![image](https://user-images.githubusercontent.com/3139353/73157533-4ff11e80-4107-11ea-8da9-b2a3222a67a2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by abdulkareemnalband** [comment]
Here are traces
Note: I have redacted all cookies and tokens

[oneDrivePicker.zip](https://github.com/OneDrive/onedrive-api-docs/files/4126998/oneDrivePicker.zip)

**Comment by figgsoftware** [comment]
@yumikohey It is definitely not an intermittent issue. It is very consistent and we have dusins of clients complaining. Please prioritize this serious issue @JeremyKelley

**Comment by yumikohey** [comment]
@figgsoftware , @abdulkareemnalband , could you go to your OneDrive and see if you can see Teamssites from your OneDrive or not? We are looking into this issue.

**Comment by figgsoftware** [comment]
Yes we can reach the team sites there. Remember that this is not just a problem in our tenant, but for many of our clients as well.

**Comment by figgsoftware** [comment]
It works if we open the url  https://xxx-my.sharepoint.com/personal/xxxxxxxx/_layouts/15/OneDrive.aspx instead of https://xxx-my.sharepoint.com/personal/xxxxxxxx/Documents/Forms/All.aspx that the OneDrive Javascript SDK opens up. Hope this helps @yumikohey @JeremyKelley

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
