### ISSUE TITLE
OneDrive personal: files filter name with startsWith returns odata.nextLink for single result

### ISSUE THREAD

**Issue by sshankar-rks** [OneDrive/onedrive-api-docs#1217]
I have replaced actual drive id and folder id with placeholders. You should be able to see the actual
values if you look at the requests (I have put in request ids wherever applicable)

1. GET https://graph.microsoft.com/beta/drives/<drive-id>/items/<folder-id>/children?$filter=startswith(name,'402048677745')

request-id: d8cd752a-9cb6-4fad-a00d-3532ded47f49

2. Actual Result:
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('<drive-id>')/items('<folder-id>')/children",
    "@odata.count": 245,
    "@odata.nextLink": "https://graph.microsoft.com/beta/drives/<drive-id>/items/<folder-id>/children?$filter=startswith(name%2c%27402048677745%27)&$skiptoken=MjAx",
    "value": []
}

3. When i follow @odata.nextLink I get the expected result

`GET https://graph.microsoft.com/beta/drives/<drive-id>/items/<folder-id>/children?$filter=startswith(name,'402048677745')&$skiptoken=MjAx`

request-id: 46571704-8922-4fcc-88c6-ef6709f6792f

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('<drive-id>')/items('<folder-id>')/children",
    "@odata.count": 245,
    "value": [
        {
            "@microsoft.graph.downloadUrl": "<url>",
            "createdDateTime": "2020-01-29T01:03:46.967Z",
            <some properties>
            "id": "<id>",
            "lastModifiedDateTime": "2020-01-29T01:26:02.827Z",
            "name": "402048677745_orig.jpg",
            "webUrl": "<1drv.ms url>",
            "size": 252817,
	    <bunch of other properties>
        }
    ]
}

**Expected result:**
@odata.count is wrong. Should be 1
Since filter actually returns a single item, the result should have value and no @odata.nextLink

This may be a recent regression, was working last week (I did have less than 200 items in the folder then). I use startsWith filter since equal doesn't seem to work.

**Comment by sshankar-rks** [comment]
Hi, can anyone take a look at this?

**Comment by chackman** [comment]
Does this issue reproduce for OneDrive Personal, OneDrive for Business, or both?

**Comment by sshankar-rks** [comment]
I only tried with OneDrive personal.

> Does this issue reproduce for OneDrive Personal, OneDrive for Business, or both?

**Comment by sshankar-rks** [comment]
> I only tried with OneDrive personal.
> 
> > Does this issue reproduce for OneDrive Personal, OneDrive for Business, or both?

Hi,  can someone take a look at this?

**Comment by chackman** [comment]
Does the `@odata.nextLink` link have the same value as before, or is it different?
example: if you call
`
GET https://graph.microsoft.com/beta/drives/<drive-id>/items/<folder-id>/children?$filter=startswith(name,'402048677745')&$skiptoken=MjAx
`
is the `@odata.nextLink` the identical URL or does a value in it (such as `skiptoken`) change?

**Comment by sshankar-rks** [comment]
Here's the info you requested. I have included request ids so that you can look at logs if needed.
I suspect @odata.count reflects the total number of files in the folder (I currently have 695 in that folder)
and not the value that is getting returned by the filter, which should be 1 in this case.

1. GET https://graph.microsoft.com/beta/drives/<drive-id>/items/<drive-id>!143496/children?$filter=startswith(name,'test.png')
request-id: a03cec81-950c-483a-b3f8-3ae361f4b9be

Result expected: single file data details in payload

Actual result:

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('<drive-id>')/items('<drive-id>%21143496')/children",
    "@odata.count": 695,
    "@odata.nextLink": "https://graph.microsoft.com/beta/drives/<drive-id>/items/<drive-id>!143496/children?$filter=startswith(name%2c%27test.png%27)&$skiptoken=MjAx",
    "value": []
}

2: GET https://graph.microsoft.com/beta/drives/<drive-id>/items/<drive-id>!143496/children?$filter=startswith(name%2c%27test.png%27)&$skiptoken=MjAx
request-id: 72c42bd6-78ca-473f-bb5f-795968cea663

Result: Skip token changed

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('<drive-id>')/items('<drive-id>%21143496')/children",
    "@odata.count": 695,
    "@odata.nextLink": "https://graph.microsoft.com/beta/drives/<drive-id>/items/<drive-id>!143496/children?$filter=startswith(name%2c%27test.png%27)&$skiptoken=NDAx",
    "value": []
}

3: GET https://graph.microsoft.com/beta/drives/<drive-id>/items/<drive-id>!143496/children?$filter=startswith(name%2c%27test.png%27)&$skiptoken=NDAx
request-id: cc36899a-0ad7-4469-b9d0-1918c17b42e1

Result: Skip token changed

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('<drive-id>')/items('<drive-id>%21143496')/children",
    "@odata.count": 695,
    "@odata.nextLink": "https://graph.microsoft.com/beta/drives/<drive-id>/items/<drive-id>!143496/children?$filter=startswith(name%2c%27test.png%27)&$skiptoken=NjAx",
    "value": []
}


4: GET https://graph.microsoft.com/beta/drives/<drive-id>/items/<drive-id>!143496/children?$filter=startswith(name%2c%27test.png%27)&$skiptoken=NjAx
request-id: 4a92c865-bb6d-46e4-9ee1-edcffe61f152

Result: Got file details, finally

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('<drive-id>')/items('<drive-id>%21143496')/children",
    "@odata.count": 695,
    "value": [
        {
            "@microsoft.graph.downloadUrl": "<some value>",
            "createdDateTime": "2020-01-22T02:07:34.037Z",
            "cTag": "<some value>",
            "eTag": "<some value>",
            "id": "<drive-id>!143823",
            "lastModifiedDateTime": "2020-01-30T03:53:32.63Z",
            "name": "test.png",
            "size": 22875,
            "webUrl": "<some value>",
            "createdBy": <some value>,
            "parentReference": <some value>,
            "file": <some value>,
            "fileSystemInfo": <some value>,
            "image": <some value>,
            "photo": {},
            "shared": <some value>
        }
    ]
}

**Comment by sshankar-rks** [comment]
Earlier this bug wasn't serious, but as the number of files in the directory increased, so does the number of requests I have to make to OneDrive, which ends up throttling because of the large number of requests.  I've now been sitting for a couple of hours waiting for embeddable links to 24 files. Please investigate and update.

**Comment by sshankar-rks** [comment]
Bumping this as it doesn't seem to be getting fixed.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
