### ISSUE TITLE
OneDrive Api search request always returns an empty collection when testing with a business account, but works when testing with a personal account

### ISSUE THREAD

**Issue by Madelene** [OneDrive/onedrive-api-docs#1218]
According to the Onedrive docs, when a search query is made, it should only return an empty collection if there were no items found. I know that there are items that exist that should show up in the response, however, no matter what I search for there are no results.

When testing with a personal account, I am able to successfully search and find our files. However, when testing with an admin/business account, the search returns an empty list. Both Delegated and Application permissions are set as: Files.Read.All

Here is the request I am making:
https://graph.microsoft.com/v1.0/search(q='s')

I have made sure that my request has the correct authorization header and am making a GET request. 

The above does work in the Graph Explorer, however.

Any ideas on what could be happening is appreciated!

**Comment by chackman** [comment]
Also, does your application use delegated or application-only permissions?  If using delegated, what permissions does the admin/business account have within their organization?

**Comment by Madelene** [comment]
@chackman  On our side, we have added both delegated and app permissions. Both are added as **Files.Read.All**. We have also added the offline_access (delegated) permission as well. 

When testing on our own OneDrive for business account, we were able to receive all files after adding these permissions when hitting the search endpoint. 🙌🏼

Thank you for getting back to us.

**Comment by chackman** [comment]
Thanks.  @Madelene, I'm going to mark this item as answered since it looks like it's working.  Please let us know if that's wrong.

**Comment by kurtsansom** [comment]
I am confused about what the resolution is? 
I am having a similar issue using a business account. when I query with the graph explorer I get non-empty results but using the same request from the test app (django and python example) It returns empty results.  

The confusion lies with what are the correct permissions to use? Ideally I want the app use a user  login  screen to get the credentials to make the requests which I believe is what the sample app does.  I would think I shouldn't have to add `offline_access (delegated)` for `Files.Read.All`
