### ISSUE TITLE
help for onedrive for business

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#122]
followed the steps to register the app for onedrive for business, really finding it difficult to register it.

from last 3-4 hrs wondering how to do it, couldnt move a step further...

Had company credential for office 365 and when clicking on azure from admin part, getting redirect to azure page, after that the wht so ever returned couldnt match it really scnerio...

can any one really help in this matter...???

**Comment by ankit-ankuagrawal** [comment]
@rgregg 
in next month our code will be out in market, and today it was decided to use onedrive for business, 

was really wandering to use which apis the new api of onedrive for business or the older describe on some webpage...

already onedrive for personal has been integrated with our product using new apis...

wht should do, pls suggest should use new api or old or should wait ???

**Comment by ankit-ankuagrawal** [comment]
@rgregg  ty for ur comment how to proceed with authentication part on wanna of the thread

after trying finally received the access_token 

but still question is should we use new onedrive api for onedrive for business 2.0?

tried GET https://mdm03-my.sharepoint.com/_api/v2.0/drive/root

{
error: 
{
code: "-2146232832, Microsoft.SharePoint.SPException"
message: "The file |0 does not exist."
}
}

**Comment by aclev** [comment]
@ankit-ankuagrawal Try https://mdm03-my.sharepoint.com/_api/v2.0/me/drive/root

**Comment by ankit-ankuagrawal** [comment]
@aclev no it does not work

**Comment by rgregg** [comment]
Are you still having an issue here @ankit-ankuagrawal? If not, can you close this thread, thanks!

**Comment by r4nm4** [comment]
Hi guys, I have the same error that @ankit-ankuagrawal mentioned ;(
In my case I retrieve the token from SharePoint and everything works... but not OneDrive API.
Thanks

**Comment by ankit-ankuagrawal** [comment]
@r4nm4 can u give more details so that can help...

what is the account type from which you are trying to login, because in my case the account type was "small business" and this api doesnt support this account. (https://dev.onedrive.com/app-registration.htm)

and other details if possible

**Comment by r4nm4** [comment]
Hi Ankit, thanks, but nevermind. I found the "another way" to retreive what I want.
In my case I use: "/_api/v2.0/me" and "/_api/v2.0/me/files".
Thanks

**Comment by rgregg** [comment]
Closing out old issues. If this is still an issue, please let us know.
