### ISSUE TITLE
Delete user from permission?

### ISSUE THREAD

**Issue by mhagesfeld** [OneDrive/onedrive-api-docs#1220]
Is there a way to remove a specific external user from a permission?  There is no delete for that, and patching with a new list of GrantedToIdentities fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cad8792a-e6c7-2fed-2ae8-b1489b6ad60f
* Version Independent ID: ea682f8a-7249-4bf4-503c-d0e01a93f142
* Content: [Remove access to an item - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/permission_delete?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/permission_delete.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/permission_delete.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  A feature to delete a specific user or PATCH is a feature enhancement that is on our backlog.

**Comment by chackman** [comment]
Please propose or vote for an enhancement via the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice. Thanks!
