### ISSUE TITLE
[ODB] upload *.rules encounter 404

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1221]
Hi folks,

Encountering a 404 http error when I request a upload with file name like *.rules
Is it possible to change the error code to be 400?

Thank you.

**Comment by chackman** [comment]
Could you clarify - is the issue the presence of the asterisk in the filename, or with the extension?
Example:
a. upload "foo.rules" and "bar.txt" work, but upload "*.rules" or "*.txt" fail
b. upload "bar.txt" works, but upload "foo.rules" fails
c. Something else

**Comment by joewutaiwan** [comment]
Any file name with extension "rules" like "test.rules" "reproduce.rules"

**Comment by chackman** [comment]
Could you please provide a correlation ID and date/time for the failed request?  And which API you are using?

For example, a basic PUT (to https://graph.microsoft.com/v1.0/me/drive/items/{item-id}:/Test2.rules:/content) worked OK.

**Comment by joewutaiwan** [comment]
Thank you for help

It is my entire header in response:
```
< HTTP/1.1 404 Not Found
< Cache-Control: private
< P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
< X-SharePointHealthScore: 1
< X-AspNet-Version: 4.0.30319
**< SPRequestGuid: 3c45379f-b034-a000-c9cb-1a243b24b4cd**
< request-id: 3c45379f-b034-a000-c9cb-1a243b24b4cd
< MS-CV: nzdFPDSwAKDJyxokOyS0zQ.0
< Strict-Transport-Security: max-age=31536000
< X-FRAME-OPTIONS: SAMEORIGIN
< SPRequestDuration: 57
< SPIisLatency: 6
< X-Powered-By: ASP.NET
< MicrosoftSharePointTeamServices: 16.0.0.19805
< X-Content-Type-Options: nosniff
< X-MS-InvokeApp: 1; RequireReadOnly
< X-MSEdge-Ref: Ref A: 5191297C05AC4436AFD39E8C92C5C970 Ref B: TPE30EDGE0223 Ref C: 2020-02-20T10:31:22Z
**< Date: Thu, 20 Feb 2020 10:31:22 GMT**
< Content-Length: 0
```

And It is my query
```
/_api/v2.0/drives/me/items/<parent_id>/children/test.rules/content?%40name.conflictBehavior=replace
```

Hope this helps!

**Comment by ificator** [comment]
When I've seen extension based weirdness in the past the colon syntax has generally worked. Can you see if the following workaround does what you need?

```
/_api/v2.0/drives/me/items/<parent_id>:/test.rules:/content?%40name.conflictBehavior=replace
```

**Comment by joewutaiwan** [comment]
@ificator 
Thanks, it would be a valid alterative.

**Comment by chackman** [comment]
Thanks, @ificator!
@joewutaiwan, I'll mark this as answered, assuming this works for you.  If not, please let us know.
