### ISSUE TITLE
Shared resource always returning scope "users"

### ISSUE THREAD

**Issue by ethanlieNS** [OneDrive/onedrive-api-docs#1222]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

We are trying to characterize the sharing settings of a [DriveItem](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online). The docs indicate we can check the [Shared](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/shared?view=odsp-graph-online) resource which should indicate if the item is shared publicly, internally, or with a select set of users.

The fact that this resource only displays one scope hints at the idea that there is some "permission precedence". I assume that this aligns with the exposure severity, so I would expect that the presence of a public link would cause a `"scope": "anonymous"` that would override any organization link or a link/direct access for a set of users.

#### Observed Behavior

It seems as if, despite any combination of permissions of the item, we are seeing the `Shared` resource _always_ contain `"scope": "users"`. It doesn't matter if we have a public link or an org link or both.

The only thing that presents something other than `"scope": "users"` is to have _no_ permissions besides the owner, in which case the `Shared` resource is omitted entirely.

We see this behavior in both v1.0 and beta. Are there any known issues with this resource currently? Is there something we are misunderstanding about how `Shared` decides permission precedence?

#### Steps to Reproduce

1. Create a new folder/file in OneDrive
2. Create a Public Link on the new item. I'm using the UI and clicking the "Copy Link" button along the top.
3. Verify the Permission shows up under "Manage Access" side panel.
4. Query `GET /me/drive/items/{item-id}/permissions` to verify that the permissions list contains two entries, the owner's direct access and the `"anonymous"` link
5. Query `GET /me/drive/items/{item-id}`. `Shared` has `"scope": "users"`

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.  Unfortunately, that is the case - the API returns `users` scope in this particular shared case.

To help us understand the request, is this ordering (highest to lowest priority) the requested ordering:
`anonymous`
`organization`
`users`
_`(none)`_

And is your question about `drive/items/{item-id}`?
Presumably this request is to save needing to make another call, enumerating the item's permissions?

**Comment by braimondo** [comment]
Chris, thank you for your answer. I don't think the desired behavior is a strict priority among these. Rather the desired behavior is for any given object in the repository to be able to detect all the sharing attributes that apply (as different policies, even concurrently, may apply to each of these conditions).

**Comment by ethanlieNS** [comment]
Thanks for responding! Yes to both points.

If a field is intending to relay the current scope of an item's sharing settings, I would expect it can be used to determine if a item is shared violates some preferred scope, which in-turn implies that one has a higher or lower precedence than another.

The order you list is exactly how we'd like it. If I as an admin prefers that some file is not shared outside a certain set of users, I would immediately know that an `organization` or an `anonymous` link violates my preference and I can act on it.

Is it returning `users` in my use case because I, as the owner, have an entry in the permissions list and `users` is currently the higher precedence?

**Comment by ethanlieNS** [comment]
As @braimondo says, if we could have it our way, it would be nice if we got a complete of the scope from this field or from some other method that doesn't require us walking the permissions.

**Comment by ethanlieNS** [comment]
As @braimondo says, if we could have it our way, it would be nice if we got a complete of the scope from this field or from some other method that doesn't require us walking the permissions.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
