### ISSUE TITLE
File Handlers 2.0 for OWA

### ISSUE THREAD

**Issue by iamrati** [OneDrive/onedrive-api-docs#1223]
@chackman Any information about when File Handlers 2.0 will be available in Outlook Web Access. Also i tried the File Handler 1.0, it works fine in SharePoint Online and OneDrive for Business, however the same is not working in Outlook Web Access. As per the documentation its GA for OWA as well.

**Comment by JeremyKelley** [comment]
This is really a question for the OWA team, will try to find a location to send you to ask them.

**Comment by iamrati** [comment]
@JeremyKelley Would be great if you would do that, thanks in advance!

**Comment by iamrati** [comment]
Hey @JeremyKelley @chackman Any luck with finding the location to send?

**Comment by chackman** [comment]
Sorry about taking so long to reply, we dug up Outlook's UserVoice location, and would recommend that you reach out to them there - https://outlook.uservoice.com/
