### ISSUE TITLE
Is the Filter Statement Incorrect on this Example

### ISSUE THREAD

**Issue by MatthewMcD** [OneDrive/onedrive-api-docs#1226]
The filter statement `/sites?filter=siteCollection/root ne null` uses the "Not equal" operator `ne` but the results show that the root element is null.

Can you include a sample that demonstrates how to get all Site Collections in a tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d2ed0c6-4c40-5d52-51b9-679aed8df5d8
* Version Independent ID: 3b0f9af8-8de0-b7e7-89d6-cc150665ede4
* Content: [Enumerate sites - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_list?view=odsp-graph-online&source=docs#feedback)
* Content Source: [docs/rest-api/api/site_list.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/site_list.md)
* Product: **onedrive**
* GitHub Login: @daspek

**Comment by chackman** [comment]
Unfortunately, this API does not currently provide a way to enumerate all site collections in a tenant.

To clarify, when you are following the example, is the `root` element empty (like below) or null (something different)?

`
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites",
    "value": [
        {
            "webUrl": "https://contoso.sharepoint.com/",
            "siteCollection": {
                "hostname": "contoso.sharepoint.com",
                "root": {}
            }
        }
    ]
}
`
