### ISSUE TITLE
Multipart file upload support for SharePoint's documentLibrary.

### ISSUE THREAD

**Issue by spmanjunath** [OneDrive/onedrive-api-docs#1227]
I was looking for API's that would support updating files to documentSets, and in the same REST call update metadata (custom fields) associated with the uploaded file, similar to [OneDrive personal](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_post_content?view=odsp-graph-online).  Is this feature currently supported for documentLibraries?  

**Note**: In the existing implementation to achieve this two calls are required: first to upload the file (using PUT), and the second call to update metadata (using PATCH).  A single call as it is available in OneDrive Personal is desired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dbb0037-4021-6fea-2188-7116ab176536
* Version Independent ID: 6f542f29-d08c-f1da-f4c6-fc2ad53205b0
* Content: [Upload contents and metadata - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_post_content?view=odsp-graph-online&source=docs)
* Content Source: [docs/rest-api/api/driveitem_post_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_post_content.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback. Unfortunately, this is not supported at the moment in OneDrive for Business / SharePoint. Multipart upload is something on our backlog though.
