### ISSUE TITLE
Downloaded file does not match reported size

### ISSUE THREAD

**Issue by saguiitay** [OneDrive/onedrive-api-docs#123]
I have a PNG image file in my OneDrive.

The API and the Web UI both report that the file is sized 21.9K

When I download the file (via either the UI, or the API), the downloaded file is 8.5K.

When trying to upload the 8.5K file back to OneDrive, it is a gain being reported as a 21.9K file.

I've checked that the file doesn't contain any alternative streams.

You can get the file here: https://onedrive.live.com/redir?resid=82a4826daa392c28!4988&authkey=!AF48zYh_qglwvVg&v=3&ithint=photo%2cpng

**Comment by ificator** [comment]
Hi @saguiitay, this is unfortunately an edge case that has existed in OneDrive for some time. I'll redirect you to [this answer of Ryan's on StackOverflow](http://stackoverflow.com/questions/26906007/onedrive-wrong-size-for-png-files) for details, and I'll reiterate that we're definitely aware of the pain this issue causes and we're making good progress towards its resolution.

**Comment by saguiitay** [comment]
I'm actually facing a similar issue for a DOCX file:

  * Id: 82A4826DAA392C28!4864
  * Name: Document 1.docx
  * Size: 15173

When I download the file (either via the API, or via the web interface), the file size is 12209 bytes.

**Comment by verybada** [comment]
Still facing this issue here. Any suggestion or news?

**Comment by seuffert** [comment]
i am seeing this on a lot of my files - how come this is still an issue?

**Comment by ificator** [comment]
While the issue is trivial at face value, there were complex constraints in the system that unfortunately complicated the path to resolution. Having said that, we've made good progress on relaxing those constraints so we're now in a position we can directly tackle the issue at hand. Hopefully it won't be too much longer!

This is our oldest open issue and we're all very much eager to see it gone :)

**Comment by cguZZman** [comment]
Just facing this issue with a .docx file and causing some failures. Do you have an ETA for the fix?

**Comment by dluces** [comment]
I think we might have just started experiencing this issue today. After uploading a plain text file, the reported file size is 0. However, when using the download URL to download the file, its content is what was expected (non-empty). Our tests started reporting this issue almost consistently starting today.

**Comment by ificator** [comment]
@dluces the issue here is that files are reported to be larger than they actually are, so what you're seeing is something different entirely. There was an issue that occurred today that resulted in some files being recorded as being 0-bytes, but it's now resolved and any files that were put into this state will be repaired in the next day or so.

**Comment by dluces** [comment]
@ificator sounds good, thank you!

**Comment by ificator** [comment]
This issue should finally be resolved - please let us know if you continue to see file sizes being reported as larger than they actually are.

**Comment by gzxu** [comment]
Still encountering the same issue at file `443A255D801D1655!300`: The size displayed in `onedrive.live.com` and the size reported by the API is around 40 KiB, however the downloaded size is just 12 KiB @ificator 

Thank you very much

**Comment by ificator** [comment]
The fix definitely applied to all new / updated files, but I'm not sure if we're expecting people to manually fix existing items in this state by reuploading - I'll follow up and see what the expectations of the fix were.

One option you could try in the mean time to avoid reuploading is to use the `copy` API - that'll essentially reupload but without you incurring any bandwidth costs. Obviously not ideal, but it's the best I can think of while I follow up.

**Comment by gzxu** [comment]
Thank you for your answer, my current workaround is to ignore the `size` values and treat them as all the same :joy: The `copy` API modifies the `id` of items and it may not be suitable for me
