### ISSUE TITLE
UnknownError appears sometimes, using File upload method

### ISSUE THREAD

**Issue by dgsqrs** [OneDrive/onedrive-api-docs#1230]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

The file must be uploaded correctly

#### Observed Behavior

`"error": {
   "code": "UnknownError",
   "message": "",
   "innerError": {
     "request-id": "040f518d-56c9-49b4-9b3e-81cc2e21aa06",
     "date": "2020-03-02T08:45:40"
   }
 }`

#### Steps to Reproduce

Well I can't reproduce the error. It appeared randomly. But if the SAME request is executed again, sometimes, it works.

Thank you.

**Comment by ificator** [comment]
How large is the file that you're uploading? It looks like you're making `PUT` requests to `/content` against Graph, which can have issues if the upload takes longer than 10s. I'd suggest looking at the [resumable file upload](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0) mechanism as it has two advantages for your scenario:
1. If the request fails you can avoid reuploading chunks that were already successfully uploaded
2. The requests that push the content to SharePoint will go directly to SharePoint and therefore not be impacted by Graph timeouts.

**Comment by dgsqrs** [comment]
It is a tiny file, 153 KB. 
I only upload this kind of small files, a few times a day maximum

**Comment by ificator** [comment]
Yeah, I wouldn't expect any issues with a file that size. The logs do suggest Graph waited 10s and then gave up, but it's not clear what caused the delay.

Have you noticed any pattern with these failures? e.g. more often at a particular time of day

**Comment by dgsqrs** [comment]
Well no pattern 'yet'. 
A few more failures :

`
      "request-id": "9a607d5b-5e28-4228-a6c3-f377865b585f",
      "date": "2020-01-24T16:45:22"
      "request-id": "5e61af5f-bedc-4dad-80a1-0e8be106f2c8",
      "date": "2020-01-28T18:45:37"
      "request-id": "bc68b10f-3723-4fe5-97cb-25d4822a0f1f",
      "date": "2020-02-12T08:45:22"
"request-id": "040f518d-56c9-49b4-9b3e-81cc2e21aa06",
      "date": "2020-03-02T08:45:40"
`
This error came too. Maybe it was because I was logged at several location using the same account ?
`"error": {
    "code": "accessDenied",
    "message": "The caller does not have permission to perform the action.",
    "innerError": {
      "request-id": "2c8486b4-1187-4081-b0f7-c8fec5ca1399",
      "date": "2020-03-01T19:45:17"
    }
  }`

The cron task is executed each hours, but there are 0-10 files per day uploaded, maximum.

Should I use the async method and wait until upload completion ?

**Comment by dgsqrs** [comment]
This is right now. My app automatically try a second time if this error is detected. The second time, it worked. The request is exactly the same, but the token might have been refreshed I suppose.

```
"error": {
    "code": "accessDenied",
    "message": "The caller does not have permission to perform the action.",
    "innerError": {
      "request-id": "62937b19-c9b7-401e-abe9-4dac675b2da3",
      "date": "2020-03-02T18:45:13"
    }
  }
```

This error has been detected the first time on this request. Previously I only had those 'Unknown Errors'
`"request-id": "b5c2685e-7fd9-4ec5-ba9c-45faf612a984",^M
      "date": "2020-02-29T12:45:13"^M`

**Comment by ificator** [comment]
The only thing async will give you in this case is that if the upload takes a long time for some reason it won't get aborted at 10s like it will through Graph. That'll give you some resilience while we try to see what's causing the delay.

**Comment by dgsqrs** [comment]
> The only thing async will give you in this case is that if the upload takes a long time for some reason it won't get aborted at 10s like it will through Graph. That'll give you some resilience while we try to see what's causing the delay.

Well I can wait and help you debug something needed. I try to reproduce this bug for weeks before submitting this ticket.

**Comment by dgsqrs** [comment]
I have detected no issue for 2 days now, have you made some investigations ?

**Comment by ravi100k** [comment]
I am hitting the similar issue while one drive upload.
```
2020-12-03 12:40:41.02107 error {
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-12-03T20:40:44",
      "request-id": "15ce7631-0d5f-431d-9a7f-3a6a7eedd0bc",
      "client-request-id": "15ce7631-0d5f-431d-9a7f-3a6a7eedd0bc"
    }
  }
} error=400
```
Notes:
1. It is not specific to any file type.
2. Only hitting this issue while generating an upload session for the files.
URL (https://graph.microsoft.com/v1.0/users/%s/drive/root:/%s:/createUploadSession)

**Comment by ificator** [comment]
Hi @ravi100k - how long is the value of the path in your upload URL? Unfortunately there isn't much in the way of telemetry generated for this failure and so we're left taking some shots in the dark.

**Comment by ravi100k** [comment]
@ificator the file path is around 311 character long.
So the total url length is around 388 character long.

**Comment by ificator** [comment]
Thanks @ravi100k, that should definitely be ok. Is there anything special about the path that comes to mind? Unicode chars etc? Can you make it work with other paths?

**Comment by ravi100k** [comment]
@ificator I dont see any regular pattern in this case.
I have tried to upload different types of files of different length.
```
nupkg 14 UnknownError
war 7 UnknownError
html 2 UnknownError
jar 6 UnknownError
```
These many error have been received while trying to upload file via graph API.
Though the different files in the same folder is getting successfully uploaded, of same type.

I have trying to upload 2 lakh files in a chunk of 4 files at a time.
With retry for error like 429, 503, 500 status code.

**Comment by ificator** [comment]
Is it possible to provide an example of one of the paths that's failing? Feel free to obfuscate by replacing a-z=>a A-Z=A 0-9=0 but leave all symbols / % encoded stuff alone so that I can see the structure

**Comment by ravi100k** [comment]
Test Fail
Note : **regex used [a-z] replace to a**
`1. aaaaaa_20201203_042846446/aaaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaa_20201121_2314331133/aaaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaa_20201110_020842242/aaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaaaaaaaaaaa2/aaaaaaaa/aaaaaaaaaaa/aaa2/aaa2aa-5.0.0/aaaaaaaaaa/aaaaaaaaaa/aaaaaa/aaaaaaa/aaaaaaa/aaa-aaa/aaa/aaa4a-4.8.1.1.aaa
2. aaaaaaa_20201203_042846446/aaaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaa_20201121_2314331133/aaaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaa_20201110_020842242/aaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaaaaaaaaaaa2/aaaaaaaa/a2a/aaaaaa/aaaaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaaaaaaaa/aaaaaa-aaaaaa-aaaaaa-aaaaaaaa/aaa-aaaaaaa-aaaaaa.aaa
3. aaaaaaa_20201203_042846446/aaaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaa_20201121_2314331133/aaaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaa_20201110_2228531053/aaaaaa@aaaaaaaa.aaaaaaaaaaa.aaa/aaaaaaaaaaaaaaaa2/aaaaaaaa/a2a/aaaaaa/aaaaaaaaaaaaaa/aaaaaaaaaaaaaa/aaaaaaaaaaaaaaa/aaaaaaaa/aaaaaaaaa.aaaaaaa.2.0.0/aaaaaaaaa.aaaaaaa.2.0.0.aaaaa
`

These are the folder+file path

**Comment by ificator** [comment]
Hi @ravi100k, I had a chance to look into this today and I believe there are two issues:
1. Those are long paths, and there's a limit of 400 for the overall path (see [this page for clarification](https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-us&rs=en-us&ad=us#filenamepathlengths)) - I believe you're hitting this and triggering an error
1. The way this specific type of error is processed in the service is buggy and ends up returning a 400 without a body to Graph - when Graph doesn't see a body it will default the code to `Unknown`

I'll see what we can do to fix the error response.

**Comment by ravi100k** [comment]
@ificator thanks for the investigation.
But I am able to put the files in the same long directory, it just fail in some cases.
If I assume the above issue to be true.
Do we have any work around for this?

**Comment by ificator** [comment]
The easiest solution will be to use the id of the parent instead of the full path:
```
https://graph.microsoft.com/v1.0/me/drive/items/parentid:/file.txt:/createUploadSession
```

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
