### ISSUE TITLE
POST /me/drive/items/{itemId}/createUploadSession fails without edit permissions on parent folder.

### ISSUE THREAD

**Issue by mjyeaney** [OneDrive/onedrive-api-docs#1231]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

When creating a large-file upload sessions via `createSession` on a shared file within a nested folder, user should NOT have to have full control / edit permissions on the parent folder (note this bug is for nested folders, not the root).

#### Observed Behavior

When a user creates a nested folder below the OneDrive root, and does NOT grant permissions to anyone else in the organization, calls to `createSession` on a shared file contained in that folder will correctly return a 200; however upon attempting to use this upload session, callers will receive a 404 (Not Found) error stating that the upload session does not exist.

Granting permissions on the files' parent folder (tested with 'edit' and 'full' permissions) cause `createUploadSession` to begin working correctly.

It is not currently documented that these permissions are required.

#### Steps to Reproduce

* Create a nested folder below the OneDrive root.
* Do NOT grant any permissions to that folder beyond the current user (call this 'USER A')
* Create a simple file in that nested folder (i.e., Excel document).
* Grant access to that file to another user (call this 'USER B')
* Issue a call to `createUploadSession` as 'USER B'.
    * Note this will return a 200 OK
    * However, when attempting to use this upload session, you will receive an error.
    * Granting 'full' or 'edit' permissions to 'USER B' on the containing folder will fix this issue, but it is not clear if this is required or a bug.

**Comment by JeremyKelley** [comment]
Thanks for reporting this issue, we have verified that it is indeed a bug and we're evaluating the right fix for it.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
