### ISSUE TITLE
Problems with drive-item preview in outlook web-addin iframe

### ISSUE THREAD

**Issue by sjkp** [OneDrive/onedrive-api-docs#1232]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

We are using the drive-item preview functionality(https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online)  from within an iframe (specifically in an outlook web addin). We would assume that this should just work. But unfortunately when we try to preview *.msg files, it nothing gets rendered. It works for other file types that we have tried with. 

#### Observed Behavior

The *.msg content doesn't get rendered. We have investigated the source files from the embed.aspx preview page, and it seems to be due to the following highlighted code 
![image](https://user-images.githubusercontent.com/3397744/75713566-56585480-5cca-11ea-89f6-d237cf2e503f.png)

For some reason the javascript on the embed.aspx page checks the HTMLIframeElement.prototype for the existance of the "srcdoc" - probably to trigger some behavior that I don't understand why should be triggered with this arcane check. I believe that this checks fails for security reasons when running within the outlook web addin pane. 

#### Steps to Reproduce

Environment info: 
Windows Build 1909 (18363.657) 
Outlook Version 2002 (Build 12527.20194)
Edge Browser (used by outlook webaddin, capture with navigator.userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363  

1. Get the embed link to an msg file, e.g. in your one drive (I use the graph explorer tool) 
This is a sample URL from my tenant, a POST request to: https://graph.microsoft.com/v1.0/drives/b!bdMt6Qi5d02F-Q3iATwwZTW0pSJRMkNLuEBVvebKx9PMx0_7Xc8fRal9JtSlK12h/items/01QZXOES4VM7MUS7WBOFCIPASZW22R3ZPT/preview
Returns an embed URL
2. Create an ourlook addin in VS and add an iframe to the html with the embed url 
![image](https://user-images.githubusercontent.com/3397744/75723902-85c48c80-5cdd-11ea-8cf6-993036a9bf2e.png)
3. Now open the addin in outlook and see nothing rendered in the iframe
![image](https://user-images.githubusercontent.com/3397744/75723995-b4dafe00-5cdd-11ea-80e8-64c240d4925d.png)
4. If you open the same embed link in a browser (also in an iframe) it works fine
![image](https://user-images.githubusercontent.com/3397744/75724164-1307e100-5cde-11ea-9581-7a004c540a69.png)

**Comment by sjkp** [comment]
@chackman  are there any update on the status of this?

**Comment by chackman** [comment]
Following up internally with a partner team.

**Comment by hemantha-ponnuru** [comment]
This issue should be fixed from the product side now and should be considered completed. Please let us know if you are still reproducing the issue.
