### ISSUE TITLE
Does ratelimits on OD graph API is per URI or not? 

### ISSUE THREAD

**Issue by puneettrehan** [OneDrive/onedrive-api-docs#1233]
We are currently experiencing issue right now where we have client which fetches meta-data and content from the cloud. Right now whenever we receive 429 on any URI( permissions, content, itemid) we pause all our threads for retry-after value returned in the API call. I am not sure whether that is correct approach or not. We have seen that we are getting very low API limits because of this. Can you please give us some guidelines that if 429 comes on /permissions URI then should we still keep making call to /content API or not

#### Category
- [ ] Question

**Comment by puneettrehan** [comment]
@chackman Can you please help in this?

**Comment by chackman** [comment]
Thanks for your feedback.  Yes, we recommend [pausing other requests](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#what-happens-when-you-get-throttled).  (Link from our scan guidance docs at aka.ms/scanguidance)
