### ISSUE TITLE
Feature Request: Get path in parentReference from search result

### ISSUE THREAD

**Issue by sven5** [OneDrive/onedrive-api-docs#1234]
We're using OneDrive for Business.
When searching for files in Graph API, the `parentReference` does not include the path string. Is there any reason for this limitation?
Example:
`GET https://graph.microsoft.com/v1.0/me/drive/root/search(q='finance')?select=name,parentReference`

returns
```
 {
            "@odata.type": "#microsoft.graph.driveItem",
            "name": "CR-227 Product Overview.pptx",
            "parentReference": {
                "driveId": "b!-RIj2DuyvEyV1T4NlOaMHk8XkS_I8MdFlUCq1BlcjgmhRfAj3-Z8RY2VpuvV_tpd",
                "driveType": "business",
                "id": "01BYE5RZ6TAJHXA5GMWZB2HDLD7SNEXFFU"
            }
        },
```

Another way would be to $expand the parentReference, but I had no luck. 
`https://graph.microsoft.com/v1.0/me/drive/root/search(q='coffee')$expand=parentReference`
produces a 400 BadRequest

**Comment by chackman** [comment]
Thanks for your feedback, we're looking into feasibility of this request.

**Comment by chackman** [comment]
We've placed this item on our backlog.  We would recommend that you also consider going to UserVoice as we consider that feedback in prioritizing future work.  Thanks!

**Comment by vikasprabhakar** [comment]
@chackman , is the new "path" field added in "parentReference"?
I'm still not getting the "path" of parentReference in search api.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
