### ISSUE TITLE
404 ItemNotFound using Upload Sessions

### ISSUE THREAD

**Issue by arsnyder16** [OneDrive/onedrive-api-docs#1237]
# Bug Report

## Prerequisites

-   [X ] Can you reproduce the problem?
-   [X ] Are you running the latest version?
-   [ X] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

If one of my users shares a file from their one drive to another user with write permissions, but does not share the folder the file is contained then anything time the uploadUrl from a createUploadSession is used they receive a 404 "ItemNotFound". This includes trying to delete the uploadsession.

If using the standard upload for small files <4MB these scenarios work fine. If the user shares the folder that the file is contained then the upload sessions seem to work as expected.

My suspicion is that an upload session is simply creating a temporary file to upload to, but when that temporary file is created the permissions are not transferred from the original file, hence being invisible(404) to all users other than the users who have access to the parent folder.

**Console Errors:** [Is there any console error]

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Share file from one user to another that is contained within a folder
2. Have the other user attempt to upload new content to the file using an upload session

**Expected behavior:**
Using the uploadUrl works

**Actual behavior:** 
Anytime the uploadUrl is used even trying to delete the upload url the server responds with 404 ItemNotFound

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please clarify whether this issue reproduces in OneDrive Personal or OneDrive for Business?

Also could you please provide the following response headers corresponding to your request(s) that resulted in a 404:
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by arsnyder16** [comment]
@chackman 

`OneDrive for Business`

Upload Session creation:
`Date: Wed, 11 Mar 2020 17:08:40 GMT`
`client-request-id: ce03a58e-9f16-9ac5-8bf5-8cc040756be2`
`request-id: d800a19b-2520-4832-b195-a3b8da6b01d4`

Failed PUT on the uploadUrl
`date: Wed, 11 Mar 2020 17:08:44 GMT`
`request-id: ebcb3d9f-e0f3-9000-7eb6-30555a5ada05`
`sprequestguid: ebcb3d9f-e0f3-9000-7eb6-30555a5ada05`
Response:
`{"error":{"code":"itemNotFound","message":"The resource could not be found."}}`

Failed DELETE on the uploadUrl
`date: Wed, 11 Mar 2020 17:08:44 GMT`
`request-id: ebcb3d9f-30fd-9000-5c9a-58faa1091715`
`sprequestguid: ebcb3d9f-30fd-9000-5c9a-58faa1091715`
Response:
`{"error":{"code":"itemNotFound","message":"The resource could not be found."}}`

**Comment by chackman** [comment]
Thanks for the additional information.  We'll put this issue on our backlog to address.  Thanks!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
