### ISSUE TITLE
What is the limit of copy action?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1238]
I find it can copy some folders but cannot copy other folders. What is the limit of the copy action? The total size or the total file count?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38d3dcf-49bd-eedc-e4cf-5041af8ed7fe
* Version Independent ID: 8a3d3fed-4e6c-0592-5f7c-8105365698d8
* Content: [Copy a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_copy.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_copy.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback. We are working on improving the documentation and also filling gaps in.  I've tagged this as a docs bug for us to clarify further.

**Comment by landall** [comment]
Thank you. It confuses me that the copy api sometimes works sometimes not.

**Comment by Dibbyo456** [comment]
I tried to copy a 3 TB folder, did not work.
Copying files large files (3-4gb) also does not work.

**Comment by JeremyKelley** [comment]
Clarifying question, is this for SharePoint, OneDrive for Business, or OneDrive consumer?

**Comment by Dibbyo456** [comment]
OneDrive for Business

**Comment by landall** [comment]
> Clarifying question, is this for SharePoint, OneDrive for Business, or OneDrive consumer?

both Onedrive for business and SharePoint.

**Comment by greenygh0st** [comment]
I believe I am encountering this same issue with OneDrive for business. It seems that files over an undocumented size fail and the API provides a very generic error message with little information to go to resolve the issue.

{
  "error": {
    "code": "invalidRequest",
    "message": "Invalid request",
    "innerError": {
      "request-id": "<request id here>",
      "date": "2020-04-22T03:40:03"
    }
  }
}

**Comment by Dibbyo456** [comment]
@chackman Any update on this? Can you specify copy limitation for OneDrive for Business ?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
