### ISSUE TITLE
It confuses me when I copy a folder and monitor the copy progress

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1239]
I copy a folder to some place, the monitor url shows the copy is completed, but in fact it is far from finishing. How can I know the real progress of a folder clone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38d3dcf-49bd-eedc-e4cf-5041af8ed7fe
* Version Independent ID: 8a3d3fed-4e6c-0592-5f7c-8105365698d8
* Content: [Copy a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_copy.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_copy.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Could you please clarify some things?
- is this issue in OneDrive for Business or OneDrive Personal
- could you provide an example of how the copy is perceived to be "far from finishing" - does the web site not show the items in the destination, for example?

**Comment by landall** [comment]
> Could you please clarify some things?
> 
> * is this issue in OneDrive for Business or OneDrive Personal
> * could you provide an example of how the copy is perceived to be "far from finishing" - does the web site not show the items in the destination, for example?
* It is a issue of OneDrive for Business.
* I copy a folder of 40GBytes. The monitor url shows the task is completed but I can just see the first file of 600MBytes there, sometimes I can see the second file only with 0 byte (it is a 14GBytes file). The copy progress is going on for at least 5 hours now.

**Comment by chackman** [comment]
Could you please clarify whether the copy is within the same site, or across sites?  Could you please provide correlation ID's for the request that created the job, and for the subsequent monitor URL request that claims completion but isn't complete?

**Comment by landall** [comment]
Excuse me, What is the  correlation ID?
----------------------------------------------
This is a Copy job within the same site.  8 files in all, the status of the monitor url become completed after the first file copied.

https://lolitaup-my.sharepoint.com/personal/admin_lolitaup_onmicrosoft_com/_api/v2.1/drive/operations/966ffe3a-a8d8-49cb-b58c-ffd69753e8e3?c=aWlyRUh0WmszQ2ZxcmRiTWhSM0xwT1ZnaEdjRGJlY3d2WUd4b3NjS0liVT0jaHR0cHM6Ly9zcG9zZzFoazFtMDA1cHIucXVldWUuY29yZS53aW5kb3dzLm5ldC8xMTQwcHEyMDIwMDMyOS02ZGM1ZjA1ZmZmNWY0OGE0OGZhZTFhYmY0YzlkNThlYT9zdj0yMDE3LTA3LTI5JnNpZz1sSUZwZHRnbVo2NUtudnVkTjB0UmVJcVNQWFdlOFFoJTJCQ3FNMUZhQ1BCY2clM0Qmc3Q9MjAyMC0wMy0yOFQwMCUzQTAwJTNBMDBaJnNlPTIwMjAtMDQtMTlUMDAlM0EwMCUzQTAwWiZzcD1yYXA&v=2.0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbG9saXRhdXAtbXkuc2hhcmVwb2ludC5jb21ANjM1OGQyMDktNTdhZi00MjQ1LTgxNzItOTUzNTA5NTFiODlmIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU4NTQ5MDc0MyIsImV4cCI6IjE1ODU1NzcxNDMiLCJlbmRwb2ludHVybCI6IlVvOVN4ODBVc3dRUDA3Wmd2VGdTR3NFaDBVZHIvVFRHa1IyMlhJUmMrOFE9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiI1MDYiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik0ySmxOMlEwWkRVdE56ZGxOQzAwWkRjeExXRmlNV010WmpjM05qRXlNVGxsTnpNeCIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJORFl6WmpRM1pqa3RNMk16WkMwMFpqSmxMV0ZpTWpRdE9EQTVaVGN5WlRZd1lqQmgiLCJhcHBfZGlzcGxheW5hbWUiOiJPbmVEcml2ZUluZGV4KE9ESSkiLCJmYW1pbHlfbmFtZSI6IkNoaSIsImFwcGlkIjoiZTZmNDI3NWQtOWJkZi00NDYxLWI0MzYtMWJjMjY1ZDMyMjE4IiwidGlkIjoiNjM1OGQyMDktNTdhZi00MjQ1LTgxNzItOTUzNTA5NTFiODlmIiwidXBuIjoiYWRtaW5AbG9saXRhdXAub25taWNyb3NvZnQuY29tIiwicHVpZCI6IjEwMDMyMDAwNDVBMjQ5RUUiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMDQ1YTI0OWVlQGxpdmUuY29tIiwic2NwIjoibXlmaWxlcy5yZWFkIGFsbGZpbGVzLnJlYWQgbXlmaWxlcy53cml0ZSBhbGxmaWxlcy53cml0ZSBncm91cC5yZWFkIGFsbHNpdGVzLndyaXRlIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.U2lOV25FSklmeUdCQnJBWlA0YzBqUCtGY0NIeFpOcHpmNVBYTXd0QkZtaz0

**Comment by landall** [comment]
I get a 500 error when copying a folder accross sites in the same tenant.

**Comment by chackman** [comment]
Regarding your question about how to get a correlation ID, it's in the response headers, I'll tag for our helpful bot to fill in more.

**Comment by landall** [comment]
HTTP/1.1 202 Accepted
Cache-Control: private
Content-Type: text/plain
Location: https://lolitaup-my.sharepoint.com/personal/admin_lolitaup_onmicrosoft_com/_api/v2.1/drive/operations/765c944e-109f-4a25-b993-0b756c8219e3?c=MDFzMFQzMFZTRmhvdkUwVHN3cUlQWG1Jb0VrbloyRnowM2o4Zzc3d0RHbz0jaHR0cHM6Ly9zcG9zZzFoazFtMDM0cHIucXVldWUuY29yZS53aW5kb3dzLm5ldC8xMTQwcHEyMDIwMDQwMy02ZDY0ZjMyMjFmNTM0NDZjOTkyZmE2NjA2MzQyMTE3MT9zdj0yMDE3LTA3LTI5JnNpZz03JTJCaDJVU2IxS053RjdNckdCbm91eU0zWFo5NTVyWjZKTkxuaWV2bHdzYTAlM0Qmc3Q9MjAyMC0wNC0wMlQwMCUzQTAwJTNBMDBaJnNlPTIwMjAtMDQtMjRUMDAlM0EwMCUzQTAwWiZzcD1yYXA&v=2.0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbG9saXRhdXAtbXkuc2hhcmVwb2ludC5jb21ANjM1OGQyMDktNTdhZi00MjQ1LTgxNzItOTUzNTA5NTFiODlmIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU4NTkyNjc2MCIsImV4cCI6IjE1ODYwMTMxNjAiLCJlbmRwb2ludHVybCI6ImNPVFFzTnUyLzRTOFhVbURLL1RRV1U1QXJZRFQxMjI1dmthbW1sR0Q1Vnc9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiI1MDYiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik5UUXlOVEprWmpVdFpHTTNZaTAwWlRCbExXSTNaRFF0WVdZM01XTTFNVGN3TVdFeiIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJORFl6WmpRM1pqa3RNMk16WkMwMFpqSmxMV0ZpTWpRdE9EQTVaVGN5WlRZd1lqQmgiLCJhcHBfZGlzcGxheW5hbWUiOiJPbmVEcml2ZUluZGV4KE9ESSkiLCJmYW1pbHlfbmFtZSI6IkNoaSIsImFwcGlkIjoiZTZmNDI3NWQtOWJkZi00NDYxLWI0MzYtMWJjMjY1ZDMyMjE4IiwidGlkIjoiNjM1OGQyMDktNTdhZi00MjQ1LTgxNzItOTUzNTA5NTFiODlmIiwidXBuIjoiYWRtaW5AbG9saXRhdXAub25taWNyb3NvZnQuY29tIiwicHVpZCI6IjEwMDMyMDAwNDVBMjQ5RUUiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMDQ1YTI0OWVlQGxpdmUuY29tIiwic2NwIjoibXlmaWxlcy5yZWFkIGFsbGZpbGVzLnJlYWQgbXlmaWxlcy53cml0ZSBhbGxmaWxlcy53cml0ZSBncm91cC5yZWFkIGFsbHNpdGVzLndyaXRlIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.NGFEb2FVR1l5UmJlUFN4SnlmN0hsRThwVXRvMFlXYytETGFubzg0eXpiVT0
request-id: 54252df5-dc7b-4e0e-b7d4-af71c51701a3
client-request-id: 54252df5-dc7b-4e0e-b7d4-af71c51701a3
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Southeast Asia","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_19"}}
Strict-Transport-Security: max-age=31536000
Date: Fri, 03 Apr 2020 15:12:40 GMT
Content-Length: 0

This request goes to fail, I will track if it is copying the files.
Array
(
    [@odata.context] => https://lolitaup-my.sharepoint.com/personal/admin_lolitaup_onmicrosoft_com/_api/v2.1/$metadata#drives('default')/operations/$entity
    [id] => 765c944e-109f-4a25-b993-0b756c8219e3
    [createdDateTime] => 0001-01-01T00:00:00Z
    [lastActionDateTime] => 0001-01-01T00:00:00Z
    [status] => failed
    [error] => Array
        (
            [code] => generalException
            [message] => General exception while processing
        )

)

**Comment by chackman** [comment]
Thanks, this sounds like an issue that we'll put on our backlog to address. Thanks!

**Comment by landall** [comment]
Wish it will be fixed and documented.
Batch-copy can save a lot of time because it takes a long time to send one request to the endpoint server.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
