### ISSUE TITLE
Upload Small Files Docs incorrect - requires json and not plain/text

### ISSUE THREAD

**Issue by yosun** [OneDrive/onedrive-api-docs#1241]
#### Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

According to https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online

This example shown in the docs link above should work: 

PUT /me/drive/root:/FolderA/FileB.txt:/content
Content-Type: text/plain

The contents of the file goes here.

#### Observed Behavior

Trying that put command with the plain/text file in the body, I receive this error: 

{
  "error": {
    "code": "BadRequest",
    "message": "Entity only allows writes with a JSON Content-Type header.",
    "innerError": {
      "request-id": "ae11f389-bd2a-4c6a-b4e5-883a8f18410d",
      "date": "2020-03-12T15:25:16"
    }
  }
}

#### Steps to Reproduce

1. Postman  PUT address: https://graph.microsoft.com/v1.0/me/drive/items/root:/[folder name]:/testpostman.txt/content
2. Set Authorization Bearer authtoken and Content-Type: text/plain
3. specify content to write in body

(replace [folder name] with folder name

**Comment by chackman** [comment]
The colon needs to be at the end of the file path, including filename.

Please try this URL (note that the colon has moved from after `[folder name]` to after `testpostman.txt`)
https://graph.microsoft.com/v1.0/me/drive/items/root:/[folder name]/testpostman.txt:/content
