### ISSUE TITLE
Can't get the item id after upload a new file.

### ISSUE THREAD

**Issue by XIAZHI1978** [OneDrive/onedrive-api-docs#1243]
When I successful upload a file  with following api
https://graph.microsoft.com/v1.0/sites/abc78c05-a77b-45bf-a1a1-51f09548b497/drive/root:/test1212123.txt:/content
the response data did not contains the item id which is need by following api.
https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-di}/fields

How can I get it after upload a file to sharepoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350cd850-d19a-ef5c-2761-e342fc3c506c
* Version Independent ID: 5bf3ef39-f20a-6c7f-77f6-3bc7e9d246f4
* Content: [Upload small files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_put_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_put_content.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Could you please clarify which item ID you are referring to?
Have you selected the `sharePointIds` property on the upload request?
example:
`https://graph.microsoft.com/v1.0/me/drive/root:/Test%20Folder/FileD.txt:/content?$select=id,name,sharePointIds`
