### ISSUE TITLE
Invalid quota returned

### ISSUE THREAD

**Issue by cristian-vescan** [OneDrive/onedrive-api-docs#1245]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Observed Behavior
Calling *https:/......sharepoint.com/_api/v2.0/drive* for OneDrive for Business returns invalid Quota.
It will always be 
```
"quota": {
		"deleted": 0,
		"remaining": 0,
		"total": 0,
		"used": 0
	}
```
#### Steps to Reproduce
Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer/preview)
Run query for `https://graph.microsoft.com/v1.0/me/drive`

Thank you.

**Comment by chackman** [comment]
This appears to work when trying this out; could you please provide more information?

**Comment by cristian-vescan** [comment]
Hello,
Please use a OneDrive for Bussiness account.
This is the response I got now for  https://graph.microsoft.com/v1.0/me/drive
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives/$entity",
    "createdDateTime": "2016-04-27T12:10:21Z",
    "description": "",
    "lastModifiedDateTime": "2019-04-18T15:22:11Z",
    "name": "OneDrive",
    "webUrl": "https://softland-my.sharepoint.com/personal/backup_softland_onmicrosoft_com/Documents",
    "driveType": "business",
.......  
  },
    "quota": {
        "deleted": 0,
        "remaining": 0,
        "total": 0,
        "used": 0
    }
}
```

**Comment by kingcpro** [comment]
Encounter same issue.  The test account is also business account. However, the response of https://graph.microsoft.com/v1.0/me/drive is different between Graph Explorer and Test App.

Graph Explorer:
```
{
   ......
   "quota": {
        "deleted": 0,
        "remaining": 1099150825664,
        "state": "normal",
        "total": 1099511627776,
        "used": 8077753
    }
}
```

Test App:
```
{
    ......
    "quota": {
        "deleted": 0,
        "remaining": 0,
        "total": 0,
        "used": 0
    }
```

The Test App is Python Code Sample from [Official Portal](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-python-webapp). 
I tried below Permissions:
 * Files.Read.All
 * Files.ReadWrite.All
 * Sites.Read.All
 * Sites.ReadWrite.All

PS:
The Test App can work well one week ago. However, it seem there are something wrong at your backend recently.

**Comment by Dibbyo456** [comment]
I'm having the exact same issue (OneDrive for Business).

**Comment by chackman** [comment]
Could you please provide request ID's corresponding to the requests that are not working as expected? 
I'll tag so our helpful bot will provide some additional information.

**Comment by cristian-vescan** [comment]
> Could you please provide request ID's corresponding to the requests that are not working as expected?
> I'll tag so our helpful bot will provide some additional information.

I just run the query again

The request-id is    `15b94868-27b9-45b9-9bef-d9d982c7156d`
The full response headers from Graph Explorer
```
    "cache-control": "private",
    "client-request-id": "e1ad90eb-d6d6-c674-8b83-6c4e5a97d6a8",
    "content-length": "587",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
   "request-id": "15b94868-27b9-45b9-9bef-d9d982c7156d"
```

**Comment by Dibbyo456** [comment]
> Could you please provide request ID's corresponding to the requests that are not working as expected?
> I'll tag so our helpful bot will provide some additional information.

```
Request-Id: a78b2c5c-98b1-497c-b747-22e07eb776d1
```

**Response**:

```
{".... ,"quota":{"deleted":0,"remaining":0,"total":0,"used":0}}
```

**Comment by Dibbyo456** [comment]
@chackman Any update on this?

**Comment by chackman** [comment]
Thanks.  We have enough information to investigate.  I've tagged it as "investigating".

**Comment by chackman** [comment]
We believe we've identified the issue, and have made a change which appears to address it.  Could you please also confirm that it's been addressed?

**Comment by Dibbyo456** [comment]
Yup. Looks like the issue resolved. Thank you.

**Comment by cristian-vescan** [comment]
It works for us also

**Comment by jgalmeida** [comment]
Hello,

I'm also getting this problem.

GET `/https://graph.microsoft.com/v1.0/me/drives`

```
"quota": {
    "deleted": 0,
    "remaining": 0,
    "total": 0,
    "used": 0
}
```

```
{
    "cache-control": "private",
    "client-request-id": "693b258a-c980-5224-94c6-91e09dc58ffc",
    "content-length": "583",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "f903c832-43e8-4bef-8f43-26140337859f"
}
```
