### ISSUE TITLE
Clarification re: alternate data streams

### ISSUE THREAD

**Issue by amtopel** [OneDrive/onedrive-api-docs#1246]
Hi, I was hoping to get clarification on something.  Can we use the OneDrive API to write and upload alternate data streams for a file?  The docs [say](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/upload?view=odsp-graph-online) that for files, "The default stream represents the contents of the file. Other streams may be used to represent item thumbnails or alternative data formats."  So let's say I have doc called example.docx, and I'd like to add an alternate data stream called example.docx:mystream.  Is it possible to set that and upload it?  Will OneDrive sync it and not overwrite it?  Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350cd850-d19a-ef5c-2761-e342fc3c506c
* Version Independent ID: 5bf3ef39-f20a-6c7f-77f6-3bc7e9d246f4
* Content: [Upload small files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online#request-body)
* Content Source: [docs/rest-api/api/driveitem_put_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_put_content.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback. This is not currently supported. We'd recommend requesting this over UserVoice, links to do so are here:
>
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.
