### ISSUE TITLE
microsoft.graph.sharedChanged not returned in certain condition. 

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-api-docs#1248]
Steps To Reproduce 

1. Get The latest delta token for the user with Prefer: hierarchicalsharing and Prefer: deltashowsharingchanges
2. Create a folder with no sharing on the folder or any of its parent
3. Add a user with direct access to the the folder
4. Fetch the latest changes for the user using delta changes with Prefer: hierarchicalsharing and Prefer: deltashowsharingchanges. The drive item returned has @microsoft.graph.sharedChanged set to true
5. Remove the direct access for the user from the folder
6. Fetch the latest changes for the user using delta changes

The drive item returned in the step 6 @microsoft.graph.sharedChanged is not returned.

Expected behavior

The drive item returned in the step 6, should have  @microsoft.graph.sharedChanged set to true

**Comment by agrankur** [comment]
@chackman @JeremyKelley Would you need any info from my side? Also is there any recommended alternatives? or any additional flags to be sent for getting this info?

**Comment by maksle** [comment]
Is there a plan to fix this? The whole sharing headers thing is useless due to this bug, and this bug is almost a year old now.
@chackman @JeremyKelley 

I have run into the same bug when using these Prefer headers:
`deltashowsharingchanges, deltashowremovedasdeleted, deltatraversepermissiongaps`

**Comment by AmitFidler** [comment]
Hi @JeremyKelley following our talk, This could help us out as well! 
Any plan of handling this issue?
Thanks!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
