### ISSUE TITLE
driveItem does not contain shared: { "scope": "users"}

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-api-docs#1249]
1. Get a latest delta token with Prefer: hierarchicalsharing and Prefer: deltashowsharingchanges
2. Upload a file in a shared folder
3. Fetch the changes using the delta token with the headers Prefer: hierarchicalsharing and Prefer: deltashowsharingchanges
4. driveItem does not contain shared: { "scope": "users"}
5. Fetch the Drive Item fr the uploaded file with the header Prefer: hierarchicalsharing and Prefer: deltashowsharingchanges
6. driveItem  contain shared: { "scope": "users"}

Expected Behavior:
driveItem in step 4 should contain shared: { "scope": "users"}

**Comment by agrankur** [comment]
@chackman @JeremyKelley Would you need any info from my side? Also is there any recommended alternatives? or any additional flags to be sent for getting this info?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
