### ISSUE TITLE
Files inheriting permissions do not show in delta query

### ISSUE THREAD

**Issue by bmiller-ns** [OneDrive/onedrive-api-docs#1250]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
According to the [docs](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#scanning-permissions-hierarchies):

> By default, the delta query response will include sharing information for all items in the query that changed even if they inherit their permissions from their parent and did not have direct sharing changes themselves

For a directory `dir1` containing `fileA`, changing the permission on `dir1` should show `fileA` in the GET /delta response.

#### Observed Behavior
Changing permission on a directory does not produce items in the GET /delta query response for files inheriting the directory permission.

#### Steps to Reproduce

1. Create directory `dir1`
1. Create `fileA` in `dir1`
1. Get the latest delta token via `GET /users/{userId}/drive/root/delta?token=latest`
1. Create a shareable link on `dir1` giving everyone with the link access.
1. Get the latest changes via `GET /users/{userId}/drive/root/delta?token=<token from step 3>`
1. `fileA` is not included in the respone

```
> GET /users/{userId}/drive/root/delta?token=<token from step 3>
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
  "@odata.deltaLink": "...",
  "value": [
    {
      "@odata.type": "#microsoft.graph.driveItem",
      "name": "root",
      ...
    },
    {
      "@odata.type": "#microsoft.graph.driveItem",
      "name": "dir1",
      ...
    }
  ]
}
```

**Comment by bmiller-ns** [comment]
Interestingly, if an additional step is included to add a sharing link to `fileA`, then immediately delete it, `fileA` begins to show up in the GET /delta response:

1. Create directory `dir1`
1. Create `fileA` in `dir1`
1. **NEW STEP** Create a shareable link on `fileA`, then delete it.
1. Get the latest delta token via `GET /users/{userId}/drive/root/delta?token=latest`
1. Create a shareable link on `dir1` giving everyone with the link access.
1. Get latest changes via `GET /users/{userId}/drive/root/delta?token=<token from step 4>`
1. `fileA` **_is_** included in the respone

```
> GET /users/{userId}/drive/root/delta?token=<token from step 4>
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
  "@odata.deltaLink": "...",
  "value": [
    {
      "@odata.type": "#microsoft.graph.driveItem",
      "name": "root",
      ...
    },
    {
      "@odata.type": "#microsoft.graph.driveItem",
      "name": "dir1",
      ...
    },
    {
      "@odata.type": "#microsoft.graph.driveItem",
      "name": "fileA",
      ...
    }
  ]
}
```

It seems step 3 caused `fileA` to take on "Unique Permissions" according to the "Manage Access" -> "Advanced" section of `fileA`. If step 3 does not occur this same "Advanced" section shows "This document inherits permissions from its parent. (dir1)".

**Comment by JeremyKelley** [comment]
This is by-design behavior when using the Prefer: hierarchicalsharing header, are you using that in this case?  Assuming you are then the Delta query is filtering out the children since they didn't technically have a change applied, the change is only on the element whose permissions actually were updated.  If you need to keep track of the children to re-evaluate them when their parent changes we recommend caching that information when doing an initial scan of the library in question.

**Comment by bmiller-ns** [comment]
> This is by-design behavior when using the Prefer: hierarchicalsharing header, are you using that in this case?

No, we're not using `Prefer: hierarchicalsharing`. We want the default behavior which according to the [docs](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#scanning-permissions-hierarchies) is:

> By default, the delta query response will include sharing information for all items in the query that changed even if they inherit their permissions from their parent and did not have direct sharing changes themselves

**Comment by braimondo** [comment]
@JeremyKelley just to clarify here, delta is behaving as Prefer: hierarchicalsharing is always on, even when not used.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
