### ISSUE TITLE
How to find watch links

### ISSUE THREAD

**Issue by he852100** [OneDrive/onedrive-api-docs#1251]
If I didn't save it.  Where can I not find

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42443681-dd86-ce0c-587f-2336f965ebaf
* Version Independent ID: abcbaeba-560b-661d-0127-5c44d9089915
* Content: [Upload from a URL - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_upload_url?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_upload_url.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_upload_url.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  Unfortunately there is no way to look up existing operations.
