### ISSUE TITLE
Refreshing a webhook subscription for a deleted resource does not throw any errors

### ISSUE THREAD

**Issue by jeffwidman** [OneDrive/onedrive-api-docs#1252]
In OneDrive for Business

### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Once a user or their drive is permanently deleted, then they will never trigger any further notifications. So **refreshing webhook subscriptions for that drive should start returning an error.** Otherwise we may perpetually refresh subscriptions that can never return notifications, wasting Microsoft API resources. Given that this is OneDrive for Business, where an account may have several hundred thousand users, this can quickly grow out of control.

#### Observed Behavior

Graph API returns `OK` (`200`) status codes when refreshing a webhook subscription where the underlying resource was deleted.

#### Steps to Reproduce
1. Create a webhook subscription for an existing drive. 
2. Delete that drive.
3. Refresh the webhook subscription, it should error, but instead returns a `200`.

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please provide more information about the request to help with the investigation?  This may be an issue with Graph or with OneDrive, not sure.  I'll tag so our helpful bot will provide some additional information about what will help with investigation.  Thanks!
