### ISSUE TITLE
How to list all webhook subscriptions associated with a resource?

### ISSUE THREAD

**Issue by jeffwidman** [OneDrive/onedrive-api-docs#1253]
This applies to OneDrive for Business.

#### Category:
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Scenario:

1. We issue a CreateSubscription call for a user's drive.
2. Microsoft internally creates the subscription
3. Something crashes in the network or my code and the response is never received.

At this point, during crash recovery, I have no idea if a webhook subscription exists for that drive. Since I never received the response, I have no subscription ID, so I cannot check the state of the subscription. 

How do I query for all the webhook subscriptions associated with a resource?

According to the docs, if the subscription ID is unknown, then the only way to query for subscriptions is the `GET https://graph.microsoft.com/v1.0/subscriptions` endpoint. However, the docs say this endpoint doesn't support any query params so will return all webhook subscriptions in paginated form. Given that this is a corporate OneDrive for Business account, there may be 200K+ users that we are subscribed to. Paginating through all 200K subscriptions just to see if one already exists for this particular user's drive is not realistic. 

If I assume it failed and trigger another CreateSubscription call, then Microsoft happily takes it and suddenly I've got two subscriptions, with identical params, happily generating duplicate notifications whenever an actions happen.

Is there a way to do either of the following?
* Filter the list of subscriptions by associated resource? Ie, list only the subscriptions tied to that user's drive. This would be ideal!
* Filter the list of subscriptions to only those created after a certain time? This would be less optimal, but at least here I could say "show only subscriptions created after my most recent pre-crash checkpoint"
* Sort subscriptions by time created... again, even less optimal as I'd have to serialize the subscription creation, but I could then go back to the last known successful creation and see which subscriptions have been created since then.

Are any of the above possible?

**Comment by chackman** [comment]
This would be a question for Microsoft Graph.  It's probably a UserVoice request; I'll add a label for our helpful bot to provide some links.

**Comment by chackman** [comment]
To find Graph's UserVoice, we also recommend going to microsoftgraph.uservoice.com

**Comment by jeffwidman** [comment]
This information can be found for an individual user's drive via its relationships: https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#relationships

Example:
```
https://graph.microsoft.com/v1.0/users/<User ID>/drive/root/subscriptions
```

It doesn't look like it's possible to check for subscriptions on `/users` resource, but being able to check individual users is far better than nothing.
