### ISSUE TITLE
OneDrive picker redirects back to my site

### ISSUE THREAD

**Issue by Dave3of5** [OneDrive/onedrive-api-docs#1254]
I'm using the OneDrive Picker documentation from [here](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online) but it doesn't work. Firstly I needed to add a redirect Url otherwise the login page that is opened says it can't log me in. Then what happens is that the page that is displayed is actually my website with an access token in the Uri:

<img width="440" alt="Screenshot 2020-04-02 at 16 24 12" src="https://user-images.githubusercontent.com/13622748/78268652-67ca9180-7500-11ea-8154-0065f88ef197.png">

The code I'm using is almost exactly copied from the tutorial but I'll give it here:

launchOneDrivePicker: function(){
  let odOptions = {
    clientId: "redacted"
  };
  OneDrive.open(odOptions);
}
I think this is a config for my app but I can't figure out at all and the documentation doesn't mention this at all.

**Comment by Dave3of5** [comment]
Anyone had a look at this the picker that I have at the moment it unusable and simply redirects to my webpage.

**Comment by Dave3of5** [comment]
Two weeks and no comments at all ?

I've tried everything the docs are so confusing here and tell you basically nothing.

I'm trying to use the onedrive picker with an Spa (Vue.js) so having a predefined Url for redirect doesn't work. Are there any example / help on setting this up ? I'm really struggling.

**Comment by shurshilov** [comment]
I have exactly the same problem and I cannot understand what is the matter, is there any news?

**Comment by shurshilov** [comment]
![onedrive](https://user-images.githubusercontent.com/11828278/87878937-192dfe00-c9f0-11ea-829e-9beb6a42389d.png)
I solved, just need understand different between implicit flow and auth code flow.
Onedrive JS picker need use implicit flow!
And it is also possible that I created a second spa application and tried to go through it, of course it did not work, you need a regular Web. But the cookies may have been erased!

**Comment by vishuk570** [comment]
@Dave3of5 @shurshilov @chackman   
I have the same issue. if you are solved it Please share the solution.
Thank you

**Comment by shurshilov** [comment]
> @Dave3of5 @shurshilov @chackman I have the same issue. if you are solved it Please share the solution. Thank you

I use like this
```
        // Create and render a Picker object
        createPickerOnedrive: function() {
            return new Promise((resolve, reject) => {
            var odOptions = {
                clientId: this.onedrive.clientId,
                //action: "download",
                action: "query",
                //action: "share",
                multiSelect: true,
                openInNewWindow: true,
                viewType: this.onedrive.viewType, //folders, files
                advanced: {
                    queryParameters: "select=id,name,size,webUrl,file,folder,photo,@microsoft.graph.downloadUrl",
                    createLinkParameters: { type: "edit" }
                },
                success: function (files) { resolve(files); },
                cancel: function () { resolve(null); },
                error: function (e) { console.log(e); reject(e); }
            };

            OneDrive.open(odOptions);
            });
        },
```

**Comment by vishuk570** [comment]
> 

I have use also like this but issue not fix. when I put credential of microsoft for access onedrive then redirect to in my web app.

**Comment by martin19** [comment]
I had success adding an endpointHint like so to the picker options:

```
advanced: {
  endpointHint: "api.onedrive.com"
},
```

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
