### ISSUE TITLE
Need more explanation about get contents from a shareingurl for onedrive for business

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1256]
I have one annoymous sharing url from onedrive personal and one from onedrive for business.
When I use the api GET /shares/u!xxxxxx/ with a work account oauth, I get “400 The site in the encoded share URI is invalid” but I can get the SharedDriveItem resource for the shareing url from 
 onedrive personal with a personal account oauth.

Is there any more rules about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292c23a1-9aab-8349-11b2-dc6f28d54e6e
* Version Independent ID: 083a591a-6425-3408-aa2f-ace9db3c43c8
* Content: [Access shared items - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/shares_get.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/shares_get.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  For this case
> When I use the api GET /shares/u!xxxxxx/ with a work account oauth
could you please clarify whether the sharing URL was a OneDrive personal sharing URL, or a OneDrive or Business sharing URL?

Also could you please provide a request-id and date/time for the request that failed?  I'll tag so our helpful bot will provide more information about getting request ID's.

**Comment by landall** [comment]
personal account  CALL personal sharing url: work

Date: Fri, 17 Apr 2020 17:26:53 GMT
request-id: 36d9658b-e215-4129-9c78-4b0dfedd6023

personal account CALL business sharing url: 400 Invalid shares key

Date: Fri, 17 Apr 2020 17:28:32 GMT
request-id: cbc2e6e3-b0e4-4f82-b368-8f78bc6d1b8c

business account CALL business sharing url: 400 The site in the encoded share URI is invalid.

Date: Fri, 17 Apr 2020 17:30:00 GMT
request-id: 0e854311-30bf-423e-8cd5-8c8007ad230d

business account CALL personal sharing url: 400 The site in the encoded share URI is invalid

Date: Fri, 17 Apr 2020 17:32:28 GMT
request-id: 34f1b5e9-ed90-41c3-b1fa-54c0632078b0

no SPRequestGuid found in all tests.

**Comment by chackman** [comment]
Thanks for your feedback.

All three failures are expected.

For business accounts, a sharing URL must belong to the same organization (tenant) as the user belongs to.  Likewise, a business account cannot use a personal sharing URL.

In addition, a personal account cannot use a business sharing URL.

**Comment by landall** [comment]
> Thanks for your feedback.
> 
> All three failures are expected.
> 
> For business accounts, a sharing URL must belong to the same organization (tenant) as the user belongs to. Likewise, a business account cannot use a personal sharing URL.
> 
> In addition, a personal account cannot use a business sharing URL.

That means, there is a situation that I can visit a sharing URL in browser but cannot visit it through Microsoft Graph?
