### ISSUE TITLE
How to resume a failed copy?

### ISSUE THREAD

**Issue by landall** [OneDrive/onedrive-api-docs#1257]
Onedrive personal:
I copy a folder with 300GB but it failed at 56% progress for the reason of blob store timeout.
How can I resume the copy?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38d3dcf-49bd-eedc-e4cf-5041af8ed7fe
* Version Independent ID: 8a3d3fed-4e6c-0592-5f7c-8105365698d8
* Content: [Copy a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_copy.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_copy.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback.  We're following up with a partner team about whether this is supported.

**Comment by landall** [comment]
Thanks for your reply.
