### ISSUE TITLE
@microsoft.graph.downloadUrl of copied files does not work initially

### ISSUE THREAD

**Issue by OlliV** [OneDrive/onedrive-api-docs#1258]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

1. Create a folder with a few plain text files under any SPO site's Documents libary.
2. Create another folder and copy all the files from the previous folder to the new folder using OneDrive's copy functionality.
3. Downloading any of the copied files using `@microsoft.graph.downloadUrl` prepared the the OneDrive Graph API
4. The file is received and it has the correct content

#### Observed Behavior

The HTTP response from 3. is 200 but the `Content-Length` header is set to 0 and no HTTP body is received. This only happens once, and a retry will download the file successfully.

#### Steps to Reproduce

As described above. Try downloading the files from the second folder and most of the time the first downloading attempts will return no body, `Content-Length: 0`, and `200 OK`. The issue will eventually disappear, likely forever as populating some metadata happens lazily after the first download attempts.

**Comment by chackman** [comment]
Thanks for your feedback.
Could you please clarify whether the copy in step (2) has completed?
If it has completed, could you please provide a request-id and date/time for requests (3), and ideally (4)?
I'll tag so that our helpful bot will provide more information about request ID's.
