### ISSUE TITLE
Once upload completes, getting the status return 404.

### ISSUE THREAD

**Issue by madhavsankar** [OneDrive/onedrive-api-docs#1259]
#### Category
- [x] Question
- [x] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
With respect to https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online,
I expect to see a Completed status or something to denote that the upload succeeded. 

#### Observed Behavior
Current behavior returns a 404 ItemNotFound. I assume that the session is closed once completed. But in this case, it becomes impossible to differentiate between a completed transfer and one where the session expired.

#### Steps to Reproduce
"GET <uploadUrl>" after the upload completes. 

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.  This is expected behavior - applications are expected to keep track of whether the upload has been completed.

**Comment by madhavsankar** [comment]
Thanks @chackman . 
In case if this helps someone:
I'm currently sending a GET request to the SharePoint upload file location url. So if the files exists, it returns some metadata, else it returns 404. So, considering that my scenario guarantees that each file has separate location, I'm using this as a workaround.
