### ISSUE TITLE
GET /drive/root API not working for OneDrive for Business

### ISSUE THREAD

**Issue by CS1-MDM03** [OneDrive/onedrive-api-docs#126]
Hi,
I have successfully performed authorization, discovery and generated access token for OneDrive for Business
I have also changed the "v1.0" in the service endpoint URI to "v2.0"

After this, I hit "https://mdm03-my.sharepoint.com/_api/v2.0/me/drive/" with the authorization header and I get a 200 response with the details for the user's drive.
But I get a 404 response on hitting "https://mdm03-my.sharepoint.com/_api/v2.0/me/drive/root/"

The error is:
{
   error: {
   code: "-1, Microsoft.SharePoint.Client.ResourceNotFoundException"
   message: "Cannot find resource for the request root."
   }
}

Is there anything that I am doing wrong?
Or drive/root/ API has some issue for OneDrive For Business?

**Comment by CS1-MDM03** [comment]
Our Office 365 setup has a Office 365 Small Business subscription, and thats the reason the Drive API is not working. Tried it on a developer subscription, and it worked.

Are we not going to provide these APIs for Small Business subscriptions?

**Comment by rgregg** [comment]
Let me look into what's going on here.

**Comment by ankit-ankuagrawal** [comment]
@rgregg 

following is the problem 

![comparison](https://cloud.githubusercontent.com/assets/11455759/7942256/b7fef066-097a-11e5-8a19-ec2f0ca44b1d.png)

**Comment by rgregg** [comment]
Thanks for the additional details. We'll investigate and I'll get back to you.

**Comment by rgregg** [comment]
Actually, one more question: Can you provide the full response headers when the request fails on your mdm05 account?

**Comment by ankit-ankuagrawal** [comment]
GET https://mdm05-my.sharepoint.com/_api/v2.0/me/drive/root

![response header](https://cloud.githubusercontent.com/assets/11455759/7943226/da408eb8-0980-11e5-928d-b39a1f6d2ff4.png)

**Comment by ankit-ankuagrawal** [comment]
@rgregg following is the detail from fiddler, the previous one was from advanced REST client

![response header from fiddler](https://cloud.githubusercontent.com/assets/11455759/7943305/6a072f3e-0981-11e5-95be-db675e4b5297.png)

**Comment by ankit-ankuagrawal** [comment]
@rgregg sir any update on this...

**Comment by ankit-ankuagrawal** [comment]
@rgregg it is working now positively... ty for ur response...

**Comment by joewutaiwan** [comment]
hi, @ankit-ankuagrawal :
Could you tell any update?
Do different accounts matter?
I couldnt see any response from @rgregg 

thank you both!

**Comment by rgregg** [comment]
It looks like the issue here was that the server farm that your Office 365 tenant was located in was missing a patch that has since been deployed. Before the patch we expected the error you were seeing, and the patch resolved this problem.

**Comment by r4nm4** [comment]
I'm sorry guys, but I'm really confuse about that.
Why use: "/me/drive"? Inside the docs is: "/me" and "/drive". Not "/me/drive".
If I try "/me/drive" I received this message:
"Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown."
Thanks
