### ISSUE TITLE
How to increase the expiration time?

### ISSUE THREAD

**Issue by madhavsankar** [OneDrive/onedrive-api-docs#1260]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
According to https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online,
when I create a session, it has expiry of 15 mins. 

1. Can you confirm if this is in fact the expiration time? 
2. Also, what happens if an upload requires more time, can the expiration time be increased?
3. Every 30 mins we track all the uploads and at times it returns 404, how can we tell if the upload has completed or if the session expired? 

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.
(1) and (2) The expiration time is an initial one; as the application starts uploading, the expiration time should update.  As the application continues to upload content the expiration time will also update.

(3) The expectation of applications is that they keep track of status of whether an upload is complete.

**Comment by madhavsankar** [comment]
Thanks you @chackman. If the expiration time keeps increasing as we upload, I don't quite get what the term signifies? What happens when
- We get the uploadUrl and don't start the uploading for the next 15 mins? The session expires?
- We get the uploadUrl, upload 25% in 15 mins. The session expiration time for the url extends?

Is the expiration time for the session same as the Url?

**Comment by chackman** [comment]
The upload session will be valid until the expiration time on the most recent response your application received for that particular upload session.

If your application does not start uploading before the expiration time, the session will expire.  When your application uploads to the upload session, the [response](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#response-1) will contain which byte ranges are expected by the service, along with an updated expiration time.

The [uploadUrl](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#response) is where your application should upload content to the upload session created by the API call, so yes they are the same.
