### ISSUE TITLE
one drive graph api permission call does not return inheritedFrom field for grantedToUsers

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-api-docs#1261]
Steps to Reproduce

1. Create a folder (say folderA)
2. Share the folder directly with a user (say user 1@domain.com)
3. Create a link for a specific user (say user2@domain.com)
4. Create a child folder (say folderB) under folderA
5. fetch permissions for folderB using the API https://graph.microsoft.com//beta/users/<user_guid>/drive/items/<id_of_folderB>/permissions
6. Two permission are returned 
     1. with grantedToIdentities and inheritedFrom
     2. with grantedTo but no inheritedFrom

Expected Behavior:

In Step 6 both the permissions should have inheritedFrom.

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please provide an example request-id and date/time (in UTC)?  I'll tag so that our helpful bot will give some more information.  Thanks!

**Comment by agrankur** [comment]
Approximate time: April 20th 2020, 10:41 PM
API Used : https://graph.microsoft.com/beta/users/b949cf7c-dd2d-4076-a1ae-6dd1b1e206f7/drive/items/01F33KN7DA7BVQTXY33FGIGY2ATVF4P2FF/permissions

Response Headers
Key: 'Strict-Transport-Security', Value: '[max-age=31536000]'
Key: 'x-ms-ags-diagnostic', Value: '[{"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_7"}}]'
Key: 'Cache-Control', Value: '[private]'
Key: 'client-request-id', Value: '[e9688ae7-2b36-4fe5-979e-0dc1fa0271c5]'
Key: 'OData-Version', Value: '[4.0]'
Key: 'Content-Length', Value: '[1837]'
Key: 'request-id', Value: '[df4f3a25-bc37-4fee-8dff-68f4fd07dd9f]'
Key: 'Date', Value: '[Mon, 20 Apr 2020 22:37:51 GMT]'
Key: 'Content-Type', Value: '[application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8]'

**Comment by agrankur** [comment]
Response Data received is as follows. The grantedTo users do not have inheritedFrom.  {"@odata.context":"https://graph.microsoft.com/beta/$metadata#users('b949cf7c-dd2d-4076-a1ae-6dd1b1e206f7')/drive/items('01F33KN7DA7BVQTXY33FGIGY2ATVF4P2FF')/permissions","value":[{"hasPassword":false,"id":"9daa4895-2b76-4d5c-89d9-3d96e057d418","roles":["write"],"link":{"preventsDownload":false,"scope":"anonymous","type":"edit","webUrl":"https://apertureqa5-my.sharepoint.com/:b:/g/personal/admin_apertureqa5_onmicrosoft_com/EWD4awnfG9lMg2NAnUvH6KUBWavZ_UsI7aqS-ODLCfLjtg"}},{"hasPassword":false,"id":"5107c084-2448-478f-b01d-f66496ae45a4","roles":["write"],"grantedToIdentities":[{"user":{"email":"aagrawal@apertureqa5.onmicrosoft.com","id":"671d2fab-0e94-4549-9126-9d8b215f7778","displayName":"Ankur Agrawal"}}],"inheritedFrom":{},"link":{"preventsDownload":false,"scope":"anonymous","type":"edit","webUrl":"https://apertureqa5-my.sharepoint.com/:f:/g/personal/admin_apertureqa5_onmicrosoft_com/EpHAmZw34NxEoj0UpwNwZqYBrTn4jmvhiuPUDT9SMe4WnA"}},{"hasPassword":false,"id":"5b9a82c5-3f86-4d9e-8a21-a5009770ee00","roles":["write"],"grantedToIdentities":[{"user":{"email":"ankur@outlook.com","displayName":"ankur@outlook.com"}}],"inheritedFrom":{},"link":{"preventsDownload":false,"scope":"users","type":"edit","webUrl":"https://apertureqa5-my.sharepoint.com/:f:/g/personal/admin_apertureqa5_onmicrosoft_com/EpHAmZw34NxEoj0UpwNwZqYBF-1JSn6o71VMg5EuuPlv7A"}},{"id":"aTowIy5mfG1lbWJlcnNoaXB8YWFncmF3YWxAYXBlcnR1cmVxYTUub25taWNyb3NvZnQuY29t","roles":["write"],"grantedTo":{"user":{"email":"aagrawal@apertureqa5.onmicrosoft.com","id":"671d2fab-0e94-4549-9126-9d8b215f7778","displayName":"Ankur Agrawal"}}},{"id":"aTowIy5mfG1lbWJlcnNoaXB8YWRtaW5AYXBlcnR1cmVxYTUub25taWNyb3NvZnQuY29t","roles":["owner"],"grantedTo":{"user":{"email":"admin@apertureqa5.onmicrosoft.com","id":"b949cf7c-dd2d-4076-a1ae-6dd1b1e206f7","displayName":"Admin User"}}}]}

**Comment by chackman** [comment]
Thanks.  Just wanted to quickly clarify - are you saying that the `permission` entities that have `grantedTo` property values do not have `inheritedFrom` property values?  Additionally, are they expected to be empty, or are they expected to have a non-empty value?

**Comment by agrankur** [comment]
Yes i mean to say that permission entities that have grantedTo property values do not have inheritedFrom property values. The documentation says that if the grantedTo property is inherited the response contains an empty inheritedFrom i.e "inheritedFrom": {}. but i do not see that coming in the response.

**Comment by chackman** [comment]
We've tried to reproduce this, and cannot get this to reproduce.
Could you please clarify how you shared the items with the user?  For example, did you use the sharing UI, make an API call, (and if so which API), or something else?

**Comment by agrankur** [comment]
I shared the items using the OneDrive web UI.

**Comment by michevnew** [comment]
I can reproduce this just fine in my tenant. Shared a folder via the browser ODFB client, then when I check via the Graph API, I can see the inheritedFrom property, but it's empty and contains no reference to the parent object. No matter if I use app or delegate permissions, and reproducible both on /beta and /v1.0 endpoints.

**Comment by agrankur** [comment]
In my case i am not even getting inheritedFrom property in the response. 

We have 2/3 tenants for testing and one of them was reporting it as you have mentioned in the  comment above last time  tested where as the other 2 were not.  So is there a setting per tenant that is needed to achieve the behavior mentioned above?

**Comment by shayan-brcm** [comment]
@chackman @JeremyKelley i am also facing the same problem. is there ETA for the fix?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
