### ISSUE TITLE
Can links be created in Net CORE 3.1? 

### ISSUE THREAD

**Issue by HarryDearing** [OneDrive/onedrive-api-docs#1263]
I working on an application that requires a shareable link and I am using Net CORE 3.1 and C#. Are there any examples or resources that will help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69601057-a846-2eea-33b4-9e1760981e88
* Version Independent ID: 5cbaae53-7d99-8075-609a-30d82c9ad0c8
* Content: [Share a file with a link - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_createlink.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createlink.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
The [Microsoft Graph SDK](https://developer.microsoft.com/en-us/graph) supports .net core (check the ["getting started" section](https://developer.microsoft.com/en-us/graph/get-started) in the Graph developer site).
The documentation for the [corresponding Graph API](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http) has some examples for additional languages.

**Comment by HarryDearing** [comment]
I am still struggling and have failed to get any of the examples running using Visual Studio 2019, Net Core 3.1 and C#. My application seems straightforward. Currently, we use the OneDrive "Share" function to generate a shareable link to a file or a folder and paste it into label making software for a QR code that users can use their phone and the QR code to look up information on our corporate OneDrive. I would like to automate that process in the applications we are developing. The ability to do that as part of the application is eluding us. My feeling is that this has been done and we should be able to see a working example that can guide us in our implementation. When I look at this example I am getting lost in the first part where it sets up the "authProvider" instance. When I try to determine how to do that in my application, I am looking at a bewildering array of possibilities, none of which I understand. I will continue to work with this and look at the examples and try to make them work, but it seems a lot harder than it should be to me.

**Comment by chackman** [comment]
Thanks for your feedback. This is a question for Microsoft Graph; I'll tag for our helpful bot to provide a link.
