### ISSUE TITLE
400 BadRequest error with multipart/related upload

### ISSUE THREAD

**Issue by mylorodelle** [OneDrive/onedrive-api-docs#1264]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

POSTing a multipart/related request to upload a file and metadata results in a successful upload.

#### Observed Behavior

POSTing a multipart/related request to upload a file and metadata results in a 400 bad request error.

```
HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Type: application/json
request-id: f9ea3434-a14a-4adc-b802-5e3759c31562
client-request-id: f9ea3434-a14a-4adc-b802-5e3759c31562
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 2","Slice":"SliceC","Ring":"1","ScaleUnit":"001","RoleInstance":"AGSFE_IN_31"}}
Strict-Transport-Security: max-age=31536000
Date: Fri, 17 Apr 2020 23:16:53 GMT
Content-Length: 254

{
  "error": {
    "code": "BadRequest",
    "message": "Entity only allows writes with a JSON Content-Type header.",
    "innerError": {
      "request-id": "f9ea3434-a14a-4adc-b802-5e3759c31562",
      "date": "2020-04-17T23:16:54"
    }
  }
}
```

#### Steps to Reproduce

Here is the text view of of the request that's being made (taken from Telerik Fiddler):

```
POST https://graph.microsoft.com/v1.0/me/drive/items/root/children/ HTTP/1.1
Accept: application/json
Authorization: Bearer {token}
Content-Length: 318
Content-Type: multipart/related; boundary="P2kAlMiG3Kb8FzP6"
Host: graph.microsoft.com
Cache-Control: no-cache

--P2kAlMiG3Kb8FzP6
Content-ID: <metadata>
Content-Type: application/json

{"@content.sourceUrl":"cid:content","@microsoft.graph.conflictBehavior":"replace","file":{},"name":"test.txt"}

--P2kAlMiG3Kb8FzP6
Content-ID: <content>
Content-Type: text/plain
1234567890ABCDEFGHIJKLMNOPQRSTUV

--P2kAlMiG3Kb8FzP6--
```

I've tried matching the request format from https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_post_content?view=odsp-graph-online. Am I missing something?

**Comment by chackman** [comment]
Could you please clarify whether this issue affects OneDrive Personal, OneDrive for Business, or both?  Thanks!

**Comment by mylorodelle** [comment]
This is when using the api for my personal one drive account.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
