### ISSUE TITLE
OneDrive Business: Search in {item-id} folder returns items outside this folder

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#1265]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

API call `https://graph.microsoft.com/v1.0/me/drive/items/{item-id}/search(q='{search-query}')` should return only items inside the `{item-id}` folder. 

That works fine for **OneDrive Personal** accounts:
`https://graph.microsoft.com/v1.0/me/drive/items/3AE367261D4DA2BC%2110513/search(q='test')`
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": [
{
            "@odata.type": "#microsoft.graph.driveItem",
            "id": "3AE367261D4DA2BC!10519",
            ....
            "parentReference": {
                "driveId": "3ae367261d4da2bc",
                "driveType": "personal",
                "id": "3AE367261D4DA2BC!10513",
               ....
             }
        }
    ]
}
```

- The item that is found is located in the `3AE367261D4DA2BC!10519` parent folder.

#### Observed Behavior
When executing the same call using an **OneDrive Business** account, the results contain items outside the `{item-id}` folder:

`https://graph.microsoft.com/v1.0/me/drive/items/01DBFMAUMY4O3S74VWQNEJ2WPV4LJ6EHJL/search(q='test')`

**Date:** Tue, 21 Apr 2020 07:28:12 GMT
**Request-id:** 2340ef25-34f4-4bbc-b5dd-26f51c1f5f82

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "id": "01DBFMAUIECAUFMSTZ4NF23BGJWU3W7ERE",
            ....
            "parentReference": {
                "driveId": "b!sU5yWrqEXUSdD8bRVZKOrn9v_xMHu7hAgHjBOOCrGQJLfoJfRGbmT5Em9RFD0Tt_",
                "driveType": "business",
                "id": "01DBFMAUP2IO45ET7FBRD33KKZPFXJEEUB"
                ....
            },
        }
    ]
}
```

- The item that is found (`01DBFMAUIECAUFMSTZ4NF23BGJWU3W7ERE`) is located outside the folder in which the search is performed (`01DBFMAUMY4O3S74VWQNEJ2WPV4LJ6EHJL`)

#### Steps to Reproduce
See API calls above. 

#### Question
Should I perform the search call in a different way for OneDrive Business accounts to only return the items that are found inside a specific folder? Or is this a bug in the API itself?

**Comment by The-Lion** [comment]
@chackman Is there any update on this? Please let me know if you need any additional information from my end.

**Comment by The-Lion** [comment]
Is this actually the place to report this kind of bugs as I am not receiving any feedback at all? I would highly appreciate it if I can get some kind of update on this problem.

**Comment by chackman** [comment]
We're waiting on a partner team to investigate this.

**Comment by The-Lion** [comment]
I can't longer reproduce this issue, so it seems to be solved. It would have been nice to get notified via this issue when this was fixed.
