### ISSUE TITLE
Tenant does not have a SPO license while accessing the OneDrive API

### ISSUE THREAD

**Issue by nobso** [OneDrive/onedrive-api-docs#1266]
## Category
- [X] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
OneDrive API response in return for the OAuth Application authenticated request  with the valid access token

#### Observed Behavior

```
curl -H 'Authorization: Bearer [VALID ACCESS TOKEN]' https://graph.microsoft.com/v1.0/drive/recent
{
  "error": {
    "code": "BadRequest",
    "message": "Tenant does not have a SPO license.",
    "innerError": {
      "request-id": "ce07f480-8ce4-df0eb56b9722",
      "date": "2020-04-22T03:46:03"
    }
  }
}
```

#### Steps to Reproduce

1. Register an application in the https://portal.azure.com/
2. Give an API Permission for the Microsoft Graph API with 'Files.Read.All' as an Application permission (Application permissions - Your application runs as a background service or daemon without a signed-in user.)
3. Grant Admin Consent for the selected API
4. curl the graph API to get an Access Token
5. Use the access token to get the recent drive files **https://graph.microsoft.com/v1.0/drive/recent**

Thank you.

**Comment by nobso** [comment]
I don't understand why I need to have SPO license while calling graph API. After reading a lot of online help forums, it seems like i need to own Office 365, But why do i need to buy Office 365 Business account as i'm trying to access my personal OneDrive? I'm so confused! I could not find any clear documents.

**Comment by JeremyKelley** [comment]
Hi nobso,

There are a couple things we noticed here.

1) Microsoft Graph returns data based on what account you logged in with, are you logging in to portal.azure.com to create the application with a consumer Microsoft account or an Azure Active Directory account?
2) The API path you requested isn't valid, /drive/recent as a top level URL is not supported.  If you want the current user's OneDrive then you need a few things, first you need to be using Delegated rather than Application permissions as you'll need a user context.  Second the API URL you would want for the current user's drive is /me/drive.

You may want to check out the samples that run through the Graph Explorer at https://aka.ms/ge.
You can sign in with your personal Microsoft Account and try the samples against your data to help figure out which calls you want to make.

**Comment by nobso** [comment]
HI @JeremyKelley 
Thanks for responding. 

> Microsoft Graph returns data based on what account you logged in with, are you logging in to portal.azure.com to create the application with a consumer Microsoft account or an Azure Active Directory account?

I'm using my consumer Microsoft account to log into the portal.azure.com. It shows as 'DEFAULT DIRECTORY' after logging in. I don't think that i was told any difference between the consumer Microsoft account or an Azure Active Directory account while signing up for Azure


> The API path you requested isn't valid, /drive/recent as a top level URL is not supported. If you want the current user's OneDrive then you need a few things, first you need to be using Delegated rather than Application permissions as you'll need a user context. Second the API URL you would want for the current user's drive is /me/drive.

I don't want the 'Delegated Permissions' which will go thro' typical OAuth flow. My application does not have any UI and the daemon that runs in my server needs to authorize this application, that's the reason i've given my Azure application the 'Application Permissions' for the OneDrive read APIs.

Also if i use the Graph Explorer, **/drive/recent** API works just fine.

I even bought the Office 365 thinking that it would resolve the License issue, but its still the same.  Please help me on this.

**Comment by nobso** [comment]
Do we have any updates?

**Comment by tweissin** [comment]
I saw this comment about it. https://stackoverflow.com/a/55036124/1042151

**Comment by nobso** [comment]
> I saw this comment about it. https://stackoverflow.com/a/55036124/1042151

Thanks.. but did not help

**Comment by tweissin** [comment]
I was also seeing what you see, but now I've tried something different. Maybe you can try this and it will help both of us.

Query to get access token (as per [this link](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-acquire-token?tabs=java#protocol)):

```
POST /YOUR-TENANT/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id=YOUR-CLIENT-ID
&client_secret=YOUR-SECRET
&scope=https://api.onedrive.com/.default
&grant_type=client_credentials
```

Note, for scope above, I tried both `graph.microsoft.com` and `api.onedrive.com` (see below).

This should get you back something like the following

```json
{
    "token_type": "Bearer",
    "expires_in": 3599,
    "ext_expires_in": 3599,
    "access_token": "YOUR-ACCESS-TOKEN"
}
```

At this point, I was the API would work. Again, I specified `api.onedrive.com` instead of `graph.microsoft.com`.

```
GET /v1.0/drive/root: HTTP/1.1
Host: api.onedrive.com
Authorization: Bearer YOUR-ACCESS-TOKEN
```

What I get back is the following:

```json
{
    "error": {
        "code": "unauthenticated",
        "message": "Must be authenticated to use '/drive' syntax"
    }
}
```

I am also getting the same behavior on the Graph explorer page. On that page I didn't see a spot to "authenticate" myself as per the error message.

Re: `api.onedrive.com` above, on [this page](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences?view=odsp-graph-online), it says:

> To access OneDrive API for OneDrive personal, your app must use the `https://api.onedrive.com/v1.0` endpoint for all requests.

Not sure where to go from here.

**Comment by orenxperitos** [comment]
I also have this problem. Does anyone found a solution for this ??

**Comment by nobso** [comment]
> I also have this problem. Does anyone found a solution for this ??

MicroSoft is non-responsive, very poor in tracking the issue

**Comment by tocsi-hun** [comment]
I had the same issue. Long days of trial and fail :)
1. the app registration on AzurePortal should use **Personal Microsoft Accounts**, Mobile and Desktop Applications, the .../nativeclient redirect uri
![image](https://user-images.githubusercontent.com/4420961/105734420-e7639a00-5f32-11eb-8f60-b308a5c1c6d5.png)


2. the endpoint should be the **/consumers** endpoint. Which actually means that the tenant id should be "consumers". 
I used the C# client and this is how it looks there

```csharp
            IPublicClientApplication publicClientApplication = PublicClientApplicationBuilder
            .Create(<app-clientid>)
            .WithDefaultRedirectUri()
            .WithTenantId("consumers")
            .Build();
```
And basically that was it. No extra license is needed.

**Comment by orenxperitos** [comment]
1. Please Remind me, what is the link (or how do i get) into the configuration page you have presented ?
2. where does the **client_secret** goes in ? (i want that **only my app** will be able to access my onedrive account)

**Comment by augustoicaro** [comment]
Hello @nobso,

A few days ago, I had the same problem and read a lot with a long sequence of trials and errors to solve my problem.

The main problem is our account type. As a personal account, there are some restrictions to access one drive files. These restrictions are:

1. You can only use `Oauth2 Code Flow` or `Oauth2 Token Flow`. Both are interactive approaches. [[1](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online#supported-authentication-flows)]
2. Your application registered in AAD needs be `Personal Microsoft accounts only` or `Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)` and each one have a different endpoint to acquire the access token (That you can saw clicking on `endpoint` button, near the delete app button in app page). [[2](https://stackoverflow.com/questions/46802055/tenant-does-not-have-a-spo-license#comment80647746_46809518)]
3. Enable these delegated permissions to your application registered in AAD: `Files.Read`, `Files.Read.All`, `Files.ReadWrite`, and `Files.ReadWrite.All`.

With these restrictions in mind, you can set up a workflow in Postman following these two steps(I'm using endpoints of `Personal Microsoft accounts only` app type and using `Oauth2 Code Flow`):

`Important note: To use code flow, you need to enable Access tokens in Implicit grant and hybrid flows on Authentication ADD app sidebar menu.`

1. Aquire access token:
```
https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=YOUR_CLIENT_ID&response_type=token&redirect_uri=ONE_OF_REGISTERED_REDIRECT_URI&scope=Files.Read Files.Read.All Files.ReadWrite Files.ReadWrite.All
```
After you fill in your information on Postman's request, I recommend using a browser and network inspection to login with a Microsoft account and permit the app. You are getting the access token via network inspection.

2. List one drive root files:
```
https://graph.microsoft.com/v1.0/me/drive/root/children
Add a new header:
Authorization
With value:
Bearer ACCESS_TOKE_OF_STEP_1
```

**Comment by PremDnj** [comment]
Same issue I faced. Do you have any updates about this?

**Comment by augustoicaro** [comment]
> Same issue I faced. Do you have any updates about this?

The situation still the same for personal accounts. My previous answer https://github.com/OneDrive/onedrive-api-docs/issues/1266#issuecomment-803518395 still valid and explain the options that we have as personal accounts.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
