### ISSUE TITLE
Can we upload large files with upload sessions to a sharepoint list

### ISSUE THREAD

**Issue by madhavsankar** [OneDrive/onedrive-api-docs#1267]
### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I want to upload large items (https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online) and attach webhooks (https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks) to it to keep track of all the updates.

But as webhooks are supported currently only for list items, I would like to upload to a lost. Is this supported? If yes what is the url to send the uploadSession request to?
POST /sites/{siteId}/Lists/{listId}/createUploadSession ?

Thank you.

**Comment by chackman** [comment]
File uploads are only supported within drives (document libraries in SharePoint).  If the list is a document library, you can get to the drive via the /drive relationship on the list.
