### ISSUE TITLE
Resumable file upload API documentation issue

### ISSUE THREAD

**Issue by mizvyt** [OneDrive/onedrive-api-docs#1268]
#### Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

The API documentation for resumable uploads specifies a list of relative HTTP request URLs, but each of the URLs require an `itemId` to be specified (see https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#http-request). I don't really see how I'd know the `itemId` when uploading a new file, and there is no explanation about it anywhere on the page.

Every example uses a different URL from those listed in the HTTP request section (e.g. `POST /drive/root:/{item-path}:/createUploadSession`, see https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#request).

**Comment by k-tsoi** [comment]
Instead of the itemId, use the path of the "new file to be uploaded".
This issues is noted and the document will be updated.
