### ISSUE TITLE
i want to get user share library list,but i can't find any way to do  it 

### ISSUE THREAD

**Issue by yuanlincong** [OneDrive/onedrive-api-docs#1269]
- [ ] Question
i want to get user share library list,but i can't find any way to do it, can you help me? 

Thank you.

**Comment by chackman** [comment]
Could you please clarify your scenario?
Are you asking about "shared with me? https://docs.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0

**Comment by yuanlincong** [comment]
i am sorry,I didn't reply in time。but i not asking 'share with me', i want get 'shared library' in one drive bueiness, i want to get 'share library' list

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
