### ISSUE TITLE
receiving 500 instead of 401 when access_token is getting expired "OneDrive for Business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#127]
receiving 500 error instead of 401 when access_token is getting expired and also it doesnt contain json response format

following is the screenshot 
![access_token expires](https://cloud.githubusercontent.com/assets/11455759/7946283/57ad61d4-0993-11e5-91f3-370595076862.png)

**Comment by ankit-ankuagrawal** [comment]
@katahir , now error code is correctly cming 401...

but the response header doesnt contain Content-Type: application/json
and it seems json response is not acc to format described 

![untitled1](https://cloud.githubusercontent.com/assets/11455759/8045462/17039b5e-0e51-11e5-9d6a-8dfc1a2ee81f.png)

**Comment by ankit-ankuagrawal** [comment]
@katahir receiving error code 500 again...

![untitled3](https://cloud.githubusercontent.com/assets/11455759/8078796/b8bed4c2-0f7d-11e5-8e5e-f0c90bb7c276.png)

**Comment by ankit-ankuagrawal** [comment]
@katahir any update on this

still receiving 500 error with in proper json format

**Comment by ankit-ankuagrawal** [comment]
@katahir receiving 401, but header dont contain content-type header

headers 
Server: Microsoft-IIS/8.5 
x-ms-diagnostics: 3000002;reason="The access token has expired. It's valid from '6/24/2015 3:45:18 PM' and to '6/24/2015 4:50:18 PM'.";category="invalid_client"
SPRequestGuid: 6590139d-e0e0-2000-0df6-15d2e607a84f
request-id: 6590139d-e0e0-2000-0df6-15d2e607a84f
SPRequestDuration: 18
SPIisLatency: 1
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.4107
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI" 
WWW-Authenticate: Bearer realm="32d85f65-6a62-432a-9ab3-941a3b9f85bd",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize" 
Date: Wed, 24 Jun 2015 18:34:26 GMT 
Content-Length: 64

**Comment by rgregg** [comment]
This issue is pretty old now: are you still reproducing this behavior or are things working as expected?

**Comment by ankit-ankuagrawal** [comment]
@ryan gregg sir cant say since some time not using the apis

**Comment by rgregg** [comment]
OK, thanks. I'm going to close this issue down then.
