### ISSUE TITLE
Search for Sites is listed twice in the Tasks

### ISSUE THREAD

**Issue by MatthewMcD** [OneDrive/onedrive-api-docs#1271]
Search for sites:
```
Search for sites	GET /sites?search={query}
```
is listed twice. You can remove the bottom one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69875418-5ba8-85d2-6839-9f3931191cb6
* Version Independent ID: fdc7ade0-67f3-ae4f-a8c0-bea73de49104
* Content: [Site - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/site?view=odsp-graph-online)
* Content Source: [docs/rest-api/resources/site.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/site.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback; feel free to update the docs and create a pull request.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
