### ISSUE TITLE
Error getting thumbnail content

### ISSUE THREAD

**Issue by philipstratford** [OneDrive/onedrive-api-docs#1272]
If I call `https://graph.microsoft.com/v1.0/me/drive/items/{item-id}/thumbnails/0/small` I get the expected response, but if I add `/content`, as per the section "Retrieve thumbnail binary content", I get a response error "Failure - Status Code 0" and the response itself just contains a single json property: `{ "isTrusted": true }`. I have granted the Files.Read and Files.Read.All permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 860b00a0-e2f0-0ac9-5feb-4e488d99098f
* Version Independent ID: 4000c65d-ef19-4c94-0d89-2e6e7a21401b
* Content: [Retrieve thumbnails for a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_thumbnails?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_list_thumbnails.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_list_thumbnails.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ificator** [comment]
Are you making this call through Graph Explorer by any chance? If doesn't support rendering binary content and so will display this error.

**Comment by philipstratford** [comment]
> Are you making this call through Graph Explorer by any chance? If doesn't support rendering binary content and so will display this error.

Yes I am, that explains it. Thank you!
