### ISSUE TITLE
AAD application scopes for OneDrive SDK are not available in Azure API now

### ISSUE THREAD

**Issue by westleyMS** [OneDrive/onedrive-api-docs#1274]
#### Category
- [ ] Question
- [x] Documentation issue
- [ ] Bug

in this doc-
docs/rest-api/getting-started/msa-oauth.md
public link-
[https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online#use-microsoft-graph](url)

The scopes are listed as -

Scope name | Description | Required
-- | -- | --
offline_access | Enables your app to work offline even when the user isn't active. This provides your app with a refresh_token that can be used to generate additional access tokens as necessary. This scope is not available for token flow. | No
onedrive.readonly | Grants read-only permission to all of a user's OneDrive files, including files shared with the user. | Yes
onedrive.readwrite | Grants read and write permission to all of a user's OneDrive files, including files shared with the user. To create sharing links, this scope is required. | Yes
onedrive.appfolder | Grants read and write permissions to a specific folder for your application. | Yes

#### Expected or Desired Change

The top of the article states that you should use the new Graph endpoints, but does not stand out at all, and doesn't indicate the deprecation of the permission scopes. We need a better banner at the top, maybe a yellowish background or something.

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
