### ISSUE TITLE
Subscription creation fails due to non-existent Resource property

### ISSUE THREAD

**Issue by PILLOWPET** [OneDrive/onedrive-api-docs#1275]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I'm trying to create a webhook subscription to my application running with ngrok. I'm using Postman to create the subscription on the following address `POST: https://graph.microsoft.com/v1.0/subscriptions` with the following parameters `application/json`:
```
{
    "changeType: "updated",
    "notificationUrl": "https://<ngrokurl>/drive_change",
    "resource": "/drives/john.doe@company.com/root",
    "expirationDateTime": "2020-05-25T11:23:00.000Z",
    "clientState": "update"
}
```
The validation request sent by OneDrive does go through my application and the correct validationToken is sent back to OneDrive's API. However, I get the following response from OneDrive and I don't really understand why I get it:

```
{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: BadRequest; Reason: The property 'Resource' does not exist on type 'oneDrive.subscription'. Make sure to only use property names that are defined by the type.]",
    "innerError": {
      "request-id": "2dfa2b01-32bb-4f18-989d-17a72733f083",
      "date": "2020-05-06T14:15:03"
    }
  }
}
```

I've tried changing the resource to `"resource":"/drives/<drive-id>/root"` but it did not make any difference.

Thank you for your help.

**Comment by dbalve** [comment]
I am also experiencing this issue; and I can't seem to narrow it down, other than the fact that these are all OneDrive business users. 

```
{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: BadRequest; Reason: The property 'Resource' does not exist on type 'oneDrive.subscription'. Make sure to only use property names that are defined by the type.]",
    "innerError": {
      "request-id": "858ab555-80fd-47cf-817c-c826b1e4803e",
      "date": "2020-05-06T16:36:42"
    }
  }
}
```

I have also tried various ways of referencing the drive; typically `/drives/<Drive ID>/root` however I've also tried `/me/drive/root` and many other combinations that should be valid.

I have also tried duplicating this issue on OneDrive E3 account and haven't been able to. I noticed the users I have inspected with this issue occurring have been from China, but that may be coincidence. 

Generic Attempt

```
POST /v1.0/subscriptions HTTP/1.1
Authorization: <redacted>
Content-Type: application/json
Host: graph.microsoft.com
Connection: close
Content-Length: 222

{"changeType":"updated","notificationUrl":"<webhook URL>","resource":"/drives/<redacted drive id>/root","clientState":"<redacted string>","expirationDateTime":"2020-06-04T20:11:18+00:00"}
```


```
HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Type: application/json
request-id: 858ab555-80fd-47cf-817c-c826b1e4803e
client-request-id: 858ab555-80fd-47cf-817c-c826b1e4803e
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"South Central US","Slice":"SliceC","Ring":"4","ScaleUnit":"003","RoleInstance":"AGSFE_IN_40"}}
Strict-Transport-Security: max-age=31536000
Date: Wed, 06 May 2020 16:36:41 GMT
Connection: close
Content-Length: 403

{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: BadRequest; Reason: The property 'Resource' does not exist on type 'oneDrive.subscription'. Make sure to only use property names that are defined by the type.]",
    "innerError": {
      "request-id": "858ab555-80fd-47cf-817c-c826b1e4803e",
      "date": "2020-05-06T16:36:42"
    }
  }
}
```

**Comment by matthewcocook** [comment]
We have code in production that was previously working/tested that has started to fail. I believe this is a "bug" but could just need documentation update. https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http

**Comment by dbalve** [comment]
This issue seems to be verified and worked actively under this ticket:

https://github.com/microsoftgraph/microsoft-graph-docs/issues/8063

**Comment by baywet** [comment]
as indicated in the issue that @dbalve pointed to, the issue has been resolved. This issue can be closed.
