### ISSUE TITLE
Internal server error while calling personal drive children endpoint for user without access to OneDrive

### ISSUE THREAD

**Issue by odudycz** [OneDrive/onedrive-api-docs#1276]
While calling endpoint for personal drive children:

`https://graph.microsoft.com/v1.0/me/drive/root/children?filter=folder%20ne%20null&top=30&%24skiptoken=`

For the user that does not have access to OneDrive `500` status is being returned. 

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

The endpoint should return `403`

#### Observed Behavior

Yesterday (6th of May 2020) it was working fine and was returning expected `403`, but starting from today (7th of May 2020) it started to fail with `500`

- Date: Thu, 07 May 2020 10:33:13 GMT
- request-id: `313e5f56-1a0e-4e42-80c6-10fa3b99b371`
- client-request-id: `313e5f56-1a0e-4e42-80c6-10fa3b99b371`
- x-ms-ags-diagnostic:
`{"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"003","RoleInstance":"AGSFE_IN_61"}}"

#### Steps to Reproduce

Call `https://graph.microsoft.com/v1.0/me/drive/root/children?filter=folder%20ne%20null&top=30&%24skiptoken=` with a user that does not have access to OneDrive or Sharepoint

**Comment by chackman** [comment]
Thanks for your feedback. If you remove the skiptoken query argument with empty value, does that fix the issue?

**Comment by odudycz** [comment]
@chackman, unfortunately, no, it's still the same.

**Comment by chackman** [comment]
Thanks for your feedback. Could you please also provide the request id and date / time for a request that doesn't have a `skipToken` query argument, e.g.
`https://graph.microsoft.com/v1.0/me/drive/root/children?filter=folder%20ne%20null&top=30`
