### ISSUE TITLE
How to deal with shared link and password?

### ISSUE THREAD

**Issue by kilagg** [OneDrive/onedrive-api-docs#1279]
Hi,

What is the request we need to do if we are working with link that is provide with a password?
In this request : GET /shares/shareEncodeUrl it suppose the link is without any password and that we have a full access with just the link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292c23a1-9aab-8349-11b2-dc6f28d54e6e
* Version Independent ID: 083a591a-6425-3408-aa2f-ace9db3c43c8
* Content: [Access shared items - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/shares_get.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/shares_get.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Could you please clarify whether this is a OneDrive Personal or OneDrive for Business scenario?

**Comment by jgriepentrog** [comment]
Hello,

I'm running into this as well for OneDrive Personal (Premium edition from O365 Home subscription that supports setting a password on a sharing URL).

Is there a way to supply the password in the request or another method to provide it? The fixItUrl seems to supply a user facing page vs an automated method to provide the password.

Here's the request/response:

**Request**
`GET https://api.onedrive.com/v1.0/shares/u!<rest of encoded share link redacted>`

**Response**
`{
    "error": {
        "code": "unauthenticated",
        "message": "Password is needed for this request.",
        "fixItUrl": "https://onedrive.live.com/?v=validatepermission&id=<redacted>&challengeToken=<redacted>",
        "localizedMessage": "This item might have been deleted, expired, or you might not have permission to access it. Contact the owner of this item for more information.",
        "innererror": {
            "code": "sharingPasswordRequired"
        }
    }
}`

Thank you for very assistance.

**Comment by jgriepentrog** [comment]
@chackman - I know the author hasn't responded, but hopefully my note above supplies enough info to remove the author feedback tag? If it's best if I simply open a new issue, I can certainly do that too. Thanks!

**Comment by kilagg** [comment]
@chackman It was on one drive business

**Comment by chackman** [comment]
Thanks for your feedback. Unfortunately the password cannot be supplied directly in the request. We would recommend asking for a feature enhancement on UserVoice, links to do so are here:
>
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.
