### ISSUE TITLE
various behaviour observed while creating folder with @name.conflictBehaviour "OneDrive for Business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#128]
![creating folder behaviour](https://cloud.githubusercontent.com/assets/11455759/7946618/453a1892-0995-11e5-96b1-8273aa8056a4.png)

**Comment by rgregg** [comment]
@ankit-ankuagrawal: Thanks for reporting this. As mentioned in our [release notes](https://dev.onedrive.com/odb-preview/release-notes.htm#rename-on-upload-is-not-supported) we don't support the @name.conflictBehavior attribute for ODB yet.
