### ISSUE TITLE
OneDrive file picker within MS Teams Tab

### ISSUE THREAD

**Issue by jharzmann** [OneDrive/onedrive-api-docs#1280]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I am working on an application that uses the OneDrive file picker (v7.2) which works fine when running the application in the browser.
However, when integrating it in MS Teams, it doesn't work correctly (in the desktop client, the browser works fine again). Instead of a popup, a new browser tab (or if not browser is open a new browser window) opens.

In the browser, the behavior is the following:
- button click (on the application) triggers oneDrive.open(odOptions)
- _popup_ opens with current application's url
- after authenticating, the user is redirected to OneDrive in order to login
- after login, the user is presented with the folders and files
- the user can select a file
- the success callback is called

#### Observed Behavior
In the MS Teams desktop client, this is the behavior:
- button click (on the application) triggers oneDrive.open(odOptions)
- _a new browser tab_ opens with current application's url
- after authenticating, nothing happens

I also checked another application (Trello) and even though they got some steps further, the success callback is never called:
- button click (on the application) triggers oneDrive.open(odOptions)
- _a new browser tab_ opens with current application's url
- after authenticating, the user is redirected to OneDrive in order to login
- after login, the user is presented with the folders and files
- the user can select a file
- an error is thrown
![4d2c7900-99d7-11ea-8252-5a8a70c81e2d](https://user-images.githubusercontent.com/1194366/82332754-16aa2a80-99e6-11ea-929b-7e5be8721390.png)

#### Steps to Reproduce
This happens for every application added to MS Teams as a website that uses the OneDrive file picker.

#### Additional Context
I think this is related to https://github.com/OneDrive/onedrive-api-docs/issues/650 but it never got resolved.

Thank you.

**Comment by boraunlu** [comment]
Hey, @jharzmann,

Were you able to find a workaround for this problem? 

Thank you,

**Comment by figgsoftware** [comment]
No unfortunately. These days Teams apps are the thing I have heard:) You should really make this work.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
