### ISSUE TITLE
ItemNotFound while forcerefresh

### ISSUE THREAD

**Issue by sumitmodi84** [OneDrive/onedrive-api-docs#1281]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior
Accessing the end point https://sharepointsite/_api/v2.0/drive/apps?forceRefresh=1 should return list of apps. 

#### Observed Behavior
Getting {"error":{"code":"itemNotFound","message":"Item not found" }} Stragenly, i am getting this error for india users while USA users it is working fine.
I have already checked it multiple times.
#### Steps to Reproduce

Thank you.

**Comment by chackman** [comment]
Could you please provide a request ID and date/time for your issue?

**Comment by sumitmodi84** [comment]
The way we are trying to access the resource api  is as following
From the browser, we first login to OneDrive and Sharepoint like
https://tenantname.sharepoint.com or https://tenantname-my.sharepoint.com
After that, we change the URL to
https://tenantname.sharepoint.com/_api/v2.0/drive/apps?forceRefresh=1  or  https://tenantname-my.sharepoint.com/_api/v2.0/drive/apps?forceRefresh=1  
Since, we are authenticated in the browser, browser automatically sends the accesstoken in the request.
Let me know, in case you want me to fire the request using the Postman to fire the request. 
Last we tried the request on 28th May 2020 at 8:00 PM UTC.

Can you plz guide me for where I can get the rest of the information like request-id and SPRequestGuid?

**Comment by chackman** [comment]
The Date, request-id, and SPRequestGuid are response headers that you should be able to find using an application like Fiddler or the Network tab in your browser's debugging tools (Postman probably also has this).
