### ISSUE TITLE
Bad Request when expanding on thumbnails for driveItems delta on AAD.

### ISSUE THREAD

**Issue by dcakirkaya** [OneDrive/onedrive-api-docs#1283]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior
According to https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#optional-query-parameters drive item delta queries support $expand:

> Optional query parameters
> This method supports the $select, $expand, and $top OData query parameters to customize the response.

I'm expecting this request to succeed (regardless of whether I login with my AAD or MSA account):
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=thumbnails

#### Observed Behavior

200 for MSA and successfully returns thumbnails, 400 for AAD.
```
{
    "error": {
        "code": "badArgument",
        "message": "One of the provided arguments is not acceptable.",
        "innerError": {
            "request-id": "2a0afa55-01c4-4dd0-9c60-19a04b7ceece",
            "date": "2020-05-20T01:18:34"
        }
    }
}
```
#### Steps to Reproduce

Login with a work/school account and GET https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=thumbnails

Repro on both v1.0 and beta endpoints of Graph.

Thank you.

**Comment by chackman** [comment]
Could you please clarify whether this is happening for an MSA account through Graph, or if this is a issue with ODB/work/school through Graph?  Thumbnails through delta are not supported in ODB.

**Comment by dcakirkaya** [comment]
@chackman I'd already specified both in the subject & descriptin that this is happening on AAD account (work/school) and works fine on MSA. What's ODB ? Could you update documentation because clearly this information is no where to be found.

**Comment by chackman** [comment]
"ODB" stands for OneDrive for Business. This is on our documentation backlog.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
