### ISSUE TITLE
Search all documents in the tenant which is shared with a user: How ?

### ISSUE THREAD

**Issue by nambin** [OneDrive/onedrive-api-docs#1284]
Let say the tenant organization has 
- user A
- group B with A as a member

What's the best way to get "all documents shared with A"?
I expected that "https://graph.microsoft.com/v1.0/me/drive/search" will do it, but it doesn't show "documents shared with group B" (For the record, it shows "documents shared with user A").

---------------------
Aside from that, is there a way to get "all documents in the organization shared with user A including link-shared" ?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a094aa0-adc5-9f08-d75e-bff6c5c42b4b
* Version Independent ID: c674446f-0d55-5c4b-0d0a-bbddf184dd1b
* Content: [Search for files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_search?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_search.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_search.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
