### ISSUE TITLE
One Drive delta ignores $top after initial sync is complete and sends responses with page size = 7

### ISSUE THREAD

**Issue by dcakirkaya** [OneDrive/onedrive-api-docs#1285]
#### Category
- [X] Question
- [X] Documentation issue
- [ ] Bug

I'm following the [Track changes for a Drive](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http) to make a drive items delta request. I want to be able to set a large page size to avoid throttling. 

#### Expected or Desired Behavior
I'm using $top=1000 (Seems like prefer odata.maxpagesize is ignored/not supported)

GET /me/drive/root/delta?$top=1000

#### Observed Behavior
I'm receiving 1000 items per response until the delta link is received and then I receive responses with page size = 7. These requests look like:

GET /me/drive/root/delta?$top=1000&token=##my_deltatoken##

Could you clarify  the expected API behavior and how to correctly receive items with a bigger page size than 7 when the delta token present? 

Thank you.

**Comment by ificator** [comment]
Quick clarifying question: are you targeting a business or personal user?

**Comment by dcakirkaya** [comment]
Observed this on business, but we're targeting both, I'd really like to understand the constraints for both cases if possible.

**Comment by dcakirkaya** [comment]
You're right, they're all deleted. (Except for the first-ever item I receive, which is the root). I deleted some large number of files from my one drive last week, and now every time I use a delta token, I seem to keep getting a bunch of deletions (7 items at a time) like this : 

delta#1 > next11..next21..next31.. > delta#2
delta#2 > next21..next22..next23.. > delta#3

Note that next11 and next21 contain different set of ids (but still, all deletions). I haven't made any other deletions  in my One Drive Business ever since.

Is this also a known issue? 

It looks like this:
```
> BEGIN SYNC : https://graph.microsoft.com/beta/me/drive/root/delta?$top=1000&token=MzslMjM0OyUyMzE7Mzs3NGI0MDA3NS00YmEwLTQxMjMtOWE1My1hNTcyMDBiOTA0Yzc7NjM3MjYwNDc0NzU5MzMwMDAwOzQ3NzA4MDY1MDslMjM7JTIzOyUyMzA +1ms
> 
> ...following 3852 next links later
> 
> END SYNC: https://graph.microsoft.com/beta/me/drive/root/delta?$top=1000&token=MzslMjM0OyUyMzE7Mzs3NGI0MDA3NS00YmEwLTQxMjMtOWE1My1hNTcyMDBiOTA0Yzc7NjM3MjYxMDIwNzQ2ODAwMDAwOzQ3NzU1MTAxMDslMjM7JTIzOyUyMzA +0ms
```
and repeats every time I use the delta token from the end sync.

**Comment by ificator** [comment]
Just to clarify, after your `END SYNC` you get a new `deltaToken` and if you use that you go through the 3852 next links again? I assume, after getting the new `deltaToken` (but before using it to make another `delta` request) you are not making any changes to your drive?

**Comment by dcakirkaya** [comment]
yes, I'm using the last delta token that I receive in END sync. and making no changes at all to my one drive in between (and would be highly unlikely that an app I'm using is triggering that many deletions each time).

**Comment by ificator** [comment]
That does seem strange - one more question... is the `token` shown on the `END SYNC` the `deltaToken` that was returned from the final page?

**Comment by dcakirkaya** [comment]
yes

**Comment by dcakirkaya** [comment]
so this stopped happening with no code changes on our side. seems like it was an intermittent issue but still affected us for a few days. would really like to understand why it was happening, is it always the case for deletions ?

**Comment by ificator** [comment]
The very small limit on deletes per response is unfortunately expected at this time, but the behavior you described whereby using a `deltaToken` obtained after enumerating all deletes results in another enumeration of deletes is not (assuming no changes occurred in the system to trigger them). I haven't heard of it before, and so if the behavior has stopped for you there's probably not much we can do to investigate. Let us know if you encounter it again.

**Comment by dcakirkaya** [comment]
got it, thank you!
