### ISSUE TITLE
Incosistent parentReference in search results

### ISSUE THREAD

**Issue by dkhizhniakov** [OneDrive/onedrive-api-docs#1287]
When doing search driveId in parentReference isn't consistent over time.

## Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

parentReference -> driveId should return the same value for the same object.

#### Observed Behavior

parentReference -> driveId differs on consequent requests. 
Example response 1 (driveId is fine):
`
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
  "value": [
    {
      "@odata.type": "#microsoft.graph.driveItem",
      "createdDateTime": "2020-01-24T06:11:27.107Z",
      "cTag": "adDo5RENFNERCQjAwN0Y4Q0VFITQ1OS42MzcxODE5NjY2NzgyNzAwMDA",
      "eTag": "aOURDRTREQkIwMDdGOENFRSE0NTkuMg",
      "id": "9DCE4DBB007F8CEE!459",
      "lastModifiedDateTime": "2020-02-25T03:04:27.827Z",
      "name": "1.108 re",
      "size": 305401,
      "webUrl": "https://1drv.ms/f/s!AO6MfwC7Tc6dg0s",
      "reactions": { "commentCount": 0 },
      "createdBy": {
        "application": { "displayName": "ARES Kudo", "id": "481f0597" },
        "user": { "displayName": "ANUJ KESARWANI", "id": "9dce4dbb007f8cee" }
      },
      "lastModifiedBy": {
        "application": { "displayName": "ARES Kudo", "id": "481f0597" },
        "user": { "displayName": "ANUJ KESARWANI", "id": "9dce4dbb007f8cee" }
      },
      "parentReference": {
        "driveId": "9dce4dbb007f8cee",
        "driveType": "personal",
        "id": "9DCE4DBB007F8CEE!101",
        "path": "/drive/root:"
      },
      "fileSystemInfo": {
        "createdDateTime": "2020-01-24T06:11:27.106Z",
        "lastModifiedDateTime": "2020-01-24T06:20:10.033Z"
      },
      "folder": {
        "childCount": 4,
        "view": {
          "viewType": "thumbnails",
          "sortBy": "name",
          "sortOrder": "ascending"
        }
      },
      "searchResult": {
        "onClickTelemetryUrl": "https://www.bing.com/personalsearchclick?IG=31F7FF3E4F6C4B68977C139117CE2ADE&CID=9DCE4DBB007F8CEE0000000000000000&ID=DevEx%2c5024&q=%7b1.108%7d&resid=9DCE4DBB007F8CEE%21459"
      }
    }
  ]
}
`

Response 2 - same request, but note driveId is different:
`
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
  "value": [
    {
      "@odata.type": "#microsoft.graph.driveItem",
      "createdDateTime": "2020-01-24T06:11:27.107Z",
      "cTag": "adDo5RENFNERCQjAwN0Y4Q0VFITQ1OS42MzcxODE5NjY2NzgyNzAwMDA",
      "eTag": "aOURDRTREQkIwMDdGOENFRSE0NTkuMg",
      "id": "9DCE4DBB007F8CEE!459",
      "lastModifiedDateTime": "2020-02-25T03:04:27.827Z",
      "name": "1.108 re",
      "size": 305401,
      "webUrl": "https://1drv.ms/f/s!AO6MfwC7Tc6dg0s",
      "reactions": { "commentCount": 0 },
      "createdBy": {
        "application": { "displayName": "ARES Kudo", "id": "481f0597" },
        "user": { "displayName": "ANUJ KESARWANI", "id": "9dce4dbb007f8cee" }
      },
      "lastModifiedBy": {
        "application": { "displayName": "ARES Kudo", "id": "481f0597" },
        "user": { "displayName": "ANUJ KESARWANI", "id": "9dce4dbb007f8cee" }
      },
      "parentReference": {
        "driveId": "8000000000000000",
        "driveType": "personal",
        "id": "9DCE4DBB007F8CEE!101",
        "path": "/drive/root:"
      },
      "fileSystemInfo": {
        "createdDateTime": "2020-01-24T06:11:27.106Z",
        "lastModifiedDateTime": "2020-01-24T06:20:10.033Z"
      },
      "folder": {
        "childCount": 4,
        "view": {
          "viewType": "thumbnails",
          "sortBy": "name",
          "sortOrder": "ascending"
        }
      },
      "searchResult": {
        "onClickTelemetryUrl": "https://www.bing.com/personalsearchclick?IG=5E286AF1CD9A4D369E823A6DEE4F6796&CID=9DCE4DBB007F8CEE0000000000000000&ID=DevEx%2c5024&q=%7b1.108%7d&resid=9DCE4DBB007F8CEE%21459"
      }
    }
  ]
}
`

As a workaround, I think we can use user's Id as a driveId if driveType=personal, but I'm not entirely sure if this is always true. Can you, please, confirm?

#### Steps to Reproduce

Just search for some folder/file several times and observe the parentReference. Unfortunately, it doesn't reproduce consistently for all accounts, only for some, but for those accounts the issue is consistent.

Let me know if I can provide any other info.

Thank you.

**Comment by BarryShehadeh** [comment]
Hi @dkhizhniakov 
While I take a look, I can confirm to you that the driveId is just the user's id for driveType=personal, so please feel free to use that.

Best,
Barry

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
