### ISSUE TITLE
I am not able to  select Folder while i need to select folder in my use case.

### ISSUE THREAD

**Issue by sonus2-chetu** [OneDrive/onedrive-api-docs#1288]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#parameters)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
