### ISSUE TITLE
Access revoking takes time to take an effect

### ISSUE THREAD

**Issue by dkhizhniakov** [OneDrive/onedrive-api-docs#1289]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Folder should be removed from "shared" section as soon as access has been revoked by other user.

#### Observed Behavior

It takes large amount of time (5-10 minutes) to update.

#### Steps to Reproduce

1. Create folder in user A account.
2. Share folder with user B - folder is shown in "shared" section of user B
3. Revoke access using user A account (either through API call or from onedrive.com UI)
4. Folder is still presented in "shared" section of user B and returned by API calls. Eventually it's removed, but the delay is too big and makes users worry.

Thank you.

**Comment by JeremyKelley** [comment]
If user B tries to access the folder after access has been revoked are they able to see contents, or just the entry in the Shared list?

**Comment by dkhizhniakov** [comment]
Hi, 
Sorry for late response - I've missed the notification.

Folder content is unavailable - it shows the message that "item might not exist or is no longer available", but the folder itself shows up in the "shared with me" list for quite a long time.

**Comment by dkhizhniakov** [comment]
Actually the latest test folder I've used is still shown in "shared with me" section. 
I've created the folder "SHARED_NATIVE_1" in account A and shared it with account B then revoked access (you can see that in "manage access" tab only the owner's account is shown - account A), but it still shown (~ 40 minutes after access has been removed) in account B. Contents aren't available and I can't do anything with this folder from account B, but it is still in the list.
![image](https://user-images.githubusercontent.com/25896054/87055087-8e3d4e80-c20c-11ea-92d9-792c2e10a74c.png)

**Comment by dkhizhniakov** [comment]
Hi, 
Any news here?
