### ISSUE TITLE
getting httpStatusCode: 409 while creating file "OneDrive for Business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#129]
when ever trying to create a file using PUT (simple file upload), without @name.ConflictBehaviour

PUT https://testfiberlink-my.sharepoint.com/%2F_api%2Fv2.0%2Fme/drive/items/root/children/hello.txt/content

getting following error
httpStatusCode: 409 reason: Conflict

"code: NameAlreadyExists | message: A resource with the same name already exists" 

but there is no such file with hello.txt name in the folder

**Comment by ankit-ankuagrawal** [comment]
the problem is files are getting created abt in response 409 with the error is cming

**Comment by rgregg** [comment]
Did you close this because you've resolved the issue?

**Comment by ankit-ankuagrawal** [comment]
@rgregg 
there is little bit confusion, currently @name.conflictbehaviour is not available for creating file, right...?

thts the problem when trying to upload the file for second time it is giving 409, wht should be done in this case now, otherwise anything edited and trying to upload it will fail 

wht should be done in tht case

**Comment by ankit-ankuagrawal** [comment]
@rgregg ty for ur reply
no it was my mistake, @name.ConflictBehavoiur for replace is working fine, didnt read out the docs carefully
