### ISSUE TITLE
Error thrown in Js Sdk:  e.data.indexOf is not a function

### ISSUE THREAD

**Issue by jotatoledo** [OneDrive/onedrive-api-docs#1290]
### Category

- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

No error should be thrown

#### Observed Behavior

As of v7.2 of the OneDrive file picker Sdk for JS, an error is thrown when invoking the `open` method:

```
OneDrive.js:4 Uncaught TypeError: e.data.indexOf is not a function
    at OneDrive.js:4
```

#### Steps to Reproduce

Simply invoke the `open` method

This was mentioned already in #863 

> There was also another issue of e.data.indexOf is not a function. That was fixed via adding an additional e.data.indexOf null check.

**Comment by shablenko-sednor** [comment]
Any updates on this issue?
I have the same bug

**Comment by dsnipe** [comment]
I have the same issue. Although it looks like it doesn't break anything, just an annoying error message in a console.

**Comment by react-ghost** [comment]
+1

**Comment by Knightabhi** [comment]
Having the same error trying to use Filepicker in React

**Comment by maxidr** [comment]
+1

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
