### ISSUE TITLE
Unable to upload files which are larger than 4MB using OneDrive Picker

### ISSUE THREAD

**Issue by splinter** [OneDrive/onedrive-api-docs#1291]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
The OneDrive Picker should allows larger than 4MB and less than 100MB to be uploaded. The following error is seen in the console:

![image](https://user-images.githubusercontent.com/53738/82898405-e7ac2f80-9f76-11ea-9ef2-8768f88d9157.png)

#### Observed Behavior
The OneDrive Picker allows file smaller than 4MB to be uploaded but fails when the file size is more than 4MB.

#### Steps to Reproduce

1. Upload any file larger than 4MB using the OneDrive Picker.

Thank you.

**Comment by chackman** [comment]
Could you please clarify whether this is still currently reproducing?
Also if it is could you please provide more information about the request that is failing, and the responses from the server?
