### ISSUE TITLE
How to get token for file handler refresh?

### ISSUE THREAD

**Issue by MalikDrako** [OneDrive/onedrive-api-docs#1292]
How do I get the right token to refresh the file handler cache? I have tried several different tokens, but none were accepted. 

Alternatively, is there now a way to do this through the Graph API? I have been able to get a token for the Graph API. Much of the documentation for file handlers seems to be out of date or redirect to less relevant sections for the newest APIs.

I am trying to add a custom file handler, but haven't found any kind of feedback from OneDrive on why it isn't appearing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18ba6d3-b187-12d6-2e08-418b0746ac5b
* Version Independent ID: dd01f1c1-7e26-39e2-9e06-afd3305c65e7
* Content: [Reload OneDrive File Handlers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/reset-cache?view=odsp-graph-online)
* Content Source: [docs/file-handlers/reset-cache.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/reset-cache.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by lukchen** [comment]
Any update ?

**Comment by MalikDrako** [comment]
I think I just ended up hitting the endpoint in my browser while I was logged in, but I ran into other issues with it not refreshing in a timely manner despite getting the expected response

**Comment by laurensmartz** [comment]
> I think I just ended up hitting the endpoint in my browser while I was logged in, but I ran into other issues with it not refreshing in a timely manner despite getting the expected response

same problem, any updates?

**Comment by MalikDrako** [comment]
I was able to complete development of my file handler by using the browser refresh, but the delay in updating was very annoying.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
