### ISSUE TITLE
Get "Must be authenticated to use '/drive' syntax" when using Graph Explorer

### ISSUE THREAD

**Issue by tweissin** [OneDrive/onedrive-api-docs#1294]
When I try to use the Graph Explorer to do any OneDrive operation, I get an error "Must be authenticated to use '/drive' syntax".

How can I fix this?

**Comment by chackman** [comment]
Could you please provide the URL, operation type, and request ID / date time that you are trying in Graph Explorer?  (example: GET to https://graph.microsoft.com/v1.0/me/drive works fine; note that any API calls to modify content do require sign-in)
