### ISSUE TITLE
Providing params breaks PDF preview.

### ISSUE THREAD

**Issue by tomoemp** [OneDrive/onedrive-api-docs#1295]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

By providing paramaters in request body, we get working embed url - even preview app doesn't support the params such as "zoom".

#### Observed Behavior

Preview doesn't render properly. Preview app container shows, but no pdf shown. (see the image below)
Sometimes document shows 1-2 sec, and then shows the blank document.
![image](https://user-images.githubusercontent.com/25950494/83503843-02752b80-a4c4-11ea-934a-47fe4de71251.png)

I realized the parameter in the geturl link "embed={"p":1,"z":50}"
If I remove quotation marks, preview renders.  ( embed={p:1,z:50} )

#### Steps to Reproduce

Get preview link of a pdf from preview endpoint. (both V1.0 and beta)

POST /drives/{driveId}/items/{itemId}/preview
Content-type: application/json
{"zoom":50,"page":"1"}

**Comment by JeremyKelley** [comment]
@kevklam is this a code bug for poor error handling or a doc bug that this needs to be more clear?

**Comment by sjkp** [comment]
@JeremyKelley is there any update on this? We are still blocked.

**Comment by sven5** [comment]
@sjkp I think you're wrong here. These parameters shouldn't be applied to GET request. You'll have to POST them in json format.
Please [see doc here](https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0). 

You can try it using [MS Graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer). 

example URL:
**POST https://graph.microsoft.com/v1.0/sites/xxxxxx-c030-475e-a498-23e6dbdf0471/drive/items/02BM7R3FHBUXUUVXYPURB3D47GORZGY3PJ/microsoft.graph.preview**

json parameters:
`{
   "zoom":1
}`

response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.itemPreviewInfo",
    "getUrl": "https://the.path.to.the.preview",
    "postParameters": null,
    "postUrl": null
}
```

**Comment by tomoemp** [comment]
@sven5 
I was posting with json parameters as I mentioned in "Steps to Reproduce".
![image](https://user-images.githubusercontent.com/25950494/93760297-014f4200-fc0c-11ea-8a2c-9232467224ef.png)

When I looked at the link (getUrl) I get in response, the link contained "embed={"p":1,"z":50}".
![image](https://user-images.githubusercontent.com/25950494/93760877-20020880-fc0d-11ea-80e6-ecd715848124.png)

I have just tried again. Now the link I got was urlencoded, and I could see the preview.
![image](https://user-images.githubusercontent.com/25950494/93760713-daddd680-fc0c-11ea-8822-bae7ae982085.png)

I guess you have fixed the problem.

**Comment by sven5** [comment]
When setting zoom level to a value of 50 I can see nothing.  The correct value is 0.5 for 50% - then it shows the correct preview with 50%.

Sure, when you get the url from the ms graph json response it's encoded. 
However, in the browser we see: `embed={"z":0.5}`

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
