### ISSUE TITLE
OneDrive : Accessing external shared folder through Graph API 

### ISSUE THREAD

**Issue by SP-2020-dev** [OneDrive/onedrive-api-docs#1296]
Hi,

I'm using One drive for Business. The" https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true" returns a list of folders (remoteItem), and I try to access this folders.
The "allowexternal=true" makes the requests returns external shares (across domains shares).

Accessing the non external shares (from the same domain) works perfectly using the endpoints :

- /drives/{driveId}/items/{itemId} (driveId and ItemId used are the one given in the remoteItem facet)

- /shares/u!id/driveItem (u!id is found using the Microsoft documentation https://docs.microsoft.com/fr-fr/onedrive/developer/rest-api/api/shares_get?view=odsp-graph-online#http-request)

However, when I try the same endpoints with external shares, its does not work ("Item Not Found" for the first request, and "The site in the encoded share URI is invalid" for the second request). My questions :

1. Has anyone ever used the "?allowexternal=true" option ?

2. Is access to external shares is possible across domain ? 

Thank you !

**Comment by mrdang1407** [comment]
I have the same problem, how can i upload file to external shared folder?

**Comment by RafaelReamp** [comment]
The same here, I have the same questions.

**Comment by chackman** [comment]
Thanks for your feedback.
To access external shares in another domain, the application currently needs to be authenticated with the external domain/tenant.

**Comment by SP-2020-dev** [comment]
Hi Chackman,

Thanks for your answer.
Reading https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant, **I finally succeeded accessing external shared folder through Graph API** : for an external share, the access token must be gotten by giving the **tenantId** in the request.

1. For a user A in a tenant Ta, get a refresh token using the https://login.microsoftonline.com/**common**/oauth2/v2.0/token endpoint. You will also get the token to access Ta.

2. A user B, in a tenant Tb shares a folder with the user A. When the user A lists shared folders ( https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true), the external share is visible. By the way, the tenantId is accessible through the same endpoint. The user A can then get an access token, using the https://login.microsoftonline.com/**{tenantId}**/oauth2/v2.0/token and providing the refresh token gotten at the first step. {tenantId} is user B tenant. Then, the user A can access shared folder.

Thanks !

**Comment by jeorling** [comment]
> 
> 
> Hi Chackman,
> 
> Thanks for your answer.
> Reading https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant, **I finally succeeded accessing external shared folder through Graph API** : for an external share, the access token must be gotten by giving the **tenantId** in the request.
> 
>     1. For a user A in a tenant Ta, get a refresh token using the https://login.microsoftonline.com/**common**/oauth2/v2.0/token endpoint. You will also get the token to access Ta.
> 
>     2. A user B, in a tenant Tb shares a folder with the user A. When the user A lists shared folders ( https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true), the external share is visible. By the way, the tenantId is accessible through the same endpoint. The user A can then get an access token, using the [https://login.microsoftonline.com/**{tenantId}**/oauth2/v2.0/token](https://login.microsoftonline.com/**%7BtenantId%7D**/oauth2/v2.0/token) and providing the refresh token gotten at the first step. {tenantId} is user B tenant. Then, the user A can access shared folder.
> 
> 
> Thanks !

Hi SP-2020-dev,

I'm having exactly the same issue, but I cannot get your two-step procedure to work. Could you please provide me with an example for the step 2 (getting access token from Tenant B and accessing shared folder)? I think that I can't find the correct API calls.

I will really appreciate your help.

**Comment by jeorling** [comment]
Thanks, SP-2020-dev! 
I think I got the point, just two more questions:
1. When getting access_token and refresh_token from Tenant B, don't you need to have you app registered too in Tenant B's Azure AD? Or at least grant some kind of permission.
2. Once you get Tenant B's access_token, do you access the shared folder using /drives/{Drive ID}/items/{Share ID}

Thanks again

**Comment by DavicVictor** [comment]
Hi @SP-2020-dev I am facing the same issue. I have been following what you have said about getting an access token from the tenant id. But then I am not able to get access to the file as it says : "Either scp or roles claim need to be present in the token". Did you have the same problem ?

**Comment by SP-2020-dev** [comment]
Hi Jeorling, 

1. When getting tokens from Tenant B, you do not have to have your app registered in Tenant B's Azure AD.

2. Once you get your Tenant B's access_token, you are able to access shared folder through _https://graph.microsoft.com/v1.0/drives/{drivedId}/items/**{itemId}**_ for example. The driveId and ItemId are accessed through the request _https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true_ : 
            "remoteItem": {
                ....
                "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                ....
                "parentReference": {
                    "driveId": "b!XXXX-XXXX-X_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                    ....
                },
                ...
                "sharepointIds": {
                    ....
                    "tenantId": "XXXXXXXXX-XXXXX-XXXX-XXXX-XXXXXXXXXXXXX",
                    ....
                }
            }

**Comment by SP-2020-dev** [comment]
Hi DavicVictor,

I didn't have the same issue.
You might have trouble with roles claim. I suggest you take a look at [this ](https://github.com/pnp/cli-microsoft365/issues/1738)and [this](https://stackoverflow.com/questions/35839675/graph-api-either-scp-or-roles-claim-need-to-be-present-in-the-token).

**Comment by Knele83** [comment]
Poslato sa mog uređaja Galaxy


-------- Originalna poruka --------
Od: SP-2020-dev <notifications@github.com>
Datum: 14.1.21. 13:37 (GMT+01:00)
U: OneDrive/onedrive-api-docs <onedrive-api-docs@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Naslov: Re: [OneDrive/onedrive-api-docs] OneDrive : Accessing external shared folder through Graph API (#1296)


Hi Jeorling,

  1.  When getting tokens from Tenant B, you do not have to have your app registered in Tenant B's Azure AD.

  2.  Once you get your Tenant B's access_token, you are able to access shared folder through https://graph.microsoft.com/v1.0/drives/{drivedId}/items/**{itemId}<https://graph.microsoft.com/v1.0/drives/%7BdrivedId%7D/items/**%7BitemId%7D>** for example. The driveId and ItemId are accessed through the request https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true :
"remoteItem": {
....
"id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
....
"parentReference": {
"driveId": "b!XXXX-XXXX-X_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
....
},
...
"sharepointIds": {
....
"tenantId": "XXXXXXXXX-XXXXX-XXXX-XXXX-XXXXXXXXXXXXX",
....
}
}

**Comment by jeorling** [comment]
Hi SP-2020-dev,

Relating your point 1 below, how do you get a token from Tenant B,
considering that your account is from Tenant A, if you do not register your
app in Tenant B's AD? Can you provide an example API call to achieve this?

I explicitly asked Microsoft support and they told me that this
registration is required:

"When you execute "me/drive/sharedwithme", you receive back the references
only that were stored for your user, but they act like "pointers". For each
reference returned by this API method you should generate an access token
for each tenant do direct content access from "*drives('id')/items('id')*"



It means that in order to access an external shared DriveItem with Graph
API, you have to create an app registration in target tenant with at
least Files.Read.All API Permission (Highly suggest to be a Delegation to
ensure that only users with access to specific content can access them)."


Regards,

**Comment by hiepsieunhan** [comment]
Hi @SP-2020-dev,

I am having the exact use case as you.

Following your steps, I am able to get the `access_token` for external tenant. The response having `scope = profile openid email`

When I am trying to access the shared folders from external tenant with API, e.g https://graph.microsoft.com/v1.0/sites/{site-id}/drive/items/{item-id}, I always get `Access denied.` error.

Do I need to request for any scope/permission when using `https://login.microsoftonline.com/**{tenantId}**/oauth2/v2.0/token` to get the token?

Thanks

**Comment by andreidore** [comment]
@hiepsieunhan 

How do you succed to make https://login.microsoftonline.com/**{tenantId}**/oauth2/v2.0/token ?
What parameters do you provide in the body of the request? Special headers?

**Comment by SP-2020-dev** [comment]
Hi @hiepsieunhan,
As written in the Microsoft link [](https://docs.microsoft.com/fr-fr/graph/auth-v2-user), you do need to ask for a scope when requesting for a token (/token endpoint). I suggest : 

- You use [](https://jwt.ms/) so you can read what as your token specifications,
- You ask directly for a specific scope (at least to debug) when asking for a token, and not using the '.default' endpoint. For example : 
`https://graph.microsoft.com/files.readwrite.all "\
    L"offline_access "\
    L"https://graph.microsoft.com/sites.readwrite.All "\
    L"https://graph.microsoft.com/User.ReadBasic.All "\
    L"https://graph.microsoft.com/Mail.Send "\
    L"https://graph.microsoft.com/User.ReadWrite`

**Comment by SP-2020-dev** [comment]
Hi @jeorling,

When connecting to an external tenant, you do not register your app but only the user **when the user authentication** is performed. As described in my previous posts, when a folder is shared with a user A, user A :

- Can access to the tenand-Id, driveId and itemId of the shared folder (using /sharedWithMe endpoint),
- Can authenticate to the external shared folder, using the endpoint : 
`https://login.microsoftonline.com/{external-tenant-id}/oauth2/v2.0/authorize?...`
- Can get token using the endpoint : 
`https://login.microsoftonline.com/{external-tenant-id}/oauth2/v2.0/token`

When performing an authorization (/authorization endpoint), it should be a delegated persmissions (and not an application permissions), so the actions are performed on behalf of the user. In that way, the user A is registered in the external Azure AD (as a guest user). It may be what Microsoft calls "an app registration", but when this delegated permissions, it becomes a "user registration".

**Comment by jviney** [comment]
I'm trying to get an auth in tenant B so a user from tenant A can get a fetch a shared OneDrive item. This error appears when trying to auth using MSAL.

![Screen Shot 2021-05-19 at 10 49 39 AM](https://user-images.githubusercontent.com/7051/118733287-1dd17600-b890-11eb-9e1e-5f892ea38135.png)

If I manually invite user A as a guest user in tenant B, the errors goes away. I can only do this for testing because we control both tenants. Is there a way to do this without having to create guest users?

**Comment by SP-2020-dev** [comment]
@jviney,

This happens because you did not use the share link that is created when you perform the share operation with external user that are not know in the tenant making the share operation. The url looks like this (for Business account) :
`https://XXXXXX-my.sharepoint.com/:f:/g/personal/user_name_XXXXX_onmicrosoft_com/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

- The first time this link is imported, you have to provided a one-time passcode, as described here : 
`https://docs.microsoft.com/en-us/azure/active-directory/external-identities/one-time-passcode`
- Once the passcode is provided, a redirection is performed, so the authentication can be perfomed through : 
`https://login.microsoftonline.com/{external-tenant-id}/oauth2/v2.0/authorize?...`
`https://login.microsoftonline.com/{external-tenant-id}/oauth2/v2.0/token`

**Comment by lochri** [comment]
I am using a registered application that has the permissions for the GraphApi to get drive items from sharepoint. It works fine to download shared files attached to emails for files that are on our own domain/tenant.
If one of our users receives an email with a shared sharepoint file from an external tenant i am not able to download it.

I tried getting the access token from https://login.microsoftonline.com/{external-tenant-id}/oauth2/v2.0/token
but using it i am getting this response:
{"error":{"code":"AccessDenied","message":"Either scp or roles claim need to be present in the token.","innerError":{"date":"2021-06-29T10:44:44","request-id":"xxx","client-request-id":"xxx"}}}

How can i get access using the application permissions without any user interaction?

**Comment by SP-2020-dev** [comment]
Hi @lochri,

"Either scp or roles claim need to be present in the token"
- You should verify what permissions you are asking when getting the access token.
- Use https://jwt.ms so you access permissions provided in the token.

"I am using a registered application that has the permissions for the GraphApi"
Do you use an access "on behalf of a user" or "without a user" to get your token ? I guess in each mode, there is a user (or admin) interaction

**Comment by lochri** [comment]
I have the application permissions on our own tenant/domain. So i am trying to access the external files without a user.
The only permission that is successful when requesting the token from the external tenant is the https://graph.microsoft.com/.default

I am using 
grant_type=client_credentials 
response_type=code

I have tried requesting other, more specific scopes like Files.ReadWrite but they all fail to get the token.

I have to get the file without user interaction, because this is a server based process.

**Comment by tooptoop4** [comment]
did u solve @lochri ?

**Comment by matthewhampton** [comment]
@lochri @tooptoop4 @SP-2020-dev I am also struggling to get access to a shared file on another tenant using this strategy (https://github.com/OneDrive/onedrive-api-docs/issues/1296#issuecomment-646489874):

> 
> 1. For a user A in a tenant Ta, get a refresh token using the https://login.microsoftonline.com/**common**/oauth2/v2.0/token endpoint. You will also get the token to access Ta.
> 2. A user B, in a tenant Tb shares a folder with the user A. When the user A lists shared folders ( https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true), the external share is visible. By the way, the tenantId is accessible through the same endpoint. The user A can then get an access token, using the [https://login.microsoftonline.com/**{tenantId}**/oauth2/v2.0/token](https://login.microsoftonline.com/**%7BtenantId%7D**/oauth2/v2.0/token) and providing the refresh token gotten at the first step. {tenantId} is user B tenant. Then, the user A can access shared folder.
> 

Specifically when I try to "get an access token, using the [https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token](https://login.microsoftonline.com/**%7BtenantId%7D**/oauth2/v2.0/token) and providing the refresh token gotten at the first step" I find that my app has not been authorized on the third-party tenant - it returns this error :`AADSTS65001: The user or administrator has not consented to use the application with ID 'xxxxxxx-xxxxx-xxxxx' named 'yyyy yyyy yyyy'. Send an interactive authorization request for this user and resource.`

I suppose this is understandable - even though the third-party user has shared a file with my user, they have not explicitly authorized my application to access it. I think maybe this is what you were referring to here, @SP-2020-dev : https://github.com/OneDrive/onedrive-api-docs/issues/1296#issuecomment-842249928

I any case, I am about ready to give up on this - but if anyone does know something that I don't and can reveal how you could have access even without that interaction, I would love to know about it!

**Comment by rscs** [comment]
@matthewhampton I am facing the same problem you mentioned above.  Were you ever able to figure this out?

**Comment by lochri** [comment]
@matthewhampton , unfortunately i could not solve it. I wonder how outlook does it? Because there the shared items from other tenants show up.

**Comment by jcharnley** [comment]
depends on the setup of the root tenant where it is being shared from

MS Graph API has known issues with external sharing isnt the root tenant is not full open. Alot of large orgs dont have a fully open tenant, this is different from where the file is shared from and who has access it, its another lvl up from that
