### ISSUE TITLE
Application registrations portal is no longer available

### ISSUE THREAD

**Issue by pacific202** [OneDrive/onedrive-api-docs#1297]
There is a link to the Application registrations portal which sends me to a page that says this:

Application registrations portal is no longer available to register and manage converged applications. We recommend that ​you manage your existing applications and register new applications by using the App registrations (now Generally Available) experience in the Azure portal. ​

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be99838-ec0d-2d14-954e-4a6cff48096d
* Version Independent ID: bb52ff31-8e3d-122f-edbb-6b1cb3fde806
* Content: [Access OneDrive and SharePoint via Microsoft Graph API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online)
* Content Source: [docs/rest-api/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback. The Graph team has a page here regarding auth: https://docs.microsoft.com/en-us/graph/auth-register-app-v2

I couldn't find the broken link on the page you are referencing ("Access OneDrive and SharePoint via Microsoft Graph API - OneDrive dev center"), which page has the broken link?  We have an item to fix these links on our backlog.
