### ISSUE TITLE
documentation missing for deltashowremovedasdeleted and deltatraversepermissiongaps

### ISSUE THREAD

**Issue by baywet** [OneDrive/onedrive-api-docs#1298]
If one uses "Prefer: deltashowsharingchanges" as documented here on a Microsoft Graph delta query (drive), one will get the following error message 
```json
{
    "error": {
        "code": "invalidRequest",
        "message": "Must also prefer deltashowremovedasdeleted and deltatraversepermissiongaps when preferring deltashowsharingchanges for a user request.",
        "innerError": {
            "date": "2020-06-17T14:03:11",
            "request-id": "82052e06-2dca-4847-838d-73cf96877849"
        }
    }
}
```
Documenting the existing, effect, defaults and potentially opposites of those two header values would help understand what the delta response is returning depending on the header values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b036f172-b0cf-d2af-1307-a3f5abf49524
* Version Independent ID: 894da04b-5803-4f44-a94f-0fa462b006a9
* Content: [Best practices for discovering files and detecting changes at scale - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#scanning-permissions-hierarchies)
* Content Source: [docs/rest-api/concepts/scan-guidance.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/scan-guidance.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley

**Comment by ificator** [comment]
Hi @baywet can you tell me if you're making your request using an app-only token? What application permissions have you requested?

**Comment by baywet** [comment]
Thanks for the follow up @ificator . At the time I was trying with Microsoft Graph Explorer because I'm trying to document the headers in the MS Graph docs https://github.com/microsoftgraph/microsoft-graph-docs/pull/8757

**Comment by ificator** [comment]
Ok that makes sense - the scan guidance is targeted at app-only / daemon / crawler scenarios and so some of what it describes applies only to that kind of auth. In this case, if the caller is not an "app-only" token it'll fail with that error.

**Comment by baywet** [comment]
So I can only use "Prefer: deltashowsharingchanges" in an apponly context?

**Comment by chackman** [comment]
Graph Explorer does not support apponly context - every request thru Graph Explorer is user context.  The preference `deltashowsharingchanges` will work in user context, but may require the additional preferences (which as you mention are not currently documented).

**Comment by baywet** [comment]
@chackman can you provide me with the specific details of the undocumented headers please so I can include it in graph docs?

**Comment by chackman** [comment]
@baywet just wanted to double-check - are we good to close this since you've made the doc update? Or did you have other questions?

**Comment by baywet** [comment]
Docs is still missing a couple of options as far as I remember because I didn't have the information. I have transitioned to a new role however. Closing
