### ISSUE TITLE
Office 365 onedrive api generate share link error.

### ISSUE THREAD

**Issue by williamparker88** [OneDrive/onedrive-api-docs#1299]
Hello, 
Could someone explain to me where im wrong? I try to generate a share link via microsoft api but i get this : 

`{
  "error": {
    "code": "itemNotFound",
    "message": "The resource could not be found.",
    "innerError": {
      "date": "2020-06-17T18:08:09",
      "request-id": "06fe190c-fa09-4544-8a6f-a2921de2941e"
    }
  }
}`

The code which i use 

`curl.exe https://graph.microsoft.com/v1.0/me/drive/root:/test.txt:/createLink -X POST -d '{"type": "view"}' -H "Authorization: bearer myapikey"`

> 

Im using a student account on office 365
Edit: English is not my native language sorry for grammar mistakes.

**Comment by chackman** [comment]
Thanks for your feedback. The error suggests that the file `test.txt` does not exist in the root folder of the current user's drive.
If you perform GET on `https://graph.microsoft.com/v1.0/me/drive/root:/test.txt:/`, does that work?
