### ISSUE TITLE
why the "https://api.onedrive.com/%2Fv1.0/drive/items/root/children" url is failing

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#130]
GET https://api.onedrive.com/%2Fv1.0/drive/items/root/children

why this url is invalid, pls anyone can explain???

following error was responded

![untitled2](https://cloud.githubusercontent.com/assets/11455759/8045826/d7332190-0e53-11e5-95d2-efaa151cd658.png)

**Comment by peternied** [comment]
Looks like you have an extra %2F in front of the version number, try this url instead:

https://api.onedrive.com/v1.0/drive/items/root/children

**Comment by ankit-ankuagrawal** [comment]
@peternied the url u suggested is working absolutely fine...

i was concern for uri https://api.onedrive.com/%2Fv1.0/drive/items/root/children

because the uri "https://mdm05-my.sharepoint.com/%2F%2F_api%2Fv2.0%2Fme/drive/items/root/children" is working absolutely fine, as u can observer this as 2 extra %2F before _api

**Comment by peternied** [comment]
Thanks for reporting, that extra '/' should be an error.

**Comment by ankit-ankuagrawal** [comment]
@peternied there are two extra '/', can u pls elaborate abt this error little, because my code is generating this all url, and this all wrong...

ty for ur reponse

**Comment by peternied** [comment]
@ankit-ankuagrawal The endpoint that you are interacting with should not be accepting a request that has leading '/' in it.  We should have uniform constraints on all of our urls no matter the endpoint.

**Comment by rgregg** [comment]
Since this isn't a blocking issue, I'm closing the issue out.
