### ISSUE TITLE
Upload metadata along with large file upload (using upload session)

### ISSUE THREAD

**Issue by madhavsankar** [OneDrive/onedrive-api-docs#1300]
How to upload metadata (that are searchable) along with these items?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d409f771-fd62-e549-d581-aac009e79e8c
* Version Independent ID: fe646b3a-06f5-a269-47e6-b4ee693e5410
* Content: [Resumable file upload - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_createuploadsession.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createuploadsession.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback. Supporting this in one request would be a separate feature enhancement.
However, if you wanted to change `driveItem` properties you can change them once the file has completed upload. (The `driveItem` is returned at completion.)

If the file belongs to a SharePoint Document Library, then your application could also access the `listItem` (available as a relationship on the `driveItem` resource) and then change custom metadata columns there.

With respect to searchability you may need to make the column searchable, which may only be supported in SharePoint. This is likely documented in SharePoint search documentation.
