### ISSUE TITLE
FileHandler not redirecting to the specified URL

### ISSUE THREAD

**Issue by dvd95** [OneDrive/onedrive-api-docs#1302]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
After registering FileHandler, on click of file-name we should be redirected to the URL mentioned in the manifest. If there are multiple File Handler registered we can select them from the 3 dots menu and the expectation is we should be redirected to the corresponding URL.

#### Observed Behavior

Some times on click of file-name, a new tab is opened with empty URL. In case there are multiple FileHandlers, on click of one FileHandler the redirection is on the URL of the next FileHandler mentioned.

This is intermittent issue and gets resolved without any changes from our side.

#### Steps to Reproduce
Issue1
1. Register a FileHandler
2. After it gets reflected, click on the file-name where it is registered.
   - You are redirected to an empty page.

Issue2
1. Register 2 FileHandlers, FileHandler1 and FileHandler2
2. After it gets reflected, click on 3 dots option and choose FileHandler1.
   - You are redirected to FileHandler2.url

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
