### ISSUE TITLE
Drive Item returned by MSFT using graph API has lastModifiedAt date in future 

### ISSUE THREAD

**Issue by agrankur** [OneDrive/onedrive-api-docs#1303]
Bug Description:
Sometime the lastModifiedDate returned in driveItem in a delta query or fetch drive item or fetch children returns the lastModifiedAt date in future

Expected Behavior:
lastModifiedAt date cannot be in future. 

We do not have the request details of when this happened but we have seen this in a few cases.

**Comment by chackman** [comment]
When you experience this issue could you please provide request ID and timestamp? That way we could reach out to a partner team to see if they can investigate.
