### ISSUE TITLE
Preview getURL doesn't show CSV

### ISSUE THREAD

**Issue by tomoemp** [OneDrive/onedrive-api-docs#1304]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
A preview of the CSV file is shown, when the user navigates to "getUrl" in the response of POST request to "/drives/{driveId}/items/{itemId}/preview".

#### Observed Behavior
We get an error message in preview as below. This happens both in iframe and in browser, and for both semicolon separated and comma separated csv file.

![image](https://user-images.githubusercontent.com/25950494/86099928-69343780-bab8-11ea-95fb-885ce570ac75.png)

#### Steps to Reproduce
1. POST request to : https://graph.microsoft.com/v1.0/drives/{driveId}/items/{itemId}/preview
2. Navigate to "getUrl" in the response. 
  (example of response)
   {"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.itemPreviewInfo",
    **"getUrl":"https://{tenant}/sites/{sitename}/_layouts/15/embed.aspx?uniqueId={uniqueId}&access_token={access_token}",**
    "postParameters":null,
    "postUrl":null}

**Comment by kpreddy89** [comment]
We are facing this issue as well, the getUrl" in the response of POST request to "/drives/{driveId}/items/{itemId}/preview" lead to this
![image](https://user-images.githubusercontent.com/28785014/95239108-1e009200-0828-11eb-8e5e-c53e5c475828.png)

**Comment by kpreddy89** [comment]
![image](https://user-images.githubusercontent.com/28785014/95239255-4f795d80-0828-11eb-971a-da02724a0c4d.png)
We are facing the same issue for csv files

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
