### ISSUE TITLE
Microsoft Graph Drive search API does not work for some file names

### ISSUE THREAD

**Issue by lpoublan** [OneDrive/onedrive-api-docs#1305]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

The[ search for a drive item api ](https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http) does not find some files. I added many files with the same content but different names in my drive.
It tried the following call for all my files: 
GET /me/drive/root/search(q='{file_name}')
It works for many files, but not for others.
I tried several times, always get the same result.
I am not able to find a pattern for the file names, but it seems names containing a dash or more than one dot or parentheses are affected. Maybe some characters are not correctly handled?
For instance, this query does not find my file (which is named 04-20-142.pdf):
GET /me/drive/root/search(q='04-20-142.pdf')
However I can find this file with the following requests:
GET /me/drive/root/search(q='04-20-142')
or
GET /me/drive/root/search(q='-142.pdf')

The file extension does not matter, same result with "04-20-142.txt".
Also, the file can be at the root of the drive or in a subdirectory, the result is the same.
I did not find any way to find a file by name in a drive other than listing all files in the drive recursively.
I tried in team drives and my drive, with hundreds of file names.

#### Expected or Desired Behavior

There needs to be a way to get a file by name in a drive.
The search drive item should at least return file with the exact name entered.

#### Steps to Reproduce

Add a file named "04-20-142.pdf" in your drive and try to find it with 
GET /me/drive/root/search(q='04-20-142.pdf')

Same result with beta and v1.0  API versions.

Thank you.

**Comment by ti55987** [comment]
I met the same issues. Do we know what characters are being affected so we can avoid them? Thanks

**Comment by VKVSH** [comment]
I am observing the same issue since last few weeks on code that was *definitely working fine* earlier

**Comment by Loppone** [comment]
Same problem.

This works:
https://graph.microsoft.com/v1.0/drives/<My_Drive_Id>/search(q='{enel.pdf}')

This not works:
https://graph.microsoft.com/v1.0/drives/<My_Drive_Id>/search(q='enel.pdf')

**Comment by sudhakar3697** [comment]
Having the same issue now also

**Comment by kyohei-ts** [comment]
I'm also having the same issue when using the API in SharePoint Document Library. 
I thought there was some issues with permissions so I checked Azure AD Enterprise Application has correct permissions. 
Issue seems to happen either when I logged in with my account or logged in with Enterprise Application.
A few items just can't search with this API. 

In my case... 

* a few folders are not searchable. 
* logged in account does not matter for the issue
* can get the item if I search with partial name. ("full_name" is not working but "name" is wokring)
* [List the contents of a folder](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http) API can give me the item I"m searching

**Comment by oharrell** [comment]
We also having the same issue when using the API in SharePoint Document Library. Some examples I have to share for help debugging. We will have to perform a workaround with the empty search until this is fixed it appears. 

**Document 1**: 0694d821-0f3f-4c23-81db-e5321038cde0.pptx

**Works**:
https://graph.microsoft.com/v1.0/drives/<My_Drive_Id>/root/search(q='0694d821-')

**Doesn't work**:
https://graph.microsoft.com/v1.0/drives/<My_Drive_Id>/root/search(q='0694d821-0')

**Document 2**: d9a79790-5e42-4f4e-8aff-d45111e142f8.docx

**Works**:
https://graph.microsoft.com/v1.0/drives/<My_Drive_Id>/root/search(q='d9a79790-5e42-4f4e-8aff-d45111e142f8.docx')


And finally, I see Document 1 and 2 when I do an empty search, so they are there. 

**Works**: https://graph.microsoft.com/v1.0/drives/<My_Drive_Id>/root/search(q='')

**Comment by cosmin-teslovan** [comment]
Same issue here. Looks like nobody cares about this issue. Is there a workaround or a fix that is not documented? Thank you! 🙏

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
