### ISSUE TITLE
Failure return values

### ISSUE THREAD

**Issue by RichardPointon** [OneDrive/onedrive-api-docs#1306]
[Enter feedback here]

What is the status that is returned when the operations fails ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccad95fe-ccea-c668-17c3-90781dc6b416
* Version Independent ID: cdd73909-251b-ed82-6a3b-778c7f5ce08a
* Content: [Calling long running actions - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/long-running-actions?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/long-running-actions.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/long-running-actions.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
For information about common error responses and codes, see this page
  https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/errors?view=odsp-graph-online

**Comment by RichardPointon** [comment]
It would seem that the API returns 200 with a status of failed, this is not documented.

{"@odata.context":"https://xxxxxxx-my.sharepoint.com/personal/devtest_dn-lab_com/_api/v2.1/$metadata#drives('default')/operations/$entity","id":"21490691-da30-4f6c-ac7b-e737e6526718","createdDateTime":"0001-01-01T00:00:00Z","lastActionDateTime":"0001-01-01T00:00:00Z","status":"failed","error":{"code":"nameAlreadyExists","message":"Name already exists"}}

**Comment by ificator** [comment]
The operations endpoint is a little different - the `200` represents the successfully retrieve of the status of an asynchronous operation. Whether that asynchronous operation succeeded or failed is exposed as metadata in the status response.
