### ISSUE TITLE
Graph API 429 error (activityLimitReached) returned immediately when issuing a query request to https://graph.microsoft.com/beta/sites

### ISSUE THREAD

**Issue by Dam0nW** [OneDrive/onedrive-api-docs#1307]
I receive a 429 error response immediately after issuing a Graph API query request to https://graph.microsoft.com/beta/sites, no data is ever returned with the complete response below. This is clearly not a standard Graph API throttling response as it doesn't contain Retry-After. Can this be fixed please?

HTTP/1.1 429
Content-Type: application/json
request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
client-request-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"4","ScaleUnit":"005","RoleInstance":"AGSFE_IN_33"}}
Strict-Transport-Security: max-age=31536000
Date: Wed, 01 Jul 2020 11:08:23 GMT
Content-Length: 271
Cache-Control: private, proxy-revalidate
Connection: Keep-Alive

{
  "error": {
    "code": "activityLimitReached",
    "message": "The request has been throttled",
    "innerError": {
      "code": "throttledRequest",
      "date": "2020-07-01T11:08:23",
      "request-id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    }
  }
}

**Comment by chackman** [comment]
Thanks for your feedback, we will need to investigate this issue.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
