### ISSUE TITLE
shared with me for personal api

### ISSUE THREAD

**Issue by ccomangee** [OneDrive/onedrive-api-docs#1308]
How can i list up shared folders/files with?

I tried to request the url such as "https://api.onedrive.com/v1.0/drive/sharedWithMe".

But the response is "Api Not Found" or "Invalid Request or Resource".

I can not find concerning documents about it.

**Comment by chackman** [comment]
We [recommend using Microsoft Graph](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online); a couple pointers:
  Overview of Microsoft Graph:
    https://docs.microsoft.com/en-us/graph/overview
  List items shared with the signed-in user:
    https://docs.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0&tabs=http
