### ISSUE TITLE
Embeded URl

### ISSUE THREAD

**Issue by Muhammad-saqib** [OneDrive/onedrive-api-docs#1309]
[Enter feedback here]

those who request type is Edit and Organization  .it will returned editable  share url but i want to use in iframe 
and want to send Token to open in client side   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69601057-a846-2eea-33b4-9e1760981e88
* Version Independent ID: 5cbaae53-7d99-8075-609a-30d82c9ad0c8
* Content: [Share a file with a link - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_createlink.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createlink.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
To clarify are you asking about whether the `embed` link type is supported on OneDrive for Business?  If so, it is not currently supported, and we would recommend suggesting this as an enhancement here: 

> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice
