### ISSUE TITLE
get owner's email address of file/folder shared with me

### ISSUE THREAD

**Issue by ccomangee** [OneDrive/onedrive-api-docs#1312]
I can't get the owner's email address of what shared with me.

I can get the owner's id from shared.owner.user.id of A DriveItem.

But when trying to get the email address of the id, It returns one of sigin-in user.
I've tried this several time changing permissions( User.Read, User.BasicRead, User.Read.All)

I thinks it's a bug.

the following is sample;

request: /users/4168cffb3d4eXXXX

response: {"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users/$entity","displayName":"kim kim","surname":"kim","givenName":"kim","id":"**sigin-in-user-id**","userPrincipalName":"**sigin-in-user-email**","businessPhones":[],"jobTitle":null,"mail":null,"mobilePhone":null,"officeLocation":null,"preferredLanguage":null}

**Comment by chackman** [comment]
Could you please clarify whether this is a request for OneDrive Personal or OneDrive for Business / SharePoint?
Also could you please provide a request ID and timestamp in UTC?
I'll tag so our helpful bot will provide more information about what we require to investigate further.

**Comment by ccomangee** [comment]
It's a request for personal.
I'd like to provide the details, but what do you mean "request id"?
UTC time is about July 13th, 04:12:00

the following the sample codes and logs:

============================ sample codes ===============================

DefaultLogger defaultLogger = new DefaultLogger();
        DefaultSerializer serializer = new DefaultSerializer(defaultLogger);
        DefaultExecutors executor = new DefaultExecutors(defaultLogger);
        IAuthenticationProvider auth = new IAuthenticationProvider() {
            @Override
            public void authenticateRequest(IHttpRequest request) {

                request.addHeader("Authorization", "Bearer " + token);

                Log.e("P2", "method:" + request.getHttpMethod());
                Log.e("P2", "request:" + request.getRequestUrl().toString());
                request.setUseCaches(false);
            }
        };
        IGraphServiceClient graphClient = new GraphServiceClient.Builder()
                .httpProvider(new DefaultHttpProvider(serializer, auth, executor, defaultLogger))
                .executors(executor)
                .serializer(serializer)
                .authenticationProvider(auth)
                .logger(defaultLogger)
                .buildClient();


        IBaseDriveSharedWithMeCollectionRequestBuilder request = graphClient.getDrive().getSharedWithMe();
        IDriveSharedWithMeCollectionPage page2 = request.buildRequest().get();

        String lastId = null;
        for (DriveItem d : page2.getCurrentPage()) {
            Log.e("P2", "shared:" + d.name + ",owner:" + d.remoteItem.shared.owner.user.id);
            lastId = d.remoteItem.shared.owner.user.id;
        }


        IUserRequest ir = graphClient.getUsers(lastId).buildRequest();

        User user = ir.get();
        Log.e("P2", "sharedOwner:" + user.userPrincipalName + "," + user.mail + "," + lastId + "," + user.id);


======================= sample logs =========================================

method:GET
request:https://graph.microsoft.com/v1.0/drive/microsoft.graph.sharedWithMe
shared:my-file-name,owner:4bcbc2310d39d3ec
method:GET
request:https://graph.microsoft.com/v1.0/users/4bcbc2310d39d3ec
sharedOwner:**sign-in-user-email**,null,**4bcbc2310d39d3ec,400e580b9296e15d**

**Comment by chackman** [comment]
The Graph API call should have a response header named "request-id".

Since the request to the /users/ API returns the incorrect email and ID, you should contact the Graph team. I'll tag so that our bot can point you to Graph StackOverflow.
