### ISSUE TITLE
The QuickXorHash value on the DriveItem does not match the quickXorHash computed for .zip files downloaded. 

### ISSUE THREAD

**Issue by ddineen** [OneDrive/onedrive-api-docs#1314]
[Enter feedback here]
public static byte[] ComputeQuickXor(string filePath)
        {
            using (var quickXor = new QuickXorHash())
            {
                using (FileStream stream = File.Open(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                {
                    return quickXor.ComputeHash(stream);
                }
            }
        }

----
  byte[] quickX = Helper.ComputeQuickXor(downloadfilefromonedrive);
                string localHash = Convert.ToBase64String(quickX);

                if (driveItem.File.Hashes.QuickXorHash == localHash) ..... 
--- 
for a .ZIP file this does not match at all.
I am using - for the QuickXorHash
//https://gist.githubusercontent.com/rgregg/c07a91964300315c6c3e77f7b5b861e4/raw/eb2a9e7bc50a1521cff325d4b4524dbc8fb059bf/QuickXorHash.cs
//https://docs.microsoft.com/en-us/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0031e667-d40f-7ca2-7cab-13c8a941f711
* Version Independent ID: ff6ce5d0-08c7-58d2-d598-cba114f4c578
* Content: [QuickXOR Hash Sample - OneDrive - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online)
* Content Source: [docs/code-snippets/quickxorhash.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/code-snippets/quickxorhash.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Could you please provide more information about your request - is this reproducing in OneDrive Personal, OneDrive for Business, etc., and could you also provide a request-id + timestamp (UTC) for your requests?
I'll tag so our helpful bot will fill in more information about what you can provide to help us.
