### ISSUE TITLE
Adding known constraints with HTML --> PDF conversion

### ISSUE THREAD

**Issue by SheaAhna** [OneDrive/onedrive-api-docs#1318]
Hello,

I have a couple of bullet points I would like to add regarding known constraints and best practices with HTML to PDF conversion. Who would I engage to get this page updated?

Thanks,
Shea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46acaeca-c7f2-1013-239e-93853818f3d7
* Version Independent ID: 8b42fae5-53c9-f8c3-b88f-f2a087b23f8c
* Content: [Convert to other formats - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_get_content_format.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get_content_format.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
You are welcome to create a PR to update our documentation - more information can be found under "Contribute to OneDrive developer documentation" at our repo: https://github.com/OneDrive/onedrive-api-docs/
