### ISSUE TITLE
Resume download is not working "one drive for business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#133]
Resume downloads not working properly 

GET "https://mdm05-my.sharepoint.com/_api/v2.0/me/drive/items/01MFUQXWKHDPWRP2HFOFCINJ3IRAJ2LG2V/content"

Range: bytes = 3-4

response code is not 206, but 200

![untitled4](https://cloud.githubusercontent.com/assets/11455759/8078870/4dd7184e-0f7e-11e5-9440-7a63730b9ad3.png)

**Comment by ificator** [comment]
Out of curiosity, did the chunked response contain the entire file or just the requested bytes?

**Comment by ankit-ankuagrawal** [comment]
it contains entire file

**Comment by ankit-ankuagrawal** [comment]
@rgregg still getting same 200

**Comment by rgregg** [comment]
When using the Range: header on a @content.downloadUrl link, I'm getting an HTTP 200 but instead of getting the whole file, I now get an HTML page that indicates "sorry, something went wrong"

**Comment by ificator** [comment]
I just tried reproing this and didn't have any luck?

**Request** 
> GET *snip* HTTP/1.1
> Host: *snip*
> Range: bytes=0-4

**Response** 
> HTTP/1.1 206 Partial Content
> Cache-Control: private
> Content-Length: 5
> Content-Type: text/plain
> Content-Range: bytes 0-4/23
> Accept-Ranges: bytes
> ETag: "{02D7B866-FD60-4807-B4D3-B2DFD1379D8F},1"
> Server: Microsoft-IIS/8.5
> X-SharePointHealthScore: 0
> X-Download-Options: noopen
> Content-Disposition: attachment;filename="testfile2.txt"
> X-AspNet-Version: 4.0.30319
> SPRequestGuid: bdd07c9d-b04a-0000-1a9b-8cb5f0aae6c3
> request-id: bdd07c9d-b04a-0000-1a9b-8cb5f0aae6c3
> Strict-Transport-Security: max-age=31536000
> X-FRAME-OPTIONS: SAMEORIGIN
> X-Powered-By: ASP.NET
> MicrosoftSharePointTeamServices: 16.0.0.5312
> X-Content-Type-Options: nosniff
> X-MS-InvokeApp: 1; RequireReadOnly
> P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
> Date: Mon, 16 May 2016 18:40:56 GMT
> 
> This
