### ISSUE TITLE
view.changes doesn`t reflect proper result when rename or move a file

### ISSUE THREAD

**Issue by shrimpy** [OneDrive/onedrive-api-docs#134]
when rename a file 
````
e.g "oldfile.txt" to "newfile.txt"
````

view.change result will only see "newfile.txt", doesn`t indicate "oldfile.txt" need to be deleted

same issue when move a file to a different location.

**Comment by rgregg** [comment]
This is by design. You can track that the item was renamed / moved because the id for the item will be the same. You should update your local instance of the object (looked up by ID) to match the new metadata you receive from view.changes.
