### ISSUE TITLE
intermittent 401 response with generalException

### ISSUE THREAD

**Issue by RhysInUS** [OneDrive/onedrive-api-docs#1340]
Hi, I was trying to get do a GET with OneDrive items, I was using the same appID and secret to get the token. However sometime I got 401 and the message was not clear to me why it failed. I am not sure how to reproduce this error. It only happened for 30 minutes then I was able to do the GET again. I have attached some of the failed request id and timestamp below, would you mind checking why it was a 401?

#### Category
- [ ] Question
- [ ] Documentation issue
- [x ] Bug

#### Expected or Desired Behavior

I should be able to get the OneDrive item

#### Observed Behavior
```
{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "date": "2020-07-30T11:39:48",
            "request-id": "106f43d1-56f9-4b90-ac48-24c698106dd7"
        }
    }
}
```

```
{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "date": "2020-07-30T11:59:55",
            "request-id": "c3a5383a-8e28-4ace-84a8-d7c9794f4a41"
        }
    }
}
```
Can I have more info on why those request failed? 

#### Steps to Reproduce

It happens randomly, I am not able to reproduce the bug.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Thanks for your feedback. Could you clarify whether this is still reproducing? It looks like the error was due to a potentially temporary issue.

**Comment by RhysInUS** [comment]
No, this issue did not occur anymore. Are you saying it is a transient
issue on Microsoft side?
