### ISSUE TITLE
one drive connection via rclone : Token date has expired but i am still able to connect without issues.

### ISSUE THREAD

**Issue by anandkulkarnisg** [OneDrive/onedrive-api-docs#1341]
Issue:

Currently configured mounting of one drive service via rclone daemon. Initial configuration generates an authentication token in the below form which rclone will use every time to login or mount drive without credentials. My credentials were supposed to expire on 2020-07-26 which has already passed. I am easily able to connect even now without need to refresh the access token in rclone.conf.

**Token details from rclone.conf look like below.**

Note that critical information of security token is removed below with XXXXXX.

[onedrive]
type = onedrive
token = {"access_token":XXXXXXXXXXXXXXXXXXXXXXXXXXX"expiry":"2020-07-26T21:06:39.464833312+08:00"}
drive_id = XXXXXXXXXXX
drive_type = personal

**Comment by chackman** [comment]
Could you please clarify how the rclone application requested the token and where the expiry value came from?
For example did the rclone application request a token from Microsoft Identity / AAD?

**Comment by anandkulkarnisg** [comment]
https://rclone.org/onedrive/ this link should give you the idea.

**Comment by chackman** [comment]
Thanks. 
Could you ensure that the expiry value of the access token matches the expiry value listed in the config file?  You can use the [jwt.ms](https://jwt.ms) tool, referenced in AAD documentation here: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens, to inspect the access token and its claims (like `exp` - expiration time).

If needed, please provide the relevant claims of the decoded access token (without the signature).

**Comment by anandkulkarnisg** [comment]
I currently have a token which as per config should expire on 1st August 2020. I tried the jwt.ms tool you mentioned but it is not able to decode the access token. When i paste it nothing comes up in the decoded token and claims sections below. This means ( guessing here ) that token is not valid/parsed by the authentication system. Again due to security reasons and privacy i cant paste my access token here. Apologies. I am not sure what to do further here but i can send you some screenshots in case you require and want to take a look further. I know we all are busy but if you are keen you can do a google hangout and i cant help you take further look.

Also you can create a rclone mount on some system for a specific test one drive mount and verify this yourself. should be very easy to simulate.

**Comment by chackman** [comment]
Thanks. It appears that the client application may be using Microsoft Graph API's to access your drive.
Could you look at the logs to see whether the client application records any of these response headers from the API request:
> - Date
> - request-id
> - SPRequestGuid
Could you please provide those (please make sure Date is in UTC or has a clear date/time offset)?

**Comment by anandkulkarnisg** [comment]
Its fair to say that at this point i am stuck ending up nowhere. :) All i see from rclone daemon is as below.

[anand@ldnpsr2937 ~]$ps -ef|grep rclone
root        1623       1  0 11:13 ?        00:00:10 rclone --vfs-cache-mode writes mount --allow-other onedrive: /run/media/anand/Windows/os-common/repo/ExpanDrive/onedrive/
root        1624       1  0 11:13 ?        00:00:00 tee -a /var/log/rclone/rclone.live.log
anand      31385   30558  0 21:00 pts/0    00:00:00 grep --color=auto rclone
[anand@ldnpsr2937 ~]$tail -f /var/log/rclone/rclone.live.log 
Started the rclone service at the timestamp = 08-29-2020.08.58.00.AM
2020/08/29 17:06:28 ERROR : os-common/fedora/users/dhruv/Documents/dhruv-music-competition/: Dir.Remove not empty
2020/08/29 17:06:28 ERROR : os-common/fedora/users/dhruv/Documents/dhruv-music-competition/jpeg/: Dir.Remove not empty
2020/08/29 17:06:33 ERROR : os-common/fedora/users/dhruv/Documents/dhruv-music-competition/pdfs/: Dir.Remove not empty
Starting the rclone service at the timestamp = 08-30-2020.08.24.09.AM
Started the rclone service at the timestamp = 08-30-2020.08.24.10.AM
Starting the rclone service at the timestamp = 08-30-2020.08.51.38.AM
Started the rclone service at the timestamp = 08-30-2020.08.51.39.AM
Starting the rclone service at the timestamp = 08-30-2020.11.13.16.AM
Started the rclone service at the timestamp = 08-30-2020.11.13.17.AM
