### ISSUE TITLE
How to set zoom level 

### ISSUE THREAD

**Issue by sven5** [OneDrive/onedrive-api-docs#1344]
Please explain how to set zoom in general and espacially how to set level to "full-page width" programmatically.

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abaca550-f44d-455b-ef18-a284dd222dbc
* Version Independent ID: de0dfe46-b10b-5b53-59a1-37967fe2b1ab
* Content: [Get short-lived embeddable link for preview purposes - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_preview.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_preview.md)
* Product: **onedrive**
* GitHub Login: @kevinlam
* Microsoft Alias: **kevinlam**

**Comment by chackman** [comment]
It's a number, percentage zoom, so unfortunately there is no way to set to full-page width.  This sounds like a useful feature enhancement.  I'll add a tag if you wanted to suggest that via our User Voice, which is where we recommend feedback about feature enhancements.

**Comment by chackman** [comment]
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.
> If you have a question about Azure Active Directory, outside of issues with the documentation provided in the OneDrive Developer Center, please ask it here: https://stackoverflow.com/questions/tagged/azure-active-directory
