### ISSUE TITLE
Update the app registration process, the one listed is deprecated

### ISSUE THREAD

**Issue by westleyMS** [OneDrive/onedrive-api-docs#1345]
The article states to use the Microsoft Application Registration Portal. This is deprecated, and they need to register the app in the Azure application registry. This needs to spell out the app requirements too-

1. must grant tokens (implicit flow)
2. must be multi-tenant enabled (due to the use of the common endpoint in the OneDrive.js file).

The reference to the Microsoft Application Registration Portal is found in some other places in the OneDrive.js picker documentation, and these should all be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01cfabca-01d3-decc-8194-1b21ed536a42
* Version Independent ID: b98f73e7-5aa8-92a0-0ca4-a598534c6425
* Content: [File Picker SDK for JavaScript - OneDrive - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online#setting-up)
* Content Source: [docs/controls/file-pickers/js-v72/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
This item is on our documentation backlog. See also #1297. If you wish, you may also contribute a PR to address this issue.
