### ISSUE TITLE
Outdated information on app registration docpage

### ISSUE THREAD

**Issue by KovacsGG** [OneDrive/onedrive-api-docs#1348]
App registration has been moved from the Application Registration Portal to Azure App resistrations for all users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02010cc-2715-86ca-b3fe-e4f92e934fdb
* Version Independent ID: 27b3e16e-f80f-32f4-0e4f-69cfcd1cf769
* Content: [Create an app with Microsoft Graph - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/app-registration.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/app-registration.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
This item is on our documentation backlog. See also #1297. If you wish, you may also contribute a PR to address this issue.
