### ISSUE TITLE
Get Metadata by ID ( GET /drive/items/{item-id} ) does not return correct parentReference

### ISSUE THREAD

**Issue by bscharm** [OneDrive/onedrive-api-docs#135]
When I do the call by path it works, but by ID the parentReference is incorrect (seems to always be root or '/')

**Comment by ificator** [comment]
Hey @bscharm, do you repro this on the Consumer or Business endpoint?
I tried against https://api.onedrive.com and couldn't repro:

    GET /v1.0/drive/items/MYID!336443 HTTP/1.1

    {
      ...
      "parentReference": {
        "driveId": "myid",
        "id": "MYID!320846",
        "path": "/drive/root:/Test"
      },
      ...
    }

**Comment by bscharm** [comment]
Apologies for not being specific.. this is for a OneDrive for Business endpoint, so the base URL is `https://{mytenant}-my.sharepoint.com/_api/v2.0/me`.

**Comment by ificator** [comment]
Thanks for confirming!

**Comment by rgregg** [comment]
Hi @bscharm I wasn't able to reproduce this exact error, although I did notice another error. Can you tell me if this is still a problem and provide more details (perhaps examples of what's wrong)?

**Comment by rgregg** [comment]
Closing out old issues. If this is still a problem, please reopen and provide more details.
