### ISSUE TITLE
[OneDriveSDK] Failed due to unknown error

### ISSUE THREAD

**Issue by ishansaxena1** [OneDrive/onedrive-api-docs#1350]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I'm trying to run a sample OneDrive picker. But it didn't seems to work. 

#### Observed Behavior

A popup opens asking to login. As soon as I enter my email address and hit the next button. The popup closes and there is this error in the console.

![image](https://user-images.githubusercontent.com/53508123/90594491-31b85080-e208-11ea-8f22-492e529b3c99.png)

#### Steps to Reproduce

Here is my `index.html` and `odcallback.html`

`index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <script
      type="text/javascript"
      src="https://js.live.net/v7.2/OneDrive.debug.js"
    ></script>
  </head>
  <body>
    <button onclick="createPicker()">Open OneDrive</button>
    <script type="text/javascript">
      function createPicker() {
        var odOptions = {
          clientId: "CLIENT_ID_HERE",
          action: "download",
          multiSelect: true,
          advanced: {
            redirectUri: "http://localhost:8000/odcallback.html",
          },
          success: function (files) {
            console.log(files);
          },
          cancel: function () {},
          error: function (error) {
            console.error(error);
          },
        };
        OneDrive.open(odOptions);
      }
    </script>
  </body>
</html>
```

`odcallback.html`
```html
<html>
  <script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.debug.js"></script>
</html>
```

Here is my app registration 

![image](https://user-images.githubusercontent.com/53508123/90594398-ee5de200-e207-11ea-8932-ec40c9280b5a.png)

Did I missed something in configuration ?

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ishansaxena1** [comment]
![image](https://user-images.githubusercontent.com/53508123/90607143-74852300-e21e-11ea-895f-2dde1fcad9bc.png)

Enabling those two options worked for me. But was not able to find it in documentations though.
I was using this documentation for Setting up https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online.

**Comment by ShixAJ** [comment]
I am having the same problem, however checking the Access tokens and ID tokens didn't work. Are there any updates on how to use OneDrive filepicker sdk in javascript and setup our application on azure?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
