### ISSUE TITLE
[ODB] fail to request status for upload large file session with hash tag

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1352]
Hi forks,

I am going to create a session for large file but encounted some problems.

### case 1:
file name : '120@MB'
create a real tmp file on cloud '~tmp73_120@MB'
upload url :  https://blahblah&path='~tmp73_120%40MB' blahblah

It's OK.

### case 2:
file name : '120#MB'
create a real tmp file on cloud '~tmpE4_120#MB'
upload url :  https://blahblah&path='~tmpE4_120%23MB' blahblah
But for this I failed to get status with error
```
http code (404)
error message (Item not found)
error code (itemNotFound)
```

Thanks for help!

**Comment by ificator** [comment]
Can you tell me what the version is after the `/_api`? The URL is correctly encoded which means it's an issue with the endpoint that's handling the request.

**Comment by joewutaiwan** [comment]
Hi @ificator 

Thanks for reply.

We use endpoint  _api/v2.0/  for uploading.

**Comment by ificator** [comment]
It looks like there's an issue specific to the `GET` path for upload sessions.

**Comment by joewutaiwan** [comment]
@ificator 

Thanks for help, and it is possible to have a issue fixed date?

**Comment by ificator** [comment]
If things progress normally, I would imagine the fix will fully deployed by the week of September 14th.

**Comment by ificator** [comment]
This should be deployed now - please let us know if you're still seeing the issue.
