### ISSUE TITLE
Invalid quota returned

### ISSUE THREAD

**Issue by jgalmeida** [OneDrive/onedrive-api-docs#1353]
Hello,

I'm having a problem that was marked as solved in another issue regarding invalid quotas.

reference: https://github.com/OneDrive/onedrive-api-docs/issues/1245

GET `/https://graph.microsoft.com/v1.0/me/drives`

```
"quota": {
    "deleted": 0,
    "remaining": 0,
    "total": 0,
    "used": 0
}
```

```
{
    "cache-control": "private",
    "client-request-id": "693b258a-c980-5224-94c6-91e09dc58ffc",
    "content-length": "583",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "f903c832-43e8-4bef-8f43-26140337859f"
}
```

**Comment by chackman** [comment]
Could you please provide a date/time (in UTC) for the request that is not working as expected?

**Comment by jgalmeida** [comment]
@chackman don't know the request time for the example above but here's a new one.

2020-09-07
10:00:00 am UTC + 1

```
{
    "cache-control": "private",
    "client-request-id": "6742cd99-e096-ae7d-fdad-a61ef10f0b41",
    "content-length": "595",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "271d2966-83a7-48de-a3ef-4c6a9c1ea304"
}
```

**Comment by chackman** [comment]
Thanks, I have followed up with a partner team regarding this issue.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
