### ISSUE TITLE
Graph API does not give updated lastModifiedTime for few events 

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1355]
#### Category
- [ ] Question
- [ ] Documentation issue
- [ ] **Bug** 
When i create or update a document in Onedrive, i do get an updated lastModifiedTime every time but when i share/unshare file and call API, lastModifiedTime does not change and remain same as last one
Steps to Reproduce
Call https://graph.microsoft.com/v1.0/users/{user_id}drive/root/delta and move until delta url found
1- Upload a file
call above API with delta link and notice lastModifiedTime
2- share same file  after few seconds or minutes
call above API with delta link and notice lastModifiedTime (lastModifiedTime does not change and remain same as last event)
[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Thanks for your feedback. While the `lastModifiedTime` property will change when the item's content or metadata changes, it unfortunately doesn't currently change when permissions change on the item.

In our scan guidance we do mention how you can use delta to detect items with changes in permissions:
   https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#scanning-permissions-hierarchies
Will that address your scenario?

**Comment by shayan-brcm** [comment]
Thanks @chackman it would be good if `lastModifiedTime` property gets updated after permission change also. 
We actually need this field to be updated because after 429 we want to start processing events from the point we had stopped so this field can be useful in filtering out events but as its not updating so we are facing issues.
Is there any good way to resume processing from the point where we had stopped due to throttling? because we have same delta link and it may already have some events that are already processed before throttling

Thanks

**Comment by chackman** [comment]
Regarding this:
> Is there any good way to resume processing from the point where we had stopped due to throttling? because we have same delta link and it may already have some events that are already processed before throttling
At what point did the application stop processing? For example, did it stop while enumerating through the delta, or after completing enumeration?
If, for example, the application had partially enumerated through the delta, then was paused for throttling, try resuming where it was paused.

**Comment by chackman** [comment]
If your application has completed delta enumeration, and stopped while doing other things (like getting metadata on individual drive items), restart with the item that failed.
And then, the next time that it enumerates delta, it can use the new delta link.

**Comment by shayan-brcm** [comment]
Thanks @chackman for your answer.
Yes we do call delta link and get events and during enumeration we do call api to get metadata and we have observed that we get throttled mostly in meta api call so how can we resume exactly from that item? As all i have is a same delta link which again may have other items which we already processed?
In order to explain you in better way here is an example
we have delta link x, we made a call and got 10 events
we started enumerating events one by one and make meta api call y
now lets say we have synced 5 events out of 10 and on making item meta call for item 6 we get throttled 
we still have same delta link x and we processed till item 5, how can we start processing item 6 and skip from item 1-5?
I hope you will get i try to explain
Thanks

**Comment by chackman** [comment]
Thanks. Your application should continue processing where it left off with the delta link. And then continue through each page, as needed, until it has completed enumerating the delta.

**Comment by shayan-brcm** [comment]
Thanks for your response.
with your answer, i am assuming you are saying to reprocess the in hand delta link again? We dont want this as it will cause duplicate processing of same file because we may already processed few events from that link before 429 on item meta API

**Comment by chackman** [comment]
Your application does need to continue processing where it left off.
So if the 429 was on the third item in the delta enumeration, resume with that item - the application does not need to restart at the beginning of the delta, though.
It is important to continue where the application left off because items may have changed after processing it the first time.

**Comment by shayan-brcm** [comment]
@chackman when we face 429, we stop processing and then task get requeue which executes again after few time to retry
so for example if delta url is x and it has 5 items, we process 3 and at time of processing 4 we got 429 so we dont save delta url because we did not finished all the item from a given delta url so next time when we start we have to start from item 1 again of that page. How could we skip 3 items and start from 4th on that page?

**Comment by shayan-brcm** [comment]
@chackman 
is there any way to get the activity time of share or unshare activity?

**Comment by chackman** [comment]
Unfortunately, the Graph API does not provide that level of detail - exactly what activity changed, or time of last change of a particular activity type.

**Comment by shayan-brcm** [comment]
@chackman Thanks for reply. Is it something you will be fixing any time soon or it will remain the way it is?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
