### ISSUE TITLE
Best way to handle 410 (resyncRequired) error

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1356]
#### Category
- [ ] **Question**
- [ ] Documentation issue
- [ ] Bug

How to avoid 410 error? and whats the best way to handle it? is there any possibility to start getting event from the point we have got this error?

`"error": {
    "code": "resyncRequired",
    "message": "Resync required. Replace any local items with the server's version (including deletes) if you're sure that the service was up to date with your local changes when you last sync'd. Upload any local changes that the server doesn't know about.",
    "innerError": {
      "date": "2020-09-02T13:13:42",
      "request-id": "4066dbff-4e0c-48a0-bf94-31934a1aaea4"
    }` 

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Unfortunately there are occasions where a 410 error response is possible (and you cannot currently avoid it).
Within the "response" section there is a short description of how to handle it - unfortunately your application does need to do a full enumeration.
   https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#response-2

However, if there are certain drives that consistently get 410's (as in multiple times a day), please let us know - provide request ID + timestamp for those for us to get started.

**Comment by sailor777** [comment]
Hello, we have not been synchronizing attachments from the cloud for 2 months and now we got an error on request changes:
u'message':
	u"Resync required. Replace any local items with the server's version (including deletes)
	  if you're sure that the service was up to date with your local changes when you last sync'd.
	  Upload any local changes that the server doesn't know about.",
u'code': u'resyncRequired'

Is this a good approach to call without a token to keep data consistent after that?
https://graph.microsoft.com/v1.0/drives/me/root/delta

**Comment by KamilMichalik** [comment]
Hi there,

I would like to bump this ticket as I am experiencing the same error and am unsure how to handle it. Any guidance or solutions would be greatly appreciated.

Thank you!

**Comment by kylienhu-ssg** [comment]
bumping this ticket as I'm experiencing the same error
