### ISSUE TITLE
How to search across subsites?

### ISSUE THREAD

**Issue by tchernobog** [OneDrive/onedrive-api-docs#1357]
In the page description at https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_search?view=odsp-graph-online, it is unclear whether this search will also list subsites the user has access to.

If not, there does not seem to be a good way to search for them without traversing the graph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc17fd29-98dc-b6c6-071f-e717b221d4ad
* Version Independent ID: a6b19289-2ef4-e668-2223-3cc4426326ac
* Content: [Find SharePoint sites by keyword - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_search?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/site_search.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/site_search.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Thanks for your feedback. Are you attempting to enumerate through sites, or search for sites that match some search query?
