### ISSUE TITLE
Editing Manifest directly

### ISSUE THREAD

**Issue by jfluet** [OneDrive/onedrive-api-docs#1358]
Should this doc be updated since you can edit the manifest directly in the Azure portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae4e030-350f-9362-de6e-ffce340b6ab8
* Version Independent ID: 19d0784a-b9cb-e2a3-23eb-8d8c1569411e
* Content: [How to: Register a file handler add-in manually - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/register-manually?view=odsp-graph-online)
* Content Source: [docs/file-handlers/register-manually.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/register-manually.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
We'll add this item to our documentation backlog. If you wish, you may also contribute a PR to address this issue.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
