### ISSUE TITLE
Create Delta Token using datetime

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1359]
#### Category
- [ ] **Question**
- [ ] Documentation issue
- [ ] Bug

Is there any way to create a delta token using some datetime? because token=latest would create token using current time and we may need to have one that could be created using some old time
Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Unfortunately the `delta` API does not currently support creating a token based on a time. It's something we are considering, though.

**Comment by shayan-brcm** [comment]
Thanks @chackman it will be great to have this support. Any ETA?

**Comment by chackman** [comment]
We're discussing this internally. Could you please provide some more information about how your application would use this functionality?

**Comment by shayan-brcm** [comment]
on 410 error, our application would be interested in creating a new delta token based on time when we last synced so that we dont need to do full enumeration. Also it will be helpful when we want to know what changes happened after x time without having a chain of API calls to reach at that point

**Comment by shayan-brcm** [comment]
@JeremyKelley any update on this?

**Comment by shayan-brcm** [comment]
@chackman is there any update on this?

**Comment by jayde3m** [comment]
any update on this? my reason is the same @chackman 
Instead of rebuilding everyone, we could just get delta changes from a particular point in time

**Comment by shayan-brcm** [comment]
@chackman i think he mean to full resync. on 410 we have to do full resync which is a heavy operation. so instead of starting from beginning we could have some way to continue from a point where we have got 410

**Comment by shayan-brcm** [comment]
@chackman is there any update on it?

**Comment by chackman** [comment]
Assuming your application would only be attempting a partial resync (by specifying a date/time) we still recommend a full resync for the scenario, because a partial resync may miss changes.

**Comment by shayan-brcm** [comment]
@chackman Thanks for response. Dont you think full resync require more API calls to go through all the items?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
