### ISSUE TITLE
Pagination for children listing not clearly described in documentation

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#136]
Using the API for listing children (https://dev.onedrive.com/items/list.htm), if more than the limit per page is requested (default 200), a @odata.nextLink property is in the response, to get the next page.

However, the pagination feature isn't listed on the API page, though it is on the search page (https://dev.onedrive.com/items/search.htm).

**Comment by rgregg** [comment]
Thanks for noticing this @Lyrrad. I'll work on getting this improved.

**Comment by rgregg** [comment]
I've just pushed an update 2c9c199 to the documentation that adds information about paging to this topic. Thanks!
