### ISSUE TITLE
OneDrive picker web SDK, svg files have wrong content-type.

### ISSUE THREAD

**Issue by BesoKakulia** [OneDrive/onedrive-api-docs#1361]
I use OneDrive picker web SDK v7.2, when I try to select SVG files they have a content-type `application/octet-stream`  instead of `image/svg+xml` there is a response example in the picker success method
![image](https://user-images.githubusercontent.com/26166174/92471429-fe565980-f1e8-11ea-92e3-e213ee93a246.png)

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
