### ISSUE TITLE
"optional query string parameters" link error

### ISSUE THREAD

**Issue by onLeserKey** [OneDrive/onedrive-api-docs#1362]
The link at the bottom of page does not exist and I can't find the related information.
Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 272714c3-6387-1c6c-c57f-3d477ca648bc
* Version Independent ID: ec2ca64c-5ddf-c6fb-73a8-9d202b7d7049
* Content: [List the contents of a folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_children?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_list_children.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_list_children.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
We'll add this item to our documentation backlog. If you wish, you may also contribute a PR to address this issue.

**Comment by onLeserKey** [comment]
Sure, how do I go about it?

**Comment by chackman** [comment]
Click on the "Edit" button on the upper-left of the doc page, which should take you to the source code (markdown format).
Then you should be able to Edit that in GitHub's editor and submit a PR which we can help with reviewing.
Thanks!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
