### ISSUE TITLE
not able to use webUrl in iframe.

### ISSUE THREAD

**Issue by anilabsinc-harpreet** [OneDrive/onedrive-api-docs#1364]
I am using this api 'https://graph.microsoft.com/v1.0/users/${id}/drive' to get user's onedrive. I am getting 'webUrl' in response. But not able to use this 'webUrl' in iframe. my main concern is that, this 'webUrl' is not contained any unique id to authenticate the user.
if i am using the wrong api then let me know the exact api to get user onedrive root 'webUrl' to display in iframe.
If am using this api 'https://graph.microsoft.com/v1.0/me/drive/items/{id}/createLink' with {  "type": "embed" } then not getting the expected result and getting:
400 - Bad Request

{
  "error": {
    "code": "invalidRequest",
    "message": "Link type must be either 'edit' or 'view'.",
    "innerError": {
      "date": "2020-09-14T12:01:56",
      "request-id": "85f1702f-a119-40e9-888c-.........",
      "client-request-id": "85f1702f-a119-40e9-888c............."
    }
  }
}

**Comment by chackman** [comment]
Thanks for your feedback. Could you please clarify whether this is an issue with OneDrive Personal or OneDrive for Business?

Unfortunately, the `createLink` API only supports `embed` in OneDrive Personal - so the API's behavior would be expected if your request is for OneDrive for Business.
    https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http
