### ISSUE TITLE
The simple upload API of OneDrive for Business does not respect the content length and saves a partial file

### ISSUE THREAD

**Issue by gilbertchen** [OneDrive/onedrive-api-docs#1366]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

When an upload is aborted and the number of received bytes is less than what is specified by the content length in the http header, OneDrive for Business servers should not keep the partial file.

#### Observed Behavior

Instead, with the [simple upload API](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content), OneDrive for Business keeps the partial file even if the file size is smaller than the specified content length.  As a result, the file becomes corrupt.

This doesn't not happen with OneDrive for Personal.  Nor does it when the [upload session API](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession) is used.

#### Steps to Reproduce

Try to upload a file with curl or a test program, but before the upload is complete, press ctrl-c to terminate the upload.  A partial file will appear on OneDrive smaller than the expected size.
 
I can provide a small test program written in Go to reproduce the bug.

**Comment by chackman** [comment]
Thanks for your feedback. Could you please provide a request-id and timestamp? I'll tag so our bot will follow-up with more information.

**Comment by gilbertchen** [comment]
You can easily reproduce the issue with curl:

```
curl -v -X PUT -T <file> -H "Authorization: Bearer <access_token>" https://graph.microsoft.com/v1.0/me/drive/root:/file:/content
```
`<file>` can be any file less than 4MB.  You'll need to replace `<access_token>` with your own access token.

While the curl command is is running, press ctrl-c to terminate it before it finishes.  A file named `file` will appear on your OneDrive with a size smaller than the local file to be uploaded.

**Comment by chackman** [comment]
Thanks for your feedback, we're following up with a partner team about this issue.

**Comment by ificator** [comment]
We tracked this down to an issue in Microsoft Graph that should now be resolved - can you try your repro again and confirm things are working as expected?
