### ISSUE TITLE
What is yhe go with keeping me locked out of my account 

### ISSUE THREAD

**Issue by Dogemain** [OneDrive/onedrive-api-docs#1367]

**Comment by Dogemain** [comment]
Email me at ableyards@gmail.com I own both accounts ableyards@hotmail.com and Gmail so fucking let me back in my account I have an issue to prove and I need my email to do it

**Comment by chackman** [comment]
(Deleting comment with personal email address and expletives. Closing this issue.)

**Comment by chackman** [comment]
This might help you reset or recover: https://support.microsoft.com/en-us/help/17875/microsoft-account-reset-or-recover-password
