### ISSUE TITLE
'@microsoft/file-browser' package not providing share/move/search functionality.

### ISSUE THREAD

**Issue by anilabsinc-harpreet** [OneDrive/onedrive-api-docs#1368]
'@microsoft/file-browser' package is not updated from last two year. I want the share, move and search functionality there. Do i can customize this package to extend the package functionality? Can you help me on this?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
