### ISSUE TITLE
zoom level not working for 100%

### ISSUE THREAD

**Issue by sven5** [OneDrive/onedrive-api-docs#1369]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

When setting the zoom level with json parameter "zoom" and value "1" it should return a file preview with 100% zoom.

#### Observed Behavior

The zoom level does not apply.

#### Steps to Reproduce

example URL:
**POST https://graph.microsoft.com/v1.0/sites/xxxxxx-c030-475e-a498-23e6dbdf0471/drive/items/02BM7R3FHBUXUUVXYPURB3D47GORZGY3PJ/microsoft.graph.preview**

json parameters:
`{ "zoom": 1 }`

response:

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.itemPreviewInfo",
    "getUrl": "https://the.path.to.the.preview",
    "postParameters": null,
    "postUrl": null
}
```

But document's zoom level is not set to 100% - see screenshot below.

![image](https://user-images.githubusercontent.com/8734624/93759391-60ac5280-fc0a-11ea-9b8f-ac81da043347.png)

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Thanks for your feedback. Could you please clarify whether the viewer that displays is the Office browser application (Word/PowerPoint/etc.), or if it is a different previewer?

**Comment by sven5** [comment]
@chackman 

Sorry for being late.  Yes it's the Office browser application viewer.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
