### ISSUE TITLE
FileSystemInfo documentation error

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#137]
https://dev.onedrive.com/resources/item.htm indicates that FileSystemInfo is read-only.
https://dev.onedrive.com/facets/filesysteminfo_facet.htm indicates that it is read/write.

I assume the first page is incorrect.

**Comment by daspek** [comment]
You're right, the first page is wrong. FileSystemInfo is writable. We'll get the docs fixed. Thanks for bringing this to our attention!

**Comment by rgregg** [comment]
This is now fixed. Thanks for reporting the bug!

**Comment by Lyrrad** [comment]
There's a small inconsistency now on that page.  FileSystemInfo says it's "Read-write", while all other writable properties simply say "Writable".  Also there's no period after Writable for the parentReference property.
