### ISSUE TITLE
Documentation of "Request Files" or "Guest Link" features API

### ISSUE THREAD

**Issue by LMUoD** [OneDrive/onedrive-api-docs#1370]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

Finding the documentation of the API corresponding to the "Request Files" or "Guest Link" features available in OneDrive.

#### Observed Behavior

Can't find the documentation for the API corresponding to the "Request Files" or "Guest Link" features available in OneDrive.
These features open a webpage in which the user can upload files without being logged in and we would need to do the same from an app.
The webpage the links from these features open is using an API which look similar but doesn't seem to be documented.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Thanks for your feedback, this is on our backlog to address.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
