### ISSUE TITLE
Broken link in Getting started > App registration

### ISSUE THREAD

**Issue by chinmaykunkikar** [OneDrive/onedrive-api-docs#1372]
The link in the [Register your app with Microsoft](https://apps.dev.microsoft.com/?referrer=https%3A%2F%2Fdev.onedrive.com) section might be broken. The page redirects users to an Azure portal page.

> You can no longer manage converged applications here. [Go to the Azure portal.](https://apps.dev.microsoft.com/?referrer=https%3A%2F%2Fdev.onedrive.com#)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02010cc-2715-86ca-b3fe-e4f92e934fdb
* Version Independent ID: 27b3e16e-f80f-32f4-0e4f-69cfcd1cf769
* Content: [Create an app with Microsoft Graph - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/app-registration.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/app-registration.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
This item is on our documentation backlog. See also #1297 . If you wish, you may also contribute a PR to address this issue.
