### ISSUE TITLE
Proper way to get item metadata by path while avoiding the url length limit

### ISSUE THREAD

**Issue by nozhT** [OneDrive/onedrive-api-docs#1373]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I use the `https://${SHAREPOINT_SITE_ID}/_api/v2.0/drives/${DRIVE_ID}/root:@path:?path='${URL_ENCODED_PATH}' ` endpoint to get an item by its path.

When a file name contains unicode characters, it's quite easy for the url to exceed the 2048-character length limit.
For example, the character "鵝" is usually encoded to "%E9%B5%9D", and a filename consisting of 300 "鵝" encodes to an url longer than 2700 characters, so when I try to get the item's metadata the API returns a 401 error with an empty response body.

I did find a way to shorten the url by encoding "鵝" as "%u9D5D", however there's 3 problems with it:
1. I _think_ this is UTF-16?
2. is this encoding supported for all onedrive apis?
3. the character U+1F4A9 "💩" is "%uD83D%uDCA9", so a filename with 300 "💩"s would be more than 300 * 6 * 2 = 3600 characters and still exceed the 2048-character limit

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Unfortunately there is a URL length limit, and our recommendation would be to use ID's to reference drive items, rather than their paths.
Could you explain your scenario more?

**Comment by nozhT** [comment]
We obtain a list of Sharepoint items that we care about with the (old) [Sharepoint Rest APIs](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-rest-reference/jj860569(v=office.15)?redirectedfrom=MSDN), and then use the Sharepoint items' paths (FileRef) to get the corresponding drive items for file hashes and other useful information.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
