### ISSUE TITLE
Detecting file rename kind of scenario using delta query

### ISSUE THREAD

**Issue by ManojNisal** [OneDrive/onedrive-api-docs#1374]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

What is the right way to detect whether contents of a file have been modified or file has just been renamed? In the delta query response, both are returned with etag and ctag modified.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Could you please clarify whether there were other changes to the file content, or if this was purely a rename scenario where only the metadata about the `driveItem` had changed?
If so could you please provide request-id's and timestamps for your request?  (I'll tag so our bot fills in some more information about request ID headers and timestamps.)

**Comment by ManojNisal** [comment]
Thanks for the response, Chackman.
I'm not able to reproduce the issue I saw earlier. What I see now is eTag is updated but cTag is not, if a file is just renamed. 
So, is there a way by which metadata changes can be detected just through delta API response, without referring to earlier eTag/cTag values?

Also, if a file is just opened in browser, it is marked as changed in delta query even if there has been no change in the file. eTag, cTag, hash all remain the same but the item is still flagged as changed.

Here are response headers from a request showing this behavior.:
"client-request-id": "d8160034-539d-424f-1485-bc5a708d6642",
"request-id": "98d11990-8990-4e47-b087-c91302e24787"

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
