### ISSUE TITLE
Unable to select folders in a Shared Library from the OneDrive JS Picker

### ISSUE THREAD

**Issue by splinter** [OneDrive/onedrive-api-docs#1376]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
A user should be able to select either a folder or file in a Shared library (Private  access) and shared link should be generated.

#### Observed Behavior
A user is only able to select  files in a Shared library. If a folder is selected the OneDrive JS Picker throws the following error:

![image](https://user-images.githubusercontent.com/53738/94770193-9c48d880-03d1-11eb-8df9-7873003fef7a.png)

Please find the Date, request-id and SPRequestGuid in the screenshot.

What is the permission or feature referenced by this error?

#### Steps to Reproduce

1. Create a Shared Library (Private)
2. Create a folder and file
3. Access the Shared Library from the OneDrive picker
4. Select the folder

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by splinter** [comment]
Nudge :)

**Comment by splinter** [comment]
Nudge

**Comment by splinter** [comment]
Bump

**Comment by chrisecorcoran** [comment]
@chackman would you be able to help us get this sorted out? I work with @splinter (am on the management side) and this has been escalated by our prospect. Tks.

**Comment by zsabbasi** [comment]
I need this quite desperately, is this opensource so that I can fix the folder selection?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
