### ISSUE TITLE
Permissions does not be updated after group renamed

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1377]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Issue Description

Drive item's permissions should be updated after group was renamed.

For example, I have a file with 'bleak_tea@mydomain.com' permission

```
"grantedTo": {
    "user": {
        "email": "bleak_tea@synologydst.onmicrosoft.com",
        "id": "f2dd39b6-8d07-4745-94cb-50d62bc7beea",
        "displayName": "bleak_tea成員"
    }
}
```

Then I rename 'bleak_tea@mydomain.com' to 'green_tea@mydomain.com'. but the permission is still the same.

And add permission API is only valid with email
https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http

Thank you.

**Comment by chackman** [comment]
This is expected behavior - permissions stay with the group or user after an email alias change. Use the current email to invite.
