### ISSUE TITLE
Update fileSystemInfo in driveitem occupied twice storage

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1378]
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hi folks,

### OneDrive for Business

After uploaded a file to **OneDrive for Business** and then only update **fileSystemInfo** meta _**occupied twice storage.**_

And this file has **_two versions in history._**

![image](https://user-images.githubusercontent.com/12619781/95410729-505cdd00-0957-11eb-9306-fb5cad2be308.png)
![image](https://user-images.githubusercontent.com/12619781/95410754-61a5e980-0957-11eb-9e62-f2dcd803da80.png)

### OneDrive for Personal

But in **OneDrive for Personal** does not have this issue.

![image](https://user-images.githubusercontent.com/12619781/95410820-8ef29780-0957-11eb-8461-e24ca7ec3d6c.png)
![image](https://user-images.githubusercontent.com/12619781/95410857-a92c7580-0957-11eb-9884-ba0eea396c5b.png)

Without any modification for file itself, it seems like ODP have right behavior.

Thank you.

**Comment by chackman** [comment]
Unfortunately this is expected behavior for OneDrive for Business / SharePoint.
