### ISSUE TITLE
Fail to update fileSystemInfo with Create an upload session

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1379]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

Fail to update fileSystemInfo with [Create an upload session](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online)

> No request body is required. However, you can specify an item property in the request body, providing additional data about the file being uploaded.

Request body
```
{
   "item":{
      "fileSystemInfo":{
         "lastModifiedDateTime":"2009-09-09T09:09:09Z"
      }
   }
}
```

### ODB
```
http code: 400 
error message: The request is malformed or incorrect.
```

### ODP
Successfully uploaded, **but fileSystemInfo is not updated.**

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Could you please provide more information?   I'll tag so our bot fills in what would be needed to look at this further.

**Comment by joewutaiwan** [comment]
Hi @chackman,

Thank you for reply, and here is your information.

### Could you please provide the following response headers:
- Date (in UTC, please)
Tue, 20 Oct 2020 02:42:44 GMT
- request-id
0061859f-30ca-b000-e515-be19842756ee
- SPRequestGuid (for requests made to OneDrive for Business)
0061859f-30ca-b000-e515-be19842756ee


### Could you please describe the steps to reproduce the bug in sufficient detail for another person to be able to reproduce it?
Use following create session API in ODB

### Could you please provide sample requests and responses that illustrate the issue that you are encountering?
```
POST /_api/v2.0/drives/<drive id>/items/<parent_id>:/<file_name>:/createUploadSession
{
   "item":{
      "@odata.type":"microsoft.graph.driveItemUploadableProperties",
      "fileSystemInfo":{
         "lastModifiedDateTime":"2020-09-09T09:09:09Z"
      }
   }
}
```

### Could you please describe the behavior you expected to occur when performing the action?

1. I expect this upload session should be created, 
2. After file uploaded, fileSystemInfo should be applied also.

**Comment by joewutaiwan** [comment]
Are there any updates?
Thank alot!

**Comment by chackman** [comment]
Could you please ensure that the content type on your request is `application/json`? It appears that the content type provided in the request was an invalid content type.

**Comment by joewutaiwan** [comment]
Hi @chackman 

Thanks for reply.
I did miss the  `application/json` header in requset, and now it works fine.

Additionally, is it possible to have the same behavoir (update fileSystemInfo in upload request) in [single upload request](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online)?
Because for small files, this will be a efficient option.

Thanks!

**Comment by k-tsoi** [comment]
That scenario is currently not supported, this is good feedback. Please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice to voice this feature.
