### ISSUE TITLE
couldnt discover service for a user when license (subscription) provided "OneDrive for Business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#138]
we have one user "testuser1@mdm05.onmicrosoft.com", and previously it was not subscribe to use onedrive for business, now provided license (subscription) to access onedrive for business.

from web browser was able to login in the account and can access onedrive and other services.

but when trying from the api, in the service discovery api (https://api.office.com/discovery/v2.0/me/services) couldnt receive anything, the call contains zero array
response...
"{
@odata.context: "https://api.office.com/discovery/v2.0/me/$metadata#allServices"
value: [0]
}"   

question is after how much time the changes will reflect in api call, or something wrong happening?

**Comment by rgregg** [comment]
Are you following the [auth request flow](https://dev.onedrive.com/auth/aad_oauth.htm#step-3-discover-the-onedrive-for-business-resource-uri) defined in our documentation **exactly**? In particular, you can get an empty list if you have the wrong resource path on your access_token or make the call to a similar but slightly different URL from what's written in the docs.

**Comment by ankit-ankuagrawal** [comment]
@rgregg im following the process, after some time (2-3 hrs) i got the array, my question was after how much it get reflected in the api once user is subscribed?

**Comment by rgregg** [comment]
We don't have a formal SLA on how long the discovery service takes to be updated. It sounds like it's on the order of a few hours right now, and we'll continue working to improve that time and reduce the delay between a user being provisioned for ODB and when all of the APIs work as expected.
