### ISSUE TITLE
Copy/Move Item api is not throwing exception when i provide invalid parentReference.id with in drive

### ISSUE THREAD

**Issue by ssapa** [OneDrive/onedrive-api-docs#1381]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X ] Bug

Both Move and copy apis are successful when we provide invalid ParentReference.id with in drive. And it is copying the file to same folder as source item. Expected Behaviour : It should throw invalid parentReferece.id error. This functionality is working fine when we provide invalid parentReference.path.

Copy Item : POST https://graph.microsoft.com/v1.0/drives/b!dckkz8p7EkKltFwLt5o0QJ6VxtVc1UlOlv0XvR1bhLAo3oh17BLfTIZmGKhBkrry/root:/home/new-item.jpg:/microsoft.graph.copy 

{'name':'test5.jpg','parentReference':{'driveId':'b!dckkz8p7EkKltFwLt5o0QJ6VxtVc1UlOlv0XvR1bhLAo3oh17BLfTIZmGKhBkrry','id':'fgdftgarsgdreg'}} 

Move Item : PATCH https://graph.microsoft.com/v1.0/drives/b!dckkz8p7EkKltFwLt5o0QJ6VxtVc1UlOlv0XvR1bhLAo3oh17BLfTIZmGKhBkrry/root:/home/new-item.jpg: 

{'name':'test6.jpg','parentReference':{'id':'fgdftgarsgdreg'}}

**Comment by ssapa** [comment]
@chackman Can you please provide some insight on the above issue?

**Comment by chackman** [comment]
This might be a bug, could you please provide more information? I'll tag for our bot to respond.

**Comment by ssapa** [comment]
@chackman  When I provide invalid id for parentReference.id, it is coping the file to same source folder i.e. Susgma_rc2 folder.

Here is the latest request details for Copy Item api:

https://graph.microsoft.com/v1.0/drives/b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6/root:/Sushma_rc2/Rc2Demo.docx:/copy

Body : {"name":"test5.docx","parentReference":{"driveId":"b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6","id":"fgdftgarsgdreg"}}

Response Headers 
{
    "cache-control": "private",
    "client-request-id": "a58abaad-a8bc-6700-f461-5b19967c7c1b",
    "content-length": "0",
    "content-type": "text/plain",
    "location": "**** Location URL ****",
    "request-id": "37886914-3bad-4fc6-98ae-83ed67f7f439"
}

Screenshot after copy :
![image](https://user-images.githubusercontent.com/50152071/97417748-0fd8f980-192e-11eb-9c8e-e9fd8b710405.png)

Steps to reproduce the issue 
1. In copy item api , provide the path of the item that you want to copy to target folder. 
2. In the body, provide the name and parentReference details as mentioned in the documentation. So in the ParentReference.id provide a invalid ID like "22ehveww87t3gevyfewf".
3. Then run the api using either graph explorer or postman and observe that we will get response 202 Accepted.
4. Once copy is completed observe that the item copied to the Source directory.

Expected Behaviour : API should throw an error stating the parentReference.id is invalid.

you can follow same steps for Move Item api as well. For move item also , the item is getting moved to the source directory.

Do let me know, if you want any more information

**Comment by chackman** [comment]
Thanks; this looks like an issue which we'll put on our backlog to address.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
