### ISSUE TITLE
Move Item fails with Bad Request error when i use special chars  in parentReference.path

### ISSUE THREAD

**Issue by ssapa** [OneDrive/onedrive-api-docs#1382]
#### Category
- [ ] Question
- [ ] Documentation issue
- [ X] Bug

Here is the request and response for move item.

Request :+1: 

https://graph.microsoft.com/v1.0/drives/b!2jIVYv-TmkuIJKAhTCyu6WeVZIBaVEpEmt_D06E9j2ZNSSz7vQgARJphpkDG4raQ/root:/test/text.xml:

{"parentReference":{"path":"/drive/root:/@$%^&()_++={}[];1233Asaa"}}

Response :+1: 
{
    "error": {
        "code": "invalidRequest",
        "message": "Invalid request",
        "innerError": {
            "date": "2020-10-09T14:42:18",
            "request-id": "b337c007-2fb5-493b-934f-e1b7dee37222",
            "client-request-id": "989068eb-5115-4dc2-4bc9-80b918a6b5c3"
        }
    }
}

As we are able to create folder using the above special characters, So expecting it to work when we use them in Move Item. Can you please help us understand what special character is causing issue and What all things we need to take care of when we do copy and Move?

**Comment by ssapa** [comment]
@chackman @baywet Can you please provide some insight on the above issue?

**Comment by baywet** [comment]
@ssapa I'm not sure why you included me, I work on the SDKs, not the service. I'm not sure I'd be able to help here but @chackman is on the right team :)

**Comment by chackman** [comment]
This item is already on our backlog to address. I'll tag it as such here.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
