### ISSUE TITLE
@microsoft.graph.conflictBehavior=Replace and Rename not working for Move Item

### ISSUE THREAD

**Issue by ssapa** [OneDrive/onedrive-api-docs#1383]
- [ ] Question
- [ ] Documentation issue
- [ X] Bug

**Conflict Behaviour=replace** not working for Move Item.
Here is the Request and Response.

PATCH : https://graph.microsoft.com/v1.0/drives/b!2jIVYv-TmkuIJKAhTCyu6WeVZIBaVEpEmt_D06E9j2ZNSSz7vQgARJphpkDG4raQ/root:/Sushma/test:

{"parentReference":{"path":"/drive/root:/"},"@microsoft.graph.conflictBehavior":"replace"}

Expected Behaviour :  Expecting it to replace the old item with the new Item.

Observed Behaviour : {
    "error": {
        "code": "nameAlreadyExists",
        "message": "Name already exists",
        "innerError": {
            "date": "2020-10-09T15:12:00",
            "request-id": "4e0d7ced-26c1-45fa-afc0-d6af2816ad94",
            "client-request-id": "25663889-0f88-d574-a8e7-9145af173c2d"
        }
    }
}

Steps to Reproduce
Try to move any folder which exists in the target folder.

**Conflict behaviour = rename** 
 For move Item, conflict bahaviour=rename is not working when the parentReference.path contains # symbol init. Here is the request.

 **Request** : 

PATCH https://graph.microsoft.com/v1.0/drives/b!2jIVYv-TmkuIJKAhTCyu6WeVZIBaVEpEmt_D06E9j2ZNSSz7vQgARJphpkDG4raQ/root:/Test%20%20%20Fo%20%20%20ld%20%20er%20NULL:

{
    "parentReference": {
        "path": "/drive/root:/tes      t     with    lon!@$#"
    },
    "@microsoft.graph.conflictBehavior": "rename"
}

Expected Behaviour :  The folder name should be renamed.
Observed Behaviour : 
{
    "error": {
        "code": "nameAlreadyExists",
        "message": "Name already exists",
        "innerError": {
            "date": "2020-10-09T14:09:26",
            "request-id": "58d88027-ac70-4e2f-9a43-67a72d9e83c3",
            "client-request-id": "39b35266-e3a2-e954-5b71-e8dab42097fc"
        }
    }
}

**Note** : When i remove # from the path, the rename is working as expected.

Thank you.

[x]: http://aka.ms/onedrive-api-issues

**Comment by ssapa** [comment]
@chackman Can you please provide some insight on the above issue?

**Comment by chackman** [comment]
Thanks, this is already on our backlog. We'll tag it here as backlogged.

**Comment by Kanac** [comment]
@chackman I believe this is still happening right now, is that expected?

**Comment by Knele83** [comment]
Uočeno ponašanje: {
"error": {
"code": "nameAlreadyExists",
"message": "Ime već postoji",
"innerError": {
"date": "2020-10-09T15: 12: 00",
"request -id ":" 4e0d7ced-26c1-45fa-afc0-d6af2816ad94 ",
" client-request-id ":" 25663889-0f88-d574-a8e7-9145af173c2d "
}
}
}

**Comment by rvirsingh** [comment]
Is it Resolved?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
