### ISSUE TITLE
Sharing with specific people only instead of "organization" scope with the filepicker sharing action

### ISSUE THREAD

**Issue by Deewens** [OneDrive/onedrive-api-docs#1385]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

Hello,
I am trying to use the OneDrive API for adding filepicker integration in a webapp. So I am using the OneDrive JS Library from this page : https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online

Here is what I would like:
When a user open a OneDrive item with the file picker, I would like to create a sharable link with no permission or, add permission just before creating the sharing link only for specific people. I saw that we can create shared link with "organisation" scope, but I don't want that all the people of an organization have access to the document, only the person for those the owner of the doc' allowed it.
Is there a way to generate a link with no permission at all (then, the person without the permission can click on the link and a "permission request" is sent to the owner of the doc') ? Or, just let the owner of the doc' add permission just before clicking on "open" in the file picker.
I can't find a way to do that with the file picker or the API.

#### Observed Behavior

There is only two way to create a sharable link with OneDrive API, anonymous or organization scope.
```javascript
var odOptions = {
            clientId: "",
            action: "share",
            multiSelect: false,
            advanced: {
                redirectUri: "blabla/authResponse.php",
                createLinkParameters: { type: "view", scope: "organization" }
            },
            success: function(files) {
                console.log(files);
                $("").val(files.value[0].webUrl);
                $("").val(files.value[0].name);
            },
            cancel: function() { /* cancel handler */  },
            error: function(error) { console.log(error); }
        };
        OneDrive.open(odOptions);
```

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Thanks for your feedback.
To share with individual users you should use the "invite" API.
   https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http
If you want to create a link with similar semantics - shared to specific users - then this would be a separate enhancement for the picker and/or Graph API that you should log using UserVoice.

**Comment by Deewens** [comment]
Hello!
So It is not possible with the current version of the Picker. Thanks for your answer, I'll probably post a feature request with this ! Until then, I will try to use the "invite" API !

Thanks!
