### ISSUE TITLE
Discrepancy in created field for sites when fetching from different API's

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1386]
#### Category
-  Bug

I have made a call for one particular site through sharepoint api endpoint
https://tenant.sharepoint.com/sites/site/subsite/_api/Web?$select=HasUniqueRoleAssignments,RoleAssignments,*&$expand=RoleAssignments/Member,RoleAssignments/RoleDefinitionBindings
and made a graph api call 
https://graph.microsoft.com/v1.0/sites?search=site_name

#### Expected or Desired Behavior
Expected behaviour is to get a same created date from both the API's 

#### Observed Behavior
however first API returns
"Created":"2020-06-19T19:37:37"
Request header details
Date:2020-10-13T10:45:08Z
Request_id: d23b839f-00e1-b000-7abe-6e90f908845e

however graph API returns
createdDateTime":"0001-01-01T08:00:00Z",
Request header details
Date: Tue, 2020-10-13 10:18:43Z
Request_id: 5c8f6e1a-30bb-4fdb-926a-5b51ac838e78

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Thanks, this might be a search issue. If you use the "get site by ID" API does that also provide the correct results?
   https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http
