### ISSUE TITLE
File Picker "Save" button is disabled before selecting a folder

### ISSUE THREAD

**Issue by mnaeimi** [OneDrive/onedrive-api-docs#1387]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

I am using oneDrive file picker to save a file in oneDrive according to this documentation (https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/save-file?view=odsp-graph-online). 
But after the dialog is opened in specified path the save button is disabled till user select a folder. 
![image](https://user-images.githubusercontent.com/6196596/95870815-39f6bd00-0d6d-11eb-837e-2a6c4409c3f8.png)

Options I used are: 
> var odOptions = {
> 				  clientId: clinetID,
> 				  action: "query",
> 				  viewType: "folders",
> 				  openInNewWindow: true,
> 				  advanced: {
> 					  endpointHint: filePath,
> 				  	  accessToken: token,
> 					  navigation:{
> 						  disable:false,
> 						  sourceTypes : ["Sites", "OneDrive"]
> 					  }
> 				  },
> 				  success: function(files) { onSuccess(files);},
> 				  progress: function(percent) { onProgress(percent); },
> 				  cancel: function() { onCancel(); },
> 				  error: function(error) {onFail(error); }
> 				}

#### Expected or Desired Behaviour
after the dialog is opened in specified path the save button should be enabled.

Please let me know if you need more information.
Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
