### ISSUE TITLE
Need Role mappings for roles return from graph API and roles return from _api/Web/Lists endpoint (with RoleAssignments)

### ISSUE THREAD

**Issue by zeeshanzahid-elastica** [OneDrive/onedrive-api-docs#1389]
#### Category
- [x] Question

- If we make following API call

https://tenant.sharepoint.com/personal/user_id/_api/Web/Lists(guid'XXXXXXX')?$select=HasUniqueRoleAssignments,RoleAssignments,*&$expand=RoleAssignments/Member,RoleAssignments/RoleDefinitionBindings

- We can drive one of the following roles from the response of above API

    "Limited Access" ,
    "Read",
    "Contribute",
    "Design",
    "Full Control",
    "Edit"

- But if we want to use following graph permission API

https://graph.microsoft.com/v1.0/users/user_id/drive/items/item_id/permissions

- We can only get one of the following roles from the response 

read	        
write	
sp.owner	
sp.member

### Question

We want to use graph permission API. But How can we map roles from above two API calls?

**Comment by chackman** [comment]
Thanks for your feedback. Could you please explain your scenario a little further - why this information is required?

**Comment by zeeshanzahid-elastica** [comment]
We have been categorizing roles using following scenarios

"Limited Access" ,
"Read",
"Contribute",
"Design",
"Full Control",
"Edit"

But now from graph APIs we are not getting the above mentioned info

**Comment by chackman** [comment]
We're following up internally about this.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
