### ISSUE TITLE
[Question] Is there any place to indicate the file/folder limitation?

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#139]
Hi, is there any place to indicate the limitations like min/max length, valid characters and naming constraints of file and folder?

Thanks!

**Comment by rgregg** [comment]
Some of that information is documented on the [Path Encoding](https://dev.onedrive.com/misc/path-encoding.htm) page. If there are other specifics you think would be helpful, let me know and I'll see if we can get them documented.

**Comment by mikechiu1012** [comment]
Hi @rgregg ,

thanks u!

Other conventions like the file amount in the same folders or the maximum file numbers, is there any comment about this?

By my testing, there could be more than 60k files under the same folder.
But how about OneDrive for Business?
It seems to be 20k files upper bound.

I am appreciated if there is any document about this! 
thanks for ur efforts.

**Comment by mikechiu1012** [comment]
according to the Path Encoding page, 
the leading blanks of folder/file name is permitted.

but if I create a folder with name ' 123' under root folder,
the response is:
400 {"error":{"code":"pathContainsInvalidCharacters","message":"Path is Invalid","innererror":{"code":"badArgument","innererror":{"code":"invalidPath"}}}}

I think it might be a constraint cause old API has this naming convention.
there are three constraints:
1. no leading blanks
2. no tailing common
3. name could not be all blanks.
under my test, these three constrains are satisfied for new API.
I think this might be new API's constraints, too?
or just bugs need to be checked ?

**Comment by joewutaiwan** [comment]
ref. this
https://github.com/OneDrive/onedrive-api-docs/issues/132

**Comment by rgregg** [comment]
We are missing the details about limits for OneDrive for Business, since the requirements are currently more strict than personal OneDrive. I'll work on getting those added to the documentation.

**Comment by mikechiu1012** [comment]
hi rgregg, thanks for ur reply!

**Comment by rgregg** [comment]
I've added more details about OneDrive for Business limitations to the page here: [File encoding](https://dev.onedrive.com/misc/path-encoding.htm).

However, our documented limitations don't cover the limitations you mentioned. I'm looking into those, although 3) is definitely true, a filename cannot be just whitespace.
