### ISSUE TITLE
Create folder invalidRequest error

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1390]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hello, 

Sometimes when I request a [create folder API] encount this error, but succeed after a retry.
```
https://mydomain-my.sharepoint.com/_api/v2.0/drives/[drive_id]/items/012DOYZZW6I6H5LZMETNF2Z7TJ5MEH4ZOM/children
content_type: application/json
post_data: {"@name.conflictBehavior":"fail","folder":{},"name":"123123"}:
```

`
400
invalidRequest
Invalid request 
`

This is request infotmations:

request A:
```
Date: Mon, 19 Oct 2020 09:56:16 GMT
SPRequestGuid: 6727859f-90c3-b000-3ef9-f8b5754297fa
request-id: 6727859f-90c3-b000-3ef9-f8b5754297fa

```

request B:
```
Date: Mon, 19 Oct 2020 09:56:16 GMT
SPRequestGuid: 6727859f-40c2-b000-110c-2fc733ac3706
request-id: 6727859f-40c2-b000-110c-2fc733ac3706

```

Is it possible to know what happen here?

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback. In this situation there were too many requests at the same time and your application should have received a 429 or 503, but the error code returned is currently incorrect.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
