### ISSUE TITLE
Is file handler available on OneDrive mobile app?

### ISSUE THREAD

**Issue by lukchen** [OneDrive/onedrive-api-docs#1391]

**Comment by chackman** [comment]
Thanks for your feedback. Unfortunately File Handlers are not currently available via the OneDrive mobile app. We would recommend suggesting this feature via UserVoice. Links to UserVoice are in the New Issue template; here they are again for your convenience
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.
