### ISSUE TITLE
Can not open uploaded ONENOTE file 

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1393]
### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Uploaded ONENOTE file *.one can open in OneDrive.

#### Observed Behavior

Recently we found a weird problem, ONENOTE file can not be open after we uploaded it **for days.**

It shows following message:
**This section was originally created in an older version of OneNote.**

![image](https://user-images.githubusercontent.com/12619781/96836900-356e8a80-1478-11eb-8be3-105c51c47d87.png)

#### Steps to Reproduce

Step 1. use upload item API to upload OneNote file
`PUT /_api/v2.0/drives/d_id/items/root:/test_123_2.one:/content?%40name.conflictBehavior=replace`
```
Date: Thu, 22 Oct 2020 07:21:48 GMT
SPRequestGuid: c315869f-30f4-b000-7ffd-f6a0d1348000
request-id: c315869f-30f4-b000-7ffd-f6a0d1348000
```

Step 2. after day, the OneNote file fails to open, but works fine at begining.

#### Question

1.Should I do any process or API request after I uploaded ONENOTE file?
2.For ONENOTE file which failed to open,  I can download it and then upload it via browser operations to fix it.

Thank you.

**Comment by joewutaiwan** [comment]
Additionally, I found that uploaded file contains hashes facet, but others do not.

File which uploaded by API:
```
"file": {
    "hashes": {
        "quickXorHash": "C7f0/bkeoat4+SJ7x9w/zPaghvc="
    },
    "irmEnabled": false,
    "mimeType": "application/msonenote"
},
```

Others: (original one or uploaded by browser)
```
"file": {
    "irmEnabled": false,
    "mimeType": "application/msonenote"
},
```

**Comment by joewutaiwan** [comment]
### More information:

This kinds of file has more versions than expected.
For example, **one version** at beginning, but **two versions** while failing to open

![image](https://user-images.githubusercontent.com/12619781/96952904-77eca180-1522-11eb-93ba-f11b987e318c.png)

And the version 2.0 file has additional hash facet.

So in my speculation, maybe the cause is the hash calculation in post-process on server side.

Thank for help!

**Comment by chackman** [comment]
This is likely a feature enhancement request, but per the current documentation, the recommended way to move a notebook is to use the OneNote client: 
https://support.microsoft.com/en-us/office/move-a-onenote-notebook-to-onedrive-0af0a141-0bdf-49ab-9e50-45dbcca44082

**Comment by joewutaiwan** [comment]
Hi @chackman,

Thanks for reply.

Is it possible to fix this or have a alternative in Onedrive Upload API?

For example, we can bring some parameter in Onedrive Upload API to prevent this, etc.

**Comment by joewutaiwan** [comment]
Are there any updates about this?

Now every onenote file uploaded by OneDrive is corrupted.

Thank a lot!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
