### ISSUE TITLE
Error when Uploading MS Office files through Graph API to sharepoint online

### ISSUE THREAD

**Issue by onlinerack** [OneDrive/onedrive-api-docs#1395]
We get an error when we upload MS files via Graph API to sharepointonline.  Stating that the size is different. I understand sharepoint add meta data to the file as soon as it is uploaded. The quesiton is, how can we upload the files and not receive that error?

**Comment by chackman** [comment]
Could you please provide more information about your issue? We'll tag so our bot replies with what we would require.
