### ISSUE TITLE
404 response because of wrong API URL generated by onedrive.js (OneDrive File Picker JavaScript SDK)

### ISSUE THREAD

**Issue by PierrickMartos** [OneDrive/onedrive-api-docs#1396]
Hi,

I got an issue with your OneDrive File Picker Javascript SDK (i'm using 7.2), when i use the `share` or `download` actions (it works with the `query` actions), **OneDrive.js generate wrong API URL**, mysteriously, your Javascript append to the API url the sharepoint sitename.

Here is more details of what i do and to reproduce : 

Like specified in your documentation (https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online), we can pass in `endpointHint` a SharePoint document library URL.
So i've set the URL to my shared documents sharepoint website, i'm under a french sharepoint so url is `https://mytenant.sharepoint.com/Documents%20partages/` instead of `https://mytenant.sharepoint.com/shared%20documents/`.

Everything ok, popup, then login, then the onedrive picking page:
![image](https://user-images.githubusercontent.com/1785711/97581212-9526e180-19f4-11eb-975e-2a5185c1029f.png)
I select one or several files, then click on "Ouvrir" (Open), popup close and then i got 404 error response with this error : 

```
XHR GET https://mytenant.sharepoint.com/Documents%20partages/_api/v2.0/drives/b!SACSU4CwMEumL8i7GhBy_6-tGhuvB9VBhv2zaXnTBlwJEM203M0NRb0Nrb5cytGZ/items/01YGYIIS7WVLP4SNN4CNBLPC7ZUWSJ4ZJW
[HTTP/2 404 Not Found 68ms]
XHR GET https://mytenant.sharepoint.com/Documents%20partages/_api/v2.0/drives/b!SACSU4CwMEumL8i7GhBy_6-tGhuvB9VBhv2zaXnTBlwJEM203M0NRb0Nrb5cytGZ/items/01YGYIIS37VMXCKXOYE5FKUSIBZF42OTDH
[HTTP/2 404 Not Found 65ms]
[OneDriveSDK] calling xhr failure callback, status: 404 
OneDrive.js:4:42959
[OneDriveSDK] Received ajax error. 
OneDrive.js:4:42959
[OneDriveSDK] Failed due to unknown error:  
OneDrive.js:4:42959
TypeError: a is undefined
    shareItems https://js.live.net/v7.2/OneDrive.js:4
    shareItems https://js.live.net/v7.2/OneDrive.js:4
    o https://js.live.net/v7.2/OneDrive.js:12
    H https://js.live.net/v7.2/OneDrive.js:12
    A https://js.live.net/v7.2/OneDrive.js:12
    f https://js.live.net/v7.2/OneDrive.js:12
```

I don't know why, but OneDrive.js generates wrong API urls, instead of generating `https://mytenant.sharepoint.com/_api/v2.0/drives/{driveId}` it generates `https://mytenant.sharepoint.com/Documents%20partages/_api/v2.0/drives/{driveId}`

The subdir `/Documents%20partages` is appended to the URI... here is a screenshot of Firefox console : 

![image](https://user-images.githubusercontent.com/1785711/97581754-3e6dd780-19f5-11eb-98e7-3718ab4bb829.png)

Here is my snippet:
```js
let odOptions = {
                clientId: appId,
                action: "share",
                multiSelect: true,
                advanced: {
                    endpointHint: 'https://mytenant.sharepoint.com/Documents%20partages/',
                    createLinkParameters: { type: "edit", scope: "organization" },
                    redirectUri: Routing.generate('onedrive_redirect', null, true),
                },
                success: function(files) {
                    console.log(files);
                },
                cancel: function() {
                    console.log('cancel');
                },
                error: function(error) {
                    console.log(error);
                }
            }
            OneDrive.open(odOptions);
```

Here is the SDK version i used:
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>

PS : i've replaced my real tenant name by `mytenant`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#customize-capabilities)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by PierrickMartos** [comment]
Hi @chackman , 15 days and still no answer anywhere. I've contacted Microsoft 365 support no answers also, is it possible that someone at Microsoft took care of this issue?

**Comment by chackman** [comment]
Could you please clarify whether this has been resolved?

**Comment by chackman** [comment]
(Removing Triage tag as we have tagged it for the area owners to investigate.)

**Comment by PierrickMartos** [comment]
> Could you please clarify whether this has been resolved?

It’s **not** resolved. I’ve tried several configurations on several sharepoints, same issue all the times. I’m losing faith for finding a solution.

**Comment by ThomasMichon** [comment]
Just to comment on usage of the Picker API:
The `endpointHint` value is intended to be that of a SharePoint *Site* or *Site Collection*, not that of a specific *List* or *Document Library*. This is because only Sites have 'API Endpoints' for the Graph API. Here, 'Documents partages' is a *List*, and while its URL is a sub-directory under the domain, that doesn't mean it can be used directly as an 'endpoint'.

Unfortunately the documentation that `endpointHint` can be used for a list is misleading.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
