### ISSUE TITLE
Create subscription fails: Status Code: Forbidden; Reason: Access denied

### ISSUE THREAD

**Issue by register110** [OneDrive/onedrive-api-docs#1398]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
Subscription successfully created

#### Observed Behavior
The server successfully sent back verification, but the response to create the subscription showed an error. Of course, the server never gets the resource change notification
![server_feedback](https://user-images.githubusercontent.com/60174486/99635288-ba9b8e00-2a7c-11eb-89a2-2df4875d618a.PNG)

```
{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: Access denied]",
    "innerError": {
      "date": "2020-11-19T07:28:27",
      "request-id": "24eb84e5-61e9-4725-8e19-4bf7f04b528d",
      "client-request-id": "24eb84e5-61e9-4725-8e19-4bf7f04b528d"
    }
  }
}
```

#### Steps to Reproduce
```
import requests

headers = {
    'Authorization': 'Bearer my_token_here_login_as_app'
}
json = {
    "changeType": "updated",
    "notificationUrl": "https://b9e2eae74621.ngrok.io/notification",
    "resource": "/users/my_id_here/drive/root",
    "expirationDateTime": "2020-11-19T18:23:45.9356913Z",
    "clientState": "secretClientValue",
    "latestSupportedTlsVersion": "v1_2"
}
subscription_api = "https://graph.microsoft.com/v1.0/subscriptions"
resp = requests.post(subscription_api, headers=headers, json=json)
print(resp.text)
```
Configured permissions
![permission](https://user-images.githubusercontent.com/60174486/98907384-b6f68d00-24f9-11eb-93c8-061f332609d2.PNG)

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
