### ISSUE TITLE
Resumable Upload does not give nextExpectedRanges

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-api-docs#14]
When I have one thread `PUT`ting partial content (e.g., `bytes 0-65360/123456789`) on the uploadUrl given by uploadSession, the response is simply HTTP 202 with body
```javascript
{'expirationDateTime': '2015-03-13T03:42:23.7511359+00:00'}
```
without key `nextExpectedRangs`.
I thought I would get a nextExpectedRanges like `['655361-123456789']`. Might this be a bug? If not then this behavior better be documented as I haven't read any indication that this param is optional.

Thanks for this new API! It is much better than the old Live API + BITS API combined.

**Comment by daspek** [comment]
Thanks for the report! Yes, this looks like a bug. We'll work on a fix.

**Comment by ificator** [comment]
This issue should now be resolved, please let us know if you still see something strange.
