### ISSUE TITLE
Authentication expires during upload

### ISSUE THREAD

**Issue by psyfreaky** [OneDrive/onedrive-api-docs#140]
Hi,
when the upload takes a long time, authentication token expires (401 Unauthorized) and current chunk is not saved. I think this is a regression because it was ok before. It is not a problem to refresh the token but it is needed to get status and upload last chunk again. I don't have to explain that it is not comfortable for people who upload large files and have slow connection. That is not a correct behavior I think.

**Comment by rgregg** [comment]
This behavior is a bug. The validation of the auth check should occur when the request starts, and if the request takes 1+ hour to finish, it shouldn't be rejected because the `access_token` is no longer valid.

**Comment by rgregg** [comment]
This is still an issue. For now, we recommend renewing the access_token well before the expiration date if you are doing an upload to ensure that the upload will finish before the token expires. @daspek is working on a fix.

**Comment by psyfreaky** [comment]
Thanks for working on that. Unfortunately, renewing access_token does not work anymore. For some unknown reason it returns this:
{"error":{"code":"invalidRequest","message":"Upload session failed","innererror":{"code":"uploadSessionFailed"}}}
Is that upload url removed if the session expires?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
