### ISSUE TITLE
Required graph api's endpoint to fetch the url which can remove share link

### ISSUE THREAD

**Issue by zeeshanzahid-elastica** [OneDrive/onedrive-api-docs#1400]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I have a question for sharelink removal.

We are using the sharepoint api:_api/SP.Web.DestroyOrganizationSharingLink. The acceptable parameter for this api is an url of format "/sites/servicetransitionknowledgebase/Shared Documents/Email and Exchange Online/Email Protection Administration.docx”. 
 
We currently use the graph api to get metadata
Example: https://graph.microsoft.com/v1.0/drives/b!6z4B5Aa4uEOKHadx7BYqYfaGaqzHnC5DvZrkr-TVMAS-hBjDjz2MTpozSoGtLlky/root/delta?$select=id%2cname%2csize%2csharepointIds%2cparentReference%2ccTag%2cfileSystemInfo%2ceTag%2ccreatedBy%2cfile%2cfolder%2cdeleted%2cshared%2cwebUrl
 
But I don’t find any metadata from graph api/ delta api that gives the url for compatible with DestroyOrganizationSharingLink api. The path, url metadata is the preview url of the format (https://lumeris1.sharepoint.com/sites/servicetransitionknowledgebase/_layouts/15/Doc.aspx?sourcedoc={89cfcfd8-f054-425f-ba0e-da2742a6ac02}&action=interactivepreview) 
 
Could you please point me to the correct endpoint that fetches this acceptable url for sharelink removal?

**Comment by chackman** [comment]
We would recommend that your application uses the [delete permission API](https://docs.microsoft.com/en-us/graph/api/permission-delete?view=graph-rest-1.0&tabs=http) to delete the permission associated with the link that needs to be deleted.
Could you please try that API?

**Comment by register110** [comment]
@zeeshanzahid-elastica 
If you just want to delete the shared link, you can follow chackman's suggestion, but you use delta query here, I guess you want to call some api to delete the shared link when someone is sharing, right? Actually I am facing such a problem. There is no guarantee that the shared link will be deleted before someone views it. In addition, you can only check whether the user is sharing the file by finding this element in the response of the delta query:
```
"shared": {
         "scope": "users"
}
```
For example, if you want to check whether /root/some_directory/your_file is shared with others, the response of the delta query will look like this:
```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
  "@odata.deltaLink": "https://graph.microsoft.com/v1.0/users/username@yourdomain.onmicrosoft.com/drive/root/delta?token=MzslMjM0OyUyMzE7MztiYTVhMzA4YS1hMmQyLTRjYzEtOGU4ZC02ZGE1ZWE3NzAzNWY7NjM3NDE3OTQ5ODQ1MzAwMDAwOzMwNTQ3MjcwODslMjM7JTIzOyUyMzA",
  "value": [
    {
      root information block
    },
    {
      some directories information block
    },
    {
      This is the last index of the value, please note that this is your file information block,
      If the following shared element exict, it means the file has been shared with others
      "shared": {
        "scope": "users"
      }
    }
  ]
}
```
