### ISSUE TITLE
What is the drive id. The doc is not useful. So in drive/{driveId}, make a user go to driveId(what it is, how to get) when he clicks this.

### ISSUE THREAD

**Issue by future-mine** [OneDrive/onedrive-api-docs#1401]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350cd850-d19a-ef5c-2761-e342fc3c506c
* Version Independent ID: 5bf3ef39-f20a-6c7f-77f6-3bc7e9d246f4
* Content: [Upload small files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_put_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_put_content.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by register110** [comment]
@future-mine 
when you see the id in document, which means you could replace it by:
1. id
2. resource name( or path)

for example, to get a user's OneDrive by resource name, you could:
**GET** https://graph.microsoft.com/v1.0/users/username@yourdomain.onmicrosoft.com/drive

you can have a look at this response, which also include username's drive id, so, for the next time you could:
**GET** https://graph.microsoft.com/v1.0/users/resource_id_here/drive

**Comment by chackman** [comment]
Thanks, register110. future-mine does this address your question?
