### ISSUE TITLE
lantency between delta query and receipt of change notification

### ISSUE THREAD

**Issue by register110** [OneDrive/onedrive-api-docs#1402]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
~~The program can get the right delta query result~~
The program can get the right delta query result in time after server gets the resource change notification

#### Observed Behavior
~~When you follow the delta link on Graph Explorer, you will get the correct result, but when the program sends delta query, it will return a different delta token, which always returns a null value~~
Both Graph Explorer and the program can get the correct results, but it is delayed. You cannot get it in time after the user makes changes and the server receives the change notification

#### Steps to Reproduce
```
import requests

headers = {
    'Authorization': 'Bearer my_token_here_login_as_app'
}

delta_query = "https://graph.microsoft.com/v1.0/users/my_id_here/drive/root/delta"
resp = requests.get(delta_query, headers=headers).json()
resp = requests.get(resp['@odata.deltaLink'], headers=headers)

print(resp.text)
```
~~And the output is:~~
When sending delta queries early, you will get a null value:
```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
  "@odata.deltaLink": "https://graph.microsoft.com/v1.0/users/my_id_here/drive/root/delta?token=MzslMjM0OyUyMzE7MztiYTVhMzA4YS1hMmQyLTRjYzEtOGU4ZC02ZGE1ZWE3NzAzNWY7NjM3NDExMDc3MTcxNTMwMDAwOzMwMTQyODI1MzslMjM7JTIzOyUyMzA",
  "value": []
}
```

Thank you.

**Comment by JeremyKelley** [comment]
A couple questions:
1) Are you using Delegated or App Only authentication?
2) If you're using Delegated auth do you have access to the drive you're looking for the Delta on?

**Comment by register110** [comment]
> 
> 
> A couple questions:
> 
>     1. Are you using Delegated or App Only authentication?
> 
>     2. If you're using Delegated auth do you have access to the drive you're looking for the Delta on?

@JeremyKelley 
Thanks for your reply. I use App Only authentication. And I updated this issue. Currently, I need to get the delta results in time after the Microsoft Graph sends the change notification, but I don’t know when to send the delta query

**Comment by chackman** [comment]
You service should send the delta query after the change notification was sent to your service.
Here is a link to our scan guidance which, among other things, talks about how to register and respond to change notifications. It's pretty lengthy, but might be helpful.

https://aka.ms/scanguidance

**Comment by register110** [comment]
Thank you very much. Really helpful. I followed the documentation and it can be work now.
