### ISSUE TITLE
SDK handling of percent encoding & Unclear or deprecated code samples

### ISSUE THREAD

**Issue by david-fong** [OneDrive/onedrive-api-docs#1404]
In lieu of [this issue resolution](https://github.com/microsoftgraph/msgraph-sdk-java/issues/259), I think the documentation section for Android development should be updated with a note that percent encoding is automatically handled for Java SDK versions 2.1.0 and up.

For the .NET section: [the .NET sdk has built percent encoding into itself](https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/572). That PR was merged into master [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/771), which was released in its [sdk version 3.15.0](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/3.15.0). Those using a lower version could use [`UriBuilder.Uri.OriginalString`](https://docs.microsoft.com/en-us/dotnet/api/system.uri.originalstring), which is a little magical since the original string is given to the Uri constructor by the UriBuilder. That approach can probably be replaced with [`Uri.EscapeDataString`](https://docs.microsoft.com/en-us/dotnet/api/system.uri.escapedatastring).

At the JavaScript section, the `escape` function is being recommended by the code sample, but `escape()` is [currently pending deprecation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape). [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) is recommended to be used in its place, and it seems to meet all the encoding criteria required by the Graph API.

It's worth aligning with the SDK teams to establish procedures for updating Microsoft docs so that the SDK capabilities and the Microsoft docs don't fall out of sync. A lack of consistency can create a frustrating and confusing user experience, especially when trying to read documentation to find out why something isn't working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1091f-ac3f-0b89-dad1-230ffe642eeb
* Version Independent ID: c71b093b-db90-b85d-6208-52a3ddde5e40
* Content: [How to address resources - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/addressing-driveitems?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/addressing-driveitems.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/addressing-driveitems.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
We'll add this item to our documentation backlog. If you wish, you may also contribute a PR to address this issue.

**Comment by david-fong** [comment]
> We'll add this item to our documentation backlog. If you wish, you may also contribute a PR to address this issue.

Thanks, Chris. I'll make a PR if I find time.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
