### ISSUE TITLE
500 error response when trying to get the Content of the File

### ISSUE THREAD

**Issue by roman-belfer** [OneDrive/onedrive-api-docs#1405]
Hi! I'm creating a WebApi application to interact with the OneDrive.

I've successfully set the subscription up to get a notification when the OneDrive items are changed. Now I want to somehow manipulate the changed file.

When I'm trying to get the methadata of the changed file it works:

`var item = await client.Drive.Items[resourceId].Request().GetAsync();`

But if I'm trying to get a Content of the specific file it does nothing:

` var content = await client.Drive.Items[resourceId].Content.Request().GetAsync();`

ngrok tool, used to get notifications, keeps showing me a 500 Internal Server Error

![image](https://user-images.githubusercontent.com/11720897/100371736-e8e71380-3010-11eb-8ad1-8699b0430c36.png)

I've also set the ReadWrite.All permissions for Microsoft Graph on Azure Active Directory, where my app is registered, but it says that it's not granted. Could it be the reason?

![image](https://user-images.githubusercontent.com/11720897/100372056-601ca780-3011-11eb-9339-a3514b66c6e3.png)

**Comment by k-tsoi** [comment]
Could you give us more information about the failing request like a requestId(correlationID) and timestamp
