### ISSUE TITLE
How does the custom file handler support the sharing link?

### ISSUE THREAD

**Issue by llx9** [OneDrive/onedrive-api-docs#1406]
[Enter feedback here]
if I created my own file with the custom file handler and created a sharing link.
What's the expected pattern for others to hit that link directly? Does it trigger the "open" action specified in manifest?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815ef941-29d7-1864-6be3-f533dd62da00
* Version Independent ID: 1d566c70-e679-caf2-312a-27aa5e2cc62e
* Content: [Add custom actions to files - OneDrive - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/define-actions?view=odsp-graph-online)
* Content Source: [docs/file-handlers/define-actions.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/define-actions.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
