### ISSUE TITLE
[Question] Forbidden char at create folder etc.

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#141]
hi all,

I could not create folder or file at onedrive for business at office with those chars:  " # % * : < > ? / \ |

But when I use API like create folder:
```http
POST https://{tenant}-my.sharepoint.com/_api/v2.0/me/item_id/children
authorization: Bearer access_token
Content-Type: application/json
```
```json
{
  "name": "FolderA#",
  "folder": { },
  "@name.conflictBehavior": "fail"
}
```

I can break through the limitation.
Is it an API bug or developer should get handle of this?

thanks

**Comment by ksheode** [comment]
Hi joewutaiwan,
This is a feature to allow developers to be able to create files and folders with characters that are still restricted in the UI. It is not a bug.
Thanks.

**Comment by ankit-ankuagrawal** [comment]
@ksheode 
what is the use case behind giving developer ability to create files and folder with characters that are still restricted in the UI.

since they are restricted no one be able to create...

can u pls elaborate this

**Comment by rgregg** [comment]
@ankit-ankuagrawal: We're evaluating various internal ways that we can add support for these restricted characters to SharePoint and OneDrive for Business and you noticed that the OneDrive API lets you created them. 

Right now the only end point that allows them is the OneDrive API. We've logged a bug to make sure that the API is consistent with how the rest of SharePoint works -- in other words, we should be blocking those characters until such time that they are available to be used everywhere.
