### ISSUE TITLE
what is item id

### ISSUE THREAD

**Issue by AjithSatheesh** [OneDrive/onedrive-api-docs#1411]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc176919-e830-cd2e-33fe-6a4ff59020e8
* Version Independent ID: 97b9df74-d897-36a9-7f46-82114a2d7180
* Content: [Get a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_get.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by k-tsoi** [comment]
Please take a look at this DriveItem documetation: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online
The "id" field of this object is the itemId you are looking for
