### ISSUE TITLE
Perdi meu telefone não tô conseguindo acessar meu Hotmail o número pra recuperar não tenho mais

### ISSUE THREAD

**Issue by Marcossaint** [OneDrive/onedrive-api-docs#1413]
A muito tempo não uso minha conta agora que quero entrar pedem pra confirmar que sou eu mais o número de telefone pra recuperar não tenho acesso a muito anos
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d07a81d-cdaf-bafb-c1d5-aaf640d8de09
* Version Independent ID: c674b276-f0cb-a5d6-3098-6a31c417f162
* Content: [OneDrive Controls for Developers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/?view=odsp-graph-online&redirectedfrom=MSDN)
* Content Source: [docs/controls/file-pickers/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by k-tsoi** [comment]
If you are having trouble with your account please go here
https://support.microsoft.com/en-us/account-billing/when-you-can-t-sign-in-to-your-microsoft-account-475c9b5c-8c25-49f1-9c2d-c64b7072e735

**Comment by DanielaNogueira2022** [comment]
Tem alguns anos que venho tentando resgatar o acesso a conta de email danielaesucesso@hotmail.com. Já usei todos os meios oferecidos pelo site. Alguém pode me ajudar. Não lembro a senha, não tenho acesso ao celular cadastrado. Meu novo email é danielabrasiliense2022@gmail.com
