### ISSUE TITLE
PATCH to update metadata of a file in DocumentLibrary results in 409 response; Code: resourceModified

### ISSUE THREAD

**Issue by spmanjunath** [OneDrive/onedrive-api-docs#1414]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
I am using Microsoft Graph SDK to upload a file to SharePoint's DocumentLibrary (..DocumentSet) and then update the metadata.   The code used to upload and update metadata is as below,
```
var created = await _graphServiceClientFactory.GetClient().Drives[driveId].Root.ItemWithPath($"{id}/{fileName}").Content.Request().PutAsync<DriveItem>(stream);
if (created != null)
{
    await _graphServiceClientFactory.GetClient().Drives[driveId].Root.ItemWithPath($"{id}/{fileName}").ListItem.Fields.Request()
               .UpdateAsync(new FieldValueSet { AdditionalData = dataDictionary });
}
```
Since the call to update metadata happens only after successful response from the file upload the expectation is that the metadata to be updated successfully.  The metadata (part of dataDictionary) contains few of the custom fields.

#### Observed Behavior
The file upload works as expected, however once in a while updating metadata of a file fails with 409 error.  The error details returned on failed scenarios is below:

> Code: resourceModified
> Message: The resource has changed since the caller last read it; usually an eTag mismatch
> Inner error:
> 	AdditionalData:
> 	date: 2020-12-16T16:00:05
> 	request-id: 87b6fddb-eed0-4454-8550-5db28b919c29
> 	client-request-id: 87b6fddb-eed0-4454-8550-5db28b919c29
> ClientRequestId: 87b6fddb-eed0-4454-8550-5db28b919c29

Flow as observed in Application insight,
![image](https://user-images.githubusercontent.com/7764072/102380100-89679c80-3fed-11eb-8ce4-8e034309037c.png)

#### Additional information
The implementation described above is part of a middleware exposed as REST API's.  

Thank you.

**Comment by k-tsoi** [comment]
@spmanjunath are you making the same request to the same file concurrently?

**Comment by spmanjunath** [comment]
There are no concurrent requests.  The request for patch that does the metadata update happens only after the file upload (PUT) request is completed.

**Comment by spmanjunath** [comment]
More information:  Since the issue appeared to be transient in nature, i retried the request using Polly, and across several tests the observation was that PATCH call was consistently failing.  Please note that the PATCH call is done sequentially i.e., after the success response from the PUT call (for file upload).  Although, retry seem to fix this issue, i am concerned on the frequency of PATCH failing, in my tests past 10 calls consistently displayed the below behaviour.

Note:  The second PATCH call below is a retry call using Polly.
![image](https://user-images.githubusercontent.com/7764072/104568739-75f43380-5676-11eb-8157-bfc3b868f7f8.png)

**Comment by k-tsoi** [comment]
@spmanjunath is this still reproducing? like I mentioned in the other issue, there was a bug fix that went in that could have resolved this issue

**Comment by spmanjunath** [comment]
I couldn't find a failed PATCH request that occurs immediately after the PUT (file upload) request - earlier PATCH requests were failing due to resourceModified (eTag) error .  It is difficult to conclude if the issue has been fixed as it was an intermittent issue, but from the current data it appears that it is no longer occurring.  Importantly, I am also noticing a different error, which i had not noticed earlier, this error too occurs immediately after the PUT (file upload), the error details are as below, not sure if it is result of the recent fix.

```
Code: timeout
Message: The request timed out.
 The operation was canceled. Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. The I/O operation has been aborted because of either a thread exit or an application request.
```


HostInstanceId | 1b0d0257-5b45-495e-ba11-1bd7af7c9931 |  
-- | -- | --
InvocationId | 98d1dd9a-d133-46bd-a500-67ba6696a519 |  
ProcessId | 6876 |  
Category | Function.UploadFileWithMetadata |  
LogLevel | Information |  

![image](https://user-images.githubusercontent.com/7764072/106999825-de818c80-67ac-11eb-9723-ede44fab4974.png)

**Comment by k-tsoi** [comment]
@spmanjunath This issue should be fixed now, the new timeout error is unrelated

**Comment by spmanjunath** [comment]
I have been noticing this issue again (not sure if it was resolved earlier), this error occurs intermittently after uploading of file is completed, 
![image](https://user-images.githubusercontent.com/7764072/224297317-ddccef6b-fa42-4b2d-971d-814047e8bb5b.png)

There are 4 retries, the first exception is '409 eTag mismatch', the next 2 is '504 Gateway timeout' response, the last is again the '409 etag mismatch'.  Across several calls the same set of errors are observed.  This seems to happen even in scenarios where there is only one call updating the file.  What could be contributing to this error?  Is this an issue in Microsoft graph?

**Operation ID:** 8ce787b083141a4aaf3d6389e4d2300f

**eTag mismatch error:**
```
Code: resourceModified
Message: The resource has changed since the caller last read it; usually an eTag mismatch
Inner error:
	AdditionalData:
	date: 2023-03-10T08:59:07
	request-id: 57a09998-6af2-4b42-9878-cfbce0fe80e8
	client-request-id: 57a09998-6af2-4b42-9878-cfbce0fe80e8
ClientRequestId: 57a09998-6af2-4b42-9878-cfbce0fe80e8
```
