### ISSUE TITLE
drive ID received from /me/drive appears to be malformed 

### ISSUE THREAD

**Issue by jonath92** [OneDrive/onedrive-api-docs#1416]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior
A couple of month ago I made some code changes for  [Joplin](https://github.com/laurent22/joplin)  in order to support OneDrive For Business. Therefore I added a request to `/me/drive` for getting the drive ID which is necessary for making request to OneDrive for Business and optional for OneDrive Personal. Since then the drive ID is used inter alia for getting the App Directory by making a request to: `/me/drives/${driveId}/special/approot`.  For simplicity the request is used also for OneDrive Personal although the App Directory could also be received without the use of the Drive Id in that case. I expect that I always return the App Directory or a clear error message when using the Drive ID which I received from the API. 

#### Observed Behavior

For the vast majority this is working without any problems but two users received the error: 
```
Error: The provided drive id appears to be malformed, or does not represent a valid drive.
```

Luckily one user provided a log file with the request- and client-request-id: 
```
request-id":["24f73de2-59b6-4476-8086-454b81606bc6"],"
client-request-id":["24f73de2-59b6-4476-8086-454b81606bc6"]
```
For troubleshooting purposes I asked the user then to make a request to `/me/drive` using the Graph Viewer. For some reason the user received the following error:

```
{
    "error": {
        "code": "unauthenticated",
        "message": "Must be authenticated to use '/drive' syntax.",
        "innerError": {
            "date": "2020-12-16T14:32:32",
            "request-id": "72296ca3-bb5d-44e0-bfb6*****c416992",
            "client-request-id": "e17bf025-2d8f-070d-8dd7-****c4e56d6c"
        }
    }
}
```
Could you please have a look at the provided request id and tell me why we get the error messages? Let me know if you need more information. Thanks

**Comment by k-tsoi** [comment]
@jonath92 please provide the full unsanitized guid for the requestID and correlating timestamp
