### ISSUE TITLE
OneDrive Delta API call doesnot honor the $top parameter

### ISSUE THREAD

**Issue by agrankur** [OneDrive/onedrive-api-docs#1417]
When using the API (https://graph.microsoft.com/v1.0/users/<user_id>/drive/root/delta?token=<token>&$top=50) to fetch changes from One Drive, the value specified as $top is not honored.  I have observed many times that even though we have asked for 50 items, the graph api returns less then 50 (some time only 7/8) and sends a next link in the response. 

This causes us to make the API call again to fetch the changes and causes us to consume more API's.  

How is this supposed to work?

**Comment by k-tsoi** [comment]
@agrankur is this a onedrive for business account or onedrive personal account?
Could we also get a requestId and timestamp of the call.
