### ISSUE TITLE
Instruction Not Updated

### ISSUE THREAD

**Issue by goh-chunlin** [OneDrive/onedrive-api-docs#1419]
As shown in the screenshot below, the response returned from OneDrive now will have one more field called `resourceId` in the JSON. It will also have another field called `statusDescription` when we are copying a drive item which is a folder.

In addition, if the operation of copy fails, then the JSON will have another field called `errorCode`.

Finally, the "Retrieve the results of the completed operation" section is not finished by the author. Please look into it.

Thank you for your time attending to this. =)

![image](https://user-images.githubusercontent.com/8535306/103223194-a5a9f880-4960-11eb-8e96-7c57106fbc2f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccad95fe-ccea-c668-17c3-90781dc6b416
* Version Independent ID: cdd73909-251b-ed82-6a3b-778c7f5ce08a
* Content: [Calling long running actions - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/long-running-actions?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/long-running-actions.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/long-running-actions.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by k-tsoi** [comment]
@goh-chunlin please go here to view the documentation here https://docs.microsoft.com/en-us/graph/long-running-actions-overview?tabs=http
This documentation is more up to date.
We have logged a documentation bug for this issue.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
