### ISSUE TITLE
Error : invalidRequest - One of the provided arguments is not acceptable while downloading file content

### ISSUE THREAD

**Issue by shahtajk7** [OneDrive/onedrive-api-docs#1420]
We are getting 400 API error on some of the files when we try to download them using below API:

https://graph.microsoft.com/v1.0/users/<user-id>/drive/items/<item-id/content
API doc : https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http

Error:

"error": {
"code": "invalidRequest",
"message": "One of the provided arguments is not acceptable.",
"innerError": {
  "code": "badArgument",
...
Same API calls works for most of the files, but we are getting this error recently against multiple files. Kindly let me know What's the reason behind it? and how can we fix?

Request Id of one of the time we faced this error : 87542dd3-21f4-4d86-879f-5f833cb1b922
Timestamp : 2020-12-30T08:56:12.786754798+00:00

**Comment by ificator** [comment]
Hi @shahtajk7 are you still seeing this behavior or did it resolve on its own? Do you have any newer request ids we can take a look at?

**Comment by shahtajk7** [comment]
@ificator We got this error last time on December 30 on request Id shared above. Was this an issue earlier and is fixed now ?

This is the exact API call :
https://graph.microsoft.com/v1.0/users/d63eb74b-3604-4482-ad97-1f2e32dd61a3/drive/items/01JCKFNL3MXNXNLWHB6VBK2SHKBLYVZGMS/content

**Comment by ificator** [comment]
The data for that request definitely shows an issue, but it appears to have been isolated to a single server which has since been repaired. This is the first time I've seen this type of issue and so it's definitely rare, and we'll drill in further to make sure we understand the circumstances so that it won't happen again, but for now I think we can say your issue is resolved.

There was nothing wrong with how you made the call.

**Comment by shahtajk7** [comment]
@ificator Great, good to know.
Thanks for the prompt response.

**Comment by jerem99** [comment]
Hi,
I got the same issue now on many files.

**Comment by Sathieswar** [comment]
Hi,

I got the same issue today. This is my request id:
![image](https://user-images.githubusercontent.com/5582111/124568446-8edde480-de62-11eb-95ca-9dea35231180.png)

**Comment by ificator** [comment]
There was a regression detected and resolved yesterday for `download.aspx` calls for `App Permission` scenarios (i.e. requests authenticated without a user principal) but it was resolved 2021-07-06 18:30 UTC. It was unrelated to the original issue.
