### ISSUE TITLE
One Drive: unable to use a URL embeddable in an iframe

### ISSUE THREAD

**Issue by dionatanmelo1** [OneDrive/onedrive-api-docs#1421]
I am using the Microsoft Graph REST API version v1.0, my current plan is Microsoft 365 Business Basic and I am unable to use a embeddable URL from a PowerPoint file in the website's iframe and I do not receive any error returns from the Microsoft Graph API, I just can't see.

Endpoint: POST /me/drive/items/{itemId}/preview

Doc: https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0

![test-pptx](https://user-images.githubusercontent.com/26264022/103823958-cdc8e400-5051-11eb-9af6-bd32fca87c09.png)

**Comment by k-tsoi** [comment]
@dionatanmelo what argument is provided for the /preview call? if you were to navigate to the file in the web browser, does it the preview come up or does it give the same error?

**Comment by dionatanmelo** [comment]
Hi @k-tsoi, 
the error also occurs in the web browser.
But it was fixed by changing the version of the api to "beta" and changing the viewer to "office".

thanks

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
