### ISSUE TITLE
Nothing works, weird documentation

### ISSUE THREAD

**Issue by jtheis1993** [OneDrive/onedrive-api-docs#1425]
Nothing in here works. Have you tested this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd8a4b3-eb11-087a-2406-5979bd3931b3
* Version Independent ID: 39e9d7ef-e826-0096-2758-f6259741cd91
* Content: [Microsoft File Browser SDK (Preview) - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/react/?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/react/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/react/index.md)
* Product: **onedrive**
* GitHub Login: @KevinTCoughlin
* Microsoft Alias: **keco**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
