### ISSUE TITLE
file handler bug with files with '#' character in their names

### ISSUE THREAD

**Issue by s20blast** [OneDrive/onedrive-api-docs#1426]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

proper url passed 

#### Observed Behavior

(i posted same question on stackoverflow. https://stackoverflow.com/q/64365007/6097433)

I have an onedrive file handler
which runs well in most cases.

when I click file handler menu that I registered in manifest at azure management portal, from onedrive file list,
I get a request with json body contains appId, client, cultureName, domainHint, and items array.
And by sending a request to one of the url (it starts with "https://graph.microsoft.com") in that array with graph access token, I can get information of the file. (after here, I'll call it as "file info api".)

but, when the file has '#' character in it's name, file info api works differently.

if file name has only '#' characters or '#' characters followed by other characters ("##.xlsx" or "##test.xlsx"),
information of parent directory is responsed.

if file name has some characters except '#' character and followed by '#' characters ("test##.xlsx"),
file info api returns 302 found status code and location header direct "https://tenant_name-my.sharepoint.com/_vti_bin/client.svc/..."
and when I send request to "client.svc" with same graph access token, I get 401 unauthorized response.

I think regardless of file name, file info api should return proper response and 302 found response is a bug.
Should I just wait for bugfix or is there any workaround?

#### Steps to Reproduce

1. upload files that have '#' characters in their names to onedrive.
2. open any file by file handler

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
This is a bug we have currently tracked on our backlog

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
