### ISSUE TITLE
ODB: OneDrive API does not report 'sharepoint links' when using /delta

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#1427]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

When querying OneDrive API /delta or other applicable API's, SharePoint links should also be returned with viable data so that the links can be used and SharePoint Sites accessed 

#### Observed Behavior

Consider the following OneDrive Business top folder structure:
![Capture](https://user-images.githubusercontent.com/4956234/105406712-e86da080-5c80-11eb-9546-6146f818a59e.JPG)

When the following /delta query is called:
```
https://graph.microsoft.com/v1.0/drives/<driveId>/items/<itemId>/delta?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
```
no SharePoint Link item is returned:
```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
	"@odata.deltaLink": "https://graph.microsoft.com/v1.0/drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd/items/01WIXGO5V6Y2GOREDACTED/delta?select=id%2cname%2ceTag%2ccTag%2cdeleted%2cfile%2cfolder%2croot%2cfileSystemInfo%2cremoteItem%2cparentReference%2csize&token=MzslMjM0OyUyMzE7Mzs0ZTQ3OTgyMi0xZjFkLTRhYjUtOGVjMi1hOWU0ZjUzMWYxYzA7NjM3NDY4NTYyMDc5MDAwMDAwOzEzMzY1NzY0OTslMjM7JTIzOyUyMzA",
	"value": [
		{
			"@odata.type": "#microsoft.graph.driveItem",
			"fileSystemInfo": {
				"createdDateTime": "2019-12-07T15:02:58Z",
				"lastModifiedDateTime": "2021-01-21T20:03:18Z"
			},
			"folder": {
				"childCount": 4
			},
			"id": "01WIXGO5V6Y2GOREDACTED",
			"name": "root",
			"parentReference": {
				"driveId": "b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd",
				"driveType": "business"
			},
			"root": {},
			"size": 1054856683
		},
		{
			"@odata.etag": "\"{46BEA6A6-4F2B-4031-BE63-3B6510A6A96B},1\"",
			"@odata.type": "#microsoft.graph.driveItem",
			"cTag": "\"c:{46BEA6A6-4F2B-4031-BE63-3B6510A6A96B},0\"",
			"eTag": "\"{46BEA6A6-4F2B-4031-BE63-3B6510A6A96B},1\"",
			"fileSystemInfo": {
				"createdDateTime": "2020-09-24T22:17:02Z",
				"lastModifiedDateTime": "2020-09-24T22:17:02Z"
			},
			"folder": {
				"childCount": 0
			},
			"id": "01WIXGO5VGU27EMK2PGFAL4YZ3MUIKNKLL",
			"name": "random_files",
			"parentReference": {
				"driveId": "b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd",
				"driveType": "business",
				"id": "01WIXGO5V6Y2GOREDACTED",
				"path": "/drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd/root:"
			},
			"size": 184639808
		},
		{
			"@odata.etag": "\"{A642CEB7-DB67-4E0B-BC06-C91A54BE5633},1\"",
			"@odata.type": "#microsoft.graph.driveItem",
			"cTag": "\"c:{A642CEB7-DB67-4E0B-BC06-C91A54BE5633},0\"",
			"eTag": "\"{A642CEB7-DB67-4E0B-BC06-C91A54BE5633},1\"",
			"fileSystemInfo": {
				"createdDateTime": "2020-09-24T22:17:53Z",
				"lastModifiedDateTime": "2020-09-24T22:17:53Z"
			},
			"folder": {
				"childCount": 0
			},
			"id": "01WIXGO5VXZZBKMZ63BNHLYBWJDJKL4VRT",
			"name": "random_images",
			"parentReference": {
				"driveId": "b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd",
				"driveType": "business",
				"id": "01WIXGO5V6Y2GOREDACTED",
				"path": "/drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd/root:"
			},
			"size": 0
		},
		{
			"@odata.etag": "\"{54CBF5F7-3668-495C-A890-A4493E87C5A7},1\"",
			"@odata.type": "#microsoft.graph.driveItem",
			"cTag": "\"c:{54CBF5F7-3668-495C-A890-A4493E87C5A7},0\"",
			"eTag": "\"{54CBF5F7-3668-495C-A890-A4493E87C5A7},1\"",
			"fileSystemInfo": {
				"createdDateTime": "2020-09-24T22:18:33Z",
				"lastModifiedDateTime": "2020-09-24T22:18:33Z"
			},
			"folder": {
				"childCount": 0
			},
			"id": "01WIXGO5XX6XFVI2BWLRE2REFEJE7IPRNH",
			"name": "random_videos",
			"parentReference": {
				"driveId": "b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd",
				"driveType": "business",
				"id": "01WIXGO5V6Y2GOREDACTED",
				"path": "/drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_ReDaCtEd/root:"
			},
			"size": 0
		}
	]
}
```

#### Steps to Reproduce

1. Add a SharePoint link to 'My Files' using the 'Add shortcut to My files' function in OneDrive WebUI
2. Attempt to query OneDrive using /delta or other, and the newly created 'shortcut' to SharePoint drive is not available.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by abraunegg** [comment]
@JeremyKelley

Are you able to provide some insight / analysis here regarding this API issue?

**Comment by JeremyKelley** [comment]
Just want to make sure I'm understanding the question correctly (I think I read it wrong a few times and want to make sure I've got it right now).

When you call the delta query there's no item in the list that represents the "virtual" item that you created a link for in the target drive is that correct?

**Comment by abraunegg** [comment]
@JeremyKelley 
Correct - the 'link' as created on the OneDrive WebUI is not presented in any way via the API, thus, you cannot follow this link or item using the API, only a web browser.

**Comment by abraunegg** [comment]
@JeremyKelley
Any update here?

**Comment by adam2392** [comment]
@JeremyKelley is this updated yet, so that @abraunegg can make an update to allow syncing of shared folders added via "Add Shortcut"? This would be an awesome feature and frankly it's really cumbersome on OneDrive to not be able to sync data shared among my collaborators without having to create a dedicated SharePoint library.

**Comment by abraunegg** [comment]
@JeremyKelley , @k-tsoi 
Any update here?

**Comment by ethanjyx** [comment]
@JeremyKelley @k-tsoi any update here? Strongly need this feature

**Comment by ngoonee** [comment]
Sharepoint share (specifically in my case Teams sync) is necessary because most organisations have a huge number of Teams (for example as an educator I have a Team for each class, for each research project etc.) Each Team has one or multiple shared folders which are currently important (say, purchasing documents for a project or submitted powerpoint files for a presentation). This list of folders may change over time, from semester to semester.

Currently one of the best ways to handle this (and the way recommended by my IT personnel) is to 'add shortcut to OneDrive' for relevant folders. These shortcuts can then be moved in the onedrive interface to produce a proper folder structure (grouping all my research student work in a folder for example). This works well as long as I'm using the web interface. However due to this not being exposed properly in the API, I'm not able to sync these files automatically to my main (Linux) machine.

Please update the API to support this feature ASAP.

**Comment by abraunegg** [comment]
@JeremyKelley , @k-tsoi , @microsoft

Any update on fixing the OneDrive API so that SharePoint Links, as created in the web browser, as visible and usable via the API ?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Comment by kashiftahir** [comment]
Can you please try adding a prefer header to your request and see if that fixes your issue?

Prefer: Include-Feature=AddToOneDrive
