### ISSUE TITLE
Upload from a URL - OneDrive API - Available for OneDrive for b

### ISSUE THREAD

**Issue by haneef95** [OneDrive/onedrive-api-docs#1428]
Hi,

This is a really good feature.

Any timeline as to when this will be available on OneDrive for Business?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42443681-dd86-ce0c-587f-2336f965ebaf
* Version Independent ID: abcbaeba-560b-661d-0127-5c44d9089915
* Content: [Upload from a URL - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_upload_url?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_upload_url.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_upload_url.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment]
We don't currently have a timeline for adding this to OneDrive for Business.  You may want to go add a vote on our UserVoice for this feature:  https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform?category_id=194593
