### ISSUE TITLE
Downloading File - invalidRequest: One of the provided arguments is not acceptable.

### ISSUE THREAD

**Issue by saibaskaran57** [OneDrive/onedrive-api-docs#1430]
#### Category
- [x] Question
- [ ] Documentation issue
- [x] Bug

For the last 48 hours, we started to notice errors when trying to download file content from OneDrive with the error `invalidRequest: One of the provided arguments is not acceptable.`

Endpoint:
`_api/v2.0/me/drive/root:/<filepath>/content`

#### Expected or Desired Behavior

Should successfully get file content/provide more descriptive errors to investigate.

#### Observed Behavior

Details of the request sent:
1.  Date = 2021-01-24T11:51:49.4295856Z
2.  request-id = 9366a49f-c0bf-0000-69f5-0cc012b2212b
3.  SPRequestGuid = 9366a49f-c0bf-0000-69f5-0cc012b2212b
4.  Code = invalidRequest
5.  Message = One of the provided arguments is not acceptable

#### Question

Can we get some assistance to check on this issue as we don't have enough information on the errors to narrow down the issue? 
It's not happening to all the sharepoint instances but only to this specific instance. I'm creating this as a bug first as more occurrences is being observed.

Thank you.

**Comment by k-tsoi** [comment]
@saibaskaran57 is this still occurring?

**Comment by saibaskaran57** [comment]
Hello @k-tsoi,

Yeah, it is still occurring based on today results.

**Details of the new request issue:**
Date = 2021-02-01T15:01:13.5533703Z
request-id = 9804a79f-002f-b000-d1a6-ba0736702e85
SPRequestGuid = 9804a79f-002f-b000-d1a6-ba0736702e85
Code = invalidRequest
Message = One of the provided arguments is not acceptable

Any idea on what's the issue of this request?

**Comment by k-tsoi** [comment]
@saibaskaran57 could you also provide us the requestId and timestamp of the content API call as well.

**Comment by saibaskaran57** [comment]
@k-tsoi From the above comments, it includes the request-id & timestamp.

Date = 2021-02-01T15:01:13.5533703Z
request-id = 9804a79f-002f-b000-d1a6-ba0736702e85

**Comment by k-tsoi** [comment]
Looks like there is a bug, we are investigating internally.
We will update this thread when the issue has been resolved.

**Comment by PiotrekKrakowiak** [comment]
Can you try to add a User Agent string to the request? This resolved a very similar issue for us

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
