### ISSUE TITLE
Delta API returning next link which is returning same items again and again

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1431]
#### Category
- [ ] Question
- [ ] Documentation issue
- [ x] **Bug**

#### Expected or Desired Behavior

If there is no more delta items then it should return delta url instead of next url

#### Observed Behavior

Delta API is returning next link again and again with the same data
When calling /delta, the deltaLink is responding as per the following example:
`[DEBUG] deltaLink: https://graph.microsoft.com/v1.0/drives('66d53be8a5056eca')/items('66D53BE8A5056ECA!101')/microsoft.graph.delta(token='aTE09NjM3NDI5NzI5OTI.....`

Previously, this would respond as:
`[DEBUG] deltaLink: https://graph.microsoft.com/v1.0/drives/66d53be8a5056eca/items/66D53BE8A5056ECA!101/delta?select=id%2cname%2ceTag%2ccTag%2cdeleted%2cfile%2
`
#### Steps to Reproduce

1- Perform a /delta query for OneDrive Personal Accounts
2- Analyse the /delta response

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ificator** [comment]
Do you have the full url in the broken case? We need to see what query parameters are on it.

**Comment by shayan-brcm** [comment]
@ificator 
https://graph.microsoft.com/v1.0/drives('b!RbBMxB2BqkKp2_RPBGQzRKNOF6SZvR1Ih5Sl0fiP_Uq-SJD7kJB8RrA0F5s5DPP9')/root/microsoft.graph.delta(token='MzslMjM0OyUyMzE7MztmYjkwNDhiZS05MDkwLTQ2N2MtYjAzNC0xNzliMzkwY2YzZmQ7NjM3NDY4OTk3MTE4NDAwMDAwOzYwMzc0ODE0NTslMjM7JTIzZFJzUmVraFZ2YWxVQlElMjUyQnUlMjUyQlFtaFhVWXU2N3pabnp1RWVGJTI1MkJETVNYRW5aZyUyNTNEOyUyMzA')?$select=id%2cname%2csize%2csharepointIds%2cparentReference%2ccTag%2cfileSystemInfo%2ceTag%2ccreatedBy%2cfile%2cfolder%2cdeleted%2cshared%2cwebUrl&token=MzslMjM0OyUyMzE7MTtjNDRjYjA0NS04MTFkLTQyYWEtYTlkYi1mNDRmMDQ2NDMzNDQ7NjM3NDc4MTk5MjU5OTMwMDAwOzYwNDc2ODUzNTslMjNQYWdlZF9DVD0xOzE7YzQ0Y2IwNDUtODExZC00MmFhLWE5ZGItZjQ0ZjA0NjQzMzQ0OzYzNzQ3Mzc0OTY3ODkzMDAwMDs2MDQyMjg2MTI7JTIzZFJzUmVraFZ2YWxVQlElMjUyQnUlMjUyQlFtaFhVWXU2N3pabnp1RWVGJTI1MkJETVNYRW5aZyUyNTNEOyUyMzA

**Comment by k-tsoi** [comment]
@shayan-brcm is this still an issue ?
