### ISSUE TITLE
Sometimes plus signs (+) in files become spaces depending on which server we upload to

### ISSUE THREAD

**Issue by ncw** [OneDrive/onedrive-api-docs#1432]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I expect to be able to upload files such as `01 - 2 + 2 = 5.txt` correctly.

#### Observed Behavior

However about half the time the file is uploaded as

    01 - 2   2 = 5.txt

instead of

    01 - 2 + 2 = 5.txt

Looking at the `X-MS-Ags-Diagnostic` header, if I upload the file to this server

    X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"SliceC","Ring":"4","ScaleUnit":"002","RoleInstance":"AGSFE_IN_29"}}

Then it works fine, whereas if I upload to this server then it is bad and the `+` gets replaced with ` `

    X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"LN2PEPF00003362"}}

I don't get a choice about which server I upload to - it seems to be random.

Here is a log from a "good" upload including all HTTP transactions

[onedrive.ok.log](https://github.com/OneDrive/onedrive-api-docs/files/5919385/onedrive.ok.log)

And here is a log from a "bad" upload inclusing all HTTP transactions

[onedrive.bad.log](https://github.com/OneDrive/onedrive-api-docs/files/5919389/onedrive.bad.log)

#### Steps to Reproduce

I can reproduce this with rclone. First download rclone from https://rclone.org . Follow the instructions on creating a onedrive remote here: https://rclone.org/onedrive/

Create a directory called `source` with a text file called `01 - 2 + 2 = 5.txt`

```
$ tree source/
source/
└── 01 - 2 + 2 = 5.txt

0 directories, 1 file
```

Upload it to onedrive like this

    rclone copy -vv source onedrive:source --low-level-retries 1 --retries 1

Check the name after upload with this

    rclone lsf -R onedrive:source

Remove the directory to start the next test

    rclone purge onedrive:source

Add `-vv --dump bodies` to those rclone commands to see the http transactions.

This issue was reported in https://github.com/rclone/rclone/issues/4993

**Comment by k-tsoi** [comment]
@ncw does a file with the name already exist when you uploaded in in the ok and the bad request?

**Comment by ncw** [comment]
@k-tsoi 
> does a file with the name already exist when you uploaded in in the ok and the bad request?

No it doesn't. The directory was removed between runs.

**Comment by k-tsoi** [comment]
@ncw  we are following up with a partner team about this issue, We are investigating this.

**Comment by ificator** [comment]
Hi @ncw, we believe we tracked down what was going on here and have resolved it. Can you confirm that you're no longer seeing the issue?

**Comment by ncw** [comment]
@ificator I tried my test 20 times in a row with no failures, so it looks like you've fixed it - thank you :-) I've asked the original reporter to test too, I'll report back if they have problems.

**Comment by ncw** [comment]
My original reporter says it is closed for them too, so I'll close this ticket - thank you!

**Comment by ificator** [comment]
Thanks for confirming and closing!
