### ISSUE TITLE
Create Share Link API Broken

### ISSUE THREAD

**Issue by marcreicher** [OneDrive/onedrive-api-docs#1435]
Currently the `/drives/{driveId}/items/{itemId}/createLink` endpoint documentation says that the `scope` field is not required. Specifically, the documentation says:
```
If the scope parameter is not specified, the default link type for the organization is created.
```
However, when I supply the following request body the API errors:
```
{
    "type": "view"
}
```
Here is the specific error I get

```
{
    "error": {
        "code": "invalidRequest",
        "message": "Invalid request"
    }
}
```

Note that an empty request body of `{}` seems to work fine, and a request body specifying both the `type` and the `scope` also works fine. However, it seems that if only a `type` parameter is specified, then the API errors. There is no explanation for why this is happening.

I also want to clarify that until a few days ago, this request body actually worked fine
```
{
    "type": "view"
}
```

I believe Microsoft introduced a breaking change here, so that was either an accident or these docs need updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69601057-a846-2eea-33b4-9e1760981e88
* Version Independent ID: 5cbaae53-7d99-8075-609a-30d82c9ad0c8
* Content: [Share a file with a link - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online#creating-company-sharable-links)
* Content Source: [docs/rest-api/api/driveitem_createlink.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createlink.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ashtonhsu20** [comment]
I'm getting the same error message when I make this request. This seemed to happen gradually across clients across this past week

**Comment by k-tsoi** [comment]
@marcreicher  @ashtonhsu20 There was a change that was gradually being rolled out that caused this issue.
The rollout has been halted and this should no longer be occurring.

**Comment by SupSuper** [comment]
This issue is back. The documentation mentions the "scope" parameter is optional, but now omitting it results in this error:
"The default link settings cannot be used to create a sharing link without a scope. Scope must be specified"

Is this a bug, or do the docs need to be updated?

**Comment by k-tsoi** [comment]
Hi @SupSuper 
This behavior is expected.
The MS Graph documentation mentions "If the scope parameter is not specified, the default link type for the organization is created."
This means that we take the organization's defaulting link scope and use that to create a sharing link.
In the case or receiving this error message "The default link settings cannot be used to create a sharing link without a scope. Scope must be specified" this means that the organization's scope sharing link is not valid and a scope must be provided.
We will update the documentation to make this behavior more clear.
