### ISSUE TITLE
Folder resolve conflict option

### ISSUE THREAD

**Issue by ravi100k** [OneDrive/onedrive-api-docs#1437]
As per the resolve conflict option i can only rename or fail or replace the files at a location.
What if i want to resolve the conflict if there is a duplicate folder.

This https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#request-body
Explain to solve the file conflict.

**Comment by k-tsoi** [comment]
@ravi100k to clarify this is asking about creating a folder ?
the conflict resolution is only for resolving file names

**Comment by ravi100k** [comment]
@k-tsoi The use case is if we try to upload the file at some location for which we have a folder conflict as well.
In that the one drive is putting the file at the same location, it should also create a new folder if the folder already exist in one-drive.

**Comment by k-tsoi** [comment]
@ravi100k This would be a feature request, please log your request at User Voice. https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359590
The conflict resolution is only on file name.
