### ISSUE TITLE
driveItem: preview - How long does a short-lived embeddable URL last?

### ISSUE THREAD

**Issue by r-a-y** [OneDrive/onedrive-api-docs#1438]
I'm writing an app that allows users to embed their OneDrive items on external sites.

One problem I'm running into is supporting SharePoint and OneDrive for Business. When using SharePoint, `createLink` URLs cannot be used for embedding into an `<iframe>` due to cross-domain iframe restrictions. This is especially for user uploads (any miscellaneous file like an image, audio file or PDF), so I'm looking into the `preview` endpoint and am wondering how long a short-lived embeddable URL will last.

This information is missing from the documentation.

It would also be great if an `expires` property is added to the JSON response as well, so we know when we have to fetch another preview URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abaca550-f44d-455b-ef18-a284dd222dbc
* Version Independent ID: de0dfe46-b10b-5b53-59a1-37967fe2b1ab
* Content: [Get short-lived embeddable link for preview purposes - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_preview.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_preview.md)
* Product: **onedrive**
* GitHub Login: @kevinlam
* Microsoft Alias: **kevinlam**

**Comment by r-a-y** [comment]
Okay, I've answered my own question. The expiry time is five minutes.

**Comment by k-tsoi** [comment]
The preview URL is designed for short term download use, it should only last the length of time the user is viewing.
It should now be used for long term viewing

**Comment by r-a-y** [comment]
The docs should still be updated to list how long the preview lasts and
will expire. I'll submit a PR about this so developers are aware of the
time limit.
