### ISSUE TITLE
[Question] is there sign-user-out url in OneDrive for Business ?

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#144]
normal API has this method as following:
https://dev.onedrive.com/auth/msa_oauth.htm#sign-the-user-out
but it seems not exist in OneDrive for Business.
or just I missed it?
https://dev.onedrive.com/auth/aad_oauth.htm

thank you for help!

**Comment by rgregg** [comment]
I'm looking into this.

**Comment by joewutaiwan** [comment]
hi,@rgregg 
Is this url "https://login.windows.net/common/oauth2/logout " credible and reliable?
thanks

**Comment by rgregg** [comment]
Yes, the valid URL to use is `https://login.microsoftonline.com/common/oauth2/logout`.
