### ISSUE TITLE
Unicode string(japanese-string) use atob is getting error 

### ISSUE THREAD

**Issue by pthhung1997** [OneDrive/onedrive-api-docs#1441]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

When using Onedriver file picker, no error decode.

#### Observed Behavior
Current version: Opening Files with the OneDrive File Picker JavaScript SDK v7.2
I get exception like
```
[OneDriveSDK] Failed due to unknown error:  
         0: DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```
#### Steps to Reproduce

1. Use javascript open picker dialog with option:  
 ```
  OneDrive.open({
  clientId: "my-client-id",
         action: "share",
         multiSelect: true,
         advanced: {
             redirectUri: myRedirectUri
         },
         success: function(data) { /* success handler */ },
         cancel: function() { /* cancel handler */ },
         error: function(error) { /* error handler */ }
     });
```
2. Microsoft account login with the name as: `ABCD先生生０３`
3. Meet the bug
Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
