### ISSUE TITLE
Auth skipping (with accessToken) does not work on the OneDrive FilePicker javascript sdk (v7.2)

### ISSUE THREAD

**Issue by lucdems** [OneDrive/onedrive-api-docs#1444]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
OneDrive file picker should open directly on the user files when accessToken is specified in the advanced options object.

#### Observed Behavior
I want to open the OneDrive file picker bypassing the Auth part by providing an accessToken, as intendend in the [documentation](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#advanced-options).

So in the advance object I put the accessToken I already got in an other part of my app, I know the accessToken is valid because I can make working calls on the Graph API with it. As long as I use the Microsoft Graph API i shouldn't precise an endpointHint in the same advance object.

I tried first without specifying endpointHint, then I put _api.onedrive.com_, then directly the personal SharePoint endpoint for this account. None of this worked.

Also I tried to with and without specifying the loginHint and also the isConsumerAccount property.
Everytime the filepicker pop-up opens on the auth form but I want it to show directyly the file picker.

#### Steps to Reproduce
Follow the steps on this [documentation page](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online) and specify a valid accessToken in the advanced object.

**Comment by r-a-y** [comment]
There are a lot of tickets about this on Github. This isn't possible at the moment: https://github.com/OneDrive/onedrive-api-docs/issues/943#issuecomment-469916583

Documentation should be updated to avoid confusion.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
