### ISSUE TITLE
offline_access scope does not work properly with js onedrive picker v7.2

### ISSUE THREAD

**Issue by arsnyder16** [OneDrive/onedrive-api-docs#1445]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Passing offline_access should be a valid scope

#### Observed Behavior

When passing offline_access to the scopes under advanced the settings the file picker will close immediately because it will error with invalid_scope.

It appears that the picker incorrectly handles offline_access. There seems to be some code where it always prepends `https://graph.microsoft.com/` to any scope passed, but https://graph.microsoft.com/offline_access is an invalid scope. 

I notice that the picker automatically passes profile, openid. I would be nice if this were to also pass offline_access, or would properly support offline_access by not prepending https://graph.microsoft.com/. 

I fi don't pass offline_access and this is the first time an end user needs to consent to my application they won't be prompted to consent to offline_access causing me to force another interactive flow in order to gain that consent.

#### Steps to Reproduce
```
OneDrive.save({
    fileName            : 'NewFile',
    clientId,
    action              : 'query',
    viewType            : 'all',
    nameConflictBehavior: 'rename',
    advanced            : {
      scopes: ['Files.Read', 'Files.ReadWrite', 'offline_access']
    },
);
```
[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
