### ISSUE TITLE
Failed to upload small file with graph sdk

### ISSUE THREAD

**Issue by william8479** [OneDrive/onedrive-api-docs#1446]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _Submission Guidelines:_
> - Questions and bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please provide clear reference(s) to the specific file(s) or URL('s).
> - Remember to include sufficient details and context.
> - If you have multiple issues, please submit them as separate issues so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

> For the above list, an empty checkbox is [ ]. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.

#### Expected or Desired Behavior

upload file smaller than 4MB successfully

#### Observed Behavior

Date: Mar 03 2021 20:51:24 GMT+0800
request-id: "0188d74b-b8ed-4c00-8810-e51668638a04"

"error":{"code":"invalidRequest","innerError":{"client-request-id":"0188d74b-b8ed-4c00-8810-e51668638a04","code":"nameContainsInvalidCharacters","date":"2021-03-03T12:51:24","request-id":"0188d74b-b8ed-4c00-8810-e51668638a04"},"message":"Path (/LiveFolders//1K_file) contains invalid leading character."}

BTW, we can successfully upload file larger than 4MB.
#### Steps to Reproduce

Upload a new file 1KB file with the following request, where the size of 1K_file is 1KB.

PUT "https://graph.microsoft.com/v1.0/me/drive/root://1K_file:/content"

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@william8479 The double slash maybe the issue "//", can you try remove that and only have a singular "/" to see if that works

**Comment by william8479** [comment]
It works after we use singular "/" instead of "//".  Are there any changes to the API format?  We could upload the small file with "//" just several months ago. Anyway, thanks for your help.

**Comment by k-tsoi** [comment]
@william8479  glad to hear this is working, we will be closing this issue
