### ISSUE TITLE
Issue with content download for new app access on specific sp Sites Sites.Selected (Preview)

### ISSUE THREAD

**Issue by alphaz18** [OneDrive/onedrive-api-docs#1447]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

The expected behavior for Sites.Selected Graph Permissions is that calls to all objects work under the particular site assigned will be able to access all the resources. including downloading the content of the driveitems

eg. sites.read.all gives access to download content/downloadurl

#### Observed Behavior

With Sites.Selected permission on an app permissions, the app can sucessfully call the driveitems endpoint for sites
and list all the objects, and even get the pre-authed temp downloadurl. 

However, when you try to use that url, you get access denied. 
eg. /sites/<siteID>/Drive/root/children Correctly returns all the objects, including  @microsoft.graph.downloadUrl
but when you try to use the downloadURL in a browser, or try to hit the content endpoint it will error out or give access denied.

Headers for Successful DriveItem Call preceding the download:
  "Date": ["Wed, 03 Mar 2021 18:09:32 GMT"],
  "request-id": ["c8beadfe-2ef1-4084-b338-807a700dd3f5"]

Headers for Access Denied downloadurl attempt (behavior for /content is same, gives error) 

Date →Wed, 03 Mar 2021 18:10:37 GMT
SPRequestGuid →5bb7b09f-b045-b000-db7e-a850c9c3cd10
request-id →5bb7b09f-b045-b000-db7e-a850c9c3cd10

If api permissions Files.Read.All added to app, or Sites.read.All .. the downloadurl works and /content works. 
(this is what we don't want)

#### Steps to Reproduce

1. Create an App Registration
2. Give app api permissions to graph for sites.Selected
3. Use a http call to graph to any specific site /permissions endpoint to give newly created app id permissions. 
4. make call to site/drive/root/children using a secret/appid of the app registration 
5. use the downloadurl returned in step 4 to try to download a file. 
6. observe Access Denied.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@alphaz18 we are investigating this issue

**Comment by alphaz18** [comment]
thanks k-tsoi, I was wondering if there are any updates? thanks

**Comment by chackman** [comment]
Thanks for your patience. We're still looking into it.

**Comment by JeremyKelley** [comment]
We believe this should be working now.  Can you let us know if your app now works correctly with download (and upload) using the Sites.Selected permission?

**Comment by k-tsoi** [comment]
Closing this issue, it should be working now
