### ISSUE TITLE
Getting empty instead of returning a list of files from OneDrive

### ISSUE THREAD

**Issue by Uolary** [OneDrive/onedrive-api-docs#1450]
At the moment I am using this endpoint to get the user's files from OneDrive - `/me/drive/root/children`
However, the private user gets an empty value:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('bc*********************************f')/drive/root/children",
    "value": []
}
```
If I submit a request from accounts in organizational directory then I get the right answer.

I have verified tokens in jwt.io for a private account - https://i.imgur.com/S5BzmbS.png and account in organizational directory - https://i.imgur.com/yGq2RM7.png

Permissions - https://i.imgur.com/oMlqlqx.png

I used this [example](https://github.com/OfficeDev/msteams-tabs-sso-sample-nodejs) for request the token

**Comment by k-tsoi** [comment]
@Uolary The private account (first image) does not have the necessary scopes. You need at least File.Read.All

**Comment by Uolary** [comment]
Thanks, it helped.
