### ISSUE TITLE
Unable to fetch "@microsoft.graph.sharedChanged" attribute when using $select clause in delta query 

### ISSUE THREAD

**Issue by sumit-sarin** [OneDrive/onedrive-api-docs#1451]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

We use delta query for OneDrive business and SharePoint online. Our requests include “Prefer: hierarchicalsharing” and “Prefer: deltashowsharingchanges” headers. As per documentation we receive "@microsoft.graph.sharedChanged":"True" in the delta query response for items due to permission changes. 

Reference : https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#scanning-permissions-hierarchies

However when we use $select clause in delta query, the delta response does not include attribute "@microsoft.graph.sharedChanged”. 

Question:

Which property should we specify in $select query to fetch the "@microsoft.graph.sharedChanged" attribute in delta response for an item.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by Dethras** [comment]
Upon further investigation I found that the $select filter for this should be "oneDrive.sharedChanged", it was somehow mentioned in [Scanning permissions hierarchies](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#scanning-permissions-hierarchies) and upon trying it out, it worked, but I believe that this should be better documented.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
