### ISSUE TITLE
Must be authenticated to use '/drive' syntax

### ISSUE THREAD

**Issue by airbear** [OneDrive/onedrive-api-docs#1457]
Hi, I want to use graph api to get files from shared folder and upload new files there
Trying with graph explorer first, I created a new microsoft account and signed in into it in the explorer
I get /me with no problems, but /me/drive/sharedWithMe?allowexternal=true throws following: 
`{
    "error": {
        "code": "unauthenticated",
        "message": "Must be authenticated to use '/drive' syntax",
        "innerError": {
            "date": "2021-03-17T09:08:49",
            "request-id": "00fc2e8f-20fb-4507-9f81-1e7128cabceb",
            "client-request-id": "738f0ad0-c1aa-23e3-e609-463b4dcae8e5"
        }
    }
}`
what am I doing wrong here?

**Comment by JeremyKelley** [comment]
I tried this out with both a Business and Personal account and got results for the sharedWithMe endpoint.

First thing to do is check to make sure that Graph Explorer has the appropriate Files.* permission scope selected.  If it's only sending User.Read you won't be able to read files.  Permissions can be selected from the gear menu next to the signed in user name in Graph Explorer.

If that doesn't fix the issue you might try refreshing the page or fully logging out and logging back in to Graph Explorer.

**Comment by airbear** [comment]
thanks, that helped, I didn't have all the permissions checked 
401 error was confusing
