### ISSUE TITLE
Need Rest API for Microsoft.sharepoint.splistitementitycollection.getbyid

### ISSUE THREAD

**Issue by zeeshanzahid-elastica** [OneDrive/onedrive-api-docs#1458]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Question

We have tried but couldn't find Rest API for Microsoft.sharepoint.splistitementitycollection.getbyid. So We need the REST API so that we can use this method by web.

Thanks

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
