### ISSUE TITLE
Getting Invalid request on https://graph.microsoft.com/v1.0/drives/DRIVEID/items/ITEMID when DRIVEID and ITEMID is REMOTE

### ISSUE THREAD

**Issue by marta71** [OneDrive/onedrive-api-docs#1459]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _Submission Guidelines:_
> - Questions and bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please provide clear reference(s) to the specific file(s) or URL('s).
> - Remember to include sufficient details and context.
> - If you have multiple issues, please submit them as separate issues so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Documentation issue
- [X ] Bug

A user that has a file "Sharedwithme" can use https://graph.microsoft.com/v1.0/me/drive/sharedWithMe?allowexternal=true to get a list of these files. In the respons the DriveID and ItemID of the shared item (is returned). (A)

When the user use https://graph.microsoft.com/v1.0/drives/DRIVEID/items/ITEMID with DriveID and Item id from (A) the API returns "invalid respons" if the item is not from the users tenant, so getting access to the file if it is external returns error

#### Steps to Reproduce

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
