### ISSUE TITLE
required doc for symbols not allowed in name of file/folder and other details for OneDrive for Business

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#146]
there is no documentation for special symbols not allowed in name of file/folder for onedrive for business, no. of character limit for file / folder names and other stuff 

can we have this immediate

**Comment by ankit-ankuagrawal** [comment]
on portal it was stated following
![symbols not allowed portal](https://cloud.githubusercontent.com/assets/11455759/8339293/fef00130-1ad3-11e5-8087-8bfb82cb1b56.png)

but through API able to create folder
![folder getting created with symbol not allowed](https://cloud.githubusercontent.com/assets/11455759/8339308/1caa85a6-1ad4-11e5-8b73-f3e7a26361e2.png)

**Comment by rgregg** [comment]
I've updated the [File Encoding](https://dev.onedrive.com/misc/path-encoding.htm) topic to include this information.

**Comment by AndreiPashkin** [comment]
@rgregg, I wonder, how can I find this document currently?

**Comment by ificator** [comment]
This [addressing-driveitems](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/addressing-driveitems) page should be equivalent.
