### ISSUE TITLE
Bulk exporting SharePoint online file metadata (specifically DriveItem unique id, path, filename)

### ISSUE THREAD

**Issue by cmnicholas** [OneDrive/onedrive-api-docs#1461]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

**Question**

We have existing files in a SharePoint online site that we need to integrate with the Graph API (1.0) however the calls require the DriveItem item-id value

`GET /drives/{drive-id}/items/{item-id}`

Using the OneDrive file picker ( [https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online](url)) it's possible to extract this id manually when selecting files.

`{
      "webUrl": null,
      "value": [{
           "id": "01NJDWP4LK732UVFCO2ZCYLZF3QDARTUYT",
           "parentReference": {
                 "driveId": ""
           },
`

However we need to be able to bulk export the item-id (and file name and path) for all files in a SharePoint online site to be able to integrate the data with an existing Graph API solution (which depends on the id value).

Looking to find out how to achieve this either from a functionality within the SharePoint online site or PowerShell script.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
