### ISSUE TITLE
unable to override action permission scopes

### ISSUE THREAD

**Issue by jcharnley** [OneDrive/onedrive-api-docs#1462]
I cannot seem to override the scope permission through the onedrive sdk picker login

my object is

```
    let odOptions = {
      clientId: oneDriveApplicationId,
      action: "share",
      advanced: {
        scopes: [
          "openid",
          "profile",
          "User.Read",
          "Files.ReadWrite",
          "Files.ReadWrite.All",
        ],
      },
```

I know Action: share has  "Files.ReadWrite", "Files.ReadWrite.All", predefined but i cannot seem to add other scopes, I need it to match my msal login flow so it doesnt need to request access twice.

Error -

ation+%27d3plotviewer-app%27+asked+for+scope+%27Files.ReadWrite.All.All%27+that+doesn%27t+exist+on+the+resource+%2700000003-0000-0000-c000-000000000000%27.+Contact+the+app+vendor.%0d%0aTrace+ID%3a+a27b1a4f-6528-42bc-9a88-8a8d341a0900%0d%0aCorrelation+ID%3a+8cf507ac-9522-42fa-8d1b-382472a41387%0d%0aTimestamp%3a+2021-03-26+09%3a25%3a16Z&state=http%3a%2f%2flocalhost%3a8080_mvAfH

API permissions

<img width="1095" alt="Screenshot 2021-03-26 at 09 30 56" src="https://user-images.githubusercontent.com/25176118/112611629-fd4be900-8e15-11eb-8f43-84745dd379c0.png">

For some reason I can override the scopes but it wont allow me to add File permissions 

```
  let odOptions = {
      clientId: oneDriveApplicationId,
      action: "share",
      advanced: {
        scopes: [
          "openid",
          "profile",
          "User.Read",
          // "Files.ReadWrite",
          // "Files.ReadWrite.All",
        ],
      },

```

works but I lost Files permissions

**Comment by jcharnley** [comment]
everyone why cannot you define Files.ReadWrite.All in the onedrive scopes?? it clearly needs it and comes over as default but you cannot list it!! I need to make sure this is scoped within the token request...

**Comment by jcharnley** [comment]
@chackman Hey can this be revisited. the OneDrive picker 7.2 does not accept Files.ReadWrite.All. it will only access Files.ReadWrite and you cannot override this. it conflicts with my msal scopes as that has Files.ReadWrite.All, and requires the users to consent twice

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
