### ISSUE TITLE
Getting same number of items alot of times from delta API with next link

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1464]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

if there are 500 items that had changed then i am suppose to receive at least 100+ items per page

#### Observed Behavior

I am getting 7 events per page every time with the next link. Which make me call delta API more often
This is observed for deleted file events
#### Steps to Reproduce

Not any special steps to follow. 
upload bunch of files and then removed them after a while

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by shayan-brcm** [comment]
@JeremyKelley

**Comment by k-tsoi** [comment]
@shayan-brcm There is a known limitation of paging with deleted items in particular.
This should not be an issue for not deleted items.

**Comment by shayan-brcm** [comment]
@k-tsoi Thanks for your reply. Yes this is not happening for not deleted items. Is this documented any where?

**Comment by chackman** [comment]
This is not currently documented, but we'll backlog it for future consideration on a known issues list.

**Comment by shayan-brcm** [comment]
Thanks @chackman. As its a known limitation. Is there a best way to get a fixed number of items per delta page which could also include delta delete items? otherwise it will increase the number of delta API calls when deleted items arrived in a chunks of delta API calls with a few no of items

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
