### ISSUE TITLE
Convert file in jpg requires width and height information

### ISSUE THREAD

**Issue by coupalm** [OneDrive/onedrive-api-docs#1465]
GET /drive/items/{item-id}/content?format={format}
GET /drive/root:/{path and filename}:/content?format={format}

When using the jpg format as the download format, it requires a width and height. What is the synthax? 

{
    "error": {
        "code": "invalidRequest",
        "message": "jpg format requires width and height values",
        "innerError": {
            "date": "2021-03-27T02:22:22",
            "request-id": "1a56c7fa-5ae5-42f7-a784-1c90d1b2a7a0",
            "client-request-id": "4b0d0225-1532-6064-f194-f404a75830dd"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46acaeca-c7f2-1013-239e-93853818f3d7
* Version Independent ID: 8b42fae5-53c9-f8c3-b88f-f2a087b23f8c
* Content: [Convert to other formats - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_get_content_format.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get_content_format.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@coupalm Width and height need to be int values and should be passed in as part of the queryString.
This is a documentation bug, we will update the documentation with examples

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
