### ISSUE TITLE
Delta API response contain items which was uploaded years ago

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1468]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

For one of user's onedrive, we observe that the delta link contains a file which was created and updated more than 2 years ago. Also the item_id of that file is greater than the item_id of file which is created more recently

#### Expected or Desired Behavior
Next / Delta link should contain an item whose created time / modified time is greater than the one of its previous item

#### Observed Behavior

Next / Delta link contain an item whose item_id is for example 33455 and its created/modified time is years old and we have received another item before it on some page whose item_id was smaller than 33455 and have created/updated time of february 2021.

#### Steps to Reproduce
There is no particular steps to reproduce. This found randomly.

Is this case is known?

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
