### ISSUE TITLE
GET for Monitor URLs returns HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by rgregg** [OneDrive/onedrive-api-docs#147]
When trying to use the monitor URL returned from a long running operation, like upload from URL, I get an HTTP 401 Unauthorized error, even though I've added the correct Authorization header to the request.

This bug appears to have started a few days ago. There is no workaround available.

We're investigating a fix and will update this thread with more details.

**Comment by jack2060** [comment]
I am getting the same issue even with small file copy operations. Sometimes it's 401 else it's 500 Internal server error.

**Comment by ificator** [comment]
This issue was specific to monitor URLs resulting from providing a "@content.sourceUrl" on creation of a file, and it's now resolved.

If you're seeing other issues related to monitor URLs (e.g. from copy) please create another issue with as much detail as you have. Thanks!

**Comment by ankit-ankuagrawal** [comment]
@ificator @rgregg 
for onedrive business

received this error now also while creating a file
note: file name exceed limit 

PUT : https://mdm05-my.sharepoint.com/_api/v2.0/me/drive/items/01MFUQXWN6Y2GOVW7725BZO354PWSELRRZ/children/123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567123.docx/contentb

with valid accessToken
 

![untitled5](https://cloud.githubusercontent.com/assets/11455759/8382737/710fa868-1c52-11e5-8b59-7423b58fb978.png)

**Comment by ificator** [comment]
@ankit-ankuagrawal can you create a new issue for this? It definitely seems wrong, but it's not related to the monitor url issue we had.

**Comment by ankit-ankuagrawal** [comment]
@rgregg okay will do

**Comment by legsak1mbo** [comment]
We're seeing this again when performing a copy operation in OneDrive for business using the graph endpoints. The copy actually works but any GET to the monitor URL results in a 401 "Invalid issuer or signature".
