### ISSUE TITLE
No example how to specify a personal OneDrive folder driveItem as resource when posting to subscriptions

### ISSUE THREAD

**Issue by tzot** [OneDrive/onedrive-api-docs#1471]
#### Category
- [x] Question
- [x] Documentation issue

#### Expected or Desired Behavior

I have a registered application that requests permissions to read/write the approot (app folder) of a user in their personal OneDrive. The access is granted and the app can read/write various driveItems.

Based on the following info:
- Use the Microsoft Graph API to get change notifications
  https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0
- Set up notifications for changes in user data - Microsoft Graph | Microsoft Docs
  https://docs.microsoft.com/en-us/graph/webhooks#supported-resources
- Create subscription - Microsoft Graph v1.0 | Microsoft Docs
  https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#driveitem

**I would like to subscribe for updates to a specific folder (could be the approot folder or a subfolder), but I don't know how to specify the resource attribute.**  
I am testing various ways that should work, all of which I can **GET** in MS Graph, but they don't work as resource values.

#### Observed Behavior

Subscribing to the approot folder works: **POST** subscriptions … "resource": "drive/special/approot" …

‣ {"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity", "id": "xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx", "resource": "drive/special/approot",

Subscribing to any other folder, using various values as resource fails consistently:

‣ "message": "resource '/drive/root:/Apps/‹my_app_name›' is not supported.", … "request-id": "04bdc07d-055a-48b4-bcd2-61a06ec8826c",
‣ "message": "resource '/drive/items/xxxxxxxxxxxxxxxx!242' is not supported.", … "request-id": "0364709c-78da-4bfa-bd26-67bf41e3c8f3",
‣ "message": "resource 'drive/items/xxxxxxxxxxxxxxxx!242' is not supported.", … "request-id": "d3115baa-d19a-44c2-87aa-bc643f344fed",

[x]: http://aka.ms/onedrive-api-issues

**Comment by tzot** [comment]
Related queries:

- [How can I track changes to specific OneDrive folder under approot?](https://docs.microsoft.com/en-us/answers/questions/339022/how-can-i-track-changes-to-specific-onedrive-folde.html) at docs.microsoft.com
- [How can I track changes to specific OneDrive folder under approot?](https://stackoverflow.com/questions/66871556/how-can-i-track-changes-to-specific-onedrive-folder-under-approot) at stackoverflow.com

**Comment by k-tsoi** [comment]
@tzot are these requests prefixed with a "/me/" infront of the drive ?
We have created a item in our backlog to update the documentation with examples

**Comment by tzot** [comment]
@k-tsoi 
There is this folder:  
`GET /drive/items/7DCD75924995F1EC!242` or `GET /drive/root:/Apps/tzot OneDrive handler/Extra data`:

    {"parentReference": {"driveId": "7dcd75924995f1ec", "driveType": "personal", "path": "/drive/items/7DCD75924995F1EC!233:", "id": "7DCD75924995F1EC!233", "name": "tzot OneDrive handler"}, "cTag": "adDo3RENENzU5MjQ5OTVGMUVDITI0Mi42Mzc1Mjk4NzY4NzgyNzAwMDA", "lastModifiedDateTime": "2021-04-02T19:14:47.827Z", "name": "Extra data", "createdDateTime": "2021-03-16T13:48:55.97Z", "webUrl": "https://1drv.ms/f/s!AOzxlUmSdc19gXI", "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drive/items/$entity", "fileSystemInfo": {"createdDateTime": "2021-03-16T13:48:55.97Z", "lastModifiedDateTime": "2021-03-16T13:48:55.97Z"}, "lastModifiedBy": {"application": {"displayName": "OneDrive website", "id": "44048800"}, "user": {"displayName": "\u039a\u03bb\u03ac\u03bc\u03c0\u03b7\u03c2 \u039e\u03b5\u03bd\u03cd\u03c7\u03c4\u03b7\u03c2", "id": "7dcd75924995f1ec"}}, "eTag": "aN0RDRDc1OTI0OTk1RjFFQyEyNDIuMA", "createdBy": {"application": {"displayName": "OneDrive website", "id": "44048800"}, "user": {"displayName": "\u039a\u03bb\u03ac\u03bc\u03c0\u03b7\u03c2 \u039e\u03b5\u03bd\u03cd\u03c7\u03c4\u03b7\u03c2", "id": "7dcd75924995f1ec"}}, "folder": {"childCount": 4, "view": {"viewType": "thumbnails", "sortBy": "takenOrCreatedDateTime", "sortOrder": "ascending"}}, "id": "7DCD75924995F1EC!242", "size": 4754732}

(At this point, I don't care about protecting real IDs; these are the verbatim responses)

Attempt subscription using `/me/drive/items/7DCD75924995F1EC!242`:

`{"innerError": {"date": "2021-04-11T10:23:30", "request-id": "d2dd8c64-d738-4442-ac68-0fd570ff8e98", "client-request-id": "d2dd8c64-d738-4442-ac68-0fd570ff8e98"}, "message": "resource '/me/drive/items/7DCD75924995F1EC!242' is not supported.", "code": "InvalidRequest"}`

Attempt subscription using `/me/drive/root:/Apps/tzot OneDrive handler/Extra Data`:

`{"innerError": {"date": "2021-04-11T10:34:37", "request-id": "5793d1dd-1a22-445b-b59b-f40c081b512f", "client-request-id": "5793d1dd-1a22-445b-b59b-f40c081b512f"}, "message": "resource '/me/drive/root:/Apps/tzot OneDrive handler/Extra Data7DCD75924995F1EC!242' is not supported.", "code": "InvalidRequest"}`

**But I get a different message** when I attempt subscription using '/me/drive:/Apps/tzot OneDrive handler/Extra Data' (**no '/root'**):

`{"innerError": {"date": "2021-04-11T10:32:12", "request-id": "71e5009e-abe6-4b6a-8bd2-70b6a1650c69", "client-request-id": "71e5009e-abe6-4b6a-8bd2-70b6a1650c69"}, "message": "Specified resource is not supported for MSA requests.", "code": "InvalidRequest"}`

So: how do I subscribe to that folder of my personal OneDrive?

**Comment by tzot** [comment]
Does anyone need any more information from me?  Or maybe any clarifications about what the issue is here?

**Comment by MarcoEnxuto** [comment]
Hi, i do understand this is a API issue, but the we need clarification both on the docs and in the API. We also have an opened question on Microsoft Q&A which has not been responded yet.
Could you help us out? Interestingly no one has complained about this.
[https://docs.microsoft.com/en-us/answers/questions/339022/how-can-i-track-changes-to-specific-onedrive-folde.html](url)

**Comment by tzot** [comment]
I believe that I read somewhere that it is possible through the OneDrive API but it is not through the Graph API… now if only I could locate that article…

**Comment by MarcoEnxuto** [comment]
@tzot Don't bother. I found a way to manage that. It is posted on Q&A. Thanks anyway.

**Comment by tzot** [comment]
@MarcoEnxuto please provide a link for your solution :)

**Comment by MarcoEnxuto** [comment]
> @k-tsoi Any update on fixing this?

Still waiting. Take a look at my workaround.

**Comment by natsuozawa** [comment]
Yeah this is what I did. You can create a special `approot` folder for each application, so setting up a webhook in the approot is the least bad thing you can do in this case.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
