### ISSUE TITLE
Duplicate/skipped items in paginated directory queries

### ISSUE THREAD

**Issue by nickgaya** [OneDrive/onedrive-api-docs#1472]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

* When querying the contents of a OneDrive directory, each item should be returned exactly once.

#### Observed Behavior

* Pairs of files whose names differ by a 0 preceding a string of decimal digits (*e.g.* `a1b`, `a01b`) do not have a consistent sort order.  Sometimes the filename with the leading 0 comes first, sometimes second.

* If such a pair of files happens to span a pagination boundary, one file may be duplicated in the list and the other file omitted.

#### Steps to Reproduce

Here are request logs from a real-world example where the bug was observed: [rclone.log](https://gist.githubusercontent.com/nickgaya/6d8c325f9602c893f5bc7e100a411a69/raw/1af438b920c52444c60819f728b660d74422b6be/rclone.log). In this example, the directory contained two files called `d06b` and `d6b`.  The request logs show that `d06b` was returned twice, in two consecutive paginated requests, while the file `d6b` was not returned at all.

Note that this bug occurs intermittently and I have not found a way to reliably reproduce it in isolation.  The following steps are designed to create conditions where the bug may occur, but in practice I have not been able to trigger the bug by this method.  There may be some internal details of the system that influence the likelihood of the bug occurring.

1. Create a directory containing files whose filenames differ by leading 0s as described above.  The following bash script will generate 1024 such files:

        mkdir test
        for f in a{1,01}a{1,01}a{1,01}a{1,01}a{1,01}a{1,01}a{1,01}a{1,01}a{1,01}a{1,01}a; do
            echo 'test' >test/${f}
        done

2. Upload the test directory to OneDrive

3. Query the directory contents via the API using the `top` parameter to limit the number of results, and use the `@odata.nextLink` property of the results to retrieve the full list of files.

4. Verify whether all files are present in the list of results.

**Comment by k-tsoi** [comment]
@nickgaya could you clarify what API you are calling this is causing this issue, and please provide requestId and timestamps of failing requests

**Comment by nickgaya** [comment]
> could you clarify what API you are calling this is causing this issue, and please provide requestId and timestamps of failing requests

@k-tsoi This affects the OneDrive "list children" operation, `GET /v1.0/drives/{drive-id}/items/{item-id}/children` endpoint, when using the `top` parameter.

The log file linked in my [previous comment](https://github.com/OneDrive/onedrive-api-docs/issues/1472#issue-847128853) has full details.  Here is the link again: [rclone.log](https://gist.githubusercontent.com/nickgaya/6d8c325f9602c893f5bc7e100a411a69/raw/1af438b920c52444c60819f728b660d74422b6be/rclone.log)

> Could you please provide the following response headers:
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)
> Please provide as recent values as possible.

See the log file from the [previous comment](https://github.com/OneDrive/onedrive-api-docs/issues/1472#issue-847128853).

> Could you please describe the steps to reproduce the bug in sufficient detail for another person to be able to reproduce it?

See [previous comment](https://github.com/OneDrive/onedrive-api-docs/issues/1472#issue-847128853).

> Could you please provide sample requests and responses that illustrate the issue that you are encountering?

See [previous comment](https://github.com/OneDrive/onedrive-api-docs/issues/1472#issue-847128853).

> Could you please describe the behavior you expected to occur when performing the action?

See [previous comment](https://github.com/OneDrive/onedrive-api-docs/issues/1472#issue-847128853).

**Comment by JeremyKelley** [comment]
For sync'ing the contents of a drive we recommend using the Delta query API.  In Delta query if new results come in while you're paging through the new items should be appended to the results and you would get what you expect.

We think what's likely happening in your initial scenario is that the second item bumps the first item to the second page, and since you already got the first page you won't see the second item returned.  Delta would be more consistent in this scenario and is what we recommend for all "scanning" operations.  You should also check out our scanning guidance at https://aka.ms/scanguidance to get our best practices here.

**Comment by nickgaya** [comment]
Hi @JeremyKelley, thanks for your response!  In my use case, the drive is not being modified while the queries are occurring, so there are no new results coming in while paging.  Therefore I do not think the Delta API will solve this issue.

A key piece of evidence is that the bug only affects pairs of files whose filename differs by one or more 0s preceding a decimal digit.  This points to the inconsistent sort order as the root cause of the issue.

**Comment by nickgaya** [comment]
Here's what I think is going on, based on the evidence:

When sorting by filename (the default), files are sorted according to a [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order).  This is like an alphabetic sort, except groups of digits are sorted numerically.  This ensures that "file10" comes after "file2".  However, this leads to ambiguity when comparing "file01" and "file1".

This ambiguity can lead to problems in a distributed system.  Suppose our data store contains the following data replicated across instances A and B:

    A: ["file1", "file2", "file02"]
    B: ["file1", "file02", "file2"]

Suppose we are querying with page size 2.  If our first query happens to use replica A, and our second query uses replica B, then we may get results `["file1", "file2"], ["file2"]`.  Notice how one item is duplicated across a page boundary, while the other item is omitted — exactly what we observed in our real-world use case.

Of course, the real backend is more complex than this; this is just a simplified model demonstrating how the ambiguous sort order can lead to the observed behavior.

Based on this analysis, the issue can likely be solved by ensuring the sort order always produces a consistent ordering without "ties" or ambiguity.

**Comment by dnoji** [comment]
@nickgaya Are you still having this issue? We're getting similar results with this query.

**Comment by nickgaya** [comment]
@dnoji Yes, still having this issue.  Note that the bug I am reporting only affects pairs of files in the same directory whose filenames differ by a 0, leading to a non-deterministic sort order that causes inconsistent paging results.

If the symptoms you are observing are different then you may be experiencing a different issue.

If your issue is the same, it might be helpful to provide more context and request logs to help the Microsoft team understand the issue.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
