### ISSUE TITLE
Files.ReadWrite.AppFolder not supported on buisness accounts

### ISSUE THREAD

**Issue by mymindstorm** [OneDrive/onedrive-api-docs#1474]
[According to this](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online):

> To have your own app's folder, you must request either the Files.ReadWrite.AppFolder or Files.ReadWrite permission scope when getting an access token. For more details, see authentication. Note, Business OneDrive accounts do not currently support the Files.ReadWrite.AppFolder permission.

This seems to still be the case, a note should be added to the Permissions section of this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea09cc9-7668-ae89-2fee-cee17c0b34de
* Version Independent ID: 4a851b01-ed02-9cef-8c23-4408d148991c
* Content: [Understand differences between OneDrive API and Microsoft Graph - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences?view=odsp-graph-online#onedrive-personal-accounts)
* Content Source: [docs/rest-api/concepts/direct-endpoint-differences.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/direct-endpoint-differences.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@mymindstorm could you please clarify which page to add this note to.
you are welcome to contribute by creating a documentation pull request

**Comment by mymindstorm** [comment]
@k-tsoi I have opened a PR with the proposed changes.

**Comment by sakgoyal** [comment]
Will the API ever be updated to support business accounts?
