### ISSUE TITLE
[Question] OneDrive for Business, How long is the expire time of refresh token?

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#148]
Should the refresh toke last for 6 months?
Why I get this error, did I request any bad action?
It works so fine for weeks.
![default](https://cloud.githubusercontent.com/assets/12619781/8353890/7e70d096-1b75-11e5-8f3e-93b6df4c0d54.PNG)

thanks!

**Comment by rgregg** [comment]
The authentication and authorization system used with OneDrive for Business is Azure Active Directory (AAD), which has different expiration times. With AAD, any single refresh token is valid for 14 days. Every time you redeem a refresh token for a new access token, we also provide a new refresh token that is good for the next 14 days, so you need to store both the new refresh token and the access token each time you redeem a refresh token.

Beyond that though, AAD has a requirement that users log back into your app every 90 days. Thus, you can extend the 14 day refresh token expiration by requesting a new one multiple times, but after 90 days you have to go back through the sign-in experience.

**Comment by ankit-ankuagrawal** [comment]
@Ryan Gregg can u pls elaborate more this statement "Beyond that though,
AAD has a requirement that users log back into your app every 90 days.
Thus, you can extend the 14 day refresh token expiration by requesting a
new one multiple times, but after 90 days you have to go back through the
sign-in experience"

thank you

**Comment by rgregg** [comment]
Basically 90 days after the user first signed into your app, your app will be unable to redeem a refresh token for access tokens (you'll get an error) and you'll need to go through the OAuth 2 sign-in experience again.
