### ISSUE TITLE
Is there any invite limit?

### ISSUE THREAD

**Issue by paella55** [OneDrive/onedrive-api-docs#1481]
Hello,

first of all, I would like to thank you for the great documentation you guys created. Nevertheless, I have a question related to the [Invite API](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite?view=odsp-graph-online). I want to invite at least 5800 users to a file and One Drive API is always returning:

`504 gateway timeout`

I thought that maybe sending a unique request with that many users is unhandleable (makes sense), so I splitted it into chunks of 200 users (29 requests). However, still I am getting the same error. If I send only one invite of ± 30 users, it works. But this won't meet my project requirements.

The question is, is there any invite limit? If so, how can I workaround it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20835c68-99bc-a096-f40b-ed7108712eec
* Version Independent ID: bed66be5-c472-116c-1d42-09d2e0fc65eb
* Content: [Send an invite to access an item - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_invite.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_invite.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by chackman** [comment]
Could you please clarify whether this request is for OneDrive Personal or OneDrive for Business?

**Comment by paella55** [comment]
OneDrive for business

**Comment by chackman** [comment]
It is not recommended to share an item with that many unique users. Instead consider alternatives like company sharable links, sharing with groups, or something else to accomplish your scenario.
