### ISSUE TITLE
Page does not exist. 

### ISSUE THREAD

**Issue by corncup** [OneDrive/onedrive-api-docs#1482]
[Enter feedback here]

This page does not exist.

https://support.office.com/en-us/article/Introduction-to-content-types-and-content-type-publishing-e1277a2e-a1e8-4473-9126-91a0647766e5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f8f2b9-26e0-7f1d-d46e-86901f544118
* Version Independent ID: 2c0b93a4-45b7-3eba-6175-64675f2b32bf
* Content: [ContentType - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/contenttype?view=odsp-graph-online)
* Content Source: [docs/rest-api/resources/contenttype.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/contenttype.md)
* Product: **onedrive**
* GitHub Login: @daspek
* Microsoft Alias: **dspektor**

**Comment by chackman** [comment]
This looks like it was temporary, since the page resolves now.
