### ISSUE TITLE
Why call Actor Identity but not Actor? 

### ISSUE THREAD

**Issue by corncup** [OneDrive/onedrive-api-docs#1483]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db473b79-1a5b-91f9-741f-0c8745fcfd3a
* Version Independent ID: b01ffaa5-2a5b-5536-d779-b36d35a29c69
* Content: [Identity - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/identity?view=odsp-graph-online)
* Content Source: [docs/rest-api/resources/identity.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/identity.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by chackman** [comment]
Please clarify your question.
