### ISSUE TITLE
Open/Cancel button disappearing from filepicker UI

### ISSUE THREAD

**Issue by ti55987** [OneDrive/onedrive-api-docs#1485]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Expect the open/cancel button to appear

#### Observed Behavior

It works at times and suddenly it would stop working.
It only happens in business accounts. 

#### Steps to Reproduce
- Log into Microsoft by going through auth flow
- With the token obtained above, call https://graph.microsoft.com/v1.0/me?$select=mySite to get the targeted url for file picker endpointHint field.
- Call file picker open in JS SDK with obtained token and the site url.

The video below showing the problem:
https://share.getcloudapp.com/eDuj88jx

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by iacopocarlini** [comment]
I am facing the same issue. Any plans to fix it?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
