### ISSUE TITLE
Cannot download in jpg format when there are multiple pages in office documents

### ISSUE THREAD

**Issue by sshresthareach** [OneDrive/onedrive-api-docs#1486]
Is there a way to download a pptx and other office documents with multiple pages in jpg format?

Calling endpoint below only returns the first page as jpg image. Is it possible to get other pages as image as well?
https://graph.microsoft.com/v1.0/me/drive/items/{item-id}/content?format=jpg&width=300&height=300

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46acaeca-c7f2-1013-239e-93853818f3d7
* Version Independent ID: 8b42fae5-53c9-f8c3-b88f-f2a087b23f8c
* Content: [Convert to other formats - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_get_content_format.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get_content_format.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@sshresthareach This is not a scenario that is currently supported.
Please provide this feature request here https://aka.ms/m365dev-suggestions
