### ISSUE TITLE
Create Folder is giving 404 when we use folder name with unicode characters

### ISSUE THREAD

**Issue by ssapa** [OneDrive/onedrive-api-docs#1487]
#### Category
- [ ] Question
- [ ] Documentation issue
- [ X] Bug

While creating folder using graph api, I am observing 404 when the folder name ends with unicode chanracters.
Here is the Request URL :
https://graph.microsoft.com/v1.0/drives/b!GHbdSsDfn0etjdEUZ99tSa_C3Q1enhdNtwZJdddeTbOBncMjxs2KQo-9Gtb1j1Xc/root:/FolderForInvalidtestcases/TestUnicodeCharacter:/children

Request Body : 
{
    "folder": {},
    "name": "𝓱𝓲𝓳𝐅𝐆𝐚𝐛𝐤𝐥𝐦𝐷𝐸𝐹𝑃𝑄𝑅𝑔𝑖𝑦𝑧𝑨𝑱𝑲𝑳𝒇𝒈𝓱𝓲𝓳𝑅𝑔𝑖𝑦𝑧𝑨",
    "@microsoft.graph.conflictBehavior": "replace"
}

Response Headers : {
    "cache-control": "no-cache",
    "client-request-id": "bdd8ae74-c7ed-95ac-db2d-47854713ab65",
    "content-type": "application/json",
    "request-id": "cdba0026-b50a-467c-a0de-290b46a5bbaa"
}

Observed Response : 
{
    "error": {
        "code": "itemNotFound",
        "message": "The specified item name is incompatible with a similar name on an existing item.",
        "innerError": {
            "date": "2021-04-19T11:37:04",
            "request-id": "cdba0026-b50a-467c-a0de-290b46a5bbaa",
            "client-request-id": "bdd8ae74-c7ed-95ac-db2d-47854713ab65"
        }
    }
}

Expected Behaviour:  As we could able to create the folder name with above unicode chars in onedrive UI, expecting it to work through API as well.

**Note** : When I give conflict Behaviour= rename, I could able to create folder using api.

Thank you.

[ X]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@ssapa  could you clarify if this is on OneDrive for Business or OneDrive Personal.
Could you also provide a new requestId and Timestamp for us.

**Comment by ssapa** [comment]
@k-tsoi We are observing the issue for OneDrive for Business.

And here are the latest request ID details.
"client-request-id : f71ce391-4cc9-448f-9108-8462ddb887cb"
"Content-Type : application/json"
"request-id : 96971f7a-ca70-4f97-b061-2e1544558ada"
"Date : Wed, 26 May 2021 10:54:29 GMT"

Do let me know if you need any more info.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
