### ISSUE TITLE
[ODB] Cannot upload file with with leading "full-width" space

### ISSUE THREAD

**Issue by allen1759** [OneDrive/onedrive-api-docs#1488]
#### Category
- [X] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

In [Restrictions and limitations in OneDrive and SharePoint](https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-US&rs=en-US&ad=US) says

>Leading and trailing spaces in file or folder names also aren't allowed

We thought this restriction means "half-width" spaces.

Using **OneDrive for Personal** upload API:

As expected, file name with leading half-width space (encoding to `%20`) will be regarded as invalid request.

```
curl -X PUT 'https://api.onedrive.com/v1.0/drive/items/ITEM_ID:/%20test.txt:/content?%40name.conflictBehavior=replace' -H 'Authorization:Bearer XXX' --upload-file test.txt 
```
```
{
  "error": {
    "code": "invalidRequest",
    "message": "Path (/ test.txt) contains invalid leading character.",
    "localizedMessage": "XXX"
    "innererror": {
      "code": "nameContainsInvalidCharacters"
    }
  }
}
```

And file name with with leading full-width space (encoding to `%E3%80%80`) could be upload normally.

```
curl -X PUT 'https://api.onedrive.com/v1.0/drive/items/ITEM_ID:/%E3%80%80test.txt:/content?%40name.conflictBehavior=replace' -H 'Authorization:Bearer XXX' --upload-file test.txt 
```

#### Observed Behavior

Using **OneDrive for Business** upload API:

Same as ODP, file name with leading half-width space (encoding to `%20`) will be regarded as invalid request.

```
curl -X PUT 'https://xxx-my.sharepoint.com/_api/v2.0/me/drive/items/ITEM_ID:/%20test.txt:/content?%40name.conflictBehavior=replace' -H 'Authorization:Bearer XXX' --upload-file test_file.txt
```
```
{
  "error": {
    "code": "invalidRequest",
    "message": "The provided name cannot contain leading, or trailing, spaces."
  }
}
```

However, file name with with leading full-width space (encoding to `%E3%80%80`) will be regarded as invalid request just like half-width space.

```
curl -X PUT 'https://xxx-my.sharepoint.com/_api/v2.0/me/drive/items/ITEM_ID:/%E3%80%80test.txt:/content?%40name.conflictBehavior=replace' -H 'Authorization:Bearer XXX' --upload-file test_file.txt
```
```
{
  "error": {
    "code": "invalidRequest",
    "message": "The provided name cannot contain leading, or trailing, spaces."
  }
}
```

Is it a normal behavior? We thought that full-width spaces should not be considered as invalid space character.

If it is by design, will any full-width version of invalid characters (`~ " # % & * : < > ? / \ { | }`) be regarded as invalid request?

#### Steps to Reproduce

Upload with trailing full-width space file name.

```
curl -X PUT 'https://xxx-my.sharepoint.com/_api/v2.0/me/drive/items/ITEM_ID:/%E3%80%80test.txt:/content?%40name.conflictBehavior=replace' -H 'Authorization:Bearer XXX' --up
load-file test_file.txt
```

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@allen1759 We do not support leading or trailing spaces, or invalid characters of any form. These are not to be consider valid.
