### ISSUE TITLE
Random "InvalidAuthenticationToken: Unable to initialize RPS" have started appearing

### ISSUE THREAD

**Issue by ncw** [OneDrive/onedrive-api-docs#1489]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

No errors

#### Observed Behavior

Occasional  "InvalidAuthenticationToken: Unable to initialize RPS" where there used to be none.

#### Steps to Reproduce

The errors look like this - I believe the token to be valid

```
2021/04/20 10:40:01 DEBUG : HTTP REQUEST (req 0xc0008d4700)
2021/04/20 10:40:01 DEBUG : GET /v1.0/drives/f917c1b90389819/items/F917C1B90389819!123986/children?$top=1000 HTTP/1.1
Host: graph.microsoft.com
User-Agent: rclone/v1.54.1
Authorization: XXXX
Accept-Encoding: gzip
```

```
2021/04/20 10:40:01 DEBUG : HTTP RESPONSE (req 0xc0008d4700)
2021/04/20 10:40:01 DEBUG : HTTP/1.1 401 Unauthorized
Transfer-Encoding: chunked
Client-Request-Id: a1adaad0-5ffa-4539-8f1a-2c8d408a82d8
Content-Type: application/json
Date: Tue, 20 Apr 2021 15:40:01 GMT
Request-Id: a1adaad0-5ffa-4539-8f1a-2c8d408a82d8
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
Www-Authenticate: Bearer realm="", authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", client_id="00000003-0000-0000-c000-000000000000"
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"Central US","Slice":"E","Ring":"2","ScaleUnit":"002","RoleInstance":"DS3PEPF00001701"}}

130
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Unable to initialize RPS",
    "innerError": {
      "date": "2021-04-20T15:40:01",
      "request-id": "a1adaad0-5ffa-4539-8f1a-2c8d408a82d8",
      "client-request-id": "a1adaad0-5ffa-4539-8f1a-2c8d408a82d8"
    }
  }
}
```

The errors happen anywhere from very occasionally to about 50% of the time.

This was reported in several rclone forum threads:

- https://forum.rclone.org/t/invalidauthenticationtoken-unable-to-initalize-rps/23595/
- https://forum.rclone.org/t/problems-with-onedrive-personal-ransomware-protection/23590/
- https://forum.rclone.org/t/onedrive-sync-problem-invalidauthenticationtoken-unable-to-initialize-rps/22809/
- https://forum.rclone.org/t/rclone-errors-with-onedrive-sync/22792/

And also here

- https://docs.microsoft.com/en-us/answers/questions/360116/commicrosoftgraphhttpgraphserviceexception-error-c.html

I believe this to be a change or regression in the onedrive servers, but it might be that rclone is acting out of spec somehow.

Any help gratefully received.

**Comment by nickgaya** [comment]
Another place this issue was reported: https://github.com/black-roland/homeassistant-microsoft-todo/issues/57

**Comment by grncdr** [comment]
I also started seeing recently this with a commercial OneDrive integration I maintain. Would be happy to help with testing/specific request details if needed.

**Comment by k-tsoi** [comment]
@grncdr @ncw @nickgaya This looks like an issue with the Microsoft Graph
You can reach out to them there https://developer.microsoft.com/en-us/graph/support

**Comment by nickgaya** [comment]
@k-tsoi Hi, thanks for taking a look at this, however I don't see any useful information at the link you provided.  It seems the only ways to submit a ticket are for paid Azure subscribers or Microsoft 365 users with a premium support contract.  Is there any way to submit a bug report for developers or normal Microsoft 365 users?
