### ISSUE TITLE
folder name can have upto 207 character not 250 for onedrive business

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#149]
1) on this link it was been told  ( https://support.microsoft.com/en-us/kb/2933738 )
Folder names can have up to 250 characters

2) on office 365 portal it is showing 
![untitled6](https://cloud.githubusercontent.com/assets/11455759/8383009/996ad556-1c54-11e5-923e-ab48c5bf0a2c.png)

3) but the problem is tht when tried to create folder with 250 character it failed on both office 365 portal and through API

my count say "207" character are accepted on both office 365 and onedrive api

this string contains 208 character and this string failes
"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678"

there been alot of confusion, can some body comment on this

**Comment by rgregg** [comment]
Hey @ankit-ankuagrawal: This is super confusing and we'll see if we can get the document you linked updated.
