### ISSUE TITLE
How to remove specific user from sharelink?

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1492]
#### Category
- [x ] Question
- [ ] Documentation issue
- [ ] Bug

I have shared the file with two users, out of which one user does not belongs to organization. Now i want to remove that external user access from the file and keep the internal users continue to access the file. Please help me in finding an endpoint which does this job

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@shayan-brcm You can use the /revokeGrants Graph API to

**Comment by shayan-brcm** [comment]
@k-tsoi thanks. Can we use this in production as its in beta?

**Comment by k-tsoi** [comment]
@shayan-brcm 
Yes you will call this API on Graph Beta

**Comment by shayan-brcm** [comment]
@k-tsoi Thanks but as per documentation
`APIs under the /beta version in Microsoft Graph are subject to change. Use of these APIs in production applications is not supported. To determine whether an API is available in v1.0, use the Version selector.`
so its recommended to use beta endpoints on production

**Comment by k-tsoi** [comment]
@shayan-brcm we are still gather feedback on this feature.
If you have any feedback please feel free to provide while we evaluate publishing this feature to V1.0.
Beta are subject to change and it is generally not recommended for use in production environments.

**Comment by shayan-brcm** [comment]
Thanks @k-tsoi sure i will try this out and provide my feedback if any and i would love to have it in V1.0
