### ISSUE TITLE
Reg unclear information in filterable properties

### ISSUE THREAD

**Issue by AyshwaryaRamakrishnan** [OneDrive/onedrive-api-docs#1495]
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online#filterable-properties
Here, in the Note section, it mentions:
Note: In OneDrive for Business, SharePoint Online and SharePoint Server 2016, filtering support only name and url properties.

audio
createdDateTime (for gt, ge, lt, le)
deleted
file
folder
image
lastModifiedDateTime (for gt, ge, lt, le)
video

Does this mean only name and url are supported? What about the list of properties? 
Is it supported or not - the wordings are not clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b69523-6e05-fc2e-57c9-4ee861c8e0b2
* Version Independent ID: 05845d47-c93a-7b9b-cb65-e18826cc5116
* Content: [How to filter items - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/filtering-results.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/filtering-results.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by chackman** [comment]
Yes, they are. If you are requesting support for specific filterable properties please suggest using UserVoice.

**Comment by chackman** [comment]
Up to date information is available through the Microsoft Graph developer center
https://docs.microsoft.com/en-us/graph/query-parameters
