### ISSUE TITLE
In angular js onedrive V7.2 is not working

### ISSUE THREAD

**Issue by shoeb168** [OneDrive/onedrive-api-docs#1496]
When i onedrive V7.2 in angularjs then i could not be getting onedrive screen after access token screen, but the same flow is working in onedrive V7.0

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
