### ISSUE TITLE
How to set dynamic redirect URI?

### ISSUE THREAD

**Issue by hassanrazadev** [OneDrive/onedrive-api-docs#1498]
We are using **OneDrive File Picker JavaScript SDK v7.0** to allow users to pick files from one drive. The page the will use the **File Picker** will have a URL like `http://<SERVER>/upload-policy-page/{ID}` where `{ID}` is dynamic. How can I set this type of redirect URI in app registration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1abe8106-640d-2ebc-9536-ff4fa69ebcaa
* Version Independent ID: e06c2570-70ed-b0fd-4f19-239d0b537cab
* Content: [Opening Files with the OneDrive File Picker JavaScript SDK v7.0 - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v7/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v7/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v7/open-file.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by Maxorenko** [comment]
@hassanrazadev We have the same problem, except our redirectUri has different tenants like: [someTenant].somehost.com. Have you found the solution yet?

**Comment by thenaim** [comment]
any news?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
