### ISSUE TITLE
File not found for many minute after rename

### ISSUE THREAD

**Issue by Loppone** [OneDrive/onedrive-api-docs#1499]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

After renaming a file on SharePoint I would like to be able to search the file with the new name

#### Observed Behavior

I renamed a file directly on SharePoint.
I perform a search on Graph Explorer, but I couldn't find the new file name for many minutes.

#### Steps to Reproduce

1. Rename "enel.pdf" file to "enel1.pdf" on SharePoint
2. https://graph.microsoft.com/v1.0/drives/<my_drive_id>/search(q='{enel1.pdf}')

Thank you.

**Comment by k-tsoi** [comment]
@Loppone The index takes some time to propagate through.
We recommend looking up items using the Id rather than searching for the item using the name.
