### ISSUE TITLE
AsyncOperationStatus status strings mismatch

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-api-docs#15]
In the document page http://onedrive.github.io/resources/asyncJobStatus.htm, 
the status strings are like "notStarted", but what is really returned can be "NotStarted" as in 
```javascript
{
'status': 'NotStarted', 
'statusDescription': 'Completed 0/0 files; 0/0 bytes', 
'percentageComplete': 0.0, 
'operation': 'ItemCopy'
}
```
This may be a typo and better be corrected for consistency.

(BTW, I have been waiting for one hour for this ItemCopy thing to complete, but it hasn't even started...)

**Comment by ificator** [comment]
Fixing it now.

**Comment by ificator** [comment]
And it turns out the fact that the copy is stuck is another bug, so thanks for reporting that as well!

**Comment by ificator** [comment]
The casing issue with the "status" field should now be resolved.

**Comment by ificator** [comment]
Please reactivate if issue still exists for you.
