### ISSUE TITLE
while creating a file (file name length exceede) receiving 401 (accessToken is valid) "onedrive for business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#150]
trying to create a file with name of file exceeding in length 

PUT : https://mdm05-my.sharepoint.com/_api/v2.0/me/drive/items/01MFUQXWN6Y2GOVW7725BZO354PWSELRRZ/children/123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567123.docx/content

with valid accessToken

response: was receiving 401 in http status error code, but string was displaying error correctly  and error was not in std json format 

![untitled5](https://cloud.githubusercontent.com/assets/11455759/8383100/450b942c-1c55-11e5-8fd6-37fe0bcc716f.png)
 
note: when accessToken become invalid still receiving same error (all same), json was not using anything abt accessToken got expired and stuff

**Comment by ificator** [comment]
The root cause of this one actually appears to be the same as https://github.com/OneDrive/onedrive-api-docs/issues/189

**Comment by ificator** [comment]
This appears to now be resolved. I'll open another bug to track the URL limit.
