### ISSUE TITLE
Reference to deprecated Discovery API

### ISSUE THREAD

**Issue by 1klap** [OneDrive/onedrive-api-docs#1500]
[Enter feedback here]
Step 3 refers to the deprecated Discovery API, which is no longer available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d44c1c-08a2-3cbf-90e4-497a9a98d7b6
* Version Independent ID: c51d78c1-3982-a9fa-819f-a48852a60575
* Content: [Using Azure Active Directory to sign-in - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/aad-oauth.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/aad-oauth.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@1klap  Thank you for pointing this out, we need to clean this up.
We recommend moving to use Microsoft Graph instead.

**Comment by toby11** [comment]
how difficult is it to keep the offical documents up to date - you can spend ages trying to get something working only to findout that something has been deprecated!!

2 years ago this was logged!
