### ISSUE TITLE
Note: Activities is in a limited Preview and not yet available to all tenants.

### ISSUE THREAD

**Issue by yaniv-intlock** [OneDrive/onedrive-api-docs#1501]
Hi,

Listing OneDrive activities is in preview as mentioned here -
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/activities_list?view=odsp-graph-online
_Note: Activities is in a limited Preview and not yet available to all tenants._

Any estimate on when this is going to be available?

#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

**Comment by k-tsoi** [comment]
@yaniv-intlock we are doing some internal investigation on this, thanks for you patience
