### ISSUE TITLE
Pingar - Handle throttling issues around metadata publishing

### ISSUE THREAD

**Issue by TarangSoni** [OneDrive/onedrive-api-docs#1502]
Customer is using Pingar to automatically tag and categorize content. 

**Problem Statement:**
We need some guidance to handle throttling issues around metadata publishing routines. The metadata publishing speed is very slow as compared to our scanning workloads while using the Pingar tool. It becomes worse with OneDrive for Business libraries. Lately, we have also noted that MS might have taken out the support for some of the field types (Managed Metadata) for OneDrive for Business. This also compounds our problem as we are unable to access latest info from MS documentation.
 
We are out to determine if metadata publishing speeds are as designed, if so we can put a closure to the ticket, else we would require your guidance implement changes.

**Comment by k-tsoi** [comment]
@TarangSoni The managed metadata column is currently available in Graph beta https://docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta
We expect it to make its way to Graph V1.0 soon.
please provide requestID and timestamps of the throttled request

**Comment by TarangSoni** [comment]
I have requested this information from the customer. I will share it as soon as I find more.

Regards,
Tarang

**Comment by TarangSoni** [comment]
Is there a way that we can get on a call with the team at Pingar to understand the issue better?

Thanks,
Tarang

From: Tarang Soni
Sent: Monday, 31 May 2021 3:14 PM
To: OneDrive/onedrive-api-docs ***@***.***>; OneDrive/onedrive-api-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OneDrive/onedrive-api-docs] Pingar - Handle throttling issues around metadata publishing (#1502)

I have requested this information from the customer. I will share it as soon as I find more.

Regards,
Tarang

**Comment by TarangSoni** [comment]
Close
