### ISSUE TITLE
"createUploadSession" issue uploading large files into Document Library -> item created but no file

### ISSUE THREAD

**Issue by aaclage** [OneDrive/onedrive-api-docs#1504]
#### Category
- [X] Question
- [ ] Documentation issue
- [X] Bug

Article "[Upload large files with an upload session](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)":
https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0

This is a code issue that could need clarification and recommendation regarding the best practices and validate if is a bug or not. 
I am able to upload Large files by chunk using SharePoint Online, React and Microsoft Graph Web Service, no problem there.
**When issue appear:**
When uploading large file using Graph API and Browser and in the middle of upload process, internet connection is lost, click refresh "F5" or computer is turned off and upload stay in limbo environment .
**The following behavior happen:**
Access to Document Library and see a new item was created but no File, when i access to Library View nothing is there. 
**Info**:
I understand it's because the session is not close and we could use the "delete the session" if i still have the upload session url as described in support article, 
**Question**:

- It's possible to identify open Uploadsessions that can be closed "deleted". 
- What to do in document library that item created but without file, there is any defined command to removed it to keep the integrity of Library content?
- What would be the Best practice to manage a situation like this "Lost Upload Sessions" and items without files in Document Libraries?

Sample:
Access to View count of Library and appear with 23 items (all lost internet connection in the middle of upload for testing purpose).
![image](https://user-images.githubusercontent.com/8522348/120932494-5aa5c580-c6f6-11eb-8b11-7c1fbe7bded7.png)

When access to View of Files appear Empty and no files
![image](https://user-images.githubusercontent.com/8522348/120932517-78732a80-c6f6-11eb-82d7-2b7a2b6b1ca4.png)

When used Powershell for further investigation the Library will display the item entries but empty of files.
This items can be deleted using the PowerShell with exception of header "deferCommit: true".

#### Expected or Desired Behavior

User upload a large file and for some reason connection is lost, if file is not fully uploaded a empty item should not be created in Document Library.

#### Observed Behavior
```
 const sessionOptions = {
      item: {
        "@microsoft.graph.conflictBehavior": "rename",
      },
    };
```

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by aaclage** [comment]
More additional information:

Code can be found here:
https://github.com/aaclage/SPFX-Sample/blob/main/react-onedrive-finder/src/webparts/Services/GraphService.ts 

Library has 3 items that fail (i close connection in the middle) to see how the Library behaved when session fail.
Access to Library and appear empty.
Access to custom feature that upload Large File "this sample has 14 MB" and drag and drop upload.
I close the connection using refresh and access to library and appear 4 items and empty of Files.

PS: If i don't close  the connection everything goes ok what is expected, this use case if for sessions that are lost.

Here are the steps 
![image](https://github.com/aaclage/SPFX-Sample/raw/main/MGTDragDropPoC5.gif)

**Comment by k-tsoi** [comment]
@aaclage Currently there is no way for you to check what session you currently have open.
We expect customers to keep the list of open sessions themselves.
Temporary files and their accompanying upload session are automatically cleaned up after the expirationDateTime has passed. Temporary files may not be deleted immedately after the expiration time has elapsed.
