### ISSUE TITLE
issues with file length name"onedrive for business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#151]
in onedrive business file can be created using PUT method, in which we have to give file name with the uri

1) in documentation it was said the file name length "In SharePoint Online, file names can have up to 256 characters"

2) on the portal was said 260 url length
![untitled6](https://cloud.githubusercontent.com/assets/11455759/8383423/bf5cf746-1c57-11e5-8305-dd46df207eeb.png)

3) but when trying to create through the api it was taking upto 291 URL length, and file was getting created. Beyond the call was failing with error as follows and the error is not acc to json format
![untitled5](https://cloud.githubusercontent.com/assets/11455759/8383477/460ebc34-1c58-11e5-9055-c5725845fdd7.png)

if the limit of the URL length is upto 291, then file name length will be coming in between 160 to 180 length

**Comment by rgregg** [comment]
How is this and #149 different? Both seem to be issues regarding the length of filenames that are allowed for OneDrive for Business. Is there something that makes them separate issues?

**Comment by ankit-ankuagrawal** [comment]
149 was abt folder name length

and this is for file

moreover both have differerent api call to create file

for folder creation name goes in json body, for file goes in URL so

**Comment by rgregg** [comment]
Got it. I'll see if we can provide better guidance around filename length. When we have the full set of APIs implemented for OneDrive for Business, you'll be able to use either multipart/post, data URIs, or large file upload to upload a file without the URL length limitation getting in the way of the filename.
