### ISSUE TITLE
The attempted operation is prohibited because it exceeds the list view threshold.

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1510]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

We are trying to upload a file to one of the site folder. But at time of making API call we are getting error code 500 with description
`"error":{"code":"-2147024860, Microsoft.SharePoint.SPQueryThrottledException","message":{"lang":"en-US","value":"The attempted operation is prohibited because it exceeds the list view threshold."}}}`
API we used: `https://abc.sharepoint.com/sites/abctsite/_api/web/getfolderbyId(@v)/files(@x)?@v='3dfdbc84-4cd6-4bbe-bff1-2551bb1e93b5'&@x='fjBdPLNG.txt`
How can we resolve this? any workaround?
Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@shayan-brcm could you please provide requestID and timestamp(UTC) of the failing request

**Comment by shayan-brcm** [comment]
@k-tsoi 
Please find the request details below
RequestID: a9cfe69f-f0df-0000-a4e7-47b653478854 
TimeStamp: Wed, 18 Aug 2021 19:47:20 UTC

**Comment by k-tsoi** [comment]
@shayan-brcm  This issue is occurring due to the list being very large.
I would recommend reading this troubleshooting doc https://docs.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/items-exceeds-list-view-threshold
