### ISSUE TITLE
Is this approach depreciated?

### ISSUE THREAD

**Issue by ghufs** [OneDrive/onedrive-api-docs#1513]
This document says it outlines how to access OneDrive for business, but it seems out-dated, based on this: https://developer.microsoft.com/en-us/graph/blogs/upcoming-deprecation-of-discovery-service-api/ 

What is the correct approach for getting access to **OneDrive for Business?**
Needs more clarity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d44c1c-08a2-3cbf-90e4-497a9a98d7b6
* Version Independent ID: c51d78c1-3982-a9fa-819f-a48852a60575
* Content: [Using Azure Active Directory to sign-in - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/aad-oauth.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/aad-oauth.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@ghufs Yes the discovery service is deprecated, please use Microsoft Graph to access OneDrive for business
https://docs.microsoft.com/en-us/graph/
