### ISSUE TITLE
Add to Common Tasks

### ISSUE THREAD

**Issue by tzot** [OneDrive/onedrive-api-docs#1515]
Please add an example of a Common Task for: “subscribe to changes of a folder under the App folder (not the App folder itself)”.
App folders exist on Personal OneDrive drives so we're supposed to be able to subscribe to any subfolder of the App folder, but it is neither obvious nor documented anywhere how to specify the subfolder resource in the subscription request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd45832d-84c9-36e7-5c06-77eb70e1b55a
* Version Independent ID: 0ca96ced-7304-2ea0-08fa-b2a3f22afa1a
* Content: [What is an App Folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/special-folders-appfolder.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/special-folders-appfolder.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
