### ISSUE TITLE
Reset File Handler Cache not work

### ISSUE THREAD

**Issue by laurensmartz** [OneDrive/onedrive-api-docs#1516]
[Enter feedback here]

I use postman to request the api: https://{{tenant}}-my.sharepoint.com/_api/v2.0/drive/apps?forceRefresh=1,

and I get the response with status 200, and I clear the browser cache for onedrive.

I reopen the onedrive and use file handler to open a pdf file, the fileHandler url is still the old value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18ba6d3-b187-12d6-2e08-418b0746ac5b
* Version Independent ID: dd01f1c1-7e26-39e2-9e06-afd3305c65e7
* Content: [Reload OneDrive File Handlers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/reset-cache?view=odsp-graph-online)
* Content Source: [docs/file-handlers/reset-cache.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/reset-cache.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by laurensmartz** [comment]
Any update?

**Comment by k-tsoi** [comment]
@laurensmartz  how often do you try to call the tenant admin reset?

**Comment by dvd95** [comment]
Hi,
I am facing the same issue. I am have tried adding, removing the FileHandler, it's not working. Also, after changing(URL) in the existing FileHandler, the url still points to the old URL. The existing FileHandlers are working fine but no new changes are picked.

In response of the forceRefresh url,
I am getting this: 
request-id: c8b7e69f-b0c4-0000-b3c7-221b6f1a890a
sprequestguid: c8b7e69f-b0c4-0000-b3c7-221b6f1a890a

**Comment by raneaaditya98** [comment]
Is there any update on this ?
I am also facing same issue, in my tenant.

**Comment by ificator** [comment]
I realize this issue was created before https://github.com/OneDrive/onedrive-api-docs/issues/1526, but that's the one I started putting some information in so I'm going to use that to track the "file handlers not updating" issue.
