### ISSUE TITLE
Can not get file which having - glimmer marks - One Drive - Using Graph Search API

### ISSUE THREAD

**Issue by hardikthakkar54** [OneDrive/onedrive-api-docs#1517]
Search for a Drive Items (One Drive) - Using below API. 

[](https://graph.microsoft.com/v1.0/me/drive/root/search(q='finance')?select=name,id,webUrl)

Not getting items which includes - Glimmer Marks - need solution for that

![Screenshot 2021-07-22 at 6 27 07 PM](https://user-images.githubusercontent.com/86776855/126642716-98fa30c7-d886-4232-af92-675d166f5898.png)

Thanks in Advance!

**Comment by k-tsoi** [comment]
@hardikthakkar54 
Thanks for contacting us.
This appears to require more investigation.
If you have a support contact could you please work through them to file a support case for us to do further investigation on this issue.
