### ISSUE TITLE
OneDrive File Picker not authenticating with US national cloud

### ISSUE THREAD

**Issue by moos** [OneDrive/onedrive-api-docs#1518]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

A OneDrive API app has been created following the guidelines in [National cloud deployments](https://docs.microsoft.com/en-us/graph/deployments).  We're using the OneDrive.js SDK to initiate a File Picker session. We should see a login popup at `https://login.microsoftonline.us/common/oauth2/v2/authorize?...` (note **.us**) and be able to login.

#### Observed Behavior

However the login popup goes to `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?...`  (note **.com**) with the following  message:
```
Sign in
Sorry, but we’re having trouble signing you in.

AADSTS700016: Application with identifier '5b[snip]2e' was not found in the directory 'fa7[snip]e1'. This can
 happen if the application has not been installed by the administrator of the tenant or consented to by any
 user in the tenant. You may have sent your authentication request to the wrong tenant.
```

#### Steps to Reproduce
n/a

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by moos** [comment]
Similar issue #1034 for German cloud.  However the patch suggested there did not work.

**Comment by moos** [comment]
**Update**: the patch does work (partially). It goes to the "Sign in" page - after entering an email address, it says "Taking you to your organization login..." and lands on `https://login.microsoftonline.com/common/OAuth2/authorize?...` or `https://login.live.com/oauth20_authorize.srf?...` (both **.com**) depending on the email entered.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
