### ISSUE TITLE
Accept-Encoding header not respected for file download requests

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#152]
I am developing an app to work with OneDrive for Business using the APIs
To download a file, I am making the file download API call, with Accept-Encoding as "identity", and so I expect the response not to be chunked and have a Content-Length header (which is required to show download progress)
But even on sending Accept-Encoding as "identity", the client is receiving a response with Content-Encoding as "chunked" and consequently no Content-Length response header.

Note: The APIs for OneDrive Personal respect the Accept-Encoding identity header and send a Content-Length header in response

**Comment by rgregg** [comment]
Looks like I haven't published this change, but there's an open issue around this that will be mentioned in the release notes:

```
OneDrive for Business always sends download requests as chunked-encoded
transfers. Even if you send the `Accept-Encoding: identity` header for the
request the response will use chunked encoding.
```
