### ISSUE TITLE
FileHandler is not registering or updating.

### ISSUE THREAD

**Issue by dvd95** [OneDrive/onedrive-api-docs#1524]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

I am have tried adding, removing the FileHandler, it's not working. Also, after changing(URL) in the existing FileHandler, the url still points to the old URL. The existing FileHandlers are working fine but no new changes are picked.

I have followed the doc [https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online)
#### Expected or Desired Behavior

FileHandler should be visible on OneDrive and SharePoint
#### Observed Behavior

It is not visible and even not reflecting in the refreshUrl
GET _https://{tenant}-my.sharepoint.com/\_api/v2.0/drive/apps?forceRefresh=1_
or via the Admin refresh
GET _https://{tenant}.sharepoint.com/\_api/v2.0/drive/apps?adminForceRefresh=1_

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by PlayPratz** [comment]
I am facing the same issue on a newly created file handler. Any updates on this?

**Comment by ificator** [comment]
I realize this issue was created before https://github.com/OneDrive/onedrive-api-docs/issues/1526, but that's the one I started putting some information in so I'm going to use that to track the "file handlers not updating" issue.
