### ISSUE TITLE
Application installation / deletion operations using File Handler 2.0 are not reflected in OneDrive for Business

### ISSUE THREAD

**Issue by fbyuichi** [OneDrive/onedrive-api-docs#1526]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

In the operation of the application using the technology of File Handler 2.0, a behavior that seems to be a Bug has occurred.
We are developing an application that uses the file handler 2.0 technology, but this behavior will affect the market release, so please take immediate action.

* 1 Outline of File Handler 2.0
https://docs.microsoft.com/ja-jp/onedrive/developer/file-handlers/?view=odsp-graph-online

There are two behavior in 1) and 2) below, which are described below.

#### Expected or Desired Behavior

1) App installation
- A message indicating that the application installation was successful is displayed on the installation site.
- The app is reflected on the OneDrive for Business screen.
(The icon to be linked with the file handler 2.0 technology, the application name on the "Open" menu list is displayed)

2) Delete application
- The deleted application is no longer displayed from the enterprise application screen of the Azure AD portal.
- The app disappears from the OneDrive for Business screen.
(The icon to be linked with the technology of File Handler 2.0 and the application name on the "Open" menu list are no longer displayed.)

#### Observed Behavior

1) App installation
-A message indicating that the application installation was successful is displayed on the installation site.
-The app is not reflected on the OneDrive for Business screen.
(The icon to be linked with the file handler 2.0 technology, the application name on the "Open" menu list is not displayed)

2) Delete application
-The deleted application is no longer displayed from the enterprise application screen of the Azure AD portal.
-The app remains displayed on the OneDrive for Business screen.
(The icon to be linked with the technology of File Handler 2.0 and the application name on the "Open" menu list are still displayed)

#### Steps to Reproduce

1)App installation
At the application installation site under development by our company, install the application using the technology of File Handler 2.0.
* The above installation site is a verification environment that can only be accessed within our company, but since there are similar installation sites published by other companies, we could check the reproduction by an alternative method.

2) Delete application
* It is assumed that the app has already been installed in the Azure AD tenant to be confirmed.
1. Log in to the Azure AD portal as a user with administrator privileges.
2. Delete the application from the application list screen of the enterprise application.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by dvd95** [comment]
Hi @fbyuichi, 
Any update on this issue?
I am still facing this on my tenant.

**Comment by ificator** [comment]
There's a fix rolling out as we speak - I would expect it to be mostly completed by the start of next week.

**Comment by ificator** [comment]
The fix should, for the most part, be rolled out now. Are folks seeing file handler updates refreshing as expected now?

**Comment by dvd95** [comment]
Hi @ificator 
It is working properly in my system now
Thank you for help
