### ISSUE TITLE
Is the parameter in the HTTP request wrong?

### ISSUE THREAD

**Issue by edixon-github** [OneDrive/onedrive-api-docs#1527]
Using the HTTP example in the documentation it tried the following which produces an error:
https://graph.microsoft.com/v1.0/sites?search=landing
"error": {
        "code": "",
        "message": "The query parameter '$search' is not supported.",
}

But, switching 'search' to 'query' does work!
https://graph.microsoft.com/v1.0/sites?query=landing

Is the documentation wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc17fd29-98dc-b6c6-071f-e717b221d4ad
* Version Independent ID: a6b19289-2ef4-e668-2223-3cc4426326ac
* Content: [Find SharePoint sites by keyword - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_search?view=odsp-graph-online&viewFallbackFrom=sharepoint-server)
* Content Source: [docs/rest-api/api/site_search.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/site_search.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by ificator** [comment]
Your initial request looks fine, and works for me. To debug further we'll need a `request-id` and `date` for a request that fails like this. The data should be in the response json body that Microsoft Graph returns.

**Comment by edixon-github** [comment]
Original premise is not an issues.  The parameter ?query= is actaully just ignored and doesn't work in place of ?search.  I'm still getting the error message "The query parameter '$search' is not supported.", but will open a different ticket if I can't resolve.
