### ISSUE TITLE
OneDrive Picker not displaying Sharepoint libraries

### ISSUE THREAD

**Issue by comaggi** [OneDrive/onedrive-api-docs#1528]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

OneDrive picker displays both the user OneDrive Folder and SharePoint Libraries 

![image](https://user-images.githubusercontent.com/76538272/131817615-19141aca-e1bf-43a1-99ff-c4ef7724144e.png)

#### Observed Behavior

When opening the Picker, libraries do not show anymore. Only user files are displayed.

This was working as expected till Sep-01

#### Steps to Reproduce

N/A

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by jcharnley** [comment]
I've noticed this too, anyone know why and a possible fix?

**Comment by davidnorthfb** [comment]
We have the same issue here. We have a custom integration to one of our in-house systems which now means we can't link to SharePoint documents.

**Comment by jcharnley** [comment]
Our sharing capabilities from sharepoint drives wont work now

**Comment by jcharnley** [comment]
it seems to be the reverse to the issue logged last year

 https://github.com/OneDrive/onedrive-api-docs/issues/1215

 > It works if we open the url https://xxx-my.sharepoint.com/personal/xxxxxxxx/_layouts/15/OneDrive.aspx instead of https://xxx-my.sharepoint.com/personal/xxxxxxxx/Documents/Forms/All.aspx that the OneDrive Javascript SDK opens up. Hope this helps @yumikohey @JeremyKelley

I tested going to endpoint Documents/Forms/All.aspx and the quick access is there but not via _layouts/15/OneDrive.aspx

**Comment by swasti1994** [comment]
This is not working for us as well, it's only showing Recent and OneDrive tabs. When clicking on "Recent" it shows this error.

<img width="1017" alt="Screen Shot 2021-09-07 at 5 14 18 PM" src="https://user-images.githubusercontent.com/40160613/132339133-fb2842fb-63ce-434c-a47e-b7d5d13004a2.png">

Any workarounds?

**Comment by comaggi** [comment]
@JeremyKelley Is there any update on this issue? Thanks!

**Comment by jcharnley** [comment]
a update would be great :)

**Comment by jcharnley** [comment]
so I tried to switch accounts and reloaded the picker, its now showing my quick access list.
<img width="1121" alt="Screenshot 2021-09-10 at 14 22 51" src="https://user-images.githubusercontent.com/25176118/132860186-7b70b5c8-f7cf-44dd-8fa5-8a1296227bfe.png">

**Comment by jcharnley** [comment]
is was there now its gone again, maybe was in my cache ?

**Comment by jcharnley** [comment]
its working again for me, guess this can be closed?

**Comment by chrisecorcoran** [comment]
It's not working for me. I work with @swasti1994

**Comment by gtiguy92** [comment]
When I view the network tab and load the page I get 404s for the following resources, possibly this is contributing to the problem:

- https://modernb.akamai.odsp.cdn.office.net/files/odsp-web-prod_2021-09-03.003/brotli/SimpleEngagementHandlers.js
- https://modernb.akamai.odsp.cdn.office.net/files/odsp-web-prod_2021-09-03.003/brotli/LegacyItemCacheSPResponseHandler.js
- https://modernb.akamai.odsp.cdn.office.net/files/odsp-web-prod_2021-09-03.003/brotli/tDt.js

**Comment by gtiguy92** [comment]
> When I view the network tab and load the page I get 404s for the following resources, possibly this is contributing to the problem:
> 
> * https://modernb.akamai.odsp.cdn.office.net/files/odsp-web-prod_2021-09-03.003/brotli/SimpleEngagementHandlers.js
> * https://modernb.akamai.odsp.cdn.office.net/files/odsp-web-prod_2021-09-03.003/brotli/LegacyItemCacheSPResponseHandler.js
> * https://modernb.akamai.odsp.cdn.office.net/files/odsp-web-prod_2021-09-03.003/brotli/tDt.js

I reloaded the page and I no longer get 404s, but also the above mentioned resources aren't actually loaded when viewing the network tab. It seems that an update may have been pushed, as now I am seeing resources loaded from a path which references 2021-09-10 (see below) as opposed to 2021-09-03 (see above).

https://modernb.akamai.odsp.cdn.office.net/files/odsp-web-prod_2021-09-10.004/brotli/.....

**Comment by chrisecorcoran** [comment]
This is working for me now. It's also working for most, but not all, of our customers. Is this because the fix takes time to roll out?
Would still be good to know why the issue occurred so we can let our customers know.

**Comment by Nicolentx32** [comment]
Return to Nicole harris

**Comment by safidison** [comment]
hi guys, this issue is fixed?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
