### ISSUE TITLE
Error in Chrome console while opening Onedrive File picker

### ISSUE THREAD

**Issue by Rocky2908** [OneDrive/onedrive-api-docs#153]
Hi,
I am a developer working on Onedrive for the past few months.  I am using Code flow authentication the with the help of LIVE SDK. I am opening the onedrive file picker window on my site. All working fine. But, I am getting the following error in the console.
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://onedrive.live.com') does not match the recipient window's origin ('http://xyz.ngrok.com').
![screen shot 2015-07-01 at 2 23 29 pm](https://cloud.githubusercontent.com/assets/10181686/8450943/e34144e8-1ffc-11e5-9e89-eedf48e53cfe.png)
How do I overcome this error.

**Comment by jscaria** [comment]
@Rocky2908 We looked into this further, and it turns out this issue is a race condition that sometimes occurs between the evaluating the postMessage function and loading the picker window.   Since there's retry logic, this shouldn't negatively affect the end user experience.
