### ISSUE TITLE
DriveItem is missing from finished upload session

### ISSUE THREAD

**Issue by akih** [OneDrive/onedrive-api-docs#1531]
It seems that **driveItem** is not anymore delivered when the final byte range of the file is PUT to the upload URL. Final response contains the same expected range than previously send bytes. Response code is 201 and file is uploaded successfully. From the documentation it is not obvious whether **driveItem** should be in final response or not if **deferCommit** is not used. For me it sounds logical to include the item data and before it did work that way. If I want to get **driveItem** after upload is finished do I need to handle upload session with **deferCommit** set as true?

Response after sending final bytes:
{"expirationDateTime":"2021-09-21T07:02:17.624Z","nextExpectedRanges":["10485760-15334441"]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d409f771-fd62-e549-d581-aac009e79e8c
* Version Independent ID: fe646b3a-06f5-a269-47e6-b4ee693e5410
* Content: [Resumable file upload - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_createuploadsession.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createuploadsession.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by ificator** [comment]
That response suggests the service is expecting you to upload another range. Can you show the `Range` headers for each of the Put requests you've made?

**Comment by akih** [comment]
Here is an example:

Content-Range: bytes 0-5242879/15846246
-> 202 {"expirationDateTime":"2021-09-22T05:21:57.637Z","nextExpectedRanges":["5242880-15846245"]}

Content-Range: bytes 5242880-10485759/15846246
-> 202 {"expirationDateTime":"2021-09-22T05:21:57.637Z","nextExpectedRanges":["10485760-15846245"]}

Content-Range: bytes 10485760-15728639/15846246
-> 202 {"expirationDateTime":"2021-09-22T05:21:57.637Z","nextExpectedRanges":["15728640-15846245"]}

Content-Range: bytes 15728640-15846245/15846246
-> 201 {"expirationDateTime":"2021-09-22T05:21:57.637Z","nextExpectedRanges":["15728640-15846245"]}

**Comment by ificator** [comment]
That is weird - the fact that it's a `201` implies that the service did think it's completed. To drill in further I'll need a few more details:
1. Are you calling personal or business OneDrive?
2. Are you providing an access token (via the `Authorization` header) or relying on the fact the upload URL is preauthorized?
3. Getting a request id would let us look at telemetry:
   - If hitting business OneDrive directly the `SPRequestGUID` and `Date` headers in the the `201` response

**Comment by akih** [comment]
We are using Microsoft Graph SDK for Java. And as said we have used this interface successfully before.

In this particular case:
1. Personal OneDrive
2. Access token is provided in header

I noticed that when `deferCommit` is used and upload is finished with PUT request then response contains DriveItem as described in here: https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession. But I'm bit confused whether `deferCommit` can be used with both personal and business accounts.

Documentation in https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession says:

deferCommit | Boolean | If set to true, final creation of the file in the destination will require an explicit request. Only on OneDrive for Business.
-- | -- | --

But later on the same documentation page:

> If deferCommit is true, you can explicitly complete the upload in two ways:
> 
> - After the final byte range of the file is PUT to the upload URL, send a final POST request to the upload URL with zero-length content (currently only supported on OneDrive for Business and SharePoint).
> - After the final byte range of the file is PUT to the upload URL, send a final PUT request in the same way that you would handle upload errors (currently only supported on OneDrive Personal).
>

**Comment by ificator** [comment]
re: defer commit, I believe it works on both so the fact that it calls out `OneDrive for Business` specifically is probably a documentation bug.

However, it really shouldn't be needed in this case and I'm at a loss to explain how you're seeing what you're seeing. The code that sets the status code to `201` will only serialize the item metadata to the response stream.

Are you using the `LargeFileUploadTask` from the Java SDK or are you executing the upload session manually?

**Comment by akih** [comment]
We are using version 2.10.0 from the Java SDK and can not upgrade at the moment because our device has 23 Android SDK. So the class that I'm using is  `ChunkedUploadProvider`. I looked deeper to our Java SDK sources and it seems that there is a bug in `ChunkedUploadResponseHandler` which is causing this behavior; previous response is cached and used when trying to serialize item metadata.. So the problem was in our end, sorry for bothering!
