### ISSUE TITLE
Graph API missing performer information 

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1536]
#### Category
- [ x] Question
- [ ] Documentation issue
- [ ] Bug
Hi,
We have observed that no information provided about the activity performer in the API response. 
For example in case when file is shared and removed by the user other than who created then how could we get this info
In the below response, we even don't know who deleted the file

`{
            "@odata.type": "#microsoft.graph.driveItem",
            "id": "0166T5MOBRHQUSGQXRCRHJZEXTT7XJF5UM",
            "cTag": "\"c:{23293C31-F142-4E14-9C92-F39FEE92F68C},4294967295\"",
            "size": 0,
            "parentReference": {
                "driveId": "b!gl16TrIwKEmJS_q1D0yOw_Wn9CYX0X9LmxyC90FWSC5vV2ltvzsrRIS0McMNLVqM",
                "driveType": "business",
                "id": "0166T5MOF6Y2GOVW7725BZO354PWSELRRZ"
            },
            "deleted": {
                "state": "deleted"
            },
            "file": {},
            "fileSystemInfo": {}
        }
    ]
}`
Is there any ETA about this fix or any alternate way to get the info about the performer?
Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by shayan-brcm** [comment]
@JeremyKelley can you please help in getting the response of above question?

**Comment by k-tsoi** [comment]
@shayan-brcm The delta API will combine multiple changes into a singular item.
We would recommend getting the Audit logs to get more granular information about specific changes.
