### ISSUE TITLE
Certificate expired for https://js.live.net/v7.2/OneDrive.js 

### ISSUE THREAD

**Issue by fuzzypix** [OneDrive/onedrive-api-docs#1537]
The link to the OneDrive.js has expired certificate (as of today, Sep 28 2021), making it impossible to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by jcharnley** [comment]
is this the same issue that everyone will have, 

app.bundle.js:3 Uncaught ReferenceError: OneDrive is not defined

**Comment by jhoffman-minitab** [comment]
Seeing this issue as well, major impact

**Comment by riyazpanarwala** [comment]
I got the same issue as well. Please resolve as soon as possible.  Thanks

**Comment by fuzzypix** [comment]
Yep, resolved now, closing.
