### ISSUE TITLE
JS Filepicker - Error code 103

### ISSUE THREAD

**Issue by marcospri** [OneDrive/onedrive-api-docs#1541]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Using one drive's file picker should work the first time authentication happens.

#### Observed Behavior

I'm using the file picker's library as described here https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online

The integration works *unless* an new login happens on the file picker window, ie:

- File picker is launched from our app
- File picker opens in a new window and a user/password prompts shows up
- File picker ends up in a window like:

![103](https://user-images.githubusercontent.com/1433832/136781205-29936544-6019-4d3d-9acc-7037dd18a24e.png)

when the error happens the filepicker has triggered request like:

https://skyapi.onedrive.live.com/API/2/GetUpgradeOptions
https://skyapi.onedrive.live.com/API/2/GetWorkProgress?type=itemCop
https://skyapi.onedrive.live.com/API/2/GetUserInfo

that fail with a 500 error code and a body similar to:

```{"HttpStatusCode":200,"RetryAfterHeader":null,"error":{"code":103,"debugMessage":"The given canary was not valid.","isExpected":true,"stackTrace":"2cd93cdad92489bf1:rqMllmk9O+YCCj7GvLBFcSgaeqkROeJFNYsMYbrDd6p2TjkTllMVgyIu9tAHUnQlzqF7bB4sZyrfjSkRre0WaA4Dafa7FyIwTJQFvrpdxXenpRDyYk3n55jv5UpkpSUnYWgdZsEAfktdEUkmHdMVFZyMOCPNB3UtJ+nMrGfRYkX9mjxGVur8eV0PuhpXhiQxLysvDySYF2blAuuwRRU3Mp+HNhtrpGtoCfNZeU8il7lPBFhoSfCcVbPylCnJPBxo0mmVRR6Cz5fMoWyhLqTG8hguQv\/ShCkLO0DmeDtUBR5\/Bu6GIqqrYT7rW5Hfurepm9cf7r9tWPT94lfTs7S5S+cMZCu8AqielwEGp1U082TnEujoMUi9X5PiKEZwXOwSuu+p9VlncVI+\/13YEhcMeAxMod0bbGL6XmKXiZQH++r1eXrFZUl\/GmWQXrkmq6Y1pIj+VvkXAYAfl4aB3\/yCaLD6oZOok\/PkBDMm0xqvffFV83QGcpCKrHxRREv1uwEh3ERoDuhKiBcZ6cHBh+xDa31xVsGH0pDTFgAM88F94YM5ifdU2yV1WIibB+lbgVaNo8pxZydvPkdSSYgON4Qa1a160sv7u35yEFe5LgYjXqPsWLvkm+\/wLT\/9rGq09xo5gpfUhQGrX9tMnykkOLyXTzJu\/Lj9IHWy32YRuNGD4MQhxmYU6YqVNA=="}}```

Note that the same API requests are made by the filepicker when it works but they return 200 codes instead.

- Starting over (which will not prompt for user/password) will not trigger the error
- When the error is present, just refreshing the windows "fixes it"
- Signing out of the microsoft account after this, will make the error re-appear. 

#### Steps to Reproduce

The minimal HTML page which I can triggered the error is similar to:

```
<html>
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
<body>
<script type="text/javascript">
    function launchOneDrivePicker(){
      const filePickerOptions = {
        clientId: '',
        action: 'share',
        multiSelect: false,
        viewType: 'files' // The type of item that can be selected.
      };
      OneDrive.open(filePickerOptions);
    }
</script>
<button onClick="launchOneDrivePicker()">One Drive</button>
</body>
</html>
```

Thank you.

**Comment by marcospri** [comment]
Small update on this, tested with the same code, same app registration but login in as a sharepoint user while using the filepicker doesn't trigger the error.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
