### ISSUE TITLE
Does refresh token expire for OneDrive API?

### ISSUE THREAD

**Issue by tomasjerabek-com** [OneDrive/onedrive-api-docs#1542]
Does the refresh token ever expire for OneDrive API or is it permanent?
Is this statement valid: As long as I have the refresh token I can use it to get fresh access tokens and connect to OneDrive API (unless app permission is manually removed by account holder from https://account.live.com/consent)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210daf87-f00d-db74-cdb0-279d033d29de
* Version Independent ID: 03050364-41d2-e475-69b1-08b554ade330
* Content: [Authorization for OneDrive API via Microsoft Graph - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#step-3-get-a-new-access-token-or-refresh-token)
* Content Source: [docs/rest-api/getting-started/graph-oauth.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/graph-oauth.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by chackman** [comment]
Here is the documentation link from AAD that talks about refresh tokens and expiration: https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens
