### ISSUE TITLE
Drive delta call giving response although user's onedrive does not exists

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1544]
#### Category
- [ x] Question
- [ ] Documentation issue
- [ ] Bug

User had onedrive but then the subscription had revoked and does not have onedrive subscription but still API call is giving response
API calls i made and got status code 200 with response
`https://graph.microsoft.com/v1.0/users/user_id/drives`
`https://graph.microsoft.com/v1.0/users/user_id/drive/root/delta`
`https://graph.microsoft.com/v1.0/users/user_id?$select=mySite`
![Uploading Screenshot 2021-10-14 at 11.56.45 AM.png…]()
Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
Could you please provide request ID's and UTC timestamps for the requests that are not working as expected?
