### ISSUE TITLE
Interact OneDrive and GitHub Actions

### ISSUE THREAD

**Issue by teddychao** [OneDrive/onedrive-api-docs#1545]
#### Category
- [ x ] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

Hi. We have a question about interact OneDrive and GitHub Actions. We wish to use OneDrive API to download files from OneDrive to GitHub Actions server. We have some data stored at our University's OneDrive storage and we need to download them to GitHub Actions for code testing. 

#### Observed Behavior

However, we are unable to find an available solution on GitHub Actions marketplace. We have enquired GitHub Actions service and we were told that REST API may help, but we are not clear where to start. Can we have some information about writing some code to start?

Thank you.

Best wishes
Teddy

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment]
We'd recommend looking at the Microsoft Graph documentation at graph.microsoft.com, and find an appropriate sample.
Here is the documentation for "Download file": https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http
