### ISSUE TITLE
The search API does not work when searching under a folder hierarchy.

### ISSUE THREAD

**Issue by HuangKaize** [OneDrive/onedrive-api-docs#1546]
In our project, we are using searching API: /_api/v2.0/drive/items('DriveItem.id')/search(q='{search-text}')
1. search in root/whole drive
  ` /_api/v2.0/drive/items('root')/search(q='{search-text}')` 
  it's using **root** specifically, and works well.
2. but when searching inside specific folder, it does not work
we have following folder structures, and need to search items in folder **huang.kaize_1**:
![image](https://user-images.githubusercontent.com/58523323/137446734-3150314e-86d1-4c97-b874-2c4b06cf7bfe.png)
the folder’s id is **014KNK33NGQEV3MHBTERD3RUXVATNPVQHH**, and it has **2** files and **2** empty sub-folders； 
  a. search with **q='start'**, it returns empty, but it's expected to return the item **start**_face_1
    ![image](https://user-images.githubusercontent.com/58523323/137447239-cb46702c-4573-42c2-b437-233a5adad5cf.png)
  b. search with **q='sub'**, it returns 2 folder objects,  
    ![image](https://user-images.githubusercontent.com/58523323/137447337-9608053e-32bb-4f3f-8a6a-f9031d75f63b.png)
  c. search with **q='12'**, it return empty, but it's expected to return the item **1223**
  d. search with **q='1'**, it  return 3 folder objects(huang.kaize_1,  subfolder1 and subfolder2)
It proves that when searching in specific folder, it matches the folders instead of the files; but for  q='1' it also query out subfolder2, it’s very strange; seems it's a OneDrive bug.

Would you please address the searching issue?  So we can search items under a folder hierarchy with OneDrive API.

Best regards.
Kaize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a094aa0-adc5-9f08-d75e-bff6c5c42b4b
* Version Independent ID: c674446f-0d55-5c4b-0d0a-bbddf184dd1b
* Content: [Search for files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_search?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_search.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_search.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by toannguyenspce** [comment]
Please re-open this issue, is this an onedrive bug or it's simply not supported in graph API ?
