### ISSUE TITLE
OneDrive via Microsoft Graph: Unable to refresh tokens: Error AADSTS70011: The scope '' is not configured for this tenant

### ISSUE THREAD

**Issue by maborAIS** [OneDrive/onedrive-api-docs#1549]
#### Category
- [X] Question
- [ ] Documentation issue
- [ ] Bug

I wanted to get new tokens using refresh_token (via https://login.microsoftonline.com/common/oauth2/v2.0/token). I am using the following documentation: Authorization for OneDrive API via Microsoft Graph - OneDrive dev center, Code flow, Step 3. Get a new access token or refresh token. I am getting the following error:

{"error":"invalid_scope","error_description":"AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope '' is not configured for this tenant.\r\nTrace ID: 8b2f863f-ec78-43db-b949-f8cad47b8301\r\nCorrelation ID: 3cc17455-6179-4482-8aae-352f3c03aee7\r\nTimestamp: 2021-10-25 07:31:43Z","error_codes":[70011],"timestamp":"2021-10-25 07:31:43Z","trace_id":"8b2f863f-ec78-43db-b949-f8cad47b8301","correlation_id":"3cc17455-6179-4482-8aae-352f3c03aee7"}

My access_token and refresh_token were migrated from our provider: Kloudless (unfortunately I have no information on how the provider obtained these tokens, I am unable to obtain this information from the provider). The access_token works fine for queries to the Microsoft Graph API (ex. https://graph.microsoft.com/v1.0/me), but I don't know why I can't refresh these tokens with the refresh_token.

If I try to refresh the tokens through Authorization for OneDrive API for Microsoft Accounts - OneDrive dev center , I get new tokens but the new access_token is not working in queries to Microsoft Graph API.

Any help is appreciated!

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
This looks like a AAD issue, please send your feedback to the stackoverfollw link that was provided.
We would recommend using the AAD libraries to deal with tokens
https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries
