### ISSUE TITLE
file extension restriction "onedrive business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#155]
can we have docs updates for file extension restriction, specified here (https://community.office365.com/en-us/f/172/t/280295)

also "file without extension" is failing in response (500 http error) with description 
code: -2130575312, Microsoft.SharePoint.SPException | message: The URL 'Documents/ankit' is invalid.  It may refer to a nonexistent file or folder, or refer to a valid file or folder that is not in the current Web.

but this is not mention, what should we expect for file without extension ?

**Comment by rgregg** [comment]
I wasn't able to reproduce the error creating a file without extension. Here's what my request looked like:

```http
PUT /personal/{user-upn}/_api/v2.0/drive/root:/myFilename:/content HTTP/1.1
Authorization: Bearer ...
Content-Length: 23
Content-Type: application/octet-stream

The contents of my file
```

And I got back `HTTP/1.1 201 Created`

**Comment by rgregg** [comment]
Closing out old issues. If this continues to be an issue, please reopen and provide additional details.
