### ISSUE TITLE
Doc page refers to earlier mention that doesn't exist

### ISSUE THREAD

**Issue by bmulholland** [OneDrive/onedrive-api-docs#1551]
Page says "See the earlier-mentioned documentation on how to refresh your subscriptions." but there is no earlier mention of refreshing subscriptions, much less a link to its documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b036f172-b0cf-d2af-1307-a3f5abf49524
* Version Independent ID: 894da04b-5803-4f44-a94f-0fa462b006a9
* Content: [Best practices for discovering files and detecting changes at scale - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online#crawl-and-process-by-using-delta-query)
* Content Source: [docs/rest-api/concepts/scan-guidance.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/scan-guidance.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@bmulholland The documentation we are referring to is the Graph subscription page linked above.

**Comment by k-tsoi** [comment]
https://aka.ms/webhookdoc

**Comment by bmulholland** [comment]
@k-tsoi Okay, but that's not in the documentation page, and answering me here doesn't fix the problem on the page itself. This issue is not closed.
