### ISSUE TITLE
When specifying requireSignin false on sharing invite API the message specified is not used.

### ISSUE THREAD

**Issue by bvstone** [OneDrive/onedrive-api-docs#1553]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

When  I specify a message it should appear in the email invite.

#### Observed Behavior

I found that only when requireSignin is false the message specified is not used and just the default message of "Here's the document that xxxxxxx shared with you." is used.

#### Steps to Reproduce
Make call to POST /me/drive/items/{item-id}/invite

```
{
	"recipients": [{
			"email": "bvstone@xxxxx.com"
		}
	],
	"message": "Here is the file!",
	"requireSignIn": false,
	"sendInvitation": true,
	"roles": ["read"]
}
```

This will not use the message specified.

```
{
	"recipients": [{
			"email": "bvstone@xxxxx.com"
		}
	],
	"message": "Here is the file!",
	"requireSignIn": true,
	"sendInvitation": true,
	"roles": ["read"]
}

```
This will use the message specified.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issue

See screenshots below:
![works](https://user-images.githubusercontent.com/15163488/146416026-d1973f81-c0d0-4a2d-91f6-edecc664c218.jpg)
![doesntwork](https://user-images.githubusercontent.com/15163488/146416029-407ac284-8b62-4a7d-96a7-bc1df74b062a.jpg)
s

**Comment by bvstone** [comment]
So... nothing yet?  Hmmm... maybe I did something wrong on how I reported this bug.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
