### ISSUE TITLE
Not possible to copy or list content of a directory that contains # in the name

### ISSUE THREAD

**Issue by damirnemcanin** [OneDrive/onedrive-api-docs#1554]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Using the API I expected to be able to copy files from the directory called `#02 Test`, but I received the message 'directory not found '.

#### Observed Behavior

The directory `#02 Test` is created in the OneDrive. I also tried to create the directory `#01 Test` using API. 
The directory created from API is possible to list, copy, or sync, but the directory created on OneDrive is not.
When I check in the OneDrive the directory created with API has a space between # and number  `# 01 Test` but the one created in OneDrive doesn't `#01 Test`. 
If I list directories with API both directories are without space between # and number.

The same problem is if the name use letter after #. For example #A Example

The tool used to communicate with OneDrive API is rclone, but the error should not be on the rclone side because I tested the same scenario with other providers and I don't get this error.

#### Steps to Reproduce

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ificator** [comment]
Do you have examples requests for copy /enumerate requests that are failing? It seems like the folder is referenced by push and contains an unencoded #.

**Comment by damirnemcanin** [comment]
I hope this helps:
rclone is a tool use to connect from Linux to  OneDrive API
lsd -list directory
damirMSO - is the connection name 

`rclone lsd "damirMSO:" `
         ` -1 2021-12-17 20:43:51         5 #01Test`
         ` -1 2021-12-17 20:48:17         1 #02Test`
When I list my root directory on the OneDrive I can see that I have two directories, both containing #

If I try to list directories in the \#01test, I get the result
`rclone lsd "damirMSO:#01Test"`
`          -1 2021-12-17 20:44:11         0 #02 Test`
`          -1 2021-12-17 21:06:49         0 #03 Test`
`          -1 2021-12-17 21:31:14         0 #a Test`
 `         -1 2021-12-17 21:31:51         0 #b Test`
  `        -1 2021-12-17 21:36:25         0 AB#test`

But from \#02Test (which I created on OneDrive WebUI):
`rclone lsd "damirMSO:#02Test"`
 `  2021/12/20 08:09:53 ERROR : : error listing: directory not found`
  ` 2021/12/20 08:09:53 Failed to lsd with 2 errors: last error was: directory not found`

**Comment by k-tsoi** [comment]
@damirnemcanin would you be able to provide requestIds and timestamps for the failing API requests?
unfortunately we are unable to look into why this is the case without them
