### ISSUE TITLE
Known Issue: Cannot convert digitally-signed Word doc to PDF

### ISSUE THREAD

**Issue by thomasjeffries11** [OneDrive/onedrive-api-docs#1557]
The API cannot convert digitally-signed Word documents to PDF.  We should add this as a limitation in documentation.

I can provide details of the investigation.  You can reach out to me on Teams (thjeffri@microsoft.com) if needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46acaeca-c7f2-1013-239e-93853818f3d7
* Version Independent ID: 8b42fae5-53c9-f8c3-b88f-f2a087b23f8c
* Content: [Convert to other formats - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_get_content_format.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get_content_format.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@thomasjeffries11 you are welcome to contribute a change to our docs.
please tag and link the PR here and we will look at it
