### ISSUE TITLE
Size limitation documentation is absent

### ISSUE THREAD

**Issue by daviburg** [OneDrive/onedrive-api-docs#1558]
Please document what is the size limitation for this OneDrive format conversion API. Does the limitation apply to the input content size, output content size, or both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46acaeca-c7f2-1013-239e-93853818f3d7
* Version Independent ID: 8b42fae5-53c9-f8c3-b88f-f2a087b23f8c
* Content: [Convert to other formats - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online#known-issues-with-html-to-pdf-conversion)
* Content Source: [docs/rest-api/api/driveitem_get_content_format.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get_content_format.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@daviburg 
Thank you for your feedback, we will take a look at what content can be provided.
Unfortunately, it is not just Content-size that is a factor for conversion limitation but a number of other factors too
