### ISSUE TITLE
Message parameter max length is 500 characters, not 2000

### ISSUE THREAD

**Issue by LeoTanoue** [OneDrive/onedrive-api-docs#1559]
Message parameter max length is 500 characters, not 2000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20835c68-99bc-a096-f40b-ed7108712eec
* Version Independent ID: bed66be5-c472-116c-1d42-09d2e0fc65eb
* Content: [Send an invite to access an item - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/driveitem_invite.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_invite.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@LeoTanoue Thanks for spotting this error, please feel free to create PR to update the documentation and mention me so that I can take a look.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
