### ISSUE TITLE
Onedrive Business - Rename file/folder in root folder

### ISSUE THREAD

**Issue by bscharm** [OneDrive/onedrive-api-docs#156]
When I try to rename/move a file or folder in the root folder I get an incorrect argument error, but when renaming/moving to other folders it works fine. This is on the PATCH by id or by path.

Example of body when renaming in/into root:
`{"parentReference":{"path":"/drive/root:"},"name":"yodanew.jpeg"}`

Example of body when renaming in/into non-root:
`{"parentReference":{"path":"/drive/root:/foo"},"name":"yodanew2.jpeg"}`

Here are the response headers on the failed call (getting back a 400):
```{date=[Mon, 06 Jul 2015 22:38:28 GMT], server=[Microsoft-IIS/8.5], x-ms-invokeapp=[1; RequireReadOnly], expires=[Sun, 21 Jun 2015 22:38:28 GMT], transfer-encoding=[chunked], x-aspnet-version=[4.0.30319], x-sharepointhealthscore=[0], x-frame-options=[SAMEORIGIN], microsoftsharepointteamservices=[16.0.0.4121], request-id=[217b179d-a0a0-2000-381a-f0b19c97669c], p3p=[CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"], spclientservicerequestduration=[128], last-modified=[Mon, 06 Jul 2015 22:38:28 GMT], x-sp-serverstate=[ReadOnly=0], sprequestguid=[217b179d-a0a0-2000-381a-f0b19c97669c], x-content-type-options=[nosniff], x-powered-by=[ASP.NET], content-type=[application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8], cache-control=[private, max-age=0], odata-version=[4.0]}```

**Comment by ankit-ankuagrawal** [comment]
@katahir @bscharm 

they are working fine for me

**Comment by bscharm** [comment]
If I am just passing a name I believe it will work, but as documented on your site I am always passing a parent reference (please see my original comment for the body I am sending with the requests). Also if trying to move something from a nested folder into the root it would be impossible as it fails with the parent reference. Please confirm.

**Comment by ankit-ankuagrawal** [comment]
@bscharm both operation renamed and move to root folder are working, so wht i did
let me make it clear in parentreference u can pass id of parent folder also 

before making request we check which operation is this rename or move

for rename we follow above comment request 

for move this is the request:
parentReference take https://github.com/OneDrive/onedrive-api-docs/blob/master/resources/itemReference.md refer this

**Comment by bscharm** [comment]
@ankit-ankuagrawal Is there an issue with the parent reference path I am passing then? `"parentReference":{"path":"/drive/root:"}`

**Comment by ankit-ankuagrawal** [comment]
@bscharm may be yes try this

PATCH https://mdm05-my.sharepoint.com/_api/v2.0/me/drive/items/01MFUQXWJP2YMV7DT47BAKNZJSUHDDOI2L

Headers:
If-Match: *
Content-Type: application/json
Authorization: bearer accessToken

body: {"parentReference":{"id":"01MFUQXWLCOXOYJDXD6ZFL2UHE7C4TA2YQ"}}

id for folder in which u have to move 

this works fine with me

**Comment by bscharm** [comment]
@ankit-ankuagrawal For our use case we will only have access to the path of the parent folder and not the ID unfortunately. We would have to then make a call to get the ID via metadata and then our PATCH, which is not efficient. If there is an issue with my root path than seemingly that would be an easy fix, as it works for any other folder.

**Comment by ankit-ankuagrawal** [comment]
@bscharm do u guys stored id of each file / folder received from server

and there is no required to make extra call to get id of folder in which u have to move

if ur storing id of each item, before making move request call for id of the folder in which u have to move and then make a request

**Comment by bscharm** [comment]
@ankit-ankuagrawal We do not store any file/folder information.

I don't understand how this is not a bug if I can't rename/move files into root when passing parentReference + path. Shouldn't that work? I can confirm it works for regular OneDrive. Apologies If I am misunderstanding.

**Comment by ankit-ankuagrawal** [comment]
@bscharm ur right there are many thinks tht work for onedrive personal and in business they fail

definitely its a bug

**Comment by rgregg** [comment]
We're investigating... I'll provide an update when I have more details.

**Comment by bscharm** [comment]
@ankit-ankuagrawal @rgregg thanks for your help on this, wanted to be sure it was not on my end

**Comment by ificator** [comment]
This issue was actually fixed quite a while ago. Please open again if you believe otherwise.
