### ISSUE TITLE
No documentation for "secureSharingInvalidRequest" error response code

### ISSUE THREAD

**Issue by george-ayris** [OneDrive/onedrive-api-docs#1561]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

#### Missing Documentation
I have received the following response from the One Drive API:
```
{
   "error": {
      "code": "invalidRequest",
      "message": "Some users in the request cannot be invited securely.",
      "innerError": {
         "code": "secureSharingInvalidRequest",
         "date": "2022-01-31T12:47:14",
         "request-id": "c51608f5-8452-4ffe-85f5-aa69b511f498",
         "client-request-id": "c51608f5-8452-4ffe-85f5-aa69b511f498"
      }
   }
}
```

This is from calling the following URL:
`https://graph.microsoft.com/v1.0//drives/#{one_drive_drive_id}/items/#{folder_id)/invite`

with body:
```
{
   "requireSignIn": true,
   "sendInvitation": false,
   "roles": "read",
   "recipients": [
      "#{recipient_email}"
   ]
}
```

I can't find any documentation on how to resolve this or actually what the issue means. Can you help?

Cheers,
George

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
