### ISSUE TITLE
Maxed out OneDrive webhook subscriptions - Unable to delete existing subscriptions

### ISSUE THREAD

**Issue by wengera** [OneDrive/onedrive-api-docs#1562]
How am I supposed to delete a subscription when I don't have an id? I accidentally created a loop that maxed out my subscriptions and now I have no way of getting rid of them because I don't have the ids recorded anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70301fdf-007d-834f-e5e3-cb2bfbbd2d84
* Version Independent ID: 5bada6e0-9402-e46a-9f0a-4a9c9e181795
* Content: [Update a webhook subscription - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_update?view=odsp-graph-online#feedback)
* Content Source: [docs/rest-api/api/subscription_update.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/subscription_update.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by wengera** [comment]
Sorry I thought this was done on the Delete page not the Update page. The issue still stands though.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
