### ISSUE TITLE
Add sample for copying from a specific (non-default) SharePoint document library

### ISSUE THREAD

**Issue by heinrich-ulbricht** [OneDrive/onedrive-api-docs#1563]
My use case is copying files **from** a specific (**non-default**) SharePoint document library. The documentation did not help me in this regard. I propose adding something that would've helped.

I'm referring to this part of the documentation:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/3469970/153548909-e2d904ae-63fe-4e5b-9ce2-e7aa4cd9fd81.png">

The sample to copy from a SharePoint site is currently only this:

`POST /sites/{siteId}/drive/items/{itemId}/copy`

This copies from the default "Documents" library of a SharePoint site.

Please add the sample to copy from a non-default library of a SharePoint site which would be this:

`POST /sites/{siteId}/drives/{driveId}/items/{itemId}/copy`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38d3dcf-49bd-eedc-e4cf-5041af8ed7fe
* Version Independent ID: 8a3d3fed-4e6c-0592-5f7c-8105365698d8
* Content: [Copy a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_copy.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_copy.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by heinrich-ulbricht** [comment]
(Or maybe wait until it's clear that it is not causing problems... see #1566)

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
