### ISSUE TITLE
Wrong deltaLink in Response example

### ISSUE THREAD

**Issue by vladimir-efimenko** [OneDrive/onedrive-api-docs#1564]
In the example of the response there is wrong value of @odata.deltaLink: 
Should be "https://graph.microsoft.com/v1.0/me/drive/root/delta(token='1230919asd190410jlka')" (without **?**)
The example located here: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online#response-2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f139d8af-bd5e-3289-daec-a101e7071fbf
* Version Independent ID: 69ddaa8b-120b-14e7-643e-dfa921d196fb
* Content: [Sync the contents of a drive - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_delta.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delta.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@vladimir-efimenko feel free to create a PR to update this bug. please tag me in the PR so that I can look and approve it
