### ISSUE TITLE
Failing to copy ~3 GB across SharePoint sites - generalException after a few seconds!?

### ISSUE THREAD

**Issue by heinrich-ulbricht** [OneDrive/onedrive-api-docs#1566]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I expect a simple copy operation to work across SharePoint sites.

I'm copying a _folder_ (from a _non-default_ document library) containing ~3 GB of files and folders from SharePoint site A to a document library's _folder_ in site B. I expect this to work.

#### Observed Behavior

The copy operation does not create any files in site B and fails after a few seconds.

Response headers of a recent API call:
- request-id: 48ac9470-85ab-4ad2-9209-d4cb29c9d79c
- Date: Fri, 11 Feb 2022 09:49:11 GMT
- no SPRequestGuid

_Note: copying another folder (right next to the one I want to copy) with some test files worked. So I'm not sure what's preventing the actual files I want to copy from being copied._

#### Steps to Reproduce

I'm copying files:
- from _Site A_, document library _11PJ00000-KOPIE_, folder _Sourcefolder_
- to _Site B_, document library _Kopierziel_, folder _Destfolder_

So after the copy operation there should be a folder _Site B/Kopierziel/Destfolder/Sourcefolder_.

I'm copying via Graph API call: `POST https://graph.microsoft.com/v1.0/sites/{siteId}/drives/{driveId}/items/{itemId}/copy` using `Sites.ReadWrite.All` application permissions.

- `siteId` is the id of the source SharePoint site retrieved via `https://graph.microsoft.com/v1.0/sites/$($siteUri.Authority):$($siteUri.AbsolutePath)?$select=id`
- `driveId` is the source document library ID retrieved via `https://graph.microsoft.com/v1.0/sites/{siteId}/drives?$select=id,name`
- `itemId` is the source folder ID retrieved via `https://graph.microsoft.com/v1.0/sites/{siteId}/drives/{driveId}/list/drive/root:/{pathRelativeToRoot}?$select=id,name,webUrl`

The POST body looks like this:

```
{
  "parentReference": {
    "driveId": "b!_dStGJzSBEC1L<snip>_q6pPyQph-0cSIm_cgkGaZTq",
    "id": "01KONSX3CV<snip>JIVBZ2TDY3KEBQQW6"
  }
}
```

- `driveId` is the destination document library ID in the destination site (retrieved like the source doc lib ID described above)
- `id` is the destination folder ID in the destination doc lib that where the source folder should be copied to (retrieved like the source folder ID described above)

After sending the copy request I use the status URL to retrieve the state.

For about 2 seconds I get an `inProgress` state:

```
{
  "@odata.context": "https://customer.sharepoint.com/sites/SiteName/_api/v2.1/$metadata#drives('b!Uvw5ZQERZ0OliYQvBT3HslhNSrmfoBdGr1RKdmLb9Yni1XbJsG4yQYVTymvGF7WH')/operations/$entity",        
  "id": "477c6f14-354b-4888-bca1-da68a5015bda",
  "createdDateTime": "0001-01-01T00:00:00Z",
  "lastActionDateTime": "0001-01-01T00:00:00Z",
  "percentageComplete": 0.0,
  "percentComplete": 0.0,
  "status": "inProgress"
}
```

Then I get the `failed` status and a `generalException`:

```
{
  "@odata.context": "https://customer.sharepoint.com/sites/SiteName/_api/v2.1/$metadata#drives('b!Uvw5ZQERZ0OliYQvBT3HslhNSrmfoBdGr1RKdmLb9Yni1XbJsG4yQYVTymvGF7WH')/operations/$entity",        
  "id": "477c6f14-354b-4888-bca1-da68a5015bda",
  "createdDateTime": "0001-01-01T00:00:00Z",
  "lastActionDateTime": "0001-01-01T00:00:00Z",
  "status": "failed",
  "error": {
    "code": "generalException",
    "message": "General exception while processing"
  }
}
```

_Note: I used [this excellent blog post by Srinivas Varukala](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-mailbag-copy-move-files-and-folders-in-sharepoint-online/) as basis. The only thing that I changed was copying from a non-default SharePoint library._

This should not happen. And I don't know how to debug this further as there is no additional information about the error. What's going on here?

**Comment by heinrich-ulbricht** [comment]
Note: I looked at #980 where the missing name for the copy destination was a problem but providing a name (either the same or a different one) makes no difference. It still fails for me.

**Comment by svarukala** [comment]
I didn't face this issue but as noted in lessons learned in my blog, i found that an issue can happen when the “name” used for the destination file is different from the source file name. Ensure the destination file name is same as the source file name to resolve this issue. This issue is not reproducible with smaller files.

Btw, are you seeing similar issue with a different file (small size)?

**Comment by heinrich-ulbricht** [comment]
@svarukala When you say "file name" this would in my case refer to the "folder name", right? Because I'm copying one item - a folder - containing thousands of other items. I did not check the size of those files, only the sum which is 3 GB. There could be one big file in there.

Regarding the smaller file sizes: When creating a folder right adjacent to the failing folder that only contains some small files and a sub-folder with some other small files it works fine (copying to the same destination). So something is special about the folder I need to copy. But I don't know what.

**Comment by heinrich-ulbricht** [comment]
I had a hunch and tried copying via the SharePoint browser UI - it also fails! And via the developer tools I can see something in the response. A call stack and an actual error!

Copying a part of it in case it's useful:

> "ErrorType\": \"System.ArgumentException\",\r\n  \"Message\": \"An item with the same key has already been added. CallStack --    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\\r\\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\\r\\n   at Microsoft.SharePoint.Deployment.MetaInfoHandler.Parse(Byte[] propertyBytes)\\r\\n   at Microsoft.SharePoint.Deployment.FileSerializer.HandleMetaInfo(ExportObjectManager objectManager, SPWeb parentWeb, Object metaInfoObject, SerializationInfo info, Guid listID, Guid itemID, String itemETag)\\r\\n   at Microsoft.SharePoint.Deployment.FileSerializer.GetDataFromDataSet(Object obj, SerializationInfo info, StreamingContext context)\\r\\n   at Microsoft.SharePoint.Deployment.DeploymentSerializationSurrogate.GetObjectData(Object obj, SerializationInfo info, StreamingContext context)\\r\\n   at Microsoft.SharePoint.Deployment.XmlFormatter.SerializeObject(Object obj, ISerializationSurrogate surrogate, String elementName, Boolean bNeedEnvelope)\",\r\n  \"CorrelationId\": \"079a1fa0-d00e-3000-dc64-b7ca62efa959\"\r\n}","{\r\n  \"Event\": \"JobFatalError\",\r\n  \"JobId\": \"745253c2-1ae0-4787-8f97-f5eba0aa2058\",\r\n  \"Time\": \"02/11/2022 14:33:56.569\",\r\n  \"TotalRetryCount\": \"0\",\r\n  \"MigrationType\": \"Copy\",\r\n  \"MigrationDirection\": \"Export\",\r\n  \"ErrorCode\": \"-2147024809\",\r\n  \"ErrorType\": \"System.ArgumentException\",\r\n  \"Message\": \"An item with the same key has already been added. CallStack --    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\\r\\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\\r\\n   at Microsoft.SharePoint.Deployment.MetaInfoHandler.Parse(Byte[] propertyBytes)\\r\\n   at Microsoft.SharePoint.Deployment.FileSerializer.HandleMetaInfo(ExportObjectManager objectManager, SPWeb parentWeb, Object metaInfoObject, SerializationInfo info, Guid listID, Guid itemID, String itemETag)\\r\\n   at Microsoft.SharePoint.Deployment.FileSerializer.GetDataFromDataSet(Object obj, SerializationInfo info, StreamingContext context)\\r\\n   at Microsoft.SharePoint.Deployment.DeploymentSerializationSurrogate.GetObjectData(Object obj, SerializationInfo info, StreamingContext context)\\r\\n   at Microsoft.SharePoint.Deployment.XmlFormatter.SerializeObject(Object obj, ISerializationSurrogate surrogate, String elementName, Boolean bNeedEnvelope)\\r\\n   at Microsoft.SharePoint.Deployment.XmlFormatter.Serialize(Stream serializationStream, Object topLevelObject)\\r\\n   at Microsoft.SharePoint.Deployment.SPExport.SerializeObjects()\\r\\n   at Microsoft.SharePoint.Deployment.SPExport.Run()


The key message seems to be: "An item with the same key has already been added". What is this?

**Comment by heinrich-ulbricht** [comment]
Since [SharePoint 2013 is popping up](https://social.technet.microsoft.com/Forums/office/en-US/3e8d5e92-7f12-4752-a00b-67f2453cf012/content-migration-api-export-did-not-complete-an-item-with-the-same-key-has-already-been-added?forum=sharepointgeneral) when searching for the error this might play a role:

The content of the folder we try to copy has been migrated from SharePoint 2013 to SPO using the SharePoint Migration Tool (SPMT).  Maybe this screwed something up?

Anyway, copying in the out-of-the-box SharePoint UI should succeed. And via API too.

**Comment by heinrich-ulbricht** [comment]
We opened a support ticket with Microsoft: 29718177
fyi @svarukala

**Comment by k-tsoi** [comment]
Closing this issue as there is a support case, please reopen if further assistance is needed outside of the support case

**Comment by heinrich-ulbricht** [comment]
Seems like a platform bug has been found. I try to get more information.

**Comment by heinrich-ulbricht** [comment]
We got an update from Microsoft that the problem will be solved in about 4 weeks.

Additional note: we could reproduce the error using a set of MPP (MS Project) files. Copying even only one of those MPP files failed 100% every time. Although we got no additional info from MS our assumption so far is that the error might be restricted to those files.
