### ISSUE TITLE
Deletion in Resumable File Upload

### ISSUE THREAD

**Issue by siddharth-redseer** [OneDrive/onedrive-api-docs#1569]
Two issues. 1 - An upload might stop due to some error (resumable large file upload), 
> SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)     

accompanied by   

> MaxRetryError: Max retries exceeded with url: "uploadURL". (Caused by SSLError(SSLEOFError(8, 'EOF occurred in 
violation of protocol (_ssl.c:2384)'))).      

2 - When retrying upload again, I get this  
> 'code': 'nameAlreadyExists',   'message': 'A file with the same name is currently being uploaded. Change the filename and try to save again.'     

Now, next step would be to delete the session via "DELETE https://sn3302.up.1drv.com/up/fe6987415ace7X4e1eF866337".   

My issue is 1st, what leads to this error and why is this inconsistent. I only encounter this error once in a while. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d409f771-fd62-e549-d581-aac009e79e8c
* Version Independent ID: fe646b3a-06f5-a269-47e6-b4ee693e5410
* Content: [Resumable file upload - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_createuploadsession.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createuploadsession.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
@siddharth-redseer
We could recommend trying to recover the current upload session, see documentation here
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#handle-upload-errors

If that does not work we recommend overriding the current upload session, you should not need to delete the session
