### ISSUE TITLE
Can't upload files which take longer than 24 hours using resumable upload

### ISSUE THREAD

**Issue by ncw** [OneDrive/onedrive-api-docs#1570]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I would like to be able to upload files which take longer than 24 hours to upload.

#### Observed Behavior

The resumable upload session expires after 24 hours with an error like this

    expiredToken: The access token has expired. It's valid from '2/23/2022 3:45:26 PM' and to '2/24/2022 3:45:26 PM'.

#### Steps to Reproduce

Create a [resumable upload](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online).

This has an [an expiry date](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#response-1) `expirationDateTime` which always seems to be 24 hours after the upload session starts.

This expiry date should probably move forwards each time a valid chunk is uploaded otherwise total upload time is limited to 24h.

This was originally reported [in the rclone forum](https://forum.rclone.org/t/one-drive-failed-to-copy-unauthenticated-expired-token-the-access-token-has-expired/29425/25)

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@ncw What size is the file? is your connection speed slow? could you clarify the scenario so that we can understand it better

**Comment by ncw** [comment]
The file was 213GB and the internet speed less than the ~20 Mbit/s needed to upload the file in less than 24h.

There are loads more details in the forum thread I linked above if you are interested.
