### ISSUE TITLE
Msgraph api throwing error while accessing onedrive

### ISSUE THREAD

**Issue by nagnagendra** [OneDrive/onedrive-api-docs#1572]
I created a new user in microsoft admin center assigned a license(office365 E3).

While accessing onedrive by using client_credentials flow, i'm getting following error.
Graph API : https://graph.microsoft.com/v1.0/users/{user_id}/drive
{
    "error": {
        "code": "invalidRequest",
        "message": "Call was made to the default drive, which is not supported for apponly tokens.",
        "innerError": {
            "date": "2022-03-11T16:07:43",
            "request-id": "2e974e24-50d0-4b3b-b0b2-bb54d0439cbf",
            "client-request-id": "2e974e24-50d0-4b3b-b0b2-bb54d0439cbf"
        }
    }
}

I logged into the user account onedrive is displaying and able to add folders/files.

But accessing by using onedrive api, i'm getting error. Same api is working for different users of same license type.

Please provide the solution/ provide an alternative way to get the response by using app only token.

**Comment by k-tsoi** [comment]
@nagnagendra this looks like an issue with MSGraph routing, please reach out to the MSGraph team
