### ISSUE TITLE
FileHandler is visible in Teams Application's "files" tab.

### ISSUE THREAD

**Issue by Mandar-kanade** [OneDrive/onedrive-api-docs#1576]
We have a customized file opening solution that uses FileHandler integration for opening files from onedrive and sharepoints document library. Recently we have observed that FileHandler was visible in Teams Application's(Web view and Desktop app) "Files" tab also. This behaviour is inconsistent as it is only visible for some users in our tenants. 

This behaviour only observed on Microsoft Teams Version 1.5.00.5967 (64-bit).
#### Category
- [x] Question
- [x] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

> According to documentation [here ](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online)of FileHandler, it should only be visible on sharepoint and onedrive. Is this an upcoming feature for Teams as well?

#### Observed Behavior

> File handler is visible on Teams Files tab for some users in our tenant.

**Comment by Mandar-kanade** [comment]
@k-tsoi, Yes it is working as expected in OneDrive and SharePoint. Only few users in our tenant are experiencing FileHandler experience in Teams "Files" tab.

**Comment by JeremyKelley** [comment]
This should be available to all users in the latest version of Teams, is this still only showing up for some users?
