### ISSUE TITLE
Files are corrupted sometimes when uploaded with multipart uploads

### ISSUE THREAD

**Issue by ncw** [OneDrive/onedrive-api-docs#1577]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Multipart uploads complete without corrupting data

#### Observed Behavior

Sometimes (maybe one time in 20) multipart uploads of a 128MiB file get corrupted.

I know they are corrupted because the SHA1 that onedrive reports is different to the local one.

Downloading the file from the web interface reveals that a portion of it has been replaced with what appears to be base64 encoded data.

Attached is a log which created the corrupted SHA1 - this has a full HTTP header dump in (it just doesn't have the uploaded data as it is rather large).

[upload-thrasher-error.log](https://github.com/OneDrive/onedrive-api-docs/files/8420622/upload-thrasher-error.log)

For comparison here is a log which was successful

[upload-thrasher-ok.log](https://github.com/OneDrive/onedrive-api-docs/files/8420625/upload-thrasher-ok.log)

I've diffed those logs extensively and I can't see anything significantly different between them other than IDs and different onedrive endpoints.

Here is what the corrupted data looks like: 
[corruption.txt](https://github.com/OneDrive/onedrive-api-docs/files/8420632/corruption.txt)

This just overwrites a part of the file.

I don't seem to be able to attach the original and the corrupted file (as downloaded from onedrive web interface) for some reason - I have these and can share them with you if you want.

Here is a hex diff of the original and the corrupted file showing the insertion of the base64 data and the position: 
[hexdiff.diff.txt](https://github.com/OneDrive/onedrive-api-docs/files/8420652/hexdiff.diff.txt)

#### Steps to Reproduce

I reproduced this with rclone, uploading 128 MiB files using this script. ~~I haven't tried to reproduce this with a different tool so this could conceivably be a bug in rclone. I think this is unlikely however since rclone users didn't used to see this bug, and now with the same version of rclone they are seeing this bug, indicating a change in Onedrive is the cause rather than rclone. I also can think of no conceivable mechanism rclone would write several kilobytes of base 64 encoded data.~~

Update: this has been reproduced uploading files with the onedrive web interface too (see comments below) so likely affects **all** onedrive users.

```
!/bin/bash

size=134217728
destination=TestOneDrive:thrashfiles/

for round in $(seq 100); do
    name="test-${round}-${RANDOM}${RANDOM}${RANDOM}.bin"
    echo
    echo --------------- $(date -Is) - round $round - $name ------------------
    echo

    dd if=/dev/urandom of=$name bs=1M count=$(($size/1048576+1))
    truncate -s $size $name
    sha1sum $name

    rclone --low-level-retries 1 --retries 1 -vv --dump responses copy "${name}" "${destination}"
    error=$?

    if [ $error -ne 0 ]; then
       echo "ERROR $error on $name"
    else
	rm $name
	rclone -v deletefile "${destination}${name}"
    fi
       
    sleep 5
done
```

This was originally reported on the rclone forum: https://forum.rclone.org/t/onedrive-sync-never-completes-with-sha-1-corrupted-transfer-with-latest-rclone/29884/

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ncw** [comment]
I managed to reproduce this problem with rclone v1.53.2 using the binary released on 2020-10-26

This in my mind makes it increasingly likely this is a onedrive problem and not an rclone problem since it is only recently people have been reporting this problem in the forum.

```
$ ./rclone-v1.53.2 version
rclone v1.53.2
- os/arch: linux/amd64
- go version: go1.15.3
```

**Comment by ncw** [comment]
When trying to replicate the problem this morning (10:00 UTC) I note that it is taking more like 200 attempts to replicate the problem, wheras when I tried at 17:00 UTC it seemed more like 1 in 20. Rclone users have noted that the problem occurs more often when ondrive is busy which is another data point for you.

**Comment by ificator** [comment]
Thank you for your thorough analysis @ncw - do you happen to have an upload log and corresponding diff? It looks like the diff you provided in the original issue description was for an upload other than that of the upload-thrasher-error.log. I'd like to see if the unexpected data aligns with a single chunk.

**Comment by ncw** [comment]
I think the `hexdiff.diff.txt` file should be the correct one - it was generated with

    diff -u <(hd test-14-130091289123.original.bin) <(hd test-14-130091289123.broken.bin) > hexdiff.diff.txt 

I just double checked that gives the same output.

Here is a diff just showing the first 3 lines of the hex dump - the base64 data seems to start at 0x01a6fff6 offset from the start of the file approx which doesn't quite line up to any block boundaries that I can work out :-( (That was my thought too)

```
--- /dev/fd/63	2022-04-06 23:06:14.943792443 +0100
+++ /dev/fd/62	2022-04-06 23:06:14.943792443 +0100
@@ -1732605,775 +1732605,775 @@
 01a6ffc0  91 13 7a f9 d9 10 1f 64  f3 d6 5c 7b fc 8b 51 7d  |..z....d..\{..Q}|
 01a6ffd0  88 d4 94 fe 04 8a 0d 80  ee f0 7b a3 c5 bb 99 10  |..........{.....|
 01a6ffe0  6d 3f ae 5f 29 d8 d5 41  85 61 88 4f de 17 c5 fe  |m?._)..A.a.O....|
-01a6fff0  e8 d7 fe 52 80 8f 6e 85  82 54 4f 3d 9f d3 22 cf  |...R..n..TO=..".|
-01a70000  a7 3b 0b 19 08 7b fc 44  55 76 35 aa 79 6c ba 36  |.;...{.DUv5.yl.6|
-01a70010  a9 3d 3e 8c 6e 9f 5d dc  ff 26 2d 04 17 04 76 5c  |.=>.n.]..&-...v\|
+01a6fff0  e8 d7 fe 52 80 8f 6e 56  57 6a 7a 4c 67 39 77 32  |...R..nVWjzLg9w2|
+01a70000  36 56 44 6c 61 63 75 6d  53 4b 6e 54 2f 6a 30 7a  |6VDlacumSKnT/j0z|
+01a70010  55 43 76 56 31 33 4d 44  4a 45 38 51 59 6a 30 78  |UCvV13MDJE8QYj0x|
```

I put the original files, logs and analysis here: https://pub.rclone.org/onedrive-corruption/

There are further corruption events in the sub directories `v1.58.0-empty` and `v1.53.2` which were done with different versions of rclone and the `-empty` variant was done with all 0 files to see if the base64 intrusion looked any different (it didn't). All the ones in the main directory refer to the same files as in this issue. The `corruption-decodedX.bin` files are the base64 data decoded at the 4 possible offsets to see if the data looked significant. I couldn't see anything and I couldn't find the data in the original file.

**Comment by ificator** [comment]
And the corruption length is a nice power-of-2 (65535) which always makes me suspicious...

**Comment by ncw** [comment]
In the files we've seen the corruption is

1. Base64 data
2. A few kilobytes but variable in length
3. Doesn't seem to align to any block boundaries
4. Decodes to random or encrypted data

That's all I've found out so far.

Did you manage to replicate the problem?

**Comment by rleeden** [comment]
I have also been experiencing this issue, and have contributed to the rclone forum discussing this issue.

During testing this morning, I still see the problem. I created a random test hierarchy of 100 files containing random data between 128M and 256M, and uploaded this to OneDrive via the web interface.

Checking the sha1sum of the original files and the files on OneDrive, I see that 16 out of the 100 files have been corrupted.

Analysing the corrupted files, I see the same type of corruption as @ncw mentioned above - i.e. Base64 data, a few KB in size, and no obvious pattern or clue as to what the data is.

The data is available to view here: [scratch](https://1drv.ms/u/s!ApgjEHesi5p5lMMoIbelhX7OhbVb8A?e=10ksnX)

The folders are as follows:

- **Web Upload** : This is the folder that the 100 files were uploaded to via the OneDrive Web interface
- **ORIGINAL** : The original uncorrupted version of the 16 files that were corrupted
- **ONEDRIVE** : The 16 files after they have been corrupted
- **CORRUPT** : The base64 corrupt data extracted from the corrupted files (Note: file zujavul2q had two sections of corrupted data, so there are two files here)

**Comment by ificator** [comment]
I haven't been able to repro thus far - out of 50 attempts at uploading a 100MiB file all generated the expected hash. I'll keep experimenting..

**Comment by ificator** [comment]
I managed to get a repro - a small blob of base64 in my file. Is anyone able to reproduce the issue now?

**Comment by olefrost** [comment]
I reproduced 4 hours ago in CEST business hours, anything changed since?

**Comment by rleeden** [comment]
I have just repeated the test I did earlier comprising of 100 files sized between 128M and 256M. All files uploaded via the web interface, with no corrupt files.

So not able to reproduce the problem so far.

I will initiate another larger transfer of MP4 files using rclone now. This is a transfer that I've not been able to complete for the last few days, so I will see if this now works and report back.

**Comment by rleeden** [comment]
My rclone of large MP4 files has also completed successfully. So all looking good from my point of view. Thanks.

**Comment by ncw** [comment]
I left a transfer of 1000 128MiB files running over night and I can report that there were no corruptions in those.

So that is looking much better :-)

Can we know what you changed?

**Comment by ncw** [comment]
@ificator presumably there are thousands or millions of corrupted files people have uploaded to OneDrive over the period the problem was active. Will Microsoft be issuing a statement and/or contacting affected users?

**Comment by ts678** [comment]
[OneDrive high levels of uploaded file corruption](https://forum.duplicati.com/t/onedrive-high-levels-of-uploaded-file-corruption/13879) is what I saw with the Duplicati backup program, while another tester did not...
Base64-where-my-data-should-be usually took around 500 MB to 1 GB to get, and was very binary-even in location and length.
I'm not sure that multipart was involved, but I'm not the author of the code, just someone who tried finding a cause (but failed).

**Comment by ncw** [comment]
@ts678 thanks for the link. It looks like exactly this problem and you noticed it on 2 Feb 2022 which means the problem has been active for over 2 months.

Is it fixed for you now?

**Comment by ts678** [comment]
> which means the problem has been active for over 2 months.

I don't know if I would have seen it sooner, because I wasn't using OneDrive. I also stopped testing after finding it was broken.
Where the break was had never been clear enough to me (due to partial network logs) to try my luck claiming MS was broken.
Seeing no confirmatory reports using the software I was using (or a similar description anywhere on the Internet) didn't help...
Thank you for providing a similar description.

> Is it fixed for you now?

After restarting testing just now using two methods that might have experienced over four failures previously, I get none now, however that's kind of a statistical point so isn't totally satisfying. Still, my issue seems to be either fixed or much better, so far.

**Comment by ificator** [comment]
First, I want to personally thank you all for the very detailed investigation you performed. Getting issues with this level of detail helps our own investigations immensely. I cannot offer any more details other than we're still investigation on our side, and I'll update this issue once there's something to share.

**Comment by automaton82** [comment]
Thanks for investigating the issue. I am the one who originally reported the issue in the rclone forum, and am rather thankful rclone does a SHA-1 check to catch corruption. I do also wonder how many people's personal files were affected from just uploading via the UI.

As a note I am still experiencing this issue today, at least as of 10am EST with a large file. It failed with the same error and I am re-trying it overnight again tonight.

**Comment by ificator** [comment]
If any rclone user still sees failures of this nature I'd appreciate the rclone logs like "upload-thrasher-error.log" referenced in the issue description. Some idea where the file deviated will be useful as well.

**Comment by ncw** [comment]
> If any rclone user still sees failures of this nature I'd appreciate the rclone logs like "upload-thrasher-error.log" referenced in the issue description.

For any rclone users that want to generate a log like "upload-thrasher-error.log", it was generated with the `-vv --dump responses` flags which will dump the outgoing HTTP headers and the returning HTTP headers and bodies. The log is quite verbose though so you'll need to save it to a file.

**Comment by automaton82** [comment]
My overnight upload finished this morning with zero errors.

That's the first time it's had zero errors in a long time.

**Comment by klemperer** [comment]
> My overnight upload finished this morning with zero errors.
> 
> That's the first time it's had zero errors in a long time.

How did you fix the problems? I am using the latest rclone 1.58 and experiencing a lot of similar problems recently. Thanks for your reply.

**Comment by olefrost** [comment]
@klemperer I [replied](https://forum.rclone.org/t/onedrive-sync-never-completes-with-sha-1-corrupted-transfer-with-latest-rclone/29884/66) to [your post in the rclone forum](https://forum.rclone.org/t/onedrive-sync-never-completes-with-sha-1-corrupted-transfer-with-latest-rclone/29884/65)

**Comment by pgodwin** [comment]
Just came across this thread after my own uploads were corrupted. Uploaded 17/03/2022 7:59 PM. 
File on the left is from OneDrive, file on the right is the original:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1046558/163497045-60210a01-7993-46f9-a14c-fc7a542861a2.png">

**Comment by ncw** [comment]
@pgodwin that looks like if fits the problem in this issue which should be fixed now.

How did you upload the file?

**Comment by pgodwin** [comment]
> How did you upload the file?
Either via Cyberduck or directly in the browser. I uploaded about 400gb, and stupidly deleted it once it was uploaded successfully (or so I had thought).

**Comment by olefrost** [comment]
@ificator Here is a quick heads up, the issue with base64 injection still seems to occur for some users:
https://forum.rclone.org/t/onedrive-sync-never-completes-with-sha-1-corrupted-transfer-with-latest-rclone/29884/75
Note the "Subversion ... trigger ...timer" text at the end of the corruption.

We are now trying to reproduce while generating a log similar to "upload-thrasher-error.log". Anything specific you are looking for in the log? (to allow the affected user to easily filter out sensitive data and reduce size before posting)

**Comment by klemperer** [comment]
Attached here is the rclone log and the error could be found in line 3863.
[2022.log](https://github.com/OneDrive/onedrive-api-docs/files/8499026/2022.log)
Again I compared the original file and the corrupted file. It seems that the corruption begins at the same position but ends at different possition, and there are two parts of difference for these two files. No "Subversion...trigger...timer" text could be found this time.
![cc](https://user-images.githubusercontent.com/16667572/163656039-c62be265-80d6-4164-83c2-b7aa8aecf237.jpg)

**Comment by ncw** [comment]
@ificator the last of the rclone users says it is fixed for them now.

I'm hoping Microsoft will do a public announcement about this and/or email affected users who might have uploaded corrupted files and will need to re-upload them.

**Comment by pgodwin** [comment]
Yep, I tried to reproduce the issue this week, but was unable to - so hoping it's been resolved.

> I'm hoping Microsoft will do a public announcement about this and/or email affected users who might have uploaded corrupted files and will need to re-upload them.

I'd love to see it too @ncw, but I'm not going to hold my breath.
