### ISSUE TITLE
Shared File Download in OneDrive for Business

### ISSUE THREAD

**Issue by Sayron** [OneDrive/onedrive-api-docs#158]
I am trying to download a file from a shared folder that appears in the "Shared with me" folder of OneDrive for Business. I am using the following REST call to get the folder name and the files that appear in it:

```
https://{tenant}-my.sharepoint.com/_api/search/query?querytext='(SharedWithUsersOWSUSER:{UserAccountName} AND contentclass:STS_ListItem_MySiteDocumentLibrary)
```

and

```
https://{tenant}-my.sharepoint.com/_api/search/query?querytext='(ParentLink:{parentlink})'
```

with no issues. From the metadata supplied from these calls, I get the files in each directory and tried downloading them using the following GET request calls (note that "user1" is the person downloading the file, "user2" is the person that shared the file):

```
https://{tenant}-my.sharepoint.com/personal/user1_mydomain_com/_api/Web/GetFileByServerRelativeUrl('/personal/user2_mydomain_com/Documents/test/test1.docx')/$value
```

or

```
https://{tenant}-my.sharepoint.com/_api/v1.0/user2_mydomain_com/files/{fileid}
```

I have also attempted to use the new v2.0 calls, but they don't seem to support "Shared with me" folder/file access yet.

In all my attempts, I get a "Bad Request" or "Not found" error when trying to download a shared file. I have no issues downloading my own OneDrive for Business files using the following REST call:

```
https://{tenant}-my.sharepoint.com/personal/user_mydomain_com/_api/Web/GetFileByServerRelativeUrl('/personal/user_mydomain_com/Documents/User Folder/Test.htm')/$value
```

See:  http://stackoverflow.com/questions/30924549/how-to-download-a-shared-file-on-onedrive-for-business-with-the-rest-api

**Comment by rgregg** [comment]
Hi @Sayron,

As you mentioned, this is not supported in OneDrive API for Business yet. There is a request for this functionality on [UserVoice](http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7103641-allow-us-to-access-shared-files-on-sharepoint-and) though, which you may want to throw some votes on.

**Comment by jaycdave88** [comment]
@rgregg has this been implemented yet? Does OneDrive for Business have "shared with me" functionality yet? Also, is that functionality available on the `Microsoft Graph C# SDK`?

**Comment by rgregg** [comment]
Yes, [shared with me](https://dev.onedrive.com/drives/shared_with_me.htm) is available in the API by doing [`GET https://graph.microsoft.com/v1.0/me/drive/sharedWithMe`](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me/drive/sharedWithMe&method=GET&version=v1.0).

**Comment by anildbest83** [comment]
Functionality of 'Shared With Me' is working fine.
Is the functionality of Downloading Shared Files is implemented yet?

**Comment by rgregg** [comment]
Yes, you can use `GET /drives/{item.parentReference.id}/items/{item.id}/content` to download shared items.

**Comment by anildbest83** [comment]
@rgregg thanks its working fine..

**Comment by saikiran3103** [comment]
@rgregg , I tried  with the below url
https://graph.microsoft.com/beta/me/drive/sharedWithMe , in the response i did not get "id" under parent reference , i got only drive id in it"parentReference": {
          "driveId": "b!xTDMGJt6IEiuUTWPKWl2DIgyJcgGyIxOnPrOum8TeyfKUQRBWwV8TofsOMwgqCI2"
        }    , can you please suggest on this

**Comment by rgregg** [comment]
@saikiran3103: Sorry, that was a typo. I've corrected it above. It should have been item.parentReference.driveId

**Comment by saikiran3103** [comment]
@rgregg Thanks , I'm able to get the download urls for shared files now,
and is there any graph api call available to download a entire one drive for business personal  folder, currently I'm listing the children individually and  downloading using download url for each individual file,
the folders has sub folders in it ,so im making a sequence of calls, input to my application is shared link from the user. do we have any call available to download the entire folder?.Thanks

**Comment by vishwajeetsonkar** [comment]
@rgregg  I tried to do this [https://{tanent}-my.sharepoint.com/_api/v2.0/drives/b!0mHQ9NnEwEynXqBVIxckxNsO-hD5sOBAr62bn4ESNwBzY1UZsR9zQpAQ54-S8xbU/items/01CXPFAMMKYFPITQZXAFH3ISLKREEJFOHQ/content](url) 
but it gives me 404 am i missing some thing
plz help
