### ISSUE TITLE
Hi. I have the same issue like kazhhh commented on Apr 27, 2021 .I check but i don't see the answer . When trying to get the download link doing "GET /me/drive/items/{item-id}/content". i get a 200 back instead of 302 without any Location in the header.  I saw it is a known issue but I didn't find how to correct this.  Thank you for your help. Please help me.

### ISSUE THREAD

**Issue by Ndmanh123** [OneDrive/onedrive-api-docs#1587]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _Submission Guidelines:_
> - Questions and bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please provide clear reference(s) to the specific file(s) or URL('s).
> - Remember to include sufficient details and context.
> - If you have multiple issues, please submit them as separate issues so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

> For the above list, an empty checkbox is [ ]. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.
> If you have a question about Azure Active Directory, outside of issues with the documentation provided in the OneDrive Developer Center, please ask it here: https://stackoverflow.com/questions/tagged/azure-active-directory
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the observed behavior.
>
> Please also provide the following response headers corresponding to your request(s):
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug, please describe the steps to reproduce the bug in sufficient detail for another person to be able to reproduce it.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
[Per the docs](https://learn.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http) this is working now as you expect in Graph. Are you still seeing an issue?

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
