### ISSUE TITLE
expiry time for url for downloadable content?

### ISSUE THREAD

**Issue by phileo** [OneDrive/onedrive-api-docs#159]
According to this page:
https://github.com/OneDrive/onedrive-api-docs/blob/master/items/download.md

The url for downloadable content is valid only for a short time and should not be cached.  How short exactly is this short time?  In other words,
How long exactly is the downloadable url valid for, is it 12 hours, 24 hours, 7 days ?

**Comment by rgregg** [comment]
The best way to think of the @content.downloadUrl value is that you should use it _immediately_. If you need a URL that you can use for longer term or hold on to for hours, then you can use the `/drive/items/{item-id}/content` URL, which is a valid reference to download the file forever.

A number of factors are involved in the longevity of the download URL, so we aren't ready to commit to a duration of time that URL is considered valid or than saying a "short time."

**Comment by phileo** [comment]
how is  "/drive/items/{item-id}/content URL" different from @content.downloadUrl ?

**Comment by rgregg** [comment]
A couple of key differences:

* The API URL `/drive/items/{item-id}/content` requires authentication and is a generic link that is routed to the nearest available data center to serve the request.
* The API URL will always return a 302 redirect to the current `@content.downloadUrl` value when the request is made.
* The `@content.downloadUrl` is a direct link (no redirect) to a data center where the content of the file is available.
* The downloadUrl is not constant and will expire after a set period of time or when a file has been relocated within our data centers.
* The downloadUrl does not require authentication, hence why the URLs expire fairly quickly.

**Comment by phileo** [comment]
Thanks for the info.
One more question:  what does it mean if @content.downloadUrl is null ?

**Comment by rgregg** [comment]
Shouldn't ever be null, although we did recently roll out a change where @content.downloadUrl isn't returned by default for an item (this is a performance increase for the API). If you want the @content.downloadUrl value to be returned when enumerating items, you need to use the ?select= syntax to ask for the property names you're looking for, including @content.downloadUrl.

**Comment by phileo** [comment]
I tried this:

"https://api.onedrive.com/v1.0/drive/items/CF87200791751124%21136/?expand=children%28expand%3Dthumbnails%29%2Cthumbnails&select=@content.downloadUrl"  but I'm not seeing the content.downloadUrl in my response.

**Comment by phileo** [comment]
hmm.... just recently tried it again, and now the content.downloadUrl is magically appearing in the response.  
So if @content.downloadUrl is null, is it safe to assume that the service is down?

**Comment by ificator** [comment]
In this case there was a problem on our side - our apologies.

Generally the rules will be:
1. If you don't "select" anything you'll get "@content.downloadUrl" back (E.g. expand=thumbnails)
2. If you specifically "select" it you'll get "@content.downloadUrl" back (E.g. select=id,name,@content.downloadUrl&expand=thumbnails)
3. If you specify a "select" that does not include "@content.downloadUrl" you will NOT get "@content.downloadUrl" back (E.g. select=id,name&expand=thumbnails)
