### ISSUE TITLE
When I set download as action it redirects me to my website (query works)

### ISSUE THREAD

**Issue by stevan-borus** [OneDrive/onedrive-api-docs#1592]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I am setting the options object like this: 

```
const odOptions = {
      clientId: `${process.env.REACT_APP_ONE_DRIVE_CLIENT_ID}`,
      action: 'query',
      multiSelect: true,
      openInNewWindow: true,
      advanced: {
        redirectUri: 'http://localhost:3000',
        endpointHint: 'api.onedrive.com',
      },
      success: async (results: any) => {
        console.log(results);
      },
      cancel: () => {
        return null;
      },
      error: (error: any) => {
        console.log(error);
      },
    };
```

When I use it like this the picker opens as it should and I can select the files. Except that way I don't get any kind of url which I can use to download those files. I only get drive and file ids.

When I change the action to **download** I just get redirected to my website in that new window (no picker). The same thing happens with **share**. So only **query** as action works

Why is that happening?
Is there a way that I can download those files using drive and file ids with **query** action?

I need to download the files in order to upload them to a chat.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
Hello, the v7.2 Picker is no longer receiving updates, when possible please [migrate to the v8 picker](https://aka.ms/onedrive/file-picker), you can ask [questions for v8 picker in this issues list](https://github.com/OneDrive/samples/issues).
