### ISSUE TITLE
Unable to fetch "@microsoft.graph.sharedChanged" attribute when the delta include folder permission change

### ISSUE THREAD

**Issue by gilb77** [OneDrive/onedrive-api-docs#1594]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Steps to Reproduce

1. Create a folder with sharing on the folder 
2. Add a user with direct access to the folder
3. Fetch the latest changes for the user using delta changes with Prefer: hierarchicalsharing, deltashowremovedasdeleted, deltatraversepermissiongaps and deltashowsharingchanges. 
 then we received an  error with status code 410 (gone)"
{"error":{"code":"resyncRequired","message":"Resync required. Replace any local items with the server's version (including deletes) if you're sure that the service was up to date with your local changes when you last sync'd. Upload any local changes that the server doesn't know about.","innerError":{"date":"2022-06-07T13:26:02","request-id":"xxxx","client-request-id":"xxxx"}}}

Only when I remove deltashowsharingchanges from the header the response return ok but I cat retrieve the "@microsoft.graph.sharedChanged" attribute

#### Expected or Desired Behavior
The drive items returned in step 4, with the property @microsoft.graph.sharedChanged set to true 

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by JeremyKelley** [comment]
Hi Gil, in order for us to look into this issue more we'll need the request-d and client-request IDs along with the timestamp.

To make sure I'm following correctly, if you exclude deltashowsharingchanges you get a successful delta call including the results for the user that was added to the folder, but adding deltashowsharingchanges results in the 410 response?

**Comment by fsereno** [comment]
This still occurs, rather the response is 200 ok without  deltashowsharingchanges but there is no change returned. For a nested permission change, only the document library root is returned.
