### ISSUE TITLE
suggest to remove link to archived example

### ISSUE THREAD

**Issue by Josverl** [OneDrive/onedrive-api-docs#1595]
the first referenced example has been archived and should probably no longer be referenced.

* [GPXFileHandler](https://github.com/OfficeDev/GPX-FileHandler)

---- 

[ARCHIVED] GPX-FileHandler

> Note: This repo is archived and no longer actively maintained. Security vulnerabilities may exist in the project, or its dependencies. If you plan to reuse or run any code from this repo, be sure to perform appropriate security checks on the code or dependencies first. Do not use this project as the starting point of a production Office Add-in. Always start your production code by using the Office/SharePoint development workload in Visual Studio, or the [Yeoman generator for Office Add-ins](https://github.com/OfficeDev/generator-office), and follow security best practices as you develop the add-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54125c13-f269-89ae-ca8f-b37f2b049c00
* Version Independent ID: 71319f9d-c785-ee02-de6e-718b81bea58c
* Content: [Integrate with OneDrive file handlers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online)
* Content Source: [docs/file-handlers/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/file-handlers/index.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**
*

**Comment by patrick-rodgers** [comment]
Thanks, we've removed the link.
