### ISSUE TITLE
File Picker 7.2: Error on tab "Photos"

### ISSUE THREAD

**Issue by jonasgaiswinkler** [OneDrive/onedrive-api-docs#1598]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

"Photos" tab in File Picker 7.2 (js) shows photo gallery.

#### Observed Behavior

Error: Something went wrong. Please try again or refresh the page.

![image](https://user-images.githubusercontent.com/19706825/173946677-21f4e63e-a07a-48bc-aa5a-68aa40765dfb.png)

Error message in console:

`Uncaught (in promise) ItemOperationError: Page size is not defined, we cannot generate page keys for photos itemset!`

"My files" tab works as expected.

#### Steps to Reproduce

Clicking on the "Photos" tab after opening the file picker. My file picker config:

`{
          clientId: msalConfig.auth.clientId,
          action: "query",
          multiSelect: true,
          advanced: {
            redirectUri: msalConfig.auth.odRedirectUri,
            endpointHint: "api.onedrive.com",
            queryParameters: "expand=thumbnails",
            loginHint: context.rootState.msal.username,
            isConsumerAccount: true,
            filter: "photo,video,.heic,.mov,.jpg,.jpeg,.png",
          }`

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by patrick-rodgers** [comment]
Hello, the v7.2 Picker is no longer receiving updates, when possible please [migrate to the v8 picker](https://aka.ms/onedrive/file-picker), you can ask [questions for v8 picker in this issues list](https://github.com/OneDrive/samples/issues).
