### ISSUE TITLE
cTag for folders

### ISSUE THREAD

**Issue by kekolab** [OneDrive/onedrive-api-docs#1599]
In the document unclear information is given.
In the **Property** paragraph it's written:

| Property | Type | Description |
| :-- | :-- | :-- |
| cTag | String | An eTag for the content of the item. This eTag is not changed if only the metadata is changed. **Note** This property is not returned if the item is a folder. Read-only. |

At the end of the table there is written:
**Note**: The eTag and cTag properties work differently on containers (folders). The cTag value is modified when content or metadata of any descendant of the folder is changed. The eTag value is only modified when the folder's properties are changed, except for properties that are derived from descendants (like **childCount** or **lastModifiedDateTime**).

In the **Remarks** section, it's written:
In OneDrive for Business or SharePoint document libraries, the cTag property is not returned, if the driveItem has a folder facet.

It seems a bit confusing about whether the cTag/eTag are returned for folders and for Onedrive personal/Onedrive business/Sharepoint

Regards,
Gianluca

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8afe01-1167-52b4-b2b4-47cbee8ddccf
* Version Independent ID: 56ef57eb-5eed-75ef-36a5-8e38fa7dd075
* Content: [DriveItem - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online)
* Content Source: [docs/rest-api/resources/driveitem.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/driveitem.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by patrick-rodgers** [comment]
Upon review the wording seems that in OneDrive for Business and SharePoint cTag is not returned for folders. Meaning it would be for OneDrive consumer folders.

Regardless as we work to a single tech stack for all files services these differences will no longer apply.
