### ISSUE TITLE
change list information question

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#16]
I move a folder into other folder

the change list return will contain all the sibling folder.

e.g.
folder A contain B, C, D folder
I move folder E into A
the changelist return will contain B, C, D

I think it is strange to get change about B, C, D

Is this a bug?

Thanks.

**Comment by daspek** [comment]
Did the server return the '@changes.resync' property after the folder move? If so, this is expected. When you move a folder into or out of your sync scope, we require you to resync, so you'll see all the contents under A again. I'll update the documentation to be more clear about this behavior.

**Comment by mikechiu1012** [comment]
yes, but if I create a folder inside the sync scope, the resync is not returned.
so the behaviour is different between create folder and move folder?

 in sum:
1) create a new folder, no resync, only this new folder in change list.
2) move a folder, resync returned and all the contents in change list in the same folder.

I think for the sync scope folder, it looks like the same thing, so the different result is really confused.

Thanks for quick response and if there are more example and scenario listed in the documents will be a grateful help! :)

**Comment by rgregg** [comment]
The behavior is different unfortunately. Due to the way we track sync tokens, the move scenario does cause the resync logic to trigger. When you see the **@changes.resync** property you'll need to follow the resync guidance in the documentation.
