### ISSUE TITLE
Describing  the size limit converting a pttx file to pdf "maxFileSizeExceeded"

### ISSUE THREAD

**Issue by FMRb** [OneDrive/onedrive-api-docs#1601]
The documentation doesn't describe the size limit for converting a file like `.pttx` to `pdf`. The response from the API comes with a message like this one:

```
Microsoft convert format API error. Status: 406 Message: {"error":{
"code": "notSupported",
"message": "Error from Office Service. Url=https://pptcs.officeapps.live.com/document/export/pdf HttpCode=UnsupportedMediaType cert=subject:;thumbprint: ResponseHeaders=X-ErrorCode: Service_FileTooBigToDownload\r\nX-ErrorCategory: NotSupported\r\nX-IsRetriable: False\r\nX-FileDownloadTimeInMs: 0\r\nX-ClientCorrelationId: xxxxx\r\nX-ServiceCorrelationId: xxxx\r\nCache-Control: private\r\nDate: Tue, 28 Jun 2022 08:43:05 GMT\r\nServer: Microsoft-IIS/10.0\r\nX-AspNet-Version: 4.0.30319\r\nX-Powered-By: ASP.NET\r\n",
"innererror": {
"code": "maxFileSizeExceeded"
}
}}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46acaeca-c7f2-1013-239e-93853818f3d7
* Version Independent ID: 8b42fae5-53c9-f8c3-b88f-f2a087b23f8c
* Content: [Convert to other formats - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_get_content_format.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get_content_format.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by JeremyKelley** [comment]
Thanks for the feedback on this error!  Unfortunately there isn't a set size limit that can be documented, the service that does the conversion is actually sensitive to content complexity as much as content size, so you may have a smaller file that could still get an error based on having more complex content.

We will take another look at the docs though to see if there's anything more we can add.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
