### ISSUE TITLE
Share drive items using Client Credentials work flow access token.

### ISSUE THREAD

**Issue by atulckrishna** [OneDrive/onedrive-api-docs#1604]
I have generated access token for my app using client credentials work flow(By using Client Secret , Client_Id and Tenant_Id).

Now when i am trying to share the drive item from A user with B user using this access token then i am getting below error
"code": "invalidRequest",
        "message": "The provided drive id appears to be malformed, or does not represent a valid drive.",

Both A and B user already granted access to the app.

So Is there any way that i can share the files from A user with B user using the access token generated through client credentials workflow ?

**Comment by JeremyKelley** [comment]
Please provide a Request ID and Timestamp for the failing request.  Also, can you specify which API you are using to share the file?

**Comment by atulckrishna** [comment]
@JeremyKelley 
Thanks for your quick response!
Here is the info you needed ..

Request ID : "1c45686d-b699-4b0b-b1f9-f921667134c0"
Timestamp :  "2022-07-07T07:52:20"
Api I am calling is :  POST /drives/{drive-id}/items/{item-id}/invite
https://graph.microsoft.com/v1.0/drives/{drive-id of User A}/items/{item-id of user A}/invite

Also User A and User B are not part of Azure Active Directory users in which i have created the app but they signed into app and grant permissions to app as while setting the app i have selected option that 'Accounts in any organizational directory and personal Microsoft accounts' can sign into app.

So does we share files between any users using the client_credentials access token who signed into app and grant permissions to app ?
Or
It will work for only those users who are part of the directory in which we have created app ? If this is the case then does we need any subscription so that users created in directory can access OneDrive and share files using API and client_crednetials access token ? As currently I have 'Azure AD Free' subscription or it will work with 'Azure AD Free' subscription and i just need to create users in directory and try sharing files using those users id's.

**Comment by atulckrishna** [comment]
@JeremyKelley 

Can you please check my above message with all info you need to check it further ? 
Any update will be very helpful for me to proceed with OneDrive Sharing Api's implementation in my site.

Thanks

**Comment by patrick-rodgers** [comment]
I believe the [createLink API](https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http) is the newer method to share - can you give that a test?

**Comment by t135792468** [comment]
createLink API 当5分钟调用大于十次，就会出现 too many request的错误，我的需求远远大于这个值，应该如何解决这个问题。

**Comment by t135792468** [comment]
When the createLink API is called more than 10 times in 5 minutes, there are too many requests. My requirements are far greater than this value. How should I solve this problem?
