### ISSUE TITLE
[Bug] OneDrive 7.2 File Picker options.advanced.navigation.sourceTypes no longer correctly filters out other source types

### ISSUE THREAD

**Issue by jbyt1** [OneDrive/onedrive-api-docs#1608]
Using options.advanced.navigation.sourceTypes no longer removes excluded types from the navigation bar.

Previously if I did not include "Recents" or "Sites" in the array the recents did not display and sites were not shown in the quick access navigation bar group.
Suddenly these have started appearing.
https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file
https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#customize-capabilities

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Providing options.advanced.navigation.sourceTypes should ONLY include these source types in the navigation bar.\
I want to be able to display the file picker without SharePoint sites being displayed.

#### Observed Behavior

All source types are shown in the navigation bar despite not being added.
This seems to have changed in the last week or so.

With only "OneDrive" specified for source types I get this.
The styling also changed recently but I put that down to some cross over coming from the v8.0 update.

![image](https://user-images.githubusercontent.com/109130057/178858474-38b8233d-3e19-4acf-b188-1eb79b1c4b76.png)

#### Steps to Reproduce

Assign a source type to the file picker options.
Confirm all source types are displayed in the navigation bar and not excluded.

```
var odOptions = {
  clientId: clientId,
  openInNewWindow: true,
  action: "query",
  viewType: "files",
  advanced: {
      navigation: {
          sourceTypes: "OneDrive"
      },
      accessToken: authToken,
      redirectUri: redirectUri
  },
  multiSelect: allowMultiSelect,
  success: function(files) { pickedFiles(callback, files) },
  cancel: function() { },
  error: function(error) { onError(error) }
}

OneDrive.open(odOptions);
```

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ThomasMichon** [comment]
@jbyt1 Thanks for reporting this! Yes, `sourceTypes` was overlooked when we rolled out the improved 8.0-style experience in our 7.2 contract flow.

We'll have a fix rolled out for this issue in about a month.

**Comment by ThomasMichon** [comment]
@jbyt1 The fix for this issue should be fully rolled out to all customers. Please help confirm that the issue was resolved for your case!

**Comment by patrick-rodgers** [comment]
Hello, the v7.2 Picker is no longer receiving updates, when possible please [migrate to the v8 picker](https://aka.ms/onedrive/file-picker), you can ask [questions for v8 picker in this issues list](https://github.com/OneDrive/samples/issues).
