### ISSUE TITLE
eTag behavior

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#161]
According to the spec, the eTag should change when the metadata or the content of an item changes.
But experimentally the eTag changes only when the items's metadata changes.
Should I expect this behaviour to change in the future ? 
In fact, as it is, it is really useful because it enables metadata caching.

**Comment by daspek** [comment]
The eTag should definitely change if the content changes. I just tried it on one of my files and it worked. Can you tell me more about what you're seeing?

**Comment by skilion** [comment]
Sorry, I forgot to mention that the my test was performed on a **folder**.
If I edit or add a file inside a folder its eTag remains the same.

**Comment by daspek** [comment]
Ah, that is expected then. The eTag of the folder only covers the metadata on the folder itself, not the files inside of it (or their content). The cTag of the folder, though, will change whenever anything under the folder changes (folder metadata, or metadata or content of any descendants).

**Comment by rgregg** [comment]
I'll update the docs to include more details on how cTag and eTag work.

**Comment by rgregg** [comment]
Closing out old issues. If this continues to be an issue, please reopen and provide additional details.
