### ISSUE TITLE
Inconsistency in Graph user API and outlook API

### ISSUE THREAD

**Issue by shayan-brcm** [OneDrive/onedrive-api-docs#1610]
#### Category
- [ x] Question
- [ ] Documentation issue
- [ x] Bug

#### Expected or Desired Behavior

We used below graph API to fetch user service subscription like exchange, sharepoint etc

https://graph.microsoft.com/v1.0/users/user_id?$select=assignedPlans

if service is enabled then we consider that user have subscription to that particular service otherwise dont. 

It is expected that if user does not have exchange service then user should not have any outlook emails

#### Observed Behavior

Recently we have found one user for which capabilityStatus shows deleted/disabled but when we made call to outlook for same user we got response

https://outlook.office365.com/api/v2.0/Users('user_email')/Messages

#### Steps to Reproduce
We found it randomly

Is there any inconsitency between these 2 API's or is there any different way to discover user subscriptions?
Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by JeremyKelley** [comment]
Unfortunately we don't have any way to route this to the appropriate Microsoft Graph or Outlook teams from our GitHub repository.  I would recommend going to the [Microsoft Graph Docs](https://github.com/microsoftgraph/microsoft-graph-docs/issues) repo instead and logging the issue there.
