### ISSUE TITLE
General exception when inviting users to drive item.

### ISSUE THREAD

**Issue by zz-kivo** [OneDrive/onedrive-api-docs#1614]
I'm receiving 500 http status code with a "generalException" code in the body when attempting to invite external users to edit a document through the /v1.0/drives/{driveId}/items/{itemId}/invite endpoint. These users are specifically ones that do not have a microsoft or azure ad account.

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
The invite post should succeed with a 200. 

If the recipient email has an azure AD or microsoft account, they should be able to sign in to edit the document. Otherwise, the user should receive a one time password which can be used to edit the document.

Users that have a microsoft account should be able to edit the documents on the desktop office applications.

#### Observed Behavior
If the email has a microsoft account, the call succeeds and they can access the document online. The user's account is added as an external guest with the azure active directory. If the user is on a PC they can edit the document locally. If the user is on a mac, they cannot edit the document in the desktop version and instead see a message saying "Your account doesn't allow editing on a Mac". This is probably a separate issue and if it's not related it would be helpful to know where to post this issue.

If the email does not have a microsoft account, the endpoint returns a 500 code with a "generalException" code in the body.

#### Steps to Reproduce
POST https://graph.microsoft.com/v1.0/drives/{driveId}/items/{itemId}/invite

example body:
```
{
    "requireSignIn": true,
    "sendInvitation": false,
    "roles": [
        "write"
    ],
    "recipients": [
        {
            "email": "AnEmailWithoutAMicrosoftAccount@gmail.com"
        }
    ]
}
```

example error response:
```
{
    "error": {
        "code": "generalException",
        "message": "An unspecified error has occurred.",
        "innerError": {
            "date": "2022-08-03T17:47:09",
            "request-id": "c7c579c9-720e-4d96-849b-344dd2b78b6a",
            "client-request-id": "c7c579c9-720e-4d96-849b-344dd2b78b6a"
        }
    }
}
```

additional failed request-ids:
5d6b311c-91be-4d50-8aef-414eca4a2eac
c07d32fe-87c9-4d1d-8b68-7f5f28850c21

I believe this has something to do with the b2b integration. Here the settings I have in various areas.

I have b2b integrations turned on for the sharepoint site using the powershell commands listed here: https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration

In Azure AD:
- I have Azure Active Directory, Microsoft Account, and Email one-time passcode all enabled as identity providers
- I have "Allow invitations to be sent to any domain" for collaboration restrictions
- Anyone in the org can invite guests and guests have same access as members

In the sharepoint admin:
- I have the site and organization settings synced
- I have most permissive external sharing for sharepoint and one drive
- Default link set as specific user
- Edit permission as default for links

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by k-tsoi** [comment]
@zz-kivo is this issue still occurring? if so could you please provide new correlationIDs and timestamps of the falling request

**Comment by MarioVitale** [comment]
Hello, I have the same problem using the [MS Graph API Add Permissions]( https://learn.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http) on a SharePoint site.
My application uses an app registration with the **Sites.ReadWrite.All** permissions allowing to upload and share a file using the Graph API. The SharePoint configuration is as follows:
<img width="628" alt="image" src="https://github.com/OneDrive/onedrive-api-docs/assets/25910212/f2e0c82b-b131-45fd-98e7-de93e6820ace">

I encountered 2 issues while developing. The first is that when the "**Allow only users in specific security groups to share externally**" flag is enabled, the app registration can no longer share files, even if it is present within one of the allowed groups. Removing the flag restores the sharing functionality.
<img width="747" alt="image" src="https://github.com/OneDrive/onedrive-api-docs/assets/25910212/43843b76-43c0-4ccd-a388-2bb15371a413">
<img width="368" alt="image" src="https://github.com/OneDrive/onedrive-api-docs/assets/25910212/fb75206f-c3ba-4da2-b425-67ba2770e897">

The second problem is related to sharing itself. Currently, sharing only works with Microsoft Work Accounts. If a "non-Microsoft" account is used, I receive a 500 error with code "**generalException**" and message "**An unspecified error has occurred.**".

What can I check? Are there any configurations in the tenant or in the API that I can verify?

Thank you
