### ISSUE TITLE
Is deletion of one Note Notebooks recommended using this approach?

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [OneDrive/onedrive-api-docs#1625]
We all know that one Note notebooks are stored in the one-Drive, and we can delete them using drive/driveID/items/itemID .

is this the recommended approach to delete the one Note notebook ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1972b81a-297f-08b6-274a-60ecda82a218
* Version Independent ID: f0da765f-de5f-e6a1-a17c-c02dcfabd3ae
* Content: [Delete a file or folder - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delete?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_delete.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delete.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by k-tsoi** [comment]
We recommend using the APIs provided by the Onenote team via MSGraph.
You can read more about these APIs here: https://learn.microsoft.com/en-us/graph/api/resources/onenote-api-overview?view=graph-rest-1.0
