### ISSUE TITLE
404 item not found on /me/drive/

### ISSUE THREAD

**Issue by zeroday17** [OneDrive/onedrive-api-docs#1628]
Developer.microsoft.com graph-explorer shows 

{
    "error": {
        "code": "itemNotFound",
        "message": "Item not found",
        "innerError": {
            "date": "2022-09-18T02:21:45",
            "request-id": "dc6b81ef-f007-4c54-9914-ee1ed5d01b30",
            "client-request-id": "bf17bc4a-6fc9-f73d-e099-538568226436"
        }
    }
}

**Comment by k-tsoi** [comment]
@zeroday17 could you provide more details about this file, does it show up in the UI? but is not returning via the aPI?
what API are you call?
if this is still occurring please provide a requestId and timestamp of a recent failure
