### ISSUE TITLE
Outdated documentation on API call itemActivity?

### ISSUE THREAD

**Issue by billflu** [OneDrive/onedrive-api-docs#1629]
I was looking into this and wondering if the ItemActivity resource type will ever be implemented. The last substantial edit to [this document is from 2017](https://github.com/OneDrive/onedrive-api-docs/commits/live/docs/rest-api/resources/itemactivity.md), when it was added that this is in “limited Preview”. I used the  [Graph API Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), but can only find a similar call referenced with “OLD” in the title (see the image below). From what I’m gathering, it may have never came out of Preview and was scrapped. It could be something which is already deprecated.

![itemactivity](https://user-images.githubusercontent.com/1281248/192055979-28d5d1d8-44c7-4332-8571-c5c325c65fb9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9f88ddd-0fc6-e19e-656e-db3d6b72029b
* Version Independent ID: f1b9a8cb-5c5e-0b0a-077e-cb406a274749
* Content: [ItemActivity - OneDrive API - OneDrive dev center](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/resources/itemactivity?view=odsp-graph-online)
* Content Source: [docs/rest-api/resources/itemactivity.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/itemactivity.md)
* Service: **one-drive**
* GitHub Login: @daspek
* Microsoft Alias: **dspektor**

**Comment by patrick-rodgers** [comment]
I believe [getActivitiesByInterval](https://learn.microsoft.com/graph/api/itemactivity-getbyinterval) is what you want.

We are working to clean up older documentation, but for the latest information you can always refer to the graph docs.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
