### ISSUE TITLE
WL.logout() callback function always execute after 30 seconds.

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#163]
When I use WL.logout().then( callback ), every times the callback function will execute after 30 seconds. It's not reasonable.

The origin issue link is: https://github.com/OneDrive/onedrive-api-docs/issues/113#issuecomment-115832444

**Comment by rgregg** [comment]
Judging by the syntax, is this the JavaScript SDK you're using?

**Comment by benjaminliugang** [comment]
Yes, it's JavaScript SDK.

**Comment by jscaria** [comment]
Thanks @benjaminliugang.   We're looking into this.

**Comment by jscaria** [comment]
@benjaminliugang - this should be fixed.   If you can still reproduce this bug, please reopen this issue.

**Comment by benjaminliugang** [comment]
Hi @jscaria, how can I get the latest code to test? 
Because when I use http://js.live.net/v5.0/wl.js library to test, the issue still can reproduce.

**Comment by jscaria** [comment]
@benjaminliugang: can you confirm that you don't have an older reference cached somewhere in your browser?   I can't seem to repro the issue anymore when referencing http://js.live.net/v5.0/wl.js.

**Comment by benjaminliugang** [comment]
Hi @jscaria, checked again in my project, with bower cache cleaned, it works well now. Thanks a lot!
