### ISSUE TITLE
Is there any api could add or modify caption of a video file?

### ISSUE THREAD

**Issue by gamekingv** [OneDrive/onedrive-api-docs#1630]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I look through the docs and could not find any api about caption of video file. Is it possible to add or modify caption of a video file?

**Comment by patrick-rodgers** [comment]
No, there is currently no dedicated API to set the caption on videos.

You can get the [transcript for meeting recordings](https://learn.microsoft.com/en-us/graph/api/calltranscript-get)

As well you can [update the captions for files hosted in Stream](https://learn.microsoft.com/en-us/stream/portal-add-subtitles-captions#upload-a-subtitle-or-caption-file-to-an-existing-video), and you can use the [files API](https://learn.microsoft.com/en-us/graph/api/resources/driveitem) operations to update the associated vtt files.

**Comment by gamekingv** [comment]
> No, there is currently no dedicated API to set the caption on videos.
> 
> You can get the [transcript for meeting recordings](https://learn.microsoft.com/en-us/graph/api/calltranscript-get)
> 
> As well you can [update the captions for files hosted in Stream](https://learn.microsoft.com/en-us/stream/portal-add-subtitles-captions#upload-a-subtitle-or-caption-file-to-an-existing-video), and you can use the [files API](https://learn.microsoft.com/en-us/graph/api/resources/driveitem) operations to update the associated vtt files.

Oh, I see. Thank you for reply.
