### ISSUE TITLE
"The operation failed because the object does not support sharing."  

### ISSUE THREAD

**Issue by prattay56** [OneDrive/onedrive-api-docs#1631]
[unable to generate sharing links using Graph calls for SharePoint Library.  I am using this method 
<html>
<body>

Create link | POST /drive/items/{item-id}/createLink
-- | --
Reference https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online

</body>
</html>[Create link](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online)	POST /drive/items/{item-id}/createLink

EG :
https://graph.microsoft.com/v1.0/sites/1982b061-59fa-429a-91d2-3494330f67a2/drive/items/3/createLink

Response

{
    "error": {
        "code": "notSupported",
        "message": "The operation failed because the object does not support sharing.",
        "innerError": {
            "code": "objectNotSupported",
            "date": "2022-09-28T07:58:43",
            "request-id": "10ada8fa-a87f-4e3a-8359-ac3387313d8d",
            "client-request-id": "a69860dc-9b64-4c62-08d7-de27fceb9508"
        }
    }
}

Request Body

_{
  "type": "edit",
  "scope": "organization"
}_

]

![image](https://user-images.githubusercontent.com/74849664/192719793-a3f44845-73c9-4492-b0da-28fc60dd576f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69601057-a846-2eea-33b4-9e1760981e88
* Version Independent ID: 5cbaae53-7d99-8075-609a-30d82c9ad0c8
* Content: [Share a file with a link - OneDrive API - OneDrive dev center](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online#remarks)
* Content Source: [docs/rest-api/api/driveitem_createlink.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createlink.md)
* Service: **one-drive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by prattay56** [comment]
*Folow up *Hello Team, Is there any update on thi.

**Comment by prattay56** [comment]
Follow up
Hello Team, Is there any update on this.

**Comment by patrick-rodgers** [comment]
You can [review these common causes of failed sharing](https://learn.microsoft.com/en-us/sharepoint/sharepoint-onedrive-error-message) to see if any resolve your issue.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Comment by hasanradi93** [comment]
Anyone find a solution for this issue?

**Comment by MicahWW** [comment]
Was an answer ever found? In my specific case I'm trying to give access to the root of the Drive and it isn't working but it works when I share an item within the Drive.

```ps1
$params = @{
    recipients = @(
        @{ email = "jsmith@example.com" }
    )
    message = "Lorem ipsum dolor sit amet"
    requireSignIn = $true
    sendInvitation = $true
    roles = @( "read" )
}

$personDrive = Get-MgUserDefaultDrive -UserId jdoe@example.com
Invoke-MgInviteDriveItem -BodyParameter $params -DriveId $personDrive.Id -DriveItemId (Get-MgDriveRoot -DriveId $personDrive.Id).Id
```
