### ISSUE TITLE
FilePicker 8.0 Multi-tenant support

### ISSUE THREAD

**Issue by vpolovit** [OneDrive/onedrive-api-docs#1636]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

In File Picker 8.0 Documentation (https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/?view=odsp-graph-online), it mentioned support for multitenant:

>>> c. You may optionally configure this application for multitenant but this is outside the scope of this article

I could not find any additional documentation on how to use multitenant with FilePicker 8.0
I could not find any example on how to use File Picker 8.0 with multitenant. Its not in sample code (https://github.com/OneDrive/samples/tree/master/samples/file-picking).

**Comment by patrick-rodgers** [comment]
The AAD application defining the permissions used for authentication can be multi-tenant. The picker itself supports calling a single tenant per-launch.

Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
