### ISSUE TITLE
First Time Sync API - Unclear on process via Documentation. 

### ISSUE THREAD

**Issue by RaphaelUlysses** [OneDrive/onedrive-api-docs#1637]
Looking to see if there are exposed APIs to trigger the 'first time sync' against SPO/OD to fetch and download a repository. The documentation is unclear if it is expected to use the get-item, download-item APIs to individually list and download everything before using the sync API to match and maintain that sync. It appears that Onedrive.exe on Windows will initiate a first time sync which leads me to believe this exists, but there is no mention of it in the sync documentation, only how to maintain the sync. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f139d8af-bd5e-3289-daec-a101e7071fbf
* Version Independent ID: 69ddaa8b-120b-14e7-643e-dfa921d196fb
* Content: [Sync the contents of a drive - OneDrive API - OneDrive dev center](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_delta.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delta.md)
* Service: **one-drive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by patrick-rodgers** [comment]
You can find more information in this [article on scan guidance](https://aka.ms/scanguidance).

You would need to make an initial query to establish the baseline, then you can make additional delta queries in the future to determine changes from that initial query.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
