### ISSUE TITLE
download large .one file (5.6GB) encounter 503 http error

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1638]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

Recently we found that when we download large onenote, it returns error 503 and contain as static html page.

`GET /items/{item_id}/content`

And it already last for monthes, retry also can not solve this.

![image](https://user-images.githubusercontent.com/12619781/194509203-e0bb5f4a-0f95-4605-8f32-c2f3c75e0077.png)

What handles are expected after we recieve this message? 

Thank you.

**Comment by kashiftahir** [comment]
Hi @joewutaiwan , would you mind sharing a correlationId/timestamp for me to look up the logs. 503 generally means server is under duress, but i would expect this to be temporary and if you are seeing this consistently, we should debug.

**Comment by joewutaiwan** [comment]
@kashiftahir 

Thanks for reply

Here are entire response headers for APIs with specific item ID `01SB6GJOKDEOWDQCYMCNDLPHC5HZO6CHJH`

via GET `/drive/items/{item_id}` -> this works fine
```
Cache-Control:[no-store, no-cache] 
Client-Request-Id:[a73f73f4-1950-4505-ab64-cb9c02cc5f25] Content-Type:[application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8] 
Date:[Wed, 19 Oct 2022 05:54:42 GMT] 
Odata-Version:[4.0] 
Request-Id:[a73f73f4-1950-4505-ab64-cb9c02cc5f25] 
Strict-Transport-Security:[max-age=31536000] 
Vary:[Accept-Encoding] 
X-Ms-Ags-Diagnostic:[{"ServerInfo":{"DataCenter":"Korea Central","Slice":"E","Ring":"3","ScaleUnit":"001","RoleInstance":"SE1PEPF00003EAA"}}]]
```

but GET `/items/{item_id}/content` -> this case

```
Cache-Control:[no-store] 
Content-Length:[8060] 
Content-Type:[text/html] 
Date:[Wed, 19 Oct 2022 05:52:35 GMT] 
X-Azure-Externalerror:[0x80072efe,OriginConnectionAborted] 
X-Msedge-Ref:[Ref A: 3DB064E4F63F4A6183862C6692A678E8 Ref B: TPE30EDGE0507 Ref C: 2022-10-19T05:52:33Z]]

```

**Comment by ificator** [comment]
When you say "retry cannot resolve this" did you mean a full file download or did you use a range request to continue from your last byte?
