### ISSUE TITLE
OneDrive session timeout cannot back to file picker (JavaScript SDK)

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#164]
Reproduce steps:

a) Open two tabs for http://isdk.dev.live.com/dev/isdk/ISDK.aspx?category=scenarioGroup_core_concepts&index=0#
b) Click run button in one tab, and login with your oneDrive account, then the file picker dialog will popup
c) Switch to another tab, click sign out button to logout oneDrive
d) Back to the first tab, and click open button on file picker dialog
e) Click run button again, and login with your oneDrive account

Result:
The file picker dialog does not open

Expect result:
The file picker dialog should be opened

**Comment by jscaria** [comment]
@benjaminliugang - when you reproduce this issue, what error message do you see in the console in the first tab?

**Comment by benjaminliugang** [comment]
@jscaria - It always popup '[WL]WL.login: The popup is closed without receiving consent.' log when I try to open the file picker again.

**Comment by rgregg** [comment]
This should be resolved in the latest file picker (v6.0). If you continue to have problems, please reopen with additional details.
