### ISSUE TITLE
Consumer OneDrive: Delta query reporting zero for childCount property on all folder driveItems

### ISSUE THREAD

**Issue by turquoiseowl** [OneDrive/onedrive-api-docs#1641]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Running a delta query against a consumer OneDrive (onedrive.live.com) account.

Expecting the ```folder.childCount``` property of each json object representing the folder driveItems to accurately count the number of child driveItems in a folder.

#### Observed Behavior

The value for the ```folder.childCount``` property is zero for ALL folders, even though folders clearly contain driveItems enumerated within the same response.

Note that this only appears to be a proplem with consumer OneDrive; ODB works as expected.

Example ```delta``` json response extract below:

```
"value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "name": "root",
            "size": 16856,
            . . .
            "folder": {
                "childCount": 0,
                "view": {
                    "viewType": "thumbnails",
                    "sortBy": "name",
                    "sortOrder": "ascending"
                }
            },
            "root": {}
        },
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "name": "Documents",
            "size": 16851,
            "parentReference": {
                . . .
                "name": "root:",
                "path": "/drive/root:"
            },
            "fileSystemInfo": {
                "createdDateTime": "2022-07-26T20:47:25.733Z",
                "lastModifiedDateTime": "2022-07-26T20:47:25.733Z"
            },
            "folder": {
                "childCount": 0,
                "view": {
                    "viewType": "thumbnails",
                    "sortBy": "name",
                    "sortOrder": "ascending"
                }
            },
            "specialFolder": {
                "name": "documents"
            }
        },
        . . .
```

#### Steps to Reproduce

1. Open Graph Explorer and login to consumer MS account.
2. https://graph.microsoft.com/v1.0/me/drive/root/delta

I would be most grateful if someone would look into this.
Thank you.

**Comment by ificator** [comment]
Unfortunately it isn't an easy change to make this work at scale, but we do have some long-term work scheduled that may help.
