### ISSUE TITLE
File Picker v7.2 Session and Picker UI Reachability Problem

### ISSUE THREAD

**Issue by cangokceaslan** [OneDrive/onedrive-api-docs#1642]
Hi,

I have a problem with OneDrive File Picker v7.2 about showing files to user.

Problem occurs when another OneDrive tab is opened

![Ekran Resmi 2022-10-28 10 35 37](https://user-images.githubusercontent.com/48398625/198530719-65d759cd-732a-4c05-9cb1-2209bdf70660.png)

When I refresh it, it is showing the files on picker

![Ekran Resmi 2022-10-28 10 37 15](https://user-images.githubusercontent.com/48398625/198531039-287b2b19-2453-478d-aecb-f577b18637e3.png)

I think this is a session or cookie issue.

Thanks for help

**Comment by patrick-rodgers** [comment]
Hello, the v7.2 Picker is no longer receiving updates, when possible please [migrate to the v8 picker](https://aka.ms/onedrive/file-picker), you can ask [questions for v8 picker in this issues list](https://github.com/OneDrive/samples/issues).
