### ISSUE TITLE
Scopes does not accept Files.ReadWrite.All please fix

### ISSUE THREAD

**Issue by jcharnley** [OneDrive/onedrive-api-docs#1645]
Simple. The onedrive picker 7.2 cannot accept Files.ReadWrite.All scope. It only accepts Files.ReadWrite. I have Files.ReadWrite.All in my msal scopes and requires the users to ask for admin concent twice. can this be fixed please ?

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Observed Behavior

  scopes: [
          "Files.ReadWrite",
          // "Files.ReadWrite.All",
          "offline_access",
          "openid",
          "profile",
          "Sites.Read.All",
          "User.Invite.All",
          "Group.Read.All",
          // added for externalUserState
          "User.Read.All"
        ]

works but if you change  "Files.ReadWrite.All", instead of Files.ReadWrite it errors

[OneDriveSDK] Failed due to unknown error:  

#### Steps to Reproduce
Install OneDrive picker 7.2 sdk

 clientId: oneDriveApplicationId,
      action: "query",
      multiSelect: false,
      advanced: {
        filter:
          "folder,.glb" /* display folder and files with extension '.glb' only */,
        scopes: [
          "Files.ReadWrite",
          // "Files.ReadWrite.All",
          "offline_access",
          "openid",
          "profile",
          "Sites.Read.All",
          "User.Invite.All",
          "Group.Read.All",
          // added for externalUserState
          "User.Read.All"
        ]
      },

Thank you.

**Comment by patrick-rodgers** [comment]
Hello, the v7.2 Picker is no longer receiving updates, when possible please [migrate to the v8 picker](https://aka.ms/onedrive/file-picker), you can ask [questions for v8 picker in this issues list](https://github.com/OneDrive/samples/issues).
