### ISSUE TITLE
accountSwitchEnabled is not working in OneDrive FilePicker v7.2

### ISSUE THREAD

**Issue by vp70** [OneDrive/onedrive-api-docs#1649]
Account Switch UI is not showing up in FilePicker v7.2 anymore

Here is simple JavaScript

```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.debug.js"></script>
    <meta charset="utf-8" />
    <title>JSFilePicker</title>
</head>
<body>
    <div>
        <button onClick="launchOneDrivePicker()">Open OneDrive File Picker</button>
    </div>
    <script>
       function launchOneDrivePicker() {
          var odOptions = {
          clientId: "<ID>",
          action: "query",
          multiSelect: true,
          advanced: {
          },
          success: function(files) { /* success handler */ },
          cancel: function() { /* cancel handler */ },
          error: function(error) { /* error handler */ }
       }
       OneDrive.open(odOptions);
    }
    </script>
</body>
</html>
```

Anyone know if there was a change to stop supporting this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Service: **one-drive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by patrick-rodgers** [comment]
Hello, the v7.2 Picker is no longer receiving updates, when possible please [migrate to the v8 picker](https://aka.ms/onedrive/file-picker), you can ask [questions for v8 picker in this issues list](https://github.com/OneDrive/samples/issues).
