### ISSUE TITLE
share with no log in not working

### ISSUE THREAD

**Issue by spiderrr** [OneDrive/onedrive-api-docs#165]
When we share folder to some user ex. user@domian - edit mode ; a next user use a link with no log in  - a onedrive open but when try to send a file/folder then get a login screen.

**Comment by rgregg** [comment]
Hi @spiderrr. Sorry to hear you're having trouble with the sharing APIs. Unforutnately I need more details to be able to help you out here. Can you provide which APIs calls you're making and a walk through of what is/isn't working?

**Comment by rgregg** [comment]
I'm closing out due to lack of activity. Please feel free to reopen with more details.
