### ISSUE TITLE
Unable to upload to onedrive if filename contains _vti_ in any part of it 

### ISSUE THREAD

**Issue by tecepeipe** [OneDrive/onedrive-api-docs#1653]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I noticed that some encrypted files (with hash on their filenames) weren't uploaded to onedrive and returned:
 Failed to copy: invalidRequest: Invalid request

Filenames:
223.rprIx_spIp_ItBEApIt_wDHI_Bxq_vtI_EGxCItG_IDIpA_EpvtH.MBA
IJGtH_-_StrDst_uAxGIpIxDJH_vtHIJGtH_pCs_vtI_RadhTg_id_ndjg_VdPa.BE1

#### Observed Behavior

I was stripping the file name until I notice that both would fail to upload to business onedrive (it works on personal) if having `_vti_` in the encrypted filename. 

If you try to upload using web UI on onedrive a file named _dummy_vti_file.txt_, it will fail with access denied!

Googling for `_vti_` I found this:
_The `_vti_bin` is the built-in SharePoint Web services directory_

So, my suggestion is to accept  `_vti_`  in other parts of the filename, just prevent it if the filename **starts** with `_vti_` .

#### Steps to Reproduce

If you try to upload using web UI on onedrive a file named _dummy_vti_file.txt_, it will fail with access denied!

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ificator** [comment]
Unfortunately this currently a known limitation - see [this support document](https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidfilefoldernames).

However, I agree that this isn't ideal so I've started an internal discussion to see if the check can at least be loosened up a little.
