### ISSUE TITLE
OneDrive Business Authentication

### ISSUE THREAD

**Issue by bscharm** [OneDrive/onedrive-api-docs#166]
My OneDrive for Business Authentication flow what was previously working is no longer working and I am receiving the following error-

Additional technical information:
Correlation ID: 2188fbc2-9af5-4519-8da5-5219d24a2c0a
Timestamp: 2015-07-20 16:42:38Z
AADSTS90011: The 'resource' request parameter is not supported.

If I remove the resource parameter it says my scope is incorrect, my scope is `wl.signin wl.offline_access onedrive.readwrite`, which also previously worked

**Comment by rgregg** [comment]
Hi @bscharm,

With OneDrive for Business, you shouldn't pass any scope values to the OAuth flow. You define your scopes through the Azure Management portal when you create your app, and then those permissions are given out on each token. Can you try altering the request to not pass scopes, but still pass the resource, and see if that resolves the error?

**Comment by bscharm** [comment]
I removed scope and added resource and got the same error about resource not being supported (though I am realizing I should not need resource as this is for the "authorization" URL portion of the flow), and if I remove both I get the following error-

```Additional technical information:
Correlation ID: 2d3f2cc7-b554-48bd-af86-499f29b04d87
Timestamp: 2015-07-20 17:11:56Z
AADSTS70011: The provided request must include a 'scope' input parameter.```

This is the URL I am using (without both scope and resource parameters) - `https://login.microsoftonline.com/common/oauth2/authorize?api-version=2.0&response_type=code&client_id=3b6d93d5-2bc0-42c6-abfd-4d1e9bb66626&redirect_uri=https://cloud.ngrok.com/elements/jsp/home.jsp`

**Comment by rgregg** [comment]
Can you remove the "api-version=2.0" query parameter? That shouldn't be there.

**Comment by bscharm** [comment]
that worked, thanks for your help
