### ISSUE TITLE
Duplicate/skipped items in paginated directory queries

### ISSUE THREAD

**Issue by nickgaya** [OneDrive/onedrive-api-docs#1669]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

When querying the contents of a OneDrive directory, all files in the directory are returned exactly once.

#### Observed Behavior

When querying the contents of a OneDrive directory, some files are skipped, and other files are returned more than once.

Note: No changes are being made to the directory when this bug is observed.

#### Steps to Reproduce

This is a probabilistic ("random") bug so it is difficult to reliably reproduce.  However I observe this frequently when syncing a large number of files to OneDrive using rclone.

Example [request log](https://gist.githubusercontent.com/nickgaya/6d8c325f9602c893f5bc7e100a411a69/raw/1af438b920c52444c60819f728b660d74422b6be/rclone.log).  In this example, the directory contained two files called `d06b` and `d6b`. The request logs show that `d06b` was returned twice, in two consecutive paginated requests, while the file `d6b` was not returned at all.

#### Root cause analysis

In order for pagination to work correctly, files must be ordered consistently across requests.  If the ordering changes between requests, then items in the list may be skipped or duplicated.

The root cause is that OneDrive's [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order) implementation is unstable when comparing files containing strings of digits that differ by a leading zero, for example `d06b` and `d6b`.  These files may be returned in either order, and this ordering can differ from one request to the next.  This is what causes the observed issue described above.

To fix this issue, OneDrive needs to add some form of tie-breaking to their sort implementation to ensure that the ordering is stable.

Previous bug report: https://github.com/OneDrive/onedrive-api-docs/issues/1472

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ificator** [comment]
Your analysis is spot on @nickgaya - we're essentially asking the service to sort the same string, which without something else to keep it consistent can result in randomized results. I'll take a quick peek to see if there's anything cheap we can do to fix this.

**Comment by ificator** [comment]
@nickgaya we pushed a change that should help here - can you see if your scenario works as expected now?

**Comment by nickgaya** [comment]
I have not seen this issue occur for my use case since 3/13, so it seems to be fixed.  Thanks!

**Comment by kashiftahir** [comment]
Closing the issue since the customer verified its fixed.
