### ISSUE TITLE
integrate the OneDrive for Business to a Web Form App

### ISSUE THREAD

**Issue by RamakantVerma** [OneDrive/onedrive-api-docs#167]
I m trying to integrate the OneDrive for Business to a Web Form App.
For this i am using the documentation given at this url [https://dev.onedrive.com/auth/aad_oauth.htm][1]
In web Form App I have two Page 
First one is Login page which have a button for login
In button login click i am making a GET Request to OneDrive for Business API using the following code

```csharp
HttpClient client = new HttpClient();
Redirecturi = Uri.EscapeDataString(Redirecturi);
string url = string.Format("https://login.windows.net/common/oauth2/authorize?response_type=code&client_id={0}&redirect_uri={1}", ClienId, Redirecturi);
var response = client.GetAsync(url);
var json = response.Result.Content.ReadAsStringAsync();
Label2.Text = json.Result;
```
When I Click on login button it is taking me to micorosoft login servie and sending me back to callback.aspx page with access code (Redirect URi configured on azure)

I got the access code 
On second page i am redeeming the access code and  making a POST request to get the Authentication token
Here is the code for the second page.

```csharp
private string BaseUri="https://login.windows.net/common/oauth2/token";
public string Redirecturi = "http://localhost:51642/CallBack.aspx";
public string ResourcesId = "https://api.office.com/discovery/";
private string ClienId = "180c6ac4-5829-468e-.....-822405804862"; ///truncated//azure 
private string ClientSecert = "G4TAQzD8d7C4...OE6m366afv8XKbTCcyXr4=";//truncated
protected void Page_Load(object sender, EventArgs e)
{
    if (!string.IsNullOrEmpty(Request.QueryString[OAuthConstants.AccessToken]))
    {
        // There is a token available already. It should be the token flow. Ignore it.
        return;
    }
    if (!string.IsNullOrEmpty(Request.QueryString[OAuthConstants.Code]))
    {
        string _accessCode = Request.QueryString[OAuthConstants.Code];
        HttpClient client = new HttpClient();
        // BaseUri = Uri.EscapeDataString(BaseUri);
        Redirecturi = Uri.EscapeDataString(Redirecturi);
        ResourcesId = Uri.EscapeDataString(ResourcesId);
        string url = string.Format("{0}?client_id={1}&redirect_uri={2}&grant_type=authorization_code&client_secret={3}&code={4}&grant_type=authorization_code&resource={5}", BaseUri, ClienId, Redirecturi, ClientSecert, _accessCode, ResourcesId);
        var response = client.PostAsync(url, null);
        var json = response.Result.Content.ReadAsStringAsync();
        Response.Write(json);
    }
}
```

But instead of Response i am getting following error. Which say include the grant_type in url. I already added (u can check in code).
Without including this also i am getting same error.

**Here is error**

```json
{"error":"invalid_request","error_description":"AADSTS90014: The request body must contain the following parameter: 'grant_type'.\r\nTrace ID: 2adb3a7f-ceb1-4978-97c4-3dc2d3cc3ad4\r\nCorrelation ID: 29fb11a0-c602-4891-9299-b0b538d75b5f\r\nTimestamp: 2015-07-15 09:58:42Z","error_codes":[90014],"timestamp":"2015-07-15 09:58:42Z","trace_id":"2adb3a7f-ceb1-4978-97c4-3dc2d3cc3ad4","correlation_id":"29fb11a0-c602-4891-9299-b0b538d75b5f","submit_url":null,"context":null}
```

please help to know where , what geting wrong.
Any kind of help will be appreciable 
Thanks a lot in advance

  [1]: https://dev.onedrive.com/auth/aad_oauth.htm

**Comment by rgregg** [comment]
Hi @RamakantVerma 

Which permissions have you configured your app to request inside the Azure Management portal?

While probably not related, the way you are calling the OAuth flow is not correct. You should be redirecting the browser to the authorize URL (`https://login.windows.net/common/oauth2/authorize?response_type=code&client_id={0}&redirect_uri={1}`) instead of loading it in an HttpClient request. After the user has signed in (on our page) and approved your app, then it will redirect back to your callback URL with the access token / refresh token.

**Comment by rgregg** [comment]
You can take a look at the [onedrive-explorer-js sample I've modified](https://github.com/rgregg/onedrive-explorer-js), which is a single page JavaScript app that lets you log in to both MSA and AAD. Although it's client side code, it should provide a good example of what the flow should look like that you'll need to replicate.
