### ISSUE TITLE
Error when creating folder named "Forms" in Sharepoint

### ISSUE THREAD

**Issue by kotsak** [OneDrive/onedrive-api-docs#1671]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Observed Behavior

I am receiving an HTTP 400 Bad Request when trying to create a folder named "_Forms_" on Sharepoint Online. I am aware that such name is reserved and not allowed to be used as a folder name in the root of a document library but in my case (and in our customer's case, who brought this up) the folder is being created in a subfolder. I have no problem creating it manualy via the Office 365 Sharepoint web page but the API rejects it. Here is the HTTP request/response:

```
POST /sites/testing/_api/v2.0/drives/b!6vsuLOWBgEOykKqKKn_2GOCi2Z7HpZdNowmxO8Iou6iXnD66Xu-QQqrNl1tNMQXR/items/01ESVDJ3REA53NJMG7G5FZBVOPQFTLTJ57/children
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Content-Length: 28
Authorization: Bearer [snip]
Host: [snip]
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: [snip]


{"name":"Forms","folder":{}}

HTTP/1.1 400 Bad Request

Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Length: 87
Content-Type: application/json
Expires: -1
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
X-NetworkStatistics: 0,525568,0,0,351755,0,525568
X-SharePointHealthScore: 0
X-VroomVersion: 2.0
X-DataBoundary: NONE
X-1DSCollectorUrl: https://mobile.events.data.microsoft.com/OneCollector/1.0/
X-AriaCollectorURL: https://browser.pipe.aria.microsoft.com/Collector/3.0/
SPRequestGuid: ab6298a0-8075-2000-1828-8468cf471402
request-id: ab6298a0-8075-2000-1828-8468cf471402
MS-CV: oJhiq3WAACAYKIRoz0cUAg.0
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com *.skype.com *.teams.microsoft.us local.teams.office.com *.powerapps.com *.yammer.com *.officeapps.live.com *.office.com *.stream.azure-test.net *.microsoftstream.com *.dynamics.com *.microsoft.com onedrive.live.com *.onedrive.live.com securebroker.sharepointonline.com;
SPRequestDuration: 45
SPIisLatency: 1
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.23408
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: 1EABBEAB868540E79717548691739D07 Ref B: BKK30EDGE0509 Ref C: 2023-02-21T12:41:02Z
Date: Tue, 21 Feb 2023 12:41:02 GMT
Connection: keep-alive

{
	"error": {
		"code": "invalidRequest",
		"message": "Name is reserved for list forms folder."
	}
}

```

**Comment by abhijeet-chatarjee** [comment]
I am also facing the same issue. I am creating a folder by the name 'Forms' through the API, but it is rejected with the 
`Executing the curl RPC: 1356 failed with error: 0, status msg: {"error":{"code":"invalidRequest","message":"Name is reserved for list forms folder.","innerError":{"date":"2023-03-07T17:08:06","request-id":"6d28c5d4-5900-40c7-bdd0-97d21379d741","client-request-id":"c4ff9a01-6c84-4267-9eae-68128f86d12f"}}}`

Please triage this asap.

**Comment by abhijeet-chatarjee** [comment]
But Microsoft is creating the subfolder with the name 'Forms' anyway even after returning the error.
[kotsak](https://github.com/kotsak) Please check if it's the same behavior in your case also.

**Comment by kotsak** [comment]
> But Microsoft is creating the subfolder with the name 'Forms' anyway even after returning the error. [kotsak](https://github.com/kotsak) Please check if it's the same behavior in your case also.

@abhijeet-chatarjee Not in my case.

**Comment by PeetMcK** [comment]
Not in my case either. This same issue presents in rclone when attempting to create "forms" folders outside of the Document Collection root. I do believe this is a bug.

**Comment by abhijeet-chatarjee** [comment]
Will Microsoft be going to fix this anytime soon?

**Comment by AZweimiller** [comment]
This is causing us major issues as well. I am having to manually create hundreds of "Forms" folders in a complicated directory tree because the API rejects the folder name. Creating on the Sharepoint web interface works fine.

**Comment by kashiftahir** [comment]
Thanks for reporting the issue. We are working on a fix. Will circle back here once the issue is resolved.

**Comment by PeetMcK** [comment]
> Thanks for reporting the issue. We are working on a fix. Will circle back here once the issue is resolved.

@kashiftahir  I've been waiting with bated breath here. Do you have any sort of timeline. This really is a giant time suck. Thanks.

**Comment by kotsak** [comment]
FYI, I don't receive the errors anymore. Has the problem been fixed or I was just been lucky? :>

**Comment by kashiftahir** [comment]
The change completed rolling out on 5/20. Let me know if folks can still repro and I can take a look otherwise I will consider this resolved. Thanks everyone for the feedback.
