### ISSUE TITLE
429 - throttledRequest errors using /createLink endpoint after creating just a few links

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#1673]
#### Category
- [x] Question
- [x] Documentation issue
- [x] Bug

#### Observed Behavior
I am reopening issue #1436 as the problem still exists and some questions remain unanswered. See #1436 for the observed behavior and steps to reproduce it.

I understand that there is some sort of limit for creating sharing links (apparently 50/hour for OneDrive Personal), but that's not the behaviour I'm experiencing. Please see the latest replies starting with [this comment](https://github.com/OneDrive/onedrive-api-docs/issues/1436#issuecomment-811703069).

**Main problem:**

1. If the API endpoint /createLink is limited to 50 calls/hour, why is the API throttling requests immediately after only ~10-20 calls are made? The throttling immediately returns a retry header of 1 hour, while the limit you describe isn't reached.

**Other questions**

1. Why is the /createLink endpoint only limited to 50 calls/hour? I haven't seen such limits on other similar APIs. In most cases they limit the usage (e.g. bandwidth) of the shared links, but not the link creation itself.
2. Can you please document this API limit on the [/createLink page](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink)?
3. Is it possible to raise the limit? What would be the process?
4. Is it possible to create Drive items that are shared by default so that we don't have to call /createlink?

**Comment by patrick-rodgers** [comment]
Throttling is a separate process from any creation limits. Throttling is based on many factors in the service and typically happens when the load is too high, which if you (or another app in the same tenant) are making many requests any request would be throttled.

1. Why is the /createLink endpoint only limited to 50 calls/hour? I haven't seen such limits on other similar APIs. In most cases they limit the usage (e.g. bandwidth) of the shared links, but not the link creation itself.
> This was a decision made when the service was designed.

2. Can you please document this API limit on the [/createLink page](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink)?
> Will check with the owning team and see what is appropriate to include.

4. Is it possible to raise the limit? What would be the process?
> No, throttling limits cannot be adjusted

5. Is it possible to create Drive items that are shared by default so that we don't have to call /createlink?
> No, creating a file and sharing it are two different operations.

**Comment by The-Lion** [comment]
Thanks for your answers on the questions. 

But the main issue remains. If I don't make any API calls for 24 hours and then make, say, ~10-20 /createLink calls I still get the same 429 - throttledRequest error with a retry-after header of 1 hour.

**Comment by patrick-rodgers** [comment]
Throttling isn't based on the number of links created, rather a complex calculation involving many factors relating to total load. If you are making 10 links very quickly you might get throttled, this is a reality of the shared service. We don't publish an exact limit for operations as even if the limit was say 30/hour you might still be throttled unrelated to that limit.

**Comment by The-Lion** [comment]
Well, that is quite inconvenient. So basically I can't use the API to upload 10 files in a single upload session and create a shared link for those files after the upload is finished. That sounds very limited to be honest...

**Comment by imbarbudiman** [comment]
> Throttling isn't based on the number of links created, rather a complex calculation involving many factors relating to total load. If you are making 10 links very quickly you might get throttled, this is a reality of the shared service. We don't publish an exact limit for operations as even if the limit was say 30/hour you might still be throttled unrelated to that limit.

At least there is specific documentation for the createLink limitation.
