### ISSUE TITLE
Registration Link Throws Status 403

### ISSUE THREAD

**Issue by miqrogroove** [OneDrive/onedrive-api-docs#1675]
Both of these pages ...

https://learn.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online

https://learn.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online

... have links to ... 

https://aka.ms/AppRegistrations

But that page just redirects to

https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade

which in turn throws Error code 403.  The error message includes vague references to PowerShell and Visual Studio.

Are all of these pages obsolete?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f02010cc-2715-86ca-b3fe-e4f92e934fdb
* Version Independent ID: 27b3e16e-f80f-32f4-0e4f-69cfcd1cf769
* Content: [Create an app with Microsoft Graph - OneDrive API - OneDrive dev center](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online)
* Content Source: [docs/rest-api/getting-started/app-registration.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/getting-started/app-registration.md)
* Service: **one-drive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
