### ISSUE TITLE
AsyncOperationStatus has undocumented field 'statusDescription'

### ISSUE THREAD

**Issue by robses** [OneDrive/onedrive-api-docs#168]
In the document page http://onedrive.github.io/resources/asyncJobStatus.htm, 
the field 'statusDescription' is undocumented.

**Comment by rgregg** [comment]
As documented in the [API compatibility](https://dev.onedrive.com/README.htm#api-compatibility) section, we expect to add additional properties over time. Any code should be resilient to additional properties appearing for objects that are not yet documented. Additionally we only support the usage of documented properties / methods / collections, so you shouldn't take a dependency on undocumented properties.

**Comment by robses** [comment]
Clear answer, will read into the API compatibility section. Thank you.
