### ISSUE TITLE
Problems download content in document library: 401 Unauthorized

### ISSUE THREAD

**Issue by how123480** [OneDrive/onedrive-api-docs#1686]
#### Category
- [x] Question
- [ ] Documentation issue
- [x] Bug

I try to download the file in document library by `GET /drives/{drive-id}/items/{item-id}/content`
then I get the `401 Unauthorized`
Following picture is the responsed web pages
![image](https://user-images.githubusercontent.com/24409834/232742005-4fff55f2-3451-45e4-8806-8f94d9a505ac.png)

It seems that the request will be redirected to server `https://{sharepoint-site}/_layouts/15/download.aspx?UniqueId={id}&Translate=false&siteHost={host}&tempauth={token}&ApiVersion=2.0`

Is it the same issue as https://github.com/OneDrive/onedrive-api-docs/issues/593

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ificator** [comment]
Are you still seeing this issue?
