### ISSUE TITLE
Remove "Keep me signed in" for Kiosk Applications

### ISSUE THREAD

**Issue by dmorrison42** [OneDrive/onedrive-api-docs#169]
We are developing a OneDrive API application for a public kiosk. For security reasons, we would like to prevent the user from selecting "Keep me signed in" by removing it as an option. Is this possible using OneDrive's OAuth2 authorization flow?

We are able to work around this by clearing the session when the user leaves the machine, but our users have found this confusing, because they are prompted again after selecting "Keep me signed in".

![login_screen](https://cloud.githubusercontent.com/assets/198433/8883542/6b50d768-321d-11e5-8a2e-d2842b20840d.png)

**Comment by rgregg** [comment]
@dmorrison42 is this a web app or a native client app?

**Comment by dmorrison42** [comment]
@rgregg, I believe this would be considered a web app.

All of the resources are deployed to the local machine, which in turn starts a web server locally, which is only accessed by the local machine. It's similar in architecture to many of the go lang apps that I have seen (e.g. Syncthing).

**Comment by rgregg** [comment]
Thanks. Right now we don't have a way to disable this box for web apps. The box doesn't appear if you select that your app is a mobile or native app, but that probably won't get you the right authentication flow for a web app.

If you don't mind, can you create a request for more control around the "Keep me signed in" box on our [UserVoice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) page?

**Comment by dmorrison42** [comment]
Thank you. This can now be tracked at http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/9151300-allow-applications-to-chose-whether-or-not-to-disp as a feature request.
