### ISSUE TITLE
default page size?

### ISSUE THREAD

**Issue by phileo** [OneDrive/onedrive-api-docs#170]
1.)  In this page:
https://dev.onedrive.com/items/list.htm

It says that if the collection exceeds the default page size, then @odata.nextLink will magically appear in the json response.

I tried to search for the value of default page size, but could not find it.  What is the default page size ?

2.) Is this the correct the query option to retrieve 100 child items per page:
/drive/items/root/children?top=100,skipToken=100

**Comment by rgregg** [comment]
The default size of a page is 200 items. I'll add that to the docs.
To request a different page size, use ?top=100. You don't need the skipToken parameter.

**Comment by rgregg** [comment]
I've added this information to the [List Children](https://github.com/OneDrive/onedrive-api-docs/blob/master/items/list.md) page of the documentation. Thanks for pointing out the missing info.
