### ISSUE TITLE
The new OneDrive RESTful API seems to have lost some special folders.

### ISSUE THREAD

**Issue by iMoreApps** [OneDrive/onedrive-api-docs#171]
How to get a list of the user's most recently used documents and a list of OneDrive objects that are shared with the signed-in user?

**Comment by rgregg** [comment]
OneDrive API doesn't have a way to get to those collections right now. It's something we've got on our backlog, but I don't see it on our [UserVoice](http://aka.ms/1drvdevvoice). Please consider submitting this as a request on [UserVoice](http://aka.ms/1drvdevvoice) so others can vote to help prioritize these features.

**Comment by iMoreApps** [comment]
I just submitted this as a request on OneDrive UserVoice. Thanks.

**Comment by rgregg** [comment]
I'm going to close out the issue here since we have it tracked on Uservoice. Thanks!
