### ISSUE TITLE
Uploading  50% |oooooooooooooooooooo                    |   ETA   00:00:00 ERROR: OneDrive returned an error with the following message:   Error Message: SSL peer certificate or SSH remote key was not OK on handle 55B5300928D0   Calling Function: perform()

### ISSUE THREAD

**Issue by lvazdela** [OneDrive/onedrive-api-docs#1714]
#### Category
- [ ] Question
- [ ] Documentation issue
- [ X] Bug

#### Expected or Desired Behavior

synchronize file in ubuntu linux

#### Observed Behavior
It does not synchronize de file, and throws the following error:
Uploading  50% |oooooooooooooooooooo                    |   ETA   00:00:00 ERROR: OneDrive returned an error with the following message:
  Error Message: SSL peer certificate or SSH remote key was not OK on handle 55B5300928D0
  Calling Function: perform()

>

#### Steps to Reproduce

upload a file in Onedrive
open the ubuntu linux terminal. Ubuntu 22.04.2 LTS)
write onedrive --synchronize
currenly using onedrive for linux version v2.4.25-1+np1

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ificator** [comment]
Microsoft does not make a Linux client
