### ISSUE TITLE
Retrieve JWT from access token

### ISSUE THREAD

**Issue by praneethw** [OneDrive/onedrive-api-docs#172]
Using the "Code flow" method for authentication, how could I derive a JWT token from the access_token sent back? I dont seem to get an access_token that can be decoded to a JWT.
e.g.
EwCAAq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAUd8aP24SC3mcrCJa33rZVIg4W2/edyfEt4EfFQzjajkmhK0fDWe+fK4FbzH8XlXRASSblslBfSvdUaFOyxU/eHBpnoM90fDBWwscltpjInxbZliBYPZ69zhU0uV72NJjj/PgtvjTZKvUhpnIc1H3Z3/s6WWxIJ1aX5TpNexA+2Xp1vCQ+9q8dbspOPgm3CzZOSHYOWwJPLtR109D4d0cM2UNiii90IhYluVLan0EmM0XT79IrI0J07oQj+wFo1DKfMzAbk4PdItBi4B3ZoWf6ILPPdYN/jkgAjFcckD33NSHPx5rKaWKa6woN6X9I7R0qmGPg9bAZOB+5ZlTJGl9qUDZgAACPrjjaHHrv+hUAHjhN8bwevcOY7kV84K8Z7D88jMPr5CtG+dfvB5N5DUx7QzZ6WoiQXui+w+8gs0mGc7dlo0IxTUxjYRbUoU7DAjpS2Fv/c0Ic0TFt+p/dEtxwdtmsiShfdz7BIMFziBxTF8cc88n9SGOWvvqRAUjDdzTcjr4vPZ8TJLstbYTRxuH7yA51oOO0/VktvkUJGcC5Keg9MPR8BPqiIEGZjUtil3SMuX7IMzBoPRBR6pDNgNMn7bWJWtiGbwd0Wg8qCm7KdYthvKB3ULiUP0jizP/OQnopFekn8vZxihKTtX1q5ukG+zP2AhWmCluCLQBrtWC6TlLC+g9HDL7H4w50U6z+0qrX1RA3eCFFwi/59ZeGj4F3cMr0idme4fpoU9WlXdj5+PGcW+my7whSvmxadQpX9fdFaeqVhwsMKX9j/7E1A/Xk6fjl6bRtU6ZC03W27qxeVtAQ==

My app is created and has the following properties set,

![image](https://cloud.githubusercontent.com/assets/13520386/8904900/f4f46c40-3480-11e5-8450-7d840cc0ab02.png)

By which other means can I derive a JWT token if its not part of the access_token?

**Comment by rgregg** [comment]
I'm looking into this.

**Comment by rgregg** [comment]
@praneethw To get JWT, you need to fill out the Target domain property to be the final domain that you'll be using (since you're using localhost as the root domain right now).

Once you've done that, you should see a JWT returned as the `authentication_token` property from the response.

**Comment by praneethw** [comment]
@rgregg Thank you for your response, if thats the case, how would you suggest me test my application using localhost or a test environment before i go to production? If i use localhost as the target domain it gives me the following warning,

"The root domain is invalid, query strings are not allowed. Length is limited to 255 characters."

Your help is much appreciated.

**Comment by praneethw** [comment]
Thanks @rgregg! I used a custom domain and was able to receive the JWT. Only issue I currently have is not being able to use localhost as the target doamin.

**Comment by rgregg** [comment]
That's "by design" - right now the usage of localhost in the target domain is blocked.
