### ISSUE TITLE
webUrl field of driveItem resolves to non-functioning URL

### ISSUE THREAD

**Issue by tipa** [OneDrive/onedrive-api-docs#1724]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

My app retrieves a list of images as "driveItems" using the Graph API: https://learn.microsoft.com/en-us/graph/api/resources/driveitem

#### Expected or Desired Behavior

The webUrl field cointains a URL that allows displaying the resource (in this case photo) in the web browser (as it's documented)

#### Observed Behavior

When opening the webUrl (which has a format like `https://1drv.ms/i/s!xyz`) in a web browser, the URL redirects to another path (which has a format like `https://photos.onedrive.com/share/...?cid=...&resId=...&ithint=photo`, which does not load anything - screen remains blank, only shows some buttons on the top:
![image](https://github.com/OneDrive/onedrive-api-docs/assets/2863198/9fa29ade-93dc-4219-a0fd-8d6510f17720)

However, when removing the trailing `&ithint=photo` part of the (redirected) URL, the photo shows as expected.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by ificator** [comment]
Are you still seeing this?

**Comment by tipa** [comment]
No it seems to be working correctly now

**Comment by ificator** [comment]
Great, sorry for the delay but at least it's working!
