### ISSUE TITLE
Can a file be uploaded to a different user's OneDrive?

### ISSUE THREAD

**Issue by GermanEZI** [OneDrive/onedrive-api-docs#1727]
We created a process of collecting user log files and stuffing them into a zip file.   It works just fine.

What we want to do is upload these zip files to a sub folder in my OneDrive.   Of course, the process works for me, since I'm the owner; but it doesn't work for anyone else.   I've even turned on logging and no errors were reported.

Is what I'm doing even possible?   I've even updated the access to my subfolder, but that made no difference.

[My Post on StackOverflow](https://stackoverflow.com/questions/77054921/how-do-i-upload-a-file-to-a-folder-in-another-users-onedrive)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68f993b6-934a-54ce-d720-43e45f5b71e6
* Version Independent ID: d0b43b63-9460-ef97-9fc2-c05adb7f14af
* Content: [OneDrive for Developers - OneDrive dev center](https://learn.microsoft.com/en-us/onedrive/developer/?view=odsp-graph-online)
* Content Source: [docs/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/index.md)
* Service: **one-drive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by ificator** [comment]
Let's use the StackOverflow question for this one.
