### ISSUE TITLE
Uploading a binary file (XLSX) to Sharepoint

### ISSUE THREAD

**Issue by HannuSihvonen** [OneDrive/onedrive-api-docs#1728]
Hi, I think uploading a binary file should be possible using PUT. Can you write an example code for that, please? What is payload in that case? I am using Python. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 350cd850-d19a-ef5c-2761-e342fc3c506c
* Version Independent ID: 5bf3ef39-f20a-6c7f-77f6-3bc7e9d246f4
* Content: [Upload small files - OneDrive API - OneDrive dev center](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_put_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_put_content.md)
* Service: **one-drive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by ificator** [comment]
This question is better suited for StackOverflow
