### ISSUE TITLE
application name is not displayed on login page "onedrive business"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#173]
for onedrive business, while registering we give the name of the application.

when login page(webview) use to open, the name of the application used to appear at the top, has specified while registering the app.

from almost 1 week, the name of the application is not displayed on the login screen. "Login" this text appear on the login page

this update is by design, or some problem?

**Comment by rgregg** [comment]
Ankit, I'm investigating the design here. I'll get back to you when I have more details.

**Comment by rgregg** [comment]
Closing out old issues. If this is still an issue, please let us know.
