### ISSUE TITLE
Files in OneDrive file picker dialog cannot be selected if the width of browser has changed to small size

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#174]
*Reproduce steps:*
a) open http://isdk.dev.live.com/dev/isdk/ISDK.aspx?category=scenarioGroup_core_concepts&index=0#
b) click run button
c) Change the width of browser to small size

*Result:*
The files in file picker dialog cannot be selected. Please see the attached screenshot.

*Expect Result:*
The files should can be selected.

![image](https://cloud.githubusercontent.com/assets/1411188/8924417/1d3a34aa-3530-11e5-80eb-b22508f82914.png)

**Comment by jscaria** [comment]
Thanks @benjaminliugang for reporting this issue.    It's a known issue that we are tracking in our backlog.

**Comment by jscaria** [comment]
@benjaminliugang - take a look at the updated JavaScript Picker/Saver SDK at https://dev.onedrive.com/sdk/javascript-sdk.htm.   It supports different browser window sizes.
