### ISSUE TITLE
Integrate the OneDrive for Business to a Windows 32 app

### ISSUE THREAD

**Issue by Kammy6679** [OneDrive/onedrive-api-docs#175]
1. Can we use Windows 7 and VS 2010 to integrate the OneDrive for Business to a Windows 32 app?
2. We have followed this page(https://dev.onedrive.com/app-registration.htm#register-your-app-for-onedrive-for-business) to register our app to work with OneDrive for Business. Follow this page(https://dev.onedrive.com/auth/aad_oauth.htm) to sign into OneDrive for Business:

step 1：Log in and get an authorization code, looks no problem
![1](https://cloud.githubusercontent.com/assets/10860444/8978658/bbc79a70-36d6-11e5-8223-301eb586710d.jpg)

step 2：Redeem the authorization code for tokens, looks no problem
![2](https://cloud.githubusercontent.com/assets/10860444/8978651/aef589ec-36d6-11e5-9f35-8712594f7269.jpg)

step 3：Discover the OneDrive for Business resource URI, get the following error message:
![3](https://cloud.githubusercontent.com/assets/10860444/8978647/a1f7b332-36d6-11e5-9492-f3c2bdd20df5.jpg)

Here are some "define" in code
#define ONE_DRIVE_BUSINESS_GET_ACCESS_TOKEN_URL L"https://login.windows.net/common/oauth2/token" 
#define ONE_DRIVE_BUSINESS_RD_CLIENT_ID L"033...............6ebf"
#define ONE_DRIVE_BUSINESS_RD_REDIRECT_URI L"com.test.com.testapp://authorize"
#define ONE_DRIVE_BUSINESS_AUTHORRITY_URL L"https://login.windows.net/common";
#define ONE_DRIVE_BUSINESS_RESOURCEID L"https://api.office.com/discovery/"

Do you have any suggestion for this issue?

**Comment by rgregg** [comment]
What permissions / scopes are you requesting in the Azure Management Portal for your application?

**Comment by Kammy6679** [comment]
I don't what permissions / scopes  need to be requested. I just want to get/download the files from OneDrive,  then edit these files, then save these back. What permissions / scopes I need to request?

I have set all permissions for my app in Azure Management Portal.
![image](https://cloud.githubusercontent.com/assets/10860444/9079060/80bc0b68-3b78-11e5-9b85-cd705e8f207a.png)

**Comment by rgregg** [comment]
To access OneDrive for Business, you need to enable the "Read user files" or "Read and write user files" delegated permission for the Office 365 SharePoint Online app inside the Azure Management Portal. This doesn't appear to be well documented in our docs, so I'll see if I can update that, but here's what you need to do:

1. Go into the management portal and select the application you are developing. Click on the Configure tab.
2. Scroll down to "Permissions to other applications" section and click the green Add Application button.
3. Select **Microsoft apps** in the drop down and then select **Office 365 SharePoint Online**. If SharePoint online doesn't appear in the list, the tenant you are creating the application doesn't have an Office 365 account. You can sign up for an Office 365 developer tenant trial to resolve that.
![image](https://cloud.githubusercontent.com/assets/1435771/9092192/716073e4-3b59-11e5-88bb-aa44a51bcbb7.png)

4. Once you have SharePoint added to your permissions list, you can enable the permissions to access OneDrive for Business:
![image](https://cloud.githubusercontent.com/assets/1435771/9092208/8b7bcde6-3b59-11e5-8d8e-322581c5cb39.png)

Then you should be good to go.

**Comment by Kammy6679** [comment]
@rgregg ,

We have enabled the "Read and write user files" delegated permission for the Office 365 SharePoint Online app inside the Azure Management Portal. But still get the same error message.

**Comment by dima72** [comment]
Dear Kammy6679 ,

having problem at the step2 (Redeem the authorization code for tokens)

Can you please show value for param 'resource' in Step2 http request?

thanks in advance,
