### ISSUE TITLE
[Question] normal office365 user can't get oauth code

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#176]
hi forks,

the scenario is as following:

1.I had a office 365 admin user -- adminA
2.I bought a new licence of onedrive for biz
3.I use adminA at office to create a new user normalB belongs to the adminA
4.use normalB to access the Oauth flow but failed

error:AADSTS90093: This operation can only be performed by an administrator. Sign out and sign in as an administrator or contact one of your organization's administrators.

but it can finish the Oauth flow after I promote normalB to become adminB

anything wrong??
I supposed the normalB have privilege to pass the Oauth flow...

thank you!

**Comment by rgregg** [comment]
Joe, what permission scopes are you asking for? There are some permission scopes for an application that can only be given to an administrator user. If you request one of those permissions, you'll get an error like this when trying to authenticate.

**Comment by joewutaiwan** [comment]
hi @rgregg ,
thank you for replay.
Is the permissions you mean in Azure Active Direct APP setting?

I had tried this way, but it still did not work.
my setting is : 
Windows Azure Active Directory:
1)app permission : Read and write directory data
share point Online:
1)app permission : Read and write user profiles
2)delegate permission : Read and write user files

what is the minimum setting should I take, if I only want both normal and admin user access onedrive for biz?

Thanks!

**Comment by joewutaiwan** [comment]
update.
if any one has this issue
ref. this
https://msdn.microsoft.com/office/office365/HowTo/application-manifest
hope it will help

**Comment by thesecretary** [comment]
Totally right about lion

**Comment by rgregg** [comment]
Closing this issue down since it appears to be resolved.
