### ISSUE TITLE
429 Too many requests return without Retry-After header

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#177]
I run the test to upload 100k files rapidly to test 429 too many requests status and expect that get the retry-after header return.

But there is no such information in header.

here is the header what I got:

resp.headers: {'content-length': '0', 'via': '1.1 BN1303____PAP280 (wls-colorado)', 'x-throwsite': '2207.ccc2', 'x-asmversion-proxyapp': 'UNKNOWN; 19.22.0.0', 'x-clienterror': 'ThrottledRequest', 'date': 'Tue, 04 Aug 2015 10:47:51 GMT', 'x-msnserver': 'SN3302____PAP028', 'p3p': 'CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"', 'server': 'Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0', 'x-wlsproxy': 'BN1303____PAP280'}

Is this a bug or is the normal case?

**Comment by ificator** [comment]
We should retyrn the Retry-After header for this scenario. Thanks for letting us know!

**Comment by ificator** [comment]
This should have been resolved a while ago now so I'm going to close this issue out - please let us know if you are still seeing scenarios where it appears to be missing.
