### ISSUE TITLE
Fragment upload returns 401 when uploading a file with a '#' in the filename.

### ISSUE THREAD

**Issue by wnojopra** [OneDrive/onedrive-api-docs#179]
I'm using the resumable uploader specified in https://dev.onedrive.com/items/upload_large_files.htm . I make the initial request in which I pass the item path to get an uploadUrl. For the case where there is a '#' character in the filename, I always get back a 401 when I upload a fragment. The error message simply says 'Unauthorized'. This can't be right because I can upload other files fine with the same access token.

**Comment by ificator** [comment]
Hi @wnojopra, could you let us know if you're hitting this with a consumer account or a business account? It would also be helpful to see the request/response for the upload.createSession call, as well as the request (without the payload)/response that shows the 401 on the upload of a fragment. You can omit the bearer token.

**Comment by wnojopra** [comment]
Hi, sorry but it seems someone else on my team has resolved this issue through a combination of changes, one of which was including the bearer token on each fragment upload.

**Comment by wnojopra** [comment]
Hi! I have learned that my teammate had previously 'resolved' the issue by adding the Authorization: Bearer header in every fragment request. However, this causes a new issue where if the access_token expires in the middle of an upload, the fragment upload will fail. If I simply do not include the authorization header in every fragment request, it will succeed. The documentation seems to support not including the authorization header. The following is what happens when I try to upload a file with a '#' in the name and I do not include the authorization header. 

I am doing this with a consumer account (non-business). The filename I am uploading is "temp_#.zip".

I first make the request to upload.createSession with this URL: "https://api.onedrive.com/v1.0/drive/items/2DB9CC9D2E7626A4!519:/temp_%23.zip:/upload.createSession"

The response I get is 200 with this content:
{"@odata.context":"https://api.onedrive.com/v1.0/$metadata#oneDrive.uploadSession","uploadUrl":"https://api.onedrive.com/up/eyJSZXNvdXJjZUlEIjoiMkRCOUNDOUQyRTc2MjZBNCE1MTkiLCJSZWxhdGlvbnNoaXBOYW1lIjoiL3RlbXBfIy56aXAiLCJBbGlhcyI6bnVsbH0/3mV7bIhZh_P_NkQ4YkbPiahDmc8bKLCg6brpP43hNSEsvqoiRVJwjpGHwEcgWZ0kWR/eyJAbmFtZS5jb25mbGljdEJlaGF2aW9yIjoiZmFpbCIsIk5hbWUiOiJ0ZW1wXyMuemlwIn0","expirationDateTime":"2015-11-17T01:44:56.8927233Z","nextExpectedRanges":["0-"]}

I then make the first fragment upload request to "https://api.onedrive.com/up/eyJSZXNvdXJjZUlEIjoiMkRCOUNDOUQyRTc2MjZBNCE1MTkiLCJSZWxhdGlvbnNoaXBOYW1lIjoiL3RlbXBfIy56aXAiLCJBbGlhcyI6bnVsbH0/3mV7bIhZh_P_NkQ4YkbPiahDmc8bKLCg6brpP43hNSEsvqoiRVJwjpGHwEcgWZ0kWR/eyJAbmFtZS5jb25mbGljdEJlaGF2aW9yIjoiZmFpbCIsIk5hbWUiOiJ0ZW1wXyMuemlwIn0"

The response I get is 401 with this content:
{"error":{"code":"unauthenticated","message":"Authentication failed"}}

**Comment by ificator** [comment]
All requests to the OneDrive API require the Authorization header, with the exception of the download urls and thumbnail urls. Regarding expiration of the token during upload the expectation is that the caller should keep track of the lifetime of the token, and perform appropriate refreshing to ensure the token provided to each fragment request is not expired. You can take a look at our SDKs to see examples of how we do this in our own code.

I'm not sure why you'd see a success for the scenario where the file name doesn't include the # character thought... that's definitely not expected.

**Comment by wnojopra** [comment]
Thanks for the response.

The fact that my uploads are working without supplying the token on each fragment put may be a bug on OneDrive's end, but perhaps its something that should remain as is. I have already supplied the access token in the call to upload.createSession, so we can tie the security of the subsequent fragment upload requests to the upload url.
