### ISSUE TITLE
action.copy does not work for files

### ISSUE THREAD

**Issue by ificator** [OneDrive/onedrive-api-docs#18]
[Forking bug from https://github.com/OneDrive/onedrive-api-docs/issues/15 to track the issues separately]

It appears as though such a copy request gets stuck in a state whereby it's not processed.

**Comment by mikechiu1012** [comment]
hi there,

I am testing for copy feature and found some scenarios will cause failed.
1) copy folder from subfolder to root folder. e.g. copy /dir1/a --> /
2) copy folder from root folder to root folder with other name. e.g. copy /dir1 --> /dir2

both two test case will get error response:
< Response [404] > {u'error': {u'innererror': {u'innererror': {u'code': u'folderDoesNotExist'}, u'code': u'itemDoesNotExist'}, u'message': u'Item Does Not Exist', u'code': u'itemNotFound'}}


I hope this information is helpful. thanks!

**Comment by rgregg** [comment]
We're working on a fix for this bug. Thanks for reporting it!

**Comment by bscharm** [comment]
I am experiencing a similar issue thought not exactly the same as this. I am POSTing to /action.copy with both a proper path and ID and I am receiving a 202 back from the server, though when I do the Location header on the reply contains a bad link, and the file is never getting copied. I have seen others have this same issue on StackOverflow and they suggest to revert to the old API (though I'd rather not). Is there someone I can reach out to regarding this? Or is there a timeline for a fix? Thanks!

**Comment by ificator** [comment]
Hi @bscharm, the fix for this has definitely taken a lot longer to get out the door than we'd have liked but we should **almost** be there. I'll update the thread once things look good.

Having said that, the current issue is related to valid monitor URLs that never make any progress so it sounds like your issue may be slightly different. Can you confirm that the we give you doesn't work, or by "bad link" do you mean that we return data but it never seems to make progress?

Thanks!

**Comment by bscharm** [comment]
I have double checked the response on the POST to /action.copy to be sure I am getting a 202 Accepted, and indeed I am. The response from the Location get is 
```json
{"error":{"code":"invalidArgument","message":"Bad Argument","innererror":{"code":"badArgument"}}}
```

**Comment by ificator** [comment]
Thanks. Could you provide the HTTP headers that came with that response? There's something else going on with your request.

**Comment by bscharm** [comment]
Here are the response headers I am getting back-
```
{x-msnserver=[DM2302____PAP224], date=[Tue, 07 Apr 2015 19:20:46 GMT], content-length=[0], server=[Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0], preference-applied=[respond-async], content-encoding=[gzip], location=[https://api.onedrive.com/v1.0/monitor/2sUl3DKLR3bKcJGvxkvI1cQOVbSKe5q-aTxXTciJPJu213K9QcUhPAhrxATNSwl7eB-qsQa0Bk8VNEPFlXi9sBgwJcwnNTVrEArZobB76EmcbAjotaP_CtmifTxIqREvsDposrlYz6j7kdf2jByXJe1w], x-wlsproxy=[BL3302____PAP067], p3p=[CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"], x-asmversion=[UNKNOWN; 19.17.0.0], via=[1.1 BL3302____PAP067 (wls-colorado)], x-asmversion-proxyapp=[UNKNOWN; 19.17.0.0]}
```

**Comment by ificator** [comment]
@bscharm, the monitor URL requires the Authorization header and based on the data in the response my guess is that it's missing. Can you confirm?

If that's the case we should obviously improve our error messaging, which is a common theme in the past couple of days. We'll get right on that.

**Comment by bscharm** [comment]
@ificator that was definitely the issue for the error response. Thats my fault for forgetting this! After adding the authorization header I am seeing the following JSON response-
```
{"operation":"ItemCopy","percentageComplete":0.0,"status":"notStarted","statusDescription":"Completed 0/0 files; 0/0 bytes"}
```
and the files are still not being copied. Same result when using path or ID.

**Comment by ificator** [comment]
Yeah, we're back to this issue now. Hopefully we'll have good news soon ;)

**Comment by bscharm** [comment]
Awesome, I will keep an eye out on this thread, thanks for your incredibly prompt responses and support.

**Comment by ificator** [comment]
Good news time - copy files should work now! Copying folders is still not working (it'll just copy the folder and not the children) but that'll be fixed pretty soon.

**Comment by bscharm** [comment]
@ificator I can definitely copy files, but it is not taking the "name" property and instead always keeps the original name. In the case of copying to the same folder as the original, I get back the following error message-
```
{code=itemNotFound, message=Item Does Not Exist, innererror={code=itemDoesNotExist, innererror={code=folderDoesNotExist}}}
```
which I'm thinking should be something along the lines of "file already exists" since it is trying to create a file with the same name. Copying to a new folder works, but as I said it keeps the original name no matter what. Once again really appreciate your help on this!

**Comment by ificator** [comment]
I've confirmed the rename issue. Let's do this - you create a new issue on the "copy to the same folder as the original" issue including all of the response headers as what you put above, and I'll create a new issue to track the name issue. That way we can close out this issue before it morphs in to a generic "copying is working as expected for me" :).

Thanks!
