### ISSUE TITLE
[Question] Get metadata for a OneDrive item by drive/items:path or drive/root:path

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#182]
hi forks,
I want to get metadata by path, so i use the following HTTP request

```
GET /drive/root:/{item-path}
```

it work so fine in od_v1, but failed in od_business
instead, i use this

```
GET /drive/items:/{item-path}
```

it works in od_business (except path=='/' ) but not in od_v1
And it was not documented.

So should I keep use this HTTP request or it was a bug need to be fixed

thx!

**Comment by ksheode** [comment]
GET /drive/root:/path/to/file (access by path) and GET /drive/items/{item-id} (access by id relative to root) should work in both ODB and ODC API. Details are under Root Resources in https://dev.onedrive.com/README.htm.

Could you provide some details on the failing request when you try GET /drive/root:/{item-path} in ODB?

FYI - GET /drive/items/{item-id}:/path/to/file (access by path relative to another item) is supported in the ODC API and support for this in the ODB API is coming soon.

**Comment by joewutaiwan** [comment]
hi @ksheode ,
thanks for reply,
GET /drive/root:/path/to/file only failed when path/to/file is '/'
```
GET /drive/root:/
```
```
{
  "error": {
    "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
    "message": "運算式 \"me/files('root'):\" 無效。"
  }
}
```
but it works in ODC

**Comment by ksheode** [comment]
Thanks for pointing this out @joewutaiwan. 

GET /drive/root: and GET /drive/root:/ not working is a known bug in ODB API and we have just completed the work to fix the issue. 

The fix should be available worldwide by mid-September.

**Comment by ificator** [comment]
There are no known issues with path based access using the colon notation so I'm going to close this off - it looks like we just neglected to resolve when it was fixed.

If you're still seeing issues please reactivate.
