### ISSUE TITLE
view.changes returns the wrong select argument for nextLink

### ISSUE THREAD

**Issue by ddurdle** [OneDrive/onedrive-api-docs#184]
When calling view.changes with select=%40content.downloadUrl%2Cname%2Cid%2Csize%2Cfile, the nextLink returned drops %40content.downloadUrl and returns only 
select=name%2Cid%2Csize%2Cfile

It should not drop any select values.

**Comment by ificator** [comment]
Great find @ddurdle! This is definitely an issue on our part - we'll get it fixed right away.

**Comment by rgregg** [comment]
This should be fixed and deployed.
