### ISSUE TITLE
[Question] metadata in One Drive For Business

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#185]
in ODC, the meta data would contain 
{"mimeType": "application/onenote"}
but it does not in ODB

is there any alternatives?

thx!

**Comment by rgregg** [comment]
Are you specifically looking for how you can identify OneNote folders/files or are you generically interested in the mimeType of files?

**Comment by joewutaiwan** [comment]
@rgregg ,
thanks for reply!
I want both.
appreciated!

**Comment by joewutaiwan** [comment]
hi @rgregg ,
Sorry to bother you.
Is only way to determine by Filename Extension?
Appreciated!

**Comment by rgregg** [comment]
Yes, for OneDrive for Business we don't provide the MIME type currently. Even in personal OneDrive, the mime type is our best guess, it may be wrong or not reflect the mime type provided when the file was uploaded.

**Comment by joewutaiwan** [comment]
thanks for reply, =)
