### ISSUE TITLE
How to integrate office 365 in web project

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#186]
Currently, I had integrate oneDrive in our web project, we can upload documents both from oneDrive and local.
And now I try to integrate office 365 in our project, so that we could preview & edit the uploaded documents in browser.  
But I have no idea about office 365 integrate, anyone have idea about it? Thanks!

**Comment by rgregg** [comment]
This is a pretty open-ended question. If you have a more specific question, please feel free to open another issue.
