### ISSUE TITLE
Getting 500 Internal Server Error when logging in

### ISSUE THREAD

**Issue by lfcgomes** [OneDrive/onedrive-api-docs#187]
Hi guys,

I'm trying to implement a log in  feature in my web application so users can access to their one drive accounts, using the OAuth 2.0 (https://dev.onedrive.com/auth/msa_oauth.htm#code-flow).

So, after receiving the authorization_code, I'm trying to request the access_token (step 2 on the diagram I posted above). And that's where the things are going wrong. For some reason that I don't know, in this step I'm always getting "500 Internal Server Error" message, no matter the parameters I send in the request.

I'm posting my code here, in nodejs.

````
var data = '{"code": "'+ code +'","grant_type" : "authorization_code","client_id" : "'+clientID+'","client_secret" : "'+clientSecret+'","redirect_uri" : "'+userINFO.redirect_uri+'"}';
                    var params = {
                        host: 'login.live.com',
                        path: '/oauth20_token.srf',
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded'
                        }
                    };
                    var body = '';
                    var req = https.request(params, function (response) {

                        response.on('data', function (chunk) {
                            console.log('DATA');
                            console.log(chunk);
                            body += chunk;
                        });

                        response.on('end', function(){
                            console.log('END')
                            console.log('body ' + body);
                        });
                    });
                    req.write(data);
                    req.end();
````

Even if I pass wrong client id, or secret, the only error I get is "500 Internal Server Error".

This is my output:

DATA
< Buffer 35 30 30 20 49 6e 74 65 72 6e 61 6c 20 53 65 72 76 65 72 20 45 72 72 6f 72 >
END
body 500 Internal Server Error

I'm following the documentation, but I cannot manage a way to implement this.

Does anyone have any idea?
Thanks!

**Comment by rgregg** [comment]
Can you use Fiddler or a similar tool to capture a trace of the HTTP traffic and attach that trace?

**Comment by rgregg** [comment]
Closing due to lack of a reply. Feel free to reopen with more details.
