### ISSUE TITLE
[OneDriveBusiness] access_token fail after refresh in trial free account

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#188]
hello guys,
I registered a trial free account for test for a while (about several days )
In beginning , it works so fine
but one day, the access token could not work after refreshed
```
{
"error":"invalid_client",
"error_description":"Invalid audience Uri 'https:\/\/onlyforjoe-my.sharepoint.com\/'."
}
```
But this account isnt expired yet, it still be in trial period.
However, the paid account do not encounter this.

I want to know this is policy or something wrong?

thx!

**Comment by rgregg** [comment]
Joe, can you show the full request (minus the access token value) and response you're seeing?

**Comment by joewutaiwan** [comment]
hi @rgregg ,
sorry for late reply.
But now I have no that testing environment.
I think this problem might affected by the "return 401" bug.
So I might have more test after your server fixed.
