### ISSUE TITLE
OneDrive for Business download API returning 401

### ISSUE THREAD

**Issue by CS1-MDM03** [OneDrive/onedrive-api-docs#189]
I am using the "GET /drive/items/{item-id}/content" API to download file's contents.

OneDrive for Business documentation mentions that:
"When downloading an item's content from OneDrive for Business, instead of receiving a 302 redirect to the download URL, the content will be returned directly as the response of the API call."
This is what was happening earlier.

Recently, instead of directly returning the content, the OneDrive for Business download API too returns a 302 first. I successfully follow the 302 to the download URL, but instead of 200 response, the second request gives a 401 response(on examining the response, I found out that even though it returns 401, it gives me the file contents in the response body)

This is very critical as my app has a logic to refresh the access token whenever it gets a 401, so on every download the app refreshes the access token. Access token is otherwise valid, all other operations, like listing folder's contents, creating file/folder, rename, etc. are successful with the same access token.

![screen shot 2015-08-26 at 2 47 21 pm](https://cloud.githubusercontent.com/assets/12709104/9489867/b0ddea7a-4c01-11e5-8916-b78e27235263.jpg)

![screen shot 2015-08-26 at 2 47 38 pm](https://cloud.githubusercontent.com/assets/12709104/9489873/b5d9da70-4c01-11e5-9668-abba6eae6dba.jpg)

**Comment by joewutaiwan** [comment]
I got the same problem Q_Q

**Comment by nitishjha** [comment]
Having the same problem. Any update on this one?

**Comment by rgregg** [comment]
This looks like a bug for sure.

Can you try the request to the download URL without the Authorization header? I believe that should work and give you back a 200 OK instead of the 401 Unauthorized error. The download URLs are short-lived and do not require authentication.

**Comment by joewutaiwan** [comment]
I got 403 instead.
how long is the short-lived period?
I upload the file by webpage, and download it without Authorization header in 5s

**Comment by CS1-MDM03** [comment]
Yes, the download URL throws a 403 without authorization header.

The redirects are not handled by our code but by the http client itself, and if you provide authorization header to the http client, it puts that in all redirects as well. 
Also, we already have apps with OneDrive integration in the market, and as I mentioned, right now they are refreshing access token on every download request. The apps work perfectly with normal OneDrive(non-Business) APIs, and there too we get a 302 first.
That's why, even if hitting the second URL without the authorization header works, it won't be the solution to this issue.

**Comment by ankit-ankuagrawal** [comment]
@rgregg sir any update on this. Our product is out in market but due to this bug we are facing much problem.

**Comment by ificator** [comment]
Just to keep you guys in the loop, we've tracked down the issue and are working on a fix. We'll update with an ETA when we have one.

**Comment by CS1-MDM03** [comment]
@ificator, Thanks a lot.

**Comment by nitishjha** [comment]
Hi @ificator 
Could you please help us if there has been any progress made on pushing the fix out for this one?

**Comment by ificator** [comment]
Unfortunately the area in which the issue resides is making potential fixes more complicated. I can't give an ETA just yet, but we're definitely making progress. I'm aware this isn't a very useful answer, but it's unfortunately the best we have at the moment.

**Comment by nitishjha** [comment]
Thanks for the update, @ificator 
However, please do understand that there are real world customers who are waiting to get this in their hands to try and compare the product with other solutions. This is a very core feature in the product and not being able to even try this product does affect its reputation even before they have got a chance to try it!
Any help to expedite this would be greatly appreciated.

**Comment by ificator** [comment]
Sorry for the radio silence, but I have some good news! We managed to come up with a safe fix for this issue, and it's on its way now. Our estimate is that it should be 100% available by 10/28.

**Comment by ankit-ankuagrawal** [comment]
@ificator ty for the update 

recently there was update for download api (https://github.com/OneDrive/onedrive-api-docs/blob/master/items/download.md)

"When you download an item's content by requesting its /content property, you must provide the Authorization header, in order to be granted access to download. The response would normally return a 302 redirect to the URL where the file can be downloaded from. This URL is pre-authenticated and does not require the Authorization header. However, if you specify an Authorization header to this download URL when downloading an item's content from OneDrive for Business, you will receive a 401 error"

is this same safe fix which are you talking about in above comment?

**Comment by ificator** [comment]
That snippet is outline a work around to stop the 401s from occurring when following the redirect, however it will be unnecessary once the code fix has shipped. We'll update the documentation when that happens, but for the interim it's really the only way you can make things work.

If you implement behavior as currently documented you will not see any functional change once our code fix ships.

**Comment by joewutaiwan** [comment]
any updates about this issues? still receive 401 @@!
or should I change some setting?
thank you!

**Comment by joewutaiwan** [comment]
hi guys, i got a little confused.
The safe fix on 10/28 is going to solve the 'redirect return 401' problem with content api,
and the OD and ODB will both work fine with this download api?
Or just a workaround the former mentioned to stop the 401s,
and ODB still failed at this download api with auto redirect??

thank you

**Comment by KoenZomers** [comment]
I'm facing this issue as well. Can't get anything downloaded from OneDrive for Business using the OneDrive v2.0 API.

**Comment by rgregg** [comment]
The fix is now deployed to nearly all tenants with the last few remaining tenants getting resolved this week.

**Comment by ificator** [comment]
The deployment that resolves this issue is now complete.
