### ISSUE TITLE
How to do localization with javaScript SDK

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#190]
Currently, we try to do localization in our product, I found oneDrive javaScript SDK provide library for each language. It seems we need to switch library when we change the product's language.

I don't think this is a good way. Do we have a library which contains all of the language packages, so that we do not need to switch library? Or if we have a good way to do localization?

**Comment by jscaria** [comment]
Hi @benjaminliugang - we don't have a library that contains all the language strings.   Yes, you're correct - once you know the user's locale, you have to load the corresponding SDK.   There are more details at https://msdn.microsoft.com/en-us/library/hh550837.aspx.   

I've made a note of your concern about how this isn't ideal for you.    Please reopen this issue if this doesn't answer your question.
