### ISSUE TITLE
 action.copy does not work for files or folders (please reopen)

### ISSUE THREAD

**Issue by PNowell67** [OneDrive/onedrive-api-docs#191]
Still having problems with this issue where action.copy is accepted but never starts.

below is for a file copy, same behaviour is also observed for folder copy

URL

https://api.onedrive.com/v1.0/drive/items/2F95D6B4F7D1CDBA!296/action.copy

HEADERS

Authorization: Bearer EwBYAq1DBAAUGCCX...
Content-Type: application/json
Prefer: respond-async
User-Agent: com.smart40.files

BODY

{"parentReference":{"id":"2F95D6B4F7D1CDBA!300"}}

**Comment by mmarmol** [comment]
I am having the same issue also:

"POST /v1.0/drive/items/BF667A0C62207823!119/action.copy HTTP/1.1[\r][\n]"
"Content-type: application/json[\r][\n]"
"Authorization: Bearer EwBwAq...............
"Content-Length: 69[\r][\n]"
"Host: api.onedrive.com[\r][\n]"
"Connection: Keep-Alive[\r][\n]"
"User-Agent: Apache-HttpClient/4.3.1 (java 1.5)[\r][\n]"
"Accept-Encoding: gzip,deflate[\r][\n]"
 "[\r][\n]"
 "{"parentReference":{"id":"BF667A0C62207823!104"},"name":"copy_1.png"}"

I tried also using path copy both for item to be copied and parent and get same results.

[org.apache.http.headers] : http-outgoing-0 << HTTP/1.1 400 Bad Request
[org.apache.http.headers] : http-outgoing-0 << Via: 1.1 DM2304____PAP125 (wls-colorado)
[org.apache.http.headers] : http-outgoing-0 << Content-Length: 109
[org.apache.http.headers] : http-outgoing-0 << Content-Type: application/json
[org.apache.http.headers] : http-outgoing-0 << Content-Encoding: gzip
[org.apache.http.headers] : http-outgoing-0 << Server: Microsoft-IIS/8.5 Microsoft-HTTPAPI/2.0
[org.apache.http.headers] : http-outgoing-0 << X-WLSPROXY: DM2304____PAP125
[org.apache.http.headers] : http-outgoing-0 << X-MSNSERVER: SN3301____PAP023
[org.apache.http.headers] : http-outgoing-0 << Strict-Transport-Security: max-age=31536000; includeSubDomains
[org.apache.http.headers] : http-outgoing-0 << X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
[org.apache.http.headers] : http-outgoing-0 << X-ThrowSite: 621a.862f
[org.apache.http.headers] : http-outgoing-0 << X-AsmVersion: UNKNOWN; 19.30.0.0
[org.apache.http.headers] : http-outgoing-0 << X-MSEdge-Ref: Ref A: CEB1F657A88642F88552ACCD6079294B Ref B: E449DF2EA681A811EB41D7B9457542F0 Ref C: Wed Oct 21 09:42:04 2015 PST
[org.apache.http.headers] : http-outgoing-0 << P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
[org.apache.http.headers] : http-outgoing-0 << Date: Wed, 21 Oct 2015 16:42:04 GMT

**Comment by ificator** [comment]
@PNowell67 I'll look in to this today
@mmarmol Your issue appears to be that you aren't including the required "Prefer: respond-async" header

**Comment by mxhero-scm** [comment]
Quick feedback. @ificator you are right. That solved the copy issue at least on my case.

Thanks!

**Comment by ificator** [comment]
@mxhero-scm Thanks for letting us know!

@PNowell67 There were some know performance issues occurring around the time that you reported this. They should now be fixed, so can you let us know if you're still seeing issues?
