### ISSUE TITLE
Unable to detete file from App Folder

### ISSUE THREAD

**Issue by ki0ki0** [OneDrive/onedrive-api-docs#192]
My app scope is "wl.offline_access onedrive.appfolder" .
And I can upload file using:
`https://api.onedrive.com/v1.0/drive/special/approot:/test.txt:/content`

But I failed to delete this file using DELETE request to:
`https://api.onedrive.com/v1.0/drive/special/approot:/test.txt`
Error: Status code is 404 
```javascript
{"error":{"code":"itemNotFound","message":"Item does not exist"}}
```

But still can delete it using:
`https://api.onedrive.com/v1.0/drive/root:/Apps/AppName/test.txt`
even if i don't have "onedrive.readwrite" in my scopes.

**Comment by peternied** [comment]
@ki0ki0 I can confirm that deleting an item by using a special folders path isn't working, we are fixing it

Until we get that fix out, you can delete items by using the item id:
`https://api.onedrive.com/v1.0/drive/items/{item-id}`

**Comment by peternied** [comment]
This issue has been resolved.
