### ISSUE TITLE
Uploading large files on OneDrive

### ISSUE THREAD

**Issue by dima72** [OneDrive/onedrive-api-docs#194]
Please suggest right url path for upload of large files feature.

I'm trying to POST upload to
https://api.onedrive.com/v1.0/drive/items/folder.a5858c9cb698b77b:/myfile.txt:/upload.createSession

where folder.a5858c9cb698b77b is root folderID

but I'm getting error: 
{"error":{"code":"invalidRequest","message":"API not found"}}: {"error":{"code":"invalidRequest","message":"API not found"}}'

thanks in advance,

**Comment by rgregg** [comment]
The item ID that your using looks like an ID from the Live Connect API. Those IDs aren't compatible with the OneDrive API. You'll need to use the OneDrive API to find the item's ID or use the path syntax to address the folder by path.

**Comment by rgregg** [comment]
For root, you can do this:

POST https://api.onedrive.com/v1.0/drive/root/upload.createSession

**Comment by dima72** [comment]
POST to 'https://api.onedrive.com/v1.0/drive/root/upload.createSessionaccess_token=....

with access_token applied 
returns 404 and {"error":{"code":"invalidRequest","message":"API not found"}}'
either.

thanks in advance for any help.

**Comment by dima72** [comment]
rgregg, thank you for kicking me 
https://api.onedrive.com/v1.0/drive/root:/myfile.txt:/upload.createSession?access_token=....

works. my mistake was missing ? sign to separate params part in url.

**Comment by rgregg** [comment]
No worries, glad you got it working!
