### ISSUE TITLE
How to do localization for javaScript SDK

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#195]
How can I do localization for javaScript SDK? So that I can switch from one language to another language in my project.

Should I import all of the libraries in this page (https://msdn.microsoft.com/en-us/library/dn631825.aspx), or I just need to pass a param to change the language?

**Comment by jscaria** [comment]
Hi @benjaminliugang - once you know the locale that the user is in, you can load the corresponding JavaScript SDK.   There's more details on the SDK URL format at https://msdn.microsoft.com/es-es/library/hh550837.aspx.  You may want load the SDK dynamically, which is described further at http://www.javascriptkit.com/javatutors/loadjavascriptcss.shtml.    

Please reopen this issue if you feel that this didn't answer your question.

**Comment by benjaminliugang** [comment]
Hi @jscaria, it works well for oneDrive login page, but the file picker will always keep with the first language. I had filed another ticket about this issue, please help me check.

https://github.com/OneDrive/onedrive-api-docs/issues/197
