### ISSUE TITLE
File picker localization not works well for JavaScript SDK

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#197]
Currently, I just switch oneDrive library when user change language, then init oneDrive again, it works well for login dialog, but for file picker, it will always keep with the first language.

It there anything more need to do for file picker?

**Comment by benjaminliugang** [comment]
Hi @jscaria, can you help me to check this issue? Because we need to complete oneDrive localization task in this sprint.
BTW, I found when I open the filePicker, the request's *mkt* param value is right, but it still open with the first load language.

**Comment by jscaria** [comment]
We're looking into this.

**Comment by jscaria** [comment]
Can you reproduce this in a new incognito session?

**Comment by benjaminliugang** [comment]
Hi @jscaria, it seems it's a cache issue. When I cleaned my browser's cache, it will open the file picker with expect language. But if I don't clean the cache, it will always open the file picker with the first open language.

Is there any method in SDK to clean the file picker cache, so that I could clean the cache when I switch to another language.

**Comment by jscaria** [comment]
Currently, there's no supported way to clear that without the user manually picking his or her language on the OneDrive website.

**Comment by benjaminliugang** [comment]
So @jscaria , do you have any suggestion about it?

**Comment by Faiza294** [comment]
Hii did any one find solution about clearing filepicker cache ? I'm having same problem.
