### ISSUE TITLE
URLs for stylesheets/scripts and links in header are broken in subfolders

### ISSUE THREAD

**Issue by elyscape** [OneDrive/onedrive-api-docs#2]
The various relative URLs for stuff are broken on the site when not in the root folder.  For example, check the source on [the page about viewing changes](http://onedrive.github.io/items/view_changes.htm):
```html
<link rel="stylesheet" href="..\stylesheet.nav.css" />
<!-- [...] -->
<img src="..\onedrive_api_blue.png" height="24" alt="OneDrive API" align="absmiddle">
<!-- [...] -->
<li class="active"><a href="..\README.htm">Documentation</a></li>
<!-- [...] -->
<li ><a href="..\sample-code.htm">Samples</a></li>
<!-- [...] -->
<script src="..\ie10-viewport-bug-workaround.js"></script>
```
This causes those images/scripts to not load and the links to not work.

**Comment by rgregg** [comment]
Elyscape, what browser are you using? I've tried to reproduce any issue here in Chrome and IE and both of those browsers are able to handle the relative URLs and render properly.

**Comment by elyscape** [comment]
The problem is that the path divider used is `\` instead of `/`.  I'm using an oldish version of Firefox (24, to be specific), but that should still be fixed even if current browsers work with it.

**Comment by rgregg** [comment]
Ah yes, you're right. I'll get that fixed.

**Comment by rgregg** [comment]
Should be all fixed up. Let me know if you still see a problem.

**Comment by elyscape** [comment]
Looks good.  Thanks for your help!
