### ISSUE TITLE
need to be more clear what the payload is for "Simple item upload to OneDrive using PUT"

### ISSUE THREAD

**Issue by shrimpywu** [OneDrive/onedrive-api-docs#20]
need to be more clear what the payload is for "Simple item upload to OneDrive using PUT"
http://onedrive.github.io/items/upload_put.htm

have no idea what kind of content i should put into payload, e.g if i want to upload an png or jpeg, do i just dump all the binary there? (doesn`t seems like the case)

**Comment by daspek** [comment]
Yup, you do just dump the binary data there. Is that not working for you?

**Comment by shrimpywu** [comment]
yep.. works! thanks!
