### ISSUE TITLE
OneDrive for business how to start?

### ISSUE THREAD

**Issue by dima72** [OneDrive/onedrive-api-docs#200]
Dear all,
I'm looking into interacting with OneDriveForBusiness on REST level.
please give me simple workable example of GET request to get drive metadata /drive
assuming you are using your own access tokens.

https://{tenant}-my.sharepoint.com/_api/v2.0/drive
seems does not work for me.

thanks in advance.

**Comment by rgregg** [comment]
Depending on the version of SharePoint your tenant is running, you may need to construct the base URL as follows:

`https://{tenant}-my.sharepoint.com/_api/v2.0/me/drive`

This is a bug in an older build of the service that should be nearly out of production by now.
