### ISSUE TITLE
No way to retrieve user email/name

### ISSUE THREAD

**Issue by JaredBanyard** [OneDrive/onedrive-api-docs#202]
As far as I can tell there is no route to retrieve user email/username for display purposes?

**Comment by peternied** [comment]
The createdBy and lastModifiedBy will contain a set of [identities](https://dev.onedrive.com/resources/identity.htm) which have a Display Name within them.

**Comment by JaredBanyard** [comment]
Sorry if I was unclear, this is for account display purposes.  Not for file display.  I need to be able to display it without any files (that could change) so that I have a permanent solution.

**Comment by peternied** [comment]
The [Drive](https://github.com/OneDrive/onedrive-api-docs/blob/master/drives/default.md) object has an owner associated with it, which can be used for display purposes

**Comment by JaredBanyard** [comment]
Yeah that has the display name but not the email address/username.

**Comment by peternied** [comment]
The OneDrive API does not store or expose account information (Such as email address/username) at this time.

If you are looking to resolve user's email address information, there is a Mail API offered by Outlook https://dev.outlook.com/; however, the exposed information might not be useful for users that do not use an outlook.com email address.

**Comment by rgregg** [comment]
@JaredBanyard It's on our backlog to add email address for the drive owner.

**Comment by dluces** [comment]
@rgregg will it be possible to retrieve the email address from an [Identity](https://dev.onedrive.com/resources/identity.htm) id? I'm needing to get the email addresses of people that a document is shared with--so from the response of [this API call](https://dev.onedrive.com/items/permissions.htm) (the grantedTo property).

**Comment by DineshDhyani** [comment]
any resolution to this issue? How else can we associate(to what user identiafiable id) the integrated onedrive using oauth?

**Comment by rgregg** [comment]
For OneDrive for Business, you can use the [Microsoft Graph API](http://graph.microsoft.io) to look up information about the user IDs returned by the OneDrive API. With OneDrive Personal, there is currently no API available to give you more information about a given user ID due to privacy concerns. We're investigating available options for making some information available, depending on the relationship between users.

**Comment by DineshDhyani** [comment]
Thanks for the quick response @rgregg

**Comment by sloba88** [comment]
@rgregg Is this added to OneDrive api yet? Microsoft Graph Api has different limitations when it comes to upload size in Drive than OneDrive api so we couldn't use it.

**Comment by rgregg** [comment]
It's not, and likely won't be. Microsoft Graph now provides access to consumer account profile information as well, and supports all the same capabilities at the OneDrive API. While the upload size for a PUT request through Microsoft Graph is limited at 4mb, you can upload any size file using the [createUploadSession API](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_createuploadsession).

**Comment by rgregg** [comment]
The recommendation now is to use [Microsoft Graph API](https://graph.microsoft.com) to accomplish this:

`GET https://graph.microsoft.com/v1.0/me`

More details are available here: [Working with Users](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/users).
