### ISSUE TITLE
Can't pull thumbnails in list for OneDrive for Business

### ISSUE THREAD

**Issue by JaredBanyard** [OneDrive/onedrive-api-docs#203]
Why isn't this supported?

**Comment by rgregg** [comment]
Can you elaborate on what REST call you're making that isn't working?

**Comment by JaredBanyard** [comment]
`/_api/v2.0/me/drive/root?expand=children(expand=thumbnails)`

**Comment by rgregg** [comment]
Yes, that's a [known issue right now](https://dev.onedrive.com/odb-preview/release-notes.htm#thumbnails-collection).

We're working on getting this supported.
