### ISSUE TITLE
[Question] Does OneDrive will support versioning API?

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#204]
Hi, I wonder if OneDrive API will support versioning API, cause of some implementation requests.

thanks!

**Comment by rgregg** [comment]
If you mean API access to multiple versions of a file, it's on our backlog. We use votes on our [UserVoice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) page to help prioritize backlog items, so consider adding/voting for file versions.
