### ISSUE TITLE
OneDrive for business Oauth2 

### ISSUE THREAD

**Issue by dima72** [OneDrive/onedrive-api-docs#205]
Dear All,
I have portal.office.com account and want to access OneDrive for business at tenant-my.sharepoint.com by means of my REST application.
I have registered my application in Azure Active Directory and starting Oauth2 authentication like this:

https://login.windows.net/common/oauth2/authorize?response_type=code&client_id='+ App.Key +  '&redirect_uri=http://localhost:8889/';

On this phase I have got AuthCode from azure and next phase is obtaining session tokens.

As next step in authentication I'm doing POST request to https://login.windows.net/common/oauth2/token
with params:
    'client_id=' + App.Key
    + 'client_secret=' + App.Secret
    + 'code=' + AuthCode
    + 'redirect_uri=http://localhost:8889/'
    + 'grant_type=authorization_code'
    + 'resource='+URLEncode('syncovery1');

Unfortunately I'm getting error in response:
{"error":"invalid_resource","error_description":"AADSTS50001: The application named syncovery1 was not found in the tenant named konnov.onmicrosoft.com.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 1af2ced2-b2bb-4568-8a87-bd2d1186cf9a\r\nCorrelation ID: 15dcda2c-0599-4279-8744-27c61e6912a9\r\nTimestamp: 2015-10-06 07:46:03Z","error_codes":[50001],"timestamp":"2015-10-06 07:46:03Z","trace_id":"1af2ced2-b2bb-4568-8a87-bd2d1186cf9a","correlation_id":"15dcda2c-0599-4279-8744-27c61e6912a9"}'

Please suggest the ways to a possible solution. In my portal.office.com account I can not find any place where third party application might be associated with the account. Can you guess the meaning of the 'resource' param in the last request?
What services or licences in portal.office.com should be active to allow authentication? Maybe I just don't have OneDriveForBusiness subscription activated?

Thanks in advance,

**Comment by aclev** [comment]
Hi @dima72 
The resource for OneDrive for Business is usually  `https://{tenant}-my.sharepoint.com/_api/v2.0/me/ `However, you won't know the tenant of the user when they login. If you take a look at OneDrive for Business authentication [documentation](https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/aad_oauth.md) you can see in [step 2](https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/aad_oauth.md#step-2-redeem-the-authorization-code-for-tokens).  The resource used is `https://api.office.com/discovery`/.  This is because in  [step 3](https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/aad_oauth.md#step-3-discover-the-onedrive-for-business-resource-uri) you will call the discovery service API to discover the endpoint URL for the OneDrive for Business API. Once you have this URL you can continue to [step 4](https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/aad_oauth.md#step-4-redeem-refresh-token-for-an-access-token-to-call-onedrive-api) where you use the URL you obtained in step 3 as the resource.
Thanks!

**Comment by dima72** [comment]
Dear Aclev, thanks for supporting me,

I tried https://api.office.com/discovery/ as 'resource' param,
but getting error:

{"error":"invalid_resource","error_description":"AADSTS50001: Resource ''https://api.office.com/discovery'' is disabled.\r\nTrace ID: d57cc0c8-9135-45a6-a668-d04a4e4fd919\r\nCorrelation ID: 78402acd-b8ad-4e9a-921a-36bf81d6d4ed\r\nTimestamp: 2015-10-06 17:07:42Z","error_codes":[50001],"timestamp":"2015-10-06 17:07:42Z","trace_id":"d57cc0c8-9135-45a6-a668-d04a4e4fd919","correlation_id":"78402acd-b8ad-4e9a-921a-36bf81d6d4ed"}'

at the moment I have all subscriptions in portal.office.com cancelled.
In your view, what kind of service or subscription should be activated to allow discovery service?

Thanks in advance.

**Comment by peternied** [comment]
Try using 'https://api.office.com/discovery' as the resource id

**Comment by aclev** [comment]
If you see the [Office 365 documentation](https://code.msdn.microsoft.com/Office-365-APIs-How-to-use-609102ea#content) in the configuring permissions section you will see how to add both Azure Active Directory and SharePoint online in your permissions section in the portal.  Those two should be enough to access OneDrive for Business.

**Comment by dima72** [comment]
Doc says:
/////////////////////////////////////////////////////////////////////////////////////////
To sign into OneDrive for Business the first time, your app needs the following values:

Client ID and Key (client secret) as registered with Azure Active Directory (AAD)
Authorization code received from OAuth 2 authorization code flow
OneDrive for Business API endpoint URL
Access token for the OneDrive for Business resource
Refresh token to generate additional access tokens when the current token expires.
///////////////////////////////////////////////////////////////////////////////////////////

I have application registered with Azure Active Directory (AAD) and Client ID and Key.
I have Authorization code received from OAuth 2.

where do I take: OneDrive for Business API endpoint URL?

should I have OneDrive for Business payed subscription activated in portal.office.com?

Thanks in advance,

**Comment by aclev** [comment]
See will see in our documentation at [step 3](https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/aad_oauth.md#step-3-discover-the-onedrive-for-business-resource-uri)  You use the discovery API to discover the OneDrive for Business API endpoint URL.

**Comment by dima72** [comment]
Aclev, thank you for directing me to step3.

I stuck in redeeming authorization code for tokens.
Doc says:
Step 2. Redeem the authorization code for tokens
resource	string	The resource you want to access.

What kind of resource should be provided? Is it name of application or http resource?
Please give me examples.
I'm providing name of my application as resource - 'resource=syncovery1';

but response of server is:

{"error":"invalid_resource","error_description":"AADSTS50001: The application named syncovery1 was not found in the tenant named konnov.onmicrosoft.com. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 1af2ced2-b2bb-4568-8a87-bd2d1186cf9a\r\nCorrelation ID: 15dcda2c-0599-4279-8744-27c61e6912a9\r\nTimestamp: 2015-10-06 07:46:03Z","error_codes":[50001],"timestamp":"2015-10-06 07:46:03Z","trace_id":"1af2ced2-b2bb-4568-8a87-bd2d1186cf9a","correlation_id":"15dcda2c-0599-4279-8744-27c61e6912a9"}'


thanks in advance,

**Comment by dima72** [comment]
If i provide resource = https://api.office.com/discovery/
I'm getting error:

{"error":"invalid_resource","error_description":"AADSTS50001: Resource ''https://api.office.com/discovery/'' is disabled.\r\nTrace ID: e7137f83-a44c-46c0-b786-880d036ffead\r\nCorrelation ID: 3721422e-ebdb-4135-bad5-ef93e91e24e2\r\nTimestamp: 2015-10-07 14:23:46Z","error_codes":[50001],"timestamp":"2015-10-07 14:23:46Z","trace_id":"e7137f83-a44c-46c0-b786-880d036ffead","correlation_id":"3721422e-ebdb-4135-bad5-ef93e91e24e2"}'

Please advice how to enable https://api.office.com/discovery/ in my account, or what might be a problem. 

Thanks in advance,

**Comment by aclev** [comment]
Can you post the URL and body your are posting to in step 2? Make sure to scrub your client id/secret/redirect URL.  Thanks.

**Comment by dima72** [comment]
POST https://login.windows.net/common/oauth2/token/client_id=1a975277-ee0b-46bd-919e-325474q4f534&client_secret=C77LbDTGuWfb6z4oEt2uw9PrT0ETI%2FQzJmeVrYLSVOk%3D&code=AAABAAAAiL9Kn2Z27UubvWFPbm0gLc6YTEZ4fNZ6eICOLWOHDsFrGGTFPbzv8lbJE1Nug6NjgaC-dJOvOYxcqNzJUllnZowXWDDGqY8Ec6nQoZNgfHnXe7fpIh92FVlzjvWT4X3qSfEeln250_sYQ_4Yq5nSeaECvjjJIWtRx2Yz0XzHVDB1023n_mMo__HyKXml1uzuHALMbail4RnViWb4zyYfzW5TgPB9rHLKE7_VL6dO6HqDkmW4s-LxPkCGUll-1-V2vSv-UVzGmFEIQ3UjbyUx14qUNm1gTOwtCRpibbPuajLSxT3uzrYh8XnNhwXRdUqnagBa1HZGztE8EPNjVc-nJKALpAol5DVFG2MzEV1bjoJuqnSQVn1050P6WqeNHqHwOip0HQYQVqV861e-TDezmoiagoe3YqSVjrM1TRsCm2D02VFbBDvisQXb8srkeOHtqP53tP8d09oE0psg2SN6CUcK2xBtAJHxHYWQ_I2FDP0fNP7g9SSnDvtnUEgiCxS0Vce_euohOlGOoXDTN_7wSrbtPtLIyAfJY3WCoBmVuVy1Fhb05hJ7t8mei9IVgk4cEGLXCxEEVab74blMmIECyCAA&redirect_uri=http%3A%2F%2Flocalhost%3A8889%2F&grant_type=authorization_code&resource=https%3A%2F%2Fapi.office.com%2Fdiscovery%2F'

**Comment by aclev** [comment]
You should be making a POST to `https://login.windows.net/common/oauth2/token` 

with the body  :
```
client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}
&code={code}&grant_type=authorization_code&resource={resource_id}
```
Not in the query parameters.  You also need to make sure that your redirect_uri is the same as the one in the portal.
As I mentioned above you should hide your cliend id, client secret, and redirect URI when posting online.  I would recommend regenerating a client secret as you have publicly posted it.

**Comment by dima72** [comment]
Dear Aclev,
thank you for supporting! 
yes I'm making POST into https://login.windows.net/common/oauth2/token/   - right address

yesterday I asked my friend who has active Office365 developer subscription and active                       {tenant}-my.sharepoint.com  website (and obviously  Office365 developer subscription includes that ), I asked him to register application, and
for his account it works!
I'm getting 
"resource":"https://api.office.com/discovery/","access_token":" .....
in response!

Respectfully,

**Comment by dima72** [comment]
Dear All, thank you for supporting,

I have successfully redeemed tokens in Step4 and now have actual access_token.

but even I'm trying simple request

GET {serviceEndPointUri}/drive
Authorization: Bearer {access_token}

I'm getting
'HTTP ERROR 401: {"error_description":"Invalid issuer or signature."}'

Are there any specific rules for signing the url?

thanks in advance,

**Comment by rgregg** [comment]
Closing out this thread. If you're still having issues, feel free to reopen with more details.
