### ISSUE TITLE
Is it possible to delete a file into recycle bin ?

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#21]
Is there any way to implement delete operation like WEB UI does to move items into recycle bin?

Or I could use move command and indicate specific folder name recyclebin ?

I have been search for this for old API, but it does not support and found that:
http://stackoverflow.com/questions/23845368/is-there-any-way-of-accessing-recycle-bin-functions-of-onedrive

I wonder if this could be pulled as a request? cause I think its more safe to move file into recycle bin rather than real delete it.

thanks!

**Comment by rgregg** [comment]
Hi @mikechiu1012. The [delete action](https://github.com/OneDrive/onedrive-api-docs/blob/master/items/delete.md) does move the item to the recycle bin. Currently we don't have a way to access the recycling bin in the API, but the file is moved there instead of being deleted forever.

**Comment by mikechiu1012** [comment]
hi gregg, good day.

Yeah, I found out the files in recycle bin via delete api.

another question is, if I empty the recycle bin, the chage_list will return all the deleted files under root folder.

it seems like the files returned in changing list under the root folder but not under 'recycle bin'
I think this is a dummy (virtual) folder out out sight by developer API.

But this might be an overhead to maintain the changing list, local device must check all the files listed in the change_list for delete operation even thought the file is already gone.

If there is API to empty recycle bin or there's keyword returned in changing list could make developer to recognise items deleted from recycle bin will be a grateful help. :)

thanks.

**Comment by rgregg** [comment]
I've added an item to our backlog to flesh out the recycle bin and delete APIs to make this more clear. Not sure when we'll get to the work, but it's on our radar.
