### ISSUE TITLE
InvalidRequestError: Application display name could not be resolved

### ISSUE THREAD

**Issue by vitali-trend** [OneDrive/onedrive-api-docs#213]
For "GET /v1.0/drive/special/approot/children?access_token=...", One Drive *intermittently* returns this error:

    {"error":{"code":"invalidRequest","message":"Application display name could not be resolved"}}

The documentation says that invalidRequest is returned when the request is malformed or incorrect, but since I'm just repeating the same request and it fails only intermittently, it looks like there may be a bug in One Drive. Could you please advise whom I should contact about it to get it fixed and if there is any workaround for now?

**Comment by rgregg** [comment]
You've found the right place. @amanghag Can you take a look at what's going on here?

**Comment by amanghag** [comment]
Thanks for the report! We identified the issue and we’ll begin rolling out the fix today. We’ll let you know when it’s done.

**Comment by daspek** [comment]
@vitali-trend, the fix has been rolled out. Please let us know if things are working for you now.

**Comment by chriadam** [comment]
I was suffering from this issue also.  It appears to be resolved for us now.  Thank-you!

**Comment by vitali-trend** [comment]
Not seeing this issue any more. Thanks for fixing it!
