### ISSUE TITLE
View.Delta on items does not work for OneDrive for Business

### ISSUE THREAD

**Issue by Mertsch** [OneDrive/onedrive-api-docs#214]
`https://{tenant}-my.sharepoint.com/_api/v2.0/drive/items/{id}/view.delta`
returns
```
{
    "error": {
        "code": "notSupported",
        "message": "view.delta can only be called on the root."
    }
}
```
But https://dev.onedrive.com/items/view_delta.htm#remarks states that it support ODBiz, except for a few properties.

If would be nice if somebody can confirm this.

**Comment by daspek** [comment]
Hi @Mertsch, thanks for the heads up. We will update the docs. Currently, view.delta is only supported at the root on OneDrive for Business. So you'll need to make your call against `/drive/root`.

**Comment by Mertsch** [comment]
@daspek Thanks for the confirmation. The call against `drive/root` works fine. Can you give me any hint on how to actually get the details about the delta. As I see it now, I know that there are changes, but I actually have no chance of knowing who made what change and when. Is that correct?

**Comment by daspek** [comment]
That's basically correct. The delta response doesn't currently return `lastModifiedBy` but you should be able to know when a change was made by looking at `lastModifiedDateTime`.

**Comment by daspek** [comment]
Closing out the issue as the docs have been updated to reflect the expected behavior. Please keep an eye out for updates as we resolve the known differences between OneDrive and OneDrive for Business.
