### ISSUE TITLE
In pure WebAPI model, how to use serverside LiveSDK ?

### ISSUE THREAD

**Issue by arangari** [OneDrive/onedrive-api-docs#22]
Hi,

I am writing an WebAPI application, which authenticates user with their LiveID credentials from server side. 
I have written a filter implementing System.Web.Http.Filters.IAuthenticationFilter  which defines the method 
         AuthenticateAsync(HttpAuthenticationContext context, CancellationToken cancellationToken) 

for authentication. The method has parameter HttpAuthenticationContext. However when I try to use below code, I cant get the required context. 

LiveAuthClient authClient = new LiveAuthClient(...)
var result = await authClient.ExchangeAuthCodeAsync(???);

the ExchangeAuthCodeAsync() expects HttpContextBase parameter. 

In my MVC application, the IAuthorizationFilter.OnAuthorization(AuthorizationContext filterContext)  provides the HttpContextBase from its RequestContext as below.

var result2 = await authclient.ExchangeAuthCodeAsync(     
                                        filterContext.RequestContext.HttpContext.ApplicationInstance.Context)

Is there equivalent in API ?   I am trying to avoid using   System.Web.HttpContext.Current  for cleaner code.

Regards,
Amit Rangari

**Comment by rgregg** [comment]
With OAuth2, you can't authenticate someone server side. You always need to have the user authenticate using the OAuth 2 flow, and then your service should grab the access_token and/or refresh_token and use those on the server side.

I would recommend not using the Live SDK code and just using the OAuth 2 authorization code flow and then redeem the authorizationCode for access_token and refresh_token in your server code. The OAuth flow should be pretty straight forward, and then you can leverage [this code sample](https://github.com/rgregg/microsoft-account-winforms/blob/master/MicrosoftAccount.WindowsForms/MicrosoftAccountOAuth.cs) to actually redeem the authorization code for the right tokens server-side.
