### ISSUE TITLE
OneDrive for business always return http code 403

### ISSUE THREAD

**Issue by NerxhanMusliu** [OneDrive/onedrive-api-docs#221]
Hi there,

I'm writing a library in php to communicate with OneDrive Business API. 

I follow all the steps from here https://dev.onedrive.com/auth/aad_oauth.htm. 

And everything works fine until I try to make a request on last step:
<code>
GET {serviceEndPointUri}/drive </code>
<code>
Authorization: Bearer {access_token}
</code>

And after make a request with curl always get 403 Code. 

<code>[url] => https://eduongo765-my.sharepoint.com/_api/v2.0/me/drive </code>
<code>[content_type] =></code> 
<code>[http_code] => 403</code>

I follow exactly all the steps from documentation, 

Have anyone any idea what happened there.

Thanks

**Comment by rgregg** [comment]
HI @NerxhanMusliu. Are you getting any response back at all, or just the HTTP 403 and no body? If there are any headers also being included on the response, can you please include those so we can take a look at what's going on here?

**Comment by NerxhanMusliu** [comment]
Hi @rgregg 

Thanks for your fast response, I really appreciated.

When I make a request I use  {serviceEndPointUri}/drive 
And I make a request with curl (include accessToken). And I get this response: 

Array
(
    [url] => https://eduongo765-my.sharepoint.com/_api/v2.0/me/drive
    [content_type] => 
    [http_code] => 403
    [header_size] => 783
    [request_size] => 1477
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 2.434
    [namelookup_time] => 1.513
    [connect_time] => 1.576
    [pretransfer_time] => 1.981
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => 0
    [upload_content_length] => -1
    [starttransfer_time] => 2.434
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 134.170.206.59
    [certinfo] => Array
        (
        )
    [primary_port] => 443
    [local_ip] => 192.168.0.3
    [local_port] => 58747
)

**Comment by NerxhanMusliu** [comment]
Hi @rgregg.

Did you have time to see it.

I make a log of all steps like in documentation.

You can find here. 

http://pastebin.com/R12VBwVD

Thanks

**Comment by NerxhanMusliu** [comment]
Hi @rgregg. 

Did you have time to see it. 
I still get same error. According to https://github.com/OneDrive/onedrive-api-docs/issues/189 I thinks is API bug

Thanks

**Comment by rgregg** [comment]
Sorry for the delay on this @NerxhanMusliu. Those look like the curl responses, but not the actual response headers from the HTTP request. I think you can use the -i parameter for curl to make it output the response headers.

**Comment by NerxhanMusliu** [comment]
Hi @rgregg 

I've tested again, I'm still get the same error again, in the last steps when I try to connect to the '/drive'.
Any idea.

Thanks

**Comment by rgregg** [comment]
Hi @NerxhanMusliu:

I just re-read this thread, and noticed that the URL you're using includes "me" in the path. That isn't part of the OneDrive API and is probably the source for the 403 errors. 

To request the drive info, you'd want to use this path:

```GET https://eduongo765-my.sharepoint.com/_api/v2.0/drive```

If you continue to get an error after trying that, please send me the value of the **request-id** header on the http response. I can use that to look up the server logs and see what's going wrong.

**Comment by NerxhanMusliu** [comment]
Hi @rgregg 
Thanks for your quick response.

This url was serviceEndpointUri which came from Step 3 from Onedrive documentation https://dev.onedrive.com/auth/aad_oauth.htm

I've change to https://eduongo765-my.sharepoint.com/_api/v2.0/drive, but I still get the same error.

Hmhm request-id, we are talking about client-id='200def6e-46cf-4902-a0a5-02b455856223'. Is this right

Thanks

**Comment by rgregg** [comment]
Thanks for including the page you found that reference on, I'll get it updated. As for the request-id, that's different than client-id.

If you're using **curl**, you can have it write out the response headers by using `-i` as a parameter to curl. The response then is printed like this:

```
HTTP/1.1 403 Forbidden
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Tue, 05 Jan 2016 23:22:53 GMT
Last-Modified: Wed, 20 Jan 2016 23:22:53 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
SPRequestGuid: 5e38579d-30b2-0000-4a2e-876101eb5afc
request-id: 5e38579d-30b2-0000-4a2e-876101eb5afc
Strict-Transport-Security: max-age=31536000
MicrosoftSharePointTeamServices: 16.0.0.4907
Date: Wed, 20 Jan 2016 23:22:53 GMT

{"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Access denied. You do not have permission to perform this action or access this resource."}}
```

You'll see one of the response headers is named **request-id** and contains a unique value per request/response.

**Comment by NerxhanMusliu** [comment]
Hi @rgregg 

Sorry for late email (We are on UTC+1)
The request id is:

<code>
request-id: e757579d-e0fa-2000-4505-a7fabac9f6b7
</code>

Thanks

**Comment by NerxhanMusliu** [comment]
Hi @rgregg 

Did you check what's wrong with that request-id


Thanks

**Comment by rgregg** [comment]
Hi Nerxhan, can you send me an e-mail to rgregg at microsoft.com? I'd like to follow up via e-mail.

**Comment by NerxhanMusliu** [comment]
Yeap, sure @rgregg 

Thanks

**Comment by NerxhanMusliu** [comment]
Hi there,

We resolve this issue (combining javascript with php)

Thanks

**Comment by allthesignals** [comment]
what was the issue? I'm seeing this exact error code and headers, but only intermittently.

**Comment by rjaduthie** [comment]
How was this resolved?
