### ISSUE TITLE
LiveConnect replacement

### ISSUE THREAD

**Issue by Joel95** [OneDrive/onedrive-api-docs#223]
Hello all,

I'm writing a Joomla extension (SlideshowFx) aimed to display photo stored on OneDrive.
I implemented the OneDrive API and it works fine with photos/albums stored in document, photos and images folders (as well as my own app folder slideshowfx).

Now, when I upload photos from my mobile (using Android OneDrive application), photos are by default stored in OneDrive albums (it looks like another app folder). I can get access to these albums from onedrive.live.com web page but I didn't found how to get access from OneDrive API.

After some Google search, I found the LiveConnect API but this API is deprecated (https://msdn.microsoft.com/en-us/library/hh243641.aspx) and I didn't found OneDrive replacement.

So, how can I get access to albums stored in OneDrive?

Thanks for your help.

**Comment by daspek** [comment]
Hi @Joel95, there isn't yet a way to get at those albums from the OneDrive API, but we're working on it. So stay tuned. It's one of our top asks on [uservoice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer).

The LiveConnect API doesn't actually expose albums, either. What it calls an "album" is just a normal folder that contains photos.
