### ISSUE TITLE
Attempting to update an item in an AppFolder using "@name.conflictBehavior=replace" results in a 409 / nameAlreadyExists error.

### ISSUE THREAD

**Issue by emdelaney** [OneDrive/onedrive-api-docs#225]
I have an app folder that contains items which are frequently replaced with updated items of the same name. Recently, when attempting to update an existing file with @name.conflictBehavior=replace, OneDrive has started to return a 409 error instead of replacing the file as expected. 

**The "fail" and "rename" conflict behaviors work as expected:**
Case 1: `PUT https://api.onedrive.com/v1.0/drive/special/approot:/test.txt:/content?access_token={access-token-here}&%40name.conflictBehavior=fail`
When the file test.txt does not exist, doing two PUT requests with a conflict behavior of "fail" works as expected: the file is created successfully on the first request, returning a 201 status code; the second request fails, returning a 409 HTTP error code and a JSON error code of nameAlreadyExists.

Case 2: `PUT https://api.onedrive.com/v1.0/drive/special/approot:/test.txt:/content?access_token={access-token-here}&%40name.conflictBehavior=rename`
When the file test.txt does not exist, doing two PUT requests with a conflict behavior of "rename" works as expected: the file is created successfully on the first request, returning a 201 status code; the second request also succeeds, creating a new item, "test 1.txt".  

**The "replace" conflict behavior has the same behavior as the "fail" case:**
Case 3 (broken): `PUT https://api.onedrive.com/v1.0/drive/special/approot:/test.txt:/content?access_token={access-token-here}&%40name.conflictBehavior=replace`
When the file test.txt does not exist, **doing two PUT requests with a conflict behavior of "replace" has the same results as Case 1 / "fail":** the file is created successfully on the first request, returning a 201 status code; the second request fails, returning a 409 HTTP error code and a JSON error code of nameAlreadyExists. The second request should probably succeed, replacing the existing item, instead of failing with a nameAlreadyExists error.

**Steps to reproduce:** Execute the case 3 PUT request twice with a valid access token and request body.

**Comment by ificator** [comment]
I just tried to repro this and didn't have any luck.

**First request (test.txt doesn't exist):**
```
PUT https://api.onedrive.com/v1.0/drive/special/approot:/test.txt:/content?@name.conflictBehavior=replace
201 Created (application/json)
```

**Second request (test.txt was previously created):**
```
PUT https://api.onedrive.com/v1.0/drive/special/approot:/test.txt:/content?@name.conflictBehavior=replace
200 OK (application/json)
```

@emdelaney: Are you still able to reproduce this issue?

**Comment by emdelaney** [comment]
I'm seeing what you are seeing :) It looks like the team fixed the issue somewhere between October and now. Thanks for looking into this.

**Comment by ificator** [comment]
Thanks for confirming!
