### ISSUE TITLE
OneDrive for Business access denied 403

### ISSUE THREAD

**Issue by durimjusaj** [OneDrive/onedrive-api-docs#227]
OneDrive for Business returns only 403 when I try to pass access_token, i tried with both method(header get parameter) same problem. Is this a bug at your side.

PS. I'm using same app in AzureAD for SignIn, OneNote and OneDrive. Sign in and OneNote are working fine the only problem is with OneDrive for Business.

Anything on this ?

**Comment by ksheode** [comment]
Could you share the steps you followed to generate the access token?

**Comment by rgregg** [comment]
Closing this out since there hasn't been any activity responding to our questions. Please feel free to reopen on reply.
