### ISSUE TITLE
[OneDrive] list children return 404 rather than 401 after access_token expired

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#228]
Hi folks,

There are many ways to list data form server.
But it seems return different code after access token expired

**retuen 404**:

```
https://api.onedrive.com/v1.0/drive/items/CB0BF412D51BBD9F!25418/children

```

```
{
  "error": {
    "code": "itemNotFound",
    "message": "Item does not exist"
  }
}
```

**retuen 401**:

```
https://api.onedrive.com/v1.0/drive/root/children
```

```
{
  "error": {
    "code": "unauthenticated",
    "message": "Must be authenticated to use '/drive' syntax"
  }
}
```

what is going wrong ヽ(o’Д`o)ノヽ(o’Д`o)ノヽ(o’Д`o)ノヽ(o’Д`o)ノヽ(o’Д`o)ノ.....

**Comment by Mike-Bell** [comment]
FWIW, there could be security implications to returning a 401 instead of a 404 for a specific item. If I'm an attacker trying to brute force random items with a made-up token, you shouldn't tell me when I hit a valid one. Even if I'm not allowed to get it.

**Comment by ssimono** [comment]
Hi,

I am also facing issues with this wrong error code. The only way to handle expired tokens is for now to remove  *access_token* and get a new one each time my application gets a 404, which in most cases does not come from any auth issues.

I am pretty sure a lot of consuming apps implementations could easily lead to infinite loops if not handled with care.

Mike has a point about security, but if the service returned a 401 for any invalid or missing token, regardless of asked resource, then the attacker couldn't know if the item exists. This is the way a lot of APIs work.

Thank you

**Comment by Mike-Bell** [comment]
Good point. And FWIW, my implementation would also suffer from this issue, I just haven't had it pop up yet.

**Comment by peternied** [comment]
When you retrieve your access token there is an [expires_in field](https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/msa_oauth.md#response-2), that should be how you determine that your token is viable or needs to be refreshed.

I would not recommend detecting 401 and making the assumption that your application does not have a valid access token anymore as there are many scenarios when interacting with a OneDrive you do not own that would send 401 Unauthorized and a new access token would not resolve them (The current accounts permissions were revoked by the owner)

**Comment by ssimono** [comment]
Thank you,

Do you think the *expires_in* field is reliable? In other terms, is there any reason that would cause an access_token to become invalid sooner?

That would be a shame for my app to NOT ask for a new token because it thinks that current one is valid although it is not. But if this cannot happen, then I will definitely rely on *expires_in* rather than blindly refreshing the token at each 404.

**Comment by peternied** [comment]
I own and maintain the [MSA OAuth client for Android](https://github.com/MSOpenTech/msa-auth-for-androi), and the [OneDrive SDK for Android](https://github.com/OneDrive/onedrive-sdk-android).  I have a lot of faith in the value in the *expires_in* field, as it prevents unneeded round tripping when an authentication token has expired.

**Comment by jrd261** [comment]
Shouldn't an expired or invalid access token always get a 401? 

Why would you even check for the existence of a resource before checking the validity of the supplied token?

**Comment by D4N14L** [comment]
Hi everyone,

I know it's been a bit, but this has been fixed. It should 401 in the case of an invalid token now.

Thanks!
