### ISSUE TITLE
status code differed with the API doc if Insufficient Storage 

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#23]
I try to test the quota full exception and got the response:
< Response [500] > {u'error': {u'message': u'Insufficient Space Available', u'code': u'generalException'}}

But according to http://onedrive.github.io/misc/errors.htm,
the insufficient storage should return status_code with 507.

If this is a bug, would this status code changed to 507 in the future?
Thanks.

**Comment by rgregg** [comment]
Yes, the proper error code should be 507 and we'll make sure that's what we return in all cases, so you should expect that value.
