### ISSUE TITLE
Multipart upload to OneDrive using POST fails when @name.conflictBehavior is set to 'replace'

### ISSUE THREAD

**Issue by kotsak** [OneDrive/onedrive-api-docs#230]
Hi,

I've encountered a problem when trying to replace an existing file by using the *Multipart* upload to OneDrive using the POST method.

I am using the Instance Attribute `@name.conflictBehavior = replace` but my call fails with a HTTP 400 error and with this error:
`{
	"error": {
		"code": "invalidRequest",
		"message": "Cannot overwrite an item with the current operation"
	}
}`

It works as expected when using `fail` or `rename` for `@name.conflictBehavior`. Is `replace` currently supported? (the error message indicates it may not be)

Thanks
Kotsak

**Comment by ificator** [comment]
Thanks for reporting this @kotsak - it definitely looks like we're a little inconsistent in how we're applying some policy. We're actually in the process of going over all of these kinds of scenarios and making sure we're doing the logical thing, so we'll keep you posted on how that goes.

**Comment by kotsak** [comment]
Hi,

Any update on this? Seems the issue has not been resolved yet.

Thanks.

**Comment by kotsak** [comment]
Hi,

Noticed that it's been some time already so I just did a quick test but found that the problem persists. Any news on this?

Thanks.

**Comment by ificator** [comment]
Hey @kotsak, I managed to find some time over the holiday period to get this one fixed and so it should be resolved sometime within the next month. I'll ping this issue when it's live.

**Comment by ificator** [comment]
The fix has finally been deployed so this should now be resolved. Please let us know if you continue to see the behavior.
