### ISSUE TITLE
Apigee 'File Upload' sample returns 400 Bad Request

### ISSUE THREAD

**Issue by iambmelt** [OneDrive/onedrive-api-docs#232]
Using the recommended format if you want to put a new file in a folder you put `root:/path/to/folder` in the parent-path field, and `myFilename.txt` in the filename field.  This creates this url: `https://api.onedrive.com/v1.0/drive/root:/path/to/folder:/myFilename.txt:/content`.  Using that URL gives the error “Paths can only contain at most two colons.” Instead you actually have to use: `https://api.onedrive.com/v1.0/drive/root:/path/to/folder/myFilename.txt:/content`.

Sandbox location:
https://apigee.com/OneDrive/embed/console/OneDrive

Using request template:
`Upload File API`

![screen shot 2015-10-20 at 9 28 00 am](https://cloud.githubusercontent.com/assets/990063/10614021/e0cad55a-770c-11e5-80a0-538705a3a07b.png)

```
PUT /v1.0/drive/root:/testfolder:/myFilename.txt:/content HTTP/1.1
Authorization: Bearer <token>
Host: api.onedrive.com
Content-Length: 23
X-Target-URI: https://api.onedrive.com
Content-Type: application/octet-stream
Connection: Keep-Alive
```

Returns

```
HTTP/1.1 400 Bad Request
X-QosStats:
{"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-MSNSERVER: DM2305____PAP187
Date: Tue, 20 Oct 2015 16:17:49 GMT
X-ThrowSite: 0f1c.0271
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Content-Length: 89
X-AsmVersion: UNKNOWN; 19.30.0.0
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0

{
  "error":  {
    "code": "invalidRequest",
    "message": "Paths can only contain at most two colons"
  }
}
```

**Comment by xor-zz** [comment]
Second.

**Comment by jscaria** [comment]
Thanks for posting this issue.    I resolved it by making the text clearer.

**Comment by iambmelt** [comment]
Thanks @jscaria ! :+1:
