### ISSUE TITLE
Apigee 'Upload from URL' sample returns 400 Bad Request

### ISSUE THREAD

**Issue by iambmelt** [OneDrive/onedrive-api-docs#233]
This request, interestingly exhibits the opposite problem from #232 

Sandbox location:
https://apigee.com/OneDrive/embed/console/OneDrive

Using request template:
`Upload from URL`

Using the template, specify the parent-path (which has an undefined format), so if you take the recommended format from the uploadd file API you would put in `root:/path/to/folder` which creates the url: `https://api.onedrive.com/v1.0/drive/root:/path/to/folder/children`.  This gives `API not found`.  In fact, you need to put `root:/path/to/folder:` in the `parent-path`, creating: `https://api.onedrive.com/v1.0/drive/root:/path/to/folder:/children`.

![screen shot 2015-10-20 at 9 40 11 am](https://cloud.githubusercontent.com/assets/990063/10614349/99b80c30-770e-11e5-90c0-e0b04481ea8e.png)

```
POST /v1.0/drive/root:/testfolder/children HTTP/1.1
Prefer: respond-async
Authorization: Bearer <token>
Host: api.onedrive.com
Content-Length: 192
X-Target-URI: https://api.onedrive.com
Content-Type: application/json
Connection: Keep-Alive

{
  "@content.sourceUrl": "http://wscont2.apps.microsoft.com/winstore/1x/e33e38d9-d138-42a1-b252-27da1924ca87/Screenshot.225037.100000.jpg",
  "name": "halo-screenshot.jpg",
  "file":  {}
}
```

Yields:

```
HTTP/1.1 400 Bad Request
X-MSNSERVER: BN1305____PAP281
Content-Length: 61
Connection: keep-alive
X-AsmVersion: UNKNOWN; 19.29.0.0
Server: Microsoft-IIS/8.5 Microsoft-HTTPAPI/2.0
X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Tue, 20 Oct 2015 16:39:58 GMT
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-ThrowSite: 0274.43d9
Via: 1.1 BL3301____PAP165 (wls-colorado)
X-MSEdge-Ref: Ref A: CD773687E73346358D92A1DE339F4DF6 Ref B: 98643703DBE9B92B32A5E974F3DB7F96 Ref C: Tue Oct 20 09:39:58 2015 PST
Content-Type: application/json
X-WLSPROXY: BL3301____PAP165

{
  "error":  {
    "code": "invalidRequest",
    "message": "API not found"
  }
}
```

**Comment by xor-zz** [comment]
Second.

**Comment by jscaria** [comment]
I've updated the console documentation to make this clearer.   The correct parameter name is the parent  item, which could be `root`, `root:/path/to/my/folder:`, etc.
