### ISSUE TITLE
Documentation recommends obsolete version of IETF OAuth Spec

### ISSUE THREAD

**Issue by xor-zz** [OneDrive/onedrive-api-docs#234]
https://tools.ietf.org/html/rfc6749 is the final RFC version of the OAuth 2.0 specification.  The version linked at https://account.live.com/developers/applications/apisettings/ under the "Learn More" link is: http://go.microsoft.com/fwlink/?LinkId=225674 which resolves to: http://tools.ietf.org/html/draft-ietf-oauth-v2-20#section-2.1 which is 12 versions out of date, and is a draft which expired in 2012.

**Comment by rgregg** [comment]
Thanks for the feedback on the link. I'll make sure the link is updated to point to the proper place.
