### ISSUE TITLE
What is OAuth authentication_token used for?

### ISSUE THREAD

**Issue by jsinh** [OneDrive/onedrive-api-docs#24]
At [OneDrive authentication and sign-in](http://onedrive.github.io/auth/msa_oauth.htm) page, in Code flow section.

"Step 2. Redeem the code for access tokens" returns response that contains "authentication_token" along with other data like access and refresh token.

I might be asking silly question here but as I am not aware yet, I would like to know - what is "authentication_token" used for?

Context: access_token is used for authenticated calls to API and refresh_token used for fetching new access_token when the current one expires. authentication_token is used for .... ?

Thanks

**Comment by rgregg** [comment]
It's a legacy token that the Microsoft Account OAuth flow returns that isn't that useful for the way apps use OAuth. I'd recommend just ignoring it.

**Comment by jsinh** [comment]
@rgregg thanks for the information.

Does that probably mean that "authentication_token" has nothing to do with anything that is offered as part of OneDrive API Version 2.0 with OAuth 2.0 (on web, application etc.)?

If that is not the case, I would request you to provide me at least one use case where "authentication_token" is part of or used somehow.

**Comment by rgregg** [comment]
Yes, that's correct. `authentication_token` has nothing to do with anything we offer in the OneDrive API.

**Comment by jsinh** [comment]
Thanks again, that resolves my query.

**Comment by jsinh** [comment]
Is it fine if I can send a PR that adds a note regarding this clearification on "msa_oauth" page. It would be helpful for anyone who keeps wondering like me

**Comment by rgregg** [comment]
Sure.
