### ISSUE TITLE
Upload session expiry

### ISSUE THREAD

**Issue by TayNelson** [OneDrive/onedrive-api-docs#240]
There doesn't seem to be a method for extending the expiry date of an upload session. As a result, the user is given a deadline by which they must complete the uploading of their file.

A user who is uploading a large file might be in one or more of the following circumstances:
* Slow upload speed
* Internet service provider usage limits for particular timeframes
* Intermittent computer usage (and therefore intermittent uploading)

A method for extending the expiry date of upload sessions still wouldn't completely solve the problem. Ideally there would be no expiry date on upload sessions, and their uncommitted contents should count against the user's storage quota.

A contrived example of such a user is one who only has home computer access on Saturday evenings. This user could be unable to complete the upload of their file before the expiry date of the upload session. Furthermore, this user might be unable to issue a expiry date extension request in a timely fashion.

Should there be no expiry date, this user would be able to continue the upload from where they left off, whenever they please, without fear of having their uploaded data destroyed.

This issue could also be mitigated if #241 is implemented &ndash; the above example user could commit their upload session at the end of Saturday and create a new upload session on subsequent Saturdays until all file parts are uploaded, at which point they could be joined to form a single file.

**Comment by daspek** [comment]
Hi Tay, interesting scenario. We wanted to avoid having in-progress uploads count against user quota because we thought it'd be confusing to message to the user... hence the somewhat rigid expiry semantics. I like your suggestions of using real files + append to solve this problem. We'll take this into consideration.
