### ISSUE TITLE
Joining files

### ISSUE THREAD

**Issue by TayNelson** [OneDrive/onedrive-api-docs#241]
This is a feature request. It would be nice to be able to upload multiple files to OneDrive and then, once they're uploaded, join them together into one file.

On Windows, this can be achieved through the following command:

```
copy /b 1.txt + 2.txt + 3.txt all.txt
```

It would be great for this functionality to be available on OneDrive too. An alternative to using one request to join multiple files, there could be an endpoint which will append one file's contents to another.

Amongst other uses, this could be useful for working around issues with uploading large files, as described in #240.

**Comment by daspek** [comment]
Good idea Tay! We'll take this into consideration.
If you don't mind, please consider adding this to our list on [UserVoice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) so that others can vote to help prioritize this.

**Comment by TayNelson** [comment]
Thank you for your replies. I have posted my [idea](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/10495221-file-appending-concatenation) to your UserVoice list.

Should this and my other two related GitHub issues be closed?
