### ISSUE TITLE
Invalid Timestamp Format

### ISSUE THREAD

**Issue by cguZZman** [OneDrive/onedrive-api-docs#243]
Accordingly with the documentation, we should be getting ISO 8601 dates, and we are (kind of), but the problem is in the milliseconds part. 
My understanding is we should be getting 3 digits for milliseconds, but I'm getting 7 digits instead.
This is happening after upload a fragment in 
```
PUT https://api.onedrive.com/up/eyJSZXNXXX
```
response part:
```
"expirationDateTime": "2015-11-01T17:24:54.8958422+00:00"
```
It doesn't make sense right? There are only 1000 milliseconds in one second. So what a millisecond of 8958422 means :)
This is internally throwing me a format exception.
Let me know.
Thanks

**Comment by daspek** [comment]
Hi Carlos, the ISO 8601 standard doesn't have a limit on the precision of the date. OneDrive stores dates with precision greater than milliseconds, so you wind up with more decimal places than 3. It sounds like your deserializer assumes that the decimal part only goes to three places. Is this a piece of code you have control over?

**Comment by cguZZman** [comment]
Hi Daron,
You right. In fact, the published standard never talks about milliseconds, it's a fraction of the second.
I'll handle it in my side.
Thank you
