### ISSUE TITLE
Can't create a share link with OneDrive for business API action.createLink but can retrieve existing link

### ISSUE THREAD

**Issue by mflalor** [OneDrive/onedrive-api-docs#244]
Hi,
I'm getting an Internal Server Error 500 with error message "host web isn’t a personal site" when trying to create a share link with the OneDrive for Business root url - https://{tenant}-my.sharepoint.com/_api/v2.0 

I can upload / create files via the above API but I cannot create a shared link. If I create the link using the Office365 OneDrive portal I can then retrieve the link with action.createLink.

Can you confirm this is a bug? Or am I missing something?

Edit: It should be noted that I am using the Office 365 Developer Pack subsciption but the file that I can upload and update but not create a link for is definitely in OneDrive and not the team site.

Cheers, Mark

**Comment by ksheode** [comment]
Hi Mark,

This is a bug and we have checked-in a fix for this. It is currently getting applied to Production and should be available worldwide in the next 2 weeks.

-Ketaki

**Comment by mflalor** [comment]
Thanks Ketaki,

I look forward to the fix.

Cheers, Mark

On 31 October 2015 at 07:06, Ketaki Sheode <notifications@github.com> wrote:

> Hi Mark,
>
> This is a bug and we have checked-in a fix for this. It is currently
> getting applied to Production and should be available worldwide in the next
> 2 weeks.
>
> -Ketaki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OneDrive/onedrive-api-docs/issues/244#issuecomment-152638865>
> .
>



-- 
Mark Lalor
(w) procq.com.au <http://www.procq.com.au>
(e) markl@procq.com.au
(t) +61 2 8719 0163

**Comment by bmschwa** [comment]
Did anyone confirm the fix resolved the issue?   I'm seeing something similar now

**Comment by ificator** [comment]
If you're seeing an issue now it's most likely something new. To avoid conflating with this old one I'm going to close this out, but please create a new issue with details on what you're seeing so we can drill in.
