### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Smeaven** [OneDrive/onedrive-api-docs#247]
I can't really understand the advantages of doing the pagination with `nextLink`and `skiptoken` instead of using the `limit` and `offset` parameters?

With the current pagination method I can't retrieve a specific subset of items, so my flexiblity is limited.

**Comment by peternied** [comment]
We wanted to keep the pagination model consistent with the different kind of pagable results that OneDrive can offer.  While some collections would be easily served with a limit and offset value, our delta collection and search collections need additional details about the context of the request to provide consistent results.

When you mention 'specific subset of items', what scenario did you have in mind that isn't working?
