### ISSUE TITLE
OneDrive Javascript Development write access wl.contacts_skydrive

### ISSUE THREAD

**Issue by michaelhoes** [OneDrive/onedrive-api-docs#248]
(Maybe this isn't the right forum)

I am building a web application with wl.js (js.live.net/v5.0/wl.js)

I have a user that has shared a folder with other users. But those users can not create new folders in that shared folder. Only the owner can create new folders

Isn't there a wl.contacts_skydrive_write scope or something?

I always get this error:

error: Object
code: "request_token_unauthorized"
message: "The access token doesn't have the correct permission for the resource."

**Comment by rgregg** [comment]
Hi Michael: I'd encourage you to not use the wl.js file. It's outdated and uses the older APIs which don't support writing to shared data.

The new APIs provide more functionality and broader access, and can easily be called directly from JavaScript. The [OneDrive Explorer sample](https://github.com/onedrive/onedrive-explorer-js) is a good example of how to call the API from JavaScript directly, without using an SDK.
