### ISSUE TITLE
Starting fresh enumeration using nextLink when view.delta gives a 410 Gone response, gives an Error

### ISSUE THREAD

**Issue by robses** [OneDrive/onedrive-api-docs#249]
Hello,

when using the view.delta action and getting an 410 Gone response back. The documentation states a fresh delta enumeration can be started by using the nextLink URL provided in the Location of the response. 

An example of a Location header i get back is:

    Location: https://api.onedrive.com/v1.0/drives('me')/items('root%252FAPITest')/view.delta?token=aTE09MDtJRD0zRDIzMEI1NkE5RTM2ODZBITU5MzE7TFI9NjM1ODMwODcwNjE1MzM7RVA9NTtSTj1UcnVl

When using this nextLink URL in a GET request, I get back the following error response:

    GET https://api.onedrive.com/v1.0/drives('me')/items('root%252FAPITest')/view.delta token=aTE09MDtJRD0zRDIzMEI1NkE5RTM2ODZBITU5MzE7TFI9NjM1ODMwODcwNjE1MzM7RVA9NTtSTj1UcnVl

    5 * Client response received on thread main
    5 < 500
    5 < Content-Length: 100
    5 < Content-Type: application/json
    5 < Date: Sat, 14 Nov 2015 08:37:41 GMT
    5 < P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
    5 < Server: Microsoft-HTTPAPI/2.0
    5 < Strict-Transport-Security: max-age=31536000; includeSubDomains
    5 < X-AsmVersion: UNKNOWN; 19.32.0.0
    5 < X-MSNSERVER: BY3301____PAP144
    5 < X-QosStats: {"ApiId":0,"ResultType":4,"SourcePropertyId":0,"TargetPropertyId":42}
    5 < X-ThrowSite: 6426.c69a
    {"error":{"code":"generalException","message":"An assertion failed while processing this request."}}

My question is this the correct way of starting a fresh delta enumeration of should I extract the deltaToken out of the nextLink URL and use that in a new view.delta request?

Regards Rob

**Comment by ificator** [comment]
You seem to be hitting an unexpected error, thanks for letting us know! I'll dig in on Monday and see if we can get it resolved ASAP.

**Comment by ificator** [comment]
Hi @robses, this issue should now be resolved. Can you let us know if you see further instances of the Location header returning a non-functional delta link?

**Comment by robses** [comment]
Hello @ificator,

i have tested it, and the resync using the Location header is now working. Thanks for fixing the issue.

Regards Rob

**Comment by ificator** [comment]
Thanks for confirming!
