### ISSUE TITLE
When providing top parameter to view.search last page of results is always empty

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-api-docs#250]
When using the view.search action in combination with the 'top' query parameter, the last page of the result set is an empty collection. In my opinion, when there are no more results the nextLink parameter should not set, and should no be pointing to an empty collection.

This triggers a exception In my Java OneDrive SDK. There i created an Iterable that iterates over the results and loads the next page automatically When this follows the nextLink but then encounters an empty page I cannot give back an empty element, because this break the Iterator interface contract. 

See the understanding trace for more information

Search action with where top=1

```
GET https://api.onedrive.com/v1.0/drive/root:/:/view.search?q=e&top=1
```

NextLink in view.search response 

```
@odata.nextLink":"https://api.onedrive.com/v1.0/drives('me')/items('root%252F')/view.search?q=e&$top=1&$skiptoken=Mg"}
```

GET request of the last page giving back the empty collection

```
5 > GET https://api.onedrive.com/v1.0/drives('me')/items('root%252F')/view.search?q=e&$top=1&$skiptoken=Mg
5 * Client response received on thread main
5 < 200
5 < Content-Length: 41
5 < Content-Type: application/json; odata.metadata=none
5 < Date: Sun, 15 Nov 2015 10:05:36 GMT
5 < OData-Version: 4.0
5 < P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
5 < Server: Microsoft-IIS/8.5 Microsoft-HTTPAPI/2.0
5 < Strict-Transport-Security: max-age=31536000; includeSubDomains
5 < Via: 1.1 BN1301____PAP142 (wls-colorado)
5 < X-AsmVersion: UNKNOWN; 19.32.0.0
5 < X-MSEdge-Ref: Ref A: 5E5711BBBF294C1C8A843D3BB6D430CC Ref B: 03EBE8801E37AD3169BB334719E23FF9 Ref C: Sun Nov 15 02:05:37 2015 PST
5 < X-MSNSERVER: BY3301____PAP126
5 < X-WLSPROXY: BN1301____PAP142
{"@search.approximateCount":0,"value":[]}
```

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
