### ISSUE TITLE
ODB can fail with a 400 when a long (but valid) path is provided

### ISSUE THREAD

**Issue by ificator** [OneDrive/onedrive-api-docs#254]
Forked from https://github.com/OneDrive/onedrive-api-docs/issues/150.

We need to make sure that the API supports all paths that can be created in Sharepoint.

**Comment by vladvarna** [comment]
Simple file upload works with long paths, but resumable upload fails with 400 with the same path

**Comment by ificator** [comment]
I believe this should be resolved now.
