### ISSUE TITLE
Invalid format of response body, it should be in json not html code

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#255]
I am testing unicode support of OneDrive API.

But I got an invalid response body in html rather than json

The request url is:

```
GET /v1.0/drive/root:/multi-byte/%EF%B7%8A%EF%B7%8B%EF%B7%8C%EF%B7%8D%EF%B7%8E%EF%B7%8F%EF%B7%90%EF%B7%91%EF%B7%92%EF%B7%93%EF%B7%94%EF%B7%95%EF%B7%96%EF%B7%97%EF%B7%98%EF%B7%99%EF%B7%9A%EF%B7%9B%EF%B7%9C%EF%B7%9D%EF%B7%9E%EF%B7%9F%EF%B7%A0%EF%B7%A1%EF%B7%A2%EF%B7%A3%EF%B7%A4%EF%B7%A5%EF%B7%A6%EF%B7%A7%EF%B7%A8%EF%B7%A9%EF%B7%AA%EF%B7%AB%EF%B7%AC%EF%B7%AD%EF%B7%AE%EF%B7%AF%EF%B7%B0%EF%B7%B1%EF%B7%B2%EF%B7%B3%EF%B7%B4%EF%B7%B5%EF%B7%B6%EF%B7%B7%EF%B7%B8%EF%B7%B9%EF%B7%BA%EF%B7%BB?select=id%2Cname%2Csize%2ClastModifiedDateTime%2CeTag%2CcTag%2Cfile%2Cfolder%2Cdeleted%2CparentReference HTTP/1.1" 400 324
```

Response content is:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
```

Here are two questions:
1) Response seems in wrong format
2) What is the unicode support ? Is there any limitation or invalid range about API?
Thanks!

**Comment by rgregg** [comment]
Hi @mikechiu1012 Can you confirm that you're receiving this error when connecting to OneDrive for Business or OneDrive consumer?

**Comment by ificator** [comment]
It's most likely both - the problem is actually in HTTP.sys, which both services use, where it is rejecting the request in the kernel before it even gets to our API code. There isn't a great deal we can do about it unfortunately.

**Comment by mikechiu1012** [comment]
Hi @rgregg , I connect to OneDrive consumer.

Thanks!

**Comment by ificator** [comment]
This is unfortunately an issue with HTTP.sys rejecting a request due to it not liking some of the characters provided in the path (even though there's actually nothing wrong with it). The best we can do on our side is to provide a way to specify the path as a query string parameter, which HTTP.sys will not examine so closely.

**Comment by ificator** [comment]
Recent changes have reduced the Unicode characters that cause this, and most scenarios should allow the use of Odata aliases as a work around if need be.
