### ISSUE TITLE
Why Copy Api is So slow???

### ISSUE THREAD

**Issue by lolhyuck** [OneDrive/onedrive-api-docs#256]
I have tested some one drive api method. 
And I found that one drive copy api is very slow... 

I tried 20 times copy api, and the the fatest time is 8 second, and the slowest is 2 min and 2 second.

everage secont is 40 sec....

File size is only 13.62 KB docx type file...

Is there some way to make speed up copy speed? or Do you have any plan to make speed up copy speed???

**Comment by rgregg** [comment]
Hi @lolhyuck 

This is one of the reasons the copy API is still "in preview". We're working on improving how the copy API works and will continue to iterate on that before taking the API out of preview.
