### ISSUE TITLE
get 404 itemNotFound rather than 401 invalid token

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#259]
I am porting id-based API with OneDrive Consumer.

Here is one weird situation I suffered:
When I list some dir item, it will return 404 item not found rather than 401.
But if I list root folder, it will return 401 if token is invalid. 

```
"GET /v1.0/drive/items/54DFDA9D9CE4FDED!408202/children?top=1000&select=id,name,size,lastModifiedDateTime,eTag,cTag,file,folder,deleted,parentReference HTTP/1.1" 404 65
ERROR:common:404 {"error":{"code":"itemNotFound","message":"Item does not exist"}}
```

I am not pretty sure if this is an bug or not.
Please help to clarify it, thanks!

**Comment by ificator** [comment]
Hi @mikechiu1012, can you help me understand your scenario a little more? Specifically, here's my understanding:
1. You get an invalid token (maybe expired?)
2. You make a request to /54DFDA9D9CE4FDED!408202/children and get a 404
3. You make a request to /root and get a 401

For #2 can you confirm the state of 54DFDA9D9CE4FDED!408202? Is it a valid folder? Does it contain any children?

**Comment by mikechiu1012** [comment]
hi @ificator 

For #2 can you confirm the state of 54DFDA9D9CE4FDED!408202? Is it a valid folder? Does it contain any children?
Yes, I am sure the folder is valid and has children.

And I think this is the same issue with https://github.com/OneDrive/onedrive-api-docs/issues/228
is there any update on #228?

**Comment by D4N14L** [comment]
Hi @mikechiu1012,

I know it's been a bit, but this has been fixed. It should 401 in the case of an invalid token now.

Thanks!
