### ISSUE TITLE
optinal request headers such as "if-none-match: etag"

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#26]
as mention on the github page items/get.md, items/list.md and others...
"if-none-match : If this request header is included and the etag provided matches the current etag on the file, an HTTP 304 Not Modified response is returned."

so providing the same eTag value that at the server, still in response getting items object with response code 200, never get 304 code in response, as specified above

![1](https://cloud.githubusercontent.com/assets/11455759/6635310/95eef8ac-c98a-11e4-95c1-38a8b1c5bf37.png)
![2](https://cloud.githubusercontent.com/assets/11455759/6635311/95f11da8-c98a-11e4-8d05-107f859fc38b.png)

**Comment by aclev** [comment]
Hi There!
Thanks for the input.  We are working on a fix now.

**Comment by igokoro** [comment]
Faced this issue as well. @aclev do you have a timeline for a fix? Should we expect it anytime soon or is it somewhere at the bottom of your todo list?

**Comment by rgregg** [comment]
This should be available very soon (like next week).

**Comment by ificator** [comment]
This should now be resolved.
