### ISSUE TITLE
AutoRefreshTokens not working if use token flow

### ISSUE THREAD

**Issue by VanKrock** [OneDrive/onedrive-api-docs#260]
How refresh tokens in client desktop applications? 
I do not want to give my app secret to clients

**Comment by rgregg** [comment]
For Microsoft accounts (OneDrive Personal) if you configure the app as a native client application, you do not need to provide the client_secret value when using the token end point.

**Comment by VanKrock** [comment]
It's true, but, access token expires in 3600 seconds, how refresh access token without refresh token? Because token flow don't returning refresh token.

**Comment by rgregg** [comment]
In those cases, you need to go back through the OAuth 2 authorization flow. However, since the user has already authorized the application and is still signed in (with a cookie from the login server) you will receive a new access_token without the user going through any additional input.

**Comment by VanKrock** [comment]
And I shold show my authorization form every hour?

**Comment by rgregg** [comment]
The recommended approach here would be to use a hidden IFRAME element to load the authorization page again and silently reauthenticate and receive a new access_token. In this scenario, you would use the _&prompt=none_ query string parameter to ensure that the OAuth provider doesn't challenge for authentication or display the authorization page. You'll either get back a new access token or an error.

This is a pretty standard recommended approach for using OAuth 2 implicit flow with single page apps.

**Comment by VanKrock** [comment]
For my solution i write custom authorizer [snippet for WinForms on gostash.ru](http://gostash.it/ru/users/3292) this use cookies like your advice at 30 Nov 2015, and doesn't show form if redirect on target page at once after authorization page.
