### ISSUE TITLE
Shared folders

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#261]
I am trying to view the changes of a folder that has been shared with me. I have added it to my OneDrive so it shows up as a normal folder in the website and my PC.
Looking at the metadata, the shared folder has an undocumented facet called `remoteItem`. It seems that I can use its content to make the item work like a normal folder (view.delta works fine with the id provided in the facet).
Can I rely on it ? Is this facet going to be documented ?

**Comment by ificator** [comment]
It looks like the documentation has caught up to the code! Have a read over https://github.com/OneDrive/onedrive-api-docs/blob/master/facets/remoteitem_facet.md and hopefully it'll confirm whatever you derived from the responses. To answer your first question, yes you can rely on it.

**Comment by skilion** [comment]
Thank you
