### ISSUE TITLE
Bug in OneDrive 6.3 iOS app

### ISSUE THREAD

**Issue by marcinwalus** [OneDrive/onedrive-api-docs#262]
Hi,
where can I file a bug to OneDrive 6.3 iOS app (actually extension to the app)? 

I'm trying to import programmatically document from OneDrive app to my app using UIDocument Picker (iOS extension). And after selecting a document in Document Picker I'm getting an error message on screen "Sorry, there was a problem. There might be a problem with the file.". In logs I can see warning and critical error:
`OneDrive[407] <Warning>: open on /private/var/mobile/Containers/Shared/AppGroup/xxx/File Provider Storage/xxx/xxx.zip: File exists`
`OneDrive[407] <Critical>: 2015-11-30 15:12:26:062 | MODPickerFileManager | E | There was an error copying file from cache to desired location. Error domain = NSCocoaErrorDomain, Error code = 516.`

I'm referring to https://dev.onedrive.com/sdks.htm (Picker and saver SDKs->iOS->UIDocumentPicker)

BR
![img_0522_png_and_devices_and_pictures_and_settingsviewcontroller_swift](https://cloud.githubusercontent.com/assets/1926917/11474980/4b539a04-977b-11e5-9fea-73dd5c1d8863.png)

**Comment by rgregg** [comment]
I'll pass this along to the team that owns the iOS app and we'll figure out what's going on. What OS is the device using, and is this an iPhone or iPad?

**Comment by marcinwalus** [comment]
Hello. Example above is from iOS9.1 on iPhone 5S using 4G connection. I will try to test tomorrow on other devices.
I have an impression, that it was working correctly few days ago and error showed up today.

BR

**Comment by marcinwalus** [comment]
Hi.
I have the same story on my other device. I have to remove OneDrive app and install it again to be able to download the file.

I will add few more explanations to the process:
Everything works when I select file for the first time. After picking the file I'm copying the file to my apps Documents directory and then I'm removing this file at given url.

```
internal func documentPicker(
   controller: UIDocumentPickerViewController, 
   didPickDocumentAtURL url: NSURL)
{
  if (controller.documentPickerMode == .Import)
  {
    // move file to documents directory
    ApplicationHelpers.moveDatabaseToDocumentsDirectory(url)
  }      
}
```

When I try to pick same file again I'm getting error as described above.

**Comment by marcinwalus** [comment]
Hello.
It seems that in OneDrive app version 6.4 updates 07 Dec 2015 this problem had been fixed.
It is now possible to import same file several times without any issue.
Thank you.

**Comment by rgregg** [comment]
Thanks for confirming that @marcinwalus!
