### ISSUE TITLE
view.delta not working in one drive

### ISSUE THREAD

**Issue by phanindraramesh** [OneDrive/onedrive-api-docs#265]
When I request to https://graph.microsoft.com/v1.0/me/drive/root/view.delta, it returns 
{
    "error": {
        "code": "BadRequest",
        "message": "Unsupported segment type.",
        "innerError": {
            "request-id": "27ce54be-755d-4307-981c-af0eb79db3fc",
            "date": "2015-12-04T11:00:07"
        }
    }
}.

I am using One drive for business and https://graph.microsoft.com/v1.0/me/drive/root/children is giving expected results but view.delta is the only thing that seems to be not working. 

Can anyone please help?

**Comment by rgregg** [comment]
These aren't aren't yet supported through Graph API. If you want to use view.delta or several other actions/functions defined in the OneDrive API, right now you need to call those using the OneDrive API directly. We're continuing to work to make these available in Graph for a future update.

**Comment by phanindraramesh** [comment]
I followed the process explained in https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/aad_oauth.md for getting endpoint for one drive for business.
So, when I make a get request to https://{tenant-name}-my.sharepoint.com/_api/v1.0/me/drive/root/view.delta 

(or https://{tenant-name}-my.sharepoint.com/_api/v2.0/me/drive/root/view.delta )

I am getting the following error 
{"error":"invalid_client","error_description":"Invalid audience Uri 'https:\/\/api.office.com\/discovery\/'."}

Can you please help me with that?

**Comment by phanindraramesh** [comment]
I just found my mistake that I need to again request an access token with the serviceResouceId as resource.
Thank you for your response. view.delta is working as described.

**Comment by phanindraramesh** [comment]
I am trying to fetch both user profile information and files in user's one drive account. In that case do I need to use two access tokens (one for user profile details from graph api using https://graph.microsoft.com/ as a resource and another for one drive api using resource id as provided in descovery services api)  to fetch the information that I need?

As resource parameter is different for both the apis, the same access token doesn't seem to be working.
Can you please comment if there is any way that I can use the same access token for both the operations that I need?

**Comment by peternied** [comment]
@phanindraramesh Have you looked into our [SDKs](https://dev.onedrive.com/sdks.htm), they all support authentication scenarios with ODB accounts?

**Comment by rgregg** [comment]
@phanindraramesh: You're correct that you need one access token per service resource you want to target. If you're making calls to graph.microsoft.com and {tenant}-my.sharepoint.com, you need two access tokens. If you need to call the discovery API to find the SharePoint URL, then you'd need a third access token to be able to call the discovery service as well.

All of those access tokens can be retrieved using the same refresh token though, so it can all happen behind the scenes without the user going through the authorization page again.

**Comment by phanindraramesh** [comment]
Thanks @rgregg . I am able to implement my solution using same refresh token and maintaining multiple access tokens at the same time.

**Comment by mauze-muawwaz-elastica** [comment]
@phanindraramesh @rgregg If the app is using ClientCredentialsFlow (App only tokens) then drive/root/view.delta doesn't work.
