### ISSUE TITLE
client.GetFolderAsync() return null for some account

### ISSUE THREAD

**Issue by VanKrock** [OneDrive/onedrive-api-docs#266]
for some accounts GetFolderAsync() return root folder.

**Comment by VanKrock** [comment]
Sorry my fail, need extended scopes, for some accounds need scopes "wl.photos", "wl.skydrive"

**Comment by peternied** [comment]
@VanKrock Make sure you use the [scopes](https://dev.onedrive.com/auth/msa_oauth.htm#authentication-scopes) for the OneDrive API not the LiveConnect scopes, for the OneDrive API including `onedrive.readonly` or `onedrive.readwrite` would be the correct ones granting the appropriate access.

**Comment by VanKrock** [comment]
@peternied I use "onedrive.readonly", but for some accounts GetFolderAsync returns null folder
