### ISSUE TITLE
Root Url for Sharepoint Online

### ISSUE THREAD

**Issue by phanindraramesh** [OneDrive/onedrive-api-docs#268]
On Onedrive Dev Center home page (https://dev.onedrive.com/index.htm), it is written that one drive api can be used for onedrive, one drive for business and sharepoint. But in the documentation, nothing about share point is mentioned. Can any one please update the document with the root url to be used to access documents in sharepoint online document libraries and Delegated Permissions to be given to app in azure management portal, so we can access Sharepoint online document libraries. 

I have give the following permissions to an applicaiton

Access User's data any time,
Read Files that User selects,
Read and write Files that User selects,
Have full access to user's Files and Files shared with...
Read user files and files shared with user

But in the discovery services, I only see onedrive for business services but no sharepoint related services. Can you please point out what wrong am I doing that is preventing me to access sharepoint services?

**Comment by danjarvis** [comment]
:+1:

**Comment by mimetnet** [comment]
I second this! I have been searching for more than a day without any luck. Any help would be greatly appreciated.

👍🏼

**Comment by danjarvis** [comment]
So @phanindraramesh it looks like the serviceResourceId is just: `https://<tenant>.sharepoint.com` (drop the '-my' from the OneDrive for Business resource id).

However, the API endpoints are not the same as they are for OneDrive. If you query: `https://<tenant>.sharepoint.com/_api` you will get back a JSON blob like this:

```
{
  "odata.metadata": "https://<tenant>.sharepoint.com/_api/$metadata",
  "value": [
    {
      "name": "files",
      "url": "files"
    },
    {
      "name": "lists",
      "url": "lists"
    }
  ]
}
```
You can then make requests to `/_api/lists` and `/_api/files`. I have yet to actually get the files to list properly though ;/

**Comment by danjarvis** [comment]
Actually... that is just the normal SharePoint 2013 API :(

**Comment by rgregg** [comment]
You can use the OneDrive API for the default document library in a site by using the Site URL + "_api/v2.0/drive". For example:

`https://{tenant}.sharepoint.com/sites/{site-name}/_api/v2.0/drive`

**Comment by danjarvis** [comment]
Thanks, @rgregg. Looks like you also need to have a subscription to SharePoint Online when using an app registered through AzureAD...

**Comment by phanindraramesh** [comment]
Thank you, @rgregg .

@danjarvis , can you please elaborate on "Looks like you also need to have a subscription to SharePoint Online when using an app registered through AzureAD...". Do you mean that the azure account used to register the app should also have an office 365 subscription?

**Comment by rgregg** [comment]
To be able to access the permissions for SharePoint in the Azure Active Directory management console, your tenant needs to be provisioned for an Office 365 subscription.

**Comment by phanindraramesh** [comment]
Thanks @rgregg . Can you also please point out how to check if my tenant is provisioned for Office365 subscription?

**Comment by phanindraramesh** [comment]
@rgregg When both One drive for business and Sharepoint Online are part of office365 and my the app that I have registered is able to fetch data from one drive for business, can you please point out what wrong am I doing that is preventing me to access SharePoint related permissions in Azure Active Directory Management console?

**Comment by rgregg** [comment]
Can you shoot me an e-mail? I need a little more information from you including some details that probably shouldn't be recorded in public forever. My e-mail is my username @ microsoft.com

**Comment by neeraj-khosla** [comment]
@rgregg , I'm also facing the same issue. Can you please help me . I have searched a lot on this and followed almost all the tutorial but can't find success.

Please check this screen shot. http://prntscr.com/bfvf0u
I'm using HttpClient to make a request to the url after authentication the user.
BaseUrl = https://boardsyn-my.sharepoint.com/_api/v2.0/me

These are the applications, i have added on the Azure Activity and given permissions. 
Please check this screenshot http://prntscr.com/bfvgom

**Comment by neeraj-khosla** [comment]
Hello @rgregg 
Can you please help me out here.

While getting reference of drive service, we need to get Access token for service Right?
and while retrieving the Access Token for Service I'm getting 400 bad request error.
I'm using this resource id https://<>-my.sharepoint.com/ .

**Comment by shoaibadil** [comment]
hi @rgregg  you said 
The API doesn't yet support accessing secondary document libraries, but we're working on that support.

Can we use following API to support non-default document libraries

 https://{tenant}.sharepoint.com/sites/{site-name}/_api/v2.0/drives/{driveId}

**Comment by rgregg** [comment]
@shoaibadil Yes, that works. You should also be able to get a list of document libraries by enumerating the /drives collection:

GET https://tenant.sharepoint.com/{url-to-site}/{_api/v2.0/drives

**Comment by sbellan** [comment]
@rgregg 
We are able to get the list of drives(document libraries within the site) with /drives. But unable to a list the contents of a non-default document library by passing the driveId with /drives/{driveId}. Is this functionality already there or still in works? Thanks.

**Comment by jensdotbruggeman** [comment]
@sbellan , @rgregg  
Same issue here. Every document library got listed correctly with the /drives command , however listing the content of a non-default document library did not work f.e.
https://<tenantname>.sharepoint.com/_api/v2.0/drives/<driveid>/root/children

**Comment by rgregg** [comment]
What auth scopes have you requested?

**Comment by sbellan** [comment]
We have  in
Application permission,
 - Read and write items and lists in all site collection
Delegated permission,
 - Read and write user files
 - Read and write items and lists in all site collection

**Comment by jensdotbruggeman** [comment]
@rgregg : using app-only token (daemon application) -> uploading files works correctly.  
Performing LIST via https://tenantname.sharepoint.com/_api/v2.0/drives/driveid/root/children does not give me detail about the items.
Auth scope : Office365 Sharepoint Online: has all 8 application permissions enabled and are granted by admin. (effectively checked the JWT)

**Comment by sbellan** [comment]
@rgregg Can you please confirm if non-default document libraries are supported or if we are not using it correctly. Thanks.

**Comment by rgregg** [comment]
Those permissions should be sufficient to get you access to items in all site collections that the signed in user can access (when delegated permissions are used) or all items in all document libraries (when using client credentials).

Secondary document libraries are supported through the API you're calling. How are you obtaining the driveId for a secondary document library (are you using /drives to enumerate them)? Is the document library you are targeting in the same site collection as the tenant's root site, or a different site collection (say, under a mysite)?

Can you include a request / response example?

**Comment by sbellan** [comment]
Thanks @rgregg Figured it was a user error. I was using drive/{drive-id} instead of drives/{drive-id}.

The following works for me,

https://veraengenv.sharepoint.com/SarvaTestSite/_api/v2.0/drives/b!vZn4gvPZgEGfRWFQYbih6mFCzVktIRBNhZu_RwyO_w6wxB2Rrk8mRbLphnvO21K7/root/children

**Comment by anildbest83** [comment]
@sbellan , i m getting unauthorized error when trying to get documents like this

do i need to remove 'my' from the serviceResourceId ?

**Comment by sbellan** [comment]
@anildbest83 From the discovery API response, you need to get the resource id corresponding to the capability 'RootSite' and get that service resource id. ( and yes, that is usually without the my)

**Comment by anildbest83** [comment]
@sbellan thanks for your reply.
i m getting token from https://api.office.com/discovery/v2.0/me/services and in serviceResourceId i have removed '-my' and serviceResourceId is now

https://aniltest.sharepoint.com/_api/v1.0/drives/items

but when i try to get response from HttpWebRequest it gives me 'unauthorized ' error ,
Response Header show
reason="Invalid audience Uri 'https://aniltest-my.sharepoint.com/'.";category="invalid_client"

Please advise

**Comment by sbellan** [comment]
Probably you dont have access to sharepoint, In the response to the
me/services, you should see an entry for Shareporint(Capability=RootSite),

{
   "@odata.context":"
https://api.office.com/discovery/v2.0/me/$metadata#allServices",
   "value":[
      {
         "@odata.editLink":"services('MyFiles@O365_SHAREPOINT@v1.0')",
         "serviceApiVersion":"v1.0",
         "@odata.type":"#Microsoft.DiscoveryServices.ServiceInfo",
         "entityKey":"MyFiles@O365_SHAREPOINT@v1.0",
         "serviceName":"Office 365 SharePoint",
         "serviceResourceId":"https://xxx-my.sharepoint.com/",
         "@odata.id":"
https://api.office.com/discovery/v2.0/me/services('MyFiles@O365_SHAREPOINT@v1.0')
",
         "capability":"MyFiles",
         "providerId":"72f988bf-86f1-41af-91ab-2d7cd011db47",
         "serviceEndpointUri":"https://xxx-my.sharepoint.com/_api/v1.0/me",
         "serviceAccountType":2,
         "serviceId":"O365_SHAREPOINT",
         "providerName":"Microsoft"
      },
      {
         "@odata.editLink":"services('MyFiles@O365_SHAREPOINT@v2.0')",
         "serviceApiVersion":"v2.0",
         "@odata.type":"#Microsoft.DiscoveryServices.ServiceInfo",
         "entityKey":"MyFiles@O365_SHAREPOINT@v2.0",
         "serviceName":"Office 365 SharePoint",
         "serviceResourceId":"https://xxx-my.sharepoint.com/",
         "@odata.id":"
https://api.office.com/discovery/v2.0/me/services('MyFiles@O365_SHAREPOINT@v2.0')
",
         "capability":"MyFiles",
         "providerId":"72f988bf-86f1-41af-91ab-2d7cd011db47",
         "serviceEndpointUri":"https://xxx-my.sharepoint.com/_api/v2.0/me",
         "serviceAccountType":2,
         "serviceId":"O365_SHAREPOINT",
         "providerName":"Microsoft"
      },
      {
         "@odata.editLink":"services('RootSite@O365_SHAREPOINT@v1.0')",
         "serviceApiVersion":"v1.0",
         "@odata.type":"#Microsoft.DiscoveryServices.ServiceInfo",
         "entityKey":"RootSite@O365_SHAREPOINT@v1.0",
         "serviceName":"Office 365 SharePoint",
         "serviceResourceId":"https://xxx.sharepoint.com/",
         "@odata.id":"
https://api.office.com/discovery/v2.0/me/services('RootSite@O365_SHAREPOINT@v1.0')
",
         "capability":"RootSite",
         "providerId":"72f988bf-86f1-41af-91ab-2d7cd011db47",
         "serviceEndpointUri":"https://xxx.sharepoint.com/_api",
         "serviceAccountType":2,
         "serviceId":"O365_SHAREPOINT",
         "providerName":"Microsoft"
      }
   ]
}

**Comment by anildbest83** [comment]
@sbellan you are right, i m not getting entry for Shareporint(Capability=RootSite) in the response

With my office 365 account i can see files for One Drive for business but not Sharepoint

How can i set permissions to access sharepoint?

**Comment by sbellan** [comment]
Its about licensing.. talk to your o365 Admin.

**Comment by anildbest83** [comment]
i can not use my test account for development?

Do i need to purchase a licence?

**Comment by anildbest83** [comment]
@sbellan Hi, thanks a lot, it is working fine now, i used account which has license and it is returning proper response
Thanks

**Comment by legsak1mbo** [comment]
@sbellan @anildbest83 We've got the same issue here. The application has all required permissions and the user has an Office 365 Business Premium license with Sharepoint but I'm not seeing Shareporint(Capability=RootSite) in the response. Which license is required for this?

**Comment by EbinJohn** [comment]
@rgregg Did you guys started supporting secadory document libraries through `https://{tenant}.sharepoint.com/sites/{site-name}/_api/v2.0/drive`
