### ISSUE TITLE
Webhooks for Onedrive for Business

### ISSUE THREAD

**Issue by phanindraramesh** [OneDrive/onedrive-api-docs#270]
In the documentation for webhooks for Onedrive (https://dev.onedrive.com/misc/webhooks.htm), it is mentioned that to register OneDrive Webhook, the developer has to send a mail to odwhr@microsoft.com with "Webhook registration" as subject and "client_id%" as the body. Can any body give the exact the body of the mail to be sent as the documentation talks about "webhook URL" as well.

Also, it is mentioned that notification doesn't include any information about the changes that triggered it and the app is expected to use view.delta to detect changes based on entity.id provided in notification body. But in case of ODB, view.delta can only be used on 'root', In that case how can we use the entity.id for fetching the latest changes on the item?

It would be great if anyone could provide a link to an example that demonstrates an example on Webhooks for ODB.

**Comment by rgregg** [comment]
Webhooks are only supported for the consumer service right now. We're still working on delivering them for OneDrive for Business and SharePoint.
