### ISSUE TITLE
New Search Results Not Appearing (Or Massively Delayed?)

### ISSUE THREAD

**Issue by JaredBanyard** [OneDrive/onedrive-api-docs#271]
I added 3 new files, and they appear in the web, and through the api list.  But have yet to appear through search.  How long is the delay?

**Comment by JaredBanyard** [comment]
Nevermind, you guys require wildcards

**Comment by rgregg** [comment]
Hi Jared, can you elaborate on what you mean by "you guys require wildcards"? You should be able to generate a search query like view.search?q=foobar and get back results that include "foobar" without the need to specify any wildcard characters.

**Comment by JaredBanyard** [comment]
@rgregg Oh, I'm saying you don't match partial words.  `fooba` will not match `foobar`.  You have to use `fooba*` instead.  Which I will just add programmatically.  We search in real time, so as you type `foobar`, we would do `fo*` `foo*` `foob*` `fooba*` etc.. etc..
