### ISSUE TITLE
[Question] is there any way to modify the mtime of the file by REST API

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#273]
Hi there,

I make an experiment:
1. Install OneDrive client on two Computer (1 is MAC, 1 is PC)
2. copy a file with mtime:2014/12/01 from one PC.
3. I found that after synchronising, mtime of the file in another PC is still 2014/12/01
4. use REST API to get metadata of the file, event createdDateTime or lastModifiedDateTime are the time when the file created in the cloud.

Does that mean OneDrive Client will keep the client mtime/create time of files and API does not support such attribute?

Some storage service like dropbox will keep a attribute 'client mtime' as the real client mtime and we could make all the files with the same mtime.

Is it normal if we get the mtime/create time from metadata differed from what we see from WEB ?

**Comment by ificator** [comment]
Check out the [fileSystemInfo facet](https://github.com/OneDrive/onedrive-api-docs/blob/master/facets/filesysteminfo_facet.md) - it should have what you want. Essentially, it tracks the timestamps that should manifest on the a system, while the `item` level timestamp properties track the times from the services perspective.

**Comment by mikechiu1012** [comment]
Hi @ificator, 

Thanks for ur quickly reply.

I will follow the filieSystemInfo: lastModifiedDateTime. 

Please Close it, thanks.

**Comment by ificator** [comment]
Thanks for confirming!
