### ISSUE TITLE
Azure portal string change issue

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#275]
@rgregg sir...
It is urgent can somebody reply

While creating application from azure portal we give required permission 
i.e windows azure active directory, delegate permission we use to select : "Enable sign-on and read users' profiles" 
for which in response, scope used to be "UserProfile.Read"

but now instead of "Enable sign-on and read users' profiles" it is "Sign in and read user profile"
so in response receiving "User.Read"

attaching snapshot 

![onedrive](https://cloud.githubusercontent.com/assets/11455759/11855124/5302e2b4-a46e-11e5-9097-b3c8f17b4749.png)

this change in string value causing problem to the app...

In the app we have checks on scope value, if any scope value doesnt match with the required scope, we prompt that "App doesnt have required permission" and authentication process fails, and user couldnt login 

currently all attempt to login are getting failed since the value have been changed...

**Comment by ankit-ankuagrawal** [comment]
There is one more twist to this issue
having 2 application, one is receiving scope has "UserProfile.Read"
and other receiving scope has "User.Read" for same permission 

attaching screenshot
1) 1st application receiving scope has "UserProfile.Read"
![onedrive working permission](https://cloud.githubusercontent.com/assets/11455759/11864012/2c73bab4-a4bf-11e5-89b3-edba61d46146.png)
![one drive working](https://cloud.githubusercontent.com/assets/11455759/11864013/2e36961e-a4bf-11e5-9ac3-f068e2af13ba.png)

2) 2nd application receiving scope has "User.Read"
![onedrive fail permission](https://cloud.githubusercontent.com/assets/11455759/11864037/67c63bbe-a4bf-11e5-8636-d95e619f6498.png)
![onedrive fail](https://cloud.githubusercontent.com/assets/11455759/11864040/6a144712-a4bf-11e5-8c7e-1e8d1edf0432.png)

**Comment by ankit-ankuagrawal** [comment]
any update here?

**Comment by rgregg** [comment]
The scope names were changed as you discovered. In general, we don't recommend that client applications validate the scopes in the access token / token response, since the API itself will validate those scopes.

At this time we don't expect to make additional changes to existing scope names.
