### ISSUE TITLE
If-None-Match not working?

### ISSUE THREAD

**Issue by markusf** [OneDrive/onedrive-api-docs#276]
Hey guys, I am currently trying to explore the API and having issues requesting files with etag provided. I always get a 200 and never run into a 304, even though I provided the correct E-Tag Header:

If-None-Match "{EF977E3B-81E9-485E-874E-E5A9E03E2184},1"

I am using Postman (with cached turned off) for testing. Also with a different Restclient it is not working.

Any Ideas?

Cheers,
Markus

**Comment by ificator** [comment]
Hi @markusf, can you let us know what URL you're hitting? That'll help us repro your exact scenario easier.

**Comment by markusf** [comment]
https://idealerdemo-my.sharepoint.com/_api/v2.0/drive/items/016N7NUIG2SD6ESZAFPVDIQHKIHICZER76/content would be the url

**Comment by ificator** [comment]
Thanks for confirming - it appears as we do have a bug in precondition evaluation specifically on the use of /content.

**Comment by markusf** [comment]
Okay, it's good that you can reproduce. Do you already have an idea, when this would be fixed?

**Comment by ificator** [comment]
Realistically, due to the time of year, I wouldn't expect this to be fixed until towards the end of January at the earliest. But you never know... I'll update when we have some idea of when it will land.

**Comment by markusf** [comment]
I guess this code is closed-source and we would not have a chance here to collaborate right?

I am just wondering, why such an crucial feature is not working at all.

**Comment by markusf** [comment]
Any news here?

**Comment by Soenke-incadea** [comment]
Is there any update on this topic? We will very soon go- live with our implementation and need this fix

**Comment by Soenke-incadea** [comment]
@ificator 
Did you have an update on the bubfix. In the earlier discussion you mentioned end of January as expected closure date

**Comment by markusf** [comment]
@rgregg 
Do you have an update on this? Seems like @ificator is not responsive anymore.

**Comment by rgregg** [comment]
I'll figure out where we are on this and report back on Tuesday.

**Comment by Soenke-incadea** [comment]
@rgregg 
Do you have an update on this topic?

**Comment by rgregg** [comment]
Hi folks: a fix for this issue has been checked in and is still in the deployment process to SharePoint. If everything continues smoothly, it should be broadly deployed in about a week.

**Comment by markusf** [comment]
Great, thank you!

**Comment by Soenke-incadea** [comment]
Hi @rgregg 
was the fix deployed?

**Comment by Soenke-incadea** [comment]
@rgregg  any update on this topic?

**Comment by ificator** [comment]
The fix was deployed - if you're still seeing issues please paste in a sample, full, request/response so that we can take a look.
