### ISSUE TITLE
Not able to see the shared folders anymore

### ISSUE THREAD

**Issue by Rocky2908** [OneDrive/onedrive-api-docs#277]
I have created this [issue](https://github.com/OneDrive/onedrive-api-docs/issues/237) stating I couldn't create a link using action.createLink for the files that are shared by other account holder's. I have received a response in that ticket that for _most of the tenants the issue is resolved_. 

In order to test that I tried to _upload a file from the shared_ folder. But to my surprise I couldn't see the shared folder and I could only see the rest of the files. _I have attached a screen shot of that_,
![screen shot 2015-12-17 at 2 33 18 pm](https://cloud.githubusercontent.com/assets/10181686/11865617/28e12e7a-a4cb-11e5-8f0c-a3e09da2c5b9.png)

I have two questions now.
1. I want to know does this feature of uploading files from the shared folder is disabled now?
2. And about my first [issue](https://github.com/OneDrive/onedrive-api-docs/issues/237), can we now create the public sharing link for shared files using action.createLink.

Thank You.

**Comment by rgregg** [comment]
@Rocky2908: Is this for OneDrive Personal or Business?

I'm a bit fuzzy on what you're trying to accomplish. Are you trying to upload/create a new file in a shared folder that the signed in user has access to? How are you accessing the shared folder?

Can you provide sample code or a Fiddler trace of the issue? That will help us see what's going on and debug.

Thanks!

**Comment by Rocky2908** [comment]
@rgregg : I am using onedrive for personal.
**Scenario I want to accomplish:** My users will select their files through the Onedrive iFrame window and I will make an API request to fetch the public link for the file( so that other users can view that file too).

The [issue](https://github.com/OneDrive/onedrive-api-docs/issues/237) I reported before was regarding  getting public link for the files that are shared with my users. During the time I reported this issue, my users were able to view their **shared** folders along with their normal **Files** folder using the Onedrive iFrame.

But recently they were able to see only the **Files** folder but not the **shared** folder(as shown in the screenshot). 

I am curious to know how they can see the **shared** folder of them on the iFrame window.

Thanks.
