### ISSUE TITLE
Upload of a large file (>60MB) fails with connection aborted

### ISSUE THREAD

**Issue by wiktorn** [OneDrive/onedrive-api-docs#279]
When I try to upload a large file to OneDrive, API will accept the upload, but abort the connection once the 60MB are sent.

As the content length is known before hand, API could reject the upload with predefined error code, to save the time and inform the app, that multipart upload is necessary.

**Comment by ificator** [comment]
Are you seeing this on Consumer or Business?

**Comment by wiktorn** [comment]
Consumer

**Comment by wiktorn** [comment]
Just for reference. I'm using maybe not canonical request to upload as:
''''
PUT https://api.onedrive.com/v1.0/drives/me/root:/backupy:/children/backup-svn.7z/content
''''

(mind the "children" part). This is what I get I follow examples from:
https://github.com/OneDrive/onedrive-sdk-python

**Comment by ificator** [comment]
Hmm, consumer has a maximum request size of 100MB so it really shouldn't be aborting at all. Do you know how long it's taking to send the 60MB?

**Comment by wiktorn** [comment]
I'm trying to upload a file with a size of around 2.2GB, I guessed that the abort happens at 60MB border, but maybe it's 100MB border. It's roughly after 5 minutes. I should be able to send ~375MB file during this time.

**Comment by wiktorn** [comment]
Even uploading 150MB I get connection aborted, instead of some meaningful error. I've tried also URL:
```
PUT https://api.onedrive.com/v1.0/drives/me/root:/backupy:/backup-svn.7z/content
```

But it gives the same behaviour

**Comment by mikechiu1012** [comment]
I had met this situation recently and I adjusted the send buffer size from 8K per packet to 16K and the situation is gone.

I am not sure if the root cause is sending a fragment(multiple of 320K) in many pieces of packets.
But now It works.

**Comment by ificator** [comment]
@mikechiu1012:
I think wiktorn's scenario is a little different - there isn't any chunking involved. That should mean there's a 100MB file limit.

@wiktorn:
I tried a few different things to repro, but all occurred as you'd expect - instantaneous response of `413 Request Entity Too Large`. Is it possible you're actually jumping through some form of proxy server that's attempting to buffer before sending it on to us?

**Comment by wiktorn** [comment]
For sure there is no proxy between me and the server. While playing with Python SDK I've observed different behaviour based on some headers.

Full request is:
```
PUT /v1.0/drives/me/root:/backupy/backup-svn-dummy.7z:/content HTTP/1.1
Host: api.onedrive.com
Accept-Encoding: identity
Content-Length: 157286400
Authorization: bearer *redacted*
X-RequestStats: SDK-Version=python-v1.0.1

```
And file length is indeed 157286400. Adding `Content-Type: application/octet-stream` header doesn't change situation

**Comment by wiktorn** [comment]
Indeed, I can't reproduce the problem using curl. Maybe this has something to do with multiple requests done over same http connection

**Comment by wiktorn** [comment]
Ok, it looks like it's a bug in requests python library. Although the server returns HTTP 413 response code, http.client python library is not taking this into account on PUT request.

**Comment by ificator** [comment]
Thanks for letting us know wiktorn!

**Comment by wiktorn** [comment]
Python bug tracked here:
http://bugs.python.org/issue25919
