### ISSUE TITLE
who does user_id refer to?

### ISSUE THREAD

**Issue by dwhieb** [OneDrive/onedrive-api-docs#281]
When using the Authorization Code grant flow, I receive a `user_id` parameter, as mentioned in #43. I thought this was the ID of the resource owner (the `owner.user.id` property of the default drive), but the `user_id` changes depending on whether I'm authenticating from my dev app or my production app. This makes me think that `user_id` might actually be an ID for the app owner, or something else entirely.

Can you clarify what the `user_id` parameter refers to? Then I'd be happy to create a pull request that updates the documentation on authentication.

**Comment by rgregg** [comment]
In the authorization code grant flow, the user_id parameter is a unique identifier for the signed in user that is generated for the application. This user_id is anonymized between apps, and would be expected to be different for the same user when multiple client_ids are involved.

**Comment by dwhieb** [comment]
Created pull request #285 with information about `user_id` (and the `state` parameter, since this was also missing)
