### ISSUE TITLE
Conflict while batch remove permission

### ISSUE THREAD

**Issue by festum** [OneDrive/onedrive-api-docs#282]
I have a folder share with multiple users. 409 conflict will encountered when [delete permission](https://github.com/OneDrive/onedrive-api-docs/blob/master/items/permission_delete.md) after 1st permission. Is it a limitation?

**Comment by rgregg** [comment]
Hi Festum, I'm not sure I understand what you're doing so I can't repo this behavior. Can you provide more details about what calls you're marking and when you get the error response?

**Comment by chiouchu** [comment]
Hi rgregg, we use:
https://api.onedrive.com/v1.0/drive/root:/{path}:/permissions
get all of the permission on the folder, and then use for loop to delete permission by each id
https://api.onedrive.com/v1.0/drive/root:/{path}:/permissions/{id}

If there are two or more permissions, after the first one I will get 409 conflict and the error message:
{"error":{"code":"resourceModified","message":"ETag does not match current item's value"}}

**Comment by rgregg** [comment]
Thanks @chiouchu. I've assigned @katahir to investigate and see what's going on here.

**Comment by daohoangson** [comment]
@katahir Is this resolved? I have encountered this error message today while running a sync via [ncw/rclone](https://github.com/ncw/rclone)

**Comment by chackman** [comment]
Sorry about this very old issue going stale.  If this is still reproducing, could you please provide updated request & response information to help us investigate further?  Thanks.
