### ISSUE TITLE
Loss of precision when updating datetime

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-api-docs#283]
I notice that datetime OneDrive API returns is of format like "2015-02-23T19:02:31.433Z", so when calling API to update lastModified time I give strings of the same format. But I got error

```
[item] Cannot convert the literal '2015-10-05T02:24:27' to the expected type 'Edm.DateTimeOffset'. (invalidRequest).
```

Of course I can remove the microsecond part from the string at the expense of precision, but can't the API preserve the precision correctly? Or am I doing something wrong?

**Comment by ificator** [comment]
Hey @xybu do you have a sample request that hits this? It works for me when I send a timestamp back in the same format - make sure yours looks like what we return including the Z at the end to indicate UTC.

**Comment by rgregg** [comment]
Closing out due to lack of response. Please reopen if you have more information.
