### ISSUE TITLE
Sites under a tenant in SharePoint Online

### ISSUE THREAD

**Issue by phanindraramesh** [OneDrive/onedrive-api-docs#286]
Hi, 
  Is there a way to list all the sites available in SharePoint online under a tenant using the rest api?

**Comment by rgregg** [comment]
This is not available using the OneDrive API.

There are a few methods for discovering _some_ sites using the SharePoint REST API, but in general getting a list of all sites/webs in SharePoint isn't possible for apps.

See this question on the SharePoint StackExchange: http://sharepoint.stackexchange.com/questions/92467/retrieve-toplevel-sites-subsites-using-rest-api
