### ISSUE TITLE
onedrive for business delta request return 404 Not Found Error while delete whole folders from Cloud

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#288]
Hi I am trying to test delta API of onedrive for business.
There's a strange response if I delete a whole folder(within files in it) from cloud, I will get 404 Not Found Error.

here is the request:
HTTPError: 404 Client Error: Not Found for url: https://mikechiuqnap-my.sharepoint.com/_api/v2.0/me/drive/root/view.delta?top=1000&token=1%3B%25234%3B%25231%3B3%3B41f7f027-b93a-40a2-a30d-e80e1d93f3dd%3B635880933863070000%3B61026599%3B%2523&select=id%2Cname%2Csize%2CeTag%2Cfile%2Cfolder%2Cdeleted%2CparentReference%2CfileSystemInfo

other operations like move/rename/... are fine and return correct information from delta API.
OneDrive consumer API will not response such error, too.

Is this a bug or something illegal? Thanks.!

**Comment by rgregg** [comment]
There's a bug in the view.delta API that causes this behavior. We've coded a fix and are verifying that the fix is correct before we'll start rolling it out to production.

**Comment by mikechiu1012** [comment]
Thanks for ur quickly reply.

I'll wait for it.

**Comment by mikechiu1012** [comment]
Additional, 
sometimes view.delta will return 404 with other error message:
GET /_api/v2.0/me/drive/root/view.delta?top=1000&token=1%3B%25234%3B%25231%3B3%3B41f7f027-b93a-40a2-a30d-e80e1d93f3dd%3B635883666123570000%3B61350035%3B%2523&select=id%2Cname%2Csize%2CeTag%2Cfile%2Cfolder%2Cdeleted%2CparentReference%2CfileSystemInfo HTTP/1.1" 404 None
404 {"error":{"code":"itemNotFound","message":"The resource could not be found."}}

I am not sure if this is the same issue as above one, I add this here cause the same API.
Thanks.

**Comment by ificator** [comment]
The fix for this issue was deployed a LONG time ago so I'm going to close this out - please feel free to reopen if there are still issues being observed.
