### ISSUE TITLE
id value not returned in response to select query as specified

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#29]
wanna bring in notice
http://stackoverflow.com/questions/29006895/id-value-not-returned-in-response-to-select-query-as-specified

**Comment by jsinh** [comment]
I have tested and can confirm this bug too (was going to post the same tonight). Either this should be possibly fixed in the API calls to works as expected or the document should be updated accordingly.

**Comment by rgregg** [comment]
Yep, this is a doc bug. We don't return the ID property always, I'll update the docs to that effect.

**Comment by rgregg** [comment]
The docs are updated to indicate you need to specify all fields you want returned.

**Comment by ankit-ankuagrawal** [comment]
thank u for response
