### ISSUE TITLE
onedrive for business rename file failed with Invalid folder name

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#290]
Reproduce steps:
1. upload a file with name 100k.mv under /test_mv/move
2. call PATCH api to rename this file to /test_mv/move/100k_file
Get exception:
500 {u'message': u'Invalid folder name.  You cannot create a folder name that ends with a suffix used to organize supporting files. Enter a different name and click OK.', u'code': u'-2130245263, Microsoft.SharePoint.SPException'}

Request body and headers:
data: {'name': '100k_file'}, headers: {'Content-Type': 'application/json'}

If I change step 2 to /test_mv/move/100k_fil, it success.
Directly upload with name '100k_file' is fine, too.

I think it's a bug and there's no reason that one file could not be rename with 'file' as postfix?

**Comment by ificator** [comment]
Unfortunately this is a limitation of OneDrive for Business - check out [Restrictions and limitations with OneDrive for Business](https://support.microsoft.com/en-us/kb/2933738) for the complete set.

**Comment by mikechiu1012** [comment]
hi @ificator , 
Thanks for ur reply. 
I will try to verify these limitation and restriction.

By the way, 
the upload action could directly upload file with _file as postfix.
here is the response:
"PUT /_api/v2.0/me/drive/root:/abc/up_file:/content HTTP/1.1" 201
/abc/up_file meta: {'mtime': 0, 'type': u'file', 'name': u'up_file', 'etag': u'"{EA567B71-D7A6-42A8-AD63-E5D7622F679C},1"', 'size': 102400}

So it's an illegal action, right? If it is, it might be a bug ?

**Comment by ificator** [comment]
We have a bug somewhere no matter how you spin it since both create and move scenarios should enforce identical constraints on names. As to which is the bug, I'll need to follow up with the team.

**Comment by mikechiu1012** [comment]
hi @ificator,

thanks for ur reply, I'll wait for it.

**Comment by mikechiu1012** [comment]
Hi @ificator , I try to create folder with suffix _Dateien and create successfully.

And create dir with max length 203 (file is the same)

Here are two questions:
1) what different between share point 2013 and share point library and onedrive business?
2) Does the limitation and restriction list above all apply among these three services?

It's important to clarify these points for developing the application, thanks!

**Comment by ificator** [comment]
We just tried to revalidate this issue and it seems to work now - we continously make changes to improve the product and so it may be that this was implicitly fixed. Please reactivate if you continue to see the problem.
