### ISSUE TITLE
SharePoint permissions documentation

### ISSUE THREAD

**Issue by phanindra-ramesh** [OneDrive/onedrive-api-docs#293]
Hi,
  Is there a place where permissions of files and folders in SharePoint sites are documented? When I try to query https://{tenant}.sharepoint.com/{siteName}/_api/v2.0/drive/items/{itemId}/permissions, I am getting that looks like the following

"@odata.context": "https://{site-name}.sharepoint.com/<site-name>/_api/v2.0/$metadata#permissions",
    "value": [
        {
            "@odata.type": "#oneDrive.permission",
            "@odata.id": "https://{site-name}.sharepoint.com/<site-name>/_api/v2.0/oneDrive.permission{uid}",
            "@odata.editLink": "oneDrive.permission{uid}",
            "id": "<some Id>",
            "roles": [
                "read"
            ],
            "link": {
                "scope": "organization",
                "type": "view",
                "webUrl": Permission Url
            }
        },
        {
            "@odata.type": "#oneDrive.permission",
            "@odata.id": "https://{site-name}.sharepoint.com/<site-name>/_api/v2.0/oneDrive.permission{uid}",
            "@odata.editLink": "oneDrive.permission{uid}",
            "id": {uid},
            "roles": [
                "write"
            ],
            "link": {
                "scope": "organization",
                "type": "edit",
                "webUrl": Permission Url
    }
        },
        {
            "@odata.type": "#oneDrive.permission",
            "@odata.id": "https://{site-name}.sharepoint.com/<site-name>/_api/v2.0/oneDrive.permission{uid}",
            "@odata.editLink": "oneDrive.permission{uid}",
            "grantedTo": {
                "user": {
                    "displayName": "Company Administrator"
                }
            },
            "id": {uid}
            "roles": [
                "write"
            ]
        }
    ]
What I didn't understand here is scope values (organization in above output) of link attribute. Also, when I share a file with some user or a group, I don't see the permission granted to the user or group in the rest call output. 

Can anyone please help me with the issue?

**Comment by phanindraramesh** [comment]
Hi team,
  Any update on this?

**Comment by rgregg** [comment]
That isn't covered by our docs yet. Links with "scope": "organization" is a new feature of SharePoint and OneDrive for Business that allows the links to be used by anyone within the company, but not external users / anonymous access. They are currently automatically created for every file in OneDrive for Business, but can be deleted/removed by the user through the sharing dialog.

We'll update the docs soon to include this additional parameter.
