### ISSUE TITLE
scope to allow fetch of /drive/view.recent

### ISSUE THREAD

**Issue by cguZZman** [OneDrive/onedrive-api-docs#296]
Hi there,
Can you guys tell me which scope should I use to fetch **`/drive/view.recent`** list?
I'm getting a 403 - Forbidden using the scopes `wl.offline_access`, `wl.signin`, `onedrive.readwrite`.
Thanks!

**Comment by rgregg** [comment]
The `view.recent` isn't part of our of our supported API. Only the API resources, properties, and methods documented on [dev.onedrive.com](https://dev.onedrive.com) are supported.

**Comment by cguZZman** [comment]
All right. Just wondering about it because it's on the SDK at the Drive request builder (https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/generated/BaseDriveRequestBuilder.java), and looked supported to me. 
Good to know that [dev.onedrive.com](url) is the rule here.
Thanks
