### ISSUE TITLE
OneDrive Business file upload fails with 500 internal Server error

### ISSUE THREAD

**Issue by acarlsen** [OneDrive/onedrive-api-docs#302]
I am having issues uploading files to my OneDrive Business account in Android.

I am using the upload API described here (simple and resumeable both doesn't work for me): https://dev.onedrive.com/items/upload.htm

Everything else works fine. I can browse, create folders, delete, rename, download files. I use the same implementation for regular OneDrive and that works without issues. I have also tested with official OneDrive Android app and there upload works, so it doesn't seem to be a permissions issue with my OneDrive Office 365 account.

I am using Retrofit/OkHttp.

This is the log from the query:

```
OkHttp: --> PUT https://<tenantname>-my.sharepoint.com/_api/v2.0/drive/items/root:/pricelist.pdf:/content HTTP/1.1
OkHttp: Content-Type: application/pdf
OkHttp: --> END PUT

OkHttp: <-- 500 Internal Server Error https://<tenantname>-my.sharepoint.com/_api/v2.0/drive/items/root:/pricelist.pdf:/content (831ms)
OkHttp: Cache-Control: private, max-age=0
OkHttp: Transfer-Encoding: chunked
OkHttp: Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
OkHttp: Expires: Mon, 01 Feb 2016 22:09:26 GMT
OkHttp: Last-Modified: Tue, 16 Feb 2016 22:09:26 GMT
OkHttp: Server: Microsoft-IIS/8.5
OkHttp: X-SharePointHealthScore: 0
OkHttp: X-SP-SERVERSTATE: ReadOnly=0
OkHttp: ODATA-VERSION: 4.0
OkHttp: SPClientServiceRequestDuration: 92
OkHttp: X-AspNet-Version: 4.0.30319
OkHttp: SPRequestGuid: e5e45f9d-80fa-3000-9580-b34e009cc4be
OkHttp: request-id: e5e45f9d-80fa-3000-9580-b34e009cc4be
OkHttp: Strict-Transport-Security: max-age=31536000
OkHttp: X-FRAME-OPTIONS: SAMEORIGIN
OkHttp: X-Powered-By: ASP.NET
OkHttp: MicrosoftSharePointTeamServices: 16.0.0.4921
OkHttp: X-Content-Type-Options: nosniff
OkHttp: X-MS-InvokeApp: 1; RequireReadOnly
OkHttp: P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
OkHttp: Date: Tue, 16 Feb 2016 22:09:25 GMT
OkHttp: OkHttp-Sent-Millis: 1455660569448
OkHttp: OkHttp-Received-Millis: 1455660570267
OkHttp: <-- END HTTP
TransferFileTask: Exception when transferring file
HttpException: OneDrive error: code = -1, System.IO.IOException, message = I/O error occurred.
```

What happens is that I always get a 500 internal server error with the same error body as seen above. As stated the exact same upload code works for ordinary OneDrive.

I have tried adding many different headers, like Content-Length, Host, Cache-Control etc. but nothing seems to make a difference. What is not seen is a Authorization header which is of course correct and works for all other requests.

**Comment by peternied** [comment]
I see the headers from the response, but I don't see the body which should be application/json.  The body of the response can have more [detailed error information](https://github.com/OneDrive/onedrive-api-docs/blob/master/misc/errors.md) encoded as json which would help determine next steps.

**Comment by acarlsen** [comment]
This is the full errorBody:

{"error":{"code":"-1, System.IO.IOException","message":"I/O error occurred."}}

**Comment by peternied** [comment]
Thanks @acarlsen 

@ificator This is coming back from the service, could you check the service logs?

**Comment by ificator** [comment]
I had a quick look and unfortunately it has as much useful information as the errorBody. @acarlsen how big is the file you're trying to upload?

**Comment by acarlsen** [comment]
The latest I tried was a 19 byte large text file. But I have tried with all different kinds of file types and sizes. Thanks for looking into this.

**Comment by ificator** [comment]
If you use the [resumable upload](https://dev.onedrive.com/items/upload_large_files.htm) mechanism do you have more luck? I'm just trying to scope down the surface area over which your issue is reproing as the logs don't tell us much :(

**Comment by acarlsen** [comment]
The error when using resumable upload is a little bit different, here a 12.5 MB file:

```
OkHttp: --> POST https://<tentantname>-my.sharepoint.com/_api/v2.0/drive/items/root:/test.bin:/upload.createSession HTTP/1.1
OkHttp: Content-Type: application/json; charset=UTF-8
OkHttp: Content-Length: 62
OkHttp: Accept: application/json; charset=UTF-8
OkHttp: --> END POST

OkHttp: <-- 200 OK https://<tentantname>-my.sharepoint.com/_api/v2.0/drive/items/root:/test.bin:/upload.createSession (1378ms)
OkHttp: Cache-Control: private, max-age=0
OkHttp: Transfer-Encoding: chunked
OkHttp: Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
OkHttp: Expires: Thu, 04 Feb 2016 21:52:22 GMT
OkHttp: Last-Modified: Fri, 19 Feb 2016 21:52:22 GMT
OkHttp: Vary: Accept-Encoding
OkHttp: Server: Microsoft-IIS/8.5
OkHttp: X-SharePointHealthScore: 0
OkHttp: X-SP-SERVERSTATE: ReadOnly=0
OkHttp: ODATA-VERSION: 4.0
OkHttp: SPClientServiceRequestDuration: 1229
OkHttp: X-AspNet-Version: 4.0.30319
OkHttp: SPRequestGuid: 1ddb609d-303d-3000-9580-bbb471fe0b41
OkHttp: request-id: 1ddb609d-303d-3000-9580-bbb471fe0b41
OkHttp: Strict-Transport-Security: max-age=31536000
OkHttp: X-FRAME-OPTIONS: SAMEORIGIN
OkHttp: X-Powered-By: ASP.NET
OkHttp: MicrosoftSharePointTeamServices: 16.0.0.5004
OkHttp: X-Content-Type-Options: nosniff
OkHttp: X-MS-InvokeApp: 1; RequireReadOnly
OkHttp: P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
OkHttp: Date: Fri, 19 Feb 2016 21:52:23 GMT
OkHttp: OkHttp-Sent-Millis: 1455918748418
OkHttp: OkHttp-Received-Millis: 1455918749782
OkHttp: <-- END HTTP

OkHttp: --> PUT https://<tentantname>-my.sharepoint.com/personal/anders_<tentantname>_onmicrosoft_com/_api/v2.0/drive/root/uploadSession?guid=%274104fbb9-bea1-4048-a8be-b54eeb275cfe%27&path=%27/~temp_test.bin%27&overwrite=False HTTP/1.1
OkHttp: Content-Type: application/octet-stream
OkHttp: Accept: application/json; charset=UTF-8
OkHttp: Connection: keep-alive
OkHttp: Content-Range: bytes 0-10485759/13067825
OkHttp: --> END PUT

OkHttp: <-- 500 Internal Server Error https://<tentantname>-my.sharepoint.com/personal/anders_<tentantname>_onmicrosoft_com/_api/v2.0/drive/root/uploadSession?guid=%274104fbb9-bea1-4048-a8be-b54eeb275cfe%27&path=%27/~temp_test.bin%27&overwrite=False (2960ms)
OkHttp: Cache-Control: private, max-age=0
OkHttp: Transfer-Encoding: chunked
OkHttp: Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
OkHttp: Expires: Thu, 04 Feb 2016 21:52:23 GMT
OkHttp: Last-Modified: Fri, 19 Feb 2016 21:52:23 GMT
OkHttp: Server: Microsoft-IIS/8.5
OkHttp: X-SharePointHealthScore: 0
OkHttp: X-SP-SERVERSTATE: ReadOnly=0
OkHttp: ODATA-VERSION: 4.0
OkHttp: SPClientServiceRequestDuration: 35
OkHttp: X-AspNet-Version: 4.0.30319
OkHttp: SPRequestGuid: 1ddb609d-0098-3000-9580-bd7479dd817b
OkHttp: request-id: 1ddb609d-0098-3000-9580-bd7479dd817b
OkHttp: Strict-Transport-Security: max-age=31536000
OkHttp: X-FRAME-OPTIONS: SAMEORIGIN
OkHttp: X-Powered-By: ASP.NET
OkHttp: MicrosoftSharePointTeamServices: 16.0.0.5004
OkHttp: X-Content-Type-Options: nosniff
OkHttp: X-MS-InvokeApp: 1; RequireReadOnly
OkHttp: P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
OkHttp: Date: Fri, 19 Feb 2016 21:52:23 GMT
OkHttp: OkHttp-Sent-Millis: 1455918749860
OkHttp: OkHttp-Received-Millis: 1455918752808
OkHttp: <-- END HTTP
```

The errorbody:

> {"error":{"code":"-1, System.NotSupportedException","message":"Specified method is not supported."}}

I have tested the same file with the same upload code and it works without issue to my personal normal OneDrive.

**Comment by acarlsen** [comment]
I tried the same request using normal HttpUrlConnection and there was no issue.

I then removed the ProgressRequestBody implementation I was using with OkHttp and replaced it with the standard, non-progress listening RequestBody, and it worked. I don't know why progress one doesn't work with OneDrive Business - I use the same ProgressRequestBody class with multiple other cloud providers and OneDrive personal...

So I got it working.. now just to see how I can track progress of the upload again...

**Comment by ificator** [comment]
Your upload session failed because `Content-Length` was not provided. Obviously the error message here sucked, so we'll track fixing that.

**Comment by acarlsen** [comment]
Thanks you seem to be right. I did set that, but it was removed for some reason, before being sent by OkHttp. Still strange it works with vanilla OneDrive, but it may not be as picky.

Thanks for your assistance.
