### ISSUE TITLE
Shared with Me (Business)

### ISSUE THREAD

**Issue by jmcrthrs** [OneDrive/onedrive-api-docs#304]
How can I retrieve a list of items that have been shared with me?

The following is from [https://dev.onedrive.com/misc/working-with-links.htm](https://dev.onedrive.com/misc/working-with-links.htm):

> "When a shared folder is added to OneDrive, the folder appears in the root..." 

> "When enumerating a collection of items, shared folders appear as
> items with the remoteItem facet."

It would appear the items in OneDrive's Shared with Me section should be returned with the following method:

`GET /drive/root/children`

However they aren't. 

Is there a separate endpoint for Shared items?

**Comment by rgregg** [comment]
Hi @jmcrthrs: The article you mentioned is about a feature of OneDrive Personal ("Add to OneDrive"). Currently the API does not provide a way to enumerated shared items, although we're working on it.

**Comment by rgregg** [comment]
This issue is tracked on our user voice page: https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7103641-allow-us-to-access-shared-files-on-sharepoint-and

**Comment by jmcrthrs** [comment]
Thanks @rgregg. That issue has been up since before the new OneDrive API was released.

Do you know if accessing the Shared with me items is currently on the roadmap?
