### ISSUE TITLE
Using Upload by SourceURL does not return status

### ISSUE THREAD

**Issue by BertCotton** [OneDrive/onedrive-api-docs#306]
https://dev.onedrive.com/items/upload_url.htm

Using this feature the response when checking the returned location does not return the progress.

I've been transferring large files (~100Mb) our of Amazon S3 into my OneDrive and they have been taking a while.  The "percentageComplete" is always 0.0

Response From Header Location:
`{"operation":"DownloadUrl","percentageComplete":0.0,"status":"inProgress"}.`

The documentation also says the the location URL will allow me to know when the file has finished uploading.  I have not seen the status go to a completed state, I just get a 404.

When uploading a file, it stays in the "notStarted" for a long time before proceeding. In one instance from 9:50 PM to 1035 PM MST for file id=6A1237F04038E20A%21457
`{"operation":"DownloadUrl","percentageComplete":0.0,"status":"notStarted"}`

**Comment by BertCotton** [comment]
Another thing that I have noticed is that item report as existing through the API before they show up through the web page.

I wonder if, similar to what is mentioned with using BITS-Packet-Type: Close-Session(https://gist.github.com/rgregg/37ba8929768a62131e85) if the connection needs to be closed so that the file is moved from the temp directory into my OneDrive.

**Comment by ificator** [comment]
@BertCotton I apologise for the delay - I didn't notice this land on me! Are you still seeing delays in downloading the URLs?
