### ISSUE TITLE
Discovery API returns a v2.0 endpoint with /me/ which is invalid

### ISSUE THREAD

**Issue by rgregg** [OneDrive/onedrive-api-docs#309]

**Comment by mikechiu1012** [comment]
hi @rgregg , 
I suffer the bug about onedrive for business discovery.
It will return empty value like:
<code>
discovery_response: {'value': [], '@odata.context': 'https://api.office.com/discovery/v1.0/me/$metadata#allServices'}
</code>

Even I change the API to 1.0 will get the same response.
Is this the same bug with this one and any update about this?
Thanks!

**Comment by mikechiu1012** [comment]
hi @rgregg,

I try the mac onedrive app to add account for onedrive for business, but I got error and failed.

Auth API also failed as I listed above, is there any update about this?

Thanks.

**Comment by rgregg** [comment]
@mikechiu1012: Can you e-mail me your OneDrive for Business username? My e-mail is rgregg -at- microsoft.com.

**Comment by mikechiu1012** [comment]
Hi @rgregg, 

Thanks for ur help, the root cause is my testing accounts were expired.

Here is a suggestion that auth flow could be blocked at the page of account probing or password confirm page to stop the auth flow continuous.

Thanks

**Comment by rgregg** [comment]
Thanks for the update. The empty array isn't very helpful in diagnosing what's going wrong, so it's something I'll add to our backlog.
