### ISSUE TITLE
Nothing happens when I click on "Open from OneDrive"

### ISSUE THREAD

**Issue by iiminov** [OneDrive/onedrive-api-docs#310]
I was trying to integrate [OneDrive file picker SDK for JavaScript](https://dev.onedrive.com/sdk/js-v6/js-picker-open.htm).

I have:
- registered my app with AAD and have my ClientID (tested with standalone web app)
- added SDK reference to my site (as instructed with attributes)
- added file picker launch script (as instructed)

Now when I click on the `Open from OneDrive` button my page seems to just refresh. No console errors, no popups, no notifications of popup getting blocked. Just a refresh.

Setting `openInNewWindow` to `false` has no effect.

I am obviously missing something fundamental here. Question is what could it be and what should be my course of action in troubleshooting this issue?

Any help or pointers is much appreciated.

**Comment by rgregg** [comment]
Would it be possible for you to share your code or a link to a page so we can take a look at what's going on?

**Comment by iiminov** [comment]
@rgregg
Would it be possible for you to share your code or a link to a page so we can take a look at what's going on?

Mm, you kind of put me on the spot here. I have it on my local dev server so I can't provide links to that. But let me see if I can set up a copy of it on our production sever and get a link to that.
