### ISSUE TITLE
Typo in Docs?

### ISSUE THREAD

**Issue by rayluo** [OneDrive/onedrive-api-docs#313]
1. Should [this line](https://github.com/OneDrive/onedrive-api-docs/blame/master/items/move.md#L41) mention `parentReference` rather than `parentInfo`?

2. A dozen key names [here](https://github.com/OneDrive/onedrive-api-docs/blame/master/odata/filtering.md#L101) lost their quotation marks.

**Comment by rgregg** [comment]
Thanks for reporting these @rayluo. I'll get them corrected.

**Comment by rayluo** [comment]
Not sure if this (and each) issue is by default waiting for the original poster's confirmation. I'll go ahead and close this issue anyway. Thanks for the quick fix @rgregg !
