### ISSUE TITLE
sharepoint: Access token with the GET list request is not working

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#314]
GET https://mdm05.sharepoint.com/sites/teama/_api/v2.0/drive/root/children

access token can be provided by 2 ways
1) url parameter (receiving 403 error, attaching fiddler snapshot)
2) As a header (receiving 401 error, attaching fiddler snapshot)

1st case: When trying with Fiddler
1) As URL parameter snapshot
![sharepoint_list_urlparameter](https://cloud.githubusercontent.com/assets/11455759/13567400/1a1df576-e481-11e5-9f1f-b7551ff13ff2.png)

2) As header snapshot
![sharepoint_list_header](https://cloud.githubusercontent.com/assets/11455759/13567402/1abba4f6-e481-11e5-95af-733f3679a860.png)

2nd case: When trying with Postman REST client
Successfully executing, i think it is due to cookies

Note: Access Token is been acquired by the process same as that of OneDrive Business.

Can you please look in to this, or performed some steps wrong?

We are starting to support office365 sharepoint support, can we start using this apis. Are they enough mature to be used for sharepoint?

**Comment by rgregg** [comment]
Using the access token query string is not supported with SharePoint. That method only works for OneDrive Personal.

When using the authorization header, it looks like your access token was granted for the wrong resource. You're using a token that has a resource of "mdm05-my.sharepoint.com" and trying to access a resource on "mdm05.sharepoint.com". You need to redeem the refresh token you received initially for a new access token valid for that resource.

**Comment by ankit-ankuagrawal** [comment]
@rgregg ty for pointing out the correction. It is working now.

[Few questions]
1) Are this apis are able to list subsites now?

2) We are starting to support office365 sharepoint support, can we start using this apis. Are they enough mature to be used for sharepoint?

**Comment by rgregg** [comment]
We're moving away from direct endpoints and converging our developer APIs via [Microsoft Graph](https://graph.microsoft.com). There is support for accessing SharePoint sites, lists, and files, via the beta version of Microsoft Graph today: https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/sharepoint
