### ISSUE TITLE
[Question] Sharepoint: Authentication Process

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#315]
For using Sharepoint (office365) the normal login procedure is through weblogin same as that of OneDrive Business. This is my basic understanding.

But there is one android app by name "SharePlus" used for sharepoint mostly, it provides various ways of authentication, such as
1) Windows based
2) Office365
3) Forms based
4) Web login

When selecting Office365 authentication it is not webbased, in this we have to provide username password and domain (attaching snapshot for the same).
![shareplus](https://cloud.githubusercontent.com/assets/11455759/13569246/e8aef434-e48c-11e5-8057-704f6ab41d3a.png)
Can you pls provide the details of this login (if any)?

**Comment by rgregg** [comment]
You'd have to ask the app developer what they're doing here.

The recommended and preferred way to log in to SharePoint Online / Office 365 is using the OAuth2 flow. AAD also supports the password flow which allows you to provide username/password directly without using web auth. However, using this method is considered insecure and not recommended for end user application.

Here's a blog post on using the password flow: http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/
