### ISSUE TITLE
Some questions and thoughts

### ISSUE THREAD

**Issue by rayluo** [OneDrive/onedrive-api-docs#317]
First of all, thanks for the great work on this docs! Using markdown on github is such a pleasant way to read and contribute to the docs.

I'm reading through the docs recently for my project. Here comes the summary of my questions and thoughts so far.
1. Question: Do we also need write permission for the original folder?
   https://github.com/OneDrive/onedrive-api-docs/blame/master/items/move.md#L9
2. Question: This API mentions using POST to upload a file from a URL (https://github.com/OneDrive/onedrive-api-docs/blob/master/items/upload_url.md). Can we also use PUT (similar to what's documented here: https://github.com/OneDrive/onedrive-api-docs/blob/master/items/create.md) to reach same effect?
   
   PS: For NO. 1 and No. 2 questions, I should be able to do some experiments to find out the answer by myself. I just haven't done that yet. But then I think if other new developers have same question, it is perhaps worthy to address it in the documentation in the first place.
3. Suggestion: These are different ways to create (and upload) an item, currently documented in following sections. Personally I would like to suggest to rename their section titles, in order to better communicate their purposes, therefore helping readers to choose.
   
   In https://github.com/OneDrive/onedrive-api-docs#item-resource
   - Suggest to change "Create an Item" to "Create a Folder Item"
   - Suggest to change "Upload an item's contents" to "Different ways to upload a File Item"
   
   The motivation of this change is that, the current titles give an impression that you need to first create an item and then upload content into it. Turns out that is not the case. The new suggested titles do not have such ambiguity.
   
   In https://github.com/OneDrive/onedrive-api-docs/blob/master/items/upload.md
   - "Simple Item Upload" -> "Upload a File item with its name and content"
   - "Resumable Item Upload" -> "Resumable Item Upload" (i.e. keeps its current name, but FWIW, this is sometimes known as "multipart upload" in other context, and that is also why I'd like to suggest to change the next description)
   - "Multipart Item Upload" -> "Upload a File item with its metadata and content". (Note: I know, under the hood, this API uses multipart content as an underlying transmit format, but still, feature-wise it is all about uploading the file in a single chunk. Hence my suggestion.)
4. Suggestion: This page (https://github.com/OneDrive/onedrive-api-docs/blob/master/items/upload_put.md) hints we can PUT to a `/drive/items/{parent-id}:/{filename}:/content` resource even before `/drive/items/{parent-id}:/{filename}` exists. This is a little bit conceptually unusual. So perhaps an extra mentioning would be helpful, such as "Yes, you can send PUT requests to this sub-resource endpoint `.../{filename}/content`, even when `.../{filename}` does not yet exist at that piont".
5. An open question. Currently share links can only be created by calling an action (https://github.com/OneDrive/onedrive-api-docs#sharing-and-permissions). Do we also consider providing a "POST /drive/items/{item-id}/permissions" to do the same thing? The new API will be more unified with the rest of RESTful (pun not intended) permission APIs.

**Comment by rinkp** [comment]
As for the last point I can tell that currently the POST method works to create a (or return an existing) link. ([https://github.com/OneDrive/onedrive-api-docs/blob/master/items/sharing_createLink.md](https://github.com/OneDrive/onedrive-api-docs/blob/master/items/sharing_createLink.md)) 
`POST /drive/items/{item-id}/action.createLink`
`POST /drive/root:/{item-path}:/action.createLink`

**Comment by ificator** [comment]
I apologize for the lack of response on these questions, however given how long ago it was I'm going to close this issue. If you desire answers to any of these please reactivate and specify the questions again.
