### ISSUE TITLE
/drives endpoint

### ISSUE THREAD

**Issue by Constantine-Fry** [OneDrive/onedrive-api-docs#32]
```
/drives	List Drives available to the authenticated user.
```

There is Drives endpoint which returns available drives for user. And I can't understand how to add second drive to my personal account to test it. Can user have several drives in his account? How can I add second drive to my account?

**Comment by ankit-ankuagrawal** [comment]
ty for asking the question...

In which scnerios multiple drive will be attached to one account???

pls elaborate

**Comment by rgregg** [comment]
There isn't a scenario that adds another drive to the drives collection today. This is here to future proof the API so that depending on how we evolve OneDrive in the future we can support scenarios where a user would have access to multiple drives, if such a scenario ever comes to exist.
