### ISSUE TITLE
Recieved 501 error while performing Close-Session

### ISSUE THREAD

**Issue by swhsiao** [OneDrive/onedrive-api-docs#320]
I received 501 Not Implemented error while performing close-session

It looks like the issue is file independent because the same file can be uploaded on another account.

The [detail log](https://github.com/OneDrive/onedrive-api-docs/files/171509/http.501.error.txt)

**Comment by swhsiao** [comment]
> BITS_POST /users/0x2922167cb05960cc/LiveFolders/BookShelf/price%209386_.ods HTTP/1.1
Host: cid-2922167cb05960cc.users.storage.live.com
Accept: */*
BITS-Packet-Type: Create-Session
BITS-Supported-Protocols: {7df0354d-249b-430f-820d-3d2a9bef4931}
Authorization: Bearer EwCIAq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAceivHKlUCCfxX3K1YHzaRGoy7TKcP3FoVYZocqRgeglPwJNd7bnQZ8dJTePgSPzH3S8A7vhuHXYDsne7zexJWHWm6jNMK7URPFjrEm1mccq6EPFTqwMovyyieoRuKQRUDeH7c5ihoESlByZNrihe/mITY5QgE7Tgdx0Msr5lTikofgvdF0xRZ6XXLZ59lqA6PsPwbpYwspocMZYV6uZuW0+yxVSbdvbnG7GqN2yj0o2GsWoiZWxOYdZtgZJrow0oVAmF4sh9quOITfLVziOzJ8YOEG/5nwTXFnfLO8fFE8lizxaRTJDt/489KxOswTn9D9vtnH0YrZVHDjRbOmoajADZgAACBSBHCNAhIWsWAEyzm0MQZEbXXEkmT1zbmGvtaXOuhYLISeNlZvtiFitZXzKb/51G2sUW4bRshgD3wzPyOE7/Scbib+8cGjPWPCOwJcuHDky/4zqmoIzvB+3wQOZric27FZD5KBCvFF9xxOCoKDftaDkTfkxQYm9r5B5JlQZndTXXN56an2m5ynsDBrYfubCBkR8hAiikOM5fr+E2ieRHQLMDFWcpduOqK15+kXp4EhWFjWo2lfiQXOcSWULNf3ceUqvcv1GV/OkmRpr83BrvqtemT4tb6UT5kK0Cvf6HUx8yhCH0+mFPOHiML4+01j1iGKzpy0nhaahqbzPijxvfeFKwhh53BuvB8XbvBIYLSPzkdaX/fbQjqV/WtuKa1zuOYhkK0/Bacdf6qgZFuaNqkIfx9gXUEDhaTbBykq41i9Ta6IcxLDzKoV9R/Hh+t+7mFPLSaVtgr8xfwuaFbssquD2vIcB

< HTTP/1.1 201 Created
< Content-Length: 0
< Server: Microsoft-HTTPAPI/2.0
< P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
< X-MSNSERVER: BL3302____PAP240
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< BITS-Packet-Type: Ack
< BITS-Protocol: {7df0354d-249b-430f-820d-3d2a9bef4931}
< BITS-Session-Id: 3mmkY-CHc8gWoGPgwkAAkKTwq2-_HSHIlgM_3EYYXH2rx6Ab3mi-uGBLFen-l_O_AD
< Accept-Encoding: Identity
< X-AsmVersion: UNKNOWN; 19.35.0.0
< Date: Thu, 10 Mar 2016 04:03:02 GMT

=================================================================================================

> BITS_POST /users/0x2922167cb05960cc/LiveFolders/BookShelf/price%209386_.ods HTTP/1.1
Host: cid-2922167cb05960cc.users.storage.live.com
Accept: */*
BITS-Packet-Type: Fragment
Content-Length: 12728
Content-Range: bytes 0-12727/12728
BITS-Session-Id: 3mmkY-CHc8gWoGPgwkAAkKTwq2-_HSHIlgM_3EYYXH2rx6Ab3mi-uGBLFen-l_O_AD
Authorization: Bearer EwCIAq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAceivHKlUCCfxX3K1YHzaRGoy7TKcP3FoVYZocqRgeglPwJNd7bnQZ8dJTePgSPzH3S8A7vhuHXYDsne7zexJWHWm6jNMK7URPFjrEm1mccq6EPFTqwMovyyieoRuKQRUDeH7c5ihoESlByZNrihe/mITY5QgE7Tgdx0Msr5lTikofgvdF0xRZ6XXLZ59lqA6PsPwbpYwspocMZYV6uZuW0+yxVSbdvbnG7GqN2yj0o2GsWoiZWxOYdZtgZJrow0oVAmF4sh9quOITfLVziOzJ8YOEG/5nwTXFnfLO8fFE8lizxaRTJDt/489KxOswTn9D9vtnH0YrZVHDjRbOmoajADZgAACBSBHCNAhIWsWAEyzm0MQZEbXXEkmT1zbmGvtaXOuhYLISeNlZvtiFitZXzKb/51G2sUW4bRshgD3wzPyOE7/Scbib+8cGjPWPCOwJcuHDky/4zqmoIzvB+3wQOZric27FZD5KBCvFF9xxOCoKDftaDkTfkxQYm9r5B5JlQZndTXXN56an2m5ynsDBrYfubCBkR8hAiikOM5fr+E2ieRHQLMDFWcpduOqK15+kXp4EhWFjWo2lfiQXOcSWULNf3ceUqvcv1GV/OkmRpr83BrvqtemT4tb6UT5kK0Cvf6HUx8yhCH0+mFPOHiML4+01j1iGKzpy0nhaahqbzPijxvfeFKwhh53BuvB8XbvBIYLSPzkdaX/fbQjqV/WtuKa1zuOYhkK0/Bacdf6qgZFuaNqkIfx9gXUEDhaTbBykq41i9Ta6IcxLDzKoV9R/Hh+t+7mFPLSaVtgr8xfwuaFbssquD2vIcB
Expect: 100-continue

< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Content-Length: 0
< Server: Microsoft-HTTPAPI/2.0
< P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
< X-MSNSERVER: BL3302____PAP240
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< BITS-Packet-Type: Ack
< BITS-Session-Id: 3mmkY-CHc8gWoGPgwkAAkKTwq2-_HSHIlgM_3EYYXH2rx6Ab3mi-uGBLFen-l_O_AD
< BITS-Received-Content-Range: 12728
< X-AsmVersion: UNKNOWN; 19.35.0.0
< Date: Thu, 10 Mar 2016 04:03:05 GMT

=================================================================================================

> BITS_POST /users/0x2922167cb05960cc/LiveFolders/BookShelf/price%209386_.ods HTTP/1.1
Host: cid-2922167cb05960cc.users.storage.live.com
Accept: */*
BITS-Packet-Type: Close-Session
Content-Length: 0
Authorization: Bearer EwCIAq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAceivHKlUCCfxX3K1YHzaRGoy7TKcP3FoVYZocqRgeglPwJNd7bnQZ8dJTePgSPzH3S8A7vhuHXYDsne7zexJWHWm6jNMK7URPFjrEm1mccq6EPFTqwMovyyieoRuKQRUDeH7c5ihoESlByZNrihe/mITY5QgE7Tgdx0Msr5lTikofgvdF0xRZ6XXLZ59lqA6PsPwbpYwspocMZYV6uZuW0+yxVSbdvbnG7GqN2yj0o2GsWoiZWxOYdZtgZJrow0oVAmF4sh9quOITfLVziOzJ8YOEG/5nwTXFnfLO8fFE8lizxaRTJDt/489KxOswTn9D9vtnH0YrZVHDjRbOmoajADZgAACBSBHCNAhIWsWAEyzm0MQZEbXXEkmT1zbmGvtaXOuhYLISeNlZvtiFitZXzKb/51G2sUW4bRshgD3wzPyOE7/Scbib+8cGjPWPCOwJcuHDky/4zqmoIzvB+3wQOZric27FZD5KBCvFF9xxOCoKDftaDkTfkxQYm9r5B5JlQZndTXXN56an2m5ynsDBrYfubCBkR8hAiikOM5fr+E2ieRHQLMDFWcpduOqK15+kXp4EhWFjWo2lfiQXOcSWULNf3ceUqvcv1GV/OkmRpr83BrvqtemT4tb6UT5kK0Cvf6HUx8yhCH0+mFPOHiML4+01j1iGKzpy0nhaahqbzPijxvfeFKwhh53BuvB8XbvBIYLSPzkdaX/fbQjqV/WtuKa1zuOYhkK0/Bacdf6qgZFuaNqkIfx9gXUEDhaTbBykq41i9Ta6IcxLDzKoV9R/Hh+t+7mFPLSaVtgr8xfwuaFbssquD2vIcB
BITS-Session-Id: 3mmkY-CHc8gWoGPgwkAAkKTwq2-_HSHIlgM_3EYYXH2rx6Ab3mi-uGBLFen-l_O_AD
Expect: 100-continue

**< HTTP/1.1 501 Not Implemented**
< Content-Length: 02
< Server: Microsoft-HTTPAPI/2.0
< P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
< X-MSNSERVER: BL3302____PAP240
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< BITS-Packet-Type: Ack
< BITS-Error-Code: 800300fe
< BITS-Error-Context: 0x5
< X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
< X-ThrowSite: 2c0b.31f8
< X-ClientErrorCode: SyncGhostItemProxyNeeded
< X-AsmVersion: UNKNOWN; 19.35.0.0
< Date: Thu, 10 Mar 2016 04:03:05 GMT

**Comment by ificator** [comment]
I'd suggest switching to the new OneDrive API for [uploading of large files](https://github.com/OneDrive/onedrive-api-docs/blob/master/items/upload_large_files.md) as this repository deals solely with it.

However, if I had to guess it looks like you're trying to upload a file into a mounted folder, which is not technically allowed. The current recommendation is to upload directly to the shared folder (i.e. the target of the mounted folder) for these kinds of scenarios.

**Comment by swhsiao** [comment]
@ificator Thanks for your advice .
