### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#321]
In our product, it always popup below error message when I open file picker dialog. It also happens on the demonstration server(http://isdk.dev.live.com/dev/isdk/Default.aspx).

Do we have any ideas about this?

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://onedrive.live.com') does not match the recipient window's origin ('http://isdk.dev.live.com').

**Comment by daboxu** [comment]
Hi @benjaminliugang, try the new version of file picker: https://dev.onedrive.com/sdk/js-v6/js-picker-overview.htm

**Comment by benjaminliugang** [comment]
@daboxu , Thanks for your quick response! I will try it in our product and then give you result.

**Comment by benjaminliugang** [comment]
Hi @daboxu, do we support locals with the latest version(6.0)?
If we support how can I get all of the locals library?

**Comment by benjaminliugang** [comment]
Hi @daboxu, BTW, when I try to use v6.0, it always popup below error, it seems I need to pass client id when I import the library, but I don't know how to pass the value when I try to use requirejs to import this library.
Actually, for v5.0, I just pass the client id when init oneDrive.
So, do you have any ideas about it?

require_config.ts:5 Error: [OneDriveSDK Error] SDK script tag missing 'onedrive-js' id

**Comment by daboxu** [comment]
You just need to reference the js file in your working webpage like this
    
    <script type="text/javascript" src="https://js.live.net/v6.0/OneDrive.js" id="onedrive-js" client-id="APP_ID"></script>

Because you missing the id attribute so it throws error. Please see the page:
https://dev.onedrive.com/sdk/js-v6/js-picker-open.htm
https://dev.onedrive.com/sdk/js-v6/js-picker-save.htm
for detail.
