### ISSUE TITLE
Download response give an invalid location which will give 403 access denied

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#322]
Hi, 

I tried to download my files from my onedrive account, but some of them are always return 403 error. 

These files are not shared files and they can download from website.

Here are responses I receviecd. Any suggestion of this?

```
"GET /v1.0/drive/root:/Documenti/Nas%20e%20Cloud%20Hubic/Vecchie%20cose%20di%20Lavoro%20di%20Pippo/2MG/2MG.rar?select=id%2Cname%2Csize%2CfileSystemInfo%2CeTag%2Cfile%2Cfolder%2Cdeleted%2CparentReference%2ClastModifiedDateTime HTTP/1.1" 200 759
"GET /v1.0/drive/root:/Documenti/Nas%20e%20Cloud%20Hubic/Vecchie%20cose%20di%20Lavoro%20di%20Pippo/2MG/2MG.rar:/content HTTP/1.1" 302 0
"GET /y3m_6VB0sH9TpMy7KDpvAirNqSrDk7QY09rWrTG1Cdt7XxbutdaeTLQ7Vn9fLqzvMj9CcnuDEXhzq9_YyYz-voJSFRgoWbeNOeEBoOkEFa2pznTWTJAvtnI26UgV0mTHQYbt4BAjC5LZESRBHkI42V9WknbBj_3b6hXypO60oWCPX2089RBV0C0bgnELRMB24mBAFwbNeCazyF9Cqca1W4jS6exQARehs1VDrKgRM9lM-c/2MG.rar HTTP/1.1" 403 0
ERROR:403 Client Error: Forbidden
```

**Comment by verybada** [comment]
Hi,

I found it will happen on .zip file those involved other .zip. If i'd like to download this kind of file form web, the web will give alert about "can't analysis this file ... are your sure to download ", then I need to click OK to start my session. But, from API, how should I do?

**Comment by saguiitay** [comment]
https://github.com/OneDrive/onedrive-api-docs/issues/178#issuecomment-178472620

**Comment by verybada** [comment]
Thanks for help. It works after add "AVOverride".

**Comment by ificator** [comment]
I've updated #178 with a status update, and I'm going to close this issue since it's technically a duplicate.
