### ISSUE TITLE
Request to support an OData $skip option to support virtual data lists on clients

### ISSUE THREAD

**Issue by ginach** [OneDrive/onedrive-api-docs#324]
Reported by @ericleigh007, copied from [here](https://github.com/OneDrive/onedrive-sdk-csharp/issues/43).

Though the current server paging capability can support an incremental loading capability, this doesn't support at all the case of user quickly scrolling through their photos or data in a virtual list, because scrolling can be done so quickly that any incremental loading queue can get saturated. 

Random access data virtualization is what is required to support the quick scrolling scenario. Unfortunately, it looks as if the SDK and the OneDrive API don't support the OData query options (namely $skip) which would enable that.

Hopefully $skip is in the near range plan, so that we'll be able to create awesome third party apps that use the OneDrive API.
 The concepts I'm describing can be found here:
https://msdn.microsoft.com/en-us/library/windows/apps/mt574120.aspx

To illustrate, let's say that a list or grid is used to show picture thumbnails. We start with a query to get the camera roll by date descending, but we only get just a few of the thousands of pictures' metadata with the first call. In fact, to remain responsive, we may want the call to get even fewer than 100 items.

```
https://api.onedrive.com/v1.0/drives('me')/items('cameraroll_id')/children?$top=100&$orderby=lastModifiedDateTime%20desc
```

Now the user scrolls very quickly to item 200, but we're still loading the previous items into the control. This might be reported to the app by the  IItemsRangeInfo  interface for a list and overriding the  RangesChanged  method..

What we need is this:

```
https://api.onedrive.com/v1.0/drives('me')/items('cameraroll_id')/children?$top=100&$orderby=lastModifiedDateTime%20desc&skip=200
```

If there is a way to enable this scenario, please let me know.
 -THANKS
 -e

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
