### ISSUE TITLE
File picker pop up shows the web site(when redirect) all the time instead showing the onedrive to pick files

### ISSUE THREAD

**Issue by rohitha123** [OneDrive/onedrive-api-docs#326]
My one is a SPA which is created using angular. when a user click on button to open a the onedrive its loading login page and after authentication happens success then it redirect to my own site within the pop up itself and it remain until close the window instead showing onedrive picker to choose files.

This does not happens when I hardcode the javascript file as below.
`<script type="text/javascript" src="https://js.live.net/v6.0/OneDrive.js" id="onedrive-js" client-id="4eg142a...xxxxxx"></script>`

But the issue is that I can't hardcode the client id all the time because same code using for multiple sites and each site has different client_id. So I do want to load this dynamically. (through ajax request)

Please help me. Thanks in advance

**Comment by daboxu** [comment]
Hi @rohitha123 , the redirect process is by design. For your problem, I think you can use a separate url for the picker and communicate between the picker and your app with postmessage. :)

**Comment by Welle7DevReader** [comment]
@rohitha123 Did you manage to find a solution for this issue?

**Comment by bjoernbur** [comment]
@rohitha123 Did you manage to find a solution for this issue? I have exactly the same problem. Thanks.

**Comment by rgregg** [comment]
@rohitha123 You could also upgrade to the v7 SDK, which changes how you pass in the application ID to be a parameter in the options instead of as part of the script tag. This would give you the ability to include the script tag without hardcoding the application ID.
