### ISSUE TITLE
Search wildcards - all items in and under a folder

### ISSUE THREAD

**Issue by martinlaukkanen** [OneDrive/onedrive-api-docs#328]
Hi,

I'm trying to do some item reporting and the documentation is not clear on the syntax of wildcard usage (it's not mentioned actually) I basically want to do the following:

https://api.onedrive.com/v1.0/drive/root/view.search?q=*

However this (weirdly) returns a result set containing "asterix" in the name?? Is that intentional or am I just going mad?

Thanks,

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
