### ISSUE TITLE
why access_token valid even after changing the password

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#33]
did the following steps:

1) got the new access_token and refresh_token
2) query using the obtained access token
*** 3) now changed the password of the account
4) still can query using the old access token(step 1)

why still old access token valid??? it should not be valid once password changed otherwise for 1 hr it is vulnerable 

continued with the steps
5) tried to get new access token and refresh token using the old refresh_token obtained from step 1

got the following response 
{"error":"invalid_grant","error_description":"The user could not be authenticated or the grant is expired. The user must first sign in and if needed grant the client application access to the requested scope."}

6) even after getting the above error ,still can query using the access_token(step 1)

why so access_token is valid after changing password also and getting error for demanding new access_token(step 5)???

**Comment by rgregg** [comment]
Access tokens are like short-lived passwords. Once a token is generated, it is valid for the 1 hour period regardless of what changes are made to the account. There isn't a mechanism that revokes or disables the access token other that it timing out.

Changing the user's password invalidates the refresh token and requires that the user sign-in again to get a new refresh token, but access tokens are not invalidated.

**Comment by ankit-ankuagrawal** [comment]
Asking the following question, because was unable to check this scenario... 
what happened in the case of logout will access_token will be valid or it will become invalid???

**Comment by jscaria** [comment]
Per @rgregg 
> Access tokens are like short-lived passwords. Once a token is generated, it is valid for the 1 hour period regardless of what changes are made to the account. There isn't a mechanism that revokes or disables the access token other that it timing out.

@ankit-ankuagrawal If you log the user out, the access_token is still valid until it expires (3600 seconds after issue)

**Comment by rgregg** [comment]
Closing this issue down, since I believe we've explained how access tokens work.
