### ISSUE TITLE
upload.createSession fails with 404 for special folders

### ISSUE THREAD

**Issue by bdares** [OneDrive/onedrive-api-docs#330]
Making a POST request to the endpoint:
`/drive/special/approot:/newfile.txt:/upload.createSession`
fails with the following response:

Status: 404
Body:

```
{
  "error": {
    "code": "itemNotFound",
    "message": "The resource could not be found."
  }
}
```

This is the v2.0 endpoint for OneDrive for Business, and I get the same response for all of the special folders.  

`HEAD /drive/special/approot` gives the expected response.  

This appears to be similar to https://github.com/OneDrive/onedrive-api-docs/issues/67

**Comment by Livven** [comment]
This also applies to uploading with [`@content.sourceUrl`](https://dev.onedrive.com/items/upload_url.htm). Uploading a file from a URL to the app folder (`POST drive/special/approot/children`) fails with a 404 error if the folder doesn't already exist.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
