### ISSUE TITLE
shared with me: createdDateTime / lastModifiedDateTime is not of ISO 8601 std

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#331]
Requested shared with me files folder using https://github.com/OneDrive/onedrive-api-docs/blob/master/drives/shared_with_me.md

received the response but something wrong with createdDateTime or lastModifiedDateTime there are not with the std ISO 8601 format (example posted here https://github.com/OneDrive/onedrive-api-docs/blob/master/facets/timestamp.md) because java date api is throwing exception for it,  and also 2 different files have same createdDateTime, though there where created at different time

following is the response 
![shread with me response](https://cloud.githubusercontent.com/assets/11455759/14213173/29fc7ddc-f854-11e5-8d76-ee1a9b277ed1.png)

**Comment by ificator** [comment]
Can you share the exception Java is throwing?

The value for `createdDateTime` looks to be technically valid from an ISO8601 perspective, but it's definitely not an expected value.

**Comment by ankit-ankuagrawal** [comment]
@ificator i may be wrong with ISO8601 std, but we where expecting value in the following format
1) yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
2) yyyy-MM-dd'T'HH:mm:ss'Z'

In general the java is throwing following exception
aused by: Unparseable date: "0001-01-01T00:00:00-08:00" (at offset 19)
                                                                                               at java.text.DateFormat.parse(DateFormat.java:622)

**Comment by peternied** [comment]
I would recommend looking at the [CalendarSerializer](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/serializer/CalendarSerializer.java) which is part of our Android SDK.  Otherwise I'd recommend picking up [Joda-Time](http://www.joda.org/joda-time/) library which has a full featured parsing system.

**Comment by ankit-ankuagrawal** [comment]
@peternied we are not using the android SDK. Will be looking in yo joda-time library. 
Thanking for suggestion.

**Comment by ificator** [comment]
The `Z` in the timestamps is just an indication that the value is in UTC. It's also perfectly legal to write a value like `2016-04-01T07:00:00+00:00` and `2016-04-01T00:00:00-07:00` - they're both equivalent to '2016-04-01T07:00:00Z`.

Unfortunately getting access to the actual ISO8601 specification isn't trivial, however you can have a look at RFC3339 for the profile that is recommended for use "on the Internet". Specifically [this section](http://tools.ietf.org/html/rfc3339#section-5.6) describes the ABNF for the allowed formats.

**Comment by ankit-ankuagrawal** [comment]
@ificator they may be valid, but exception is thrown due to which code is getting broke.
Will the value will be cming in this format only 2016-04-01T00:00:00-07:00 or it will be going to change to what we get normally

**Comment by ificator** [comment]
In this case we'll be fixing it to make sure it's a valid UTC timestamp and so it should align with the documentation (which states we'll always return UTC). My previous comment was more for educational purposes than anything else :)

**Comment by ificator** [comment]
We should now be returning UTC timestamps so I'm going to close this issue. Please reactivate if you're still seeing issues.
