### ISSUE TITLE
How to get recent files using android SDK

### ISSUE THREAD

**Issue by ishratkhan** [OneDrive/onedrive-api-docs#332]
I can see in docs , I must use **GET /drive/view.recent ** to get recent files but, i am using onedrive sdk 

> compile ('com.onedrive.sdk:onedrive-sdk-android:1.1+') {
>         transitive = false
>     } 

I am not getting any way to manually call **GET /drive/view.recent ** or any inbuilt method,

**how to get recent files .**

Thank you

**Comment by rgregg** [comment]
Hi @ishratkhan Can you open this as an issue on the Android SDK project instead? I believe the issue is that the SDK needs to be updated to support these newly released capabilities.

**Comment by ishratkhan** [comment]
I thought SDK is supporting such basic features and docs are missing for recent files, that's why i open issue here,

I have opened issue in Android SDK project.

thank you
