### ISSUE TITLE
After click open button from file picker, nothing will happens, just open button disabled

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#336]
After click open button from file picker, nothing will happens, just open button disabled

My library is http://js.live.net/v5.0/wl.js, and the log in console is:
```
Picker on inited
The picker process has completed.
```

If open successfully, it should be follow a `'[WL]onPickerComplete'` log.

I cannot find the root cause, anyone can help me to check this issue?

BTW, it works well for a long time, it's just happened in these days. I think it's caused by `wl.skydrivepicker.js` change.

**Comment by benjaminliugang** [comment]
I found if I invoke WL.getSession() after login and then invoke WL.fileDialog, this issue will always happen.

**Comment by rgregg** [comment]
@daboxu Can you see what might be going on here?

@benjaminliugang The v5.0 picker is pretty old now. Is it possible your site can update to the v6 or v7 picker experience, which enables OneDrive and OneDrive for Business support and a more modern and robust SDK?

**Comment by benjaminliugang** [comment]
Thank you @rgregg, I will try to upgrade oneDrive to latest version for our product. But for our old release  versions, we still need to fix this issue with the old oneDrive(v5.0).

BTW, If I use v7.0, how to support locals? Do we have some references?

**Comment by benjaminliugang** [comment]
One reproduce step update: I just use `WL.fileDialog` to open popup dialog not `OneDrive.open` function.

**Comment by benjaminliugang** [comment]
Hi @daboxu, do you have any ideas about these issues?

**Comment by daboxu** [comment]
Hi @benjaminliugang , do you have a fiddler trace for your call? I cannot figure out the root cause based on the context. If you have an online demo app for testing, that will be better.

For the v7.0, we do not show the user account information dialog anymore, probably what you want is making request to (GraphAPI)[http://graph.microsoft.io/en-us/docs] via  https://graph.microsoft.com/v1.0/me to get these information back.

We move the documentation to https://dev.onedrive.com/sdk/js-v7/js-picker-overview.htm for better user experience.

@rgregg I think we support locale according to users' setting right?

**Comment by benjaminliugang** [comment]
Hi @rgregg , today I cannot reproduce the open button disabled issue. Actually, we didn't made any change about oneDrive in our product. Is there any change about it in your part?
Since this issue cannot reproduce in our product, we still use the live SDK(https://msdn.microsoft.com/en-us/library/hh243643.aspx) in our product. So I just want to confirm, is your team always support these apis(WL.init, WL.login, WL.fileDialog ...)?

**Comment by rgregg** [comment]
The Live SDK and the Live Connect API are still supported, but we discourage their usage. Already some scenarios relating to parts of the Live SDK are no longer functional, like access to mail, calendar, and contacts, for some users. We expect to deprecate the whole Live SDK in the future. I'd recommend finding time to migrate to the new onedrive.js in the near future.

**Comment by benjaminliugang** [comment]
Thanks @rgregg , we will do it in our future. Already add the upgrade task in our backlog.
