### ISSUE TITLE
Simple Upload API started failing on 10th April 2016

### ISSUE THREAD

**Issue by elangomca** [OneDrive/onedrive-api-docs#339]
I am using the one drive simple upload API to upload file to one drive business based on the following documentation (https://dev.onedrive.com/items/upload_put.htm)

PUT https://graph.microsoft.com/v1.0/me/drive/items/root/children/732f64cc-0719-4a24-abe8-6fd39cb96403.txt/content?%40name.conflictBehavior=replace 

But this request fails with the following error message, This was working until 8th April 2016 
{
    "error": {
        "code": "BadRequest",
        "message": "Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.",
        "innerError": {
            "request-id": "7e734f93-3033-4bb4-a433-c5d9c400f46e",
            "date": "2016-04-11T02:33:35"
        }
    }
}

All our file upload tests started failing because of this. The documentation says content-type as text/plain but error message is asking us to send data as JSON

**Comment by marych** [comment]
There was an issue with a new build that was rolled out over the weekend, and we have now reverted it. The issue should now be resolved.
