### ISSUE TITLE
Add an optional window name in the file picker option

### ISSUE THREAD

**Issue by dfournier** [OneDrive/onedrive-api-docs#340]
Hi,

When the window popup is created, you pass `_blank` as window name. Is it possible to add an optional configuration in the file picker options to customize it?

**Comment by rgregg** [comment]
@dfournier Can you give us more details about how you would use this?

**Comment by daboxu** [comment]
Hi @dfournier , due to need for IE browser compatibility and our workflow, it could not be customized at right now. Is this something blocking you?

**Comment by dfournier** [comment]
Thanks for your replies.

We use it to identify which window should be considered as internal (like OneDrive file picker) or external (a link pointing out of our application). This is useful for an application based on Electron. Electron provides a hook (documentation [here](http://electron.atom.io/docs/v0.37.5/api/web-contents/#event-new-window)) and in my opinion, using `frameName` to identify internal/external windows is the best solution.

**Comment by daboxu** [comment]
Thanks @dfournier, right now it seems we have conflicts with the Electron framework, thanks for pointing out that and we will work on avoiding the '_blank' trick.

**Comment by dfournier** [comment]
@daboxu I planned to find out why the file picker doesn't work with Electron... Should I open another issue about Electron and keep this one about the frame name option?

**Comment by dfournier** [comment]
@daboxu I agree `frameName` is an enhancement, it's a nice to have thing. But the problem Electron is much more critical for us, that's why I opened #350. I hope to see it tagged as bug and see it fixed to enjoy the integration in our desktop application 😄

**Comment by daboxu** [comment]
Worked with @dfournier and he found a work around for now. :)
