### ISSUE TITLE
File picker load files failed

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#341]
OneDrive file picker always load files failed after the first time opened, please check the screencast(https://onedrive.live.com/redir?resid=2E4ED184A28C5BD!203&authkey=!ADvuvOIMpRYguyc&ithint=video%2cmp4). And it only happens for my one account, it cannot reproduce in other accounts.

You could try with my account to reproduce this issue in the sample code(http://isdk.dev.live.com/dev/isdk/ISDK.aspx?category=scenarioGroup_skyDrive&index=0):
UserName: liugangyanxing@163.com
Password: _REMOVED_

**Comment by ificator** [comment]
FYI: I've removed the password.

We'll follow up for details if we need them.
