### ISSUE TITLE
Large File Upload fragment response includes null value for "uploadUrl"

### ISSUE THREAD

**Issue by bdares** [OneDrive/onedrive-api-docs#342]
The upload itself is behaving as expected, but every time I upload a fragment, the response looks something like this:

```
{
  "@odata.context": "https://my-sharepoint-here.com/_api/v2.0/$metadata#oneDrive.uploadSession",
  "expirationDateTime": "2016-04-12T22:41:55.9162251Z",
  "nextExpectedRanges": [
    "4453-4999"
  ],
  "uploadUrl": null
}
```

Docs suggest that the field shouldn't even be present, and I'm not depending on it, but it still looks like an oversight.

**Comment by ificator** [comment]
This issue should now be resolved - please let us know if you still see problems.
