### ISSUE TITLE
What is the limitation of large file size @upload @ODB

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#344]
I use the resume upload request to upload large file 10GB

But when i going to commit the upload session

it returns 

```
http code (500), 
error message (An unspecified error has occurred.), 
error code (generalException)
```

But I succeed with smaller file (9GB and 8GB)
And document seems not to mention this restriction about the largest file size
https://dev.onedrive.com/items/upload_large_files.htm

And how about the file size restriction  @ODP 

thank you for help!

**Comment by rgregg** [comment]
Limits for OneDrive for Business are documented here: https://support.microsoft.com/en-us/help/3125202/restrictions-and-limitations-when-you-sync-files-and-folders-using-the-new-onedrive-for-business-sync-client
