### ISSUE TITLE
ODP Enumerate the contents of a shared folder API is not the same like document.

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#346]
Hi,

I am trying to porting shared folder behaviour and I read document from: https://dev.onedrive.com/misc/working-with-links.htm

API need to indicate drive-id as prefix to retrieve children under other drive.
But when I use the Console(APIGEE) of your own, this will failed

<pre>
https://api.onedrive.com/v1.0/drive/a174a883faed7af/items/A174A883FAED7AFA!113845/children
HTTP/1.1 400 Bad Request
X-QosStats:
{"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
Strict-Transport-Security:
max-age=31536000; includeSubDomains
X-MSNSERVER:
BL3301____PAP031
Date:
Thu, 14 Apr 2016 07:54:32 GMT
X-ThrowSite:
5b44.8246
P3P:
CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Content-Length:
71
X-AsmVersion:
UNKNOWN; 19.37.0.0
Connection:
keep-alive
Content-Type:
application/json
Server:
Microsoft-HTTPAPI/2.0

{
  "error":  {
    "code": "invalidRequest",
    "message": "Invalid API or resource"
  }
}
</pre>

But if i remove the drive-id, it will work fine.
I wonder if this is a bug or document without updated cause this will affect the implementation if the api format could not be sure.

Thanks.

**Comment by ificator** [comment]
The issue here was the use of `drive` instead of `drives` when providing the `drive-id` value. The URL should have been:

> https://api.onedrive.com/v1.0/drives/a174a883faed7af/items/A174A883FAED7AFA!113845/children

Obviously such a comment after such a long time isn't entirely useful so I hope you managed to resolve the issue on your own!
