### ISSUE TITLE
500 with "Share Link" in JS SDK v7

### ISSUE THREAD

**Issue by antoinelyset** [OneDrive/onedrive-api-docs#347]
Hi,

We are currently experiencing a bug with JS SDK v7 : 

- Go https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm
- Select "Share Link"
- Click "Open from OneDrive"
- Use a "Not-Business" OneDrive account, you can create one here : https://signup.live.com/
- Select a file
- Click "Open"
- It crashes with 500

Hope you will be able to reproduce. (Do not hesitate to ask)

Best,

— Antoine

**Comment by antoinelyset** [comment]
Up ! This is kind of critical I think.

**Comment by daboxu** [comment]
@antoinelyset thanks, confirmed it is a known issue. I will let you know when it is fixed.

**Comment by antoinelyset** [comment]
Up ! Any more news ?

**Comment by prenaudin** [comment]
For further informations, there is no more 500 Server error but a 
`OneDrive.7-0-rc.js:2 Uncaught TypeError: Cannot read property 'webUrl' of undefined`
which seems like a JavaScript unparsing error.

Here is a screenshot taken on https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm with a "Not-Business" OneDrive account.
<img width="879" alt="screen shot 2016-04-26 at 16 57 16" src="https://cloud.githubusercontent.com/assets/887094/14822772/3198e6b8-0bd0-11e6-943e-6c8816edafde.png">

Please let me know if you need more informations.

**Comment by antoinelyset** [comment]
It now works. Thanks OneDrive's team.
