### ISSUE TITLE
What is the block extension of ODB and ODP

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#348]
In case I can not  upload some extensions of files @ODB like 

```
*.jar *.aspx 
```

But it works fine @ODP.
so I want to know what is the **full block table** @ODB and ODP

I only find out this documentation
https://support.microsoft.com/en-us/kb/2933738
But it only show 'You can't upload files that have the following extensions:'

```
*.tmp*.ds_store
```

thank you for help!

**Comment by joewutaiwan** [comment]
two more blocked extensions
```
*.master *.ascx
```

**Comment by ificator** [comment]
Hi @joewutaiwan I apologize for the delay - do you still see issues uploading files with these extensions? We've made some fixes in the past to avoid extension based issues.

**Comment by joewutaiwan** [comment]
Hi @ificator 
Thanks for reply,

Now I can successfully upload the following file extensions:
All of that was failed to upload before.
```
"ds_store", "htc", "swf", "jar", "aspx", "master", "ascx", "xap"
```
Except for this:
```
"asmx",
```

**Comment by ificator** [comment]
Thanks, I'll check in to `asmx` and see if there's something we can do.

**Comment by joewutaiwan** [comment]
Hi, @ificator 

I found another file name failed to upload
```
permissions
```
Would you please  to check this.

Thanks

**Comment by ificator** [comment]
Hi @joewutaiwan could you provide the `SPRequestGuid` and `Date` headers for the failure responses for the `asmx` and `permissions` failures? I wasn't able to repro the issue on my test environments.

**Comment by joewutaiwan** [comment]
Hi @ificator 

for permissions
```
{
    "error": {
        "code": "invalidRequest",
        "message": "The request is malformed or incorrect."
    }
}
access-control-allow-origin →*
access-control-expose-headers →SPRequestGuid, X-MoveState
access-control-max-age →2592000
cache-control →private, max-age=0
content-type →application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
date →Mon, 22 Jan 2018 07:29:48 GMT
expires →Sun, 07 Jan 2018 07:29:49 GMT
last-modified →Mon, 22 Jan 2018 07:29:49 GMT
microsoftsharepointteamservices →16.0.0.7310
ms-cv →nkLvLHtwAFDOD4jO3NeP7A.0
odata-version →4.0
p3p →CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
request-id →2cef429e-707b-5000-ce0f-88cedcd78fec
spclientservicerequestduration →79
sprequestduration →145
sprequestguid →2cef429e-707b-5000-ce0f-88cedcd78fec
status →400
strict-transport-security →max-age=31536000
x-aspnet-version →4.0.30319
x-content-type-options →nosniff
x-frame-options →SAMEORIGIN
x-ms-invokeapp →1; RequireReadOnly
x-msedge-ref →Ref A: B3F3442C4FE64CE4835774644455E90F Ref B: HK2EDGE0312 Ref C: 2018-01-22T07:29:49Z
x-powered-by →ASP.NET
x-sharepointhealthscore →4
x-sp-serverstate →ReadOnly=0
```

for permissions.asmx
```
content-length →0
date →Mon, 22 Jan 2018 07:30:58 GMT
microsoftsharepointteamservices →16.0.0.7310
ms-cv →nkLvPWegAFB4TsaourdpNQ.0
p3p →CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
request-id →3def429e-a067-5000-784e-c6a8bab76935
spiislatency →4
sprequestduration →129
sprequestguid →3def429e-a067-5000-784e-c6a8bab76935
status →404
strict-transport-security →max-age=31536000
x-content-type-options →nosniff
x-frame-options →SAMEORIGIN
x-ms-invokeapp →1; RequireReadOnly
x-msedge-ref →Ref A: 2B980C020BE445A1B08577BABF7F6FCD Ref B: HK2EDGE0312 Ref C: 2018-01-22T07:30:58Z
x-powered-by →ASP.NET
x-sharepointhealthscore →4
```

Thanks

Joe
=)

**Comment by ificator** [comment]
Hi @joewutaiwan.

I can repro now! It looks like it's an issue with `/children/permissions` specifically. You should be able to work around it using the colon notation (e.g. `/drive/root:/permissions:/content`). The same work around seems to help `permissions.asmx`, but the issue there is deeper in the stack and will be harder to resolve. The work around may become a recomendation for that specific scenario.

**Comment by ificator** [comment]
Hi @joewutaiwan, we looked into this a little more and while it's definitely a bug in our code it's rather non-trivial to fix. We have other changes coming down the pipeline that will resolve it but they're a while off.

In that light I'm going to say we aren't going to fix this, and the work arounds are:
1. Use the "colon path" syntax (e.g. `/drive/root:/permissions:/content`)
2. Use the parameterized syntax (e.g. `/drive/root/children('permissions')/content`)

I personally just use the "colon path" syntax whenever I need to refer to anything by path/name.

**Comment by joewutaiwan** [comment]
Hi @ificator 
Thanks for investigation.
