### ISSUE TITLE
Upload failed with some urlencode string

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#349]
I upload a file with name like ''峎党弝隙溫"
and urlencode it as 

```
%E5%B3%8E%E5%85%9A%E5%BC%9D%EF%9B%85%E9%9A%99%E6%BA%AB
```

however it failed to upload
the problem is server could not accept this encoded string

```
%EF%9B%85
```

But I think it had been encode properly

how can I solve this issue?

Really thank you for help...

**Comment by ificator** [comment]
Unfortunately you aren't doing anything wrong.

%EF%9B%85 = U+F6C5, which falls in the Private-Use Area that is not fully supported. The issue resides in how the incoming URLs are validated, and we're working towards resolution. However to ensure a consistent experience filenames that contains these characters will also be blocked from being provided in request bodies.

Your best hope at the moment is that the character in question has an equivalent codepoint assigned in Unicode that you can use instead (e.g. if this character is from GB18030 then the equivalent would be U+96E0).

**Comment by rgregg** [comment]
@joewutaiwan: Do you have more information on the number of users impacted / total customers your app is addressing?

**Comment by ificator** [comment]
@daspek posted a relevant update to a similar issue: https://github.com/OneDrive/onedrive-api-docs/issues/400

I'll quote here for simplicity:
> Just wanted to provide an update here. The HTTP.SYS team has taken the fix, but because it's in such a deep component, it's not something we're able to patch in the near term. However, we will have the fix in a future upgrade.
