### ISSUE TITLE
Facing problem with logout

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#35]
did the following steps for logout
1) GET "https://login.live.com/oauth20_logout.srf?client_id=000000004813EF9B&redirect_uri="

response received -> "https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+request+must+include+a+'redirect_uri'+input+parameter."

        Q1) why "redirect_uri" query parameter value is being demanded???

**Comment by ankit-ankuagrawal** [comment]
continue...

On one of the github page it is been quoted(https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/msa_oauth.md)
"The redirect URL that the browser is sent to when authentication is complete. This must match exactly the redirect_uri value used in the get token request."

To acquire the access token, i always keep "redirect_uri" query parameter value empty, following is the query
GET "https://login.live.com/oauth20_authorize.srf?client_id=000000004813EF9B&scope=wl.signin+wl.contacts_skydrive&response_type=code&redirect_uri="

in the above scnerio, successfully receives the "access_token", without specifying the value for redirect_uri

**Comment by rgregg** [comment]
It should be required in the login flow as well, but it looks like there is a bug there. For desktop and mobile applications (or anything that isn't a web application) you can use `https://login.live.com/oauth20_desktop.srf` as the redirect_uri. If you don't specify a redirect URI on the logon flow, it will default to the first URL defined in your application configuration.

**Comment by ankit-ankuagrawal** [comment]
pls refer the snapshots 
![1 request uri to get code](https://cloud.githubusercontent.com/assets/11455759/6716538/3a6c3922-cdcc-11e4-8634-edf0446cb902.png)
![Uploading 2 response for code.png . . .]()

![3 request to get access_token](https://cloud.githubusercontent.com/assets/11455759/6716540/3bb6cb4e-cdcc-11e4-896d-a1c33082c7bb.png)
![Uploading 4 response for access_token.png . . .]()
![Uploading default redirect_uri.png . . .]()

**Comment by ankit-ankuagrawal** [comment]
pls refer the following snapshots
![1 request uri to get code](https://cloud.githubusercontent.com/assets/11455759/6716755/82d0b8f4-cdcd-11e4-8064-d743693042df.png)
![2 response for code](https://cloud.githubusercontent.com/assets/11455759/6716759/837a3956-cdcd-11e4-90ef-b66aa6d3148a.png)
![3 request to get access_token](https://cloud.githubusercontent.com/assets/11455759/6716756/83685678-cdcd-11e4-825c-5c1d6efc9b9f.png)
![4 response for access_token](https://cloud.githubusercontent.com/assets/11455759/6716758/836d02ea-cdcd-11e4-9bfe-8e1296bec3cb.png)
![default redirect_uri](https://cloud.githubusercontent.com/assets/11455759/6716757/836bc2d6-cdcd-11e4-9d6e-4d4c32cc0eed.png)

**Comment by ankit-ankuagrawal** [comment]
@rgregg sir, in the above scenario is bug present???

**Comment by rgregg** [comment]
I talked with the team that owns this stuff, and it's "by design" to make it easier to use the OAuth 2 flow. Since the logout flow isn't required and isn't used very often, the team chose not to make the optimization to substitute the redirect_uri value with a default value when it was missing.

It's recommended that you always provide a redirect_uri so your can be predictable about how the OAuth flow will work. While it may work without redirect_uri, external changes may break your application.

**Comment by ankit-ankuagrawal** [comment]
thank u for ur response, ur hepling alot

**Comment by ankit-ankuagrawal** [comment]
if it is by design, then redirect_uri value should not be compulsory for logout purpose also...

as of now it is compulsory to give the redirect_uri value for logout purpose, otherwise error occurs...

**Comment by rgregg** [comment]
I agree that the design could be better, but as I mentioned before, the usage of logout is low and it's easy enough to work around the problem. It doesn't rise to the level of a critical bug that we feel must be fixed.

Hope you understand and thanks for providing so much feedback!

**Comment by Velojet** [comment]
(Let's try reopening this with a variation on the OP.)
**The redirect_uri doesn't redirect for me**.
I logout the client with (PHP) `https://login.live.com/oauth20_logout.srf?client_id=' . urlencode(CLIENT_ID) . '&redirect_uri=' . urlencode(CALLBACK_URI)
`
... which is all by the book ("redirect_uri ... must match exactly the redirect_uri value used in the get token request"). (Unlike the OP I do supply the `redirect_uri` value in the login call.)
The client is duly signed out (and required to sign in again) - but there's no redirection and I need to code an explicit redirect.
So, is `redirect_uri` actually used by `oauth20_logout.srf`?
Is there any downside to doing an explicit redirect myself?
