### ISSUE TITLE
File picker modal doesn't work with Electron

### ISSUE THREAD

**Issue by dfournier** [OneDrive/onedrive-api-docs#350]
Hi,

The OneDrive integration works on our web application. The same code is run in Electron, but for some reason the modal doesn't load properly... Here a screenshot showing the error: 
![onedrive_picker_bug](https://cloud.githubusercontent.com/assets/2329786/14603769/f4c721d4-056f-11e6-999a-ddb7d51629ef.png)

Best,
David

**Comment by daboxu** [comment]
based on the console record, it looks like it is the user login page?

**Comment by dfournier** [comment]
You're right @daboxu, it's the login page. Since I can't pass the login screen, I can't select a file from OneDrive. I can provide you an access to our desktop application with the devtools if you'd like to reproduce the bug easily 😃

**Comment by daboxu** [comment]
that would be awesome, could you please give me that?

**Comment by dfournier** [comment]
Tomorrow morning, time to sleep here (France). I'll send you this by mail.
Can I use the one you provided on your github account?

**Comment by daboxu** [comment]
yes, the @microsoft.com one is good.

**Comment by dfournier** [comment]
@daboxu Your email address is not public, could you mail me at dfournier@azendoo.com ?

**Comment by dfournier** [comment]
@daboxu pointed out that the first issue is a known one from https://github.com/electron/electron/issues/254. The solution to fix it is to set `webPreferences.nodeIntegration` to `false`. So I was able to log on my Microsoft account.

Then I got an error from OndeDrive.js. Here the screenshot, right after the success login redirection 😢 
![one_drive_error](https://cloud.githubusercontent.com/assets/2329786/14735502/77b131e4-0871-11e6-963f-3dfaa6b13d28.png)

@daboxu feel free to contact back if you need more informations 😃

**Comment by daboxu** [comment]
@dfournier confirmed I can reproduce it. It is tricky that Electron seems clean up the window.name for every redirect. Need more time to look up how Electron works, hopefully we could have some hack as work around.

**Comment by dfournier** [comment]
@daboxu good news, it worked! I had to monkey patch a lot... Next script is loaded first in the OneDrive modal:
```js
// Force jQuery to load as global name
delete window.module;

var ipcRenderer = require('electron').ipcRenderer;
// Remove natif require to let OneDrive puts its own
delete window.require;

// Set window.name with the last value background process received
window.name = require('electron').ipcRenderer.sendSync('get-window-name');

window.addEventListener("beforeunload", function() {
  // Send window.name value to background process
  ipcRenderer.sendSync('set-window-name', window.name);
});

// When documents are selected, call window.onedriveReceiveMessage on the base window via background process
window.opener.onedriveReceiveMessage = function(info) {
  ipcRenderer.sendSync('send-message-to-one-drive', info);
};

// Changing account call window.open(url, '_top') which open a new window in electron.
// Refreshing current page instead
window.open = function(url) {
  window.location = url;
};
```

To make it clear, thanks to the background process: 
* `window.name` is forwarded between locations
* `window.opener.onedriveReceiveMessage` call is forwarded to the main window

**Comment by daboxu** [comment]
Good to hear it works. If no more problem related, feel free to close it.

**Comment by dfournier** [comment]
I just hope the API will not change...

**Comment by kaykayyali** [comment]
Any chances on reopening this one? The workaround above does not seem to be working.

**Comment by daboxu** [comment]
@kaykayyali what's the issue?

**Comment by kaykayyali** [comment]
When loading the file picker from an electron application, the OneDriveSdk is complaining producing 
<img width="717" alt="screen shot 2016-06-22 at 10 19 55 am" src="https://cloud.githubusercontent.com/assets/6797969/16270066/ea6069be-3862-11e6-8aff-e10a749ba30b.png">
