### ISSUE TITLE
What is the unicode normalization method ODP/ODB supports?

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#351]
Hi, 
I am using ODP api and I try to upload two files which unicode NFC normalisation is the same, and I got response about invalid.
Does this mean ODP support NFC normalisation or other kind of normalisation?

Two files:
u732a
ufa16
will normalize with NFC as u732a and only could upload one of them, and native onedrive client only sync one of them, too.
unlink other storage, onedrive leave one as orphan but other like dropbox will rename the conflict one and do sync.

Thanks.

**Comment by mikechiu1012** [comment]
Hi, I try the ODB API for unicode test.

I use unicode range from 3400 ~ 3C00 to do create new file test.
some unicode will failed due to 
500 {"error":{"code":"generalException","message":"A service invariant has been violated."}}

Is there any restriction about unicode range?

Thanks.

**Comment by ificator** [comment]
Closing stake issues.
