### ISSUE TITLE
get 200 OK rather than 401 invalid token for expired token

### ISSUE THREAD

**Issue by azraelxyz** [OneDrive/onedrive-api-docs#353]
Here is an issue about calling get item metadata api for root item with a expired token.
Get item metadata api responses with status code 200 for root item id.
For non-root item id, get item metadata api responses 404 Not Found.
It might lead to some security issues to distinguish root or non-root item for a given id
with a expired token.

E.g.
Request:

> GET https://api.onedrive.com/v1.0/drive/items/C4A912C98CAF0C8B!267

,where C4A912C98CAF0C8B!267 is the root item id and a expired token is given.

Responses:

> HTTP/1.1 200 OK
> WWW-Authenticate:
> Bearer realm="OneDriveAPI", error="expired_token", error_description="Auth token expired. Try refreshing."
> X-MSNSERVER:
> SN3302____PAP104
> Date:
> Wed, 13 Apr 2016 02:57:01 GMT
> P3P:
> CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
> Content-Length:
> 214
> OData-Version:
> 4.0
> Via:
> 1.1 DM2302____PAP115 (wls-colorado)
> X-AsmVersion:
> UNKNOWN; 19.37.0.0
> Connection:
> keep-alive
> Content-Type:
> application/json; odata.metadata=minimal; odata.streaming=true
> Server:
> Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
> X-WLSPROXY:
> DM2302____PAP115
> 
> {
>   "@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives('me')/items/$entity",
>   "id": "C4A912C98CAF0C8B!267",
>   "name": "root",
>   "webUrl": "https://onedrive.live.com/?cid=c4a912c98caf0c8b",
>   "folder":  {
>     "childCount": 0
>   }
> }

**Comment by rgregg** [comment]
Are you still seeing this?

**Comment by azraelxyz** [comment]
Dear Ryan Gregg,

yes,

A request to reproduce it:

GET https://api.onedrive.com/v1.0/drive/items/C4A912C98CAF0C8B!267

Authorization: Bearer
EwB4Aq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAbyKbL68eldZ/DKtDGN9dzYadZjqtnBwiWzNNr0qgr5/QNQy6dVKsRjEZTxt87Lr+QgBMBvQQtKsXw0SypMAVacxII1ZG0DyvVtWzZqMUH9IWhzMOdfa+pmA8ypbD44Z8SrZ3kvOzFPNAX0kYQChzAYK/j9kX84uVoEVXgn2Wd3xSxqQRHfCZW4iRNvJR8aMU7BbSejTX0/MdBHbT4vieIz6LiYF4h+zHqpF3cu06nSrYtZL7QW60ug59puj5B9AxktPrCR24gcc5EzqbJJRhUAtIDzk08EF805SH3US1LXWaXcCZHR/Aujv5IqSNcOOieuK2/BfJffH7KMqlHTjB7ADZgAACAGBhXP9vSn3SAHNo1eOj+E5uwd9Z+r40H98URvOTKbcjnDHhm4CkMC/edbO9eJmjxrZEalgHsuBFJgqps6lss253bnF5xFUCf9g/1e2YR7/hc6fVX3o3/cYDuTdhvvSDr/7fIcYN1JM4WEW5xHbd/1KsR9QDGQRpD0dnHndR+e5sAxe6bnX5VU3EDDBu0BPSbhPusH/WGIHuAKV9ndZ7xN9p3eicckF3b3y3cVX0vPBH9eseSLRU69m+zluHL8Jdbrn5JpSl7cQq2XVUPIV/eQapG6wR7XCMtG3XtBf+Fin4mJLwSTb2WyzzacX8MXrJSi9P7N8APUy4l5Z/mFXul4yUn7f91Y6bYHQR8+UwGsSyCz/uujvNaYOTDKCC1KZBTh8BzAS1KfGP1wRBzs8v3LSY3nc9nU3Z6kpKWdDoVe2jRV9i2ssuc0ZdFw04PSVngdViwE=


Response:
200 OK
{
    "@odata.context": "
https://api.onedrive.com/v1.0/$metadata#drives('me')/items/$entity",
    "id": "C4A912C98CAF0C8B!267",
    "name": "root",
    "webUrl": "https://onedrive.live.com/?cid=c4a912c98caf0c8b",
    "folder": {
        "childCount": 0
    }
}


2016-06-04 7:10 GMT+08:00 Ryan Gregg <notifications@github.com>:

**Comment by chackman** [comment]
Sorry about this very old issue going stale.  If this is still reproducing, could you please provide updated request & response information to help us investigate further?  Thanks.
