### ISSUE TITLE
Sharing link does't work

### ISSUE THREAD

**Issue by losmicar** [OneDrive/onedrive-api-docs#354]
https://www.dropbox.com/s/i4jhmrjqcp7y160/Screenshot%202016-04-25%2010.18.34.png?dl=0

How to reproduce bug:

1.) On the official demo page, select sharing link.
2.) Click button to start file picker.
3.) Select image from default Photos folder.
4.) Result will be: User cancelled! - even User has clicked Open button and popup closed.

More info:
https://www.dropbox.com/s/em8q87y70pzkr2j/Screenshot%202016-04-25%2010.22.21.png?dl=0
https://www.dropbox.com/s/mwcmvmi670xo1a2/Screenshot%202016-04-25%2010.23.29.png?dl=0

Browser: Chrome, OS: Mac OS Yosemite

**Comment by Jazmon** [comment]
+1 pls fix

**Comment by daboxu** [comment]
@rgregg probably we want to update it

**Comment by daboxu** [comment]
It should be fixed.
