### ISSUE TITLE
Azure App Permissions for a Non-Admin Not Working

### ISSUE THREAD

**Issue by daniellelaforte** [OneDrive/onedrive-api-docs#355]
I am trying to use the OneDrive for Business API as a non-admin user, my app has 2 Azure `Delegated Permissions`, Read User Files and Read and Write User Files, as specified in the OneDrive API docs.  When I make calls to the API I get the following error...
```
{
  "requestId": "5720038b0cf2479188e66725",
  "message": "Request failed",
  "providerMessage": "error - {code=-1, Microsoft.SharePoint.Client.UnknownError, message=Unknown Error}"
}
```

If I am signed in as an Admin and still only granting those 2 permissions, the calls work.

**Comment by bscharm** [comment]
This seems to be working now...was there a fix put in?

**Comment by rgregg** [comment]
Closing out since this issue is no longer reproducible.
