### ISSUE TITLE
The file id is not same from file picker with different version

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#356]
When I use v5.0 web file picker, the selected file's id type like file.AAAA.BBBB(file.1b491acce7ef54dd.1B491ACCE7EF54DD!111), but when I try to use v7.0, the file's id type is just BBBB(1B491ACCE7EF54DD!111).
I don't know why we have this change, but I need you confirm, is the v5.0 file id generated by 'file.' + ownerID + id? Or any other generate rule?

**Comment by daboxu** [comment]
Hi @benjaminliugang, for v5.0 case, it is the format recognized by: https://apis.live.net/v5.0/ endpoint while for v7.0, we are using the newest api which is https://api.onedrive.com/v1.0/.
