### ISSUE TITLE
view.search and view.recent returns empty value

### ISSUE THREAD

**Issue by zoomabv** [OneDrive/onedrive-api-docs#357]
Hi, since yesterday we noticed our REST calls **view.search** and **view.recent** return empty value arrays. 
Any changes being rolled out?

f.e. calls to 
https://gearhing-my.sharepoint.com/_api/v2.0/me/drive/root/view.search?q=test
and
https://gearhing-my.sharepoint.com/_api/v2.0/me/drive/view.recent
both return empty value arrays like 

```
{
    "@odata.context": "https://gearhing-my.sharepoint.com/_api/v2.0/$metadata#items",
    "value": []
}
```

whereas
https://gearhing-my.sharepoint.com/_api/v2.0/me/drive/root:/intranet:children
returns a list of files

It has been working before. Any help is appreciated?

Kind regards, Menno

**Comment by kotsak** [comment]
Hi,

I've noticed similar behaviour as well. With OneDrive it can find files but not folders, where with OneDrive Business it doesn't find anything at all (no files and no folders).

Is there any update on this?

**Comment by chackman** [comment]
Sorry about this very old issue going stale. If this is still reproducing, could you please provide updated request & response information to help us investigate further? Thanks.
