### ISSUE TITLE
400 with createLink view JS File Picker

### ISSUE THREAD

**Issue by prenaudin** [OneDrive/onedrive-api-docs#358]
We are still facing an issue with the JS File Picker v7 when using a OneDrive NOT Business account.
Here is how to reproduce it:

- Use `createLinkParameters: { type: "view", scope: "anonymous" },` to open the OneDrive file picker modal.
- Select a OneDrive NOT Business account
- Pick a file
- While creating the link, the request fails with a 400 status `[actionParameters] The parameter 'scope' in the request payload is not a valid parameter for the operation 'createLink'.`

![screen shot 2016-04-29 at 17 56 58](https://cloud.githubusercontent.com/assets/887094/14922058/bb48f76a-0e35-11e6-9edc-9372d1a25075.png)

It works fine with a OneDrive Business account.
Hope you will be able to reproduce. (Do not hesitate to ask)

Best,

— Pierre

**Comment by rgregg** [comment]
I am able to reproduce this. Let me see what's going on here.

**Comment by groetzi** [comment]
Hi there, great library! unfortunately i ran into the same problem, any news on this?

**Comment by rgregg** [comment]
This should be resolved now. Please let me know if you continue to have trouble.
