### ISSUE TITLE
Access to all special folders

### ISSUE THREAD

**Issue by hartungstenio** [OneDrive/onedrive-api-docs#36]
While I can access every special folder in the root directory using the /drive/special/{special-folder-name} syntax (even "music", which is not documented), it seems to be impossible to access nested special folders, like "xboxGameDVR", "savedPictures" and "mobilePhotos", all under the "photos" folder.

Is there a way to do that. Am I missing something?

I'm trying to develop an app which saves pictures to OneDrive, and I'd like to use the "savedPictures" folder.

**Comment by rgregg** [comment]
Hi @hartungstenio! Can you show me an example of a call that doesn't work for you?

**Comment by hartungstenio** [comment]
I can try. I'm using the API console right now.

What I'm trying to do is to access some "Special Folders" through the `/drive/special/<special folder name` endpoint.

But first, let's issue a GET to `https://api.onedrive.com/v1.0/drive/root/children`. The result of this, as you know, is a list of all files and folders at the root of my OneDrive. In my case, all of the items returned are folders, and all of them have `specialFolder` attribute, with the following names (my language is pt-BR):

specialFolder.name | real name
-------------------------|----------------
attachments            | Anexos de Email
documents              | Documentos
photos                    | Imagens
music                      | Músicas
public                      | Pública

All of them, except `music` and `attachments`, are [documented ](http://onedrive.github.io/items/special_folders.htm). If I try to GET at `https://api.onedrive.com/v1.0/drive/special/<any of those names>` (like `https://api.onedrive.com/v1.0/drive/special/music`), it will work.

Now the problematic part.

If I issue a `https://api.onedrive.com/v1.0/drive/special/photos/children`, a lot of items will get returned. Some of them are also marked as special folders.

specialFolder.name | real name
-------------------------|----------------
xboxGameDVR       | DVR de Jogo do Xbox
cameraRoll              | Imagens da Câmera
savedPictures          | Imagens Salvas
mobilePhotos          | Mobile uploads *(Some time ago, this was called "Arquivos de Dispositivos Móveis", and I used to like that name. You should default to it in pt-BR)*

If I issue a GET to `https://api.onedrive.com/v1.0/drive/special/cameraroll` (the only of those in the [documentation](http://onedrive.github.io/items/special_folders.htm)), everything works. But for my application, I would like to use the `savedPictures` folder. I tried `https://api.onedrive.com/v1.0/drive/special/savedPictures` and `https://api.onedrive.com/v1.0/drive/special/savedpictures`. None of them worked, resulting in the following error:

```javascript
{
  "error":  {
    "code": "invalidArgument",
    "message": "Unknown special folder name: savedpictures",
    "innererror":  {
      "code": "badArgument"
    }
  }
}
```

**Comment by rgregg** [comment]
We did some digging into this, and it appears that savedPictures and mobilePhotos are extra special folders that our special folder logic doesn't know how to find. The other two should work just fine though (xboxGameDVR and cameraRoll).

We're looking to figure out how to make this scenario work better, so that anything you see with a specialFolder facet can be looked up using that value in the /special/ URL path.

Thank you for reporting the bug!

**Comment by rgregg** [comment]
Closing this out since access to the documented special folders works as expected.

**Comment by hartungstenio** [comment]
That is sad, since you return them as special folders :(

:-1:

**Comment by rgregg** [comment]
Actually we are going to fix this... Should be available soon.

**Comment by hartungstenio** [comment]
Nice!
:+1:
