### ISSUE TITLE
Resumable upload and relative path

### ISSUE THREAD

**Issue by psyfreaky** [OneDrive/onedrive-api-docs#364]
I want to create folder structure while uploading files, eg. root/subfolder1/subfolder2/.
It used to work correctly by providing the path in the URL - "/drive/root:/subfolder1/file.dat:/upload.createSession".
Now I can just see the note in resumable upload method docs: "the parent folder must exist before you call createSession."

Why only resumable upload method is limited? It used to work this way and simple upload method still works like that.
Do I really need to list all folders first, create non-existing folder and then upload? Do you plan to put it back? Or is there any faster way to create longer sub-folders tree?

Thanks

**Comment by psyfreaky** [comment]
Funny, that I have to create the folder first.
Please, consider removing this step.

POST https://api.onedrive.com/v1.0/drive/root:/some/very/long/path/:/children
{"name": "SomeSubfolderNeeded","folder": { }}

**Comment by rgregg** [comment]
Thanks for reporting this. We have this tracked on our backlog and are looking into fixing this issue in a future update.
