### ISSUE TITLE
View all changes of a document in OneDrive for business

### ISSUE THREAD

**Issue by phanindraramesh** [OneDrive/onedrive-api-docs#365]
Hi,
  I have 7, versions of a document in OneDrive. I want to download all the versions of the document through rest api. But, since I can call view.delta only on root folder, in the view.delta response, I am getting only one item related to the document. So, I am able to fetch the data of the latest version only.

Can any body let me know if there is a way to fetch all the changes  made to a document in OneDrive for business?

**Comment by rgregg** [comment]
OneDrive API doesn't support file versions yet. Right now you would need to call the [SharePoint 2013 REST API to manage/access versions](https://msdn.microsoft.com/en-us/library/office/jj246487.aspx) of a file:

```
http://<sitecollection>/<site>/_api/web/folders/getbyurl(folderrelativeurl)/files/getbyurl(filerelativeurl)/versions
```
