### ISSUE TITLE
Access from 365

### ISSUE THREAD

**Issue by Fprietom** [OneDrive/onedrive-api-docs#367]
Hello.
I´m using sharepoint designer to access Sharepoint site thorough a WorkFlow using  OneDrive API. But I get no success. Do I need to register in Azure? Is not ok with my 365 user?  
I’m executing the workflow as Admin.

I´m trying  next:

GET
https://{Tenant}.sharepoint.com/_api/v2.0/Drive/root

And the result:
ContentREsponse:
 {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Acceso denegado. No tiene el permiso necesario para realizar esta acción o tener acceso a este recurso."}}

ResponseCode: Unauthorized

Waht I`m doing wrong?

Any help will be much appreciated

**Comment by rgregg** [comment]
Hi @Fprietom: The OneDrive API is different from the SharePoint APIs, in that it doesn't allow cookie authentication. You need to provide authentication explicitly through an Authorization header on the request and an OAuth bearer token. This means the app making the request needs to be registered in AAD and authenticated separately.
