### ISSUE TITLE
[ODP] upload .mov and .mp4 file

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#370]
These seems not to be  blocked file extensions

However when I upload *.mov both from API and web page

The web page do not show all items properly.

But it works fine when I using listchildren api to get all items

I think it might be a bug

thank you for help !

**Comment by rgregg** [comment]
Hi @joewutaiwan. Can you tell me what you mean that the website is not showing all items properly? Are the files appearing but somehow wrong, or do the files not appear at all? Perhaps you can include a screenshot so I can see what you mean. Thanks!

**Comment by joewutaiwan** [comment]
![image](https://cloud.githubusercontent.com/assets/12619781/15561455/9c151ac4-2328-11e6-9e9d-12ff625f8fec.png)

the website folder is empty now

but after I upload such files (like .mov .mp4)

![image](https://cloud.githubusercontent.com/assets/12619781/15561486/f1db1a1c-2328-11e6-8e34-72ad0dc6f030.png)

those files i have uploaded before

However, the APIs works fine

thank you for help!

**Comment by ificator** [comment]
Hi @joewutaiwan, I would hope that after 1 and a half years you don't see this anymore... has this been resolved?

**Comment by joewutaiwan** [comment]
hi @ificator 
now it works fine by webpage upload and API
=)

**Comment by ificator** [comment]
Thanks for confirming!

**Comment by rpili1313** [comment]
I still have this problem!
Any assistance?
