### ISSUE TITLE
Retrieving the children of an item returns 400 Bad Request

### ISSUE THREAD

**Issue by tzuchelin** [OneDrive/onedrive-api-docs#371]
Hi,
   I have 2 folders (中 and 文) in my onedrive.
   I can get children in 中.
GET /v1.0/drive/root:/%E4%B8%AD:/children?top=1000&select=id,name,size,fileSystemInfo,eTag,@content.downloadUrl,webUrl,file,folder,deleted,parentReference,lastModifiedDateTime
   But I get 400 error in 文.
GET /v1.0/drive/root:/%E6%96%87:/children?top=1000&select=id,name,size,fileSystemInfo,eTag,@content.downloadUrl,webUrl,file,folder,deleted,parentReference,lastModifiedDateTime

  Is there any error?
  Please advise.

**Comment by tzuchelin** [comment]
Hi,
    I inspeced this issue on 
[https://apigee.com/OneDrive/embed/console/OneDrive?apig_cc=1](url)
   I got the same error code.
![error response](https://cloud.githubusercontent.com/assets/19570846/15563196/f1975466-2338-11e6-98d8-1fd1f90d97a3.png)

**Comment by skvalex** [comment]
The same issue with Cyrillic characters, please fix the the problem as soon as it possible.

**Comment by ificator** [comment]
I suspect this issue is equivalent to https://github.com/OneDrive/onedrive-api-docs/issues/349 so I'm going to close this one as a "dupe".
