### ISSUE TITLE
OneDrive File Picker JavaScript SDK v7.0 - Display only folders

### ISSUE THREAD

**Issue by simonbelanger** [OneDrive/onedrive-api-docs#373]
When I try to open a file in my drive using the OneDrive File Picker JavaScript SDK v7.0 sample available at https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm, only folders are displayed (no files). I tried to integrate the picker in my app to tweak the calling parameters but I always get the same result. I can see the problematic query string parameter `typeFilters=folder` in the url but I have no idea how to change it. Any idea?

**Comment by utsavdevsharma** [comment]
Hey @simonbelanger 
were you able to resolve this ? we are having same issues #377

**Comment by simonbelanger** [comment]
No, sorry... actually I'm building one myself right now based on Azure AD OAuth, Microsoft Graph and Meteor/React.

**Comment by rgregg** [comment]
We've found the source of this problem and are rolling out a fix today.

**Comment by prenaudin** [comment]
There is still the same issue for the OneDrive Business accounts.
It works fine now for OneDrive Perso account.
Do you need more info to reproduce it?
 
<img width="803" alt="screen shot 2016-06-03 at 07 40 12" src="https://cloud.githubusercontent.com/assets/887094/15769765/72db8404-295e-11e6-80fb-4fdcbe4d0ea4.png">

**Comment by rgregg** [comment]
The fix for OneDrive for Business has been rolling out today. Most users should see this start working again by the end of the day.
