### ISSUE TITLE
No redirect URI actioned on OAuth OneDrive logout

### ISSUE THREAD

**Issue by Velojet** [OneDrive/onedrive-api-docs#374]
(This is a variation on a closed issue: https://github.com/OneDrive/onedrive-api-docs/issues/35)
The redirect_uri doesn't redirect for me.
I logout the client with (PHP) `https://login.live.com/oauth20_logout.srf?client_id=' . urlencode(CLIENT_ID) . '&redirect_uri=' . urlencode(CALLBACK_URI)
`
... which is all by the book ("redirect_uri ... must match exactly the redirect_uri value used in the get token request"). (Unlike the OP in the closed issue, I do supply the `redirect_uri` value in the login call.)
The client is duly signed out (and required to sign in again) - but there's no redirection and I need to code an explicit redirect.
So ..
Q.1: Is `redirect_uri` actually used by `oauth20_logout.srf`?
Q.2: Is there any downside to doing an explicit redirect myself?

**Comment by rgregg** [comment]
The oauth20_logout page doesn't use the redirect_uri parameter. It clears the auth cookies that are stored in the browser and that's it. You'll need to detect that the page has finished loading and then redirect back to a sign-in experience.
