### ISSUE TITLE
[ODP] listdir will return 400 , but API explorer will not.

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#376]
hi,

I create a folder though web and I use API to list children under it.
but I got 
<code>
400 Client Error: Bad Request for url: https://api.onedrive.com/v1.0/drive/root:/%E6%96%87%E4%BB%B6:/children
</code>

but when I use apigee (api explorer)
I could get the correct result.
I think it's a severe bug and I think there will be a great help the supporting unicode range be documented.
![screen shot 2016-05-31 at 14 18 46](https://cloud.githubusercontent.com/assets/6646174/15665081/4eff11d8-273b-11e6-808c-ce2607255a66.png)

Please help to check it.
Thanks.

**Comment by mikechiu1012** [comment]
Hi there,

Now it works fine. 
So this is just a case in accidental or a regular bug over all servers?

Thanks.

**Comment by ificator** [comment]
There shouldn't be any issues with that URL you provided - do you have a full response from when it failed? Maybe there was something else at play.
