### ISSUE TITLE
SDK JS V7 is broken , file picker is not showing files

### ISSUE THREAD

**Issue by utsavdevsharma** [OneDrive/onedrive-api-docs#377]
I created an integration using the guidelines here https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm

The file picker opens but dont show any files .. even if I try to pick files on your demo https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm , it does not show any file in the file picker modal ..

**No-files in file picker:**
<img width="1280" alt="No files in file picker" src="https://cloud.githubusercontent.com/assets/869838/15706095/80a3238a-280f-11e6-809f-01a665d4d835.png">

**Actual screenshot from my one drive account, I do have a lot of files but they are not showing up in file picker modal:**
<img width="1280" alt="screen shot 2016-06-01 at 15 42 30" src="https://cloud.githubusercontent.com/assets/869838/15706145/b8f58c64-280f-11e6-9f53-f7b325803a8c.png">

even if I try to pick files on your demo https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm , it does not show any file in the file picker modal ..

Please let me know what do you find .. Thanks in Advance !!

**Comment by blazedd** [comment]
I am also encountering this issue. This occurs on the demo and my new app just the same.

**Comment by rgregg** [comment]
We've found and fixed the source of this problem in the v7.0 picker. You should see the normal behavior again now.

**Comment by utsavdevsharma** [comment]
Yes this works now, Thanks @rgregg 👍  👍  👍  👍
