### ISSUE TITLE
Not able to upload as Base64

### ISSUE THREAD

**Issue by rahulvpandey** [OneDrive/onedrive-api-docs#378]
Hello,

I am trying to upload Base64 data for files like image/doc/pdf etc to Onedrive(personal) via rest. File is getting uploaded with correct name and correct type however, content is corrupt for files like image/doc/pdf and, for text files the content is the actual Base64. It seems Onedrive is not decoding the Base64 code.

Below is the code

*b64attachment - The encoded Base64 Value

*token- access token

```
var restMessageUpload = new sn_ws.RESTMessageV2();
restMessageUpload.setHttpMethod("post");
restMessageUpload.setEndpoint("https://apis.live.net/v5.0/me/skydrive/files?access_token="+token);
var boundary = 'A300x';
var delimiter = "\u000d\u000a--" + boundary + "\u000d\u000a";
var close_delim = "\r\n--" + boundary + "--"+"\r\n";

var multipartRequestBody =                
    "--" + boundary + "\r\n" +
    'Content-Dis-data; name=\"file\"; filename=\"'+file_name+'\"\u000d\u000a' +
    "Content-Type: application/octet-stream" + "\u000d\u000a" +"\r\n"+
     b64attachment+"\u000d\u000a"+
     close_delim;
restMessageUpload.setRequestHeader('Content-Type', 'multipart/form-data; boundary=A300x');
restMessageUpload.setRequestHeader('Content-Transfer-Encoding', 'base64;charset=utf-8');
restMessageUpload.setRequestBody(multipartRequestBody);
var responseUpload = restMessageUpload.execute();
gs.log("the response body of Upload is"+responseUpload.getBody());
var json = responseUpload.getBody();

```
I am sure, there is no issue at base64. Thanks in advance.

**Comment by rgregg** [comment]
@rahulvpandey: Looks like you are using the old Live Connect API, which we're migrating away from supporting. You should use the OneDrive API for all new development work.

OneDrive doesn't support the Content-Transfer-Encoding header, so we take the binary contents of the stream as-is and use that for the file, which is what you're seeing (you see the raw Base64 data). You need to upload the data stream without the base64 encoding to be successful.
