### ISSUE TITLE
Writable File Metadata

### ISSUE THREAD

**Issue by batteryshark** [OneDrive/onedrive-api-docs#38]
Are metadata options like 'description' or 'tags' going to be re-implemented into this API? 

It's rather useful to have custom metadata to sort and search by.

**Comment by rgregg** [comment]
Description is on our backlog. We're working through finding the right design for concepts like tagging, but we know that having custom metadata attributes is important and we're working to land a good plan for that.

**Comment by rgregg** [comment]
Instead of leaving this issue open, please make sure you've voted for this issue on our [UserVoice](http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7155719-allow-new-api-to-access-and-change-file-descriptio) page.

**Comment by mlafleur** [comment]
For those coming across this post, the `description` property requested in the above UserVoice has been added to the API. 

There is still an [open UserVoice](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7866669-include-tags-in-api) for `tags` however.
