### ISSUE TITLE
/drives cannot expand relationships using OData

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#380]
It would be a great addition if the `/drives` endpoint could expand relationships such as `root` using OData. That is, if doing `GET /drives?select=root&expand=root` would actually return the drives and their root item information. Instead, to get the root item, we need to query `/drives` and then loop through each drive and query `/drives/{drive_id}/root`.  This can slow thing down quiet a bit.

**Some context on why we need this in case there's a better way:**
My team is currently juggling both the SharePoint REST API and the OneDrive API and we would ideally want to move to the OneDrive API completely. In the meantime, we need to get both the drive IDs and their root item's SharePoint IDs (we still need these to use parts of the SharePoint REST API). Having a way to relate the drives to libraries would be ideal. However, no info returned for drives matches anything in the library counterpart (no IDs, not even names--"Documents" vs "Shared Documents", "SiteAssets" vs "Site Assets"--and drives do not get the sharepointIds facet). We basically need to know exactly what drive represents what library, and it seems like the only way to do this is by matching the drive root folder to the library root folder. Having to do that, it'd be nice if we could get the info on a single API call as it can otherwise be a painfully slow process.

**Comment by rgregg** [comment]
Thanks for the suggestion @dluces. I'll add this to our backlog and see if we can provide a solution here.

**Comment by dluces** [comment]
That'd be great, thank you!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
