### ISSUE TITLE
validationToken actual request not camelCase

### ISSUE THREAD

**Issue by prichter** [OneDrive/onedrive-api-docs#381]
Using aws lambda with API gateway, I was attempting handling a validation request for a webhook and received an all lower case query string of 'validationtoken' in a response from OneDrive server, whereas the docs at https://dev.onedrive.com/webhooks/webhook-validation.htm indicate I should be expecting 'validationToken' as a camel-case query string.  Would have submitted a pull request myself, except for: a) I haven't had any other confirmation that others are having the problem, and b) I need some hand-holding about the pull-request etiquette before wading in to this.

POST Request: https://api.onedrive.com/v1.0/drive/root:/{insert path here}:/subscriptions?access_token=abc/easyas/123 
Body: {
      "notificationUrl": "https://tricky.url/validation",
      "expirationDateTime": "2016-12-31T11:23:00.000Z"
    }

Response: 
querystring: { validationtoken: 'UQe-zq5k90S5JFxKGFGgtQ' } +...

**Comment by rgregg** [comment]
Hi @prichter. Thanks for noticing this. This looks like a bug in OneDrive Personal. We should be sending the querystring camel cased as written in the docs.

**Comment by rinkp** [comment]
As this probably causes some troubleshooting, it maybe is a solution to make a comment about this on the documentation page.
