### ISSUE TITLE
non-unique root ids for all SharePoint DocumentLibraries

### ISSUE THREAD

**Issue by desmondyeung** [OneDrive/onedrive-api-docs#382]
I've noticed in my sharepoint instance that all document libraries have the same exact `id` for `root:`. I've removed personal data, but in the example below

`id_of_shared_documents_library` and `id_of_other_documents_library` are the same.

Is this a bug? I've assumed uniqued ids in my application.

`GET https://{tenant}.sharepoint.com/_api/v2.0/drives/{drive_id}/items/root`

```
{"@odata.context"=>"https://{tenant}.sharepoint.com/_api/v2.0/$metadata#items/$entity",
 "@odata.type"=>"#oneDrive.item",
 "@odata.id"=>
  "https://{tenant}.sharepoint.com/_api/v2.0/drives/{drive_id}",
 "@odata.editLink"=>"drives/{drive_id}",
 "createdDateTime"=>"2015-01-22T18:11:55Z",
 "folder"=>{"childCount"=>1},
 "id"=>{id_of_shared_documents_library},
 "lastModifiedDateTime"=>"2016-06-02T12:58:58Z",
 "name"=>"root",
 "size"=>0,
 "specialFolder"=>{"name"=>"documents"},
 "webUrl"=>"https://{tenant}.sharepoint.com/Shared%20Documents"}
```

`GET https://{tenant}.sharepoint.com/_api/v2.0/drives/{other_drive_id}/items/root`

```
{"@odata.context"=>"https://{tenant}.sharepoint.com/_api/v2.0/$metadata#items/$entity",
 "@odata.type"=>"#oneDrive.item",
 "@odata.id"=>
  "https://{tenant}.sharepoint.com/_api/v2.0/drives/{other_drive_id}",
 "@odata.editLink"=>"drives/{other_drive_id}",
 "createdDateTime"=>"2015-01-22T18:11:27Z",
 "folder"=>{"childCount"=>0},
 "id"=>{id_of_other_documents_library},
 "lastModifiedDateTime"=>"2016-05-28T07:37:09Z",
 "name"=>"root",
 "size"=>0,
 "specialFolder"=>{"name"=>"documents"},
 "webUrl"=>"https://{tenant}.sharepoint.com/FormServerTemplates"}
```

**Comment by ificator** [comment]
This is, unfortunately, an unavoidable problem with the current version of the API. We'd love to fix it, but doing so would break any clients that are currently caching IDs and not expecting them to change. A fix is being tracked for the next iteration of the API, but we cannot comment on when you'd see it.

Not a great answer, but it's the only one we have :(

**Comment by thomasthejn** [comment]
Would love to know when this is changed ;-)
