### ISSUE TITLE
Incorrect documentation for OAuth OneDrive logout

### ISSUE THREAD

**Issue by Velojet** [OneDrive/onedrive-api-docs#383]
(Follow-on from [closed issue #374] (https://github.com/OneDrive/onedrive-api-docs/issues/374) - because it's thrown up an issue with the OneDrive API documentation)
@rgrigg Thanks for responding to my previous issue.
What you wrote is contrary to the [OneDrive authentication documentation](https://dev.onedrive.com/auth/msa_oauth.htm).
You wrote:
"The oauth20_logout page doesn't use the redirect_uri parameter. It clears the auth cookies that are stored in the browser and **that's it**" (my emphasis).
The [documentation](https://dev.onedrive.com/auth/msa_oauth.htm) says "After removing the cookie, **the browser will be redirected to the redirect URL you provided**." (my emphasis).
But your statement confirms my own experience so it seems the documentation needs to be changed.

**Comment by rgregg** [comment]
Thanks for calling that out @Velojet. I'll get the docs updated.
