### ISSUE TITLE
OneDrive for Buisness

### ISSUE THREAD

**Issue by sshilpashetty** [OneDrive/onedrive-api-docs#385]
Hi ,

When I am trying to get access token .

using below restAPI request  "https://login.microsoftonline.com/common/oauth2/v2.0/token?client_id={clientID}&client_secret={client_secret}&code={code}&grant_type=authorization_code&resource =https://api.office.com/discovery/&redirect_uri=http://localhost"

I am getting bad request.
Tried with all posibilites ,I have doubt on resource .Could you please let me know is it proper resource

**Comment by ankit-ankuagrawal** [comment]
can u pls closed this has your issue have been solved

**Comment by sshilpashetty** [comment]
Thank you for the support
