### ISSUE TITLE
MSOneDrive for buisness to get access token

### ISSUE THREAD

**Issue by sshilpashetty** [OneDrive/onedrive-api-docs#386]
I am getting the below error  via postman when I requesting for access token 
{
  "error": "invalid_request",
  "error_description": "AADSTS90014: The request body must contain the following parameter: 'grant_type'.\r\nTrace ID: a9c28457-a3ec-4ded-a3e8-2c69de6f596f\r\nCorrelation ID: 5181ef9a-9071-445b-a8b5-752538e97a36\r\nTimestamp: 2016-06-07 14:03:00Z",
  "error_codes": [
    90014
  ],
  "timestamp": "2016-06-07 14:03:00Z",
  "trace_id": "a9c28457-a3ec-4ded-a3e8-2c69de6f596f",
  "correlation_id": "5181ef9a-9071-445b-a8b5-752538e97a36"
}
REST API request to get access token::

POST  "https://login.microsoftonline.com/common/oauth2/token?client_id=6c317738-25a7-4da8-a196-b2ab54c9e540&redirect_uri=http://localhost&client_secret=RTEWAghjrTERAfzHXb2nxzy&code=M066ebbed-f351-822f-dc77-5255d76ad23e&grant_type=code&resource=https://api.office.com/discovery/"

Please let me know what changes I have to make to work.Any help appreciated

**Comment by ankit-ankuagrawal** [comment]
The POST request you making is wrong, there should not be any query parameter

For post man, attaching the snapshot have a look

![access_token](https://cloud.githubusercontent.com/assets/11455759/15860866/5eb73e04-2ce8-11e6-9877-9599ca210ca7.png)

**Comment by sshilpashetty** [comment]
Hi Ankit,

Thank you so much!!


Still I am facing the same issue .

Regards
Shilpa

**Comment by ankit-ankuagrawal** [comment]
can you pls attach the snapshot of the postman app with ur query

**Comment by ankit-ankuagrawal** [comment]
update the grant_type to "grant_type=authorization_code" and not "grant_type=code"

**Comment by ankit-ankuagrawal** [comment]
Did it work?

**Comment by sshilpashetty** [comment]
Hi Ankit ,

No it is not working.


On 6/7/2016 7:56 PM, ankit-ankuagrawal wrote:


Regards
Shilpa

**Comment by rgregg** [comment]
@sshilpashetty Are you getting the same error code or something different? You may want to look into using ADAL instead of writing the authentication layer yourself, if there is an ADAL library available for your target platform.

The list of available ADAL implementations is here: https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-libraries/

**Comment by sshilpashetty** [comment]
Hi rgregg,

I am getting different error 

{
  "error": "invalid_grant",
  "error_description": "AADSTS70000: Authentication failed: Authorization Code is malformed or invalid.\r\nTrace ID: d3e97998-0c84-4884-85b5-b3f9b0495fe0\r\nCorrelation ID: 2a2f3dff-7742-4335-a4e3-ce506d0d322f\r\nTimestamp: 2016-06-08 04:49:36Z",
  "error_codes": [
    70000
  ],
  "timestamp": "2016-06-08 04:49:36Z",
  "trace_id": "d3e97998-0c84-4884-85b5-b3f9b0495fe0",
  "correlation_id": "2a2f3dff-7742-4335-a4e3-ce506d0d322f"
}

**Comment by sshilpashetty** [comment]
![authorizingfrom_create_edit_page](https://cloud.githubusercontent.com/assets/19778228/15883484/1d518554-2d66-11e6-9392-272b5bac7dfd.PNG)

**Comment by ankit-ankuagrawal** [comment]
I think got your problem the value you providing is wrong for "code".

From the step 1 to generate code we provide the value to this step2 (where you are facing problem),

the response for the step 1 to generate code is following
https://login.live.com/oauth20_desktop.srf?code=AAABAAAAiL9Kn2Z27UubvWFPbm0gLR6izIR27CYrLpegU3ke7X1Ak8Zo-pXVrO00pJ-2V40aJm1ULxgQS5WuNR7i5YasDjDzPNqfM7BTu9YhDboIkmPmAde0gLN2yntNnYZWbp68Pnok83jte07t2SeoNkWKFG1s7mHKuC24UEAqiHJS_wme4o-DK-1NrW31F04xndYmWn_CJ7aUO4oCEjtPMMwVxVoI283TSC0s_wXI6kzFcG8-GFpGer0dxpGic3tLdw_bLdZbdOqfab6uFPMfwcxhvMRdI1F_7tRC1z70s_VdeuMf4PM8JjjBzWmplLVKeNyaO1wT5sWH2oEmwcsFSEzehC5QkKWw8inlFg4k6JaIF_XGemEMVanZ2nJ_kOa26rlAnUKADvdsFGMkBStBETotZlja77oJ1qZ_LuIfXgj1TOcFxp8wKggKYrxc1E9i-jicfGe1bb1a-7veCQ8EUyK7j1835P3TRawztz0rCVJPY9JogqxDQfn5h8NmDIflgp5D_uFPhhRq44xYuJyQnx36KJqClAT5Icj7TNpWge1gN8OHpv9TwaiUwalxjF2aI1xJ9wBahoLAgGgaZCmWTuLXGzyObQknl-Z5wcGgtTDavUWDgcoRI4zNVqQuipAfUPa16_vs9fLDSCoSr0KtxPj4b5-t9gYe-8_3SfchwCCn65QgAA&session_state=f0dd6c1a-2159-45d8-a71f-c077ae3d786f

If you focus on this there are 2 query parameters "code" and "session_state"
And you where providing value of session state in your step2 query, so provide the value of "code" 
so the value for code will be =AAABAAAAiL9Kn2Z27UubvWFPbm0gLR6izIR27CYrLpegU3ke7X1Ak8Zo-pXVrO00pJ-2V40aJm1ULxgQS5WuNR7i5YasDjDzPNqfM7BTu9YhDboIkmPmAde0gLN2yntNnYZWbp68Pnok83jte07t2SeoNkWKFG1s7mHKuC24UEAqiHJS_wme4o-DK-1NrW31F04xndYmWn_CJ7aUO4oCEjtPMMwVxVoI283TSC0s_wXI6kzFcG8-GFpGer0dxpGic3tLdw_bLdZbdOqfab6uFPMfwcxhvMRdI1F_7tRC1z70s_VdeuMf4PM8JjjBzWmplLVKeNyaO1wT5sWH2oEmwcsFSEzehC5QkKWw8inlFg4k6JaIF_XGemEMVanZ2nJ_kOa26rlAnUKADvdsFGMkBStBETotZlja77oJ1qZ_LuIfXgj1TOcFxp8wKggKYrxc1E9i-jicfGe1bb1a-7veCQ8EUyK7j1835P3TRawztz0rCVJPY9JogqxDQfn5h8NmDIflgp5D_uFPhhRq44xYuJyQnx36KJqClAT5Icj7TNpWge1gN8OHpv9TwaiUwalxjF2aI1xJ9wBahoLAgGgaZCmWTuLXGzyObQknl-Z5wcGgtTDavUWDgcoRI4zNVqQuipAfUPa16_vs9fLDSCoSr0KtxPj4b5-t9gYe-8_3SfchwCCn65QgAA

Note: without &

**Comment by sshilpashetty** [comment]
Thank you so much for the help !!!.It worked :) :+1:

**Comment by sshilpashetty** [comment]
Hi Ankit,

Thank you for the support .Yes it worked .
Really appreciate your quick response.Thank you once again .

Regards
Shilpa

**Comment by sshilpashetty** [comment]
Hi Ankit,

When I went through docs related to create folder in  MSOnedrive  ,(
![image](https://cloud.githubusercontent.com/assets/19778228/15893529/e38fc8c0-2d9d-11e6-960e-9ea299eb07f0.png)) prerequest mentioned as permission should be files.readwrite.Even though my app has all permission its throwing access denied.
May I know where exactly the issue .
I tried all possiblites my getting new accesstoken  with different scopes


![capture_newfolder](https://cloud.githubusercontent.com/assets/19778228/15893504/c154ebc8-2d9d-11e6-97f0-9b539e1c7de9.PNG)

**Comment by ankit-ankuagrawal** [comment]
firstly why are using graph based apis

if ur objective is to use onedrive business you can use this apis.

If you are using graph based api then i think this is not the right forum
to raise the issues

this apis are totally new launched last year only, through these apis you
can access onedrive personal, onedrive business and sharepoint with the
same set of apis

**Comment by mgsuneel** [comment]
Ankit you are great.. its working like any thing....

**Comment by meetfrnky** [comment]
Hi @ankit-ankuagrawal ankit-ankuagrawal,
Need your help again ,
getting same error tried with above solution ,but still
getting this
"error_description": "AADSTS90014: The request body must contain the following parameter: 'grant_type'.\r\nTrace ID: 4a038548-8284-487a-8955-76c101218900\r\nCorrelation ID: 2758f3b1-d683-43b1-b061-4cc858b5677e\r\nTimestamp: 2017-10-30 19:50:27Z",
    "error_codes": [
        90014
 
Attaching my postman request and  
![image](https://user-images.githubusercontent.com/8298019/32192896-8ebebc32-bddb-11e7-8163-3f5bc139ef18.png)
