### ISSUE TITLE
Any plans to support .ignore?

### ISSUE THREAD

**Issue by dotkebi** [OneDrive/onedrive-api-docs#388]
I've experienced hard to ignore folders without synchronization.

I use oneDrive for source repository. When I build my projects, oneDrive client try to synchronize thousands of files. So I unchecked `build` and `target` folders in Settings, remove them in online site. But after building project, oneDrive client alerts Synchronization Problem with red exclamation mark.

I really hope `oneDrive` support `.ignore` file like `.gitignore`

**Comment by rgregg** [comment]
Sounds like you're talking about the OneDrive sync client. Since this is a feature suggestion, can you add it on the onedrive uservoice page: https://onedrive.uservoice.com/forums/262982-onedrive

**Comment by jdgregson** [comment]
For anyone else finding this from a Google search, this is the issue that needs your votes: https://onedrive.uservoice.com/forums/913522-onedrive-on-windows/suggestions/18449926-reassess-the-possibility-to-ignore-or-exclude-sele

**Comment by mattvasc** [comment]
> 
> 
> For anyone else finding this from a Google search, this is the issue that needs your votes: https://onedrive.uservoice.com/forums/913522-onedrive-on-windows/suggestions/18449926-reassess-the-possibility-to-ignore-or-exclude-sele

Unfortunately, the link is broken.  (404) "UserVoice instance is no longer available."

**Comment by jdgregson** [comment]
> 
> 
> > For anyone else finding this from a Google search, this is the issue that needs your votes: https://onedrive.uservoice.com/forums/913522-onedrive-on-windows/suggestions/18449926-reassess-the-possibility-to-ignore-or-exclude-sele
> 
> Unfortunately, the link is broken. (404) "UserVoice instance is no longer available."

Yes, Microsoft recently decided to delete all of their UserVoice instances without notice and is thinking about making the top requests available again somewhere else. Most user request and comments, including those shared at that link, have been deleted forever.

Don't ask me why they did this, the only reason that makes any sense is that they decided user's voices don't actually matter after all and they're tired of us asking for the features that we need.

**Comment by jdgregson** [comment]
I just found out today that Microsoft has created their own portal to replace UserVoice and has imported the most popular requests from UserVoice as indicated. Unfortunately, no comments have been migrated and likely never will.

The issue linked above can now be found here: https://feedbackportal.microsoft.com/feedback/idea/084d42ab-d51c-ec11-b6e7-0022481f8143

**Comment by VincentGaoHJ** [comment]
Microsoft rolls out function for excluding files, but there is no support for excluding folders right now. Please check the link below:

https://docs.microsoft.com/en-us/onedrive/use-group-policy#exclude-specific-kinds-of-files-from-being-uploaded)

**Comment by hotcuppajojo** [comment]
any updates on a issue request somewhere on Microsoft's side to request folder exclusion?

**Comment by pl4nty** [comment]
@hotcuppajojo a policy was [added to the docs](https://learn.microsoft.com/en-us/sharepoint/use-group-policy#exclude-specific-kinds-of-folders-from-being-uploaded) recently, and in `OneDrive.exe` for a while, but I can't actually get it to work. regkeys are loaded but new matching folders are still synced. tested with Insider and Internal Fast (24.078.0416.0001)

**Comment by bmacGTPM** [comment]
> @hotcuppajojo a policy was [added to the docs](https://learn.microsoft.com/en-us/sharepoint/use-group-policy#exclude-specific-kinds-of-folders-from-being-uploaded) recently, and in `OneDrive.exe` for a while, but I can't actually get it to work. regkeys are loaded but new matching folders are still synced. tested with Insider and Internal Fast (24.078.0416.0001)

I also tried to get this working and failed. However, I also admit that I don't really know what I'm doing lol. Here's what I tried though, in case it helps. I didn't see the key `HKLM\SOFTWARE\Policies\Microsoft\OneDrive\EnableODIgnoreFolderListFromGPO` in the registry, so I added  it, and added the value `.Rproj.user` hoping that all folders named `.Rproj.user` would be ignored, but the folders are still syncing.

**Comment by Tongzhao9417** [comment]
any news about exclude folders? The file have exclude successfully by "EnableODIgnore", but it's failed for subfolders.

**Comment by pl4nty** [comment]
it was recently removed from the docs, but codepaths still exist in `OneDrive.exe`. I've been tracking it here https://garden.tplant.com.au/microsoft/one-drive/

**Comment by pl4nty** [comment]
This feature is roadmapped for June https://www.microsoft.com/en-us/microsoft-365/roadmap?id=178292
