### ISSUE TITLE
Creating a folder returns an invalid location header

### ISSUE THREAD

**Issue by skleeschulte** [OneDrive/onedrive-api-docs#39]
Creating a folder with POST /v1.0/drive/items/{itemId} returns a location header of the format https://api.onedrive.com/v1.0/drives('{driveId}')/items('{itemId}')/children('{newFolderId}'). However this URL is not valid, following it returns a 404 Not Found error. In addition I wonder why a location header is present in the response at all - all necessary information is included in the item which is returned in the response body.

**Comment by ificator** [comment]
Thanks for reporting, that format of the URL is definitely not what we'd expect. The header is present to conform with the OData v4 specification, but realistically most scenarios won't really care about it.

**Comment by ankit-ankuagrawal** [comment]
tried this, the uri is received as specified above, but not 404 error code.
received 201 status code
![1](https://cloud.githubusercontent.com/assets/11455759/6742763/89f5de34-ceb8-11e4-9f89-96ff591d7671.png)

**Comment by ificator** [comment]
@ankit-ankuagrawal Why would you expect a 404 for that request? It successfully created a folder with the name "FolderB".

The location header highlighted is invalid, but it has no impact on the status code of the response. If you attempt to use the highlighted URL it would 404 (as a result of it being invalid), which is what skleeschulte is referring to.

**Comment by ankit-ankuagrawal** [comment]
oh...
@ificator thank u so much , for making me correct...
