### ISSUE TITLE
CreateFolder issue

### ISSUE THREAD

**Issue by ginach** [OneDrive/onedrive-api-docs#391]
Copied over from the [SDK repo](https://github.com/OneDrive/onedrive-sdk-csharp/issues/122).

Based on the documentation (https://dev.onedrive.com/items/create.htm)
 there is "@name.conflictBehavior" query option available when creating a folder.
 But regardless of which value for the option is provided, SDK always failing to create a folder, if it is already exists ("rename" does not work). This is true, if you signed in with "Business" account. If you signed in with "Personal" account, the call to CreateFolder always returns the instance of an already existing folder with the same name ("rename" and "fail" options do not work).

**Comment by nsouren** [comment]
Any news on this?

**Comment by ificator** [comment]
I don't repro this:

Scenario | Result
--- | ---
ODB-fail | 409
ODB-rename | 201 with unique name
ODC-fail | 409
ODC-rename | 201 with unique name

It may be that it has been resolved by other unrelated changes since the original issue was opened in the SDK?
