### ISSUE TITLE
ctag changing on jpg uploads

### ISSUE THREAD

**Issue by amagliul** [OneDrive/onedrive-api-docs#392]
We are seeing that the ctag of a jpg image file item is changing after upload, seemingly on its own. 

On successful upload the item resource will contain a ctag value, which we record. On a subsequent query on the item, the ctag will have changed (within 30 seconds) to another value. The end result is that our client thinks the file has been updated remotely.

This seems to be recently changed behavior, as our integration code hasn't changed for a while. So far we are only seeing this on .jpg files. Other file types seem unaffected, maintaining their original ctag.

Is this expected?

**Comment by ificator** [comment]
Hi @amagliul, do you also observe the hash of the file changing when the CTag value changes?

The short answer is: yes, the CTag can change without your application doing anything to the file. There are really two scenarios that can trigger this:
1. Another application
2. The service itself

In your case you're most likely seeing *#*2 since you mentioned uploading an image. When an image is uploaded to the service it is immediately accepted, but asynchronous processing is queued for the generation of thumbnails and other metadata related activities that would otherwise delay file uploads. As to why you're only seeing this recently I'm not sure - technically this behavior has been present for quite a while now.

But TL;DR: yes it's expected that the CTag can change outside of your apps knowledge.

**Comment by amagliul** [comment]
I appreciate the swift response Brad. Thank you!

It is possible that this behavior has existed, but went unnoticed until recently. I am trying to verify that.

To provide a little more info: we have a synchronization client that currently uses ctag to determine if file content has been changed. Since the ctag here is modified, despite there being no discernible change to the file content (the MD5 hash is the same after the ctag is changed), it limits the usefulness of the content eTag, especially if the OneDrive service can conceivably change this value at any time without the item content actually being changed.

What would be your advice for dealing with this particular behavior? We would like reference an authoritative "marker" for item resource content changes. I see there is a hashes facet. Is this value populated by the OneDrive service after upload?

Thanks!

**Comment by ificator** [comment]
I would argue that if the content of the file didn't actually change, having the CTag change is not valuable - I'll check into that.

In the mean time what you suggested is probably your best course of action - the `hashes` facet will contain a SHA1 value that is a hash of the files contents and so you can detect a change in content by a change in its value.

**Comment by ificator** [comment]
Actually, I need to clarify - are you hitting the Consumer API or the Business API?

**Comment by amagliul** [comment]
Sorry for the tardy reply. We integrate with both OneDrive and OD4B. OneDrive is the more common though. I realize that hases aren't available on OD4B.

I would prefer to use cTag, if possible. It seems like it should be usable in this scenario. Thanks for looking at it and please let me know what you find.

Thanks!

**Comment by ificator** [comment]
Thanks for the info @amagliul - I can easily repro this on the consumer endpoint and can confirm your observations and expectations. If the content has not changed (i.e. the hash is the same) I would NOT expect the CTag to change. I'll follow up with the appropriate people and see if we can figure out what's going on.

**Comment by amagliul** [comment]
Much appreciated @ificator! Props to you and your team for the swift attention on this.

**Comment by ificator** [comment]
Just to update this, we've found a recent change that is causing this behavior and are trying to figure out the best path forward.

**Comment by amagliul** [comment]
Excellent! Thanks for keeping me in the loop.

**Comment by ankit-ankuagrawal** [comment]
@ificator any update on this

**Comment by ificator** [comment]
This should be resolved now - let us know if you still notice anything strange.

**Comment by amagliul** [comment]
I missed this earlier, but I appreciate the update. Thanks for resolving!
