### ISSUE TITLE
Scope in OneDrive API documentation appear to be wrong

### ISSUE THREAD

**Issue by adamgallowayscala** [OneDrive/onedrive-api-docs#393]
In the following documentation the scopes reference `onedrive.read` but requesting this scope results in an error stating that the scope does not exist.

https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/msa_oauth.md

Instead using the scope `onedrive.readonly` successfully grants access.

**Comment by rgregg** [comment]
Thanks for catching this error @adamgallowayscala. I've updated the docs with commit ba99cfa to resolve this.
