### ISSUE TITLE
After how much time we should use the new refresh and Access Tokens

### ISSUE THREAD

**Issue by vivekrmishra** [OneDrive/onedrive-api-docs#394]
Hi, I am working on an app that connects to onedrive, and try to get the list of files and present it to users. Our app is making the java REST call to access onedrive. After signing in and getting the new access and refresh tokens we start accessing the file list. If the onedrive is large, it take few hours to get the complete list of files. As per documentation and Github [issue#228](https://github.com/OneDrive/onedrive-api-docs/issues/228) when we get 401 or 404 response code, we are getting the new refresh and access tokens. After that we continue accessing the files.  
We are facing a issue where after getting the newly generated access and refresh tokens, it is still not able to connect onedrive and give 404 error in response code. If we retry 3-4 times to get new tokens, we are able to proceed, but there is no timeline of getting a new tokens. I mean that if it gets the new tokens after sleeping the application for few seconds it may or may not work. Many times we may have put our app in sleep mode for more than 15 mins and up to an hour, get the new tokens and then start accessing again. 
Q1: Is there a limit where we should get the new tokens after minimum specific amount of time, say after 10mins or 15 mins.
Q2: If app is not able to connect with new tokens, how many retry should be there to get new tokens and at what interval of time.

**Comment by ificator** [comment]
Closing stale issue - if this is still applicable please reopen so we can triage appropriately.
