### ISSUE TITLE
file upload: In case of .exe or files larger than 50 MB using resumable upload did not upload with MIMETYPE

### ISSUE THREAD

**Issue by testingash** [OneDrive/onedrive-api-docs#395]
Hi,

I want to upload .exe files using resumable upload. File get uploaded using resumable upload but, when list in that directory this uploaded file did not have MIMETYPE as .exe file hence, it listed as directory instead of file.

How to upload such files?

**Comment by ificator** [comment]
Hi @testingash, are you hitting OneDrive Business or OneDrive Consumer when you see this behavior?

**Comment by testingash** [comment]
I am hitting to OneDrive Consumer not business.

**Comment by testingash** [comment]
Hi,
I am creating session for upload. On getting uploadUrl, using this url .exe file getting uploaded. The response is as below:

{"@content.downloadUrl": "…………",
"file": {"hashes": {"crc32Hash": "F2D5B3E9","sha1Hash": "247FF5EBA83A55F8B196558F016E32EDD629E4FF" } },"fileSystemInfo": {"createdDateTime": "2016-07-01T08:28:14.91Z","lastModifiedDateTime": "2016-07-01T08:28:14.91Z" },"id": "8055A16EAF17FF79!509","lastModifiedBy": {"application": {"displayName": "uosapp","id": "40127b3c" },"user": {"displayName": "ashlesha tillu","id": "8055a16eaf17ff79" } },"lastModifiedDateTime": "2016-07-01T08:28:14.91Z","name": "jdk-7u45-nb-7_4-windows-x64.exe","parentReference": {"driveId": "8055a16eaf17ff79","id": "8055A16EAF17FF79!238","path": "/drive/root:/sky" },"size": 236820312,"webUrl": "https://1drv.ms/u/s!AHn_F69uoVWAg30" }

Thus, in "file" property mime type should occur in MIMETYPE. As this is not in response hence ,not finding that file is .exe type.

**Comment by ificator** [comment]
Thanks for the clarification @testingash, this does seem strange. I'll look into it.

**Comment by ificator** [comment]
Hi @testingash, this should now be resolved!
