### ISSUE TITLE
 error response is not a json object when error code is 400

### ISSUE THREAD

**Issue by tobecontinued** [OneDrive/onedrive-api-docs#397]
the https://github.com/OneDrive/onedrive-api-docs/blob/master/misc/errors.md said:

> Errors in the OneDrive API are returned using standard HTTP status codes, as well as a JSON error response object. 

but I received a html format message when the error code was 400:
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BODY><h2>Bad Request - Invalid URL</h2>\r\n<hr><p>HTTP Error 400. The request URL is invalid.</p>\r\n</BODY></HTML>\r\n
```

**Comment by tobecontinued** [comment]
the request is : 

> POST /v1.0/drive/root:/papers/distributed%20machine%20learning/TensorFlow-%0ALarge-Scale%20Machine%20Learning%20on%20Heterogeneous%20Distributed%20Systems.pdf:/upload.createSession HTTP/1.1

**Comment by rgregg** [comment]
Were you sending this request to api.onedrive.com or to a OneDrive for Business URL? Could there be a proxy server between your client and the service?

**Comment by tobecontinued** [comment]
Yes I send it to api.onedrive.com and I think it's impossible that there is a proxy. Actually there are other people who use the same appliaction also have had this situation. Whats more, It seems that some errors have json respone, but others not.

**Comment by rgregg** [comment]
Can you include the response headers for one of the fails without JSON requests? That can help us debug what's going on so we can take a look.

**Comment by tobecontinued** [comment]
here is:

> {'Date': 'Thu, 30 Jun 2016 10:59:58 GMT', 'Content-Type': 'text/html; charset=us-ascii', 'Content-Length': '324', 'Connection': 'close'}

in other requeset:

> "GET /v1.0/drive/items/47A3F775951035AE!16839/content HTTP/1.1" 

it has json object:

> {"error":{"code":"itemNotFound","message":"The specified item does not exist, or does not have content.","innererror":{"errorType":"client","debugMessage":....

**Comment by ificator** [comment]
Regarding the following:
>  POST /v1.0/drive/root:/papers/distributed%20machine%20learning/TensorFlow-%0ALarge-Scale%20Machine%20Learning%20on%20Heterogeneous%20Distributed%20Systems.pdf:/upload.createSession HTTP/1.1

The problem is the use of `%0A` - that's a line feed and unfortunately HTTP.sys is currently rejecting the request before it gets to us. We'll look at fixing that, but this request would have eventually failed anyway since `%0A` is not allowed in file / folder names.

**Comment by tobecontinued** [comment]
Oh, thanks for your help.
