### ISSUE TITLE
Multipart upload error HTTP 400 Bad Request

### ISSUE THREAD

**Issue by RonaldCY** [OneDrive/onedrive-api-docs#399]
Dear Sir/Madam,
When i was doing upload file to onedrive with following:

> HTTP POST https://apiis.live.net/v5.0/{foldid}/files?access_token={ACCESS_TOKEN}
> 
> Content-Type: multipart/form-data; boundary={boundary}
> 
> --{boundary}
> Content-Disposition: form-data; name="file"; filename="{filename}"
> Content-Type: application/octet-stream
> 
> {File content goes here}
> --{boundary}

by which I follow the guide from https://msdn.microsoft.com/en-us/library/office/dn659726.aspx

It always give me error "java.lang.Exception: HTTP 400. Bad Request".
Would one drive team help to give me advice what it was going wrong?

Thanks and Best Regards,
Ronald

**Comment by peternied** [comment]
@RonaldCY from the url, this would indicate you are using the deprecated LiveConnect API.  I would recommend using the new APIs upload method described here https://dev.onedrive.com/items/upload_put.htm where the request does not need the multipart mime schema

```
PUT /drive/root:/{parent-path}/{filename}:/content
Content-Type: text/plain

The contents of the file goes here.
```

If you are still having trouble, please make sure to include the full http response headers and body.
