### ISSUE TITLE
 the query parameter "lc" not received in the error_response uri 

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#40]
the following steps perform on android device (using webview client)
1) made the first request to get code using the uri
"https://login.live.com/oauth20_authorize.srf?client_id=000000004813EF9B&scope=wl.signin%20wl.offline_access%20onedrive.readwrite%20wl.emails&response_type=code&redirect_uri="
![android request for code](https://cloud.githubusercontent.com/assets/11455759/6741965/e0a2d0ae-ceb1-11e4-82c7-4316a785da02.png)

2)successfully submitted username and password

3)new page pop up to get permission/scope to let app use info
![scope page](https://cloud.githubusercontent.com/assets/11455759/6742001/37f82606-ceb2-11e4-921a-c2beec2d472c.png)

***4) pressed no
![scope page_no](https://cloud.githubusercontent.com/assets/11455759/6742017/5ef328dc-ceb2-11e4-9e71-26e4db592e24.png)

***5)in RESPONSE should get error uri as specified 
eg "https://login.live.com/err.srf?lc=1033#error=unauthorized_client&error_description=The%20client%20does%20not%20exist.%20If%20you%20are%20the%20application%20developer%2c%20configure%20a%20new%20application%20through%20the%20application%20management%20site%20at%20https://manage.dev.live.com/."

with the query parameter (https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/msa_oauth.md)
1)lc 	
2)error
3)error_description 

the problem arise here, in RESPONSE received only the following parameter
1)error
2)error_description

the query parameter "lc" not received in the uri 
![error_uri_fix](https://cloud.githubusercontent.com/assets/11455759/6742137/4e26198c-ceb3-11e4-8fe6-7289674fac27.png)

the above mention problem is creating a lot problem with the app in which we are integrating the onedrive, due to change in response error structure, code written couldnot detect the error

**Comment by rgregg** [comment]
It appears we don't always return the `lc` parameter. Ideally your logic for parsing the parameters in the error response is resilient to missing properties and does it's best to recover based on missing data.

I'll update the docs to remove the `lc` parameter in the error response.

**Comment by rgregg** [comment]
OK, dug into this more and I see what's happening. the ?lc=1033 parameter is included on the error response page provided by Microsoft Account to determine the language the page renders in. When the user clicks the No button, we're redirecting back to your page and adding on the bookmark with error details. Because we always redirect to your URL + "#bookmark" we don't append the ?lc=1033 data.

This would be "by design" since we don't own your redirect URL. The ?lc=1033 query string is only added when we display our own error page.

**Comment by ankit-ankuagrawal** [comment]
can this be updated on the github page, like me there may be many folks to get confuse (there will be more clarity)

thank u for ur response...

**Comment by rgregg** [comment]
Yep. I'm pushing a change to that page right now.

**Comment by skleeschulte** [comment]
"This would be 'by design' since we don't own your redirect URL. The ?lc=1033 query string is only added when we display our own error page."
I want to mention that the redirect after a logout (by sending the client to https://login.live.com/oauth20_logout.srf?client_id={clientId}&redirect_uri={redirectUri}) get's the 'lc'-parameter appended. However, I would expect this parameter not to be present here.

**Comment by rgregg** [comment]
I've updated the documentation to not mention the `lc` parameter in the way we did before. Thanks for reporting the issue!

**Comment by ankit-ankuagrawal** [comment]
as before when trying to get code using "https://login.live.com/oauth20_authorize.srf?client_id=000000004813EF9B&scope=wl.signin%20wl.offline_access%20onedrive.readwrite%20wl.emails&response_type=code&redirect_uri="

the value of redirect_uri used to be null

and when pressing no on consent page, the following response received contains only error, error_description 

***now when passing redirect_uri = "https://login.live.com/oauth20_desktop.srf."
and pressing the no on consent page the uri received is different 

the o/p is "https://login.live.com/oauth20_desktop.srf?error=access_denied&error_description=The%20user%20has%20denied%20access%20to%20the%20scope%20requested%20by%20the%20client%20application.&lc=1033"

it contains lc, error, error_description and that to the order of appearing is different without #

pls look into the matter urgently

**Comment by ankit-ankuagrawal** [comment]
@rgregg sir like to have ur attention on the post above

**Comment by rgregg** [comment]
@ankit-ankuagrawal while it may work without a redirect_uri value, our docs specify that that value is required. I'd recommend always providing a redirect_uri to the OAuth flow so you have consistent behavior.

**Comment by ankit-ankuagrawal** [comment]
@rgregg started giving (using) redirect_uri, but the response is different, you can check that.
want to just notify abt different behaviour, as u said before ""This would be 'by design' since we don't own your redirect URL. The ?lc=1033 query string is only added when we display our own error page."
I want to mention that the redirect after a logout (by sending the client to https://login.live.com/oauth20_logout.srf?client_id={clientId}&redirect_uri={redirectUri}) get's the 'lc'-parameter appended. However, I would expect this parameter not to be present here."" but now can receive "lc" also when consent page is cancel
