### ISSUE TITLE
OneDrive File Picker does not work on safari and firefox

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#403]
OneDrive File Picker does not work on safari and firefox, but it works well on chrome.
This issue can reproduce both on our product and oneDrive sample

*Reproduce steps:*
a) Open https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm
b) Click Open from OneDrive button
c) Login with your account

*Result:*
The file picker will keep loading, cannot get reference files

*Environment:*
OS: Version 10.11.5
Safari: Version 9.1.1 (11601.6.17)
Firefox: 48.0a2

It's really a critical issue, it's impact our product's release.

**Comment by daboxu** [comment]
hi @benjaminliugang, I tested with following 2x2 matrix:

| | Customer Account  | Business Account |
|----|:----:|----:|
|Safari| work | failed|
|FireFox| work | work|

My test environment is:

Mac OS: 10.11.5
Safari: 9.1.1 (11601.6.17)
FireFox: 47.0.1

The failing case has been noticed. If it is not  your case, could you please provide more detail on the account you are using? Any browser console log and/or screenshot will be appreciated.

**Comment by benjaminliugang** [comment]
Already works for my case, just close the ticket.
