### ISSUE TITLE
Deleting a folder in ODB: You have to delete all the items in this folder before you can delete the folder

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#404]
I'm trying to delete a folder in a OneDrive for Business user's drive, using an admin token. This works for most users in the organization just fine. When deleting folders for a couple of users, I get an error.

The request:
```
DELETE {ODB_user_site}/drive/items/{item_id}
```

The response:
```
HTTP/1.1 500 Internal Server Error
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Thu, 23 Jun 2016 17:23:59 GMT
Last-Modified: Fri, 08 Jul 2016 17:23:59 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 293
X-AspNet-Version: 4.0.30319
SPRequestGuid: 66db8d9d-30c1-3000-0a08-047c66d5be8e
request-id: 66db8d9d-30c1-3000-0a08-047c66d5be8e
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5423
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Fri, 08 Jul 2016 17:23:58 GMT

{"error":{"code":"-2130575223, Microsoft.SharePoint.SPException","message":"You have to delete all the items in this folder before you can delete the folder."}}
```

Edit:
The error message provides a potential alternative. However, I don't think that this should be happening. As stated before, this does not happen for lots of other folders with many items and folders inside it either. If this behaviour is expected and not a bug, when should I expect to have to delete all items inside a folder before deleting the folder? Also, would there be an alternative so the whole folder can be deleted along with all its items?

**Comment by ificator** [comment]
I haven't seen this error before, but after searching around it seems like it could be related to eDiscovery which can put "holds" on SharePoint sites.

From https://technet.microsoft.com/en-us/library/fp161516.aspx#in_place_holds:
>  *Users will also receive an error if they try to delete a folder that contains a file that’s on hold. If users want to delete a folder that contains one or more files that are on hold, they have to delete those files before they can delete the folder.*

However, the response you received doesn't appear as documented so there's definitely more we can do to make this more obvious. I'll look in to that.

**Comment by dluces** [comment]
Interesting. I've also received errors when deleting files that say something like `Item is on hold`. I'm assuming that's related as well. In the meantime, if I get this error on folders, I do a listing and delete each file first. Sometimes I get the `item is on hold` error and I just queue it for deletion again. So I've managed to work around this. Thank you.

**Comment by ificator** [comment]
FYI I've checked in a change to return a more meaningful error message.

**Comment by dluces** [comment]
@ificator Thank you! If the new error message/code could be documented in the [errors doc page](https://dev.onedrive.com/misc/errors.htm) it would be great.
