### ISSUE TITLE
[ODB] root/view.delta gives useless token while reach the end

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#405]
Hi, 

I use /drive/items/root/view.delta to get changes from ODB, everything is ok if I'm using next link to receive changes. 

But when I reach the end of my storage, I'll get an useless token like `1;%234;%231;3;64d77af3-ac65-4a82-9162-fd5e71086f0b;636032100807700000;15048766;%23` from the response. If I put this token into a new view.delta request the only response I can get is read timeout.

Is this an issue of onedrive for business?

```
GET https://cloudqnap-my.sharepoint.com/_api/v2.0/me/drive/root/view.delta params={'top': 1000, 'token': u'1;%234;%231;3;64d77af3-ac65-4a82-9162-fd5e71086f0b;636032100807700000;15048766;%23', 'select': 'id,name,size,fileSystemInfo,webUrl,file,folder,parentReference,lastModifiedDateTime,remoteItem,package,deleted'},headers={}
Encounter error HTTPSConnectionPool(host='cloudqnap-my.sharepoint.com', port=443): Read timed out. (read timeout=60)
```

**Comment by ificator** [comment]
Hi @verybada, are you still seeing timeouts? That certainly sounds like a service issue.

If possible, could you increase your timeout to something insane and wait patiently for the query to come back. Hopefully it will eventually, in which case you should be able to grab the `request-id` header out of the response. We can use that to take a look at what's actually going on.
