### ISSUE TITLE
[ODP] docx sha1 mismatch

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#407]
hi all,

I think the sha1 hash got a little problem in mime_type: application/vnd.ms-word.document.12

```
file id  : BC6BAF0531250242!67529
sha1_hash: E3F8566423ECA45422FD28FDA334C03A54EE1E1C
```

after download and run openssl sha1

```
4668f15966dda307576006a0e905977d00335214
```

but in mime_type: application/vnd.ms-excel.12; charset=UTF-8

```
file id  : BC6BAF0531250242!8538
sha1_hash: 58C7BD39FE7DBCD9628BD76EEB84C5ECD9B87572
```

after download and run openssl sha1

```
58c7bd39fe7dbcd9628bd76eeb84c5ecd9b87572
```

it matchs!

**Comment by ificator** [comment]
Hi @joewutaiwan, I asked around and apparently there was an issue that could have caused this hash discrepancy. It will be resolved by one of the following actions:

1. An edit to the file in question
2. A notification from the sync client that the hash is mismatching

For your specific repro it'll probably be easiest to edit the file and save it, at which point the hashes should match again.
