### ISSUE TITLE
List Entire Heirarchy

### ISSUE THREAD

**Issue by scottbasgaard** [OneDrive/onedrive-api-docs#408]
Hey there,

Is there a way to list out an entire hierarchy (directory / files) from the root level or a specific folder?

Trying to use view.delta but it seems to only bring back latest changes, even if I omit a token:
>token    string    The last token returned from the previous call to view.delta. If omitted, view.delta returns the current state of the hierarchy.

S

**Comment by rgregg** [comment]
Hi @scottbasgaard: you should get the current state of the hierarchy if you make this call:

```
GET https://api.onedrive.com/v1.0/drive/root/view.delta
```

Are items missing that you see in your drive when making that call and paging through the `@odata.nextLink` pages of results?

**Comment by scottbasgaard** [comment]
@rgregg thanks! Works good :)
