### ISSUE TITLE
Get Access and Refresh token via Ajax

### ISSUE THREAD

**Issue by sergiomedinag** [OneDrive/onedrive-api-docs#409]
I'm trying to get a refresh token and access token for One Drive Business by using an AJAX request. But when I perform such request, I get the missing Access-Control-Allow-Origin error. If I perform the same request with curl, it works perfectly.

Request details to https://login.microsoftonline.com/common/oauth2/token:

`POST /common/oauth2/token HTTP/1.1
Host: login.microsoftonline.com
Connection: keep-alive
Content-Length: 987
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
Origin: http://slc04rku.us.oracle.com:7101
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://slc04rku.us.oracle.com:7101/bali/?pageid=datasources
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8

client_id=xxx&client_secret=xxx&redirect_uri=http%3A%2F%2Flocalhost%2Fauthresponse.jsp&grant_type=authorization_code

`

Response details:

`HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
x-ms-request-id: 4af29899-6eec-485b-81f4-eb654e4ce8f0
client-request-id: e307d3b2-dcdd-4e6f-b892-3f0ab9b6d8e7
x-ms-responsehealth: TargetId=ESTSFE_IN_166;Action=None;Category=None;Health=0;Load=25;
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: esctx=AAABAAAA0TWEUN3YUUq5vuCvmnaQicX4MVI1_yI1ufS9w-9YAaQPxCGXvR8oiEo7fqzcDM0AYPgVgmjFUN03Xw6nUdD_D5MkLLyoACMzmimrn53jr-RxNb2RhKeckZwC4HrTWqxbR7Wjf9jm75f4zPfOohV_hCns_42xQ8byFsQqtqsd7XVIG6tBzxrJAm8Kyb1bQRgnIAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie: x-ms-gateway-slice=productionb; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Date: Thu, 21 Jul 2016 18:29:16 GMT
Content-Length: 3024`

Console error:

`XMLHttpRequest cannot load https://login.microsoftonline.com/common/oauth2/token. No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by rgregg** [comment]
Posted this on your StackOverflow thread, but I'll repost here too.

This is by design, single page apps are not allowed to request refresh tokens, but instead require SPAs to use implicit flow. If you need to continue to maintain access after the 1 hour expiration of the access-token you are given, there is a way to silently get a new token as long as the user is still signed in. The method for doing this is documented here: https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-protocols-implicit/#refreshing-tokens

**Comment by sergiomedinag** [comment]
Thanks Ryan, Should I close this since this not an actual bug then?
