### ISSUE TITLE
Getting throttle on specific API requests and not in others

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#410]
I'm using ODB with an admin token.

I can list a user's root folder just fine. I can create a folder (`sampleFolder`) in the user's root folder just fine. However, when trying to get the children of `sampleFolder`, I'm getting throttled. I can list the user's root folder before, during and after attempting to list `sampleFolder`, and still the response from listing `sampleFolder` is that the app or user is being throttled. No other app is accessing the user and my app is doing nothing else. Waiting for hours and then listing `sampleFolder` keeps receiving a back-off request. Immediately listing the root works just fine. Why is the API call to list `sampleFolder` getting throttled? Why is it getting throttled when listing that particular folder and not when listing the root or even when creating the folder?

```
HTTP/1.1 429 Too Many Requests
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Thu, 07 Jul 2016 15:56:21 GMT
Last-Modified: Fri, 22 Jul 2016 15:56:21 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 53
X-AspNet-Version: 4.0.30319
SPRequestGuid: f357929d-f0b6-2000-0a07-3842ddd8ab3d
request-id: f357929d-f0b6-2000-0a07-3842ddd8ab3d
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5507
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Fri, 22 Jul 2016 15:56:21 GMT

{"error":{"code":"activityLimitReached","message":"The application or user has been throttled."}}
```

**Comment by rgregg** [comment]
Can you send me an e-mail (rgregg at microsoft.com) with the email address of the user who is affected by this? This is likely a known issue that impacts a small number of specific accounts, and with that information we should be able to resolve the problem.

**Comment by dluces** [comment]
@rgregg Sent! Thank you!

**Comment by ificator** [comment]
Hi @dluces, this issue should now be resolved. Please let us know if you continue to see issues.

**Comment by dluces** [comment]
@ificator I can confirm that the issue has been fixed and we're not getting throttled anymore. Thank you!
