### ISSUE TITLE
Creating a sharing link in ODB succeeds most times but others fails with 403 Fobidden

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#413]
My team has been creating sharing links for a company's users' files, using ODB with an admin token. Most of the times, we can create sharing links successfully but other times, we get a `403 Forbidden` response.
We are using [this endpoint](https://dev.onedrive.com/items/sharing_createLink.htm) to create the sharing links.
I have not been able to determine in what circumstances creating the sharing links fails. It succeeds in some PDF, PPTX and even EXE files and it fails in others, for the same user.
If a feature needs to be enabled, like the error shows, what are the steps needed to enable such feature?

Sample response:
```
HTTP/1.1 403 Forbidden
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Thu, 07 Jul 2016 04:28:29 GMT
Last-Modified: Fri, 22 Jul 2016 04:28:29 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
SharePoint-CreateSharingLink-Error: Sharing by link is not enabled on the web, site, or tenant.
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 491
X-AspNet-Version: 4.0.30319
SPRequestGuid: 9730929d-e08e-2000-0a07-31c08d44878a
request-id: 9730929d-e08e-2000-0a07-31c08d44878a
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5507
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Fri, 22 Jul 2016 04:28:30 GMT

{"error":{"code":"notAllowed","message":"The feature has been disabled. Please contact your admin to get it enabled."}}
```

**Comment by ificator** [comment]
Do you see different behavior within the same drive/document library?

**Comment by dluces** [comment]
@ificator Yes. For the same ODB user, I was able to create a sharing link to file `/sample.exe` but not to file `/subfolder/another.exe`, both of which reside in their `Documents` library.

**Comment by ificator** [comment]
That does seem unexpected - we'll need to drill in and see what's going on

**Comment by dluces** [comment]
@ificator I have a report on sharing links that got created successfully and those that didn't. I could send it over in case it helps. I also have newer error responses in the logs in case they might be helpful. Let me know if I can help somehow. Thanks.

**Comment by ificator** [comment]
Hi @dluces, do you have a response from a request that succeeded, ideally in the same document library as the one that failed?

**Comment by dluces** [comment]
@ificator Unfortunately, I don't have a log for successful requests anymore. However, I do have a list of items for which we successfully created sharing links.
I'll see what I can do to get a log with successful requests and will get back to you. Thanks

**Comment by dluces** [comment]
Hello @ificator,

I've managed to log more responses for you.

Successful response:
```
HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Sun, 10 Jul 2016 22:53:33 GMT
Last-Modified: Mon, 25 Jul 2016 22:53:33 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 210
X-AspNet-Version: 4.0.30319
SPRequestGuid: 0467939d-402c-2000-ab2c-c63001f0590e
request-id: 0467939d-402c-2000-ab2c-c63001f0590e
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5507
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"
Date: Mon, 25 Jul 2016 22:53:32 GMT
```

Error:
```
HTTP/1.1 403 Forbidden
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Sun, 10 Jul 2016 22:57:53 GMT
Last-Modified: Mon, 25 Jul 2016 22:57:53 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
SharePoint-CreateSharingLink-Error: Sharing by link is not enabled on the web, site, or tenant.
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 505
X-AspNet-Version: 4.0.30319
SPRequestGuid: 4367939d-b0c7-2000-0a07-34928f7d648c
request-id: 4367939d-b0c7-2000-0a07-34928f7d648c
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5507
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"
Date: Mon, 25 Jul 2016 22:57:54 GMT

{"error":{"code":"notAllowed","message":"The feature has been disabled. Please contact your admin to get it enabled."}}
```

These were both requests to create sharing links for `.docx` files, for a same user, in the same document library.

**Comment by ificator** [comment]
Thanks @dluces! These will be very helpful for debugging this.

**Comment by ificator** [comment]
Hi @dluces, can you confirm that for both the success case and the failure case that the same type of link was requested?

**Comment by dluces** [comment]
@ificator No. Actually, the one that failed was for `anonymous` access while the one that succeeded was for `organization` access. I just checked a few users and all the errors seem to be when sharing for anonymous access. That might be the feature that's disabled: external sharing. Sorry, I should have checked that earlier. If that's the case, could you point me to a resource about enabling such feature so I can pass it on to my client? Thank you.

**Comment by ificator** [comment]
Try the following:

https://support.office.com/en-us/article/Manage-external-sharing-for-your-SharePoint-Online-environment-c8a462eb-0723-4b0b-8d0a-70feafe4be85?ui=en-US&rs=en-US&ad=US

It seems to go into pretty good detail about sharing and the ramifications of the various options.

**Comment by dluces** [comment]
@ificator looks like this is not an issue anymore. The client decided to make the sharing links company-wide instead of enabling external anonymous sharing. I have been seeing a different error while retrying the creation of some of these links though. The server returns `Unable to determine the user associated with the provided token. App-only tokens are not supported for this scenario.` I've logged it as a different issue: #415
