### ISSUE TITLE
Creating a sharing link errors: "Unable to determine the user associated with the provided token"

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#415]
Sometimes, when creating a sharing link for ODB users, using an admin token, the servers return a `400 Bad Request` error: `Unable to determine the user associated with the provided token. App-only tokens are not supported for this scenario.`

Strangely, though, retrying the API request to create the sharing link on the same item sometimes fixes the issue.

This is a response for a failed request on one item:
```
HTTP/1.1 400 Bad Request
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Wed, 13 Jul 2016 01:27:59 GMT
Last-Modified: Thu, 28 Jul 2016 01:27:59 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 236
X-AspNet-Version: 4.0.30319
SPRequestGuid: a514949d-20e3-2000-0a08-0efe32fa3494
request-id: a514949d-20e3-2000-0a08-0efe32fa3494
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5507
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"
Date: Thu, 28 Jul 2016 01:27:59 GMT

{"error":{"code":"invalidRequest","message":"Unable to determine the user associated with the provided token. App-only tokens are not supported for this scenario."}}
```

This is the response from retrying the previous request:
```
HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Wed, 13 Jul 2016 01:27:59 GMT
Last-Modified: Thu, 28 Jul 2016 01:27:59 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 720
X-AspNet-Version: 4.0.30319
SPRequestGuid: a514949d-a0f6-2000-0a08-0e651e55c058
request-id: a514949d-a0f6-2000-0a08-0e651e55c058
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5507
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"
Date: Thu, 28 Jul 2016 01:28:00 GMT
```

Any ideas on what might be causing this issue? I couldn't find anything related to the error message and it seems strange that the provided token doesn't work in some requests but does in immediate retries. The request is the same in both cases.

**Comment by ificator** [comment]
Hi @dluces, do you know if this only happens once per user, or is it intermittent? The error suggests that the system couldn't find the user in question, which may suggest some kind of new user replication latency.

**Comment by dluces** [comment]
Hi @ificator, I've gotten the error in multiple files for a same user. Most of the sharing links are created successfully after some extra attempts. However, for one user, 4 sharing links failed to be created even after the ninth attempt (our limit). Then I have a handful of users for which only 2 sharing links failed to be created after the maximum number of attempts. 
Retrying the whole migration (so, creating all the links from scratch--the ones that succeeded and the ones that failed) for a same user ends up in the same sharing links failing to be created. I found that specially interesting, as if it had something to do with specific files. For one user, though, after a couple of times re-running their migration, it fixed one of the failing links. For the same user, a sharing link that was previously successfully created, failed to be created in the re-run.

**Comment by ificator** [comment]
Hi @dluces we drilled in a little and think we see the problem. The call that failed is hitting the my site host requesting /drive but the provided token is an app-only token. For that scenario we need the token to tell us the user who's drive is being targeted, which the app-only token fails to provide resulting in the 400. We're going to make a change so that this is more obvious, but to resolve you'll want to make sure any calls made using an app-only token are made directly against a users site (`https://tenant-my.sharepoint.com/personal/user/_api/...`) and not the my site host (`https://tenant-my.sharepoint.com/_api/...`).

**Comment by dluces** [comment]
Hi @ificator. That does makes sense. I added an extra check for the user-site instead of the company-wide site, and it does seem to be fixing this issue. Extra info on the error message would absolutely help as well. Thank you very much again.
