### ISSUE TITLE
item.htm says Create Folder using PUT?

### ISSUE THREAD

**Issue by firefoxNX** [OneDrive/onedrive-api-docs#416]
The page on https://dev.onedrive.com/resources/item.htm for 

> Create a Folder   PUT /drive/items/{parent-id}/children/{name}    PUT /drive/root:/{parent-path}/{name}

But https://dev.onedrive.com/items/create.htm has Create Folder using POST.

Does https://dev.onedrive.com/resources/item.htm need to be corrected?

**Comment by ificator** [comment]
Both are valid ways of creating a folder - you can either POST to children, or PUT directly to a name

`POST .../root:/path/to/parent:/children`
`POST .../items/<parentid>/children`

vs

`PUT .../root:/path/to/parent/newchildname`
`PUT .../items/<parentid>/children/newchildname`

**Comment by firefoxNX** [comment]
Thanks @ificator will try it out. Should https://dev.onedrive.com/items/create.htm mention the PUT API then?

**Comment by ificator** [comment]
It does seem a little inconsistent how different places mention different mechanisms. There's no doubt some tidying up to do.

**Comment by rgregg** [comment]
We cleaned this up already.
