### ISSUE TITLE
Use onedrive api to get user accountName(email address)

### ISSUE THREAD

**Issue by slunlun** [OneDrive/onedrive-api-docs#418]
Hi, I am using the Onedrvie API to get user account info. Is it possible to get user account email address according the API?
In the old liveClient API, I can get the eamil address by get user info "me".

**Comment by ificator** [comment]
The OneDrive API does not support getting user information. However, if you're accessing OneDrive via Graph it does have the capability you're after. Have a read of [this documentation](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_get).
