### ISSUE TITLE
Create upload session 400 bad request error when uploading large files using Resumable item upload 

### ISSUE THREAD

**Issue by MiniYellow** [OneDrive/onedrive-api-docs#419]
I was trying to upload a file larger than 100MB and the doc told me create a session before upload by fragments.  It seems rather simple however it always receives HTTP Error 400。Is something wrong。
Below is my request code in python.It works fine to request other apis.The requested url looks like this:
https://api.onedrive.com/v1.0/drive/items/C3D9CE*****63E7!60:/myFileName:/upload.createSession

def createSession(url,fileName,token):
    url+=':/'+fileName+':'+'/'+'upload.createSession'
    print(url)
    binary=json.dumps({'item':{"@name.conflictBehavior":"rename","name":"chuckedFile"}}).encode('utf-8')
    req = request.Request(url,binary,headers={'Authorization':'bearer '+token,'Content-Type': 'application/json'})
    responObj=request.urlopen(req)
    responContent=responObj.read()
    return responContent.decode('utf-8')

**Comment by rgregg** [comment]
I didn't see anything Ono he code that indicates your making his a 'POST' request instead of a GET request. Can you confirm the call to createSession is being POSTed?

**Comment by MiniYellow** [comment]
yes I'm sure.Here is the request trace:
send: b'POST /v1.0/drive/items/C3D9CEC5****3E7!3460:/1dmg:/upload.createSession HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-Length: 69\r\nAuthorization: bearer EwAIA61DBAAUG...XvNf9QpxlKo9YrtLcaxwl6qyalsiUCt/qKbSO4ZFFQAEsEC8B/uZ3Do/wE=\r\nConnection: close\r\nHost: api.onedrive.com\r\nContent-Type: application/json\r\nUser-Agent: Python-urllib/3.5\r\n\r\n'
send: b'{"item": {"name": "chuckedFile", "@name.conflictBehavior": "rename"}}'
reply: 'HTTP/1.1 400 Bad Request\r\n'

**Comment by ificator** [comment]
It's hard to categorically say without seeing the response body, but my guess is that in this case there's a inconsistency between the target name in the URL. In this case, the name in the URL is `1dmg` and the name in the body is `chuckedFile` and so we're probably throwing an error along the lines of `Inconsistency between document name provided in request body and url`

**Comment by MiniYellow** [comment]
Yes, I modify the name and it works! I thought the name in json text was to rename when filename conflict happens. Thank you very much !
