### ISSUE TITLE
wrong HTTP method used when requesting for access_token

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#42]
steps followed 
step 1) requesting for access_token, using the url on different clients
          a. firefox
          b. advanced REST client (crome addon)

POST https://login.live.com/oauth20_token.srf
Content-Type: application/x-www-form-urlencoded

client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}
&refresh_token={refresh_token}&grant_type=refresh_token

![request access_token firefoxclient](https://cloud.githubusercontent.com/assets/11455759/6775930/409b9e74-d15e-11e4-9259-3e0012239e6a.png)
![request access_token advanced rest client](https://cloud.githubusercontent.com/assets/11455759/6775931/40a6b61a-d15e-11e4-9f74-e404b92e5171.png)

*** following are the response received from different clients
1) advanced REST client (crome browser addon)
    Receiving the error, refer snapshot
![response access_token advanced rest client](https://cloud.githubusercontent.com/assets/11455759/6775933/52a6d25a-d15e-11e4-96ce-643d0f62cc10.png)

2) firefox broswer
     Successfully received access_token
![response access_token firefox](https://cloud.githubusercontent.com/assets/11455759/6775946/85a49430-d15e-11e4-9f1f-121f583d84ed.png)

comparison
![comparison](https://cloud.githubusercontent.com/assets/11455759/6776025/7110a2ba-d15f-11e4-853d-79a2e1386a0f.png)

when used GET method for the same from advanced REST client
successfully received access_token
![request access_token get advanced rest client](https://cloud.githubusercontent.com/assets/11455759/6776080/274065f2-d160-11e4-8273-5d66c432bfe7.png)
![response access_token get advanced rest client](https://cloud.githubusercontent.com/assets/11455759/6776079/27155b1e-d160-11e4-8c00-8500b2c47223.png)

so the request should be GET not POST(as mention in github page)

**Comment by rgregg** [comment]
You can use either GET or POST. In your example when doing POST, you put the parameters in the query string instead of the body of the POST request. As the docs say, those parameters should be included in the body of the POST request, not on the query string (Example in Step 2).

The documentation is correct for the flow it describes. While the GET method may work, using POST is our preferred approach.

**Comment by ankit-ankuagrawal** [comment]
ty sir, for ur response...

will be more careful while reading the docs (it was mistake on my part)

and ty once more
