### ISSUE TITLE
Error returned in plain-text when uploading file with long names

### ISSUE THREAD

**Issue by firefoxNX** [OneDrive/onedrive-api-docs#420]
**Request**
PUT /_api/v2.0/drive/items/01WWEXMHAA55FZYR7D3VHZPFE2JXLQVWIC/children/244_Chars_01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789.txt HTTP/1.1
Host: mysharepointonline.sharepoint.com
Connection: keep-alive
Content-Length: 244
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer eyJ....
Postman-Token: a514e669-8765-77b7-c97e-756e041511c5
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8

244_Chars_01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789.txt

**Response**
HTTP/1.1 401 Unauthorized
Server: Microsoft-IIS/8.5
SPRequestGuid: 49d4969d-20ad-3000-4500-e37ef5e95f01
request-id: 49d4969d-20ad-3000-4500-e37ef5e95f01
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
x-ms-suspended-features: features=""
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5528
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
WWW-Authenticate: Bearer realm="32ad0b3f-d2d3-47bd-a78f-98d10aed3c00",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@_,https://sts.windows.net/_/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
Date: Fri, 05 Aug 2016 14:24:58 GMT
Content-Length: 81
Connection: Keep-alive

The length of the URL for this request exceeds the configured maxUrlLength value.

File used for testing is attached.
[244_Chars_01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789.txt](https://github.com/OneDrive/onedrive-api-docs/files/403955/244_Chars_01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789.txt)

**Comment by firefoxNX** [comment]
Similar behavior when creating folder with name "aedsefrfesfxdsweafsergrdtbtnesdcserntyeetsreaegaedsefrfesfxdsweafsergrdtbtnesdcserntyeetsreaegaedsefrfesfxdsweafsergrdtbtnesdcserntyeetsreaegaedsefrfesfxdsweafsergrdtbtnesdcserntyeetsreaegaedsefrfesfxdsweafsergrdtbtnesdcserntyeetsreaegaedsefrfesfxdsweafse"

**Comment by ificator** [comment]
We made changes to the URL limits so this should hopefully be resolved.
