### ISSUE TITLE
Maximum length of driveID, itemID, webUrl?

### ISSUE THREAD

**Issue by DamirLisak** [OneDrive/onedrive-api-docs#421]
I want to store driveID's, itemID's and webUrl's to a database - but I don't know which maximum length I have to define for those fields because this is not documented here.

**Comment by ificator** [comment]
The drive and item ids are a consistent length (66 bytes and 34 bytes respectively) so those ones are easy. Unfortunately the length of the web url depends on the path to the item, and so it can grow relatively large - to be safe I'd probably allow it to have up to 4KiB.

**Comment by rgregg** [comment]
We don't define those limits as 66 bytes and 34 bytes though. You should ensure that you allow enough space for those identifiers to be larger in the future. I'd suggest a length more like 255 bytes for each identifier.
