### ISSUE TITLE
Listing of deleted items or recycle bin for Onedrive personal. apparently there is no endpoint available that works

### ISSUE THREAD

**Issue by DineshDhyani** [OneDrive/onedrive-api-docs#424]
I am trying to integrate onedrive personal in my web app using OAuth. 

there doesn't seems to be any endpoint available to list deleted items metadata that works.

I tried filtering using 
https://api.onedrive.com/v1.0/drive/root/children?filter=deleted eq yes

but it doesn't gives correct results.

Any suggestions would be highly appreciated.

**Comment by DineshDhyani** [comment]
@rgregg  could you please help?

**Comment by ificator** [comment]
Enumeration of deleted items (other than via delta) isn't supported by the system. Feel free to open something [on our UserVoice](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) and we'll look into it.
