### ISSUE TITLE
Azure-active-directory-certificate-rollover-august-15-2016 for ODB

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#426]
One of the customer received one mail (attaching the snapshot)
![certificate](https://cloud.githubusercontent.com/assets/11455759/17570271/570c3dae-5f69-11e6-8d4b-005318565414.PNG)

Found this announcement https://azure.microsoft.com/en-us/blog/upcoming-azure-active-directory-certificate-rollover-august-15-2016/ 

Can somebody comment over this.

What this all about, will the sign in process for onedrive business will effect my application post 15th Aug?

My application uses the procedure to login as describe in this git hub lib for onedrive business. 

What action has to be taken if necessary?

**Comment by rgregg** [comment]
This message is targeted at "resource protectors" or apps/services that integrate with AAD to enforce permissions. In most cases, apps that are using the OneDrive API are not in this category. As long as your app is only using the scopes documented in OneDrive API, and not creating your own scopes, this message can be safely ignored.

**Comment by ankit-ankuagrawal** [comment]
thank you for the reply
