### ISSUE TITLE
Should the OneDrive File Picker prompt for password everytime? I thought there would be token caching

### ISSUE THREAD

**Issue by jbarr33** [OneDrive/onedrive-api-docs#430]
Is this something that apps are supposed to implement somehow? 

I have an Angular app and I am already using ADAL.js for client implicit flow for my app.

Thanks.

**Comment by daboxu** [comment]
hi @jbarr33 , are you forced to prompt for password? In SDK 6.0 and 7.0, it should be prompted only for the first time or after the login has expired.

**Comment by jbarr33** [comment]
I haven't had a chance to get back to it.  I will follow up at some point later.  Thanks for the response.
