### ISSUE TITLE
General Exception for exapand=Children

### ISSUE THREAD

**Issue by praveenmb9752000** [OneDrive/onedrive-api-docs#431]
Hi ,

I am invoking below URL, but getting "generalException"
Request:
GET https://Tenant-my.sharepoint.com/personal/User/_api/v2.0/drive/root/view.delta?expand=children
Repsonse:
{
  "error": {
    "code": "generalException",
    "message": "An unspecified error has occurred."
  }
}

**Comment by rgregg** [comment]
You don't need (and shouldn't include) the expand=children part of this request. view.delta automatically enumerates all items in the hierarchy.
