### ISSUE TITLE
"Folder" facet  "childCount" always returns zero

### ISSUE THREAD

**Issue by praveenmb9752000** [OneDrive/onedrive-api-docs#432]
Invoking GET "https://tenant-my.sharepoint.com/personal/user/_api/v2.0/drive/root/view.delta" always retuns folder.childCount as zero.
eg:
      "folder": {
        "childCount": 0
      }

For all folders, even if there are files and sub folders inside all folders.
Also GET "https://tenant-my.sharepoint.com/personal/user/_api/v2.0/drive/root/view.delta/expand=children" gives out "General exception"

**Comment by ificator** [comment]
Hi @praveenmb9752000, this issue should now be resolved - please let us know if you're setting seeing problems.
