### ISSUE TITLE
Selecting for @content.downloadUrl is lost in delta pagination

### ISSUE THREAD

**Issue by jtippet** [OneDrive/onedrive-api-docs#433]
I reported this [here](https://github.com/OneDrive/onedrive-sdk-csharp/issues/154), and they said it's a doc bug.  So I'm filing a new bug on onedrive-api-docs.

Anyway, the repro is in the original bug: https://github.com/OneDrive/onedrive-sdk-csharp/issues/154

**Comment by ificator** [comment]
Hi @jtippet, this should now be resolved!
