### ISSUE TITLE
C# Sample for UWP is not available

### ISSUE THREAD

**Issue by ponarunkumar** [OneDrive/onedrive-api-docs#434]
The URL provided for the Sample OneDrivePhotoBrowsers UWP Windows/C# https://github.com/OneDrive/onedrive-sdk-csharp/tree/master/samples/OneDrivePhotoBrowser is not available
![image](https://cloud.githubusercontent.com/assets/6130502/17715929/8adbc270-63d4-11e6-8777-55b5d85d850a.png)
![image](https://cloud.githubusercontent.com/assets/6130502/17716023/e98e0242-63d4-11e6-8029-8b6feb6f3b43.png)

**Comment by cdmayer** [comment]
1. This project is no longer available in the master branch of that repository.
2. This repository is for the API Docs. Your issue is with the C# SDK. Please re-open this issue there. https://github.com/OneDrive/onedrive-sdk-csharp

**Comment by ponarunkumar** [comment]
Thanks cdmayer, looks like this link should be updated the latest one available at https://github.com/OneDrive/onedrive-sample-photobrowser-uwp. Appreciate your quick response!
