### ISSUE TITLE
Added shared folders are not listed in view.delta

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#438]
According to [working-with-links.md](https://github.com/OneDrive/onedrive-api-docs/blob/master/misc/working-with-links.md#using-viewdelta-with-remote-items) view.delta should return the shared folders contained in the drive.
However, in my tests after adding to my onedrive (not business) a shared folder from another account, the shared folder didn't get listed.

---

Content of my onedrive (only the shared folder):
![screenshot](https://cloud.githubusercontent.com/assets/10778434/18130443/6e2a4afe-6f8f-11e6-8ead-6021aa822315.png)

---

Output of `https://api.onedrive.com/v1.0/drive/items/root/view.delta?select=id,name,eTag,cTag,deleted,file,folder,fileSystemInfo,remoteItem,parentReference`:

```
{
  "@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives('me')/items(id,name,eTag,cTag,deleted,file,folder,fileSystemInfo,remoteItem,parentReference)",
  "@delta.token": "...",
  "value": [
    {
      "id": "D4FE0EE4D78A90DC!106",
      "name": "root",
      "eTag": "aRDRGRTBFRTRENzhBOTBEQyExMDYuMQ",
      "cTag": "adDpENEZFMEVFNEQ3OEE5MERDITEwNi42MzYwODI0NjQ5NTcwMzAwMDA",
      "folder": {
        "childCount": 0
      },
      "fileSystemInfo": {
        "createdDateTime": "2015-11-28T08:15:04.683Z",
        "lastModifiedDateTime": "2016-06-29T19:38:29.56Z"
      },
      "parentReference": {
        "driveId": "d4fe0ee4d78a90dc",
        "id": "D4FE0EE4D78A90DC!0"
      }
    }
  ],
  "@odata.nextLink": "..."
}
```

**Comment by ificator** [comment]
Duping to #488 since it has more traction.
