### ISSUE TITLE
[ODB] get default drive would not return owner user id

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#439]
Question 1 : 
my accounts have different response

```
first one
"owner": {
    "user": {
      "id": "c856xxxx-83d6-xxxx-xxxx-37f6e78fce50",
      "displayName": "synoxxxxxxlogy"
    }
 },
```

```
second one missing it
"owner": {
    "user": {
      "displayName": "Mixxxxx xxxhl"
    }
  },
```

Is it a policy or just missing?

Question 2 : 
Is drive id unique for all identification which get for get_default_drive request ?

```
"id": "b!vtO10YnDJkKu0bJxtEdqXXXXXXXXXXku6WYto7ztSpnQfeVSQq_p",
```

thank you for help!

**Comment by ificator** [comment]
This is really old so the answer probably isn't of use to you now - I apologize for that.

Question 1: There are some identities that do not have an "id" as defined by AAD - "system" identities in SharePoint are a good example,

Question 2: The drive id should be globally unique.
