### ISSUE TITLE
Lock a file

### ISSUE THREAD

**Issue by cguZZman** [OneDrive/onedrive-api-docs#440]
Hi there. 
How can I request to lock/unlock a file? I can see that Word and Excel locks/unlocks a document when the user is working on the file. I need exactly the same feature. Hope you can help me.
Thanks!

**Comment by cguZZman** [comment]
Any update on this? :)

**Comment by ificator** [comment]
Unfortunately, there isn't any mechanism exposed to control locks via the OneDrive API. Head on over to [our UserVoice page](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) and make sure that your request has some visibility.
