### ISSUE TITLE
Expand or batch permissions

### ISSUE THREAD

**Issue by dzeppa** [OneDrive/onedrive-api-docs#441]
My application (using OneDrive for Business) needs to read the permissions of all files in a user's account. Currently this is done by first calling '/view.delta' or '/children' and then calling '/permissions' for each item. Of course this is not very efficient requiring a separate request for each file.

Ideally, I would be able to call '/view.delta?expand=permissions', but this returns invalidRequest.

I also tried using OData request batching (https://msdn.microsoft.com/en-us/library/office/dn903506.aspx), but it seems I can only send a max of 5 '/permission' requests before I get errors in the batch response. It's also incredibly slow to the point that sending the requests individually is actually faster. 

Is something else like this supported in the API, or are these bugs that need fixing?

**Comment by bdares** [comment]
OneDrive for Business appears not to support attaching permissions to items via expand: https://dev.onedrive.com/items/permissions.htm

> Permissions cannot be expanded on lists of items or a single item. You must access the permissions property directly.

Will update with workarounds if I discover any.

**Comment by rgregg** [comment]
This isn't supported right now. Please considering adding this to the [developer suggestions UserVoice](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer).

**Comment by bdares** [comment]
OneDrive.com does offer this information in the UI.  Checking the network traffic for that site, I found that the browser makes calls to SharePoint APIs, e.g:

```
POST https://foo-my.sharepoint.com/personal/bdares_foo_onmicrosoft_com/_api/web/GetList(@listUrl)/RenderListDataAsStream?@listUrl=%27%2Fpersonal%2Fbdares%5Ffoo%5Fonmicrosoft%5Fcom%2FDocuments%27&View=&SortField=LinkFilename&SortDir=Asc
```

While this is clearly out of scope for OneDrive API, it is required if we want programmatic access to OneDrive behavior.
