### ISSUE TITLE
XMLHttpRequest doesn't pass preflight

### ISSUE THREAD

**Issue by rwrobe** [OneDrive/onedrive-api-docs#442]
This issue is exactly the same as this [SO ticket](http://stackoverflow.com/questions/29425390/onedrive-oauth-token-request-gets-cors-error). I'm using the code access flow to request an auth token, but am unable to use the server response because there is no Access-Control-Allow-Origin header. I believe I'm making a simple request, using the exact code from the [example in the docs](https://dev.onedrive.com/misc/working-with-cors.htm), but without the Authorization header on the request (because I don't have it yet).

I believe this is related to #66

**Comment by rwrobe** [comment]
Just for completeness, here's my code:

```
var onAuthCallback = function ( secret ) {
		var auth_code = getAuthInfoFromUrl(),
			appInfo = getAppInfo(),
			url = 'https://login.live.com/oauth20_token.srf',
			params = 'client_id='
			         + appInfo.clientId
			         + '&redirect_uri='
			         + appInfo.redirectUri
			         + '&client_secret='
			         + secret
			         + '&code='
			         + auth_code
			         + '&grant_type=authorization_code',
			method = 'POST',
			xhr = createCORSRequest( method, url );

		xhr.setRequestHeader( "Content-Type", "application/x-www-form-urlencoded" );

		xhr.onload = function () {
			successCallback( JSON.parse( xhr.responseText ) );
		};

		xhr.onerror = function () {
			console.log( xhr.responseText );
		};

		xhr.send( params );
	};

var createCORSRequest = function ( method, url ) {

		var xhr = new XMLHttpRequest();

		if ( "withCredentials" in xhr ) {
			// Most browsers.
			xhr.open( method, url, true );
		} else if ( typeof XDomainRequest != "undefined" ) {
			// IE8 & IE9
			xhr = new XDomainRequest();
			xhr.open( method, url );
		} else {
			// CORS not supported.
			xhr = null;
		}

		return xhr;

	};
```

**Comment by rgregg** [comment]
You can't use code grant flow with a single-page web application because the OAuth2 token endpoint cannot (and should not) support CORS. There is a good write-up of how to authenticate a client-side JavaScript app using Token flow, including how to silently refresh your token if your app continues to run for longer than the original token is valid for, here: https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-protocols-implicit/#get-access-tokens
