### ISSUE TITLE
Typo in "onedrive-api-docs/sdk/js-v7/js-picker-overview.md"

### ISSUE THREAD

**Issue by gregdegruy** [OneDrive/onedrive-api-docs#444]
In step 3.1

Current
Click Generate New Password to create an Application secret. While this value is not necessary for the picker, it must _**have been**_ created.

Proposed change
Click Generate New Password to create an Application secret. While this value is not necessary for the picker, it must _**be**_ created.

I am an FTE in USDX in the bay area and want to help contribute to our OSS docs in anyway that I can!

Greg

**Comment by rgregg** [comment]
Please consider sending a pull request.

**Comment by gregdegruy** [comment]
Understood will send once back at PC.
