### ISSUE TITLE
Why I always get a 401 unauthorized when uploading fragments of resumable item upload in OneDrive API?

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#446]
I'm developing a web app with the OneDrive API for OneDrive for Business, but I meet a problem that I always get a 401 unauthorized when uploading fragments of resumable item upload. I'm sure that I have sent a access_token key and even I still get a 401 using a new access_token key from refresh access_token codes.

**Comment by ificator** [comment]
Hi @imkk - in the headers for the response that returned the 401 there should be a `request-id` value... can you give that to us? It'll help us see what's going on.

**Comment by imkk** [comment]
Hello @ificator , I'm sorry to reply to you for a long time. In fact, on the next day after I asked this question I found it's alright for most of files to upload except a file with a name: "《鸟哥的Linux私房菜-基础篇》.pdf", and this is the header info you need: _request-id: 914ba59d-a084-3000-b1bf-992f6a196057_.

**Comment by ificator** [comment]
I'll close this issue since we have a new one tracking the same thing.
