### ISSUE TITLE
File rename - when renaming to file which already exists, existing file gets deleted

### ISSUE THREAD

**Issue by firefoxNX** [OneDrive/onedrive-api-docs#447]
I have two files 1.jpg and 2.jpg in a folder. When I rename 1.jpg to 2.jpg I am seeing that 1.jpg is renamed to 2.jpg and 2.jpg is deleted. API call to rename -

`curl -X PATCH -H "Authorization: Bearer xxx" -H "Accept: application/json" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{"name":"2.jpg"}' https://mysharepointonline.sharepoint.com/_api/v2.0/drive/items/<ID of 1.jpg>`

Shouldn't the API return some error message?

**Comment by shoaibadil** [comment]
I observed the same issue as well. It should have return the error or renamed the file with some prefix but instead its deleting the file having same name.
Weird behavior.

**Comment by ificator** [comment]
Hi all, this issue should now be resolved - please let us know if you're still seeing it!

**Comment by firefoxNX** [comment]
Thanks @ificator I am getting 409 with response body
```
{
  "error": {
    "code": "nameAlreadyExists",
    "message": "The specified item name already exists."
  }
}
```
