### ISSUE TITLE
Access Denied for trying to access /_api/v2.0/drive/

### ISSUE THREAD

**Issue by ismailseyfi** [OneDrive/onedrive-api-docs#449]
Hey, 
I am trying to create a server side application to programmatically upload some files to OneDrive. I set up an application in our Azure Management Portal. I am using OAUTH2.0 client_credentials grant_type. 

I am able to get access token generated when I make a request to the following token endpoint.

https://login.microsoftonline.com/{tenant}/oauth2/token

As part of this call, I am supplying my client_id, client_credentials, redirect_uri, and resource. The resource value I set is https:{tenant}-my.sharepoint.com. 

Once I have this bearer token I was trying to do a simple GET call to the 

https://{tenant}-my.sharepoint.com/_api/v2.0/drive/ API to see if I would get a 200 response. Access token I got from the call above is supplied to this call as an Authorization Bearer header. 

I get a 401 instead of 200 with the following error. 

{
  "error": {
    "code": "-2147024891, System.UnauthorizedAccessException",
    "message": "Access denied. You do not have permission to perform this action or access this resource."
  }
}

When I registered this application in our Azure Management Portal, Office 365 Applications with delegated permissions "Read user files" and "read/write user files". Is that not enough? Am I missing steps here? Thanks for your help.

**Comment by castorix** [comment]
I don't use Azure but when I connect to OneDrive with REST APIs,  I must specify a SCOPE (wl.signin, wl.basic, wl.skydrive, etc...)
(https://msdn.microsoft.com/en-us/library/office/dn659750.aspx)

**Comment by ismailseyfi** [comment]
Thanks. I will try that to see if it helps. For the time being, I ended up resolving this by using the graph API instead of the /_api/v2.0/drive. I ended up changing the resource to https://graph.microsoft.com/ and getting my access token with it. Once I had the access token, I could then access the graph apis with it including drive.

**Comment by greatBigMassive** [comment]
I am having exactly the same problem. I have done everything exactly as it says to do at the [OneDrive for Business authentication and sign in](https://dev.onedrive.com/auth/aad_oauth.htm#step-3-discover-the-onedrive-for-business-resource-uri) page and everything works fine all the way until I do the very very last part. The access token is being sent, I know that for a face as I use the same function to send the Bearer in the first request.  Something isn't right and yes, I can see in my Azure AD that I have all the permissions but there doesn't seem to be any counts on "scope".  I may try the graph option too because I have already raised a full ticket about this and nobody is answering the question.

**Comment by rgregg** [comment]
@ismailseyfi : We don't officially support client_credentials grant for OneDrive API currently. We're working on that support, but it's not there yet.

@greatBigMassive: Are you using client_credentials grant, or a regular user sign-in as documented on the page you linked? Dd you register your application through portal.azure.com or another location?

**Comment by anildbest83** [comment]
Hi @rgregg 

Call to /_api/web/getFolderByServerRelativeUrl('/Shared%20Documents')  was working fine but suddenly it is returning error now

code=-2147024891, System.UnauthorizedAccessException
value=Access denied. You do not have permission to perform this action or access this resource.

Any suggestion.

**Comment by greatBigMassive** [comment]
I can confirm this was resolved. It was an encoding issue on my side.
