### ISSUE TITLE
[Question] Why not official onedrive app from android play store doesnt ask for Apploication Id generated from Azure Portal

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#450]
Was using official app of onedrive to access onedrive business, and app never ask for application id from azure portal, which is necessary for developer to create and give during login process.

More over on providing email id and password, got logged in successful.

Why it is that the official app doesnt requires application id created from azure portal for login process?

**Comment by rgregg** [comment]
Application IDs identify the application making requests to the service. An app should never prompt the user to enter an application ID, since that's something the developer must take care of. The developer registers their app with Azure Active Directory, gets an application ID, and then uses that to get authentication tokens. The official OneDrive app has it's own application ID that's hard coded in the app, just like 3rd party apps do.

**Comment by ankit-ankuagrawal** [comment]
@rgregg Thank for the reply.

I knew that app Id must be hard coded in the app and should never be prompted by the app.

But the application must be created in once azure portal na ( customer )also we must provide the permission to access files etc?

Though we never created any thing for official app on once azure portal, how it is able to access the details and able to login?

**Comment by rgregg** [comment]
The app registration (done by the developer) defines the permissions the app requires. This is true for all apps.

When a user logs into a 3rd party application the user is required to consent to the permissions required by the app. Microsoft applications accessing Microsoft services do not show the consent screen and consent is automatically granted, as the app and service involved are both owned by Microsoft.

**Comment by ankit-ankuagrawal** [comment]
@rgregg thank for quick update on this...

The whole point for checking was that we have customer, who want that there employees should not be able to login through official ondrive app or 3rd party apps available at play store.

Can be accessible from only one app that is register on there azure portal.

Is there a way to restrict such cases?
