### ISSUE TITLE
OneDrive for Business API search: cannot search by filename using filter & search results missing property "path"

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#451]
I have two problems: 
1. I can not search by filename using the filter function, such as "_?q=searchwrod&name eq 'searchword'_". 
2. The results miss the property "_path_" contained in property "_parentReference_".

**Comment by danjarvis** [comment]
In #207 it is mentioned that `path` is not present in the `parentReference` object in the search response. This was from October 2015 and I was hoping it was resolved by now... it appears that is it not.

Any chance we can get an update on this @rgregg :)

Thanks!

**Comment by imkk** [comment]
@danjarvis, Thank you to tell me this. I'll have a try to check it.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
