### ISSUE TITLE
How to access non-admin user files when logged on as admin user

### ISSUE THREAD

**Issue by jtdiehl** [OneDrive/onedrive-api-docs#453]
Hi,

I am trying to create an application that requires the following.
1. It will run under an admin user that got tokens via authorization code
2. It will be able to request and get a list of users to which the admin user has access
3. It will be able to download,create,edit or delete on the drives of each of the users to which the admin user has access. 

Is this possible? 

I am currently running this process.
1. Get access token, refresh token, service url and tenant id for signed on admin user via Azure Active Directory
    - https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id={client-id}&redirect_uri={redirect-uri}
2. Get all user accounts accessible to signed on admin user for whom the tokens were requested
    - Request url: https://graph.microsoft.com/v1.0/users
    - Need an app-only access token for this request using the following request to get it:
        - URL: https://login.microsoftonline.com/<my-tenant-id>/oauth2/token
        - Request Body: grant_type=client_credentials&client_id={client-id}&client_secret={client-secret}&resource=https://graph.microsoft.com/
3. For each user in the list gotten from step #2 above, the contents of their drive are enumerated using the following request on each folder on the drive
    - Request URL: <Service Endpoint URL>/drive/items/<folder-id>/children 
4. For each file in the list created in step #3, the file is downloaded with one of the following requests:
    - Request URL using file id: <Service Endpoint URL>/drive/items/<file-id>/content
    - Request URL using file path: <Service Endpoint URL>/drive/root:/<file-path>:/content

Step #'s 1 and 2 are working, but step #'s 3 and 4 only work when processing the admin user, but not for any non-admin user in the list. 
Is this possible? 
I have not been able to find any documentation for how it might be done.
I have implemented this process for three other cloud providers (Box, Dropbox and Google Drive) and they all use impersonation where I specify the user id to impersonate in the header.

Any advice about how this might be accomplished is appreciated

**Comment by elegault** [comment]
+1!

**Comment by jordancoll** [comment]
I don't think this is possible using the OneDrive API.
Try using the [Graph API](https://github.com/microsoftgraph/msgraph-sdk-python)

**Comment by elegault** [comment]
Actually I discovered that it is, see: https://github.com/OneDrive/onedrive-sdk-csharp/issues/42

**Comment by jordancoll** [comment]
@elegault hahaha i already rewrote everything to use graph fml :sob:

**Comment by jtdiehl** [comment]
Thanks to all for the suggestions, but I'm not getting anywhere. I need details and specifics on how the suggestions were done. I have too too many moving parts and I've not been able to determine which is right and which is wrong and needs to be changed. 
I'm not using the sdk, so anything using the OneDrive client (as I see in the onedrive-sdk link above) is not going to help much. 
I am doing everything with web requests in c++ using the casablanca REST library. 
I've been working the Graph API approach and have done the following
1. In azure, in the account hostimg my app, I have my app config set to have all permissions selected for Microsoft Graph, Office 365 SharePoint Online and Windwos Azure Active Directory. I selected all permissions to just get through the functional part and then I would figure out and remove the permissions that weren't needed after it worked.
2. Get a access token for graph api using this:
   https://login.microsoftonline.com/<tenantid as generated from the AAD auth process>/oauth2/token?grant_type=client_credentials&client_id=<client_id>&client_secret=<client_secret>&resource=https://graph.microsoft.com

3. Get a list of users with this:
   https://graph.microsoft.com/v1.0/users
   Headers: Authorization = Bearer <access token gotten from step #2 above>
4. For each user returned for previous call, get the users drive with this:

   https://graph.microsoft.com/v1.0/users/<user id from id value in previous call response>/drive
   Headers: Authorization = Bearer <access token gotten from step #2 above>

   5. Get a list of files in the root dir of the drive gotten from previous call with this:
   https://graph.microsoft.com/v1.0/drives/<drive id from id value in previous call response>/item/<folder id>/children
   Headers: Authorization = Bearer <access token gotten from step #2 above>
6. For each file returned for previous call, get the value of @microsoft.graph.downloadUrl and send request to that url to download the file.

The call in step #6 always returns response code of 401/unauthorized even on the admin account. I have no idea what to do next. Someone please let me know where I am going wrong on this or if there is a better way to do it. As I wrote at the beginning, I need specifics and not "This worked for me" as I don't know how to do that. 

Thanks in advance

**Comment by edmj** [comment]
@jtdiehl From what I can make out, to download a file using the client_credentials (aka App only) flow, you need to use a **client certificate** (e.g. ClientAssertionCertificate) not just a client secret.  See this comment by @Deblanko: https://github.com/OneDrive/onedrive-api-docs/issues/280#issuecomment-196236706 - although I've been unable to find anywhere else this is actually documented...

And then I think you **also** need to fall back to using the SharePoint REST API 'GetFileByServerRelativeUrl'  workaround suggested by @rgregg earlier in the same thread: https://github.com/OneDrive/onedrive-api-docs/issues/280#issuecomment-180004564 to then download the file.

Happy to be corrected if that's no longer true or there's an easier way, as I'd like to know it myself.

I've got a similar scenario to you working by using the combination of those two steps, but would prefer it if you could just use a client secret instead and request the @microsoft.graph.downloadUrl url with the Bearer token or something similar.
