### ISSUE TITLE
Conditionally load Javascript SDK

### ISSUE THREAD

**Issue by hoetmaaiers** [OneDrive/onedrive-api-docs#454]
I would like to conditionally load my javascript sdk depending on some application settings. Loading the sdk happens this way:

``` javascript
var oneDriveScript = window.document.createElement('script');
oneDriveScript.setAttribute('type', 'text/javascript');
oneDriveScript.setAttribute('src', 'https://js.live.net/v7.0/OneDrive.js');
window.document.body.appendChild(oneDriveScript);
```

I supposed this would work (it did in version 5) but now the popup opens with my redirectUrl. When I add the `<script />` directly in my index.html it works as expected. 

**Question**: Is there a possibility to load the OneDrive SDK conditionally after page load?

**Comment by KevinTCoughlin** [comment]
The above issue is outside the scope of the library and implementation specific in user-land.

One should be able to dynamically (lazily) load the script and invoke it. This requires additional information to debug if indeed a library problem however unlikely.
