### ISSUE TITLE
Refresh token missing from json response (OD4B)

### ISSUE THREAD

**Issue by amagliul** [OneDrive/onedrive-api-docs#455]
Hi,
We've noticed that the refresh token is missing from the login.microsoftonline.com/common/oauth2/token response for some users. This is during what is listed as Step #4 here: https://dev.onedrive.com/auth/aad_oauth.htm

So far the users I have investigated for this all have purchased Office 365 from Godaddy. I'm not sure if its is relevant or just a coincidence. 

Any ideas? I can provide some diagnostic info, if needed.

Thanks!

**Comment by amagliul** [comment]
Hi,
I was curious if there were any ideas on this one. So far every user complaining of this is a GoDaddy Office 365 user. It seems consistent enough that I have to assume it is linked to something specific in the OAuth flow against these particular accounts.

**Comment by amagliul** [comment]
Just pinging this thread again.
We continue to have GoDaddy users that are unable to properly utilize the OneDrive API via our client, because the refresh token is missing from the response during oauth.

Is there anything we can do here? Are 3rd party providers like GoDaddy not supported by the API?

**Comment by rgregg** [comment]
@amagliul Would you be able to get a Fiddler trace of the login where this doesn't work, or alternatively the full request / response from a scenario where you don't get a refresh token?

**Comment by amagliul** [comment]
Thanks for the response. I will see what I can do. I don't have access to a GoDaddy account, myself, but I'll try to work with one of the affected users.
