### ISSUE TITLE
Simple item upload limit is wrong

### ISSUE THREAD

**Issue by sloba88** [OneDrive/onedrive-api-docs#459]
I get back "413 Request Entity Too Large" when I try simple upload using PUT for all the files around ~8MB. Files less than that work just fine.

In documentation it clearly says that limit is 100MB which seem not to be true. What is the correct limit?

**Comment by ificator** [comment]
Hi @sloba88, can you tell us whether your hitting the Business or Consumer endpoint? Either way, an 8MB file should definitely be fine.

I believe Microsoft Graph has a lower limit that could be around 8MB (I know it was 4MB at one point but it's possible it's been bumped up), so if you're accessing OneDrive via Graph that would explain it.

**Comment by sloba88** [comment]
Hi,

yeah that was exactly the case, we were using Graph. It's a bit confusing because they are both very similar yet different things that have mostly same features, especially related to OneDrive.
