### ISSUE TITLE
support for MD5 checksums

### ISSUE THREAD

**Issue by ddurdle** [OneDrive/onedrive-api-docs#46]
This is a request to support MD5 checksum.  Google Drive provides this value as part of their API, way back to their original API.  It comes in handy to have a MD5 value to check to validate the integrity of files.

**Comment by rgregg** [comment]
Hi @ddurdle! We have SHA1 hashes available on all items today, and crc32 hashes available on most items. The hashes are available on an item:

```
{
"id": "1234567890",
"name": "hello.txt",
"file": {
  "hashes": {
    "sha1Hash": "aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d",
    "crc32Hash": "3d653119"
  }
}
```

**Comment by ddurdle** [comment]
wow, this is great!  Can't wait to implement this API in my app!

**Comment by rgregg** [comment]
Since we include sha1 and crc32, I'm closing this under the assumption that adding MD5 isn't a priority. If it is, please add the issue to our [UserVoice](http://onedrive.uservoice.com) page so others can vote for the priority of this.

**Comment by ddurdle** [comment]
I went ahead and posted it to UserVoice.  I believe because Amazon and Google provide only MD5 checksum values, not having them in OneDrive makes it challenging to validate file integrity when import/exporting between storage providers.

**Comment by lanatmwan** [comment]
OneDrive personal doesn't seem to populate Crc32 now and sha1 is the only option. Is that correct?

**Comment by ificator** [comment]
@chackman can you follow up and see if the CRC32 behavior has changed?

**Comment by lanatmwan** [comment]
After I posted this, I think I saw a piece of documentation that indicated crc32 doesn't get populated unless you actually download the file. I'm not downloading anything so that may be it. Other than being slower, sha1 is perfectly fine for my needs and that is working fine.

**Comment by chris2crawford** [comment]
One argument for MD5 also is the ability to compare with existing MD5 checksums from another source when verifying cloud2cloud services, for example.

**Comment by gmctec** [comment]
An actual way to do so (other than json coding) would be appreciated for us non-developers
