### ISSUE TITLE
FilePicker with save option. How can I gracefully handle file name conflict?

### ISSUE THREAD

**Issue by mkosieradzki** [OneDrive/onedrive-api-docs#460]
When using file picker with 'save' option existing files are not shown in folders.
When user saves file to a folder which contains file with conflicting name dialog files. What options can I pass to make it gracefuly handle such a case? Even automatic generation of new name should be enough. 

In a perfect solution user would be allowed to rename the file.

**Comment by daboxu** [comment]
hi @mkosieradzki for OneDrive Business account, the 'save' action will fail and for OneDrive Consumer account, it will rename the file. It is tricky there due to the different APIs' behavior. I will add an enhancement label here and will provide this option in the future.

**Comment by rgregg** [comment]
It seems like we should allow specifying the @name.conflict behavior for the file picker, so that you can choose if you want to overwrite, rename, or abort the upload if there is a conflict.

**Comment by daboxu** [comment]
@mkosieradzki thanks for your feedback, this feature is included in our [new v7.2 SDK](https://dev.onedrive.com/sdk/js-v72/js-picker-save.htm#parameters).

```
options = {
    nameConflictBehavior: "rename", // or "replace", "fail"
}
```

**Comment by mkosieradzki** [comment]
Thanks a lot!

**Comment by dethier1958** [comment]
The nameConflictBehavior option seems to be ignored when I try it with the file picker and the save option. It just replaces any existing file.
