### ISSUE TITLE
Why does FilePicker require full access to drive content for saving a file?

### ISSUE THREAD

**Issue by mkosieradzki** [OneDrive/onedrive-api-docs#461]
I don't understand why does filepicker require full access to the onedrive consent instead allowing user to pick a folder and upload provided data?

It does not sound really right. There is a huge difference between user-supervised access to OneDrive (file picker) and automatic access by an application.

**Comment by rgregg** [comment]
[Version 6](https://dev.onedrive.com/sdk/js-v6/js-picker-save.htm) of the File Picker SDK does work this way. The app has no long term permissions granted to it to enable the file picker scenario.

Version 7 uses the Microsoft Graph API to actually upload files to OneDrive / OneDrive for Business, and Microsoft Graph doesn't support the concepts necessary for "contextual consent" like we used in Version 6. This is an open issue that we're working on resolving for a future update to Version 7.

**Comment by mkosieradzki** [comment]
@rgregg Thanks for explanation. I supposed it was related to the direct graph API usage. Looking forward to this update :).

**Comment by mrawdon** [comment]
@rgregg is there any progress on this?  Or anywhere we can track the opened issue you've mentioned

Thanks

**Comment by rgregg** [comment]
I opened #630 to allow tracking this work.
