### ISSUE TITLE
OneDrive Client cannot sync (download) OneNote NoteBook files

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#462]
As the title suggests - unable to sync OneNote NoteBook files from OneDrive to local a source using a Linux client (https://github.com/skilion/onedrive) - see https://github.com/skilion/onedrive/issues/110 for further information. 

Apigee has removed OneDrive from it's console, so cannot test there at the moment to see what is actually going on, however I suspect the .one files are not being added to the view.delta response when the client is checking for new or updated files.

The expected outcome would be that the OneNote files (.one) are able to be sync'd locally upon request.

Any suggestions on providing more details to help analyse / resolve?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
