### ISSUE TITLE
OneDrive for Business API resumable upload.createSession: returns 200 invalidRequest

### ISSUE THREAD

**Issue by devova** [OneDrive/onedrive-api-docs#465]
```
POST /_api/v2.0/drive/items/01W2E4KBTLWQEUUYGCEJBL7PBKNO6QGS32:/IMG_2493.jpg:/upload.createSession
Host: <tenant>-my.sharepoint.com
Content-Type: application/json
Authorization: Bearer {INSERT_TOKEN}
Accept: application/json;odata=verbose

{'item': {'@name.conflictBehavior': 'replace'}}
```

I've got HTTP 200

```
request-id: 1735b19d-b07b-2000-b2ad-d00be8fc59fd
SPRequestGuid: 1735b19d-b07b-2000-b2ad-d00be8fc59fd
X-AspNet-Version: 4.0.30319

{"error":{"code":"invalidRequest","message":"The request is malformed or incorrect."}}
```

It's only with OD4B, personal drive works well

**Comment by rgregg** [comment]
We'll take a look. I wasn't able to reproduce this behavior in ODB, but I'll look at the request ID you included and see what's going on. When were you getting this response?

**Comment by devova** [comment]
Hostname is insuredhealthgroup-my.sharepoint.com

**Comment by devova** [comment]
Bad header `Accept: application/json;odata=verbose` had been sent.
Need just `application/json` without `odata=verbose`

**Comment by ificator** [comment]
Thanks @devova - seems like we could improve the error message!

The OneDrive API is OData v4 compliant, and so if you want verbose metadata you can do:

`Accept: application/json;odata.metadata=verbose`
