### ISSUE TITLE
When will FileSystemInfo property be available for SharePoint or OneDrive for Business?

### ISSUE THREAD

**Issue by EricWarnke** [OneDrive/onedrive-api-docs#466]
The FileSystemInfo property is not available for items in SharePoint or OneDrive for Business. This is the only thing forcing us to us the old SPO Migration API. We'd massively prefer to just use the OneDrive API but are forced to do some crazy hybrid of the two.

Any timelines for implementing this?

**Comment by Tekki** [comment]
The FileSystemInfo is now available: #544

**Comment by rgregg** [comment]
Tekki is correct, we've now shipped support for FileSystemInfo on ODB and SharePoint.
