### ISSUE TITLE
If conflictBehavior is set to rename, Item resource is returned for original file instead of newly created one

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#47]
Hi,

I'm experimenting with the resumable item upload.  Since I haven't implemented the other upload methods yet, I don't know if this issue is isolated to this upload method.

I'm setting the "@name.conflictBehavior": "rename" option in the upload session, and uploading a simple file.

When the file is completely uploaded, I get a 201 created response from the server.  However, the server response body contains the information about the original file.

For example, I'm uploading "a.txt", which already exists.  I try to upload "a.txt" with the conflict behaviour set to rename.  It correctly creates the file ("a 1.txt", for example).  However, the response contains the Item resource for the conflicted file name ("a.txt") and not the newly created one.  

I don't see how I can get the correct Item resource for the newly created file.

**Comment by ificator** [comment]
This is most definitely a bug, we'll get it fixed ASAP!

**Comment by ificator** [comment]
This should now be resolved.
