### ISSUE TITLE
[ODB] encounter 401 with Insufficient memory within specified address space range to continue the execution of the program.

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#475]
hello,

my app receive this
```
[code] 
401 

[msg] 
Insufficient memory within specified address space range
to continue the execution of the program.
```

I want to know in this situation
it is correct pair code and msg to handle Insufficient memory in my place error
or something goes wrong?

if it does, what is the suggestion to handler this error on my app side

thank you!

**Comment by katahir** [comment]
Hello joewutaiwan,
Sorry to hear you are having trouble. Do you have the response headers that got returned with the request as well? That would help get the logs and trouble shoot the issue. Was it a one-time error, or does your app run into this error frequently?

**Comment by joewutaiwan** [comment]
@katahir 
Sorry for late reply,
This case is one of my user encountered.
I could not reproduce this case frequently.
I think it is a one-time error, so thanks for your help!
