### ISSUE TITLE
At least one part is missing its Content-Disposition header

### ISSUE THREAD

**Issue by jwb001** [OneDrive/onedrive-api-docs#478]
what is this?
This is my Multipart upload to OneDrive using POST
Request URL:https://api.onedrive.com/v1.0/drive/items/D72D39CD1CFF80A0!451/children
Request Method:POST
Status Code:400 Bad Request
Request Headers
Provisional headers are shown
Accept-Encoding:gzip
Authorization:Bearer EwAAA61DBAA...
Connection:Keep-Alive
Content-Type:multipart/form-data; boundary=e2906d30-e3b1-4d69-b4dc-80ee8c832e58
Host:api.onedrive.com
Transfer-Encoding:chunked
User-Agent:okhttp/3.2.0
Request Payload
```
--e2906d30-e3b1-4d69-b4dc-80ee8c832e58
Content-ID: <metadata>
Content-Type: application/json; charset=UTF-8
Content-Length: 95

{"name":"1.png","file":{},"@content.sourceUrl":"cid:content","@name.conflictBehavior":"rename"}
--e2906d30-e3b1-4d69-b4dc-80ee8c832e58
Content-ID: <content>
Content-Type: image/*
```
But the answer of server is 
error: {code: "invalidRequest", message: "At least one part is missing its Content-Disposition header"}
code: "invalidRequest"
message: "At least one part is missing its Content-Disposition header"
I did not know what happen



**Comment by rgregg** [comment]
Not sure if it's just a typo, but the end of the request needs the closing multipart signature, which in your case should be `--e2906d30-e3b1-4d69-b4dc-80ee8c832e58--`. Without that, the server will likely return the error message you're seeing, since it doesn't know where the part ends.

**Comment by jwb001** [comment]
Hello rgregg,I am sorry that it is a typo,Now the whole request is

Request URL:https://api.onedrive.com/v1.0/drive/items/D72D39CD1CFF80A0!451/children
Request Method:POST
Status Code:400 Bad Request
Request Headers
Provisional headers are shown
Accept-Encoding:gzip
Authorization:Bearer EwAAA61DBAAUGCCXc8wU/zFu9QnLdZXy+........
Connection:Keep-Alive
Content-Type:multipart/form-data; boundary=fb6cb33f-9ec9-497f-a87d-246d01f2b995
Host:api.onedrive.com
Transfer-Encoding:chunked
User-Agent:okhttp/3.2.0
Request Payload
--fb6cb33f-9ec9-497f-a87d-246d01f2b995
Content-ID: <metadata>
Content-Type: application/json; charset=UTF-8
Content-Length: 95

{"name":"1.png","file":{},"@content.sourceUrl":"cid:content","@name.conflictBehavior":"rename"}
--fb6cb33f-9ec9-497f-a87d-246d01f2b995
Content-ID: <content>
Content-Type: image/*

�PNG


IHDR�8���...........IEND�B`�
--fb6cb33f-9ec9-497f-a87d-246d01f2b995--

I did not know where is wrong

**Comment by rgregg** [comment]
Looking at your request, it looks like the issue may still be incorrect MIME formatting. The standard requires that there be an empty line before the separator. Can you try formatting the request body like this:

```
--fb6cb33f-9ec9-497f-a87d-246d01f2b995
Content-ID: <metadata>
Content-Type: application/json; charset=UTF-8
Content-Length: 95

{"name":"1.png","file":{},"@content.sourceUrl":"cid:content","@name.conflictBehavior":"rename"}

--fb6cb33f-9ec9-497f-a87d-246d01f2b995
Content-ID: <content>
Content-Type: image/*

�PNG
�

IHDR���8�����...........IEND�B`�

--fb6cb33f-9ec9-497f-a87d-246d01f2b995--
```

**Comment by rgregg** [comment]
Took a little longer to debug this and here's what's going with the request:

The content-type is incorrect. OneDrive doesn't support multipart/form-data, but instead uses multipart/related. Here's what the request should look like:

```
POST https://api.onedrive.com/v1.0/drive/root/children
Content-Type: multipart/related; boundary="e2906d30-e3b1-4d69-b4dc-80ee8c832e58"
Authorization: Bearer EwA...

--e2906d30-e3b1-4d69-b4dc-80ee8c832e58
Content-ID: <metadata>
Content-Type: application/json

{"name":"1.png","file":{},"@content.sourceUrl":"cid:content","@name.conflictBehavior":"rename"}

--e2906d30-e3b1-4d69-b4dc-80ee8c832e58
Content-ID: <content>

**PNG IMAGE DATA HERE**

--e2906d30-e3b1-4d69-b4dc-80ee8c832e58--
```

**Comment by jwb001** [comment]
Ah,I know how to do!
Thank you Very much!
It is great!
