### ISSUE TITLE
why the file becomes larger

### ISSUE THREAD

**Issue by jwb001** [OneDrive/onedrive-api-docs#479]
I used the Simple item upload to OneDrive using PUT
this is my request:
Request URL:https://api.onedrive.com/v1.0/drive/items/D72D39CD1CFF80A0!451/children/1.png/content
Request Method:PUT
Status Code:200 OK
Request Headers
Provisional headers are shown
Accept-Encoding:gzip
Authorization:Bearer EwAAA61DBAAUGCCXc8wU/zFu9QnLdZXy+...
Connection:Keep-Alive
Content-Type:multipart/form-data; boundary=ed7e45fc-3387-4019-b4d8-8a230028bce1
Host:api.onedrive.com
Transfer-Encoding:chunked
User-Agent:okhttp/3.2.0
Request Payload
--ed7e45fc-3387-4019-b4d8-8a230028bce1
Content-ID: <content>
Content-Type: image/*
 my file is 65536 , but the response is 65668
@content.downloadUrl: "https://ikwffq.bn1303.livefilestore.com/y3pv3LFr7G0sXZCBZliu_vZqyQa9l3DJZuehy1YYrZORCH5bHXsZzTt4-tyW5LznReMMJB8By9CQ_aoWG_CJVfAhjZh6PF8KQoheE5NA_FlitBXRSBEoMwQ-t9Cc0xj5hWZvlDEr-uYqErKmJNW_l19_xmdgH2zOxY-pN-rW8Rh3SEus7ego5_2nDFARROb7DsX"
@odata.context: "https://api.onedrive.com/v1.0/$metadata#drives('me')/items('D72D39CD1CFF80A0%21451')/children/$entity"
cTag: "aYzpENzJEMzlDRDFDRkY4MEEwITUyMy4yNjA"
createdBy: {application: {displayName: "WebTest", id: "441afb49"},…}
createdDateTime: "2016-11-28T02:07:51.807Z"
eTag: "aRDcyRDM5Q0QxQ0ZGODBBMCE1MjMuOQ"
file: {hashes: {crc32Hash: "0F9FBA63", sha1Hash: "BC5731682290B331BDE892AC89E16E9651A974BE"},…}
fileSystemInfo: {createdDateTime: "2016-11-28T02:07:51.807Z", lastModifiedDateTime: "2016-11-28T03:37:27.82Z"}
id: "D72D39CD1CFF80A0!523"
lastModifiedBy: {application: {displayName: "WebTest", id: "441afb49"},…}
lastModifiedDateTime: "2016-11-28T03:37:27.843Z"
name: "1.png"
parentReference: {driveId: "d72d39cd1cff80a0", id: "D72D39CD1CFF80A0!451", path: "/drive/root:/folder"}
size: 65668
webUrl: "https://1drv.ms/i/s!AKCA_xzNOS3XhAs"
why?

**Comment by rgregg** [comment]
Looks like a dupe of #123 . We're working on a fix for the misreported size for some image files.

**Comment by jwb001** [comment]
Hello rgregg, it is different from #123 .
This is My request that:
Request URL:https://api.onedrive.com/v1.0/drive/items/D72D39CD1CFF80A0!451:/1.png:/content
Request Method:PUT
Status Code:200 OK
Request Headers
Provisional headers are shown
Accept-Encoding:gzip
Authorization:Bearer EwAAA61DBAAUGCC.....
Connection:Keep-Alive
Content-Type:multipart/form-data; boundary=e60564a6-3fc5-4806-b5e2-765396a17ee2
Host:api.onedrive.com
Transfer-Encoding:chunked
User-Agent:okhttp/3.2.0
Request Payload
--e60564a6-3fc5-4806-b5e2-765396a17ee2

�PNG


IHDR�8���CsBIT|d� IDATx���A
�0��1s��
��%��NA���s��ߛ_p�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0@�aD�0�n�d�[��+�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�s	IDAT�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`�	0!�&0��`BL`��H	�s}��IEND�B`�
--e60564a6-3fc5-4806-b5e2-765396a17ee2--

 I download the PNG from the OneDrive and used the Binary Viewer to see what happen.
This is the data of PNG in Binary Viewer:
000000 - - e 6 0 5 6 4 a 6 - 3 f c 5 -
000010 4 8 0 6 - b 5 e 2 - 7 6 5 3 9 6
000020 a 1 7 e e 2 ◦ ◦ ◦ ◦ ◦ P N G ◦ ◦
000030 ◦ ◦ ◦ ◦ ◦ ◦ I H D R ◦

look that --e60564a6-3fc5-4806-b5e2-765396a17ee2. this is the data of boundary above.

So this is the reason of the question.it case the PNG can not be open because the data of file is incorrect.

**Comment by rgregg** [comment]
Ah, OK. If you are using the PUT verb, OneDrive expects just the contents of the file (not multipart/MIME). If you use the POST verb (as in your other thread) then multipart/MIME is expected. In this case, you're getting back the same content that you uploaded via PUT, which is expected. To fix it, just upload the file content instead of wrapping it in the MIME headers/separators.

**Comment by jwb001** [comment]
But when I used the POST ,like #478 ,why?

**Comment by jwb001** [comment]
It can upload now,and also can be opened!
Great!
