### ISSUE TITLE
how long is alive @content.downloadUrl?

### ISSUE THREAD

**Issue by cguZZman** [OneDrive/onedrive-api-docs#48]
how long is alive @content.downloadUrl?
I want to save time by not requesting a new url every time I need it.

**Comment by peternied** [comment]
If you want a download link that you can cache, I would recommend following on of the formats from our [download specification](http://onedrive.github.io/items/download.htm).  They will typically look like:

````
GET /drive/items/{item-id}/content
````

This will automatically redirect via a 302 to the @content.downloadUrl location.

**Comment by rgregg** [comment]
@content.downloadUrl links should be used right away. As @peternied mentioned, if you need a URL you can cache longer term, use the /content URL in the API.
