### ISSUE TITLE
/me/drive - HTTP/1.1 401 Unauthorized Code: 2147024891, System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by greatBigMassive** [OneDrive/onedrive-api-docs#480]
Hi there,

I'm trying to create a simple Web App that reads files (Read Only) on our OneDrive Business Account.
We've had the Office 365 Medium Business account for over a year now.

## Main point of reference
I am using this page to configure everything and believe I've done everything right down to the point of obtaining a new access token via the refresh_token. However, when I go to make the /drive request I get the Unauthorized message.

[OneDrive for Business authentication and sign in](https://dev.onedrive.com/auth/aad_oauth.htm)

Here's what I have done based on that page:-

- Subscribed to the trial run of Azure (everything worked fine - I can see our users, groups etc)
- I launched the new portal and did the following from there...
- At the new portal homepage I clicked **Azure Active Directory** on the left
- Next, on the submenu that appears I clicked **App registrations**
- I added a new App, set up a key and gave it Delegate permissions to the minimal operations it needed.
Screenshot below...
![app_permissions](https://cloud.githubusercontent.com/assets/6818250/20670668/de9836a2-b571-11e6-82e0-747afc4d20d2.jpg)

- It is not ticked as multi-tenanted
- I have provided a single Reply URL which is the exact https:// URL of the script I am using to call the Authorize Code, Access Token, Refresh Token etc...

## Selecting the correct EndPoint Uri
In the OneDrive API document (link at the top) in Step 3 it says to ensure I select the correct service Uri which I do and this is the array I pick out (xxxx to hide sensitive parts)

Array
(
    [@odata.type] => #Microsoft.DiscoveryServices.ServiceInfo
    [@odata.id] => https://api.office.com/discovery/v2.0/me/services('MyFiles@O365_SHAREPOINT@v2.0')
    [@odata.editLink] => services('MyFiles@O365_SHAREPOINT@v2.0')
    [capability] => MyFiles
    [entityKey] => MyFiles@O365_SHAREPOINT@v2.0
    [providerId] => xxxxxxxxxxxxxxxxxxx
    [providerName] => Microsoft
    [serviceAccountType] => 2
    [serviceApiVersion] => v2.0
    [**serviceEndpointUri**] => https://xxxxx-my.sharepoint.com/_api/v2.0/me
    [serviceId] => O365_SHAREPOINT
    [serviceName] => Office 365 SharePoint
    [**serviceResourceId**] => https://xxxxx-my.sharepoint.com/
)

## Redeem refresh token
As suggested by Step 4 of the OneDrive API document I need to get a new access token by using the refresh_token I received previously and setting the "resource" param as the value of **serviceResourceId** above, which I do and I get a response with a new Access Token.
Response below (xxx to hide sensitive stuff)
Array
(
    [token_type] => Bearer
    [scope] => MyFiles.Read MyFiles.Write
    [expires_in] => 3599
    [ext_expires_in] => 0
    [expires_on] => 1480343008
    [not_before] => 1480339108
    [resource] => https://xxxxx-my.sharepoint.com/
    [access_token] => eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsI...etc
    [refresh_token] => AQABAAAAAADRNYRQ3dhRSrm-4K-adpCJMKs...etc
)
Brilliant! - so now I have my new Access Token.

## Make a request to the OneDrive API
Step 5) of the OneDrive API document says I can use the new access_token as the "Bearer" and append **/drive** to the **serviceEndpointUri** that I received earlier which is https://xxxxx-my.sharepoint.com/_api/v2.0/me

I do that, but this is what I get as a response.
I've included the Response headers too....

**GET** Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsI..etc
**Request:** https://xxxxx-my.sharepoint.com/_api/v2.0/me/drive

**Response Header:**
HTTP/1.1 401 Unauthorized
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Sun, 13 Nov 2016 13:23:28 GMT
Last-Modified: Mon, 28 Nov 2016 13:23:28 GMT
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
ODATA-VERSION: 4.0
X-AspNet-Version: 4.0.30319
x-ms-suspended-features: features=""
SPRequestGuid: 79d4bb9d-c0d8-3000-a07e-f6b9b90882dc
request-id: 79d4bb9d-c0d8-3000-a07e-f6b9b90882dc
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.5910
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
WWW-Authenticate: Bearer realm="f7b63abf-2824-41e3-9136-274b7299485c",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
Date: Mon, 28 Nov 2016 13:23:27 GMT

**Response Body** (JSON decoded)
Array
(
    [error] => Array
        (
            [code] => -2147024891, System.UnauthorizedAccessException
            [message] => Access denied. You do not have permission to perform this action or access this resource.
        )
)

## Summary
I have a feeling I am missing something with regards to permissions on the Office 365 Admin area? I've seen lots of apparent solutions relating to Sharepoint in the Office 365 area and allowing Apps access to the flow but every time I refer to the API they are talking about it say's it's deprecated.  I didn't want to start messing with those types of solutions because, surely, if the OneDrive API Document above didn't mention changing permissions of SharePoint in my Office365 Medium Business account, then I don't go off on a tangent.

If you have any advise I would appreciate it.
I saw a similar issue being solved but it said it was done using a combination of Javascript but no actual solution of what that entailed was included - it was just closed.

If I need to provide any more information I am happy to.
Thank you in advance! - hope someone can help.

Adam

**Comment by rgregg** [comment]
Hi Adam

Sorry you're having trouble. I can look up the request-id and see if I can get any more details about the what's going on here, but I need your tenant name (the xxxx-my.sharepoint.com) to do that. Alternatively, if you can decode the `access_token` (using a tool like https://jwt.io) and tell me the value of "scp", that will at least narrow down some possible errors.

**Comment by greatBigMassive** [comment]
Hi Ryan! No need to apologise, I appreciate there's a minefield of variables going on here and just glad to get a reply :)  I decrypted the access token like you asked. Here's the result. I can message the tenant if it's okay if the stuff below isn't enough along with the test script I use (it shows all the response headers etc and the process flow for debugging.

{
  "aud": "https://xxxx-my.sharepoint.com/",
  "iss": "https://sts.windows.net/f7b63abf-2824-41e3-9136-274b7299485c/",
  "iat": 1480412234,
  "nbf": 1480412234,
  "exp": 1480416134,
  "acr": "1",
  "amr": [
    "pwd"
  ],
  "app_displayname": "OneDrive Test",
  "appid": "4abaa720-fc46-40b6-ad02-13ddd6eb6c90",
  "appidacr": "1",
  "family_name": "xxxx",
  "given_name": "Adam",
  "ipaddr": "93.190.117.118",
  "name": "Adam Stephenson",
  "oid": "a97d86ad-07b7-4b99-ba41-940598ad2f1b",
  "platf": "3",
  "puid": "100300008E7C9EFF",
  "scp": "MyFiles.Read MyFiles.Write",
  "sub": "IKYXEjWvLfV__EoVTyNUmZ-xz75OQp--JKNCkLXOhZU",
  "tid": "f7b63abf-2824-41e3-9136-274b7299485c",
  "unique_name": "adam@xxxx.com",
  "upn": "adam@xxxx.com",
  "ver": "1.0"
}

Thanks again!!
Adam

**Comment by greatBigMassive** [comment]
Hi there,
I've left it some time to get a response - apologies for chasing but do you have any news on this please?

**Comment by katahir** [comment]
Hi Adam,
I dug up the logs for your request and it looks like the request didn't have an Access Token appended as a header. Can you please double check your client code? As mentioned in the documentation, the Access Token needs to be passed on to SharePoint Resource under the bearer header.

**Comment by greatBigMassive** [comment]
Hi Katahir, is it possible to send you an entire screen dump of all of the requests and responses I am sending. This shows that I do send the Access Token and the way I send the header via cURL is exactly the same as the previous request to it that required the access_token sent to the Discovery Service.  I have still not been able to solve this and wonder now if it's more about the Resource I am using and something I am doing wrong there.  Could I send this privately maybe as it will contain some private details.

I have recently made another request, according to what I see I am sending the new access token correctly having first asked to get a new access_token by passing the refresh_token to 'https://login.microsoftonline.com/common/oauth2/token' and specifying the resource.

Thanks in advance!

**Comment by greatBigMassive** [comment]
Just to add to this.. but could it simply be that the message is correct and I genuinly don't have permission to access the location because I've not Registered the APP correctly on Azure?  I have followed the instructions but to be honest, it's a bit vague when it comes to the part where I have to set up Permissions and Scopes.  It should be as simple as, I want anyone to use the APP - so even if a school with Office 365 logs into our APP they get to see their own OneDrive files - if our company logs in, we see our files etc.  On the permissions side, maybe I'm not allowing the right access.

Is there a guide for this that explains exactly what permissions need to be applied the ensure access to a users personal files and any group files they can acccess?

Thanks again!

**Comment by rgregg** [comment]
@greatBigMassive: I'm sorry that this is still an issue! Would you be able to use Fiddler to trace all of the requests/responses for your scenario, and then send me that capture so I can take a look at what's going on? You can shoot me an email at rgregg -at- microsoft -dot- com and I'll see if we can figure out what's going wrong.

**Comment by greatBigMassive** [comment]
Thankyou Ryan, I've sent an e-mail. It would be really good to get a solution to this especially given there is another ticket on your issues list that is exactly the same bug but the person reported it said they worked around it by using graph. It would be good to have an answer that can be put on here as a solution!

**Comment by ificator** [comment]
Hi @greatBigMassive, did this end up getting resolved?
