### ISSUE TITLE
Get used space from OneDrive for Business

### ISSUE THREAD

**Issue by yuribb** [OneDrive/onedrive-api-docs#483]
Hello. I am trying to get information about used space of my OneDrive for business by using API.

I get a request to url:
- [https://tenant-my.sharepoint.com/_api/v2.0/drives/driveId](url).

The response of this request looks like:

`{
  "id": "0123456789abc",
  "owner": {
    "user": {
      "id": "12391913bac",
      "displayName": "Name FamilyName"
    }
  },
  "quota": {
    "total": 1024000,
    "remaining": 1010112,
    "deleted": 0,
    "state": "normal"
  },
  "driveType": "business"
}`

but this response can't contain the 'used' field in the 'quota' field.
In [https://dev.onedrive.com/drives/get.htm](url) sample contains the 'used' field in qouta, but it's a personal onedrive.

I am trying to get the used field by using an expand parameter.

Url looks like:
- [https://tenant-my.sharepoint.com/_api/v2.0/drives/driveId?expand=quota(select=used)](url),

but response of request of this url can't contain a quota with the 'used' field too.

i am trying to get a quota directly, by using this urls:
- [https://tenant-my.sharepoint.com/_api/v2.0/drives/driveId/quota](url),
- [https://tenant-my.sharepoint.com/_api/v2.0/drives/driveId/quota?$select=used](url).

Responses of these urls return quotas, but they don't contain the 'used' fields.

It is possible to get 'used' info in OneDrive for business?
How to get number of items in OneDrive?

**Comment by katahir** [comment]
Hi Yurib,
OneDrive API for business doesn't support 'used' property. This property is only there for consumer accounts. It is possible to get 'used' quota for the entire OneDrive for business site collection using legacy REST/CSOM calls to SharePoint. You can look for 'SPSite.Storage.StoragePercentageUsed' property. 
OneDrive API also doesn't natively support getting the total number of items in the Drive but you might be able to do something on the client side by adding up the childCount property of folders.

**Comment by yuribb** [comment]
Hello,

Would you be so kind to give me some examples of requests?

I tried to get a response with the following requests:

- https://tenant-my.sharepoint.com/_api/v2.0/drives/driveId/items?$filter=folder ne null
- https://tenant-my.sharepoint.com/_api/v2.0/drives/driveId/view.delta?$filter=folder ne null

I see a list of folders of my drive but all of them have childCount = 0 while there are files in the folders.

Also, I can't understand how to get a number of items in the root folder.

Additionally, I tried to get the size with CSOM for the site. But this request returns only the site size while I need to get the size of every site separetly. What is more the size that I got is wrong.

In order to get the size I used the following request:

- https://tenant-my.sharepoint.com/_api/site/usage

Thank you in advance.

Kind regards

**Comment by yuribb** [comment]
Now it works fine in OneDrive for business and SharePoint. Thanks.
