### ISSUE TITLE
Sharepoint permissions for external users

### ISSUE THREAD

**Issue by sswati1507** [OneDrive/onedrive-api-docs#484]
Hi,

I am using the invite/share functionality of OneDriveAPI to share file with external user using the gmail id. It is being shared correctly and I get a permission ID back. But when I do getPermissions on the item, I dont see that permission ID which was returned in the share item response.

I tried the same thing with users of the organization and it works as expected. 

Can anyone tell me why this doesnot work in the case of external users?

Thanks

**Comment by katahir** [comment]
Hi Swati,
This is the expected behavior. External users are only returned in the [Permissions API ](https://dev.onedrive.com/items/permissions.htm)response once they accept the invite.
