### ISSUE TITLE
Not getting contents of file if i give "Read items in all site collections" sharepoint permission to my app for one drive with business.

### ISSUE THREAD

**Issue by pathaniaVikas** [OneDrive/onedrive-api-docs#487]
With this sharepoint app permission "Read items in all site collections", when I am trying to download contents of file using One Drive 2.0 APIs url : 
"{resource}/{site}/_api/v2.0/drive/items/{id}/content", I am getting 404 error (Permission denied).

But if i change this permission to "Have full control of all site collections" i am able to download the contents.
I don't understand why i am not able to read the file with "Read items in all site collections".

**Comment by rgregg** [comment]
Hi @pathaniaVikas 

I think you're hitting a regression in the production service that we're working on. When you request the /content URL, we send a 302 redirect to the actual download URL for the time. That URL is "preauthenticated" and therefore doesn't need the Authorization header. Normally if you provide the Authorization header for the download URL, we ignore it and the file downloads. However, currently if you provide the header, we'll return a permission error.

Can you check to see if you are able to download files if the Authorization header is removed from the download request (from the URL we 302 redirect to)?

**Comment by pathaniaVikas** [comment]
Hi thanks for your reply. 
I did what you said i send no headers for "redirected url"
But i am getting
"{"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Access denied. You do not have permission to perform this action or access this resource."}}
403"

Below i have attached the permissions snapshot. 
Yesterday i was able to download content using these permissions. And for "read only permission" i was getting permission denied 404 error.
I am still looking into this and will let you know my findings. Any suggestions on what may be the issue is highly appreciated.
![permisssions](https://cloud.githubusercontent.com/assets/16267752/21179880/1bd84e10-c21c-11e6-9b2c-deb47c7c97a8.png)
![permissions1](https://cloud.githubusercontent.com/assets/16267752/21179881/1bd8bb2a-c21c-11e6-8d99-8f642222c7e4.png)

**Comment by pathaniaVikas** [comment]
I was using "client_credentials" in grant_type while fetching access_token and getting 401 forbidden error while requesting content download. I removed it and fetched access_token as mentioned in one drive documentation, its working now. 
Thanks for your help, i am closing the issue.
