### ISSUE TITLE
Shared folders are not listed in view.delta

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#488]
According to [working-with-links.md](https://github.com/OneDrive/onedrive-api-docs/blob/master/misc/working-with-links.md#using-viewdelta-with-remote-items) view.delta should return the shared folders contained in the drive.
However in my tests shared folders (that have been added to the drive) are **never** returned.

---

Content of my drive:
![2016-12-16](https://cloud.githubusercontent.com/assets/10778434/21281057/5c888e0a-c3ea-11e6-9b01-ce2e24c18122.png)

---

Output of `/drive/items/root/view.delta?select=name`:

```
{
	"@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives('D4FE0EE4D78A90DC')/items(name)",
	"@delta.token": "...",
	"value": [
		{
			"name": "root"
		},
		{
			"name": "empty"
		}
	],
	"@odata.nextLink": "..."
}
```

**Comment by ificator** [comment]
I noticed your response contains a `nextLink` - if you fetch that URL do you see `SHARE-TEST` come back?

**Comment by skilion** [comment]
No, this is the response:
```
{
	"@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives('D4FE0EE4D78A90DC')/items(name)",
	"@odata.deltaLink": "https://api.onedrive.com/v1.0/drives('D4FE0EE4D78A90DC')/items('root%252F')/view.delta?$select=name&token=...",
	"@delta.token": "...",
	"value": [
		{
			"name": "root"
		}
	]
}
```

**Comment by ificator** [comment]
Hi @skilion, this should now be resolved! It will only work for new tokens though - a delta session that was started prior to the fix will continue to not return the mount points (you can get a new token by either not providing the `token` query string parameter).

**Comment by skilion** [comment]
Just tested and it's working, thank you.
