### ISSUE TITLE
lastModifiedDateTime from Item does not match OneDrive Web/Desktop UI

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#49]
Files and folders in OneDrive don't seem to have Modified dates that match between OneDrive Web and Desktop and the API.

Note: My local timezone is UTC-4; it was UTC-5 at the time of creation.

For example, I have one file with the following properties:
Web UI: Modified: 11/18/2014 
Windows 8.1 OneDrive Sync: Date modified: 11/18/2014 10:32:34PM
Item resource lastModifiedDateTime: 2015-03-25T19:13:08.283Z
(The Item resource createdDateTime is: 2015-03-25T19:13:08.283Z)

The folder:
Web UI: Modified: 2/17/2015
Windows 8.1 OneDrive Sync: Date modified: 2/17/2015 3:44:23AM
Item resource lastModifiedDateTime: 2015-03-25T19:46:20.57Z
(The item resource createdDateTime is: 2015-02-17T08:44:23.903Z)

Are the OneDrive Web UI and Desktop clients using some other metadata to store modified dates? Is this accessible to the OneDrive API?

**Comment by rgregg** [comment]
The created and last modified times provided by the OneDrive API are the server times that those events occurred. We also track client-side times which are reported by apps when they make changes. This isn't currently available in the OneDrive API but is something that our mobile clients and website use. We're working on making this available to OneDrive API as well.

You can see this [OneDrive User Voice suggestion](http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7139629-improve-api-to-allow-the-timestamps-date-time-of) for more details and to track when the changes are released.
