### ISSUE TITLE
One drive for business APIs not working( 401 error ) if i give "client_credentials" grant_type for getting token

### ISSUE THREAD

**Issue by pathaniaVikas** [OneDrive/onedrive-api-docs#490]
With one drive v1.0 APIs, i was using grant_type as "client_credentials" to access users files from app and having "app permissions" given to app. But with 2.0 APIs i am not able to access users file from app using "client_credentials" grant_type for token.
Its working only with "delegated permissions" and grant_type as "refresh_token" and having admin added to site administrator for all users.
Is there a way we can use client_credentials workflow instead of adding admin to all users site administrators.

**Comment by katahir** [comment]
Hi PathaniaVikas,
'Client_credentials' a.k.a app-only flow should work with 2.0 apis. I just tested this in my tenant and I am able to see user drives using this grant flow. What exact error are you seeing when you try to access user files? I am thinking maybe you don't have the right scopes in the access token.

**Comment by katahir** [comment]
Hi PathaniaVikas,
I haven't heard back from you. Just to clarify things a bit, you can get the metadata of a file but there is a known issue downloading the contents of a file using app-only token. We are working to fix it.

**Comment by pathaniaVikas** [comment]
Hi Katahir, 

Sorry for not responding back, i was on leave and hence was not able to reply. 
Since we were getting the errors downloading the file using app-only token we put this work on hold. 
Thanks for looking into this.

**Comment by chackman** [comment]
Sorry about this old issue going stale. If this issue is still reproducing, could you please provide updated request and response information to help us investigate further? Thanks for your patience!
