### ISSUE TITLE
[ODB] upload large file encounter 401 when create session

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#491]
hi all,

When I created session with some special words like this chinese

'使用计算字段减少脚本的使用.avi'

It will response 401, even if I encoded it.

I think it would not be a correct return code.

Thank you for help!

**Comment by katahir** [comment]
Hi JoeWuTaiwan,
I just tried creating a resumable upload session with the exact name that you used and I was successfully able to create the upload session. I get a valid response back and in the UI I do see the temporary stub file created for the session, so maybe your 401 is a valid authentication issue. Do you have a correlation id/date for me? I can take a look at the logs and see where the authentication error is coming from.

**Comment by joewutaiwan** [comment]
hi @katahir 
thanks for reply

here is the information
http code 401
```
Connection: close
Content-Length: 0
Date: Wed, 04 Jan 2017 09:50:05 GMT
HTTP/1.1 401 Unauthorized
MicrosoftSharePointTeamServices: 16.0.0.6008
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
SPRequestGuid: f9b0c79d-7014-3000-d4fc-fe78a9425791
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000
WWW-Authenticate: Bearer realm="dcb0ac15-0be0-44fe-9662-e578d2178b94",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
X-Powered-By: ASP.NET
request-id: f9b0c79d-7014-3000-d4fc-fe78a9425791
x-ms-suspended-features: features=""
```

Best Regard

Joe

**Comment by katahir** [comment]
Hey Joe,
Sorry for getting back to you after a week. During this time, I have tried to search for the logs of your request, but for some reason I couldn't find any logs. Can you please share the details of a more recent failure? Also, the request url will be helpful. 
401 usually means an authentication failure. Do you have the right scopes in the access token?

Kashif

**Comment by joewutaiwan** [comment]
hi @katahir 
thanks for reply,
I use this to create session
```
/drive/items/parent_id:/file_name:/upload.createSession
```
But I think access token scope will not be a problem,
because I can success upload by changing the request file name


attaching another failed header
```
Connection: close
Content-Length: 0
Date: Tue, 17 Jan 2017 07:30:46 GMT
HTTP/1.1 401 Unauthorized
MicrosoftSharePointTeamServices: 16.0.0.6105
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
SPRequestGuid: 2bd8cb9d-b007-3000-d4fc-fdde63652de5
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000
WWW-Authenticate: Bearer realm="dcb0ac15-0be0-44fe-9662-e578d2178b94",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
X-Powered-By: ASP.NET
request-id: 2bd8cb9d-b007-3000-d4fc-fdde63652de5
x-ms-suspended-features: features=""
```
Thank you

Best Regard

Joe

**Comment by chackman** [comment]
Sorry about this very old issue going stale.  If this is still reproducing, could you please provide updated request & response information to help us investigate further?  Thanks.
