### ISSUE TITLE
How to use onedrive file picker when redirect url is dynamic.

### ISSUE THREAD

**Issue by creedrahul** [OneDrive/onedrive-api-docs#496]
I am using onedrive file picker which works absolutely perfect when the redirect uri is static but when i try to use a dynamic uri it allows me to pick a file from drive but does not returns success and only shows the loader image. I get the following error in browser console.
![dynamicuri_onedrive_err](https://cloud.githubusercontent.com/assets/14090825/21678325/47b11586-d364-11e6-878e-c13a48213611.PNG)
I am using the following code to call onedrive file picker
`$(document).on('click', '#btnOneDrive', function () {`
     `var odOptions = {`
              `clientId: "XXXXXX-XXXXX-XXXX-XXXX",`
              `action: "query",`
              `multiSelect: true,`
              `openInNewWindow: true,`
              `advanced: {`
                       `queryParameters: "select=id,name,@content.downloadUrl"`
               `},`
              `success: function (files) {`
              /* success handler */
              `for (var i = 0; i < files.value.length; i++) {`
                    `OneDriveFileSaveEnv(files.value[i]['@microsoft.graph.downloadUrl'], files.value[i].name);`
              `}`
         `},`
          `cancel: function () { /* cancel handler */ },`
          `error: function (e) { /* error handler */ }`
      `};`
        `OneDrive.open(odOptions);`
  `});`

**Comment by daboxu** [comment]
hi @creedrahul , would you mind sharing me more detail with your story? Are you invoking the picker in a popup? Is your host page is a dynamic url? Basically we assume the host page should be a static url due to the oauth requirement, but you can set the oauth redirect url like:

```javascript
var odOptions = {
    advanced: {
        redirectUri: "<your url registered on apps.dev.microsoft.com>"
    }
}
```

**Comment by creedrahul** [comment]
Hi @daboxu my base url has query parameters that change with every request made to the page. I have already tried to implement the redirecturi in advance block. Is there any work around that can be used to make dynamic url work.

**Comment by daboxu** [comment]
@creedrahul if your host app is dynamic url and you have another static url in the same subdomain for oauth redirect, then the answer is yes.

Let's say you have a host app at "www.foo.com/dynamic?random=123" page just like how you invoke the picker, and you set the redirectUri in advanced block which is used for oauth redirect to "www.foo.com/pageforoauth.htm", you should be good to go. Does this help?

**Comment by creedrahul** [comment]
@daboxu can i redirect to the url as it is. As the values in query string are important in handleing the next in coming data. The file download in my case is a part of work flow and redirecting it to any other page will break the work flow. If i am redirecting from a url like www.foo.com/dynamic?random=123 i want it to return to same url.

**Comment by daboxu** [comment]
@creedrahul unfortunately no, the redirectUri you set in the advanced block is used in the popup window for oauth so you should be safe. As the oauth endpoint will strip out all query param there is no way we can get around of it. If my understanding is correct, the host app will not do redirect right? So basically you just need a separate static page which including the v7.0 js file as well.

**Comment by creedrahul** [comment]
@daboxu thanks for your efforts to here me out  and suggest a solution. Let's hope in future onedrive will provide some method to use redirect url with parameters just like google and dropbox.

**Comment by daboxu** [comment]
@creedrahul thanks for your feedback! You can also let us know your voice: https://onedrive.uservoice.com/forums/262982-onedrive so we can better help other developers.

**Comment by pradeepshastry** [comment]
@daboxu Is there a workaround for configuring a dynamic redirect URL? We have a URL which has dynamic values embedded as part of the URI and it wouldn't be possible to separate them as query params. 

e.g. http://foo.com/<userId>/product/<productId>/productDetails.html

In the above URL, userId and productId are part of the URI and are required in the callback
