### ISSUE TITLE
filter on the basis of name not working

### ISSUE THREAD

**Issue by sswati1507** [OneDrive/onedrive-api-docs#498]
I have implemented search and filter together. the search is working fine but the filter is not. The URL is also being created correctly. 

https://tenant/site/_api/v2.0/drives/id/root/view.search?q=test&filter=name%20eq%20'abc.pdf'

but I do not get relevant document filtered.

**Comment by katahir** [comment]
Hi Swati,
Filter isn't supported with search api just yet. It is something we are looking to do in the future. For now, can you limit your result set by adding more keywords in your search query , e.g. q='test abc pdf'?

Kashif

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
