### ISSUE TITLE
Error 'Cannot find the personal tenant url'

### ISSUE THREAD

**Issue by niesink** [OneDrive/onedrive-api-docs#499]
I'm trying to use the javascript filepicker in my webapp to allow the user to pick a file. The user is on a different tenant than the filepicker-application. For registration of the filepicker-application I followed all the steps at: https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm

What happens after the user selects and their account in the filepicker-popup (so before the actual list of available files shows up) is the following javascript error in the console: 
```
Uncaught Error: [OneDriveSDK Error] Cannot find the personal tenant url, response text: {"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users(mySite)/$entity","mySite":null}
    at Function.e.throwError (OneDrive.js:2)
    at e._successCallback (OneDrive.js:2)
    at e._callSuccessCallback (OneDrive.js:3)
    at XMLHttpRequest._request.onreadystatechange (OneDrive.js:3)
e.throwError @ OneDrive.js:2
(anonymous) @ OneDrive.js:2
e._callSuccessCallback @ OneDrive.js:3
_request.onreadystatechange @ OneDrive.js:3
```
Are the docs not up to date, should I add something with regarding to consent, grants or permissions to my application registration? Also, is there anything required to make the application multi-tenant?

**Comment by daboxu** [comment]
hi @niesink , the picker is designed to work with the user in the same tenant.

**Comment by niesink** [comment]
@daboxu wow really, are you sure?
It would've been nice if that was mentioned in the docs at https://dev.onedrive.com/sdk/js-v7/js-picker-overview.htm

So the intended use of the file picker (in combinatie with Onedrive for Business) is only for internal web applications, like on an intranet? Our product is a student information system that is used by many school, they all have their own Azure AD / Office365 tenant. We want to allow teachers and students to upload files to our application by selecting a file from Onedrive for Business, we then use the download-link from the file picker to save the file to our servers. So what you're saying is the file picker cannot be used for this situation? What is the recommended approach for us?

**Comment by daboxu** [comment]
hi @niesink , thanks for the explanation. The picker can provide access to different tenants but not cross-tenant support. It seems like you registered your app through Azure Portal? The v7.0 app should be registered on dev.microsoft.com: https://dev.onedrive.com/sdk/js-v7/js-picker-overview.htm#setting-up. V7.0 Picker works with Microsoft Graph API to allow your app access different tenants.

**Comment by niesink** [comment]
@daboxu No, I registered the app through apps.dev.microsoft.com (as it says on the 'Setting up' part), I log in there with my Azure acount. My app-id is 78d3ac8f-6b87-4133-bca1-66339102ff73, if that helps..?

I'm afraid I don't understand what you mean by 'access to different tenants but not cross-tenant'.

**Comment by daboxu** [comment]
hi @niesink , sorry for late reply, can you make sure the user's tenant has been initialized? Our engineer suggests that it could happen if the user you logined does not have his OneDrive for Business set up. It is set up by the first time you access to the OneDrive in browser, ex: https://sharepointsite-my.sharepoint.com/personal/dabo_microsoft_com/.

**Comment by niesink** [comment]
hi @daboxu that appears to have been the problem. Using another user from our own tenant, that does have Office365 active can succesfully login.

Unfortunately when using an account from a different tenant I run into a different error. After entering the username and password and clicking the login-button I get the following in my javascript console:
`[OneDriveSDK] calling xhr failure callback, status: 403`
![image](https://cloud.githubusercontent.com/assets/445989/23700340/c74fe416-03f2-11e7-936d-410a136bfdff.png)

**Comment by daboxu** [comment]
hmm, that's interesting, would you mind sharing the fiddler traces of these requests? It would be helpful to identify the root cause by the requests. You can send me email dabxu AT microsoft DOT com.

**Comment by niesink** [comment]
Just letting you (and any other readers) know I've sent you that e-mail yesterday. Please let me know if there's anything else I can do to help.

**Comment by daboxu** [comment]
handled by internal thread.
