### ISSUE TITLE
error code and error message problem, when requesting for operations using access_token (expired) passed in request header

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#50]
did the following 4 operations
1) GET /drive/root 
with access_token expired in the request header
2) GET /drive/root
without passing access_token in the request header
3) GET /drive/root 
with access_token expired in the query parameter
4) GET /drive/root
without passing access_token in the query parameter

the following are the response received 
1)
with access_token expired in the request header
![with expired access_token](https://cloud.githubusercontent.com/assets/11455759/6842152/6b52661c-d3ba-11e4-8d23-df080445404e.png)

2) 
without passing access_token in the request header
![without access_token](https://cloud.githubusercontent.com/assets/11455759/6842155/77822634-d3ba-11e4-939a-d2790bbeae75.png)

3)
with access_token expired in the query parameter header
![query paramater with expired access_token](https://cloud.githubusercontent.com/assets/11455759/6842439/2477934e-d3be-11e4-9df1-024dae10e08e.png)

4)
without passing access_token in the query parameter
![query parameter without access_token](https://cloud.githubusercontent.com/assets/11455759/6842442/274a8e50-d3be-11e4-9a0e-3789dff21a5e.png)

comparison
![comparison](https://cloud.githubusercontent.com/assets/11455759/6842443/39e32f2c-d3be-11e4-8ef6-5f5d85a649f1.png)

Q1) some thing when passing expired access_token as request header?
Q2) why same type response is received when access_token is not passed as request header/query parameter compared with expired access_token in query paraemter???

**Comment by rgregg** [comment]
Returning the 400 Bad Request is a bug on our side. We're investigating and hope to get it fixed.

**Comment by jsinh** [comment]
I am suffering from the same issue.

IMO if the API response as "Token expired" in all cases where it applies that it would be more precise on part of the API consumer to take necessary action.

+1 to @ankit-ankuagrawal for reporting this and @rgregg for the response. Thanks

**Comment by rgregg** [comment]
This is fixed now, and we're returning the proper error code to indicate the request is unauthorized (401)
