### ISSUE TITLE
[ODB] lastModifiedDateTime in view.delta and get file info are mismatch

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#500]
Hi all,

I use following requests to get file info in order to make comparison.
But the lastModifiedDateTime field are not match
```
https://{tenant}/_api/v2.0/me/drive/items/01FCA3SLPFKDYDGMFWIFC2PLSVXOEUKDED
     "lastModifiedDateTime": "2017-01-17T07:04:20Z",
```
```
https://{tenant}/_api/v2.0/me/drive/items/01FCA3SLN6Y2GOVW7725BZO354PWSELRRZ/view.delta
     "lastModifiedDateTime": "2017-01-17T07:04:19Z",
```

about margins 1 second

thank u for help!

**Comment by katahir** [comment]
Hey Joe,
Thanks for reporting this issue. I have fixed it and the fix should roll out to Production soon.
