### ISSUE TITLE
Hashing consistency for OneDrive Personal/for Business/SharePoint

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#501]
In the [documentation on hashes](https://dev.onedrive.com/facets/hashes_facet.htm), there's the following remark:
> In OneDrive for Business and SharePoint Server 2016, sha1Hash and crc32Hash are not available.
> In OneDrive Personal, quickXorHash is not available.

Could I request some consistency between all the products? There's not one single hashing algorithm supported by all the services. If there are plans to make this consistent, could it be decided on a widely supported hashing algorithm (e.g. sha1 or crc32) instead of quickXor?

**Scenario**
If I wanted to move a file from OneDrive Personal to OneDrive for Business, I would need to:
1. download it from ODP,
2. calculate the sha1 hash locally
3. compare it with the one ODP returned
4. calculate the quickXor hash locally (for which there are no libraries in many languages)
5. upload the file to ODfB
6. compare the hash returned by ODfB to the quickXor calculated in step 4

And these are all Microsoft products. It shouldn't be that complicated. It's a HUGE issue that "quickXor" is the only algorithm available for ODfB.

**Comment by ificator** [comment]
I've opened [a UserVoice suggestion](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/18130390-onedrive-for-business-and-onedrive-for-consumers-s) to cover this ask.
