### ISSUE TITLE
Keep me signed in - not working for business accounts

### ISSUE THREAD

**Issue by brettbatie** [OneDrive/onedrive-api-docs#502]
I'm seeing an issue where the OneDrive picker v7 is not keeping me logged in when using a business account. I can duplicate this with the sample picker on this page: https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm

Replication Steps:
1. Open the picker
2. Check "Keep me signed in" and login with a business account
3. Close the picker and then open it again

Expected: Automatically take user to files
Actual: User is asked to login again

If I use a personal account everything works as expected and I am not asked to login again.

Also, I noticed a small work around on step 3. If I click the "back" button and then select the account that I used on step 2 it will automatically take me to my files without asking me for a password.

**Comment by daboxu** [comment]
hi @brettbatie , thanks for reporting the issue. I have tried with the sample app and my work account and it works for me for different browsers. I have tested with Chrome 55.0.2883.87 and Firefox 49.0.2. Would you mind sharing more info with how you tested it?

**Comment by brettbatie** [comment]
@daboxu I have tested this with Chrome Version 54.0.2840.90 (64-bit) and Firefox 50.1.0 using Debian Linux and I get the exact same behavior as previously stated in both browsers. I also had a colleague test this (with a different account but same org) on Microsoft Edge 38.14393.0.0 and mac os 10.11.6 - Chrome Version 55.0.2883.95 (64-bit) and the same behavior is there as well. 

I made a screencast of the issue which can be found [here](https://www.youtube.com/watch?v=mROqYr8mAKA).

**Comment by daboxu** [comment]
@brettbatie after setup a new tenant I can reproduce it now, thanks for reporting, will look into that.

**Comment by daboxu** [comment]
hi @brettbatie the fix should be out, please let me know if it works for you.

**Comment by brettbatie** [comment]
I have confirmed that the fix works. Thank you!
