### ISSUE TITLE
Clarify access for Javascript File Picker

### ISSUE THREAD

**Issue by sheepsheerin** [OneDrive/onedrive-api-docs#504]
The OneDrive documentation quotes: "The OneDrive API is available for OneDrive, OneDrive for Business, SharePoint, and SharePoint Server 2016".

We've recently begun upgrading our JavaScript file picker from v5 to v7 in order to allow access for Office365 business accounts. We were hoping that the file picker would also give us access to the SharePoint sites that the user has access followed as you do from the online view in OneDrive (Cloud Testing Site in the left nav is a SharePoint site):

![screen shot 2017-01-30 at 14 09 29](https://cloud.githubusercontent.com/assets/2857915/22426255/88d9e736-e6f6-11e6-9818-2786083cd3c2.png)

but the view when opening that same user in the file picker, appears to be a subset without the left hand navigation list:

![screen shot 2017-01-30 at 14 10 02](https://cloud.githubusercontent.com/assets/2857915/22426289/a1e52a74-e6f6-11e6-89fb-dd4ffa26147e.png)

Can you confirm that this is intended behavior to restrict just to the Files section and that SharePoint files are not accessible through the file picker? If so then I'm presuming we would need to use the REST APIs and build our own UI to solve the use case?

If it is not a restriction, can you let me know how to display the left nav to choose different sections? My confusion arises from the Delegate Permissions section when registering an application, they have Sites.Read.All and Sites.ReadWrite.All.

**Comment by ncabeen** [comment]
Hi @sheepsheerin,

You have it right; that is the intended behavior today with the v7 picker. We've heard the request to integrate SharePoint Sites into the picker for business accounts before, and we think it's a great idea. Thanks for the feedback!
