### ISSUE TITLE
Locating a Shared file which is not in a folder

### ISSUE THREAD

**Issue by jaycdave88** [OneDrive/onedrive-api-docs#505]
I am trying to find some documents or an example of how to query the OneDrive API and find shared files that are not in a folder. 

Is there a good resource link to this?

**Comment by ificator** [comment]
To find both file and folders that are not "added to your drive" (i.e. mounted) you'll want to use the `sharedWithMe` api. Check out the docs [over here](https://api.onedrive.com/v1.0/drive/view.sharedWithMe) and feel free to respond here with any questions.

**Comment by jaycdave88** [comment]
@ificator thank you for your quick response, however, the hyperlink you added does not seem to be working. 

Is this the correct link that you were referring to? https://dev.onedrive.com/drives/shared_with_me.htm

If so - since I am coding against the C# library - how would I construct a query for the API?

**Comment by ificator** [comment]
Unfortunately the OneDrive SDK doesn't seem to have that support yet, but I believe the Graph SDK does so you could check that out to see if it meets your needs (https://github.com/microsoftgraph/msgraph-sdk-dotnet/).
