### ISSUE TITLE
Discovery API is returning a blank "value".

### ISSUE THREAD

**Issue by justinoue** [OneDrive/onedrive-api-docs#506]
I'm following the instructions found here: https://dev.onedrive.com/auth/aad_oauth.htm and cannot get past the discovery step. If I try to make a request assuming the tenant api endpoint, I get a 401. I imagine something is wrong with my permissions but as far as I know I have them set up correctly.

I have Office 365 Sharepoint Online permissions "Read and Write User Files" and "Read User Files" enabled in the Azure AD App configuration.

Not sure what to do since I don't have a whole lot to work with.

**Comment by justinoue** [comment]
Update:
It seems that when using a user from the tenant that owns the app, I do get something back from the discovery API.

When using a user from another tenant, the discovery API is blank. I want this app to be available for anyone. How do I do that? I have Multi-tenanted enabled.

**Comment by ificator** [comment]
We have a good discussion over at https://github.com/OneDrive/onedrive-api-docs/issues/663 talking about limitations of the discovery API, and its deprecation.
