### ISSUE TITLE
js picker save v.7.0 with dataURI problem

### ISSUE THREAD

**Issue by nerazzurro80** [OneDrive/onedrive-api-docs#507]
I am trying to integrate with the js picker (v.7.0) to store files in your platform as described in https://dev.onedrive.com/sdk/js-v7/js-picker-save.htm. 

As I need to add files to OneDrive for Business/SharePoint accounts, my only option is to provide the sourceURI parameter with the full dataURI of the file.
Now as I am trying to save medium size files of 5MB<25MB, the full content is appended in the query string of the redirectUri (openInNewWindow=true), resulting in a long URL which causes a "Bad Request - Request Too Long" problems once the redirect starts to your servers.

Is there anyway to avoid that the full dataURI is passed via URL but have to use a POST instead?

Also, at the moment the demo page for the picker save (https://dev.onedrive.com/sdk/js-v7/js-picker-save.htm) seems to be broken and a message in console is given "Uncaught Error: [OneDriveSDK Error] please specified one type of resource to save". This is tested in Chrome 56.

Here is my full integration code:
`OneDrive.save({
                                    action: 'save',
                                    clientId: 'my-app-id',
                                    openInNewWindow: true,
                                    success: function(){console.log("succes");},
                                    progress: function(){console.log("progress");},
                                    cancel: function(){console.log("cancel");},
                                    error: function(){console.log("error");},
                                    advanced: {
                                        redirectUri: '/onedrive-redirect.html'
                                    },
                                    fileName: 'myfile.pdf',
                                    sourceUri: 'data.......' // full dataURI of the file content
                                });`

**Comment by daboxu** [comment]
hi @nerazzurro80 , currently the picker only support dataUri uploading for OneDrive Consumer account. The best approach for save a file in picker is using the sourceInputElementId.

**Comment by nerazzurro80** [comment]
Thanks @daboxu , I have tried that but getting `Uncaught Error: [OneDriveSDK Error] please specified one type of resource to save`, same error I get by using the demo page (https://dev.onedrive.com/sdk/js-v7/js-picker-save.htm). Is there a fix planned for that?

**Comment by daboxu** [comment]
@nerazzurro80 I have a pending fix for the demo page and you see this issue because SDK didn't find the option attribute 'sourceInputElement' which is uploading local file nor 'sourceUri' which is uploading data uri. Try specify the input element id like OneDrive.save({..., sourceInputElementId: '<input-element-id>', ...}). Let me know if it works.

**Comment by nerazzurro80** [comment]
Hi @daboxu, thanks for your reply. I have tried your suggestion and it fixes the demo page.

In our application though, we don't want to manually upload a local file but we have the content of the file (javascript Blob with dataURI) and we need to upload that programmatically. 
Setting the value to an input file via javascript is not possible for security reasons as far as I know but an user action to select a file is required.

What would be the best option to post file contents without having the user to browse her drive?

**Comment by nerazzurro80** [comment]
Hi @daboxu, do you have any idea on how we can implement what is described above? Thanks!

**Comment by daboxu** [comment]
hi @nerazzurro80 sorry for late reply, unfortunately the picker SDK does requires user picking up file as required, while we do have [Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-javascript) which you interact with [Microsoft Graph API](https://graph.microsoft.io/en-us/) which doesn't have any user interaction and it [talks to OneDrive](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/onedrive) as well. Probably it will help.

**Comment by daboxu** [comment]
feel free to reopen it if you have any questions
