### ISSUE TITLE
Unable to access a file with .json extension in OneDrive for Business

### ISSUE THREAD

**Issue by rgregg** [OneDrive/onedrive-api-docs#508]
`GET https://graph.microsoft.com/v1.0/me/drive/root/children/foobar.json`

The error returned is:

```
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "2b4ac499-41b2-4833-a2e7-65f95d4418b4",
            "date": "2017-02-02T17:02:03"
        }
    }
}
```

**Comment by ificator** [comment]
We've tracked this done and have checked in a fix - it should start hitting production in a week or so.

**Comment by ificator** [comment]
Follow up [at StackOverflow](http://stackoverflow.com/questions/41849963/unknownerror-when-getting-file-from-onedrive-graph-api) when this is resolved.

**Comment by ificator** [comment]
This issue should now be resolved.
