### ISSUE TITLE
problem with error response json format

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#51]
did the following 2 different operation
1) GET /driv
wrong spelling for drive 
2) GET /drive/item/1D641CFAE05579A4!1160
wrong spelling for items
3) GET /drive/items/1D641CFAE05579A4!1160 (this folder has been deleted)
nothing wrong in uri

following are the response received 
1) & 2) same correct error response
![successful error](https://cloud.githubusercontent.com/assets/11455759/6842473/c4a29e40-d3be-11e4-985e-4e5c07859865.png)

3) something wrong with error response message
![wrong error response json](https://cloud.githubusercontent.com/assets/11455759/6842519/3676f6ba-d3bf-11e4-9012-ad77ba56f577.png)

i think this question has been raised before also, but the question arise for wht kind of uri/operations is inproper json response is been send from the server

**Comment by rgregg** [comment]
Hi @ankit-ankuagrawal I'm not sure what isn't proper about the second error. It's the same format as the first, although it has an additional inner error property, which is valid according to the schema defined in the $metadata response. However, it appears that our documentation is missing that case. I'll update our error documentation to be more clear about recursive innererror messages.

**Comment by ankit-ankuagrawal** [comment]
@rgregg as it was not documented, so thought it is an error, otherwise it is okay
ty fo ur response

**Comment by ankit-ankuagrawal** [comment]
for which kind of operations the 2nd type error json response comes (recursive one)?

**Comment by rgregg** [comment]
It could show up for any operation, it just depends on if we have more details about the error that would be useful to show.

**Comment by rgregg** [comment]
I've updated the docs to include this recursive nature. Thanks for pointing out the doc bug!
