### ISSUE TITLE
Upload multiple images

### ISSUE THREAD

**Issue by MiteshiOS** [OneDrive/onedrive-api-docs#510]
How to upload multiple image in one request ?

**Comment by D4N14L** [comment]
This is currently not something that is possible. However, while I can't speak for the future, we've definitely heard this request. Thanks for the feedback!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
