### ISSUE TITLE
OneDrive for Business Auth API problem: response misses the "refresh_token" parameter at step 4. "Redeem refresh token for an access token to call OneDrive API"

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#511]
When I use a Office 365 Business Premium account to call the OneDrive for Business Auth API, the response from step 4. "Redeem refresh token for an access token to call OneDrive API" misses the parameter "refresh_token", but when I use a OneDrive for Business account to do this there is no problem. So I want to kwon why this hanppened?

**Comment by rgregg** [comment]
Can you trying adding the `offline_access` scope to your list of scopes?

I believe some AAD tenants require the explicit request for offline access, where others default to granting all "secure client" apps an offline_access token.

**Comment by imkk** [comment]
OK, I'll have a try,  thank you.

**Comment by imkk** [comment]
@rgregg Can you tell me how to add a offline_access scope? I can not find this permission.

**Comment by rgregg** [comment]
Hi @imkk : I realized you're using the "v1" authentication mechanism, which doesn't take scopes the same way the v2 mechanism does. Is it possible for you to see if you can get a refresh token when using the v2 authorization end point, as described here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-app-registration

**Comment by imkk** [comment]
Yeah, you are right @rgregg , I found this problem from this page: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-compare. There is no way to solve this problem if I continue to use "v1" authentication mechanism, right?

**Comment by imkk** [comment]
Hi @rgregg , I have tried to use the v2 endpoint followed here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code. However, this is too different to use it to replace the OAuth 2.0 authentication flows here: https://dev.onedrive.com/auth/aad_oauth.htm. I don't kown how to switch from each other, so can you tell me what should I do?

**Comment by imkk** [comment]
Hi @rgregg , I have solve this problem using v2 endpoint.
