### ISSUE TITLE
Shared folder not available

### ISSUE THREAD

**Issue by dfournier** [OneDrive/onedrive-api-docs#512]
Hi,

We are having problems accessing a shared folder. I have added the shared folder in question to my OneDrive directly within the OneDrive webapp. I go back into the OneDrive shared popup. I can see the folder, click on it, but I cannot do anything with the files contained in the folder.

![screenshot](https://cloud.githubusercontent.com/assets/2329786/22695921/b2fab9ee-ed4c-11e6-8b01-db4e88c4fe96.png)

Any ideas?

Best,
David

**Comment by daboxu** [comment]
hi @dfournier thanks for reporting this, unfortunately the picker SDK does not support enable selecting in the shared folder right now but it is on our backlog list. I will mark this as an enhancement. You can also go to our [user voice](https://onedrive.uservoice.com/forums/262982-onedrive) part to create an item for you tracking.

**Comment by dfournier** [comment]
Thanks for your reply! Good to know it's at least in your backlog
