### ISSUE TITLE
Unable to upload to OneDrive For Business using UIDocumentPickerViewController

### ISSUE THREAD

**Issue by paulw11** [OneDrive/onedrive-api-docs#513]
I am attempting to upload a file to a OneDrive for Business store from an iOS app using the `UIDocumentPickerViewController` interface.

The OneDrive UI is displayed and I am able to select an upload location, but after tapping "Upload to OneDrive" a dialog is displayed "Sorry, there was a problem.  There might be a problem with the file".  If I select a OneDrive Personal location the file is uploaded correctly and I am able to upload a file to the OneDrive for Business location using the OneDrive app, so credentials and permissions appear to be OK.

**Comment by paulw11** [comment]
I am no longer experiencing this issue; Perhaps it was resolved by the OneDrive client app update on Feb 15?

**Comment by paulw11** [comment]
I am still having this issue.  When I had success last week I was on the corporate network for the OneDrive client organisation.  Now I am on my home network

**Comment by chackman** [comment]
Sorry about this very old issue going stale.  If this is still reproducing, could you please provide updated request & response information to help us investigate further?  Thanks.
