### ISSUE TITLE
Add If-Match etag always not match current items's value when deleting item

### ISSUE THREAD

**Issue by shinjikao** [OneDrive/onedrive-api-docs#514]
I want to delete an item on OneDrive , I sure the Item haven't change,so Etag should not change , but when I add if-match header in request ,the response error said :
{
  "error": {
    "code": "notAllowed",
    "message": "ETag does not match current item's value",
    "innererror": {
      "code": "preconditionFailed"
    }
  }
}
always 412 preconditionFailed reject my request , why I can't do it ? also I try this issue on postman ,I got same result like below figure :

_get an item's etag  ,make sure an item exist and etag value using on deleting request_
<a href="http://imgur.com/uZSEI5i"><img src="http://i.imgur.com/uZSEI5i.png" title="source: imgur.com" /></a>

_use this etag test deleting with if-match,the result of rejected deleting_
<a href="http://imgur.com/jkZGoHS"><img src="http://i.imgur.com/jkZGoHS.png" title="source: imgur.com" /></a>

**Comment by shinjikao** [comment]
any update for this?

**Comment by ificator** [comment]
Hi @shinjikao, we confirmed there is a bug here and have already checked in a fix. We'll let you know as soon as it's deployed.

Thanks for reporting it!

**Comment by ificator** [comment]
Hi @shinjikao this issue should now be resolved!
