### ISSUE TITLE
500's in me endpoint

### ISSUE THREAD

**Issue by JEBoothjr** [OneDrive/onedrive-api-docs#515]
We regularly receive 500's from the /me endpoint. We are a 3rd-party calling the API. We were receiving a generic server error, but now we're receiving the following:

`The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs`

Sometimes we can wait 10-15 minutes and it will work. How can we best figure this out?

**Comment by ificator** [comment]
Can you provide us with the full response (including headers) when you encounter one of these 500s?
