### ISSUE TITLE
Can't get whole list of childrens

### ISSUE THREAD

**Issue by MasterSoft24** [OneDrive/onedrive-api-docs#516]
I have a folder with 300 child elements. All child elements are enumerated from 1 to 300. I'm want to get list of them by send request 

https://api.onedrive.com/v1.0/drive/root:/Изображения:/children

I receive JSON with first 200 items and @odata.nextLink attribute with link to next portion of data

This link looks like: 

https://api.onedrive.com/v1.0/drives('me')/items('root%252F%25D0%2598%25D0%25B7%25D0%25BE%25D0%25B1%25D1%2580%25D0%25B0%25D0%25B6%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F')/children?$skiptoken=MjAx

I'm sending this request and receive JSON full equal of the previous answer. First 200 items and same @odata.nextLink attribute again. What can I do to get last 100 items?

**Comment by ificator** [comment]
Hi @MasterSoft24, I tried your scenario and was unable to reproduce it. In theory, the only way that the original set of items would be returned is if there was an issue with the $skiptoken provided in the request. Could you capture a full request as it's been sent to our service (i.e. all the headers etc)? Make sure you remove the `Authorization` header first.

**Comment by MasterSoft24** [comment]
Many thanks for your answer. I'm already find my mistake. I need was obtain $skiptoken from URL and send him  as extra parameter.
I apologize for wasting your time.

**Comment by ificator** [comment]
No worries - glad you figured it out!
