### ISSUE TITLE
Update Item add if-match etag under the same etag, get 412 Precondition Failed .

### ISSUE THREAD

**Issue by shinjikao** [OneDrive/onedrive-api-docs#518]
Like https://github.com/OneDrive/onedrive-api-docs/issues/514 issue the same, I create a folder , and would like to update it , whether add "if-match" or "if-none-match" , always get 412 Precondition Failed even etag are same.

_log_ like this, 
1156 [main] TRACE OneDriveProvider - server's etag aQ0JGNTk1MTAxRkE2OTNGNSE2NjQuMQ
1156 [main] TRACE OneDriveProvider - local's  etag aQ0JGNTk1MTAxRkE2OTNGNSE2NjQuMQ
1433 [main] ERROR OneDriveProvider - HTTP PRECON FAILED

Could you please comfirm this ? thank.

**Comment by ificator** [comment]
Hmm, I'm unable to reproduce this one - here's what I tried.

**Created a folder**
> PATCH https://api.onedrive.com/v1.0/drive/root:/tempfolder-1 HTTP/1.1
> Content-Type: application/json
> Host: api.onedrive.com
> Content-Length: 21
> 
> {
>   "folder": { }
> }
> 
> HTTP/1.1 201 Created
> 
> {
>   ...
>   "eTag": "aQTkwNUFFOTJGMkUzRTc2RCE5NjM4MTYuMA",
>   "id": "XXXXXX!963816",
>   "name": "tempfolder-1",
>   ...
> }

**Updated with correct ETag**
> PATCH https://api.onedrive.com/v1.0/drive/items/XXXXXX!963816 HTTP/1.1
> Content-Type: application/json
> Host: api.onedrive.com
> Content-Length: 30
> If-Match: aQTkwNUFFOTJGMkUzRTc2RCE5NjM4MTYuMA
> 
> {
>   "name": "tempfolder-2"
> }
> 
> HTTP/1.1 200 OK
> 
> {
>   ...
>   "eTag": "aQTkwNUFFOTJGMkUzRTc2RCE5NjM4MTYuMQ",
>   "id": "XXXXXX!963816",
>   "name": "tempfolder-2",
>   ...
> }
> 

**Updated with incorrect ETag**
> PATCH https://api.onedrive.com/v1.0/drive/items/XXXXXX!963816 HTTP/1.1
> Content-Type: application/json
> Host: api.onedrive.com
> Content-Length: 30
> If-Match: aQTkwNUFFOTJGMkUzRTc2RCE5NjM4MTYuMA
> 
> {
>   "name": "tempfolder-3"
> }
> 
> HTTP/1.1 412 Precondition Failed
> 
> {
>   "error": {
>     "code": "notAllowed",
>     "message": "ETag does not match current item's value",
>   }
> }

Did I do something different what you did to get the repro?

**Comment by shinjikao** [comment]
Please test with parentReference ,I want to rename and move to other folder(A folder)

PATCH https://api.onedrive.com/v1.0/drive/items/XXXXXX!XXXX HTTP/1.1
Content-Type: application/json
If-Match: etag
{
    "name": "SubFolderB",
    "parentReference" : {"path": "/drive/root:/A"}
}


{
  "error": {
    "code": "notAllowed",
    "message": "ETag does not match current item's value",
    "innererror": {
      "code": "preconditionFailed"
    }
  }
}

**Comment by ificator** [comment]
Confirmed that's the trick, thanks @shinjikao it's definitely a bug that we'll get fixed.

**Comment by ificator** [comment]
Hi @shinjikao, this should now be resolved.
