### ISSUE TITLE
API call to get email address

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#52]
pls include api call to get the "email address" of the OneDrive account

**Comment by saguiitay** [comment]
+1
Or at least bring back the /me endpoint

**Comment by rgregg** [comment]
Can you help me understand the scenario you need the email address of the user for?

**Comment by ankit-ankuagrawal** [comment]
scenario is between 
1) an organization
2) and there employees

now a days employees prefer to do work at there devices, implementing the concept of BYOD(bring your own device) to organization and work

if the employees are working from their personal devices, the organization want that there devices should adhere to company policies and rule

there is product MaaS360 Secure Docs (contains large no of sources such google drive, sharepoint etc). and the product is control by the organization, if the organization want that no other email_id to be used other than the registered one access sources.

in this we required the user email_id, to check wheather it has been restricted from organization or not, if blocked we dont give access to sources otherwise they can used

***currently using live connect api to get the email_id of the user "/me"

the problem is that, now totally using new onedrive apis and for just email_id i have to call that live connect service, 
the error json format of live connect service totally different from error json format of new onedrive apis

**Comment by rgregg** [comment]
Thanks for the details on the scenario. I've added an item to our backlog to track this. Do you mind creating a suggestion on our [OneDrive User Voice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) site so the community can help us prioritize the issue?

**Comment by saguiitay** [comment]
I've opened an idea in UserVoice: http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7475062-support-retrieving-user-profile-information-via-ap

**Comment by mmarmol** [comment]
+1 on this one, I can figure out a way to get the user email. In our cause our application works offline. we cant send the user an email if something came up, if refresh token was lost for some reason or anything. We would need to let the user manually intro the email or use other api just for that.

**Comment by OsmondYe** [comment]
+1

**Comment by susamn** [comment]
+1

**Comment by rgregg** [comment]
This is available using the Microsoft Graph API now, if your app has requested User.Read permissions.

You can make a request to get the signed in user's email:
`GET https://graph.microsoft.com/v1.0/me/mail`

Or you can make a request to get a particular user's email, based on a user ID:
`GET https://graph.microsoft.com/v1.0/users/{userId}/mail`

You can also use the createdByUser and lastModifiedByUser navigation properties on an item to retrieve the email address for the user who created/modified the file.

**Comment by Kyba1985** [comment]
@rgregg Hi,  used your endpoint with authorization token obtained from onedrive oauth2 flow. I received error:

Status Code: 401
{
    "error": {
        "code": "InvalidAuthenticationToken",
        "message": "CompactToken parsing failed with error code: -2147184118",
        "innerError": {
            "request-id": "2b490502-0ff4-4e5d-9c70-909a82114d52",
            "date": "2017-03-21T16:27:03"
        }
    }
}

Which permission i need to get the mail from this endpoint? I read this hint on the graph explorer:

This query requires additional permissions. If you are an administrator, you can click here to grant them on behalf of your entire organization. Or, you can try the same request against your own tenant by creating a free Office 365 developer account.

Thanks in advance

**Comment by rgregg** [comment]
To call Microsoft Graph, you need to use the AAD OAuth v2 authorization / token end point. It's different than what you would have been using for OneDrive personal previously, but documented here: https://dev.onedrive.com/auth/graph_oauth.htm
