### ISSUE TITLE
Bad Argument error while creating new subscription on onedrive

### ISSUE THREAD

**Issue by amit-balisana** [OneDrive/onedrive-api-docs#522]
I am getting
{"error":{"code":"invalidRequest","message":"Bad Argument"}
while creating new subscription
the url i am using to post the json is
https://api.onedrive.com/v1.0/drive/items/{item_id}/subscriptions
also setting this header Content-Type: application/json
and my payload is
{
 "notificationUrl": "https://mycallbackurl",
 "expirationDateTime": "2016-01-01T11:23:00.000Z"
}
The callback url is getting called for validation successfully and then i get the error message.

**Comment by ificator** [comment]
Hi @amit-balisana, can you provide us with a copy of the HTTP headers from the response that contains the bad argument message?

**Comment by johnlilis** [comment]
I'm having the exact same issue.
The HTTP headers from the response are the following:
{
	"Via": ["1.1 DM5SCH102231022 (wls-colorado)"],
	"Content-Length": ["60"],
	"Content-Type": ["application\/json"],
	"Server": ["Microsoft-IIS\/8.5"],
	"P3P": ["CP=\"BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo\""],
	"X-WLSPROXY": ["DM5SCH102231022"],
	"X-MSNSERVER": ["BN2BAP9979800FC"],
	"Strict-Transport-Security": ["max-age=31536000; includeSubDomains"],
	"X-QosStats": ["{\"ApiId\":0,\"ResultType\":2,\"SourcePropertyId\":0,\"TargetPropertyId\":42}"],
	"X-ThrowSite": ["06bc.2f83"],
	"X-AsmVersion": ["UNKNOWN; 21.2.0.0"],
	"X-MSEdge-Ref": ["Ref A: FF9043AA5DE3481CA58F4F79A4439467 Ref B: ATH01EDGE0116 Ref C: Thu Mar 23 13:31:07 2017 PST"],
	"Date": ["Thu, 23 Mar 2017 20:31:07 GMT"]
}

Any ideas?

**Comment by ificator** [comment]
@johnlilis your error is due to the expiry being out of range. From memory I believe the limit is 365 days - are you by any chance trying a value larger than that?

**Comment by johnlilis** [comment]
@ificator thank you very much for your response. This was indeed the error.
I was trying a value a of a couple of months, but after some testing it seems that the limit is 1 month.
