### ISSUE TITLE
Unsupported segment type question: Daemon App trying to upload file.

### ISSUE THREAD

**Issue by tathagatbanerjee** [OneDrive/onedrive-api-docs#526]
Hi,

I'm trying to upload a file into a groups onedrive, and had a few questions. The error - 
```
 Exception while invoking method 'msGraph.utils' Error: failed [400] {
I20170228-16:34:28.801(11)?    "error": {
I20170228-16:34:28.801(11)?      "code": "BadRequest",
I20170228-16:34:28.801(11)?      "message": "Unsupported segment type. ODataQuery: groups/851b94a2-5daa-47e0-8441-89a29563f3ff/drive/root/test1.txt/This%20is%20some%20content",
I20170228-16:34:28.801(11)?      "innerError": {
I20170228-16:34:28.802(11)?        "request-id": "af48afcb-4cb1-45ea-b917-da1a4cca6c87",
I20170228-16:34:28.802(11)?        "date": "2017-02-28T05:34:26"
I20170228-16:34:28.802(11)?      }
I20170228-16:34:28.802(11)?    }
I20170228-16:34:28.803(11)?  }

```

The code I'm using - 
```
case ('putFile'): {
  const method = 'PUT';

  const groupId = msGraphInformation.groupId;
  const fileName = msGraphInformation.fileName;
  const fileContent = msGraphInformation.fileContent;

  const url = 'https://graph.microsoft.com/v1.0/'
    + 'groups/'
    + groupId
    + '/drive/root'
    + `/${fileName}/`
    + fileContent;

  const headers = {
    'Authorization': `Bearer ${msGraphInformation.token}`,
    'Content-Type': 'text/plain',
  };

  return await HTTP.call(method, url, { headers });
}
```

Questions - 
(1) I am able to authenticate and get users and group drive items etc fine without any issues.
(2) Is it possible for a daemon to upload files directly into a group's onedrive? It is a little unclear if this use case is supported. Additionally there are references to a binary stream being the only accepted format? Can you please clarify this - does it mean no utf-8 or base64, but rather a 'binary' type? Any recommended library for doing this in node?
(3) How do i get the root id of a groups onedrive? If I use code like below, it works fine, and tells me there are no children in the root of the groups onedrive (which is expected as I just created the group, and it contains nothing). But what is the actual root id, is it just the drive id?
```
case ('getGroupDriveRootChildren'): {
  const method = 'GET';
  const url = 'https://graph.microsoft.com/v1.0/'
    + 'groups/'
    + msGraphInformation.groupId
    + '/drive/root/children';

  const headers = {
    'Authorization': `Bearer ${msGraphInformation.token}`,
  };

  return await HTTP.call(method, url, { headers });
}
```
(4) The groups onedrive (if i just do a get on the group drive) shows up as type 'documentLibrary', i.e. a sharepoint drive. Is this expected? [ groups/{group-id}/drive ]

Big fan of the stuff you are doing. It was a rocky start, but once authentication got sorted (this is definitely not the easiest), it seems to be ok. Use a daemon seems to be a bit of a second class use-case though, as opposed to using a user login type app. Any assistance on the above would be very much appreciated. 

Thanks so much. 

Tat

**Comment by katahir** [comment]
Hi,
Uploading files to a group's OneDrive should be possible using app-only access tokens, and is a first class scenario. To get the root id, you should make a call to /drive/root and that will return the id. A group's onedrive showing up as 'documentLibrary' is expected as well. At the end of the day, a group site is a SharePoint site collection. And finally, you are getting the error message because you are not using the right syntax. Here is what I would do:

  const url = 'https://graph.microsoft.com/v1.0/'
    + 'groups/'
    + groupId
    + '/drive/root'
    + `:/${fileName}:/`
    + fileContent;

Notice the colon right before and after the filename.

**Comment by tathagatbanerjee** [comment]
Thanks so much for the response.  It was quite helpful. There were two issues, first, the path was incorrect, and second, I was treating the content incorrectly. Thanks so much.

For anyone else looking: a working function is below:
```
case ('putItem'): {
  const method = 'PUT';

  const url = 'https://graph.microsoft.com/v1.0/'
    + 'groups/'
    + msGraphInformation.groupId
    + '/drive/root'
    + `:/${msGraphInformation.fileName}:` // needs the slash at the start of the path after the :
    + '/content'; // I had thought this was the actual content here stupidly

  const headers = {
    'Authorization': `Bearer ${msGraphInformation.token}`,
    'Content-Type': 'text/plain',
  };

  const data = msGraphInformation.fileContent; // content needs to be passed here...

  return await HTTP.call(method, url, { headers, data });
}
```
