### ISSUE TITLE
GET file content not working - daemon version

### ISSUE THREAD

**Issue by tathagatbanerjee** [OneDrive/onedrive-api-docs#528]
Hi,

Probably related to [this](https://github.com/OneDrive/onedrive-api-docs/issues/485) issue.

(1) GET for item meta data works (sort of). The below functions works properly, but does not appear to be documented. The documentation [here](https://dev.onedrive.com/items/get.htm) suggests `GET /drive/items/{item-id}`, below I am using `GET groups/{group-id}/drive/items/{item-id}` which works fine.
```
case ('getItemMetaData'): {
  const method = 'GET';

  const url = 'https://graph.microsoft.com/v1.0/'
    + 'groups/'
    + msGraphInformation.groupId
    + '/drive/items/'
    + msGraphInformation.itemId;

  const headers = {
    'Authorization': `Bearer ${msGraphInformation.token}`,
  };

  return await HTTP.call(method, url, { headers });
}
```
(1a) Note: Using the documentation code `GET /drive/items/{item-id}` causes an error shown below, which makes sense as this is obviously a group onedrive.
```
Exception while invoking method 'msGraph.utils' Error: failed [404] {
I20170301-11:17:42.982(11)?    "error": {
I20170301-11:17:42.982(11)?      "code": "itemNotFound",
I20170301-11:17:42.982(11)?      "message": "The resource could not be found.",
I20170301-11:17:42.982(11)?      "innerError": {
I20170301-11:17:42.982(11)?        "request-id": "4653e05b-da7c-42df-9282-32733e2aa81b",
I20170301-11:17:42.982(11)?        "date": "2017-03-01T00:17:41"
I20170301-11:17:42.983(11)?      }
I20170301-11:17:42.983(11)?    }
I20170301-11:17:42.983(11)?  }
```

(2) Using the modified code `GET groups/{group-id}/drive/items/{item-id}`, getting the metadata is fine.

(3) Attempting the same thing but for the download does not work, and throws a 403 Forbidden Error. Code below, <i>note I am passing the group id even though the documentation does not ask for it</i>. Can you please confirm if this is a permissions issue? I've tried giving the app most of the permissions, but no luck. Also, getting the meta-data is working so... 
```
case ('getItem'): {
  const method = 'GET';

  const url = 'https://graph.microsoft.com/v1.0/'
    + 'groups/'
    + msGraphInformation.groupId
    + '/drive/items/'
    + msGraphInformation.itemId
    + '/content';

  const headers = {
    'Authorization': `Bearer ${msGraphInformation.token}`,
  };

  return await HTTP.call(method, url, { headers });
}
``` 

(4) SImply accessing the data from the URL using the property '@microsoft.graph.downloadUrl' from the meta data get is not working either. This is also throwing a 403: Forbidden Error. That being said, the download path seems fine. However, I cannot reach it from the browser.

Looking at the access token the permissions are below, am I missing something?

![image](https://cloud.githubusercontent.com/assets/11780602/23441279/868667d4-fe75-11e6-8330-cf5c4082ea49.png)

Download link also looks ok as far as I can tell.

(5) I also tried to remove the authorisation header for the download, but no luck. Download code below.
```
case ('downloadItem'): {
  const method = 'GET';

  const url = msGraphInformation.downloadUrl;

  const headers = {
    'Authorization': `Bearer ${msGraphInformation.token}`,
  };

  return await HTTP.call(method, url, { headers });
}
```

(6) The files are very much present, but I'm looking at this with an admin account so not sure this is useful.

![image](https://cloud.githubusercontent.com/assets/11780602/23441008/da368348-fe73-11e6-944d-0135ef6baecd.png)

Could you guys please have a look when you get a chance. I think it is pretty similar to the other Get contents issue from last December. Also, a fix to the documentation to include the groups use case would be very much appreciated (or a recommended way to download the contents). Thanks so much.

**Comment by katahir** [comment]
Hi tathagatbanerjee,
I am assuming you are using an app-only token. If so, there is a known issue with downloading the content of files using this token. You can however, fetch the metadata as you already pointed out. We are working to fix this issue. Stay tuned.

**Comment by ificator** [comment]
You can track progress on the issue over at #280

**Comment by bobbyfu** [comment]
why do we close this issue?  It is not fixed. The issue of [#280 ](https://github.com/OneDrive/onedrive-api-docs/issues/280) is related to v2.0.  It seems to me that both v1.0 and v2.0 are not working.

**Comment by ificator** [comment]
It's the same issue - Graph v1.0 is the same as OneDrive Business v2.0 so we decided to track it using the issue that had more details and close off this one to avoid duplicate investigations.

**Comment by pethuraj143** [comment]
@ificator I did not got any SPRequestGuid with header response.. I got the below response.

HTTP/1.1 403 Forbidden
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
X-SharePointHealthScore: 1
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.7604
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: ECBE76BB92EF4B79A18DDDBFF37DBBFF Ref B: MAA01EDGE0216 Ref C: 2018-04-14T16:01:04Z
Date: Sat, 14 Apr 2018 16:01:04 GMT

d
403 FORBIDDEN
0

**Comment by ificator** [comment]
@pethuraj143 the lack of the header complicates things. It suggests a fairly early, low level, failure.

If you can make changes to code I'd add an `SPResponseGuid` header to your request that contains a generated GUID. You can than give us that GUID along with the 403 response (like you did above) and we may have some luck.

**Comment by hellolindsay** [comment]
I am also getting 403 Forbidden with all urls from @microsoft.graph.downloadUrl - looks like it started within the last day-ish.

**Comment by ificator** [comment]
@pethuraj143  @hellolindsay  @shkedi 

Are all of you using app-only / daemon scenarios? I want to make sure we're all on the same page.

**Comment by pethuraj143** [comment]
@ificator yes..app only scenario..

**Comment by bokmadsen** [comment]
After spending most of my day investigating this issue I can conclude, that this is directly related to the OneDrive API for Sharepoint. I can replicate the issue by authenticating directly to this endpoint and getting the downloadUrl for a file:

https://xxxxxx.sharepoint.com/sites/xxxxxx/_api/v2.0/drives/xxxxxxxx/items/xxxxx
This is not MS Graph related as such

**Comment by ificator** [comment]
I have a repro - we're drilling in now.

**Comment by volmedo** [comment]
Same here. I've tested both app-only and user-delegated scenarios and the second one is working correctly. The problem is related with preauthenticated URLs, requests containing an `Authorization: Bearer` header work without issues.

**Comment by ificator** [comment]
We tracked down the issue to a new feature that was recently enabled and shut it off. The app-only scenarios should now be working as expected so please let us know if you continue to see issues.

**Comment by volmedo** [comment]
I can confirm it is working again.

**Comment by bokmadsen** [comment]
It seems to be working again. I haven’t tested all tenants

**Comment by shkedi** [comment]
Working also on my side, thanks to everyone :)

**Comment by hellolindsay** [comment]
Works for me too. 👍

**Comment by bokmadsen** [comment]
It's happening again. Please fix ASAP

**Comment by ificator** [comment]
This should, once again, be resolved. I apologize for the reoccurrence.

**Comment by dfeinzeig** [comment]
i think maybe this is busted again? we are seeing issues when trying to get content for a specific version of an item.
