### ISSUE TITLE
Cannot download portion of a file using OneDrive or SharePoint API

### ISSUE THREAD

**Issue by igremlin** [OneDrive/onedrive-api-docs#529]
-inability to download a file using the OneDrive API with an app-only token (#280)
-inability to partially download a file using the Sharepoint Online API

Details are at:
https://gist.github.com/dtheodor/0745d1356bab8ab15e0cc9512ec2c8fe

**Comment by ificator** [comment]
Unfortunately we're unlikely to make any enhancements to the older REST API, and so they only resolution for this issue is to wait for #280 to be resolved. Hopefully not too much longer :(
