### ISSUE TITLE
Upload sessions don't support zero length files

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#53]
Upload sessions don't appear to support 0-length files.  Is this intended?

In the first upload fragment, I tried setting the "Content-Length" to 0, and setting the "Content-Range" to values like: "0/0", "0-0/0", or not using that header at all, but I get a 400 Invalid Argument error.

I ended up using the Simple Item upload method to implement this.

Should the documentation be updated, or should the upload session support empty files?

**Comment by Lyrrad** [comment]
https://github.com/OneDrive/onedrive-api-docs/blob/master/items/create.md

Looks like the documentation says that "You can't create empty files in OneDrive."  However, you are able to do so with the Simple Item Upload method.

**Comment by peternied** [comment]
Looks like a bug in our documentation, I'll patch that up!
