### ISSUE TITLE
How long OneDrive SDK going to be supported

### ISSUE THREAD

**Issue by prakashguru** [OneDrive/onedrive-api-docs#531]
Hi, I am aware that lot of development of f onedrive heading to Graph SDK. And I saw lot of posts have wording that "use graph sdk thats where the ondrive sdk is heading too".

On Feb 23, The link for OneDrive SDK is removed from the Official SDK page and replaced by graph sdk. https://dev.onedrive.com/sdks.htm  https://github.com/OneDrive/onedrive-api-docs/commits/master/sdks.md

We have built an intergation with onedrive using onedrive sdk. I have a long release cycles. Also I am not sure wthether the Graph API supports all the features of the onedrive sdk.

I have couplke of questions based on the ansewrs I can accordingly decide the migration of my application from OneDrive SDK to Graph SDK. 

1. How long the onedrive sdk going to be supported?
2. When will the Graph SDK will become feature parity with OneDrive SDK?

Thanks,
Prakash

**Comment by prakashguru** [comment]
Any updates on this?

**Comment by rgregg** [comment]
Missed this issue getting assigned to me. Sorry about that.

The OneDrive SDK and OneDrive end point continue to be supported. We don't have plans at this moment to deprecate either. We would communicate any deprecation according to our API deprecation policy, which gives at least a year of notice before we deprecate something under normal circumstances.

If you are using the C# SDK the Graph SDK should have full parity today.

**Comment by ankit-ankuagrawal** [comment]
@ryan gregg

Lets say if OneDrive SDK will be depreciated, does it mean that OneDrive
API's will be depreciated?

**Comment by rgregg** [comment]
I can't speculate on what we would do in the future, but we have no plans to deprecate the OneDrive APIs any time soon.
