### ISSUE TITLE
500 internal error on /search -

### ISSUE THREAD

**Issue by JohnRSim** [OneDrive/onedrive-api-docs#532]
When I add ?expand=thumbnails to the search query to return thumbnails with the resultset ie - 
Request URL: https://graph.microsoft.com/v1.0/me/drive/root/search(q='1d')?expand=thumbnails

I get back the results but also an error code is appended and the response is a 500err.

```
...Search Result... .. ..
  "error": {
    "code": "InternalServerError",
    "message": "Object reference not set to an instance of an object.",
    "innerError": {
      "request-id": "d2329198-2207-45bb-b6e1-b82c6e19bcad",
      "date": "2017-03-04T14:18:45"
    }
  }
}
```

is it not possible to return thumbnails of results ie
```
?expand=children(expand=thumbnails(select=large))'
```

**Comment by ificator** [comment]
Thanks for reporting @JohnRSim!  Can you quickly clarify whether you're seeing this with a business or consumer account?

**Comment by katahir** [comment]
@JohnRSim Thanks for reporting the issue. This was indeed a bug in graph API. We are actively working on a fix. Stay tuned.

**Comment by JohnRSim** [comment]
Thanks Katahir - sorry I havent been able to get back sooner I've been traveling with little availability.
Any thoughts on when this will be fixed with the ability to deliver thumbnails on search?

**Comment by katahir** [comment]
@JohnRSim This issue should now be fixed. I am going to close out the thread. Feel free to reactivate if you still run into this issue.
