### ISSUE TITLE
Auto-Login OneDrive File picker

### ISSUE THREAD

**Issue by Ethaan** [OneDrive/onedrive-api-docs#534]
Like the title says, is there a way to avoid the user to login every time he open the file picker on my website?, the logic to get and save the `accessToken` is done, im just dealing this this.

Reading a bit on 2014 posts etc seems like `redirectUri` is the answer, but i cant find anything else.

i just want to.

```
OneDrive.open({
 ...stuff,
 advanced: {
   redirectUri: 'someUrlWithTheAccessToken' // ???
 }
});
```

im missing a point here?

**Comment by daboxu** [comment]
hi @Ethaan , do you mean you already having the token and want to pass in the Picker to making requests for you?

**Comment by Ethaan** [comment]
@daboxu yeah, basically when i do `OneDrive.open()` it opens the oauth screen again and ask the user to login again, is there a way to redirect the user the to the files screen? i suppose it should be using the `accessToken` but i cant find how.

BTW im using the v7 API

**Comment by daboxu** [comment]
hi @Ethaan , thanks for the detail information, unfortunately, we don't fully support it in v7 Picker, we only support passing access token for displaying file picker for SharePoint document library in v7. While your ask is a feature we want to delivery in the next version.

**Comment by Ethaan** [comment]
@daboxu Got It, this is enought to get my Project manager away for a time hehe.

Thanks, closing this
