### ISSUE TITLE
API to download folder (as ZIP) ?

### ISSUE THREAD

**Issue by GauSim** [OneDrive/onedrive-api-docs#536]
I see there is the[ download API](https://dev.onedrive.com/items/download.htm).
But it does not work on folders?
with 
```
GET /drive/items/{FOLDERID}/content
```

i get: 
```
{
  "error": {
    "code": "itemNotFound",
    "message": "The specified item does not exist, or does not have content.",
    "innerError": {
      "request-id": "######-#####-#####-####-######",
      "date": "2017-03-07T23:24:05"
    }
  }
}
```

no location header... 

on the official onedrive webapp you can download a folder as zip, 
is this provided some where?

**Comment by katahir** [comment]
@GauSim  There is currently no support for this. However you do bring up a good point. We have taken a note of it and will look to add the support in the near future.

**Comment by ificator** [comment]
I'm going to close this out since we don't track enhancements in this GitHub repo. Please feel free to visit our [user voice](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) site and create/upvote an idea for this.

**Comment by jayarjo** [comment]
Was there any progress on this feature?
