### ISSUE TITLE
When will GET /drive doesn't have display name?

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#538]
Hi, 

I have a user that have empty display_name from GET /drive api
```
{
    "status": {
        "state": "active"
    },
    "quota": {
        "used": 1948188471,
        "deleted": 8834994,
        "storagePlans": {
            "upgradeAvailable": true
        },
        "state": "normal",
        "total": 16106127360,
        "remaining": 14157938889
    },
    "@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives/$entity",
    "owner": {
        "user": {
            "displayName": "",
            "id": "{userid}"
        }
    },
    "driveType": "personal",
    "id": "{userid}"
}
```

and I tried old GET /v5.0/me api
```
{
    "first_name": null,
    "last_name": null,
    "name": null,
    "locale": null,
    "gender": null,
    "id": "{userid}",
    "emails": {
        "personal": null,
        "account": null,
        "preferred": null,
        "business": null
    }
}
```

most informations are empty, is it normal? how can I get correct information for this account?

thanks.

**Comment by verybada** [comment]
@katahir  @rgregg Any suggestion?

**Comment by daspek** [comment]
@verybada, the information available comes from the user's personal profile stored with Microsoft Account. It is possible for some fields to be empty, especially for very old accounts. The recommended way for accessing profile information is through the [Microsoft Graph API](https://graph.microsoft.io), which is the authoritative API for profile information. Note that those fields may still be empty when using that API.

Is this one of your own accounts that you expect to have a value for, or did you run into this with one of your users, who might actually intend to have an unspecified display name?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
