### ISSUE TITLE
@name.conflictBehaviour is set to replace by default

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#54]
According to https://github.com/OneDrive/onedrive-api-docs/blob/master/items/create.md @name.conflictBehavior is set to "fail" by default.  However, it appears to be set to "replace".  I attempted to upload files using both the Simple item upload and the Resumable Upload.  In both cases, the file was replaced unless I explicitly set it to "fail".

**Comment by rgregg** [comment]
We're taking a look at this to make sure we have a reasonable default value that is applied consistently. We'll update with a decision soon.
