### ISSUE TITLE
Redirect on cancel

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#541]
After selecting a file to upload, and after a selecting a folder to upload to, hitting the cancel button will cause a redirect withing the pop up window to the page it was launched from. Is there a way to prevent this redirect on cancelling ?

Thank you
Phuong

**Comment by daboxu** [comment]
@neunygph for picker SDK v6.0 and v7.0 they are inevitable, while we do provide option.advanced.redirectUri you can specify to a blank page referencing the SDK.

**Comment by neunygph** [comment]
hi @daboxu 

Thanks for the response, I tried the advanced.redirectUri and it works like a charm. 

Thank you very much

**Comment by daboxu** [comment]
no problem, let me know if you have any questions!
