### ISSUE TITLE
When delete file on onedrive not getting deleted facet.

### ISSUE THREAD

**Issue by amit-balisana** [OneDrive/onedrive-api-docs#542]
Hi There,
     As mentioned on onedrive api documentation when a file is deleted Api should return a deleted facet in the driveItem response. but when i call view.delta api to check the changes on a particular folder it gives me that file in response but is there no deleted facet so how do i differentiate between the files that have been deleted and those which are just updated.

**Comment by ificator** [comment]
This issue has already been reported (#535) and a fix is deploying as we speak. We'll add an update when it's considered resolved.
