### ISSUE TITLE
Copy redirect to an invalid location

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#545]
Hi,

I get 400 API not found after copy success, the copy api redirect me to a weird location "/v1.0/drives('me')/items('')". 

```
"POST /v1.0/drive/items/5F663FB20714AA03!11000/action.copy HTTP/1.1" 202 0
"GET /v1.0/monitor/3s6fwSsFIw07knGShvP5_1RfXArb1mAMFrf75u_OoHTd1Tgdedti1c0GAtVICfAXFKSz2pbIJWyGesxzFyGEOSuWG4LIjlOpdpGh4CEBSLxqdxprfJ6azBM_k6PHUWXmLltJqrODSZlqYcp9T83DdYYwvG97QcUaB-xJlzZmV6AMRl5uN9kM7NJSlwHx5I97Ne HTTP/1.1" 303 141
"GET /v1.0/drives('me')/items('') HTTP/1.1" 400 61
400 {"error":{"code":"invalidRequest","message":"API not found"}} 
```

**Comment by ificator** [comment]
Also reported via StackOverflow
http://stackoverflow.com/questions/42781729/copy-file-on-onedrive-rest-api/42790950#42790950

**Comment by akshaykumar6** [comment]
Hi @ificator,

We are also facing the same issue while hitting the copy monitor URL. Can you please let us know when will this be fixed? We have to update our clients accordingly.

Thanks!

**Comment by ificator** [comment]
Hi @akshaykumar6, our expectation is that it'll be fixed in the next day or so.

**Comment by ificator** [comment]
Looks like it's actually just finished deploying, so things should be back to normal. Please let us know if you continue to see issues.

NOTE: only new copy sessions will be fixed

**Comment by spyronis** [comment]
Thanks, I can see that it is ok now.

**Comment by verybada** [comment]
Hi,

It happens again but return 401 this time.

```
"POST /_api/v2.0/me/drive/items/01P6SIEXK3FVKD2T5OOVHIIEZZ3EECNMHP/action.copy HTTP/1.1" 202 0
"GET /personal/xxx/_api/v2.0/drives/b!oUBz-7j8y0uxka7UorcmSsqLv8OmI4xGoANyz1EVwu7zetdkZayCSpFi_V5xCG8L/items/01P6SIEXP5Q5GVC2D5HRFLGIVM44GBC2MJ?force303=1&tempauth=$token HTTP/1.1" 303 None
"GET /personal/xxx/_api/v2.0/drives/b!oUBz-7j8y0uxka7UorcmSsqLv8OmI4xGoANyz1EVwu7zetdkZayCSpFi_V5xCG8L/items/01P6SIEXP5Q5GVC2D5HRFLGIVM44GBC2MJ?tempauth=$token HTTP/1.1" 401 98
```

**Comment by spyronis** [comment]
Same for me
Getting a 500 error during copy progress monitoring:

https://api.onedrive.com/v1.0/monitor/4sd2bQ5d4XVqW6FDSJDLyw5ROIJ_dTuDfIvgTefjM0uZWhAR1B-Dk1Y1I8AKtpo0duwtohzb41E5E7UJRpadf5CkrcsRqH5B9bbJNy8wPnTnV9-SXkMIdPn7RHK8lbfUsfeRKFZNroZvHpNfs55URyPxXrx45c9tSgTQcx7JuYWVV84F-G19qvnzB56lBc8-6b_LEXOlGlc0dZU0eddqIPbw?access_token=EwAoA61DBAAUGCCXc8wU%2fzFu9QnLdZXy+YnElFkAAWn3lTy4D5lyZVO4ETqTZGHuIeyhQdzL8HhT2Qo9LQY1SUmBWeAnJSO+M3MX06psAaZu7LGaldIirYbcOToiMDMp7OC0WnXpCsyraG1nBnmNDk8XNbnKTqI1fp0KV3UijNzEpAcNG9IrkSRc2EGYkIzySBR5A+dQcnWxufNonq4ccun8HDB8m2DkWrgOuSM7I9Gm%2f7z0bNS1e65JOhMZmnaGtMMeF2V35FYfbqlXJHHZi%2f9OikX59qJ3PY6q4h7gmJPd8Eqo6W4Yh6OR1vjdL+wZ+t7VhCEudmzo8f3JAlXwSXrM%2f3BTMJqYQJgilQlYUCEXNM6PJFzKtTD+5eIjNIQDZgAACN8mKZNlWv5++AEiVmtGHJl2uZG5JqdbnAKUqc1Art71gm7yqwCOmX8zopA1X%2fiIP9QkFciiNerYDE9iAOlTr1BUINIqHialaLKD7fxqBbChIRFNHjxcppllTNgNR4ax8coYqzpxMQONzApmLZF%2ftyq5QGhPOaoUWEQZVaG740wVTmlc0DkTZDOulIZf6uCK0MdQ7xJeZwhDygzYODoktmoWVh8CzF9R74kNFl9U2oU2jZPnuwEmOzKyxkrTxrUM0CJcGgQZyY+qq4lqEzZLbEg5mpQH5lKz+0mRwqhPkBMB82%2fBPcjSztajUswgZdoxtdg4jQbxNuKuBPqlYoTyO7h+xuNL%2fwCdxzC0TmoQOJUmgZLFrazPPqjf%2fJxixPfVjhfD7xWHxt1dOlHc5wgX2veIuzLNob0GHb%2fE0S8m4MM%2fJJMTRPIjl+UO5a0K27lRFNxU2kijAU1AjaNil2uRfoG6z8u2%2fkVCWOqC7bOPlgMhoFMcA46DKFKBxcHwpPxqURnQNt0eqbXLbllIQP+JeDPRP9atrgualzg6QjaAFYmIwZCNvADA8x17m4b7pJ6UMTUgoCbFpqVPcXUqt00w1ejAUMGBnGROy13V8syL2SYD8bAeCDoceufzA3zb81VnQOqqOU8UDTGKMXWnf77dJNQuY40URKvLHUZ507C40YoAxgFHAg%3d%3d
