### ISSUE TITLE
How to get the content of files using OneDrive file picker 

### ISSUE THREAD

**Issue by OriAmir** [OneDrive/onedrive-api-docs#547]
Hey. I using [one drive js picker](https://dev.onedrive.com/sdk/js-v5/javascript-picker-saver.htm) tutorial and I success to select files and to get some information about them  . I try all options to get the **content** of the file that I could use it in my js file but without success.
I try many 'GET' request to the url that I get as response from the picer - @microsoft.graph.downloadUrl , webUrl etc but every thing return me different errors without any content .
`       
               var xhr = new XMLHttpRequest();
                xhr.open("GET", url, true);
                        xhr.setRequestHeader("Access-Control-Allow-Origin", "*");
                        xhr.setRequestHeader("Access-Control-Allow-Credentials", true);`

I not really understand to where and what I need to send to get the **content** of the file that I get from the picker ?I need to add something special or what?

Thanks all !!

**Comment by rgregg** [comment]
Hi @OriAmir:

If you are trying to download the file and use the contents of the file inside your JavaScript, then all you need to do is a simple GET on the @microsoft.graph.downloadUrl. No need to add the additional headers, allow authentication, etc.

There's an example using JQuery to open a picked file and use the contents inside the app here: https://github.com/OneDrive/onedrive-texteditor-js/blob/master/js/text-edit.picker.js#L41

Without JQuery, you would use similar code:

```javascript
var selectedFile = files.value[0];
var downloadLink = selectedFile["@microsoft.graph.downloadUrl"];
var xhr = new XMLHttpRequest();
xhr.open("GET", downloadLink, true);
xhr.onreadystatechange = function () {
        if(xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
            // do something with the responseText, which is if the file
            console.log(xhr.responseText);
        }
    };
xhr.send();
```

**Comment by OriAmir** [comment]
Great , I don't think it's so simple! Thank you very much !
