### ISSUE TITLE
OneDrive file picker doesn't work when 'redirectUri' set to different subdomain

### ISSUE THREAD

**Issue by Inok** [OneDrive/onedrive-api-docs#548]
Hi,

I want to open file picker from subdomain of my site. For example, files.mysite.com. And I set 'redirectUri' parameter to root domain url, like 'mysite.com/oneDriveFilePicker'. So I open picker window from files.mysite.com, popup redirects me to mysite.com/oneDrivePicker, that redirects to OneDrive file list. I select files, press Open button, it redirects me back to mysite.com/oneDrivePicker. And at this step picker fails. 
It fails because browser restricts to access _window.opener.onedriveReceiveMessage_ from picker popup window. It's because opener and popup windows has different domains (files.mysite.com and mysite.com).
Maybe, you should use _Window.postMessage()_ for communication between opener and popup?

Actually, I found a workaround for this one. I set document.domain to 'mysite.com' for both opener and popup windows, and it solves problem with _window.opener.onedriveReceiveMessage_.

Unfortunately, now file picker throws error 'missing access token' at _parsePickerResponse()_. I guess it's because you use localStorage to share data between opener and picker. But all domains have their own localStorages, so localStorage of files.mysite.com is not accessible from mysite.com and vice versa.

**Comment by daboxu** [comment]
hi @Inok , that's for the reply, the different domain limit is by design due to security integrity we have for other cases. Sorry for now, the picker only support in the same domain. Maybe you can try redirect mode? It will do all redirects in same window so you can control the communication between picker window and your host window by your self.

**Comment by Inok** [comment]
> the different domain limit is by design

So this is mistake at documentation? https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm
> This URL must be in the **same root domain** and use the same protocol as the page hosting the picker SDK.

Could you please explain more about redirect mode? As far as I understand, it still requires 'redirectUrl' to be at the same domain. If I need to show file picker at multiple subdomains (and it so), then I need to implement pages like files.mysite.com/onedrivepicker at each subdomain I have.

By the way, what about using window.opener.foo instead of localstorage? It will be cross-domain only when explicitly set document.domain to the same domain, and I guess it will be safe.

**Comment by daboxu** [comment]
Sorry for the confusion, I will update the documents. For the redirect mode, I believe you need a page like
a.company.com/picker.htm

In this page, define your callback function as global, exp "success-callback", and pass the function name as string to picker's option, and set openInNewWindow=false.

Basically your invoking way should look like

```````html
<html>
<js>
"callback-success" = function(obj) { postmessage(target, obj); }
</js>
<js>onedrive.v7.0.js</js>
<js>
OneDrive.open({
      openInNewWindow: false,
      success: "callback-success"
})
</js>
</html>
``````

**Comment by Inok** [comment]
I'll try it. Thanks for the help!

**Comment by sandeepDeveloper** [comment]
i tried with that "callback-success" even though i am not getting the file i am getting error message

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

**Comment by daboxu** [comment]
@devsandy it should be related to Microsoft Account login issue, please try again later.
