### ISSUE TITLE
Upload sessions with fail conflictBehavior return error after first fragment rather than upon creation

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#55]
If an upload session is created with @name.conflictBehavior set to "fail", the item path is specified at that time.  It should be possible to check for the conflict at that time.

However, instead the API returns a 409 Conflict after the first fragment is uploaded.

Is this intended behaviour?  Note that if the conflicted remote file is deleted between the session creation and first fragment, no error occurs.

Contrast this with the behaviour when the parent folder does not exist, where the error is returned on the creation of the upload session.

**Comment by ificator** [comment]
Thanks @Lyrrad, we should definitely fast fail if we can for scenarios like this. We'll see what we can do.
