### ISSUE TITLE
Not exist open/cancel buttons in OneDrive file picker in Internet explorer

### ISSUE THREAD

**Issue by OriAmir** [OneDrive/onedrive-api-docs#550]
Hi , I using one drive file picker and in Chrome / Firefox browsers everything work good but in IE and in Edge there is a problem.

In **internet explorer** after we redirect to page to choose files not exist the buttons of open/cancel so we couldn't choose anything actually:<br />
<img src='https://s15.postimg.org/qo5k0025n/one_Drive.png' border='0' alt='oneDrive'/><br />

In **edge** after insert user & password the redirect not redirect to any where , just blank page and nothing happens.

Someone maybe know what the problem or how could we change it?\
Thanks!

**Comment by daboxu** [comment]
hi @OriAmir , For IE, have you seen any error logs in IE console? For Edge issue, what's the url of the blank page? Please let me know if there is any error logs we can start with.

**Comment by OriAmir** [comment]
@daboxu I will check about edge error but in IE not have any errors in the log. It's just redirect to different page.... what could be the different ? it's just in my computer? or also to another?

thanks again!

**Comment by daboxu** [comment]
@OriAmir could you try in another PC? Also I found in the screenshot the UI in IE is different with UI in Chrome on the header and menu bar, would you mind sharing me the url in IE as well? I haven't seen the IE issue with my testing app in different machines.

**Comment by OriAmir** [comment]
@daboxu I know that header is diffrent and I don't know what the resason ..
In **chrome** the url is: https://difenlabs-my.sharepoint.com/personal/oamir_difenlabs_com/_layouts/15/onedrive.aspx?p=2

In **IE** the url is: https://difenlabs-my.sharepoint.com/personal/oamir_difenlabs_com/_layouts/15/onedrive.aspx

In **Edge** blank page . 

No errors in console in all the cases..

Tnx again.

**Comment by daboxu** [comment]
Thanks for the info, for sharepoint and IE, seems it is related to the security settings in your IE browser. If your ODB website url is in your trusted site, it could have problem. Try remove that from your trusted site. IE and Edge seems sharing the security settings while Chrome does not.

![image](https://cloud.githubusercontent.com/assets/3971919/24110997/4942996a-0d52-11e7-9b9a-110345c812d0.png)

**Comment by OriAmir** [comment]
@daboxu thank you very much for your help . In Edge it's now work but in **IE** same issue and same address.. there is something else I could do that it's also work in IE , because it's very important to me ( I need to open something form outlook desktop add-in that it's uses IE and not edge)
Tnx again!

**Comment by daboxu** [comment]
@OriAmir can you send me fiddler traces for the flow in IE? Not sure have you use fiddler before or not, it is a good tool for capturing your network traffic. You can capture the traffic for your actions in IE and it is helpful for me to investigate the redirect process in IE. My email is dabxu AT microsoft DOT com

**Comment by OriAmir** [comment]
@daboxu I send you mail with the details from fiddler ! Thank you!!

**Comment by OriAmir** [comment]
I must say big **thanks** for @daboxu for his help , he is really great !

All the problem cause because of IE security issue , to make it work in IE ( and also from Outlook Desktop ) we need to go to internet explorer settings and then under secuirty tab to  set v  on box of ‘Enable Protected Mode ‘ in: Internet , Local intranet , Trusted sited and Restricted sites:

<a href="https://imgbb.com/"><img src="https://image.ibb.co/mBZSJv/pickerIe.png" alt="pickerIe" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>how do you upload a picture</a><br />


Thanks again.
