### ISSUE TITLE
How to get createdDateTime and lastModifiedDateTime

### ISSUE THREAD

**Issue by app5000** [OneDrive/onedrive-api-docs#551]
Hello,

I am using the following codes to get the timestamps of a file through python sdk:
            created=client.item(drive='me',id='#####').get().createdDateTime
            modified=client.item(id='#######').get().lastModifiedDateTime

I keep getting the following error:
TypeError: 'Item' object has no attribute '__getitem__'

According to this page, the returned json object does have the two attributes I am looking for:
https://dev.onedrive.com/items/get.htm

Am I looking at the wrong reference?  Does making a call on item return the file metadata?  I am not sure which resource contain the file timestamp metadata.

Thanks in advance.

**Comment by ificator** [comment]
@app5000 this looks like a Python snippet, so I think you'll want to make sure you create a request:

```
item = client.item(drive='me',id='#####').request().get();
created = item.createdDateTime
modified = item.lastModifiedDateTime
```

**Comment by app5000** [comment]
Thanks for your response.  Yes I am using python.  I tried your code
item = client.item(drive='me',id='#####').request().get()
created = item.createdDateTime

but I still got the same error:
created = item.createdDateTime
AttributeError: 'Item' object has no attribute 'createdDateTime'

I got the file_id using onedrive file picker, can I use it here?
What does drive='me' mean?  Can I make this call anywhere regardless which folder this file is in?

I found another reference mentioning onedrivesdk.Item().  Where can I find more reading on how to use it and what it returns?  The upper case' Item' here seems to be the same as in the error message.

**Comment by rgregg** [comment]
The property names in the python SDK are a little different, they are mapped to standard python naming conventions. For createdDateTime, you would use `created_date_time` instead of `createdDateTime`.

drive='me' means the signed in user's drive. If you have a drive_id value from the file picker, you can use that instead. Since the file picker currently only supports opening files from the sign in user's drive, 'me' is OK to use as well.

[Per the documentation](https://github.com/onedrive/onedrive-sdk-python), onedrivesdk.Item() is the class that represents an item.

**Comment by app5000** [comment]
It seems my code is going through.  I also changed lastModifiedDateTime to last_modified_date_time and will proper test later. Thank you both.
I had read the documents for python sdk before but had a hard time finding a complete list of property names that I can call upon.  Ryan, can you give me the file name that I should look into?  Thanks.

**Comment by rgregg** [comment]
The model files for the various classes are all in [src/onedrivesdk/models](https://github.com/OneDrive/onedrive-sdk-python/tree/master/src/onedrivesdk/model). Item.py is the model used for files / folders.

**Comment by app5000** [comment]
I found it.  Thanks.

What is the difference between client.item vs onedrivesdk.Item()?  Is there any doc on when to use which?

**Comment by rgregg** [comment]
The `onedrivesdk.Item()` function creates a new instance of the python object that represents a file, without any state attached to it. You can use this when you want to create a folder, by setting properties of the resulting object, and then calling a create request.

The `client.item` is a short-cut function for retrieving an instance of the Item python class, populated with the metadata of an item on the server. client.item() has parameters for drive, item (id), and path, which you can use to specify the item you want to retrieve properties for.

**Comment by app5000** [comment]
Very clear.  Thanks.
