### ISSUE TITLE
Can't figure out how to get `view.delta` for `sharedWithMe` folders

### ISSUE THREAD

**Issue by sergiorykov** [OneDrive/onedrive-api-docs#553]
I've got /drive/view.sharedWithMe for personal account (https://api.onedrive.com/v1.0)
```
{
      "createdDateTime": "2016-08-24T12:46:35.047Z",
      "cTag": "adDo5RjREMkFGNjRGMzlFRUYhMjE2OC421111",
      "eTag": "aOUY0RDJBRjY0RjM511111",
      "id": "AF4D2AF64F39EEF!2168",
      "lastModifiedDateTime": "2016-08-24T16:52:44.063Z",
      "name": "text",
      "webUrl": "https://1drv.ms/u/s!111111",
      "remoteItem": {
        "createdBy": {
          "application": {
            "id": "111"
          },
          "user": {
            "displayName": "xxx",
            "id": "111"
          }
        },
        "fileSystemInfo": {
          "createdDateTime": "2016-08-24T12:45:00.99Z",
          "lastModifiedDateTime": "2016-08-24T12:45:00.99Z"
        },
        "folder": {
          "childCount": 3
        },
        "id": "A3BCD74FC9C8D485!125",
        "lastModifiedBy": {
          "user": {
            "displayName": "xxx",
            "id": "111"
          }
        },
        "lastModifiedDateTime": "2016-08-24T12:46:30.1Z",
        "name": "text",
        "parentReference": {
          "driveId": "111"
        },
        "shared": {
          "owner": {
            "user": {
              "displayName": "xxx",
              "id": "111"
            }
          }
        },
        "size": 273,
        "webUrl": "https://1drv.ms/u/s!11111"
      }
```

I want to get `delta` for that shared with me folder.
Recently we used `https://api.onedrive.com/v1.0/drive/items/**remoteItem.id**/view.delta`
But now it returns 404

in docs [here is section about it](https://dev.onedrive.com/misc/working-with-links.htm#using-delta-with-remote-items):
with `https://api.onedrive.com/v1.0/drive/items/**id**/view.delta` it returns empty list with @odata.deltaLink which means there is nothing to load. when trying to get `deltaLink` it returns the same response.

It seems I missed something. 

I want to sync `sharedWithMe` folders as well as the `drive` itself. 
Drive synchronization works with `https://api.onedrive.com/v1.0/drives/**rootFolderId**/root/view.delta`

**Comment by johnlilis** [comment]
Since this is a remote item, you should use the syntax for other drives, i.e.
GET /drives/{remoteDriveId}/items/{remoteItemId}/view.delta

**Comment by sergiorykov** [comment]
Thank you! 

Result items of `/drive/view.sharedWithMe` should be used as
`/drives/{remoteItem.parentReference.driveId}/items/{remoteItem.id}/view.delta`

eg `https://api.onedrive.com/v1.0/drives/f3bcd74fc9c8d485/items/f3bcd74fc9c8d485!125/view.delta`
