### ISSUE TITLE
image width/height does not return correct value from API

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#556]
Hi,

I am working on a javascript gallery which requires actual image's width and height in order to calculate a ratio. I am running into an issue where the width and height of some images are not returned correctly from an API call. And I found that the returned width and height are the other way around, for instance if I have an image with width=4 and height=7, when calling the api, it returned width=7 and height=4. This issue only occurred on some images, not every returned images from the api. And I was calling "**api.onedrive.com/v1.0/drive/items**" end point.
Example photo/item ID are: 90C80432FA7813FC!826, 90C80432FA7813FC!821, and 90C80432FA7813FC!817..and more. I tried to download of the images from the example id and re-uploaded to another folder to test the api again, and it returned the correct width and height after reuploaded.

Thanks,

**Comment by Tekki** [comment]
Is it possible that your images contain orientation metadata (for example from your camera)?

**Comment by neunygph** [comment]
Hi Tekki,

I'm not sure about that metadata, but when I tried to upload the same file and called the api again, it returned correct width and height. Also, I had some other images that were taken at the same time (only 1-2 minutes before/after) and they were returned with correct width and height.

Thanks,

**Comment by ificator** [comment]
Hi @neunygph, I took a quick look at the 3 items you mentioned above and they all seem to have 2048w x 1536h for both the metadata as well as the image data. What values are you seeing, and what are you expecting?

**Comment by neunygph** [comment]
Hi @ificator 

Thank you for looking into this for me, yes I have the 3 item mentioned above returned from the API with 2048w x 1536h. But their actual size is 1536w x 2048h. I wanted to compare their actual size vs the API's so I downloaded them directly from the official onedrive.com, and it shows they have 1536w x 2048h when looking at: right click > Property > Details.
And it looks to me that this only happen with images that have width < height, but not all of them. 

Thanks

**Comment by ificator** [comment]
As @Tekki suggested, it looks like the image has orientation metadata. So while the actual dimensions persisted in the photo are 2048w x 1536h, because the orientation is Rotate 270 CW the dimensions when viewed turn out to be 1536w x 2048h. 

The photos in question were uploaded in 2012 and so it's most likely that our metadata extraction process has improved over time and is now correctly applying the rotation when it didn't in the past. That would explain why uploading one of these photos again does what you expect.

**Comment by neunygph** [comment]
Hello @ificator 

With the situation that the mentioned photos are returned from the old extraction process. Is there a work around with the api so I can retrieve the correct width and height since we can't predict which photo a user is trying view and how long ago it was uploaded ?

Thanks,
