### ISSUE TITLE
Inconsistent API of /drive/view.sharedWithMe?select=remoteItem: remoteItem.file is missed

### ISSUE THREAD

**Issue by sergiorykov** [OneDrive/onedrive-api-docs#557]
When I execute GET `/drive/view.sharedWithMe` 
in `remoteItem` I have 
sections `folder` and `file` to distinguish folders and files respectively
```
"folder": {
   "childCount": 0
 },
```

```
"file": {
          "hashes": {
            "sha1Hash": "0214000000040000001800304C635CAB933E206C5C4EE5EB081FA745C0B1339AFCF543"
          },
          "mimeType": "image/jpeg"
 },
```

When I execute GET `/drive/view.sharedWithMe`**`?select=remoteItem`**
in `remoteItem` I have `folder` for folder, but **`file` section is missed** for files

**Comment by zachzi** [comment]
@sergiorykov This issue should be resolved now.

**Comment by sergiorykov** [comment]
thanks!
