### ISSUE TITLE
405 for view.delta on empty remote folder shared with me

### ISSUE THREAD

**Issue by sergiorykov** [OneDrive/onedrive-api-docs#558]
I have a list of shared with me items (files and folders) with `GET /drive/view.sharedWithMe`
for each item I want to get changes with 
`GET /drives/{remoteItem.parentReference.driveId}/items/{remoteItem.id}/view.delta`

when `remoteItem` is file or folder with `remoteItem.folder.childCount > 0` method returns valid response.
when I call it on empty shared folder - it returns 405 error code.
Empty list with `deltaLink` is what I suppose to receive back.

**Comment by Tekki** [comment]
Try `.../delta` instead of `../view.delta`.

**Comment by rgregg** [comment]
Hi @sergiorykov, this does sound like a bug. I'll see if I can reproduce the behavior and get engineering involved.

**Comment by chackman** [comment]
Sorry about this very old issue going stale.  If this is still reproducing, could you please provide updated request & response information to help us investigate further?  Thanks.
