### ISSUE TITLE
File versions API is not described in the docs

### ISSUE THREAD

**Issue by AndrewPashkin** [OneDrive/onedrive-api-docs#559]
The API for manipulating previous versions of a file for which [tests][1] are exist is not described in the docs.

[1]: https://github.com/OneDrive/onedrive-api-docs/blob/baf91023d448d551dce1748b2412dd2305058b88/tests/fileVersions.json

**Comment by dtheodor** [comment]
Does this mean onedrive API supports listing and downloading past versions of files?

**Comment by rgregg** [comment]
It means we don't _yet_ support this feature. But we might be working on it.

**Comment by rgregg** [comment]
I'm going to close this out as by design right now, since we don't offer this functionality in the API, but hopefully this will be coming soon.

**Comment by dtheodor** [comment]
Can you by any chance share the _unsupported_ api endpoint to download a specific file version, if such an endpoint exists?

**Comment by rgregg** [comment]
The tests were written for OneDrive personal, which has a /versions collection off the item objects. Support for ODB is still being worked on, but I hope to have a better story to share in a few weeks time.
