### ISSUE TITLE
Item resource doesn't include sharing information

### ISSUE THREAD

**Issue by saguiitay** [OneDrive/onedrive-api-docs#56]
Looking at the [item resource](https://github.com/OneDrive/onedrive-api-docs/blob/master/resources/item.md), there's not information about the sharing of the item.

For example, if a folder is shared (View Only) with email a@b.com, and (Edit) with email c@d.com, that information is not available in any facet.

**Comment by rgregg** [comment]
That's correct. Near the top of our backlog is adding more detailed permission and sharing features to the API.

**Comment by rgregg** [comment]
Closing this out because it isn't actionable right now. Please consider adding this request to our [UserVoice](http://onedrive.uservoice.com). Thanks!

**Comment by saguiitay** [comment]
I've opened a UserVoice suggestion here: http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7475017-allow-read-write-of-sharing-permissions-informatio
