### ISSUE TITLE
"Sending a Sharing Invitation" functionality released.

### ISSUE THREAD

**Issue by dbayonacode** [OneDrive/onedrive-api-docs#560]
Don't know If I can ask this question directly in here, but anyway in our company we are implementing a new platform to share documents using OneDrive API and we do need to use the "Sending a Sharing Invitation" feature on production environment as soon as possible. I am wondering if it is possible to know when will it be finally released for? Or I am wondering how will It be possible to get some notifications in advance when the current "Sending a Sharing Invitation" feature is going to change, so that way we can start using that feature on production and then action any changes before our users get affected for them. Appreciate your support.

**Comment by rgregg** [comment]
Hi @dbayonacode the ability to send an email invitation for shared items should be available for all users across OneDrive personal and OneDrive for Business. Are you still seeing issues with the mail not being sent?

**Comment by dbayonacode** [comment]
Hi @rgregg Thanks for your answer. No, It is working fine for us. We are just concerned about the information posted in the documentation which state that "Sending a Sharing Invitation (Preview)" is only a preview and it is not the final version. From the documentation (https://dev.onedrive.com/items/invite.htm): "Note: This functionality is a preview and should only be used for evaluating and testing. Some details of this API are expected to be changed before this functionality is finally released."  And we want to put that feature on production asap but we do not want to affect the users if the functionality changed. That is why we want to make sure we can release our system with that feature right now.

**Comment by rgregg** [comment]
Thanks for calling that out! That statement is erroneous and I'll have it removed. The invite API is now available for production use.

**Comment by dbayonacode** [comment]
Great. Thank you so much.
