### ISSUE TITLE
Delta presents deleted node with incomplete parentReference instead of deleted flag?

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#561]
Hi,

I got a deleted node from delta api with following format 

```
{u'parentReference': {u'driveId': u'f38c1bed489ee12f'}, u'webUrl': u'xxx', u'fileSystemInfo': {u'createdDateTime': u'2015-06-25T15:26:23.0766667Z', u'lastModifiedDateTime': u'2017-02-24T18:06:26.67Z'}, u'folder': {u'childCount': 73}, u'id': u'F38C1BED489EE12F!1108', u'size': 25398299108}
```

it doesn't have deleted facet and there is no id, name and path in its parentReference. I will get 404 error if try to get metadata.

```
GET /v1.0/drive/items/F38C1BED489EE12F!1108?select=id%2Cname%2Csize%2CfileSystemInfo%2CwebUrl%2Cpackage%2Cfile%2Cfolder%2CparentReference%2ClastModifiedDateTime%2CremoteItem HTTP/1.1" 404 65
404 {"error":{"code":"itemNotFound","message":"Item does not exist"}}
```

Why do I have a node with this kind of unexpected response?

**Comment by daboxu** [comment]
hi @verybada can you tell me more detail about how to reproduce it? any token attached with your view.delta request?

**Comment by verybada** [comment]
Hi @daboxu ,

I don't know how to reproduce it, I used view.delta without token and got this.

I found that bad node has different driveId than other nodes and my driveId either. 

This is the result of GET /drive, my id is **a9dc738acaf2c308**
```
 {u'status': {u'state': u'active'}, u'quota': {u'used': xxxx, u'deleted': xxxx, u'storagePlans': {u'upgradeAvailable': True}, u'state': u'normal', u'total': xxxx, u'remaining': xxxx}, u'@odata.context': u'https://api.onedrive.com/v1.0/$metadata#drives/$entity', u'owner': {u'user': {u'displayName': u'', u'id': u'a9dc738acaf2c308'}}, u'driveType': u'personal', u'id': u'a9dc738acaf2c308'}
```

and this node is **f38c1bed489ee12f**
```
{u'parentReference': {u'driveId': u'f38c1bed489ee12f'}, u'webUrl': xxx, u'fileSystemInfo': {u'createdDateTime': u'2015-06-25T15:26:23.0766667Z', u'lastModifiedDateTime': u'2017-02-24T18:06:26.67Z'}, u'folder': {u'childCount': 73}, u'id': u'F38C1BED489EE12F!1108', u'size': 25398299108}
```

**Comment by daboxu** [comment]
thanks for the info, it looks like it is a file that other shared with you because the id is different from your own id. Are you trying to query the delta under a folder of your own or on a folder shared with you?

**Comment by verybada** [comment]
No, I can't.

```
GET /v1.0/drive/items/F38C1BED489EE12F!1108?select=id%2Cname%2Csize%2CfileSystemInfo%2CwebUrl%2Cpackage%2Cfile%2Cfolder%2CparentReference%2ClastModifiedDateTime%2CremoteItem HTTP/1.1" 404 65
404 {"error":{"code":"itemNotFound","message":"Item does not exist"}}
```

**Comment by daboxu** [comment]
as you noted before you found the item's ID is `F38C1BED489EE12F!1108` which the part before the bang should be the owner's id: `F38C1BED489EE12F`, but your ID is `a9dc738acaf2c308` so that means you are querying an item you are not the owner. You can access to it if the owner has granted you permission or not. If you try to get the item by the path `/drive/items/itemid` which we maps it to /drives/**a9dc738acaf2c308**/items. Due to the item is not yours, the item should be fetched via /drives/**F38C1BED489EE12F**/items/F38C1BED489EE12F!1108.

It is not related to the file is deleted or not, it is related to the owner. Back to your original question, if you request delta without token, you should not see any `deleted` item, and in this case, it is an item shared with you. So what folder are you querying on? Are you querying on a folder under your drive?

**Comment by verybada** [comment]
Here is my scenario.
My app use delta.view to correct current snapshot in the beginning then I get a node which has incomplete parentRef and 404 if get items/{id}. Yes, like you said, delta.view should not return delete items without token, but in this case, it looks like delta.view gives a delete node because of 404. As a mention, I don't know where is the node, it is reported by a user. Is it possible that delta.view return an expired item?

**Comment by daboxu** [comment]
@verybada I am 99% sure view.delta will not return deleted token if you don't request it with `token=earliest` nor with a token having generated by server. I would suggest you ask the user for more information, is he/she the owner with id F38C1BED489EE12F? And is it a request under /drive/items/view.delta or it is /shares/<shareID>/root/view.delta. That could be very helpful for rule out some root causes. Thanks!

**Comment by daboxu** [comment]
close for now and feel free to reopen it if the problem still exists.
