### ISSUE TITLE
subscribing to get changes for NEWLY shared with me items?

### ISSUE THREAD

**Issue by johnlilis** [OneDrive/onedrive-api-docs#562]
I can subscribe to receive notifications for items that are already shared with me (I can list them with view.sharedWithMe and then add a subscription for each item).
Is there a way to get notified about an item that has just been shared with me so that I can subscribe to receive notifications for that as well? Or is polling the service for sharedWithMe items and making a manual diff the only option?

**Comment by rgregg** [comment]
This isn't something we have support for today, but it's a great idea. Please consider adding it to the [OneDrive User Voice page](https://onedrive.uservoice.com).
