### ISSUE TITLE
Folder Upload question.

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#563]
This is actually just a question, not an issue but I do not know where else to post. I hope it's ok to post a question.

1. Is there a way to have bulk upload to support folder upload with SDK/file saver/REST API ?
2. Since the javascript file saver does not support multiple upload, does that mean for folder upload, we have to create a new folder first, then upload single item multiple times or call "PUT /drive/items/{parent-id}:/{filename}:/content" multiple times to upload multiple items to the newly created folder ?

Thank you

**Comment by ificator** [comment]
Hi @neunygph, there is no current way to upload an entire folder in a single call - you'll have to do what you suggested in question 2. Essentially, create the folder and then create each item within that folder. If the item is another folder you'll recurse this logic, and if it's a file you'll upload it and move on.

**Comment by neunygph** [comment]
Hi @ificator , thanks for the quick response as well as the suggestion if item is another folder :)
