### ISSUE TITLE
Question about api endpoints

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#564]
1. Is there any difference in implementation, response and/or request parameters  between "api.onedrive.com" vs "graph.microsoft.com" ? 
2. Since Microsoft Graph is the preferred endpoint for accessing OneDrive personal, is it better to switch from api.onedrive.com to graph.microsoft.com.
3. Will api.onedrive.com still be supported in the future if there will be an upgraded version ?

Thanks,

**Comment by rgregg** [comment]
A lot of those questions are covered here: https://dev.onedrive.com/direct-endpoint-differences.htm

It is recommended that you use Microsoft Graph, although if you have a lot of existing code that calls api.onedrive.com, then you can continue to maintain that code. We support and maintain the OneDrive API and the Microsoft Graph API together.

It's likely that if we need to make breaking changes to the API in the future (say, adding a new v2.0 version) then we would only make those changes available via Microsoft Graph. However, v1.0 will continue to work until it is deprecated.
