### ISSUE TITLE
Unable to upload file with parenthesis included.

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#565]
I'm not sure if this is a known bug but I'm not able to upload a file with parenthesis included in the name when using the JavaScript file saver. For instance, I am can upload a file named "myfile.ico" but it threw an error for me when uploading "myfile(1).ico". I tried upload this "myfile(1).ico" with the official onedrive website and it worked just fine. Below is the error detail:
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Bearer access token is empty.",
    "innerError": {
      "request-id": "151d60cb-418d-4ced-832c-5540973e6dcc",
      "date": "2017-03-28T15:46:44"
    }
  }
}
Thank you,

**Comment by daboxu** [comment]
hi @neunygph are you using Picker SDK v7.0 or v6.0?

**Comment by neunygph** [comment]
Hi Dabo, I believe it's v7.

Thanks,

**Comment by daboxu** [comment]
@neunygph thanks, can you get the failed ajax request path in console? I can reproduce the issue with file has parenthesis while I got different error. The error I got is

**Comment by neunygph** [comment]
Hi @daboxu , the failed ajax request I got is similar, it showed 400 error:
`https://graph.microsoft.com/v1.0/drive/items/90C80432FA7813FC!3051/children/5(1).jpg/content?%40name.conflictBehavior=rename`

**Comment by Tekki** [comment]
I've the impression the queries in the last 2 comments are wrong. The URL of test(1).png in drive drive_id and folder folder_id is either
`https://graph.microsoft.com/v1.0/me/drive/items/{folder_id}:/test(1).png`
or
`https://graph.microsoft.com/v1.0/drives/{drive_id}/items/{folder-id}:/test(1).png`

**Comment by daboxu** [comment]
@neunygph what's the error message you saw in the 400 error?

**Comment by daboxu** [comment]
@Tekki I think it is right for uploading. The whole request is PUT https://graph.microsoft.com/v1.0/drive/items/<item-id>/children/test(1).png/content?%40name.conflictBehavior=rename

**Comment by neunygph** [comment]
@daboxu 
The error message from the 400 is the same one from the one I have above which is

`{
"error": {
"code": "InvalidAuthenticationToken",
"message": "Bearer access token is empty.",
"innerError": {
"request-id": "151d60cb-418d-4ced-832c-5540973e6dcc",
"date": "2017-03-28T15:46:44"
}
}
}`
Please let me know if you need any other additional information.
Thanks

**Comment by daboxu** [comment]
@neunygph can you send me the fiddler trace of the 400 error? Fiddler is a sweet tool you can capture your network traffice, and don't forget enable capture HTTPS traffic in its option. My email is dabxu AT microsoft DOT com. Thanks!

**Comment by neunygph** [comment]
@daboxu , sure I'll send you the network traffic once I get home later today.
Thanks,

**Comment by daboxu** [comment]
@neunygph the fix should be in prod now

**Comment by neunygph** [comment]
I tried it again and it worked great :)

Again, thank you very much for looking into this @daboxu  and @Tekki 
Phuong

**Comment by DMelc** [comment]
Hi,

I'm currently facing similar issue. It seems using a left parenthesis in filename lead to this error:

{
  "error": {
    "code": "BadRequest",
    "message": "Bad Request - Error in query syntax.",
    "innerError": {
      "request-id": "99b74d17-186b-4021-ae1d-8ce6faf3fa6c",
      "date": "2017-04-25T12:23:44"
    }
  }
}

The request I used is:

PUT https://graph.microsoft.com/v1.0/me/drive/items/92383E9ECE09F7EB!107/children/_(_.tif/content?microsoft.graph.conflictBehavior=fail HTTP/1.1

Thanks,

**Comment by daboxu** [comment]
@DMelc try wrap your file name with single quote like this:
```html
PUT https://graph.microsoft.com/v1.0/me/drive/items/92383E9ECE09F7EB!107/children('_(_.tif')/content?microsoft.graph.conflictBehavior=fail
```

it is a discrepancy between OneDriveAPI and GraphAPI, hopefully it will be resolved in the future. Sorry for the inconvenience.

**Comment by DMelc** [comment]
Hi,

Thanks for the tip. It works fine when uploading a file whose name contains left parenthesis. Unfortunately, it fails when filename contains a single quote, so I have to treat it as a special case.

Best regards,

Denis MELCKENBEECK
Software Engineer
________________________________

[cid:image004.png@01D2BE76.299A1D70]

I.R.I.S. Products & Technologies
Rue du Bosquet, 17
1348 Louvain-la-Neuve - Belgium
www.irislink.com<http://www.irislink.com>


        [cid:image005.png@01D2BE76.299A1D70]

**Comment by DMelc** [comment]
Additionally, having both an open brace and a single quote in the filename is a (unlikely) case that cannot be dealt with (I tried to URL encode the single quote character but it doesn’t work). Do you have an idea of the timeframe to have the issue fixed? How can I be warned?

Best regards,

Denis MELCKENBEECK
Software Engineer
________________________________

[cid:image001.png@01D2BE7B.64B7AEE0]

I.R.I.S. Products & Technologies
Rue du Bosquet, 17
1348 Louvain-la-Neuve - Belgium
www.irislink.com<http://www.irislink.com>


        [cid:image003.png@01D2BE7B.64B7AEE0]



From: Denis Melckenbeeck
Sent: 26 April 2017 10:16
To: 'OneDrive/onedrive-api-docs' <reply@reply.github.com>
Subject: RE: [OneDrive/onedrive-api-docs] Unable to upload file with parenthesis included. (#565)

Hi,

Thanks for the tip. It works fine when uploading a file whose name contains left parenthesis. Unfortunately, it fails when filename contains a single quote, so I have to treat it as a special case.

Best regards,

Denis MELCKENBEECK
Software Engineer
________________________________

[cid:image008.png@01D2BE7B.1C32ECC0]

I.R.I.S. Products & Technologies
Rue du Bosquet, 17
1348 Louvain-la-Neuve - Belgium
www.irislink.com<http://www.irislink.com>


        [cid:image007.png@01D2BE7B.64B7AEE0]

**Comment by daboxu** [comment]
@DMelc good question, try replace your URL contains single quote with two single quotes, we are relying on OData frame work and it is how it understands the url. Example:
```html
PUT https://graph.microsoft.com/v1.0/me/drive/items/92383E9ECE09F7EB!107/children('_(_''.tif')/content?microsoft.graph.conflictBehavior=fail
```

**Comment by DMelc** [comment]
Great ! Thanks

Denis MELCKENBEECK
Software Engineer
________________________________

[cid:image004.png@01D2BF4F.5B87E540]

I.R.I.S. Products & Technologies
Rue du Bosquet, 17
1348 Louvain-la-Neuve - Belgium
www.irislink.com<http://www.irislink.com>


        [cid:image005.png@01D2BF4F.5B87E540]
