### ISSUE TITLE
File path containt /bin/ will get an error.

### ISSUE THREAD

**Issue by PterX** [OneDrive/onedrive-api-docs#566]
![11](https://cloud.githubusercontent.com/assets/1871048/24440058/864e9e4c-1484-11e7-80f0-cb77e5156376.png)

look like this,it will get an 'Server Error',when i mod file path to '/bin_bak/wifi',it's ok.

**Comment by ificator** [comment]
Hi @PterX, do you happen to have any request/response traces for both the `Creating remote directory` call and the `Uploading` call? It'll be useful to see the URLs being hit for both of those, as well as the full response headers.

**Comment by Tekki** [comment]
This error is easy to reproduce:
- create folder 'Documents/bin' in web interface
- call `https://graph.microsoft.com/v1.0/me/drive/root:/Documents/bin`

Now I get exactly the same response as cited above. Code: 404, headers:
Content-Length: 1245
Server: Microsoft-IIS/8.5
Date: Wed, 29 Mar 2017 20:03:15 GMT
Content-Type: text/html
Connection: close

This is quite different from a call to an item that doesn't exist at all (`https://graph.microsoft.com/v1.0/me/drive/root:/Documents/xyz`), where the server responds with 404 and a JSON error.

**Comment by ificator** [comment]
Thanks @Tekki! I was hitting OneDrive Business directly and so wasn't seeing the failure. It definitely looks like it's some kind of Graph issue.

**Comment by ificator** [comment]
I believe this has been resolved on the Graph side! Please let us know if you're still seeing weird behavior.
