### ISSUE TITLE
OneDrive Delta API throwing 401 error: request url exceeds maxUrlLength value

### ISSUE THREAD

**Issue by nav-agarwal** [OneDrive/onedrive-api-docs#567]
I am using OneDrive's [delta API](https://dev.onedrive.com/items/view_delta.htm) to get change list. My first call succeeds. But when I try to fetch next batch results using '@odata.nextLink', I get following error message. 'The length of the URL for this request exceeds the configured maxUrlLength value.' with 401 HTTP status code.

My Request:
```
https://druvainternal-my.sharepoint.com/personal
/{email_id}/_api/v2.0/drives/{drive_id}/root/view.delta(token='1;%234;%231;3;78895df2-a9a4-4932-9983-6683629dc4a9;636263623679200000;96128348;%23Paged_CT=1;3;78895df2-a9a4-4932-9983-6683629dc4a9;636263587306070000;96123061')
```

Total length: 367 characters
Emailid: 37 character length
Drive_id: 67 character length
I have removed email_id and drive_id for security reasons.

As this URL is returned by API, I can't control its length. Because of this I am not able to fetch next batch of changes.

Would it be a good idea to make this API as POST so that token can be moved to body as done in Sharepoint APIs?

**Comment by ificator** [comment]
I was playing around with this today, and it looks like this may have been resolved - @nav-agarwal can you confirm if you're still seeing this issue?

**Comment by ificator** [comment]
The issue still persists, but the length at which it kicks in has been increased.

**Comment by ificator** [comment]
We've made a change that should hopefully bypass this issue, but you'll probably need to restart the sync sessions to get a newer token.
