### ISSUE TITLE
SharePoint Sites: Can't get site by path without access to the root site

### ISSUE THREAD

**Issue by Tekki** [OneDrive/onedrive-api-docs#568]
If I call a site by its path, for example

`https://graph.microsoft.com/beta/sharepoint:/sites/development`

this works, but queries like `...:/drives` or `...:/lists` return a 'Resource not found for the segment...' error.

**Comment by rgregg** [comment]
This is an issue with Microsoft Graph that we're working on. Right now you would need to separate this into two calls, one to get the Site ID using the path syntax, and then another API call to enumerate the lists or drives. Obviously this isn't ideal, and we're working on a fix.

**Comment by Tekki** [comment]
Thanks.
If you're working on it, another thing: I call `https://graph.microsoft.com/beta/sharepoint:/sites/development/Freigegebene%20Dokumente` and get ID, eTag, name..., but no parentReference and therefore no driveId.

**Comment by Tekki** [comment]
Seems in the meantime you have solved this in the v1.0 API. The above site can be accessed with
`https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/sites/development`
and its drives with
`https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/sites/development:/drives`
Is this correct?

**Comment by rgregg** [comment]
That's right. However, there is another issue that if the user doesn't have access to the root site for the tenant, they won't be able to path into another site that they do have access to. We're working on a fix for that.

**Comment by ificator** [comment]
This issue should now be resolved!
