### ISSUE TITLE
How do I update the sharing of a file/folder

### ISSUE THREAD

**Issue by saguiitay** [OneDrive/onedrive-api-docs#57]
As a follow-up to issue #56, is there a way to set the sharing details of an item?

For example, assign Edit "permissions" to email a@b.com ??

**Comment by rgregg** [comment]
Right now we only support creating sharing links for view or edit. We'll be adding support for more sharing scenarios, like assigning permissions to an e-mail address, in the near future.

**Comment by rgregg** [comment]
I'm closing this issue since it's not actionable right now. Please consider adding this on our [UserVoice page](http://onedrive.uservoice.com)
