### ISSUE TITLE
Delta request do not return all selected properties.

### ISSUE THREAD

**Issue by JamesDommisse** [OneDrive/onedrive-api-docs#570]
When selecting certain combinations of item properties in a delta query. Some of the properties are not returned.

In this python example the cTag is not returned for files:
```
import json
import requests_oauthlib
from pprint import pprint

ITEM_FIELDS = ['id', 'lastModifiedDateTime', 'name', 'shared', 'folder', 'size',
               'parentReference', 'cTag', 'deleted']

def delta_view():
    oauth_session = requests_oauthlib.OAuth2Session(
                CLIENT_ID,
                token=json.loads(JSON_TOKEN))
    res = oauth_session.get('https://api.onedrive.com/v1.0/drive/root:/:/view.delta', params={'select' : ','.join(ITEM_FIELDS)})
    for value in res.json()['value']:
        if 'cTag' not in value:
            pprint(value)
```
This prints out all the files. 

Thanks for your help, 

JD

**Comment by ificator** [comment]
@JamesDommisse it looks like there's some reliance on the `file` facet in this scenario when there shouldn't be. As a work around, if you also select `file` you'll get the `cTag` value back.

**Comment by julian-r** [comment]
With onedrive for business the problem happens as soon as you add `parentReference` to the select param. There it is not possible to get `cTag` and `parentReference` in the same call. This makes it really hard to use.

**Comment by ificator** [comment]
It looks like this issue should now be resolved - please let us know if you're still seeing it.
