### ISSUE TITLE
webhook: permission change events not supported?

### ISSUE THREAD

**Issue by vorio** [OneDrive/onedrive-api-docs#574]
When permission of collaborators on a file or folder is changed between Can View and Can Edit, webhooks are not triggered?  If true, this is a very big limitation.

Other operations like Upload file does trigger webhook though.

**Comment by rgregg** [comment]
This is true, permission changes do not currently trigger a webhook and do not cause an item to appear in the /delta API response. If this is important, please consider adding it to our UserVoice page: https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer

**Comment by vorio** [comment]
Behavior seems erratic. It does seem to trigger webhook for some period. Validated when only change is permission related. Please clarify the confusion. Are we talking about the same things here?

If it is truly not supported, are there other ways we get notified via RESTful way? Polling is fine as long as it is targeted. Like for a particular List. We don't want to poll thousands of Lists to find few or no changes. In other words, looking for decent workaround for now.
