### ISSUE TITLE
Unable to subscribe to the notifications(OneDrive For Business)

### ISSUE THREAD

**Issue by mauze-muawwaz-elastica** [OneDrive/onedrive-api-docs#575]
I'm using the APP only tokens (fetched used Client Credentials Flow) to subscribe to webhooks for my OneDrive for Business.

The request I make is as follows

## URL 

`https://graph.microsoft.com/v1.0/subscriptions`

## Body

```
{
 "notificationUrl": "<my notification url>",
 "expirationDateTime": "2017-04-04T11:23:00.000Z",
 "resource": "/users/abcdefgh-111a-4cb8-222f-a08860b9000c/drive/root/",
 "changeType": "updated",
 "clientState": "randomstringval121"
}
```

I get this response

```
{
  "error": {
    "code": "InvalidRequest",
    "message": "Cannot create app-only subscriptions for OneDrive resources.",
    "innerError": {
      "request-id": "59d362fb-54b3-4036-b540-3d55767a5ab0",
      "date": "2017-04-03T11:13:47"
    }
  }
}
```

Is there something wrong in my request or is it not supported?

**Comment by rgregg** [comment]
We don't currently support app-only scenarios with files in OneDrive or SharePoint. As a result, the support for webhooks is also disabled. If using app-only is important, please consider adding it on our user-voice page to help prioritize the work: https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer

**Comment by judebigj** [comment]
Any plans of adding the "app only" subscription?
