### ISSUE TITLE
item metadata returns a 'bundle' field - undocumented facet or bug?

### ISSUE THREAD

**Issue by johnlilis** [OneDrive/onedrive-api-docs#579]
I have come across an item that looks like a folder from the UI but when requesting metadata it does not have a folder facet, but instead returns a 'bundle' field containing 'childCount' information.

Is this some undocumented facet that acts similarly to a folder? If so, what is the difference from a folder?
Also, in case this is a feature and not a bug, is there a way to call view.delta on such an item? Because the typical way of requesting /drive/items/{itemId}/view.delta gives a 'Method Not Allowed' error.

**Comment by daspek** [comment]
You have indeed stumbled across an undocumented facet :)

A bundle is like a folder, except it doesn't have "ownership" of its contents like folders do. The OneDrive apps use these for Albums and for grouping items together in multi-select sharing.

The reason it's not yet documented is that, as you discovered, view.delta isn't supported. You have to do a full enumeration to see what changed (though you could optimize by looking at parent timestamps/ctags to cut down your recursion).

Curious, how did you come across one of these in the API? Did you plug in an ID that you found in the UI?

**Comment by johnlilis** [comment]
Thanks for the response! A few additional questions:

1) Not having "ownership" of the contents means the contents are also available in the drive through some other path? Sort of like a folder with links?
2) Getting the contents works like folders (i.e. with /drive/items/{item-id}/children)? 
3) Do normal items (i.e. files and folders) within a bundle support view.delta as usual?

I got the item through the /drive/view.sharedWithMe endpoint.

**Comment by daspek** [comment]
1. Yes, exactly.
2. More or less. Access by path (or by 'children') won't work consistently. Bundles can also contain items that live in multiple drives. The best thing to do for now is to get the DriveID and ItemId for the thing you want to access, and get to it through /drives/{drive-id}/items/{item-id}.
3. They do if you access them "directly" (ie not through the bundle).

Ah, yes, SharedWithMe. For some reason I thought we filtered bundles out, but that's clearly not the case :)

**Comment by johnlilis** [comment]
Ok, thanks for the information!

**Comment by johnlilis** [comment]
So just for testing purposes how can I create a new bundle, either from the UI or trough the API?

I tried creating a new folder but using the bundle facet instead of folder as shown below, but this returns a folder.
{
 "name": "MyBundle",
 "bundle" : {} //I also unsuccessfully tried "bundle" : { "childCount": 0 }
}

This seams to be in the right direction though, as without any facet I get an error message saying "Must provide one of the following facets to create an item: Bundle, File, Folder, RemoteItem". I'm probably missing some additional information that goes inside the bundle facet.

**Comment by ksmutny** [comment]
@johnlilis I got a little further: I POSTed a payload:

```
{
  "name": "Test Album",
  "bundle": {
    "album": {}
  }
}

```
and got a response

```
{
    "error": {
        "code": "accessDenied",
        "message": "Access Denied",
        "innerError": {
            "request-id": "9eb484d7-702b-422f-9db8-019a6df0f721",
            "date": "2018-08-29T20:44:40"
        }
    }
}
```

Don't have any clue what kind of permission is necessary to create albums. Any thoughts?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
