### ISSUE TITLE
item without a name - valid behavior or bug?

### ISSUE THREAD

**Issue by johnlilis** [OneDrive/onedrive-api-docs#580]
When syncing the contents of an account with view.delta I got an entry without a name field and with a parentReference pointing to a file (png image in particular). Is this a valid entry or a bug?

If relevant, the fields I get for the item are: createdBy, createdDateTime, eTag, id, lastModifiedBy, lastModifiedDateTime, size, webUrl and fileSystemInfo.
The size is 0, and when trying to access the webUrl I get a 'This item might not exist or is no longer available'. The image specified in parentReference seems ok and opens normally from the UI.

**Comment by ificator** [comment]
That definitely sounds strange @johnlilis. Can you provide us with the JSON response (feel free to obfuscate anything you'd rather not be public, but don't change the overall meaning of the response - e.g. don't delete properties or replace a value with an empty string)?

If this is a call against a business account it would also be useful if we could grab the `request-id` and `Date` headers from the response.

**Comment by johnlilis** [comment]
Since it's not my data, but a customer's, is it possible to somehow send the metadata privately?
Otherwise I'll have to fully obfuscate the response and I don't know if it will be helpful then.

**Comment by ificator** [comment]
Hi @johnlilis, feel free to email odwhr@microsoft.com and we can discuss options for getting the data we require.

**Comment by johnlilis** [comment]
Ok, thanks, I just sent an email with the metadata information.

**Comment by ificator** [comment]
We received your email @johnlilis, and it contained enough information for us to see what was going on. It looks like these mysterious items are actually comments sneaking through. That's not the experience we want, and so we'll look at making sure these do not come back while we figure out the long term story.

**Comment by johnlilis** [comment]
Ok, thanks for the quick response!

**Comment by ificator** [comment]
This issue should now be resolved - please let us know if you still see it.

**Comment by johnlilis** [comment]
It appears to be ok now. Thanks for the effort!
