### ISSUE TITLE
shared with me: metadata of file, child count of folder is always empty and size of file is always zero.

### ISSUE THREAD

**Issue by ramyareddy123** [OneDrive/onedrive-api-docs#582]
I was using postman rest api client to get the list of all the sharedWithMe files and folder using the one drive for business api. 
1. Get request was made.
2. Request url: {serviceEndpointUri}/drive/sharedWithMe.
3. Added "bearer <accesstoken>" in the header and made the request.
The shared files are getting listed but the meta data of each file and child count for folder(even for those that has sub files and folders) is always zero is always empty and the size of files is zero everytime. Other details like id, name of file etc are received correctly. What could be the possible issue?
4. CreatedDateTime for shared files is wrong. Its always "0001-01-01T00:00:00Z"
Also cTag and eTag are missing for all the shared files. Is that expected?

**Comment by ankit-ankuagrawal** [comment]
@katahir any update on this

**Comment by katahir** [comment]
Currently, we don't return the actual createdDateTime of the item. It is a known limitation, but something that should be fixed in the coming months. Same for etag/ctag.

**Comment by chackman** [comment]
Sorry about this very old issue going stale. If this is still reproducing, could you please provide updated request & response information to help us investigate further? Thanks.
