### ISSUE TITLE
OneDrive file picker doesn't work when 'redirectUri' set to different subdomain

### ISSUE THREAD

**Issue by devsandy** [OneDrive/onedrive-api-docs#583]
Facing issue with the redirect url with the v7 of file picker i am having different tenants in my project and i cant give those many tenants in the onedrive application so i want it to be in the javascript but it is not working with options that are there in the api docs "advance" which is used for redirect url

**Comment by daboxu** [comment]
currently #548 should be the best work around for different subdomain problem. FYI SharePoint has different security level in IE/Edge so postMessage is broken if you don't configure it right: #550

**Comment by devsandy** [comment]
i am trying in chrome and i am getting this message every time 

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

**Comment by daboxu** [comment]
can you provide the detail url of the page showing error?

**Comment by devsandy** [comment]
https://login.live.com/err.srf?lc=2057#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=redirect_type%3dauth%26display%3dpage%26request_ts%3d1491886261658%26response_method%3durl%26secure_cookie%3dfalse

**Comment by daboxu** [comment]
@devsandy based on the error, have you registered your app with the redirect uri you provided to picker SDK on https://apps.dev.microsoft.com? Make sure you added web in 'Platform' column, added the redirect uri and checked 'Allow Implicit Flow'.
![image](https://cloud.githubusercontent.com/assets/3971919/24918598/c35c0b42-1e95-11e7-88f4-e188752d7565.png)

**Comment by devsandy** [comment]
i have added redirect url just main domain like https://dev.example.com but i have sub domains like https://dev1.example.com when i am using picker in dev it is working fine when i changed the url it is not working and i am having different domains like this i cant add those domains into the app, it have to work for sub domains the problem is with sub domains.

**Comment by daboxu** [comment]
Sorry misunderstood your story, can you move the picker page hosting on https://dev.example.com and set option.openInNewWindow=false? The basic idea is on the subdomain page https://dev1.example.com button onclick, you can set window.open("https://dev.example.com/pickerhostpage"), and you can use postMessage between the page  https://dev.example.com/pickerhostpage and https://dev1.example.com.

**Comment by daboxu** [comment]
close for now as the thread is not active for a long time, feel free to reopen it if you have any questions.

**Comment by munhochong** [comment]
I trying to do what you suggested in above. But i facing the popup issue. Although i set openInNewWindow to false, when i load the page, it will pop up oneDrive file picker. 

Below is my script - onedrivesdk.html, 

`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
    <script type="text/javascript">
        function launchOneDrivePicker() {
            var odOptions = {
                clientId: "93axxxxxxxxx",
                action: "share",
                multiSelect: true,
                openInNewWindow: false,
                advanced: {
                    redirectUri: "http://domain.com/onedrivesdk99.html"
                },
                success: function (files) {
                    for (var i = 0; i < files.value.length; i++) {
                        console.log(files.value[i]);
                    }
                },
                cancel: function () { /* cancel handler */ },
                error: function (e) { /* error handler */ }
            }
            OneDrive.open(odOptions);
        }

        $(document).ready(function () {
            launchOneDrivePicker();
        });
    </script>
</head>
<body>
</body>
</html>`
