### ISSUE TITLE
When One Drive App is installed on IOS the picker does not work.

### ISSUE THREAD

**Issue by mainseq** [OneDrive/onedrive-api-docs#584]
When using the JavaScript picker on IOS safari (iPhone, iPad) it suddenly jumps out to the installed app and stops functioning. Is there a preference or any way to prevent this from happening? It is a real deal breaker. If you delete the app it works fine.

**Comment by daboxu** [comment]
hi @mainseq , are you using the JavaScript Picker SDK? https://dev.onedrive.com/sdk/js-v7/js-picker-overview.htm

**Comment by mainseq** [comment]
Yes. It works everywhere but on IOS with the OneDrive app installed.

for reference here is the .js we are using:
<script type="text/javascript" src="https://js.live.net/v7.0/OneDrive.js">

**Comment by mainseq** [comment]
Bueller?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
