### ISSUE TITLE
404 on enumerating contents of a shared folder using One drive for business API 

### ISSUE THREAD

**Issue by ramyareddy123** [OneDrive/onedrive-api-docs#586]
I was using one drive for business API and was trying to retrieve and access the shared with me files and folders.
1.  I am not able to enumerate the contents of shared folder. It always returns `404 Not Found error.` 
     part of the response from the `GET <serviceEndpointUri>/drive/sharedWithMe`

     `"remoteItem": {

        "createdBy": {
          "user": {
            "displayName": "abc"
          }
        },
        "createdDateTime": "0001-01-01T00:00:00Z",
        "fileSystemInfo": {
          "createdDateTime": "0001-01-01T00:00:00Z",
          "lastModifiedDateTime": "2016-09-02T11:57:00Z"
        },
        "folder": {
          "childCount": 0
        },
        "id": "03573WEOCZ4LCMXDTQ6ZAJMHHM62HZ7OK6",
        "lastModifiedBy": {
          "user": {
            "displayName": "abc"
          }
        },
        "lastModifiedDateTime": "2016-09-02T11:57:00Z",
        "name": "bm",
        "parentReference": {
          "driveId": "b!ZoYKIsneuEOLnrc5r-V_pacv7nIc2-tMiOMGPnRSb3y_JXvXPJYsTacVGx6k6DFd"
        }
      }`

     Request Made : `GET <serviceEndPointUri>/drives/b!ZoYKIsneuEOLnrc5r-V_pacv7nIc2-tMiOMGPnRSb3y_JXvXPJYsTacVGx6k6DFd/items/03573WEOCZ4LCMXDTQ6ZAJMHHM62HZ7OK6/children`. Request always returns 404 Not found error.
Response :
 `{
  "error": {
    "code": "itemNotFound",
    "message": "The resource could not be found."
  }
}`
 Tried with different shared folders in the response same error with every folder.

2. I have shared two files, one with only read permission and the other with read and write permission. When I made a call using `GET <serviceEndpointUri>/drive/sharedWithMe`, there is no difference in the response for both the files. How do we retrieve the permissions associated with a shared file?
I tried `GET /drives/<drive-id>/items/{item-id}/permissions` but even this return 404 resource not found error. Same is the case with the copy and also download operation. What could be the possible issue? Is it a different web service call that has to be made for these operations?

**Comment by ankit-ankuagrawal** [comment]
+1

**Comment by ankit-ankuagrawal** [comment]
@katahir any update on this

**Comment by abhishekxi** [comment]
Facing same issue. I am trying to GET "/content" instead of "/children". Any idea or workarounds? Files however, are visible online. Any help/workaround is much appreciated.

Thank you.

**Comment by Tekki** [comment]
You can't use the same `<serviceEndPointUri>` for calls to your own and to a remote drive.

**Comment by katahir** [comment]
I think it may have something to do with the scopes you have in the access token. Can you please paste the scopes part here. I tried this on my test tenant and I cant repro the issue. The scopes needed to access files in drives not owned by the user are files.readwrite.all/files.read.all. Can you request these scopes and then try again?

**Comment by ramyareddy123** [comment]
@katahir right now, we ask the customers only for two permissions

**Comment by ramyareddy123** [comment]
@katahir right now, we ask the customers only for two permissions. 1. Read user profiles 2. Read and write user files. Is requesting for files.readwrite.all/files.read.all scopes, the only way to download, access shared with me files?

**Comment by ramyareddy123** [comment]
@katahir we have tried adding the files.readwrite.all and files.read.all scopes but still the same issue persists. part of the response after login is as follows:                                                                                  
 ```
`{
  "token_type": "Bearer",
  "scope": "Directory.AccessAsUser.All Directory.Read.All Directory.ReadWrite.All **Files.Read.All Files.ReadWrite.All** Group.Read.All Group.ReadWrite.All MyFiles.Write User.Read User.Read.All User.ReadBasic.All",
  "expires_in": "3599",
  "ext_expires_in": "0",
  "expires_on": "1493217576",
  "not_before": "1493213676",
  "resource": "https://api.office.com/discovery/",
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzUU4wQlpTN3M0bk4tQmRyamJGMFlfTGRNTSIsImtpZCI6ImEzUU4wQlpTN3M0bk4tQmRyamJGMFlfTGRNTSJ9.eyJhdWQiOiJodHRwczovL2FwaS5vZmZpY2UuY29tL2Rpc2NvdmVyeS8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zMmQ4NWY2NS02YTYyLTQzMmEtOWFiMy05NDFhM2I5Zjg1YmQvIiwiaWF0IjoxNDkzMjEzNjc2LCJuYmYiOjE0OTMyMTM2NzYsImV4cCI6MTQ5MzIxNzU3NiwiYWNyIjoiMSIsImFpbyI6IlkyWmdZTGhpM2ZZcWUrbTErVXhYNnB2dXQvV2ZZOG9wN09PK3ZPYzNyNmJkNGNCTjcwMEIiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiNjBiODk5YTYtZmJlNC00MjI5LTg2ZTctMzMxZGM3ZGVlODA4IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJNRE0wNSIsImdpdmVuX25hbWUiOiJmaWJlcmxpbmtxYSIsImlwYWRkciI6IjExMS45My4yNDUuMzciLCJuYW1lIjoi55Sz6KuL54Sh44GX44Ki44OX44Oq44Kx44O844K344On44Oz5LiA6KanIiwib2lkIjoiZTNkY2YyMzUtNjVmNy00MmZkLWJjNWYtYjM3ZjhhNTU0ZGJjIiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMzRkZGODY5M0RDODkiLCJzY3AiOiJEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZC5BbGwgRmlsZXMuUmVhZFdyaXRlLkFsbCBHcm91cC5SZWFkLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIE15RmlsZXMuV3JpdGUgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIiwic3ViIjoiNzV1b3ak1zSkE0VndpUEZhT2RxcmhqNCIsInRpZCI6IjMyZDg1ZjY1LTZhNjItNDMyYS05YWIzLTk0MWEzYjlmODViZCIsInVuaXF1ZV9uYW1lIjoiZmliZXJsaW5rcWFAbWRtMDUub25taWNyb3NvZnQuY29tIiwidXBuIjoiZmliZXJsaW5rcWFAbWRtMDUub25taWNyb3NvZnQuY29tIiwidmVyIjoiMS4wIn0.H2fPIJcFgnR4kM1jeQuFsndbjx-Ns5xQcoZNA-HHDyEZ7USBsEW6lb8bCY                                                   
}`
```
you can see that the scope value has the files.readwrite.all/files.read.all  in it.

**Comment by katahir** [comment]
Can you please share the response headers of a 404 request with me? Since I cant repro, I will need the logs to see what is going on.

**Comment by ramyareddy123** [comment]
@katahir Here is the response headers for a 404 api request made to download a shared file.
````
Cache-Control →private, max-age=0
Content-Type →application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Date →Tue, 02 May 2017 05:20:12 GMT
Expires →Mon, 17 Apr 2017 05:20:12 GMT
Last-Modified →Tue, 02 May 2017 05:20:12 GMT
MicrosoftSharePointTeamServices →16.0.0.6420
ODATA-VERSION →4.0
P3P →CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
SPClientServiceRequestDuration →23
SPRequestDuration →421
SPRequestGuid →6e9ced9d-9017-3000-165b-850aa9f80e92
Server →Microsoft-IIS/8.5
Strict-Transport-Security →max-age=31536000
Transfer-Encoding →chunked
X-AspNet-Version →4.0.30319
X-Content-Type-Options →nosniff
X-FRAME-OPTIONS →SAMEORIGIN
X-MS-InvokeApp →1; RequireReadOnly
X-MSEdge-Ref →Ref A: 826547FB92D445EFA734FED43DCE2C57 Ref B: BOM01EDGE0221 Ref C: Mon May 1 22:20:13 2017 PST
X-Powered-By →ASP.NET
X-SP-SERVERSTATE →ReadOnly=0
X-SharePointHealthScore →0
request-id →6e9ced9d-9017-3000-165b-850aa9f80e92`
```

**Comment by ankit-ankuagrawal** [comment]
@katahir any update on this.

**Comment by ankit-ankuagrawal** [comment]
@rgregg @katahir any update for this, we have the customer pushing for this. And we are not able to proceed.

**Comment by ankit-ankuagrawal** [comment]
@katahir @rgregg it is really disappointment to see no update here at all.

**Comment by sanjaynetision** [comment]
Facing exactly same issue. Any idea or workarounds? Any help is much appreciated.

Thank you.

**Comment by rgregg** [comment]
Hi sanjaynetision, can you include the request, and the full response (headers + body) for the error you are seeing?

**Comment by sanjaynetision** [comment]
@rgregg thanks for quick response.Here is my code.

GET <serviceEndpointUri>/_api/v2.0/me/drive/sharedwithme

when I run above code I got the result below : 

{
"@odata.type": "#oneDrive.item",
"@odata.id": "<serviceEndpointUri>/_api/v2.0/drive/items/01YH4M3NJX244RV73L5BDLAYVW2H6FJNWE",
"@odata.editLink": "drive/items/01YH4M3NJX244RV73L5BDLAYVW2H6FJNWE",
"createdBy": {
"user": {
"email": "**",
"displayName": "**"
}
},
"createdDateTime": "0001-01-01T00:00:00Z",
"id": "01YH4M3NJX244RV73L5BDLAYVW2H6FJNWE",
"lastModifiedBy": {
"user": {
"email": "**",
"displayName": "**"
}
},
"lastModifiedDateTime": "2017-11-09T10:12:00Z",
"name": "CSLTest",
"parentReference": {
"driveId": "b!JDUyUEXv30Ox3fJCk9h9k7YuJTRxBXpOlg7swVPzQSlbBMNLaGQrQYjZGhpaFPT0",
"driveType": "business"
},

"fileSystemInfo": {
"createdDateTime": "0001-01-01T00:00:00Z",
"lastModifiedDateTime": "2017-11-09T10:12:00Z"
},
"folder": {
"childCount": 0
},
"remoteItem": {
"createdBy": {
"user": {
"email": "PJain@daymon.com",
"displayName": "Pallav Jain"
}
},
"createdDateTime": "0001-01-01T00:00:00Z",
"fileSystemInfo": {
"createdDateTime": "0001-01-01T00:00:00Z",
"lastModifiedDateTime": "2017-11-09T10:12:00Z"
},
"folder": {
"childCount": 0
},
"id": "01YH4M3NJX244RV73L5BDLAYVW2H6FJNWE",
"lastModifiedBy": {
"user": {
"email": "******",
"displayName": "****"
}
},
"lastModifiedDateTime": "2017-11-09T10:12:00Z",
"name": "CSLTest",
"parentReference": {
"driveId": "b!sBnp-sc0oE28Ol8s8f7gCgLVjw2KNfdEkFYC3I1gjb7h58QNe-f9RoXQ8Nc3YpPM"
},
"shared": {
"scope": "users",
"sharedBy": {
"user": {
"email": "**",
"displayName": "**"
}
},
"sharedDateTime": "2017-11-09T10:14:00Z"
},

},




GET  <serviceEndpointUri>/_api/v2.0/drives/b!sBnp-sc0oE28Ol8s8f7gCgLVjw2KNfdEkFYC3I1gjb7h58QNe-f9RoXQ8Nc3YpPM/items/01YH4M3NJX244RV73L5BDLAYVW2H6FJNWE
authorization : Bearer <accesstoken>

when I run above code I got the result below : 

Response Header :

cache-control:
private, max-age=0
transfer-encoding:
chunked
content-type:
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
expires:
Mon, 30 Oct 2017 08:43:05 GMT
last-modified:
Tue, 14 Nov 2017 09:43:05 GMT
server:
Microsoft-IIS/8.5
x-sharepointhealthscore:
0
x-sp-serverstate:
ReadOnly=0
odata-version:
4.0
spclientservicerequestduration:
107
sprequestduration:
234
x-aspnet-version:
4.0.30319
sprequestguid:
5fc12c9e-50ef-4000-f1c5-e777b4a38ce0
request-id:
5fc12c9e-50ef-4000-f1c5-e777b4a38ce0
ms-cv:
nizBX+9QAEDxxed3tKOM4A.0
strict-transport-security:
max-age=31536000
x-frame-options:
SAMEORIGIN
x-powered-by:
ASP.NET
microsoftsharepointteamservices:
16.0.0.7101
x-content-type-options:
nosniff
x-ms-invokeapp:
1; RequireReadOnly
p3p:
CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
date:
Tue, 14 Nov 2017 09:43:05 GMT

{
"error": {
"code": "itemNotFound",
"message": "The resource could not be found."
}

Please Help !

**Comment by rgregg** [comment]
Thanks for the details. I’m going to pull up the logs and see what’s happening server side. Just to confirm though, which permissions / scopes has your app requested? Can you use https://jwt.ms to decode your access token and copy out the scopes in the token for me too?

**Comment by sanjaynetision** [comment]
@rgregg , Thanks for the reply.
I have decoded the token and following are the scopes .Do I need to mention any other scopes
to access shared files?

"scp": "email Files.ReadWrite Mail.Send offline_access openid profile User.Read",


  "app_displayname": "DaymonOneDrive",
  "appid": "37c2f667-a3d5-4d66-8a93-effcc80f04bb",
  "appidacr": "1",
  "oid": "c9472432-d36b-4dd0-a97a-1c5a1474aa57",
  "puid": "10033FFFA0E8BB71",
  "scp": "email Files.ReadWrite Mail.Send offline_access openid profile User.Read",
  "signin_state": [
    "kmsi"
  ],

**Comment by sanjaynetision** [comment]
@rgregg Any update on this.Please help.

**Comment by rgregg** [comment]
@sanjaynetision It looks like you're missing the Files.ReadWrite.All permission scope, which is required to get access to shared files.

**Comment by chackman** [comment]
Sorry about this very old issue going stale.  If this is still reproducing, could you please provide updated request & response information to help us investigate further?  Thanks.
