### ISSUE TITLE
Documentation missing 509 Error response

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#59]
Here, various errors are listed http://onedrive.github.io/misc/errors.htm

I was able to get a 509 error code (bandwidth limited exceeded) when downloading files, which isn't listed in the table  The header returns an "x-clienterrorcode" of "UsageRestricted".   There is also no "Retry-After" header or JSON object returned.

**Comment by rgregg** [comment]
This is fixed.
