### ISSUE TITLE
[ODB] how to get reliable tenant resource url

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#592]
Hello,
in Oauth, we can use code to get access_token in different tenant resource (like synologydst-my.sharepoint.com ..etc)

However the account emails are not in the same format
**joewu@synologydst.onmicrosoft.com**

I have seem some other email format which is not in 
**xxxx@xxxx.onmicrosoft.com**
Maybe they are on demand.

And here is the question,
- Is the account email domain 
(like above **synologydst** in joewu@synologydst.onmicrosoft.com) 
differ from  synologydst-my.sharepoint.com where the resource I desired
Or they would follow some naming rule?

- After Oauth, I can get id_token, should I use that as user identification?
I want to use tid and unique_name to retrieve the onedrive business tenant resource

thanks for help!

**Comment by rgregg** [comment]
@joewutaiwan: there isn't a reliable way to compose a tenant URL yourself. While most tenants follow a particular template, there are special conditions that can cause the URLs to be different than expected. IT administrators may also have the option to change the template used.

To retrieve the OneDrive for Business URL, the only reliable method is to request this information from Microsoft Graph:

`GET https://graph.microsoft.com/v1.0/me?$select=mysite`

This returns the URL for the user's MySite, if it exists. If it has not yet been provisioned, this will return no value.
