### ISSUE TITLE
Does content change affect item's ID?

### ISSUE THREAD

**Issue by AndrewPashkin** [OneDrive/onedrive-api-docs#594]
[The docs][1] say:
> Items are assigned a unique identifier when they are created and **the ID persists across the actions a user performs on the item**. Renaming or moving the item will not change the item's ID.

What about content change in a file? Would it change the ID?

[1]: https://github.com/OneDrive/onedrive-api-docs/blob/196e8bbc4eaa032ee13e2721a2675c4058279149/misc/addressing.md#id-based-addressing

**Comment by ificator** [comment]
The ID should *not* change with a file content change (or any other action that can be taken on a file for that matter).

**Comment by AndrewPashkin** [comment]
What about the case when a user creates the file, deletes it and then creates again with the same name?

**Comment by ificator** [comment]
That would be considered a new item and so would have a new id.

**Comment by AndrewPashkin** [comment]
@ificator, okay, thank you very much!
