### ISSUE TITLE
OD API Auth Change?

### ISSUE THREAD

**Issue by BenMcGarry** [OneDrive/onedrive-api-docs#595]
On the browser extension "Reddit Enhancement Suite" we had the option that allows users to embed onedrive content and show it inline. Over the past few weeks it appears our API requests are starting to fail with "Must be authenticated to use '/drive'".

Has there been a recent change that means all API requests must to be authenticated via oauth? These requests have worked in the past.

Ref https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/4180

**Comment by rgregg** [comment]
Hey @BenMcGarry:

Instead of decomposing the URL, I'd recommend you use the [Shares API](https://dev.onedrive.com/shares/shares.htm) to access shared items. This way you'll be resilient to URL changes and shouldn't encounter these authentication errors.

**Comment by BenMcGarry** [comment]
Many thanks @rgregg, that appears to have done the trick :)
