### ISSUE TITLE
[ODFB] Constantly getting these errors when trying to upload a file with status code 400

### ISSUE THREAD

**Issue by rsuram** [OneDrive/onedrive-api-docs#596]
When i am trying trying upload file to deeper folders(inner folders) of depth level 7.
Unable to create chunk upload session also.

API calls used in OneDrive For Business:
/drive/items/{parent-id}:/{filename}:/content
/drive/items/{parent-id}:/{filename}:/upload.createSession

Error  : 
Status code : 400
Message :  {"error":{"code":"invalidRequest","message":"One of the provided arguments is not acceptable."}}

**Comment by rgregg** [comment]
@rsuram Can you provide the value of the `Request-ID` header in the response when this error occurs so we can look up the server logs? It's possible that there is a maximum path length issue that you're encountering.

**Comment by rsuram** [comment]
@rgregg I have the long folder names minimum length is 10 - 15 characters.
Trying to upload file having 104 characters in file name.

Is there is any way to find out acceptable length of file name in deeper folder ?

**Comment by ificator** [comment]
We've done a lot of work recently to reduce the size of upload session URLs, so hopefully this has resolved your issue. Please let us know if you continue to see unexpected 400s / 404s when uploading content.
