### ISSUE TITLE
OneDrive WL.fileDialog does not work anymore

### ISSUE THREAD

**Issue by audiorecorder** [OneDrive/onedrive-api-docs#599]
OneDrive WL.fileDialog (javascript API for web apps) does not work anymore. This file/folder seletor feature has worked for two years. But now it does not work.
"The folders couldn't be shared. Please try again later." error occur. How to fix it?

More Detail, Screencapture (stackoverflow)
<a href="http://stackoverflow.com/questions/43715793/onedrive-wl-filedialog-does-not-work-anymore" target="_blank">http://stackoverflow.com/questions/43715793/onedrive-wl-filedialog-does-not-work-anymore</a>

    WL.fileDialog({
        mode: "save"
    }).then(
        function(resp){
            if(!resp || !resp.data || !resp.data.folders || resp.data.folders.length==0)return;
            var id=resp.data.folders[0].id;
            var arr=id.split('.');
            if(arr.length==3){
                id=arr[arr.length-1];
            }else{
                id='';
            }
            proc_setfolder(id, resp.data.folders[0].name);
        },
        function(resp){
            //alert(resp.error_description);
        }
    );

**Comment by Balaji29** [comment]
We are also facing the same issue with WL.fileDialog. How do we move forward with this?

**Comment by spyronis** [comment]
Same problem for me also. Any update on that?

**Comment by daboxu** [comment]
sorry guys, our engineer is working on fix it. I will give you update once the fix is deployed, we are strongly recommend you move to [new version picker SDK](https://dev.onedrive.com/sdk/js-v7/js-picker-overview.htm).

**Comment by audiorecorder** [comment]
"File picker for JavaScript v7.0" supports only HTTPS site. It is problem.

**Comment by ThomasMichon** [comment]
We just rolled out an update which should resolve this issue.
