### ISSUE TITLE
Clarify scope for creating share link

### ISSUE THREAD

**Issue by dkhamsing** [OneDrive/onedrive-api-docs#6]
Seems like the scope required to create share links is `onedrive.readwrite`, would be nice to add a note about that

http://onedrive.github.io/items/sharing_createLink.htm
https://github.com/OneDrive/onedrive-api-docs/blob/master/items/sharing_createLink.md

**Comment by rgregg** [comment]
Thanks @dkhamsing for the suggestion! I'll update the docs to indicate that you need read/write permissions to create sharing links.

**Comment by rgregg** [comment]
I've updated the docs. Thanks again for the suggestion.

**Comment by dkhamsing** [comment]
You're welcome
