### ISSUE TITLE
resumable upload return bad request

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#60]
I try to use resumable upload and got bad request but I have not idea what is wrong with my requests

command upload file named '20M' to 'M870/Sheet Music/I.Orchestra Works(Symphonies, Concertos, Overtures...)/Peter Ilyitch Tchaikovsky(1840-1893)/II. Overtures and Symphonic Fantasies/The Tempest, Symphonic Fantasia after Shakespeare/b'

the response is:
HTTP Error 400. The request URL is invalid.

but if I use simple upload api to upload to the same path, the result is OK.

if I shorten the destination to  'M870/Sheet Music/I.Orchestra Works(Symphonies, Concertos, Overtures...)/Peter Ilyitch Tchaikovsky(1840-1893)/II. Overtures and Symphonic Fantasies/The Tempest, Symphonic Fantasia after/b', it works fine.

I have no idea about this situation and I  think I do not exceed the max folder path length.
or there's any reserved word I met?

**Comment by mikechiu1012** [comment]
I try some composition of the url, once the total url in upload.createSession reach length 300, the upload will failed.

Is there any length limitation existed?

**Comment by mikechiu1012** [comment]
furthermore, the bad request error does not return error json object but only html body like:
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>

is this a normal response or it should return error json format, too?

**Comment by ificator** [comment]
Thanks @mikechiu1012, I see what's going on. We'll get that fixed ASAP!

**Comment by saguiitay** [comment]
I'm facing a similar issue, and this is becoming critical to me...

Files are failing to upload when the path of the parent folder is very long, for example _"/gskk/unterricht/pik ass/pik ass/pikas.dzlm.de/upload/material/haus_4_-_sprachfoerderung_im_mathematikunterric/um/rechenwege/schueler-material/Arbeitsblaetter_4_Rechenwege/H4_UM_SPF_RW_Schueler_1a_Rechenweg_1_legen_und_beschreib-2"_

**Comment by saguiitay** [comment]
Any update regarding this? it's been 3 weeks already, without any comment...

**Comment by ificator** [comment]
We've pushed a change that we think will resolve most occurrences of this issue. Hopefully that will help things out while we work on a better solution.
