### ISSUE TITLE
4Gb download limit

### ISSUE THREAD

**Issue by silto** [OneDrive/onedrive-api-docs#600]
Our service uses your API and some of our users are complaining because they can't download some of their biggest files. After investigation, we realized that an undisclosed 4Gb limit exists on downloads. I don't know if the same limit exists on upload, maybe it was added later, but the fact is that users have their files "trapped" in OneDrive.
Investigations lead me to this thread :
https://answers.microsoft.com/en-us/onedrive/forum/odwork-odshare/any-way-around-4gb-download-limit/46e80faa-bb1b-400b-9140-49f7994a666b
It is suggested that people trying to download a folder at once should split it. This tip can not be applied to my issue since there is no way to split a unique file before downloading it.

We tried splitting requests in < 4Gb requests using the "Range" header, but the requests still fail with a 429 code. This is the rate limit code but since it only happens with files over 4Gb and our requests stay the same we deduced the issue was the size and not the way we do the requests.
We use the @content.downloadUrl url to download, but I don't think there is another one since  ```/drive/items/{item-id}/content```redirects to it too.

Do you have any indication on how to proceed in this case?
Thank you for your time

**Comment by ificator** [comment]
Hi @silto, can you confirm whether you're seeing this behavior on OneDrive Consumer or OneDrive Business?

**Comment by silto** [comment]
It looks like the user who noticed this problem had a premium consumer account (1To).

**Comment by silto** [comment]
Our test account is a consumer basic account but I'm still in the process of uploading a >4Gb file to reproduce

**Comment by ificator** [comment]
OneDrive Consumer has a 10GiB file size limit, so you should definitely be able to download >4GiB. Do you have any logs that would indicate what error the clients encounter at this boundary?

Also, when you hit the 429 how many requests have you made? What range sizes are you requesting?

**Comment by ificator** [comment]
I just uploaded a 5GiB file, and downloaded it successfully with the following code:

```
    using (var fileStream = new FileStream(@"c:\temp\downloadedlarge.dat", FileMode.Create, FileAccess.Write))
    {
        HttpWebRequest request = WebRequest.CreateHttp(contentUrl);
        HttpWebResponse response = null;
        try
        {
            response = (HttpWebResponse)request.GetResponse();
            using (var stream = response.GetResponseStream())
            {
                stream.CopyTo(fileStream);
            }
        }
        catch (WebException ex)
        {
            response = (HttpWebResponse)ex.Response;
        }
        finally
        {
            if (response != null)
            {
                response.Dispose();
            }
        }
    }
```

So we'll need to see the error to debug further.

**Comment by ificator** [comment]
I'm going to close this issue - please reopen if you any new information comes up that would point to an issue on our side.

**Comment by patricksmallhornwest** [comment]
HI there

I believe this issue still exists

**Comment by xiaoninh** [comment]
Yes, the issue exists. When downloading a  folder that is larger than 4gb, it cannot be unzipped and opened .

**Comment by ificator** [comment]
To my knowledge the API described by this documentation does not support downloading a folder as a zip. How are you triggering the download? Is this an action through the web site?
