### ISSUE TITLE
Expected refresh token not returned with offline_access scope?

### ISSUE THREAD

**Issue by JohnRSim** [OneDrive/onedrive-api-docs#601]
Documentation - https://dev.onedrive.com/auth/graph_oauth.htm

Scopes 'offline_access files.read.all'
EndPoint 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize'

I'm passing the above scope however I am not being returned a refresh token only an access token in the oAuth Callback URL.

I'm not sure what I'm missing - I've checked the application has Microsoft Graph Permissions 
'offline_access'

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
