### ISSUE TITLE
[ODB] Sharepoint resource disabled?

### ISSUE THREAD

**Issue by aleksclark** [OneDrive/onedrive-api-docs#602]
We've had a ODB integration in place for nearly 3 years but just recently a client says they are unable to connect their ODB account to our service. From our investigation, the problem appears during the resource token exchange:

we request:
```
https://login.windows.net/common/oauth2/authorize?client_id=XXXXXX&client_secret=XXXXXX&redirect_uri=http%3A%2F%2Fauth-dev.lvh.me%3A3000%2Fauth%2Fazure_ad%2Fcallback&resource=Microsoft.SharePoint&response_type=code&scope=MyFiles.Read%2CMyFiles.Write
```
and the response is:
```
    {"error"=>"invalid_resource", "error_description"=>"AADSTS50001: Resource 'Microsoft.SharePoint' is disabled.\r\nTrace ID: 16750e77-b8c9-4965-ae3c-a471dfc80a00\r\nCorrelation ID: 9bdba4f9-5277-48f6-b735-2548ce4aba71\r\nTimestamp: 2017-04-28 18:49:48Z"}
```

Any ideas? this is the first time we've had this problem. We've tried contacting onedrive support but apparently this is a 'developer problem' that has to do with 'the codes and apis'. appreciate any help, or at least point us in the right direction!

**Comment by aleksclark** [comment]
@ificator any ideas? The ODB people 'handling' this ticket have bounced me to 3 separate call centers so far, and nobody even seems to know what 'integration' or 'api' mean....

**Comment by aleksclark** [comment]
@rgregg Omar Shahine says you're the guy to talk to about OneDrive API issues, have any input on the above error?

**Comment by rgregg** [comment]
HI @aleksclark 
I need to do some more digging here, because I'm surprised that ever worked. The resource string needs to be the URL for the service that you are calling, such as `https://contoso.sharepoint.com`. I haven't seen the syntax you are using, with "Microsoft.SharePoint" as the resource before. Is that the same request syntax that worked previously?

**Comment by aleksclark** [comment]
Hi! It's still working today, for many other customers, it's just this one that doesn't. It smells like it's the correct syntax too, since the API response isn't saying the resource isn't found, it's saying it's disabled.

**Comment by rgregg** [comment]
That error can mean that the user's Office 365 license is no longer available or has expired. In the scenarios where you are seeing the failure, are you certain the user still has a valid license?

**Comment by aleksclark** [comment]
I just logged into the test account on that user's Office 365 and uploaded a file to ODB, I assume that means it's working....

**Comment by aleksclark** [comment]
my same code as before is now getting a different error message: {"error"=>"invalid_resource", "error_description"=>"AADSTS50001: The application named Microsoft.SharePoint was not found in the tenant named {CORRECT TENANT URL}.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 37c6a15f-b49f-4397-a5e1-080453f01800\r\nCorrelation ID: c3ea5522-4361-437e-89d4-3f7f2062a363\r\nTimestamp: 2017-05-11 23:22:18Z"}

**Comment by rgregg** [comment]
OK @aleksclark. We're investigating. Do you get the same error if you try the request using resource={url} instead of resource=Microsoft.SharePoint?

**Comment by aleksclark** [comment]
Rewriting to follow the new docs has gotten me further, I am able to discover and use their sharepoint, but now I'm getting this error when trying to upload a file: 
```
10:45:42 web.1            | User-Agent: "Faraday v0.9.1"
10:45:42 web.1            | content-length: "2207"
10:45:42 web.1            | content-range: "bytes 0-2206/63017"
10:45:42 web.1            | 401
10:45:42 web.1            | content-length: "84"
10:45:42 web.1            | server: "Microsoft-IIS/10.0"
10:45:42 web.1            | p3p: "CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\""
10:45:42 web.1            | www-authenticate: "Bearer realm=\"8361c3d5-b6c8-498a-a27b-2f5487ecd340\",client_id=\"00000003-0000-0ff1-ce00-000000000000\",trusted_issuers=\"00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b\",authorization_uri=\"https://login.windows.net/common/oauth2/authorize\""
10:45:42 web.1            | sprequestguid: "466b009e-a011-3000-2f68-29bfce031aa9"
10:45:42 web.1            | request-id: "466b009e-a011-3000-2f68-29bfce031aa9"
10:45:42 web.1            | strict-transport-security: "max-age=31536000"
10:45:42 web.1            | x-frame-options: "SAMEORIGIN"
10:45:42 web.1            | sprequestduration: "48"
10:45:42 web.1            | spiislatency: "2"
10:45:42 web.1            | x-ms-suspended-features: "features=\"\""
10:45:42 web.1            | x-powered-by: "ASP.NET"
10:45:42 web.1            | microsoftsharepointteamservices: "16.0.0.6621"
10:45:42 web.1            | x-content-type-options: "nosniff"
10:45:42 web.1            | x-ms-invokeapp: "1; RequireReadOnly"
10:45:42 web.1            | x-msedge-ref: "Ref A: 43F46DA6AFCD4E4E92C5757E46AAEDF4 Ref B: BL2EDGE0818 Ref C: Thu Jun 29 08:45:42 2017 PST"
10:45:42 web.1            | date: "Thu, 29 Jun 2017 15:45:41 GMT"
10:45:42 web.1            | connection: "close"
10:45:42 web.1            | Index and length must refer to a location within the string.
10:45:42 web.1            | Parameter name: length
```

**Comment by aleksclark** [comment]
figured this out: the server doesn't like URL-encoded parameters and thus throws this opaque error
