### ISSUE TITLE
Sharepoint Add Folder error

### ISSUE THREAD

**Issue by anildbest83** [OneDrive/onedrive-api-docs#603]
When i m trying to create a folder on Sharepoint using OneDrive Business API i m getting following error.

odata.error
value=Invalid JSON. More than one value was found at the root of the JSON content. JSON content can only have one value at the root level, which is an array, an object or a primitive value.

My API request is

POST /_api/web/folders 
{'__metadata':{'type':'SP.Folder'}, 'ServerRelativeUrl':'/Shared Documents/PB35(Test Consulting Pty Ltd)'}}

It was working fine earlier but suddenly breaks.

Please suggest

**Comment by ificator** [comment]
@anildbest83 that doesn't look like a call to the OneDrive Business API - it looks like the SharePoint REST API. If you want to switch to the OneDrive Business API, which we support here, I'd suggest you take a look at [our documentation](https://dev.onedrive.com).

I can, however, offer a general statement about what you're seeing. The JSON you provided above seems to a superfluous } at the end - it's possible that's confusing the deserializer.

**Comment by anildbest83** [comment]
@ificator thanks for your reply, yes it is SharePoint Rest API. Do you know where i can post questions related to it?

**Comment by anildbest83** [comment]
@ificator your suggestion work perfectly but the same thing working before not sure how, anyway thanks.
