### ISSUE TITLE
Getting access token during OneDrive File Picker JavaScript SDK v7.0

### ISSUE THREAD

**Issue by spyronis** [OneDrive/onedrive-api-docs#605]
Hi.
I am following the process to integrate OneDrive JS file picker as noted here: https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm.

After successful download of file details, I want to use separately OneDriveAPI. This will require an access_token. Is it possible to get that from authentication process that happened during the picker instance?

**Comment by daboxu** [comment]
Thanks for the feedback, actually the accesstoken is included in our [new version](https://dev.onedrive.com/sdk/js-v72/js-picker-overview.htm).

**Comment by spyronis** [comment]
I tried that but:
When I embed 7.2 version on my oneDrive picker page <script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>) and try to do: OneDrive.open(options) to open that page, nothing loads on the picker page (it is just an empty page).

However, when I am including <script type="text/javascript" src="https://js.live.net/v7.0/OneDrive.js"></script> everything seems to be fine.

From documentation I cannot find any difference to setup. Is it something I may probably be missing?
Thanks.

**Comment by daboxu** [comment]
My guess is you haven't set the 'my_onedrivePickerPage' with a reference to the v7.2 picker? We have different way of consuming the parameters when invoking the new popup window. By the way, you don't need to specify the `openInNewWindow` param as it is by default in v7.2.

**Comment by spyronis** [comment]
What is the reference to the 7.2 picker?
Currently I am adding <script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script> on my-onedrivePickerPage. 
Any more clues? Or any working example/ sample ? Thank you very much

**Comment by daboxu** [comment]
your reference is right as I saw, the sample is on our dev portal: https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm. Does the working sample work for you? If so, what's the url you see on the popup? Any query parameters or hashes?

**Comment by spyronis** [comment]
The sample is working for me.
But for my webapp, when my oneDrivePicker page opens, it is returning 400. Specifically this is the request:

https://WEB_APP_HOST_PAGE/onedrive_picker.html
?oauth={
%22clientId%22:%XXXXXXX-XXXXX-XXXXXX-XXXX-XXXXXXX%22,
%22endpoint%22:1,
%22scopes%22:[%22Files.Read.All%22],
%22origin%22:%22https://WEB_APP_HOST_PAGE%22,
%22redirectUri%22:%22https://WEB_APP_HOST_PAGE/onedrive_picker.html%22,
%22state%22:%22https://WEB_APP_HOST_PAGE_AxPmi%22}

When I checked the request (before the authenticate) for the previous successful sample, the format of query string of request is similar.

Is it possible I have something wrong on my options that I use to open the window?
var odOptions = {
                                clientId: _that.pickerAppID,
                                action: "download",
                                multiSelect: false,
                                advanced: {
                                    redirectUri: oneDrivePickerPage,
                           }
OneDrive.open(odOptions);

It s weird, because if I replace JS library with : <script type="text/javascript" src="https://js.live.net/v7.0/OneDrive.js"></script>, everything works as expected..

**Comment by daboxu** [comment]
what's the 400 error saying? Switch to 7.0 works because you are using the 7.0 SDK while you cannot get access token, right?

**Comment by spyronis** [comment]
It is a 400-Bad Request 
There is no Preview/Response available.

You are right, I am trying to switch to 7.2 to have the advantage of getting access token, but still no luck. When replacing with 7.0 I am getting a successful redirect to loginpage via this request:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize
?redirect_uri=https%3A%2F%2FWEB_APP_HOST_PAGE/onedrive_picker.html
&client_id= xxxxxx-pickerAppID-xxxxxx
&scope=profile%20openid%20https%3A%2F%2Fgraph.microsoft.com%2FFiles.ReadWrite%20https%3A%2F%2Fgraph.microsoft.com%2FUser.Read
&response_mode=fragment
&state=aad_login
&nonce=H7jdB
&response_type=id_token+token

**Comment by daboxu** [comment]
I see, I tested with the same param with the dev portal and it does the redirect to OAuth page
```
https://WEB_APP_HOST_PAGE/onedrive_picker.html
?oauth={
%22clientId%22:%XXXXXXX-XXXXX-XXXXXX-XXXX-XXXXXXX%22,
%22endpoint%22:1,
%22scopes%22:[%22Files.Read.All%22],
%22origin%22:%22https://WEB_APP_HOST_PAGE%22,
%22redirectUri%22:%22https://WEB_APP_HOST_PAGE/onedrive_picker.html%22,
%22state%22:%22https://WEB_APP_HOST_PAGE_AxPmi%22}
```

I am suspecting something wrong on the onedrive_picker.html which prevent the redirect happen.. Are you using [Fiddler](http://www.telerik.com/fiddler) for capturing your https traffic? You can enable that in [Tools]-[Telerik Filddler Options]-[Https] check `Capture HTTPS CONNECTs` and `Decrypt HTTPS traffic`.

Let's see what's the 400's request and error. Please let me know if you need help with using Fiddler.

**Comment by spyronis** [comment]
One more note: I am using a custom redirect page onedrive_file_picker.html as described on the section **Using a custom redirect URI** https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm.

That means this page is very simple and just contains the js-v7.2 script:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OneDrive Picker</title>
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
</head>
<body></body>
</html>

This page is passed as redirect url when I am calling on my JS the OneDrive.open(options) (which opens the picker), as I have described previously. I am really wondering what has been changed from 7.0 and this is broken now?

I ll run Fiddler and let you know for any updates.

**Comment by daboxu** [comment]
thanks, we change the way we communicate between the popup and the host page (which opens the picker). In 7.2 we use postMessage and in 7.0 we use a custom defined function. Post message allows us to set up the redirect page and the host app page in different subdomain.

**Comment by spyronis** [comment]
**UPDATE**
The issue seems to happen because I am using the default API endpoint (https://graph.microsoft.com/v1.0/).
When overriding that in my options (by setting **endpointHint**: "api.onedrive.com" and providing the **accessToken** that was received from a previous oauth, I am able to see the dev picker page rendered properly. 

That means I cannot avoid doing the authentication before the picker, receive the access_token and then use it to immediately open the file picker. 

I am still wondering how the default endpoint is being used.

**Comment by daboxu** [comment]
so providing endpointHint will let you avoid the OAuth flow which in bascially is a redirection process:

https://WEB_APP_HOST_PAGE/onedrive_picker.html?oauth={param} -> OAuth Endpoint, here is Microsoft AAD Oauth V2 https://login.microsoftonline.com/common/oauth2/v2.0/authorize -> https://WEB_APP_HOST_PAGE/onedrive_picker.html#access_token=xxxx -> OneDrive Picker UI

the arrow `->` means redirect. As you provided the info in post above, the issue happens for your app at the first redirection from  https://WEB_APP_HOST_PAGE/onedrive_picker.html to Microsoft AAD Oauth V2.

If you have access token before invoking the picker, I would encourage you continue provide endpoint hint and access_token but it is very very *strange* to me that you are hanging on the page https://WEB_APP_HOST_PAGE/onedrive_picker.html?oauth={param} because the SDK does the redirect as soon as it parses the query parameter `oauth` in the url. That's why the 400 error looks wired.

Another useful debugging tool is our debug js binary version: http://js.live.net/v7.2/OneDrive.debug.js
you can reference it in your project, if you are hanging on the popup page: https://WEB_APP_HOST_PAGE/onedrive_picker.html?oauth={param}

open Chrome console and set break point at ```handleOauth``` invocation:

```javascript
    function onAuth() {
        DomUtilities_1.onDocumentReady(function () {
            var redirResults = UrlUtilities_1.readCurrentUrlParameters();
            var isOauth = redirResults[PARAM_OAUTH_CONFIG] || redirResults[PARAM_ERROR] || redirResults[PARAM_ACCESS_TOKEN];
            if (isOauth && window.opener) {
                handleOauth(redirResults, new Channel_1.default(window.opener));
            }
        });
    }
```

if it never got hit, we can check whether `isOauth` is false or the `window.opener` is undefined. Looking forward for more info.

**Comment by daboxu** [comment]
closed for now as you got a solution for your case.
