### ISSUE TITLE
Cannot select download URL through Graph

### ISSUE THREAD

**Issue by ificator** [OneDrive/onedrive-api-docs#606]
The instance annotation that exposes the download URL via graph is `@microsoft.graph.downloadUrl`, however that value is not correctly handled when specified in the select statement.

**Comment by gunna025** [comment]
I ran into this issue and the solution is to query for content.downloadUrl, I wouldn't say that this issue is completely resolved yet.

https://stackoverflow.com/questions/45502275/microsoftgraph-querying-for-microsoft-graph-downloadurl-returns-character-i

**Comment by ificator** [comment]
Hi @gunna025, I just tried using `select=@microsoft.graph.downloadUrl` for both OneDrive for Business and OneDrive for Consumers and it returned the URLs in both cases. If you're seeing it not work could you grab the `request-id` and `date` headers from the response and provide them here?

**Comment by gunna025** [comment]
request-id: 737300e7-e857-406f-9f7b-b85a4b707e95
Date: Mon, 15 Oct 2018 13:18:07 GMT

Also, it may be worth noting that this request is being made with MS Graph and not the one drive API directly.
