### ISSUE TITLE
Usage of "if-match" header in case of file creation

### ISSUE THREAD

**Issue by AndreiPashkin** [OneDrive/onedrive-api-docs#607]
The doc's say<sup>[1][1], [2][2]</sup>:
> If this request header is included and the eTag (or cTag) provided does not match the current eTag on the folder, a 412 Precondition Failed response is returned.

Is there a way to perform similar operation in case if file does not exist on the remote side (and hence doesn't have an eTag)?

[1]: https://github.com/OneDrive/onedrive-api-docs/blob/bede978b6a9c5a107306dd779b878af387a5dcbb/items/update.md#optional-request-headers
[2]: https://github.com/OneDrive/onedrive-api-docs/blob/49dd4ab6d891022d3f9055b675d033d6c97177a9/items/upload_large_files.md#optional-request-headers

**Comment by ificator** [comment]
If you want to assert that target file does not exist you can use:

`If-None-Match: *`

Does that answer your question?

**Comment by AndrewPashkin** [comment]
@ificator, For what requests it is applicable and what is the error response?

**Comment by ificator** [comment]
It should work on any request that directly accesses individual items, but it won't be applicable to enumerations or operations like "delta" and "search". If the precondition fails, you should expect to get back a `412 Precondition Failed`.
