### ISSUE TITLE
Folder creation fails with HTTP code 403 if body JSON includes "size: 0"

### ISSUE THREAD

**Issue by igokoro** [OneDrive/onedrive-api-docs#61]
I'm creating folders as described in http://onedrive.github.io/items/create.htm:

```
POST https://api.onedrive.com/v1.0/drive/items/root/children
Content-Type: application/json

{"folder":{},"name":"e", "size": 0}
```
As a result I'm getting:

403 Forbidden
```
{
    error: {
        code: "accessDenied"
        message: "Access Denied"
        innererror: {
            code: "accessDenied"
        }-
    }-
}
```

Folder creation works fine if *"size": 0* is not included in body JSON, but fails if it is.
I'm aware of the limitation with 0-size files which can't be created through the API. But for folders this restriction is kind of strange! 

And, I believe, return code ```403``` is not the right one for such situations.

**Comment by rgregg** [comment]
Hi @igokoro. I agree that the 403 error seems strange in this situation. I'll take a look at getting that fixed.

If you don't specify the size property, you should be fine. In general you should only include the properties that are required to create the item, which for a folder should look like this:

```json
POST https://api.onedrive.com/v1.0/drive/items/root/children
Content-Type: application/json

{"folder":{},"name":"e"}
```

**Comment by igokoro** [comment]
@rgregg, thank you for acknowledging the issue! 

I agree with the fact that in general we should only include the properties that are required, but, say, on android with gson lib, it might be unnecessarily complex task to do. This would involve custom ```TypeAdapter```s that should be used only in certain situations - generally quite error prone boilerplate!

**Comment by peternied** [comment]
In our [Android application](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ItemFragment.java#L464) we used the following formula to create new folders, which I find very light weight:

```java
final Item newItem = new Item();
newItem.Name = newNameTextView.getText().toString();
newItem.Folder = new Folder();
```

Around posting items back we built up a [rudimentary gson exclusion strategy](https://github.com/OneDrive/onedrive-explorer-android/blob/master/onedriveaccess/src/main/java/com/microsoft/onedriveaccess/GsonFactory.java#L31) which allows the sample application to perform all of its functionality.

**Comment by igokoro** [comment]
I'm using [LoganSquare](https://github.com/bluelinelabs/LoganSquare) library to handle JSON, so can't use gson exclusion strategies (in addition to the fact that I specifically avoid them as they harm performance). I've ended up defining specialized DTO that includes only required fields - the simplest and most efficient way of handling this.
