### ISSUE TITLE
OneDrive API view.delta using 'top' results in missing files

### ISSUE THREAD

**Issue by ritter** [OneDrive/onedrive-api-docs#610]
Specifying any value for 'top' on the view.delta endpoint results in files missing from results (when the total number of files exceeds the value given to 'top').

Example scenario:
Put 11 documents in to two nested folders:
"/drive/root:/FolderOne/FolderTwo/FileOne.docx"
...
"/drive/root:/FolderOne/FolderTwo/FileEleven.docx"

Make a request to OneDrive API for Deltas with a 'top' value of 10:
https://api.onedrive.com/v1.0/drive/root/view.delta?top=10

The result will contain ten total items, the first three are the root and folder driveItem resources. The remaining seven are file driveItem resources. The result will also include a '@odata.nextLink' and '@delta.token'.

Using either the '@delta.token' or '@odata.nextLink' to get the next page of results will return a response of four total items. Of these items, three again are the folder driveItem resources, leaving one that is a file driveItem resource. The response will again provide a token for the next page.  However, this is the last response and returns only the root driveItem resource.

The end result is that three of the eleven files where never included in the results.

The number folders (and root) in the result, will be the number files missing. If there are more folders than the value given in 'top' no file driveItem resources will ever be returned.

The simple workaround is to not specify 'top' in the request.

**Comment by ificator** [comment]
That's quite the bug... thanks for reporting @ritter

**Comment by ificator** [comment]
This issue should now be resolved!

**Comment by ritter** [comment]
Thank you!  This appears to be resolved for us.
