### ISSUE TITLE
Javascript SDK 7.2 File picker & Windows 8/ IE11 support

### ISSUE THREAD

**Issue by spyronis** [OneDrive/onedrive-api-docs#612]
Hi.
I am testing my oneDrive file picker integration with IE11 (Windows 8).
I am using SDK 7.2 (https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm)

When I am testing the sample demo from previous link, just before loading the picker I am getting a waiting indicator (spinning circle) that stays forever - followed by empty page (this is the url : https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm). (for older versions v7.0, v.6.0 I didn't notice any problems)

On my custom web application, I am able to connect to the picker but when trying to select an item to open it, I am getting following error on picker window: **The file couldn't be shared. Please try again later.** This also appears when I am hitting Cancel button.

Is there any support for Windows/ IE11 ? 
ps. I am using browser stack for testing IE11.

**Comment by spyronis** [comment]
Update:
Tested on Browser Stack on Windows7/IE11 and it is working.

**Comment by spyronis** [comment]
**Update 2**
For my application I am using endpoint endpoint https://api.onedrive.com/v1.0/)
due to restrictions noted on : https://github.com/OneDrive/onedrive-api-docs/issues/605#issuecomment-301139046

**Comment by daboxu** [comment]
can you check your IE security settings? 'postMessage' is not working in IE #550

**Comment by spyronis** [comment]
I cannot change IE security settings as I am testing through Browser Stack machines.

To sum up: v7.2 is **working** for:

Windows7/IE11
Windows10/IE11

**not working** for:
 Windows 8/IE11.
Windows8.1/IE11

Tested on https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm

**Comment by daboxu** [comment]
currently not a good solution for the compatibility issue except changing the settings on IE. close it for now.

**Comment by olanb7** [comment]
@daboxu can I ask why this was closed? Are there any plans to fix this?

I'm seeing the same issue - OneDrive Picker works fine in IE11 on Win 10 & Win 7, but does not do anything after redirecting from the auth login in Win 8.1.
