### ISSUE TITLE
Problem with QuickXorHash

### ISSUE THREAD

**Issue by judithting** [OneDrive/onedrive-api-docs#613]
Hi,
I am trying to implement a C++ program for QuickXorHash. 
To verify my code, I use OneDrive API to get the quickXorHash value of ```a.txt``` file in my OneDrive for Business.

The contents of the file is

```
1\n
```

and the OneDrive API response

```
"quickXorHash": "MVAAAAAAAAAAAAAAAgAAAAAAAAA="
```

According to the document (https://dev.onedrive.com/snippets/quickxorhash.htm),
```
method block extend64(int64 i):
     returns a block of all zero bits except for the lower 64 bits which come from i.

method block XorHash0(byte rgb[], int cb):
     block ret = zero()
     for (int i = 0; i < cb; i ++)
       ret = xor(ret, rotate(extend8(rgb[i]), i * 11))
     returns ret

entrypoint block XorHash(byte rgb[], int cb):
     returns xor(extend64(cb), XorHash0(rgb, cb))
```

we call ```XorHash()``` to calculate the hash value of quickXorHash algorithm.
In my case, ```rgb``` is "1\n" and  the size of input byte array is 2 (aka ```cb = 2```).

First, we call ```XorHash0()```, and execute ```xor()``` twice in the for-loop; then return 
```ret = {'\000' <repeats 18 times>, "P1"}```  to the caller (```XorHash``` function).

Second, we call ```extend64(2)``` and get the return value = ```{'\000' <repeats 19 times>, "\002"}```.

Next, we execute ```xor()``` with the return values from ```extend64()``` and ```XorHash0```, then get
```ret = {'\000' <repeats 18 times>, "P3"}```.

Furthermore, after encoding by Base64 algorithm, the quickXorHash of ```a.txt``` is 
```"AAAAAAAAAAAAAAAAAAAAAAAAUDM="```.

However, my result is not as same as the Onedrive API responded.

Do I misunderstand the QuickXorHash algorithm?

**Comment by ificator** [comment]
I would use the C# code as your guide to port it to C++ as that implementation is definitely correct. It's possible that the pseudo code itself has a bug in it that we haven't spotted yet so I'll take a look at implementing it myself.

But your implementation does seem a little off - for starters `extend64(2)` should give something like:
0000000000000000000000000200000000000000

My guess is that we're looking at a byte order issue - the algorithm is assumed to convert integers to little-endian and so 2 should be 0x0200000000000000 and not 0x0000000000000002. It looks like we need to update the docs to clarify that at the very least.

**Comment by judithting** [comment]
Thanks for your explanation.
I found the bug in my program, but I'm not sure my modification is followed quickXorHash algorithm or not.
Besides, I should apologize for my typo of return value on the previous post first, and I have corrected it.

As your guess, the bug is about byte order issue. I modify these two methods: ```extend64()``` and ```XorHash0()```, and get the correct hash value in Base64 type.

In ```extend64()```, I modify the implementation according to your advise, and get the return value ```ret = 0x0000000000000000000000000200000000000000```. 
In ```XorHash0()```, before ```return ret```, I convert it to little-endian. Therefore, I get the return value  ```ret = 0x3150000000000000000000000000000000000000```. (aka ```ret = {"1P" '\000' <repeats 18 times>}```)
After the above modification, we can get the return value ```0x3150000000000000000000000200000000000000``` from ```XorHash()``` and encode it into Base64 type to get the hash value: ```"MVAAAAAAAAAAAAAAAgAAAAAAAAA="```.

Are the above modifications correct?

**Comment by ificator** [comment]
Realistically if you're getting the right value your modifications are most likely perfect :). I'd confirm by running your code after numerous files from a drive and comparing the values with what the service returns.

On our side I think we need to make two changes to the documentation:
1. We need to call out the byte order for the "extend" methods
2. It does seem like the result of XorHash0 needs to be byte reversed as well, even though there's really no question of endian-ness

Thanks for working through this!

**Comment by ificator** [comment]
The documentation update has now worked its way through and been published.

**Comment by liubeck** [comment]
@judithting 
I am trying to implement a C++ program for QuickXorHash too. And I have a lot of issues.
Could you show your implement and give me a reference?

**Comment by vikram9491** [comment]
@ificator  how to generate quickxorhash value 
byte[] hashArray =  { 48, 49, 86, 50, 75, 85, 89, 82, 70, 81 ,72, 53, 72 ,69, 86, 52, 82, 85, 84 ,82, 66, 73, 87, 87 ,79 ,76 ,84, 73, 50 ,83, 78, 83, 81, 80 };
//byte[] hashArray = {150, 131 ,160, 235, 250, 243, 185, 8 ,191, 159, 10, 168, 143, 95, 123 ,116, 187, 168, 19, 195};
Console.WriteLine("hasharray::::");
Console.WriteLine(hashArray.Length);
 quickXorHash.HashCore(hashArray,0,34);
  var hashValue = quickXorHash.HashFinal();

        Console.WriteLine("OneDrive QuickXorHash Value:");
        foreach (var b in hashValue)
        {
            Console.Write(b + " ");
		}
       // Convert the hash value to Base64 string
        string base64Hash = Convert.ToBase64String(hashValue);
        Console.WriteLine("\nBase64 Hash Value: " + base64Hash);   tried like this but couldn't generate same like onedrive response .
