### ISSUE TITLE
OneDrive WL.fileDialog does not work again.

### ISSUE THREAD

**Issue by audiorecorder** [OneDrive/onedrive-api-docs#615]
The same error occurs again. https://github.com/OneDrive/onedrive-api-docs/issues/599 (fixed issue)
It has been fixed some time ago and I get the same error again.

*Network Error Log
Request URL:https://skyapi.onedrive.live.com/API/2/GetItems?caller=CA2A8FEEFF8DB9F1&m=en%2DAU&rset=skyweb%5Fpicker&v=0%2E31253185914829373&d=1&iabch=1&pi=5&path=1&lct=1&id=undefined&urlType=2
Request Method:GET
Status Code:500 Internal Server Error

Response: {"error":{"code":1007,"debugMessage":"Invalid item id passed.  Must be null, 'root', canonical name, or a valid item id.","isExpected":true,"message":"Sorry, something went wrong. Please try again, or refresh the page.","stackTrace":"811b5a5354d308112:Jaks37wUP55\/e9ve8risSgPYj7ZnvtpaacKMbPggLnz8qbNP9Ao\/T97D...."},"transactionId":"44600c34-e078-4356-81e1-acc4489718d8.SkyDrive1"}

=================================================
Previous Issue 599 
=================================================
OneDrive WL.fileDialog (javascript API for web apps) does not work anymore. This file/folder seletor feature has worked for two years. But now it does not work.
"The folders couldn't be shared. Please try again later." error occur. How to fix it?

More Detail, Screencapture (stackoverflow)
http://stackoverflow.com/questions/43715793/onedrive-wl-filedialog-does-not-work-anymore

WL.fileDialog({
    mode: "save"
}).then(
    function(resp){
        if(!resp || !resp.data || !resp.data.folders || resp.data.folders.length==0)return;
        var id=resp.data.folders[0].id;
        var arr=id.split('.');
        if(arr.length==3){
            id=arr[arr.length-1];
        }else{
            id='';
        }
        proc_setfolder(id, resp.data.folders[0].name);
    },
    function(resp){
        //alert(resp.error_description);
    }
);

**Comment by ThomasMichon** [comment]
Apologies, I think a build without the fixes snuck out thanks to some unfortunate timing and some emergency rollbacks. Good news is that a new build with the fixes permanently applied should be out shortly.
