### ISSUE TITLE
[ODB] AADSTS70000 when get refresh_token and access_token from api.office.com/discovery/

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#618]
Hi,

one of my client request this POST to get refresh_token and access_token
```
https://api.office.com/discovery/
"code" => $code,
"client_id" => client_id,
"client_secret" => client_secret,
"redirect_uri" => redirect_uri,
"resource" => "https://api.office.com/discovery/",
"grant_type" => "authorization_code"
```
but the response is 
```
error = invalid_grant
&error_description = 
AADSTS70000: Transmission data parser failure: Authorization Code is malformed or invalid.
Trace ID: 48298c93-4ac2-4dff-a592-f276f8ad0700
Correlation ID: c399efc2-9765-497f-b6aa-8ea61b1f4bff
Timestamp: 2017-05-10 09:31:50Z
```

However the flow is good for other users, did not encounter this before.
Could you please to advise me
thank you for help!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
