### ISSUE TITLE
Partial file download via HTTP Range header suffix doesn't work

### ISSUE THREAD

**Issue by igokoro** [OneDrive/onedrive-api-docs#62]
I need to download last 5000 bytes of files in my application. Usually this can be implemented by suppling header into the download request:

```Range: bytes=-5000```

But at the moment OneDrive API ignores the Range header in this form, server returns this for one of my files:
```
200 OK
Content-Length: 93816
```
This is not correct - ```206``` status code should be returned along with only requested bytes.

If I download with ```Range: bytes=0-5000``` - it works as expected, returning: 
```
206 OK
Content-Length: 5001
```
But this is not what I can use, as I don't usually know file size and can't really request it upfront with a separate request.

**Comment by rgregg** [comment]
Hi @igokoro. I couldn't find anything in the HTTP/1.1 RFCs about being able to do a range request like you mentioned. Do you have a link to an RFC or other supporting documentation that shows negative range values being implemented like that?

Our implementation is correct according to the RFCs, if the value of the range header is not understood, the server is supposed to ignore the range header completely and act as though it wasn't there, which is what we're doing by returning the entire file with an HTTP `200 OK` response.

You can work around this, as you said, by querying for the item's metadata first to get it's size, and then requesting a range like `Range: {item.size}-4999-{item.size}` where you replace `{item.size}` with the value you get from the metadata. Alternatively you could do a HEAD request first to get the Content-Size header and then do the same sort of math to calculate the proper range.

**Comment by ificator** [comment]
It's in http://tools.ietf.org/html/rfc7233#page-8 (or rather the definition of byte-ranges-specifier in http://tools.ietf.org/html/rfc7233#page-5). This behavior is a limitation on our side that we'll need to drill in to further.

**Comment by rgregg** [comment]
I've added this to our backlog. @igokoro can you add this to the [OneDrive User Voice page](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) so the community can help prioritize which requests we should focus on fixing?

**Comment by igokoro** [comment]
Posted item for this issue on OneDrive User Voice: http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7484185-implement-support-for-downloading-a-number-of-byte
