### ISSUE TITLE
Url in @odata.nextLink is wrong/incomplete when fetching by path

### ISSUE THREAD

**Issue by cguZZman** [OneDrive/onedrive-api-docs#620]
The url in the **@odata.nextLink** property is not complete when a list is requested by path.

The response of the request: 
`https://graph.microsoft.com/v1.0/drives/c12345/root:/music/abc:/children`
is:
```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives('c12345')/root/children",
  "@odata.nextLink": "https://graph.microsoft.com/v1.0/drives/c12345/root/children?$skiptoken=MjAx",
  "value": [
    {
```
Thef item path is missing.
Response for `@odata.nextLink` should be:
```
"@odata.nextLink": "https://graph.microsoft.com/v1.0/drives/c12345/root:/music/abc:/children?$skiptoken=MjAx",
```

**Comment by rgregg** [comment]
I'm unable to reproduce this issue. We fixed this back in February, and the fix still looks good today. If you can reproduce this, please let us know.
