### ISSUE TITLE
OneDrive Write Permission in Refresh Token Response Handler

### ISSUE THREAD

**Issue by tmvipinster** [OneDrive/onedrive-api-docs#621]
We have an app that integrates with onedrive for business . Based on the response MyFiles.Read and MyFile.Write we disable certain actions in our app.

Now the issue is that when we disable the write permissions in Application settings as attached in the screenshot
<img width="853" alt="screen shot 2017-05-30 at 4 30 02 pm" src="https://cloud.githubusercontent.com/assets/306124/26580371/67962b4e-4555-11e7-8890-c6eacc29cfeb.png">

In the response we always get MyFile.Write due to which we are not able to disable certain buttons in our app.

The request we send is as below

URL = https://login.windows.net/common/oauth2/token
Params in Get Request client_id=%@&redirect_uri=%@&refresh_token=%@&grant_type=refresh_token&resource=%@

where %@ is replaced by appropriate values

Please let us know if we are sending the correct parameters or is it something wrong in the server side

**Comment by rgregg** [comment]
@tmvipinster The configuration settings for the app in the Azure Portal specify which permissions a new user, who has not previously consented to your app, will receive. If a user has previously consented to your app, they will continue to have the same permissions they originally received until the user goes through the consent flow again. You can force this to happen by adding `&prompt=consent` to the end of the request to the authorization endpoint.
