### ISSUE TITLE
Get permanent file link

### ISSUE THREAD

**Issue by AndrewLang** [OneDrive/onedrive-api-docs#622]
Currently for DriveItem, there is no way to get a permanent link of a file, so it is not possible to insert images from OneDrive to my blog post (WordPress). 
From the documentation here [https://dev.onedrive.com/resources/item.htm](https://dev.onedrive.com/resources/item.htm) the downloadUrl and sourceUrl will expire . 

Is there a way or a plan to get a permanent file link?

**Comment by rgregg** [comment]
Hi @AndrewLang are you targeting OneDrive personal or OneDrive for Business accounts? I ask because there is an answer for OneDrive personal, but not for OneDrive for Business.

**Comment by AndrewLang** [comment]
Hi @rgregg , thanks for your reply, I do use OneDrive personal. 

I suppose you mean create a sharing [link ](https://dev.onedrive.com/items/sharing_createLink.htm).  I tried the embed option, it give back a url with is only able to use with iFrame, that doesn't match my use case. 

My user story is.
As a blog writer, I use this [tool](http://www.matrixrepublic.com/product/details/matrix-writer), I want to insert images from my OneDrive.

Thanks.

**Comment by AndrewLang** [comment]
Is there any updates?

**Comment by rgregg** [comment]
Hi Andrew,

So, it's a bit convoluted, but there is a way. When you call createLink with type = embed, you get back a URL, but you also get back a `shareId` value, which is the key to making this work.

If you take that shareId value, and use it in the following URL, you get a URL that you can embed into a webpage / img tag directly:

    https://api.onedrive.com/v1.0/shares/{shareId}/root/content

This generates a URL that will download the contents of the item (including through img tags). The URL is valid as long as the "embed link" exists, so you can always remove the permissions in the future if you want to revoke access to the file.

You can also generate thumbnail images for the file using the same URL format:

    https://api.onedrive.com/v1.0/shares/{shareId}/root/thumbnails/0/medium/content

**Comment by AndrewLang** [comment]
Hi @rgregg thank you very much!

With one day testing, I think this way works!

Before I asked this question, I spent more than a week to go through onedrive API documentation, there was no answer. 

Just want to know is this a stable way that MS will support it for long time?

Thanks again!

**Comment by rgregg** [comment]
Yes, this is documented here: https://dev.onedrive.com/shares/shares.htm

The shareId part isn’t well explained today because it isn’t consistent between OneDrive and OneDrive for Business but the model is something that we document and support as part of our API story.

**Comment by AndrewLang** [comment]
Great, thanks a lot!

**Comment by exp0nge** [comment]
@rgregg Are the downloadUrls provided through the `/shares/` endpoint permanent also? For example: `https://graph.microsoft.com/v1.0/shares/{share-id}/root/` (say some `@microsoft.graph.downloadUrl` are present). Also, is there a difference in the lifetime of a share direct link when created through the graph api vs the FilePicker SDK (`action:"share"`)?

**Comment by dfredriksen** [comment]
No solution for OneDrive for business? I am hoping to embed links to documents in Visual Studio Team Services cards but if they expire it would be less useful...

**Comment by markspolakovs** [comment]
@rgregg Is there a similar trick for OneDrive for Business?

**Comment by philipstratford** [comment]
> https://api.onedrive.com/v1.0/shares/{shareId}/root/content

Sorry to reply to this three years later but I'm trying to implement this trick myself. Your post says that the `https://api.onedrive.com/v1.0/shares/{shareId}/root/content` will generate "a URL that will download the contents of the item".

Is that in contrast to the documentation [here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_thumbnails?view=odsp-graph-online#retrieve-thumbnail-binary-content) for getting the `content` of image thumbnails, where it says that the response will be the binary content of the image? 

I ask because I'm treating the response from `https://api.onedrive.com/v1.0/shares/{shareId}/root/content` as binary content and trying to use it in an `<img>` tag (e.g. `<img src="data:image/jpg;base64,{response}">`) but not having much success.

**Comment by vitali-karmanov** [comment]
I have OneDrive for Business, and when I call /CreateLink with type view and scope anonymous I don't get the shareId at all.

It is forcing me to use the webUrl. However, I wish I was able to call /Shares with the shareId and access the file directly.

@rgregg Is there any solution for OneDrive Business? Thank you.

**Comment by dmillerywg** [comment]
Hi I was trying to do the same if you use Create share link by Path then Select Link type in my case Edit then link Scope Organization I am able to get the file URL
