### ISSUE TITLE
[ODB] how to get drive or resource on Office 365

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#623]
Hi @rgregg ,

Thank you for reply @ #592 

As we could not guarantee the validation of root url (or resource) which parses from graph's id_token,
because there is no general templet for its composition.

So we decide to manually fill it instead of parsing it from API response.
The usage of this resource is to get onedrive API's access token.
(Because we use graph API to handle user's info but user old onedrive API to handle files)

And this is the way I to get onedrive resource uri.
![image](https://cloud.githubusercontent.com/assets/12619781/26672727/e14bc1fe-46ec-11e7-873f-5171e98b8015.png)

I want to ask is there any better way to get the resource uri? more formal?
And how to indicate which one is the onedrive API resource uri

Thank you for help.

**Comment by rgregg** [comment]
Hi @joewutaiwan 
You should be able to use the Graph API for anything and everything you're using the OneDrive API for today. Is there a reason you're unable to just use the Graph API to make all the requests?

You can use the Graph API to retrieve the user's OneDrive URL:

    GET https://graph.microsoft.com/v1.0/me?$select=mysite

And to get the SharePoint root site URL:

    GET https://graph.microsoft.com/v1.0/sites/root?$select=webUrl

These URLs can then be used to get the resource ID to request an access token. You should always trim the resulting URL to just protocol + hostname though, just in case the URLs in the future contain additional path information.
