### ISSUE TITLE
Set only domain for picker auth redirect?

### ISSUE THREAD

**Issue by mdedys** [OneDrive/onedrive-api-docs#624]
I am trying to get auth redirect working for my application but running into an issue where I cannot just specifiy the domain for the redirect.

Ex: `https://my.domain.com`

My applications will be deployed to an endpoint like this: `https://my.domain.com/apps/{version}/`

Currently the only way I could get it to work is to directly specifiy: `https://my.domain/apps/1.0/`. I could work with this in a production environment but in a test environment the version would be a git hash and adding a new url redirect for each test deployment is not feasible. Am I going about this the wrong way or  is there a way to achieve this?

Another question I have is about local development. The application registration portal only allows localhost with the `http` protocol. My application locally runs off of `http://machine-name:port`. Setting `localhost:port` does not work and I cannot set `http://machine-name:port` on the portal page due to not being able to use `http`. Is there a better approach with dealing local dev environments?

**Comment by daboxu** [comment]
@mdedys I am sorry that's the limit for the oauth process, and I found a user voice reported here similar to your request: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/18320224-allow-http-redirect-uris-from-private-address-spac. You can vote up for addressing the impact. Currently for there is no work around at Picker SDK side for avoiding this, really sorry about that.

**Comment by daboxu** [comment]
Thanks for the report and close it for now.
