### ISSUE TITLE
Picker fails to open documents on mobile

### ISSUE THREAD

**Issue by mdedys** [OneDrive/onedrive-api-docs#626]
On mobile Safari and Chrome for iOS 10 I cannot open a file. It shows a message 'File couldn't be shared. Please try again later' when pressing **open** or **cancel**.

**Comment by AurelioDeRosa** [comment]
Can we have an update for this? This is affecting me too.

**Comment by chackman** [comment]
Sorry about this very old issue going stale. If this is still reproducing, could you please provide updated request & response information to help us investigate further? Thanks.
