### ISSUE TITLE
Complete status for upload_url

### ISSUE THREAD

**Issue by ddurdle** [OneDrive/onedrive-api-docs#63]
With reference to this feature: http://onedrive.github.io/items/upload_url.htm

I did some testing of a 700MB Mp4 file. It took 30 mins to get to 50% downloaded (querying the monitor URL). I walked away, assuming it would finish at 30 mins later. Came back in 30 mins and the monitor URL displayed error 404. The file never made it into my OneDrive. There must have been a download error in the last 50%. I can't seem to find a way of validating that. Should the monitor URL remain functional afterwards to indicate success/failure?

**Comment by ificator** [comment]
Thanks for the feedback @ddurdle. The monitor URLs do remain active for a period of time after the completion (failure or success) of the upload, but as you've observed that period of time is pretty short. We'll look in to bumping it up to something that's more useful.

**Comment by ificator** [comment]
The tombstone period is now around 4 hours. We're investigating increasing it further, but hopefully this new value is suitable for most scenarios.

**Comment by ddurdle** [comment]
I concur, 4 hours would be most reasonable.
