### ISSUE TITLE
FilePicker SDK needs to support File.ReadWrite.Selected scopes

### ISSUE THREAD

**Issue by rgregg** [OneDrive/onedrive-api-docs#630]
Instead of granting full access forever to an application to use the file picker, we should leverage the .Selected scopes to allow the app access only to the files that were selected by the user.

**Comment by nat-ser** [comment]
@rgregg @ncabeen  I am using the picker sdk v7.2 to open a file with a `share` action.  According to the docs,  the permission `scopes` default is:  
```
The SDK will automatically request the Files.Read.All scope for open flows, and Files.ReadWrite.All scope for save flows. However, if you wish to request additional permissions, you can add additional scopes here.
```
Please see https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#advanced-options

The actual permissions requested are not consistent with this statement. Below is a screenshot of how it works for me 

![premissions_requested__file_picker](https://user-images.githubusercontent.com/8990017/67519450-e29ba080-f674-11e9-8229-80783429b22d.png)

1) Am I right to assume that my problem has to do with this particular issue?
2) If so, do you have an update on the progress of this task?

**Comment by KevinTCoughlin** [comment]
What is incorrect in the above screenshot?

The Picker uses OAuth interactive mode which requires the user to accept the scopes requested which are the following in-code for `v7.2` when using `share` action:

```js
if (!_this.scopes) {
    _this.scopes = [_this.action === PickerActionType_1.default.share ? 'Files.ReadWrite' : 'Files.Read'];
}
```

When saving the Picker only requests the following scope:

```js
if (!_this.scopes) {
    _this.scopes = ['Files.ReadWrite'];
}
```

https://js.live.net/v7.2/OneDrive.debug.js

Currently, the Picker does not make use of `File.ReadWrite.Selected`.

**Comment by nat-ser** [comment]
Based on the docs, I was under the impression that the default scope for open flows was `Files.Read.All`.  Is the open flow with `share` action considered a `save` flow?

![Screen Shot 2019-10-24 at 16 29 00](https://user-images.githubusercontent.com/8990017/67522836-76706b00-f67b-11e9-88ee-3a94da0c6137.png)

**Comment by KevinTCoughlin** [comment]
> Based on the docs, I was under the impression that the default scope for open flows was `Files.Read.All`. Is the open flow with `share` action considered a `save` flow?
> 
> ![Screen Shot 2019-10-24 at 16 29 00](https://user-images.githubusercontent.com/8990017/67522836-76706b00-f67b-11e9-88ee-3a94da0c6137.png)

Share requires write access to create the URL: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online

We can modify the documentation if it is unclear; I'm open to suggestions or PRs.

**Comment by nat-ser** [comment]
Makes sense, thanks for clarifying.

It was a bit unclear because `Save a file` is a separate section https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/save-file?view=odsp-graph-online I thought everything under `Open a file` section is an `open` flow and everything in the `Save a file` section is a `save` flow.

**Comment by jcharnley** [comment]
can we tailer the scope permissions via the option request or is it inherent from options.action variable?

**Comment by jcharnley** [comment]
nevermind found it i think

```
    action: "share",
      advanced: {
          scopes: [
            "openid",
            "profile",
            "User.Read",
            "Files.ReadWrite",
            "Files.ReadWrite.All",
          ]
      },
```

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
