### ISSUE TITLE
OneDrive for Business: Upload a file whose filename contains the string "$0" will result in several directories and wrong filename.

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#631]
When I use the graph API to upload a file whose filename contains the string "$0" to OneDrive for Business, the result is not correct, there will be several directories whose names are the pathnames of the API endpoint and the file will also named after with the last pathname of the API endpoint or the parent folder id. 
Example1: if I upload a " aa$0bb.txt" to the root directory of OneDrive for Business, it will result in a directory structure: aa\drive\rootbb.txt. the API endpoint that I use is "https://graph.microsoft.com/v1.0/me/drive/root:/" + URIUtil.encodePath(filename, "UTF-8") + ":/content";
Example2: if I upload a "aa$0bb.txt" to a non-root directory of OneDrive for Business, it will result in a directory structure: aa\drive\items\parentFolderIdbb.txt. the API endpoint that I use is "https://graph.microsoft.com/v1.0/me/drive/items/" + parentFolderId + ":/" + URIUtil.encodePath(filename, "UTF-8") + ":/content";
So I want to know what's wrong with this situation? Thanks.

**Comment by ificator** [comment]
Wow, this is a strange one! Thanks for reporting @imkk.

**Comment by imkk** [comment]
Not at all, please let me know the result when you solve it. Thanks.

**Comment by ificator** [comment]
This issue appears to have been resolved by Graph now, please let us know if you still see issues.

**Comment by imkk** [comment]
It's alright now, thanks for your job.
