### ISSUE TITLE
Can't get the hash value after rename a .jpg/.png file

### ISSUE THREAD

**Issue by judithting** [OneDrive/onedrive-api-docs#632]
Hi,
I found something strange when I use OneDrive API to get the file hash value from my OneDrive business account. I can't get the .jpg/.png file hash value after I rename it.

Here are my test steps:
1. Upload abc.jpg and pic.png file.
2. Use OneDrive API ```GET /drive/root/children``` to list my root folder.
    The response contained the hash value of abc.jpg and pic.png. The following are a part of the response I get.
    ```
    {
    "@odata.context": "https://synologydst-my.sharepoint.com/_api/v2.0/$metadata#items",
    "value": [
        {
            "name": "abc.jpg",
            "file": {
                "hashes": {
                    "quickXorHash": "5/QqIlZ35PLc3VNqo/KWX/reZKM="
                }
            },
            "fileSystemInfo": {
                "createdDateTime": "2017-06-16T06:19:56Z",
                "lastModifiedDateTime": "2017-06-16T06:19:56Z"
            },
            "image": {}
            "size": 43872
        },
        {
            "name": "pic.png",
            "file": {
                "hashes": {
                    "quickXorHash": "nElXPeiKegSjj4H0SGaVm6BqHJM="
                }
            },
            "fileSystemInfo": {
                "createdDateTime": "2017-06-16T06:20:04Z",
                "lastModifiedDateTime": "2017-06-16T06:20:04Z"
            },
            "image": {}
            "size": 38242
        }
    } 

3. Rename abc.jpg to test.jpg, and rename pic.png to 123.png.
4. Use OneDrive API ```GET /drive/root/children``` to list my root folder again. However, the "file" field of test.jpg and pic.png is empty.
    ```
    {
    "@odata.context": "https://synologydst-my.sharepoint.com/_api/v2.0/$metadata#items",
    "value": [
        {
            "name": "test.jpg",
            "file": {},
            "fileSystemInfo": {
                "createdDateTime": "2017-06-16T06:19:56Z",
                "lastModifiedDateTime": "2017-06-16T06:21:08Z"
            },
            "image": {}
            "size": 43872
        },
        {
            "name": "123.png",
            "file": {},
            "fileSystemInfo": {
                "createdDateTime": "2017-06-16T06:20:04Z",
                "lastModifiedDateTime": "2017-06-16T06:20:54Z"
            },
            "image": {}
            "size": 38242
        }
    }

Can you help me to deal with this problem? Thanks a lot.

**Comment by ificator** [comment]
I can repro this on my dev machine... very strange! I'll need to drill in to see what's going on.

**Comment by katahir** [comment]
Hi @judithting,
This issue should now be fixed. Thanks for reporting.  I am going to close the thread for now. Please feel free to reactivate if you still see the issue.

**Comment by judithting** [comment]
Hi @katahir and @ificator ,
Thanks for your help. I appreciate your effort.
However, I found that the api cannot return the correct hash value immediately after I rename the file.

I expect to receive it immediately.
Does it mean I need to wait a few seconds until the server updates the hash value?

Here are my test steps:
1. Upload a abc.jpg file to my root folder. (about 100MB)
2. Use OneDrive API `GET /drive/root/children` to list my root folder.
    The response contains the hash value of abc.jpg
3. Use web interface to rename abc.jpg to abc1.jpg
4. Send `GET /drive/root/children` request immediately
    I can get the renamed file info(abc1.jpg), but the response does not contain its hash value.
5. Repeatedly send the api request. 
    After about 15~30 seconds later, the api returns the correct hash value of abc1.jpg.
