### ISSUE TITLE
[ODBxGRAPH] how to auto enable Onedrive Business

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#634]
related to https://github.com/OneDrive/onedrive-api-docs/issues/629

I found that if I want to use Onedrive by graph API.
It need two step after adding a new user at admin center

1. user log-in and initial his onedrive business, and then the onedrive will be provisioned.

2. admin center > users > active user >  choose one user > onedrive setting
 > Access > dbclick Access , now the admin have permission to use the user's onedirve by graph API.

The step 1 seems to be reasonable.
But how about the step 2, is here anyway to auto enable the permission all users?
Or the admin should follow the steps below to enable all users manually?

Thank you for help!

**Comment by katahir** [comment]
Hi @joewutaiwan,
As I mentioned in issue 629, you can use the app-only flow(a.k.a client credential grant flow) to achieve the desired result. App-only tokens are consented to by the tenant admins, and grant access to all drives. You can read more about it here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds

**Comment by joewutaiwan** [comment]
hi @katahir 
thanks for the reply

I successfully get drives and drive ids via app-only flow

However when I use the drive id (which was only provisioned) to request One drive by one drive API
it returns 
```
401
{
    "error": {
        "code": "unauthenticated",
        "message": "The caller is not authenticated."
    }
}
```
I still could not use the drive by one drive API

ps:  The onedrive API (I requested in my resource https://syno*****-my.sharepoint.com)
is seems not support app-only token, I still use in auth code way.

How can I solve this?
Thank you!

**Comment by joewutaiwan** [comment]
[updated]
when I use app-only flow to request Onedrive by graph API
failed at resume upload and download

download http code is 401 and resp. header is
```
Content-Length →0
Date →Wed, 21 Jun 2017 06:05:19 GMT
MicrosoftSharePointTeamServices →16.0.0.6614
P3P →CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
SPRequestGuid →e2b6fd9d-c09b-3000-af7a-b22377a805e0
Server →Microsoft-IIS/10.0
Strict-Transport-Security →max-age=31536000
WWW-Authenticate →Bearer realm="dcb0ac15-0be0-44fe-9662-e578d2178b94",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
X-Content-Type-Options →nosniff
X-FRAME-OPTIONS →SAMEORIGIN
X-MS-InvokeApp →1; RequireReadOnly
X-MSEdge-Ref →Ref A: C875D4DA6F6F42818976CDB85E5B5E8E Ref B: HK2EDGE0114 Ref C: Tue Jun 20 23:05:19 2017 PST
X-Powered-By →ASP.NET
request-id →e2b6fd9d-c09b-3000-af7a-b22377a805e0
x-ms-suspended-features →features=""

```

and in upload the http code is also 401
when I request the GET https://tenant-my.sharepoint.com/alkjl1kjklna
```
{"error_description":"Invalid issuer or signature."}
```

However I can do upload large file by code flow
except the users drive is only provisioned and not accessible by admin
 (encounter "code": "unauthenticated", described below )

Thank you for help..!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
