### ISSUE TITLE
Using custom redirect URI not working in Safari

### ISSUE THREAD

**Issue by afisher88** [OneDrive/onedrive-api-docs#635]
I am using a custom redirect URI implementation of the OneDrive picker API as described in the docs here (v7.2): https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm

This works fine on all browsers apart from Safari, both on desktop in Sierra and iOS (tested in iOS9). In these browsers when the redirect page is hit, the user is not forwarded on and they are stuck on the redirect page with a blank screen. The redirect page is on the same domain.

I assume that Safari is blocking the redirect, although I can't find any other references to similar problems.

**Comment by KevinTCoughlin** [comment]
> I am using a custom redirect URI implementation of the OneDrive picker API as described in the docs here (v7.2): https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm
> 
> This works fine on all browsers apart from Safari, both on desktop in Sierra and iOS (tested in iOS9). In these browsers when the redirect page is hit, the user is not forwarded on and they are stuck on the redirect page with a blank screen. The redirect page is on the same domain.
> 
> I assume that Safari is blocking the redirect, although I can't find any other references to similar problems.

@afisher88 are you still experiencing this in Safari? Is it an incognito window? Are there any console errors throw or network request errors?
