### ISSUE TITLE
openInNewWindow doesn't work

### ISSUE THREAD

**Issue by munhochong** [OneDrive/onedrive-api-docs#636]
I trying to do what you suggested in #583 . But i facing the popup issue. Although i set openInNewWindow to false, when i load the page, it will pop up oneDrive file picker. 

Below is my script - onedrivesdk.html. Thank you.

`

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>

    <meta charset="utf-8" />
    <title></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
    <script type="text/javascript">

       function launchOneDrivePicker() {
            var odOptions = {
                clientId: "93a0xxxxxxx",
                action: "share",
                multiSelect: true,
                openInNewWindow: false,
                advanced: {
                    redirectUri: "http://localhost/onedrivesdkaa.html"
                },
                success: function (files) {
                    for (var i = 0; i < files.value.length; i++) {
                        console.log(files.value[i]);
                    }
                },
                cancel: function () { /* cancel handler */ },
                error: function (e) { /* error handler */ }
            }

            OneDrive.open(odOptions);
        }

        $(document).ready(function () {
            launchOneDrivePicker();
        });
    </script>

</head>
<body>
    
</body>
</html>`

**Comment by daboxu** [comment]
hi @munhochong , we updated the v7.2 picker which we don't support [openInNewWindow](https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm#parameters) option anymore due to Microsoft OAuth restriction on the redirect uri of web app. Would it be possible for you to host the picker SDK at the same domain as the redirect uri?

**Comment by daboxu** [comment]
close for now and feel free to reopen it if the issue consists.

**Comment by Torrichel** [comment]
@daboxu I need to use picker inline my page, how is that possible with new version? Opening new window for picker isn't a solution for me.
