### ISSUE TITLE
Promise being overwritten by SDK

### ISSUE THREAD

**Issue by feesh** [OneDrive/onedrive-api-docs#637]
Hi there!

I'm testing out integrating the [OneDrive JS File Picker SDK](https://js.live.net/v7.2/OneDrive.js) `v7.2` with our web app. Unfortunately, if I import it directly, it apparently overwrites `Promise` and breaks functionality that we have written in already. Do you have any suggestions around this or have plans to fix it? Thanks!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
