### ISSUE TITLE
[GRAPH] app only with one drive API

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#639]
hi all,
In my testing, the onedrive API seems not to be fully supported with graph in  App-only flow
at Download and Upload
refer to: https://github.com/OneDrive/onedrive-api-docs/issues/634
and https://stackoverflow.com/questions/41854365/daemon-app-onedrive-file-download

So if our app wants to do something  App-only (daemon apps)  can do, dealing with all files in all users.
Is this article a solution to achieve?
https://msdn.microsoft.com/en-us/office/office365/howto/building-service-apps-in-office-365

Thank you for help!

**Comment by katahir** [comment]
Hey @joewutaiwan,
App-Only flow is indeed not fully supported with Microsoft Graph. While most scenarios will work, some asynchronous scenarios like copy/session based uploads will not work. So yes, your only option would be to request access to OneDrive resource directly and bypass Graph. 'Files.ReadWrite.All' is an app-only scope for OneDrive api so requesting that will grant you app-only access.

**Comment by joewutaiwan** [comment]
[updated]
Found some good reference for app only with one drive API 
https://stackoverflow.com/questions/42567402/unsupported-app-only-token-when-query-onedrive-for-business
hope this will help
