### ISSUE TITLE
resumable upload response 416 after retry with status code 503

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#64]
I am testing upload large file into Onedrive, e.g. 10G file.

but I suffered a  situation: if I got 503 status code and retry the request, I'll get 416 range erroor with error message: {"error":{"code":"invalidRange","message":"Uploaded fragment overlaps with existing data.","innererror":{"code":"fragmentOverlap"}}}

and during my test, I could not finished uploading 10G file more than 10 times, I'll get 503 error often and 416 error after retry.

please check this and I hope this is not a bug but just my mistake. Thanks!

**Comment by ificator** [comment]
Hi @mikechiu1012, it sounds as though you've obviously undesirable scenario whereby although the PUT for the fragment returned an error it actually succeeded under the covers. We'll dig in to why that occurred, but for now you may find you can work around the issue by, if you get a 416 on a PUT, doing a GET against the upload URL and parsing the "nextExpectedRanges" in the response body. Have a look at http://onedrive.github.io/items/upload_large_files.htm#request-upload-status and see if that will work for you.

**Comment by mikechiu1012** [comment]
hi @ificator, thanks for response, I'll test what you suggest for and I think it might related with https://github.com/OneDrive/onedrive-api-docs/issues/70. cause I use fragment size as 4MB.

I will try and report the latest result here, thanks for help!

**Comment by ificator** [comment]
Hey @mikechiu1012, I just wanted to follow up and see if you were still seeing issues uploading large files.

**Comment by mikechiu1012** [comment]
hi @ificator , since I used 5MB as fragment size, the error response is lesser to be seen.

thanks for ur great help!
