### ISSUE TITLE
[ODB] app only download encounter 401

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#640]
Hi all,

I following these articles and successfully create a app only token for accessing Onedrive for business.
https://msdn.microsoft.com/en-us/office/office365/howto/building-service-apps-in-office-365#to-upload-the-certificate-through-the-manifest-file
https://stackoverflow.com/questions/42567402/unsupported-app-only-token-when-query-onedrive-for-business

Everything works fine except the download request alway returns 401 and following header

```
Content-Length →0
Date →Mon, 26 Jun 2017 06:05:19 GMT
MicrosoftSharePointTeamServices →16.0.0.6614
P3P →CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
SPRequestGuid →df52ff9d-d075-3000-d4fc-d036ecb4d6e4
Server →Microsoft-IIS/10.0
Strict-Transport-Security →max-age=31536000
WWW-Authenticate →Bearer realm="dcb0ac15-0be0-44fe-9662-e578d2178b94",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
X-Content-Type-Options →nosniff
X-FRAME-OPTIONS →SAMEORIGIN
X-MS-InvokeApp →1; RequireReadOnly
X-MSEdge-Ref →Ref A: C98788EB615C4CD2924E47DFAB555034 Ref B: HK2EDGE0818 Ref C: Sun Jun 25 23:05:20 2017 PST
X-Powered-By →ASP.NET
request-id →df52ff9d-d075-3000-d4fc-d036ecb4d6e4
x-ms-suspended-features →features=""
```

I noticed that the header contain RequireReadOnly, but I have granted all permission for this app

![image](https://user-images.githubusercontent.com/12619781/27526704-3970bb0a-5a7a-11e7-915f-7533aba4d314.png)

So where should I modify the APP for downloading files

Or It is a wrong path again

Thank you!

BTW my app-only steps for ODB are 

1. create the x509 cert.
2. create a custom JWT.
3. use JWT to get credential for my resource "https://{my-tenant}-my.sharepoint.com" by urn:ietf:params:oauth:client-assertion-type:jwt-bearer way.

**Comment by joewutaiwan** [comment]
Hi, @ificator 
For now, the problem seems to be solved.
Do you have any update?

thank you...

**Comment by ificator** [comment]
We did make some changes to both download urls as well as session based upload URLs to reduce the overall URL size. It's plausible that this change has resolved your issue.
