### ISSUE TITLE
Create new file?

### ISSUE THREAD

**Issue by feesh** [OneDrive/onedrive-api-docs#642]
I'm interested in programmatically creating new files that open with Office Online using the Graph API — it looks like it might be possible [here](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/driveitem): `createItem`

![image](https://user-images.githubusercontent.com/453474/27665908-0ce94672-5c25-11e7-9f6e-3b6f802e7144.png)

But going to that link only provides information on creating a new folder. Is creating a document not allowed through Graph?

**Comment by katahir** [comment]
Hi @feesh,
It is definitely allowed. You can make a POST to children collection as follows:

POST /drive/root/children
Content-Type: application/json
{
  "name": "FileA.docx",
  "file": { }
}
 
You can also do a PUT to /content api to create a file and add content to it. You can read more about it here:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/item_uploadcontent
