### ISSUE TITLE
MimeType is missing from files in Business Accounts

### ISSUE THREAD

**Issue by mdedys** [OneDrive/onedrive-api-docs#643]
I am using the following api call:

`https://graph.microsoft.com/v1.0/me/drive/root/children`

and it does not return the mimeType of the file. This call works fine for personal accounts.

**Comment by ificator** [comment]
ODB has never returned a `mimeType` value, but it's definitely an inconsistency that we should resolve.

**Comment by DotNetJAlexG** [comment]
> The ODB API has never returned a mimeType value, but it's definitely an inconsistency that we should resolve.

I'm having trouble understanding how such a useful field would be omitted vs plain old OD. Could there be some obscure intentional reason for this?

**Comment by ificator** [comment]
There was no internal reason - SharePoint simply doesn't expose the mimetype value directly. We've made a change to the API to derive it from the file extension, and it should be live now. Please let us know if you see anything unexpected for your scenarios.
