### ISSUE TITLE
[ODB] delta API can not detect onenote file detail change

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#646]
Although the delta API can detect the change of onenote file
but the changed name was not presented correctly.

For example, If I change the section name of a onenote file, 
the event I get from delta API was still the old name.

Is this the limitation? Or I have to get correct detail information only by onenote API?

Thank you!

**Comment by ificator** [comment]
Hi @joewutaiwan, I apologize of the delay. Can you tell me whether you're hitting a business or consumer account? I have the same expectation as you - if you renamed the file that represents a section and then called delta I would expect to see the NEW name appear in the delta response.

**Comment by joewutaiwan** [comment]
Hi @ificator 

Thanks,

1.I am hitting a business account.
2.The delta API still failed to detect the section change
3.There is no way to rename the file that represents a section, I only can operate that as a one note package on web

**Comment by ificator** [comment]
I just tried to get my own repro:
1. Created a OneNote with a section called "Test Section"
2. Got a current delta token
3. Renamed the section to "Renamed Section" in the OneNote client
4. Used the delta token from step 2 to get changes

The response came back and said the name of the modified section was "Renamed Section". Did you follow different steps to get the behavior you're seeing?

**Comment by joewutaiwan** [comment]
Hi @ificator :

I did what you exactly do.
But I create the OneNote at Onedrive online by right-click -> New -> One note
And the section keeps its created name, Untitled Section.one, when I request delta API.
Even I created a new section in this Note, the behavior is the same.

Thanks!

**Comment by ificator** [comment]
Hey @joewutaiwan,

So I finally have an answer for you on this front.

The API is doing exactly what it's meant to do, as in reality when you rename a section using the web OneNote client it doesn't actually rename the file. It appears as though it changes state within the section file, but not the name of the section file itself. This is not the case for the rich client, which will rename the file as well, and the rich client will actually "fix" the naming inconsistency created by the web client if it sees the names are out of sync.

I cannot explain why the web client doesn't actually rename the file - hopefully they're planning on fixing that at some point, but for now there's nothing either of us can do :(.
