### ISSUE TITLE
OD4B access token restrictions based on IP/client?

### ISSUE THREAD

**Issue by amagliul** [OneDrive/onedrive-api-docs#648]
Hello OneDrive Team.

I am hitting a scenario I have not seen before and I'm wondering if it has to do with specific OneDrive for Business domain/tenant policies in place.

We centralize the generation of access tokens and then pass the access token to an authenticated user for use on their client(s) (instead of holding a refresh token on each client). I am seeing for this particular user account that the access token can only be used by the system that requested it. If the access token is used by another client, OneDrive returns a 401 error.

It looks like the access token is being restricted by IP or client, but I can't find any documentation that states such a feature exists. Could there be another reason this is happening?

All other OD4B user accounts do not encounter this scenario.

Thanks!

**Comment by chackman** [comment]
Sorry about this very old issue going stale. If this is still reproducing, could you please provide updated request & response information to help us investigate further? Thanks.
