### ISSUE TITLE
OData 4 - Filtering search results using UTF8 characters

### ISSUE THREAD

**Issue by waiyan1612** [OneDrive/onedrive-api-docs#649]
This is a crosspost from [StackOverflow](https://stackoverflow.com/questions/44964321/onedrive-odata-4-filtering-search-results-using-utf8-characters) since it is not getting attention over there.

I am trying to filter the search contents from OneDrive Search API. This is the request without the filter where the original query keyword is 中英字典 whose UTF-8 encoded value is 
`%25E4%25B8%25AD%25E8%258B%25B1%25E5%25AD%2597%25E5%2585%25B8`

The request without the filter is like this.

> https://api.onedrive.com/v1.0/drive/root:%2F:/view.search?q=%25E4%25B8%25AD%25E8%258B%25B1%25E5%25AD%2597%25E5%2585%25B8&access_token=$access_token

The use case is to find the matching `keyword` in the name so I need to add a filter like `filter=contains(name,'$keyword')`.

The corresponding request with the filter is

> https://api.onedrive.com/v1.0/drive/root:%2F:/view.search?q=%25E4%25B8%25AD%25E8%258B%25B1%25E5%25AD%2597%25E5%2585%25B8&filter=contains%28name%2C%27%255Cu4E2D%255Cu82F1%255Cu5B57%255Cu5178%27%29&access_token=$access_token

The first request will give me the correct results for both ascii and non-ascii characters, but the second one gives me the correct results only for ascii characters and does not work for url-encoded UTF-8 characters (only returns empty results).

I have tried encodings from this post as well but they also do not work.

Is this a bug from OneDrive or am I using a wrong type of encoding for `$filter`?

**Comment by ificator** [comment]
One thing that jumps out is the UTF8 value seems to be double encoded - I'd expect `中英字典` to be encoded as `%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%85%B8`. I'd also expect the encoded `contains` value to either be UTF-8 (e.g. `%E4%B8%AD%E8%8B%B1`) or UTF-16 (e.g. `%u4e2d%u82f2`) where as yours seems to be a of the form `\uABCD` after decoding.

Having said all that, I still cannot get the filtering to work when I play with it locally so it may be that the OData framework has some issues around Unicode values in such a filter. I'll need to try and drill into their code to figure out what's going on.

**Comment by ificator** [comment]
This issue should now be resolved! Please let us know if you continue to see issues.
