### ISSUE TITLE
resumable upload : unclear error :  400 - badArgument :  which argument ?  

### ISSUE THREAD

**Issue by svvbe** [OneDrive/onedrive-api-docs#65]
I got simple upload working fine.
However, when trying resumable upload, I get

OD 02 apr 16:10:20 INFO  - Uploading 246916159 bytes to https://api.onedrive.com/v1.0/drive/root:/verylargezip.zip:/upload.createSession
OD 02 apr 16:10:22 INFO  - Uploading next chunk 0-10485759/246916159 towards https://api.onedrive.com/up/eyJSZXNvdXJjZUlEIjpudWxsLCJSZWxhdGlvbnNoaXBOYW1 and so on
OD 02 apr 16:10:22 INFO  - Wrote bytes on OutputStream: 10485760
OD 02 apr 16:20:05 INFO  - Status  : 400
OD 02 apr 16:20:05 INFO  - {"error":{"code":"invalidArgument","message":"Bad Argument","innererror":{"code":"badArgument"}}}

I have the following headers in my Http-PUT: Authorization,Content-Type/Content-Length/Content-Range,
all filled with reasonable values:
{Authorization=[bearer EwC and so on], Content-Length=[10485760], Content-Range=[0-10485759/246916159], Content-Type=[application/octet-stream]}

It would help if the response would be more specific
which argument is bad ? which argument is missing (assuming it is not a bug?)

Thanks.

PS: for the doc: 
in the section "download a OneDrive Item contents",
it is stated the download url can be found in the response under Location
Seems it is not Location, but Content-Location

**Comment by ificator** [comment]
Hi @svvbe, this is definitely an area we need to work on. If you run in to the issue again could you dump out all of the HTTP headers that came with the response and provide them here?

**Comment by svvbe** [comment]
See HTTP headers at the end:

OD 07 apr 08:53:43 INFO  - Uploading 246916159 bytes to https://api.onedrive.com/v1.0/drive/root:/verylargezip.zip:/upload.createSession
OD 07 apr 08:53:48 INFO  - Uploading next chunk 0-10485759/246916159 towards https://api.onedrive.com/up/eyJSZXNvdXJjZUlEIjpudWxsLCJSZW...
OD 07 apr 08:53:48 INFO  - Wrote bytes on OutputStream: 10485760
OD 07 apr 08:55:10 INFO  -   
OD 07 apr 08:55:10 INFO  - Status  : 400
OD 07 apr 08:55:10 INFO  -  
OD 07 apr 08:55:10 INFO  - {"error":{"code":"invalidArgument","message":"Bad Argument","innererror":{"code":"badArgument"}}}
OD 07 apr 08:57:51 INFO  -  
OD 07 apr 08:57:54 ERROR - HTTP headers:
OD 07 apr 08:57:55 ERROR - X-QosStats  {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
OD 07 apr 08:57:58 ERROR - Date  Tue, 07 Apr 2015 06:55:11 GMT
OD 07 apr 08:58:00 ERROR - X-MSNSERVER  DM2301____PAP129
OD 07 apr 08:58:02 ERROR - X-ThrowSite  3f0c.e6a6
OD 07 apr 08:58:04 ERROR - P3P  CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
OD 07 apr 08:58:06 ERROR - Content-Length  97
OD 07 apr 08:58:06 ERROR - X-AsmVersion  UNKNOWN; 19.17.0.0
OD 07 apr 08:58:06 ERROR - Content-Type  application/json; charset=utf-8
OD 07 apr 08:58:06 ERROR - Server  Microsoft-HTTPAPI/2.0
OD 07 apr 08:58:06 ERROR - Problem uploading file (resumable upload)

**Comment by ificator** [comment]
The error appears to be related to the Content-Range header. I'll make sure we expose something more meaningful for that scenario, but in the mean time can you confirm the value you're providing is of the form:

Content-Range: bytes <start>-<end>/<totallength>

Your original comment mentioned "Content-Range=[0-10485759/246916159]", in which case the answer may simple be to add the "bytes" (See http://onedrive.github.io/items/upload_large_files.htm#upload-fragments and http://tools.ietf.org/html/rfc7233#section-4.2)

**Comment by svvbe** [comment]
Thanks Brad. Indeed, my mistake. I added "bytes" to the Content-Range header and now I get already better behaviour. 
I do not get back the nextExpectedRanges in the response json, but I will try to work around that.
Thanks for now.

**Comment by ificator** [comment]
No problem!

Regarding "nextExpectedRanges" - that's a known issue being tracked with https://github.com/OneDrive/onedrive-api-docs/issues/14. We should have the fix out soon.
