### ISSUE TITLE
Sharepoint API call to get all Documents

### ISSUE THREAD

**Issue by anildbest83** [OneDrive/onedrive-api-docs#651]
Hi @ificator 

I need you help in understanding SharePoint

When i logged in to Office 365 with my business account, i see Sites Links there, some sites which my organisation shared with me. 

When i click on Site link it shows "Document Library" and "Document sharing" links on left.

Click on "Document Library" it takes me to

https://myorganisation.sharepoint.com/Document Library/Forms/AllItems.aspx

And Click on "Document sharing" it takes me to

https://myorganisation.sharepoint.com/Documents sharing/Forms/AllItems.aspx

The API call i m using to get shared documents is following
/_api/web/getFolderByServerRelativeUrl('/Shared%20Documents')

but the Documents above call return does not contain any document from  "Document Library" and "Document sharing".

So do i need to make a separate call to get "Document Library" and "Document sharing" docs?
OR 
Is there a common API call to get all Documents?

Please advice

**Comment by ificator** [comment]
Generally speaking, document libraries are treated as the scope of both the old (what you're referencing via _api/web) and the new (via _api/v2.0), and so when you make such a query you're only going to be getting back items within the specific document library. The only other option I can think of would be to drive and use search to find all the documents that are shared with you, but search is by definition not enumeration and so it won't have the same correctness guarantees.
