### ISSUE TITLE
HTTP/1.1 403 Forbidden when downloading zip file from Onedrive Personal

### ISSUE THREAD

**Issue by kotsak** [OneDrive/onedrive-api-docs#653]
Hi,

We have a user who receives this error when downloading various zip files from his Onedrive Personal storage using our application.
```

HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Server: Microsoft-IIS/10.0
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-MSNSERVER: BN2BAPA4B1D52C7
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-MSDAVEXT_Error: 9830409
X-Virus-Infected: ScanError
X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
X-ThrowSite: 1e99.cd8a
X-Retry-After: Id=*,Duration=281
X-ClientErrorCode: VirusError
X-AsmVersion: UNKNOWN; 19.71.608.4009
X-MSEdge-Ref: Ref A: FC01E3F7CE024A7C9058A83E9546649E Ref B: TPE30EDGE0121 Ref C: Thu Jun 29 15:01:39 2017 PST
Date: Thu, 29 Jun 2017 22:01:39 GMT
Content-Length: 0
```

I've read about a parameter named AVOverride we can use to override those virus scans during downloads but is there a place where this parameter is officially documented?

Thanks,
KT

**Comment by kotsak** [comment]
Hi again,

Any update on this?

Thanks,
KT

**Comment by ificator** [comment]
I was just looking at this one today - I assume you still see the issue? Is it only for a particular zip file?

**Comment by kotsak** [comment]
We haven't heard from the user since then so I can't confirm if he is still receiving the error, but at that time it was involving multiple zip files.

Regarding my original question, is the AVOverride parameter still valid and available for use if needed?

Thanks,
KT

**Comment by ificator** [comment]
That parameter was never documented, and so we cannot comment on its purpose. It likely will not help you in this case though.

I did make a change to the system to not block downloads on "scan errors" though, which should hopefully stop this kind of thing happening again.

**Comment by kotsak** [comment]
Thanks for the update and the fix.

**Comment by ificator** [comment]
This should now be deployed. Please let us know if you continue to see issues.
