### ISSUE TITLE
[ODB] Is any way to use Onedrive API at China?

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#654]
I registered APP at **Azure China.**
However, there is no option to enable share point API  when I set app permissions.

Second, the graph API also has no option to enable read-write file in app-only permission.

How can I get started with this?

thanks for help

**Comment by ificator** [comment]
Hi @joewutaiwan I'm going through old issues trying to figure out what to do with them - are you still having issues here or did you figure it out?

**Comment by joewutaiwan** [comment]
@ificator 

Yes, we should buy an office365 china

https://www.microsoft.com/china/office365/signup.html

That kind of  account has full support for SharePoint online API and exchange online API

**Comment by ificator** [comment]
Thanks @joewutaiwan! Since you figured it out I'll close this issue.
