### ISSUE TITLE
LocationFacet incorrect/Onedrive returning incorrect result

### ISSUE THREAD

**Issue by Thalhammer** [OneDrive/onedrive-api-docs#656]
Today I noticed a bug in many of my applications which use onedrive quite a lot.
My code failed because some time ago onedrive started to return properties different from those listed [here](https://github.com/OneDrive/onedrive-api-docs/blob/master/facets/location_facet.md). This caused errors inside my parser logic because it expected a result like this (the way it is documented), which was returned until now.
`{
  "altitude": 760.0,
  "latitude": 122.1232,
  "longitude": 34.0012
}`

But now the location facet returned looks like this:
`{
  "address": {}
}`

This is not a big deal and was easy to fix, but I think the documentation should get updated accordingly.

**Comment by ificator** [comment]
Hi @Thalhammer, the `address` property should be an addition to the `location` facet and so I'd expect the other properties to still be present. Are you not seeing `altitude`, `latitude`, and `longitude` coming back at all? I assume you're hitting the Consumer endpoint, but if you can confirm that it would be useful as well.

**Comment by Thalhammer** [comment]
No, I don't see altitude, latitude or longitude returned if the location facet is present.
My client builds up a local database containing all items in my onedrive using the delta method, so I did a quick search inside the facets.
Out of the 63105 items inside my Onedrive, 858 contained a facet of type location and all of those 858 had exactly the same value: `{"address":{}}`
I don't have any items containing latitude, longitude or altitude.
However, I could not check if they were there in the past because if the location facet does not exist at all it is fine and I did not use location information anywhere (which is the reason it was so easy to fix).
Yes, I'm using the consumer endpoint ("https://api.onedrive.com/v1.0").

So in the past those items either returned no location facet at all, or one including `altitude`, `latitude` and `longitude`.

**Comment by ificator** [comment]
Apparently there is a bug where a location facet of the form `{"address":{}}` will be returned for items that do NOT have any location data, but if there are actual lat/long values those should be present. It seems like that will explain what you're seeing so I'll flag this as a bug so we can let you know when it's resolved.

**Comment by zachzi** [comment]
The fix for this has been deployed and looks to be working.
