### ISSUE TITLE
OneDriveError: invalidRequest - ObjectHandle is Invalid

### ISSUE THREAD

**Issue by app5000** [OneDrive/onedrive-api-docs#657]
Hello:
I have been using: item = client.item(drive='me',id=fileid).request().get() to get file created time and modified time in python.  A few days ago, I was still able to get the created time although I could not get the modified time from onedrive. Here is my code:

created = item.created_date_time and modified = item.last_modified_date_time

But yesterday, I started getting the OneDriveError: invalidRequest - ObjectHandle is Invalid on the item=xxx line.  What am I doing wrong?  Has something changed on Onedrive?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
