### ISSUE TITLE
Need help with upload

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#659]
Hi There,
I'm trying to upload a file (image or any other type) with the REST api end point and look like the file got corrupted after being uploaded to the server even it was successfully uploaded. 
example upload url:
PUT https://api.onedrive.com/v1.0/drive/items/90C80432FA7813FC!3743:/mytest.jpg:/content 
Is there any special header that I should include before sending the request , please help.

Thanks in advance.

Phuong

**Comment by ificator** [comment]
What does the body of the request contain? Are you doing something like base64 encoding it first? OneDrive will persist EXACTLY what you give it (ignoring gzip scenarios) so I'd start by confirming what you're pushing up is what you expect.

**Comment by neunygph** [comment]
Hi, I'm trying to upload images and sending the raw binary data. Does it has to be encoded into base64 or it's just optional ?

What about other type such as .docx, .txt, .PDF and such ?

Thanks

Phuong Nguyen

________________________________

**Comment by ificator** [comment]
I called out Base64 because we've seen people do that in the past by accident. Our service will persist the literal Base64 data if that's what you give us, which is more than likely NOT what you want. So DO NOT provide us with Base64 :)

As long as you provide the service with the raw bytes of the file it should be fine. This applies to all file types.

**Comment by neunygph** [comment]
Hi,

I have tried sending the binary raw data but not sure why it's still not working. Below is an example of how I send the data:
        var xhr = new XMLHttpRequest();
        var reader = new FileReader();
        
        xhr.open("PUT", uri, true);
        xhr.setRequestHeader('accept','application/json');
        xhr.setRequestHeader('authorization','Bearer ' + token);
        xhr.setRequestHeader('prefer', 'respond-async');
        xhr.setRequestHeader('content-type', 'application/x-www-form-urlencoded');
        
        reader.onload = function(evt) {
            xhr.send(evt.target.result);
        };
        reader.readAsDataURL(file);
My files were successfully uploaded with the above code, but they can't be open on onedrive or even when I downloaded them. Is there a required custom header that I should be aware of ?

Thanks,

**Comment by ificator** [comment]
Without seeing the request that's sent it's hard to say, but the fact that the `content-type` is `application/x-www-form-urlencoded` seems weird.

**Comment by neunygph** [comment]
Hi,

I tried to upload my image from Google drive with the Url method and my file still got corrupted after it got uploaded. This should has nothing to do with my setting since the file is directly downloaded from one drive. Below is the example url which my image is corrupted.
{
 "@content.sourceUrl":"https://drive.google.com/ucid=0B8M0g7s0hlJmelNTOEY4M1czS2c&export=download",
  "name": "test.jpg",
  "file": { }
}
I found that it only work when the url contains a file extension, for instance
This got corrupted : https://drive.google.com/ucid=0B8M0g7s0hlJmelNTOEY4M1czS2c&export=download
This is good: https://mydomain.com/test.jpg
Please advice if this is the expected behavior.
Thanks,

**Comment by ificator** [comment]
Hi @neunygph did you ever figure out what's going on here?

**Comment by michwii** [comment]
Hi guys, 
I have the same issue.

Can anyone reopen the case ?
