### ISSUE TITLE
CORS support in OneDrive API

### ISSUE THREAD

**Issue by yegodz** [OneDrive/onedrive-api-docs#66]
hello
I'm developing a single page app that makes XMLHttp requests to retrieve files from oneDrive.

According to the oneDrive API site http://onedrive.github.io CORS is supported.

Indeed, I can accomplish Oauth 2.0 authentication using both token flow and code flow AND I am able to retrieve file metadata and upload file content successfully. In all these operations, api.onedrive.com responds with the correct `Access-Control-Allow-Origin` in the header.

HOWEVER, when I try to _download_ a file by fetching the file metadata and then trying to send a GET request to the `@content.downloadUrl` link, I get a CORS error. It seems that the content site `1drv.com` does not support the CORS  `Access-Control-Allow-Origin` header.

Is there some setting missing or is COR support exclusive of downloads?

**Comment by rgregg** [comment]
Hi @yegodz. We've noticed this as well and are working on a fix. Obviously there are important use cases for being able to download a file that should work for JavaScript apps as well.

**Comment by ificator** [comment]
Hi @yegodz, I believe this has been fixed now. Can you confirm you're seeing the behavior you expect?

**Comment by yegodz** [comment]
Hello @ificator 
I did check the code today and it seems to be working fine.
Thanks very much for getting this fixed!

**Comment by ificator** [comment]
You're welcome!

**Comment by yegodz** [comment]
Hi  - this is not really related to this issue, but how do I get my app listed on the https://dev.onedrive.com/index.htm# <https://dev.onedrive.com/index.htm#> page at the bottom where it lists
“Apps that work with OneDrive” ?
I can’t find any place in the API signup where we can register the app to have it listed.
Thanks!
--
Ruchir Godura
ruchir@cerient.com
Founder, Cerient Technology, LLC. 

Keep your cloud data private at http://www.xooui.com <http://www.xooui.com/>
