### ISSUE TITLE
Upload from URL

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#660]
1. Is conflict behavior query string( @content.conflictBehavior) supported for uploading from URL ? It did not work for me when I tried it but just wondering if I did something wrong or it's not supported.

2. Also, with the body content example from the official page, what should be the value for "file" member if it's not empty ?
{
  "@microsoft.graph.sourceUrl": "http://wscont2.apps.microsoft.com/winstore/1x/e33e38d9-d138-42a1-b252-27da1924ca87/Screenshot.225037.100000.jpg",
  "name": "halo-screenshot.jpg",
  "file": { }
}

Thanks,

**Comment by ificator** [comment]
1. Conflict behavior is supported, but it's expected to be an annotation in the request body. The only scenario that really accepts the value as a query string parameter is a PUT to /content since the body in this case is file content and not metadata

2. You'll want to only provide an empty file facet as an hint to the service that the item being created is a file. The values within the facet will be populated by the service when the file is created

**Comment by neunygph** [comment]
1.Do you have an example of the json body that includes an annotation that support the conflict behavior ?

2. Look like object url is not support or can't be downloaded on Onedrive server. I tried something like below, got 202 status from the request. but the file never got uploaded.
{
  "@content.sourceUrl": "blob:https://mydomain.com/778e824f-62ed-4ad8-a874-bab98ab476e6",
  "name": "testme.png",
  "file": { }
}

Thanks,

**Comment by ificator** [comment]
1. It would look something like:

```
{
  "@content.sourceUrl": "blob:https://mydomain.com/778e824f-62ed-4ad8-a874-bab98ab476e6",
  "@name.conflictBehavior": "rename",
  "name": "testme.png",
  "file": { }
}
```

2. The response that returns the 202 should also contain a `Location` header. You can use that URL to query for the status of the upload, and see any errors that were encountered. If the URL you mentioned is the one you tried, my guess is that the `blob:` prefix is breaking things.

**Comment by neunygph** [comment]
I tried both "@name.conflictBehavior": "rename" and  "@content.conflictBehavior": "rename", but not working :)

**Comment by neunygph** [comment]
Is there a usage limit with upload from URL since all the uploading cost (bandwidth, downloading data..etc) will be on Microsoft ?

**Comment by ificator** [comment]
My apologies, I didn't realise you're making the calls through graph. If you use `"@microsoft.graph.conflictBehavior": "rename"` does that work?

**Comment by neunygph** [comment]
Sorry I did not see your response until now, I tried again with @name.conflictBehavior and it worked :).

Thank you very much.
