### ISSUE TITLE
Shared With Me: Graph APIs or OneDrive Business APIs

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#661]
Is shared With Me should be access using graph access token or onedrive business access token.

Since after providing proper permission from azure portal, we are getting 404 error.

Any documentation available.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
