### ISSUE TITLE
Graph Api query for mySite returns null

### ISSUE THREAD

**Issue by sbukhtiyarov** [OneDrive/onedrive-api-docs#662]
Hello!
Could you help me with mySite url?
In which cases can the request  'https://graph.microsoft.com/v1.0/me?$select=mysite' return null?

Test call, using Graph Explorer

https://graph.microsoft.com/v1.0/me?$select=mysite

```
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Cache-Control: private
client-request-id: 2156d592-740f-4d54-932d-1fcc081e7e61
request-id: 2156d592-740f-4d54-932d-1fcc081e7e61

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(mySite)/$entity",
    "mySite": null
}
```

**Comment by ificator** [comment]
Does the user have a mysite? Does `/me/drive` work?

**Comment by verybada** [comment]
Hi @ificator ,

What do you mean about 'mysite'? I have a business account which was able to acquire $mySite but it is facing the same issue recently.

**Comment by ificator** [comment]
For the scenario where you fail to get the `mySite` value can you list out the permissions that were allocated to the session? I wonder if something is lacking that results in the `mySite` value being excluded even when requested.
