### ISSUE TITLE
Graph API returning different thumbnails sizes [OneDrive Business only]

### ISSUE THREAD

**Issue by The-Lion** [OneDrive/onedrive-api-docs#664]
I just came across the following issue when using the Graph API to access an **OneDrive Business** account.  

I want to know the thumbnail sizes of images inside a folder. So I execute the following call:
`https://graph.microsoft.com/v1.0/me/drive/items/{ID-FOLDER}?expand=children(expand=thumbnails)`

In this call, the thumbnail sizes for an image inside the folder are returned like this:
```
"thumbnails": [
    {
        "id": "0",
        "large": {
            "height": 800,
            "url": "...&width=800&height=800",
            "width": 800
        },
        "medium": {
            "height": 176,
            "url": "...&width=176&height=176",
            "width": 176
        },
        "small": {
            "height": 96,
            "url": "...&width=96&height=96",
            "width": 96
        }
    }
]
```
In this response the heights and widths don't correspond with the actual thumbnail size as only the longest edge has that size since the thumbnail isn't cropped. 

However, when I list the thumbnails of the image directly via:

`https://graph.microsoft.com/v1.0/me/drive/items/{ID-FILE}/thumbnails`
OR
`https://graph.microsoft.com/v1.0/me/drive/items/{ID-FILE}?expand=thumbnails`

The response for the thumbnails looks quite different:
```
"thumbnails": [
     {
         "id": "0",
         "large": {
             "height": 500,
             "url": "....&width=800&height=800",
             "width": 750
         },
         "medium": {
             "height": 200,
             "url": "...&width=176&height=176",
             "width": 300
         },
         "small": {
             "height": 200,
             "url": "...&width=96&height=96",
             "width": 300
         }
     }
 ]
```

While the dimensions now have the right ratio (which is perfect for my case), the actual thumbnails still have a different dimension.

The issue is **not present** when doing the same calls to an **OneDrive Personal** account. In that case the API returns the exact sizes of the thumbnails.

Is this the expected behavior or a bug? If it is the expected behavior, could explain to me how I should interpret the different results?

**Comment by ificator** [comment]
Part of it is unfortunately expected - for some reasons I won't delve into we cannot provide the actual dimensions during enumeration and so can only provide the estimates. When you fetch the URLs for those you'll get back an image that is sized appropriately. There is work ongoing to improve this situation as it's obviously far from ideal.

The part that is unexpected is the fact that, as an example, `small` is reported as being `300x200` but the URL is passing through `96x96`. I'll mark this as a bug due to that.

**Comment by The-Lion** [comment]
@ificator thanks for your clear response and I am glad to hear that you are aware of this issue and on track to improve this. It would be great if we can get an idea of the image dimensions or image aspect ratios when enumerating items on Business accounts as well!

**Comment by ificator** [comment]
We've made some improvements here that should help:
1. We now attempt to estimate what dimensions will result after the scaling has been applied.
2. We will now return dimension data during enumeration if we have the data available at that time.
