### ISSUE TITLE
OneDrive for business - create file fails(UnauthorizedAccessException) for AppOnly accessToken

### ISSUE THREAD

**Issue by brucewangkorea** [OneDrive/onedrive-api-docs#665]
Hi,

I got the Access token by using following method.
https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service

By calling the Microsoft Graph API, I can list up files of every user in tenant, download them, and even can create a folder.
but I can not create file, the response is
"{"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":"Access denied. You do not have permission to perform this action or access this resource."}}"

The Azure app has all the permissions enabled, and If I get the AccessToken by going thru the Web Login based way, everything works (of course with some collection admin related configuration).

Can you check on this?

Thanks in advance.

**Comment by ificator** [comment]
Unfortunately any ability to write using application permissions currently has [limited support](https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference#application-permissions-5). We're hopefully not far off adding official support, but we aren't there yet.

**Comment by ificator** [comment]
At long last we believe session based uploads should work via MS Graph for app-only scenarios. If you're still having issues please let us know.
