### ISSUE TITLE
Files created using onedrive interface are not copied (root to root)

### ISSUE THREAD

**Issue by danpecher** [OneDrive/onedrive-api-docs#666]
I'm successfully using the API to copy files that I manually uploaded. However there is one specific scenario where copying doesn't work: when I try to copy a Word, Excel or PowerPoint document that I had previously created in onedrive interface **from root folder to root folder with different name**, the API returns successful response with a link to monitor but when I follow that link, response looks like this:
```
{
"operation": "ItemCopy",
"percentageComplete": 0,
"status": "failed",
"statusDescription": "Completed 0/0 files; 0/9314 bytes"
}
```
All other scenarios work (copying from root to subfolder and the other way around, copying simple txt file or onenote document from root to root, etc. - everything ok).

Sample request:
`POST https://graph.microsoft.com/v1.0/drive/items/root:/DocumentCreatedInsideOnedrive.docx:/copy`
Request body:
```
{
  "parentReference": {
    "path": "/drive/root"
  },
  "name": "DocumentCreatedInsideOnedrive_copy.docx"
}
```
Response is `202 Accepted` with Location header pointing to the failed status mentioned above.

**Comment by ificator** [comment]
Hi @danpecher - can you confirm that you're accessing a consumer OneDrive when you're seeing this?

**Comment by danpecher** [comment]
Yes, it's my basic personal account.

**Comment by ificator** [comment]
I am able to repro this - thanks for reporting @danpecher!

**Comment by ificator** [comment]
This should hopefully be resolved now - please let us know if you still see issues.
