### ISSUE TITLE
Upload api success but not return some metadata.

### ISSUE THREAD

**Issue by codezjx** [OneDrive/onedrive-api-docs#669]
I follow the topic here: https://dev.onedrive.com/items/upload_put.htm, and execute a simple item upload like:

# Request:
Request URL:https://api.onedrive.com/v1.0/drive/items/root/children/generics2.png/content?@name.conflictBehavior=rename
Request Method:PUT
**Request Headers**
Authorization:bearer my_token
Content-Type:image/png

# Response:
HTTP/1.1 201 Created
Content-Type: application/json
{
  "id": "1C6546CD87472073!348",
  "name": "generics2.png",
  "size": 10191,
  "file": { }
  ...
}

Everything works fine but the response metadata was missing something, just like `"image":{"height":287,"width":765}`  and `"photo":{"takenDateTime":"2017-05-23T07:19:16.957Z"}`.

So, I execute a get item request and try to get the correct metadata:

# Request
Request URL:https://api.onedrive.com/v1.0/drive/items/1C6546CD87472073!348
Request Method:GET
**Request Headers**
Authorization:bearer my_token

But it also didn't return `image` and `photo` tag, similar situation in mp3 file and didn't return `audio` tag.

After a long try, I found that if we delay a period(about few seconds) before execute the get item request, it works and return the correct `image` and `photo` tag. So, my question is: How can I fix this issue? Is there OneDrive server need some time to processing image data？

Looking forward to your reply! Thanks!

**Comment by ificator** [comment]
This is actually by design - in order to ensure uploads complete as fast as possible the process that extracts image metadata is run asynchronously. As a result, it can take a few seconds for the associated metadata to appear.
