### ISSUE TITLE
Unable to create upload session to special folder paths

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#67]
This issue occurs whether my program has either the onedrive.appfolder or onedrive.readwrite permission scope.

I am able to upload a file by doing a PUT request with the regular simple item content method.
```
https://api.onedrive.com/v1.0/drive/special/approot:/filename:/content
```
However, when I try to start a resumable upload session, I get a 500 error. I'm doing a POST request for this.
```
https://api.onedrive.com/v1.0/drive/special/approot:/filename:/upload.createSession
```
```
Error: {
  "error": {
    "code": "generalException",
    "message": "General Exception While Processing"
  }
}
```
As a workaround, it appears I can create a session from the full path name of the folder, even if I have just the onedrive.appfolder permission:
```
https://api.onedrive.com/v1.0/drive/root:/Apps/AppName/filename:/upload.createSession
```
According to the [Special Folders](http://onedrive.github.io/items/special_folders.htm) page, you should be able to use any API call with Special Folders.

I tried it with the Camera Roll special folder (with readwrite permission scope) and got the same error.

**Comment by ificator** [comment]
Thank for reporting this @Lyrrad! This is definitely an issue - we'll get it fixed ASAP.

**Comment by ificator** [comment]
Hi @Lyrrad, I believe this has now been resolved. Please let us know if you continue to see issues.
