### ISSUE TITLE
Range downloads, first chunk

### ISSUE THREAD

**Issue by kvmorozov** [OneDrive/onedrive-api-docs#670]
# Request
/v1.0/drive/items/{item-id}/content

Headers:
Range: bytes=0-1023

# Expected
HTTP 206, content length = 1024

# Actually
Http 200, content length = {total length}
If I send Range: bytes=1-1023, it's working well, but without first byte.

**Comment by ificator** [comment]
Hi @kvmorozov, can you tell me if you're hitting a consumer or business account? Can you also confirm that you're applying the `Range` header when you follow the redirect (I assume this is the case if `1-1023` worked)?

**Comment by kvmorozov** [comment]
Hello @ificator I have a consumer account, and testing via my own application and REST API tool by direct URL and setting headers.

**Comment by ificator** [comment]
Hi @kvmorozov I was unable to reproduce this issue. Do you notice any pattern when it happens (such as only for files that are a specific size) or does it happen all of the time for you?
