### ISSUE TITLE
{} in URL are not being encoded

### ISSUE THREAD

**Issue by vishesh04** [OneDrive/onedrive-api-docs#671]
OneDrive file picker 7.2 opens following URL in popup

<domain url>?oauth={"clientId":"xxxxxxxxxxxxxxx","endpoint":1,...}

The curly braces in URL are not encoded so it is rejected by my haproxy backend on ubuntu throwing a 400 error. When I tried encoding it myself by adding `url = encodeURI(url)` on line 1737 in `OneDrive.debug.js`, url encoding issue is resolved and popup redirects to OAuth and list files.

However, ~~any~~ this change in `OneDrive.debug.js` results in sidebar disappearing from popup. Open and Cancel button stop working - showing "This file can't be shared. please try again"

**Comment by vishesh04** [comment]
Turns out, issue was some params being encoded twice. i resolved is by only encoding {} in URL.
Line 1744: 
`url = url.replace('{', '%7B').replace('}', '%7D')`

**Comment by daboxu** [comment]
@vishesh04 thanks for reporting that, I will add a fix for it.

**Comment by daboxu** [comment]
@vishesh04 it should be fixed, could you verify it works for you?

**Comment by daboxu** [comment]
closed it for now as it should be fixed. Feel free to reopen it if the issue still exists.
