### ISSUE TITLE
How to use OneDrive API with endless access token - node.js

### ISSUE THREAD

**Issue by arenacheck** [OneDrive/onedrive-api-docs#672]
I tried now since several days to get unlimited access token or a way to refresh it or whatever. I cant find any sample codes. I can upload files an other stuff with the 60min access token from the auth page. But I need a way that I don´t need to enter always a new access token. Please help me guys and send me working sample codes for node.js

I also created post on stackoverflow.
https://stackoverflow.com/questions/45404855/onedrive-code-flow-public-clients-cant-send-a-client-secret-node-js
 We can write there if you want. Thank you

**Comment by arenacheck** [comment]
problem was solved. The onedrive docs told to use http://localhost but in my case I use XAMPP and always get redirected to http://localhost/dashboard so that I can´t the generated code in the url. I used redirect url http://localhost/dashboard and it works thank you

**Comment by ificator** [comment]
Thanks for updating with your solution @arenacheck - hopefully it will help other people in the future!
