### ISSUE TITLE
offline_access with FilePicker

### ISSUE THREAD

**Issue by exp0nge** [OneDrive/onedrive-api-docs#673]
Hello,

Since offline_access is not allowed through implicit grants, does that mean that the user would need to first authorize the application (`response_type=code`) then they can use the FilePicker?

**Comment by daboxu** [comment]
hi @exp0nge are you using the JS FilePicker or a native app like iOS/Android?

**Comment by exp0nge** [comment]
@daboxu I used the JS file picker. I ended up using the oauth interface then showing the file picker. I'm not sure why the file picker only supports implicit grants. I know opening in a new window became mandatory.

**Comment by daboxu** [comment]
@exp0nge thanks for the info, you are right, we made decision on using the implicit flow because the picker was designed for the single page web application.

**Comment by exp0nge** [comment]
I guess I'll close this. I wish the picker was more flexible.
