### ISSUE TITLE
OneDrive for Buiseness: When I use the resumable upload of Graph API to upload some files there will result in 404 Not Found

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#675]
When I use the resumable upload of Graph API to upload a mp3 or pdf file, the first step "Create an upload session" will success, but when I perform the second step "Upload bytes to the upload session" will result in 404 Not found. Not all mp3 and pdf files will result in this error, I don't know why?

**Comment by ificator** [comment]
Hi @imkk do you still see this issue? We've been enabling some changes that should resolve a lot of the issues related to upload sessions via MS Graph.

**Comment by imkk** [comment]
Hi @ificator , it's all right now. thanks for your job.

**Comment by imkk** [comment]
@ificator , I found another issue has been solved too, which I submitted before: https://github.com/OneDrive/onedrive-api-docs/issues/452.

**Comment by ificator** [comment]
Thanks for confirming!
