### ISSUE TITLE
README states that you can use Graph API to access OneDrive for Business files, but that is only partially true

### ISSUE THREAD

**Issue by nddipiazza** [OneDrive/onedrive-api-docs#676]
I noticed that in the readme https://dev.onedrive.com/README.htm it states that you can use Graph API to access OneDrive for Business files.

But if you see: 
https://stackoverflow.com/questions/45549370/microsoft-graph-api-drive-root-children-always-empty-even-though-i-have-file you may notice that it actually does not allow app-only users to access OneDrive through the Graph API. It just returns sharepoint files only.

Can someone comment on whether or not it is possible to access OneDrive for Business files of any user in your business using app-only access? 

I contacted support and they have repeatedly told me it is not possible. So I'm thinking it is not possible. But they have been wrong before and I'm hoping they are wrong about this?

If it is not possible, we should really put some text on the README stating as such so that it is very clear - you cannot, as an administrator, access users in your business' onedrive for business files unless you have an oauth token generated from that user's username and password.

**Comment by rgregg** [comment]
You can use the API, with app-only access, to request OneDrive for Business data. The pattern for the request is:

```http
GET https://graph.microsoft.com/v1.0/users/{userIdOrUPN}/drive
```

**Comment by ificator** [comment]
app-only via Graph has been supported for some time now.
