### ISSUE TITLE
Resumable upload - set content-length

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#677]
Resumable upload requies setting custom content-length in the header which is invalid in most browsers. Does it mean resumabale upload is designed or server upload only ?

Thanks,

**Comment by rgregg** [comment]
The content-length header usage is standard. The content-range header is also standard usage, but needs to be set manually because it cannot be inferred from the request. You should be able to specify this header when doing an AJAX request. Can you provide an example or more details about the specific problem you're encountering?

**Comment by neunygph** [comment]
Hi @rgregg ,

According to the upload fragments section from https://dev.onedrive.com/items/upload_large_files.htm#upload-fragments . We need to set content-length and content-range so after created an upload session I made another http request with
xhr.setRequestHeader('Content-Length',contentLength);
xhr.setRequestHeader('content-range',contentRange);
and I got a javascript error , this is a standard error from most of the browsers "Refused to set unsafe header 'content-length'". Please advice if this resumable upload is intended only for server upload ?

Thanks,

**Comment by neunygph** [comment]
Hello @rgregg 

To upload multiple fragments, do we need to "actually" split the file into multiple parts ?

**Comment by rgregg** [comment]
You don't, if the file is small enough. The larger the file, the better off you will be to split the file so you can resume a file transfer without starting all over again. Either way though, you need to specify the content-range header to tell OneDrive how big the file is going to be and what portion of the file you are providing with your request.

**Comment by neunygph** [comment]
Oh I see, also I'm aware that for simple upload, the upload file should be in binary. Does it has to be in binary form as well for session upload?

Thanks

**Comment by ificator** [comment]
Hi @neunygph, session based uploads expect the binary data as well when you're executing the `PUT` to the upload URL. It's also better to wait for the completion of the previous fragment before proceeding to upload the next.
