### ISSUE TITLE
File Picker API v7.2 doesn't work on Safari

### ISSUE THREAD

**Issue by juanferrer** [OneDrive/onedrive-api-docs#678]
Trying to load a file in the [Open demo](https://dev.onedrive.com/sdk/js-v72/js-picker-open.htm#open-demo) from Safari MacOS shows an error:

![onedrive safari error](https://user-images.githubusercontent.com/22564520/29065064-d26200e8-7c22-11e7-8b84-0a6809fe246e.png)

This error is present when using the JavaScript File Picker API v7.2 in Safari. The Open and Cancel buttons, both show the same behaviour. Using Safari v9.1.2, OSX El Capitan.

When the picker is opened, the following error is logged to the console:

> Blocked a frame with origin "https://onedrive.live.com" from accessing a frame with origin "https://dev.onedrive.com". The frame requesting access set "document.domain" to "live.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.

Should be noted that Safari on iOS v11.0 works as expected.

More details [here](https://stackoverflow.com/questions/45433681/onedrive-picker-api-on-safari)

**Comment by halfdevil85** [comment]
I'm facing the same issue on Safari v10.0.3,  macOS Sierra v10.12.3.
I'm able to make it work in development environment by accessing the Develop tab > Disable Cross-Origin Restrictions, but this will not be the option since impossible to ask normal user to disable it. Any assistance on this issue would be greatly appreciated.

**Comment by JuanFerrer** [comment]
@halfdevil85 Since we couldn't afford waiting, we've downgraded to [v7.0](https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm). It works fine in most browsers and platforms. Check it out, maybe it works for you too. I'll keep an eye on this to upgrade when they fix it.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
