### ISSUE TITLE
UnknownError sporadically during /shares/

### ISSUE THREAD

**Issue by exp0nge** [OneDrive/onedrive-api-docs#679]
I'm having trouble figuring out why this error occurs sometimes. I build "permanent" links:
`https://api.onedrive.com/v1.0/shares/{share-id}/root/content` 

Oddly, sometimes I get this:
```{'error': {'code': 'UnknownError', 'message': '', 'innerError': {'request-id': '6a0c3009-f87a-4816-8941-94e159a4991e', 'date': '2017-08-11T07:40:00'}}}```

I'm not sure how I can diagnose this. I know the access tokens are valid because I make queries before this.

**Comment by exp0nge** [comment]
I'm using the `https://graph.microsoft.com/v1.0/drive/items/{item-id}` endpoint to get a download link but I can't cache those since they expire which leaves me having to make the request every time.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
