### ISSUE TITLE
enh: allow all return urls from a domain (like dropbox & google drive)

### ISSUE THREAD

**Issue by jitbit** [OneDrive/onedrive-api-docs#68]
Currently you need to specify the EXACT "return url" for an app, which makes it difficult, since in my app urls are like "XXX.domain.com/user/item/1234/" (where "1234" can change, "XXX" too).

**Comment by rgregg** [comment]
Thanks for the suggestion @jitbit. I'll forward this along to the Microsoft account team. In the mean time, can you add this feature request to our [UserVoice](http://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer) page for others to vote on as well?

**Comment by jitbit** [comment]
will do thanks
