### ISSUE TITLE
Unexpected behavior for AppFolder permissions

### ISSUE THREAD

**Issue by nicolasbeauvais** [OneDrive/onedrive-api-docs#682]
I created an app with `Files.ReadWrite.AppFolder` permission only.
Request to: `https://graph.microsoft.com/v1.0/drive/special/approot`
Response: 404, and the AppFolder is not created in my Onedrive.

The documentation states:
>"OneDrive creates your app's folder in the user's Apps folder, located in the root of the user's OneDrive, when your app makes the first call to the folder using the special folder namespace. Below are the most common calls your app can make to create the folder for the first time."

So my AppFolder should have been created and not return 404.

If I try the exact same process after adding the `Files.ReadWrite.All` permission the request success and return the expected response:
```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drive/special/$entity",
    ...
    "folder": {
        "childCount": 0
    }
}
```
and my AppFolder is successfully created. Isn't the whole point of the `Files.ReadWrite.AppFolder` permissions to avoid requiring full read/write access to our users?

**Comment by mobitar** [comment]
I too have just experienced this same issue. Requesting `Files.ReadWrite.AppFolder` gives me access denied when I try to access my app folder via `drive/special/approot`. Only when I request `Files.ReadWrite.All` am I finally able to access my app folder.

Like OP said, this kind of defeats the point of having a sandboxed app folder if a user needs to give me total access for me to write to it. Hoping this gets fixed.

**Comment by MickaelTH** [comment]
February 2018, still have this issue. Hope it will get fixed soon.

**Comment by ificator** [comment]
This issue has unfortunately changed owners a couple of times - let me get to the bottom of the status here see where we are.

**Comment by ificator** [comment]
For those who are seeing issues, are you trying to hit OneDrive Business or OneDrive Consumer. From what I can tell the fix for ODC should be deployed now.

**Comment by nicolasbeauvais** [comment]
@ificator had the bug with both, ODC and ODB

**Comment by ificator** [comment]
OK, so here's what the state of the world is:

1. OneDrive Consumer had an issue whereby provisioning wouldn't work when the `Files.ReadWrite.AppFolder` scope was the only one present, but that should now be fixed. To my knowledge OneDrive Consumer should be working as expected so please let me know if you're seeing anything that contradicts this.

2. OneDrive Business does not support `Files.ReadWrite.AppFolder` ([see these remarks](https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference#remarks-5)). We want to fix this so that it aligns with how OneDrive Consumer behaves, but it's a non-trivial change.

If support for OneDrive Business is something that you'd really like to see I'd suggest upvoting any appropriate asks [on our uservoice page](https://onedrive.uservoice.com/forums/262982-onedrive?category_id=89523) (or creating one if there aren't any already).

**Comment by benbro** [comment]
Any news about this issue?
I know it is closed but it's been few months and the [uservoice task ](https://onedrive.uservoice.com/forums/262982-onedrive-archive/suggestions/33911101-make-files-readwrite-appfolder-work-with-onedrive)wasn't even acknowledged by the OneDrive team.

**Comment by barisbikmaz** [comment]
@ificator How is the status of [uservoice](https://onedrive.uservoice.com/forums/262982-onedrive-archive/suggestions/33911101-make-files-readwrite-appfolder-work-with-onedrive). Looks like closed and we can't rate anymore.

By the way. If you give us developers a good way to store application information for users this scope should be working similar to personal users. 

If you are an ISV and you have a produvt, then it is really difficult to tell customeer why we need different scopes for onedrive and onedrive for business to do the same stuff.

**Comment by ificator** [comment]
It looks like the uservoice was created in the archive forum - I'm not exactly sure how it was done, but my guess is that there's policy in that forum that disables voting. I'll see if I can track down someone who has control over our UserVoice to find out if it's possible to move the task into the appropriate area, otherwise we'll unfortunately have to create a new one and start from the beginning vote wise.

I can say that we're aware of the desire for appfolder permissions in ODB, and it's on our backlog, but I cannot comment on timeframes.

**Comment by ificator** [comment]
We managed to move it back to the developer area so you should be able to vote on it again!

**Comment by justinformella** [comment]
I'm not sure how you can close this and somehow label this "not a bug it's a yet to be implemented feature". You public documentation doesn't even mention the fact that the appFolder scope is not available on OneDrive Business. When both share the same API but yet dependent on the kind of plan the end user chooses that same API behaves entirely differently and that behavior is undocumented, I'd be hard pressed to find anyone who would call this anything other than a bug.

Please reopen this issue, this smacks of nothing more than the overused "it's a feature, not a bug" scapegoat.

**Comment by komikoni** [comment]
I want to remedy excessive scope requirements.

The following document describes whether ODB (OneDrive for Bussiness) supports `Files.ReadWrite.AppFolder` scope.
Is this true?

Is this ticket really closed?

https://docs.microsoft.com/en-US/onedrive/developer/rest-api/concepts/direct-endpoint-differences?view=odsp-graph-online#permissions

**Comment by barisbikmaz** [comment]
@komikoni I think, this issue is still not fixed. Currently you can just vote on UserVoice so that it get more priority.

**Comment by oFlo193o** [comment]
Is there any news on that Topic?

**Comment by OlliV** [comment]
It looks like it works partially. It works fo me if I use the v2 auth endpoint but not with v1. Unfortunately I need v1 because currently that's the only/easiest way to use device code flow with Node.js.

**Comment by oFlo193o** [comment]
@OlliV using AppFolder permission to Enterprise/Business Accounts, or private MS Accounts?

**Comment by OlliV** [comment]
@oFlo193o ah sorry, I didn't specify my plan. I'm using SharePoint Online which might actually have more OneDrive API features enabled than OneDrive for Business.

**Comment by jbostoen** [comment]
So should Files.ReadWrite.AppFolder be working when using the v2.0 API combined with an Office 365 E1 or E3 subscription?

**Comment by OlliV** [comment]
It has been a while since I touched this but yes. Note that I said v2 authentication API not v2 Graph API.

**Comment by jbostoen** [comment]
> 
> 
> It has been a while since I touched this but yes. Note that I said v2 authentication API not v2 Graph API.

Oh, okay, thanks for the clarification

**Comment by VitalyKnyazev** [comment]
The issue is still there, Files.ReadWrite.AppFolder works for most users but for some full RW access is the only workaround.

**Comment by EduardoFromTheFuture** [comment]
Anyone knows if there is an issue open to support de AppFolder for business users?

Also, how about being able to write to One Drive in a hidden folder, that the user can't accidentally delete the contents by mistake? Google drive offers this, it's called the AppFolder in there.

**Comment by introwit** [comment]
@jbostoen were you able to get `Files.ReadWrite.AppFolder` working with an e3 subscription?

**Comment by introwit** [comment]
@ificator seems like `Files.ReadWrite.AppFolder` is still not supported for OneDrive for Business (I am using the e3 subscription), any idea?

**Comment by KuzonCode** [comment]
> The issue is still there for v4, Files.ReadWrite.AppFolder works for most users but for some (ODC) full RW access is the only workaround.

I am trying to work out who gets affected by this, what does ODC mean @VitalyKnyazev?

**Comment by aguarino77** [comment]
The frustrating part is that delegated permission work in e3, but not application permission… does anyone else experiences the same?

**Comment by Digipom** [comment]
Is there any plan to support this?
