### ISSUE TITLE
OneDrive: How to Download selected file after click on "Open" button 

### ISSUE THREAD

**Issue by mathesvaranc** [OneDrive/onedrive-api-docs#683]
**Client side code**

       <script type="text/javascript" src="https://js.live.net/v7.0/OneDrive.js"></script>

function launchOneDrivePicker() {
        var odOptions = {
            clientId: "axxxxxxxxxxxxxxxxxxxxxxx72d6eea9",
            action: "download",
            multiSelect: false,
            advanced: {
                queryParameters: "select=id,name,size,file,folder,photo,@microsoft.graph.downloadUrl",
                redirectUri: "http://localhost:13055/FileUploadTesting"
            },
            success: function (response) {
                var downloadurl = response.value[0]["@microsoft.graph.downloadUrl"];
                alert("You picked : " + downloadurl);
                location.href = downloadurl;
                HandleIT(downloadurl, "dontknowfilename");
                alert("Download completed.."); /* success handler */      },
            cancel: function () { /* cancel handler */ },
            error: function (e) { /* error handler */ },
        };
        OneDrive.open(odOptions);
    }

        function HandleIT(downloadurl, file_name)
        {
            PageMethods.ProcessIT(downloadurl, file_name, onSucess, onError);
            function onSucess(result) { alert(result); }
            function onError(result) { alert('Something wrong.'); }
        }

     <asp:Button Text="text" OnClientClick="launchOneDrivePicker()" runat="server" />

**server side**
        [WebMethod]
        public static string ProcessIT(string downloadURL, string file_name)
        {
            // Create a new WebClient instance.
            WebClient myWebClient = new WebClient();
            string path = @"c:\";
            string path_n_name = path + file_name;
            // Download the Web resource and save it into the current filesystem folder.
            myWebClient.DownloadFile(downloadURL, path_n_name);
            return "SUCCESS";
        }

My issue: 
I can able to do authorize my app
I can able to choose my any of files from oneDrive
Its not redirected to my page and not able to downloaded which I selected files

Please help me to resolve my issue

**Comment by daboxu** [comment]
hi @mathesvaranc for the client side code, did the success callback function got invoked?

**Comment by daboxu** [comment]
close for now and feel free to reopen it if the problem consists.
