### ISSUE TITLE
Graph Search doesn't return same results on different directory levels

### ISSUE THREAD

**Issue by exp0nge** [OneDrive/onedrive-api-docs#684]
I'm using the search endpoint:
`https://graph.microsoft.com/v1.0/drive/items/{item-id}/search(q='*.mp3')?filter=audio ne null`

What I've noticed is that if the `item-id` which is directory, returns different number of results depending on the depth. 

```
dir1
  dir2
    dir3
      *.mp3
```

If I query from `dir2` I am able to get all the expected results. However, on a higher level, the results are truncated. There is also no `nextLink` for me to page through the results. The truncated results are significantly less.

**Comment by exp0nge** [comment]
Update: seems like there are more results today than yesterday on the same item-id. Is this some sort of caching/indexing issue? Is it better for me to traverse the directories myself?

**Comment by exp0nge** [comment]
I tried changing my search query to a more broad term to one of the facet items and it gives me the results that I expect. I'm not sure why this is since all the files I'm searching for are of .mp3 type.

**Comment by Manmohanbadaya** [comment]
When i am trying to run this query on graph api explorer
`https://graph.microsoft.com/v1.0/drive/items/{item-id}/search(q='*.mp3')?filter=audio ne null`

i am receiving this error.
  "message": "A potentially dangerous Request.Path value was detected from the client (*).",

Can you please tell how you are using this search api?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
