### ISSUE TITLE
400 error from session upload

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#686]
I'm try to do a session upload with multiple fragments, I got a successful response with 202 status on first request, but it failed on the second fragment and all I see is bad request with 400 status, nothing else in the response. Below is an example of what I'm doing with my content-range header

First request: bytes 0-99/300 //I got 202 status on this
Second request: bytes 100-199/300 //i got 400 status on this

Also, are these good example of perfect fragment size ? 32 * 320 * 1024 or 64 * 320 * 1024 or 128* 320 * 1024

Thanks,

**Comment by ificator** [comment]
Theoretically we support any fragment size, but our recommendations are:
1. A fragment size of 10 MiB for stable high speed connections is optimal. For slower or less reliable connections you may get better results from a smaller fragment size. The recommended fragment size is between 5-10 MiB.
2. Use a fragment size that is a multiple of 320 KiB (320 * 1024 bytes). Failing to use a fragment size that is a multiple of 320 KiB can result in large file transfers failing after the last fragment is uploaded.

To help figure out what's going on with your request we'll need a couple of pieces of information:
1. Are you calling a business or consumer account?
2. If it's a business account, can you provide us with the `SPRequestGuid` header that's in the response?

**Comment by neunygph** [comment]
Hi @ificator ,

Thanks for the response, I actually just figured the reason it failed because the size of first and second fragment were 1 byte different. It would be nice if we can be able to see what went wrong with the request from the response instead of seeing only 400 status.

Is it possible to have a fragment size that is a multiple of 640 KiB instead of 320 KiB ? Does it affect performance ?

**Comment by ificator** [comment]
It won't impact performance on our side, so it's really a choice of what is best for your scenario. If it's a mobile app where networks can be less reliable having smaller fragment sizes is normally better, but if it's an app that will be hard wired then the bigger the better. I'd suggest experimenting a little while emulating your target environment to see what meets your goals.

**Comment by neunygph** [comment]
Oh I see , thank you
