### ISSUE TITLE
Webhooks on items (not "/me/drive/root")

### ISSUE THREAD

**Issue by exp0nge** [OneDrive/onedrive-api-docs#687]
I notice that the Update webhooks has a `PATCH /drive/items/{item-id}/subscriptions/{id}` request where the response has a value for resource of ` "resource": "/drives/0/items/57705F13F13C3C0C!104",`. Does this mean that webhooks can be created for specific item IDs?

When I try to send a create request with a specific item-id, I get this:
```
{
    "error": {
        "code": "InvalidRequest",
        "message": "resource '/drive/items/{item-id}/' is not supported.",
        "innerError": {
            "request-id": "793ba53f-a055-4000-aa69-25e775483d26",
            "date": "2017-08-21T17:04:25"
        }
    }
}
```
I'm only able to subscribe to the root folder (`"/me/drive/root"`).

**Comment by ificator** [comment]
Unfortunately it's only possible to subscribe to the root via Microsoft Graph.

Is that really the error message you got back? Seems strange that it would complain about `/content/`

**Comment by exp0nge** [comment]
@ificator Oh, I was just testing different endpoints to see if one would work, but the general error response is just the URL I provide for the resource.

How come the update subscription docs show an item-id endpoint (https://dev.onedrive.com/webhooks/update-subscription.htm)?

**Comment by ificator** [comment]
Ah, this is probably left over from when the documentation was for the direct endpoints. OneDrive Consumer does actually support subscriptions at the item level, but unfortunately OneDrive Business does not. Since MS Graph needs to provide a consistent view of both services it implements the lowest common denominator.

If you call the direct endpoint for OneDrive Consumer you could do what you ask.

**Comment by exp0nge** [comment]
Okay, good to know. Thanks.

**Comment by aandis** [comment]
@ificator I'd like to create webhook subscriptions at item level so I am using `https://api.onedrive.com/v1.0/subscriptions` but it returns `400` with 
```json
{
    "error": {
        "code": "invalidRequest",
        "message": "Invalid API or resource"
    }
}
```
Any ideas?

**Comment by ificator** [comment]
You'll need to address the item that will be the root of the subscription. For the following will subscribe to changes on the entire drive:
```
https://api.onedrive.com/v1.0/drive/root/subscriptions
```

While the following will subscribe to changes for a specific item (and its children):
```
https://api.onedrive.com/v1.0/drive/items/{id}/subscriptions
```

**Comment by aandis** [comment]
Ah, so it's not [this](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_post_subscriptions) webhook api I guess. The post body needs to be different? Can you point me to the documentation for the above?

**Comment by ificator** [comment]
It actually is, the documentation is just unclear on what needs to come before `/subscriptions` - it's a documentation bug.

**Comment by aandis** [comment]
@ificator It looks like the `POST` body needs to be different for this request. I tried sending 
```json
{
 "changeType": "updated",
 "notificationUrl": "<my-url>",
 "resource": "<same resource as url>",
 "expirationDateTime": "2018-02-03T17:00:00Z",
 "clientState": "client-specific-string"
}
```
and received 
```
[subscription] The property 'changeType' does not exist on type 'oneDrive.subscription'. Make sure to only use property names that are defined by the type.
```
I had to remove `changeType`and `resource` to get it working. 

Thanks for your help. :) Please update the documentation for this.

**Comment by exp0nge** [comment]
@aandis I'm getting `Unsupported segment type. ODataQuery: drive/items/{0}/subscriptions'`. I've tried using the full resource uri `https://api.onedrive.com/v1.0/drive/items/{id}/subscriptions` in the request and JSON body and combinations of the root API URL. What URL did you POST to?

**Comment by ificator** [comment]
Hi @exp0nge, can you give us a full request example so we can see the URL being POSTed to along with the request headers and body?

**Comment by exp0nge** [comment]
@ificator My mistake it looks like I get that error on the Graph API, I'm not actually using the OneDrive API but if the feature is available in Graph then here's my request details:

POST  `https://graph.microsoft.com/v1.0/drive/items/F1AE114A173FAE6C!105/subscriptions`

# Body
```
{"notificationUrl": "mywebsite.com/webhook", "expirationDateTime": "2018-04-20T20:04:21.310235Z", "resource": "https://graph.microsoft.com/v1.0/drive/items/F1AE114A173FAE6C!105/subscriptions", "changeType": "updated"}
````
