### ISSUE TITLE
Calling upload.createSession on Sharepoint results in error 404 when updating a file

### ISSUE THREAD

**Issue by kotsak** [OneDrive/onedrive-api-docs#689]
Hi,

We have a customer/user who is experiencing errors when trying to upload a file over an existing file on Sharepoint using the Onedrive API resumable upload method.
If the file already exists, he receives a 404 error during the upload.createSession API call. If he manually deletes the file from his Sharepoint document library before attempting the upload then it works fine.

Below are the requests/responses for both successful and failed attempts (with AUTH and Host info removed).

**Successful attempt:**

POST /Sales/_api/v2.0/drives/b!Yym8pE-hvEKrlMi1_AhwdvCaPdz0ErFBu1MroEaNSm6HxA3bBYTdSpKsGQQm7xCj/items/01ZA2MFZQMFOG73TXXWFAJEFAXVR6PGCOD:/Import%20Sales%20Report%20w%20subItem%202017.xlsx:/upload.createSession HTTP/1.0
Content-Type: application/json; charset=UTF-8
Content-Length: 219
Authorization: Bearer [snip]
Host: xxxxxxxxxxxxx.sharepoint.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/3.0 (compatible; Indy Library)

{"item":{"@microsoft.graph.conflictBehavior":"replace","name":"Import Sales Report w subItem 2017.xlsx","fileSystemInfo":{"lastModifiedDateTime":"2017-08-18T12:20:41.000Z","createdDateTime":"2017-01-09T16:47:48.000Z"}}}

**HTTP/1.1 200 OK**
Cache-Control: private, max-age=0
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Thu, 03 Aug 2017 13:51:55 GMT
Last-Modified: Fri, 18 Aug 2017 13:51:55 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 1174
SPRequestDuration: 1289
X-AspNet-Version: 4.0.30319
SPRequestGuid: a27c109e-20ee-4000-2b60-74040ff3c2cb
request-id: a27c109e-20ee-4000-2b60-74040ff3c2cb
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.6809
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: ACA49E0D7CC14C908120F2A529A85FC4 Ref B: SN1EDGE0115 Ref C: 2017-08-18T13:51:56Z
Date: Fri, 18 Aug 2017 13:51:56 GMT

**Failed attempt:**

POST /Sales/_api/v2.0/drives/b!Yym8pE-hvEKrlMi1_AhwdvCaPdz0ErFBu1MroEaNSm6HxA3bBYTdSpKsGQQm7xCj/items/01ZA2MFZQMFOG73TXXWFAJEFAXVR6PGCOD:/Import%20Sales%20Report%20w%20subItem%202017.xlsx:/upload.createSession HTTP/1.0
Content-Type: application/json; charset=UTF-8
Content-Length: 219
Authorization: Bearer [snip]
Host: xxxxxxxxxxxxx.sharepoint.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/3.0 (compatible; Indy Library)

{"item":{"@microsoft.graph.conflictBehavior":"replace","name":"Import Sales Report w subItem 2017.xlsx","fileSystemInfo":{"lastModifiedDateTime":"2017-08-18T12:20:41.000Z","createdDateTime":"2017-01-09T16:47:48.000Z"}}}

**HTTP/1.1 404 Not Found**
Cache-Control: private, max-age=0
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: Thu, 03 Aug 2017 13:45:32 GMT
Last-Modified: Fri, 18 Aug 2017 13:45:32 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 2526
SPRequestDuration: 2669
X-AspNet-Version: 4.0.30319
SPRequestGuid: 457c109e-606d-4000-2b60-7a8d24b6642a
request-id: 457c109e-606d-4000-2b60-7a8d24b6642a
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.6809
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: D204E4525D9A4BFF8149CB9C2C8F79FA Ref B: SN1EDGE0113 Ref C: 2017-08-18T13:45:35Z
Date: Fri, 18 Aug 2017 13:45:34 GMT

Any hints on what is causing this behaviour?

Thanks,
KT

**Comment by ificator** [comment]
Thanks for all of the details! I'll take a look on Monday and see what stands out.

**Comment by ificator** [comment]
It does seem to be an issue on our side.

**Comment by ificator** [comment]
Hi @kotsak, we've made a change that should stop the `upload.createSession` failing like this. But we may find that it's kicking the can down the road so to speak, resulting in a potential failure in the subsequent `PUT` call. If you see something like this occur, can you create a new issue and include the response for both the `upload.createSession` call as well as the failing `PUT` call (including the headers for both). Thanks!

**Comment by kotsak** [comment]
Hi @ificator, the user came back saying that the problem is still there but seems unwilling to pursue this further since he already has a workaround (by deleting the old files prior copying the new ones).

Since we had only one user with this problem I will contact you again if another user comes up with the same issue.

Thanks.

**Comment by ificator** [comment]
Thanks for following up @kotsak.

**Comment by kotsak** [comment]
Hi @ificator ,

After all this time we had another user today with the same issue. The problem occured on two different file uploads. Again (like the first time), the files already existed in the target folder when the error occured, and deleting them manually, prior the upload, resolved the problem until the next time they got updated when it threw the same error again. So it seems it happens only during updating an existing file.

First case:

```
POST /sites/admin/_api/v2.0/drives/b!pFII7bu34U2NyExHlZqabdaiOEDMljBFtp8mNSHMBnnJLZ7AYCotT5_OJKLTo9A3/items/01RQB3XZV6Y2GOVW7725BZO354PWSELRRZ:/NationalLegalAct.Doc:/createUploadSession HTTP/1.0
Content-Type: application/json; charset=UTF-8
Content-Length: 200
Authorization: Bearer xxxxxxxxxx
Host: xxxxxxxxxx.sharepoint.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/3.0 (compatible; Indy Library)

{
	"item": {
		"@microsoft.graph.conflictBehavior": "replace",
		"name": "NationalLegalAct.Doc",
		"fileSystemInfo": {
			"lastModifiedDateTime": "2003-10-22T08:46:46.000Z",
			"createdDateTime": "2004-07-01T13:50:26.437Z"
		}
	}
}

HTTP/1.1 404 Not Found

Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 867
SPRequestDuration: 955
X-AspNet-Version: 4.0.30319
SPRequestGuid: 6d21639e-3093-5000-6cfd-86858753e3d2
request-id: 6d21639e-3093-5000-6cfd-86858753e3d2
MS-CV: nmMhbZMwAFBs/YaFh1Pj0g.0
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.7618
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Wed, 02 May 2018 08:13:40 GMT

{
	"error": {
		"code": "itemNotFound",
		"message": "The resource could not be found."
	}
}

```
Second case:

```
POST /sites/admin/_api/v2.0/drives/b!pFII7bu34U2NyExHlZqabdaiOEDMljBFtp8mNSHMBnnJLZ7AYCotT5_OJKLTo9A3/items/01RQB3XZV6Y2GOVW7725BZO354PWSELRRZ:/New_2004.ppt:/createUploadSession HTTP/1.0
Content-Type: application/json; charset=UTF-8
Content-Length: 192
Authorization: Bearer xxxxxxxxxx
Host: xxxxxxxxxx.sharepoint.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/3.0 (compatible; Indy Library)

{
	"item": {
		"@microsoft.graph.conflictBehavior": "replace",
		"name": "New_2004.ppt",
		"fileSystemInfo": {
			"lastModifiedDateTime": "2004-02-06T08:22:34.000Z",
			"createdDateTime": "2004-07-01T13:50:28.343Z"
		}
	}
}

HTTP/1.1 404 Not Found

Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
X-SharePointHealthScore: 1
X-SP-SERVERSTATE: ReadOnly=0
ODATA-VERSION: 4.0
SPClientServiceRequestDuration: 531
SPRequestDuration: 613
X-AspNet-Version: 4.0.30319
SPRequestGuid: 6d21639e-80f5-5000-9f5d-1c434109d0e1
request-id: 6d21639e-80f5-5000-9f5d-1c434109d0e1
MS-CV: nmMhbfWAAFCfXRxDQQnQ4Q.0
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.7618
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Wed, 02 May 2018 08:13:41 GMT
Connection: close

{
	"error": {
		"code": "itemNotFound",
		"message": "The resource could not be found."
	}
}
```
I haven't created a new thread for this issue as you requested since it happens again during the upload session creation and not during the subsequent data upload.

Thanks.

**Comment by ificator** [comment]
This is a strange one.

Basically we persist the fileSystemInfo timestamps on the file so that we can use them on commit, and that works fine if left alone. But for some reason the properties that we write to already exist on the item with a different time (string vs datetime) which is causing a failure (obviously with an incorrect status code). Do you know if there's any processing done on these files that could be messing with file properties?

**Comment by kotsak** [comment]
We asked the user and the reply we got was that currently there are no changes being done to the online files once they get uploaded.

He just tested it on a blank Sharepoint site, initial file upload went fine but the subsequent update failed for a lot of files. We've asked him for fresh debug logs to make sure the errors are the same.
