### ISSUE TITLE
"multipart/form-data" multipart upload fails with HTTP 400 error

### ISSUE THREAD

**Issue by igokoro** [OneDrive/onedrive-api-docs#69]
I'm implementing upload of very small files using multipart method. My implementation sends the following request to the OneDrive server
```
HTTP POST https://api.onedrive.com/v1.0/drive/items/{folder-id}:/{child-folder-name}:/children
Authorization: bearer EwB...
Content-Type: multipart/form-data; boundary=87ca48b5-cc31-4889-9e81-87df743e08ae
Content-Length: 1284
--87ca48b5-cc31-4889-9e81-87df743e08ae
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8
Content-Length: 31
Content-Transfer-Encoding: binary
{"file":{},"name":"file-name.ext"}
--87ca48b5-cc31-4889-9e81-87df743e08ae
Content-Disposition: form-data; name="content"
Content-Type: text/plain
Content-Length: 842
Content-Transfer-Encoding: binary
  File content goes here
--87ca48b5-cc31-4889-9e81-87df743e08ae--
```

In response I get HTTP 400 error from server:
```
HTTP 400

{
    "error": {
        "code": "invalidArgument",
        "message": "Bad Argument",
        "innererror": {
            "code": "badArgument"
        }
    }
} 
```
Unfortunately, it's not particularly clear what argument is invalid to start with.
My implementation conforms to [RFC 2388](https://www.ietf.org/rfc/rfc2388.txt) which is mentioned on [Multipart Upload docs page](http://onedrive.github.io/items/upload_post.htm).

It's also confusing that documentation of multipart upload talks about ```multipart/related``` but references RFC for ```multipart/form-data```.

I wonder if OneDrive team is able to help me to resolve the issue?

**Comment by ificator** [comment]
Hi @igokoro this is definitely an area we need to work on. If you run in to the issue again could you dump out all of the HTTP headers that came with the response and provide them here?

**Comment by yegodz** [comment]
Hi @igokoro 

I had to try a bunch of stuff before I got file upload to work. You are right there is a contradiction in the documentation that is not clear if you need multipart/form-data or multipart/related.
The following worked for me.. you can try it out. I used `multipart-related` so my request header had the following:
```
content-type:multipart/related; boundary=---------------------------a4bbcc4a-89f2-420b-b284-f02dfb8b5c60
```
Then the body of the POST request looked like this:
Note that `Content-ID: <metadata>` and `Content-ID: <content>` need to be in the header of each of the two parts of the multipart.
Also, the `"@content.sourceUrl":"cid:content"` property needs to be in the metadata part. Presumably that tells the oneDrive server to take the contents of the file from the body of the post rather than from some url. 
Most servers also need you to put an additional newline `\r\n` between the header and body of each part of the multipart request.

```
-----------------------------a4bbcc4a-89f2-420b-b284-f02dfb8b5c60
Content-ID: <metadata>
Content-Type: application/json

{"name":"myFileName.dat","file":{},"@content.sourceUrl":"cid:content"}
-----------------------------a4bbcc4a-89f2-420b-b284-f02dfb8b5c60
Content-ID: <content>
Content-Type: application/octet-stream

<binary file data ...>
```

**Comment by igokoro** [comment]
Hi @ificator, this issue is happening to me every single time. I guess this is because I'm sending out ```multipart/form-data``` instead of ```multipart/related```, as @yegodz said. But this is what I get out of the box from the Retrofit android lib. And I don't see why ```multipart/form-data``` shouldn't be sufficient for this kind of task - of course, this my opinion, and don't really know if this is the case.
 
So my request:
```
---> HTTP POST https://api.onedrive.com/v1.0/drive/items/{folder-id}/children
Authorization: bearer EwB...
Content-Type: multipart/form-data; boundary=4481a45d-4451-4501-9129-99738f4f84d5
Content-Length: 1284
--4481a45d-4451-4501-9129-99738f4f84d5
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8
Content-Length: 31
Content-Transfer-Encoding: binary
{"file":{},"name":"policy.ncc"}
--4481a45d-4451-4501-9129-99738f4f84d5
Content-Disposition: form-data; name="content"
Content-Type: text/plain
Content-Length: 842
Content-Transfer-Encoding: binary

    content goes here

--4481a45d-4451-4501-9129-99738f4f84d5--
---> END HTTP (1284-byte body)
```

Response from server:
```
<--- HTTP 400 https://api.onedrive.com/v1.0/drive/items/{folder-id}/children (898ms)
Via: 1.1 CH3302____PAP299 (wls-colorado)
Content-Type: application/json
Server: Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
X-WLSPROXY: CH3302____PAP299
X-MSNSERVER: DM2303____PAP187
X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
X-ThrowSite: 7eaf.31e2
X-AsmVersion: UNKNOWN; 19.17.0.0
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Date: Tue, 07 Apr 2015 11:00:37 GMT
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1428404435284
OkHttp-Received-Millis: 1428404436171
{
    "error": {
        "code": "invalidArgument",
        "message": "Bad Argument",
        "innererror": {
            "code": "badArgument"
        }
    }
}
<--- END HTTP (144-byte body)
```

Please let me know if you need something more from me.

**Comment by igokoro** [comment]
@yegodz, thank you for the suggestion! This is going to be quite useful, if I'll decide to construct request manually. For now I still hope that I'll be able to use default implementation of Retrofit lib, which is ```multipart/form-data```.

**Comment by ankit-ankuagrawal** [comment]
can somebody help me to form this query for android, whole day have been spend still no result

**Comment by rgregg** [comment]
This isn't Android, but I've written a sample in C# that builds a multipart/related request that may be a useful reference: https://github.com/rgregg/multipart-builder

**Comment by peternied** [comment]
From these other examples I don't see much usage of the file body, if that is the case you can just use this retrofit implementation from our sample, https://github.com/OneDrive/onedrive-explorer-android/blob/master/onedriveaccess/src/main/java/com/microsoft/onedriveaccess/IOneDriveService.java#L115

**Comment by yegodz** [comment]
@igokoro did you try adding the `"@content.sourceUrl":"cid:content"` as an additional field in your meta-data part? It seems to be required.

try making your metadata part as follows:
`{"file":{},"name":"file-name.ext", "@content.sourceUrl":"cid:content"}`

**Comment by ankit-ankuagrawal** [comment]
@yegodz it is required otherwise it gives error

**Comment by ankit-ankuagrawal** [comment]
how to use Content-Disposition???

**Comment by igokoro** [comment]
@yegodz I've ended up using simple file upload without multipart request. It seems to be more straightforward to implement.

**Comment by ankit-ankuagrawal** [comment]
@igokoro it is straightforward, the only problem which we are facing is abt
@name.conflictbehaviour because simple file upload doesnot support this
feature and multipart supports it.

and wanna use which has @name.ConflictBehaviour

**Comment by rgregg** [comment]
Sounds like everything on this thread is resolved now. If you continue to have difficulty here, please reopen this thread.

**Comment by deeksha92** [comment]
Hi,
Im also facing the same issue.Getting the response code as 400.Please find my code below.
 URL serverUrl = new URL("https://apis.live.net/v5.0/me/skydrive/files");	 
			 HttpURLConnection urlConnection = (HttpURLConnection) serverUrl.openConnection();
			 String boundaryString = "--AaB03x";
			 File FileToUpload = new File("C://Users//djhalani//SparkFile//Test.txt");
			 urlConnection.setDoOutput(true);
			 urlConnection.setRequestMethod("POST");
			 urlConnection.addRequestProperty("Authorization", "Bearer Ew....");
			 urlConnection.addRequestProperty("Content-Type", "multipart/related; boundary=" + boundaryString);
			 urlConnection.setDoOutput(true);
			 OutputStream outputStreamToRequestBody = urlConnection.getOutputStream();
			 BufferedWriter httpRequestBodyWriter =new BufferedWriter(new OutputStreamWriter(outputStreamToRequestBody));
			 httpRequestBodyWriter.write("\n--" + boundaryString + "\n");
			 httpRequestBodyWriter.write("Content-Disposition: form-data;"
				        + "name=\"file\";"
				        + "filename=\""+ FileToUpload.getName() +"\""
				        + "\nContent-Type: text/plain\n\n");
			 
			 httpRequestBodyWriter.flush();
			 FileInputStream inputStreamToLogFile = new FileInputStream(FileToUpload);
			 int bytesRead;
			 byte[] dataBuffer = new byte[1024];
			 while((bytesRead = inputStreamToLogFile.read(dataBuffer)) != -1) {
			     outputStreamToRequestBody.write(dataBuffer, 0, bytesRead);
			 }
			  
			 outputStreamToRequestBody.flush();
			  
			 // Mark the end of the multipart http request
			 httpRequestBodyWriter.write("\n--" + boundaryString + "--\n");
			 httpRequestBodyWriter.flush();
			 
			 outputStreamToRequestBody.close();
			 httpRequestBodyWriter.close();
			 inputStreamToLogFile.close();
			 
			 int responseCode = urlConnection.getResponseCode();
			 System.out.println(responseCode);

**Comment by rgregg** [comment]
Hi @deeksha92:

The issue you are reporting is different than the issue reported above. You're using the LiveConnect API, and this thread is about the modern API.

If your code isn't new code, and used to work but now is returning a 400 Bad Request, then please open a new issue so we can investigate. If you are writing new code to try and upload via Live Connect, please use MS Graph instead. The LiveConnect APIs are [formally deprecated](https://dev.office.com/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation) and will stop working Nov 2018.

**Comment by deeksha92** [comment]
Hi Ryan,

Thanks. This is my new code. Will try using microsoft graph and will post
in the thread if will have any issue.

**Comment by Akhilesh05** [comment]
Why was this issue closed?
It's still not resolved...

**Comment by ificator** [comment]
The issue is resolved - the question was related to `multipart/form-data` returning a 400, which is expected because it's not supported. You can read the documentation on multipart support [here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_post_content).

If you would support for `multipart/form-data` I'd suggest creating an idea (or upvoting one that already exists) on our [uservoice page](https://onedrive.uservoice.com/forums/262982-onedrive?category_id=89523) and we can look into it if there's enough support.
