### ISSUE TITLE
Fragmented upload calling upload.createSession returns `This access token is not valid on this endpoint.`

### ISSUE THREAD

**Issue by gojohnkevin** [OneDrive/onedrive-api-docs#690]
`Traceback (most recent call last): File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedriveb_cli/actions.py", line 195, in upload uploaded_item = client.item(drive=drive, id=resource_id).children[cleaned_filename].upload_async(file) File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 173, in fragment_upload_async resp = upload_builder.post(i * __PART_SIZE, length) File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 121, in post return self.request(begin, length, options).post() File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 57, in post entity = UploadSession(json.loads(self.send(data=self._file_handle).content)) File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/request_base.py", line 151, in send data=data) File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/http_provider.py", line 71, in send custom_response = HttpResponse(response.status_code, response.headers, response.text) File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/http_response.py", line 62, in __init__ raise Exception(str(message["error"])) Exception: invalid_request`

**Comment by ificator** [comment]
HI @gojohnkevin 

We did find an issue with `createSession` when the site in which the drive lives happens to contain an `&` in it's name. That issue has been resolved so hopefully your requests are now succeeding.

Otherwise we're going to need some more details from your side - ideally the FULL response that the server is sending (headers and body).
