### ISSUE TITLE
One drive for business api retun less number of records

### ISSUE THREAD

**Issue by anildbest83** [OneDrive/onedrive-api-docs#691]
I m using OneDrive for Business API to get folders and files inside a folder like this

/_api/v2.0/me/drive/items/01ZFGAWKSQXL************7Y/children

which is working fine.

But it is not returning all records but only few. I have more than 3000 folders but it is returning only 200

Here 

https://dev.onedrive.com/items/list.htm 

I found that there is a default limit of 200 items, and  @odata.nextLink property can be use to get next set of records. And for this i have to create a RECURSIVE method. But to get 3000 records in set of 200 it will make approx 16 API calls.

Please suggest is the a right way to get all records or is there any better approach for it.

**Comment by ificator** [comment]
The OneDrive API implements standard paging semantics to protect both the clients and the service from unbounded requests. As a result, for a sufficiently large folder making N calls is unavoidable.

You can minimize the number of round trips by specifying the maximum page size, which I believe is 1000:

`/_api/v2.0/drive/items/ABCD/children?top=1000`

**Comment by anildbest83** [comment]
Thanks @ificator for your suggestion

**Comment by anildbest83** [comment]
Hi @ificator 

i want to search a file or folder based on its name only.

It is mentioned that The query text used to search for items. Values may be matched across several fields including filename, metadata, and file content.

I used filter as well like this

 /_api/v2.0/me/drive/items/01Z54FA3E**********2XOG2FQOJ5/search(q='u')?filter=contains(name,'u')

but it still return other items as well.

Is it possible to search based on name only?
