### ISSUE TITLE
Error in Chrome: popup window is disconnected

### ISSUE THREAD

**Issue by halfdevil85** [OneDrive/onedrive-api-docs#693]
Previously the OneDrive file picker is working fine, but recently it suddenly not working on Chrome, others browsers are working fine.

When calling OneDrive.open(object), in Chrome will not open popup, in Developer Tools console tab, will able to see error message return by OneDrive.js which is {errorCode: "popupOpen", message: "popup window is disconnected"}.

Anyone having the same issue as me?

**Comment by daboxu** [comment]
hi @halfdevil85 , what's the picker version are you using? I tested with 7.2 and it works for me.

**Comment by daboxu** [comment]
closed for now and please feel free to reopen it if the issue consists.

**Comment by AurelioDeRosa** [comment]
@daboxu this is happening to me on Edge on Windows 10. The reasons is that the call to OneDrive.open opens a new window rather than a popup. This doesn't happen in IE11. The version I'm using is 7.2.

**Comment by alejandl-msft** [comment]
This happens if Chrome's popup-blocker blocks the file picker from opening. Enabling popups for that site will fix the issue.

**Comment by chetanyakan** [comment]
This is still an issue with `Electron` as well.

**Comment by andy-asana** [comment]
@chetanyakan Does enabled popups fix this in Electron as well?

**Comment by jcharnley** [comment]
Seems like this is still a problem on all browsers. If have not used the app before, BrowserStack testing I get a popup blocker error from Onedrive even tho the login popup works its the acutal picker that is the issue.

anyone have a solution ?
