### ISSUE TITLE
409 and 500 error code while moving files

### ISSUE THREAD

**Issue by johnlilis** [OneDrive/onedrive-api-docs#695]
I'm using the **OneDrive personal** API to move items (files and folders) from the root folder into a newly created folder.
Sometimes all items are moved successfully (200 ok everywhere), other times I get 409 or 500 errors in some files (in my tests I haven't gotten an error caused by a folder).

409 errors are in the following form, however the files are actually moved (there is no real conflict as the target folder is initially empty and root folder contents are moved as they are)
```
{
	"error": {
		"code": "nameAlreadyExists",
		"message": "An item with the same name already exists under the parent"
	}
}
```

500 errors are in the following form, and the files are not moved. If I retry the request, the files are moved normally without any further issues.
```
{
	"error": {
		"code": "generalException",
		"message": "An error occurred in the data store."
	}
}
```

A couple recent failing examples while moving files to target folder "6D4D5044C60EA101!243":

PATCH https://api.onedrive.com/v1.0/drive/items/6D4D5044C60EA101!108
POST data: {"name":"Call.docx","parentReference":{"id":"6D4D5044C60EA101!243"}}
> HTTP/2.0 409 Conflict
> content-length: 106
> content-type: application/json
> content-encoding: gzip
> p3p: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
> x-msnserver: BN2BAP4267A8D0B
> strict-transport-security: max-age=31536000; includeSubDomains
> access-control-allow-origin: https://app.qloudplus.com
> access-control-expose-headers: Content-Range, ETag, Location, Preference-Applied, X-Resource-ID
> x-qosstats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
> x-throwsite: 0bfa.2610
> x-asmversion: UNKNOWN; 19.77.809.2029
> x-msedge-ref: Ref A: B58F671A37B64281987356209A6DC7B3 Ref B: ATH01EDGE0107 Ref C: 2017-09-06T10:13:13Z
> date: Wed, 06 Sep 2017 10:13:12 GMT
> X-Firefox-Spdy: h2

PATCH https://api.onedrive.com/v1.0/drive/items/6D4D5044C60EA101!182
POST Data: {"name":"graph_api_check.txt","parentReference":{"id":"6D4D5044C60EA101!243"}}
> HTTP/2.0 500 Internal Server Error
> content-length: 96
> content-type: application/json
> content-encoding: gzip
> p3p: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
> x-msnserver: BN2BAP3F5D7BF6A
> strict-transport-security: max-age=31536000; includeSubDomains
> access-control-allow-origin: https://app.qloudplus.com
> access-control-expose-headers: Content-Range, ETag, Location, Preference-Applied, X-Resource-ID
> x-qosstats: {"ApiId":0,"ResultType":4,"SourcePropertyId":42,"TargetPropertyId":372}
> x-throwsite: 0bfa.2610
> x-asmversion: UNKNOWN; 19.77.809.2029
> x-msedge-ref: Ref A: 7D8ABA90146A47559BC15937C11FD911 Ref B: ATH01EDGE0107 Ref C: 2017-09-06T10:13:08Z
> date: Wed, 06 Sep 2017 10:13:07 GMT
> X-Firefox-Spdy: h2

**Comment by ificator** [comment]
Hi @johnlilis, when you are doing these moves are you executing the requests in parallel or sequentially?

**Comment by johnlilis** [comment]
Hi @ificator, thanks for the quick response.
The requests are sent asynchronously using angular $http calls.

**Comment by ificator** [comment]
If you make all of the move requests sequentially do you still see issues. I'm wondering if it's contention on parallel moves under the same parent.

**Comment by johnlilis** [comment]
Yes, when making the requests sequentially they don't seem to fail. This can be used as a fallback, however the process takes significantly longer to complete.

**Comment by ificator** [comment]
Closing stale issues.
