### ISSUE TITLE
One drive for business api Search file or folder with name

### ISSUE THREAD

**Issue by anildbest83** [OneDrive/onedrive-api-docs#696]
i want to search a file or folder based on its name only.

It is mentioned that the query text is used to search for items. Values may be matched across several fields including filename, metadata, and file content.

I used filter as well like this

/_api/v2.0/me/drive/items/01Z54FA3E**********2XOG2FQOJ5/search(q='u')?filter=contains(name,'u')

but it still return other items as well.

Is it possible to search based on name only?

**Comment by anildbest83** [comment]
@ificator 

Hi,

i m trying to sort data using following API rest call

```
/_api/v2.0/me/drive/items/01Z54FA3E********KCC2XOG2FQOJ5/children?top=200&orderby=lastModifiedDateTime%20desc

/_api/v2.0/me/drive/items/01Z54FA3**********2XOG2FQOJ5/children?top=200&orderby=size%20desc
```

but getting following in result

message=The property Last_x0020_Modified is not supported for OrderBy.
message=The property File_x0020_Size is not supported for OrderBy.

Please suggest

**Comment by anildbest83** [comment]
Anyone guide me on this?

**Comment by anildbest83** [comment]
Hi @rgregg will you please put some thoughts on this?

**Comment by anildbest83** [comment]
Hi @ificator any suggestion on this?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
