### ISSUE TITLE
code 503 and message is empty but return a html in body rather then JSON

### ISSUE THREAD

**Issue by shinjikao** [OneDrive/onedrive-api-docs#697]
I got a 503 error when fetch delta, this debug message like below:
url=https://api.onedrive.com/v1.0/drives('me')/items('9005F332ACBDB318!101')/view.delta?$top=200&$select=id%2cname%2csize%2ccreatedDateTime%2clastModifiedDateTime%2ccTag%2ceTag%2cparentReference%2cfile%2cfolder%2cdeleted&token=aTE09NjM2NDAyOTU4MTM2NDA7SUQ9OTAwNUYzMzJBQ0JEQjMxOCExMDE7TFI9NjM2NDAzMDkzNTU2Mzc7RVA9MTY7U0k9ODE7U0c9MTtTTz0yO1BJPTM ,code=503 , msg= , body=<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>OneDrive</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>Ref A: 7DF50CEFF7D94A2B858069FC1393CDB0 Ref B: TYO01EDGE0214 Ref C: 2017-09-06T15:50:37Z</span></div></div></body></html>

The problem is 
1.Message is empty in top level,
2.Inner error should be JSON format are wrapped in response body, but if return a HTML from webservice, client parser can't expectd a HTML format
3.Why return a HTML format rather then JSON? how to handle this ?

**Comment by ificator** [comment]
Thanks @shinjikao. We are tracking this issue with the above issue so I'm going to close this one to avoid duplication. Please feel free to comment on the other issue if you have anything else do add.
