### ISSUE TITLE
Custom facets support for OneDrive for Business

### ISSUE THREAD

**Issue by atkinchris** [OneDrive/onedrive-api-docs#699]
Custom facets are currently in exclusive preview for OneDrive personal. Is there a roadmap (or even plan to) bring these to OneDrive for Business, to allow the viewing and editing of custom metadata? Alternatively, is there an option in the current API to access custom metadata on OneDrive for Business?

>Custom facets are in preview and only available for OneDrive Personal at this time. https://dev.onedrive.com/misc/custom-metadata.htm

**Comment by ificator** [comment]
This is definitely something that's on our radar, but we unfortunately have nothing to share at this point.

**Comment by atkinchris** [comment]
Thanks for the information @ificator.

Is updating List items using a `MERGE` to the REST API still the best way to set custom metadata, in lieu of library support?

**Comment by atkinchris** [comment]
@ificator - is there anything to share on this for 2018?

**Comment by suparnavg** [comment]
@ificator - any updates on this request? Alternatively, if there's another way of getting/setting custom metadata, would appreciate it if you could let us know! Thanks in advance

**Comment by atkinchris** [comment]
@ificator - is there anything to share on this for 2019?

**Comment by ificator** [comment]
It's still on the radar. I'd suggest making sure it's tracked on https://onedrive.uservoice.com so it can be prioritized appropriately.
