### ISSUE TITLE
Resume uploads can't replace

### ISSUE THREAD

**Issue by zhuxuland** [OneDrive/onedrive-api-docs#7]
when use "@name.conflictBehavior": "replace", in uploading.

Still return file conflict error........ 
{"error":{"code":"nameAlreadyExists","message":"Relationship name already exists under the parent","innererror":{"code":"itemAlreadyExists","innererror":{"code":"relationshipNameAlreadyExists"}}}}

**Comment by ificator** [comment]
Thanks for pointing this out, we're looking in to it now.

**Comment by peternied** [comment]
@zhuxuland would it be possible to get a fiddler trace or the specific scenarios that you are using here?

**Comment by ificator** [comment]
I have a repro - looking in to why it's not doing the right thing now.

**Comment by zhuxuland** [comment]
thx for that.






发自 Windows 邮件





发件人: Brad Cleaver
发送时间: ‎2015‎年‎3‎月‎4‎日, ‎星期三 ‎3‎:‎50
收件人: OneDrive/onedrive-api-docs
抄送: 祝旭





I have a repro - looking in to why it's not doing the right thing now.

**Comment by zhuxuland** [comment]
there is something wrong when i sent the Fiddler zip.......type it instead. what's more , I did this with rest( User-Agent: RestSharp/104.4.0.0)

here is the session detail
--- create session:
request:

POST /v1.0/drive/items/C1089030D6F1B89!915:/111.rar:/upload.createSession HTTP/1.1
Authorization: Bearer EwBwAq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAS28R5mHERh/UKMfS5grD4jphNu0P4bED5+Kt7Wkk7IdTV25VXYDenHq9wxxxg+yT5W4gwECwba75Ux5W/o5X8dummY0zuaxgpYGe3ZiIVaP5X4+6rmSmfqNIWnPaBAKVZkPIULj+7WVpMD02ctwp4h6JSQpvA3FkKvw56d2s65ln5a/F/H98jjslfRqsLbmG8jlSqRc5VqzyXe5T/fu2Nrt9x1H7wDJ8UrulBgjWPc9qswp2m46xxX2yhs6b9htMBRVIjSfyYj9ODg3hnGTwvn9NK2+g5QjHcDEzM8LN/gK0J4+1O+4EWYDJWan2e3WjPDJDjXIDEs1C5uiflebq7IDZgAACMzfBIz40jDuQAFZa6u/GyRotSubLbPBX49HzvdHez52wW3hzjv8GtG0jRs5OERM+lsRA+wS7PCPyysUQDXD34x7Hc/oTzXxwUZl4QDJfNElteo27eSOt0YR6W84QlBpsPqcPoSm5fsTGpxN0NlxB5uM5U7AbNyHOo38ss9OxoJpeRDhU4xoe9T8fgveaXguidUHh2G22PQQTtj7WNL8DyweVxJ2mknujYD+XmW44wugubsaxNBqeFmLu30BRodHLVLNWWLaqb96Zb/hqJMSVjTt6m4F0Z/lWXzvdzMKqHsloiR0JPh28Z7W/E3lODM/Q9PXxqvS/tRdtvLI3VA9uVHAoVnzMxVhVUYBQTwcA6K8Zfe3w+eJjnGiEqhLX/JhpZsRj+l4ILlpr/XntW4YmSGgGWpKuPAXTMNEH2KCLRBEJ7uSaI0xryZVTlkB
Content-Type: application/json
{ "@name.conflictBehavio" : "replace" }

response:

HTTP/1.1 200 OK
expirationDateTime=2015-03-11T05:53:37.0206805Z
nextExpectedRanges 0-
uploadUrl=https://api.onedrive.com/up/eyJSZXNvdXJjZUlEIjoiQzEwODkwMzBENkYxQjg5ITkxNSIsIlJlbGF0aW9uc2hpcE5hbWUiOiIvMTExLnJhciIsIkFsaWFzIjpudWxsfQ/2m36TwX-AUSYlUrsElOzItUjCL3LzIM5jL17Jf6jnytHCGf59kD20xX0UkmBmw_Wep/eyJAbmFtZS5jb25mbGljdEJlaGF2aW9yIjpudWxsLCJOYW1lIjoiMTExLnJhciIsIlNpemUiOjB9

---upload fragment(only include the head and the tail)
a_ request:
PUT/up/eyJSZXNvdXJjZUlEIjoiQzEwODkwMzBENkYxQjg5ITkxNSIsIlJlbGF0aW9uc2hpcE5hbWUiOiIvMTExLnJhciIsIkFsaWFzIjpudWxsfQ/2m36TwX-AUSYlUrsElOzItUjCL3LzIM5jL17Jf6jnytHCGf59kD20xX0UkmBmw_Wep/eyJAbmFtZS5jb25mbGljdEJlaGF2aW9yIjpudWxsLCJOYW1lIjoiMTExLnJhciIsIlNpemUiOjB9 HTTP/1.1
Authorization: Bearer EwBwAq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAS28R5mHERh/UKMfS5grD4jphNu0P4bED5+Kt7Wkk7IdTV25VXYDenHq9wxxxg+yT5W4gwECwba75Ux5W/o5X8dummY0zuaxgpYGe3ZiIVaP5X4+6rmSmfqNIWnPaBAKVZkPIULj+7WVpMD02ctwp4h6JSQpvA3FkKvw56d2s65ln5a/F/H98jjslfRqsLbmG8jlSqRc5VqzyXe5T/fu2Nrt9x1H7wDJ8UrulBgjWPc9qswp2m46xxX2yhs6b9htMBRVIjSfyYj9ODg3hnGTwvn9NK2+g5QjHcDEzM8LN/gK0J4+1O+4EWYDJWan2e3WjPDJDjXIDEs1C5uiflebq7IDZgAACMzfBIz40jDuQAFZa6u/GyRotSubLbPBX49HzvdHez52wW3hzjv8GtG0jRs5OERM+lsRA+wS7PCPyysUQDXD34x7Hc/oTzXxwUZl4QDJfNElteo27eSOt0YR6W84QlBpsPqcPoSm5fsTGpxN0NlxB5uM5U7AbNyHOo38ss9OxoJpeRDhU4xoe9T8fgveaXguidUHh2G22PQQTtj7WNL8DyweVxJ2mknujYD+XmW44wugubsaxNBqeFmLu30BRodHLVLNWWLaqb96Zb/hqJMSVjTt6m4F0Z/lWXzvdzMKqHsloiR0JPh28Z7W/E3lODM/Q9PXxqvS/tRdtvLI3VA9uVHAoVnzMxVhVUYBQTwcA6K8Zfe3w+eJjnGiEqhLX/JhpZsRj+l4ILlpr/XntW4YmSGgGWpKuPAXTMNEH2KCLRBEJ7uSaI0xryZVTlkB
Content-Length: 10485760
Content-Range: bytes 0-10485759/58098433
Content-Type: application/octet-stream
{[data]}

a_response:
HTTP/1.1 202 Accepted
expirationDateTime=2015-03-11T05:53:37.0206805+00:00
(no size range here, different with the doc)


b_request:
PUT /up/eyJSZXNvdXJjZUlEIjoiQzEwODkwMzBENkYxQjg5ITkxNSIsIlJlbGF0aW9uc2hpcE5hbWUiOiIvMTExLnJhciIsIkFsaWFzIjpudWxsfQ/2m36TwX-AUSYlUrsElOzItUjCL3LzIM5jL17Jf6jnytHCGf59kD20xX0UkmBmw_Wep/eyJAbmFtZS5jb25mbGljdEJlaGF2aW9yIjpudWxsLCJOYW1lIjoiMTExLnJhciIsIlNpemUiOjB9 HTTP/1.1
Authorization: Bearer EwBwAq1DBAAUGCCXc8wU/zFu9QnLdZXy+YnElFkAAS28R5mHERh/UKMfS5grD4jphNu0P4bED5+Kt7Wkk7IdTV25VXYDenHq9wxxxg+yT5W4gwECwba75Ux5W/o5X8dummY0zuaxgpYGe3ZiIVaP5X4+6rmSmfqNIWnPaBAKVZkPIULj+7WVpMD02ctwp4h6JSQpvA3FkKvw56d2s65ln5a/F/H98jjslfRqsLbmG8jlSqRc5VqzyXe5T/fu2Nrt9x1H7wDJ8UrulBgjWPc9qswp2m46xxX2yhs6b9htMBRVIjSfyYj9ODg3hnGTwvn9NK2+g5QjHcDEzM8LN/gK0J4+1O+4EWYDJWan2e3WjPDJDjXIDEs1C5uiflebq7IDZgAACMzfBIz40jDuQAFZa6u/GyRotSubLbPBX49HzvdHez52wW3hzjv8GtG0jRs5OERM+lsRA+wS7PCPyysUQDXD34x7Hc/oTzXxwUZl4QDJfNElteo27eSOt0YR6W84QlBpsPqcPoSm5fsTGpxN0NlxB5uM5U7AbNyHOo38ss9OxoJpeRDhU4xoe9T8fgveaXguidUHh2G22PQQTtj7WNL8DyweVxJ2mknujYD+XmW44wugubsaxNBqeFmLu30BRodHLVLNWWLaqb96Zb/hqJMSVjTt6m4F0Z/lWXzvdzMKqHsloiR0JPh28Z7W/E3lODM/Q9PXxqvS/tRdtvLI3VA9uVHAoVnzMxVhVUYBQTwcA6K8Zfe3w+eJjnGiEqhLX/JhpZsRj+l4ILlpr/XntW4YmSGgGWpKuPAXTMNEH2KCLRBEJ7uSaI0xryZVTlkB
Content-Length: 5669633
Content-Range: bytes 52428800-58098432/58098433
Content-Type: application/octet-stream
{[data]}

b_response:

HTTP/1.1 409 Conflict
error
code=nameAlreadyExists
innererror
code=itemAlreadyExists
innererror
code=relationshipNameAlreadyExists
message=Relationship name already exists under the parent

**Comment by peternied** [comment]
Thanks a ton for getting us that request information, you found a bug, and we are working to get a fix out to resolve it.  It turns out that our logic to parse name conflict behavior from the request body is being completely ignored resulting in that file conflict error message.

**Comment by ificator** [comment]
This should be fixed now, please close this issue if you confirm or otherwise let us know if you're still seeing issues.

Thanks!

**Comment by zhuxuland** [comment]
Well, it works good.
There is something wrong with a low priority that in the end of the uploading session, a Status Code with 'Created' is expected, but one with 'OK' instead. It happened when I confirmed the issue mentioned above....However, it is easy for me to cover this issue.

Thanks @ificator  @peternied. 
and Appreciate it

**Comment by ificator** [comment]
Thanks @zhuxuland, we're working on a fix for that other issue you mentioned as we speak.
