### ISSUE TITLE
Unable to upload files between ~7.6GiB and 10 GiB in size with upload session

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#70]
I'm using the upload sessions functionality.

The maximum size of a file for OneDrive is 10GiB, or 10737418240 bytes.

Indeed, when I attempt to start uploading a file that's 10737418241 bytes, I get the following 400 error:
```{"error":{"code":"invalidArgument","message":"Max file size exceeded","innererror":{"code":"maxFileSizeExceeded"}}}```

However, I'm consistently getting errors when uploading large files less than 10GB.  When this issue occurs, I get a 500 error after the entire final chunk is uploaded.  When I try to upload the file again,  the same error occurs.

The error received is:
```{"error":{"code":"generalException","message":"Assertion Failure While Processing"}}```

I've tried uploading files with the following sizes:

6GiB file (6442450944 bytes): Successful.
7 GiB file (7516192768 bytes): Successful.
7.25GiB file (7784628224 bytes): Successful.
7.5GiB file (8053063680 bytes): Successful.
7.5GiB + 1B file (8053063681 bytes): Successful.
~7.58GiB file (8140000000 bytes): Failure
7.625GiB file (8187281408 bytes): Failure
7.75GiB file (8321499136 bytes): Failure
~7.82GiB file (8400000000 bytes): Failure
7.875GiB file (8455716864 bytes): Failure
8GiB file (8589934592 bytes): Failure.
9GiB file (9663676416 bytes): Failure.
10GiB file (10737418240 bytes) Failure.

I think the file size that causes the issue is somewhere between 8053063681 and 8140000000 bytes.

I assume it's unrelated, but I'm experiencing very slow uploads, averaging about 12mbit/second.  It makes it difficult to test and isolate this issue as each test case takes well over an hour.  It's possible I'm being throttled since I've been uploading hundreds of gigabytes during my testing.

**Comment by ificator** [comment]
That definitely looks like an unexpected error. Could you provide all of the HTTP headers in the error response?

**Comment by Lyrrad** [comment]
A 500 error is returned:
Error: ```{"error":{"code":"generalException","message":"Assertion Failure While Processing"}}```
Headers: ```{'x-wlsproxy': 'CH3301____PAP115', 'content-length': '84', 'content-type': 'application/json; charset=utf-8', 'x-qosstats': '{"ApiId":0,"ResultType":4,"SourcePropertyId":0,"TargetPropertyId":42}', 'x-msnserver': 'SN3301____PAP048', 'date': 'Tue, 07 Apr 2015 00:37:05 GMT', 'x-throwsite': '4aea.ab31', 'via': '1.1 CH3301____PAP115 (wls-colorado)', 'p3p': 'CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"', 'x-asmversion': 'UNKNOWN; 19.17.0.0', 'server': 'Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'}```

From another instance of the error: ```{'content-length': '84', 'p3p': 'CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"', 'via': '1.1 DM2304____PAP095 (wls-colorado)', 'x-asmversion': 'UNKNOWN; 19.17.0.0', 'x-qosstats': '{"ApiId":0,"ResultType":4,"SourcePropertyId":0,"TargetPropertyId":42}', 'server': 'Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0', 'content-type': 'application/json; charset=utf-8', 'date': 'Mon, 06 Apr 2015 23:39:48 GMT', 'x-msnserver': 'SN3301____PAP156', 'x-wlsproxy': 'DM2304____PAP095', 'x-throwsite': '4aea.ab31'}```

**Comment by ificator** [comment]
Looks like we have an idea what's going on - hopefully we can get a fix out ASAP. Thanks for reporting!

**Comment by ificator** [comment]
Looking in to this a little deeper, can you tell me what chunk size you're using? I believe this issue may not occur if you use a multiple of 320KB (See http://onedrive.github.io/items/upload_large_files.htm#best-practices). We'll obviously still work on fixing the underlying issue, but this may at least unblock you.

**Comment by Lyrrad** [comment]
I'm using 4MiB (4194304) bytes.

There's a bit of a contradiction in the documentation, where it recommends multiples of 320KB for the fragment size (327680 bytes?), while also suggesting 4MB as a recommended fragment size.  While the 10MB recommendation is a multiple of 320KB for some common definitions of MB and KB (specifically MiB and KiB), the 4MB recommendation isn't.

By 10MB, do you mean 10*2^20 bytes? (10485760 bytes)

I'll give 10MiB a try.

**Comment by ificator** [comment]
Correct, it should be 10MiB. I'll follow up on cleaning up the documentation.

**Comment by Lyrrad** [comment]
Okay.  I was able to upload a 9.65GiB file with a 10MiB fragment size.

I'd recommend a 5MiB or 2.5MiB fragment size as an alternative to the 4MiB recommendation in the documentation.

**Comment by rgregg** [comment]
I just pushed a change to the doc to try and clarify this requirement.
