### ISSUE TITLE
Error 403 on file upload attempt

### ISSUE THREAD

**Issue by khalibloo** [OneDrive/onedrive-api-docs#701]
I get an Access Denied response when I try to upload a file or even create a folder in my appfolder. This appears to be a permission issue, and I'm not entirely surprised. The docs say that I should use the scope `onedrive.appfolder`, however, this results in an error message saying my scope is invalid. I then tried `files.readwrite.appfolder`. No error message in authentication, but it doesn't seem to allow me to access the appfolder.

Here's the request
```
PUT https://graph.microsoft.com/v1.0/me/drive/special/approot:/favess.txt:/content
Authorization: bearer xxxxxx, Content-Type: application/json

JSON.stringify(data)
```

My app has the following delegated permissions:
email, files.readwrite.appfolder, files.readwrite.all, files.readwrite, profile

Background:
The app is a regular react/redux SPA.

**Comment by ificator** [comment]
We've had some other reports of this so I'm going to close the issue and instead ask you to track https://github.com/OneDrive/onedrive-api-docs/issues/701. Unfortunately it hasn't had much traction so I'll take it and make sure it's investigated.
