### ISSUE TITLE
Delta gives a 410 Gone response, start fresh enumeration

### ISSUE THREAD

**Issue by shinjikao** [OneDrive/onedrive-api-docs#702]
The documentation said " a Location header containing a new nextLink that starts a fresh delta enumeration from scratch".
[https://dev.onedrive.com/items/view_delta.htm#last-page-no-more-changes]

Does it mean that all delta events from beginning of history of this account will be returned?
E.g. I'm running the app for month, and uploaded bunch of files, so 1000 delta events generated since then. It means we have to go through 1000 delta events again? I think it can be the only way, just want to confirm.

**Comment by ificator** [comment]
That's correct - it will remain that you'll essentially have to enumerate through ALL items again in much the same way as you would if you were to call `delta` without any tokens.
