### ISSUE TITLE
[ODB] set new added user share permission will return null id

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#703]
Hi,
After I added a new user and add my file with shared permission to this guy on portal web site,
I list permission for this file it returns null of granted_to_user_id

It is good for rest field permission_id or roles, but just lost the granted_to_user_id

After a while, the granted_to_user_id shows up

**Comment by ificator** [comment]
I'm guessing this is some kind of user propagation delay. Do you know roughly how long it is before the `grantedTo` value gets to the expected state?
