### ISSUE TITLE
If there's a 2GB file size limit for each file that's uploaded to the OneDrive for Business?

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#704]
When I upload a file which is greater than 2GB to the OneDrive for Business, there will result in the error 
_400 {"error":{"code":"invalidRequest","message":"The Content-Range header is missing or malformed."}}_
when the uploaded size reaches 2GB, and I used a trial OneDrive for Business account. So I want to know if there's a 2GB file size limit for each file that's uploaded to the OneDrive for Business for some situation?

**Comment by ificator** [comment]
@imkk  can you provide an example of what your `Content-Range` header looks like when you get this error?

OneDrive for Business definitely supports files larger than 2GB via this API.

**Comment by ificator** [comment]
One "gotcha" to be careful with is the type you use to track your begin and end range values. If you're using a 32-bit integer and increment your end range over 2GB it can wrap around giving a negative number.

For example, this:
```
    int begin = int.MaxValue - 10;
    int end = begin + 20;
    long total = int.MaxValue + 100L;

    $"Content-Range: bytes {begin}-{end}/{total}".Dump();
```
Results in:
```
Content-Range: bytes 2147483637--2147483639/2147483747
```

**Comment by imkk** [comment]
@ificator you got it! Thank you very much. I have solved it.

**Comment by ificator** [comment]
That's great, thanks for letting us know!
