### ISSUE TITLE
Extract file text using onedrive api

### ISSUE THREAD

**Issue by judebigj** [OneDrive/onedrive-api-docs#706]
I am currently evaluating OneDrive SDK and so far I am able to connect to account (using Graph API)and download file content using stream. However, I am looking for a way to read only the text content (for indexing purpose) using the SDK for different types of files(pdf,xls,zip etc.) instead of going by the conventional approach of downloading the complete file and then extracting the text using some text extracting api and then index the file, which would be a time consuming task. I am aware that the SDK has its own search api, but it lacks ability to do complicated search like regular expression search, wildcard etc (please correct me if I am wrong). I believe One drive does its own indexing for each file which helps a user to do the basic search. So, is there any way I can get the text content of each file using the SDK?

**Comment by denis1stomin** [comment]
My quite similar request
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/39153640-onedrive-rest-api-format-file-content-as-a-plain
Please vote in the case you think it is useful.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
