### ISSUE TITLE
[ODB] view.delta response misses shared field

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#714]
Hello,

Once view.delta response would contain **shared** field to indicate the file own its permissions.
But now it seems to be disappeared.

How can we guarantee the permission status when we receive a change from view.delta API?

Thank you!

**Comment by ificator** [comment]
Hi @joewutaiwan, we made a change in this area and it looks like there was a sequencing issue. We've turned off the behavior until the prerequisites are in the appropriate state.
