### ISSUE TITLE
How to test refresh token expiry for Sharepoint online and both oneDrive personal and business repositories 

### ISSUE THREAD

**Issue by Varun212** [OneDrive/onedrive-api-docs#715]
Ways of testing expiry of a refresh token in cloud repositories And I am in my application

**Comment by mlafleur** [comment]
OneDrive isn't directly responsible for the tokens. Determining when your token expires depends on several factors. See [Azure Active Directory v2.0 tokens reference](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-tokens) for details.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
