### ISSUE TITLE
[ODB] how to add permission with special name alias

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#718]
Hello,

All my files have a special permission which is named by Chinese means 'All external users'
![image](https://user-images.githubusercontent.com/12619781/31062012-bc1064b2-a759-11e7-86aa-8f50f990eccf.png)

And it is the resp. section
```
{
            "grantedTo": {
                "user": {
                    "displayName": "外部使用者以外的所有人"
                }
            },
            "id": "YzowLS5mfHJvbGVtYW5hZ2VyfHNwby1ncmlkLWFsbC11c2Vycy9hYWVmNzIwOC02Njg3LTQzMGQtOWZmOS0xMjQxZTlkMzY5NDU",
            "roles": [
                "read"
            ]
},
```

How can I add this permission?

Thanks

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
