### ISSUE TITLE
Creating an upload session on a normal OD folder returns itemNotFound error

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#719]
Request:

```
POST https://{tenant}-my.sharepoint.com/personal/{user}/_api/v2.0/drive/items/01TF3QQUMVOCW3WKYFBNBKYMWOWBCSQZ62:/GoBack.aspx:/createUploadSession

{
	"item": {
		"@microsoft.graph.conflictBehavior": "replace"
	}
}
```

Response:
```json
request-id: 93061f9e-60cf-4000-7862-09c7a9c0f563

{
    "error": {
        "code": "itemNotFound",
        "message": "The resource could not be found."
    }
}
```

I thought maybe the parent (`01TF3QQUMVOCW3WKYFBNBKYMWOWBCSQZ62`) didn't exist for some reason, so I tried a get on it. It does exist. I'm also trying to replace the `GoBack.aspx` file on it, so I tried getting it to check if it existed. It does exist.

Request:
```
GET https://{tenant}-my.sharepoint.com/personal/{user}/_api/v2.0/drive/items/01TF3QQUMVOCW3WKYFBNBKYMWOWBCSQZ62:/GoBack.aspx
```

Response:
```json
request-id: 9c061f9e-8012-4000-7862-0fab497d5477

{...full json for the item...}
```

Now, given that it's an ASPX file being replaced, maybe custom scripting is off. It might be off, I don't have access to the tenant admin dashboard. But even then, the error would seem misleading. I don't know what item cannot be found.

I also tried creating the upload session by referring to the `GoBack.aspx` file by its ID:
```
POST https://{tenant}-my.sharepoint.com/personal/{user}/_api/v2.0/drive/items/01TF3QQUOMGJPGMMZAHJELY7UBRUZJKS3W/createUploadSession
```

It would still return the `404` error:
```json
request-id: 1c071f9e-c047-4000-76d7-f5412d57d87f

{
    "error": {
        "code": "itemNotFound",
        "message": "The resource could not be found."
    }
}
```

**Comment by ificator** [comment]
This is definitely a strange one @dluces. Do you know if using `createUploadSession` works for other file types in the same parent folder? If able, can you provide the full path of the `GoBack.aspx`? If you cannot divulge the path, are you able to determine if the path contains only alpha-numeric characters, or if there are other characters?

**Comment by dluces** [comment]
Hi @ificator. Yes, the path contains only alphanumeric characters (I'm not able to post it here unfortunately). I am also able to upload other files using `createUploadSession` to the parent folder.
Request (to create `GoBack.txt` instead):
```
POST https://{tenant}-my.sharepoint.com/personal/{user}/_api/v2.0/drive/items/01TF3QQUMVOCW3WKYFBNBKYMWOWBCSQZ62:/GoBack.txt:/createUploadSession
```

Response:
```
request-id: bdb41f9e-20b6-4000-7862-00d714381964

{
    "@odata.context": "https://{tenant}-my.sharepoint.com/personal/{user}/_api/v2.0/$metadata#oneDrive.uploadSession",
    "expirationDateTime": "2017-10-04T20:56:18.4727466Z",
    "nextExpectedRanges": [
        "0-"
    ],
    "uploadUrl": "{upload_url}"
}
```

**Comment by ificator** [comment]
I haven't been able to reproduce the issue yet, but I'm convinced it's an issue in us somewhere so I'll mark it as a bug.

@dluces can you tell me what scopes you have in the token? Is the caller the owner, a different user, or app-only?

**Comment by dluces** [comment]
@ificator Sorry, I was having issues with my email notifications and I just saw your response.

The token has the following roles:
```
  "roles": [
    "User.ReadWrite.All",
    "TermStore.ReadWrite.All",
    "User.Read.All",
    "Sites.Manage.All",
    "TermStore.Read.All",
    "Sites.Read.All",
    "Sites.ReadWrite.All",
    "Sites.FullControl.All"
  ]
```

And the caller is an admin impersonating another user. So not the same user. We use an admin token that we use to impersonate all users in a tenant.

**Comment by ificator** [comment]
No worries @dluces. When you say admin do you mean an app-only token?

**Comment by dluces** [comment]
@ificator Good question, I'm not sure what you mean by app-only token. We have an Azure app. A tenant admin goes to our app and logs into ODB with their credentials. We then get tokens (access, id and refresh). We use that access token from the initial auth to get access tokens for the different resources we use (e.g. Graph API, the tenant URL for OneDrive sites, etc).
An access token for the tenant URL ({tenant}-my.sharepoint.com) lets us manipulate all of the user sites. The roles I posted above are the ones we have in the access token we use for the OneDrive sites.
The initial auth token (the one we use to fetch access tokens for the different resources) have the following scopes:
```
AllSites.FullControl
AllSites.Manage
AllSites.Read
AllSites.Write
MyFiles.Read
MyFiles.Write
Sites.Search.All
TermStore.Read.All
TermStore.ReadWrite.All
User.Read.All
User.ReadWrite.All
```

Would that be an app-only token?

**Comment by ificator** [comment]
I believe if you have `roles` instead of `scp` it's app-only so I'll try to repro under those conditions. So far I've run across some unexpected permission requirements for aspx files, but nothing that manifests in the 404 that you're seeing.

**Comment by dluces** [comment]
@ificator That's right, the access token that I use with the OneDrive API (resource-specific access token) has `roles` and not `scp`. The access token that I use to fetch the resource-specific access token has `scp` and not `roles` and the scope list is the list that I sent in my previous comment.

**Comment by ificator** [comment]
@dluces I've been unable to get a repro for this issue on my side. I don't suppose you've noticed anything new that could help narrow down what's going on?

**Comment by dluces** [comment]
@ificator Unfortunately, nothing new on my side. Our client decided not to upload this file at the moment. We do come around this issue every once in a while though. So if I get another case, I'll be updating this issue with more information.

**Comment by ificator** [comment]
I'm to close this so it doesn't sit open forever. If we get more information, please feel free to reactivate.

**Comment by dluces** [comment]
@ificator Makes sense, I'll re-open it if I encounter this issue again. Thanks !
