### ISSUE TITLE
Fragment upload fails on python3.5 "This access token is not valid on this endpoint."

### ISSUE THREAD

**Issue by gojohnkevin** [OneDrive/onedrive-api-docs#720]
Reference for #690 

`GET
{'Authorization': 'bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyIsImtpZCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyJ9.eyJhdWQiOiJodHRwczovL2xhemFkYWdyb3VwLW15LnNoYXJlcG9pbnQuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMzYzYTIzNTQtZjc3MC00YzZlLTliZWQtYTVmODJmMTNkOTA5LyIsImlhdCI6MTUwNzEwMzc3NiwibmJmIjoxNTA3MTAzNzc2LCJleHAiOjE1MDcxMDc2NzYsImFjciI6IjEiLCJhaW8iOiJBVFFBeS84RkFBQUFLdkczMUVSUGowRzZTS0dWZ2ZBSENxSFJmUWtpWjltYitQT1ZWdU5Dc0M4b0tBaGt6cUpIOGlEbHNXaENlQk9oIiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJDTEkgQWNjZXNzIiwiYXBwaWQiOiI4MzRkZjcyZS0wYTA3LTRkOWMtYjVkNi00MGUyNTBlMjczOTEiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IkdvIiwiZ2l2ZW5fbmFtZSI6IktldmluIiwiaXBhZGRyIjoiMTE4LjE4OS4xMzUuMzgiLCJuYW1lIjoiS2V2aW4gR28gKExhemFkYSBHcm91cCkiLCJvaWQiOiI0NzlkZjlkMC1mOWU4LTQ3NmEtYTMyZS04MjFjNjI0ZGRjYzAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMjI5OTUxNTQxMi03NDU3MzgwMzUtMzQxNzM0Njg4Ni0zNTY0OCIsInB1aWQiOiIxMDAzMDAwMDlFRDA3NUFBIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWQuU2hhcmVkIENhbGVuZGFycy5SZWFkV3JpdGUgQ2FsZW5kYXJzLlJlYWRXcml0ZS5TaGFyZWQgQ29udGFjdHMuUmVhZCBDb250YWN0cy5SZWFkLlNoYXJlZCBDb250YWN0cy5SZWFkV3JpdGUgQ29udGFjdHMuUmVhZFdyaXRlLlNoYXJlZCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWQuU2VsZWN0ZWQgRmlsZXMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFwcEZvbGRlciBGaWxlcy5SZWFkV3JpdGUuU2VsZWN0ZWQgUGVvcGxlLlJlYWQuQWxsIFNpdGVzLlJlYWQuQWxsIFNpdGVzLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIFVzZXIuUmVhZFdyaXRlLkFsbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IllrT3BiYW1Idk5kc2FHVVNIeXZDdXJCdTdIRU9tNGlWSDljeGMyVGJGV1EiLCJ0aWQiOiIzNjNhMjM1NC1mNzcwLTRjNmUtOWJlZC1hNWY4MmYxM2Q5MDkiLCJ1bmlxdWVfbmFtZSI6ImtldmluLmdvQGxhemFkYS5jb20iLCJ1cG4iOiJrZXZpbi5nb0BsYXphZGEuY29tIiwidmVyIjoiMS4wIn0.nH_V4GvR5NMfKs_-ayCU2etONzngYXbl0YUcKEDdnhh_UM6P8YKUQg5LjckVtb7u7GlrHwOFyjRzhuS7zwBBQDuMdtnjbIW8Kr0x32SOgbLihRT6jVqL4-rgsufNKhBuIy7U_60OsQNWL2ejZT1mRj72e4MMYQke68bSc5xYH7qMyLCHbXDP_g4pbNDeJqDRkO0RGiBhinVL6SM3hgrVOCwFe7_DUgkYtMPwXdkXKXt9soDi3uTD6OMt4zVNB2lbf7-ZzWzm1FrPZvil0Xqs1Mmb1LzVWOkRM7s2-Win-y_0G3i3U58ZuwwCrxs-S1hepkoisCWOnSOFnEtbUaUWPQ', 'X-RequestStats': 'SDK-Version=python-v1.1.8'}
https://xxxx.sharepoint.com/_api/v2.0/drives/me/root:/:

GET
{'Authorization': 'bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyIsImtpZCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyJ9.eyJhdWQiOiJodHRwczovL2xhemFkYWdyb3VwLW15LnNoYXJlcG9pbnQuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMzYzYTIzNTQtZjc3MC00YzZlLTliZWQtYTVmODJmMTNkOTA5LyIsImlhdCI6MTUwNzEwMzc3NiwibmJmIjoxNTA3MTAzNzc2LCJleHAiOjE1MDcxMDc2NzYsImFjciI6IjEiLCJhaW8iOiJBVFFBeS84RkFBQUFLdkczMUVSUGowRzZTS0dWZ2ZBSENxSFJmUWtpWjltYitQT1ZWdU5Dc0M4b0tBaGt6cUpIOGlEbHNXaENlQk9oIiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJDTEkgQWNjZXNzIiwiYXBwaWQiOiI4MzRkZjcyZS0wYTA3LTRkOWMtYjVkNi00MGUyNTBlMjczOTEiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IkdvIiwiZ2l2ZW5fbmFtZSI6IktldmluIiwiaXBhZGRyIjoiMTE4LjE4OS4xMzUuMzgiLCJuYW1lIjoiS2V2aW4gR28gKExhemFkYSBHcm91cCkiLCJvaWQiOiI0NzlkZjlkMC1mOWU4LTQ3NmEtYTMyZS04MjFjNjI0ZGRjYzAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMjI5OTUxNTQxMi03NDU3MzgwMzUtMzQxNzM0Njg4Ni0zNTY0OCIsInB1aWQiOiIxMDAzMDAwMDlFRDA3NUFBIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWQuU2hhcmVkIENhbGVuZGFycy5SZWFkV3JpdGUgQ2FsZW5kYXJzLlJlYWRXcml0ZS5TaGFyZWQgQ29udGFjdHMuUmVhZCBDb250YWN0cy5SZWFkLlNoYXJlZCBDb250YWN0cy5SZWFkV3JpdGUgQ29udGFjdHMuUmVhZFdyaXRlLlNoYXJlZCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWQuU2VsZWN0ZWQgRmlsZXMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFwcEZvbGRlciBGaWxlcy5SZWFkV3JpdGUuU2VsZWN0ZWQgUGVvcGxlLlJlYWQuQWxsIFNpdGVzLlJlYWQuQWxsIFNpdGVzLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIFVzZXIuUmVhZFdyaXRlLkFsbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IllrT3BiYW1Idk5kc2FHVVNIeXZDdXJCdTdIRU9tNGlWSDljeGMyVGJGV1EiLCJ0aWQiOiIzNjNhMjM1NC1mNzcwLTRjNmUtOWJlZC1hNWY4MmYxM2Q5MDkiLCJ1bmlxdWVfbmFtZSI6ImtldmluLmdvQGxhemFkYS5jb20iLCJ1cG4iOiJrZXZpbi5nb0BsYXphZGEuY29tIiwidmVyIjoiMS4wIn0.nH_V4GvR5NMfKs_-ayCU2etONzngYXbl0YUcKEDdnhh_UM6P8YKUQg5LjckVtb7u7GlrHwOFyjRzhuS7zwBBQDuMdtnjbIW8Kr0x32SOgbLihRT6jVqL4-rgsufNKhBuIy7U_60OsQNWL2ejZT1mRj72e4MMYQke68bSc5xYH7qMyLCHbXDP_g4pbNDeJqDRkO0RGiBhinVL6SM3hgrVOCwFe7_DUgkYtMPwXdkXKXt9soDi3uTD6OMt4zVNB2lbf7-ZzWzm1FrPZvil0Xqs1Mmb1LzVWOkRM7s2-Win-y_0G3i3U58ZuwwCrxs-S1hepkoisCWOnSOFnEtbUaUWPQ', 'X-RequestStats': 'SDK-Version=python-v1.1.8'}
https://xxxx.sharepoint.com/_api/v2.0/drives/me/root:/:

POST
{'Authorization': 'bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyIsImtpZCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyJ9.eyJhdWQiOiJodHRwczovL2xhemFkYWdyb3VwLW15LnNoYXJlcG9pbnQuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMzYzYTIzNTQtZjc3MC00YzZlLTliZWQtYTVmODJmMTNkOTA5LyIsImlhdCI6MTUwNzEwMzc3NiwibmJmIjoxNTA3MTAzNzc2LCJleHAiOjE1MDcxMDc2NzYsImFjciI6IjEiLCJhaW8iOiJBVFFBeS84RkFBQUFLdkczMUVSUGowRzZTS0dWZ2ZBSENxSFJmUWtpWjltYitQT1ZWdU5Dc0M4b0tBaGt6cUpIOGlEbHNXaENlQk9oIiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJDTEkgQWNjZXNzIiwiYXBwaWQiOiI4MzRkZjcyZS0wYTA3LTRkOWMtYjVkNi00MGUyNTBlMjczOTEiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IkdvIiwiZ2l2ZW5fbmFtZSI6IktldmluIiwiaXBhZGRyIjoiMTE4LjE4OS4xMzUuMzgiLCJuYW1lIjoiS2V2aW4gR28gKExhemFkYSBHcm91cCkiLCJvaWQiOiI0NzlkZjlkMC1mOWU4LTQ3NmEtYTMyZS04MjFjNjI0ZGRjYzAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMjI5OTUxNTQxMi03NDU3MzgwMzUtMzQxNzM0Njg4Ni0zNTY0OCIsInB1aWQiOiIxMDAzMDAwMDlFRDA3NUFBIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWQuU2hhcmVkIENhbGVuZGFycy5SZWFkV3JpdGUgQ2FsZW5kYXJzLlJlYWRXcml0ZS5TaGFyZWQgQ29udGFjdHMuUmVhZCBDb250YWN0cy5SZWFkLlNoYXJlZCBDb250YWN0cy5SZWFkV3JpdGUgQ29udGFjdHMuUmVhZFdyaXRlLlNoYXJlZCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWQuU2VsZWN0ZWQgRmlsZXMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFwcEZvbGRlciBGaWxlcy5SZWFkV3JpdGUuU2VsZWN0ZWQgUGVvcGxlLlJlYWQuQWxsIFNpdGVzLlJlYWQuQWxsIFNpdGVzLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIFVzZXIuUmVhZFdyaXRlLkFsbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IllrT3BiYW1Idk5kc2FHVVNIeXZDdXJCdTdIRU9tNGlWSDljeGMyVGJGV1EiLCJ0aWQiOiIzNjNhMjM1NC1mNzcwLTRjNmUtOWJlZC1hNWY4MmYxM2Q5MDkiLCJ1bmlxdWVfbmFtZSI6ImtldmluLmdvQGxhemFkYS5jb20iLCJ1cG4iOiJrZXZpbi5nb0BsYXphZGEuY29tIiwidmVyIjoiMS4wIn0.nH_V4GvR5NMfKs_-ayCU2etONzngYXbl0YUcKEDdnhh_UM6P8YKUQg5LjckVtb7u7GlrHwOFyjRzhuS7zwBBQDuMdtnjbIW8Kr0x32SOgbLihRT6jVqL4-rgsufNKhBuIy7U_60OsQNWL2ejZT1mRj72e4MMYQke68bSc5xYH7qMyLCHbXDP_g4pbNDeJqDRkO0RGiBhinVL6SM3hgrVOCwFe7_DUgkYtMPwXdkXKXt9soDi3uTD6OMt4zVNB2lbf7-ZzWzm1FrPZvil0Xqs1Mmb1LzVWOkRM7s2-Win-y_0G3i3U58ZuwwCrxs-S1hepkoisCWOnSOFnEtbUaUWPQ', 'Content-Type': 'application/json', 'X-RequestStats': 'SDK-Version=python-v1.1.8'}
https://xxxx.sharepoint.com/_api/v2.0/drives/me/items/01HWPZQB56Y2GOVW7725BZO354PWSELRRZ/children/PDI.zip/upload.createSession

PUT
{'Authorization': 'bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyIsImtpZCI6IkhIQnlLVS0wRHFBcU1aaDZaRlBkMlZXYU90ZyJ9.eyJhdWQiOiJodHRwczovL2xhemFkYWdyb3VwLW15LnNoYXJlcG9pbnQuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMzYzYTIzNTQtZjc3MC00YzZlLTliZWQtYTVmODJmMTNkOTA5LyIsImlhdCI6MTUwNzEwMzc3NiwibmJmIjoxNTA3MTAzNzc2LCJleHAiOjE1MDcxMDc2NzYsImFjciI6IjEiLCJhaW8iOiJBVFFBeS84RkFBQUFLdkczMUVSUGowRzZTS0dWZ2ZBSENxSFJmUWtpWjltYitQT1ZWdU5Dc0M4b0tBaGt6cUpIOGlEbHNXaENlQk9oIiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJDTEkgQWNjZXNzIiwiYXBwaWQiOiI4MzRkZjcyZS0wYTA3LTRkOWMtYjVkNi00MGUyNTBlMjczOTEiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IkdvIiwiZ2l2ZW5fbmFtZSI6IktldmluIiwiaXBhZGRyIjoiMTE4LjE4OS4xMzUuMzgiLCJuYW1lIjoiS2V2aW4gR28gKExhemFkYSBHcm91cCkiLCJvaWQiOiI0NzlkZjlkMC1mOWU4LTQ3NmEtYTMyZS04MjFjNjI0ZGRjYzAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMjI5OTUxNTQxMi03NDU3MzgwMzUtMzQxNzM0Njg4Ni0zNTY0OCIsInB1aWQiOiIxMDAzMDAwMDlFRDA3NUFBIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWQuU2hhcmVkIENhbGVuZGFycy5SZWFkV3JpdGUgQ2FsZW5kYXJzLlJlYWRXcml0ZS5TaGFyZWQgQ29udGFjdHMuUmVhZCBDb250YWN0cy5SZWFkLlNoYXJlZCBDb250YWN0cy5SZWFkV3JpdGUgQ29udGFjdHMuUmVhZFdyaXRlLlNoYXJlZCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWQuU2VsZWN0ZWQgRmlsZXMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFwcEZvbGRlciBGaWxlcy5SZWFkV3JpdGUuU2VsZWN0ZWQgUGVvcGxlLlJlYWQuQWxsIFNpdGVzLlJlYWQuQWxsIFNpdGVzLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIFVzZXIuUmVhZFdyaXRlLkFsbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IllrT3BiYW1Idk5kc2FHVVNIeXZDdXJCdTdIRU9tNGlWSDljeGMyVGJGV1EiLCJ0aWQiOiIzNjNhMjM1NC1mNzcwLTRjNmUtOWJlZC1hNWY4MmYxM2Q5MDkiLCJ1bmlxdWVfbmFtZSI6ImtldmluLmdvQGxhemFkYS5jb20iLCJ1cG4iOiJrZXZpbi5nb0BsYXphZGEuY29tIiwidmVyIjoiMS4wIn0.nH_V4GvR5NMfKs_-ayCU2etONzngYXbl0YUcKEDdnhh_UM6P8YKUQg5LjckVtb7u7GlrHwOFyjRzhuS7zwBBQDuMdtnjbIW8Kr0x32SOgbLihRT6jVqL4-rgsufNKhBuIy7U_60OsQNWL2ejZT1mRj72e4MMYQke68bSc5xYH7qMyLCHbXDP_g4pbNDeJqDRkO0RGiBhinVL6SM3hgrVOCwFe7_DUgkYtMPwXdkXKXt9soDi3uTD6OMt4zVNB2lbf7-ZzWzm1FrPZvil0Xqs1Mmb1LzVWOkRM7s2-Win-y_0G3i3U58ZuwwCrxs-S1hepkoisCWOnSOFnEtbUaUWPQ', 'X-RequestStats': 'SDK-Version=python-v1.1.8', 'Content-Range': 'bytes 0-10485759/641870611', 'Content-Length': '10485760'}
https://xxxx.sharepoint.com/personal/xxxx/_api/v2.0/drives/b!4isAREOvYUCY8lRjTpHzWa21UOdOhqlItR1uPJUPLe-Iw_UNO2jaRJYTyaLQZP0l/items/01HWPZQB56Y2GOVW7725BZO354PWSELRRZ/uploadSession?tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbGF6YWRhZ3JvdXAtbXkuc2hhcmVwb2ludC5jb21AMzYzYTIzNTQtZjc3MC00YzZlLTliZWQtYTVmODJmMTNkOTA5IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTUwNzEwNDA3OSIsImV4cCI6IjE1MDcxOTA0NzkiLCJlbmRwb2ludHVybCI6InNDeEdPdE1GZ3MvVGRPeUptWVFvaURwblhoalJwanhad1JSTkZBVEYzdkE9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIyOTkiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik5ERTRPVEZtT1dVdFpqQXhOQzAwTURBd0xUZGhZVEV0WlRka05EZGpaREUyTVRNdyIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJORFF3TURKaVpUSXRZV1kwTXkwME1EWXhMVGs0WmpJdE5UUTJNelJsT1RGbU16VTUiLCJhcHBpZCI6IjgzNGRmNzJlLTBhMDctNGQ5Yy1iNWQ2LTQwZTI1MGUyNzM5MSIsInRpZCI6IjM2M2EyMzU0LWY3NzAtNGM2ZS05YmVkLWE1ZjgyZjEzZDkwOSIsInVwbiI6ImtldmluLmdvQGxhemFkYS5jb20iLCJwdWlkIjoiMTAwMzAwMDA5ZWQwNzVhYSIsInNjcCI6Im15ZmlsZXMucmVhZCBhbGxmaWxlcy5yZWFkIG15ZmlsZXMud3JpdGUgYWxsZmlsZXMud3JpdGUgYWxsc2l0ZXMucmVhZCBhbGxzaXRlcy53cml0ZSBhbGxwcm9maWxlcy5yZWFkIGFsbHByb2ZpbGVzLnJlYWQgYWxscHJvZmlsZXMud3JpdGUiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.dUZhR2d0dEQ3eHhVUHFQeDBqb2twYXBmalpCSUtCWkEyUXRsejJOcTY5bz0&overwrite=True&rename=False&guid=%274e059995-0d92-484e-a93f-79a058b3488f%27&path=%27%7Etmp88_PDI.zip%27
<onedrivesdk.helpers.file_slice.FileSlice object at 0x7fa9aa97a9e8>

{'error_description': 'This access token is not valid on this endpoint.', 'error': 'invalid_request'}
invalid_request`

**Comment by ificator** [comment]
There are a couple of things that look out of the ordinary here:
1. You should not be providing the `Authorization` header for the `PUT`, although this will not result in the failure.
2. The URL that is being used in the `PUT` request appears to have been modified. Specifically the query string parameters are in a different order, and it's most likely this that's triggering the failure.

Can you look at your code and make sure that the URL is not being modified before it's used?

**Comment by gojohnkevin** [comment]
Hello @ificator you we're right about number 2. problem is python3.5 and below doesn't retain the position of values in the dictionary. 

Thank you

**Comment by gojohnkevin** [comment]
I have added a pull request in the onedrivesdk to fix this issue.

**Comment by ificator** [comment]
Thanks @gojohnkevin !

**Comment by ificator** [comment]
Linking this issue to the PR: https://github.com/OneDrive/onedrive-sdk-python/pull/116
