### ISSUE TITLE
Not fetching files after OAuth in IE and Safari

### ISSUE THREAD

**Issue by vishesh04** [OneDrive/onedrive-api-docs#721]
After successful OAuth, sdk is not able to fetch files in IE and Safari. It hangs at OneDrive loader icon which is on our page, but doesn’t redirect to OneDrive page with files. Here is the URL, where it hangs - 

https://<url_of_our_page_with_sdk_loaded>#error=unsupported_response_type&error_description=AADSTS70005%3a+The+WS-Federation+sign-in+response+message+contains+an+unsupported+OAuth+parameter+value+in+the+encoded+wctx%3a+%27response_type%27%0d%0aTrace+ID%3a+f84db448-3696-4c61-ad72-9f9bcfe40100%0d%0aCorrelation+ID%3a+1036bd48-de5c-44c3-a07e-df95c8ab9a68%0d%0aTimestamp%3a+2017-09-28+05%3a34%3a31Z&state=https%3a%2f%2fsecure.eltropy.com_6Gs3E

Also, this issue doesn't come all the time. It works like 2 out of 10 times.

**Comment by daboxu** [comment]
hi @vishesh04 , would you mind sharing the url SDK hits the oauth endpoint? I am expecting to see an url like:

```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?redirect_uri=<redirect_uri>&client_id=<app_id>&scope=profile%20openid%20https%3A%2F%2Fgraph.microsoft.com%2FUser.Read%20https%3A%2F%2Fgraph.microsoft.com%2FFiles.Read.All&response_mode=fragment&state=<>&nonce=kJbVI&response_type=id_token+token
```

**Comment by zachzi** [comment]
Hi vishesh04,

If you're still experiencing this problem, please re-open this issue, and I'll investigate.

Thanks,
Zach
