### ISSUE TITLE
Microsoft Graph API Issue

### ISSUE THREAD

**Issue by Sajlib** [OneDrive/onedrive-api-docs#722]
Hello, 
I'm having an issue while trying to access my onedrive items through Graph API.

endpoint: https://graph.microsoft.com/v1.0/me/drive/items/{myItemID}/workbook/worksheets
error:       "message": "General Exception While Processing"

Thanks in advance

**Comment by ificator** [comment]
Hi @Sajlib, can you provide us with the body of the response? It contains a GUID and a DateTime value that will be helpful to diagnose your issue

**Comment by ificator** [comment]
Looks like we've had a similar report on StackOverflow:
https://stackoverflow.com/questions/46603053/cannot-access-onedrive-items-through-the-microsoft-graph-api

**Comment by Sajlib** [comment]
Hi,

I'm using Graph Explorer, here is my request body





HTTP/1.1 500 Internal Server Error 

Cache-Control: private

Content-Type: application/json

request-id: e5483fbd-c49e-4f0a-bb0e-8ab1cbe226c0

client-request-id: e5483fbd-c49e-4f0a-bb0e-8ab1cbe226c0

x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceB","ScaleUnit":"002","Host":"AGSFE_IN_5","ADSiteName":"AMS"}}

Access-Control-Allow-Origin: *

Access-Control-Expose-Headers: ETag, Location, Preference-Applied, Content-Range, request-id, client-request-id

Duration: 755.9903

Date: Mon, 09 Oct 2017 08:22:33 GMT

Content-Length: 236



{

  "error": {

    "code": "generalException",

    "message": "General Exception While Processing",

    "innerError": {

      "request-id": "e5483fbd-c49e-4f0a-bb0e-8ab1cbe226c0",

      "date": "2017-10-09T08:22:33"

    }

  }

}








Thanks,

Sajli





---- On Fri, 06 Oct 2017 18:40:08 +0000 Brad Cleaver &lt;notifications@github.com&gt; wrote ----




Hi @Sajlib, can you provide us with the body of the response? It contains a GUID and a DateTime value that will be helpful to diagnose your issue

**Comment by ificator** [comment]
The fix should now be fully deployed - please let us know if you continue to see issues.
