### ISSUE TITLE
Not able to get root folder from one drive 

### ISSUE THREAD

**Issue by rv77sh** [OneDrive/onedrive-api-docs#723]
I am trying to get access to root folder of one drive account using code

 folder = await this.m_graphClient.Drives[p_strUserID.Trim()].Root.Request().GetAsync();

and

 folder = await this.m_graphClient.Drives[p_strUserID.Trim()].Root.Request().Expand(expandValue).GetAsync();

and i have also done all the impersonation settings like assign admin as owner describe in below link

https://campus.barracuda.com/product/backup/article/BBS/OneDriveAdminPermissions/

still we are getting service exception 
Message: The provided drive id appears to be malformed, or does not represent a valid drive.

can anyone help me with that.

**Comment by ificator** [comment]
What is value of `p_strUserID.Trim()`?

**Comment by rv77sh** [comment]
Hello p_strUserID.Trim() this is the user id like  user@ccssoftware.onmicrosoft.com

**Comment by ificator** [comment]
Hi @rv77sh, can you provide the request id and timestamp from the response?

**Comment by rv77sh** [comment]
We found the solution issue is we are using Alise name of one drive in p_strUserID instead we use primary ID. now its working fine.

**Comment by ificator** [comment]
Thanks for letting us know!
