### ISSUE TITLE
Viewing item works but /createLink returns Access Denied

### ISSUE THREAD

**Issue by exp0nge** [OneDrive/onedrive-api-docs#724]
What **works**:
GET `https://graph.microsoft.com/v1.0/drive/items/E6C67E2E0C9058E4!2265/`

What **doesn't**:
POST `https://graph.microsoft.com/v1.0/drive/items/E6C67E2E0C9058E4!2265/createLink`
![image](https://user-images.githubusercontent.com/11747245/31695844-ee535cea-b37a-11e7-8da5-d5dde6fbfbab.png)
![image](https://user-images.githubusercontent.com/11747245/31695839-e481ea7e-b37a-11e7-902a-afaa111788c3.png)

```
{
    "error": {
        "code": "accessDenied",
        "message": "Access Denied",
        "innerError": {
            "request-id": "88b2c3f0-1b41-42f2-b5ab-b19f107cfbb2",
            "date": "2017-10-18T00:33:21"
        }
    }
}
```

---

Here's my client id: `bc136b76-2479-48d4-814d-0e5633b058e4`

**Comment by ificator** [comment]
Hi @exp0nge this is most likely an issue with the scopes associated with the token. When you get the oauth token what scopes are you requesting?

**Comment by exp0nge** [comment]
@ificator 
From the file picker url:
`...scope=onedrive_onetime.access:readwritefolders...`

From registration:
![image](https://user-images.githubusercontent.com/11747245/31741451-4b5cee5e-b422-11e7-99a3-554c89763578.png)

**Comment by ificator** [comment]
You'll probably want to make sure that `Files.ReadWrite.All` is requested for you scenario to function as expected. Can you try adding that as a delegated permission and see if that resolves your issue?

**Comment by exp0nge** [comment]
@ificator I even added the Directory.ReadWrite.All
![image](https://user-images.githubusercontent.com/11747245/31746065-823d004c-b433-11e7-9d27-98edf75d23e4.png)


Same results. This time the `GET` gives `itemNotFound` since I'm using a different item-id (ie OneDrive/onedrive-api-docs/issues/379#issuecomment-337717135)

**Comment by exp0nge** [comment]
Looks like it works once I've deleted the original access token/refresh token.
