### ISSUE TITLE
5 page/1000 items limit for pagination?

### ISSUE THREAD

**Issue by exp0nge** [OneDrive/onedrive-api-docs#728]
Is there a 5 page limit (200 results per page) limit on the pagination (`nextLink`)?

**Comment by ificator** [comment]
There shouldn't be any page limit, but there's a limit on the number of results that can be returned in each page. I believe it's at least 2000 though.

**Comment by exp0nge** [comment]
Seems like the search is and probably will be inconsistent. I ended up traversing the directories to pickup the files manually.
