### ISSUE TITLE
Sharepoint REST call getFolderByServerRelativeUrl() returns Access denied

### ISSUE THREAD

**Issue by anildbest83** [OneDrive/onedrive-api-docs#729]
Hi,

When i try to get a folder detail using REST call 

`https://mycomp.sharepoint.com/_api/web/getFolderByServerRelativeUrl('/Shared%20Documents')`

i m getting following error 

'code=-2147024891, System.UnauthorizedAccessException'
value=**Access denied**. You do not have permission to perform this action or access this resource.

It was working fine earlier but suddenly this error start coming.

Please advice

**Comment by ificator** [comment]
Closing stale issue - if this is still applicable please reopen so we can triage appropriately.
