### ISSUE TITLE
action.copy - copying with the same name as original unclear error

### ISSUE THREAD

**Issue by bscharm** [OneDrive/onedrive-api-docs#73]
When using action.copy and copying a file with the same name, and into the same folder as the original, the following error is returned-
```
{code=itemNotFound, message=Item Does Not Exist, innererror={code=itemDoesNotExist, innererror={code=folderDoesNotExist}}}
```
I would expect something like "a file with that name already exists". Here are the headers from the response-
```
{x-msnserver=[DM2302____PAP156], date=[Thu, 09 Apr 2015 15:54:36 GMT], server=[Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0], x-throwsite=[5433.1999], content-type=[application/json], x-qosstats=[{"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}], x-wlsproxy=[BL3302____PAP237], p3p=[CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"], x-asmversion=[UNKNOWN; 19.17.0.0], via=[1.1 BL3302____PAP237 (wls-colorado)]}
```

**Comment by ificator** [comment]
Thanks @bscharm. I tried reproing and got an expected 409 back. Could you provide me with the URL and JSON body of your copy request when you hit this failure?

**Comment by bscharm** [comment]
URL-
```
https://api.onedrive.com/v1.0/drive/root:/test3.txt:/action.copy
```
BODY-
```
{"parentReference":{"path":"/drive/root:"},"name":"test3copy.txt"}
```

**Comment by ificator** [comment]
Thanks, I can repro now. Seems like an issue if you attempt to copy any item to the root of the drive.

**Comment by ificator** [comment]
Thanks for your patience, this should now be fixed!
