### ISSUE TITLE
Opening OneDrive picker with an existent Microsoft GraphQL token to avoid login screen

### ISSUE THREAD

**Issue by nathanmarcos** [OneDrive/onedrive-api-docs#730]
Hi, I'm getting some troubles when try to open the picker with an existent token from Microsoft GraphQL, the token is ignored and the login screen appears.

The user has already authenticated and authorized the app and we already got the user token previously. According to the documentation if you add the "accessToken" parameter in the [advanced options](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file#advanced-options) section, a param called "endpointHint" is required, but the "endpointHint" documentation says: "It is not required if the app talks to Microsoft Graph API.".

I've tried many possibilities that I could but the login screen always appears, in the end I suppose that I should set my parameters something like this:

```javascript
var odOptions = {
  clientId: "INSERT-APP-ID-HERE",
  action: "query",
  multiSelect: true,
  advanced: {
    accessToken: "Ey..."
  },
  success: function(files) { /* success handler */ },
  cancel: function() { /* cancel handler */ },
  error: function(e) { /* error handler */ }
}
```

There is some way to make it works?

**Comment by daboxu** [comment]
hi @nathanmarcos sorry for the confusion in the docs. We are expecting an access token for OneDrive for Person endpoint: api.onedrive.com or a specific OneDrive for Business/SharePoint endpoint. So the graph token you had won't work because we reply on Graph to handle the different user types (Personal/Business) and Graph API handles the different endpoint will hit to. The 'endpointHint' + 'accessToken' flow we proposed were intend for getting rid of the Graph auth if the user knows which endpoint the request will go to. Unfortunately I think it is not your case. I will add a back log for supporting the access token from Graph, but sorry I cannot promise a date so far.

**Comment by nathanmarcos** [comment]
Ohh, I got it! For now, the users will need to log in again when picker opens.

Thank you @daboxu.

**Comment by daboxu** [comment]
@nathanmarcos  you are welcome! And the login again is expected for the user first login with the same account and the picker web page will pick up cookie if user signed in before.

**Comment by daboxu** [comment]
closed for now

**Comment by etyp** [comment]
@daboxu ah, happy I finally found this. So we're using 3-legged oAuth and running into similar issues.

For example, we have:
- A user who has OneDrive for Business
- The user logs in with Microsoft, we get an access token from https://login.microsoftonline.com/common/oauth2/v2.0/token and store it on our server
- The user logs into our app and we send the access token to their client browser

How can I utilize that token to prompt the OneDrive picker?

When I try the following, it asks me to log in again:
```
var options = {
  action: 'share',
  multiSelect: true,
  clientId: OUR_CLIENT_ID,
  advanced: {
    accessToken: STORED_ACCESS_TOKEN,
    endpointHint: 'api.onedrive.com',
  },
}
```

And when I try using the `endpointHint` of `https://graph.microsoft.com/v1.0/`, I get `InvalidAuthenticationToken` which says `Access token is empty.`:
```
var options = {
  action: 'share',
  multiSelect: true,
  clientId: OUR_CLIENT_ID,
  advanced: {
    accessToken: STORED_ACCESS_TOKEN,
    endpointHint: 'https://graph.microsoft.com/v1.0/',
  },
}
```

Am I using the wrong `endpointHint`? If so, what should I use?

Or is the problem that this isn't even possible?

**Comment by etyp** [comment]
Update: I tried using `endpointHint` of https://myorg-my.sharepoint.com/personal/username_myorg_onmicrosoft_com and it worked.

I guess my question is: how am I supposed to know what that URL is for any given user? Is that something that's provided in the oAuth flow?

**Comment by ujjwal-iqlect** [comment]
Any update on this?
