### ISSUE TITLE
[ODB] forbidden or invalid file name

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#731]
Hello, 

Is there a fine document to indicate the invalid file name
Thank you for help

--
What i found:
https://support.office.com/en-us/article/Invalid-file-names-and-file-types-in-OneDrive-OneDrive-for-Business-and-SharePoint-64883a5d-228e-48f5-b3d2-eb39e07630fa
https://support.microsoft.com/en-us/help/2933738/restrictions-and-limitations-when-you-sync-sharepoint-libraries-to-you

**Comment by ificator** [comment]
I believe the second link is the most accurate documentation we have on the matter.
