### ISSUE TITLE
expand=children(...) does not include @odata.nextLink

### ISSUE THREAD

**Issue by daniel-kun** [OneDrive/onedrive-api-docs#732]
I am calling this:
`https://graph.microsoft.com/v1.0/me/drive/items/1F56D0165ED3C523%211209?expand=children(select=id,name)`
on a folder (my Camera Roll folder), which includes 6519 items.
200 of them are returned expanded, but there is no @odata.nextLink in the result.
This does neither work on v1.0, nor on beta, neither on the Graph Explorer, nor in my code.

**Comment by ificator** [comment]
Unfortunately this is a known issue with Microsoft Graph's integration with OneDrive. We're working with them to get it resolved, and will update this issue when it has been.

**Comment by isac322** [comment]
Is there any alternative way to get nextLink for now?

**Comment by ificator** [comment]
So I finally have some news on this one... it looks like there's been a partial fix. If you make the call against Graph using `$` prefixed odata options it should come back:

```
https://graph.microsoft.com/v1.0/me/drive/items/1F56D0165ED3C523%211209?$expand=children($select=id,name)
```

Unfortunately there is still an issue if you do NOT prefix with `$` - I'm working on seeing if that's something Graph can fix.

**Comment by ificator** [comment]
The workaround is the best we're going to get for now - I'll update this issue if things change.
