### ISSUE TITLE
/me/drive/recent gives DriveItems that contains remoteItem even though it's in my drive

### ISSUE THREAD

**Issue by isac322** [OneDrive/onedrive-api-docs#735]
`GET https://graph.microsoft.com/v1.0/me/drive/recent`

gives (one of the items in "value" array)

```json
{
    "@odata.type":"#microsoft.graph.driveItem",
    "createdBy":{
        "user":{
            "displayName":"\uc720\ubcd1\ud6c8",
            "id":"d4fd82ca6df96a47"
        }
    },
    "createdDateTime":"2015-11-03T13:28:33.983Z",
    "eTag":"aRDRGRDgyQ0E2REY5NkE0NyExODcwNS45",
    "id":"D4FD82CA6DF96A47!18705",
    "lastModifiedBy":{
        "user":{
            "displayName":"\uc720\ubcd1\ud6c8",
            "id":"d4fd82ca6df96a47"
        }
    },
    "lastModifiedDateTime":"2016-01-25T03:48:07.987Z",
    "name":"\uacac\uc801\uc11c.xls",
    "parentReference":{
        "driveId":"d4fd82ca6df96a47"
    },
    "webUrl":"https://1drv.ms/u/s!AEdq-W3Kgv3UgZBK",
    "fileSystemInfo":{
        "lastAccessedDateTime":"2015-12-14T04:30:09.423Z"
    },
    "remoteItem":{
        "fileSystemInfo":{
            "lastAccessedDateTime":"2015-12-14T04:30:09.423Z"
        },
        "file":{

        },
        "id":"D4FD82CA6DF96A47!18506",
        "name":"\uacac\uc801\uc11c.xls",
        "parentReference":{
            "driveId":"d4fd82ca6df96a47"
        },
        "size":268288,
        "webUrl":"https://1drv.ms/u/s!AEdq-W3Kgv3UgZBK"
    }
}
```

As you can see, `parentReference.driveId` is the same as `remoteItem.parentReference.d4fd82ca6df96a47`. And I'm sure that the file is in my drive.

Is it bug or my misunderstand? please help me :cry:

**Comment by isac322** [comment]
And that's not the only one. I couldn't check for all the items (too many), but every item I had saw has remoteItem facet.

**Comment by rgregg** [comment]
This is somewhat badly documented here: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_recent#remarks. It should say "results from /recent will always include the remoteItem facet". If you want to determine what is truly an item in another drive, you would need to compare the driveId value to the user's own drive. This is a bit of a quirk with the way the recent API works, where all items appear "remote".
