### ISSUE TITLE
Requesting custom thumbnail size does not work

### ISSUE THREAD

**Issue by d3c0y** [OneDrive/onedrive-api-docs#736]
Hi,

I use OneDrive for Business and its Graph API.
I am trying to get a custom thumbnail size following the documentation but I am getting a strange error.

My request looks like:
`https://graph.microsoft.com/v1.0/me/drive/items/<item_id>/thumbnails/0/c32x32_Crop/content`

and the response is:
`{
  "error": {
    "code": "BadRequest",
    "message": "Unsupported segment type. ODataQuery: users/<user_id>/drive/items/<item_id>/thumbnails/0/c32x32_Crop/content",
    "innerError": {
      "request-id": "<request_id>",
      "date": "2017-11-17T09:41:57"
    }
  }
}`

If I try to retrieve thumbnails with "select" query parameter and its value "c32x32_Crop" I will get empty values. 

Is there any special permission required by the API or it can be a bug? (It works correctly for OneDrive Personal API)

**Comment by ificator** [comment]
Unfortunately ODB has a limitation that blocks `select=c32x32_Crop` from working, but direct selection via a path segment is expected to work. This looks to be an issue in Microsoft Graph itself (as the same request made directly against our service works as expected). We'll forward this issue on to them and hope that we can get a quick resolution.

**Comment by ificator** [comment]
Just to update this, while we're still waiting on Graph to support the direct selection via a path segment we were able to unblock the use of `select=c32x32_Crop` against ODB. This will allow you to access custom thumbnails via Graph using the `select` syntax.
