### ISSUE TITLE
Getting permanent public link for multiple media files

### ISSUE THREAD

**Issue by raRaRa** [OneDrive/onedrive-api-docs#737]
Hi all.

I'm working on a live slideshow website where you can add OneDrive folder and display the media in the folder on slides. The main challenge seems to be getting a public link that doesn't expire. 

My current idea is to do the following:

Start by creating a sharing link for the folder:
`POST -> https://graph.microsoft.com/v1.0/me/drive/root:/{folderPath}:/createLink`

The response has a shareId that I can use for the next request, which gets all the thumbnails for the sharing link:

Get thumbnails for the shareId (**Please note that this is a non-authenticated call**):
`GET -> https://api.onedrive.com/v1.0/shares/{shareId}/root/thumbnails`

This will return public links to the media files in the folder, that don't seem to expire because it was not requested with a authentication token. Or is that a misunderstanding that I read from another issue? Because the links look the same if I request with or without an access token

Now my slideshow should be able to poll the shares/{shareId}/root/thumbnails to check for new media in the folder. I guess I could also call shares/{shareId}/root/children, but the response for that contains the `content.downloadUrl` for media files. Can I assume that the downloadUrl link will not expire?

<s>Is there a way to get the thumbnails as well with this request: shares/{shareId}/root/children?</s>
**UPDATED:**
Seems like I can get the thumbnails with the request by doing: `shares/{shareId}/root/children?expand=thumbnails`

Thanks!

**Comment by rgregg** [comment]
Hi @raRaRa,

In general, downloadUrls expire after an hour. If you want to persist a link that is public and does not expire, you can use the /shares/ API somewhat link you mentioned:

```
GET https://api.onedrive.com/v1.0/shares/{shareId}/root/thumbnails/0/large/content
```

This will redirect to an expiring download URL for the file, as long as the {shareId} is still valid.

However, this only works with OneDrive personal accounts. OneDrive for Business (or calls through MS Graph) always require a token.

**Comment by raRaRa** [comment]
Thanks @rgregg

I want to rely on some form of caching, e.g. 4 hours would be great. That way I can just store the book keeping on my side, such as when I need to re-fetch images before they expire. (It's kinda what I'm doing with Dropbox, their API has a feature to create temporary link that expires after X hours).

My main use case is allowing people to create a website slideshow from OneDrive folders, and they will have the ability to share the slideshow with their friends (or even the public). So it would be ideal if I could avoid spamming the OneDrive API with requests for each individual user who is viewing the slideshow. This is the main reason why I need some form of caching.

I'm still a bit confused with the downloadUrl and thumbnails. But here are my main questions:

1. If I send an anonymous GET request to `shares/{shareId}/root/children` with no Authorization header, will the downloadUrl links expire after an hour?

2. If I send an anonymous GET request to `shares/{shareId}/root/children` with no Authorization header, will the thumbnail links expire (given that the share will never be deleted). If they expire, do you know the expiration time?

3. Based on my use case above, would you recommend creating a share for the folder and then fetching the thumbnails? Would you do it differently?

Thanks again!

**Comment by ificator** [comment]
Hi @raRaRa, I apologize for the delay in following up on your questions.

1 and 2. When you make a call against `shares/{shareid}/root/children` with NO authorization header the URLs will not expire - their lifetime is dictated by the share itself and not a time window.

3. Shares is the only real way to get URLs that can be cached for long periods of time. It'll also result in the same URL (assuming the same shareid is always used) whenever you call the API so it's better from a browser cache perspective as well.

**Comment by elTorito666** [comment]
Hi all, 
i have simple question where i can't not found answer in the world wide web :-( 
Where can i get/see the shareid from a folder. 

I Try list photo files from a shared folder in a uwp app. 
I try in the [MS GRaph tester](https://developer.microsoft.com/de-de/graph/graph-explorer#) the Get 
"h ttps://graph.microsoft.com/v1.0/shares/{sharedidorencodedurl} " as here described:
https://docs.microsoft.com/de-de/onedrive/developer/rest-api/api/shares_get

but nothing works,....

 which is the syntax of this id? Where can i see the sharedid/url of my shared folder? 

When i Click on Shared FolderUrl will be in Format: 
onedrive.live.com/?id=ABCD7D546D72E2D6!328698&cid=ABCD7D546D72E2D6
but this id's don't work

thanks  a lot and sorry my bad english
