### ISSUE TITLE
Onedrive for business discover services returns nothing with 200

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#738]
Hi,

I use this endpoint `https://api.office.com/discovery/v2.0/me/services` to discover uri and resource id, but it returns nothing from this morning.

Here is the response I got
```
GET https://api.office.com/discovery/v2.0/me/services
{
"@odata.context": "https://api.office.com/discovery/v2.0/me/$metadata#allServices",
"value": [],
}
```

Is it deprecated or just a temporary glitch?

**Comment by rgregg** [comment]
That endpoint is deprecated: https://dev.office.com/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation

I'd recommend moving over to use Microsoft Graph to retrieve this information, as mentioned in the post above. However while deprecated, the API is not deactivated yet and I would have expected it to return results. Are you still seeing nothing returned?

**Comment by verybada** [comment]
Hi @rgregg ,

Still the same, please see the curl result.
```
curl https://api.office.com/discovery/v2.0/me/services -H "Authorization: Bearer $token" -v
* Connected to api.office.com (13.76.85.80) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: o365discovery.officeapps.live.com
* Server certificate: Microsoft IT SSL SHA2
* Server certificate: Baltimore CyberTrust Root
> GET /discovery/v2.0/me/services HTTP/1.1
> Host: api.office.com
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Bearer $token
>
< HTTP/1.1 200 OK
< Cache-Control: private, max-age=0
< Transfer-Encoding: chunked
< Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
< Expires: Mon, 06 Nov 2017 01:38:13 GMT
< Last-Modified: Tue, 21 Nov 2017 01:38:13 GMT
< Server: Microsoft-IIS/8.5
< X-CorrelationId: ce4a5eb3-9276-4176-9452-b432c1156af1
< X-UserSessionId: ce4a5eb3-9276-4176-9452-b432c1156af1
< X-OfficeFE: O365DiscoveryFrontEnd_IN_4
< X-OfficeVersion: 16.0.8806.6526
< X-OfficeCluster: sea-000.o365Discovery.officeapps.live.com
< P3P: CP="CAO DSP COR ADMa DEV CONi TELi CUR PSA PSD TAI IVDi OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR"
< ODATA-VERSION: 4.0
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< X-Content-Type-Options: nosniff
< Date: Tue, 21 Nov 2017 01:38:13 GMT
<
* Connection #0 to host api.office.com left intact
{"@odata.context":"https://api.office.com/discovery/v2.0/me/$metadata#allServices","value":[]}
```

**Comment by rgregg** [comment]
Investigating this still... just to confirm, the user definitely has a OneDrive for Business account, right?

**Comment by verybada** [comment]
@rgregg 

sure, we have tried other business accounts, they got the same.

**Comment by verybada** [comment]
@rgregg, seems service back already.

**Comment by BuuChau** [comment]
I have 1 error same u, but i fix success.
Error is when you using Azure, you not set permission when register, Choose app after click button permission in menu AD. 
![image](https://user-images.githubusercontent.com/16359854/35798787-71c1188e-0a96-11e8-82fb-f96f06281150.png)

I hope this is help u.
