### ISSUE TITLE
[Question] Is it possible to extend the list count response more than 200?

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#74]
Hi, I am trying to upload a lot of files into a folder, and there is some thing bothered me.

The response of the list once maximum entries is 200, that is, if there are 10000 files need to be returned, I'll take 50 http requests.

the same number issues is also occurred when I request for change list.

This will take a lot time. Other providers' APIs like dropbox, could response 2000 entries in one response.

Is there any way to get more return entries or it's just the limitation? Thanks.

**Comment by ificator** [comment]
If you specify the top query parameter I believe it'll let you go up to 1000.

    /v1.0/drive/root/children?top=1000

**Comment by ginach** [comment]
That change isn't out yet but it should be soon.

**Comment by mikechiu1012** [comment]
yes, I know it could set top parameter but that's the response:
Bad request(400) :The query specified in the URI is not valid. The limit of '200' for Top query has been exceeded. The value from the incoming request is '1000'.

but as u mentioned, 200 is not the limitation?

**Comment by ificator** [comment]
Doh, @ginach is right it looks like it hasn't quite made it. I'll ping this issue when it works like I described. Sorry for the false alarm!

**Comment by mikechiu1012** [comment]
thanks @ificator, also, could u please doc this description(about the response entry number) in the list and change API doc? I think it would be helpful for developer :)

**Comment by ificator** [comment]
Will do, I won't close this out until we've updated the docs.

**Comment by ificator** [comment]
This should actually be working now, I promise ;)

**Comment by ificator** [comment]
I've also updated the documentation (will hopefully be included in the next documentation push).

**Comment by mikechiu1012** [comment]
hi @ificator, I try the top and now it could set upper to 1000.

thanks for help!
