### ISSUE TITLE
GetItems throws 500 error. Error code - 103

### ISSUE THREAD

**Issue by Santhosini** [OneDrive/onedrive-api-docs#741]
I've integrated one drive. I'm getting a 500 response error for past two days.

https://skyapi.onedrive.live.com/API/2/GetItems

{"error":{"code":103,"debugMessage":"The given canary was not valid.","isExpected":true,"stackTrace":"6e0d716691d635f42:zVCkWx+WIP/8xepxq6/8c2RH4LQYAsgEb1g+Bh5Z96HZMkpNLJO3U4UCp8LYeXJGS4m2qr7hnEvx8E98Dc/SgYcs+W6eaeUOybmMw4Oos3Im1kqUdodTZpuyCKAQ7ZPq3Q6MHrjOFLky0W/YGX/Mhm0yiWzrlqpZe8Vips78JILwsph8MRSfwlkHCmdBCNSyca15FnSBCJ819k38ZlbRsI/PUQzGzNBFYYmqYQuq7Bws8pmBUrTlY3nW9v3BvXWU/izxjB4LAnNNtigueQs6WIS3z6/ZgQBLxj0JnSKgx/555c3uQp7lQ3vY8idp2HSBRrkiwwB8A4hQ85zP8kmQNy6Tn34zPW5BceFldNN31qBe7ECNa8mI4sl5DHoIeEGRwd/DmCZ4YM70z0N7m2Ht9xtYACSGCQy+Q5KVst4p0hCL9dXe9gP06qfdUyjTp6MX4OhWgve4qJsBlVyM/wxGJQ2ToQjCEfE9MUwFNkUX6Rqq/1xVrUmMbZHOtS8shxhyHuFkMZn63hDYeKxNSQO0VaFFjhIfyTQUC2j+4g0mrm0Os7RLZ8xfnCQBsfkcvGsG5idsIdlR43gL/NHItIZLYEa5NuTOFdwJwczcQCuGr1UYxftEj68q8MSK27yariTciRw/MyS4x7YxEdlJKqb6lUX8RMPVGEEfwE+w/Ow6+9vlFfgmXyFtj3rlf4jwklh3"}}

**Comment by rgregg** [comment]
Hi Santhosini,

It looks like you're trying to use an unsupported private API. To enable this scenario, you need to use the Microsoft Graph APIs, for example [List Files](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_children).

**Comment by Santhosini** [comment]
We are using this library for the file picker - https://js.live.net/v5.0/wl.js
So as a part of it, when I try to use WL.fileDialog it throws a 500 error for the following request -
 https://skyapi.onedrive.live.com/API/2/GetItems
