### ISSUE TITLE
Some files(.xls) in Onedrive for personal do not have cTag

### ISSUE THREAD

**Issue by isac322** [OneDrive/onedrive-api-docs#742]
Although the [documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem) says that only folders do not have cTag,
`GET /drives/D4FD82CA6DF96A47/items/D4FD82CA6DF96A47!22182`
,
`GET /drives/D4FD82CA6DF96A47/items/D4FD82CA6DF96A47!24854`
and
`GET /drives/D4FD82CA6DF96A47/items/D4FD82CA6DF96A47!26221`

doesn't have cTag.

But I found that the extension of all those files is xls.
Is this intended? Is it a bug?

**Comment by isac322** [comment]
I just found that `D4FD82CA6DF96A47!22113` doesn't have cTag but it is vsdx file.

**Comment by ificator** [comment]
I have a theory what could be going on here - it's nothing you can control). I'll mark it as a bug while I confirm.

**Comment by ificator** [comment]
Whoops, I dropped the ball on this one! We've made a change to make sure the `cTag` value is correctly populated for Office documents so hopefully you see this working now.

**Comment by isac322** [comment]
Thanks it works! 👍
