### ISSUE TITLE
File picker "Open" button is diabled when current folder contains only one file.

### ISSUE THREAD

**Issue by yutao-huang** [OneDrive/onedrive-api-docs#743]
The OneDrive file picker dialog's "Open" button is disabled when a file is selected and that file is the only file within that folder. But after I manually uploaded a file to that folder and selected the same file again, the "Open" became enabled.

P.S.: Options I used here (omitting other irrelevant parameters) - `{ action: 'query', multiSelect: false }`

**Comment by AurelioDeRosa** [comment]
I've just experienced the same issue. This is quite severe, can we have an update on it?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
