### ISSUE TITLE
"Empty Payload. JSON content expected" when uploading an item to OneDrive from a URL

### ISSUE THREAD

**Issue by ayoisaiah** [OneDrive/onedrive-api-docs#745]
I get the following error when I try to upload an item to OneDrive from a URL (https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_upload_url)
```
{
  "error": {
    "code": "BadRequest",
    "message": "Empty Payload. JSON content expected.",
    "innerError": {
      "request-id": "d7e82630-2db0-4cbe-aa47-0325b9e2994d",
      "date": "2017-11-30T13:11:53"
    }
  }
}
```
I don't understand what this means.

Here's my code:

```
  const headers = new Headers({
    'Content-Type': 'application/json',
    Prefer: 'respond-async',
    Authorization: `bearer ${onedriveData.access_token}`,
  });

  const body = {
    name: `photo-${imageId}.jpg`,
    '@microsoft.graph.sourceUrl': downloadUrl,
    file: {},
  };

  const init = {
    method: 'POST',
    headers,
    body,
  };

  const request = new Request('https://graph.microsoft.com/v1.0/drive/special/approot/children', init);

  fetch(request)
    .then(validateResponse)
    .catch(error => console.log(error));
```

**Comment by ificator** [comment]
Hi @ayoisaiah, I believe the issue is with how the body is serialized. You'll need to make sure it's converted to a JSON string:

```
const init = {
  method: 'POST',
  headers: headers,
  body: JSON.stringify(body),
};
```

**Comment by ayoisaiah** [comment]
Ok that fixed it, thanks. However, I get a 404 error:
```
{
  "error": {
    "code": "itemNotFound",
    "message": "Item does not exist",
    "innerError": {
      "request-id": "b25e390e-a1fd-4ece-a40f-01f81c34357c",
      "date": "2017-11-30T19:09:12"
    }
  }
}
```
Meanwhile, the url passed to `@microsoft.graph.sourceUrl` is publicly accessible. Is there something I'm missing?

**Comment by ificator** [comment]
Does it work if you use `@content.sourceUrl` instead? I have a feeling this is another translation issue.

**Comment by ayoisaiah** [comment]
@ificator Now I get a 400 Bad request error: 

```
{
  "error": {
    "code": "invalidRequest",
    "message": "Cannot create a file without content",
    "innerError": {
      "request-id": "a4755dde-ccd2-443f-a7f0-d3e8a0e77359",
      "date": "2017-11-30T23:58:20"
    }
  }
}
```

**Comment by ificator** [comment]
Thanks for confirming @ayoisaiah, `@microsoft.graph.sourceUrl` is working as it should - continue to use it and NOT the other suggestion I made. I believe your problem is the `approot` folder doesn't yet exist for your application, so if you do a GET against the following URL first, and then try your upload again it should work.

```
https://graph.microsoft.com/v1.0/drive/special/approot
```

Unfortunately the upload from URL code path is a little more sensitive to the existence of its parent - I'll look into whether this is something we can improve.

**Comment by ayoisaiah** [comment]
@ificator Thanks a lot. That solved my problem 👍
