### ISSUE TITLE
Creating an upload session for OneDrive Personal returns "API not found"

### ISSUE THREAD

**Issue by vbarzokas** [OneDrive/onedrive-api-docs#746]
A request for creating an upload session works fine if the target account is OneDrive for Business:

```
https://graph.microsoft.com/v1.0/me/drive/items/01DGSVRWXHTUQM7HCBXVFJPD365PXQKIJQ/children('test.txt')/createUploadSession

{"item":{"@microsoft.graph.conflictBehavior":"replace"}}
```

but fails with the below error if the account is OneDrive Personal:
```
POST https://graph.microsoft.com/v1.0/me/drive/items/C3E3DEE5AD1B57AF!336/children('test.txt')/createUploadSession

{"item":{"@microsoft.graph.conflictBehavior":"replace"}}```
```

with this response: 
```
{ "error": { "code": "invalidRequest", "message": "API not found", "innerError": { "request-id": "f787f4ef-2935-4f13-a1cf-11bbdaa8f284", "date": "2017-11-30T16:45:02" } } }
```

However it works as expected if I use the full path of the file in the requested URL, something like this: 
```
POST https://graph.microsoft.com/v1.0/me/drive/root:/Documents/folder1/folder2/test.txt:/createUploadSession

{"item":{"@microsoft.graph.conflictBehavior":"replace"}}
```

**Comment by ificator** [comment]
This looks to be a bug on our side, but there's a work around you can use until we fix it. Essentially any place where `children('file.txt')` is used can generally be replaced with `:/file.txt`.

If you try using the following it should work:
```
POST https://graph.microsoft.com/v1.0/me/drive/items/C3E3DEE5AD1B57AF!336:/test.txt:/createUploadSession

{"item":{"@microsoft.graph.conflictBehavior":"replace"}}
```

**Comment by vbarzokas** [comment]
Thank you for your quick reply.
Indeed the suggested URL works fine, I was using `children('file.txt')` in order to be able to use the characters `(` and `'` in the filename (as suggested in [#565](https://github.com/OneDrive/onedrive-api-docs/issues/565) but the `:/file.txt` seems to work fine with those characters as well.

**Comment by ificator** [comment]
And as a bonus you don't have to "OData Escape" the ' characters when you use the colon syntax :)

**Comment by ificator** [comment]
This should now be fixed.

**Comment by denven** [comment]
@ificator Now, this is 2023, I am using `:/path:/createUploadSession`  this way for uploading large files by chunks, however, it still has the issue for the personal account, business account works fine.

sample:
`curl -s -k -L -X PUT 'https://graph.microsoft.com/v1.0/me/drive/root:/yihack_videos/2023Y01M02D23H/08M00S60.mp4:/createUploadSession' \ 
-H 'Content-Type: application/json' --data-raw '{"item":{"@name.conflictBehavior":"replace","name":"08M00S60.mp4"}}' \
-H 'Authorization: Bearer /sKRIH3ZZk8wFojsUhsC37es8VmyUJVmGwrBrD50DJb2+uGZ8AmwVfpDACKfN/0r9PFMWdWTNiwtPlYIpj1EtWX2ewnLopIqk5Tb9NZzvjrsbSfbMA2NRvzgNSvZwjKPgyNXHHk+/OfUgJ+3l1RvXLjNxi8X+5zMBi6DG3kULCh0I3jonv5dLCCG5v2z2UlcEmXtjOmmdCTfsWgC'`

error:
```json
{
    "error": {
        "code": "invalidRequest",
        "message": "API not found",
        "innerError": {
            "date": "2023-01-04T07:55:23",
            "request-id": "56a60ada-08fe-408c-9dbd-058a92e2b8aa",
            "client-request-id": "56a60ada-08fe-408c-9dbd-058a92e2b8aa"
        }
    }
}
```
