### ISSUE TITLE
Create upload session returns 409 for `conflictBehavior: replace` for consecutive calls

### ISSUE THREAD

**Issue by vbarzokas** [OneDrive/onedrive-api-docs#747]
I am using this URL as suggested in #746 for creating an upload session: 
```
https://graph.microsoft.com/v1.0/me/drive/items/{folder-id}:/{file-name}:/createUploadSession

{"item":{"@microsoft.graph.conflictBehavior":"replace"}}
```

If I make two or more consecutive requests from an account that is OneDrive for Business without completing the upload session (e.g. by uploading the file) and without deleting the upload session, then after the first request I get this response:
```
409
{
  "error": {
    "code": "nameAlreadyExists",
    "message": "The specified item name already exists.",
    "innerError": {
      "request-id": "b892e11a-de01-43f0-9381-9d6bd6d8c409",
      "date": "2017-12-01T17:43:31"
    }
  }
}
```
If I delete the session by calling `DELETE <uploadUrl>` then it works for the next request but of course if I make more requests the same will happen again.

However when I try the exact same scenario from an account that is OneDrive Personal, I get no errors and a new `uploadUrl` is returned every time that I make the request.

**Comment by ificator** [comment]
Unfortunately as much as we've tried to align the OneDrive Business and OneDrive Consumer there are still some differences between them - this is one of them. In Business the session based upload is tied to a name (via a stub file) the moment it's created, which means it is not possible to have two with the same name. On the contrary, Consumer doesn't associate a session based upload to a name until it's committed.

From an API perspective the Consumer approach is a lot more friendly, but unfortunately making Business behave the same way is almost a none starter.

**Comment by vbarzokas** [comment]
The above scenario now returns:

```
403
{
    "error": {
        "code": "notAllowed",
        "message": "An upload session already exists for this file",
        "innerError": {
            "request-id": "280e7516-5b88-4c81-a048-58a4bb118b5a",
            "date": "2018-02-20T14:29:56"
        }
    }
}```

Which is even more confusing as the status code 403 is used to have a different meaning, like for example that there have been provided invalid credentials.

**Comment by ificator** [comment]
This should probably be a `409 Conflict` - I'll look into making that change.
