### ISSUE TITLE
The rest api of download file have an error.

### ISSUE THREAD

**Issue by wudeyong** [OneDrive/onedrive-api-docs#748]
Hi:

  I try to download a file by the driveItem unique identifier using **drive/items/{item-id}**.But the server return the error code of 400.

Thanks

Davin

**Comment by ificator** [comment]
Hi @wudeyong, can you provide the full request / response? Without those it's hard to say why you'd be seeing a `400 Bad Request`.

**Comment by wudeyong** [comment]
Yes,of course.

The request like this:


> GET https://graph.microsoft.com/v1.0/drives/items/{item-id}/content



The response is:
```
{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment '01FASBQH4B3TCO37AHZRCLRP3CVRSN34QX'.",
    "innerError": {
      "request-id": "4c90ff6a-37df-40cd-8436-e8e93fd087de",
      "date": "2017-12-07T09:07:46"
    }
  }
}
```
Thanks

But it can correct work when use another  API: **/drives/{driver-id}/items/{item-id}/content**
