### ISSUE TITLE
Unclear documentation: Resuming upload session, next expected ranges and fragment size

### ISSUE THREAD

**Issue by Lyrrad** [OneDrive/onedrive-api-docs#75]
I occasionally get an error when uploading a fragment.  I'm currently using a fragment size of 10MiB, but when the fragment fails, the next expected range almost always doesn't start on a multiple of 320KiB.  

Example: I get an error uploading a fragment and the status command returns the following:
```{'nextExpectedRanges': ['1325399232-3517313465'], 'expirationDateTime': '2015-04-17T02:15:08.9815266+00:00'}```

Now, "1325399232" bytes isn't a multiple of 320KiB, even though I was uploading in that sort of multiple. So, only part of the fragment I was uploading was committed to the upload session.

So, what's the next fragment size that I should upload to avoid the issue from #70?  A multiple of 320KiB or one that takes the beginning of nextExpectedRanges to a multiple of 320KiB?

What happens if I'm uploading a 9GiB file and a failure occurs near the end, will #70 occur then due to the incorrect fragment size committed to the session?  I can't efficiently test this because of the unpredictability of upload session failures.

**Comment by rgregg** [comment]
Fragments that you upload should always be a multiple of 320KiB. In this case, it appears that part of a previous fragment was accepted, and thus the alignment within the file is no longer aligned to a multiple of 320KiB. The service will be able to recover from that condition successfully, so long as you continue to upload fragments in multiples of 320KiB starting at the next expected range start (1325399232 in your example).

**Comment by rgregg** [comment]
I'll add a note to the docs about this in the next website refresh.
