### ISSUE TITLE
Is it possible to establish permament or long-term non-interactive access to API?

### ISSUE THREAD

**Issue by AndrewPashkin** [OneDrive/onedrive-api-docs#750]
Hello, 

when I'm making such requests:
```
POST /common/oauth2/token HTTP/1.1
Host: login.microsoftonline.com
User-Agent: python-requests/2.18.4
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 790

client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}&code={code}&grant_type=authorization_code&resource=https%3A%2F%2Fapi.office.com%2Fdiscovery%2F
```

I often get such responses:
```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
x-ms-request-id: ...
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: ...
Set-Cookie: x-ms-gateway-slice=007; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Date: Sun, 10 Dec 2017 12:45:18 GMT
Content-Length: 547
Connection: Keep-alive

{"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70008: The provided authorization code or refresh token is expired. Send a new interactive authorization request for this user and resource.\r\nTrace ID: {trace_id}\r\nCorrelation ID: {correlation_id}\r\nTimestamp: 2017-12-10 12:45:19Z","error_codes":[70002,70008],"timestamp":"2017-12-10 12:45:19Z","trace_id":"{trace_id}","correlation_id":"{correlation_id}"}
```
It seems like authorization code expires in less than one hour. Is it correct or am I doing something wrong? If you could - provide any documentation about authorization code expiration, please.

I'm building a third-party client for OneDrive and it uses OneDrive API and I want to make it "remember" access credentials so that a user won't be needed to enter login/password too often to retrieve authorization codes.

If the authorization code really expires so fast it turns out that it's impossible to do that. Maybe there are other ways?

**Comment by ificator** [comment]
Do you see a refresh token come back for the `/common/oauth2/token` requests that succeed? You should be able to utilize that token in future requests to maintain long term access (see [this documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth#step-4-redeem-refresh-token-for-an-access-token-to-call-onedrive-api)).

**Comment by AndrewPashkin** [comment]
@ificator, okay, I see, thank you.

**Comment by AndrewPashkin** [comment]
@ificator, is it possible somehow to implement "login automatically" authentication option in an application that uses the API?
