### ISSUE TITLE
/me/drives/ returns 404

### ISSUE THREAD

**Issue by AndrewPashkin** [OneDrive/onedrive-api-docs#751]
Here is the dump of the HTTP session:
```
< GET /_api/v2.0/me/drives/ HTTP/1.1
< Host: pashkin-my.sharepoint.com
< User-Agent: python-requests/2.18.4
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Authorization: Bearer {access_token}
< 

> HTTP/1.1 404 Not Found
> Cache-Control: private, max-age=0
> Transfer-Encoding: chunked
> Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
> Expires: Sat, 25 Nov 2017 21:55:25 GMT
> Last-Modified: Sun, 10 Dec 2017 21:55:25 GMT
> P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
> X-SharePointHealthScore: 0
> X-SP-SERVERSTATE: ReadOnly=0
> ODATA-VERSION: 4.0
> SPClientServiceRequestDuration: 11
> SPRequestDuration: 95
> X-AspNet-Version: 4.0.30319
> SPRequestGuid: 9c49359e-40d2-4000-cd45-957ae17b1002
> request-id: 9c49359e-40d2-4000-cd45-957ae17b1002
> MS-CV: njVJnNJAAEDNRZV64XsQAg.0
> Strict-Transport-Security: max-age=31536000
> X-FRAME-OPTIONS: SAMEORIGIN
> X-Powered-By: ASP.NET
> MicrosoftSharePointTeamServices: 16.0.0.7129
> X-Content-Type-Options: nosniff
> X-MS-InvokeApp: 1; RequireReadOnly
> X-MSEdge-Ref: Ref A: 907485BB78F542F58539D730A840121F Ref B: AMSEDGE1117 Ref C: 2017-12-10T21:55:25Z
> Date: Sun, 10 Dec 2017 21:55:24 GMT
> 
{"error":{"code":"itemNotFound","message":"The resource could not be found."}}
```

I was referring to this page:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_list#list-the-current-users-drives

It says:
> List the current user's drives
> GET /me/drives

p.s.
I get the same thing with API v1.0.

**Comment by AndrewPashkin** [comment]
I've also managed to get 500 response:
```
< GET /_api/v1.0/drives/ HTTP/1.1
< Host: pashkin-my.sharepoint.com
< User-Agent: python-requests/2.18.4
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Authorization: Bearer {access_token}
< 

> HTTP/1.1 500 Internal Server Error
> Cache-Control: private, max-age=0
> Transfer-Encoding: chunked
> Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
> Expires: Sat, 25 Nov 2017 22:11:58 GMT
> Last-Modified: Sun, 10 Dec 2017 22:11:58 GMT
> P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
> X-SharePointHealthScore: 0
> X-SP-SERVERSTATE: ReadOnly=0
> ODATA-VERSION: 4.0
> SPClientServiceRequestDuration: 44
> SPRequestDuration: 154
> X-AspNet-Version: 4.0.30319
> SPRequestGuid: 8f4a359e-405d-4000-8573-a1d48337854b
> request-id: 8f4a359e-405d-4000-8573-a1d48337854b
> MS-CV: njVKj11AAECFc6HUgzeFSw.0
> Strict-Transport-Security: max-age=31536000
> X-FRAME-OPTIONS: SAMEORIGIN
> X-Powered-By: ASP.NET
> MicrosoftSharePointTeamServices: 16.0.0.7129
> X-Content-Type-Options: nosniff
> X-MS-InvokeApp: 1; RequireReadOnly
> X-MSEdge-Ref: Ref A: DAD0215EAC284AE8AE4C5203DE95D536 Ref B: AMSEDGE0916 Ref C: 2017-12-10T22:11:58Z
> Date: Sun, 10 Dec 2017 22:11:58 GMT
> 
{"error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":"The file |0 does not exist."}}
```

**Comment by ificator** [comment]
Hi @AndrewPashkin, unfortunately the documentation is for Graph while you're trying to hit SharePoint directly. While the documentation is mostly applicable there are some differences that you need to be aware of.

Specifically, for your case I'd avoid using "me" directly - you should be able to hit `https://<tenant-my>.sharepoint.com/_api/v2.0/drives` and have it succeed. I'd also avoid trying v1.0 as it's a very old version of the API implementation on SharePoint and is in no way comparable to the v1.0 implemented for Graph or the v1.0 implemented for OneDrive Consumer.

**Comment by AndrewPashkin** [comment]
@ificator, I used this tutorial:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth

And it [says][1] (end of the paragraph) that I should use `https://{tenant}-my.sharepoint.com/_api/v2.0/` type of endpoint. I would use Graph API but I don't know how to do it.

[1]: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth#using-azure-active-directory-for-authentication

**Comment by AndrewPashkin** [comment]
I try to use this one:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth#code-flow

But I get this error when I try to retrieve the authorization code:
```
http://localhost:8080/?error=unauthorized_client&error_description=AADSTS70001%3a+Application+'<client-id>'+is+not+supported+for+this+API+version.Trace+ID%3a+7546d96e-7ced-4455-a2cb-d656a9b00000Correlation+ID%3a+88f7dcbb-552f-4a67-b188-4addf6fc776fTimestamp%3a+2017-12-14+21%3a37%3a06Z
```

**Comment by ificator** [comment]
You can still hit the SharePoint endpoint directly if that works for you, you just need to be prepared for some subtle differences between the documentation you referenced and what the SharePoint endpoint will accept.

One of those is how to enumerate drives - you cannot use "me". Instead the following should work:

`https://{tenant}-my.sharepoint.com/_api/v2.0/drives`

Changing that is probably easier than trying to figure out why your auth for Graph isn't working, but we can drill into that if you want to switch as well :)

**Comment by AndrewPashkin** [comment]
@ificator, well if you don't know out of the top of your head what `Application+'<client-id>'+is+not+supported+for+this+API+version.` error message could indicate I think I'm gonna stick with SharePoint endpoint for now then.
