### ISSUE TITLE
Using custom redirect URI not working

### ISSUE THREAD

**Issue by Santhosini** [OneDrive/onedrive-api-docs#753]
I'm trying to use the latest file picker (v7.2) for integrating it with my helpdesk. I use custom redirect URI. 
I've mentioned the redirect uri in https://apps.dev.microsoft.com same as 'https://abctest.freshdesk.com/helpdesk'. When i call initOneDrivePersonal my helpdesk gets loaded in the iframe with the url 

_https://abctest.freshdesk.com/helpdesk?oauth=%7B%22clientId%22%3A%22xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx%22%2C%22endpoint%22%3A1%2C%22scopes%22%3A%5B%22Files.ReadWrite.All%22%5D%2C%22origin%22%3A%22https%3A%2F%2Fabctest.freshdesk.com%22%2C%22redirectUri%22%3A%22https%3A%2F%2Fabctest.freshdesk.com%2Fhelpdesk%22%2C%22loginHint%22%3A%22onedriveaccount%40freshdesk.com%22%2C%22isConsumerAccount%22%3Atrue%2C%22state%22%3A%22https%3A%2F%2Fabctest.freshdesk.com_WREU4%22%7D_ 

```
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>


function initOneDrivePersonal() {
      let odOptions = {
        clientId: 'xxxxx',
        action: 'share',
        multiSelect: true,
        advanced: {
          redirectUri: 'https://abctest.freshdesk.com/helpdesk'
        },
        success (files) {
         console.log(files)
        },
        error () {
        }
      };
      OneDrive.open(odOptions);
    } 
```

**Comment by daboxu** [comment]
hi @Santhosini , first picker v7.2 is not allowed to be embedded a iframe because oauth endpoint will require you have a full window so based on your config, I expect a popup should be invoked. Could you please give me more detail on your issue?

**Comment by Santhosini** [comment]
@daboxu I have an application where my url is https://abctest.app.com/helpdesk/tickets/{{ticket-id}} where ticket-id is dynamic. I invoke the initOneDrivePersonal within my editor to attach onedrive files. I've added my domain https://abctest.app.com as the redirect URI in https://apps.dev.microsoft.com. But I get the following 
**https://login.live.com/err.srf?lc=2057#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=https://abctest.app.com_3jadw**


```
function initOneDrivePersonal() {
      let self = this;
      let odOptions = {
        clientId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        action: 'share',
        multiSelect: true,
        success (files) {
         console.log(files)
        },
        error () {
          
        }
      };
      OneDrive.open(odOptions);
    } 
```
So I tried the custom redirect URI which din't work. By iframe I meant that the Onedrive popup loaded my application rather than onedrive signin page.

**Comment by daboxu** [comment]
hi @Santhosini , for oauth purpose, the dynamic uri is not recommend and a static uri is good. Can you have a static page holds the picker?

**Comment by daboxu** [comment]
pinging

**Comment by Santhosini** [comment]
No I don't have a static page. Is there any workaround for this? We need the file picker in our helpdesk. Previously we developed the onedrive picker adding the "https://js.live.net/v5.0/wl.js" -
 **WL.fileDialog** which no longer works. I get a 500 on GetItems request and get the following error - "These files couldn't be shared. Please try again later" when I try to attach files from onedrive.

**Comment by daboxu** [comment]
@Santhosini sorry for that. v5.0 is very old and we really want to onboard on the new SDK. I am curious about how's your application config for the v5.0 picker? It didn't use oauth?

**Comment by Santhosini** [comment]
So previously onedrive picker was written as below.

```
<script type="text/javascript" src="https://js.live.net/v5.0/wl.js"></script> 
<script>
WL.init({ client_id: 'xxxxx',              
 redirect_uri: 'https://login.app.com/onedrive/callback', response_type: 'code'}); 

 WL.login({ 'scope': 'wl.skydrive wl.signin onedrive.readwrite' , 'state': '<%= request.protocol + request.host_with_port%>'}).then(
   function(response) {  
    WL.fileDialog({
        mode: 'open',
        select: 'single'
    }).then(
    function(response) {
        console.log(“in”);
    });
});     
}
</script>
```

The same redirect uri(https://login.app.com/onedrive/callback) was mention in the one drive app. The picker was accessed from https://abctest.app.com/helpdesk/tickets/{{ticket-id}}

**Comment by daboxu** [comment]
I see. Thanks for the info. As you have a static page `https://login.app.com/onedrive/callback` so actually you can fetch an access token and pass it to the onedrive picker instead of delegate the oauth work to the picker SDK.

```javascript
var option = {
    ...other config...
    advanced: {
        accessToken: xxxxxx
        endpointHint: 'api.onedrive.com'
     }
     ...other config...
}
```

You can find more detail info about the `accessToken` and `endpointHint` in the advanced options: https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file#advanced-options. Hope this may help you.

**Comment by Santhosini** [comment]
But while I click "switch account" in the picker how can I handle it?

**Comment by jeremyroelfs** [comment]
I think this is the answer you are looking for?

Say your page url is http://localhost:80000/Do/Something/45678 or http://localhost:80000/Do/Something/?id=45678

You can't redirect because you need a "static" url like http:/localhost:80000/Do/Something

Set your redirectUri to that static URL; like so:
var odOptions = {
action: "query",
advanced: {
redirectUri: "http://localhost:80000/Do/Something"
}
}
OneDrive.open(odOptions);

And make sure you add the same exact static Url (http://localhost:80000/Do/Something) to your Redirect URLs in your microsoft "my applictions"

This will ignore the dynamic part of the url and allow you flow as expected.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
