### ISSUE TITLE
Get shared Link for multiple files/folders

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#758]
This is actually a question/request not a but, I'm wonder if it's possible to get a shared link for multiple files from the API. I see this action is possible from onedrive official page but I don't see any instruction how to do that from the API document.
I tried the below  request but it doesn't work, please advice.
`https://api.onedrive.com/v1.0/drive/items/{id1},{id2}/oneDrive.createLink`

Thanks,

**Comment by ificator** [comment]
Unfortunately there isn't currently a way to execute a bulk `oneDrive.createLink` call, so you'd unfortunately need to make a request for each of the items. I'd suggest heading over to our UserVoice site and upvoting (or creating if you cannot find one) suggestions that are relevant ([here's one](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7109264-allow-bulk-sharing-and-unsharing) that looks pretty close ).

**Comment by neunygph** [comment]
Oh ok, thanks @ificator  for the input.
