### ISSUE TITLE
[Question] about sign user out, what is the meaning of clearing cached token?

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#76]
according to http://onedrive.github.io/auth/msa_oauth.htm#sign-the-user-out

the sign out operation will do:
1. Delete any cached access_token or refresh_token values you've previously received from the OAuth 2 flow.
2. Perform any sign out actions in your application (cleaning up local state, removing any cached items, etc).
3. Make a call to the authorization web service using this URL:
GET https://login.live.com/oauth20_logout.srf?client_id={client_id}&redirect_uri={redirect_uri}

If my application delivery many access_tokens to many users, one of the user (maybe application did in background) trigger the sign out url, then what will happen or affect to other access_tokens?

Cause the parameters in the url does not point out which access_token I want to sign out(no Authorization information in the header), how could I know this API really do?

**Comment by rgregg** [comment]
We assume that somewhere in your code, you're holding on to the access_token and refresh_token that you received during the OAuth flow. To "log out" of your application you need to forget those stored values so your app won't continue using them.

**Comment by mikechiu1012** [comment]
OK, I see, thanks for reply :)
