### ISSUE TITLE
SDK - File saver question/request

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#761]
I'm trying to select a directory with file picker v7.2 - OneDrive.save({action: "query"}). Everything is working as expected but it would be nice to show "select" button instead of "save"button since the action is query. Is it possible to change this button text according ?

Thanks,

**Comment by daboxu** [comment]
hi @neunygph that's for the feedback, it is on our backlog for future update.

**Comment by neunygph** [comment]
Hi @daboxu ,

Is there a specific page/forum from OneDrive that is for features request rather than going here ?

Thanks,

**Comment by daboxu** [comment]
hi @neunygph Github is one source we are actively tracking and there is also an [user voice](https://onedrive.uservoice.com/forums/262982-onedrive) page.

**Comment by neunygph** [comment]
Oh great, I didn't know about this user voice page. Thanks, @daboxu 

Phuong
