### ISSUE TITLE
cTag is returned even if the documentation says otherwise

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#763]
The "Remarks" section of [driveitem_delta.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delta.md#remarks) states that `cTag` is not returned when using the `delta` action.
However in my test on OneDrive Personal it is always returned.

**Comment by ificator** [comment]
Hi @skilion - this looks like a documentation bug. OneDrive Personal will return `cTag`, `lastModifiedBy`, and `size` for delta requests - it's OneDrive for Business that has the limitations on those fields.

**Comment by ificator** [comment]
Documentation has been updated.
