### ISSUE TITLE
Inconsistent behavior of delta with remote items

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#764]
The page [driveitem_delta.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delta.md) and the section "Using Delta with remote items" in [sharing-links.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/using-sharing-links.md#using-delta-with-remote-items) do not explain how delta (called on the root of the default drive) behaves when there are changes in the shared folders.

In my tests on OneDrive Personal, when files are **created**, **edited** or **deleted** in the shared folder then the folder is announced in the delta call. However when files are just **renamed**, the shared folder is _not_ announced in delta.
In both cases a separate delta call for the specific shared folder does return all changes.

This creates an inconsistent behavior, how do I detect changes in the shared folders? Should I always call delta on each separate folder or I should call it only when I see a shared folder announced in the delta call of the root dir?

**Comment by ificator** [comment]
You should always be calling delta on the shared items to guarantee you notice all changes. The local item (the one with the `remoteItem` facet) is essentially a pointer to the shared item, and while there are scenarios where it's updated as a result of a change in the shared item there are many where it is not.

We'll update the documentation to make this more clear.

**Comment by ificator** [comment]
Documentation has been updated.
