### ISSUE TITLE
cTag does not change for Office documents

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#765]
When office documents are edited (either through the web or desktop app) the `cTag` does not change. The `eTag` and `lastModifiedDateTime` do change however.

Is this a bug? Should I drop the `cTag` altogether and just monitor the `lastModifiedDateTime` to detect content changes of files?

(Tested on OneDrive Personal)

**Comment by ificator** [comment]
Yeah, this is a bug - thanks for reporting! In the past `cTag` wasn't even exposed for office documents but we made a change recently to do so. Obviously that change has some issues due to how editing of office documents works.

**Comment by ificator** [comment]
This issue should now be fixed - please let us know if you still see unexpected behavior.

**Comment by hshank** [comment]
I renamed an Excel file, and notice that the ctag is still changing?
I thought ctag changes only if content changes.

Is this a known issue?
