### ISSUE TITLE
Conflict behavior does not work for copy in ODC

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#766]
When monitor the copy progress, the get request to `https://api.onedrive.com/v1.0/monitor/{monitorId}` return 500 error "_at the end_" when copy item with the same name in the same directory. It works fine with when copying item with different name.

For instance I have img1.png belong to folder1, the monitor progress request worked as expected when copying img1.png to folder2. The monitor request return error with copying another image with the same name img1.png to folder 2.

The copy endpoint that I used is `https://api.onedrive.com/v1.0/drive/items/{itemid}/oneDrive.copy`

Error message from monitor request `{"error":{"code":"operationNotFound","message":"The operation does not exist."}}`

Is there a way to make it auto rename when copying a file with the same name?

Thanks,
Phuong Nguyen

**Comment by ificator** [comment]
Hi @neunygph 

Can you show me what the body of the copy request looks like? I'm curious to know if you're including a conflict behavior.

Also, could you provide the an example monitor URL that returns the `The operation does not exist` error? Do you know how old the URL was when you got that error?

**Comment by neunygph** [comment]
Hi @ificator ,

I don't see any option to include conflict behavior in the body of the copy request from the document https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy
Below is the body of the request.
```
{
"parentReference":{"driveId":"90c80432fa7813fc","id":"90C80432FA7813FC!5549"},
"name":"download (2)(copy).jpg"
}
```
Also, I don't see the "operation does not exist" error anymore but it returned failed status for me and below is the URL

https://api.onedrive.com/v1.0/monitor/4svYMn7xovsDVf2M9ui9w67vhno27GIOzEpUGjXfk1cuGmfAEz4A7a8yjgf7QDXBZBRlpT7TFnghenkOf7tS2rwuiGEdHn3zOA66e8chh0hCUXkFv8_ZHkWHDk2Mr2lnltAjjBrYKHxrJh0m1q5fgPh5gmONHxgX1YyZCkbD0Wux_wwTtGJTKM03gwqosiAtdIGsyDCP6v1LEkVVQZDkkQFcSpmrMSopVrKycVuUI-PTrqqEQIMHmH9OskBQxISUP9

Please let me know if you need any additional information.

Thanks,
Phuong

**Comment by ificator** [comment]
I checked the code and copy is indeed special - I'll figure out why that is, but in the mean time you can add a `@name.conflictBehavior` query string parameter and you should hopefully see the behavior you expect.

As for the `operation does not exist`, that is most likely resulting from the completion state (failure or otherwise) being purged from the system after 24 hours. For example, the URL you gave is now resulting in that error.

If you past in the error response you're getting when it's not `operation does not exist` I might be able to provide more context on what's going on for your scenario.

**Comment by neunygph** [comment]
Hi @ificator 

I saw the "operation does not exist" 1 or 2 seconds after I made the copy request because I checked the upload status right away as soon as the copy request return with 202 response. But I don't see that anymore , I only see failed status as now as mentioned above.

For the @name.conflictBehavior, I tried both below cases but it doesn't copy or rename though the copy request returned 202 status. Not what if I missed anything, please advice.

`/drive/items/{id}/oneDrive.copy?@name.conflictBehavior=rename`
AND
```
{
"parentReference":{"driveId":"90c80432fa7813fc","id":"90C80432FA7813FC!5549"},
"name":"download (2)(copy).jpg",
"@name.conflictBehavior": "rename"
}
```

Thanks,
Phuong

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
