### ISSUE TITLE
FileSize is not matching when downloading for some users

### ISSUE THREAD

**Issue by abhinitjava** [OneDrive/onedrive-api-docs#769]
When i requesting microsoft graph url For getting the File Info
Request URI :- https://graph.microsoft.com/v1.0/me/drive/items/fileId
its returning the file size in JSON response with  "size": 17410 (in KB).

But when i am trying to download the same file with
Request URI :-https://graph.microsoft.com/v1.0/me/drive/items/fileId/content 
then its giving Input Stream  then i am storing in my local system.
its giving different "size" 14267 (in Kb)

At last its not giving for all files its only for particular user i am getting.

**Comment by ificator** [comment]
Hi @abhinitjava are you calling as a OneDrive Consumer user, or a OneDrive business user? Do you only see this for certain types of files (e.g. Office files), or do you see it for lots of different types?

**Comment by abhinitjava** [comment]
Hi @ificator i am calling OneDrive Consumer user and i saw this problem in file (.jpg,.png.excel file)

**Comment by ificator** [comment]
Interesting, thanks @abhinitjava. Do you have an item ids for files that have this issue?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
