### ISSUE TITLE
some name to json response when single item is return

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#77]
can we have some name to json response when single item is return, as "values" in case of list response

making difficult to understand otherwise

**Comment by rgregg** [comment]
Can you provide an example here @ankit-ankuagrawal ?

When we have an API path that always returns a single item (e.g. /drive, /drive/items/{item-id}) the object that we return is the single item, you shouldn't need to guess if it's an item or a collection.

For paths that return collections, we always return an object with a property "value" which is an array of the objects that could be returned. We use this structure, even if only one item will be returned in the collection.

If there are places in the API where this is confusing or unclear, I'd love those specific examples. Thanks!

**Comment by ankit-ankuagrawal** [comment]
may be not so right, but still will like to give ex

made 1 class OneDriveItem contains all variables that are return in json
format

according our requirement for each operation we have 1 class

now lets getting one file/folder have class OneDriveGetItem here have to
write again all variables in this class and stuff (using gson library)

again in case of other operations where single file/folder is return

and in case when collection is return have class OneDriveItemList, just
required to have variable of List<OneDriveItem> value and thats it

pls make me correct, if something is wrong

**Comment by ankit-ankuagrawal** [comment]
got the solution to the my problem...

ty for ur response
