### ISSUE TITLE
Are the new Converge Apps Backwards Compatible with the Live SDK API?

### ISSUE THREAD

**Issue by cassiedbrown** [OneDrive/onedrive-api-docs#771]
We are currently using the Live SDK API in our integration with OneDrive. However, new customers do not have the ability to create Live SDK Applications, since this is being deprecated. We are working toward migrating to the new Graph API, however, my question is do the new Converged Apps (to be used with the Graph API) still work with the Live SDK API or can only new customers who only have access to Converged Apps use the Graph API?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
