### ISSUE TITLE
409 for "conflictBehaviour":"replace"

### ISSUE THREAD

**Issue by atchyuth** [OneDrive/onedrive-api-docs#772]
Is there a way to replace the files while uploading(Upload large files) files to One drive using POST method. I know there's is a "rename" and it works perfect in all cases. But I would like to replace instead of rename. I tried below in the body request but no luck:

```
{
    "item": {
        "@microsoft.graph.conflictBehavior": "replace"
    }
}
```

For some reason without any extra request in the body the files were replaced without any conflict error in some cases but fails in most of the time. It's like 40% success and 60% unsuccessful. Error response below: 

```
[Create Upload Session] Error: The remote server returned an error: (409) Conflict.
Response Url: https://graph.microsoft.com/v1.0/me/drive/root:/Test/TestFile.xlsx:/createUploadSession

Status Code: Conflict

Response Body: {
  "error": {
    "code": "nameAlreadyExists",
    "message": "The specified item name already exists.",
    "innerError": {
      "request-id": "6c94042c-1bbf-443f-a5f5-919966a79089",
      "date": "2018-01-11T15:51:43"
    }
  }
}
```
Is this supported yet? If not any plans in the near future?

Any help would be appreciated. Thanks!

**Comment by ificator** [comment]
This should theoretically work - can you tell me if you're calling Graph for a OneDrive Consumer or a OneDrive Business account?

**Comment by atchyuth** [comment]
I’m using OneDrive Business account!

**Comment by ificator** [comment]
Hi @atchyuth,

If you don't provide a `@microsoft.graph.conflictBehavior` value at all in the body does it end up replacing the content like you expect?

**Comment by atchyuth** [comment]
Most of the cases it fails to replace. Somehow got replaced on few occasions without  @microsoft.graph.conflictBehavior

**Comment by atchyuth** [comment]
Hi @ificator 
Any insights on this?

**Comment by ificator** [comment]
Hi @atchyuth I'm having trouble pulling the logs for the failure in your issue description, could you paste in another Graph response when it gave the `nameAlreadyExists` error?

**Comment by atchyuth** [comment]
hi @ificator thanks for the response.
I'll post as I see any.

**Comment by atchyuth** [comment]
Hi @ificator here's a couple more cases where I received 409 though I'm sending below in the body request:
`{
    "item": {
        "@microsoft.graph.conflictBehavior": "replace"
    }
}`

Error message

`The remote server returned an error: (409) Conflict.
Response Url: https://graph.microsoft.com/v1.0/drives/b!bLuFVDUjeUefUPrxgKOR3f8oepOI6q5KjYSaxWXbSVlsk3Qy_VDIRIT-8TAHR_zE/items/01F3OM7KJOGXW5GZP635E2OJ5W7YFUW5SL:/PendingPrintOptys.xlsx:/createUploadSession

Status Code: Conflict

Response Body: {
  "error": {
    "code": "nameAlreadyExists",
    "message": "The specified item name already exists.",
    "innerError": {
      "request-id": "18f8f30b-54f9-4b94-a735-cfa5dc8d4e72",
      "date": "2018-01-17T14:04:13"
    }
  }
}`

After retry error message
`{
    "error": {
        "code": "nameAlreadyExists",
        "message": "The specified item name already exists.",
        "innerError": {
            "request-id": "c3caa024-7189-4d0a-84b8-cb7d18898887",
            "date": "2018-01-17T14:06:57"
        }
    }
}`

**Comment by atchyuth** [comment]
Hi @ificator , any update on this please?

**Comment by ificator** [comment]
It looks like the failure is actually being triggered by concurrent uploads to the same file. Internally I see the following:
```
A file with the same name is currently being saved to this site. Change the filename and try to save again. 
```

Unfortunately this is a limitation in OneDrive Business that does not exist in OneDrive Consumer. I'm going to try to repro, and if I can I'll make sure the error message is at least useful.

**Comment by atchyuth** [comment]
Hi @ificator if I understood you correct, you're saying I tried to upload files with the same name at the same time which caused the error? Please correct me if I'm wrong. 

If this is the case, replace should work fine without any problem if files don't have the same name right?

**Comment by ificator** [comment]
The specifically scenario that seemed to be happening was:

1. File `foo.txt` was created
2. An upload session was created for `foo.txt`
3. Another upload session was attempted to be created for `foo.txt` and failed because the one from (2) was already in progress.

Even if the conflict behavior was replace, the fact that two sessions were in attempted for the same file meant a conflict was still generated. I've made a change to improve the error message, but ideally we'd allow this kind of thing like we do for OneDrive Consumer. Unfortunately that's a non-trivial change for OneDrive Business.

**Comment by kexingcui** [comment]
The end result? This replacement is not allowed?
