### ISSUE TITLE
Uploading files to shared withMe on OneDrive?

### ISSUE THREAD

**Issue by atchyuth** [OneDrive/onedrive-api-docs#773]
Is it possible to upload files to the folders that were Shared with Me? If so, which is the right syntax for the PUT (small file) or POST (upload session)?

I have the scopes (i.e. **Files.ReadWrite.All**) to upload to another user's drive. After going through the documentation I found this `POST /users/{userId}/drive/items/{itemId}/createUploadSession` but I'm not sure on to get the **UserId** & **ItemId**. 

Can someone point me in the right direction on how to achieve this?

Thanks!

**Comment by ificator** [comment]
You'll need to discover the appropriate user id and item id in order to successfully upload to someone else's drive. Ideally that information would come from a shared with me query, which should contain everything you need.

Another option is to use `/drives/{driveId}/items/{itemId}` if you have a drive id but not a user id.

**Comment by atchyuth** [comment]
Querying for shared with me returns json object with DriveId’s but I don’t see any value for ItemId’s.

**Comment by atchyuth** [comment]
In the below JSON response object what is to be considered as ItemID?

`"value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "createdBy": {
                "user": {
                    "email": "",
                    "displayName": ""
                }
            },
            "createdDateTime": "0001-01-01T00:00:00Z",
            "id": "01GDUP4VCIN2BBBKTHF62SQSPGSL",
            "lastModifiedBy": {
                "user": {
                    "email": "tom@gmail.com",
                    "displayName": "tom"
                }
            },
            "lastModifiedDateTime": "2018-01-07T10:27:00Z",
            "name": "SharedFolderTest",
            "parentReference": {
                "driveId": "b!Yeoxv_U50kUcSJIIlws0hHs2CKf19Z7u-Bj8fiYPiIRoYFm_xEDBM3",
                "driveType": "business"
            },
            "webUrl": "https://my.sharepoint.com/personal/username/Documents/SharedFolderTest",
            "fileSystemInfo": {
                "createdDateTime": "0001-01-01T00:00:00Z",
                "lastModifiedDateTime": "2018-01-07T10:27:00Z"
            },
            "folder": {
                "childCount": 0
            },
            "remoteItem": {
                "createdBy": {
                    "user": {
                        "email": "tom@gmail.com",
                        "displayName": "Tom"
                    }
                },
                "createdDateTime": "0001-01-01T00:00:00Z",
                "fileSystemInfo": {
                    "createdDateTime": "0001-01-01T00:00:00Z",
                    "lastModifiedDateTime": "2018-01-07T10:27:00Z"
                },
                "folder": {
                    "childCount": 0
                },
                "id": "01GDUXYSIE5PBBBKTHF62SQSPGSL",
                "lastModifiedBy": {
                    "user": {
                        "email": "tom@gmail.com",
                        "displayName": "tom@gmail.com"
                    }
                },
                "lastModifiedDateTime": "2018-01-07T10:27:00Z",
                "name": "SharedFolderTest",
                "parentReference": {
                    "driveId": "b!1ah26tEN4EGPYuimketNpPYVSlCq0OPmgr0nthFghQF2iaXQbwlN763AyWT"
                },
                "shared": {
                    "scope": "users",
                    "sharedBy": {
                        "user": {
                            "displayName": "Tom"
                        }
                    },
                    "sharedDateTime": "2018-01-07T18:29:00Z"
                },
                "sharepointIds": {
                    "listId": "051482-26da-4197-bc25-37be032593",
                    "listItemId": "267",
                    "listItemUniqueId": "51fb04-ba21-4208-a99c-bea1279a4b",
                    "siteId": "ea76d5-0dd1-41e0-8f62-e8ecbb7a36",
                    "siteUrl": "/personal/usernmae",
                    "webId": "9336a7-55d8-4229-ab43-8f9a0af49ed8"
                },
                "size": 0,
                "webDavUrl": "https://my.sharepoint.com/personal/username/Documents/SharedFolderTest",
                "webUrl": "https://ypg-my.sharepoint.com/personal/usernmae/Documents/SharedFolderTest"
            },
            "size": 0
        },`

**Comment by ificator** [comment]
You'll want to look at the `remoteItem` within each item - you can think of these kinds of items as pointers to another drive, and the `remoteItem` facet contains information about the target item.

In your case `remoteItem.Id` is the itemid, and `remoteItem.parentReference.driveId` is the driveid.

**Comment by atchyuth** [comment]
After running the query below
`https://graph.microsoft.com/v1.0/me/drives/b!1ah26tEN4EGPYuim7NketNpP0OPmgr0nthFghQF2iaXQbwlN763AyWT/items/01GDUXYSIE5P4VCIN2BBBSQSPGSL/createuploadsession`  I get the following response:
`{
    "error": {
        "code": "accessDenied",
        "message": "Cannot reference a user's drive from another user's personal site",
        "innerError": {
            "request-id": "eb55d374-8624-4159-b387-d977b02b230e",
            "date": "2018-01-12T20:29:12"
        }
    }
}`

I'm using the following scopes: 
offline_access
Files.ReadWrite.All
Files.Read.All
User.ReadWrite

**Comment by ificator** [comment]
In this case the error result is incorrect, and we've got a fix in the pipeline for it already. Essentially, the response shouldn't be a 401 but a 403. You're authenticating successfully, but the attempt to actually create the file is failing due to a lack of permissions.

Can you confirm that the folder in question was shared for writing and not just reading?

**Comment by atchyuth** [comment]
I can confirm the folder has been shared Owner permissions(read & write).

**Comment by ificator** [comment]
Ah I think I see what's going on - the item with id `01GDUXYSIE5P4VCIN2BBBSQSPGSL` is a folder, and so you'll need to add the target file name to the URL for it to create a new file:

```
https://graph.microsoft.com/v1.0/drives/b!1ah26tEN4EGPYuim7NketNpP0OPmgr0nthFghQF2iaXQbwlN763AyWT/items/01GDUXYSIE5P4VCIN2BBBSQSPGSL:/mynewfile.txt:/createuploadsession
```

**Comment by atchyuth** [comment]
Awesome! Works as expected. Thanks for your help.

**Comment by ificator** [comment]
Thanks for confirming @atchyuth, I'm going to mark this as a bug since the error is completely unhelpful.

**Comment by atchyuth** [comment]
Hi @ificator , Can you point me to the right direction to upload to sub folder inside a folder?
I'm using below to upload to main folder:
`https://graph.microsoft.com/v1.0/drives/driveId/items/ItemId:/mynewfile.txt:/createuploadsession`

**Comment by ificator** [comment]
The segments between the colons can be any path relative to the item whose id is `ItemId`. So in your case you could upload to a `subfolder` using:

```
https://graph.microsoft.com/v1.0/drives/driveId/items/ItemId:/subfolder/mynewfile.txt:/createuploadsession
```

**Comment by atchyuth** [comment]
Thanks for your help. Works as expected.
