### ISSUE TITLE
@odata.nextLink when paging the contents of a subfolder does not include subfolder path

### ISSUE THREAD

**Issue by geoffrey-mantel** [OneDrive/onedrive-api-docs#774]
I am paging through the contents of a subfolder containing 500 items, using the "List children of a DriveItem with a known path" API, like this (drive_id intentionally obfuscated):

```
GET https://graph.microsoft.com/v1.0/drives/{drive-id}/root:/Paging%20Bug:/children?$select=id,name
 ```

The value of `@odata.nextLink` is:

```
"@odata.nextLink": "https://graph.microsoft.com/v1.0/drives/{drive-id}/root/children?$select=id%2cname&$skiptoken=UGFnZWQ9VFJVRSZwX1NvcnRCZWhhdmlvcj0wJnBfRmlsZUxlYWZSZWY9Y2F0XzI3OC5qcGcmcF9JRD05ODA"
```

You can see that the folder path has been dropped. I figured this was because the information was encoded in the skiptoken, but this doesn't seem to be the case - this nextLink returns the contents of the root folder.

**Comment by ificator** [comment]
This looks like a regression of https://github.com/OneDrive/onedrive-api-docs/issues/620 :(

**Comment by geoffrey-mantel** [comment]
Any update? Thanks.

**Comment by geoffrey-mantel** [comment]
Any update?

**Comment by ificator** [comment]
It's currently being investigated by the Graph team - hopefully it won't be much longer until it's resolved.

**Comment by ificator** [comment]
I tried this scenario again today and it looks like the Graph issue was resolved as I'm now seeing the path coming back in the `@odata.nextLink`.
