### ISSUE TITLE
File picker issue

### ISSUE THREAD

**Issue by bakarwa** [OneDrive/onedrive-api-docs#775]
I've setup an API account for onedrive file upload and select uploaded files via the file picker. 
`var odOptions = {
 clientId: "APP CLIENT ID",
 action: "download",
 advanced: {
  redirectUri: "redirect url according to app redirect url"
 },
 multiSelect: false,
 openInNewWindow: true,
 success: function(files) { / success handler /
 },
 cancel: function() { / cancel handler / },
 error: function() { / error handler / }
}`
But` it is showing a message "This file couldn't be shared. Please try again later."
<img src="https://snag.gy/EeqabQ.jpg">

Even clicking on Cancel button the same message shows.  How this issue can be fixed?

**Comment by zachzi** [comment]
Hi bakarwa,

Are you still experiencing this issue?  If so, is the OneDrive account a consumer or business / SharePoint account?  As for the 'Cancel' button issue, that should still work regardless of any other errors - will investigate.

Thanks,
zachzi

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
