### ISSUE TITLE
An unspecified error has occurred.

### ISSUE THREAD

**Issue by Woody-Woo** [OneDrive/onedrive-api-docs#777]
Hi,

One of our clients uses Onedrive for Business and gets the following error:

Request:
GET https://<endpoint>-my.sharepoint.com/_api/v2.0/drive 

Response: 
StatusCode:InternalServerError
Content: "{"error":{"code":"generalException","message":"An unspecified error has occurred."}}"

The request runs just after the authorization.:
Response. StatusCode: "OK"; StatusDescription: "OK"; Content: "{"token_type":"Bearer","scope":"AllSites.Read MyFiles.Read MyFiles.Write","expires_in":"3599","ext_expires_in":"0","expires_on":"1516119324","not_before":"1516115424","resource":"https://<endpoint>-my.sharepoint.com","access_token":"...","refresh_token":"...","id_token":"..."}

P.S. We have many clients whose use Onedrive for Business and everything works smoothly except this.

Any ideas?

If you need any other information please let me know.

Thanks.

**Comment by ificator** [comment]
Hi @Woody-Woo, can you provide the values for the `SPRequestId` and `Date` headers in the response that returns the `generalException`?

**Comment by Woody-Woo** [comment]
Hello,

Sorry, but we cannot provide you SPRequestId. We do not log it. We can do it,  but we may need some time.

The utc time interval for the request that return the error is:
reuqest - 2018-01-16 15:15:24.4484
response - 2018-01-16 15:15:25.2185

endpoint - https://kajaine365-my.sharepoint.com

Perhaps this information will be enough?

**Comment by Woody-Woo** [comment]
Hello

SPRequestGuid = bb49449e-a0b2-5000-7c96-99d2951d923c

Request  = 2018-01-26 12:26:23.9395
Response = 2018-01-26 12:26:24.6385

**Comment by ificator** [comment]
Hi @Woody-Woo, it's definitely a lot easier with the GUID so thanks for grabbing one.

It looks like the issue is that the caller doesn't have a license for OneDrive Business, and so that provisioning of the drive is failing:

```
[NoCapabilitiesOrLicense]: You do not have access to create this personal site.
```

I'm going to mark this as a bug to that we can at least return an error that's more meaningful.

**Comment by Woody-Woo** [comment]
Ok. Thanks for your help.

**Comment by D4N14L** [comment]
The fix is now rolling out to production. The error will now be much more clear with the error response, returning a 403 Forbidden with error code: NotAllowed
