### ISSUE TITLE
Issue while setting multiSelect: false.

### ISSUE THREAD

**Issue by Santhosini** [OneDrive/onedrive-api-docs#779]
```
var options = {
    clientId: client_id,
    action: "share",
    multiSelect: false,
    advanced: {
      navigation: {
        disable: true
      },
      endpointHint: "api.onedrive.com",
      accessToken: access_token
    },
    success: successCallback,
    error: errorCallback
  };
  OneDrive.open(options);
```
I've enable single file selection. When I choose a file but then select some other file and then I click "Open", I get the url of whatever I choose first. I'm using this version of the SDK - https://js.live.net/v7.2/OneDrive.js

Say I select "Getting started with OneDrive.pdf" and then "File 2.pdf" when I click open in my successCallback I get the url for "Getting started with OneDrive.pdf" instead of "File 2.pdf"

**Comment by Santhosini** [comment]
Any updates on this? This seems to be a serious issue. What if I selected something personal file and then unselect to choose the right file? But the 1st file gets attached. Any fix on this?

multiSelect: false doesn't work?

**Comment by Arzie** [comment]
We're running into the same issue. Shouldn't be too hard to fix, right?

**Comment by Arzie** [comment]
Great, thanks!

**Comment by sandermak** [comment]
We are running into this as well. Any update on this @zachzi ?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
