### ISSUE TITLE
Request to display authorization code in the body of oauth20_desktop.srf

### ISSUE THREAD

**Issue by cguZZman** [OneDrive/onedrive-api-docs#78]
Is any chance to get the authorization code as a message in the body of oauth20_desktop.srf? and not only in URL?
Something like: "Please, provide the following code to the app: xxxxx-xxxxx-xxxxx-xxxxx-xxxx"
(Drop-box already have it)

What is the point? 
Some clients apps doesn't have a browser embedded. So it's required to final users to go to any browser to make the oauth2 login process. Once the final user finish the process, this will help the user to know what to do next and provide the authorization code to the non-browser-nor-cellphone-app and then happily use their account in more devices.

And why I don't make my own redirect page so I can show whatever I want?
Because if I use my own redirect page instead of oauth20_desktop.srf, it is required to provide my secret password (and therefore distribute my app with my secret password) to get the final access token, and that is what I want to avoid.

does that make sense?

thanks guys for such a great job with this api.

**Comment by rgregg** [comment]
Thanks @cguZZman. I've passed that feedback along to the Microsoft Account team so they can consider it for the next update to the OAuth implementation.
