### ISSUE TITLE
Unable to retrieve tenant service info

### ISSUE THREAD

**Issue by imkk** [OneDrive/onedrive-api-docs#781]
What's meaning of the following error, anybody can tell me how to solve this issuse?
{
	"error": {
		"code": "BadRequest",
		"message": "Unable to retrieve tenant service info.",
		"innerError": {
			"request-id": "59bf9f1d-f25f-4ae4-bd8a-eadb27f75e5f",
			"date": "2018-01-21T13:12:38"
		}
	}
}

**Comment by ificator** [comment]
Hi @imkk do you see this regularly? It looks like an internal error that you shouldn't expect to see.

**Comment by imkk** [comment]
Hi @ificator ,  this issue happens frequently to a user of my app, but I don't know what's the meaning of this error.

**Comment by ificator** [comment]
Hi @imkk, I'm having trouble getting any information for the request - could you provide a new error body so we can try again?

**Comment by imkk** [comment]
Hi @ificator , I‘ll contact the user and let him try again. If the problem reappears, I'll let you know the first time and send you the error body.

**Comment by PatrykBobak** [comment]
Hi. I have a similar problem. From time to time we can see: 
```Message:
Code: BadRequest
Message: Unable to retrieve tenant service info.
Inner error:
        AdditionalData:
        request-id: 762b4062-bedd-4180-abcb-bfb05c7df768
        date: 2020-03-16T01:00:11
ClientRequestId: 762b4062-bedd-4180-abcb-bfb05c7df768
```
In the last  two days, I had this error for 5 different accounts

**Comment by pavelanihimovsky** [comment]
Hi, I have the same issue when I'm trying to read data from my personal azure account. I get 400 Bad Request for
GET https://graph.microsoft.com/v1.0/drives/{drive-id}
and inner exception is: Error message: Unable to retrieve tenant service info.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
