### ISSUE TITLE
Syncing OneDrive for Business shared items

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#782]
It seems to me it is not possible to track changes of shared items in OneDrive for Business.

I think that to sync shared items I have to:
1. get the list of shared items with `me/drive/sharedWithMe`
2. call `delta` on each of them
3. download changes

However, the [docs](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_delta.md#remarks) says that it is not possible to call `delta` on any folder except the root and I have verified it (it gives 501 Not Implemented).

How should I sync shared items then?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
