### ISSUE TITLE
OneDrive server returns 500 if the filter string constains character '

### ISSUE THREAD

**Issue by bryan-liang** [OneDrive/onedrive-api-docs#784]
Hi,

OneDrive server responses with 500 status code with the following request. The filter is name eq 'Bryan's Book'. So how can I encode the filter string if it contains character '?

GET /v1.0/me/drive/items/{item-id}/children?filter=name%20eq%20%27Bryan%27s%20Book%27

Response:

HTTP/1.1 500 Internal Server Error
{                                                                         
  "error": {                                                              
    "code": "generalException",                                           
    "message": "Syntax error at position 16 in 'name eq 'Bryan's Book''.",
    "innerError": {                                                       
      "request-id": "{request-id}",               
      "date": "2018-01-26T00:25:01"                                       
    }                                                                     
  }                                                                       
}

**Comment by ificator** [comment]
You'll need to escape the inner quote:

`GET /v1.0/me/drive/items/{item-id}/children?filter=name%20eq%20%27Bryan%27%27s%20Book%27`

**Comment by bryan-liang** [comment]
Thanks for the answer. It works.
