### ISSUE TITLE
Using external sharing with graph api

### ISSUE THREAD

**Issue by aandis** [OneDrive/onedrive-api-docs#786]
How do I use the [external sharing feature](https://techcommunity.microsoft.com/t5/OneDrive-Blog/Introducing-a-new-secure-external-sharing-experience/ba-p/112624/page/2#comments) through the [graph api](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/)? I am aware of the [driveitem_invite](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite) api and I tried it with `requireSignIn: true` and `sendInvitation: true` but when the user opens the link sent in email, it asks them to login using a microsoft account.
I am looking for a way to share documents with people outside my organization so they can access it without the need to login with a microsoft account.

**Comment by dluces** [comment]
I was also looking at external sharing without requiring the recipient to have a MS account. I saw [this post](https://techcommunity.microsoft.com/t5/OneDrive-Blog/Introducing-a-new-secure-external-sharing-experience/ba-p/112624) about a "new secure external sharing experience". However, I'm not sure how to implement this using the API.

ODB/SPO is quite complicated when it comes to sharing:
1. Cannot do external shares unless `sendInvitation: true` (which makes sense but is not listed as a requirement and see next points)
2. If just `requireSignIn: true` but `sendInvitation: false`, API will return *success* but permission is ephemeral. It won't be listed in the item's permissions and it won't work. Accessing the permission directly will return `404`. Is as if it would get created and deleted right away.
3. Folders need both fields to be `true`. API specifically asks for `requireSignIn: true` if it was `false`.

Can someone confirm that? Is point 2 something that's expected? I don't see it documented anywhere.

**Comment by dluces** [comment]
Also, per [this page](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/sharing):
> **Permissions** on the item allow it to be shared with specific users who must be signed in to access the files.

If that's the case, then why does the API endpoint let us include the `requireSignIn` field? It makes one think that it can have a value of `false`, but the documentation says that with permissions a user must be signed in.

I suppose then that the feature mentioned above for secure external sharing without requiring the user to be signed in would be implemented as access-controlled sharing links?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
