### ISSUE TITLE
issue in redirect url

### ISSUE THREAD

**Issue by GnanaAjana** [OneDrive/onedrive-api-docs#788]
I was opening onedrive picker using following options:

`{
      clientId: ONEDRIVE_CLIENTID,
      action: 'share',
      multiSelect: true,
      advanced: {
        redirectUri: 'abc.com/redirect/onedrive.html'
      },
      success (files) {
      },
      error () {
      }
    }`
I injected script(https://js.live.net/v7.2/OneDrive.js) in both onedrive picker page and redirect url page.

And I created app in 'apps.dev.microsoft.com' and didn't give redirect url. OAuth flow worked fine previously. But since yesterday I've been getting the following error,

> #error=invalid_request&
error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+
The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.

Was there any changes made in script "https://js.live.net/v7.2/OneDrive.js" recently to cause this?

**Comment by zachzi** [comment]
Hi GhanaAjana

If you add the redirect uri to your registered app does this fix your issue?  There haven't been any changes in the OneDrive picker, but it's possible the OAuth flow has been updated to enforce the expectation of a redirect uri.

Thanks,
zachzi

**Comment by delockdown** [comment]
Hi @GnanaAjana ,
Have you found any answer for this issue. I have used the same thing you used, it shows me same error. I tried the example given in the document. Faced with same error. 
Can some one resolve it or suggest a working JS library version or something else

Thank you.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
