### ISSUE TITLE
resumable upload file in size 10G will fail

### ISSUE THREAD

**Issue by mikechiu1012** [OneDrive/onedrive-api-docs#79]
I could successfully upload file in size 1G, 3G, 5G.

but if I upload file in 10G(10737418240), when uploading last fragment(10732175360-10737418239/10737418240), I get the error response:
{"error":{"code":"invalidRange","message":"Uploaded fragment overlaps with existing data.","innererror":{"code":"fragmentOverlap"}}}

I upload with fragment size 5MiB and fail with twice.

i think the only possible is the size limitation issue cause I use the same flow to upload files in different size.

could u please check about this, thanks!

**Comment by ificator** [comment]
If you request the current status (http://onedrive.github.io/items/upload_large_files.htm#request-upload-status) when you hit this problem can you tell us what it says?

**Comment by mikechiu1012** [comment]
I could not reproduce this situation again cause it will take much time.

but I found two wired situations during testing:
1. upload last fragment failed and get status contained nextExpectedRanges ["0-"]
steps:
a. resumable upload 11M file with fragment size 5MiB
b. upload last 1M part with header: {'Content-Length': '1048576', 'Content-Range': 'bytes 10485760-11534335/11534336'} 
c. network problem(ssl error, timeout..., etc.) and retry this fragment upload
d. got response: <Response [416]> {"error":{"code":"invalidRange","message":"Uploaded fragment is out of order.","innererror":{"code":"fragmentOutOfOrder"}}}
e. get upload status and got response: <Response [200]>: {"expirationDateTime":"2015-04-21T15:08:37.0196887+00:00","nextExpectedRanges":["0-"]}

I guess that at step c the uploading process is succeeded, so I got 416 at step d.
but it's wired I will got the nextExpectedRanges if the uploading process is succeeded.

This is the first situation I met.
I'll post another situation in the next comment.

**Comment by mikechiu1012** [comment]
2. nextExpectedRanges over the fragment size I used.
steps:
a. resumable upload 11M file with fragment size 5MiB
b. upload first fragment with headers: {'Content-Length': '5242880', 'Content-Range': 'bytes 0-5242879/11534336'}
c. network problem occurred and retry to upload this fragment
d. got response: <Response [416]> {"error":{"code":"invalidRange","message":"Uploaded fragment overlaps with existing data.","innererror":{"code":"fragmentOverlap"}}}
e. get upload status and got response: <Response [200]>: {"expirationDateTime":"2015-04-21T15:16:53.1030021+00:00","nextExpectedRanges":["5242880-11534335"]}

The nextExpectedRanges is over the fragment size I used (more than 5MiB).
I wonder if file is bigger, nextExpectedRanges will bigger, too.
With response like that, should I upload by the response range or use my fragment still?

**Comment by mikechiu1012** [comment]
I upload the 10G files successfully.

I deal the issues I mentioned before:
1. upload failed by network issue, upload again
2. got 416 response, get nextExpectedRanges in status url and check if range bigger than fragment, upload a fragment, else upload with the nextExpectedRanges in the response

In the case of nextExpectedRanges: "0-", I could only re-upload in current logic.
I think this is the severe issue about the response of range "0-".

**Comment by ificator** [comment]
The intent of nextExpectedRanges is to identify the missing bytes that must be provided to complete the file transfer, and these ranges are not direct mappings to fragments. We updated the documentation recently with [this change](https://github.com/OneDrive/onedrive-api-docs/commit/4c8f0bf96403230ffa17230981d97d5b038027a3) to highlight this - do you feel this update is adequate?

**Comment by mikechiu1012** [comment]
OK, with clear document I think it's enough.
And for recently testing, no failed case happened again. 

I think it's fine to close it.
Thanks for your effort!
