### ISSUE TITLE
OneDrive file picker doesn't work when 'redirectUri' set to different domain for version V7.2

### ISSUE THREAD

**Issue by GnanaAjana** [OneDrive/onedrive-api-docs#790]
I am using script version "**v7.2**" and options as follows:

`var options = {
			      clientId: '1abcxxxyyy23',
			      action: 'share',
			      multiSelect: true,
			      advanced: {
			        redirectUri: 'https://abc1.xxxxx.yyy/assets/integrations/onedrive.html'
			      },
			      success (files) {
			      },
			      error (error) {
			      }
			    }
			    OneDrive.open(options);`

Redirect URL contains script. Onedrive picker domain is 'https://abc.xxxxx.yyy'.

Getting error as:

> redirect uri is not in the same domain as picker sdk

Is there any other possibility that different domains can access redirect URL as specified above?

**Comment by GnanaAjana** [comment]
Any update on this?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
