### ISSUE TITLE
Invalid request - provided id is not suitable for the current host error when requesting a site

### ISSUE THREAD

**Issue by rloehr** [OneDrive/onedrive-api-docs#791]
When requesting drives for a site for a particular tenant, I'm encountering an error that states the provided id is not suitable for the current host.

Here is the flow I am following:
1)  Search for site and get its id:

```
https://graph.microsoft.com/v1.0/sites?search=portal4
```

Response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites",
    "value": [
        {
            "createdDateTime": "2010-04-16T18:56:54Z",
            "description": "Workspace for all internal volunteer projects",
            "id": "seattleworks1org-portal4.sharepoint.com,2b7b00f7-987c-4b2a-b5e2-7a2b99c94d1d,22d63cbc-a320-44db-8c94-521b944203fe",
            "lastModifiedDateTime": "0001-01-01T08:00:00Z",
            "name": "seattleworks1org-portal4.sharepoint.com",
            "webUrl": "https://seattleworks1org-portal4.sharepoint.com",
            "root": {},
            "siteCollection": {
                "hostname": "seattleworks1org-portal4.sharepoint.com"
            },
            "displayName": "Capacity Building Volunteers"
        }
    ]
}
```
```
client-request-id →df6ae32c-ce9c-4741-8415-ae6d188c8520
request-id →df6ae32c-ce9c-4741-8415-ae6d188c8520
x-ms-ags-diagnostic →{"ServerInfo":{"DataCenter":"East US","Slice":"SliceA","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_23","ADSiteName":"EST"}}
```

Now i'll take the id "seattleworks1org-portal4.sharepoint.com,2b7b00f7-987c-4b2a-b5e2-7a2b99c94d1d,22d63cbc-a320-44db-8c94-521b944203fe" and request it.

```
GET Request to:
https://graph.microsoft.com/v1.0/sites/seattleworks1org-portal4.sharepoint.com,2b7b00f7-987c-4b2a-b5e2-7a2b99c94d1d,22d63cbc-a320-44db-8c94-521b944203fe
```

Returns:
```
{
    "error": {
        "code": "invalidRequest",
        "message": "Provided id is not suitable for the current host",
        "innerError": {
            "request-id": "ae9cb469-a0de-41fd-85b1-30eaca281d1b",
            "date": "2018-02-01T14:39:11"
        }
    }
}
```
An sp request id is not returned with this call.
The response headers include:
```
client-request-id →ae9cb469-a0de-41fd-85b1-30eaca281d1b
request-id →ae9cb469-a0de-41fd-85b1-30eaca281d1b
x-ms-ags-diagnostic →{"ServerInfo":{"DataCenter":"East US","Slice":"SliceA","Ring":"2","ScaleUnit":"000","Host":"AGSFE_IN_1","ADSiteName":"EST"}}
```

I'm following docs here:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_get

Is this a data problem on the backend?

**Comment by ificator** [comment]
Hi @rloehr, this is unfortunately a limitation in Graph at the moment where they do not currently send requests to the correct endpoint. A `/sites` query will hit the default endpoint for the tenant, and so if the provided id is for a site on a different endpoint we'll get a failure like this. Work is being done to resolve this limitation.

**Comment by MuhammadMobeen** [comment]
@ificator Thanks a lot for sharing the information. We had been banging our heads against this issue for some time. Any idea when this issue will be resolved?

@rolehr were you able to find a way around to this issue for the moment? We have the same use case and can really use any help in finding a solution.

**Comment by rloehr** [comment]
@MuhammadMobeen we don't have a workaround.

**Comment by smotti** [comment]
@ificator would this also allow access to OneDrive for Business personal sites? For example `/sites/odb-my.sharepoint.com:/personal/some_user_onmicrosoft_com:/`.

**Comment by kevitra** [comment]
Is this still a known issue? I am trying to access a user's OneDrive for Business and I receive this error.  The same code accessing a SharePoint file is fine.

**Comment by smotti** [comment]
This works now. An example request using ODB hostname and a site-path:

```
GET https://graph.microsoft.com/v1.0/sites/example-my.sharepoint.com:/personal/user_example_com:
```

**Comment by kevitra** [comment]
Thanks for the feedback.  Do you know if the .Net Graph SDK supports sending a URL like "example-my.sharepoint.com:/personal/user_example_com:"?  I have been trying but can't figure out the syntax.  I am trying with ItemWithPath. For example (not working):
var items = await graphClient.Groups["teamId/groupId"].Drive.Root .ItemWithPath("example-my.sharepoint.com:/personal/user_example_com:").Children.Request().GetAsync();

**Comment by smotti** [comment]
Sorry with that I can't help. Never used .Net Graph SDK.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
