### ISSUE TITLE
description property of baseItem

### ISSUE THREAD

**Issue by matbech** [OneDrive/onedrive-api-docs#793]
The documentation of baseItem is not clear whether "description" is a property or not:
https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/baseItem.md

The example (JSON representation) shows it as a property but it is no listed in the Properties table.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
