### ISSUE TITLE
Document created via onedrive api can't be opened for editing

### ISSUE THREAD

**Issue by aandis** [OneDrive/onedrive-api-docs#795]
I am doing a `POST` to `https://api.onedrive.com/v1.0/drive/special/approot:/Test.docx:/content` to create a `Test.docx` file in the `AppFolder`. The call succeeds and I see the file being created in the correct location. However, when I visit onedrive and try to open the file in Word Online, I get

![word](https://user-images.githubusercontent.com/4983347/35934974-14fec3b4-0c65-11e8-885f-287333564e06.png)

This only happens for files created via the api. Any ideas?

**Comment by ificator** [comment]
What content are you providing in the body of the request? It will need to be the raw bytes for a valid `docx` file (I.e. NOT base64 encoded)

**Comment by aandis** [comment]
Ah yeah. That was the issue. Thanks.

**Comment by DerekCacciotti** [comment]
Can you provide a code snippet on how to solve this? I'm experiencing this issue right now in one of my apps. thanks
