### ISSUE TITLE
[ODB] frequently receives 429 when requesting

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#797]
Hi all,

Maybe due to the large amount request to Onedrive server,

Now my app receives 429 frequently.

In this case, I want to know the mechanism for this error.
What level this error resided in ? an app or in a user or a domain?
I am going build a throttle control for this error, and find the proper way to do it.

Thanks!

**Comment by ificator** [comment]
The throttles are generally applied for the app in the tenant. If there's a `Retry-After` header in throttling response you should wait that amount of time before trying again, otherwise I'd recommend some kind of exponential back-off.

**Comment by rloehr** [comment]
Our experience thus far has been that the Retry-After time is always 2 minutes.   I've never seen it change.

**Comment by ificator** [comment]
Thanks @rloehr - that wouldn't surprise me and seems like something we could improve. I'll take a note to investigate to see what we can do.

**Comment by joewutaiwan** [comment]
@ificator 
Thanks for the reply,
So the recommended throttle time seems to be 120 sec.
But in my testing, there is no `Retry-After `header in throttling response.

Here is my response:
```
< HTTP/1.1 429
< Content-Length: 125
< Content-Type: application/json; charset=utf-8
< P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
< SPRequestDuration: 76
< SPIisLatency: 7
< X-Powered-By: ASP.NET
< MicrosoftSharePointTeamServices: 16.0.0.7521
< X-Content-Type-Options: nosniff
< X-MS-InvokeApp: 1; RequireReadOnly
< X-MSEdge-Ref: Ref A: 8BDA0A086BA24EB9B24ABF03DC5C6912 Ref B: SG2EDGE0115 Ref C: 2018-03-29T09:44:30Z
< Date: Thu, 29 Mar 2018 09:44:29 GMT
<
{"error":{"code":"activityLimitReached","innererror":{"code":"throttledRequest"},"message":"The request has been throttled"}}
```

**Comment by ificator** [comment]
Thanks for pointing that out @joewutaiwan, I'll see if we can at least make the 429 responses in that regard. In the mean time I guess you can just assume a value of 120 seconds if you do not see the `Retry-After` header on a 429 response.

**Comment by ificator** [comment]
We have a number of issues discussing throttling at the moment so we're going to coalesce into a single one. If you'd like to add your piece, jump over to issue https://github.com/OneDrive/onedrive-api-docs/issues/853 add a comment.
