### ISSUE TITLE
SharePoint Api. 401 Unauthorized with  '429 TOO MANY REQUESTS' in body

### ISSUE THREAD

**Issue by sbukhtiyarov** [OneDrive/onedrive-api-docs#799]
Hello!

Large number of SharePoint API requests have incorrect status code - (401) Unauthorized while response body contains 429 TOO MANY REQUESTS.

request-id for example:
SPRequestGuid: 95bf4a9e-404c-5000-1be1-01d888334eb0
request-id: 95bf4a9e-404c-5000-1be1-01d888334eb0

**Comment by ificator** [comment]
Hi @sbukhtiyarov, we've made some changes with how throttling requests were handled in SharePoint - can you let us know if you're still seeing this?

**Comment by sbukhtiyarov** [comment]
Hello, @ificator!
Unfortunately, still present...

https://_tenant_.sharepoint.com/_api/Web/Lists(guid'guid')?$select=AllowContentTypes,BaseTemplate,BaseType,ContentTypesEnabled,CrawlNonDefaultViews,Created,Description,Direction,DocumentTemplateUrl,DraftVersionVisibility,EnableAttachments,EnableFolderCreation,EnableMinorVersions,EnableModeration,EnableVersioning,EntityTypeName,FileSavePostProcessingEnabled,ForceCheckout,HasExternalDataSource,Hidden,Id,ImageUrl,IrmEnabled,IrmExpire,IrmReject,IsApplicationList,IsCatalog,IsPrivate,ItemCount,LastItemDeletedDate,LastItemModifiedDate,ListExperienceOptions,ListItemEntityTypeFullName,MajorVersionLimit,MajorWithMinorVersionsLimit,MultipleDataList,NoCrawl,ParentWebUrl,ParserDisabled,ServerTemplateCanCreateFolders,TemplateFeatureId,Title


The remote server returned an error: (401) Unauthorized.
StatusCode:Unauthorized
Status:ProtocolError
Headers:
Retry-After: 120
SPRequestDuration: 15
SPIisLatency: 13
x-ms-suspended-features: features=""
MicrosoftSharePointTeamServices: 16.0.0.7514
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: EF697D636F0644A9A6675ED228BFA5AC Ref B: AMSEDGE1119 Ref C: 2018-03-22T13:03:07Z
Content-Length: 21
Content-Type: text/plain; charset=utf-8
Date: Thu, 22 Mar 2018 13:03:06 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
WWW-Authenticate: ....
X-Powered-By: ASP.NET

Response:
429 TOO MANY REQUESTS
