### ISSUE TITLE
Receiving error 412 (Precondition Failed) when trying to update the metadata of an image with OneDrive Personal

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#800]
I randomly receive an error 412 when updating the FileSystemInfo facet just after uploading an image. The error resource is always like this:
```
"error": {
    "code": "resourceModified", 
        "innerError": {
            "date": "<date>",
            "request-id": "<req-id>"
        },
    "message": "ETag does not match current item's value"
}
```
The error is triggered when uploading many images in sequence using simple upload. The operations performed are:
1. PUT image content
2. PATCH using id and `if-match: <cTag>` returned by PUT
3. repeat with next image

I did some tests and this is what I discovered:
- subsequent GET confirmed that cTag stays constant on the file
- eTag always changes after a small time after the upload
- repeating the PATCH operation after some time does not trigger the error again and the operation is performed correctly
- not setting the `if-match` header in the PATCH operation still trigger the error, but the status code changes to HTTP 409, exactly as described in the issue #767

I suspect there is a race condition that makes the PATCH operation fail as @ificator hypothesizes in #767. If that is the case and the conflict cannot be solved, I think at least the error should be changed to something that suggest to retry later like code 503 (Service Unavailable).

**Comment by fabienpe** [comment]
I have the same error when uploading a large number of files: the process stops randomly always with the same exception. When I run the onedrive command again, it picks up from where it stopped and continues for a while, until the same error happens again. So instead of exiting, maybe the app could gracefully handle that exception, display a warning, and continue.

Example of error output:
```
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 412 (Precondition Failed)
{
    "error": {
        "code": "resourceModified",
        "innerError": {
            "date": "2018-03-07T11:20:40",
            "request-id": "2a27a8b6-68d4-4734-a4c5-9981e675c34f"
        },
        "message": "ETag does not match current item's value"
    }
}
----------------
??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x2694c1f8]
??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x2694c2be]
??:? std.json.JSONValue onedrive.OneDriveApi.updateById(const(char)[], const(char)[], std.json.JSONValue, const(char)[]) [0x2694ace7]
??:? void sync.SyncEngine.uploadLastModifiedTime(const(char)[], const(char)[], const(char)[], std.datetime.systime.SysTime) [0x2695719f]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x26956ed8]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956954]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x26956877]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x26955cb9]
??:? void main.performSync(sync.SyncEngine) [0x26943593]
??:? _Dmain [0x269430c3]
```

**Comment by abraunegg** [comment]
@fabienpe 

FYI I added some logic in https://github.com/skilion/onedrive/pull/314 to handle this 412 error. Since adding that logic the 'onedrive' application does not crash on this response and gracefully continues.

**Comment by sksksksk** [comment]
I applied skilion/onedrive#314 and I do not think that it crashes now, but I get the same error messages as fabienpe.

All in all I have 3 files that need to get uploaded to OneDrive, and none of them is being uploaded. So is there any way to solve this?

**Comment by abraunegg** [comment]
@sksksksk  @fabienpe 

I have updated the 'workaround' to be slightly more cleaner. When the error occurs, I check OneDrive & all the files are correct and present.

**Comment by sksksksk** [comment]
I updated the code again and no longer receive the error. i will keep monitoring the process. Thanks!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
