### ISSUE TITLE
[ODB] How to create an item sharing link with grantedToIdentities

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#801]
Hi,

I create a shared link to a file like this:
![image](https://user-images.githubusercontent.com/12619781/36468644-284a8ca4-171f-11e8-8f2f-a2279a86b9ab.png)

The response of permissions is 
```
{
            "@odata.type": "#oneDrive.permission",
            "@odata.id": "https://synologydst-my.sharepoint.com/personal/joyceb_synologydst_onmicrosoft_com/_api/v2.0/drives/b!cz12r4BFEkSuezNMij8SMQ_c8wNP8ypBgKoglc7-nwa61WJH-vSGSJdIkLi6aOR_/items/012DOYZZXO4UTTXSF4SVE2OVE3OLUJW56Q/permissions/OEJBNjA4Q0MtN0Q2MC00RjEzLUEyNzItOEIzQUI5M0ZCOEQ3",
            "@odata.editLink": "drives/b!cz12r4BFEkSuezNMij8SMQ_c8wNP8ypBgKoglc7-nwa61WJH-vSGSJdIkLi6aOR_/items/012DOYZZXO4UTTXSF4SVE2OVE3OLUJW56Q/permissions/OEJBNjA4Q0MtN0Q2MC00RjEzLUEyNzItOEIzQUI5M0ZCOEQ3",
            "expirationDateTime": "0001-01-01T00:00:00Z",
            "grantedToIdentities": [
                {
                    "application": null,
                    "group": null,
                    "user": {
                        "email": "jackiel@synologydst.onmicrosoft.com",
                        "id": "71111e6a-323f-49fc-8900-c6c536536578",
                        "displayName": "Jackie Lee",
                        "self": null,
                        "userPrincipalName": null
                    }
                }
            ],
            "id": "OEJBNjA4Q0MtN0Q2MC00RjEzLUEyNzItOEIzQUI5M0ZCOEQ3",
            "roles": [
                "write"
            ],
            "link": {
                "scope": "anonymous",
                "type": "edit",
                "webUrl": "https://synologydst-my.sharepoint.com/:x:/g/personal/joyceb_synologydst_onmicrosoft_com/Ee7lJzvIvJVJp1Sbcuibd9ABRuYZ-lHafQyCxMANfb17ZA"
            }
        }
```

But I can not find the corresponding document to restore or create this in this page
https://docs.microsoft.com/zh-tw/onedrive/developer/rest-api/api/driveitem_createlink

Could you give me any information about this?

Thanks,
Joe

**Comment by ificator** [comment]
It sounds like you're after the `invite` API.

Have a read through [this documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite) and see if it answers your question.

**Comment by joewutaiwan** [comment]
Hi @ificator ,

In my understanding, there are two type permissions in onedrive item
permission and link.

permission:


> use /invite API
> give permission to a user email based on a file and the response is like

```
...
"grantedTo": {
     "user": {
          "email": "DST8410@synologydst.onmicrosoft.com",
          "displayName": "DST"
     }
},
...
```

link:

> use /createLink API
> give permission to a link base a file

Normally, the link only can be assigned type and scope.
But at the new type of link which I provided above is a grantedToIdentities under that
So I think I should go start with /createLink API, isn't it?

Thanks,
Joe

**Comment by katahir** [comment]
CreateLink api will allow you to create links of type 'anonymous/organization'. This link can then be shared to other people via email. Once they open the link up, they will be added to grantedToIdentities property for that link permission.
If you are looking to invite specific people, you can use the invite api. Invite api can also create links (depending on the tenant configuration). If a link was created for specific people using invite, the link permission will again have grantedToIdentities populated. If the user was a known principal, then the user will be given direct permission with grantedToIdentity populated. Hope that clears up the confusion.

**Comment by pathaniaVikas** [comment]
Hi katahir,
Can you tell how to create links using invite API and what tenant configuration is required. From documentation given here https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite there is no specification of how to create link using invite API, as i am also having the similar issue.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
