### ISSUE TITLE
[ODB] How to download reference attachment at email

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#802]
Hi all,

I created a mail and enclosed a reference attachment.

by using graph API, I could get source url like:
```
https://synologydst-my.sharepoint.com/:u:/g/personal/joyceb_synologydst_onmicrosoft_com/EQBS3ojp0l5JmvY1PQdY2LsBY4M0DJ41LeDIMUPSgQreYA
```

and then redirect to a previewer
![image](https://user-images.githubusercontent.com/12619781/36519652-aee58ad6-17c7-11e8-9724-f51e12773723.png)

click download, the url is:
```
https://synologydst-my.sharepoint.com/personal/joyceb_synologydst_onmicrosoft_com/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fjoyceb_synologydst_onmicrosoft_com%2FDocuments%2FRef%20attachment%2Fnormal%2FEffectiveCpp%20Ch1_item1_4%2Epdf
```

I want to know it is possible to download files like this by onedrive api?

Thanks,
Joe

**Comment by ificator** [comment]
Hi @joewutaiwan you should be able to use the URL from the mail to generate a shares request to our API.

First step is to generate the URL based shared id using [the steps outlined here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get#encoding-sharing-urls). You should end up with something like `u!aHR0cHM6Ly9zeW5vbG9neWRzdC1teS5zaGFyZXBvaW50LmNvbS86dTovZy9wZXJzb25hbC9qb3ljZWJfc3lub2xvZ3lkc3Rfb25taWNyb3NvZnRfY29tL0VRQlMzb2pwMGw1Sm12WTFQUWRZMkxzQlk0TTBESjQxTGVESU1VUFNnUXJlWUE`.

Then you can craft a request to shares like the following to get the metadata for the shared file:

```
https://synologydst.sharepoint.com/_api/v2.0/shares/u!id/root
```

And by extension, something like the following will get you the content:

```
https://synologydst.sharepoint.com/_api/v2.0/shares/u!id/root/content
```

**Comment by joewutaiwan** [comment]
hi @ificator ,

Yes, it works, but when I get shared file which located another domain
like 

> https://synologyqc-my.sharepoint.com/:w:/g/personal/synoqc_synologyqc_onmicrosoft_com/EckIfs3Ks1lOoMnoiGXFNq4BLrpeu0WUcjp-N3ePOlB2eQ

would not work and returns

```
400
{
    "error": {
        "code": "invalidRequest",
        "message": "The site in the encoded share URI is invalid."
    }
}
```

Is it possible to get crossed domain shared file?

Thanks!

**Comment by ificator** [comment]
Throwing this one of the fence now - @kevklam can you answer @joewutaiwan's question?

**Comment by joewutaiwan** [comment]
hi @kevklam 
Is any update here?

Thanks!

**Comment by gmarland** [comment]
Any progress on this? This still appears to be an issue.

Thank you!

**Comment by ificator** [comment]
In the case where you're *not* going through Graph I'd probably just pull the domain from the sharing link and use that for the base, so assuming we want to access:

```
https://synologyqc-my.sharepoint.com/:w:/g/personal/synoqc_synologyqc_onmicrosoft_com/EckIfs3Ks1lOoMnoiGXFNq4BLrpeu0WUcjp-N3ePOlB2eQ
```

Get the hostname from the url, create the encoded id (i'll just call it u!id again), and merge them like:

```
https://synologyqc-my.sharepoint.com/_api/v2.0/shares/u!id/root/content
```

**Comment by gmarland** [comment]
I generated the encoded id (u!id) as defined in the Graph API documentation. Using the URL you provided as an example I did it as follows

```
string base64Value = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("https://synologyqc-my.sharepoint.com/:w:/g/personal/synoqc_synologyqc_onmicrosoft_com/EckIfs3Ks1lOoMnoiGXFNq4BLrpeu0WUcjp-N3ePOlB2eQ"));
string encodedUrl = "u!" + base64Value.TrimEnd('=').Replace('/', '_').Replace('+', '-');
```

I then passed that with a GET request to the endpoint as suggested. I receive in response the following:

`{"error":{"innerError":{"code":"invalidSignature"},"code":"unauthenticated","message":"Token contains invalid signature."}}`

I've tried invaliding the auth token and I receive a different error message in response. This appears to be related to the share token. Am I doing something wrong?

**Comment by ificator** [comment]
Your id looks fine.

What kind of URL did you encode? Was it one that looked like our example, or was it one that had a `tempauth` query string parameter?

If you grab the `SPRequestGuid` and `Date` headers from the failure response I can take a peek and see if there are more details as to what's going on.

**Comment by gmarland** [comment]
I used the c# HttpUtility URLEncode. I tried replacing +'s with %20 but fortunately there were none in the token.

The URL I encoded took the form

> https://ourportal.sharepoint.com/:f:/g/Product_Dev/GUID?e=Characters\

The SPRequestGuid is a87ef19e-10b4-9000-3599-f0b255a19fb9
The Date is Thu, 18 Jul 2019 15:40:13 GMT

Thank you for your help

**Comment by gmarland** [comment]
Any luck with this issue? I've tried to persue this though the Azure support system and the support with my MSDN account... this is the last act of a desperate man!

**Comment by ificator** [comment]
Hi @gmarland - are you calling Graph or hitting SharePoint directly? From the logs it looks like you're hitting SharePoint directly, but providing an auth token that was obtained for Graph. If you want to hit us directly you'll need to get a token specifically for SharePoint.

**Comment by gmarland** [comment]
I was attempting to read the share using the Microsoft Graph API OAuth Token, but I guess it makes sense that it doesnt work with the Sharepoint API. Are there any plans to make external shares available through the Micrsoft Graph API? It feels like something most people would want to do.

**Comment by ODtian** [comment]
same question,need more information

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
