### ISSUE TITLE
Confusing documentation around scopes

### ISSUE THREAD

**Issue by mlafleur** [OneDrive/onedrive-api-docs#803]
The documentation can be pretty confusing when it comes to scopes.

Take for example the [page covering][1] `/approot`. It mentions the `Files.ReadWrite.AppFolder` Graph scope in the first paragraph but switches without context to referencing `onedrive.appfolder` and `onedrive.readwrite`. Unless the reader happens to stumble upon the very last section of the [OneDrive endpoint page][2], they could become very easily confused. Even if they did read that section, they wouldn't know that `Files.ReadWrite.AppFolder` is only supported for MSAs if they looked at the remarks in the [Graph documentation][3].

It would be helpful to have some standardized Permission Scopes format. The standardization picked up by the Microsoft Graph doc set certainly isn't ideal, but it was a reasonable attempt to provide some standardization:

| Permission type                        | Permissions (from least to most privileged) |
| :------------------------------------- | :------------------------------------------ |
| Delegated (work or school account)     | `scope 1`, `scope 2`, `etc`                 |
| Delegated (personal Microsoft account) | Not supported.                              |
| Application                            | `scope 1`, `scope 2`, `etc`                 |

Would something like this make sense?

| Permission type | Microsoft Graph             | OneDrive Personal    | SharePoint and OneDrive for Business |
| :-------------- | :-------------------------- | :------------------- | :----------------------------------- |
| Delegated (AAD) | `Files.ReadWrite.AppFolder` | Not Supported        | `Files.ReadWrite.AppFolder`          |
| Delegated (MSA) | Not Supported               | `OneDrive.AppFolder` | Not Supported                        |
| Application     | `Files.ReadWrite.AppFolder` | Not Supported        | `Files.ReadWrite.AppFolder`          |

[1]: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder
[2]: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences#permissions
[3]: https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference#remarks-5

**Comment by eight04** [comment]
Just spent a whole day on this. I just used `onedrive.appfolder` for authorization, but always got an "InvalidAuthenticationToken" error when querying `/me/drive/special/approot`:
```js
{
  code: 'InvalidAuthenticationToken',
  message: 'CompactToken parsing failed with error code: 8004920A',
  innerError: {
    'request-id': 'dcf5c100-fe8c-4603-9b29-0b4b25a66ca1',
    date: '2019-09-20T13:00:13'
  }
}
```
The error message makes me think that the token is messed up when sending the request. I didn't notice that it is a scope problem.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
