### ISSUE TITLE
Access Token expiry time

### ISSUE THREAD

**Issue by lezoudali** [OneDrive/onedrive-api-docs#804]
When using the new One Drive file picker, after successfully picking the file, we get an `acessToken` back but not an `expires_in` time. How do we know when token expires? 

Thank you :)

**Comment by zachzi** [comment]
Hi lezoudali,

Right now we don't pass back the `expires_in` value from the OneDrive file picker.  All of the tokens expire in 1 hour by default - I'll make a note to update the documentation to reflect that in the future.

Thanks,
zachzi
