### ISSUE TITLE
Unicode Private Use Area

### ISSUE THREAD

**Issue by billziss-gh** [OneDrive/onedrive-api-docs#806]
Does the OneDrive API fully support Unicode? In particular, does it support the [Unicode Private Use Areas (PUA)](https://en.wikipedia.org/wiki/Private_Use_Areas)?

In order to test the OneDrive API for a larger project, I have built a small command line client that can issue UNIX-like commands, such as `ls`, `stat`, etc. These map fairly directly to equivalent OneDrive API's.

Because this is to also run on macOS and Linux computers, I want to support the [OneDrive reserved characters](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/addressing-driveitems.md#onedrive-reserved-characters). For this purpose I map reserved characters into the PUA using a simple transformation; for example, the character `'*'` is mapped to `0xf000 + '*'`. (This is the same encoding employed by Cygwin and others.)

However I have found problems with this scheme:

- `mkdir 'foo*bar'` works:

    ```
    POST https://graph.microsoft.com/v1.0/me/drive/root/children

    {"name":"foobar","folder":{},"@microsoft.graph.conflictBehavior":"fail"}

    Success - Status Code 201
    ```

- `ls` works (enumerates the new folder).

- `stat 'foo*bar'` fails:

    ```
    GET https://graph.microsoft.com/v1.0/me/drive/root:/foo%EF%80%AAbar?select=name,size,createdDateTime,lastModifiedDateTime,root,folder,file,cTag,deleted

    Failure - Status Code 404
    {
        "error": {
            "code": "itemNotFound",
            "message": "Item does not exist",
            "innerError": {
                "request-id": "44fc2ce7-2b89-4090-8f99-415f2663c25f",
                "date": "2018-03-15T17:50:56"
            }
        }
    }
    ```

- `stat 'foo*bar'` without encoding into the PUA also fails:

    ```
    GET https://graph.microsoft.com/v1.0/me/drive/root:/foo%2Abar?select=name,size,createdDateTime,lastModifiedDateTime,root,folder,file,cTag,deleted

    Failure - Status Code 400
    {
        "error": {
            "code": "invalidRequest",
            "message": "One or more invalid characters are present in the path (/LiveFolders/foo*bar).",
            "innerError": {
                "request-id": "c433ca40-4699-4028-9c69-f6eafdc4ea49",
                "date": "2018-03-15T17:48:05"
            }
        }
    }
    ```

- `rmdir 'foo*bar'` also fails. So I can create a folder that I cannot access or delete.

These tests confirmed with Graph Explorer.

**Comment by ificator** [comment]
Thanks for bringing this to our attention @billziss-gh - it seems to be an issue when calling via Graph as I cannot reproduce when calling https://api.onedrive.com directly.

**Comment by billziss-gh** [comment]
@ificator thanks for the quick response.

In general is it better to use the Graph URIs (https://graph.microsoft.com/v1.0/me/drive) or the API ones (https://api.onedrive.com/v1.0/drive)? The docs seem to suggest the former, but some examples have the latter, so I do not have enough clarity on this.

**Comment by ificator** [comment]
Graph is the way forward, but we do sometimes discover issues when calling it that do not reproduce when calling the direct endpoint. If the issue you're hitting is problematic enough for you then switching over until it's resolved is your only option.

**Comment by billziss-gh** [comment]
@ificator thanks. I will keep using the Graph URI for now and wait for a resolution.

**Comment by ificator** [comment]
It looks like Graph has resolved the issue!

**Comment by billziss-gh** [comment]
Thank you. I can confirm that this works now.
