### ISSUE TITLE
Feature Request: Disallow Use of Recycle Bin during DELETE

### ISSUE THREAD

**Issue by billziss-gh** [OneDrive/onedrive-api-docs#807]
I would like to request the ability to DELETE a file permanently and without going through the Recycle Bin.

I am building a cross-platform file system (i.e. one that integrates with the operating system) that uses OneDrive as a backend storage. Currently when files are DELETE'd from OneDrive they are moved to the Recycle Bin. This is detrimental to how a file system operates.

In #84 a side question by @paya-cz was:

> Also, is there any parameter to specify to ensure the file/folder is permanently deleted, and not moved to recycle bin? For my particular application, recycle bin is pretty much useless, so I don't want to pollute that folder with a ton of files that are obsolete.

The response by @rgregg was:

> There isn't a way to delete permanently in the API right now. We're looking at ways to enable recycling bin management from the API, but one of the key elements of OneDrive is that your data is safe with us. Providing apps a way to destroy a file forever, while useful in some benign scenarios also enables it for destructive scenarios, so we have a balance to work through.

Given that almost 3 years have passed since those comments, I am wondering if the thinking of the OneDrive team has changed on this issue.

If you do no intend to provide this functionality you can mark this issue as `wontfix` or similar. In this case it would be helpful if you provided functionality to manage the Recycle Bin easily (e.g. automatically remove files older than 30 days, etc.)

**Comment by katahir** [comment]
Hi billziss-gh,
We’re nervous about the prospect of apps bypassing the recycle bin. Our own sync client doesn’t bypass the recycle bin on a delete, and that’s what users have grown accustomed to. We feel this is an important last line of defense against bugs and helps users maintain trust in our service. We do plan to expose an API to view the recycle bin and restore files from it, but we’re still thinking about whether to allow deleting files from it. I’m curious to learn more about your app and why the recycle bin behavior is detrimental.”

**Comment by billziss-gh** [comment]
Thank you for your response. I understand that this is now marked `wontfix`.

My (native) app is a cross-platform file system using FUSE on macOS and Linux and [WinFsp](https://github.com/billziss-gh/winfsp) on WIndows (disclaimer: I am the WinFsp author). Using these technologies the app integrates with the operating system and presents OneDrive as a file system to other processes; files within the file system can be manipulated using `open` / `read` / `write` / `close` or `CreateFileW` / `ReadFile` / `WriteFile` / `CloseHandle`.

Some processes often create and delete files and directories frequently and often without user intervention. If all such files/directories are moved to the Recycle Bin, I see a few problems:

- I am assuming that files that reside in the Recycle Bin count towards user quota. A single app that constantly creates and deletes files (e.g. in its update scenario) could eat into that quota rather fast.

- It requires user interaction to launch the OneDrive web app and empty the Recycle Bin. Often users are not aware that a Recycle Bin exists, and they are not likely to open the Recycle Bin even when they are aware.

- The list of files presented by the Recycle Bin is cluttered, because it includes files that I do not know of as a user. For example, I may have accidentally deleted MyImportantFile.txt and I would like that back, but this may not be easy if I have hundreds of files and tens of files with the same name in my Recycle Bin.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
