### ISSUE TITLE
Is there a minimum required version of OpenSSL to be able to use the Onedrive API? 

### ISSUE THREAD

**Issue by meistertigran** [OneDrive/onedrive-api-docs#809]
We have a OneDrive app, written in PHP, which was working fine, until we recently noticed that on one of our customers machine after **successfully** uploading some chunks via the large file upload, we were getting a "curl_exec() failed: SSL_write() returned SYSCALL, errno = 32" error on a random chunk and the upload was failing. After some research I found an issue similar to ours only for another Cloud service providers API and the solution was to upgrade from OpenSSL v1.0.1 to  OpenSSL v1.0.2. Hence my question. Is there a minimum required version of OpenSSL to be able to use the Onedrive API?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
