### ISSUE TITLE
Deleting subscriptions as a whole

### ISSUE THREAD

**Issue by exp0nge** [OneDrive/onedrive-api-docs#810]
Currently the only way to delete a subscription is to know the access token or respond to the OneDrive server with errors. 

During development (and sometimes production), this can be a annoying problem with multiple subscriptions coming back if not deleted.

Is there any plans to have a different mechanism to delete subscriptions using maybe the application token?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
