### ISSUE TITLE
Sharepoint. Error: The request has been throttled

### ISSUE THREAD

**Issue by Woody-Woo** [OneDrive/onedrive-api-docs#812]
Hi,

One of our clients uses Onedrive for Business and gets the following error:

Request:
GET https://ei123-my.sharepoint.com/_api/v2.0/drive/root:

Response:
StatusCode:429
Content: "{"error":{"code":"activityLimitReached","innererror":{"code":"throttledRequest"},"message":"The request has been throttled"}}"

The utc time interval for the request that return the error is:
reuqest - 2018-03-21 01:00:22.4269
response - 2018-03-21 01:00:22.5200

SPRequestGuid not exist in headers on response.

Any ideas?

If you need any other information please let me know.

Thanks.

P.S. We have many clients whose use Onedrive for Business and everything works smoothly except this.

**Comment by Woody-Woo** [comment]
Hi,

Our other client receives this error.
Endpoint: faspems-my.sharepoint.com
reuqest: 2018-04-16 15:35:58.6239 (utc)
response: 2018-04-16 15:35:59.2211 (utc)

Any ideas?

If you need any other information please let me know.

Thanks.

**Comment by Woody-Woo** [comment]
Hi guys,

Could you please tell us, can this issue happen because of two-factor authorization? A client using endpoint faspems-my.sharepoint.com, says that he uses two-factor authentication.

To access to sharepoint, we use oauth authorization. Oauth authorization on the client's side passes successfully, and we get access and refresh token.

**Comment by Woody-Woo** [comment]
Hi guys,

According to the following post 

https://developer.microsoft.com/en-us/graph/docs/concepts/throttling

the issue happens because of 

>A large number of requests from a particular application across all tenants.

Is it true that the calculation of throttling occurs uniform for our application, even though it is installed on different servers and accesses different endpoints on the Sharepoint?

We develop a tool that allows to backup SQL Server databases to different destination. One of them is Sharepoint.

Our customers are getting more and more such errors. This is probably due to the fact that we have more customers who send backups to Sharepoint.

We implemented the use of Retry-After, but this partially resolves the issue.

Is there are anything you can help us?

**Comment by ificator** [comment]
We have a number of issues discussing throttling at the moment so we're going to coalesce into a single one. If you'd like to add your piece, jump over to issue https://github.com/OneDrive/onedrive-api-docs/issues/853 add a comment.
