### ISSUE TITLE
Cannot create permissions with "owner" role.

### ISSUE THREAD

**Issue by pathaniaVikas** [OneDrive/onedrive-api-docs#813]
I am unable to create permissions with "owner" role. I am using one drive 2.0 [invite](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite) API to create permissions. As specified [here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/permission#roles-enumeration), "sp.owner" role can be specified while creating permissions.
But API errors out with following error: 
<Response [400]> {"error":{"code":"invalidRequest","message":"Invalid value for role"}}

Request:
Url: /_api/v2.0/drive/items/{item_id}/invite 
Body:
{
      "recipients": [
        {
          "email": "email@kdk.com",
        }
      ],
      "message": "Here's the file that we're collaborating on.",
      "requireSignIn": True,
      "sendInvitation": False,
      "roles": ["sp.owner"],
    }
Method: Post

Response:
<Response [400]> {"error":{"code":"invalidRequest","message":"Invalid value for role"}}

For other roles read and write its working fine. We are using client credentials workflow with full permissions given to our app.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
