### ISSUE TITLE
BadRequest when attempting to download contents of a DriveItemVersion resource

### ISSUE THREAD

**Issue by DanHopkins-TGI** [OneDrive/onedrive-api-docs#814]
I realize this feature is in beta, but according to the [documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitemversion_get_contents), I should receive a `302 Redirect` response when requesting the contents of a specific file version.  However, at this time, I currently receive a `400 - Bad Request` response when attempting to do this on a file stored in SharePoint or OneDrive Personal.

Steps:

1. I can verify that the file and version exist, by removing the `/contents` segment like so: 
 `https://graph.microsoft.com/beta/sites/{siteId}/drives/{driveId}/items/{itemId}/versions/{versionId}`.  This returns successfully with the correct version information.

2. Append the `/contents` segment to the same url and do a `GET` request

3. The response is `Failure - Status Code 400`:

```
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'contents'.",
        "innerError": {
            "request-id": "fde7d806-040d-468b-aa26-4a14c6825365",
            "date": "2018-03-23T18:05:47"
        }
    }
}
```

**Comment by D4N14L** [comment]
This appears to be because the proper URL segment is `/content` not `/contents`. Could you try this and tell me if it works?

**Comment by DanHopkins-TGI** [comment]
Using `/content` instead of `/contents`, I get the following response:
`GET https://graph.microsoft.com/beta/sites/{siteId}/drives/{driveId}/items/{itemId}/versions/{versionId}/content`
```
Failure - Status Code 400
{
    "error": {
        "code": "invalidRequest",
        "message": "The request is malformed or incorrect.",
        "innerError": {
            "request-id": "1df8b520-34e3-4163-8bb4-dfd35d4d11d7",
            "date": "2018-03-23T18:15:34"
        }
    }
}
```
I am using the Graph Explorer with the beta endpoint selected to test.

**Comment by D4N14L** [comment]
Ah, I see there is another issue here. You cannot perform `/content` on a listitem through the sites API. You must get the content using the `/drives` route to the item.

**Comment by DanHopkins-TGI** [comment]
I updated the request url to use the `/drives` route as follows: `GET https://graph.microsoft.com/beta/drives/{driveId}/items/{itemId}/versions/{versionId}/content`.  I verified that removing the `/content` segment still successfully returns a version item, but I get the same `Failure - Status Code 400` response otherwise.

**Comment by D4N14L** [comment]
Please provide the request ID

**Comment by DanHopkins-TGI** [comment]
The request ID is `6662e29f-d199-41bf-8f8c-fac70327e114` and the full response is:
```
Failure - Status Code 400
{
    "error": {
        "code": "invalidRequest",
        "message": "The request is malformed or incorrect.",
        "innerError": {
            "request-id": "6662e29f-d199-41bf-8f8c-fac70327e114",
            "date": "2018-03-23T19:03:21"
        }
    }
}
```

**Comment by D4N14L** [comment]
I just looked this up. It appears you were trying to get the current version's content, and this isn't supported. Unfortunately, it seems the error message did not bubble up for you to understand what went wrong. This is also a documentation bug, as our documentation should specify this is a limitation.

The request should work for past versions, however. Can you confirm?

**Comment by DanHopkins-TGI** [comment]
Ah, I see.  That makes sense, and I can confirm that it works as expected for past versions!  Thank you very much for your time and help!
