### ISSUE TITLE
Ability to get ShareId when listing children?

### ISSUE THREAD

**Issue by raRaRa** [OneDrive/onedrive-api-docs#816]
I have several folders that have been shared using createLink - https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink

That works fine, but I'm trying to find a way to list all folders that have been shared, and I also need their shareId. Is there any way to make such query?

`https://graph.microsoft.com/v1.0/me/drive/root/children` doesn't seem to return the shareId for the shared folders, and there's no expand for permissions, shares, etc.

Any help is much appreciated. Thanks.

**Comment by afizs** [comment]
I am also looking for similar solution.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
