### ISSUE TITLE
Enhancement: Allow use of any port on loopback redirect URL

### ISSUE THREAD

**Issue by billziss-gh** [OneDrive/onedrive-api-docs#818]
As per RFC [8252](https://tools.ietf.org/html/rfc8252) section [7.3](https://tools.ietf.org/html/rfc8252#section-7.3) I am requesting that:

> The authorization server MUST allow any port to be specified at the time of the request for loopback IP redirect URIs, to accommodate clients that obtain an available ephemeral port from the operating system at the time of the request.

According to my testing with a native app that uses a loopback redirect URL, OneDrive Oauth2 only allows the port specified in the Application Registration Portal.

**Comment by chackman** [comment]
Thanks for your feedback.

For new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.

**Comment by billziss-gh** [comment]
The original request is very clear and does not require any further feedback. I would expect that it is obvious to the project leads why supporting the cited RFC section is a good idea. If not feel free to close this issue, because I do not intend to run a social campaign for it.
