### ISSUE TITLE
HTTP 500 on DELETE/If-Match

### ISSUE THREAD

**Issue by billziss-gh** [OneDrive/onedrive-api-docs#819]
When attempting to `DELETE` a directory with an `If-Match` header I receive an HTTP 500 and the following error:

```
{
  "error": {
    "code": "generalException",
    "message": "An error occurred in the data store.",
    "innerError": {
      "request-id": "5770bc39-f72a-4793-83e8-60fca5e73f4a",
      "date": "2018-03-31T06:52:45"
    }
  }
}
```

NOTE: I used the `cTag` in the `If-Match` header.

**Comment by ificator** [comment]
Hi @billziss-gh, is this OneDrive Consumer? Also, can you give me a little information on the directory being deleted? For example, does it have a lot of children? Deep folder hierarchy? etc

**Comment by billziss-gh** [comment]
This is on OneDrive Personal. It is very easy to repro using Graph Explorer:

- Create an (empty) directory named `foo` under the root.
- Find out its `cTag` by issuing a `GET`.
- Issue a `DELETE` with `If-Match` equal to the `cTag`.

<img width="771" alt="screen shot 2018-04-02 at 3 10 21 pm" src="https://user-images.githubusercontent.com/15330948/38218922-49705ac0-3688-11e8-8f83-e08084ba5536.png">

**Comment by ificator** [comment]
Hi @billziss-gh, the fix for this issue should now be deployed. Please let us know if you're still seeing issues.

**Comment by billziss-gh** [comment]
Thank you for this resolution. I will test as soon as I get some free time and will let you know if I find any problems.

**Comment by billziss-gh** [comment]
I can confirm that this now works for me. Thank you again for the resolution!
