### ISSUE TITLE
Simple file upload using parent folder's ID and file's relative path

### ISSUE THREAD

**Issue by paya-cz** [OneDrive/onedrive-api-docs#82]
So I want to upload file using relative path to parent's folder ID, as per [this](https://onedrive.github.io/items/upload_put.htm#http-request) and [that](https://github.com/OneDrive/onedrive-api-docs#root-resources). For example, this is the request I want to execute:

> PUT /drive/items/CA123456789!33333:/folder level 1/folder level2/cool file.txt:/content

However, regardless of the relative path, as long as both the parent folder ID and the relative path are present, I get the following error:

> HttpStatusCode: 405
HttpStatusMessage: "Method Not Allowed"

>``` json
{
  "error": {
    "code": "invalidArgument",
    "message": "Item does not match expected type",
    "innererror": {
      "code": "itemTypeDoesNotMatch"
    }
  }
}
```

What exactly is the problem with my request?

**Comment by ginach** [comment]
Thanks for reporting this.  Your request is correct but there's a bug on our side.

As a workaround until we fix the issue, this does the same thing and is working: PUT /drive/items/CA123456789!33333:/folder level 1/folder level2:/children/cool file.txt/content

**Comment by paya-cz** [comment]
Thank you, your workaround works!

So when I'm uploading files using the relative path, is there any parameter I can pass in to force automatic creation of folders in the path that do not exist?

**Comment by ginach** [comment]
That should already be done automatically. Are you seeing different behavior?

**Comment by paya-cz** [comment]
Yes, I am seeing:

> HttpStatusCode: 404
HttpStatusMessage: "Not Found"

>```json
{
  "error": {
    "code": "itemNotFound",
    "message": "Item Does Not Exist",
    "innererror": {
      "code": "itemDoesNotExist",
      "innererror": {
        "code": "folderDoesNotExist"
      }
    }
  }
}
```

**Comment by ginach** [comment]
This appears to be a different issue with ID + path. I'll open another issue to track that.

**Comment by ginach** [comment]
This should be fixed now. Can you verify that you're now able to upload with ID + relative path?
