### ISSUE TITLE
Are application webhooks supported for SharePoint or OneDrive?

### ISSUE THREAD

**Issue by DanHopkins-TGI** [OneDrive/onedrive-api-docs#821]
I am developing an application that requests administrative approval to act on behalf of itself rather than a specific user.  On the [Webhooks documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_post_subscriptions) page, I see the `Application` permission type listed, and my app has been granted the required permissions, but so far all attempts to subscribe to a resource stored in SharePoint have returned `InvalidRequest - Cannot create app-only subscriptions for OneDrive resources`.

Are user delegated permissions the only way to create subscriptions?  If so, is there a recommended approach for applications that act on their own behalf to track changes to files stored in SharePoint or OneDrive?

**Comment by chackman** [comment]
Thanks for your feedback.
Could you please give us some additional information - like a sample request and response from call to create the subscription?
Thanks!

**Comment by DanHopkins-TGI** [comment]
Sure!  My steps are as follows:

1.  Request:
```
POST /v1.0/subscriptions
{
"resource":"/drives/{driveId}/items/{itemId}",
"changeType":"updated",
"clientState":"{clientKey}",
"notificationUrl":"{appUrl}",
"expirationDateTime":"{6 months from now}"
}
```
2. Response:
```
400 Bad Request
{
  "error": {
    "code": "InvalidRequest",
    "message": "Cannot create app-only subscriptions for OneDrive resources.",
    "innerError": {
      "request-id": "449e4975-f4cd-4125-bc83-bc425c2f79f3",
      "date": "2018-04-16T20:16:04"
    }
  }
}
```

Thank you for your time and help!

**Comment by chackman** [comment]
Unfortunately there are limitations around app-only scenarios for OneDrive and SharePoint webhooks.

I would suggest going to [UserVoice for OneDrive](https://onedrive.uservoice.com/forums/262982-onedrive?category_id=89523) and suggest an improvement (or upvote an existing one).  This feedback helps us prioritize future work based on the interest in those suggested improvements.
