### ISSUE TITLE
[ODB] [graph] [China] why encounter 400 when get drives

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#822]
Hi all,

Before a day, the operation works fine. https://microsoftgraph.chinacloudapi.cn/v1.0/users/{user_id}/drives

Suddenly, it keeps encounter this error:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Unable to retrieve user's mysite URL.",
        "innerError": {
            "request-id": "9d8a3714-eaa2-4e8b-9ba0-727f0753f01d",
            "date": "2018-04-03T09:19:55"
        }
    }
}
```

I have checked the subscription and APP permission in graph API, all permission is enabled

And I have tested another APP using the same graph API permission which works fine.

Do not know what is going wrong here

Thanks you.

**Comment by chackman** [comment]
Thanks for your feedback.  Could you please try this request again?

**Comment by joewutaiwan** [comment]
hi @chackman,
Thanks for the reply.
But the API still keep return 400
```
err_code:(BadRequest), 
err_message(Unable to retrieve user's mysite URL.), 
err_request_id(f112f890-3851-4b18-836f-c14d85c264a3),
 err_date(2018-04-16T06:48:26)
```

**Comment by chackman** [comment]
The 400 errors here appear to be due to scenario that intended to return a 429, but the wrong error code is being returned.  We're investigating how to fix the issue with the incorrect error code for this scenario.

**Comment by NielsFilter** [comment]
We're also experiencing the same, very intermittently, so seems very likely that the 400 is sometimes sent instead of 429. FWIW we are still sometimes receiving 429's as well.

Workaround for now, we're handling 400 with "Unable to retrieve user's mysite URL." message as 429s. We back off and retry which does the job for now.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
