### ISSUE TITLE
[ODB] Will Temporary files created by upload session be cleaned automatically ?

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#823]
Hi all,

I have a question about **Temporary files** created by upload session.

https://docs.microsoft.com/zh-tw/onedrive/developer/rest-api/api/driveitem_createuploadsession#create-an-upload-session

If we failed to cancel the upload session, will the **Temporary files** be cleaned automatically?

Thanks

**Comment by chackman** [comment]
Yes, temporary files should be cleaned up after their upload session expires.

**Comment by joewutaiwan** [comment]
@chackman ,

Hi, should I cancel the session manually by request or I do not need to do?

Will upload session expires automatically?

Because I have several temporary files which have not been deleted for two week.
(I do not use cancel request to force their upload session expired)

Thanks

**Comment by chackman** [comment]
Could you please provide some more information - could you create a new upload session and provide the request ID and time that you created that session?  Only the request ID and time should be enough.
