### ISSUE TITLE
[7.2] File picker gets stuck at loading, but 7.0 get through

### ISSUE THREAD

**Issue by tvanh** [OneDrive/onedrive-api-docs#824]
The setup for OD file picker is 
					<script type="text/javascript">
						function launchOneDrivePicker() {
							var odOptions = {
								clientId : "xxxxxxxx",
								action : "share",
								multiSelect : true,
								advanced : {
								},
								success : function(files) {
									fncAddRelationUrlFromO365Onedrive('frmInput:i_urlReference', null, files);
								},
								cancel : function() {
								},
								error : function(e) {
									alert(e);
								}
							}
							OneDrive.open(odOptions);
						}
					</script>
					<input type="button" onClick="launchOneDrivePicker()" value="Open from OneDrive"></input>

If I use the 7.2 version, it gets stuck at https://192.168.20.118:8181/abc/xyz/xyz0102e.jsf?oauth=%7B%22clientId%22%3A%22....
The version 7.0 works fine, but since I am going to upgrade to 7.2 for being able to pick file from sharepoint, I would like to ask for help.

Thanks

**Comment by KevinTCoughlin** [comment]
@tvanh I would advocate you upgrade to `v7.2` if not already as it includes a number of bug fixes. We do not plan to retroactively patch `v7.0`.

Please let us know if you still experience this problem in `v7.2`. Thank you.

**Comment by tvanh** [comment]
I would like to re-open this.
In 7.2, I got this error:
Uncaught TypeError: (intermediate value)(intermediate value).scopes.map is not a function
    at OneDrive.js:2
    at T (OneDrive.js:2)
    at HTMLDocument.<anonymous> (OneDrive.js:2)
Any idea about this?

**Comment by KevinTCoughlin** [comment]
> I would like to re-open this.
> In 7.2, I got this error:
> Uncaught TypeError: (intermediate value)(intermediate value).scopes.map is not a function
> at OneDrive.js:2
> at T (OneDrive.js:2)
> at HTMLDocument. (OneDrive.js:2)
> Any idea about this?

@tvanh can you use the unminified build at http://js.live.net/v7.2/OneDrive.debug.js and paste the stack-trace?

Also, what browser(s) does this occur in?

**Comment by tvanh** [comment]
Here is the stack trace

OneDrive.debug.js:764 Uncaught TypeError: config.scopes.map is not a function
    at buildAADOauthV2Url (OneDrive.debug.js:764)
    at redirectToOauthPage (OneDrive.debug.js:737)
    at handleOauth (OneDrive.debug.js:690)
    at HTMLDocument.<anonymous> (OneDrive.debug.js:682)

**Comment by tvanh** [comment]
oauthConfig
clientId: "XXXX-XXXX-XXXX-XXXX"
endpoint: 1
origin: "http://localhost:8886"
redirectUri: "http://localhost:8886/XXX/XXXX/XXX0102e.jsf"
scopes: "["Files.ReadWrite.All"]"
state: "http://localhost:8886_m1dII"

**Comment by KevinTCoughlin** [comment]
> oauthConfig
> clientId: "XXXX-XXXX-XXXX-XXXX"
> endpoint: 1
> origin: "http://localhost:8886"
> redirectUri: "http://localhost:8886/XXX/XXXX/XXX0102e.jsf"
> scopes: "["Files.ReadWrite.All"]"
> state: "http://localhost:8886_m1dII"

@tvanh, can you change `scopes` from a `string` to an `Array<string>` in your configuration?

```js
...
scopes: ["Files.ReadWrite.All"]
...
```

If this is the problem, TypeScript and *.d.ts files for our public interfaces will help avoid this going forward cc: @aditima.

**Comment by tvanh** [comment]
I think the config is the result from parse 
line690: redirectToOauthPage(JSON.parse(redirResults[PARAM_OAUTH_CONFIG]));
So I can't change the config file. Going to change the method in ur public interfaces will help imo.

Bests

**Comment by tvanh** [comment]
line 764, by changing
config.scopes.map(function (s) 
to
JSON.parse(config.scopes).map(function (s)
the bug gone

**Comment by tvanh** [comment]
![image](https://user-images.githubusercontent.com/15227407/53856797-f6779100-4016-11e9-9ec3-1c7455d3464f.png)
The site selection on the left is missing. 
I got these following errors
odbonedrive-mini-cfc25a4d.js:1 Refused to get unsafe header "SPClientServiceRequestDuration"
h._onReadyStateChange @ odbonedrive-mini-cfc25a4d.js:1
(anonymous) @ odbonedrive-mini-cfc25a4d.js:1
d @ odbonedriveapp-mini-5f4648eb.js:1
13:46:47.522 odbonedrive-mini-cfc25a4d.js:1 Refused to get unsafe header "SPRequestGuid"
h._onReadyStateChange @ odbonedrive-mini-cfc25a4d.js:1
(anonymous) @ odbonedrive-mini-cfc25a4d.js:1
d @ odbonedriveapp-mini-5f4648eb.js:1
13:46:47.522 odbonedrive-mini-cfc25a4d.js:1 Refused to get unsafe header "SPRequestGuid"
r.getCorrelationId @ odbonedrive-mini-cfc25a4d.js:1
e @ odbonedrive-mini-cfc25a4d.js:1
h._onReadyStateChange @ odbonedrive-mini-cfc25a4d.js:1
(anonymous) @ odbonedrive-mini-cfc25a4d.js:1
d @ odbonedriveapp-mini-5f4648eb.js:1
May I get help?

**Comment by KevinTCoughlin** [comment]
@tvanh let's isolate this specific issue to the `JSON.parse` bug.

Please open a new separate issue referencing the absence of site selection (left nav). As part of that issue, please provide your File Picker configuration with clientId and tenantId omitted so that we can debug.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
