### ISSUE TITLE
Feature Request: Add relationship between DriveItem and ListItem

### ISSUE THREAD

**Issue by mlafleur** [OneDrive/onedrive-api-docs#829]
Currently, the API supports expanding a ListItem's related DriveItem but not the other way around. 

So while we can do `/lists/{id}/items?$expand=driveItem`, we cannot do `/drives/{id}/root/children?$expand=listItem`. 

This presents a problem when a Document Library contains additional metadata columns. Currently, there is no way to find the underlying `ListItem` to obtain this metadata.

**Comment by ificator** [comment]
This should already work - you can see a `listItem` navigation property defined on the `driveItem` schema. What do you see when you try such a query?

**Comment by mlafleur** [comment]
Doh! 

You are absolutely correct, when using `$expand=listItem` against the `children` collection it is returning the associated `ListItem`. 

Where I got confused, and where it _isn't_ working as expected is `/root/search(q='query')?$expand=listItem`. This returns:

```javascript
"error": {
    "code": "notSupported",
    "message": "The request is not supported by the system.",
    "innerError": {
        "request-id": "a44adc84-b3ad-4c66-ab20-d46693dbf263",
        "date": "2018-04-12T19:48:19"
    }
}
```

The relationship with `ListItem` is also [currently undocumented](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem). When I ran across the issue with searching I went back to the documentation to confirm this was missing and made an incorrect assumption. My apologies for the confusion.

**Comment by ificator** [comment]
Ah yeah, search is it's own beast. We can only return the data that is part of the index, which doesn't include the vast majority of data that a developer would expect to see on a `listItem`.

**Comment by mlafleur** [comment]
Okay, that makes a lot of sense.

For the "wish list" pile, it would be helpful if the index could extend to include the `ListItem`. I've come across several examples where the developer is attempting to search a Document Library and needs to include additional metadata from the `ListItem` in the search result. At the moment the only option is to use the `DriveItem` identifier from the search results and make a subsiquent calls to get the full `DriveItem` and `ListItem` for each file. This ends up driving a lot of excess traffic for each search query.

**Comment by ificator** [comment]
We have a general work item to try and align the search and "normal" results, and hopefully we'll make progress over time.
