### ISSUE TITLE
[7.2] File Picker for JS: TypeError "tbody.rows.count is not a function" (action: download)

### ISSUE THREAD

**Issue by tistre** [OneDrive/onedrive-api-docs#831]
The OneDrive file picker for JavaScript opens, authenticates and displays my files just fine. It also lets me select a file and closes the dialog when I click “Open”. But the opener window does not receive proper file info – instead, I see these messages in the browser console:

```
[OneDriveSDK] calling xhr failure callback, status: EXCEPTION
TypeError
  message: "tbody.rows.count is not a function"
  stack: "startAjaxRequest@https://example.com/picker:56:4699
XMLHttpRequest.prototype.open@example.com/picker:56:13291
[33]</</h</e.prototype.start@https://js.live.net/v7.2/OneDrive.js:3:18202
c/<@https://js.live.net/v7.2/OneDrive.js:2:3299
I@https://js.live.net/v7.2/OneDrive.js:10:2890
j@https://js.live.net/v7.2/OneDrive.js:10:4195
c@https://js.live.net/v7.2/OneDrive.js:2:3271
p@https://js.live.net/v7.2/OneDrive.js:2:3576
[8]</</c</t.prototype.queryItems@https://js.live.net/v7.2/OneDrive.js:2:22202
[8]</</c</t.prototype.makeApiRequest@https://js.live.net/v7.2/OneDrive.js:2:21947
[5]</</g</e.prototype.launch/<@https://js.live.net/v7.2/OneDrive.js:2:10858
S@https://js.live.net/v7.2/OneDrive.js:10:2601
A@https://js.live.net/v7.2/OneDrive.js:10:2712
U@https://js.live.net/v7.2/OneDrive.js:10:2504
d@https://js.live.net/v7.2/OneDrive.js:10:751"

[OneDriveSDK] Received ajax error. 
{ 
  errorCode: "webRequestFailure", 
  message: "HTTP error status: -1", 
  apiEndpoint: "https://example.sharepoint.com/_api/v2.0/" 
}

The OneDrive picker returned SUCCESS 
```

The error messages are identical on both Chrome 65 and Firefox 60.

My picker invocation code looks like this:

```
function launchOneDrivePicker()
{
    var odOptions = {
        clientId: 'CLIENTID',
        action: 'download',
        multiSelect: false,
        advanced: {
            endpointHint: 'https://example.sharepoint.com/',
            accessToken: 'ACCESSTOKEN'
        },
        success: function(files)
        {
            console.log('The OneDrive picker returned SUCCESS');
        },
        cancel: function() { },
        error: function(e) 
        {
            console.log('The OneDrive picker returned an ERROR:', e);
        }
    };
    
    OneDrive.open(odOptions);
}
```

Any help is appreciated – thanks in advance!

**Comment by KevinTCoughlin** [comment]
@tistre is the above still a problem? This seems like a problem with the app which invokes the picker, not the picker itself as we do not utilize tables anywhere.

**Comment by tistre** [comment]
@KevinTCoughlin Yes, I still get the same error message – and there’s no table on the invoking page as well. Weird.

7.2 is still the current version?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin Yes, I still get the same error message – and there’s no table on the invoking page as well. Weird.
> 
> 7.2 is still the current version?

Yea `7.2` is latest still.  I was able to get a valid `downloadUrl` when I omitted both `accessToken` and `endpointHint` from the File Picker configuration.

When I use only an `endpointHint` I received an error and the Picker fails to open... seems unintentional and a bug which requires investigation.

As a workaround, are you able to omit `endpointHint`?

My configuration:

```js
var options = {
    clientId: '00000000-0000-0000-0000-000000000000',
    action: 'download',
    success: (files) => console.log('success', files),
    cancel: (err) => console.log('cancel', err),
    error: (err) => console.log('err', err)
};

OneDrive.open(options);
```

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
