### ISSUE TITLE
OneDrive API Share document for offline writing/updating

### ISSUE THREAD

**Issue by spyronis** [OneDrive/onedrive-api-docs#833]
Hello.
I have created a web app which is making use of OneDrive API (https://docs.microsoft.com/en-us/onedrive/developer/rest-api/) to perform actions such as create/update/rename/delete of documents etc. I am authorizing requests with OAuth 2.0 (client side - that means every access token is valid for ~1h and then silently I am getting a new token) and then perform previous actions using that token.

I have a new requirement for the authorized user to share his/her documents for writing/updating them (I found out that API has option for inserting permissions (https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite).

Is it possible for a non-authenticated/ guest user to be able to write/update documents (programmatically - via OneDrive API or some other API?) that have been created from the authenticated user and shared these? (something that is similar to Microsoft Word online when a user is sharing his document and guest/non authorized users are able to edit it?

Thanks.

**Comment by ificator** [comment]
Is your scenario for OneDrive Consumer or OneDrive Business, or both?

**Comment by spyronis** [comment]
hmm.. I don't think it's Business. It s a single page integrated with OneDrive via javascript calls .

**Comment by spyronis** [comment]
Also, on Google cloud there is option for service accounts that solve that problem.
Is there something similar with Microsoft/ OneDrive?

**Comment by spyronis** [comment]
Any update on that?
For Microsoft Office apps a guest user can edit/save a shared document. Can this be accomplished programmatically on OneDrive API?

**Comment by ificator** [comment]
It sounds like you may be able to [create sharing links with edit permissions](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink) for the items you care about. You can use those links to call the API using the [shares api](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get), or users can use the link directly to get the web experience.

**Comment by spyronis** [comment]
Yes this is clear for accessing shared items.. But is it also possible (any examples / documentation?)  to edit the content of the shared item (by a guest user)?

**Comment by spyronis** [comment]
I guess that means there is no possible solution right?
