### ISSUE TITLE
Onedrive delta api no longer returns timestamps for tombstones

### ISSUE THREAD

**Issue by rloehr** [OneDrive/onedrive-api-docs#834]
We've recently noticed a change in behaviour with the "drive/root/view.delta" call where the "lastModifiedDateTime" is no longer being returned for certain tenants.
Could you confirm if this is a regression on your side or is this an expected behavior going forward 

Here is some sample data from a tenant that exhibits the above behaviour :
```GET Call
https://fake-my.sharepoint.com/personal/jm_smartstart_org1/_api/v2.0/drive/root/view.delta?token=MzslMjM0OyUyMzE7Mzs2Z
DVhZDdiMi02YTc5LTQ2NzktYjAzNS04YzQwNmU2NGJjZjg7NjM2NTkwMjA2NTEzMjMwMDAwOzEzOTAwMzcwNTslMjM7JTIzOyUyMzQ```

Response header trimmed
sprequestguid →66c95c9e-501a-5000-7da8-ddbea6b64d91

Response items :
```{
            "@odata.type": "#oneDrive.item",
            "@odata.id": "https://fake-my.sharepoint.com/personal/jm_smartstart_org1/_api/v2.0/drive/items/01WHAEF4B4JHSDVNCBNFEKJ3KRFHW7PX4I",
            "@odata.editLink": "drive/items/01WHAEF4B4JHSDVNCBNFEKJ3KRFHW7PX4I",
            "id": "01WHAEF4B4JHSDVNCBNFEKJ3KRFHW7PX4I",
            "parentReference": {
                "driveId": "b!qcJBW0r4DES1sbsoYYbDRqEj8dWnqFtIp1OihnL4Hoiy11pteWp5RrA1jEBuZLz4",
                "driveType": "business",
                "id": "01WHAEF4F6Y2GOVW7725BZO354PWSELRRZ"
            },
            "deleted": {
                "state": "deleted"
            },
            "file": {},
            "fileSystemInfo": {},
            "size": 0
        },
        {
            "@odata.type": "#oneDrive.item",
            "@odata.id": "https://fake-my.sharepoint.com/personal/jm_smartstart_org1/_api/v2.0/drive/items/01WHAEF4BIGABIZO4GQRGIPPWKP6UL6APW",
            "@odata.editLink": "drive/items/01WHAEF4BIGABIZO4GQRGIPPWKP6UL6APW",
            "createdBy": {
                "user": {
                    "email": "jm@fakestart.org",
                    "displayName": "Fake name"
                }
            },
            "createdDateTime": "2016-07-13T13:51:57Z",
            "eTag": "\"{8C023028-86BB-4C84-87BE-CA7FA8BF01F6},6\"",
            "id": "01WHAEF4BIGABIZO4GQRGIPPWKP6UL6APW",
            "lastModifiedDateTime": "2017-06-01T14:03:34Z",
            "name": "Fake @ Work",
            "parentReference": {
                "driveId": "b!qcJBW0r4DES1sbsoYYbDRqEj8dWnqFtIp1OihnL4Hoiy11pteWp5RrA1jEBuZLz4",
                "driveType": "business",
                "id": "01WHAEF4F6Y2GOVW7725BZO354PWSELRRZ",
                "path": "/drive/root:"
            },
            "webUrl": "https://ncsmartstart-my.sharepoint.com/personal/jmoore_smartstart_org1/Documents/Jonathan%20@%20Work",
            "fileSystemInfo": {
                "createdDateTime": "2016-07-13T13:51:57Z",
                "lastModifiedDateTime": "2017-06-01T14:03:34Z"
            },
            "package": {
                "type": "oneNote"
            },
            "size": 4970895
        }
```
Notice that the "lastModifiedDateTime" is missing for the deleted item (the first item in the response) but not the second item.

**Comment by ificator** [comment]
We did make a change to stop returning "useless" timestamps (e.g. `0001-01-01T00:00:00Z`), and since tombstones in delta always had these values the end result is that the timestamp properties are no longer returned on the wire.

**Comment by abraunegg** [comment]
Hi,

This issue is not just on tombstones - but `lastModifiedDateTime` appears to not be returned at all when getting details about an object.

As such, this is breaking the OneDrive Linux client:

https://github.com/skilion/onedrive/issues/334

Please can you advise on how to resolve

Best regards,

Alex

**Comment by ificator** [comment]
@abraunegg, tombstones are really the only delta / enumeration scenario where we'd expect this change to appear. Can you give us more details on what your request looks like? A corresponding response with headers would also be useful (feel free to remove any file names etc as they won't be needed to investigate).

**Comment by abraunegg** [comment]
Thanks - will look at tweaking the branch I am made - the original developer appears to have abandoned the project.

Is there any way to get a OneDrive Business Developers Account or something so that I can check the changes / fixes & provide additional feedback?
