### ISSUE TITLE
Remote server returned an error: 400 Bad request

### ISSUE THREAD

**Issue by atchyuth** [OneDrive/onedrive-api-docs#837]
I am uploading files to OneDrive using OAuthV2

Below are the params I'm using:

Authorization URL: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
Access token url: https://login.microsoftonline.com/common/oauth2/v2.0/token
Client Id: ca3d6f87-5d3a-49ca-804a-73e4*****419
Client Secret : ********
Call back URL: https://abc.com/oauth

I was able to generate token successfully. However, I am not able to connect to upload files. The process was working very well for past 3 months and all of a sudden it started failing since yesterday. I am not able to troubleshoot the root cause. Could you please help me?

**Comment by chackman** [comment]
Could you please give us some additional information - what API is failing?  Could you provide sample responses for those failed API calls?

**Comment by atchyuth** [comment]
@chackman issue has been resolved. 

Thanks,
Atchyuth
