### ISSUE TITLE
Issue uploading to UploadSession

### ISSUE THREAD

**Issue by DanHopkins-TGI** [OneDrive/onedrive-api-docs#838]
I am attempting to upload a file to a SharePoint drive by creating an [UploadSession](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession).  Last week, this was working fine, but as of today I am getting a `403 Forbidden` response when performing the `PUT` request on the returned `UploadSession.uploadUrl`.  I am able to use the `PUT /content` endpoint to upload a small file directly and I have verified that my app has the required permissions as per the documentation.  

My outlined steps are as follows:
1.  `POST /drive/root:/{item-path}:/createUploadSession`
2.  Response is  `200 OK` with `uploadUrl`
3.  `PUT {uploadUrl} Content-Length: 11608 Content-Range: bytes 0-11607/11608`
4.  Response is:
```
403 Forbidden
{
    request-id: 641d5e9e-0051-5000-b48f-bee854cb19d6
    X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.
    X-MS-InvokeApp: 1; RequireReadOnly
}
```

As it was working before, I thought there might have been an update, but I checked the documentation and it doesn't appear to have changed.  Any help would be greatly appreciated!

**Comment by ificator** [comment]
Assuming your scenario is app-only / daemon, we tracked down the issue to a new feature that was recently enabled and shut it off. The app-only scenarios should now be working as expected so please let us know if you continue to see issues.

**Comment by DanHopkins-TGI** [comment]
Thank you for the update!  Things are working great now!

**Comment by tipa** [comment]
I think I am experiencing the same issue on the beta endpoint. Has the new feature that was shut off previously been enabled again?

**Comment by ificator** [comment]
This issue is old, and so if the feature that caused the issue was enabled again after being fixed it would have happened a long time ago. If you're seeing issues I'd suggest creating a new issue and make sure to provide:
1. The service you're hitting (e.g. OneDrive Personal vs OneDrive Business / SharePoint)
2. The headers from the failing response
