### ISSUE TITLE
Documentation for OneDrive API

### ISSUE THREAD

**Issue by spyronis** [OneDrive/onedrive-api-docs#839]
Around a year ago I implemented some javascript REST API calls for OneDrive.
I remember there was some nice documentation + examples which are missing now (moved to different portal.. https://docs.microsoft.com/en-us/onedrive/developer/rest-api/)
e.g I cannot find rest api calls I am using
- clone documents: **https://api.onedrive.com/v1.0/drive/items/" + id + "/action.copy?access_token=access_token**
- share links: **https://api.onedrive.com/v1.0/drive/items/" + id + "/action.createLink?access_token=access_token**
Is there any detailed guide for all these working scenarios?

**Comment by chackman** [comment]
Are these the pages what you are referring to?
  copy: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy
  createLink: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink

**Comment by spyronis** [comment]
Yes. I am talking about these requests, but I cannot find the REST calls.

**Comment by chackman** [comment]
Those pages document the REST API's used to copy drive items and to create sharing links for drive items.  Are there different API's that you need more information about?

**Comment by spyronis** [comment]
I understand what these pages are for.
I am asking if following endpoints are somehow documented? (which are still supported)
https://api.onedrive.com/v1.0/drive/items/" + id + "/action.copy?access_token=access_token
share links: https://api.onedrive.com/v1.0/drive/items/" + id + "/action.createLink?access_token=access_token

**Comment by chackman** [comment]
The OneDrive API endpoint is mentioned in a document that compares the differences between the Microsoft Graph endpoint (which is recommended) and the direct endpoints (which includes the OneDrive API endpoint):

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences

**Comment by spyronis** [comment]
I still cannot find somewhere documented the endpoints using action.---

**Comment by chackman** [comment]
The "action" namespace prefix is a legacy namespace prefix.  We recommend using the "oneDrive" namespace prefix for actions; therefore, you may not see the "action" namespace prefix in our documentation.
