### ISSUE TITLE
Limits for conversion of Excel workbooks to PDF

### ISSUE THREAD

**Issue by volmedo** [OneDrive/onedrive-api-docs#840]
I am developing a service that converts Office documents to PDF by means of the OneDrive API accessed through the Graph API:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_get_content_format

My tests show that everything works fine except for Excel workbooks with sizes beyond 1MB (empirically obtained). When I try to convert such a workbook, I always receive a `400 Bad Request` error with a body like the one below (some line breaks inserted by me for clarity):
```
{
    "error": {
        "code":"notSupported",
        "message":"Error from Office Service.
                   Url= 
                   HttpCode= OK
                   ResponseHeaders=ResponseCode:
                       FileDownloadFailed
                       ErrorCode: UrlFileMaxDownloadLimitExceeded
                       IsExpectedFailure: True
                       ErrorCategory: BadRequest
                       ServiceID: ecc1767c-39bd-48a8-94b3-4c5c7bdde27e
                       OutputFormat: 
                       ServiceRegion: NorthEurope
                       Date: Tue, 17 Apr 2018 22:05:00 GMT
                       Server: Microsoft-IIS\/8.5
                       X-Powered-By: ASP.NET"
    }
}
```
Note this only happens with Excel files. I've done a lot of searches to find more about this limitation to no avail.

Is this just a bug? If it is, there is any plan to solve it promptly? If it is not, is there any documentation about the limits of the conversion service?

Thanks in advance, any info about this issue will be greatly appreciated.

**Comment by 2opremio** [comment]
If this is intentional (which I hope isn't the case), I think that the API documentation should state it explicitly.

**Comment by ificator** [comment]
I'm following up to see if there are any restrictions on Excel PDF conversion

**Comment by volmedo** [comment]
@ificator thanks to have a look into this, I'm willing to know about your findings.

**Comment by volmedo** [comment]
@ificator any update on this?

**Comment by ificator** [comment]
Sorry for the delay - I did get confirmation that there is indeed a 1MiB limit for Excel PDF conversions. We'll update our documentation to call this out.

**Comment by volmedo** [comment]
Thanks for the info @ificator, in spite of it being bad news.

What is the rationale behind this decision? Does it respond to technical reasons? And the most interesting question, is there any plan to remove it in the short-term?

**Comment by 2opremio** [comment]
Also, is there a way to remove the cap for certain accounts? We would be more than happy to pay a premium to get the cap removed.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
