### ISSUE TITLE
[ODFB] Is there a way to upload files as a batch

### ISSUE THREAD

**Issue by rsuram** [OneDrive/onedrive-api-docs#841]
Is there a way to upload multiple files (as a batch) using single upload session ? 

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession

As i need solution for : 
when i am going upload small sized files sized < 4MB. I am not getting proper upload speed to OneDrive and  getting 429 errors constantly.
Uploading small sized files consuming more time than large files in term of total data size.

For small size file i am using below API call
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content

suggest me.

**Comment by rsuram** [comment]
Ok, Thanks @chackman

**Comment by rsuram** [comment]
Hi @chackman , @ificator ,

Is below API call will work for batch uploads ?
https://developer.microsoft.com/en-us/graph/docs/concepts/json_batching
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/json_batching.md

Thanks,
Rathnakar Suram

**Comment by chackman** [comment]
Graph API batching is a different concept.

A single upload session, returned by the createUploadSession API, still corresponds to a single file.  To upload multiple files, you need to create separate upload upload sessions, one for each file.

**Comment by dtheodor** [comment]
Ok, to upload multiple files we need seperate upload sessions. However the upload sessions can be created in bulk with the batch API, and chunks can be uploaded to the several sessions also in bulk with the batch API. Correct?
