### ISSUE TITLE
view.delta generates 501 (Not Implemented) on 'business' accounts, 'personal' accounts work

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#842]
When attempting to query a folder directly (child object, not the root) & using a onedrive business account, OneDrive returns the following:

```
Query:
/v1.0/drives/<drive_id>/items/<item_id>/delta?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference

Error:
{
    "error": {
        "code": "notSupported",
        "innerError": {
            "date": "2018-04-18T21:38:49",
            "request-id": "7a7f39a7-e60e-4b6c-be05-887f738aa6ef"
        },
        "message": "view.delta can only be called on the root."
    }
}
```

When using the exact same folder structure & query and a OneDrive personal account, the query completes successfully & without error.

The use case for this is, I may only want to sync the objects from a specific OneDrive folder, not query everything and iterate over everything that would be responded with if the view.delta performed against the root.

**Comment by abraunegg** [comment]
Work around for the moment is to use the list children function - going through various tests to see if there are any flow on impacts.

**Comment by ificator** [comment]
Hi @abraunegg, unfortunately, as you have observed, OneDrive for Business only supports change enumeration on the root (see [the remarks](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_delta#remarks) in the documentation). If `/children` doesn't end up working for you `delta` from the root may still be an option, but you'd need to implement logic to ignore notifications for any item that's not within the hierarchy of interest.

**Comment by abraunegg** [comment]
It appears that really the 'main' use of view.delta in the original code base was to get various attributes of child objects. So far `/children` achieves the same result.
