### ISSUE TITLE
[ODB] Is anyway to monitor the activityLimitReached usage?

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#843]
Hi all,

The same problem occurs in my services, keeps receiving 429 error for an office365 domain.
```
{
  "error": {
    "code": "activityLimitReached",
    "innererror": {
      "code": "throttledRequest"
    },
    "message": "The request has been throttled"
  }
}
```

It could be solved before if I changed to another app which registered in azure AD.
But now it seems to be worse, even I registered a new app.
Keeps return the same 429 error.

In this point, is any way to reduce this problem?
Even our system had throttled the request, the problem did not elminate.

Or like Gsuite, they provide a monitor panel that we can check the usage of our app
(Maybe it is still fail to handle this...)
![pasted image 2018-04-18 18-11-52](https://user-images.githubusercontent.com/12619781/38982948-c4b2484a-43f5-11e8-8b00-f9560a140b7c.png)

Really thanks for help

**Comment by chackman** [comment]
Thanks for your feedback.

We have some documentation about throttling and OneDrive for Business / SharePoint here: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online

With respect to your suggestion, I would suggest going to [UserVoice for SharePoint Dev Platform](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform) and suggest an improvement (or upvote an existing one).  This feedback helps us prioritize future work based on the interest in those suggested improvements.
