### ISSUE TITLE
HTTP request returned status code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#844]
When I upload a folder that has many items through the OneDrive WebUI, and some of those items get blocked from being uploaded. For example:

* Download https://bazaar.launchpad.net/~ecryptfs/ecryptfs/trunk/tarball/894
* Extract the downloaded file eg: `_ecryptfs_ecryptfs_trunk-r894.tgz` on Windows using winzip or similar & upload the folder as via OneDrive WebUI
* Files such as `.keep`, `00list`, `__init__.py` do not get uploaded. OneDrive presents this error message: `Sorry, OneDrive can't upload empty folders or empty files. Please try again.`. These files are of 0 size - so this is a 'valid' error message.

After uploading the files (and waiting until all 303 items are uploaded) - and then attempting a sync using the OneDrive Linux Client (https://github.com/abraunegg/onedrive), I get the following error

```
HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-04-22T21:45:34",
            "request-id": "aa5e4042-794d-4e63-8067-c5e2f9ad0306"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
```
This appears to only effect 'business' accounts as the error does not present itself when using a 'personal' account.

The only way to resolve thus far is to:

1. Remove the offending folder from OneDrive using Web UI
2. Remove the items.sqlite3 (local file the client uses to track what is in sync)
3. Perform a new sync

**HTTPS Debug:**
```
* Found bundle for host graph.microsoft.com: 0x25052e0
* Re-using existing connection! (#2) with host graph.microsoft.com
* Connected to graph.microsoft.com (65.52.176.80) port 443 (#2)
> GET /v1.0/drives('<redacted>')/items('<redacted>')/microsoft.graph.delta(token='<redacted>')?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference HTTP/1.1
User-Agent: Phobos-std.net.curl/2.079 (libcurl/7.29.0)
Host: graph.microsoft.com
Accept: */*
Authorization: <redacted>

< HTTP/1.1 500 Internal Server Error
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json
< request-id: f1b8f036-1443-46c6-972b-f8e1d76679e3
< client-request-id: f1b8f036-1443-46c6-972b-f8e1d76679e3
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East Asia","Slice":"SliceA","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_10","ADSiteName":"HKG"}}
< Duration: 1744.1266
< Strict-Transport-Security: max-age=31536000
< Date: Mon, 23 Apr 2018 03:00:38 GMT
< 
* Connection #2 to host graph.microsoft.com left intact
onedrive.OneDriveException@src/onedrive.d(539): HTTP request returned status code 500 (Internal Server Error)
{
    "error": {
        "code": "InternalServerError",
        "innerError": {
            "date": "2018-04-23T03:00:38",
            "request-id": "f1b8f036-1443-46c6-972b-f8e1d76679e3"
        },
        "message": "nextLink value without skip or skiptoken"
    }
}
```

**Comment by ificator** [comment]
This seems to be an issue with how Graph is interpreting the response from OneDrive for Business when the paging token exceeds a particular size. I'll see if there's anything we can do on our end.

**Comment by abraunegg** [comment]
The issue is with the current situation when a user get's this message the sync breaks & the only way to resolve currently is to remove the offending folder from OneDrive & perform a resync .. not exactly desirable.

Is there any way to escalate this being looked at?

**Comment by ificator** [comment]
We've made a change that should hopefully bypass this issue, but you'll probably need to restart the sync sessions to get a newer token.

**Comment by abraunegg** [comment]
Thanks - will test & get back to you
