### ISSUE TITLE
OneDrive: Unauthenticated, Must be authenticated to use '/drive' syntax

### ISSUE THREAD

**Issue by faisalraza** [OneDrive/onedrive-api-docs#845]
Hi,

I am using OneDrive api to upload files in my Ruby on Rails application and I am facing the following issue:

OneDrive API started giving the unauthenticated error on uploading file using the endpoint `/drive/root:/#{filename}:/content`. The error is given below:

`{"error"=>{"code"=>"unauthenticated", "message"=>"Must be authenticated to use '/drive' syntax"}}`

Then I got a new refresh_token by following the [OneDrive Docs](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth#register-your-app-with-azure-active-directory) using scope `files.readwrite offline_access`.

For OneDrive authentication, I am sending POST request to the endpoint `https://login.microsoftonline.com/common/oauth2/v2.0/token` to get `access_token` using the refresh_token with the following headers and body:
```
headers = { 'Content-Type' => 'application/x-www-form-urlencoded' }
body = {
  'client_id'     => "<Client ID>",
  'grant_type'    => "refresh_token",
  'redirect_uri'  => "<Redirect URI>",
  'client_secret' => "<Client Secret>",
  'refresh_token' => "<Refresh Token>",
}
```
Am I using the correct endpoint to get access_token from refresh_token?

The base uri I am using to upload files to OneDrive is `https://api.onedrive.com/v1.0`

Can anyone please help me why I am I getting unauthenticated error or how can I use `'/drive' syntax` for authentication?

Thanks in advance!

**Comment by ificator** [comment]
If you're hitting api.onedrive.com directly you'll need to auth using the [Microsoft Account flow](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth). It looks like the auth you're getting may be sufficient for graph though, so you could try your requests against `https://graph.microsoft.com/v1.0/me/drive/root...` and see if that works.

**Comment by faisalraza** [comment]
@ificator Thank you for the response. I have already solved it using [Microsoft Account flow](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth). Previously I was using Microsoft Graph authentication process and the access_token returned from that was not seem to be working. I also used `https://login.live.com/oauth20_token.srf` [POST] to get access_token and refresh_token instead of using `https://login.microsoftonline.com/common/oauth2/v2.0/token` according to the Microsoft Account flow and it worked.

Later I used my Office-365 account and followed [OneDrive for Business authentication](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/aad-oauth) to get it working.
