### ISSUE TITLE
Onedrive business group not showing up 

### ISSUE THREAD

**Issue by romanovacca** [OneDrive/onedrive-api-docs#849]
Hi, 

I'm trying to reach a Sharepoint group via the Microsoft graph api using python sdk. Im able to see my personal documents, as well also the files shared with me. However, I'm trying to access the Business Sharepoint drive.   When using GET https://{tenant}-my.sharepoint.com/_api_v2.0/sites I see some info about my personal account, but not the drive/group I'm looking for. I have given my user account some right like groups.read.all etc. But still can't find it.

I have tried removing -my from the request. but then nothing works. Is there a way for me to connect to the business sites which is given access to my account, because there are the documents I want to retrieve using the api.

**Comment by ificator** [comment]
Do you have the `files.read.all` scope? You'll need to that to access drives that belong to users/groups other than the caller.
