### ISSUE TITLE
Encoding error while uploading files with single quote

### ISSUE THREAD

**Issue by shiroychoksey** [OneDrive/onedrive-api-docs#85]
When I upload a file using PutNewFileToParentItemAsync and the file has a single quote in it, it gets uploaded as a file with 2 single quotes!!

**Comment by ificator** [comment]
Thanks for letting us know @shiroychoksey, it definitely sounds like a decoding issue. We'll get it fixed ASAP.

**Comment by ificator** [comment]
This should now be fixed! Please let us know if you still see issues.
