### ISSUE TITLE
Cant copy to anywhere bar its current folder.

### ISSUE THREAD

**Issue by kking1991** [OneDrive/onedrive-api-docs#851]
I am trying to copy a document from one folder to another inside my document library. I am able to copy the file into the same folder but not outside of it. I have tried using the parentRefernce object. Using  an ID a path trying to copy it to the root of the drive as well as the folder I actually want to put it in but keep getting the same error.

Id = 137, Status = RanToCompletion, Method = "{null}", Result = "error": "code": invalidRequest message: The request is malformed or incorrect.
"innerError":   request-id: 10989d70-c07b-4ce3-87de-ceec8f481691

**Comment by ificator** [comment]
Hi @kking1991, can you give us an example request body so we can see what you're sending us?

**Comment by kking1991** [comment]
{"ParentReference":{"DriveID":  "this is my document library drive id ",
"ID":" this is the id of the folder i want to move it to.",},
"Name":"copytemplatetoanotherfolder4.doc"}"

As documented on the api copy documentation however the format of my ids is not the same. My drive id is a lot longer than shown in the example. My id for the folder is not in the guid format either.

The request works when i take out the parent reference object. It creates the new copy inside the same folder. So i assume that the ids I'm using for the parent reference are incorrect but I have not been able to find an alternative id value.

Thanks

**Comment by kking1991** [comment]
Been resolved need to add jsonProperty annotation to my parent reference object. thanks anyway.

**Comment by ificator** [comment]
Thanks for updating us!
