### ISSUE TITLE
[ODB] "HTTP/1.1 504 Gateway Timeout" when uploading archives containing more than 2000 files.

### ISSUE THREAD

**Issue by cristian-vescan** [OneDrive/onedrive-api-docs#855]
If I try to upload a zip archive (1.5 MB in size) containing more than 2000 files I receive an `HTTP/1.1 504 Gateway Timeout` response.

The sequence is

1. I issue a `PUT https://graph.microsoft.com/v1.0/drive/root:/odrive/1.zip:/content` request 
2. The file is completely uploaded in about 300 milliseconds
3. I receive the 504 response containing
`{
	"error": {
		"code": "UnknownError",
		"message": "",
		"innerError": {
			"request-id": "7356798a-5319-4789-baf6-7f82b8455b25",
			"date": "2018-05-11T07:47:17"
		}
	}
}
`

This happens only if I use an `One Drive for Bussiness` account
If I upload an archive having the same size but a single file it works fine

Does this mean that the content of the file is scanned after upload and a large number of files causes a timeout?

What is the suggested upload sequence?

**Comment by chackman** [comment]
You can also upload using an upload session, which is recommended for large files.
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession

**Comment by cristian-vescan** [comment]
I could use an upload session for all the files (since I don't know the file content) but this would lead to double the requests and a faster throttling for the account.
The received error should clearly state the problem so I could take the appropriate steps.
For now, in case I receive a 504 Gateway Timeout, I will start an upload session.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
