### ISSUE TITLE
 HTTP/1.1 409 Conflict with "similarRelationshipNameAlreadyExists" code

### ISSUE THREAD

**Issue by kotsak** [OneDrive/onedrive-api-docs#856]
Hi,

Here is the scenario:

Folder on OneDrive Personal already has a file named Maersk.txt. Trying to rename a new file into Mærsk.txt (note ligature æ being used instead of 'ae') throws a _HTTP/1.1 409 Conflict_ response:

```
{
	"error": {
		"code": "nameAlreadyExists",
		"message": "An item with the same name already exists under the parent",
		"innererror": {
			"code": "similarRelationshipNameAlreadyExists"
		}
	}
}
```

Apparently OneDrive API treats the two filenames to be the same while Windows O/S treats them as different (both can exist in the same folder). Same issue exists also when trying to upload those files using the OneDrive's web UI, only one file remains ovewriting the other one.

Is there a way to override this behavior as it's causing problems to backup software? If not, what was the rationale behind the decision to treat those files the same because of ligature?

Thanks.

**Comment by ificator** [comment]
Under the covers Windows persists the file names using a binary collation, and so these name conflicts are a non-issue (the bytes that represent the file name in both cases are different). Unfortunately that is not the case for the OneDrive service, and the collation that is being used for name comparisons considers "ae" == "æ". As a result there isn't much that can be done, but example of unexpected conflicts like this is good feedback that we can use to improve things.
