### ISSUE TITLE
InvalidRequest error using Invite endpoint

### ISSUE THREAD

**Issue by DanHopkins-TGI** [OneDrive/onedrive-api-docs#857]
I am consistently getting `InvalidRequest` errors when attempting to use the `Invite` endpoint in my project and the Graph Explorer.  This has been working, but as of this morning I have tried various iterations of the `Invite` request body on different SharePoint files in the Graph Explorer without success.

An example request and response is below:

Request :
```
POST v1.0/drives/{driveId}/items/{itemId}/invite
{
 "recipients": [
    { "email": "{email}" }
  ],
  "message": "test",
  "requireSignIn": true, // I've tested with true and false values for both of these
  "sendInvitation": true,
  "roles": [ "read"]
}
```

Response:
```
Failure - Status Code 400
{
    "error": {
        "code": "invalidRequest",
        "message": "The request is malformed or incorrect.",
        "innerError": {
            "request-id": "fced3ea6-196c-433e-8aed-48e463a5020c",
            "date": "2018-05-15T16:22:14"
        }
    }
}
```

**Comment by chackman** [comment]
Thanks for your feedback.  This issue should now be fixed.  Could you let us know if it's not, and provide a recent request-id/date?  Thanks!

**Comment by DanHopkins-TGI** [comment]
Thank you for the update!  We are no longer experiencing the issue, so it does appear to have been fixed!
