### ISSUE TITLE
404 Response returned when attempting to download v4.master file

### ISSUE THREAD

**Issue by rloehr** [OneDrive/onedrive-api-docs#858]
Using the onedrive api I'm attempting to download a file.

I'm first issuing the request:
https://fakedomain.sharepoint.com/_api/v2.0/drives/b!mvqGl2FT4k2oAXHyyUVEHvZVq5fPWsRLm6KcX-Z8Fr-9KqTYyjaDSZezX3LgRh3Y/items/01QMKOSHIGRSRE4WCZNJHJQB7TAPYALJCX

The sprequest guid is: 1774679e-90fc-5000-926c-fe1819590568

This request returns and shows data such as:
```
    "name": "v4.master",
    "parentReference": {
        "driveId": "b!mvqGl2FT4k2oAXHyyUVEHvZVq5fPWsRLm6KcX-Z8Fr-9KqTYyjaDSZezX3LgRh3Y",
        "driveType": "documentLibrary",
        "id": "01QMKOSHN6Y2GOVW7725BZO354PWSELRRZ",
        "path": "/drives/b!mvqGl2FT4k2oAXHyyUVEHvZVq5fPWsRLm6KcX-Z8Fr-9KqTYyjaDSZezX3LgRh3Y/root:"
    },
    "webUrl": "https://fakedomain.sharepoint.com/sites/_catalogs/masterpage/v4.master",
    "cTag": "\"c:{4EA28C06-5958-4E6A-9807-F303F005A457},0\"",
    "file": {
        "mimeType": "application/xml"
    },
    "fileSystemInfo": {
        "createdDateTime": "2017-10-06T09:51:26Z",
        "lastModifiedDateTime": "2017-10-06T09:51:26Z"
    },
    "size": 27244
```

That should prove that the file exists.
When i attempt to either add a /content to the url or use the returned url returned in the 
@content.downloadUrl, a 404 is returned.

Example:
https://fakedomain.sharepoint.com/_api/v2.0/drives/b!mvqGl2FT4k2oAXHyyUVEHvZVq5fPWsRLm6KcX-Z8Fr-9KqTYyjaDSZezX3LgRh3Y/items/01QMKOSHIGRSRE4WCZNJHJQB7TAPYALJCX/content

Response:
404 FILE NOT FOUND
No sp request guid for this.

I know that the v4.master files are special "ghosted" files.   What on the backed could be causing the file to not be present?

**Comment by ificator** [comment]
Hi @rloehr I just tried to repro on my local environment and was not able to. When you make the request that returns the 404 can you provide a GUID in the `SPResponseGuid` header and let us know what value you provided and the value of the `Date` header in the response?
