### ISSUE TITLE
Onedrive Public link disabled

### ISSUE THREAD

**Issue by Rocky2908** [OneDrive/onedrive-api-docs#86]
I have been working on onedrive API for the Past one month. I was able to attach files in a forum using my web app and the users were able to view those files. But, suddenly I can see only view,edit links but not the view, edit and public links. Now my users couldn't see those files because they don't have access. how to make folders and files public in Onedrive now. below is the screen shot of how it's done before.
![image](https://cloud.githubusercontent.com/assets/10181686/7222585/4815574e-e72f-11e4-917b-88d2ccdb0887.png)

**Comment by rgregg** [comment]
Hi @Rocky2908,

We're in the process of removing the public sharing feature. It's been a source of confusing for end users who don't understand the difference between sharing something as "public" and sharing a view or edit link to a file. The ramifications of using "public" weren't clear.

You should be able to accomplish most of the scenarios that were available with public using a view link as well, although files won't be discoverable by search engines or browsing.

If you have a specific scenario that is broken as a result of no longer being able to create public links, please let us know.

**Comment by Rocky2908** [comment]
Hi @rgregg ,
Thanks for your reply.
My scenario is I am creating a developer app through which I am opening the filepicker window and a user(USER1) selects his "PUBLIC"ly shared files and other users(who have no idea about the USER1) should able to open the attached files.

I know this api can access the VIEW link a customer created
https://api.onedrive.com/v1.0/drive/{item-path}:/action.createLink

If I append access token with this API call will I get the VIEW link

**Comment by JordanSanderson** [comment]
I'm having a similar issue.  While I understand the confusion of public vs view the problem is that view requires you to be singed into a Microsoft account so there's no way to share a file or photo now with people that don't have an account.

**Comment by rgregg** [comment]
View links don't require you to be logged in, but it does require you to have the full URL (which includes a special authKey that enables you to access the content without being signed in).

Public permissions worked by just enabling anyone, including unauthenticated users, to access the content. No URL required, you could just "discover" the content freely.

Aside from the public discoverability issue, you should be able to accomplish any programmability scenario you would have used public for previously with a view link. If this isn't the case, please let me know specifically what you're trying to do and we can help you figure out how to make it work.

@Rocky2908 If you're using our picker SDK for JavaScript or Android and request a `webViewLink` link, you'll get back a URL that can be used by anyone, signed in or not, to view the file. Alternatively if you have your own picker UX you can use action.createLink to generate a view link, which works the same way. In your scenario, user 1 would create the view link URL and other users would need to use that URL to access the file.
