### ISSUE TITLE
SharedWithMe : query parameters?

### ISSUE THREAD

**Issue by dominiksteiner** [OneDrive/onedrive-api-docs#860]
We are considering using the sharedWithMe graph api

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/drive_sharedwithme

but there is no documentation about what query parameter it supports.

My guess is that it does not support any, but then will it always return all the files shared with me or is there an intrinsic limit? @rgregg

**Comment by chackman** [comment]
You can specify a top (most API's support some OData query parameters).  In the case of shared with me, the API will attempt to respect that parameter.

**Comment by JoshMayberry** [comment]
Is there a list of these query parameters somewhere?
