### ISSUE TITLE
uploadSession responds with accessDenied

### ISSUE THREAD

**Issue by msg7086** [OneDrive/onedrive-api-docs#861]
I'm writing a Ruby SDK to OneDrive API and I'm making use of the new OAuth v2.0 API and the Graph API.

Uploading fragments to uploadSession url on the sharepoint address frequently leads to 401 accessDenied response and the fragments uploaded were simply discarded by the server.

With an aggressive retry strategy I observed an average of 10% success rate. That is, uploading 100MB of data requires approximately 1GB of network traffic if you are lucky.

Slowing down retry frequency does not seem to improve the situation.

Even loading the uploadURL in a browser reads accessDenied.

Is this some kind of throttling? Or a bug?

Code can be found [here](https://github.com/msg7086/rb1drv/blob/master/lib/rb1drv/onedrive_dir.rb#L160).

```json
{"error":{"code":"accessDenied","message":"There has been an error authenticating the request."}}
```

**Comment by ificator** [comment]
Hi @msg7086, are you hitting a personal or business OneDrive? Are you providing an `Authorization` header when you make your `PUT` requests?

**Comment by msg7086** [comment]
Hello, this is a business plan, and I didn't provide the Authorization header during PUT requests.

It seems to me like API throttling, as I just waited for half day and the API was back in business.

My guess is that, since the authorization was done through the graph API, all calls to the sharepoint server with a tempauth needs to be checked by sharepoint server against graph SSO. If that fails, sharepoint just responds with a 401 instead of a 429.

**Comment by msg7086** [comment]
I'm afraid I cannot do it soon (or later) as I haven't hit the same problem since, maybe it was due to that I slowed down the request frequency. I'll post them if I ever hit it again, or anyone else who hits it can post them here as well.

Thanks

**Comment by ificator** [comment]
Thanks @msg7086, definitely let us know if you see it again. We'll keep this issue for a little while, but may end up closing it if we don't get any new information in a couple of weeks.
