### ISSUE TITLE
npm module for OneDrive API?

### ISSUE THREAD

**Issue by brownbl1** [OneDrive/onedrive-api-docs#864]
It would be very helpful for many developers to be able to bundle https://js.live.net/v7.2/OneDrive.js with their other javascript. I couldn't find a version on npm though. Do you have plans to or can you publish a common module version to npm?

**Comment by JeremyKelley** [comment]
Sorry for the very late reply on this, are you looking specifically to be able to have a package for the File Picker or other OneDrive APIs?

You can get packages for the Microsoft Graph (check https://graph.microsoft.com) that will give you types to work against and make coding easier.  They have other SDKs depending on which platform you're working against.

For the Picker and other UX components we're evaluating right now what the best delivery mechanism is.

**Comment by stefanbartos** [comment]
Hi,
it has been a while since the last comment. Is there any plan to have the File picker in npm with typings?
