### ISSUE TITLE
Instead of spawning new window, provide option for redirecting back

### ISSUE THREAD

**Issue by brownbl1** [OneDrive/onedrive-api-docs#866]
I have a use case where I am developing an Tab application for MS Teams. I would like to use this file picker control, but am having an issue with the way the window is loaded. Teams provides and SDK that works for both the web and their electron based desktop app. Traditional `window.open` works for the web, but not for electron. I'm not suggesting that you cater to the electron use case specifically, but the Teams SDK provides a method for opening a popup to a domain that is the same origin as the parent frame. (`microsoftTeams.authentication.authenticate`). From here, I could do a redirect to the file picker using the OneDrive SDK, but I wouldn't want to spawn another window. But in order to not spawn another window, I'd need to be able to tell the OneDrive SDK to redirect back to a page on my domain with the selected file info encoded in the URL hash or query. 

This would allow a good bit of flexibility and I think would be beneficial to more than just my use-case. But without this, I don't really see how one could use this filepicker from within the MS Teams app. 

Let me know if that doesn't make sense and I can clarify.

**Comment by KevinTCoughlin** [comment]
@brownbl1 you may consider the embeddable document library third-party SDK that we are working on `@microsoft/file-browser`, see https://www.npmjs.com/package/@microsoft/file-browser.

Unfortunately, the File Picker library _must_ spawn a window and use `redirectURL` flow as it is an AAD-based application and we do not allow iframing the hosted page for security reasons.
