### ISSUE TITLE
Feature Request: Delete history versions of a file

### ISSUE THREAD

**Issue by msg7086** [OneDrive/onedrive-api-docs#867]
"Get a DriveItemVersion" endpoint should accept `DELETE` request to delete a specific history version of a file.

```
DELETE /me/drive/items/{item-id}/versions/{version-id}
```

**Comment by ificator** [comment]
Hi @msg7086, thanks for the suggestion!

I'd recommend making sure it's present over at our [UserVoice page](https://onedrive.uservoice.com/forums/262982-onedrive?category_id=89523) as that provides direct feedback into our planning process.
