### ISSUE TITLE
[SharePoint] how to get all sites in Office 365

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#868]
Hi all,

According to doc, we can get group site and root site by API
```
GET /sites/root
GET /groups/{group-id}/sites/root
```

Question 1:
If there are more than one site belongs to a group, how to get them all?
![image](https://user-images.githubusercontent.com/12619781/40653931-48ee53fe-636f-11e8-8cbd-3ca298950a22.png)
DST24, DST29 are all belongs to DST
But when using GET /groups/{group-id}/sites/root, I can only get site DST24

Question 2:
How to get sites that belongs to a user via graph or Onedrive API?
![image](https://user-images.githubusercontent.com/12619781/40654018-9d30cdca-636f-11e8-9c50-7762156272d7.png)

Question 3:
What is the proper way to get all sites? by SP API  or graph API?
Another try for get all sites by SP API :
```
https://synologydst.sharepoint.com/_api/search/query?
querytext='contentclass:STS_Site contentclass:STS_Web'
&selectproperties='Title,Path'&rowlimit=500&StartRow=0
```

Thank you for help!

**Comment by joewutaiwan** [comment]
Hi @rloehr ,

Thank you for the reply,

Does the request operate on sharepoint? becase I failed to get sites from the query you provided.
It returns empty.

And about the caveats:
1.What is the root facet you cares?
2.What is the uncorrect results did you encounter? because I also use app only auth.

Really thank you for sharing this again!

**Comment by rloehr** [comment]
@joewutaiwan The call i mentioned is from the graph api.

Here is an example call:
https://graph.microsoft.com/v1.0/sites?search=

and the response i get:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites",
    "value": [
        {
            "createdDateTime": "2014-10-21T19:01:39Z",
            "id": "fake.sharepoint.com,5b462830-ef04-4e1e-a9db-8e43b86fd4c2,b48c6737-fc7a-4ea6-aabd-21254d4571f8",
            "lastModifiedDateTime": "2014-10-21T19:16:15Z",
            "name": "fake.sharepoint.com",
            "webUrl": "https://fake.sharepoint.com",
            "displayName": "fake Team Site",
            "root": {},
            "siteCollection": {
                "hostname": "fake.sharepoint.com"
            }
        }
}

The issue I believe exists is that in some cases, sites are not returned when using app only auth.

**Comment by joewutaiwan** [comment]
Hi @rloehr ,

Thank your kindly reply, this really helps me.

And here are two more questions:
1. In my observation,  only subsites are missing root facet. or do you find any exceptions?
2. How about the sites which belong to a user? Are your app just skip it?

Thank you for your time and patience in responding

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
