### ISSUE TITLE
few doubts over sharing_createLink

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#87]
can have more clarity over sharing_createLink (https://github.com/OneDrive/onedrive-api-docs/blob/master/items/sharing_createLink.md)

once the link generated,
Q1) when link will be expired?
Q2) will link be modified when file is updated for several time?
Q3) is it advisable to store share link, so tht whenever want to share with other, api calls will be saved?

**Comment by rgregg** [comment]
#1: Sharing links don't expire. They can be deleted by the app that created them or by others with edit access, but they don't automatically expire.

#2: The link is always the same, but points to the "live" version of the file, so if someone makes edits to the file, the link points to the file with those edits.

#3: If an app asks calls createLink multiple times for the same kind of link (edit or view) we'll always return back an existing link if there is one.

**Comment by rgregg** [comment]
I've added more details about sharing links, including the above answers, to the docs for createLink. These changes will go live with our next site refresh.

**Comment by NGattuccio** [comment]
So Ryan, you don’t need anything from the UA side on this, right?

**Comment by rgregg** [comment]
Nope. Thanks for reaching out though.

Sent from Outlook<http://taps.io/outlookmobile>




On Sun, May 3, 2015 at 4:33 PM -0700, "NGattuccio" <notifications@github.com<mailto:notifications@github.com>> wrote:

So Ryan, you don't need anything from the UA side on this, right?
