### ISSUE TITLE
Upload Session returning 400 Bad Request when Request Body is included

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#870]
In trying to solve 'Multiple versions of file shown on website after single upload' (https://github.com/abraunegg/onedrive/issues/2) for the Linux OneDrive client (https://github.com/abraunegg/onedrive) which is the same issue as described here - https://github.com/OneDrive/onedrive-api-docs/issues/778 - I am getting this issue - https://github.com/microsoftgraph/microsoft-graph-docs/issues/2139 - that the response generates a 400 Bad Request

As #778 is closed, opening this issue to help track this problem.

In trying to submit / upload a new item via `createUploadSession`:

```
POST /v1.0/drives/<redacted>/items/01D6JQORV6Y2GOVW7725BZO354PWSELRRZ:/Cygwin.zip:/createUploadSession
```

I add the following as the 'Request Body' as per https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession

```
{"item":{"@microsoft.graph.conflictBehavior":"rename","fileSystemInfo":{"lastModifiedDateTime":"2018-06-03T02:34:50Z"}}}
```

However OneDrive returns the following:

```
HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "date": "2018-06-03T08:00:29",
            "request-id": "cced3836-3874-4b69-bdd9-612ddd4cd70f"
        },
        "message": "The request is malformed or incorrect."
    }
}
```

How can this be resolved?

Is the 'Request Body' actually incorrect - as it matches the details in the API documents, and the details in #778 for updating lastModifiedDateTime so that 2 versions of the file are not created.

If I do not send a 'Request Body' - the session is created without issue.

**Comment by abraunegg** [comment]
Just an update - when using `@name.conflictBehavior` the request does work.

Should the documentation be updated to reflect this, or will this be resolved within Graph?

**Comment by ificator** [comment]
It's realistically an issue within Graph so we're following up with them, however if the fix is more involved we'll have to look at updating the documentation in the mean time.

**Comment by abraunegg** [comment]
@ificator 

It appears I have run into another issue with doing the session uploads & including the session body.

When uploading a file for the first time, the file gets created & by using the session body the timestamp is correct. The session body contains the following:
```
{"item":{"@name.conflictBehavior":"replace","fileSystemInfo":{"lastModifiedDateTime":"2018-06-03T02:34:50Z"}}}
```
If I then simply 'touch' the local file, and upload again as a 'modified file', with a similar session body, but now with the updated time stamp - 2 file versions are created for that session action.

The expectation here is that only 1 new file version is created for the modified file - not 2.

**Comment by ificator** [comment]
It sounds like this issue may now be resolved - if you feel like it, you should be able to revert back to using `@microsoft.graph.conflictBehavior` and it should behave as expected.
