### ISSUE TITLE
[LOC] Links in tables

### ISSUE THREAD

**Issue by OfficeGSX** [OneDrive/onedrive-api-docs#871]
There are multiple links in a table which seems to act as an examples however after clicking on such links error message is shown. Could you please confirm if this is a desired behavior or are the links supposed to redirect somewhere. See the below example:

1. Go to [https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file)
2. Search for the https://graph.microsoft.com/v1.0/ link

**Actual results**:
Link does not redirec to anywhere error code is shown
**Expected results**:
N/A as per description above

![image](https://user-images.githubusercontent.com/16706698/40919898-3c86aa80-680b-11e8-8d53-a243ce989159.png)

**Comment by chackman** [comment]
These are example API endpoint URL's, so clicking on them may not redirect to a functioning page.
