### ISSUE TITLE
Support dynamic redirect URL's

### ISSUE THREAD

**Issue by pradeepshastry** [OneDrive/onedrive-api-docs#872]
Is it possible to configure a dynamic redirect URL? We have a URL which has dynamic values embedded as part of the URI and it wouldn't be possible to separate them as query params.

e.g. http://foo.com/<userId>/product/<productId>/productDetails.html

In the above URL, userId and productId are part of the URI and are required in the callback

We have tried providing redirectUri using advanced option, but looks like the redirectUri specified here will still need to be configured in the OneDrive portal.

**Comment by chackman** [comment]
Thanks for your feedback.
Could you please explain where the redirectUri is being provided?  For example, is the redirectUri provided to the AAD portal?

**Comment by pradeepshastry** [comment]
@aditima Though I was able to solve the dynamic redirect URI issue with a workaround, I am stuck with the other issue where the SDK loads my web app in the file picker window instead of showing the OneDrive files. This happens only on v7.2 and the same code works perfectly fine on v7.0. Any inputs are highly appreciated.

**Comment by KevinTCoughlin** [comment]
> @aditima Though I was able to solve the dynamic redirect URI issue with a workaround, I am stuck with the other issue where the SDK loads my web app in the file picker window instead of showing the OneDrive files. This happens only on v7.2 and the same code works perfectly fine on v7.0. Any inputs are highly appreciated.

@pradeepshastry, are any errors thrown in the browser console? Are there any network request errors?

We'll need additional information to debug why you are seeing a difference between `v7.0` and `v7.2`.

Regarding dynamic redirectURLs, please see the OAuth spec: https://tools.ietf.org/html/rfc6749#section-3.1.2.3

**Comment by pradeepshastry** [comment]
@KevinTCoughlin We upgraded to the newer version of the SDK and we are not experiencing this issue after https://github.com/OneDrive/onedrive-api-docs/issues/891 was addressed.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin We upgraded to the newer version of the SDK and we are not experiencing this issue after #891 was addressed.

Great, thank you for following-up! Closing this issue as resolved.
