### ISSUE TITLE
IE 11 Issue with OneDriveSDK error

### ISSUE THREAD

**Issue by kubayaya** [OneDrive/onedrive-api-docs#874]
Hi ,

We are using for our website: https://js.live.net/v7.0/OneDrive.js  version and we are facing a problem 
with some users that have IE 11.0.9600.19002IS after the authentication , when redirecting back to the callback page there is an error. 

Line: 2
Error: [OneDriveSDK Error] missing options from serialized state

For the same users we had to add for IE only the microsoft.com domain to the trusted sites in order to even perform the authentication, but this might be related to the internal policy we have.
The same users using Chrome/Firefox there have no issue.

Note. For other users in the same network and with IE11.0.9600.19002 also no issue.

**Comment by KevinTCoughlin** [comment]
The above seems related to IE & restricted sites in user-land which we will be unable to address ourselves as the library requires AAD authentication redirect.
