### ISSUE TITLE
Error 501: Search is no longer supported in anaytics v2.0 api.

### ISSUE THREAD

**Issue by JoBa97** [OneDrive/onedrive-api-docs#876]
I am trying to search for elements on a single Sharepoint site, but it seems like this is not supported anymore. Am I using the wrong endpoint?

Request:
https://{tentant}-my.sharepoint.com/_api/v2.0/sites/root/search/query?querytext='text'

Response:
`{
	"error": {
		"code": "notSupported",
		"message": "Search is no longer supported in anaytics v2.0 api."
	}
}`

**Comment by ificator** [comment]
When you say you're "trying to search for elements" what kind of object are you wanting to find?

The sites API supports [searching for sites](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_search) (but not personal sites):
https://{tenant}.sharepoint.com/_api/v2.0/sites?search='text'

The drive API supports [searching for drive items](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_search):
https://{tenant}-my.sharepoint.com/_api/v2.0/drive/root/search?q='text'

**Comment by JoBa97** [comment]
Thank you for pointing me in the right direction. I am not too familiar with the terminology used to describe certain elements, but I was trying to search for drive items.
