### ISSUE TITLE
@name.conflictBehavior":"replace" creates 2 new file versions when replacing existing file

### ISSUE THREAD

**Issue by abraunegg** [OneDrive/onedrive-api-docs#877]
In trying to implement #778 & use #870 as a work around I have uncovered another issue that is similar to the original of #778 where 2 files are stored for the operation, however no PATCH call is being made.

This occurs when attempting to upload a timestamp modified via `createUploadSession` & using `@name.conflictBehavior":"replace" ` as part of the Request Body, if the file already exists, 2 new file versions are created, where the expectation is that only 1 file is created.

**Reproduction Steps**

_Step 1_
In trying to submit / upload a new item via `createUploadSession`:
```
POST /v1.0/drives/<redacted>/items/01D6JQORV6Y2GOVW7725BZO354PWSELRRZ:/<filename>:/createUploadSession
```
Include a Request Body:
```
{"item":{"@name.conflictBehavior":"replace","fileSystemInfo":{"lastModifiedDateTime":"2018-06-03T02:34:50Z"}}}
```

File is uploaded, version 1 of file

_Step 2_

1. Touch the local file so that the local timestamp is updated
2.  Re upload the file using `createUploadSession` & 'Request Body' but ensure that lastModifiedDateTime is set to the new modified file time in UTC

**Result**

3 files exist on OneDrive:

1 is from the original upload (step 1)
2 are from the modified upload - both have the exact same modified UTC timestamp (step 2)

The expectation here is that there should only be 2 file versions present - the original file uploaded & the uploaded file with the modified local timestamp

**Comment by abraunegg** [comment]
@ificator 

Any chance of looking into this issue?

**Comment by ificator** [comment]
It appears to be the `createUploadSession` call itself that's triggering the version. I'll see if there's something we can do about that.

**Comment by abraunegg** [comment]
@ificator 
Thanks for the confirmation that its a bug. Any update on the issue? This is holding back the release of a fix for the Linux OneDrive Client - https://github.com/abraunegg/onedrive

**Comment by ificator** [comment]
Hi @abraunegg the fix for this issue should have rolled out by now - please let us know if you're still seeing the issue.

**Comment by abraunegg** [comment]
Thanks - will do some testing here over the weekend & get back to you

**Comment by ificator** [comment]
I'm going to close this off now, but please feel free to reactivate if your testing finds anything you don't expect.

**Comment by abraunegg** [comment]
Sorry for the delayed reply.

Confirmed that this issue is resolved - thanks
