### ISSUE TITLE
autologin in onedrive picker by passing accesstoken in odparams

### ISSUE THREAD

**Issue by vikrasa** [OneDrive/onedrive-api-docs#879]
I am using OneDrive.js v7.2. 
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
I am trying to pass accesstoken in odparams so that I dont have to login everytime - 
var odOptions = {
  		  clientId: {appId},
  		  action: "download",
  		  multiSelect: true,		  
  		  advanced: {  			
			  endpointHint: "api.onedrive.com",
			  accessToken: {access token}
		  },
  		  success: function(response) {
                         ...
  		  },
  		  cancel: function() { 
  			  ..
  		  },
  		  error: function(e) {
  			  ...
  		  }
  		}  		
    	OneDrive.open(odOptions);

It is still asking for login everytime. As per the document - https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file#advanced-options
it should be supported in advanced odoptions. Please help.

**Comment by sandermak** [comment]
Also see https://github.com/OneDrive/onedrive-api-docs/issues/789

**Comment by liamfrawley** [comment]
Also wondering if anyone has solved this one?

**Comment by nhopp** [comment]
Has anyone solved this? It seems like basic functionality.

**Comment by lpoublan** [comment]
It works for me when I also specify loginHint parameter.
Remark: my API endpoint is  "https://graph.microsoft.com/v1.0/" (does not need to be specified as endpointHint as it is default value), it does not seem to be your case, so I'm not exactly in your configuration. But for sure it works for me when I specify loginHint and does not work if I omit it.

**Comment by dhavalsanghani** [comment]
I'm facing the same issue. Is anyone able to resolve it?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
