### ISSUE TITLE
tentative time frame for shared folder

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#88]
can we have tentative time frame for launching of apis for shared foder

**Comment by ificator** [comment]
Unfortunately we won't comment on future features here. Suffice it to say we've definitely heard all the feedback around shared folders :)

**Comment by rgregg** [comment]
Can you elaborate on the scenarios or features you are looking for?

**Comment by ankit-ankuagrawal** [comment]
@rgregg next month code will be going into production, before starting using new onedrive it was hot debate between team members over using new apis or old live connect api.
But finally onedrive api won.

Currently the scenarios looking for getting the details of file/folder shared by others, with this the permissions related to file/folders.

just curious to know when they will be launching...
