### ISSUE TITLE
Constantly receiving Activity limit reached

### ISSUE THREAD

**Issue by Zzzaru** [OneDrive/onedrive-api-docs#880]
Hi there,

We are trying to sync SharePoint site collections of a tenant that is not used by any other applications in their requests to Office365. Also, we use an application that syncs only one tenant that is mentioned above. The issue is that we receive an error Activity limit reached as soon as we perform the first request to SharePoint despite the fact that we usually wait for a few hours before performing that request.

GET https://graph.microsoft.com/v1.0/sites/root HTTP/1.1
SdkVersion: Graph-dotnet-1.9.0
Authorization: *
Cache-Control: no-store, no-cache
Host: graph.microsoft.com

HTTP/1.1 429
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json
request-id: f53b8a98-f17d-4a2f-b4c1-c2c0abfd5786
client-request-id: f53b8a98-f17d-4a2f-b4c1-c2c0abfd5786
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceA","Ring":"5","ScaleUnit":"003","Host":"AGSFE_IN_8","ADSiteName":"AMS"}}
Duration: 338.9956
Strict-Transport-Security: max-age=31536000
Date: Tue, 26 Jun 2018 09:37:28 GMT

ec
{
  "error": {
    "code": "activityLimitReached",
    "message": "The request has been throttled",
    "innerError": {
      "request-id": "f53b8a98-f17d-4a2f-b4c1-c2c0abfd5786",
      "date": "2018-06-26T09:37:28"
    }
  }
}
0

**Comment by ificator** [comment]
HI @Zzzaru, there have been numerous issues opened in regards to throttling behavior and general guidelines and so we've opted to resolve all of them in favor of tracking with a single issue (https://github.com/OneDrive/onedrive-api-docs/issues/853). Feel free to add your comments to that issue.
