### ISSUE TITLE
OneDrive Rest API delta token return empty data for track changes

### ISSUE THREAD

**Issue by nfz312** [OneDrive/onedrive-api-docs#881]
I use rest api GET https://api.onedrive.com/v1.0/drive/root/view.delta?token=*** to get oneDrive files changes, I used @delta.token to get next paging files(token).

The problem is when listing changes for oneDrive large files about 100 GB(about 18000 file) after about 40 minutes from listing files.

When get @delta.token for next request the next request provides empty value that mean there is no files remaining.

But when request again with same last request (that return empty value) the response will get list files and continue as expected.

I need a solution or documentation about this issue or work around

(maybe is related to request limitation from OneDrive but there is no documentation about it).

**Comment by ificator** [comment]
Hi @nfz312.

`view.delta` should be returning a link in the response either as `@odata.nextLink` or `@odata.deltaLink` (the former means "call using this URL straight away to get more data", while the latter means "there's nothing left for you to see at the moment, but if you call using this URL in the future we might have something new for you") and in this case it would be interesting to know which of the two you get when you see an unexpected empty page.

Generally speaking, the only time I'd expect to see nothing come back is when we've exhaust all of the possible items. Replaying the URL in the future could result in new results if any writes occurred between the two requests.

**Comment by nfz312** [comment]
Thanks for your answer, i used @odata.nextLink and it's working as expected.
