### ISSUE TITLE
Another FileHandler question

### ISSUE THREAD

**Issue by DaveHaasPowderSoftware** [OneDrive/onedrive-api-docs#883]
I've written a FileHandler manifest and application that I can now seem to get to at least render the preview. However, the preview method is passed a list of ActivationParameters which contains a list of url's (of files) that were selected by the user.

The documentation states that 'Each URL contains a token embedded in the URL that allows the file handler app to access the content without a full-trust permission scope'

I'm assuming that means some kind of access token but for the life of me I cannot figure out how to extract it from the provided url.

What am I missing?

Cheers,

Dave

**Comment by DaveHaasPowderSoftware** [comment]
Closing this as nobody is answering

**Comment by JeremyKelley** [comment]
Hi Dave, sorry we didn't respond quickly enough (just now getting through a big backlog of issues).

As far as I know you shouldn't need to extract the token, when your app follows the link back the embedded token should allow you to get the file without needing to pass the token separately.

**Comment by JeremyKelley** [comment]
Thanks for the feedback!  I'll take a look at the documentation and see what all we need to rev to make it clearer.  We'll also take a look to see if there's a better sample to work with.
