### ISSUE TITLE
Does the validity of @content.downloadUrl or @microsoft.graph.downloadUrl increase based on file size or is it fixed ?

### ISSUE THREAD

**Issue by gram25** [OneDrive/onedrive-api-docs#884]
I understand that the validity time of a pre-authenticated @content.downloadUrl or @microsoft.graph.downloadUrl is limited and undisclosed. Does it vary based on file size ? 

If I have a relatively large file to download over a slow connection, can I still use the url to start downloading immediately ?

I need to make sure the url doesn't expire once I start downloading a big file.

**Comment by ificator** [comment]
The expiration of the URLs is not impacted by the size of the file, but as long as you start using a URL to download you should be able to download the entire file no matter how big it is. The only time you may have a problem is if you're downloading a large file and you're, say, 2 hours in (assume a slow connection :)), and the connection drops - you can resume the download from where you left off using the `Range` header, but you'd have to get a new download URL first as the original will have expired.

**Comment by gram25** [comment]
That helps thanks ! Safer to get a new url every time I resume.
