### ISSUE TITLE
Not able to open attached document when tried to login with different user

### ISSUE THREAD

**Issue by geetharamu** [OneDrive/onedrive-api-docs#885]
I am using v7.0 one drive sdk and want to share the file with different users. I have attached file from one drive file picker dialog and received below response on success. 
{
  value: [
    {
      id: "4535465AA54SDE",
      name: "filename",
      size: 764674,
      webUrl: "https://1drv.ms/w/s!ANNc"
    }
  ]
}

Using value[0].webUrl link "https://1drv.ms/w/s!ANNc", I am trying to open the attached file with different userId. Url doesnt open and I am getting error 'This item might not exist or is no longer available'
![image](https://user-images.githubusercontent.com/30039108/42261574-48c79678-7f86-11e8-93a9-625d23518358.png)

In case of google drive, if we do the same it will prompt for 'Request Access', but not in onedrive. Can anyone please help how to solve the issue?

**Comment by geetharamu** [comment]
I am able to resolve the issue by taking url from => value[0].permissions[0].link.webUrl . If i share the link with other users,  they can view the document without sign in. Is there a way to prompt the user to login to access the shared document?
{
  "webUrl": "https: //1drv.ms/...",
  "value": [
    {
      "id": "id",
      "name": "Document",
      "size": 9333,
      "webUrl": "https: //1drv.ms/w/s!APPrlBIhteE-gXE",     
      "thumbnails": [{}},      
      "permissions": [
        {         
          "roles": [
            "read"
          ],
          "shareId": "s!AvPrlBIhteE-gXG32q4Qdg9aiJ_h",
          "link": {
            "type": "view",
            "webUrl": "https: //1drv.ms/w....",           
          }
        }
      ]
    }
  ]
}

**Comment by KevinTCoughlin** [comment]
@geetharamu the File Picker simply renders a frame of the hosted OneDrive site. This request seems to me like a request for additional functionality for OneDrive's web presence. I recommend adding this as an ask to https://onedrive.uservoice.com/.
