### ISSUE TITLE
OneDrive Rest API too many requests error when try to download file

### ISSUE THREAD

**Issue by nfz312** [OneDrive/onedrive-api-docs#886]
I use rest api:
https://api.onedrive.com/v1.0/drive/items/{fileID}/content
to download OneDrive file

When i tried to download multiple files from OneDrive response return error:

> The remote server returned an error: (429) Too Many Requests.

I tried to use Retry-After response header to wait before send another request but didn't work.

Is there any solution or work around for this issue?

My sample code in c#:

`try`
`{`
`  HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://api.onedrive.com/v1.0/drive/items/{fileID}/content");`
`  request.Method = "GET";`
`  request.Headers.Add("Authorization", "Bearer {accessToken}");`
`  WebResponse response = request.GetResponse();`
`  Stream fileStream = response.GetResponseStream();`
`}`
`catch (WebException ex)`
`{`
`  HttpWebResponse res = (HttpWebResponse)ex.Response;`
`  int retryAfter = 0;`
`  if (!string.IsNullOrEmpty(res.Headers["Retry-After"]))`
`   {`
`     retryAfter = int.Parse(res.Headers["Retry-After"]);`
`   }`
`  Thread.Sleep(retryAfter);`
`  //re-call same request function`
`}`

**Comment by JeremyKelley** [comment]
The work around code you have is really the suggested way to do this, if you get a 429 you need to honor the backoff, which is what it looks like you're doing.  Does it never clear and ultimately download?  How many simultaneous files are you trying to get?

**Comment by JeremyKelley** [comment]
Also, we have a larger thread that you can check out and add more comments to [here](https://github.com/OneDrive/onedrive-api-docs/issues/853).
