### ISSUE TITLE
File picker doesn't show shared files

### ISSUE THREAD

**Issue by SergeyZ11** [OneDrive/onedrive-api-docs#887]
The problem: I want to get access not only to my own OneDrive files, but to shared files also. Now I can't get them and there is the issue https://github.com/OneDrive/onedrive-api-docs/issues/733, where a similar problem is described. It is closed with "We will put it into the backlog" result.
Also, it is stated that there must be some information about this problem in docs, but I haven't found it :(
Looks like this is still doesn't work right now, am I right?
The picker is created with these parameters:
(
clientId: [clientId],
action: 'share',
multiSelect: true,
openInNewWindow: true,
advanced: {
redirectUri: [redirectUrl]
},
)

**Comment by SergeyZ11** [comment]
@aditima do you have any news?

**Comment by KevinTCoughlin** [comment]
Hey @SergeyZ11, @aditima is on leave so I'll be taking a look at this once I clear an auth parsing issue with the library #891

**Comment by liamfrawley** [comment]
Any update on this @KevinTCoughlin ?

**Comment by nkmurthy** [comment]
any update on this issue?

**Comment by filipe-rito** [comment]
Hey any news about this issue?

**Comment by DavicVictor** [comment]
Hello ! I am facing the same problem ? Does anyone have any news ? 
Is there any other way to solve this problem ?

**Comment by paella55** [comment]
I am facing the same issue. When I go to One Drive for business, I can see the files shared with me:

![image](https://user-images.githubusercontent.com/28304354/115377977-66820a80-a1d0-11eb-8a3e-e00e78b00044.png)

However, if I open the JavaScript file picker SDK, I am only able to see my own files.

![image](https://user-images.githubusercontent.com/28304354/115378068-7b5e9e00-a1d0-11eb-96cd-abd2c7fd4142.png)

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
