### ISSUE TITLE
Request access token for Office 365 Germany gives ambiguish error

### ISSUE THREAD

**Issue by pmbaldha** [OneDrive/onedrive-api-docs#888]
When I am trying to get access token for Office 365 Germany by API call as described on the 
https://docs.microsoft.com/en-in/azure/active-directory/develop/active-directory-v2-protocols-oauth-code#request-an-access-token, but it display irrelevant error like below:

    {
        "error": "invalid_client",
        "error_description": "AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 978ed68d-e8b5-419d-8f5c-a25df8f01200\r\nCorrelation ID: 45ee8bb8-b3a1-4d6f-8499-816739f6d118\r\nTimestamp: 2018-07-05 05:39:29Z",
        "error_codes": [
            70002,
            50012
        ],
        "timestamp": "2018-07-05 05:39:29Z",
        "trace_id": "978ed68d-e8b5-419d-8f5c-a25df8f01200",
        "correlation_id": "45ee8bb8-b3a1-4d6f-8499-816739f6d118"
    }

Screenshot: http://funkyimg.com/i/2JcXj.png

I have tried after url encoding client secret and making new secret, but I was failed. I have tried many times. 

However, Same flow working fine with Office 365 worldwide account.

**Comment by JeremyKelley** [comment]
I would check the documentation [here](https://developer.microsoft.com/en-us/graph/docs/concepts/deployments) to see if there is anything that looks like you might have missed it.
