### ISSUE TITLE
Inconsistent performance and reliability

### ISSUE THREAD

**Issue by volmedo** [OneDrive/onedrive-api-docs#889]
Aside from [other undocumented limitations](https://github.com/OneDrive/onedrive-api-docs/issues/840), we are experiencing a quite unreliable behaviour when testing the OneDrive API.

We are trying to use the OneDrive API to convert Office documents to PDF, so our client first uploads the document to a temporary location, invokes the [convert content](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_get_content_format) endpoint and then deletes the original document. We upload files below 4MiB directly and use upload sessions for documents greater than that, as per the documentation.

In our tests, we have seen a request error pattern similar to that described in #853 in the sense that request performance drop dramatically in business hours (our requests are being served by the North Europe Datacenter) and we can see lots of errors for test runs done on business hours. The very same test run done later at night produces no errors.

We are not facing `429 Too Many Requests` errors, so no throttling in our case, but just regular `503 Service Unavailable` and `504 Gateway Timeout` errors, with some occasional `500 Internal Server Error`s. No `Retry-After` header can be found in any of the error responses. We have implemented a backoff strategy for retries, but this is usually of no help.

We are trying to evaluate if the OneDrive API is suitable for our use case, but this "business hours chaos" thing is mind-blowing. Do you have any information on why this happens? Are any specific limitations being applied? What is the rationale behind such a decision? Are the limits applied on a per user, per tenant or per datacenter basis?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
