### ISSUE TITLE
can create folder name begin with 2 periods

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#89]
as mention on github page (https://github.com/OneDrive/onedrive-api-docs/blob/master/misc/path-encoding.md)
the folder names can't begin with two periods (..)

but can create a folder starting from .., from web portal of onedrive and also from android app
![folder name starting from 2 dots](https://cloud.githubusercontent.com/assets/11455759/7271593/1c43f98e-e902-11e4-8af1-9bbc5706fe5b.png)

**Comment by rgregg** [comment]
Looks like the restriction has been relaxed. I'm getting confirmation to that end and then I'll update the documentation accordingly.

**Comment by rgregg** [comment]
This will be updated in the next refresh.
