### ISSUE TITLE
Thumbnail URLs don't work

### ISSUE THREAD

**Issue by TastesLikeTurkey** [OneDrive/onedrive-api-docs#890]
According to the docs, I should be able to call `/drive/special/music/delta?$expand=thumbnails` to include thumbnails for items. I'm doing this, and I'm successfully getting the thumbnails. However, if I try to load one of the thumbnail URLs without an access token, I get a 200 OK response -- but it returns a redirect to the OneDrive login page. If I request the thumbnail _with_ my access token, I get a 401 Unauthorized response. I can get a usable URL by calling `/me/drive/items/{itemId}/thumbnails/{thumbnailId}/{size}` for each thumbnail, but this is extremely slow and the URLs seem to expire after a bit.

**Comment by JeremyKelley** [comment]
Hi @TastesLikeTurkey looks like you've found a bug.  We should be returning pre-authenticated URLs from the Delta query the same way we do directly but we're returning auth-required URLs instead.  I'm logging a bug to investigate internally and we'll take a look at why it's broken and how to fix it.

If you don't mind me asking, what's your scenario?  Are you using the Delta query to actually look for changes or just a way to enumerate all the folders and files in your music folder?

**Comment by TastesLikeTurkey** [comment]
@JeremyKelley Thanks for the info. 

> If you don't mind me asking...

Not at all. I'm building a music client which, among other things, will be able to show a user's OneDrive music and play it back. So I'm using the delta query with a blank url the first time to list all of the music, and subsequently to perform updates to the locally-cached library.

**Comment by JeremyKelley** [comment]
Thanks, right now what you're doing is probably the easiest way to accomplish it (once we fix the URLs).  You can also traverse the structure of the music folder but that will definitely be more calls to the service, as long as you get the parent relationships in the delta query though you should be fine as-is.

**Comment by ificator** [comment]
@TastesLikeTurkey the fix for this should have been deployed now - please let us know if you're still seeing issues.

**Comment by TastesLikeTurkey** [comment]
@ificator Thanks! I'll give it a try and let you know as soon as I get a chance.

**Comment by TastesLikeTurkey** [comment]
Ping @ificator @JeremyKelley , any updates on this?

**Comment by TastesLikeTurkey** [comment]
Ping @ificator @JeremyKelley again... Any sort of status update would be great, even if it's "nothing's happened"...

**Comment by TastesLikeTurkey** [comment]
@ificator @JeremyKelley

**Comment by TastesLikeTurkey** [comment]
@ificator @JeremyKelley

**Comment by TastesLikeTurkey** [comment]
@ificator @JeremyKelley

**Comment by TastesLikeTurkey** [comment]
@ificator @JeremyKelley

**Comment by TastesLikeTurkey** [comment]
You know what, forget it. I'm not willing to go through this unresponsiveness every time I hit a bug in the API. I'm going with a different cloud integration.
