### ISSUE TITLE
OneDrive file picker doesn't load with using IWebBrowser2 control

### ISSUE THREAD

**Issue by liamfrawley** [OneDrive/onedrive-api-docs#892]
I'm a developer working on using the OneDrive file picker on a native C++ desktop application. At the moment we're doing some investigation work to see if this is possible and we've hit a problem.

The application is using a WebBrowser control (IWebBrowser2) to display the HTML to allows the user to display the OneDrive file picker. The page is hosted here:
https://liamfrawley.github.io/liamfrawley/
This page and OneDrive file picker works on Chrome and IE11 without any problems.
 
However, when using IWebBrowser2 to display https://liamfrawley.github.io/liamfrawley/, it doesn't work. I get a spinner when displaying the popout file picker - the popout picker cross launches IE11 with Protected Mode **Off**. IWebBrowser2 is also running with protected mode **Off**

_Properties of the page https://liamfrawley.github.io/liamfrawley/ within IWebBrowser2 control:_
![image](https://user-images.githubusercontent.com/10150958/43258336-5c805e52-90ca-11e8-9756-bbaafb1d3ea3.png)

_Spinner when IE11 is cross launched by clicking "Go To OneDrive"_
![image](https://user-images.githubusercontent.com/10150958/43258177-e3f7b5a2-90c9-11e8-993f-ff4ce5daf6fc.png)

_Here are the properties for the cross launched page:_
![image](https://user-images.githubusercontent.com/10150958/43258210-fcef4048-90c9-11e8-8d5e-803627850c38.png)

The problem I'm having reads a lot like this one: Issue #755 

Is it possible to achieve what we're trying to do?
Thanks

**Comment by KevinTCoughlin** [comment]
@liamfrawley -- Any errors thrown in the window that is failing to load?
