### ISSUE TITLE
OneDrive File Picker v7.2 doesn't finish to load the picker into PWA

### ISSUE THREAD

**Issue by fredyhrios** [OneDrive/onedrive-api-docs#896]
Over the browser the function using the filepicker for access to oneDrive works well, but when I open the same functionality from the PWA, after complete the authentication process on the new window, it's stopped and only show me the loading spinner_grey_40_transparent.gif.

I'm using for make the pwa https://www.pwabuilder.com/ recommended for Microsoft.
I'm using OneDrive File Picker v7.2.

```
var odOptions = { 
        clientId: CLIENTID,
        action: "query",
        multiSelect: false,
        advanced: {
          redirectUri: "https://SERVER/onedriveredirect.html"
        },
        success: folderPickSuccess,
        progress: function(p) { },
        cancel: function() { },
        error: function(e) { console.log('ERROR');}
      };
onedriveapi.save(odOptions);
```

https://SERVER/onedriveredirect.html
```
<html>
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
</html>

```
The redirectUri was added to redirect URLs after authentication permitted as platforms web.

**Comment by fredyhrios** [comment]
hint: the function "folderPickSuccess" on the event success is never called, the window parent logged to the console "SCRIPT70 console: Permission denied".

**Comment by fredyhrios** [comment]
OneDrive File Picker v7.2 only works when using a personal account and the endpointHint property is configured with "api.onedrive.com", but when I used the commercial account, the behavior was the same (never finished the load) with any endpointHint or no endpointHint,

I can see some pending request in the development tools and they never end.

I tried from chorme in Ubuntu using the "home screen button" and it works fine.

All tested scenarios work well from browsers, including Microsoft Edge without the PWA.

Please, someone has the same problem or has a solution for that.
I appreciate all your help!

**Comment by KevinTCoughlin** [comment]
Hey @fredyhrios thanks for the report. I'll try to repro locally by using the PWA builder we supply. Can you provide any additional debug information particularly about the request minus any private credentials?

I'm wondering why the request is hanging indefinitely. I'll see if the same happens to me.

**Comment by fredyhrios** [comment]
Hey @KevinTCoughlin , Thanks for all your help!
If you need something else, please let me know.

index.html
```
var odOptions = { 
      clientId: CLIENTID,
      action: "query",
      openInNewWindow: true,
      multiSelect: false,
      advanced: {
        redirectUri: "https://SERVER/redirect.html"
      },
      success: function(a){ console.log(a); },
      progress: function(p) { },
      cancel: function() { },
      error: function(e) { console.log(e);}
    };
 OneDrive.save(odOptions);
```

redirect.html
```
<!DOCTYPE html>
<html>
	<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
</html>
```

![virtualbox_msedge - win10_3_03_08_2018_08_54_24](https://user-images.githubusercontent.com/39420994/43644164-cb1b911a-96fb-11e8-82ad-77f208c8505c.png)
![virtualbox_msedge - win10_3_03_08_2018_08_55_28](https://user-images.githubusercontent.com/39420994/43644165-cb2c5428-96fb-11e8-9525-84d73ab02e33.png)

**Comment by fredyhrios** [comment]
Hey @KevinTCoughlin, Do you have any result from your side ? If you need more information, please let me know.
I appreciate all your help!

**Comment by KevinTCoughlin** [comment]
Working to close #891 first. I'll update this thread with my findings after that.

**Comment by fredyhrios** [comment]
Hello @KevinTCoughlin, thanks for works on this issue, do you have some news ?
I appreciate all your help!

**Comment by fredyhrios** [comment]
Hi @KevinTCoughlin, Did you find the problem related to this issue ?
I appreciate all your help!

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
