### ISSUE TITLE
Can't get permissions for Microsoft Graph API Drive integration on Outlook live accounts

### ISSUE THREAD

**Issue by DenitsaGencheva** [OneDrive/onedrive-api-docs#898]
Hi, we are using Microsoft Graph API for uploading files for business and personal accounts.

After the account logs in, we ask for some permissions, but we don't add the one needed for OneDrive. After the user explicitly requests to upload a file we send another request for an AccessToken including all scopes until now + files.readwrite.all. This was working perfectly until (maybe) May 2018. Now it works for business accounts, but not for personal accounts.

Steps that we do:

Redirect the user to login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=...&redirect_uri=https%3A%2F%2Fmywebsite.com%2Fsignin-microsoft&response_type=code%20id_token&scope=openid%20offline_access%20profile%20email%20mail.readwrite%20mail.send%20contacts.readwrite%20calendars.readwrite%20people.read%20user.read%20files.readwrite.all&response_mode=form_post&nonce=636656...&state=CfDJ8MLMcPchE...

The user selects their account (with which they are already signed in)

They get redirected to https://login.live.com/oauth20_authorize.srf with the following sreen:

![error_page](https://user-images.githubusercontent.com/30897864/43388537-1c87c742-93f2-11e8-8624-c41aa8a4df83.PNG)

The permissions are not added for our application and we don't get any error. Here is also the response from the error page:

```
Error Info
"/pp1600/oauth20_authorize.srf?client_id=9d3c...&scope=openid+offline_access+profile+email+mail.readwrite+mail.send+contacts.readwrite+calendars.readwrite+people.read+user.read+files.readwrite.all&redirect_uri=https%3a%2f%2fmywebsite.com%2fsignin-microsoft&response_type=code+id_token&state=CfD...&response_mode=form_post&nonce=636...&x-client-Ver=5.2.0&display=host&uaid=521...&msproxy=1&issuer=mso&tenant=common&ui_locales=en-US&username=pesho..."
loginserverprotocolhandler(846)
HR=0x80041018
Method string:GET
URL:"/pp1600/oauth20_authorize.srf"
Query string:"code=5"
Server protocol:HTTP/1.1
```
After a couple of tries i actually managed to grant access to one of my accounts for the OneDrive integration. Not really sure what changed. I was just logging in and out with different Outlook accounts in Outlook and in our app. After that, i tried the same process with a different account and it failed again. Every time I was trying this I was logged with the same account on both places.

One more thing that I noticed is that before the consent was for all permissions and now the consent screen showed request only for the files permission.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
