### ISSUE TITLE
One drive API adding # after [Redirect URI]

### ISSUE THREAD

**Issue by jsinh** [OneDrive/onedrive-api-docs#9]
I was quickly trying to get a access token by using a sample MVC project.

I tried to use "Token flow" and sent a request to

https://login.live.com/oauth20_authorize.srf?client_id={client_id}&scope={scope}
    &response_type=token&redirect_uri={redirect_uri}

with my data filled in the {}.

The response I get back has following URL format (using {} identifier to omit long and actual query parameters values):
http://mytestdomain.com/my-apps-redirect-uri#access_token={access_token_demo_value}&authentication_token={authentication_token_demo_value}&token_type=bearer&expires_in={expires_in_demo_value}&scope={scope_demo_value}&user_id={user_id_demo_value}

If you look closely then you will observe that the URL contains a `#` right after the redirect URL.

Is this normal?
This makes it hard to extract all query string parameters within a controller's action. In this case it may work (not tried yet) if I make new exclusive entry for this type of URL pattern in my application's MVC route configurations to work around this, this would not be recommended IMO.

Ideally I (as an application) would expected a `?` instead of `#`

Awaiting response from OneDrive API dev. team or a good reason on why `#` instead of standard `?` to begin query string.

Thanks

**Comment by jscaria** [comment]
@jsinh - OneDrive uses Microsoft account as its identity provider, which implements the OAuth 2.0 protocol.   Per the OAuth 2.0 spec, the access token is returned in in the fragment component of the redirect uri when the response type is set to "token" as described at https://tools.ietf.org/html/rfc6749#section-4.2.2.    

If you would like the access token in the query parameter, consider using the "code" flow.

**Comment by rgregg** [comment]
Closing this out. If you have any additional questions, feel free to reopen.

**Comment by jsinh** [comment]
@jscaria Thanks for OAuth 2.0 protocol reference, that makes sense.

There are two redirects / response that follows following pattern, the one i mentioned above and the other is error response:

https://login.live.com/err.srf?lc=1033#error=unauthorized_client&error_description=The%20client%20does%20not%20exist.%20If%20you%20are%20the%20application%20developer%2c%20configure%20a%20new%20application%20through%20the%20application%20management%20site%20at%20https://manage.dev.live.com/.

I read the protocol spec further and found specification for this one too.
https://tools.ietf.org/html/rfc6749#section-4.2.2.1

Thanks again for the clarification !!

**Comment by jscaria** [comment]
To address the error you're seeing, register you app with Microsoft accounts.   There's more details at https://github.com/OneDrive/onedrive-api-docs/blob/master/auth/msa_oauth.md#to-register-your-app.    Ensure that you're using the same client id & redirect uri (in the query params) that you registered your app with.
