### ISSUE TITLE
some character's are missing on github page

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#90]
as mention on github page (https://github.com/OneDrive/onedrive-api-docs/blob/master/misc/path-encoding.md)
the following symbols are not allowed in file/folder name, they are

onedrive-reserved  = "/" / "\" / "*" / "<" / ">" / "?" / ":"

in this list some are missing, and they have been shown in onedrive.com

![characters symbols not allowed](https://cloud.githubusercontent.com/assets/11455759/7271857/0709bbec-e904-11e4-892c-693235b1b36d.png)

**Comment by rgregg** [comment]
Looks like we're missing two characters, | and ", from the documentation. Is that what you're seeing?

**Comment by ankit-ankuagrawal** [comment]
yup

**Comment by rgregg** [comment]
Thanks for pointing that out. I'll get this updated when the next refresh of our site goes out.
