### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by JValck** [OneDrive/onedrive-api-docs#901]
The [https://docs.microsoft.com/en-us/onedrive/developer/rest-api/#programming-notes](docs) don't mention any clear info about the limit for requests per user/per hour.

When trying myself, I noticed that with a token acquired to [get access as the user](https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_user) or a token acquired to get access [without a user logged in](https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service), I get throttled after only five requests.
The `Retry-After` header contains `30`, so I try again after 30 seconds, but without any luck.

**Comment by JValck** [comment]
Error in the logs:
```
{
    "error": {
        "code": "activityLimitReached",
        "message": "The application or user has been throttled."
    }
}
```
When I grab the token from the url MS Graph Explorer, the 429 isn't raised.

**Comment by JValck** [comment]
The error is seen when retrieving metadata for a OneDrive for Business.
Some more details:

Request-Id: `f1393536-4f61-4c75-bf67-02bf95747038`
x-ms-ags-diagnostic: `{"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"3","ScaleUnit":"001","Host":"AGSFE_IN_4","ADSiteName":"NEU"}}`
Date: `Wed, 15 Aug 2018 09:32:24 GMT`

**Comment by chackman** [comment]
As there have been many issues open about throttling and guidelines, we're tracking with a single issue - #853 - which includes a link to a corresponding UserVoice request.  Both of those talk primarily about SharePoint/OneDrive for Business.

Feel free to provide feedback there, or on the linked UserVoice request.
