### ISSUE TITLE
Upload from url with graph api

### ISSUE THREAD

**Issue by neunygph** [OneDrive/onedrive-api-docs#903]
I have everything working just fine when upload file from url with 'https://api.onedrive.com/v1.0' endpoint but when switching to 'https://graph.microsoft.com/v1.0' endpoint, it does'n't work anymore.
Below is my request body
POST: https://api.onedrive.com/v1.0/drive/items/{parentid}/children
{
  "@microsoft.graph.sourceUrl": "httt://test.png",
  "name": "testme.png",
  "file": { }
}
I even tried PUT _https://graph.microsoft.com/v1.0/drive/items/{parent-id}:/{filename}:/content_ but it's not working, it uploaded empty file to my onedrive instead of actual image. Please advice.

Thanks,
Phuong

**Comment by neunygph** [comment]
Hi @ificator ,

I tried again and it works this time, it only showed response status is bad request. Not sure what I missed last time, but it's all good now. Thank you very much.

Phuong

**Comment by neunygph** [comment]
Hi @ificator 

Now I know what I missed, when using access token that I retrieve from file picker, login dialog, the token was coming from <code>graph.microsoft.com</code> and it worked just fine when uploading to <code>graph.microsoft.com</code>.
But when using access token that I retrieve from <code>api.onedrive.com</code> and uploading to <code>graph.microsoft.com</code>, I got "unauthorized" error code (401). Below is the response
<code>
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "CompactToken parsing failed with error code: 8004920A",
    "innerError": {
      "request-id": "6546c0c5-fd92-4a7e-8225-4420d724d3d6",
      "date": "2018-08-16T18:22:00"
    }
  }
}
</code>

Is this the expected behavior because one accesstoken from another endpoint can't be used on a different endpoint ? If it is, please advice a solution because I have any features that rely on the <code>api.onedrive.com</code> endpoint.

Thanks,
Phuong

**Comment by ificator** [comment]
I apologize for the delay.

In general, the tokens used by `graph.microsoft.com` and `api.onedrive.com` are different and cannot be used against the other service. Ideally Graph would be suitable for all scenarios, so I'm curious what features of `api.onedrive.com` you're using that don't work against Graph.

**Comment by ificator** [comment]
Closing stale issues.
