### ISSUE TITLE
Enable localization support for File Picker

### ISSUE THREAD

**Issue by KevinTCoughlin** [OneDrive/onedrive-api-docs#905]
Moved from https://github.com/OfficeDev/office-ui-fabric-react/issues/5029 as we have the other picker related issues here.

 @samyaktelsang commented on May 29

>In lieu of an effort to improve globalization/localization of the products that we build, 0365 and SharePoint enable us to localize our files and custom fields.

However, while using a FilePicker class, there isn't an option to provide the button's display name. It resorts to a default text such as "Choose File" in Chrome or "Upload" on Edge.
I find that this makes it hard for developers to localize text based on the users AAD context or O365 language preference settings.
If we were allowed to set the button's display name/text ourselves, then it would enable us to localize the strings in a definition file as we have standardized across our project.
Are there any plans of ensuring we can select the text that shows up on the button while using a FilePicker component ourselves? If not, could we please ensure that we can in an effort to improve globalization/localization of the products/solutions that we build.

We're tracking this issue and hope to support it soon.

**Comment by samyaktelsang** [comment]
Thank you @KevinTCoughlin . Appreciate you incorporating this feature request into your backlog.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
