### ISSUE TITLE
Get a DriveItem resource from shared folder by path return "itemNotFound"

### ISSUE THREAD

**Issue by sploid** [OneDrive/onedrive-api-docs#908]
Hi, all.

I have a problem to get DriveItem by a path from shared with me folder.

The first request return shared with me folder:
**GET me/drive/root/children**
`"remoteItem": {
    "id": "EF8A24CC458790DF!106",
    "parentReference": {
      "driveId": "ef8a24cc458790df",
      "driveType": "personal"
    }
  }`

The second request return listing in shared with me folder:
**GET drives/ef8a24cc458790df/items/EF8A24CC458790DF!106/children**
`
{  "value": [
{
  "parentReference": {
    "driveId": "ef8a24cc458790df",
    "driveType": "personal",
    "id": "EF8A24CC458790DF!106",
    "name": "src",
    "path": "/drives/ef8a24cc458790df/root:/onedriveapi/src"
  },
} ] }
`

But a request by path in shared with me folder failed and return "itemNotFound":
**GET /drives/ef8a24cc458790df/root:/onedriveapi/src**
This request has to work: https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_get.md

**Comment by ificator** [comment]
Hi @sploid, can you describe the structure of the drive with id "ef8a24cc458790df"? Specifically, I'm curious about the relationship between "EF8A24CC458790DF!106" and it's ancestors. For example:

/onedriveapi/src = EF8A24CC458790DF!106,  shared to user b
/onedriveapi = EF8A24CC458790DF!105, not shared
/ = "root", not shared

**Comment by sploid** [comment]
1. This folder shared with me:
![image](https://user-images.githubusercontent.com/5768411/44839563-ca361e80-ac47-11e8-87a4-828d489286dd.png)

2. This is a result of call **me/drive/root/children**:
https://1drv.ms/u/s!AvfOmgqM9D8uhngpN1KP5TLZaC87
In line 53 info about this folder in my drive begins.
In line 82 info about this folder in remote drive begins.
remote-item-id: EF8A24CC458790DF!106
remote-drive-id: ef8a24cc458790df

3. I want to get DriveItem for "main.cpp" file by path in shared with me folder:
![image](https://user-images.githubusercontent.com/5768411/44840204-3cf3c980-ac49-11e8-8cfb-886341cc0898.png)

4. This is a result of call **drives/ef8a24cc458790df/items/EF8A24CC458790DF!106/children**:
In line 292 info about "main.cpp" file begins.
In line 326 we can see info about parent of "main.cpp" file.

5. Those requests failed with "item not found":
drives/ef8a24cc458790df/root:/onedriveapi/src/main.cpp
drives/ef8a24cc458790df/root:/onedriveapi/src/src/main.cpp

**Comment by ificator** [comment]
Thanks @sploid 

I cannot see a reason why the following request would not work:
https://graph.microsoft.com/v1.0/drives/ef8a24cc458790df/root:/onedriveapi/src/main.cpp

Could you provide the headers and body of the 404 response? Maybe that'll give some more details.

**Comment by sploid** [comment]
@ificator , thanks for the help.

1. this is request and response headers:
https://1drv.ms/t/s!AvfOmgqM9D8uhw8l87WcLOiLDuFx

2. this is response content:
https://1drv.ms/u/s!AvfOmgqM9D8uhxB_lwzV6XnbkqUR

**Comment by ificator** [comment]
Hi @sploid, that was useful.

I was wrong with my previous comment - for non-owner cases a direct path from the root is not allowed. In that light, it's definitely a bug that the path we return references the root so I'll track fixing that. What should actually be happening is that the path should be relative to the item shared to the caller, and so in this case I'd expect it to be `/drives/ef8a24cc458790df/items/ef8a24cc458790df!105:/src/main.cpp`. Unfortunately it's kinda hard for your code to figure this out, but you can still make a path relative to the id that you do have - so `/drives/ef8a24cc458790df/items/ef8a24cc458790df!106:/main.cpp`.

Hopefully that helps.

**Comment by ificator** [comment]
Hi @sploid, we've pushed a change that should make this scenario work as you expect. Let us know if you still seeing weird behavior for your use case.
