### ISSUE TITLE
How to create a photo album?

### ISSUE THREAD

**Issue by ksmutny** [OneDrive/onedrive-api-docs#909]
I know it is discouraged to use undocumented APIs, but I will ask anyway.

How to programmatically create an OneDrive photo album? The ones a user can create on onedrive.com or in Windows 10 Photos app.

I have already figured out where the albums are stored (in a well hidden user-inaccessible folder):

```
GET https://graph.microsoft.com/v1.0/me/drive/items/<user-id>!0:/SkyDriveCache/Albums:
```

where `<user-id>` is OneDrive user's ID. Getting `/children` then retrieves all the user's albums.

An album is a drive item with undocumented bundle `facet`:

```
"bundle": {
    "childCount": 9,
    "album": {
        "coverSourceId": "<some-photos-id>"
    }
}
```

However trying to create an album fails with `accessDenied` response.

```
POST https://graph.microsoft.com/v1.0/me/drive/items/<user-id>!0:/SkyDriveCache/Albums:/children

{
    "name": "My New Album",
    "bundle": {
        "album": {}
    }
}
```

What am I missing? What else needs to be provided to be able to create an album?

**Comment by ificator** [comment]
We got a new issue opened on this topic, and it has a little more detail, so I'm going to close this issue.

Please use https://github.com/OneDrive/onedrive-api-docs/issues/955 for future comments.
