### ISSUE TITLE
may be a problem with sharelink when deleted from portal

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#91]
dont know how much the following is issue or not, but thought to report

created the share link 
1) the link is generated from android app
https://onedrive.live.com/redir?resid=1D641CFAE05579A4!1268&authkey=!AJPwNhuCRfgkjKs
2) the following link is same for file, taken from portal
https://onedrive.live.com/redir.aspx?cid=1d641cfae05579a4&resid=1D641CFAE05579A4!1268&parId=1D641CFAE05579A4!110&authkey=!AJPwNhuCRfgkjKs&ithint=file%2ctxt

purposefully deleted the shared link from portal, still when using the link (from portal 2nd) was able to see the content for few moments, then page redirected to ask credentials

**Comment by ificator** [comment]
How long is a few moments?

**Comment by ankit-ankuagrawal** [comment]
2-3 sec

**Comment by ankit-ankuagrawal** [comment]
@ificator is there problem with this?

**Comment by ificator** [comment]
I tried reproing your scenario to see what kind of delay we're talking about and I wasn't able to. When I removed the link and immediately refreshed an InPrivate session that was using the link I got redirected to the sign in page. Is it possible browser caching or something like that was factoring in to your test?

**Comment by rgregg** [comment]
Doesn't sound like there is an API issue here and we weren't able to reproduce the delay. If this continues to be a problem please re-open this thread.
