### ISSUE TITLE
Mistake in the docs for resumable uploads

### ISSUE THREAD

**Issue by JValck** [OneDrive/onedrive-api-docs#910]
The docs give following possibilities for the `conflict behavior`:
`"@microsoft.graph.conflictBehavior": "rename | fail | overwrite"`

However, the `overwrite` option does not exists and should be changed to `replace`.

**Comment by JValck** [comment]
[Link to the docs](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession#create-an-upload-session)

**Comment by JeremyKelley** [comment]
Hi @JValck, I've logged an internal bug for us to go update the documentation.  Thanks for noticing this!

-Jeremy

**Comment by chackman** [comment]
The documentation is now updated.
