### ISSUE TITLE
The caller is not authenticated. 

### ISSUE THREAD

**Issue by Woody-Woo** [OneDrive/onedrive-api-docs#911]
Hi!

We develop utility with the option to upload files to Onedrive for Business.

During the different requests to rest API of one drive for business some customers get the following error message:

 ` "{" error ": {" code ":" unauthenticated "," message ":" The caller is not authenticated. "}}"`

This isn't the regular issue and happens from time to time. If this error happens our application waits for two minutes and refreshes OAuth token it repeats this four times, but that doesn't resolve the issue. 

Also, this error often happens with "The request has been throttled".

If you need additional information please feel free 

Any idea?

**Comment by JeremyKelley** [comment]
Hi @Woody-Woo, if this is associated with a throttle response (429) you need to wait the amount of time specified by the response not just two minutes.

To help figure out where the unauthenticated message is coming from please provide us with some example request IDs and the approximate time the error was received.  That will help us search the logs to see what happened.

Thanks!

-Jeremy

**Comment by Woody-Woo** [comment]
Hi,
endpoint: exboncom-my.sharepoint.com

request(utc): 8/25/2018 07:39:55.1088 
response(utc): 8/25/2018 07:39:55.3276
SPRequestGuid: 3423889e-70c8-0000-0c75-68fdf088b511
Content: {"error":{"code":"unauthenticated","message":"The caller is not authenticated."}} 
-
request(utc): 8/27/2018 8:14:43.3611 
response(utc): 8/27/2018 8:14:43.5018
SPRequestGuid: fdc9889e-60fd-0000-0c97-9c9f1ddcf878
Content: {"error":{"code":"unauthenticated","message":"The caller is not authenticated."}}

Thanks!

**Comment by chackman** [comment]
According to our logs, the token is invalid.  Are you possibly reusing an old refresh token?

**Comment by Woody-Woo** [comment]
We'll check this.

Thanks for your help.
