### ISSUE TITLE
HTTP Error 423 (Locked) not documented

### ISSUE THREAD

**Issue by skilion** [OneDrive/onedrive-api-docs#912]
Hello, while using the REST API to delete a file I got a response with status 423 (Locked) and body:
```
{
    "error": {
        "code": "accessDenied",
        "innerError": {
            "date": "2018-09-12T06:12:46",
            "request-id": "74d9b899-d03e-44c1-8e36-f3c80dc00718"
        },
        "message": "Lock token does not match existing lock"
    }
}
```
The error is self-explanatory and the `accessDenied` code is documented; however the [error section](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/errors.md) does not say that the 423 status may be returned by the API.

**Comment by chackman** [comment]
Thanks for your feedback, I'll log an internal bug for us to track.

**Comment by LukaBrazi** [comment]
Hope my comment will help someone& This error occurred when you try to modify or delete a file that is open at the current time in the browser.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
