### ISSUE TITLE
Invite works for some users but not other organisations onedrive users

### ISSUE THREAD

**Issue by chris-biggs** [OneDrive/onedrive-api-docs#915]
Hi,

I am sending invites from OneDrive for Business account in the format: 

     https://{tenant}-my.sharepoint.com/_api/v2.0/drive/items/{item-id}/invite

with the json body of

    {
        "requireSignIn":true,
        "sendInvitation":true,
        "roles":["read"],
        "recipients":[{"email":"someone@company.com"}],
        "message":"this is a test"
    }

This works just fine for several of my test users - none of whom have a OneDrive (Business or Personal) account. The above even works if I provide a non-existing account. (By "work" I mean the http request does not come back with an error!)

It does not work though when the email address is for someone who has a OneDrive for Business account! The http response code is 400 and I get the json:

    {
        "error": {
            "code":"invalidRequest",
            "message":"The request is malformed or incorrect."
        }
    }

I do not believe the reuqest is malformed as all I have done is change the email address and I have switched backwards and forwards all day. So is there something special I need to do for an email address that is associated with OneDrive and if so, how do I found out if an email address has a OneDrive account?

Many Thanks in Advance & Regards,
Chris

**Comment by chackman** [comment]
Hi Chris,

To help investigate, provide us with some example request IDs and the approximate time the error was received. That will help us search the logs to see what happened.

Also are the errors exclusively happening for users who do not belong to the current organization?

**Comment by chris-biggs** [comment]
Hi,

Apologies - I forgot to respond to your question..... However this perhaps was fortunate as I do now have more information.

I have my organisation (which only has one user at the moment - me). Using this account and the API, I can send invites to 3 users who are not part of any organisation (i.e. they do not have any OneDrive for Business accounts). I cannot send an invite to a user who is part of another organisation called C****** (i.e. does have a OneDrive for Business account). I have tried to send invites to 2 users from this organisation. Both failed in the same way.

I have just received confirmation from another user from another organisation called D***** (i.e. does have a OneDrive for Business account) that I succesfully sent an invite to them! The email was sent yesterday at approx. 17-Sep-2018 16:32:14. The email address was r.....@.....com.

Thanks & Regards,
Chris

**Comment by chris-biggs** [comment]
Hi Chris,

I have re-run the tests this morning and have the header information for you.

The one that fails produced these headers:

Response Header: Date	
	Wed, 19 Sep 2018 06:50:05 GMT

Response Header: request-id	
	4a2c909e-3000-6000-f57c-ded546e843ac

Response Header: SPRequestGuid	
	4a2c909e-3000-6000-f57c-ded546e843ac


The one that works produces these headers:

Response Header: Date	
	Wed, 19 Sep 2018 07:24:35 GMT

Response Header: request-id	
	432e909e-2021-6000-cc15-e3a6b9fcee76

Response Header: SPRequestGuid	
	432e909e-2021-6000-cc15-e3a6b9fcee76

Many thanks for looking into this for me.

Regards,
Chris

**Comment by chris-biggs** [comment]
Hi Chris,

I have performed some more testing and have more information that I hope will help identify the issue.

I can successfully send mutliple invites to a user that has a OneDrive for Business account if they ignore them.

Once they accept an invite, gone through the verification process and viewed the folder the invite relates to then subsequent invites to them fail to send with the "The request is malformed or incorrect" error message being returned. 

I notice that a user that has accepted an invite from me appears in both the Active Users and Guest Users pages on the 365 Admin Center --> Users lists in my OneDrive for Business Account. This feels relevant!

Thanks in Advance,
Chris

**Comment by chris-biggs** [comment]
Hi,

I have resolved the above issue. I believe it to be (at best) an undocumented feature which may get resolved at some point.

The issue was that I was using the OneDrive for Business 2016 API. The URL for this is:

    https://{tenant}-my.sharepoint.com/_api/v2.0

This works absolutely fine for everyting I want to do apart from sending invites to users who OneDrive users and have accepted an invite. I could send multiple invites to users who do not have a OneDrive account and I could send multiple invites to OneDrive users provided they did not accept them!

If I use the standard URL of:

    https://graph.microsoft.com/v1.0

I can do everything I want.

While I have read that the latter URL is preferred to the former (https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences?view=odsp-graph-online) there is nothing to say that you cannot or should not use one over the other. The documented differences do not including the issue I found.

Never mind. The problem and the resolution is now documented on the web. Hopefully someone will find this useful.

Regards,
Chris

**Comment by ificator** [comment]
Thanks for your follow up Chris. There really shouldn't be any functional difference between the two endpoints so I'm a little curious why it works through Graph. The error from the logs indicated some bad state in the UserInfo table and I was going to suggest you go to the site's user page ({SiteUrl}/_layouts/15/user.aspx) and delete the user in question, however now that it's working through Graph I'd be curious if the call directly to sharepoint.com still manifests the same failure.

**Comment by chris-biggs** [comment]
Hi,

I just tried to send an invite to the d...@....com user using the "version 2.0" method (at 09:21:57 BST). I got the same error message as before and the user confirmed they did not recieve an email.

Regards,
Chris

**Comment by chris-biggs** [comment]
Sorry I thought I was closing my comment not the thread!

**Comment by ificator** [comment]
That's very strange - there really shouldn't be any difference between Graph and direct for this. You provided an example of the direct call in your initial comment - can you provide one for the Graph call?

**Comment by chris-biggs** [comment]
Hi,

I can confirm that I have made no changes to the body of the request - only to the URL. A request ID using the Graph invite (and was successful) is 00634c5e-bb76-4785-98ff-fa468db7241a. This was made at 10-Oct-2018 10:30:27 GMT

**Comment by ificator** [comment]
Hi @chris-biggs, at the moment nothing is jumping out that would explain what you're seeing. There is one discrepancy that I'd like you to confirm though. We have information on all three requests reported in this issue and they all seem to be targeting the invite at a different user:

4a2c909e-3000-6000-f57c-ded546e843ac (FAILED) - ?@co*.com
432e909e-2021-6000-cc15-e3a6b9fcee76 (SUCCEEDED) - ?@pr*.m*.uk
00634c5e-bb76-4785-98ff-fa468db7241a (SUCCEEDED) - ?@do*.co.uk

Can you confirm that Graph still succeeds when creating a link for the co*.com user?

**Comment by chris-biggs** [comment]
Hi, I can confirm that ?@co*.com is now receiving invites when I use Graph. I can send them another one if you would like but as they are part of another company I try to minimize testing that involves them.

**Comment by ificator** [comment]
I don't suppose you managed to get a `request-id` for when you used `?@co*.com` through Graph? I don't think it'll provide us with anything really different to the request from a day ago, but it's useful to remove variables when debugging things like this. If you don't have one hande we can probably wait until the next time you need to share something with them if you like.

**Comment by chris-biggs** [comment]
Hi,

I just ran another one to ?@co*.com. Request Id df61b5d9-5c8d-4c86-b190-838a01f0df03. Ran at 11-Oct-2018 17:12:06 GMT.

Thanks for persevering with this.

Regards,
Chris

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
