### ISSUE TITLE
Documentation on the error response codes

### ISSUE THREAD

**Issue by paya-cz** [OneDrive/onedrive-api-docs#92]
Is there any documentation on the error codes of the [error resource type](https://onedrive.github.io/resources/error.htm)?

Eg. for the following JSONs
- > {"code":"serviceNotAvailable","message":"Service is temporarily unavailable","innererror":{"code":"serviceNotAvailable"}}

- > {"code":"generalException","message":"Insufficient Space Available"}

The codes would be `serviceNotAvailable` and `generalException`. It would be great if these codes would get fixed and documented, so client apps can parse them and react accordingly.

And I would like to propose that the code for "Insufficient Space Available" get changed from `generalException` to something like `insufficientSpaceAvailable`, so the app can display meaningful message to the user and also know there is not enough space (instead of thinking that some general error happened).

**Comment by ankit-ankuagrawal** [comment]
refer https://onedrive.github.io/misc/errors.htm

**Comment by paya-cz** [comment]
@ankit-ankuagrawal That document seems to just explain the HTTP error codes. Please let me know where I can find the JSON response error codes (`response["error"]["code"]`) description on that page, as I fail to find any.

**Comment by ankit-ankuagrawal** [comment]
json response error code have direct mapping with http status code

eg 1) {"code":"serviceNotAvailable",

"message":"Service is temporarily
unavailable","innererror":{"code":"serviceNotAvailable"}}

503 http status code


2) {"code":"generalException","

message":"Insufficient Space Available"}

507 http status code

for wht purpose u required all json error code details???


if u want to handles error, used http status code and
*"Important:* Error messages are not localized and are intended for the
developer to reference. They shouldn't be displayed directly to the user."

**Comment by paya-cz** [comment]
Because I did not get 507 for "Insufficient Space Available", but 500 (Internal Server Error). It might be just a bug but you never know.

**Comment by ankit-ankuagrawal** [comment]
if that is the case, report here by creating issue, so that the team can
rectified it...

**Comment by rgregg** [comment]
RE: Documenting the error codes in the JSON body -- we're working on this, but want to make sure we're happy with all of the codes that are being returned today before we document them. In most cases, the HTTP status codes are enough information to make a code decision - the error codes may be useful for informing the user of additional details.

The issue with receiving a 500 instead of a 507 for insufficient space available sounds like a bug that we'll need to fix.

**Comment by daspek** [comment]
The [error docs](https://dev.onedrive.com/misc/errors.htm) have been updated with comprehensive details about the error codes.
