### ISSUE TITLE
Upload file with multi-byte filename return "invalidToken".

### ISSUE THREAD

**Issue by yhayashi** [OneDrive/onedrive-api-docs#920]
#### Category
- [ ] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

I expect to successfully upload to OneDrive For Business using multi-byte filenames. Like "日本語.jpg".

#### Observed Behavior

OneDrive For Business returns "invalidToken" in file upload.

#### Steps to Reproduce

**First: Create upload session**

`POST https://graph.microsoft.com/v1.0/me/drive/items/<REDACTED>/%E6%97%A5%E6%9C%AC%E8%AA%9E.zip%3A/createUploadSession`

HTTP/1.1 200 OK

    {
        "@odata.context" : "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.uploadSession",
        "uploadUrl" : "https://<REDACTED>-my.sharepoint.com/personal/<REDACTED>/_api/v2.0/drive/items/<REDACTED>/uploadSession?guid='<REDACTED>'&path='~tmp00_%E6%97%A5%E6%9C%AC%E8%AA%9E.zip'&overwrite=False&rename=True&dc=0&tempauth=<REDACTED>",
        "expirationDateTime" : "2018-10-02T23:42:55.011Z",
        "nextExpectedRanges" : [ "0-" ]
    }

**Second: Extract "uploadUrl" from response** 

**Third: Upload file**

`PUT https://<REDACTED>-my.sharepoint.com/personal/<REDACTED>/_api/v2.0/drive/items/<REDACTED>/uploadSession?guid='<REDACTED>'&path='~tmp00_%E6%97%A5%E6%9C%AC%E8%AA%9E.zip'&overwrite=False&rename=True&dc=0&tempauth=<REDACTED>`

with "Content-Range" : "bytes 0-4690370/4690371"

HTTP/1.1 401 Unauthorized

    {
        "error": {
            "code": "unauthenticated",
            "message": "This access token is not valid on this endpoint.",
            "innerError": { "code": "invalidToken"}
        }
    }

Remark: I can upload to OneDrive (not For Business) by the same procedure.

Regards,

**Comment by ificator** [comment]
Hi @yhayashi, are you providing an `Authorization` header on your 3rd request? When it fails like this there should be a `request-id` header in the response - could you provide that?

**Comment by yhayashi** [comment]
> 
> 
> Hi @yhayashi, are you providing an `Authorization` header on your 3rd request? When it fails like this there should be a `request-id` header in the response - could you provide that?

Hi @ificator, 

I don't privide `Authentication` header on my request.
Latest request-id is `75e9949e-b039-7000-eec3-4147ccef9a1d`.

FYI, Upload a file is success if I only change the file name to all alphabets.

Regards,

**Comment by ificator** [comment]
Thanks for the `request-id`, I think it shows what's going on.

In the case you showed above, the URL that we return is:
```
https://<REDACTED>-my.sharepoint.com/personal/<REDACTED>/_api/v2.0/drive/items/<REDACTED>/uploadSession?guid='<REDACTED>'&path='~tmp00_%E6%97%A5%E6%9C%AC%E8%AA%9E.zip'&overwrite=False&rename=True&dc=0&tempauth=<REDACTED>"
```

However, when the request gets to us it's:

```
https://<REDACTED>-my.sharepoint.com/personal/<REDACTED>/_api/v2.0/drive/items/<REDACTED>/uploadSession?guid='<REDACTED>'&path='~tmp00_%25E6%2597%25A5%25E6%259C%25AC%25E8%25AA%259E.zip'&overwrite=False&rename=True&dc=0&tempauth=<REDACTED>"
```

Note the extra encoding in the `path` query string parameter. For security purposes, the upload URLs are very sensitive to modification and so the introduction of double encoding is triggering an error that's surfacing as an auth failure.

What client library are you using to send the request? Is it possible that it's encoding our URL?

**Comment by yhayashi** [comment]
Thank you for your replay.

I used Apache Http Components. I investigated based on your comment, and Apache Http Components encoded the URL...
I can upload files by suppressing URL encoding!

I appreciate your cooperation.

Best regards,
