### ISSUE TITLE
DriveItem Thumbnail URLs are not cache-safe

### ISSUE THREAD

**Issue by ksmutny** [OneDrive/onedrive-api-docs#922]
#### Category
- [ ] Question
- [x] Documentation issue
- [x] Bug

API behaviour is in contradiction with documentation. It's either a bug or an undocumented intended behavior.

#### Expected or Desired Behavior
DriveItem Thumbnails' URL to be cache-safe, as described in https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_list_thumbnails.md.

#### Observed Behavior
API call
```
GET https://graph.microsoft.com/v1.0/me/drive/items/<ITEMID>/thumbnails/0/large
Authorization: Bearer <ACCESSTOKEN>
```
returns JSON like
```
{
  "@odata.context": <REDACTED>,
  "height": 560,
  "url": <SOMEURL>,
  "width": 800
}
```
SOMEURL is different each subsequent call, event a second apart. The DriveItem hasn't changed to have different thumbnail. The URLs point to the same picture. They're just generated every time differently, which renders them not cache-safe and result in unnecessary reloading the thumbnails in client application after each refresh.

API call
```
GET https://graph.microsoft.com/v1.0/me/drive/items/<ITEMID>/thumbnails/<THUMBID>/<THUMBSIZE>/content
Authorization: Bearer <ACCESSTOKEN>
```
returns redirect like
```
HTTP/1.1 302 Found
Location: <SOMEURL>
<irrelevant headers left out>
```
SOMEURL is again different each time, contrary to the documentation.

#### Steps to Reproduce
1. Generate an OAUTH2 access token for a user with OneDrive Personal.
2. List items in the /drive/root and pick any with a thumbnail
3. Call any of the aforementioned APIs
4. The URLs returned are each time different.

**Comment by ksmutny** [comment]
If it is an intended behavior, besides fixing the documentation I would welcome a suggestion how to effectively cache thumbnails if one couldn't rely on the URLs returned by the APIs.

**Comment by ificator** [comment]
We do have a mechanism that will try to generate a consistent URL for a period of time, but for some reason this API is not leveraging that. I think it's fair to say that's a bug.

**Comment by ificator** [comment]
The fix for this was rolled out a while ago now, but I was on leave so couldn't update. Now you should see the thumbnail URLs remain static for a period of time for better cacheability.

NOTE: This applies only to OneDrive Consumer. Getting something similar working for Business will require more work.
