### ISSUE TITLE
[ODB] size mismatch with onenote file

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#927]
Hi all,

I found that the size meta from` GET /item/item_id` is not matched with downloaded onenote file

For example:
This is the header from ` GET /item/item_id` and the size of this item is 170
```
< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store
< Pragma: no-cache
< Content-Type: application/json; charset=utf-8
< Expires: -1
< Server: Microsoft-IIS/10.0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< x-ms-request-id: 8bedfee3-aa68-4b17-af59-cad65b811a00
< P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
< Set-Cookie: x-ms-gateway-slice=015; path=/; secure; HttpOnly
< Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
< Date: Thu, 18 Oct 2018 10:08:45 GMT
< Content-Length: 1506
```
But after I download this onenote file, the size is 10116025
And I can open the downloaded file properly via onenote 2013.

It was a bug or the ` GET /item/item_id` meta is not reliable in specific file types?

Thanks!

**Comment by chackman** [comment]
To clarify, are you only observing this issue with OneNote files?

**Comment by joewutaiwan** [comment]
@chackman ,
Thanks for reply,
Not only happened in OneNote files, but most issued files are OneNote.

**Comment by joewutaiwan** [comment]
Hi @chackman 

 Here is another case in different account

```
< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store
< Pragma: no-cache
< Content-Type: application/json; charset=utf-8
< Expires: -1
< Server: Microsoft-IIS/10.0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< x-ms-request-id: 62d7f854-e805-4670-ada7-d046e4844a00
< P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
< Set-Cookie: x-ms-gateway-slice=003; path=/; secure; HttpOnly
< Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
< Date: Mon, 05 Nov 2018 02:32:52 GMT
< Content-Length: 1504
```

Is this information enough to clarify problem?

**Comment by daspek** [comment]
Hi @joewutaiwan, the HTTP headers you include don't appear to be coming from OneDrive. Can you double check that these are the OneDrive headers and not from another endpoint? (They look similar to what login.microsoftonline.com returns).

**Comment by joewutaiwan** [comment]
Hi @daspek 

How about this one

`GET drives/<drive_id>/items/<item_id>`

Got size 119629 but actually downloaded size is 120749

```
cache-control →no-cache, no-store
content-encoding →gzip
content-type →application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
date →Wed, 14 Nov 2018 03:55:46 GMT
expires →-1
microsoftsharepointteamservices →16.0.0.8231
ms-cv →nqIoksywAHCZOtvW5d3bqQ.0
odata-version →4.0
p3p →CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
pragma →no-cache
request-id →9228a29e-b0cc-7000-993a-dbd6e5dddba9
spclientservicerequestduration →203
sprequestguid →9228a29e-b0cc-7000-993a-dbd6e5dddba9
status →200
strict-transport-security →max-age=31536000
vary →Accept-Encoding
x-aspnet-version →4.0.30319
x-content-type-options →nosniff
x-frame-options →SAMEORIGIN
x-ms-invokeapp →1; RequireReadOnly
x-msedge-ref →Ref A: D5B71E3543E549D5AB79CB638E56CB40 Ref B: HK2EDGE1009 Ref C: 2018-11-14T03:55:46Z
x-powered-by →ASP.NET
x-sharepointhealthscore →2
x-sp-serverstate →ReadOnly=0
```

Thank you for help

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
