### ISSUE TITLE
Get folder's items in original sort order

### ISSUE THREAD

**Issue by TCPcloudDEV** [OneDrive/onedrive-api-docs#929]
[Enter feedback here]

How can I get folder's items in original sort order?

var res = Client.Drive.Items[FolderId].Request().Expand("children($expand=thumbnails)").GetAsync(); // where FolderId is variable

res.Children always contains items sorted by Name only, no matter what res.Folder.View.SortBy value is.

I'm using Microsoft Graph Client Library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8afe01-1167-52b4-b2b4-47cbee8ddccf
* Version Independent ID: 56ef57eb-5eed-75ef-36a5-8e38fa7dd075
* Content: [DriveItem - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online)
* Content Source: [docs/rest-api/resources/driveitem.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/driveitem.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment]
Are you trying to change the sort of the SharePoint library view itself, or just get your results array sorted on your client?

If you just want to sort your results array you should be able to use the OrderBy method on the Children property and get back a sorted array.

**Comment by TCPcloudDEV** [comment]
Hi Jeremy,

I want to get items in the same order as OneDrive folder has online. I have many folders with custom sort arrangements, but I’m still getting items sorted by name only. Please see attached image for more info.


Thanks in advance!
Dmitriy


Sent from my Windows 10 device

**Comment by chackman** [comment]
This question was [also asked in the Microsoft Graph StackOverflow](https://stackoverflow.com/questions/52901849/get-onedrive-items-in-default-sort-order), so closing this item.
