### ISSUE TITLE
When will there be a list with nextExpectedRanges?

### ISSUE THREAD

**Issue by sohamm17** [OneDrive/onedrive-api-docs#93]
When I upload data in fragments, the server returns `nextExpectedRanges`. Whenever I tried, this `nextExpectedRanges` is a list containing only one element of expected range. However, they do have an example: 
```javascript
HTTP/1.1 202 Accepted
Content-Type: application/json

{
  "expirationDateTime": "2015-01-29T09:21:55.523Z",
  "nextExpectedRanges": [
  "12345-55232",
  "77829-99375"
  ]
}
```
I want to know the situation where this kind of multiple values in the `nextExpectedRanges` can come.

**Comment by rgregg** [comment]
There isn't a scenario today where we'll return multiple ranges. We've left this in to make it possible for us to expand the way the upload API works to support additional scenarios in the future.

As long as you handle the first range in the nextExpectedRanges array, you're code should be forwards compatible.

**Comment by sohamm17** [comment]
Okay, I thought you support this kind of service. Thanks anyway!
