### ISSUE TITLE
Check file changes in OneDrive for Business

### ISSUE THREAD

**Issue by bastyuchenko** [OneDrive/onedrive-api-docs#930]
Hello.
I need to develop RER for OneDrive for Business. Theoretically, it should work as same as in SharePoint but I have found no proof from microsoft documentation or any developer on the internet that it is possible. Could you confirm that remote event receivers work for OneDrive for Business? Maybe remote event receiver for OneDrive for Business has different name like FileHandler or something else? What restriction are there? :
- Could I register RER just for a specific folder, not only for a root of OneDrive for Business?
- Could I register just FileUpdated event?
- Will event fire every time when user changes a cell's value in an excel document and loses focus from this cell?(auto-save when you edit an excel document online)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f993b6-934a-54ce-d720-43e45f5b71e6
* Version Independent ID: d0b43b63-9460-ef97-9fc2-c05adb7f14af
* Content: [OneDrive for Developers - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/?view=odsp-graph-online)
* Content Source: [docs/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
We recommend using webhooks instead of Remote Event Receivers.  More information about webhooks can be found here:

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/webhooks
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-webhooks?view=odsp-graph-online
