### ISSUE TITLE
Access token size increased recently for SSO users

### ISSUE THREAD

**Issue by fwang96** [OneDrive/onedrive-api-docs#931]
#### Category
- [x] Question

#### Expected or Desired Behavior

We are making a REST call to OneDrive to get access token with auth code and store returned access token in our database, before the token size is under 2,048 which is the column size in our database. Recently some of our customer reported that they failed to log into OneDrive with SSO, which was working for them before. After checking the response from OneDrive, we noticed that some of the access tokens are now over 2,048 (we see 2,090 and 2,115 in our log). Is there a maximum token size that we can use to avoid future issue?

**Comment by chackman** [comment]
Could you please clarify which API you have a question about?

**Comment by fwang96** [comment]
Hi chackman, this happened after we got authorization code and making a POST to redeem the code for access token:
POST: https://login.live.com/oauth20_token.srf

**Comment by chackman** [comment]
Access tokens do not have a published maximum length, so I would discourage the use of a maximum length constraint.
