### ISSUE TITLE
Locking an item?

### ISSUE THREAD

**Issue by alfaunits** [OneDrive/onedrive-api-docs#932]
Can this (CheckOut an item) effectively be used as a LockFile() API? Since there are no other ways to do this properly.
Are there any limitations to using the file that is CheckedOut? Such as Delete/Rename not working, only one upload session, versions?

BTW, the API returns badStatus :(
"code": "BadRequest",
        "message": "Unsupported segment type. ODataQuery: users/adc4bbe0-9847-4fd7-9399-ecb7ba3aaca0/drive/items/01R5BNNTYTJKLSC5X6KFD2G4ZDU6Y262SM/checkout",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e96e772-005a-c84c-41c0-3bd20f629b34
* Version Independent ID: 6b1ac10f-2d0f-0471-68c8-5f241b70592f
* Content: [Check Out Files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_checkout?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_checkout.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_checkout.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Could you please provide more information about the request that failed? Is the request for OneDrive Personal or OneDrive for Business/SharePoint?  Though the Graph endpoint? The following response headers would also be helpful if they are available: 
 - Date (in UTC, please)
 - request-id
 - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by alfaunits** [comment]
This is the POST request I made:
https://graph.microsoft.com/v1.0/me/drive/items/01H5LCHRBJRMIBXMR4JBHZ2ZDRO2TO46OV/checkout

The result:

{
    "error": {
        "code": "BadRequest",
        "message": "Unsupported segment type. ODataQuery: users/ba4b6ed4-9248-4e5b-8377-a863dee73556/drive/items/01H5LCHRBJRMIBXMR4JBHZ2ZDRO2TO46OV/checkout",
        "innerError": {
            "request-id": "76102e7d-2f90-4230-b1c4-ecf6044eedd0",
            "date": "2018-11-03T12:53:58"
        }
    }
}

**Comment by blackmamba7** [comment]
Any update on this? I'm getting the same error for the request.

**Comment by chackman** [comment]
This API is currently only documented for the beta version of Microsoft Graph:
   https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/driveitem_checkout
Therefore, if using Microsoft Graph, specify the beta version by replacing “/v1.0/” with “/beta/”.

**Comment by alfaunits** [comment]
Hmm, I saw it hete:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_checkout?view=odsp-graph-online

So, this is a beta API, with no guarantees that it will exist even?

**Comment by chackman** [comment]
Generally speaking, beta API's are subject to change (and generally are in beta for a period of time to get feedback).  I'll make sure we have an internal tracking item about this API.

Going back to the original question, in SharePoint/OneDrive for Business, one limitation is that users with appropriate permissions can forcefully check in files that another user has checked out.

**Comment by chackman** [comment]
For the associated issue about publishing the Graph API to v1.0, we're tracking this internally.
I'll close out this item since we don't provide an official "Lock File" API and the checkout API has some differences, including mentioned earlier.
