### ISSUE TITLE
Renaming/moving a folder with a lot of files can time out

### ISSUE THREAD

**Issue by alfaunits** [OneDrive/onedrive-api-docs#933]
#### Category
- [X] Question
- [ ] Documentation issue
- [X] Bug

If a folder on OneDrive has a lot of files (it appears than several thousand is more than enough, and even several hundred makes the issue appear), a rename request will timeout on the first attempt, report several accessDenied (item is locked out for editing), but succeed eventually. The amount of retries required depends on the number of items.

The problem? The first rename request will time out after ~10seconds, and return a Bad Request 504 error. If I do not issue another rename request, the rename will not eventually appear, but even if it did, I would not know when it does without refreshing.
If the folder is large enough, the second rename will receive accessDenied 423 error, one or more times (I have seen it returned >20 times for a folder with >50K items).

#### Expected or Desired Behavior

Since a rename/move is a fairly fast operation, a fast response is expected :) And a timeout is not expected!

#### Steps to Reproduce

Create a folder with a LOT of subitems (need not be files, it can be 10.000 folders)
Rename the item, via API (UpdateItem API), regardless of whether the rename is a simple rename, a move, or a rename+move.

Thank you.

**Comment by chackman** [comment]
Could you please provide more information? Does this affect OneDrive for Business or OneDrive Personal? Please provide correlation ID, date, etc., as requested.
Renames/moves can unfortunately be expensive in some cases, but it seems weird to return a BadRequest error back to the client.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
