### ISSUE TITLE
Stale state when delta sync after rename/delete

### ISSUE THREAD

**Issue by alfaunits** [OneDrive/onedrive-api-docs#934]
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

The delta sync should give the most current state, and not a state before renames/deletes (possibly even creates)

#### Observed Behavior

(do let me know if any specific headers are required)
If a delta sync is requested, shortly after a delete/rename is done (approximaltey 2-3 seconds before the delta is requsted), we will get a stale state of the drive.

#### Steps to Reproduce
The following are TWO separate scenarios that can exhibit the issue:
1. rename X.dat -> Xn.dat 
2. rename Xn.dat ->X.dat
3. rename X.dat -> Xn.dat 
If we try to synchronize between 2 and 3, almost always, we will get a sync that says "rename x.dat -> Xn.dat", which is incorrect, as the Xn.dat->X.dat already occurred. A new sync will get the next rename, so we would get the proper data, but this means the sync presents stale data.
Between 1 and the sync, 2-4 second can occur (not more or less, otherwise either we get no sync data, or proper sync data).
An easy way to mimic this is to have a file system filter which synchronizes renames on a local drive to the OneDrive (synchronously, not async!) and a batch file which renames the files back and forth.

**Comment by chackman** [comment]
Could you please clarify whether the data returned by the delta API is correct, after waiting for a short period of time?

**Comment by alfaunits** [comment]
Yes, it is.

**Comment by chackman** [comment]
The delta sync may not be immediately consistent, but it is expected to be consistent in a short period of time.

We would expect, however, that a notification from the service (like a webhook) should follow a change in delta.  If after the final webhook notification, delta is not current, please reopen the issue.
