### ISSUE TITLE
Delta link is not listing changes when external link or company link is removed from file/folder.

### ISSUE THREAD

**Issue by puneettrehan** [OneDrive/onedrive-api-docs#937]
Steps to reproduce 
1. have file( e.g FileA) on root of that user. 
2. Share that file with specific people. 
3. Use deltalink for user check and list the changes.
4. FileA does show up in changes. Capture the deltaLink which is returned in this response.
5. Remove external link from FileA and use the deltaLink received in Step4 and get response.
6. No change is listed in this flow.

Expected behavior
1. Using deltaLink which we got in Step4, it should list fileA in changes as external link is removed from file.

**Comment by puneettrehan** [comment]
@ificator: I am from palo alto networks.

**Comment by puneettrehan** [comment]
@chackman Is there any update on this?

**Comment by chackman** [comment]
No update at the moment.

Could you clarify whether the application is using delegated/app+user or application-only permissions?
Also, The following response headers would also be helpful if they are available: 
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by chackman** [comment]
Thanks for the information so far; response headers would certainly be helpful when you can get them.

**Comment by chackman** [comment]
Hi @puneettrehan, could you let us know whether this issue has been addressed?
We believe this issue may be addressed, but would like to double-check before closing.
Thanks!
