### ISSUE TITLE
Overwrite flag for uploading

### ISSUE THREAD

**Issue by dannydan412** [OneDrive/onedrive-api-docs#94]
Hi,

In the Live SDK there was an option to specify an overwrite querystring to control the overwrite behavior:
"By default, the file, photo, video, or audio with the same name will be overwritten, if it already exists. You can add an overwrite query-string parameter with a value of false to not overwrite the existing file, photo, video, or audio. Or you can add an overwrite query-string parameter of ChooseNewName if you want to upload a duplicate copy of the file but let OneDrive choose a new file name for the uploaded file."
(source: https://msdn.microsoft.com/en-us/library/office/dn659726.aspx)

Is this also available in the new API? Otherwise there would have to be some overhead of checking if a file with the same name exists before uploading, which would mean an extra REST call.

**Comment by rgregg** [comment]
What you're looking for is the `@name.conflictBehavior` attribute, which lets you specify for a content upload what to do if a file with that same name already exists.

This is documented on the [Create](https://dev.onedrive.com/items/create.htm) API page, but works on any of the POST actions for uploading files.

**Comment by dannydan412** [comment]
Great, thank you. I take it that means I need to use the multipart upload and not the PUT method, correct?

**Comment by rgregg** [comment]
It works on PUT, but since there isn't a JSON body you have to move the parameter into the query string. Something like this:

`PUT /drive/root:/existing_file.txt:/content?@name.conflictBehavior=rename`

This will create `existing_file 1.txt` if `existing_file.txt` exists. This doesn't appear to be covered by our documentation right now, so I'll make sure we update that.

**Comment by dannydan412** [comment]
Thanks. Last question, would this work for large file upload as well?

**Comment by ankit-ankuagrawal** [comment]
@rgregg , ty for including @name.ConflictBehaviour in PUT upload api it solves one of my problem
because making multipart/related query in android is little bit tedious (due to lib we using)
