### ISSUE TITLE
OneDrive Personal throws "generalException" when handling filenames ending with "drive"

### ISSUE THREAD

**Issue by Cnly** [OneDrive/onedrive-api-docs#941]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

The API should work for the files whose names end with `drive` when they are addressed by their paths.

#### Observed Behavior

The query

```
GET /v1.0/drives/71a96798e7b1d253/root:/test/adrive
```

which is constructed according to the docs "By file system path using `/drive/root:/path/to/file`"

returns

```
{
  "error": {
    "code": "generalException",
    "message": "Could not find a property named 'quota' on type 'oneDrive.item'.",
    "innerError": {
      "request-id": "7001728a-4c8d-48d6-96cc-3dfc31de0d18",
      "date": "2018-11-03T16:49:46"
    }
  }
}
```

However, if a trailing colon is added to the original query:

```
GET /v1.0/drives/71a96798e7b1d253/root:/test/adrive:
```

it returns the correct DriveItem.

The date and request ID can be found in the response data sample above, and it seems this only happens for OneDrive Personal.

#### Steps to Reproduce

This bug can be reproduced by the following steps:

1. In OneDrive Personal, create a folder ending with `drive`, for example `adrive`.
1. Send the request `GET /v1.0/me/drive/root:/path/to/adrive:` to confirm the item exists
1. Send the request `GET /v1.0/me/drive/root:/path/to/adrive` to see the `generalException`

This is a summary of a bug from rclone. The original discussions can be found on the rclone [forum](https://forum.rclone.org/t/onedrive-could-not-find-a-property-named-quota-on-type-onedrive-item/7403/6) and in the rclone [issue](https://github.com/ncw/rclone/issues/2720).

**Comment by chackman** [comment]
Thanks for the feedback, this looks like a bug and I'll track it as such.

**Comment by chackman** [comment]
We will need to follow up with the Graph team about this.
In the meantime, you can work around the issue by appending a ':' to the end of the path.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
