### ISSUE TITLE
No email filed in userInfo

### ISSUE THREAD

**Issue by kemike** [OneDrive/onedrive-api-docs#942]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x ] Bug

#### Expected or Desired Behavior
Get user info via https://graph.microsoft.com/v1.0/me with Authorization header: bearer authToken. See steps for full flow (implicit).

Expected result:
JSON object with valid "mail" field.

#### Observed Behavior
JSON object with "mail" field with null value. 
However the "userPrincipalName" filed has the expected email.

I tried the steps with multiple OneDrive accounts. I get the account object buth in every case the "mail" field is null while "userPrincipalName" is the expected email address.

#### Steps to Reproduce
1. get code via https://login.microsoftonline.com/common/oauth2/v2.0/authorize with ['user.read'] scope
2. get authToken via https://login.microsoftonline.com/common/oauth2/v2.0/token
3. get user info via https://graph.microsoft.com/v1.0/me with Authorization header: bearer authToken

Thank you.

**Comment by chackman** [comment]
@kemike, thanks for your feedback, but this is neither a OneDrive nor SharePoint API issue.  Could you please ask this question in the Microsoft Graph StackOverflow? See https://developer.microsoft.com/en-us/graph/support for more information.
