### ISSUE TITLE
accessToken and endpointHint for https://[mycompany].sharepoint.com/Shared%20Documents

### ISSUE THREAD

**Issue by nhopp** [OneDrive/onedrive-api-docs#943]
Using v7.2 of the Javascript FilePicker API to open the OneDrive FilePicker with an existing accessToken, and endpointHint. The ACCESS_TOKEN is retrieved from a backend service and the user has not logged into Sharepoint from the existing browser.

```
            let odOptions = {
                clientId: [CLIENT_ID]",
                action: "download",
                advanced: {
                    accessToken: [ACCESS_TOKEN],
                    endpointHint: "https://[MY_COMPANY].sharepoint.com/Shared%20Documents"
                },
                success: function (files) {
                    console.info("OneDrive.open() success: " + files);
                },
                cancel: function() {
                    console.info("OneDrive.open() cancelled");
                },
                error: function(e) {
                    console.error("OneDrive.open() error: " + e);
                }
            };

            window.onedrive_enable_logging = true;
            OneDrive.open(odOptions);
```

The OneDriveSDK prints out the following lines and opens the popup forcing the user to go through the OAuth flow.

> [OneDriveSDK] open started []
> OneDrive.debug.js:1665 [OneDriveSDK] parsed client id: f61901d3-1d59-4e33-ab4b-34d6bcb0598e []
> OneDrive.debug.js:1665 [OneDriveSDK] invoke picker with url: https://[MY_COMPANY].sharepoint.com/Shared%20Documents?p=2&picker=%7B%22aid%22%3A%22[CLIENT_ID]%22%2C%22a%22%3A%22read%22%2C%22id%22%3A%22RQmRA%22%2C%22ln%22%3Atrue%2C%22s%22%3A%22single%22%2C%22v%22%3A%22files%22%2C%22ru%22%3A%22[REDIRECT_URL]%22%2C%22o%22%3A%22[CALLING_HOST]%22%2C%22sdk%22%3A%227.2%22%2C%22sn%22%3Atrue%2C%22ss%22%3Atrue%7D 
> 

Debugging through OneDrive.Debug.js it does not appear that the accessToken provided in is used in odOptions.advanced is used when opening the popup using the endpointHint.

The token can be verified against
```
curl -X GET \
  https://graph.microsoft.com/v1.0/me \
  -H 'Authorization: Bearer [ACCESS_TOKEN]' 
```

The token has the required read roles:
>  "scp": "Files.Read Files.Read.All offline_access User.Read"

Is using the accessToken to bypass the OAuth flow and open the OneDrive FilePicker directly supported if the user has not already logged into Sharepoint in the current browser?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by nhopp** [comment]
@KevinTCoughlin in a related question. Given an access token is there any way to determine the "Shared Documents" endpointHint? If someone has signed into my app and linked their account, how can I determine the endpoint hint, or is that something the user would have to supply?

**Comment by GeBeater** [comment]
@KevinTCoughlin Is there meanwhile a way to bypass the OAuth flow when providing an access token?

**Comment by ashrafteleb** [comment]
Hi, any hope that we can open a the file picker with an existing accessToken. Also, why should I provide an endpointHint if all I need is the same file picker that is opened via direct user auth.

Thanks

**Comment by Penspinner** [comment]
@KevinTCoughlin Are there any updates on this issue?

**Comment by etyp** [comment]
Also stuck on this -- @KevinTCoughlin any idea what kind of timeline to expect or if there are any potential workarounds?

**Comment by ldcm3** [comment]
Hey @KevinTCoughlin, I have an issue that I guess it's related to this one.

When using the root company folder as endpointHint hint for Sharepoint (i.e https://test.sharepoint.com/Shared%20Documents/) users will not be able to see files on other /sites/ even when they have access and can see the sites on the left view (see picture).

![screen shot 2019-01-22 at 4 03 08 pm](https://user-images.githubusercontent.com/12711137/51548292-f99c3080-1e5f-11e9-8475-4113dee6110d.png)

This issue doesn't happen when setting endpointHint to any other site (even those where the user is not a member).

I am opening the picker similar to:

``  OneDrive.open({
    clientId: clientID,
    action: 'query',
    advanced: {
      accessToken: accessToken,
    endpointHint: "https://test.sharepoint.com/Shared%20Documents/",
     },
    multiSelect: true,
    success: onSuccess,
    error: onError,
    cancel: onCancel,  });
}

**Comment by KevinTCoughlin** [comment]
To answer @nhopp's original question in this issue:

>Is using the accessToken to bypass the OAuth flow and open the OneDrive FilePicker directly supported if the user has not already logged into Sharepoint in the current browser?

Currently, the `accessToken` parameter _will not allow_ you to bypass the authentication of the hosted page. The File Picker configuration option _is misleading_. It only allows you to bypass the OAuth flow for the SDK wrapper itself.

---

I've spoken with colleagues that manage the hosted (framed) page to see if it is possible or a workaround is available to us in the short-term. Unfortunately it is not possible in the short-term. The explanation is as follows:

The hosted page is secured by cookie auth so an OAuth token will not allow you to bypass that flow. The cookie authentication is the reason why a user is prompted to auth in a browser they have not previously visited the page's host with.

Looking forward, we are discussing ways to support bypassing the authentication flow for the File Picker. That work is a larger effort without a concrete ETA as of today, but a need we understand and would like to meet. 

---

For the separate issues raised in this thread, please recreate them as individual issues so we can triage appropriately. 

I'm considering modifying the documentation to be explicit regarding `accessToken` and open to suggestions.

cc: @ThomasMichon @aditima @Penspinner @etyp @GeBeater

**Comment by GeBeater** [comment]
@KevinTCoughlin Thanks for the explanation and too bad it's not possible.

**Comment by Penspinner** [comment]
@KevinTCoughlin Is there a way for us to get notified when a solution has been implemented? Can you comment on this issue, or is there a way for us to get an email about it?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin Is there a way for us to get notified when a solution has been implemented? Can you comment on this issue, or is there a way for us to get an email about it?

I can tag the interested parties in an issue tracking the work once its been planned for and signed-off on. It is a large body of work relative to other Picker asks as it involves coordination with the hosted page and auth teams.

**Comment by ajwhalen5** [comment]
Hi @KevinTCoughlin we're still facing this issue with our integration here at Percolate. I see you've closed the issue. Are there plans to re-open and address this request? @Penspinner

**Comment by JonathanBruce** [comment]
@KevinTCoughlin this should be re-opened or I can open a new issue linking this issue.

**Comment by r-a-y** [comment]
We're also wondering what the status on bypassing the authflow is with a generated access token.

In the meantime, I would strongly recommend removing the `accessToken` parameter on the [JS File Picker page](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online) since it leads us into believing that an access token can bypass the authentication flow. This would save developers many hours of time troubleshooting something that doesn't work as advertised.
