### ISSUE TITLE
The sender received a very strange NDR

### ISSUE THREAD

**Issue by Tomy-wang** [OneDrive/onedrive-api-docs#946]
Hi 

I followed this OneDrive and SharePoint via Microsoft Graph API to develop an Outlook plugin that sends large attachments; but the sender received an NDR with the subject "Your recipients couldn't be given access to the file". I can send emails in detail NDR. provide;
This problem has been plaguing me for a long time. Can you help me analyze it?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5be99838-ec0d-2d14-954e-4a6cff48096d
* Version Independent ID: bb52ff31-8e3d-122f-edbb-6b1cb3fde806
* Content: [Access OneDrive and SharePoint via Microsoft Graph API - OneDrive dev center](https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/?view=odsp-graph-online)
* Content Source: [docs/rest-api/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by Tomy-wang** [comment]
NDR sender:MicrosoftExchange329e71ec88ae4615bbc36ab6ce41109e@domain.com

NDR Subject：
Your recipients couldn't be given access to the file EXBCeYC_zbhBo1KV2WLCz5QBInb3qsijxug0wfABRxeoaw

NDR text:
The location where the file is stored isn't available.
The message was sent, but recipients might not be able to access the attachment.
Try opening the file EXBCeYC_zbhBo1KV2WLCz5QBInb3qsijxug0wfABRxeoaw and giving others access to it from its current location.

**Comment by chackman** [comment]
Could you please provide more information about how the file is being uploaded, and which service is being used to send the email?  For example, is the plugin uploading a file to OneDrive and then sharing it using the [invite API](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_invite) to share and send an invitation?
