### ISSUE TITLE
Sharepoint drive subscriptions do not work with multiple drives/libraries

### ISSUE THREAD

**Issue by thomasthejn** [OneDrive/onedrive-api-docs#947]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I have a Sharepoint site with multiple libraries/drives. 
I create a Microsoft Graph subscription for the root folder of each drive. 
I expect to get notifications on changes for each drive. 

#### Observed Behavior

I only get notifications from one of the drives.
The delta link returned include updates to both drives. 

#### Steps to Reproduce

(Some of the id's have been changed for security purpose ;-)

I try this query on https://developer.microsoft.com/en-us/graph/graph-explorer 

https://graph.microsoft.com/v1.0/sites/pindcloud.sharepoint.com,206a47b2-xxxxxxxxx-a34da3468374,57201aed-f09c-41e4-be3f-6e233769a4d5/drives

It returns this: 
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives",
    "value": [
        {
            "createdDateTime": "2017-11-16T10:34:02Z",
            "description": "",
            "id": "b!skdqIGdXIEmo8qNNo0aDdO0aIFec8ORBvj9uIzdppNVOUSZ1Sob3S6U-xytrer",
            "lastModifiedDateTime": "2018-11-24T12:38:14Z",
            "name": "Documents",
            "webUrl": "https://pindcloud.sharepoint.com/sites/testsite1/Shared%20Documents",
            "driveType": "documentLibrary",
            "createdBy": {
                "user": {
                    "displayName": "System Account"
                }
            },
            "owner": {
                "group": {
                    "email": "testsite1",
                    "id": "cdb607cb-a09a-4a13-89b4-erty5678",
                    "displayName": "test site 1"
                }
            },
            "quota": {
                "deleted": 0,
                "remaining": 0,
                "total": 0,
                "used": 0
            }
        },
        {
            "createdDateTime": "2018-11-18T15:17:20Z",
            "description": "Extra doc library",
            "id": "b!skdqIGdXIEmo8qNNo0aDdO0aIFec8ORBvj9uIzdppNWT96zWkSAZRKkijh8y9",
            "lastModifiedDateTime": "2018-11-24T12:37:20Z",
            "name": "Documents_2",
            "webUrl": "https://pindcloud.sharepoint.com/sites/testsite1/Documents_2",
            "driveType": "documentLibrary",
            "createdBy": {
                "user": {
                    "email": "thomas@salesvalue.net",
                    "id": "6cce8a73-b5ab-4a41-aced-f62d328ghjg",
                    "displayName": "Thomas Thejn"
                }
            },
            "lastModifiedBy": {
                "user": {
                    "email": "thomas@salesvalue.net",
                    "id": "6cce8a73-b5ab-4a41-aced-f62d32ghjgj67",
                    "displayName": "Thomas Thejn"
                }
            },
            "owner": {
                "group": {
                    "email": "testsite1",
                    "id": "cdb607cb-a09a-4a13-gajhg77-1aff138a59b0",
                    "displayName": "test site 1"
                }
            },
            "quota": {
                "deleted": 0,
                "remaining": 0,
                "total": 0,
                "used": 0
            }
        }
    ]
}

It returns the 2 sub OneDrives

Then we create a subscription for each OneDrive with:
POST https://graph.microsoft.com/v1.0/subscriptions
Content-type: application/json

{
   "changeType": "created,updated",
   "notificationUrl": "https://app.salesvalue.net/webhooks",
   "resource": "drives/b!skdqIGdXIEmo8qNNo0aDdO0aIFec8ORBvj9uIzdppNWT96zWkSAZRKkijh8y9/root",
   "expirationDateTime":"2016-11-20T18:23:45.9356913Z",
   "clientState": "secretClientValue"
}

And

POST https://graph.microsoft.com/v1.0/subscriptions
Content-type: application/json

{
   "changeType": "created,updated",
   "notificationUrl": "https://app.salesvalue.net/webhooks",
   "resource": "drives/ b!skdqIGdXIEmo8qNNo0aDdO0aIFec8ORBvj9uIzdppNVOUSZ1Sob3S6U-xytrer/root",
   "expirationDateTime":"2016-11-20T18:23:45.9356913Z",
   "clientState": "secretClientValue"
}

But we only receive notifications from one of them afterwards. But the delta link includes updates from both drives. I have seen the same behavior with other Office 365 accounts.

**Comment by chackman** [comment]
Thanks for your feedback; could you please provide request ID's (and date/time in UTC) for changes that you did not get notifications for?

**Comment by thomasthejn** [comment]
I found the issue on my end. It was due to me sending wrong subscription requests. I am closing the issue here.
