### ISSUE TITLE
OneDrive returns 504 Gateway Timeout when trying to list a directory with 100,000+ files

### ISSUE THREAD

**Issue by Cnly** [OneDrive/onedrive-api-docs#948]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

OneDrive API should return a listing even for a directory with 100,000+ files.

#### Observed Behavior

The query

`GET /v1.0/drives/<DRIVE_ID>/items/<ITEM_ID>/children?$top=1000`

(where the item referred to is a directory with more than 100,000 files) returns

```
HTTP/1.1 504 Gateway Timeout
Transfer-Encoding: chunked
Cache-Control: private
Client-Request-Id: be69783e-baaa-4723-9bd6-7d61514815f9
Content-Type: application/json
Date: Thu, 25 Oct 2018 07:47:51 GMT
Duration: 20007.1818
Request-Id: be69783e-baaa-4723-9bd6-7d61514815f9
Strict-Transport-Security: max-age=31536000
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"3","ScaleUnit":"003","Host":"AGSFE_IN_50","ADSiteName":"NEU"}}


{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "be69783e-baaa-4723-9bd6-7d61514815f9",
      "date": "2018-10-25T07:47:51"
    }
  }
}

```

(Did not see anything similar to `SPRequestGuid` in the log)

#### Steps to Reproduce

1. Create a directory with more than 100,000 files
1. Send the request `GET /v1.0/drives/<DRIVE_ID>/items/<ITEM_ID>/children?$top=1000` trying to get a listing for that directory

This is a summary of a bug report in rclone. The original GitHub issue can be found [here](https://github.com/ncw/rclone/issues/2707) and forum post [here](https://forum.rclone.org/t/error-reading-destination-directory/7316).

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback.
Just to be clear, is this consistently happening?  Also could you please provide an updated request-id and date?  The more recent the date, the better the chance that we would have to look closer.

**Comment by git-anish** [comment]
> Thanks for your feedback.
> Just to be clear, is this consistently happening? Also could you please provide an updated request-id and date? The more recent the date, the better the chance that we would have to look closer.

Hey, how many files per folder does OneDrive or OneDrive for Business currently support?

I'm trying to migrate from my Google Drive archives some of which have 400k files per folder, would I have an issue uploading them to OneDrive for Business?
