### ISSUE TITLE
One drive API never return

### ISSUE THREAD

**Issue by EasonWang01** [OneDrive/onedrive-api-docs#949]
<img width="1242" alt="2018-11-29 9 22 36" src="https://user-images.githubusercontent.com/11001914/49224682-00d52e00-f41d-11e8-99ef-331a8dfb6f4c.png">
<img width="904" alt="2018-11-29 9 21 49" src="https://user-images.githubusercontent.com/11001914/49224684-03378800-f41d-11e8-98d7-df0c3ff0cbfa.png">

**Comment by JValck** [comment]
Please provide decent information.
Describe the problem. What is going wrong? What is the endpoint?

**Comment by EasonWang01** [comment]
After login again this issue solved, oneDrive and Azure usually gas this kind of login redirect issue.
