### ISSUE TITLE
Insert your client ID here

### ISSUE THREAD

**Issue by vssaran** [OneDrive/onedrive-api-docs#950]
Hi

I' getting an error while connecting to onedrive
 
**Sign in 

Sorry, but we’re having trouble signing you in.
 
AADSTS700016: Application with identifier 'Insert your client ID here' was not found in the directory '94c3e67c-9e2d-4800-a6b7-635d97882165'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.**

 Can anyone help me to resolve this issue.

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback, but this is neither a OneDrive nor SharePoint API issue. Could you please ask this question in StackOverflow?  https://stackoverflow.com/questions/tagged/azure-active-directory
