### ISSUE TITLE
Property folder in payload has a value that does not match schema

### ISSUE THREAD

**Issue by uthpala1000** [OneDrive/onedrive-api-docs#953]
the graph API request to create a folder in one drive is

   POST /me/drive/root/children
   Content-Type: application/json

    {
      "name": "New Folder",
      "folder": { },
      "@microsoft.graph.conflictBehavior": "rename"
    }

My code:

 var tt = "{ }";
var jsonData = $@"{{ ""name"": ""{txtValue}"",""folder"":""{tt}""}}";
var body = new StringContent(jsonData, Encoding.UTF8, 
"application/json"); 
apiRequest.Content = body;
apiRequest.Headers.Accept.Add(new 
MediaTypeWithQualityHeaderValue("application/json"));
HttpResponseMessage response = await httpClient.SendAsync(apiRequest);
string d = response.Content.ReadAsStringAsync().Result.ToString();
but gives the error ""code": "BadRequest","message": "Property folder in payload has a value that does not match schema.","

anybody have any idea ?

**Comment by bhargav-devgit** [comment]
> "@microsoft.graph.conflictBehav

Hope this Finds you People in Good Cheer ! Can you Please Tell Me how to give Proper Value for Folder Property, in PHP.
