### ISSUE TITLE
Unable to create a drive item in deeply nested folders

### ISSUE THREAD

**Issue by JValck** [OneDrive/onedrive-api-docs#954]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
When creating a new `DriveItem` in a submap that is more than 10 level deep (started from the root), the endpoint should create a new `DriveItem` and return the created one.

#### Observed Behavior
When creating a new `DriveItem` (folder or file) in a submap that is more than 10 level deep (started from the root), the endpoint will return an `400` response:
```
{
    "error": {
        "code": "invalidRequest",
        "message": "One of the provided arguments is not acceptable.",
        "innerError": {
            "request-id": "49763835-4e66-4f35-bbee-536900993f77",
            "date": "2018-12-05T16:28:32"
        }
    }
}
```

#### Steps to Reproduce
1. Create a drive with a 11 level deep map structure (`A/B/C/D/E/F/G/H/I/J/`)
2. Try to create an item in the 11th level (`J`)
3. The endpoint will now return a `400` response

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
