### ISSUE TITLE
Add documentation for photo albums

### ISSUE THREAD

**Issue by paule96** [OneDrive/onedrive-api-docs#955]
Hi there,

please add documentation for the album function in OneDrive. Because there are some issues for this point.

#468 
#579 
#909 

Thanks to @ksmutny and his issue #909  here I have find a solution that work for me. But this was not an easy way.

I hope we can setup fast this points for the documentation:

- get a list of all Albums
- get media in an album
- create an album
- delete an album
- add media to an album

**Comment by suprak** [comment]
This uses the graph api, any way to do it using the onedrive api instead?

**Comment by williamhaley** [comment]
Just noticed the (beta) graph API appears to have an example for creating an album https://docs.microsoft.com/en-us/graph/api/drive-post-bundles?view=graph-rest-beta&tabs=http#example-2-create-an-album

Not part of the onedrive API, I know, but maybe helpful for anyone like me trying to understand *any* way to create an album within OneDrive.

**Comment by hanpq** [comment]
Add item to bundle according to docs at [graph api docs](https://docs.microsoft.com/en-us/graph/api/bundle-additem?view=graph-rest-beta&tabs=http) does not seem to work. I do get a "204 No Content" respons as expected according to the docs but nothing gets added to the album. Adding the file manually via gui works so nothing wrong with the file. I use the file id from a https://graph.microsoft.com/v1.0/me/drive/items/<folderid>/children call.

Anybody tried this and got it to work?

**Comment by TCPcloudDEV** [comment]
@paule96 

the "0:/SkyDriveCache/Albums:" is still works for albums. Do you know id for places?

thanks

**Comment by sorgeas** [comment]
Hello, I'm also interested in getting the photo places, and adding an item to an album. Any update on these topics ?

**Comment by paule96** [comment]
@TCPcloudDEV I'm sorry. All I know I have written down here, in the hope someone from MS will bring the missing parts together and release them in the documentation.

But what I can tell you, the graph API is an OData API. So you can read the Metadata document. (https://graph.microsoft.com/v1.0/$metadata)

This document gives you a definition of all endpoints and what types those endpoints return/accept.

So with some research, you can find the things you want to do. I'm sure. 
And if you are good to the community you write it here down 🤷‍♀️ "Lets moves the docs.com to this discussion" :D I'm sorry that is all I can do now, because it's for me also only a side project. (or it was. You know, one of the half-dead hobby projects, that will never be finished)

If you are not familiar with OData (btw. it's the best type of Web API ;) ) you can play a little bit with the official [tutorial](https://www.odata.org/getting-started/basic-tutorial/). For a more detailed understanding, you can look in the [specification](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html). (it's easy to ready. It's only long, but has a ton of samples.)

**Comment by pgn666** [comment]
Hi, had anyone figured out how to get OneDrive photo "tags" (available on web under url: https://onedrive.live.com/?v=photos&id=tags)

**Comment by TCPcloudDEV** [comment]
no, I did not ... submitted idea on Microsoft 365 Developer Platform

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/api-to-get-onedrive-photo-tags/idi-p/3057776

please vote or add comment there

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
