### ISSUE TITLE
I think you should mention that the name with special characters are not supported.

### ISSUE THREAD

**Issue by lockelost** [OneDrive/onedrive-api-docs#956]
for ex, we can not pass 'file-copy(2).txt' as a name to this request.
And can you also provide the walk-around for this issue? Like escaping some characters, or upload it with temporary name and rename it later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350cd850-d19a-ef5c-2761-e342fc3c506c
* Version Independent ID: 5bf3ef39-f20a-6c7f-77f6-3bc7e9d246f4
* Content: [Upload small files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_put_content.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_put_content.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by chackman** [comment]
Could you please provide a sample request and the following response headers for the failed request: 
 - Date (in UTC, please)
 - request-id
 - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by chackman** [comment]
Thanks for your feedback.

The URL specified above, notably the use of the parentheses, makes this an invalid OData URL.

There are a couple of options, including:
- As mentioned in issue #565, you could pass the file name in as a function argument, like so:
  https://graph.microsoft.com/v1.0/me/drive/items/{item-id}/children('txt_(2).txt')/content
- You can also use the path/filename syntax ([example](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online#example-upload-a-new-file)) as follows:
  https://graph.microsoft.com/v1.0/me/drive/root:/foldername/txt_(2).txt:/content

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
