### ISSUE TITLE
404 for get file content with special characters

### ISSUE THREAD

**Issue by mdybich** [OneDrive/onedrive-api-docs#957]
We are using Rest API to download files from the OneDrive storage ( `/content` endpoint). It works perfectly fine for normal files, but when there are special characters in the file name we are getting 404 error. It is only for `/content` endpoint, we are able to get the details of that file using https://docs.microsoft.com/pl-pl/onedrive/developer/rest-api/api/driveitem_get?view=odsp-graph-online endpoint.
About month ago everything was ok.

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Expected response:  `302 Found`

#### Observed Behavior

Observed response: `404 Item not found`

#### Steps to Reproduce

File name: `!@#$%^&()_+{}[];',.=-+ (1) (1) (1) (1).txt`

Encoded file name: `!%40%23%24%25%5E%26()_%2B%7B%7D%5B%5D%3B'%2C.%3D-%2B%20(1)%20(1)%20(1)%20(1).txt`

Get content endpoint url: 
`https://graph.microsoft.com/v1.0/drives/{driveId}/root:/Folder/HELLO/!%40%23%24%25%5E%26()_%2B%7B%7D%5B%5D%3B'%2C.%3D-%2B%20(1)%20(1)%20(1)%20(1).txt:/content`

Response for content endpoint: `404`

Get item endpoint url:
`https://graph.microsoft.com/v1.0/drives/{driveId}/root:/Folder/HELLO/!%40%23%24%25%5E%26()_%2B%7B%7D%5B%5D%3B'%2C.%3D-%2B%20(1)%20(1)%20(1)%20(1).txt:/`

Response for get item endpoint: `200`

**Comment by chackman** [comment]
Could you please provide the following response headers for the 200 and the 404 responses: 
 - Date (in UTC, please)
 - request-id
 - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by mdybich** [comment]
@chackman 

Headers for 200 response:
Date: `Mon, 17 Dec 2018 15:10:20 GMT`
request-id: `eb5a69d6-2181-4358-a66d-7be5aa9cde55`

Headers for  404 response:
Date: `Mon, 17 Dec 2018 15:14:15 GMT`
request-id: `43dd61b9-41d9-4539-8459-7ae1461648f7`

**Comment by chackman** [comment]
Thanks, we'll investigate.

**Comment by mdybich** [comment]
@chackman any update on that?

**Comment by chackman** [comment]
Thanks for your patience.  We have a prospective root cause on the issue, and are working on a fix.

**Comment by mdybich** [comment]
@chackman do you know how long do we need to wait for a fix?

**Comment by mdybich** [comment]
Looks like it's fixed now. Thank you for taking care of that.
