### ISSUE TITLE
Optional query parameters do not seem to be honored when getting default drive metadata

### ISSUE THREAD

**Issue by paya-cz** [OneDrive/onedrive-api-docs#96]
For the following request:

> GET https://api.onedrive.com/v1.0/drive?select=id

I get a response with `driveType`, `owner` and `quota` properties, even though my request explicitly states my interest in `id` only. The documentation says ([ref1](https://dev.onedrive.com/drives/default.htm), [ref2](https://dev.onedrive.com/drives/get.htm)) that optional query parameters ARE supported for `Drive` resource response. Documentation on [optional query parameters](https://dev.onedrive.com/odata/optional-query-parameters.htm) state that the `select` query is available only for `Item` resources, but I do not see what other query parameters would make any sense for `Drive` resource.

Is this just some kind of future-proofing, in a sense that optional query parameters are supported for `Drive` resource in general, but there are simply no query parameters available yet for that resource type?

**Comment by ificator** [comment]
This is definitely a bug on our side, good catch!

**Comment by ificator** [comment]
This should now be fixed! Please let us know if you still see issues.
