### ISSUE TITLE
Call was made to default drive

### ISSUE THREAD

**Issue by Ady321** [OneDrive/onedrive-api-docs#965]
when i m calling in microsoft graph explorer

https://graph.microsoft.com/v1.0/users/{userEmail}/drive/root/delta?$select=id

or

https://graph.microsoft.com/v1.0/users/{userEmail}/drive/root/delta?$token=latest

it throwing

"error": {
"code": "invalidRequest",
"message": "Call was made to the default drive, which is not supported for apponly tokens.",
"innerError": {
"request-id": "18bfc97d-f38d-42f5-ba29-1b7ffe7d856a",
"date": "2018-12-13T10:33:59"
}
}

for some users above query works fine and for some users it is not working
how to resolve this issue if any one having idea please let me know

**Comment by chackman** [comment]
Thanks for your feedback.
Could you please provide more information about successful calls?
Are those calls also going through Graph Explorer?

**Comment by Ady321** [comment]
@chackman any information you got about the issue

**Comment by kevklam** [comment]
There are a couple layers to this:
1) Graph is unable to automatically provision a user's mysite using app-only authentication
2) There was a bug on Graph end that broke app-only requests to /users/{user}/drive altogether.

The 2nd issue has been fixed and should be rolling out soon if it hasn't already. However I do not know of any plans to support auto provisioning user mysites with app-only.
