### ISSUE TITLE
Types of actions "open file locally"

### ISSUE THREAD

**Issue by bguyb** [OneDrive/onedrive-api-docs#967]
Types of actions "open file locally"

Is there an option to open the file from the local onedrive folder?
It's one of the options in the onedrive website...

https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#types-of-actions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a64e9d-ae15-46a4-4a4d-3674972d9806
* Version Independent ID: 744d6f1a-4cde-b9aa-4003-209d1d4a527b
* Content: [Open from OneDrive in JavaScript - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/open-file.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/open-file.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by KevinTCoughlin** [comment]
> 
> 
> Types of actions "open file locally"
> 
> Is there an option to open the file from the local onedrive folder?
> It's one of the options in the onedrive website...
> 

@bguyb, can you expand further on the use-case above? I'd need to double-check, but I believe the File Picker requires the resource URIs be http(s) protocol, not `file://`. However, I would like to better understand your end-goal.

**Comment by KevinTCoughlin** [comment]
@bguyb polite ping

**Comment by bguyb** [comment]
Hi kevin
I'm looking for a way to open a file (from one drive folder) locally (without the need to download the file first).
Using the API or the JS SDK.

**Comment by KevinTCoughlin** [comment]
> Hi kevin
> I'm looking for a way to open a file (from one drive folder) locally (without the need to download the file first).
> Using the API or the JS SDK.

You may consider using a OneDrive Embed for this scenario: https://support.office.com/en-us/article/embed-files-directly-into-your-website-or-blog-ed07dd52-8bdb-431d-96a5-cbe8a80b7418.

Unfortunately due to technical reasons this will not work with the Picker. Even the embed will require the browser to download the web content hosting the file stored on OneDrive.
