### ISSUE TITLE
`generalException` when uploading files with specific name to OneDrive for Business

### ISSUE THREAD

**Issue by Cnly** [OneDrive/onedrive-api-docs#968]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

The problem is with a file named `2016_06_01_000002_create_oauth_access_tokens_table.php`. OneDrive for Business should have no problem with this file.

#### Observed Behavior

Uploading data into the file named `2016_06_01_000002_create_oauth_access_tokens_table.php` via the `uploadUrl` returned by `createUploadSession` causes `HTTP/1.1 401 Unauthorized` with body `{"error":{"code":"generalException","message":"General exception while processing"}}`.

Some headers returned with the `401`:

```
Date: Sat, 22 Dec 2018 18:16:18 GMT
Sprequestguid: eb94ae9e-4011-7000-725f-e1fa9d297fd5
Request-Id: eb94ae9e-4011-7000-725f-e1fa9d297fd5
```

#### Steps to Reproduce

1. `POST /v1.0/drives/b!<REDACTED>/root:/2016_06_01_000002_create_oauth_access_tokens_table.php:/createUploadSession` to create an upload session for the file
1. `PUT` any data into the file via the `uploadUrl` returned by the previous query

This is a summary of an issue for rclone; the original post can be found here: https://github.com/ncw/rclone/issues/2859

Thank you.

**Comment by ificator** [comment]
This issue should now be resolved - please let us know if you're still seeing issues.

**Comment by Cnly** [comment]
No problem now. Thank you!
