### ISSUE TITLE
Retrieving thumbnails with a Share Link through File Picker Javascript SDK

### ISSUE THREAD

**Issue by woodsba** [OneDrive/onedrive-api-docs#969]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

I am not sure really if this is a bug, or something that I am missing. But I have followed the documentation for the File Picker JavaScript SDK here: https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online and everything is working great, except that their is no thumbnails returning with the Response object

My code for creating the picker is as follows:
```
function launchOneDrivePicker(){
var odOptions = { 
		clientId: {oneDriveKey},
		action: "share",
		multiSelect:false,
		advanced:{
			redirectUri: {custom landing uri},
			createLinkParameters: { type: "view", scope: "anonymous" }
		},
		success: function(files) { console.log(files); },
		cancel: function() { /* cancel handler */ },
		error: function(e) { console.log(e); },
		sourceTypes: "Sites"
    };
    OneDrive.open(odOptions);
}
```
I am not sure if it is because I am using my personal onedrive account for the testing or what, but the only portion I have been unable to get working is the returning of the thumbnails.

The goal that we are trying for is to allow the user to upload to/share from their OneDrive accounts and attach it to what is basically a blog article, with a thumbnail preview of the OneDrive file.

I could not find anything in the documentation pointing to what I am missing, if you could please help that would be appreciated

**Comment by woodsba** [comment]
As A follow up I came up with a temporary solution of adding an ajax request to the API inside of the Success function of the odOptions Object see below:

```
success: function(files) {
	$.ajax({
		url:files.apiEndpoint+'/me/drive/items/'+files.value[0].id+'/thumbnails',
		headers: {"Authorization": 'bearer '+files.accessToken},
		error:function(data){console.log(data);},
		success:function(data){ console.log(files, data); }
	});
}
```
But this feels like it is a hack when the documentation made it seem like I should have had the thumbnails in the files object returned when the file was selected in the popup.

**Comment by KevinTCoughlin** [comment]
@woodsba you're correct that the documentation leads one to believe that thumbnails will be returned _at least_ for image and video file types if not more. It will require additional time to investigate this issue and potentially provide a fix.

I'm glad you have a workaround in the interim. I will keep you posted.

**Comment by fatboystring** [comment]
Hi, is there any update on this issue please?  It's affecting an integration of ours as well.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
