### ISSUE TITLE
[OAuth] Is possible to migrate app from AAD or MS account to Graph?

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#971]
Hi all,

Now we have three ways to get access token from One Drive service

1.graph
- APP registered in Microsoft App Registration Portal
- GET https://login.microsoftonline.com/common/oauth2/v2.0/authorize...

2.AAD 
- APP registered in Azure AD
- GET GET https://login.microsoftonline.com/common/oauth2/authorize...

3.MS account (Live SDK)
- APP registered in Microsoft App Registration Portal -> The Live SDK (deprecated)
- GET https://login.live.com/oauth20_authorize.srf/... (deprecated)

We could find out that there are different apps at different location.

My question are :

1. Is possible to migrate app from AAD or MS account to Graph? 
    and using the existed delta token and file ids?
    or we have to build a whole new Graph APP?

2. How long would the Live SDK stop working?  
    According to this,  it was deprecated for a while
    https://developer.microsoft.com/en-us/office/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation/

Thank you.

**Comment by joewutaiwan** [comment]
To be more clarified my question,

We have updated onedrive api from live SDK to onedrive V1, but this app is still under Live SDK application category.

1. What time will this app be deprecated? for now the live SDK api still work (apis.live.net/v5.0)

2. Is it possible to migrate this app to Graph and keeps in the same app-id?

Thank you for help!

**Comment by JeremyKelley** [comment]
Hi @joewutaiwan it looks like you asked this question right before we actually turned off the Live APIs last week.  As of now all non-profile related Live APIs should be turned off.  We'll be turning the profile APIs off shortly as well but for now they're on.

There unfortunately isn't a path forward that keeps the App ID the same, generally you need to register a new application in AAD for Graph if you're coming from the Live API side.

**Comment by joewutaiwan** [comment]
Hi @JeremyKelley 

Thank you for  reply, but I need one more confirm:
Now we have app is still run the **MS account** flow, would it be affected or closed , too?

3.MS account (Live SDK)
- APP registered in Microsoft App Registration Portal -> The Live SDK (deprecated)
- GET https://login.live.com/oauth20_authorize.srf/... (deprecated)

Thanks!

**Comment by amagliul** [comment]
Hi @joewutaiwan ,
I spoke to the Microsoft team about this last week and here is the information I came away with:

- "Live SDK Applications", themselves, are not deprecated, but the Live Connect API, and the Live SDK, which uses the Live Connect API, are (see below)
- `api.live.net` (LiveConnect) endpoints are disabled or scheduled to be disabled shortly.
- `api.onedrive.com`  (OneDrive API) endpoints are not scheduled for deprecation.
- `graph.microsoft.com` (Microsoft Graph) endpoints are not scheduled for deprecation, and are the preferred choice for integrations.
- `login.live.com/oauth20..` (Microsoft Accounts) endpoints are not scheduled for deprecation and are still valid for the OAuth flow for "Live SDK Applications"

We realized, as you did, that the Graph API requires a "Converged Application" vs a "Live SDK Application". Our app  was created before the new "Converged Application" type was available, so we are currently locked in as a "Live SDK Application". We are using the the Microsoft Accounts endpoints for OAuth and the OneDrive API endpoints for OneDrive operations. According to the Microsoft Team this configuration is safe to continue using and not scheduled for deprecation.

Microsoft recommends using Graph, and we would like to make the switch, but we are still trying to figure out how to do this successfully without creating a huge disruption for our users.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
