### ISSUE TITLE
metadata search in OneDrive and Sharepoint

### ISSUE THREAD

**Issue by afizs** [OneDrive/onedrive-api-docs#972]
#### Category
- [x ] Question
- [ ] Documentation issue
- [ ] Bug

Hello Team, 

I am trying to perform metadata search in MS OneDrive, Outlook and SharePoint. I am able to do metadata search in outlook using filters. However I am not very sure how to perform metadata search in OneDrive and Sharepoint. Basically I want to get the search results matching only metadata field not content.  

Please guide me how I can do this. 

Thank you.

**Comment by JeremyKelley** [comment]
Hi @afizs generally filters and other OData query parameters are dependent on what field you're attempting to use.  Which fields in particular are you looking to filter by?

**Comment by afizs** [comment]
I am attempting to filter using filename, creation/modification date, ownername. In short I want to use filter to search in file metadata and don't want to perform search in the content of the file. Thanks

**Comment by chackman** [comment]
Can you please clarify which API you wish to filter on?   For example are you filtering on drive items (like me/drive/root/children?filter=...), a search query (drive/search) or something else?

**Comment by afizs** [comment]
@chackman I am trying to filter on https://graph.microsoft.com/v1.0/me/drive/root/children API call. I want to filter drive items based on the metadata(filename, creation/modification date, ownername).

**Comment by chackman** [comment]
Only some properties are filterable, you can see more information here as it pertains to OneDrive Personal, SharePoint, and OneDrive for Business here:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online

**Comment by afizs** [comment]
Yes, I know that only few properties can be used for filtering. My question was how to filter by other metadata fields. Is Onedrive team planning to support this in this future ??

**Comment by chackman** [comment]
Those fields are not currently supported; expanding filtering support is on our backlog.

If you have more feature requests / enhancements / suggestions I would also recommend going to the OneDrive Developer Platform UserVoice at https://onedrive.uservoice.com/.

**Comment by afizs** [comment]
I have added this as a new idea. https://onedrive.uservoice.com/forums/913708-onedrive-developer-platform/suggestions/37529443-overview
