### ISSUE TITLE
BUG: select query parameter no longer works

### ISSUE THREAD

**Issue by billziss-gh** [OneDrive/onedrive-api-docs#973]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

The URI `https://graph.microsoft.com/v1.0/me/drive?select=quota` should return a `quota` element (as per the documentation in https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/optional-query-parameters?view=odsp-graph-online).

#### Observed Behavior

The URI `https://graph.microsoft.com/v1.0/me/drive?select=quota` no longer returns a `quota` element. This appears to be a regression as this used to work a couple of months ago.

#### Steps to Reproduce

- Open Graph Explorer at https://developer.microsoft.com/en-us/graph/graph-explorer and sign in with a Personal OneDrive account.

- Issue a `GET https://graph.microsoft.com/v1.0/me/drive`. The `quota` element is returned:
    ```
    {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives/$entity",
        "id": "38f255bb65bdd594",
        "driveType": "personal",
        "owner": {
            "user": {
                "displayName": "",
                "id": "38f255bb65bdd594"
            }
        },
        "quota": {
            "deleted": 0,
            "remaining": 5368132065,
            "state": "normal",
            "total": 5368709120,
            "used": 577055
        }
    }
    ```

- Issue a `GET https://graph.microsoft.com/v1.0/me/drive?select=quota`. Observe that the `quota` element is missing:
    ```
    {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives/$entity"
    }
    ```

**Comment by ificator** [comment]
I believe this was resolved quite some time ago.
