### ISSUE TITLE
[ODB] fail to Get Item from a existed file name path

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#977]
#### Category
- [x] Question
- [x] Documentation issue
- [ ] Bug

Hi all,

After I requested a Get a DriveItem resource API by path, got this response:
`GET /me/drive/root:/{item-path}`
```
http_code :404
body :{"error":{"code":"itemNotFound",
"message":"The specified item name is incompatible with a similar name on an existing item."}}
request-id: 76d6b59e-70ed-7000-a6fb-ec6f90940240

```

It is very strange, because this item is existed and I failed to create folder with the same name:
`POST /me/drive/items/{parent-item-id}/children`
```
http_code :409
{"error":{"code":"nameAlreadyExists","message":"The specified item name already exists."}}
```

Is it an invalid char issue or an API issue?
How can I understand and handle this response?

Thank you.

**Comment by JeremyKelley** [comment]
Hi @joewutaiwan, we can take a look at what's going on but we need both the request-id and a date/time to look in the logs for.  If you can get a current repro with an ID / time pair that would help us out.  Thanks!

**Comment by ificator** [comment]
We'd need the file names to confirm, but this is most likely a quirk of how SharePoint persists file names. Even though some strings are technically different, and .NET detects them as such, they actually conflict when they are persisted (for example, %CA%AE.txt and %CF%B5.txt).

To avoid confusion we detect when you try to fetch an item with one name but actually get back one with a different name, and instead return a `404` like you observed. Arguably the message for the `409` should be a little more descriptive for the create case though.

**Comment by joewutaiwan** [comment]
Thank you for feedback, here is more details.

- file name : "VT133_S4_Unterdorfstr. 25 fini MS Ok✔"

```
Date: Tue, 15 Jan 2019 06:37:17 GMT
request-id: 7526b69e-8055-7000-a42b-4c0b4462d73c
```

**Comment by song09585** [comment]
Hi @ificator , I found the  issue can be reproduced by the following steps for both RESTful API  and  Onedrive web UI :
a. create a folder named "1"
b. create a folder named "1✅" and it will return "nameAlreadyExists" error.

**Comment by joewutaiwan** [comment]
Hi, @ificator 

Yes, we have two files:
VT133_S4_Unterdorfstr. 25 fini MS Ok✔
VT133_S4_Unterdorfstr. 25 fini MS Ok✔✅

**Comment by ificator** [comment]
Thanks for the repro - I'll see if there's anything we can do.
