### ISSUE TITLE
[ODB] fail to get drive in Onedrive API but works at Graph

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#978]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

Hi all,

it is a special case that I could get response in GRAPH but failed in ONEDRIVE API

`GET https://graph.microsoft.com/v1.0/me/drive`
```
request-id →e16ec591-de6d-42bb-bd73-54cd72534437
"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives/$entity",
    "createdDateTime": "2014-05-26T02:03:06Z",
    "description": "",
    "id": "b!cpHWDxpGOUCTBZUqx5XxxxxxUozF-Hxxxxxxx",
    "lastModifiedDateTime": "2014-10-30T22:15:01Z",
    "name": "OneDrive",
    "webUrl": "https://xxxxx-my.sharepoint.com/personal/xxxxxx/Documents",
    "driveType": "business",
    "createdBy": {
        "user": {
            "displayName": "System Account"
        }
    },
    "lastModifiedBy": {
        "user": {
            "displayName": "System Account"
        }
    },
    "quota": {
        "deleted": 0,
        "remaining": 0,
        "total": 0,
        "used": 0
    }
```
`GET https://xxxxx-my.sharepoint.com/_api/v2.0/drives/me`
```
request-id →3fdbb59e-502c-7000-e02d-36de2aca5d1c
400
{
    "error": {
        "code": "invalidRequest",
        "message": "The provided drive id appears to be malformed, or does 
         not represent a valid drive."
    }
}
```

Could I fix it in adjusting some settings?
Or it is a limitation at some kinds of license account?

Thank you.

**Comment by ificator** [comment]
When Graph makes the request, it does so directly against the user's my site and requests the default drive. Theoretrically that should be equivalent to what you're trying to do with `drives/me` and so it's hard to say why it wouldn't be working.

Does the following work?
```
GET https://xxxxx-my.sharepoint.com/_api/v2.0/drive
```

**Comment by joewutaiwan** [comment]
Hi @ificator 

This account is one of my client's, but now it was deleted.
I would feedback as the response comes back.
