### ISSUE TITLE
File sharing status is still sharing even if public link on file is expired.

### ISSUE THREAD

**Issue by puneettrehan** [OneDrive/onedrive-api-docs#979]
We are facing issue where if file is shared using "Anyone with this link can edit" option with expiration date on that file. Even if Public link on file is expired file sharing is still listed as "Shared". Also after link is expired this file does not show up in change in delta API.

Steps to Reproduce
1. Create file "file1.txt" in root folder in one-drive.
2. Share file and select "Anyone with this link can edit" option to specific people.
3. Set expiration day of 1 day.
4. Share the file.
5. After 1 day login to one-drive and check this file. It shows sharing as "Shared"
6. Copy the access link and tries to access in browser. It shows link is expired.
7. Also tries to fetch changes using delta link but this file will not show up.

Expected changes
1. After Public Link is expired this file should show up in delta change as meta-data of file is updated.
2. After link is expired the UI should show that file is Private NOT shared.

@chackman

**Comment by chackman** [comment]
Thanks for your feedback, we'll investigate.

**Comment by chackman** [comment]
I followed up with one of our partner teams about this feedback.

Unfortunately, the current behavior is expected if the user was granted permission behind the scenes (for example, user redeemed the link or they were automatically granted permissions).
Furthermore, permissions granted in this way are not currently cleaned up after link expiration.
