### ISSUE TITLE
How can I get 'Keep me login' value?

### ISSUE THREAD

**Issue by benjaminliugang** [OneDrive/onedrive-api-docs#98]
When I use JavaScript reference WL.login, then it will pop up a login dialog, If I checked the keep me login checkbox, how can I get the value in WL.login callback function?

**Comment by jscaria** [comment]
@benjaminliugang - what's the scenario you're trying to accomplish?

**Comment by benjaminliugang** [comment]
@jscaria, we have integrate oneDrive in our project. Currently, if we logout our project, the oneDrive still keep with connect status. We do not need to login oneDrive when we login our project again.
Now, we need to logout oneDrive when we logout our project if the user didn't set keep me login as true. So we need to get the keep me login value when we login oneDrive.

**Comment by jscaria** [comment]
@benjaminliugang - currently there's no supported way to get the value of the checkbox.   The "Keep me signed in" checkbox is there to keep the user signed in until he or she explicitly logs out, which includes calls to the logout endpoint (see #58) made by your app.

**Comment by benjaminliugang** [comment]
@jscaria, thanks for your help, I will try other ways to resolve my case.
