### ISSUE TITLE
`@microsoft.graph.conflictBehavior` in driveitem copy

### ISSUE THREAD

**Issue by indigane** [OneDrive/onedrive-api-docs#981]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

Copying a driveitem allows for defining `@microsoft.graph.conflictBehavior` to handle conflicts, as per design according to issue #759 

This should also be documented.

#### Observed Behavior

Conflicts cause `409 Conflict` response despite `@microsoft.graph.conflictBehavior`.

```
{
  "error": {
    "code": "nameAlreadyExists",
    "message": "The specified item name already exists.",
    "innerError": {
      "request-id": "{requestId}",
      "date": "{date}"
    }
  }
}
```

#### Steps to Reproduce

```
POST https://graph.microsoft.com/v1.0/users/{username}/drive/items/{itemId}/copy

{
  "parentReference": {
    "driveId": "{driveId}",
    "id": "{parentItemId}"
  },
  "name": "foo",
  "@microsoft.graph.conflictBehavior": "rename"
}
```
^ Making this request twice will cause `409 Conflict` `nameAlreadyExists` on the second try.

**Comment by Herz3h** [comment]
I'm trying this aswell using the Graph API and it always returns nameAlreadyExists regardless of the behaviorConflict specified

```
{
  "parentReference": {
    "driveId": "{driveId}",
    "id": "{parentItemId}"
  },
  "name": "test",
  "@microsoft.graph.conflictBehavior": "rename"
}
```

How to work around this ??

**Comment by zsybupt** [comment]
any updates?

**Comment by kostenickj** [comment]
come on guys?

**Comment by marcogiannetta** [comment]
Adding @microsoft.graph.conflictBehavior=rename to query string parameters did work for me

**Comment by jl0zano** [comment]
as @marcogiannetta said, you have to add to the query params.

Example:
https://graph.microsoft.com/v1.0/me/drive/items/{your-file-id}/copy?@microsoft.graph.conflictBehavior=rename

If you're using the C# Graph SDK you have to send a query option on the request.


```
List<QueryOption> options = new List<QueryOption>
{
    new QueryOption("@microsoft.graph.conflictBehavior", "rename")
};
```


Source: https://stackoverflow.com/a/44991860/14457092

**Comment by Herz3h** [comment]
Well docs should be updated then

**Comment by Cnly** [comment]
It looks like the workaround above only works for OneDrive for Business... OneDrive Personal still seems to ignore it.

**Comment by Herz3h** [comment]
Adding @microsoft.graph.conflictBehavior to query string doesn't work either:

https://graph.microsoft.com/v1.0/me/drive/items/{your-file-id}/copy?@microsoft.graph.conflictBehavior=replae

**Comment by czernas** [comment]
Does not work with the personal accounts. 😒

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
