### ISSUE TITLE
Availability in OneDrive

### ISSUE THREAD

**Issue by nguyenquyhy** [OneDrive/onedrive-api-docs#983]
Is this API available for OneDrive or only SharePoint?

I have been trying to use POST https://api.onedrive.com/v1.0/drives/{driveId}/items/{itemId}/preview but keep getting status 400  {"error":{"code":"invalidRequest","message":"API not found"}}.
A similar call to the SharePoint API for OneDrive for Business account works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abaca550-f44d-455b-ef18-a284dd222dbc
* Version Independent ID: de0dfe46-b10b-5b53-59a1-37967fe2b1ab
* Content: [Get short-lived embeddable link for preview purposes - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_preview.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_preview.md)
* Product: **onedrive**
* GitHub Login: @kevinlam
* Microsoft Alias: **kevinlam**

**Comment by JeremyKelley** [comment]
The /preview endpoint is currently only available on SharePoint and OneDrive for Business but not consumer accounts.

It looks like the OneDrive API docs are not current while the Microsoft Graph docs specify this explicitly.  We'll make sure the docs get updated.

**Comment by afedosenko** [comment]
Any news? I spent a lot of time before I realized that the "preview" api works for SharePoint or OneDrive for Business only. But not for personal accounts.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
