### ISSUE TITLE
Sharepoint doesnt show files on others sites rather than root

### ISSUE THREAD

**Issue by ldcm3** [OneDrive/onedrive-api-docs#985]
Hey @KevinTCoughlin, I have an issue that I guess it's related to this one.

When using the root company folder as endpointHint hint for Sharepoint (i.e https://test.sharepoint.com/Shared%20Documents/) users will not be able to see files on other /sites/ even when they have access and can see the sites on the left view (see picture).

![screen shot 2019-01-22 at 4 03 08 pm](https://user-images.githubusercontent.com/12711137/51548292-f99c3080-1e5f-11e9-8475-4113dee6110d.png)

This issue doesn't happen when setting endpointHint to any other site (even those where the user is not a member).

I am opening the picker similar to:

``  OneDrive.open({
    clientId: clientID,
    action: 'query',
    advanced: {
      accessToken: accessToken,
    endpointHint: "https://test.sharepoint.com/Shared%20Documents/",
     },
    multiSelect: true,
    success: onSuccess,
    error: onError,
    cancel: onCancel,  });
}

_Originally posted by @ldcm3 in https://github.com/OneDrive/onedrive-api-docs/issue_comments#issuecomment-456458137_

**Comment by ificator** [comment]
What scopes are present in the `accessToken` that you're providing? For data in other sites you'll need an `All` variant (e.g. `Files.Read.All`)

**Comment by ldcm3** [comment]
@ificator : "scope": "Files.Read.All profile openid email",

**Comment by ificator** [comment]
That looks ok - I'll have to defer to @KevinTCoughlin for debugging further :)

**Comment by ldcm3** [comment]
Thanks for the triage @ificator. 
Looking forward to hear back from @KevinTCoughlin

**Comment by ldcm3** [comment]
Any news here?

**Comment by KevinTCoughlin** [comment]
> Any news here?

The `endpointHint` of `https://test.sharepoint.com/Shared%20Documents/` seems correct given my testing against our own tenants and the Picker SDK documentation at https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#advanced-options.

Can you share any non-security sensitive attributes of the response to help us debug?

cc: @ThomasMichon for any insight re: the above.

**Comment by HerrickSpencer** [comment]
quick check: Since Files.Read.All is not a default permission on registered apps, was this selected as a scope on your [Azure Portal app registration settings](portal.azure.com) as well?

**Comment by ldcm3** [comment]
Hi guys, thank you for the reply.

> was this selected as a scope on your Azure Portal app registration settings as well?

Yes. I also tried with Sites.Read.All and did not work

![screen shot 2019-03-05 at 8 56 48 am](https://user-images.githubusercontent.com/12711137/53794295-99e97880-3f27-11e9-8e75-8afa565138ab.png)

> Can you share any non-security sensitive attributes of the response to help us debug?

I hope this can help you. This is was tested using our dummy implementation on: https://github.com/jokr/taaskly/blob/msft/static/js/msftpicker.js

![screen shot 2019-03-05 at 9 26 27 am](https://user-images.githubusercontent.com/12711137/53795248-77f0f580-3f29-11e9-824d-0abd32ad930d.png)
![screen shot 2019-03-05 at 9 26 18 am](https://user-images.githubusercontent.com/12711137/53795303-9820b480-3f29-11e9-82f9-8176137fe107.png)
![screen shot 2019-03-05 at 9 26 07 am](https://user-images.githubusercontent.com/12711137/53795358-b8e90a00-3f29-11e9-9741-50e25947d5d5.png)

**Comment by KevinTCoughlin** [comment]
@ldcm3, I tested setting the `endpointHint` to a valid "Shared Documents" URL against a few SharePoint test tenants and the Picker worked as expected. I was able to view and select files in the "Shared Documents" document library as well as other site document libraries I had access to.

Here was my configuration:

```js
var options = {
	clientId: '00000000-0000-0000-0000-000000000000',
	action: 'query',
	multiSelect: false,
	advanced: {
		endpointHint: 'https://<tenant>.sharepoint.com/Shared%20Documents/'
	},
	success: (files) => console.log('success', files),
	cancel: (err) => console.log('cancel', err),
	error: (err) => console.log('err', err)
};

OneDrive.open(options);
```

I could view / select files in the shared documents list as well as navigate to other site lists.

Have you tried omitting the `accessToken` parameter? One idea is that the `accessToken` is invalid for the site(s) you are trying to access.

Have you ensured that the decoded `accessToken` maps to the correct tenant resource via http://jwt.ms/?

**Comment by ldcm3** [comment]
Hey @KevinTCoughlin, I just tried again with the exactly same config you used (omitting accessToken) and same thing happens..

It doesn't seems to be a problem with permissions, since if I click on the "Go to the list" button it takes me to the site view (even I cannot pick files from there):

<img width="1050" alt="screen shot 2019-03-06 at 1 03 36 am" src="https://user-images.githubusercontent.com/12711137/53848306-b7602600-3fab-11e9-8cac-bbe9f6d494cc.png">

Please let me know how I can give you more info, thanks again!

**Comment by ldcm3** [comment]
As I said before, it is weird since the issue doesn't happen when setting endpointHint to any other site rather than the "default"   'https://<tenant>.sharepoint.com/Shared%20Documents/'

**Comment by KevinTCoughlin** [comment]
> As I said before, it is weird since the issue doesn't happen when setting endpointHint to any other site rather than the "default" 'https://tenant.sharepoint.com/Shared%20Documents/'

I set it to the "default" in my configuration and it worked i.e. https://<tenant>.sharepoint.com/Shared%20Documents/.

Hence my confusion in trying to repro.

**Comment by ldcm3** [comment]
We are definitely sending requests and getting back a 404 when accessing other sites.
So we can't debug the error code on our side. 
Can I get you a fiddler trace or a way to get a correlation id so you can trace the request on your side?

**Comment by KevinTCoughlin** [comment]
> We are definitely sending requests and getting back a 404 when accessing other sites.
> So we can't debug the error code on our side.
> Can I get you a fiddler trace or a way to get a correlation id so you can trace the request on your side?

Fiddler traces would be great. Please send them to my work e-mail (I'm on the same thread you are). The traces should give us the correlation ID and additional information to debug.

I see both a `403` and a `404 in the screenshot attached in https://github.com/OneDrive/onedrive-api-docs/issues/985#issuecomment-469608533.

**Comment by ldcm3** [comment]
So this is what we get on that 403:

{"error":{"code":"-2130575251, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The security validation for this page is invalid and might be corrupted. Please use your web browser's Back button to try your operation again."}}}

From a quick search it looks like we are missing some RequestDigest field.

Not sure how to solve that since we the frame relies on cookie authentication as you said.

**Comment by KevinTCoughlin** [comment]
This should now be resolved as the fix was released to production earlier this week. The issue was in how the hosted Picker page resolved cross-site SharePoint URLs.

Please create a new issue if anyone is still blocked with new debug information. I'm going to have the bot soft-close meanwhile.

cc: @aditima @ThomasMichon
