### ISSUE TITLE
what license is onedrive.js released under

### ISSUE THREAD

**Issue by nhopp** [OneDrive/onedrive-api-docs#986]
There does not appear to be a specific license that OneDrive.js is released under, can you please clarify the licensing.

**Comment by KevinTCoughlin** [comment]
> 
> 
> There does not appear to be a specific license that OneDrive.js is released under, can you please clarify the licensing.

This is a great question and one we should absolutely surface better as part of our documentation. I will talk with legal and provide resolution here shortly.

**Comment by nhopp** [comment]
@KevinTCoughlin any update here?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin any update here?

Not yet, but hopefully soon. Still in-progress.

**Comment by KevinTCoughlin** [comment]
@nhopp, I have a call tomorrow (Wednesday 3/6) and hope to have resolution shortly thereafter.

**Comment by KevinTCoughlin** [comment]
I have guidance from legal, but the changes require some work on my part and should roll-out within the next week or two. I need to verify a few things then I should be able to share status here prior to changes rolling out.

**Comment by rajcisco** [comment]
> I have guidance from legal, but the changes require some work on my part and should roll-out within the next week or two. I need to verify a few things then I should be able to share status here prior to changes rolling out.
> 
> cc: @aditima

Hi Kevin, what is the guidance that you got from your legal ?  Can you give us some summary until you officially publish the info. We would also like to  discuss this with our legal, hence looking to find out guidance.

**Comment by rajcisco** [comment]
> > I have guidance from legal, but the changes require some work on my part and should roll-out within the next week or two. I need to verify a few things then I should be able to share status here prior to changes rolling out.
> > cc: @aditima
> 
> Hi Kevin, what is the guidance that you got from your legal ? Can you give us some summary until you officially publish the info. We would also like to discuss this with our legal, hence looking to find out guidance.

Also, let us know based on your legal guidance whether we (Cisco) will have permission to take existing OneDrive.Js and modify it to support O365 Germany for our customers ?

**Comment by KevinTCoughlin** [comment]
> Also, let us know based on your legal guidance whether we (Cisco) will have permission to take existing OneDrive.Js and modify it to support O365 Germany for our customers ?

@rajcisco, I reached out to legal to support your scenario. We need to check a few more boxes and update the scripts to be fully compliant. Once done I anticipate your scenario to be supported.

I'm hoping for EOW to have the scripts deployed. But it depends on some paperwork.

**Comment by KevinTCoughlin** [comment]
@rajcisco what version(s) do you anticipate using? Just `7.2`?

**Comment by mbfgit** [comment]
@KevinTCoughlin @rajcisco We'll be using 7.2

**Comment by KevinTCoughlin** [comment]
Note that the changes are **pending deployment**, but we've relicensed the existing and future releases of the OneDrive File Picker under [MIT license](https://opensource.org/licenses/MIT).

The updated scripts with the license headers will roll-out this week. I will update this thread once I see them live in the production and will update the documentation accordingly. Stay tuned.

**Comment by KevinTCoughlin** [comment]
Updated scripts for the existing File Picker releases have been released to production. The scripts are now licensed under MIT license. Thanks for your patience.

**7.2**
- http://js.live.net/v7.2/OneDrive.debug.js
- http://js.live.net/v7.2/OneDrive.js

**7.1**
- http://js.live.net/v7.1/OneDrive.debug.js
- http://js.live.net/v7.1/OneDrive.js

**7.0**
- http://js.live.net/v7.0/OneDrive.debug.js
- http://js.live.net/v7.0/OneDrive.js

**6.0**
- http://js.live.net/v6.0/OneDrive.debug.js
- http://js.live.net/v6.0/OneDrive.js

**5.0**
- http://js.live.net/v5.0/OneDrive.debug.js
- http://js.live.net/v5.0/OneDrive.js

Future releases will continue to be released under MIT. I will update the documentation mentioning this and close out the issue.
