### ISSUE TITLE
Is there any way we can access the shared with me files in one drive using application permission in graph API??

### ISSUE THREAD

**Issue by kunal121** [OneDrive/onedrive-api-docs#987]
#### Category
- [ ] Question

> it is working fine with the delegated permission but I want it using application permission.
 @ https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/drive_sharedwithme?view=odsp-graph-online.
 I tried this approach
```
https://graph.microsoft.com/v1.0/users/{User-Principal-Name}/drive/sharedWithMe
```
But getting a response with the values field empty.

Any Help would be highly appreciated :)

#### Expected or Desired Behavior
> As if I make a request with delegated permission it works perfectly fine and got some values in the response but same I want with application permission.

Request
```
https://graph.microsoft.com/v1.0/me/drive/sharedWithMe
```

#### Observed Behavior

>But getting a response with the values field empty.If using the application permissions
Response
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": []
}
```
#### Steps to Reproduce

> Please make this rquest in postman with application permissions
```
https://graph.microsoft.com/v1.0/users/{User-Principal-Name}/drive/sharedWithMe
```

Thank you.

**Comment by chackman** [comment]
Thanks for your feedback, this is a feature ask that is being investigated by a partner team.

**Comment by ssapa** [comment]
@chackman Is this issue still persists. I am facing same issue when i try to fetch shared with us files for a shared library using application account.

**Comment by ssapa** [comment]
@chackman Any update on this?

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
