### ISSUE TITLE
Cannot update location of DriveItem (jpeg)

### ISSUE THREAD

**Issue by tipa** [OneDrive/onedrive-api-docs#988]
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
When updating the location of a DriveItem (in my case a jpeg file), it should work. The new coordinate should be saved to the item and when viewing the picture info in the OneDrive browser app, it should show the correct location on the map.
If this is not intended to work (the documentation states this attribute is "read-only"), I would expect an error when attempting to update the location.

#### Observed Behavior
I update the location with the Microsoft.Graph Nuget library v1.12.0. 
`PATCH /v1.0/drive/root:/Bilder/Camera%20Roll/IMG_20190123_173619.jpg`

Request body: 
![image](https://user-images.githubusercontent.com/2863198/51795351-f3041500-21e1-11e9-8f3d-57cfdb913c89.png)

However, in the returned DriveItem, the old location is still present and the new location is not saved to the picture. That makes geotagging images via the API impossible.

![image](https://user-images.githubusercontent.com/2863198/51795362-2e064880-21e2-11e9-941c-8a5da2b3a134.png)

#### C#-Code:
```
await GraphClient.Drive.Root.ItemWithPath(pathToJpeg).Request().UpdateAsync(new DriveItem()
{
    Location = new GeoCoordinates() { Longitude = 20.0, Latitude = 20.0, Altitude = 0.0 }
});
```

**Comment by ificator** [comment]
Marking this as a bug as we should either fail the request if the update is not supported, or actually update the data if it is supported. Returning `200 OK` without actually changing the state isn't nice.

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
