### ISSUE TITLE
[ODB] onenote file is not included in delta response

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#991]
#### Category
- [X] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

> Get /root/delta

This request did have onenote files in response.

#### Observed Behavior

No onenote files in response.

--

Now I am tracking for size mismatch with onenote files issue, they might be related.

I also test on GRAPH, it does not return, neither.

Thank you.

**Comment by chackman** [comment]
Can you please provide the following response headers: 
 - Date (in UTC, please)
 - request-id
 - SPRequestGuid (for requests made to OneDrive for Business)
Also are you passing in any delta tokens?  A sample URL would be helpful.

**Comment by joewutaiwan** [comment]
Hi @chackman,

Here you are, thanks

```
date →Fri, 01 Feb 2019 09:59:48 GMT
request-id →ceaabb9e-d006-7000-b143-986e2fe108e0
sprequestguid →ceaabb9e-d006-7000-b143-986e2fe108e0
```

I requested:
```
https://mytenant-my.sharepoint.com/_api/v2.0/drives/drive_id/root/delta
```

**Comment by chackman** [comment]
Thanks; a couple things:
1. How many items do you get back from the API?
2. Here's an example result for a OneNote that I could get from various drives that I have tested:
        
        {
            "name": "My Notebook",
            […]
            "package": {
                "type": "oneNote"
            }
        }
        

I'm assuming that you are missing an item that looks like the above (where the package is oneNote).
If you are expecting something different returned by the API, please clarify and provide an example of what you were expecting to see.
For example, are you getting the package, but are missing something else from the response (like a ".one" file, table of contents, etc.)?

**Comment by joewutaiwan** [comment]
Hi @chackman,

Thanks for reply:

1. I get all item in my Onedrive except the onenote items.
2. The response was what I got before, but now which missing onenote items.
3. There are many files in my onedrive like .jpeg or onenote files.
I could get all files (.jpeg or onenote files) in DELTA response before, but now it returns all files except onenote files.
I could still see them all in my drive.

![image](https://user-images.githubusercontent.com/12619781/52615297-ba498880-2ecf-11e9-9ad7-95b105180e99.png)

Only folder 123 and hello.jpeg returned.

**Comment by chackman** [comment]
Thanks for the information, this will require further investigation.

**Comment by chackman** [comment]
Could you please confirm whether the drive with `drive_id` has the same drive ID as your OneDrive?

One way to find out would be to make this API call directly in your browser:
  `https://mytenant-my.sharepoint.com/personal/user_mytenant_com/_api/v2.0/drive`
Replacing `https://mytenant-my.sharepoint.com/personal/user_mytenant_com/` with your OneDrive URL.  Compare the `id` property returned by this API call with the `drive_id` used in the first API call.

If the ID's are the same, then please provide the following information to help further investigation:

For the call to
  `https://mytenant-my.sharepoint.com/personal/user_mytenant_com/_api/v2.0/drive`
  Date (in UTC, please)
  request-id
  SPRequestGuid (for requests made to OneDrive for Business)

For a new call to
  `https://mytenant-my.sharepoint.com/_api/v2.0/drives/drive_id/root/delta`
  Date (in UTC, please)
  request-id
  SPRequestGuid (for requests made to OneDrive for Business)
