### ISSUE TITLE
@odata.nextLink 

### ISSUE THREAD

**Issue by applibs** [OneDrive/onedrive-api-docs#995]
#### Category
- [x ] Bug

#### Expected or Desired Behavior

I expect that @odata.nextLink will return next items, not duplicated previous.

#### Steps to Reproduce

I send request to api like this:
1.
https://api.onedrive.com/v1.0/drives/MYDRIVEID/root/children?top=1
2.
It will return 1 item - OK
3.
then I got @odata.nextLink which I use and it will return all items included first one from previous request. - WRONG, it must return next items.

Thank you.

**Comment by ificator** [comment]
Hmm, I see it working as expected for my drive. Can you provide the value of the `@odata.nextLink` we returned? Feel free to replace your driveId with `MYDRIVEID`.

**Comment by applibs** [comment]
https://api.onedrive.com/v1.0/drives('MYDRIVEID')/items('root')/children?$top=1&$skiptoken=Mg

**Comment by ificator** [comment]
At a glance that URL looks like what I would expect for the second page of size 1. If you set your initial `top` to something larger (e.g. 5), are all of the items returned on the second page the same as the first, or just some?

**Comment by ificator** [comment]
Closing stale issues.
