### ISSUE TITLE
How to update a Silverlight app now?

### ISSUE THREAD

**Issue by Adrianotiger** [OneDrive/onedrive-api-docs#996]
Once again, Microsoft dismiss a service that is still used by the users!
I wrote an app (3-4 years of work) that implement this API-service in a WP8 app. Once Windows Mobile was announced I did decided to not porting the app, because the work was too big. Now, people are still using my Silverlight-app on Windows Mobile devices but they can't access the OneDrive folder anymore for their backups.
Microsoft doesn't allow me anymore to upgrade a Silverlight app in the store.

What can I do now? Should I rewrite the app as UWP, for Windows Mobile now? Or is there a better solution?

You see how good a company is by the service. Microsoft has a miserable service, and their products are dead before they are really on the market. Even on simple APIs, there is no quality! There are some Nokia services (like OVI-maps) that are still working on the Symbian phones, and it is 2019! Why can't you just leave something like an API service until people doesn't use your product anymore?

Now, my app will get a bad reputation only because I trusted to Microsoft when I implemented your API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8535c93-aaae-ebfe-cfcb-5ebd37dd7d00
* Version Independent ID: 33863b36-3494-d437-b1fc-3e1bff634e74
* Content: [Migrating from Live SDK to Microsoft Graph - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk?view=odsp-graph-online)
* Content Source: [docs/rest-api/concepts/migrating-from-live-sdk.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/concepts/migrating-from-live-sdk.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
