### ISSUE TITLE
I am facing an issue while uploading larger size file(<4MB or 100MB) to one drive using File Picker for JavaScript

### ISSUE THREAD

**Issue by suryanshrathorecloudanalogycom** [OneDrive/onedrive-api-docs#997]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01cfabca-01d3-decc-8194-1b21ed536a42
* Version Independent ID: b98f73e7-5aa8-92a0-0ca4-a598534c6425
* Content: [File Picker SDK for JavaScript - OneDrive - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/index?view=odsp-graph-online)
* Content Source: [docs/controls/file-pickers/js-v72/index.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/controls/file-pickers/js-v72/index.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by KevinTCoughlin** [comment]
@suryanshrathorecloudanalogycom, what is the server response you receive when attempting to upload an especially large file?

Additional information here would be helpful as well as the explicit size of files you are attempting to upload.

**Comment by suryanshrathorecloudanalogycom** [comment]
[OneDriveSDK] error occured - code: '1', message: 'the user has selected a file larger than 100 MB' 
onedriveIntegration:50 ERROR :: {"errorCode":1,"message":"the user has selected a file larger than 100 MB"}

**using  File Picker SDK for JavaScript - OneDrive - OneDrive dev center**

Below is the JAVAScript Code for Uploading FIle :
function launchSaveToOneDrive(){
            var odOptions = { clientId: "c46e929d-62db-4c13-b74c-2e54b372a74b",
                action: "save",
                sourceInputElementId: "fileUploadControl",
               // sourceUri: "",
               // fileName: "file.txt",
                openInNewWindow: true,
                advanced: {endpointHint: "api.onedrive.com"},
                success: function(files) {
                    /* success handler */
                    console.info('files :: ');
                    console.info({files});
                    },
                progress: function(p) {  console.info('progress :: '+p); },
                cancel: function() { },
                error: function(e) { /* error handler */  console.info('ERROR :: '+JSON.stringify(e));} };
            OneDrive.save(odOptions);
        }

**Comment by suryanshrathorecloudanalogycom** [comment]
> @suryanshrathorecloudanalogycom, what is the server response you receive when attempting to upload an especially large file?
> 
> Additional information here would be helpful as well as the explicit size of files you are attempting to upload.

[OneDriveSDK] error occured - code: '1', message: 'the user has selected a file larger than 100 MB'
onedriveIntegration:50 ERROR :: {"errorCode":1,"message":"the user has selected a file larger than 100 MB"}

**using File Picker SDK for JavaScript - OneDrive - OneDrive dev center**

Below is the JAVAScript Code for Uploading FIle :
function launchSaveToOneDrive(){
var odOptions = { clientId: "c46e929d-62db-4c13-b74c-2e54b372a74b",
action: "save",
sourceInputElementId: "fileUploadControl",
// sourceUri: "",
// fileName: "file.txt",
openInNewWindow: true,
advanced: {endpointHint: "api.onedrive.com"},
success: function(files) {
/* success handler _/ console.info('files :: '); console.info({files}); }, progress: function(p) { console.info('progress :: '+p); }, cancel: function() { }, error: function(e) { /_ error handler */ console.info('ERROR :: '+JSON.stringify(e));} };
OneDrive.save(odOptions);
}

**Comment by KevinTCoughlin** [comment]
Thanks for providing that @suryanshrathorecloudanalogycom. Looking at the source code of `v7.2` this limitation is hard-coded.

As a workaround, can you break-up the file upload so that it is not one unit of `100 MB`? Even with the client restriction relaxed, uploading a `100 MB` file is not ideal and prone to failure i.e. network connectivity loss.

We will need to see if we can relax this restriction in a future version. I current lack context for the restriction.

@ificator @chackman are you aware of API limitations regarding file size upload? Judging from the documentation, it looks like we generally advice uploading single files which are less than `4 MB`, see https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/upload?view=odsp-graph-online.

**Comment by KevinTCoughlin** [comment]
The Picker does not currently support upload sessions which would perhaps be the only reason to accomplish uploading a `100 MB` file.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online
