### ISSUE TITLE
OneDrive Rest: How to get know if subscribed item is deleted or moved?

### ISSUE THREAD

**Issue by vsolanki888** [OneDrive/onedrive-api-docs#998]
I am integrating onedrive with REST, Using webhooks subscription https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-webhooks?view=odsp-graph-online with the end points  https://api.onedrive.com/v1.0 (not using graph API) to know the changes of the content, It tell me by webhooks callbackurl that particular subscribed content has been changed, So i sync the change, All goes well.

But if any subscribed webhook content is deleted or moved then i am not getting any callback from the webhook callbackurl. Therefore i am unable to detect that i have to sync the new change.

Please help me out.

**Comment by chackman** [comment]
Thanks for your feedback.
Does a delta API call indicate that items were deleted or moved?

**Comment by vsolanki888** [comment]
thanks for reply, When i call delta API with the end point https://api.onedrive.com/v1.0/drives/{driveId}/root/delta
then i get invalidRequest with 400 http code bad request

**Comment by chackman** [comment]
When using the [direct endpoint](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences) certain actions (including delta) must be prefixed.

**Comment by vsolanki888** [comment]
Thanks @chackman  i try to resolve my problem with delta
